### ISSUE TITLE
Link Broken "chrome://wallet/" (This site can’t be reached)

### ISSUE THREAD

**Issue by victorelec14** [brave/brave-browser#5164] opened 2019-07-07 11:22 UTC
## Description 

"This site can’t be reached" in the new section "Crypto Wallets" on the Settings Page.

## Steps to Reproduce

   1.  Go to "Settings" Page
   2.  Go to "Crypto Wallets" Section
   3.  Error

## Actual result:

![image](https://user-images.githubusercontent.com/543450/60767545-e2719800-a0b9-11e9-9626-806ed29bdaca.png)

![image](https://user-images.githubusercontent.com/543450/60767550-ee5d5a00-a0b9-11e9-95bc-3cc085b036b9.png)

## Expected result:
Wallets page ?

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 0.69.39 Chromium: 75.0.3770.100 (Official Build) nightly (64-bit)

## Version/Channel Information:

Nightly Channel

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by eljuno** [comment] 2019-07-07 11:58
Duplicate of #5117?

**Comment by ryanml** [comment] 2019-07-07 20:42
This will be fixed here when the mapping is complete: https://github.com/brave/brave-core/pull/2833

**Comment by ryanml** [comment] 2019-07-07 20:42
Closing as a duplicate, thanks for the report @victorelec14

**Closed by ryanml** 2019-07-07 20:42 UTC
