### ISSUE TITLE
Copy-Paste of chrome browser?

### ISSUE THREAD

**Issue by santoshbmath** [brave/brave-browser#14556] opened 2021-03-08 05:47 UTC
## Description 
When we take our cursor on "View your browsing history" (Left bottom corner), then on right bottom corner it says "chrome://history".

## Steps to Reproduce
   1. Open new tab
   2. Hover/take your cursor over "View your browsing history"
   3. Right bottom corner, it says "chrome://history".

## Actual result:
No idea. I guess it should not say "chrome" here.

## Reproduces how often: 
Easily reproducible.

## Brave version (brave://version info)
Version 1.21.74 Chromium: 89.0.4389.72 (Official Build) (64-bit)

## Version/Channel Information:
No idea
![brave](https://user-images.githubusercontent.com/3702899/110279855-d2812880-7fff-11eb-8725-bdc3be962d9c.JPG)

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment] 2021-03-08 08:40
Thanks for the report, @santoshbmath 😄 I'm going to close this as a duplicate of https://github.com/brave/brave-browser/issues/2566 which has been a long standing issue. We definitely do want to fix this

**Closed by bsclifton** 2021-03-08 08:40 UTC
Labels: OS/Desktop
