### ISSUE TITLE
[Feature] Utilize Goanna instead of Blink

### ISSUE THREAD

**Issue by David-Beetle** [brave/brave-browser#2778] opened 2019-01-02 03:53 UTC
**Description**: Switch from [Blink](https://www.wikipedia.org/wiki/Blink_(browser_engine)) to [Goanna](https://www.wikipedia.org/wiki/Goanna_(software)).
**Why**? Because [Blink](https://www.wikipedia.org/wiki/Blink_(browser_engine)), is developed by the for-profit anti-privacy [Google](https://www.wikipedia.org/wiki/Google). [Goanna](https://www.wikipedia.org/wiki/Goanna_(software)) is developed by a [non-profit organization](https://www.wikipedia.org/wiki/Nonprofit_organization).
__________________
What to back this issue? Post a [bounty](https://www.bountysource.com/issues/68158109-feature-utilize-goanna-instead-of-blink) on it! We accept bounties via [BountySource](https://www.bountysource.com/).

**Comment by srirambv** [comment] 2019-01-02 05:40
cc: @BrendanEich @bbondy @davidtemkin

**Comment by bbondy** [comment] 2019-01-02 19:21
We like both multi-process and Rust and have no plans on switching to Gecko so going to say wontfix on Goanna.

**Closed by bbondy** 2019-01-02 19:21 UTC
Labels: needs-discussion, wontfix

**Comment by asddsaz** [comment] 2019-01-03 04:02
@bbondy Why don't you want to utilize Gecko?
Is there something wrong with Gecko?

**Comment by bbondy** [comment] 2019-01-03 05:21
Not more wrong than anything else.

This repo tracks the work for our Chromium based fork though.
If we ever did a Gecko based for it would be a separate project and separate repo.

I think we'd be worse off doing a Gecko fork though because we'd have divided focus, we'd be starting over, and we'd run into more web compat issues.  The opportunity cost would be greater even if you only considered the benefits and ignored the downfalls.

**Comment by asddsaz** [comment] 2019-01-04 21:20
@bbondy The question I've seen a lot with individuals is why didn't Brave start with Gecko or Goanna. It seems like you are stating that this is why you cannot/shouldn't now switch over.
Being a Brave developer, why utilize Blink over Gecko?

**Comment by bbondy** [comment] 2019-01-05 01:51
We actually did start with Gecko, it was based on Graphene and had an HTML instead of XUL / XBL front end.  The APIs were not developed enough though and would have taken us too long to build them out.  About 5 months into Brave being founded, we evaluated our options and switched off. Team size at the time was only 5 people.

<img width="843" alt="screen shot 2019-01-04 at 8 40 54 pm" src="https://user-images.githubusercontent.com/831718/50718770-131c3a80-1061-11e9-8c36-897596a034ac.png">

We searched for something we could port to which we could get a product out with. We found electron based on Chromium and forked it to make it more security aware and allow extensions support.  The fork was called muon.  Over time we found that building everything from scratch for the UI was hard to maintain at our scale.  Muon took 2 developers 6 weeks of full time work just to do a Chromium upgrade, it was not very maintainable, each major Chromium upgrade we'd introduce issues.  Adding support for each individual extension API was a lot of work so our extension selection was very limited and was easy to break as extensions upgraded.

So we adopted the Chromium UI and applied privacy, security, and other changes to it.  This new rewrite is architected a lot better than muon for our needs.  It allows us to have full extension support and it allows us to do major Chromium upgrades within a day with 0 regressions.

Another reason we're using Chromium is that we have better webcompat with it.  There's a higher risk with Gecko that people will stop caring about supporting Gecko now that I think the market share is ~10%. Which means people stop finding it worth it to test on non blink engines. We'd run into more web compat issues over time which would hurt our growth.   Mozilla is important and makes sure there's engine choice, but if they give that up at some point (Edge already did), then that's a high risk for our startup.  We would have neither the funding nor team size to support Gecko on our own.  We have to focus on our core goals which is being a user's agent with focus on privacy, speed, and reinventing how advertising is done.

Having worked for several years in each code base, personally I think the Chromium code base is more clean and more modern as well, although the Rust integration is nice, we're doing Rust too. As a developer working on Gecko, it gave me the feeling like my skills would not port to anywhere else in the future. No STL, but using XPCOM, XBL, XUL, etc.  Mozilla is filled with extremely smart people though so I wish them the best and have a lot of respect for everyone there.

Chromium is not immutable, so there's no reason we can't change it to our needs. Take for example reliable TCP built on top of unreliable IP.

Hope this helps, cheers.
