### ISSUE TITLE
Typing in search bar in Private tab does not give "Search with <search engine>" tag

### ISSUE THREAD

**Issue by Cyberdroid1** [brave/brave-browser#11947] opened 2020-10-01 11:52 UTC
## Description 
When opening a new private tab, i go to the search bar on top and type something, I dont get the normal "Search with (search engine)" tag. Instead, it is considered as a website. Doing the same with 2 words and pressing enter crashes the browser

## Steps to Reproduce

   1. Open a new private window
   2. Type 2 words in the search bar and observe the results.
   3. Press enter to see the crash.

## Actual result:

![image](https://user-images.githubusercontent.com/51435948/94804956-43953200-0409-11eb-8352-f2dbc0be9521.png)

## Expected result:
The browser should identify this as a search term and enable the search engine to be used. 
The crash should not happen.

## Reproduces how often: 
Easily produced when following above steps.

## Brave version (brave://version info)

Brave | 1.17.3 Chromium: 86.0.4240.55 (Official Build) nightly (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Windows 10 OS Version 2009 (Build 19042.541)

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the nightly channel?  YES

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? YES

## Miscellaneous Information:

Nothing as of now.

**Comment by PyICoder** [comment] 2020-10-13 21:09
I have the same problem, from what I experience, if you type, for example "Hello World", it will crash brave all the time because there is a "space", I think it is because, as you said, not using the search engine, but trying to use whatever that is inputted as an link to a website, which I suppose is not intended.

**Comment by Cyberdroid1** [comment] 2020-10-14 04:46
@PyICoder in which version did you face this issue? I would like to know.

**Comment by PyICoder** [comment] 2020-10-14 17:24
Version 1.15.72 Chromium: 86.0.4240.75 (Official Build) (64-bit), the latest one I think, from About Brave page.

**Comment by Cyberdroid1** [comment] 2020-10-15 03:34
Ok, so I think this issue is present in all Brave versions.

**Comment by Cyberdroid1** [comment] 2020-11-19 17:45
When will this issue be fixed?

**Comment by PyICoder** [comment] 2020-11-19 18:27
I do not know, but I hope soon, because I use private alot.

**Comment by ShankarBUS** [comment] 2020-12-09 17:55
Could anyone fix this soon?
It's too annoying and irritating!

**Comment by rebron** [comment] 2020-12-15 06:08
@Cyberdroid1 Sorry for the delay, we need some more info on this. I'm not able to reproduce given the steps you provided. 
I'm in on our latest 1.18.70 on Windows and typing in two search terms in the url bar in private window gives me results either in Google search or Duck Duck Go search, didn't try any other search engines. It shows as `two words - Google search` or `two words - DuckDuckGo Search` And no crash. What search engine are you using?

Second clarification:
Search with <search engine> is an open search feature that's specific to certain websites like ebay, cnet, others that implemented the following `https://developer.mozilla.org/en-US/docs/Web/OpenSearch`. The search engine will be added here: brave://settings/searchEngines and then invoked when typing in the search engine's address (the default keyword) and pressing Tab. Is that what you mean? That should work in both normal windows and private windows. 

@PyICoder `Hello World` is giving me the results below on both WIndows and mac. Are you still seeing a crash? 
<img width="1317" alt="Screen Shot 2020-12-14 at 10 06 34 PM" src="https://user-images.githubusercontent.com/5951041/102177633-ccdcd200-3e58-11eb-94ed-f67c4ca9bbde.png">

**Comment by Cyberdroid1** [comment] 2020-12-15 11:13
Unfortunately, the bug is still there. 

I have recorded a video for the same.

[Video.zip](https://github.com/brave/brave-browser/files/5695337/Video.zip)
Have a look. 

Strangely, this bug is not present on macOS though (Brave Stable version).

**Comment by PyICoder** [comment] 2020-12-15 19:27
Same for me, it still crashes and still have the bug:
Brave Version:
![image](https://user-images.githubusercontent.com/54691311/102262577-292b0a80-3ec8-11eb-9776-443afdb8c1bd.png)
Video:

![bug 3](https://user-images.githubusercontent.com/54691311/102262854-727b5a00-3ec8-11eb-8918-683d6a87e4b1.gif)

**Comment by rebron** [comment] 2021-01-26 19:53
cc: @kjozwiak Can you reproduce?

**Comment by Cyberdroid1** [comment] 2021-01-27 04:37
I have stopped receiving this error now. 
Looks like it might be fixed now.

**Comment by PyICoder** [comment] 2021-01-27 19:43
It still happens to me, I did update, but I did figure out why it happens, it seems that when the DuckDuckGo Privacy Essentials extension controls the Search engine, and it Allowed in Private, the issue appears.   To fix, all I have to do is disable the extension from private.

**Comment by Cyberdroid1** [comment] 2021-01-28 05:23
Oh, is that so? I had removed duckduckgo extension some days back, and have not been facing this issue from then, but I couldn't relate the 2 incidents.

Duckduckgo extension seems sus now.

**Comment by PyICoder** [comment] 2021-01-28 20:04
I would not say `sus`, but in need of some fixes.

**Comment by kjozwiak** [comment] 2021-01-29 15:53
> It still happens to me, I did update, but I did figure out why it happens, it seems that when the DuckDuckGo Privacy Essentials extension controls the Search engine, and it Allowed in Private, the issue appears. To fix, all I have to do is disable the extension from private.

I was going to ask what extensions you guys are using as it sounds similar to what was reported via https://github.com/brave/brave-browser/issues/10549.

I managed to reproduce the issue using `DDG Privacy Essentials` once I switched/enabled `Allow in private` via `brave://extensions`.

![image](https://user-images.githubusercontent.com/2602313/106294634-656abe00-621d-11eb-8647-53137419964e.png)

Same thing happens with the following:

**`Qwant`**

* https://chrome.google.com/webstore/detail/qwant-for-chrome/hnlkiofnhhoahaiimdicppgemmmomijo

![image](https://user-images.githubusercontent.com/2602313/106296619-ea56d700-621f-11eb-8062-c7463be4717b.png)

**`Ecosia`**

![image](https://user-images.githubusercontent.com/2602313/106296820-1ffbc000-6220-11eb-9017-aa7ee60fee0f.png)

@Cyberdroid1 @PyICoder if you agree that this is the same issue, we can close this one off and use https://github.com/brave/brave-browser/issues/10549. However, we can mention that another case/issue was reported and link to this issue as well 👍

**Comment by Cyberdroid1** [comment] 2021-01-29 16:44
I feel it is the same issue. You can close this one :)

Both are reporting the same bug, so I feel we should go with the one you referred to.

**Comment by rebron** [comment] 2021-01-29 16:49
Closing as dupe of #10549. In #10549 looks like this is something the Extension dev should address.

**Closed by rebron** 2021-01-29 16:49 UTC
Labels: OS/Desktop, OS/Windows, feature/search, needs-investigation, needs-more-info
