### ISSUE TITLE
Brave shields defaults - resets itself to default after restart

### ISSUE THREAD

**Issue by xetorixik** [brave/brave-browser#4263] opened 2019-04-27 13:24 UTC
## Description 

Apparently there seems to be an error or bug related situation in the brave shields defaults. 
After changing the 'brave shields defaults' and the browser is restarted. 
The settings are restored to default.

## Steps to Reproduce

   1. Change the 'Brave shields defaults' from 'Block ads' to 'Allow ads and tracking'.
   2. Restart the Brave browser.
   3. Note that the settings are changed to default i.e. 'Block ads' is on again.

## Expected result:

After setting 'Brave shields defaults' to your own defaults. 
It would be fine if Brave leave these settings alone :) to your own preferred settings. 

## Brave version (brave://version info)

Using Brave version 0.63.48 on Window 10 1903 x64 MSDN.

**Comment by srirambv** [comment] 2019-04-27 16:17
Dupe of #2400

**Closed by srirambv** 2019-04-27 16:17 UTC
