### ISSUE TITLE
New-tab-page should use brave:// URLs

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#13467] opened 2021-01-11 07:34 UTC
The new tab page has a number of convenience links for brave:// configuration / settings.  For example, the "gear / settings" icon in the lower right hand links to chrome://settings; same for bookmarks and history.

These successfully "redirect" to `brave://{settings, bookmarks, history}`, but it might be nicer to have them be all-brave-all-the-time.

Mainly, to avoid confusion on the part of non-technical users who may not understand the relationship between Chrome and Brave (think of how alarming it might be to a concerned-but-not-technical user who downloaded Brave to get away from Google!).

Also (though less important) it might add to the shine and polish of the product to have more consistency across the system.

<img width="569" alt="Screen Shot 2021-01-10 at 11 28 26 PM" src="https://user-images.githubusercontent.com/76526/104155284-b5333380-539b-11eb-94ca-419ae8d3bcdd.png">

**Comment by pes10k** [comment] 2021-01-11 07:34
cc: @rebron @bsclifton

**Comment by rebron** [comment] 2021-01-15 06:41
Closing as dupe of #2566. We had a fix in that one but had to revert.

**Closed by rebron** 2021-01-15 06:41 UTC
Labels: OS/Desktop, branding, feature/new-tab, feature/settings, polish
