### ISSUE TITLE
Toggling `Show Brave News` on/off repeatedly with a large RSS 2.0 feed hangs/crashes

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21485] opened 2022-03-05 08:41 UTC
## Description 

Toggling `Show Brave News` on/off repeatedly with a large RSS 2.0 feed hangs/crashes

## Steps to reproduce 

   1. install `1.38.24`
   2. launch Brave
   3. tap on the 3-dots menu on the bottom toolbar
   4. swipe down and tap `Brave News`
   5. tap to enable via `Show Brave News`
   6. tap `Add source`
   7. enter `https://planet.mozilla.org/rss20.xml`
   8. tap `Search`
   9. wait
   10. once it's added, toggle the `Show Brave News`

## Actual result 

Hangs (even on subsequent app launches!)

https://user-images.githubusercontent.com/387249/156875680-261099e6-12c8-4004-9e2c-76f0c436a3ee.mp4

## Expected result

No hang

## Issue reproduces how often 
100% after a couple tries

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL` phone
   - Android version: `9.0`
   
## Brave version

`1.38.24, Chromium 99.0.4844.51`

cc @alexsafe @mattmcalister @srirambv

**Comment by fallaciousreasoning** [comment] 2022-11-01 03:24
I'm pretty sure this is a duplicate of https://github.com/brave/brave-browser/issues/23909, and should be fixed.

**Closed by fallaciousreasoning** 2022-11-01 03:24 UTC
Labels: crash/webview, priority/P3, QA/Yes, QA/Test-Plan-Specified, OS/Android, feature/brave-news
