### ISSUE TITLE
Removed folders doesn't re-sync even though device are in sync (follow up of #2458)

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2738] opened 2018-12-25 15:42 UTC
## Description 
Found while testing #2458 
Deleted folders doesn't re-sync even though device are in sync (follow up of #2458)

## Steps to Reproduce

   1. Setup sync between Device A and B
   2. Import 5k bookmarks in device A
   3. Make sure 5k bookmarks are synced in device B
   4. Remove 5k bookmarks root folder from device A

## Actual result:
Deleted bookmarks doesn't re-sync on device A . (Waited for almost 15 mins)

Console log errors:

![image](https://user-images.githubusercontent.com/38657976/50424608-f0ce3400-088c-11e9-8e50-36a2e01921ae.png)

## Expected result:
Deleted bookmarks should re-sync in device A<->B, when two devices are still in sync chain.

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Windows 10

### Reproducible on current release: na
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional Information
@brave/legacy_qa

**Comment by AlexeyBarabash** [comment] 2018-12-26 15:08
Errors in the attached screenshot should be fixed with issue https://github.com/brave/brave-browser/issues/2579,  PR https://github.com/brave/brave-core/pull/1179 .

**Comment by AlexeyBarabash** [comment] 2018-12-26 17:33
Could not reproduce on current master `Version 0.61.0 Chromium: 72.0.3626.28`.
Could reproduce particularly  on `Version 0.59.12 Chromium: 72.0.3626.17`, the root folder had not been deleted on DeviceB for a long time, but finally it gone.

I think, this is related with PR https://github.com/brave/sync/pull/265  from @darkdh which made speedup for interaction with AWS.

**Comment by btlechowski** [comment] 2019-01-04 01:04
Reproduced when testing https://github.com/brave/brave-browser/issues/2458 on 

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux

**Comment by srirambv** [comment] 2019-01-15 17:05
@brave/legacy_qa Needs to be retested once new beta build is available.

**Comment by rebron** [comment] 2019-01-16 20:10
cc: @bradleyrichter for expected behavior. Let's reduce to user case to 1 bookmark.

**Closed** 2020-07-02 20:59 UTC
Labels: bug, feature/sync, fixed-with-sync-v2, priority/P4, wontfix
