### ISSUE TITLE
Confirm button not visible when creating Brave wallet keyword reentry

### ISSUE THREAD

**Issue by greggdourgarian** [brave/brave-browser#7130] opened 2019-11-27 13:29 UTC
## Description 

on macpro 15" running catalina created wallet, but could not complete reenter keywords because confirm button was below the fold and there is no scroll bar

## Steps to Reproduce

   1. create brave wallet on mac pro 15" and try to reenter keywords
   2. 
   3. 

## Actual result:

confirm button not visible

## Expected result:
confirm button visible

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by greggdourgarian** [comment] 2019-11-27 15:31
btw by changing to the smallest resolution possible on the mac preferences, then the confirm button did appear

**Comment by pizzalorddex** [comment] 2019-12-23 10:55
I also have this issue or something similar. The wallet page/tab does not scroll down the page which makes it impossible to verify the backup passphrase. Once a user has gotten this far and exits Brave or the tab before confirming the backup phrase the wallet can no longer be used. Upon opening the wallet the next time the user is prompted for a password, which at first looks like it is logging in, but then returns the user to the login page with no status message (i.e. incorrect password or error message). Clicking on restore using seed phrase does nothing other than removing the typing cursor from the password field.

The two attachments show what is happening when I am actively trying to scroll down.

**Versions:**
- MacOS: 10.15.2
- Brave: 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)
- Wallet Component: 1.0.14

**Steps I Took:**
1. Open Brave and complete welcome steps
2. Create a new local wallet (Attachment 1)
3. Input a password
4. View/save backup phrase and click next
5. Cannot confirm backup phrase because the page does not scroll (Attachment 2)
6. Leave wallet tab (I switched to downloads)
7. Open the wallet tab again and am prompted for the password. (Password does not work and is not incorrect)

<img width="1198" alt="WalletTabNoScroll" src="https://user-images.githubusercontent.com/37597645/71353553-afdd2e00-2579-11ea-8774-280fed106b0e.png">
<img width="1200" alt="WalletPassNoScroll" src="https://user-images.githubusercontent.com/37597645/71353569-b9ff2c80-2579-11ea-8a8c-74d2c32dde86.png">

**Comment by srirambv** [comment] 2019-12-23 14:52
Workaround for this issue is to zoom out page view and rest once done.

**Comment by eljuno** [comment] 2020-01-07 22:12
+1 from community

https://community.brave.com/t/confirm-your-secret-backup-phrase-page-scroll-issues/101150

**Comment by ryanml** [comment] 2020-04-03 17:54
Closing as a dupe of https://github.com/brave/brave-browser/issues/7045 which has been fixed.

**Closed by ryanml** 2020-04-03 17:54 UTC
Labels: priority/P2
