### ISSUE TITLE
No link to manage extensions' keyboard shortcuts

### ISSUE THREAD

**Issue by Madis0** [brave/brave-browser#13061] opened 2020-12-05 09:52 UTC
## Description 

Chromium has a way for users to customize keyboard shortcuts for launching and managing their extension features. That can be viewed by going menu > More tools > Extensions > hamburger button > Keyboard shortcuts or `chrome://extensions/shortcuts`. However, Brave has redesigned the extension manager and has not included this link (even though the page works in Brave if opened directly).

## Steps to Reproduce

   1. Open menu > Extensions
   2. Look for "keyboard shortcuts" link

## Actual result:

There is no link.

## Expected result:
Expected a link to `chrome://extensions/shortcuts`.

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.19.47 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
Build | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by bsclifton** [comment] 2020-12-07 07:11
@Madis0 thanks for the feedback 😄 We do have a link on brave://settings/extensions but not on the actual extensions page itself (brave://extensions)
![image](https://user-images.githubusercontent.com/4733304/101320252-4866cf80-3818-11eb-8e54-8963874186d9.png)

**Comment by tlkahn** [comment] 2021-02-01 03:30
Confirmed the url also works: brave://extensions/shortcuts. But yes, I cannot find how to set up the shortcut key until I check out this issue.

**Comment by fallaciousreasoning** [comment] 2023-05-17 02:55
There's a link to this from the settings page (brave://settings/extensions), do you think that's enough for your purposes @tlkahn & @Madis0?
![image](https://github.com/brave/brave-browser/assets/7678024/c0870c7d-455a-4ddc-9547-9118fd06a79c)

If so, I might close this issue.

**Comment by Madis0** [comment] 2023-05-17 04:15
No, I think it should be in the main extensions page.

**Comment by Releece** [comment] 2023-08-13 15:43
> No, I think it should be in the main extensions page.

Agreed, this is where most users will intuitively end up to look for extension shortcut options. You press the hamburger menu > extensions, and then examine the subsequent page with a dissappointing result. Especially since this is the place where chromium / Chrome has placed this menu option. Most users that use Brave will have used / still use chromium-based browsers so it would also align well with users expectations because of their previous experience.

As a user not seasoned in using Brave, the general options page is really very large with quite more settings than most browsers (fortunately! users need choice badly :) ) so it will take a long time before one memorizes if and where what settings can be found. Which is why even as a very tech-savvy user, I eventually resorted to search the internet for the answer, little bit worried if the feature was even there at all.

Minor detail maybe, but maximize user-friendliness and you maximize adoption! Having two places that link to the shortcuts page can only help!

**Comment by bsclifton** [comment] 2024-07-01 21:44
This is now fixed 🎉 
![image](https://github.com/brave/brave-browser/assets/4733304/887b709b-fb7a-4c7c-9072-03deeb0993de)

**Closed by bsclifton** 2024-07-01 21:44 UTC
Labels: feature/extensions, feature/keyboard-shortcuts, priority/P5, feature-request, OS/Desktop
