### ISSUE TITLE
Use 'mint address' rather than 'contract' when referring to Solana NFTs in UI

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#29401] opened 2023-03-29 23:33 UTC
Also, some token information is cut off per https://bravesoftware.slack.com/archives/C02HSD2FUQJ/p1680127455969099?thread_ts=1679956644.595699&cid=C02HSD2FUQJ.

**Comment by srirambv** [comment] 2023-03-31 08:36
Dupe of #29008

**Comment by muliswilliam** [comment] 2023-04-18 06:43
@srirambv Can I close this because is a duplicate of #29008 ?

**Comment by srirambv** [comment] 2023-04-20 04:24
Yup. Closing it a dupe

**Closed by srirambv** 2023-04-20 04:24 UTC
Labels: release-notes/include, feature/web3/wallet, OS/Desktop, front-end-change, feature/web3/wallet/solana, feature/web3/wallet/nft
