### ISSUE TITLE
Nightly shortcut links to wrong version on Linux

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1746] opened 2018-10-19 22:05 UTC
## Description 

Shortcut links to wrong version on Linux

## Steps to Reproduce

   1. Install all three versions Dev(0.57.1)/Beta(0.56.5)/Release(0.55.18)
   2. Open Applications and type in Brave
   3. Click the Brave icon opens release version(0.55.18)
   4. Close and Open Beta from Application, verify the version from `brave://version`
   5. Go to Applications and type in Brave, App indicator highlights Release version even though Beta is launched
   6. Click on Release version icon from Application, no new window is launched
   7. Right Click on the app from side dock and click on new window
   8. New browser window is launched, check version via `brave://version`. shows `0.55.18`

## Actual result:

Shortcut links to wrong version on Linux

## Expected result:
Should link the correct app to shortcut

## Reproduces how often: 

Easy

## Brave version (brave://version info)

0.55.18/0.56.5/0.57.1

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes same issue with launching Dev
- Does it reproduce on browser-laptop? 
N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

@kjozwiak reproduced it as well

**Comment by srirambv** [comment] 2019-07-23 20:02
This issue is now only with release and nightly version. Nightly points to the wrong launcher icon in favourites if you have it pinned.

**Comment by fmarier** [comment] 2019-09-27 20:57
I can't reproduce this problem.

I did the following:

1. In Applications, click on Brave.
2. Close it.
3. In Applications, click on Brave Beta (leaving it open).
4. In Applications, click on Brave.

In all three cases, the correct version of Brave launched and the right icon was highlighted in my favorites bar on the left.

@srirambv Are you still seeing this problem?

I wonder whether it got fixed as a side effect of fixing #1324.

**Comment by srirambv** [comment] 2019-10-15 12:26
@fmarier this seems to be fixed however Release and Nightly still uses the same app launcher on Linux which isn't fixed

Launch release channel browser uses release channel on the dock 
Launch nightly channel browser uses the same release channel on dock doesn't use nightly icon 
[1746.zip](https://github.com/brave/brave-browser/files/3729202/1746.zip)

**Comment by fmarier** [comment] 2019-10-18 20:52
Thanks @srirambv I can reproduce with Nightly too.

Here's the problem:
```
$ xprop WM_CLASS  # dev
WM_CLASS(STRING) = "brave-browser-dev", "Brave-browser-dev"
$ xprop WM_CLASS  # stable
WM_CLASS(STRING) = "brave-browser", "Brave-browser"
$ xprop WM_CLASS  # nightly
WM_CLASS(STRING) = "brave-browser", "Brave-browser"
```

**Comment by BachoSeven** [comment] 2020-04-28 22:54
I think this issue (#9313) I opened is related, maybe a duplicate of this? I could reproduce it on nightly, beta and release.

Do you think that my workaround could be implemented?

**Comment by fmarier** [comment] 2020-04-29 00:07
Thanks for the suggestion @BachoSeven . It does sound like it would work.

Last time I had some time to look into this, I got closer to where the reason why the `WM_CLASS` wasn't set correctly in the first place. Fixing that would be my preference since it might uncover some other problems where we don't distinguish Nightly from Release.

**Comment by BachoSeven** [comment] 2020-04-29 00:36
Sounds good, thanks for looking into it!

**Comment by BachoSeven** [comment] 2020-05-09 13:35
In the meantime, if anybody wants a quick solution you could use this one-liner after upgrading the package (nightly): 
```
sudo sed -i '/Actions=new-window;new-private-window;/ a StartupWMClass=brave-browser' /usr/share/applications/brave-browser-nightly.desktop
```

**Closed** 2021-01-28 03:06 UTC
Labels: OS/Linux, QA/Test-Plan-Specified, QA/Yes, bug, priority/P5, release-notes/include

**Comment by btlechowski** [comment] 2021-02-14 14:24
Verification passed on

Brave | 1.22.23 Chromium: 89.0.4389.48 (Official Build) nightly (64-bit)
-- | --
Revision | 0fe3c4589a6cf5ce719d167834dfa9cd8978937a-refs/branch-heads/4389@{#873}
OS | Ubuntu 18.04 LTS

Verified test plan from the description and https://github.com/brave/brave-core/pull/7685
Verified each version has corresponding icon. Verified icon in dock launch proper version.
![image](https://user-images.githubusercontent.com/34715963/107879329-79c6e000-6ed8-11eb-939a-02de7b6134c1.png)

Verified `WM_CLASS(STRING) = "brave-browser-nightly", "Brave-browser-nightly"`
```
bartlomiej@bartlomiej-VirtualBox:~$ xprop WM_CLASS
WM_CLASS(STRING) = "brave-browser-nightly", "Brave-browser-nightly"
```
