### ISSUE TITLE
No icon on Thank you banner for some verified publishers

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3364] opened 2019-02-14 23:14 UTC
Follow up from https://github.com/brave/brave-browser/issues/2718

## Steps to Reproduce

   1. Enable rewards
   2. Claim grant
   3. Open `https://www.youtube.com/channel/UCW1ow8v-bl_zzbbztAACoHw`
4. Tip the publisher

More links:
`https://www.youtube.com/channel/UCwSdcnEGdt3UBCcf40rrn5g`
`https://www.youtube.com/channel/UCc8myGC9uGlFUlmfZTBWhVQ`

## Actual result:

No icon on Thank you banner

![image](https://user-images.githubusercontent.com/34715963/52823697-3271a300-30b6-11e9-9ec9-d78fa1b8427d.png)

Note: tipping banner looks like this:
![image](https://user-images.githubusercontent.com/34715963/52823806-8a100e80-30b6-11e9-959d-0e48e717fe98.png)

## Expected result:
Icon on Thank you banner
Or 
first latter instead of the icon per https://github.com/brave/brave-browser/issues/2718

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 7

cc @brave/legacy_qa @mandar-brave @NejcZdovc

**Comment by kjozwiak** [comment] 2019-02-15 02:04
@NejcZdovc does #3273 fixes this as well as per https://github.com/brave/brave-browser/issues/3265#issuecomment-461714458?

**Comment by NejcZdovc** [comment] 2019-02-15 05:29
@kjozwiak I would say so, just tried it on the latest 0.61 and it's working. Closing as dupe of #3273

**Closed by NejcZdovc** 2019-02-15 05:29 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/rewards
