### ISSUE TITLE
chrome extension bug fix in brave browser : google keep 

### ISSUE THREAD

**Issue by ggfer** [brave/brave-browser#9623] opened 2020-05-05 09:36 UTC
## Description 
Something blocks the panel. But it does not happen in the chrome browser. Could you please fix it.

## Steps to Reproduce
   1. search the extension on chrome webStore by 'google keep'
   2. add it to the brave browser menu.
   3. hit the icon.

## Actual result:

![image](https://user-images.githubusercontent.com/19473701/81052291-c2874c80-8ef5-11ea-926a-c0a56d989842.png)

## Expected result:
![image](https://user-images.githubusercontent.com/19473701/81052390-eb0f4680-8ef5-11ea-9939-cf4663bceeef.png)

## Reproduces how often: 
always.

## Brave version (brave://version info)
it is no need to concern. it is the lastest version.

## Other Additional Information:
I try the extension on the chrome browser. However, it works actually.

**Comment by rebron** [comment] 2020-05-06 16:55
Closing as duplicate of #3650

**Closed by rebron** 2020-05-06 16:55 UTC
Labels: duplicate
