### ISSUE TITLE
Bring back 'Download bubble' flag

### ISSUE THREAD

**Issue by PlatinMTA** [brave/brave-browser#34078] opened 2023-11-02 23:22 UTC
## Description 
Download bubble flag was removed in brave://flags last release. That flag let you disable the download bubble at the top right and bring it back the download bar at the bottom of the browser. If possible, bring it back.

## Brave version (brave://version info)
1.60.110 Chromium: 119.0.6045.105 (Build oficial) (64 bits)

**Comment by Emi-HoloGhostRevisionist88** [comment] 2023-11-03 00:11
The _download bar_ is deprecated by Chromium Project, and the code is getting removed by them since they are not needed anymore, like you can't even _unexpire_ the flags either, they are getting completely removed.

The download _bubble_ is the new default, and the flags were only meant as a way to disable the new feature until it got complete green light to be default, not to go back to 'old ways' forever just because people are stubborn and can't just adopt the new way.

https://chromium-review.googlesource.com/c/chromium/src/+/4851411

**Comment by PlatinMTA** [comment] 2023-11-03 00:15
> The _download bar_ is deprecated by Chromium Project, and the code is getting removed by them since they are not needed anymore, like you can't even _unexpire_ the flags either, they are getting completely removed.

Yeah figured it out already. How are you supposed to downgrade the Chromium version anyway? Tried with a few old nightlies but I'm still defaulted to 119.0.6045.105

> not to go back to 'old ways' forever just because people are stubborn and can't just adopt the new way.
You can save your opinions btw, people can and should use their software as they like

**Comment by rom4ster** [comment] 2023-11-04 00:50
I 100% agree, bring back the damn bar. I would switch to brave JUST for that. 

This is now a feature request, so here is me requesting it.

**Comment by fadedboiii** [comment] 2023-11-05 02:40
> This is now a feature request, so here is me requesting it.

Yes, if possible please add this back!

**Comment by PumpkinBear111** [comment] 2023-11-05 19:32
The download bubble is painful to use, forcing unnecessary clicks and its going to be painful to get used to after using the download bar for **years**

**Comment by Malex** [comment] 2023-11-10 17:15
The download bubble is very bad for me as well.
The old way it was easy to use the just downloaded file very easly, also it followed the natural flow of your eyes. Now I have to look aroudn. And for work I need to download files every day multiple times a day

**Comment by StrangePeanut** [comment] 2023-11-19 07:23
My main gripe with the new 'download bubble' is that there is absolutely no feedback whatsoever when you start a download. This leads to downloading the same file multiple times because it looks like nothing is happening.

**Comment by PumpkinBear111** [comment] 2023-11-19 07:25
> My main gripe with the new 'download bubble' is that there is absolutely no feedback whatsoever when you start a download. This leads to downloading the same file multiple times because it looks like nothing is happening.

I have the same issue with it. I download something and then forget about it or end up downloading it multiple times since I don't realize it downloaded successfully

**Comment by Sandorpiller** [comment] 2023-11-26 09:12
> The _download bar_ is deprecated by Chromium Project, and the code is getting removed by them since they are not needed anymore, like you can't even _unexpire_ the flags either, they are getting completely removed.
> 
> The download _bubble_ is the new default, and the flags were only meant as a way to disable the new feature until it got complete green light to be default, not to go back to 'old ways' forever just because people are stubborn and can't just adopt the new way.
> 
> https://chromium-review.googlesource.com/c/chromium/src/+/4851411

Thanks for calling reasonable people stubborn. This bubble is awful, the bar was way more useful.

**Comment by resultwrap** [comment] 2023-12-08 02:47
I agree with everyone here. I was actually very unimpressed to find out that my brave had automatically updated back to the bubble. The bubble is not useful to me in anyway. Unnecessary clicks. I do a lot of music production and during some of my projects I have to download a ton of files but I can only download in single files so when I'm doing that I can easily see what file name I've downloaded so then I don't download the same file twice, or three times etc. This is a waste of time for me with the bubble cuz now I have to click an extra button just to see what I downloaded, and then when I click off screen of the downloads window, it disappears so then I have to click the bubble again... just a humungous waste of time.

**Comment by lica98** [comment] 2023-12-09 12:15
> The _download bar_ is deprecated by Chromium Project, and the code is getting removed by them since they are not needed anymore, like you can't even _unexpire_ the flags either, they are getting completely removed.
> 
> The download _bubble_ is the new default, and the flags were only meant as a way to disable the new feature until it got complete green light to be default, not to go back to 'old ways' forever just because people are stubborn and can't just adopt the new way.
> 
> https://chromium-review.googlesource.com/c/chromium/src/+/4851411

the problem isn't just that they simply changed how something looks but that they made it less convenient to use

for example I do a lot of stuff where I download an image then copy another image and combine the 2 in paint, before I could just download the first image then go copy the second one and then just click on the bar to open the first image, but now the bubble disappears immediately when you go to the second one so you have to make another click to get it (plus the icon is very small so the chance of misclicking increases)

another problem with the bubble is that it gets in the way of stuff, like when you have an image gallery where you're downloading images and then the bubble is covering the "next picture" arrow ([like this](https://github.com/brave/brave-browser/assets/74957561/2fac1d76-b282-444f-8d82-7e0e3817e914))

**Comment by rom4ster** [comment] 2023-12-09 20:34
So this extension, while not in any form great, does bring back a good chunk of stuff. Just make sure you turn off notifications. 

https://chromewebstore.google.com/detail/download-statusbar/kfjkodkjnmdeookccjmcdbhhpbgkoche

**Comment by bsclifton** [comment] 2024-02-26 07:37
Thanks for the feedback folks - closing this issue as a duplicate of https://github.com/brave/brave-browser/issues/34451

**Closed by bsclifton** 2024-02-26 07:37 UTC
Labels: feature/download, feature-request, OS/Desktop

**Comment by T3rminat0r** [comment] 2024-02-26 08:47
> The _download bar_ is deprecated by Chromium Project, and the code is getting removed by them since they are not needed anymore, like you can't even _unexpire_ the flags either, they are getting completely removed.
> 
> The download _bubble_ is the new default, and the flags were only meant as a way to disable the new feature until it got complete green light to be default, not to go back to 'old ways' forever just because people are stubborn and can't just adopt the new way.
> 
> https://chromium-review.googlesource.com/c/chromium/src/+/4851411

If brave followed your argumentation, the whole project would be useless, since anything Chrome/Chromium did, would be changed in brave, as well ... If brave is just a chromium clone, it's actually a waste of time to maintain.
