### ISSUE TITLE
Brave crashes when closing the last tab, if brave://flags/#brave-horizontal-tabs-update is set to disabled

### ISSUE THREAD

**Issue by pitsi** [brave/brave-browser#40150] opened 2024-07-31 10:03 UTC
### Description

When setting the forementioned flag to disabled, so as to make the tabs look like... actual tabs, brave 1.68 crashes when closing the last tab and on the next launch, a prompt is shown to restore the session. This error shows up in the terminal
```
[0731/124236.247731:ERROR:elf_dynamic_array_reader.h(64)] tag not found
/usr/bin/brave-browser: line 39:  4790 Illegal instruction     (core dumped) "$HERE/brave" "$@"
```
The crash does not happen if the forementioned flag is set to enabled or default. That flag is there since late January 2024 and brave 1.62, and I have it changed since then, but no crashes happened all these months.

### Steps to reproduce

1. Change `brave://flags/#brave-horizontal-tabs-update` to disabled and restart brave as prompted.
2. Change "Close window when closing last tab" to disabled under `brave://settings/system`.
3. Open a few new tabs and close them one by one.
4. Notice that brave crashes and exits when closing the last one.

### Actual result

Brave crashes and exits.

### Expected result

Brave should not crash and should not exit, becasue of the setting on step 2 above.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave 1.68.128 Chromium: 127.0.6533.73 (Official Build) (64-bit) ￼
Revision	800676fd9ede2eb4174bac98c186e53749c7201f
OS Linux
```

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

If the flag itself is to blame, it can be removed completely in a future update.
The issue is also reproducible on a completely blank profile of brave.

**Comment by pitsi** [comment] 2024-08-01 12:36
Can someone at least confirm the issue?

**Comment by tech-zilla** [comment] 2024-08-01 13:16
Can confirm, this issue is reproducing and is a duplicate of: https://github.com/brave/brave-browser/issues/39986

**Comment by pitsi** [comment] 2024-08-01 16:21
Thank you for confirming it.
I had also noticed it since last week, right after the update in fact, but I was too busy to report it, sorry.

If the devs think it can be merged with the other one, please close this one.

**Comment by rebron** [comment] 2024-08-02 19:36
closing as dupe of #39986 can follow along there. Thanks @tech-zilla

**Closed by rebron** 2024-08-02 19:36 UTC
Labels: OS/Desktop
