### ISSUE TITLE
some YT publishers not appearing under BR panel when pasting URL

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#3800] opened 2019-03-20 03:29 UTC
## Description 

As per https://github.com/brave/browser-android-tabs/issues/1317#issuecomment-472937673, the Rewards panel won't work when directly pasting specific YT publisher URLs into the ombibox.

## Steps to Reproduce

   1.  launch `0.61.51 Chromium: 73.0.3683.75` & enable rewards
   2. paste https://www.youtube.com/watch?v=UvJl202PlNI into the URL
   3. click on the BAT icon to reveal the Rewards panel

## Actual result:

<img width="1438" alt="Screen Shot 2019-03-14 at 12 01 17 PM" src="https://user-images.githubusercontent.com/2602313/54656886-cbbd1c00-4a9d-11e9-8b18-6a479505a789.png">

## Expected result:

<img width="1283" alt="Screen Shot 2019-03-19 at 11 22 34 PM" src="https://user-images.githubusercontent.com/2602313/54656919-e8f1ea80-4a9d-11e9-8512-4ad1575ba643.png">

## Reproduces how often: 

100% reproducible when using the above STR.

## Brave version (brave://version info)

Brave | 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

### Reproducible on current release:

Yes, reproducible under `0.61.51 Chromium: 73.0.3683.75`

- Does it reproduce on brave-browser dev/beta builds? Yes, reproducible on all channels.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by NejcZdovc** [comment] 2019-03-20 11:42
+1 from https://github.com/brave/brave-browser/issues/3789

**Comment by btlechowski** [comment] 2019-03-20 17:32
Reproduced on 

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

**Comment by jasonrsadler** [comment] 2019-03-24 23:00
@kjozwiak This is due to embedding disabled and is fixed in https://github.com/brave/brave-core/pull/1901 (0.64.x)

**Comment by NejcZdovc** [comment] 2019-03-25 05:41
closing as dupe of https://github.com/brave/brave-browser/issues/3335

**Closed by NejcZdovc** 2019-03-25 05:41 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards
