### ISSUE TITLE
[Feature request] Being able to add and edit "top sites"

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#17217] opened 2021-07-28 11:31 UTC
The feature which make users be able to edit and add "top sites" is really useful. I hope it be added to the Anfroid version. Thank you.

**Comment by sanathusk** [comment] 2021-10-06 02:08
It would be great if the feature could be implemented

**Comment by Dave051987** [comment] 2021-11-05 17:48
Yes this feature would be awesome.

**Comment by gossbill** [comment] 2021-11-18 05:59
I totally support this feature request!

**Comment by blogmangit** [comment] 2022-03-15 15:51
+1 I support this issue and I think to have this feature will be awesome 👌

**Comment by DarrenSem** [comment] 2022-10-14 16:31
+1!!! I accidentally clicked Remove on a frequent site and now it thinks I wanted it permanently hidden from the list :-(

**Comment by SlowNicoFish** [comment] 2023-02-18 11:50
They have this on Mac, iOS and windows. Seems like android is always drawing the short end of the stick

**Comment by SlowNicoFish** [comment] 2023-02-18 11:51
https://github.com/brave/brave-browser/issues/16821

**Comment by kyoyacchi** [comment] 2023-02-19 15:39
Up

**Comment by Bohdan-Mishchuk** [comment] 2023-04-11 15:03
+

**Comment by Hmm-mmm** [comment] 2023-08-04 11:52
I wonder if it is really difficult to add this option to manually add/edit the sites in the front page. 🤔

It would be great if the devs could bring this feature. It is really needed.

**Comment by RickAust** [comment] 2023-08-21 18:40
Definitely a very worthwhile feature. Surely it's not that difficult to implement.

**Comment by nicdevera** [comment] 2023-08-31 23:01
no one's picking up on this? maddening lack in brave mobile.

**Comment by senescence01** [comment] 2023-10-07 15:09
It's baffling how no one cares about this feature.

**Comment by bill-mcgonigle** [comment] 2024-02-05 17:57
from a closed issue: 

> The ANDROID app needs this feature! I accidentally clicked Remove on a frequent site and **now it thinks I wanted it permanently hidden from the list** :-(

This, especially.

Do I need to get in with sqlite or something to undo a fat-finger removal of my top daily news site? It's probably my second most frequent site.

**Comment by bsclifton** [comment] 2024-02-28 19:35
Thanks for the feedback folks - I'm going to close this issue as a duplicate of https://github.com/brave/brave-browser/issues/33845

Please subscribe for updates on that issue - we have mock ups and will be starting work soon! 😄

**Closed by bsclifton** 2024-02-28 19:35 UTC
Labels: OS/Android
