### ISSUE TITLE
Let us block updates.

### ISSUE THREAD

**Issue by Dr-Sauce** [brave/brave-browser#16390] opened 2021-06-12 14:34 UTC
## Description 

Some people don't like updates. Because it just makes Brave messy with new(and removed) features.

I blocked Brave updates by stopping Brave update automatically launching on startup. But some how when I turned on my computer today Brave was updated to the newest version.  

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment] 2021-06-14 05:51
Thanks for the report @Dr-Sauce - I'm going to close this issue as a duplicate of https://github.com/brave/brave-browser/issues/5576

You can subscribe there for updates and to leave some feedback 😄

**Closed by bsclifton** 2021-06-14 05:51 UTC
Labels: OS/Desktop

**Comment by Tectract** [comment] 2021-06-30 00:11
BUMP. I also want to be able to block updates and I HATE being "nagged" to install updates. It's my computer, I will update when I'm ready. Like after you fix the tabbing bug that a thousand people are complaining about maybe.
