### ISSUE TITLE
Brave Ads displayed while in full-screen mode

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [brave/brave-browser#12494] opened 2020-11-03 15:31 UTC
## Description 
Brave Rewards ads still show when watching a video in full-screen on Disney+

## Steps to Reproduce
   1. Go to www.disneyplus.com
   2. Select a video to watch
   3. Switch to full-screen mode

## Actual result:
![2020-11-03-162824-brave](https://user-images.githubusercontent.com/22710992/98005816-c555f200-1df1-11eb-8143-51dc0751863b.jpg)
![2020-11-03-163256-brave](https://user-images.githubusercontent.com/22710992/98006269-51681980-1df2-11eb-9a14-3c8dceddf286.jpg)
![2020-11-03-171217-brave](https://user-images.githubusercontent.com/22710992/98011205-d7d32a00-1df7-11eb-95ff-56219aa84e24.jpg)

## Expected result:
Brave Rewards should not appear when browser is un full-screen mode

## Reproduces how often: 
Easily reproduced.

## Brave version (brave://version info)

Brave: 1.16.68 Chromium: 86.0.4240.111 (Official build) (64 bits)
Revision:| b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS: Windows 10 OS Version 1909 (Build 18363.1139)

## Version/Channel Information:
Only tested it on Release channel. 
Occurrence is to be highly variable: no ad in two hours, then two ads in three minutes. Ad delivery during general use is quite inconsistent on my end.

**Comment by rebron** [comment] 2020-12-15 06:31
@UjCbFwtBayFM Are you still seeing this issue on our latest 1.18.70

cc: @tmancey

**Comment by tmancey** [comment] 2021-01-04 18:35
Closing issue as cannot reproduce, @UjCbFwtBayFM if this issue occurs again please re-open this ticket. Thank you

**Comment by UjCbFwtBayFM** [comment] 2021-01-07 15:12
> @UjCbFwtBayFM Are you still seeing this issue on our latest 1.18.70
> 
> cc: @tmancey

I can't say if it's still happening, I had to stop using Brave because of the memory leaks in the recent versions.

**Comment by tmancey** [comment] 2021-01-13 12:02
Closing issue as cannot reproduce

**Comment by tmancey** [comment] 2021-01-13 12:48
Reproduced on Windows 10

**Comment by tmancey** [comment] 2021-02-03 16:59
Closing issue as working as expected with 1.19.88

**Closed by tmancey** 2021-02-03 16:59 UTC
Labels: OS/Windows, QA/Yes, bug, feature/ads, priority/P3, release-notes/exclude

**Comment by LaurenWags** [comment] 2021-02-05 13:53
@tmancey if this is `closed/wontfix` can we change `QA/Yes` to `QA/No`?
