### ISSUE TITLE
DevTools Dark theme is not applied

### ISSUE THREAD

**Issue by victorlmneves** [brave/brave-browser#20154] opened 2021-12-17 15:03 UTC
## Description 

DevTools don't change to dark theme

## Steps to Reproduce

   1.  Open DevTools
   2.  Click on the Settings icon
   3.  Change Appearance theme to Dark

## Actual result:

After reloading DevTools it stays with Light theme

## Expected result:
It should apply Dark theme

## Brave version (brave://version info)

Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment] 2021-12-17 19:42
Closing as duplicate of https://github.com/brave/brave-browser/issues/19871

**Closed by rebron** 2021-12-17 19:42 UTC
Labels: closed/duplicate, OS/Desktop
