### ISSUE TITLE
New Private window should be New private window in File menu

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16982] opened 2021-07-15 21:23 UTC
## Description 

`New Private window` should be `New private window` in File menu

## Steps to Reproduce

   1.  launch Brave on Windows
   2. click on the "hamburger" menu on the top right of the toolbar
   3. look at the casing of the `New...` options

## Actual result:

The menu item reads `New Private window`

![private-window](https://user-images.githubusercontent.com/387249/125859233-e5bb8742-e4b2-4730-8425-9bd88271e588.png)

## Expected result:

Should read `New private window`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.29.3 Chromium: 92.0.4515.101 (Official Build) nightly (64-bit)
-- | --
Revision | edb73f4fb624e2ea0cb6f5cc39c9e317ecd3535b-refs/branch-heads/4515@{#1536}
OS | Windows 10 OS Version 2009 (Build 22000.65)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

**Comment by srirambv** [comment] 2021-07-16 05:01
Dupe of #16503

**Closed by srirambv** 2021-07-16 05:01 UTC
Labels: OS/Desktop, good first issue, needs-text-change
