### ISSUE TITLE
Show `Brave Today is experiencing some issues. Try again instead` message instead of spinner when the network is OFF.

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13109] opened 2020-12-09 11:54 UTC
## Description 

Show `Brave Today is experiencing some issues. Try again instead` message instead of the spinner when the network is OFF.

## Steps to Reproduce

   1. Disconnect the Wifi/Internet
   2. Clean profile 1.18.x
   3. Open a NTP
   4. Scroll to the Brave today feeds
   

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/101622205-c3a8cb00-3a3c-11eb-983d-0ec7c1962e94.png)

## Expected result:
As mentione din the test plan https://github.com/brave/brave-browser/issues/12574#issue-738370772
![image](https://user-images.githubusercontent.com/38657976/101626470-09689200-3a43-11eb-9fcf-417acca670e6.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.18.69 Chromium: 87.0.4280.88 (Official Build) (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 10 OS Version 2004 (Build 19041.630)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @petemill @karenkliu

**Comment by mattmcalister** [comment] 2022-03-08 12:55
Closing as dupe of https://github.com/brave/brave-browser/issues/14508

**Closed by mattmcalister** 2022-03-08 12:55 UTC
Labels: bug, feature/new-tab, QA/Yes, QA/Test-Plan-Specified, OS/Desktop
