### ISSUE TITLE
Scripts can't be unblocked with custom filters

### ISSUE THREAD

**Issue by wooque** [brave/brave-browser#29215] opened 2023-03-21 17:39 UTC
## Description 
I want to block scripts in general and only allow certain scripts to be run. For test I blocked scripts on https://boards.4channel.org/g/catalog, and added exceptions in custom filters
```
@@||s.4cdn.org/js/*$script
@@||boards.4channel.org^$inline-script
```
but that didn't work.

## Steps to Reproduce

   1.  Block scripts on https://boards.4channel.org/g/catalog
   2.  Add custom filters 
   ```
@@||s.4cdn.org/js/*$script
@@||boards.4channel.org^$inline-script
```

## Actual result:
Scripts are still blocked

## Expected result:
Scripts are unblocked

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? /
- Can you reproduce this issue with the nightly channel? /

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? /
- Does the issue resolve itself when disabling Brave Rewards? /
- Is the issue reproducible on the latest version of Chrome? /

**Comment by antonok-edm** [comment] 2023-03-21 21:38
@wooque this is by design, we don't want users who enable script blocking to be affected by exceptions written specifically for selective adblock filtering (which can be shipped by upstream filter list authors).

The good news though, is that we recently landed selective script blocking exceptions through the shields panel in Nightly - see https://github.com/brave/brave-core/pull/17221 for details.

**Closed by antonok-edm** 2023-03-21 21:38 UTC
Labels: privacy, OS/Desktop
