### ISSUE TITLE
No ads have been shown for months

### ISSUE THREAD

**Issue by sahilc0** [brave/brave-browser#13409] opened 2021-01-07 04:04 UTC
## Description 

It's been months now and I haven't been getting ads (and therefore rewards). New tab ads are shown, but no rewards are given.

## Actual result:

No ad notifications are shown.

## Expected result:
Notification Ads should be shown.

## Reproduces how often: 

Every day for a few months now.

## Brave version (brave://version info)

Brave | 1.18.75 Chromium: 87.0.4280.101 (Official Build) (x86_64)
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | macOS Version 11.0.1 (Build 20B29)
JavaScript

## Version/Channel Information:

This happens on all official versions across multiple macOS devices.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No, because it's Brave specific.

**Comment by sahilc0** [comment] 2021-01-07 04:04
What other info can I provide to be helpful?

**Comment by rebron** [comment] 2021-01-08 05:23
@sahilc0 In System Preferences -> Notifications do you have Allow Notifications turned on for Brave Browser?

**Comment by Brave-Matt** [comment] 2021-01-08 17:55
@sahilc0,
You should also check and make sure Brave isn't blocked in `Security` settings and that you don't have `Do not disturb` enabled.

**Comment by sahilc0** [comment] 2021-01-09 17:41
@rebron Yup 
![image](https://user-images.githubusercontent.com/8256062/104104720-b3b02100-525e-11eb-92fd-73f697e4cbf8.png)

and @Brave-Matt DND is not enabled, and I don't see anywhere where Brave is blocked in "security" (also I use the browser every day)

**Comment by rebron** [comment] 2021-01-15 06:54
@sahilc0 Can you update to 1.18.78 and also what's your language and locale that you have set for Brave?

cc: @tmancey

**Comment by tmancey** [comment] 2021-01-15 08:07
@sahilc0 Can you please email your payment id which can be found at brave://rewards-internals to tmancey@brave.com (please include a link to this issue) so I can look into this for you. Thanks

**Comment by lxwulf** [comment] 2021-01-21 08:58
I also have this problem. I use Brave Browser Nightly on Windows. No ads there. The only device which send me ads is my android phone with brave-beta installed. For more information just ask me ✌.

**Comment by tmancey** [comment] 2021-01-21 09:01
@lxwulf I work on the Brave Ads team and am available now if you would like to screen-share so I can help diagnose the issue. If so, please email tmancey@brave.com and I will send meeting details. Thanks

**Comment by tmancey** [comment] 2021-01-22 15:08
@lxwulf Thanks for screen-sharing. We discovered a bug in Beta and Nightly where upgrade paths were failing. This will be resolved in Nightly and Beta. Are other users experiencing issues also using Beta/Nightly?

**Comment by tmancey** [comment] 2021-01-22 15:17
I am closing this issue, however if you are experiencing issues please reach out to me and I will help understand the cause. Thanks

**Comment by tmancey** [comment] 2021-01-22 15:17
Duplicate of https://github.com/brave/brave-browser/issues/13719

**Closed by tmancey** 2021-01-22 15:17 UTC
Labels: OS/Desktop, feature/ads, needs-investigation
