### ISSUE TITLE
YouTube ads, blocked videos, etc.

### ISSUE THREAD

**Issue by raj23689** [brave/brave-browser#33493] opened 2023-10-07 08:38 UTC
## Description 

YouTube video won't play unless I reload page because of ads. YouTube is just loading an ad for every video and its just _black loading screen_ or sometime _white screen with skip ad_. The only way to play a video is if I reload the page or wait (but mostly reload pages). Its happening on both android and desktop brave applications.

## Steps to Reproduce

   1. Go to [YouTube](https://www.youtube.com/)
   2. Open any Video
   3. You will see a blank loading screen or sometimes a white screen with **skip ad** on the bottom right of the screen.

### White screen with Skip ad
![image_with_skip_ad](https://github.com/brave/brave-browser/assets/92665411/193f775e-683f-4e82-bc1d-0acc1ebe0698)

### Blank Screen, Ad name on top left corner of the video pane.
![blank_loading_screen](https://github.com/brave/brave-browser/assets/92665411/c7715cbe-ae3d-4514-a452-8708583ce2e6)

## Expected result:
Block the ad and load the video.

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

1.58.137 Chromium: 117.0.5938.153 (Official Build) (64-bit) 

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? N/A / Haven't checked
- Can you reproduce this issue with the nightly channel? N/A / Haven't checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by pratyakshm** [comment] 2023-10-07 09:29
Reproducing on Windows:
1.58.137 Chromium: 117.0.5938.153 (Official Build) (64-bit)
40b532ccf3bc15f40c6165989b143955260b872c
Windows 11 Version 23H2 (Build 22631.2338)

**Comment by raj23689** [comment] 2023-10-07 09:40
Console logs are interesting, looks really really nasty to untangle. I'm guessing they've got a new video server that you actually `POST` a request to, with loads and loads of query parameters, and it serves you back a chunk. I don't see immediately see anything in the `qstring` that looks like it's differentiating ad and non-ad chunks.

**Comment by d9j** [comment] 2023-10-07 10:13
Same happens with Mac. latest brave version. ads not playing but significantly delaying  start of video play

**Comment by owliatian** [comment] 2023-10-07 11:34
Same on Win10, looks like UBO doesn't have this issue but will return a adblocker warning popup. 

1.58.137 Chromium: 117.0.5938.153 (Official Build) (64-bit)
40b532ccf3bc15f40c6165989b143955260b872c
Windows 10 Version 22H2 (Build 19045.3516)
JavaScript	V8 11.7.439.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by edt-xx** [comment] 2023-10-07 17:36
Also happening on linux with the same symptoms.

**Comment by PythonicBoat** [comment] 2023-10-11 09:46
## Youtube is forcing us to disable Ad-blocker on videos

<html>
<body>


Brave | 1.58.137 Chromium: 117.0.5938.153 (Official Build) (64-bit)
-- | --
Revision | 40b532ccf3bc15f40c6165989b143955260b872c
OS | Windows 11 Version 22H2 (Build 22621.2361)
JavaScript | V8 11.7.439.21
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36


</body>
</html>

![image](https://github.com/brave/brave-browser/assets/68675629/2fb732a9-5f68-4805-81ba-505133b61bb6)

**Comment by bsclifton** [comment] 2023-10-11 17:52
Hi folks - we're definitely working through some of these actively

There were some good fixes pushed yesterday. You can force an update by either quitting Brave/relaunching OR going to brave://components and finding `Brave Ad Block Resources Library` and clicking `Check for update`. The current version (as of this comment) is `1.0.70` and things are working for me

Please let us know - I'll keep this open so we can continue triaging

**Comment by UndercoverNL** [comment] 2023-10-11 22:11
I can confirm too, even with the latest update, that YouTube does still "warn" you about using an ad blocker, it doesn't prevent you from using YouTube strangely enough, but it still knows. I never had issues with ads showing, apart from the banners which sometimes appear, but I don't mind that my self.

**Comment by d9j** [comment] 2023-10-13 02:19
i think youtube team very dedicated this time to end adblocking thing. so dont think brave can handle it in long term due to limited resources comparing to youtube

**Comment by Flam3z** [comment] 2023-10-14 18:47
update: youtube just got more strict with completely blocking the video player and you get 3 strikes until you are forced to turn off the adblocker.

**Comment by antonok-edm** [comment] 2023-10-14 19:47
YouTube is changing these often; we're doing our best to respond as quickly as possible.

If ads ever show up, I recommend trying these steps:

## HOW TO TEST THE LATEST FIXES:

1. Visit `brave://components`
2. Find the `Brave Ad Block Updater` entry and press `Check for update`
3. Find the `Brave Ad Block Resources Library` entry and press `Check for update`
4. **Force-refresh** any youtube pages you may have open using <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> (Windows, Linux) or <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> (macOS)

**Comment by bitGimmicks** [comment] 2023-10-14 20:00
hi all, especially @antonok-edm; visiting as my bug was closed as a duplicate - sorry about that, I searched for the issue but didn't bump into this one!
Antonok, answering your question here so we update the open issue. All my components are up-to-date (I installed the browser a day ago). Here's the full list for reference:

Components (21)
Brave Ad Block First Party Filters - Version: 1.0.39
Status - Component already up to date

Brave Local Data Updater - Version: 1.0.484
Status - Component already up to date

NTP Background Images - Version: 1.0.12
Status - Component already up to date

Brave Wallet data files - Version: 1.0.72
Status - Component already up to date

Fanboy's Mobile Notifications - Version: 1.0.1798
Status - Component already up to date

EasyList Cookie - Version: 1.0.1931
Status - Component already up to date

PKI Metadata - Version: 735
Status - Component already up to date

NTP Sponsored Images (US) - Version: 1.0.1385
Status - Component already up to date

Crowd Deny - Version: 2023.10.4.1147
Status - Component already up to date

Certificate Error Assistant - Version: 7
Status - Component already up to date

Brave Ad Block List Catalog - Version: 1.0.45
Status - Component already up to date

CRLSet - Version: 8298
Status - Component already up to date

Brave Ads Resources (US) - Version: 1.0.85
Status - Component already up to date

Brave Ad Block Updater - Version: 1.0.1663
Status - Component already up to date

Hyphenation - Version: 120.0.6046.0
Status - Component already up to date

Safety Tips - Version: 2999
Status - Component already up to date

File Type Policies - Version: 62
Status - Component already up to date

MEI Preload - Version: 1.0.7.1652906823
Status - Component already up to date

Brave Ad Block Resources Library - Version: 1.0.70
Status - Component already up to date

OnDeviceHeadSuggest - Version: 20230916.567854667.14
Status - Component already up to date

Brave HTTPS Everywhere Updater - Version: 1.0.168
Status - Component already up to date


Thank you!

**Comment by BartAgterbosch** [comment] 2023-10-15 19:45
Same, unfortunately... I haven't seen the 3 strikes yet, so far I've been able to close the popup, or in case of a white screen reload the page did the trick, but man is it ever annoying, I can't help but wonder if youtube is able to pick up on say pihole which uses adblock through dns, I know that there is a fork of pihole out there that is basically a local install. But with the downward spiral youtube has been going lately, especially with that new CEO, I can't help but wonder if brave might have to change its' method of adblocking, I wonder how revanced is doing it, since I haven't had a single popup on there, ad, or any issue whatsoever

**Comment by Ticks-mentracorps-menti-TEMP** [comment] 2023-10-16 18:02
@BartAgterbosch You shouldn't use DNS adblocking with Brave, Brave already has a powerful adblocker that can see each network request and inject and modify scripts and HTML nodes and all that.
DNS adblocking only can see domains and subdomains and nothing else, DNS adblocking can also mess with Brave/uBlock $redirect and $redirect-rule feature.

You have to go to brave://settings/security and change the DNS there, so any other app in your device will not stop using pihole or whatever you want to use. 

DNS adblocking is primitive and terrible, but it is fine for apps, not a browser.

For anyone else:

1. Set the adblocker to Aggressive, I know Brave Team is stubborn in keeping the Standard / Default mode, but that's sometimes problematic to remove ads or apply cosmetics to pages that hide annoyances or ads.

2. Even unlogged accounts are getting the notice, but they can't block anyone, either, watch videos unlogged or see if clearing Youtube's data and re-log fixes the issue. I don't believe they can block accounts server side, because it would cause them to be in trouble if they start blocking people who are not even using Adblockers, so I believe everything is client side to 'scare you', just like with unlogged people.

3. Brave uses uBlock and Easylists, and they should work 100% in Youtube, there are millions of users using them and list maintainers are working to see how to bypass this. uBlock, Easylist and Brave, so if it doesn't work in Brave, it won't work in uBlock, seems like there is no too much issues with these notices though. As long as Youtube doesn't go the Amazon route of embedding the ads and now they are harder to block without using a proxies to connect to random places where Twitch ads haven't been implemented, then it should be fixed someday.
   Google is still an ad company and they are protecting their business, but Filter List maintainers are working on it, and Brave will get fixed quickly thanks to using uBlock lists.

**Comment by ryanbr** [comment] 2023-10-18 08:33
We've had some reports that everything is better now,  DNS blocking may cause issue, So test with shields only.

**Comment by Syzuna** [comment] 2023-10-18 22:30
It was gone for most of the day for me but now I got the 3 videos warning that I never had before

**Comment by ryanbr** [comment] 2023-10-18 23:58
Yeah, we're still working on it. May get the black pre-roll loading screen now

**Comment by yongjer** [comment] 2023-10-19 14:01
The built-in adblock is supposed to be the reason for people using Brave, but it appears to lack in quality. 
In my use of Edge, I installed the ublock origin extension, which still serves its purpose. It may be because more people use the extension that they fix any bugs quicker. Therefore, why not integrate this type of extension and abandon the adblock currently in use?

**Comment by Alino** [comment] 2023-10-20 04:40
today I run into issues with a notification popup on every video on youtube telling me to disable ad-blocking.
I was able to get rid of this annoying popup with adding this custom filter

```
www.youtube.com##^tp-yt-paper-dialog
```

<img width="717" alt="image" src="https://github.com/brave/brave-browser/assets/763194/e4b6e357-d190-48c7-8d74-3f749ee978c5">

**Comment by antonok-edm** [comment] 2023-10-20 04:51
Some users are having issues on YouTube related to having third-party extensions installed. For anyone still facing issues, I recommend trying with extensions disabled, at least to narrow down the cause.

**Comment by ksajan** [comment] 2023-10-22 04:18
I had to disable the tracker and ads blocking to use YouTube finally. Some extensions are also behaving weirdly such as "Enhance for YouTube".

**Comment by abhi-glitchhg** [comment] 2023-10-23 16:23
> today I run into issues with a notification popup on every video on youtube telling me to disable ad-blocking. I was able to get rid of this annoying popup with adding this custom filter
> 
> ```
> www.youtube.com##^tp-yt-paper-dialog
> ```
> 
> <img alt="image" width="717" src="https://user-images.githubusercontent.com/763194/276822532-e4b6e357-d190-48c7-8d74-3f749ee978c5.png">

Super helpful! 

Thanks

**Comment by body20002** [comment] 2023-10-23 17:31
> I had to disable the tracker and ads blocking to use YouTube finally. Some extensions are also behaving weirdly such as "Enhance for YouTube".

Enhance for youtube not working with the lateset youtube changes and it trigger the youtube anti ad-block disabling it fixes the problem :/
I didn't disable the tracker or ad block in brave it just work.

**Comment by LordAlu** [comment] 2023-10-24 16:33
> Enhance for youtube not working with the lateset youtube changes and it trigger the youtube anti ad-block disabling it fixes the problem :/ I didn't disable the tracker or ad block in brave it just work.

I would also like to confirm that disabling "Enhancer for YouTube™" stopped the YouTube Adblock pop-up which had been occurring even with Shields disabled in Brave. Brave is now correctly dealing for me with YouTube no longer showing the Adblock pop-up.

**Comment by abhi-glitchhg** [comment] 2023-10-24 16:38
Same

**Comment by Syzuna** [comment] 2023-10-26 17:31
I get more and more black screen ads. means no video for the ads but the sounds still comes through tho.

**Comment by bsclifton** [comment] 2023-12-12 21:00
Closing as fixed - the adblock rules have been updated for most cases. In some cases, you may need to exit Brave/relaunch or visit brave://components and manually update the Brave Ad Blocker components

@ryanbr can help advise for other cases - but I think clearing cookies/cache for youtube.com also helps in some cases

**Closed by bsclifton** 2023-12-12 21:00 UTC
Labels: feature/shields/adblock, OS/Android, OS/Desktop

**Comment by Mark-AAAA** [comment] 2024-03-31 19:46
Every YouTube ad goes through today !!!

**Comment by nd3w** [comment] 2024-05-03 07:44
I had this experience today. There are two ads, and while I see only black screens, the titles tell me that they're ads. After the ads, the video would start.
