### ISSUE TITLE
[Android] Unable to remove Sync on Android device

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9483] opened 2020-04-27 07:48 UTC
## Description 
Unable to remove Sync on Android device

## Steps to reproduce 

   1. Clean install 1.7.102
   2. Create a standalone sync chain on the device
   3. Try to remove sync chain doesn't work

## Actual result 
https://youtu.be/YFkACXos-5o

## Expected result
Should be able to remove standalone sync chain 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.7.102. This is a regression from 1.5.9. Hasn't worked from the first release on android-core

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by AlexeyBarabash** [comment] 2020-08-11 18:30
This is for sync v1, so for 1.7.x...1.11.x this will not be fixed.

Sync v2 also has such issue - device can only remove itself from the chain when doing reset - but for now this is expected.

**Comment by AlexeyBarabash** [comment] 2020-11-20 17:00
I cannot reproduce the issue today.
Seems it was fixed on some PRs.

@srirambv could you please re-check this issue?

**Comment by bsclifton** [comment] 2021-01-13 19:42
Fixed after moving to Sync v2

**Closed by bsclifton** 2021-01-13 19:42 UTC
Labels: OS/Android, QA/Yes, bug, feature/sync, regression
