### ISSUE TITLE
Brave News - outline on source (hover) overlaps text

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#20305] opened 2022-01-03 16:15 UTC
## Description 
When mousing over the name of a source in Brave News on Desktop, the border added (for mouseover) sometimes cuts into the text for when the story was published

## Steps to Reproduce

   1. Open a new tab
   2. Scroll down; enable Brave News
   3. Scroll through news stories
   4. Use the mouse to hover over the source name

## Actual result:
![image](https://user-images.githubusercontent.com/4733304/147952261-d9ed8fbc-2685-4bc7-9001-4f09a696126a.png)
![image](https://user-images.githubusercontent.com/4733304/147952309-8cc12979-a4d2-4d91-9e41-a712da03712c.png)

## Expected result:
Spacing should be enough that it doesn't cut into any fields
![image](https://user-images.githubusercontent.com/4733304/147952392-59d2eb7e-1573-43b4-a5a9-435ac5f40f6c.png)

## Reproduces how often: 
Depends on the sources; but easy enough to reproduce all the time

## Brave version (brave://version info)
<html>
<body>

Brave | 1.36.9 Chromium: 97.0.4692.56 (Official Build) nightly (64-bit)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Windows 10 Version 21H2 (Build 19044.1415)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? y
- Can you reproduce this issue with the beta channel? y
- Can you reproduce this issue with the nightly channel? y

**Comment by bsclifton** [comment] 2022-01-03 16:23
Per @petemill:
> It's semi-intentional until we have a better idea from design

**Comment by srirambv** [comment] 2022-01-04 04:56
Dupe of #14195

**Closed by srirambv** 2022-01-04 04:56 UTC
Labels: bug, design/needs-mock-up, OS/Desktop, feature/brave-news
