### ISSUE TITLE
Option for Multiple Rows of Tabs

### ISSUE THREAD

**Issue by popcornrulez** [brave/brave-browser#2767] opened 2018-12-31 18:43 UTC
## Description 
There is currently no support for multiple rows of tabs, which is a necessity for some people, including me. What happens when I'm browsing is that I open so many tabs that they get squished together to the point where some of the website icons don't show. Either adding support for multiple rows or adding support for a customizable fixed tab width with different "sections" that you can switch between (like with Muon).

## Steps to Reproduce

   1. Open a bunch of tabs in one window.

## Actual result:
![too many visible tabs](https://user-images.githubusercontent.com/1144106/50565743-c2b27f00-0ce6-11e9-9a96-a70b892a7810.png)

## Expected result:
Either something like how Muon handled tabs or multiple rows of tabs.

## Reproduces how often: 
Intermittent issue

## Brave version (brave://version info)
>Brave: 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)
>Revision: 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
>OS: Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
Yes

### Additional Information
NA

**Comment by srirambv** [comment] 2019-01-01 04:47
This should be fixed when  #35 is implemented to have tab pages similar to muon. Closing this as dupe of  #35

**Closed by srirambv** 2019-01-01 04:47 UTC
