### ISSUE TITLE
Create Brave-specific favicons for relevant brave:// pages

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#1820] opened 2018-10-24 17:58 UTC
We should create new favicons (most obviously visible in tabs, but also potentially in bookmarks, etc) for pages like: 

-- Rewards (currently a generic document icon)
-- Settings (currently the Chrome-default icon) 

I assume there are others. 

It looks like we already have such an icon for brave://welcome, which is great.

**Comment by srirambv** [comment] 2018-10-24 18:00
Dupe of https://github.com/brave/brave-browser/issues/1466

**Closed by srirambv** 2018-10-24 18:00 UTC
