### ISSUE TITLE
High Cpu usage in private window

### ISSUE THREAD

**Issue by JuliusBairaktaris** [brave/brave-browser#18961] opened 2021-10-23 13:54 UTC
## Description 

Extremely high cpu usage in private windows. Brave Nightly v1.33.29

## Steps to Reproduce

   1. Open a private window
   2. 
   3. 

## Actual result:

![image](https://user-images.githubusercontent.com/33199500/138559255-4fb02e3b-302c-4ab9-9a42-e205b252cd76.png)
![Uploading image.png…]()

## Reproduces how often: 

I cant reproduce the problem on my Desktop just my laptop. Both are running Windows 11 

## Brave version (brave://version info)

Brave Nightly v1.33.29

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

Only in nightly. 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

None of the above

**Comment by nate077** [comment] 2021-10-29 18:02
I reproduced this on beta 1.32.84 and 1.32.86

before the issue 1% cpu after 60-100% cpu, have all extensions disabled and it happens with any tab open, whether it's settings, private tab, normal tab etc

![123](https://user-images.githubusercontent.com/93401113/139481149-46f6704d-af3b-4b1c-9b3d-916ddbc77f35.jpg)

![1234](https://user-images.githubusercontent.com/93401113/139481160-a8158363-6a5a-4707-9371-29ab073a5bc1.jpg)

**Comment by scant271** [comment] 2021-10-30 12:22
I tested the Linux releases below and confirmed that the problem started in 1.33.24.

Maybe investigate these commits:  [https://github.com/brave/brave-core/commits/v1.33.24](url)

Version 1.33.20 Chromium: 95.0.4638.54 (Official Build) nightly (64-bit)  OK
Version 1.33.21 Chromium: 95.0.4638.54 (Official Build) nightly (64-bit)  OK
Version 1.33.22 Chromium: 95.0.4638.54 (Official Build) nightly (64-bit)  OK
Version 1.33.23 Chromium: 95.0.4638.54 (Official Build) nightly (64-bit)  OK
Version 1.33.24 Chromium: 95.0.4638.54 (Official Build) nightly (64-bit)  FAIL

**Comment by jek6094** [comment] 2021-10-30 14:20
It seems to be the wallet functionality. If I disable the brave://flags/#native-brave-wallet experimental flag, it doesn't happen!

**Comment by mixed-source** [comment] 2021-10-30 16:04
@ryanbr I have tried Nightly v1.33.2 and it's working well.

**Comment by mixed-source** [comment] 2021-10-30 16:07
@jek6094 This solution works well for me.
@ryanbr You might want to look into his solution.

**Comment by scant271** [comment] 2021-10-30 17:46
This issue appears to be resolved in **Version 1.33.22 Chromium: 95.0.4638.54 (Official Build) nightly (64-bit)**

I went to disable that flag but saw that the issue was gone before I did.

Thanks to ever fixed it and thanks @jek6094 for pointing out that flag.  I may disable this feature that I don't use.

**Comment by nihj09** [comment] 2021-10-31 10:04
I use Macbook Pro 2016 with Version 1.33.46 Chromium: 95.0.4638.69 (Official Build) nightly (x86_64) and disabling wallet flag per @jek6094 works for me. Even though I had "Default cryptocurrency wallet" set to Disabled in preferences, the flag had to be disabled for Private Windows to work normally.

**Comment by victorelec14** [comment] 2021-11-04 20:16
I have the same problem, the load goes up a lot when a private window is opened and without extensions.

> Version 1.32.91 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)

**Comment by bbondy** [comment] 2021-11-05 17:03
Taking a look, thanks for the report

**Comment by bbondy** [comment] 2021-11-05 18:05
root cause found, update will be out in a couple days, you can re-enable the flag if you want after that.

**Comment by HMaker** [comment] 2021-11-05 20:54
I can confirm that on Ubuntu 20.04 with Brave Nightly 1.33.50. CPU usage is 45% on a 6/12 CPU.

**Closed** 2021-11-06 19:39 UTC
Labels: priority/P1, perf, regression, OS/Desktop

**Comment by srirambv** [comment] 2021-11-10 10:11
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.95 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.282)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/10909>brave/brave-core#10909</a></li>
         <li>Verified no spike in CPU usage when a private tab is loaded </li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141093566-91a3e10e-5980-4eef-8808-13ef004d0c2f.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141093413-515464a5-037d-47af-884b-125c96dcb88f.png>
      </td>
      <td><img src=https://user-images.githubusercontent.com/17010094/141093067-3703bf63-7cbc-4fda-9890-f5d02bb3f247.png>
      </td>
   </tr>
</table>

**Comment by victorelec14** [comment] 2021-11-10 12:51
confirmed, the bug was fixed in the new version **1.32.95**

Thanks !

Windows 11  21H2
Version	10.0.22000 Build 22000


### Version 1.32.91 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)
![image](https://user-images.githubusercontent.com/543450/141115352-745579f5-00a6-48d8-ad6a-fc6c7c58648b.png)

![image](https://user-images.githubusercontent.com/543450/141115536-f5a18d35-8b68-466a-9588-d8555d9ea34a.png)


### Version 1.32.95 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)
![image](https://user-images.githubusercontent.com/543450/141116024-3a68a95c-51d3-4d72-93f5-5ccff796942e.png)

![image](https://user-images.githubusercontent.com/543450/141115988-804362bf-7414-4718-b579-5c589acb8685.png)
