### ISSUE TITLE
[UI/NIGHTLY] Nala icons have been replaced by the chromium ones

### ISSUE THREAD

**Issue by TheAresjej** [brave/brave-browser#38355] opened 2024-05-15 22:59 UTC
## Description 
Nala icons have been replaced by the default ones from chromium. 🙁

## Actual result:
Extensions icon (main UI)
<img width="52" alt="image" src="https://github.com/brave/brave-browser/assets/19390797/a8c9b547-7124-4354-b506-bde27ac22b6e">

Settings icon (extensions menu)
<img width="178" alt="image" src="https://github.com/brave/brave-browser/assets/19390797/74ec5405-3d90-44e4-9d57-779430003985">

Clear Browsing Data icon (brave://settings/privacy)
<img width="310" alt="image" src="https://github.com/brave/brave-browser/assets/19390797/6153af7d-4638-4bd6-ab0b-389bf3eed982">

## Expected result:
Icons should again use the Brave style.

## Brave version (brave://version info)
Version 1.68.19 Chromium: 125.0.6422.41 (Official Build) nightly (x86_64)

**Comment by bsclifton** [comment] 2024-05-16 18:50
cc: @fallaciousreasoning @zenparsing

**Comment by zenparsing** [comment] 2024-05-16 20:46
Likely due to https://chromium-review.googlesource.com/c/chromium/src/+/5444096. 

One solution would be to add an override to `leo_overrides.json` for `kExtensionChromeRefreshIcon`:

```
"//components/vector_icons/extension_chrome_refresh.icon": "leo_browser_extensions",
```

**Comment by rebron** [comment] 2024-05-16 21:31
@zenparsing Dupe of https://github.com/brave/brave-browser/issues/37583?

**Comment by bsclifton** [comment] 2024-05-20 20:30
@rebron yeah I think we can club it into that one. I'll close this out and put a note in https://github.com/brave/brave-browser/issues/37583

**Comment by sangwoo108** [comment] 2024-06-04 06:47
I think it'd be better to reopen this issue, as #37583 is about the new UI behind a flag while this regression is what we have now.

**Comment by sangwoo108** [comment] 2024-06-04 07:08
@aguscruiz , could you take a look at this? What were our icon for
* Extension icon toolbar
* Setting icon in the bubble
* Trash icon in settings/privacy?
(please refer to the issue description)

If we've never customized these, I think it's okay we can close this issue.

**Comment by aguscruiz** [comment] 2024-06-04 11:24
Hey, yes, our icons are:

- browser-extensions
- browser-extensions-remove (don't know if this one is needed, saw it once in Canary)
- browser-extensions-check (don't know if this one is needed, saw it once in Canary)
- settings
- trash

**Comment by sangwoo108** [comment] 2024-06-05 00:40
> browser-extensions-remove (don't know if this one is needed, saw it once in Canary)
> browser-extensions-check (don't know if this one is needed, saw it once in Canary)

FYI, There're icons shown when extensions are blocked and has access respectively. I guess we can replace them with ours.

**Closed** 2024-06-05 06:50 UTC
Labels: priority/P3, QA/Yes, release-notes/exclude, OS/Desktop

**Comment by stephendonner** [comment] 2024-06-11 22:09
## Verified `PASSED` using

```
Brave | 1.68.85 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | 8e76a669cf78bdfa933c8d569460092a01166588
OS | Windows 10 Version 22H2 (Build 19045.4474)
```

## `Dark` mode

`Extensions icon` | `Manage Extensions` | `Delete browsing data`
----------|---------|---------------------
![image](https://github.com/brave/brave-browser/assets/387249/be6f714d-2881-47a0-88c5-583f0770db09) | ![image](https://github.com/brave/brave-browser/assets/387249/914e2ec1-0704-42e6-aacb-551054a76bb8) | ![image](https://github.com/brave/brave-browser/assets/387249/1e3117a6-243a-49dc-a90f-f6b45d66f6c2)
