### ISSUE TITLE
Change `chrome://... says` to `brave://... says` in JavaScript popup boxes (`alert()`, `confirm()`, `prompt()`)

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#32060] opened 2023-08-03 15:02 UTC
Fixing this based on our conversation [here](https://bravesoftware.slack.com/archives/C8MP8ME4C/p1654135745228199) with @bridiver, @thypon, and @fmarier.

**Comment by bsclifton** [comment] 2024-02-05 04:43
Closing as a duplicate of https://github.com/brave/brave-browser/issues/32950

**Closed by bsclifton** 2024-02-05 04:43 UTC
Labels: QA/Yes, release-notes/exclude, OS/Android, OS/Desktop
