### ISSUE TITLE
[Desktop] copying/pasting images doesn't work

### ISSUE THREAD

**Issue by SanjayVyas** [brave/brave-browser#11084] opened 2020-08-04 19:15 UTC
## Description 
Copy image on a webpage does not work

## Steps to Reproduce
   1. Open a web page
   2. Right click on an image, select copy image
   3. Try to paste it elsewhere, there is nothing in the clipboard

## Version/Channel Information:

Brave | 1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.15.6 (Build 19G73)
JavaScript | V8 8.4.371.22

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel?

**Comment by rebron** [comment] 2020-08-07 21:20
@SanjayVyas Can you give us some more info? Do you have an example page and then also tell us what application you're pasting into. 

@kjozwiak I just tried this on 1.12.x, right clicked an image to copy image and pasted into Pages. So it looks like it works?

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.16 (Build 20A5343i)

**Comment by kjozwiak** [comment] 2020-10-07 08:17
Seems to be working for me as well. I tried the following:

* visited https://www.deviantart.com/djamilaknopf/art/This-Corner-of-the-World-833289821
* copied the image via the `Context Menu` --> `Copy Image`
* pasted it into the GH comment without any issues
* pasted it into a https://docs.google.com/document

Tried it with the following versions:

```

Brave | 1.17.18 Chromium: 86.0.4240.72 (Official Build) nightly (x86_64)
-- | --
Revision | 581582174c512f44f44fd1aea340471f54b2365f-refs/branch-heads/4240@{#1134}
OS | macOS Version 10.15.7 (Build 19H2)
```

```
Brave | 1.15.71 Chromium: 86.0.4240.72 (Official Build) (x86_64)
-- | --
Revision | 581582174c512f44f44fd1aea340471f54b2365f-refs/branch-heads/4240@{#1134}
OS | macOS Version 10.15.7 (Build 19H2)
```

@LaurenWags mind checking and see if it's working for you?

**Comment by LaurenWags** [comment] 2020-10-07 12:31
Works for me. Tried @kjozwiak steps from https://github.com/brave/brave-browser/issues/11084#issuecomment-704774092 and could not reproduce the issue from the description.

Used the below builds:

```
Brave | 1.15.71 Chromium: 86.0.4240.72 (Official Build) (x86_64)
-- | --
Revision | 581582174c512f44f44fd1aea340471f54b2365f-refs/branch-heads/4240@{#1134}
OS | macOS Version 10.14.6 (Build 18G3020)
```

```
Brave | 1.16.53 Chromium: 86.0.4240.68 (Official Build) beta (x86_64)
-- | --
Revision | ad72ee9aa8e15ed300df1238e76c7a8f4d686f97-refs/branch-heads/4240@{#1097}
OS | macOS Version 10.14.6 (Build 18G3020)
```

**Comment by kjozwiak** [comment] 2020-10-30 05:32
@SanjayVyas does the above work with the latest build which should be the following:

```
Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
```

**Comment by kjozwiak** [comment] 2021-01-04 17:32
Going to close this off as it seems like it's working for @LaurenWags @rebron and myself. I haven't seen any other reports internally nor from the community. @SanjayVyas if you're still experiencing the issue, please re-open or create a new issue 👍

If anyone runs into this, please ++ this issue so we know that users are still running into the above.

**Closed by kjozwiak** 2021-01-04 17:32 UTC
Labels: OS/Desktop, OS/macOS, bug, needs-investigation

**Comment by JimPix1** [comment] 2022-05-08 16:47
I have this problem as well and have had it for months on Linux, Other people have it too but the devs don't seem bothered about fixing it despite it being quite crucial to be able to copy/paste images
