### ISSUE TITLE
user wallets are not always correctly connecting to Uphold

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6768] opened 2019-11-05 14:57 UTC
## Description 
Sometimes after a user attempts to verify their wallet with Uphold it is not always correctly connected in BR. For example, UI in BR does not indicate that a KYC'd wallet is connected. 

## Steps to Reproduce
Unsure

## Actual result:
DM me for video, but basically user clicks on 'Verify Wallet' and is taken right to Uphold. UI in BR does not acknowledge that user has connected a verified/KYC'd wallet. Possibly similar to what is occurring in #6224 

## Expected result:
When verifying wallet with Uphold there should be no errors.

## Reproduces how often: 
no STR but has been reported occasionally

## Brave version (brave://version info)
various

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @mandar-brave @Brave-Matt

**Comment by NejcZdovc** [comment] 2020-04-10 07:26
closing as dupe of https://github.com/brave/brave-browser/issues/7961

**Closed by NejcZdovc** 2020-04-10 07:26 UTC
Labels: QA/Yes, bug, feature/rewards, needs-investigation
