### ISSUE TITLE
Firefox-like high refresh rate smooth tab opening and closing animation

### ISSUE THREAD

**Issue by MoeAmen** [brave/brave-browser#42376] opened 2024-11-19 17:58 UTC
### Platforms

Windows, macOS, Linux

### Description

Firefox's animation for opening and closing tabs is very smooth, compared to Chromium browsers. Brave's version is close, but not buttery smooth like how Firefox's version looks like. The animation looks very good on high refresh rate monitors, and wish that something like that animation could be implemented here.

**Comment by rebron** [comment] 2024-11-20 04:28
@MoeAmen Can you post a video of what you're requesting? Otherwise, your description is not specific enough for us to take action.

**Comment by rebron** [comment] 2024-11-20 19:46
Closing as dupe of https://github.com/brave/brave-browser/issues/42288

**Closed by rebron** 2024-11-20 19:46 UTC
Labels: feature-request
