### ISSUE TITLE
Feature request: button or shortcut for Distil Page

### ISSUE THREAD

**Issue by jon-shipley** [brave/brave-browser#7719] opened 2020-01-14 14:47 UTC
## Description 

Feature request: Shortcut or button to toggle 'Distil Page'

## Steps to Reproduce

Instead of clicking the menu on the RHS (3 horizontal lines), and then selecting "Distil Page" it would be nice if we could have an immediately single button to do (as on Safari)  or a keyboard shortcut.

## Brave version (brave://version info)

1.2.42+

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by rebron** [comment] 2020-02-28 17:41
Closing. Duplicate of #8372

**Closed by rebron** 2020-02-28 17:41 UTC
Labels: duplicate
