### ISSUE TITLE
Bookmarks tool bar doesn't go off in New Private Window

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#1919] opened 2018-10-31 07:04 UTC
Have you searched for similar issues? Yes.

## Description 
Bookmarks tool bar doesn't go off in New Private Windows. It is already ticked in settings and as you try to un-check it from the context menu, it just creates a tiny horizontal space in between tabs and the toolbar.

## Brave version (brave://version info)
Built 0.56.6 Chromium: 70.0.3538.67 (Official Build) beta (64-bit) from x86_64.rpm on OpenSuse

**Comment by srirambv** [comment] 2018-10-31 11:54
Dupe of #1306. Private windows have the same behaviour as normal windows. Once #1306 is implemented it should reflect on Private windows as well.

**Closed by srirambv** 2018-10-31 11:54 UTC
