### ISSUE TITLE
autoPlay stays on 'Allow' when changed to 'Block'

### ISSUE THREAD

**Issue by stortzm** [brave/brave-browser#7563] opened 2020-01-01 19:45 UTC
## Description 

'YouTube' autoPlay does not set to 'Block' on siteSettings

## Steps to Reproduce

   1. attempt to set siteSettings on youtube.com/ autoPlay set to Block
https://i.ibb.co/nRVwSXV/Sem-t-tulo.jpg
   2. the Block setting never stays on, it automatically switches to Allow

## Actual result:

https://i.ibb.co/nRVwSXV/Sem-t-tulo.jpg

## Expected result:
Block should be set; Instead, Allow stays on

## Brave version (brave://version info)

Brave | 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Windows 7 Service Pack 1 (Build 7601.24533)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

NA
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

NA
## Miscellaneous Information:

NA

**Comment by srirambv** [comment] 2020-01-02 12:58
Dupe of #3138. Added a +1 there

**Closed by srirambv** 2020-01-02 12:58 UTC
