### ISSUE TITLE
[Android] Sync setup doesn't complete until the app is quit and relaunched

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11075] opened 2020-08-04 14:01 UTC
## Description 
 Sync setup doesn't complete until app is quit and relaunched

## Steps to reproduce 

   1. Setup sync chain offline
   2. Bring device online sync setup doesn't complete
   3. Quit and relaunch the browser, setup completes instantly

## Actual result 
Sync setup doesn't complete until the app is quit and relaunched

## Expected result
Should complete setup when the device is online 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.14.10 x64 nightly build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by AlexeyBarabash** [comment] 2020-08-11 20:02
I can reproduce this issue.

**Comment by AlexeyBarabash** [comment] 2020-08-11 20:08
... when I went to another issue I found device list is filled with the current device so sync chain is created. We should wait ~ 1 minute in this case. 
So @srirambv could you try to test it again, with extra step 2.5 wait 1 minute and expect sync is online?

**Comment by AlexeyBarabash** [comment] 2020-11-20 15:54
I cannot reproduce the issue today, after waiting a while (~30 sec) after enabling - I was able to see the device list.
Seems it is related to server polling interval change.

@srirambv could you please re-test this?

**Comment by AlexeyBarabash** [comment] 2023-01-09 19:46
I can't reproduce, maybe some upstream change had fixed it.

**Comment by AlexeyBarabash** [comment] 2023-02-01 19:46
Closing.
Confirmed with @srirambv  in DM 
> can be closed. Can't repro any more

**Closed by AlexeyBarabash** 2023-02-01 19:46 UTC
Labels: bug, feature/sync, priority/P5, QA/Yes, release-notes/exclude, OS/Android
