### ISSUE TITLE
Issue: wallet not showing verified when verified wallet connected

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#5588] opened 2019-08-08 05:54 UTC
see image ---
![image](https://user-images.githubusercontent.com/35932307/62678297-f84ad500-b965-11e9-97be-676c3f673fb5.png)

STR:
1) try connecting one Uphold wallet and connect it (used an unverified wallet)
1) BR wallet panel shows verify wallet (this is OK)
3) Logout of that wallet from the Uphold site
4) try verifying wallet - this time use a verified wallet
5) Redirect never comes back to the BR page
6) Wallet continues to show "Verify wallet" -- tried 6 times with the same result (never redirected back and always showed incorrect status on BR panel)

This needs to be fixed in the 0.69.x timeframe
@NejcZdovc

**Comment by mandar-brave** [comment] 2019-08-08 06:59
This is on nightly V70.34
Not reproducing on latest developer V69.100

**Comment by NejcZdovc** [comment] 2019-08-08 11:32
logout on uphold will not disconnect wallet

**Comment by NejcZdovc** [comment] 2019-08-19 04:53
closing as @mandar-brave can't reproduce it anymore

**Closed by NejcZdovc** 2019-08-19 04:53 UTC
Labels: feature/rewards, need-more-info
