### ISSUE TITLE
[Desktop] Small rectangle overlaps top scrollbar arrow in settings

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#10205] opened 2020-06-10 13:52 UTC
The rectangle is not clickable thus makes using the top scrollbar arrow harder.

## Steps to Reproduce

   1. Open `brave://settings`
   2. Observe the top scrollbar arrow

Note: The rectangle is best visible in dark theme

## Actual result:

small rectangle overlaps top scrollbar arrow in settings.
The rectangle blocks click events.

![image](https://user-images.githubusercontent.com/34715963/84276211-5d48fb80-ab32-11ea-845a-9e76fa89ee0d.png)

![image](https://user-images.githubusercontent.com/34715963/84275992-15c26f80-ab32-11ea-877f-c27c6ff4ac31.png)

## Expected result:
small rectangle does not overlap top scrollbar arrow in settings.
Top scrollbar arrow is fully clickable

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.9.80 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.10.87 Chromium: 83.0.4103.61 (Official Build) (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | Ubuntu 18.04 LTS

Brave | 1.12.14 Chromium: 83.0.4103.97 (Official Build) nightly (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | Ubuntu 18.04 LTS

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

cc @brave/legacy_qa @rebron @bsclifton @mkarolin @simonhong

**Comment by bsclifton** [comment] 2020-06-12 07:33
Duplicate of https://github.com/brave/brave-browser/issues/8365

**Closed by bsclifton** 2020-06-12 07:33 UTC
Labels: OS/Desktop, QA/Test-Plan-Specified, QA/Yes, bug, feature/settings
