### ISSUE TITLE
Black box in Settings 

### ISSUE THREAD

**Issue by aaronsantamaria** [brave/brave-browser#9539] opened 2020-04-29 21:56 UTC
## Description 

Report from reddit.  https://old.reddit.com/r/brave_browser/comments/g9h4il/when_i_open_settings_of_brave_browser_there_is_a/

cc @petemill 

## Steps to Reproduce

   1. go to settings
   2. see box at the top of scroll bar
   3. 

## Actual result:
![image](https://user-images.githubusercontent.com/33031530/80650648-fcf67280-8a39-11ea-91af-00560f73bb62.png)

**Comment by rebron** [comment] 2020-05-06 23:31
Duplicate of #8365

**Closed by rebron** 2020-05-06 23:31 UTC
Labels: design
