### ISSUE TITLE
Startpage SE is missing from search onboarding

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#12498] opened 2020-11-03 16:49 UTC
## Description 
Startpage SE is missing from the list of SEs in search onboarding.  

## Actual result 
Don't have startpage SE in the list

## Expected result
Should have startpage SE in the list of SEs

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment] 2020-11-03 16:59
@deeppandya duplicate of https://github.com/brave/brave-browser/issues/12340?

**Comment by deeppandya** [comment] 2020-11-03 17:09
> @deeppandya duplicate of #12340?

oh yes @kjozwiak it's duplicate. i will add that issue as well in the PR. so that we can close both issues.

**Closed** 2020-11-03 19:25 UTC
Labels: OS/Android, QA/Yes, release-notes/exclude
