### ISSUE TITLE
Mute button in tab broken in Release (v0.57.18) build

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#2407] opened 2018-12-07 19:39 UTC
## Description 

The mute button that appears on the tab when audio is playing no longer works after Release update to v0.57.18
Button doesn't work on Beta or Dev builds either.

## Steps to Reproduce

   1. Visit YouTube (or any site that plays audio)
   2. Stream or play a video or music file with sound
   3.  Try to click the mute button located on/off 

## Actual result:

Nothing happens

## Expected result:
Tab/page is muted when clicked

## Reproduces how often: 

Easily/always

## Brave version (brave://version info)

Release Build v0.57.18
Beta build v0.57.8
Developer build v0.59.2
### Reproducible on current release: Yes
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Is the issue reproducible on the latest version of Chrome? Yes

### Additional Information

The mute button doesn't work in Chrome either after the last update. Likely a chromium issue that came with update.

**Comment by DarkDibblez** [comment] 2019-03-06 10:36
+1

**Comment by stefonarch** [comment] 2019-04-14 18:09
+1 on arch linux   
0.62.51 
Chromium: 73.0.3683.103

**Comment by bsclifton** [comment] 2019-06-25 00:12
Closing as duplicate of https://github.com/brave/brave-browser/issues/2025

**Closed by bsclifton** 2019-06-25 00:12 UTC
