### ISSUE TITLE
Clicking on `Restore account? Import using account seed phrase` does nothing

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#7537] opened 2019-12-30 05:56 UTC
## Description 
Reported by @CMEONE [here](https://github.com/brave/brave-browser/issues/5682#issuecomment-557766687) and @paulwaldmann [here](https://github.com/brave/brave-browser/issues/5682#issuecomment-569503394), it seems even with the latest version of Brave (`1.1.23`) this is still a problem

## Steps to Reproduce
See below report 😄

**Comment by paulwaldmann** [comment] 2019-12-30 06:15
## Description
Returning to brave://wallet can't use "import using account seed phrase"

## Steps to Reproduce
1. Go to brave://wallet
2. Close browser and go back to brave://wallet (so you're logged out and see Welcome Back! screen)
3. Click "Import using account seed phrase"
4. Nothing happens, clicking the link has no effect.

Extra note: When I generated the new wallet, during the seed phrase retyping step, the browser crashed, and that's how I encountered the problem to begin with (step 2).
 
## Actual result:
![brave_wallet](https://user-images.githubusercontent.com/32001342/71570181-7d4dab00-2b0e-11ea-8b84-904dacccd0cb.png)

 ## Expected result:
It should take me to import flow.
 
## Brave version (brave://version)
Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) unknown (64-bit)

**Comment by ryanml** [comment] 2020-01-03 21:10
Fixed via: https://github.com/brave/devops/pull/2322 cc: @bsclifton

**Comment by ryanml** [comment] 2020-01-03 21:10
@paulwaldmann thanks for reporting! Restore flow should work correctly now.

**Comment by paulwaldmann** [comment] 2020-01-03 23:42
@ryanml anytime, love Brave and what it stands for!

**Comment by paulwaldmann** [comment] 2020-01-04 00:14
@ryanml when will the changes be pushed to the stable version? I see that the dev version has been updated but the stable 1.1.23 hasn't changed. Thanks.

**Comment by ryanml** [comment] 2020-01-04 00:15
@paulwaldmann there was a networking issue with our JSON RPC, no deployments needed. Are you still seeing the problem? If so, try relaunching Brave. Let me know how that works thank you!

**Comment by paulwaldmann** [comment] 2020-01-04 00:18
Restarted browser and laptop, the problem persists.

**Comment by ryanml** [comment] 2020-01-04 00:19
@paulwaldmann got it, apologies. I cannot reproduce but I will continue to look in to this issue.

**Comment by ryanml** [comment] 2020-01-04 00:20
It would be great if you could provide any errors you see in console, if there are any

**Comment by paulwaldmann** [comment] 2020-01-04 00:21
No errors in the console. I've already checked and would have posted it if there were any. If you want, You can join via AnyDesk and have a look by yourself.

**Comment by Kevmate** [comment] 2020-01-09 08:04
I am getting the same problem, using latest version. I was creating a wallet, wrote down my passphrase, then on the next screen where you have to select the words I found they were not all on the screen. I couldn't scroll, so I refreshed the page. The words disappeared. After that the page didn't work so I came out and went back in. Now I am asked for a password, which I can remember, but when I continue it just returns to the password prompt. Recovery using phrase also fails. I expect you could reproduce this. We need a way to delete corrupted wallets.

**Comment by ryanml** [comment] 2020-01-09 17:47
Hey folks cc: @Kevmate @paulwaldmann a reset feature is in the works, however, this workaround will suffice in the meantime. (Note this will completely reset everything to how it was the first time you used Crypto Wallets)

Navigate to your Application data directory for Brave, (on MacOS for example it is `/Users/your-username/Library/Application Support/BraveSoftware/Brave-Browser`). Inside that directory navigate to `Default/Local Extension Settings/odbfpeeihdkbihmopkbjmoonfanlbfcl` and delete the file `000003.log`. Now restart Brave completely, and navigate to `brave://wallet`. You should see the original welcome screen. (If you restart Brave with that tab open you may need to refresh the page once)

**Comment by Kevmate** [comment] 2020-01-10 11:43
Yes, thanks, that removed the corrupt wallet. I haven't created a new one yet, but the fault is cleared :)

**Comment by paulwaldmann** [comment] 2020-01-11 14:42
In `Default/Local Extension Settings/odbfpeeihdkbihmopkbjmoonfanlbfcl` there's only `000004.log`

and the `000003.log` i can find in 

```find . -name 000003.log
./gcbommkclmclpchllfjekcdonpmejbdp/000003.log
./mmeijimgabbpbgpdklnllpncmdofkcpn/000003.log
./aleakchihdccplidncghkekgioiakgal/000003.log
./jidkidbbcafjabdphckchenhfomhnfma/000003.log
./mnojpmjdmbbfmejpflffifhffcmidifd/000003.log
./hoklmmgfnpapgjgcpechhaamimifchmp/000003.log
./eimadpbcbfnmbkopoojfekhnkhdbieeh/000003.log```

Which one should I remove?

**Comment by dannuttall** [comment] 2020-01-14 12:54
I am also experiencing this issue. Steps I took to create the issue:

1. Clicked "create new wallet"
2. Created a password
3. Exited out of the process on the page that asks you to reveal the seed phrase as I wanted to import a wallet not create a brand new one
4. Now when I visit the wallet I am presented with the Welcome Back page, unable to log in or import  a wallet.

I notice when I try to login the following flashes up extremely briefly before returning to the Welcome Back page: 
![Capture](https://user-images.githubusercontent.com/25965241/72345844-950b5e80-36cc-11ea-9d0c-2015e0273091.PNG)

I have tried to fix by deleting the "odbfpeeihdkbihmopkbjmoonfanlbfcl" folder from inside C:\Users\username\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Local Extension Settings\, but doing so made no difference to the above behavior.

**Comment by ryanml** [comment] 2020-01-14 17:13
@dannuttall can you try deleting the file I mentioned above, closing the Crypto Wallets tab, and fully relaunching Brave?

Also @paulwaldmann and @dannuttall, would you both mind navigating to `brave://components` and sharing what version of `Crypto Wallets` you have? Thanks!

**Comment by ryanml** [comment] 2020-01-14 17:13
If you could show me what version you have before relaunching the browser that would be great, I am trying to determine if you have an older version for whatever reason.

**Comment by paulwaldmann** [comment] 2020-01-14 17:14
Crypto Wallets - Version: 1.0.15

**Comment by ryanml** [comment] 2020-01-14 17:16
@paulwaldmann thanks. And to be clear at this time you are still unable to create/import a wallet?

**Comment by paulwaldmann** [comment] 2020-01-14 17:18
Yes, but I also didn't remove any log file as you instructed as the log file in question did not exist.

**Comment by ryanml** [comment] 2020-01-14 17:21
@paulwaldmann, try deleting 000004.log, closing the open CW tab, and relaunching Brave

**Comment by ryanml** [comment] 2020-01-14 17:21
if this doesn’t work for either of you please follow up with me at rlanese at brave.com for further diagnosis.

**Comment by paulwaldmann** [comment] 2020-01-14 17:25
After removing the log file, and relaunching Brave, nothing changed. Same "Welcome Back!" screen, not possible to create a new wallet.

I will eventually just create a new profile if you can't fix it.

**Comment by dannuttall** [comment] 2020-01-14 19:00
OK I had to restart Brave by killing the process as closing the app doesn't actually close it fully. After doing this I'm allowed to create a new wallet again. However upon hitting create and being prompted to create a password, I get the error "KeyringController - No account found on keychain."

![Capture](https://user-images.githubusercontent.com/25965241/72373382-116b6500-3700-11ea-8945-ee41a0f2fbdd.PNG)

How do I fix this?

**Comment by ryanml** [comment] 2020-01-14 21:11
@dannuttall what OS are you running?

**Comment by dannuttall** [comment] 2020-01-14 21:18
Windows 10

**Comment by ryanml** [comment] 2020-01-14 22:36
@paulwaldmann @dannuttall thank you both for your patience. I've identified the issue and made a fix for account creation/import after reset, as well as fixing import pre reset. https://github.com/brave/ethereum-remote-client/pull/108

**Comment by ryanml** [comment] 2020-01-15 18:19
Reopening as it has not deployed yet

**Comment by bbondy** [comment] 2020-01-17 18:20
Let's close and move to the project's awaiting deployment column.

**Closed by bbondy** 2020-01-17 18:20 UTC
Labels: QA/Yes, feature/crypto-wallets, priority/P3, release-notes/include, support

**Comment by GitNasi** [comment] 2020-02-07 10:37
I have the same issue and cant fix it.
I have followed the steps deleting file  000003.log and restating Brave which led me to the 
"KeyringController - No account found on keychain." error while creating a new profile.
After this error I cant do anything but closing Brave again which leads me to the initial problem situation. "Welcome Back!" screen.

Brave is up to date
Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)

Windows 10

**Comment by srirambv** [comment] 2020-02-11 05:32
Verification passed on 

Brave | 1.6.14 Chromium: 80.0.3987.87 (Official Build) nightly (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.523)
Component | `0.1.42`

- Reproduced issue from https://github.com/brave/brave-browser/issues/7537#issuecomment-569593551 and https://github.com/brave/brave-browser/issues/7537#issuecomment-574160601 on current release component `1.0.15`
- Verified doing an upgrade based on those steps allows to login successfully or import another account using seed words
- Logged #8176 for missing backup seed phrase notification upon upgrade

**Comment by nonkreon** [comment] 2020-05-03 22:20
I am still stuck here indefinitely:

![image](https://user-images.githubusercontent.com/3709448/80927236-6a700f00-8d6a-11ea-921a-4aa0c8f52338.png)
This is Brave 1.8.86 on Windows 10 1809. Local extension settings folder looks like this (snapshot taken 6:19PM 

![image](https://user-images.githubusercontent.com/3709448/80927273-ac995080-8d6a-11ea-83e4-25b516985408.png)

**Comment by bsclifton** [comment] 2020-05-17 08:32
@NejcZdovc ^^

**Comment by NejcZdovc** [comment] 2020-05-17 15:00
@nonkreon could you please start browser like this. You can send me logs on nejc[at]brave.com. Thank you 

```
Open the windows command prompt
Change directory with a cd “C:\Program Files (x86)\BraveSoftware\Brave-Browse\Application”
Run the following: brave.exe --enable-logging=stderr --vmodule=*rewards*=6 --v=0 --log-level=1
Copy and paste logs from the command prompt
```

**Comment by nonkreon** [comment] 2020-05-17 18:25
> @nonkreon could you please start browser like this. You can send me logs on nejc[at]brave.com. Thank you
> 
> ```
> Open the windows command prompt
> Change directory with a cd “C:\Program Files (x86)\BraveSoftware\Brave-Browse\Application”
> Run the following: brave.exe --enable-logging=stderr --vmodule=*rewards*=6 --v=0 --log-level=1
> Copy and paste logs from the command prompt
> ```

Thank you for your help @bsclifton and @NejcZdovc , interestingly i got 3 separate log files out of these, i'm putting them all here.
Log0: https://pastebin.com/iuTFs836
Log1: https://pastebin.com/6gWf3hJW
Log2: https://pastebin.com/Wpu085WW
What kind of problem have i gotten myself into 😄

**Comment by nonkreon** [comment] 2020-06-21 21:23
> > @nonkreon could you please start browser like this. You can send me logs on nejc[at]brave.com. Thank you
> > ```
> > Open the windows command prompt
> > Change directory with a cd “C:\Program Files (x86)\BraveSoftware\Brave-Browse\Application”
> > Run the following: brave.exe --enable-logging=stderr --vmodule=*rewards*=6 --v=0 --log-level=1
> > Copy and paste logs from the command prompt
> > ```
> 
> Thank you for your help @bsclifton and @NejcZdovc , interestingly i got 3 separate log files out of these, i'm putting them all here.
> Log0: https://pastebin.com/iuTFs836
> Log1: https://pastebin.com/6gWf3hJW
> Log2: https://pastebin.com/Wpu085WW
> What kind of problem have i gotten myself into 😄

@NejcZdovc Brave updated today and it only asked to reauthorize my uphold, everything is set back up now. Thanks for the background fixes!

**Comment by NejcZdovc** [comment] 2020-06-22 04:33
@nonkreon great to hear that it was fixed for you
