### ISSUE TITLE
Impossible to disassociate browser theme from devtools theme

### ISSUE THREAD

**Issue by L0v3l4c3** [brave/brave-browser#19509] opened 2021-11-16 19:31 UTC
## Description 
Since today's stable channel release (2021-11-16) it is impossible to disassociate the developer tools theme from the browser theme.

## Steps to Reproduce
   1. Set the browser theme as "Dark".
   2. Open developer tools, change the developer tools theme to "Light".
   3. Reload the developer tools.

## Actual result:
The developer tools theme will remain "Dark".

## Expected result:
The developer tools theme should be "Light".

## Reproduces how often: 
Always, regardless of the chosen developer tools theme, it will always use the browser's theme instead.

## Brave version (brave://version info)
Brave | 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 21H1 (Build 19043.1288)

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel? Have not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? I do not know

**Comment by arfmach** [comment] 2021-11-18 00:53
The same occurs with the inverse color scheme: browser with light theme, devtools with dark theme - devtools restarts with light theme.

**Comment by jondcallahan** [comment] 2021-12-01 20:55
Chiming in to add that I am seeing this in Brave also, and that it is **not** reproducible in current Chrome

**Comment by bsclifton** [comment] 2022-03-18 07:58
Should be fixed with https://github.com/brave/brave-core/pull/12600 - duplicate of https://github.com/brave/brave-browser/issues/20491

**Closed by bsclifton** 2022-03-18 07:58 UTC
Labels: feature/dev-tools, priority/P5, OS/Desktop
