### ISSUE TITLE
Cannot set Brave as default browser Arch Linux

### ISSUE THREAD

**Issue by cndouglas** [brave/brave-browser#2377] opened 2018-12-05 20:54 UTC
Copied from brave/browser-laptop#15323 by @Kallestofeles

## Description 
Cannot set Brave as the default browser in Arch linux. Set as default option does nothing.
System:
Kernel: 4.19.4-zen1-1-zen x86_64 bits: 64
Desktop: Gnome 3.30.2
Distro: Arch Linux

## Steps to Reproduce

1. Install brave-bin or brave-dev-bin from the AUR
2. Run the Brave browser
3. Click on "Set as default" browser button
Rinse and repeat...

## Brave version (brave://version info)
Brave Version 0.56.15 Chromium: 70.0.3538.110 (Official Build) unknown (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Brave-Matt** [comment] 2018-12-06 18:39
+1 from Community:
https://community.brave.com/t/various-bugs-on-arch-or-manjaro-linux/38521/2

**Comment by helionmelion** [comment] 2018-12-08 13:17
manually workaround is

**Comment by Kallestofeles** [comment] 2018-12-10 13:36
Thanks but does not work.
![image](https://user-images.githubusercontent.com/3207177/49735853-1d7d2b80-fc91-11e8-8bb7-ffeaec5900ec.png)
The issue is not that Brave was not the default browser - it is! It handles all the requests as it should, however every time the browser gets opened, it shows this set as default message + set as default from the settings does not work. The issue essentially is only cosmetic but annoying as hell as it pops up every time the browser is opened.

**Comment by helionmelion** [comment] 2018-12-10 13:46
could you try this: 
**`xdg-settings set default-web-browser brave-bin.desktop`**
next query if the operation was successfull:
`xdg-settings check default-web-browser brave-bin.desktop`

**Comment by cavatron** [comment] 2018-12-10 19:38
`xdg-settings check default-web-browser brave.desktop` returns `yes` but Brave still shows it's not the default browser. `xdg-open` opens Brave as it should.

**Comment by helionmelion** [comment] 2018-12-10 21:18
tested here,
-setting other browser (for instance, opera) as default: `xdg-settings set default-web-browser opera.desktop`
-going back to brave: after setting brave as default browser by xdg-settings, the message appears, but closing it (x) does the trick, it does not pop up again.
**But if I click "make default" in brave settings, the pop up is called again.**
so, close the pop up by (x) and not clicking "set as default"

**Comment by tomlowenthal** [comment] 2018-12-12 19:41
I think that the next step in debugging this is working out how Arch is doing defaults/handlers differently from other distros so that we can detect and support that.

**Comment by aphelionz** [comment] 2018-12-21 14:43
Confirmed this is happening on KDE neon as well. I don't think this is an OS problem, rather a problem with how Brave is self-detecting if it's the default or not.

**Comment by ryanerwin** [comment] 2019-03-27 06:43
The erroneous "Set as Default" dialog is still happening on Arch.

> Brave: Version 0.61.51 Chromium: 73.0.3683.75 (Official Build) unknown (64-bit)
> Linux 5.0.4-arch1-1-ARCH #1 SMP PREEMPT Sat Mar 23 21:00:33 UTC 2019 x86_64 GNU/Linux

Brave is set as the default for .html, http and https, but the dialog still pops up...

**Comment by fmarier** [comment] 2019-04-24 14:28
What is the output of `ls -l /etc/alternatives/x-www-browser`?

Does making Brave the default using `update-alternatives --config x-www-browser` make the message go away?

**Comment by cavatron** [comment] 2019-04-24 14:34
@fmarier not sure Arch has `update-alternatives`. I believe that is a Debian-based thing

**Comment by fmarier** [comment] 2019-04-24 14:50
I also saw `update-alternatives` on Fedora and so I assumed it was a standard Linux thing. Though looking at it closer, while it exists on Fedora, there is no `/etc/alternatives/x-www-browser`.

So I think you're right, that last part looks like a Debian-specific thing.

**Comment by Pitasi** [comment] 2019-07-02 18:07
For the ones like me who manually set Brave as default but were tired of the popup at every startup: just click the X instead of "Set as default".

Took me almost a week to realize this :)

**Comment by kirk-baird** [comment] 2019-07-04 02:55
Similar to @helionmelion 
I had to set it manually using xdg
`xdg-settings set default-web-browser brave-bin.desktop`
Note `brave.desktop` did not work as I installed `brave-bin` from AUR.

If you want to see what is current the default browser in xdg use `xdg-settings get default-web-browser`

**Comment by helionmelion** [comment] 2019-07-04 10:39
> Similar to @helionmelion
> I had to set it manually using xdg
> `xdg-settings set default-web-browser brave-bin.desktop`
> Note `brave.desktop` did not work as I installed `brave-bin` from AUR.
> 
> If you want to see what is current the default browser in xdg use `xdg-settings get default-web-browser`

Yes I'm using the aur version now.
`xdg-settings get default-web-browser`
`brave-beta-bin.desktop`

**Comment by Valinwolf** [comment] 2019-07-25 22:51
I can confirm that this is still a problem in Arch with Gnome 3.32.2 and kernel 5.2.2-arch1-1-ARCH. I have set Brave as the default browser in the Gnome Control Center as well as run the following commands, without luck:
```
xdg-mime default brave-bin.desktop x-scheme-handler/http
xdg-mime default brave-bin.desktop x-scheme-handler/https
xdg-settings set default-web-browser brave-bin.desktop
```
Running `xdg-settings check default-web-browser brave-bin.desktop` returns `yes`
Running `xdg-settings get default-web-browser` returns `brave-bin.desktop`
Running `xdg-open "https://duckduckgo.com"` opens `https://duckduckgo.com` in Brave

Clicking `Make Default` in the settings or on the popup does not help.
Clicking the X on the popup does not disable the popup.

**Comment by Gilgames000** [comment] 2019-11-01 14:45
I tried to set `brave` as my default browser using `xdg-settings`
```
$ xdg-settings set default-web-browser brave.desktop
```
but Brave was still showing the pop-up, so after clicking on "Make default" I checked:
```
$ xdg-settings get default-web-browser
brave-browser.desktop
$ xdg-settings check default-web-browser brave-browser.desktop
no
```
So I thought, well maybe Brave is expecting the executable to be called `brave-browser` and not `brave` hence when I click on "Make default" it's setting the wrong entry? So I aliased `brave-browser` to `brave` in my `.bashrc`:

`alias brave-browser=brave`

opened Brave, clicked on "Make default". Logged out of my user and back in to check if it worked and the pop-up was gone!
Also now xdg-settings is showing
```
$ xdg-settings check default-web-browser brave-browser.desktop
yes
```

Hope this helps.

**Comment by fmarier** [comment] 2019-11-01 16:52
> ```
> alias brave-browser=brave
> ```

Interesting. I wonder whether that's something that the Brave maintainer in Arch could add to the package.

**Comment by badlydrawnface** [comment] 2019-11-14 15:44
I figured it out,

You need to set the HTML default application to Brave for the popup to stop appearing

(Tested with KDE only, on Arch Linux)
1. Create a blank HTML file
2. Go to Open With, then Other Application
3. Choose Brave, and click the "Remember Application" tick.
4. Open the file in Brave, there, the "Brave is not your Default Browser" bar stops showing.

**Comment by whezzel** [comment] 2019-11-14 16:10
You can also just click the 'x' instead of 'Set as Default' and the popup will stop appearing

**Comment by martin-varbanov96** [comment] 2020-05-27 12:56
Using sudo was the way I fixed it:
__________________
  517  sudo xdg-settings set default-web-browser brave.desktop
  518  brave http://archlinux.org/
__________________


Randomly tried all these, all of them failed:
__________________________________ 
502  xdg-settings set default-web-browser brave.desktop
  503  xdg-open http://archlinux.org/
  504  xdg-settings set default-web-browser brave.desktop
  505  xdg-open http://archlinux.org/
  507  xdg-settings set default-web-browser firefox.desktop
  508  xdg-open http://archlinux.org/
  509  xdg-open http://archlinux.org/
  510  xdg-mime default brave.desktop x-scheme-handler/http
  511  xdg-mime default brave.desktop x-scheme-handler/https
  512  xdg-open http://archlinux.org/
  513   xdg-settings set default-web-browser brave-bin.desktop
  514  xdg-open http://archlinux.org/
  515  brave http://archlinux.org/
  516  brave-bin http://archlinux.org/

**Comment by baptiste-dauphin** [comment] 2020-05-27 14:10
On Debian 9 x64 the `xdg-settings` don't even worked (even when outputing `0`).

To solve the problem I had to manually edit `~/.config/mimeapps.list`
It's dirty but it works !
```
[Default Applications]
x-scheme-handler/http=brave.desktop
x-scheme-handler/https=brave.desktop
...
```

**Comment by fmarier** [comment] 2020-09-11 23:31
Possible work-around for Arch Linux, courtesy of https://github.com/brave/brave-browser/issues/11032#issue-669481089:
```
ln -s ~/.config/mimeapps.list ~/.local/share/applications/mimeapps.list
```

**Comment by vinnyfs89** [comment] 2020-12-08 02:33
If are you using **Brave Nightly** follow this steps:

```sh
sudo xdg-mime default brave-browser-nightly.desktop x-scheme-handler/https
sudo xdg-mime default brave-browser-nightly.desktop x-scheme-handler/http
xdg-settings set default-web-browser brave-browser-nightly.desktop
```

Hope it helps 👍

**Comment by adriano-pinaffo** [comment] 2020-12-12 09:54
> I figured it out,
> 
> You need to set the HTML default application to Brave for the popup to stop appearing
> 
> (Tested with KDE only, on Arch Linux)
> 
> 1. Create a blank HTML file
> 2. Go to Open With, then Other Application
> 3. Choose Brave, and click the "Remember Application" tick.
> 4. Open the file in Brave, there, the "Brave is not your Default Browser" bar stops showing.

This worked for me on Arch with KDE, but instead I went to KDE system settings and set the html file association to brave there (it was Firefox).
PS.: I had tried all other possible combinations.
![Screenshot_20201212_105318](https://user-images.githubusercontent.com/28174227/101980809-6a24e400-3c68-11eb-826a-7515201d5947.png)

**Comment by FahriDevZ** [comment] 2021-03-01 11:00
I am using archlinux with xmonad, I install **brave-bin**.
I tried set default browser does not work because result `xdg-settings check default-web-browser <name>.desktop
` is `no`.

My solution, check the desktop entity name.

 ```shell
ls /usr/share/applications | grep brave
# my result is: brave-browser.desktop
```
if doest not exits, you can check in different location, see [here](https://wiki.archlinux.org/index.php/Desktop_entries#Application_entry).

After you know what desktop name, you can try set

 ```shell
xdg-settings set default-web-browser brave-browser.desktop
```

Check
 ```shell
xdg-settings check default-web-browser brave-browser.desktop
# this result must be a yes
```

**Comment by wknapik** [comment] 2021-03-23 20:26
# Arch documentation on default applications

https://wiki.archlinux.org/index.php/default_applications

# Brave .desktop filenames on Arch Linux

Choose a .desktop file corresponding to your [chosen package](https://aur.archlinux.org/packages/?O=0&K=brave+browser):
* brave-browser.desktop (brave, brave-bin)
* brave-browser-beta.desktop (brave-beta-bin)
* brave-browser-nightly.desktop (brave-nightly-bin)
* brave-browser-dev.desktop (brave-dev-bin)
* brave.desktop (brave-git)

# Set Brave as default browser

It should be noted that setting default applications on Linux is not as straightforward, as on other systems. This is the flip side of the variety of possible setups across Linux distributions and within each one.

Different software respects different ways of setting defaults, so YMMV, but `xdg-utils` should be the go-to package for the purpose and should cover most cases. Users of desktop environments, which may use their own mechanisms to set defaults, should consult the documentation for their specific DE.

To use the stable release of Brave as default (brave and brave-bin packages), execute the following: 
```shell
xdg-settings set default-web-browser brave-browser.desktop
xdg-mime default brave-browser.desktop x-scheme-handler/http
xdg-mime default brave-browser.desktop x-scheme-handler/https
```

This should be enough. If not, setting the BROWSER variable to `brave` may help in some cases.

Relying on xdg-utils [appears](https://chromium.googlesource.com/chromium/src/+/refs/heads/master/chrome/browser/shell_integration_linux.cc#62) to also be the approach in [Chromium and Brave](https://chromium.googlesource.com/chromium/src/+/refs/heads/master/chrome/browser/shell_integration_linux.cc#98).

# Debugging
```console
% xdg-settings get default-web-browser  
brave-browser.desktop
% xdg-settings check default-web-browser brave-browser.desktop
yes
% xdg-mime query default x-scheme-handler/http
brave-browser.desktop
% xdg-mime query default x-scheme-handler/https
brave-browser.desktop
% echo "$BROWSER"
brave
% grep brave ~/.config/mimeapps.list                   
text/html=brave-browser.desktop
x-scheme-handler/http=brave-browser.desktop
x-scheme-handler/https=brave-browser.desktop
x-scheme-handler/about=brave-browser.desktop
x-scheme-handler/unknown=brave-browser.desktop
%
```

# Final notes

If the above doesn't work for you, please include any relevant information about your setup - most notably the desktop environment/window manager and the Brave package.

**Comment by rebron** [comment] 2021-09-16 22:48
Closing due to the instructions provided in the last comment.

**Closed by rebron** 2021-09-16 22:48 UTC
Labels: priority/P5, needs-more-info, packaging, OS/Linux/arch
