### ISSUE TITLE
Rewards NTP widget needs state/design for non-ads regions

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6751] opened 2019-11-04 13:42 UTC
## Description 
Rewards NTP widget needs a design to reflect being in a non-ads region.

## Steps to Reproduce

   1. Be in a non-ads region with Rewards enabled
   2. Upgrade to version with NTP widget
   3. Look at NTP widget

Alternatively,
1. Clean profile in non-ads region
2. Enable BR
3. Look at NTP widget

## Actual result:
Be sad, your top number is 0.0 with no chance to grow
<img width="1181" alt="Screen Shot 2019-11-03 at 18 27 58" src="https://user-images.githubusercontent.com/28145373/68125029-a969f880-fede-11e9-8430-91f162c7ba60.png">

## Expected result:
Either have NTP widget reflect Ads not available (yet) in region or not show that information? Need design input.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.73.55 Chromium: 78.0.3904.87 (Official Build) nightly (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
cc @ryanml @bradleyrichter @mandar-brave @rebron

**Comment by ryanml** [comment] 2019-11-04 20:43
Closing as duplicate of: https://github.com/brave/brave-browser/issues/6759

**Closed by ryanml** 2019-11-04 20:43 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, design/needs-mock-up, feature/new-tab, feature/rewards
