### ISSUE TITLE
Restoring crypto wallet does not restore all Primary accounts

### ISSUE THREAD

**Issue by mattpascoe** [brave/brave-browser#20233] opened 2021-12-28 04:29 UTC
## Description 
I currently have several (6) accounts set up in my crypto wallet.  They are all listed under the "Primary crypto accounts" section and not the "Secondary accounts" section.  I had attempted to restore my wallet on another instance of Brave using my recovery phrase.  The restore worked but only restored the first account in the list and nothing else.  I was hoping and expected that they would all be restored.

I was of course able to add an account by providing its private key via the add account option on the new Brave instance.  It however shows up as a "Secondary account" on that browser.  As the secondary account notes "These accounts can be used with web 3 DApps, and can be shown in your portfolio. However, note that secondary accounts cannot be restored via recovery phrase from your primary account backup."  This seems to indicate that I really can not backup and restore all of my accounts.

Ultimately this seems as if there is at least an inconsistency on behavior here.  I'm not fully grasping everything going on to know for sure what really should be happening.  Its possible that this is simply just a wording issue with the description and I assumed the recovery phrase was getting me something more than it is intended to do.

## Steps to Reproduce

   1. Starting with the first Brave browser, ensure you have multiple accounts listed under the primary crypto accounts section
   2. Create a recovery phrase
   3.  Restore wallet on a second Brave browser using this recovery phrase
   4. You should find only the first entry in the primary account list is restored and none of the other "primary accounts" listed were restored.

## Actual result:

My actual result was the restored wallet on the new browser contained only one out of my 6 primary accounts.  Contrary to what it implies in the "back up now" dialog when producing a recovery phrase.

## Expected result:
Based on the wording under secondary accounts and my own desires on performing a backup of the primary accounts. I expected all accounts listed as primary to be restored using a recovery phrase on the second browser instance, and that since mine were not secondary accounts, that they would all be restored.

I'm finding it hard to believe there is no easy/secure way for me to backup and restore the entirety of the accounts in my wallet.  It seems I have to painfully go through the recovery phrase, then one by one add additional accounts using an exported private key, And then I also have to describe each one back to its descriptive name.  

None of this would even be possible if I had lost my initial browser instance and thought it would be fine because I had my backup recovery phrase to restore it with.  

## Reproduces how often: 
I've only tried it once, but it would seem pretty reproducible.

## Brave version (brave://version info)
Both browsers are Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (x86_64)

## Other Additional Information:
I note when importing secondary accounts, I have the option of using a JSON file.  Maybe there is a way that I'm missing that would allow me to do a more complete restore using a JSON export in some way?

**Comment by bbondy** [comment] 2022-01-01 23:38
Is this a duplicate of https://github.com/brave/brave-browser/issues/18104?

**Comment by bbondy** [comment] 2022-01-01 23:39
As for secondary accounts, that can't be done through seed word restore, but can be done through JSON importing. We're also tracking an issue to do that with the importer automatically.

**Comment by bbondy** [comment] 2022-01-04 17:38
Going to close this as a duplicate but admittedly this issue has more detail. It'll be linked from the main issue.

**Closed by bbondy** 2022-01-04 17:38 UTC
Labels: feature/wallet, OS/Desktop
