### ISSUE TITLE
site settings on local file

### ISSUE THREAD

**Issue by tsao-chi1** [brave/brave-browser#7085] opened 2019-11-25 13:35 UTC
## Description 

cannot remove site settings on local file
site settings on local file not working

## Steps to Reproduce

   1. block script
   2. open a file `file:///C:/Program%20Files/Racket/doc/index.html`
   3. `Always allow Javascript`
4. `Countinue blocking Javascript`

## Actual result:

cannot remove rule `file:///C:/Program%20Files/Racket/doc/index.html` 

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment] 2019-12-02 19:40
Closing as a dupe of https://github.com/brave/brave-browser/issues/6278

**Closed by bsclifton** 2019-12-02 19:40 UTC
