### ISSUE TITLE
Add the brave shields icon in brave PWA (feature request)

### ISSUE THREAD

**Issue by youssef20031** [brave/brave-browser#14886] opened 2021-03-23 09:02 UTC
## Description 
it would be handy to add the brave shields icon in PWAs

## Actual result:

![Screenshot 2021-03-23 105411](https://user-images.githubusercontent.com/43968405/112119577-2d9d4880-8bc6-11eb-95a4-a427b0c0209e.png)

## Expected result:
![Screenshot 2021-03-23 1](https://user-images.githubusercontent.com/43968405/112120611-1b6fda00-8bc7-11eb-8cca-ff9d55999a86.png)

**Comment by srirambv** [comment] 2021-03-23 11:07
Dupe of #7715

**Closed by srirambv** 2021-03-23 11:07 UTC
Labels: OS/Desktop
