### ISSUE TITLE
speechSyntesis API not supported?

### ISSUE THREAD

**Issue by dragGH102** [brave/brave-browser#3618] opened 2019-03-07 14:59 UTC
I found an extension I really need ( https://chrome.google.com/webstore/detail/speech-recognition-anywhe/kdnnmhpmcakdilnofmllgcigkibjonof ) but looks like it's not going to work in Brave due to lack of support for `speechSyntesis` which seems to be supported by Chromium but not Brave.

Is that correct? If yes, why?
I truly believe speech-to-text API support is necessary in a modern browser, taking into account for example people like me with RSI / shoulder pain which make it difficult to type for long time.

You can see the answer by the extension's developer  going to https://chrome.google.com/webstore/detail/speech-recognition-anywhe/kdnnmhpmcakdilnofmllgcigkibjonof -> `Support` tab. The question was asked with title `Not working In Brave`

Thanks in advance

**Comment by bsclifton** [comment] 2019-03-15 15:52
Closing as duplicate of https://github.com/brave/brave-browser/issues/2802

Subscribe there for updates 😄

**Closed by bsclifton** 2019-03-15 15:52 UTC

**Comment by uc-asv** [comment] 2020-11-19 03:52
Hi, I have also the same issue. Speech synthesis API is not working on the brave browser and working in all the other browser is there any solution for this?

**Comment by bsclifton** [comment] 2020-11-19 07:01
@uc-asv unfortunately, no solution (yet). You can subscribe to issue https://github.com/brave/brave-browser/issues/2802 for more information

**Comment by uc-asv** [comment] 2020-11-19 07:06
Our user has reported the issue in mac but it seems to working fine in windows brave browser (latest release). So is this issue is occurring in mac?

**Comment by bsclifton** [comment] 2020-11-19 07:15
It's very possible it's macOS only - do you mind sharing that in #2802? It may help us narrow it down

**Comment by jasonhargrove** [comment] 2021-02-18 04:28
Just tested on Windows 10 Pro and appears to not work

**Comment by cristiandiazperdomo** [comment] 2024-01-30 14:44
Wow seems like this won't be added.
