### ISSUE TITLE
Solana Transaction manager should consider "confirmed" blockhashes as valid

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#24345] opened 2022-07-29 22:18 UTC
Currently we only take "finalized" into account so this would cause problem for wallet adapter using confirmed latest blockhash in input Transaction.
https://github.com/solana-labs/wallet-adapter/issues/478#issuecomment-1199948784

**Comment by yrliou** [comment] 2022-08-01 18:44
<img width="307" alt="Screen Shot 2022-07-29 at 14 18 09" src="https://user-images.githubusercontent.com/4730197/182220684-86111f59-3384-4b83-bd45-2ded545d669e.png">

The error we were seeing is the transaction failed the preflight check when we issue sendTransaction RPC call, the reason to that is because we do not manually assign a value for `preflightCommitment` optional argument if dApp does not specify it via SendOptions. And the default commitment level will be finalized as specified by Solana documentation.
https://docs.solana.com/developing/clients/jsonrpc-api#sendtransaction
If dApp choose to use a specific commitment level, we currently assume they would pass the config via SendOptions which we will use when doing sendTransaction RPC calls.
For example, https://github.com/solana-labs/wallet-adapter/blob/fca0b52b3232b02964253e261af9486d6ba2e97f/packages/core/base/src/adapter.ts#L97-L98, we would expect the adapter in this case would set the SendOptions when the blockhash is coming from `connection.getLatestBlockhash('confirmed')).blockhash`.

**Comment by jordansexton** [comment] 2022-08-05 00:37
This can probably be closed with https://github.com/solana-labs/wallet-adapter/pull/501

**Comment by yrliou** [comment] 2022-08-05 00:49
Fixed by https://github.com/solana-labs/wallet-adapter/pull/501, for now we don't plan to change our behavior for only passing preflightCommitment to sendTransaction RPC call if dApp passes it through `SendOptions`, so closing this with the adapter end's fix.

**Closed by yrliou** 2022-08-05 00:49 UTC
Labels: OS/Android, OS/Desktop, feature/wallet/solana
