### ISSUE TITLE
Reformat version number in Software Update screen to match brave://settings/help and brave://version

### ISSUE THREAD

**Issue by isdn** [brave/brave-browser#13819] opened 2021-01-28 18:18 UTC
## Description 

Please see the following screenshot.

<img width="732" alt="Screen Shot 2021-01-28 at 21 45 12" src="https://user-images.githubusercontent.com/2445594/106180801-3a00b880-61b6-11eb-92cb-f8a380650434.png">

According to `brave://settings/help`, my current version is `Version 1.19.86 Chromium: 88.0.4324.96 (Official Build) (x86_64)` and the new version is `1.19.88`.

OS version: macOS Big Sur 11.1.

**Comment by bsclifton** [comment] 2021-01-28 20:07
Ran this by the release team - this unusual version `119.88` is expected; it's the Sparkle (updater used for macOS) "short version". It's concatenating the MAJOR + MINOR together unfortunately

**Comment by bsclifton** [comment] 2021-02-01 07:51
See https://github.com/brave/Sparkle/issues/14

**Comment by mherrmann** [comment] 2021-04-29 17:26
@bsclifton @mihaiplesa in light of #9562, should this issue be fixed at all? Should the fix not maybe be to get rid of the update popup entirely?

**Comment by mihaiplesa** [comment] 2021-04-29 18:28
Haven't checked newer Sparkle releases, but is there an option for that?

**Comment by mherrmann** [comment] 2021-04-30 05:58
Also after reading around a little, I'm not sure whether the popup appears because of a bug in Sparkle or because of a bug in Brave's sparkle integration.

In both cases, I don't think the popup should be shown when the user goes to `brave://settings/help`. After all, there already is visual feedback about the availability of an update on that page. Showing a popup on top of that does not make sense in my eyes.

However, there might be other cases where the popup is wanted. For example, maybe the popup should be shown if the user just keeps Brave open for weeks and should benefit from the update for security reasons.

Given that I already completed the work for this present issue in https://github.com/brave/brave-core/pull/8642 and https://github.com/brave/omaha-server-private/pull/64, I think my preference would be to get this done and leave #9562 as a follow-up. The changes in the two PRs make the implementation cleaner (in my opinion) in any case.

**Comment by mihaiplesa** [comment] 2021-05-10 17:45
@rebron thoughts - do we want pop-ups? Ideally we'd like to update in the background like on the other platforms.

**Comment by mherrmann** [comment] 2021-05-20 07:11
Can I briefly again ping you about this too @rebron?

**Comment by rebron** [comment] 2021-06-08 22:50
cc: @kliu

**Comment by rebron** [comment] 2021-06-11 16:01
@mherrmann We don't want to show the pop-up but let's go ahead and proceed with what you proposed. 

Merge the two PRs brave/brave-core#8642 and brave/omaha-server-private#64, leaving #9562 as a follow-up.

**Comment by kjozwiak** [comment] 2021-06-19 04:41
@brave/legacy_qa we'll need two RC's that have the above fix to verify this properly. You won't be able to update from `1.25.73` to the new RC. You need two builds that include the above fix. Example:

* install the `1.26.x RC1` pkg (includes the above fix)
* update to `1.26.x RC2` (includes the above fix)

**Comment by LaurenWags** [comment] 2021-06-21 13:04
Verified passed on `macOS x64 Catalina 10.15.7` with

```
Brave | 1.26.64 Chromium: 91.0.4472.114&nbsp;(Official Build)&nbsp;(x86_64)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS Version 10.15.7 (Build 19H1030)
```

Verified changes to version display on update popup.
Reproduced the issue using `1.25.73` --> `1.26.65` update.
Confirmed versions display nicer using `1.26.64` --> `1.26.65` update.

`1.25.73` --> `1.26.65` | `1.26.64` --> `1.26.65`
----- | -----
<img width="653" alt="1 25 73 update popup" src="https://user-images.githubusercontent.com/28145373/122766421-80db7180-d26f-11eb-8d6b-33d6b8824d56.png"> | <img width="649" alt="1 26 64 update popup" src="https://user-images.githubusercontent.com/28145373/122766426-820c9e80-d26f-11eb-80f1-54a84e9df61f.png">

--------------

**Comment by bsclifton** [comment] 2021-06-22 05:34
Reverted by @mihaiplesa on all channels after experiencing https://github.com/brave/brave-browser/issues/16539
master - https://github.com/brave/brave-core/commit/14e74d6e017308d69c70bdc65798a467d9de6e92
1.27 - https://github.com/brave/brave-core/commit/47f369babddf9aa440b00fc47c7659035aadae73
1.26 - https://github.com/brave/brave-core/commit/7f3c11a939a9b2dfec4b6176c287cd15863c28ee

**Comment by LaurenWags** [comment] 2021-06-22 12:41
Removed from 1.26.x milestone since this was reverted

**Comment by mherrmann** [comment] 2021-06-22 16:09
In light of the above problems and the revert (sorry again and thank you @bsclifton and @mihaiplesa for the quick fix), I suggest we forego this issue and just do #9562.

**Comment by bsclifton** [comment] 2021-06-22 23:08
@mherrmann all credit to @mihaiplesa 😄 I'll go ahead and close this then as `wontfix`

**Closed by bsclifton** 2021-06-22 23:08 UTC
Labels: OS/Desktop, OS/macOS, OS/macOS-arm64, QA Pass-macOS, QA Pass-macOS-arm64, QA/Yes, feature/updater, priority/P4, release-notes/include

**Comment by mherrmann** [comment] 2021-06-23 06:11
Well, then thank you again @mihaiplesa :heart:
