### ISSUE TITLE
Can't access settings on tiled window

### ISSUE THREAD

**Issue by DeiAsPie** [brave/brave-browser#25176] opened 2022-09-02 18:20 UTC
## Description 

When the brave desktop is tiled sideways then the ability of the user to switch to other setting options is now made visible

## Steps to Reproduce

   1. Open brave Browser
   2. Navigate to `brave://settings/`
   3. Tile the window or shrink the window size to less than 980px width
   4. The user is stuck on getting started sub setting of all the settings available and switch to something else

## Actual result:

No sidebar or anything visible to switch between settings

## Expected result:
Show a side bar like chromium to switch between settings via a hamburger button/menu

## Reproduces how often: 

Easily reproduced/Always

## Brave version (brave://version info)

1.43.88 on Linux

## Version/Channel Information:

Channel agnostic issue
- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
Yes
- Can you reproduce this issue with the nightly channel? 
Yes
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No 
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by rebron** [comment] 2024-07-10 18:31
Closing as a dupe of https://github.com/brave/brave-browser/issues/24352#issuecomment-1616110746 and fixed in 1.54.x.

**Closed by rebron** 2024-07-10 18:31 UTC
Labels: OS/Linux, OS/Desktop
