### ISSUE TITLE
Be able to edit and add "top sites" shown on the Dashboard (new tab page)

### ISSUE THREAD

**Issue by Xyncgas** [brave/brave-browser#7493] opened 2019-12-19 23:51 UTC
## Test plan
See https://github.com/brave/brave-core/pull/7859

**Comment by HubDanDevMan** [comment] 2019-12-20 11:47
Can you specify what the problem is? And do you mean with Top Site? Do you mean warez FTP servers or do you mean a startpage you made?

**Comment by Xyncgas** [comment] 2019-12-28 16:41
let me elaborate.
By top sites I mean the ones that displays during brave's start page, like when you click a new tap or from starting the browsers, now brave puts those sites that you most frequently visits as those little icons like a short cut that you can pin or remove, which I found much useful.
one day I unpinned one, and by accident, and it's gone like south park, and usually there is something that says you can undo if you delete the top sites, it wasn't showing up, so by accident it was gone, and sometimes in december I had this issue with deleting too, the confirmation wasn't showing up, and right after I deleted it by accident while using touch screen, and it's gone. I wish I could edit these short cuts so I can have the freedom to add anysite I want and manage their address etc...... Instead of being stucked to them forever (when you have a lots browsing, don't forget these are the sites that you most frequently visits, so for other sites you want it to be there, I feel like more time is needed to visit them everday in order for them to show up at the start page, which the fact that you got to spam visiting them to get it to the start page is annoying) and no way to get them back after deleting them

**Comment by bsclifton** [comment] 2019-12-30 06:43
@Xyncgas thanks for the detailed description; this is something that @cezaraugusto is currently working on 😄 I couldn't find an existing issue for this feature request, so we can use this one

Here's a quick prototype interface that @cezaraugusto put together in a demo. @karenkliu I believe is working on the actual design with @rebron 
<img width="879" alt="Screen Shot 2019-12-29 at 11 39 50 PM" src="https://user-images.githubusercontent.com/4733304/71570887-a92c4a80-2a94-11ea-9158-8e620d234cac.png">

- Besides having a way to add them (ex: the "+" tile), it would be good to be able to edit ones being shown. 
- If a top site is deleted by pressing the X in top right, can there be a better way to restore one single site? For example, maybe a "top sites recycle bin" that can be shown, letting user restore one specific site instead of having to restore ALL of them

**Comment by Shudouken** [comment] 2020-01-14 10:12
I would like to see this feature implented as well.
By default the top sites link to the base url for a website, but for youtube I'd like to edit it to take me to my subscriptions feed instead.
Also it's not really clear to me how these top sites are chosen. It would be nice if I could turn that off as well and only add my own sites.
The prototype above looks great!

**Comment by CaptainSiberia13** [comment] 2020-02-06 15:52
I agree that this feature needs to be a priority. I just started using Brave as it was recommended by a friend. I like the browser, but miss the speed-dial on my old "Opera" browser. Adding that sort of home page functionality would be great!

**Comment by rwilliams** [comment] 2020-02-17 01:50
This new tab plugin has some killer features along these lines. Editible favorites, adjustable rows, columns. Folders for favorites and pages similar to iOS and Android.

https://chrome.google.com/webstore/detail/infinity-new-tab-pro/nnnkddnnlpamobajfibfdgfnbcnkgngh

I was using this in the past but now that we're getting paid to look at the new tab page it'd be nice to have more features.

**Comment by Vantiveman** [comment] 2020-02-20 17:08
I agree completely with the above. The ability to edit/add/change number of top sites would be extremely useful. It's annoying when one that I'm sure was pinned (as I pin all six, which seems to be the max) was suddenly replaced by another site that I had just used.
The layout/positioning/number of top sites should all be configurable options. It this is already being worked on as seems to be the case - Great! and thank you. I'm having a great experience with Brave, but this one aspect is a bit of a spoiler.

**Comment by Xyncgas** [comment] 2020-02-22 05:29
let's make our browser to an operating system...
wait WHOOA GOOGLE ?
We can't just use extensions though, it's essential and gotta be open source and staying alive, I mean it'd really makes me feel the freedom if I get to laugh at people how they are stuck in their home page

**Comment by rwilliams** [comment] 2020-02-22 06:52
We get paid money to use this new tab page. It would be nice if it has some of the features that many new tab page extension have. We're just talking about editable favorites here.

**Comment by finseiz** [comment] 2020-08-06 14:35
We need this!!!! almost 8 months since this issue was created

**Comment by Xyncgas** [comment] 2020-08-10 11:16
I totally think I can write codes, only if there's a way for me to get my hands on the dirt and make things change, I would really wanna do it and now I am still not even one foot in the doorway for writing patches for open source projects I've gotta start doing it

**Comment by water-chip** [comment] 2020-08-18 19:15
I made an account just so I could post in this thread. This is so ridiculous. Could you PLEASE add this extremely basic function to Brave already? It's been EIGHT MONTHS since this thread started. What tf is this, internet explorer 8? It's starting to feel that way. Get your sh** together, ffs.

**Comment by shunting65** [comment] 2020-08-24 17:17
How about a choice in history, to add this entry as a top site?  No doubt someone has navigated to a site they are interested in.

**Comment by landshrk** [comment] 2020-09-04 23:54
Adding my voice to the cries for this feature to be implemented, almost 9 months after the original request was submitted. This can't be that hard, right?

**Comment by aaronsantamaria** [comment] 2020-09-29 15:36
+1 Community
https://community.brave.com/t/make-top-sites-list-editable/166484

**Comment by MaxiM-PL** [comment] 2020-09-30 14:41
+1

So much time has passed since this issue was raised and the New Tab "dashboard" is stil completely useless. Even pinned "Top Sites" unpin themselves and disappear whenever they feel like it. It's a mess.

**Comment by aaronsantamaria** [comment] 2020-10-13 16:48
+1 Community
https://community.brave.com/t/ability-to-customize-the-new-tab-dashboard/171032

**Comment by douglasparker** [comment] 2020-10-13 19:17
> Grabbing this one next - just need to wrap up work on something else first 😄 This should be trivial after I landed the refactoring work with [brave/brave-core#6584](https://github.com/brave/brave-core/pull/6584). Stay tuned!

This is great news, thank you!

**Comment by aaronsantamaria** [comment] 2020-11-20 16:37
+1 
https://community.brave.com/t/we-need-to-be-able-to-add-custom-top-sites/181107

**Comment by aaronsantamaria** [comment] 2020-11-20 17:33
+2 
https://community.brave.com/t/we-need-to-be-able-to-add-custom-top-sites/181107

**Comment by SXMacdara** [comment] 2020-11-23 17:52
This issue has been raised in multiple threads under different names... Usually around top sites disappearing pr pinned sites not staying pinned. I see your team has removed the pin functionality. That seems a step backward. @bsclifton showed a nice prototype from @cezaraugusto almost a year ago. Can the Brave team or whoever is working on this give us ANY estimate as to when this will be completed? Why is it taking so long to add this feature?

**Comment by MaxiM-PL** [comment] 2020-11-23 19:41
> This should be trivial after I landed the refactoring work...

Umm, so I'm not going crazy and the pin was disabled completely. SO what happened to "This should be trivial"? Now it's even worse than it was before o_O

**Comment by douglasparker** [comment] 2020-11-23 20:47
> > This should be trivial after I landed the refactoring work...
> 
> Umm, so I'm not going crazy and the pin was disabled completely. SO what happened to "This should be trivial"? Now it's even worse than it was before o_O
> 
> 

That is a very good question. 🤔

**Comment by bsclifton** [comment] 2020-11-23 21:15
Explanation incoming - I know it can be frustrating ☹️ Hoping you all can hang in there as we make progress

The pinning logic we had was all custom written on top of Chromium and was seeded with information coming from the [chrome.topSites API](https://developer.chrome.com/extensions/topSites). This code mostly worked but always seemed to be plagued with issues- including sites that would seemingly disappear at random (we got a LOT of reports for this)

When 1.17 shipped, the functionality has technically regressed from user POV. There is no pinning, but the behavior matches Chromium exactly (which doesn't have pinning either). We only (at the moment) expose the "most visited" behavior. There is a "my shortcuts" mode and it does actually work - but we haven't had time to start work on this yet, unfortunately

Here's a work-around you can do if you're wanting to add/edit/move top sites in the meantime:
1. Visit brave://new-tab-page
2. In the bottom right, click `Customize` (pencil icon)
3. Click `Shortcuts` in left side of modal presented
4. Pick `My shortcuts`
    ![image](https://user-images.githubusercontent.com/4733304/100015700-3bb09900-2d8d-11eb-8da5-d888a91498af.png)
5. Click done
6. On the Chromium new tab page, click the + to add the sites you want

After you do this, the Brave NTP will work as you expect. When I was reworking this code, it seemed far better to re-use all of the Chromium logic rather than try to re-invent the top sites wheel. Unfortunately, it was a pretty large scope project (you can see the implementation with https://github.com/brave/brave-core/pull/6584

We chose to temporarily disable the `My shortcuts` mode because it's possible to get into a situation where you can delete all your entries and there isn't (at the moment) a `+` icon to add entries back.  When we grab this issue (add/edit top sites) we can re-enable this mode since there will be a way for folks to re-add sites manually

**Comment by douglasparker** [comment] 2020-11-23 21:26
Thanks for the update @bsclifton. Hopefully we'll see the situation improve in the near future.

**Comment by vfl97** [comment] 2020-12-24 11:03
I hope there will also be an option to group the favorites on the dashboard in a folder…like Safari & Opera do.

**Comment by Xyncgas** [comment] 2020-12-29 01:14
Pretty generalized and disciplined solution +1

**Comment by bsclifton** [comment] 2021-01-15 17:26
OK folks - got a happy update 😄 Thanks for your patience 

I know it's taken a while, but @karenkliu and @rebron worked out what the rest of the experience looks like. We're ready to start work on this and @simonhong will be grabbing it

Here are a few screen caps of what is to come:
1. Right now, the icons shown are "Frequently visited" mode. You can remove them but you can't change the order, etc. We'll be re-adding `Favorites` mode:
    ![image](https://user-images.githubusercontent.com/4733304/104758289-0e3ff600-5713-11eb-9c76-4857bbcad446.png)
    
    You'll also be able to toggle via the ellipsis menu:
    ![image](https://user-images.githubusercontent.com/4733304/104758365-2dd71e80-5713-11eb-9a1c-9dc6e55e4635.png)


2. When in `Favorites` mode, up to 12 icons will show and there will be a + for adding your own sites. You can also edit existing sites and drag/drop/re-order the tiles
![image](https://user-images.githubusercontent.com/4733304/104758560-78f13180-5713-11eb-941c-62f2c66a1b39.png)
![image](https://user-images.githubusercontent.com/4733304/104758714-ab9b2a00-5713-11eb-8734-cd43b1f22aed.png)

**Comment by vfl97** [comment] 2021-01-19 13:50
I don't want to bother you, but I imagined we would get something less limited. Safari, Opera & co. let us make more than 20 favorites & also folder with favorites!

**Comment by vfl97** [comment] 2021-01-19 13:50
I don't want to bother you, but I imagined we would get something less limited. Safari, Opera & co. let us make more than 20 favorites & also folder with favorites!

**Comment by MamaCoop452** [comment] 2021-02-01 20:43
I'm sorry, BRAND NEW to Brave. Totally clueless to all this ^^^, but I did accidently remove one of my faves and can't get it back and I'm not seeing "favorites" or "frequently visited" options on my dashboard (new tab). It's not critical for me, just helpful. Am I missing an important piece somewhere? Could someone explain to a neophyte, old"ish" lady, please?

**Comment by simonhong** [comment] 2021-02-03 12:55
@MamaCoop452 We are working on providing user-curated mode. Stay tuned :)
and If you want to get back accidently deleted item, I can give a tip for you.
When you delete one more item, you can see bubble like below.
`Restore All` acts like factory reset button of top sites. It can give your all sites again.

<img width="501" alt="Screen Shot 2021-02-03 at 9 52 08 PM" src="https://user-images.githubusercontent.com/6786187/106749639-2055ea00-666a-11eb-8e73-75a8c473f8f3.png">

**Comment by MamaCoop452** [comment] 2021-02-04 16:03
@simonhong YES!!! That worked! Restore All. That was all I needed... for now. Thank you.

**Comment by MamaCoop452** [comment] 2021-02-04 16:08
@simonhong WooHOO! Yes, that worked. Thanks so much for that clever trick. Silly, but that's all I wanted. Now can you tell me how to get an email sent when you answered my question? I've learned, over the years, to save the links to my questions so I can go back and check, just in case. And this proved to be valuable because I didn't get a notice that anyone had responded? Is there a setting somewhere here? Thanks!

**Comment by bsclifton** [comment] 2021-02-04 17:24
@MamaCoop452 since you commented here, you should get email notifications from GitHub whenever this issue is commented on 🙂 Just to make sure (or if there are other issues you're interested in), you can click "Subscribe" in the top right of this issue (may have to scroll down a bit)

**Comment by MamaCoop452** [comment] 2021-02-04 17:37
And this time I did! Crazy, but thanks!

**Comment by WriterDad** [comment] 2021-02-10 16:30
I'm generally enjoying Brave, and this will be a welcomed change. That the favourites are changing to every site I visit has been driving me bananas. 

Is there any timeline for when it'll be implemented? I had an Update notice a couple of days ago and was hoping that was the fix being put in, but no such luck.

**Comment by simonhong** [comment] 2021-02-11 00:15
@WriterDad Hello,  I'm working on this issue and planning to merged in `1.22.x` :)

**Comment by WriterDad** [comment] 2021-02-11 16:14
@simonhong Sounds good. Thanks very much!

**Comment by bulrush15** [comment] 2021-02-14 14:25
I'd like this too. When I click New Blank Tab, I get a list of the top 8 sites I use the most. But I accidentally deleted one site and now I can't see how to get it back. 

Would that be in an INI file perhaps? Is this site I deleted on some black list now so I'll never see Discord on my top site list on the New Tab page?

**Comment by simonhong** [comment] 2021-02-15 00:14
@bulrush15 How about trying the way I wrote at https://github.com/brave/brave-browser/issues/7493#issuecomment-772486843 to recover accidently deleted topsite item?

**Comment by Xyncgas** [comment] 2021-02-21 07:47
finally I can see my day of using brave coming back. now that microsoft is making their own browsers with chromium, it's a really strong couple with their windows system too, yet brave fulfills my fantasy for freedom, and I am glad when I saw the UI looks so good.

**Comment by bsclifton** [comment] 2021-02-22 07:42
This is looking really good - going through the dev review for it now 😄 We should be able to get this into Nightly soon and then it would be available in 1.22 which is targeted for Release channel on March 23rd

**Closed** 2021-03-02 04:00 UTC
Labels: OS/Desktop, QA/Yes, design/needs-mock-up, feature/new-tab, priority/P3, release-notes/include

**Comment by bsclifton** [comment] 2021-03-03 08:43
Awesome job @simonhong! This is live now in Nightly - it includes designs by @karenkliu with help from @rebron 😄 

This has been a long time coming - I really hope everybody enjoys this one 😄

**Comment by claudioluciano** [comment] 2021-03-03 13:15
First of all, thanks for this feature!

It would be nice if we could add more than 12 sites.
Another point i think the sites are not saved as bookmark, it would be nice if they are bookmarked as well.

**Comment by rhinounicorn** [comment] 2021-03-04 16:54
This is awesome. I recently started using Brave and have been wanting something like this. I also agree with @claudioluciano that we should be able to add more than 12 sites. Somethings as customizable as that extension that @rwilliams posted would be really nice. Thanks for the great work though!

**Comment by rwilliams** [comment] 2021-03-07 13:10
@bsclifton Do the top sites get synced? I love it, have been testing it on nightly. It's simple and clean and gets the job done.

**Comment by stephendonner** [comment] 2021-03-10 00:39
Verified `PASSED` using the testplan in https://github.com/brave/brave-core/pull/7859 and the (internal) spec.

Brave | 1.23.25 Chromium: 89.0.4389.86 (Official Build) nightly (x86_64)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | macOS Version 11.2.3 (Build 20D91)

### Areas covered:

**1. Blank by default:**
* Verified with a new profile that the Top Sites widget is blank, default

<details>
<summary>screenshot</summary>
<img src="https://user-images.githubusercontent.com/387249/110550960-801c3680-80e9-11eb-960b-81866aec777b.png">
</details>

**2. Dark and light themes:**

* Verified that UI elements were appropriately themed to their dark and light-theme counterparts

<details>
<summary>screenshots</summary>
<img src="https://user-images.githubusercontent.com/387249/110551321-249e7880-80ea-11eb-838b-9380d4792c40.png" 
<img src="https://user-images.githubusercontent.com/387249/110551362-3253fe00-80ea-11eb-8963-533c08362260.png">
</details>

**3. Frequently Visited sites:**

* verified context-menu items, from clicking ellipsis `...`, which appears on hover, to the upper-right of the Top Sites widget
<details>
<summary>screenshot</summary>
<img src="https://user-images.githubusercontent.com/387249/110552412-249f7800-80ec-11eb-9689-5962e736a695.png">
</details>

* verified a max of the top 6, fills in from the right (_and orders by comparing number of sites visits, importantly_), replacing older (less-visited) ones on the left

<details>
<summary>screenshot</summary>
<img src="https://user-images.githubusercontent.com/387249/110551652-c1f9ac80-80ea-11eb-9558-1b554bb36e4b.png">
</details>

**4. Favorite sites:**

* Verified context-menu items from ellipsis
<details>
<summary>screenshot</summary>

<img width="1312" alt="Screen Shot 2021-03-09 at 3 24 34 PM" src="https://user-images.githubusercontent.com/387249/110552315-f752ca00-80eb-11eb-894a-b92694c947cf.png">
</details>

* Verified `Add site` appears when fewer than 12 sites are populated

<details>
<summary>screenshot</summary>

<img src="https://user-images.githubusercontent.com/387249/110551889-3af90400-80eb-11eb-9a65-027a66d1bbef.png">
</details>

* verified max of 12 Favorite sites; `Add site` disappears when we reach 12 sites

<details>
<summary>screenshot</summary>

<img src="https://user-images.githubusercontent.com/387249/110551501-7cd57a80-80ea-11eb-9449-38dab0211645.png">
</details>

**5. Drag and Drop**  (to reorder):
* Verified that dragging and dropping allows the user to reorder the Top Sites dynamically

<details>
<summary>screencast</summary>

<img src="https://user-images.githubusercontent.com/387249/110553987-c758f600-80ee-11eb-8889-1b20480326ed.gif">
</details>

**6. Add site:**
* Verified successfully added site name and its URL (`CNN`, `https://www.cnn.com`)
<details>
<summary>screenshots</summary>
<img width="1785" alt="Screen Shot 2021-03-09 at 4 26 08 PM" src="https://user-images.githubusercontent.com/387249/110557028-98458300-80f4-11eb-8db8-3b05d7fccbfa.png">

<img width="1785" alt="Screen Shot 2021-03-09 at 4 26 50 PM" src="https://user-images.githubusercontent.com/387249/110556961-72b87980-80f4-11eb-8b58-33c2ec4be4b5.png">


</details>


**7. Edit site:**
* Verified successfully renamed site and changed its URL (`weather.com` -> `accuweather.com`)
<details>
<summary>screencast</summary>

<img src="https://user-images.githubusercontent.com/387249/110554596-f6239c00-80ef-11eb-966b-d70274c2dadf.gif">
</details>

**8. Remove** (site), **Undo**, **Restore all**
* Verified (separately) successfully removed both Favorite and Frequently Visited sites
* Verified successfully undid removal; site was re-populated, using `Undo`
* Verified successfully restored all deleted sites, using `Restore all`
<details>
<summary>screencast</summary>
<img src="https://user-images.githubusercontent.com/387249/110555926-5b788c80-80f2-11eb-85a8-bd185296ea84.gif">
</details>

**9. Hiding and restoring both Top Sites widgets**
* Verified the user can `Hide` the entire Top Sites widget
* Verified user can then `Restore` using `Customize` -> `Top Sites` -> and then clicking to choose either `Favorites` or `Frequently Visited`
<details>
<summary>screencast</summary>
<img src="https://user-images.githubusercontent.com/387249/110555045-c0cb7e00-80f0-11eb-9a7e-bb9c5df42e4c.gif">
</details>

==========
Known issues:

* editing a Frequently Visited site doesn't apply changes, and changes display mode to Favorites (https://github.com/brave/brave-browser/issues/14606)
* newly-added sites don't get a favicon until they're loaded (https://github.com/brave/brave-browser/issues/14481)
* difficult to read site names against white backgrounds in the new-tab page (https://github.com/brave/brave-browser/issues/14484)
* newly-added Frequently Visited sites don't always dynamically populate the new-tab page (https://github.com/brave/brave-browser/issues/14607)

**Comment by bsclifton** [comment] 2021-03-12 07:08
@rwilliams the top sites are not synced... yet! That would be a cool feature 😄 If we treated them (in favorites mode) as bookmarks, it would be quite easy to sync across all platforms (and that would cover concern by @claudioluciano)
cc: @rebron (not sure if we have an issue for that?)

@claudioluciano there is an issue for larger number of top site tiles which you can track here (subscribe, give thumbs up!):
https://github.com/brave/brave-browser/issues/6619

**Comment by WriterDad** [comment] 2021-03-25 03:20
Is there any news on when the top sites issue will be remedied for Windows? I'd mistakenly thought that March 23rd was when it would be implemented via update, but upon re-reading it, I see it was for a release channel?

Thanks for any insight.

**Comment by bsclifton** [comment] 2021-03-25 05:40
@WriterDad March 23rd we did have an update to 1.22 - our next major release version (1.23) has the new top sites functionality in it 😄 Would be great for someone to confirm - but I believe this will sync top site tiles across your Desktop instances. We might be able to pull in that same work for Android too

**Comment by WriterDad** [comment] 2021-03-25 13:18
Very strange. I've been on Brave up on my Windows every day this week week and it hasn't indicated there's an update. I was prompted for that on my Mac a day or two ago, but honestly it had been so long since I'd sat down to use Brave there I thought it may've been overdue for even the previous update.

The About info says I'm at 1.21.77 but is checking for updates as I type...

...

... just finished and says I'm "nearly up to date"?
Hmm.

I'll relaunch and see what that does.

**Comment by WriterDad** [comment] 2021-03-25 13:22
1.22.67 is what it bumped me up to. I'll take a look at how the top sites behave and get back here if needed.

Thanks!

**Comment by WriterDad** [comment] 2021-03-25 14:23
@bsclifton The top sites still don't seem to be working properly for me.

Upon my forcing the update mentioned above, I deleted three of the six top sites that were showing at the time to allow for newly visited sites to populate the slots.

Left in the first three slots--this matters for a point later--were: My own site (accurate anyway), Google Maps (I have two persistent tabs open for some writing I'm doing, so again, accurate), and ProtonMail (usually open all the time, so accurate). The last three were wide open for whatever Brave wanted to populate them with.

Since then I've only opened one new tab for the Mastodon social media site, plus then a new one in the last few minutes to check on what the top sites were looking like.

The result? My first three sites are remaining intact, but now the second set of three are, in order: Global News live streaming (I'd gone to a video there weeks ago but haven't since, and there's no tabs open with Global News currently, but that's been a recurring top site regardless), then Brave itself (which I guess makes sense, as I'm in the default Brave environment page when I open a new tab and did that twice), and then Google Maps again (which is odd, since a) it was already among the previous three sites, and b) I didn't go to the Google Maps tab nor open a new one for it).

Any suggestions for how to give the top sites a bit of a poke in the hopes they start behaving? I'm happy to wipe them all clear, but given what's popped up into the last three slots when they were empty, I don't know if that'll do much.

Thanks again.

**Comment by WriterDad** [comment] 2021-03-25 14:37
@bsclifton Incidentally, as you were curious if the cross-platform syncing works with Android: I have an Android and was embarrassed by how many browser tabs I had open in it, but I hadn't opened any new ones since updating Brave on my laptop (so I wouldn't think that would affect what populated on the top sites on my laptop), and nor were Global News, Brave or Google Maps any of the open tabs anyway.

**Comment by WriterDad** [comment] 2021-03-26 14:51
@bsclifton @simonhong Update on my top sites populating: One of the open three slots (see above for why only three) populated with a site I went to a couple of times yesterday and once this morning. Which makes sense, though oddly the Mastodon Social website, which I'm on regularly and sometimes at length, hasn't come up in those top sites in probably a couple of months. It did briefly, several weeks back, but then disappeared again, and hasn't been back since.
A site I was on two times yesterday, however, did show up in the top sites. Twice, actually. It's currently taking up two of those three slots.

Related: To try to both kick one of those repeated ones loose and to get Mastodon to show up again, I just opened a new tab to get onto Mastodon, then closed it and loaded up a new tab with it, four times in a row. The place I visited twice yesterday was reduced to one slot, but the other wasn't taken by Mastodon--I'm very curious why it isn't showing up in top sites at all lately--but now two of the three slots are taken up with Github, despite it not being in any slots at all this morning and my only loading it up once in one tab to log on and post this update.

Conclusion: The changes made to the top sites seems to definitely be paying more attention to what are actually recently (although that more than frequently) used  websites, but not to all (e.g. Mastodon), and the ones it is paying to will at times be doubled up in multiple top sites slots.
Hoping that can be addressed soon.

All the best.

**Comment by bsclifton** [comment] 2021-03-28 20:54
@WriterDad the improvements mentioned are only in version 1.23. Basically, this new add/edit top sites feature is on [https://brave.com/download-beta](Beta channel) at the moment and for release channel (what you're on) it's is looking at an April 13th release

If you wanna see how it looks, you can definitely try it with Beta - but Beta channel uses a different profile... so you won't have any bookmarks, etc. The best thing to do would be wait until it lands on release channel 😄 

With the changes I made a while back, the "frecency" (how often you visit, when it was recently visited) algorithm used to pick the most visited sites is now *exactly* the same as Chromium. We don't have any plans of changing that

**Comment by TechnoRobert** [comment] 2021-04-21 02:10
Looks as if people have been complaining about this since roughly the week that COVID-19 was discovered. I updated Brave a day or two ago (to 1.22.70), and I still don't see how to add a Top Site to the New Tab page. Still looking for the solution...

**Comment by simonhong** [comment] 2021-04-21 02:14
@TechnoRobert I think you're using previous version. Current stable version is `1.23.71` and this topsite editing feature is available since `1.23.x`.

**Comment by crabtreeak** [comment] 2021-07-14 14:00
I am not sure why there is an artificial limit of 12 sites on this favorite sites speed dial.  My new tab window has room for more than double that.  Can we have the option to add more than 12?  This feature other than that is wonderful with a great GUI interface.  Thanks!

I just converted over to this Brave browser.  It works great.

**Comment by DarrenSem** [comment] 2022-10-14 16:37
> 

The ANDROID app needs this feature! I accidentally clicked Remove on a frequent site and **now it thinks I wanted it permanently hidden from the list** :-(

https://github.com/brave/brave-browser/issues/17217
