### ISSUE TITLE
Ubuntu 19.04 support 

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [brave/brave-browser#4181] opened 2019-04-20 20:15 UTC
please add 19.04 support please thanks 

E: Failed to fetch https://brave-browser-apt-beta.s3.brave.com/dists/disco/InRelease  403  Forbidden [IP: 199.232.38.217 443]
E: The repository 'https://brave-browser-apt-beta.s3.brave.com disco InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by Madis0** [comment] 2019-04-20 20:29
#4157

**Comment by srirambv** [comment] 2019-04-22 11:59
Closing as dupe of #4157

**Closed by srirambv** 2019-04-22 11:59 UTC
