### ISSUE TITLE
Disabled Scrolling during Crypto Wallet on-boarding prevents use without fullscreen or zooming.

### ISSUE THREAD

**Issue by SoaringMoon** [brave/brave-browser#7825] opened 2020-01-20 15:47 UTC
## Description 
Within the wallet feature's scrolling appears to be disabled.

## Steps to Reproduce
1. On an install of brave-browser without a crypto wallet.
2. Go to the hamburger dropdown menu and select "Crypto Wallet"
3. On a 1360x768 monitor the onboarding "I understand" button will display below the window.
4. In order to bypass this, you are required to fullscreen your browser.

## Actual result:
![image 1](https://user-images.githubusercontent.com/11183441/72739446-a2fc2c00-3b71-11ea-8be8-fee92d2210c0.png)

## Expected result:
![image 2](https://user-images.githubusercontent.com/11183441/72739447-a2fc2c00-3b71-11ea-8122-d7b9c3c64afb.png)

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Brave | 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1903 (Build 18362.535)

**Comment by SoaringMoon** [comment] 2020-01-20 16:12
It gets even worse later into onboarding. Even in fullscreen I cannot scroll down.
I am forced to zoom the page out quite far (50% size) to continue.

This screenshot was taken in portable.
Brave | 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Windows 10 OS Version 1903 (Build 18362.535)

![image 3](https://user-images.githubusercontent.com/11183441/72741419-9679d280-3b75-11ea-937b-673585b4847c.png)

**Comment by srirambv** [comment] 2020-01-20 16:49
Dupe of  #6595 & #7045

**Closed by srirambv** 2020-01-20 16:49 UTC
