### ISSUE TITLE
Image upload blocked in Github issue tracker with shields on.

### ISSUE THREAD

**Issue by shannah** [brave/brave-browser#2893] opened 2019-01-10 14:07 UTC
## Description 

On Github, you can normally copy and paste an image into an issue directly.  However, when Shields are active, this fails, showing the message:

![image](https://user-images.githubusercontent.com/2677562/50973148-0e121d80-149d-11e9-9df0-edb91b5f3874.png)

If you turn off the Shield, then the image paste/upload works correctly.

## Steps to Reproduce

   1. Open a new issue in Github, in Brave wish shields on.
   2. Try to paste an image into the issue.

## Actual result:

Image is not added, and the following error message is shown.

![image](https://user-images.githubusercontent.com/2677562/50973148-0e121d80-149d-11e9-9df0-edb91b5f3874.png)

## Expected result:

Image should be added to the issue.

## Reproduces how often: 

Always.  Easily reproduced

## Brave version (brave://version info)

Version 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)

Mac OS 10.13.6

### Reproducible on current release:

Unknown

### Website problems only:  

- Does the issue resolve itself when disabling Brave Shields? 

Yes

- Is the issue reproducible on the latest version of Chrome? 

No

**Comment by NejcZdovc** [comment] 2019-01-10 14:15
closing this one as dupe of https://github.com/brave/brave-browser/issues/2034. Will be fixed in the next release.

**Closed by NejcZdovc** 2019-01-10 14:15 UTC
