### ISSUE TITLE
Crash Report: Pressing return in Github search bar

### ISSUE THREAD

**Issue by chrisgarber** [brave/brave-browser#24445] opened 2022-08-04 15:52 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.41.99  Chromium: 103.0.5060.134
Operating System: Mac OS X 12.4.0

URL (if applicable) where crash occurred: github.com

Can you reproduce this crash? Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Go to github.com
2. Go to the search bar and put in a query
3. Press enter to start search -> crash

going directly to the search url, e.g. https://github.com/search?q=my-component doesn't cause crash, nor does clicking on a query in the dropdown with a scope. Only pressing enter/return to begin the query causes a crash.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/dee30000-efc0-a008-0000-000000000000

**Comment by sharathprabhal** [comment] 2022-08-08 17:43
(bump)

**Comment by rebron** [comment] 2022-08-19 20:43
@chrisgarber @sharathprabhal Please update to the latest 1.42.97. This particular crash fix was fixed in 1.41.100.

**Comment by rebron** [comment] 2022-08-19 20:44
Dupe of https://github.com/brave/brave-browser/issues/24164

**Closed by rebron** 2022-08-19 20:43 UTC
