### ISSUE TITLE
Partial theme switch when opening new profile

### ISSUE THREAD

**Issue by ChrisB85** [brave/brave-browser#6341] opened 2019-10-07 19:25 UTC
## Description 
Starting second profile window with different theme affects already opened window by partially switching theme.

## Steps to Reproduce

   1. Start Brave using profile where dark theme is set
   2. Open second profile where light theme is selected
   3. Theme on first window is partially switched to light

## Actual result:
Window with dark theme:
![Window with dark theme:](https://i.ibb.co/ZGYTbCJ/dark.png)
After opening second profile window with light theme:
![After opening second profile window with light theme:](https://i.ibb.co/qBrKk57/dark-light.png)

## Expected result:
Opening second profile with other theme should not affect already opened windows.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
```
Brave	0.69.132 Chromium: 77.0.3865.90 (Oficjalna wersja) (64-bitowa)
Wersja	58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
System operacyjny	Windows 10 OS Version 1809 (Build 17763.737)
JavaScript	V8 7.7.299.11
Flash	(Wyłączone)
Klient	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Wiersz poleceń	"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-chrome-google-url-tracking-client --disable-domain-reliability --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,TranslateUI,AudioServiceOutOfProcess,UnifiedConsent --enable-dom-distiller --enable-features=NewExtensionUpdaterService,WebUIDarkMode,SimplifyHttpsIndicator --extensions-install-verification=enforce_strict --no-pings --extension-content-verification=enforce_strict --enable-features=SimplifyHttpsIndicator,WebUIDarkMode,NewExtensionUpdaterService --disable-features=UnifiedConsent,AudioServiceOutOfProcess,TranslateUI,LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication --flag-switches-begin --try-supported-channel-layouts --flag-switches-end
Ścieżka pliku wykonywalnego	C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Ścieżka profilu	C:\Users\Krzysztof\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes.
- Can you reproduce this issue with the beta channel?
Don't know.
- Can you reproduce this issue with the dev channel?
Don't know.
- Can you reproduce this issue with the nightly channel?
Don't know.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No.
- Does the issue resolve itself when disabling Brave Rewards?
No.
- Is the issue reproducible on the latest version of Chrome?
No.

**Comment by kjozwiak** [comment] 2019-10-08 03:04
Duplicate of https://github.com/brave/brave-browser/issues/5373.

**Closed** 2019-10-08 03:04 UTC
Labels: duplicate
