### ISSUE TITLE
Custom Crypto Assets (UFO) Added to Brave Wallet Shows Incorrect Market Data and Valuation

### ISSUE THREAD

**Issue by divinIN3** [brave/brave-browser#19740] opened 2021-11-25 17:27 UTC
## Description 
Added UFO crypto to Brave wallet

## Steps to Reproduce

   1. Navigate to brave://wallet
   2. In Portfolio click + Visible Assets
   3. Add the UFO contract as custom token 0x249e38ea4102d0cf8264d3701f1a0e39c4f2dc3b
   4. Fill it details (I used 18 for decimal precision).
   5. Add

## Actual result:
Shows fixed asset value of 0.41.  The wallet shows the correct volume in my wallet but incorrect crypto price.

## Expected result:
Display correct price and volume.

## Reproduces how often: 
Easily

## Brave version (brave://version info)
Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by onyb** [comment] 2021-12-28 13:45
Could not reproduce this on `1.35.x` (Nightly). I believe the incorrect price issue is fixed by https://github.com/brave/brave-core/pull/11557. Going to uplift this fix to `1.34.x` (Beta), so it's available in the Jan 4 2022 release.

https://user-images.githubusercontent.com/3684187/147571967-b73e7b56-7b5b-48d1-b206-94784614d57c.mov

**Comment by HEagle18** [comment] 2022-06-17 12:02
Confirmed with Onyb that we can now close this issue.

**Closed by HEagle18** 2022-06-17 12:02 UTC
Labels: needs-investigation, priority/P3, feature/wallet, OS/Desktop, front-end-change
