### ISSUE TITLE
Extension pages are half translated when browser and extension are on different language 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6308] opened 2019-10-03 19:16 UTC
## Description 

Reported by @SergeyZhukovsky. 
Extension pages are half translated when browser and extension are on different language 

## Steps to Reproduce

Scenario 1:
   1. Set browser language to English and add Russian to the list of browser languages
   2. Enable crypto wallet
   3. Extension page has mixed translations

Scenario 2:
   1. Set browser language to English and add Russian to the list of browser languages
   2. Add an extension like MM and set extension language to Russian
   3. Extension page has mixed translations

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/66156750-4a1f7c80-e5f0-11e9-95a1-a413329f7ea6.png)
![image](https://user-images.githubusercontent.com/17010094/66156760-50155d80-e5f0-11e9-8295-f746b4178dc9.png)

## Expected result:
All text should be translated

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by kjozwiak** [comment] 2019-10-08 03:12
@bbondy should we move this into https://github.com/brave/brave-browser/milestone/55 as we're going to need a new build for https://github.com/brave/brave-browser/issues/5698 and possibly https://github.com/brave/brave-browser/issues/5106?

**Comment by kjozwiak** [comment] 2019-10-09 05:06
@ryanml @bbondy looks like I can still reproduce this using https://github.com/brave/ethereum-remote-client/releases/tag/0.1.15 on both `Windows 10 x64` & `macOS 10.14.6 x64`. Examples:

### macOS 10.14.6 x64 example:

<img width="946" alt="Screen Shot 2019-10-09 at 1 01 21 AM" src="https://user-images.githubusercontent.com/2602313/66452903-56f90180-ea30-11e9-995b-f45590526674.png">

### Windows 10 x64 example: 

![Annotation 2019-10-09 010448](https://user-images.githubusercontent.com/2602313/66453029-dedf0b80-ea30-11e9-8f64-e2899ecf866c.jpg)

@srirambv can you check `Linux` and see if you can reproduce on your end with https://github.com/brave/ethereum-remote-client/releases/tag/0.1.15?

**Comment by srirambv** [comment] 2019-10-09 13:35
Reproduced on Linux with `1.0.15`
![image](https://user-images.githubusercontent.com/17010094/66486221-289f1480-ea78-11e9-9dab-a0ac95a985b2.png)

**Comment by bbondy** [comment] 2019-10-09 14:04
I just cleared out the english strings on each language and did an order to get the string picked up for translation.  Once that's done in a few days I can pull the translations and it'll be included in the next extension update.

**Comment by bbondy** [comment] 2019-12-20 18:26
@srirambv can you check again?

**Comment by srirambv** [comment] 2020-01-10 17:08
This still happens on current component and the rebased component
<img width="1038" alt="Screen Shot 2020-01-10 at 12 07 45 PM" src="https://user-images.githubusercontent.com/17010094/72171938-f1574100-33a1-11ea-84bf-3a0b3912a875.png">

**Comment by bbondy** [comment] 2020-01-17 18:18
Closing as dupe of https://github.com/brave/brave-browser/issues/7791

**Closed by bbondy** 2020-01-17 18:18 UTC
Labels: QA/Yes, feature/crypto-wallets, feature/extensions, l10n, priority/P3, release-notes/exclude
