### ISSUE TITLE
Bug: About Brave Page Spacing Problem

### ISSUE THREAD

**Issue by 8227846265** [brave/brave-browser#13286] opened 2020-12-23 07:19 UTC
There's a spacing issue on Brave Browser version section (Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/66582769/102970263-2799bc00-4532-11eb-8870-d1b3ee01e217.png)

System: Windows x64

**Comment by 8227846265** [comment] 2021-04-27 12:16
As of Version 1.23.73 Chromium: 90.0.4430.85 (Official Build) (64-bit). The spacing issue is still existing.
![image](https://user-images.githubusercontent.com/66582769/116239655-7e8bf800-a795-11eb-8147-a89f2fc8a727.png)

**Comment by QueshAnmak** [comment] 2022-08-16 11:04
I think this issue is a duplicate of issue #21435

**Comment by 8227846265** [comment] 2022-10-26 08:47
The issue mentioned above was published on March 23, 2022 (1 year ago)

Mine was published on December 23, 2020 (2 years ago).

In any case, as of the latest version. The awkward spacing is still there.
![image](https://user-images.githubusercontent.com/66582769/197979960-b566dd74-3c97-4106-bf6e-ba44c6e7e348.png)

**Comment by ArshErgon** [comment] 2022-11-03 06:25
@QueshAnmak can you help https://github.com/brave/brave-browser/issues/26407?

**Comment by BalanaguYashwanth** [comment] 2022-11-20 13:24
<img width="470" alt="image" src="https://user-images.githubusercontent.com/36238382/202904550-62b23315-531a-41c7-9c62-36176d2a04ef.png">
Spacing need to be like this ?

**Comment by protocolog** [comment] 2022-12-02 07:32
I am a student of BITS Pilani, india. Please assign me this issue.
@bsclifton @8227846265  @BalanaguYashwanth

**Comment by XavierJDN** [comment] 2022-12-29 21:07
Hi,
Is this issue still relevant?

**Comment by vassyz** [comment] 2022-12-29 22:16
> Hi,
> Is this issue still relevant?

Well the issue is still present, but I guess it doesn't bother that many people so it's not high priority.

**Comment by XavierJDN** [comment] 2022-12-30 14:14
> > Hi,
> > Is this issue still relevant?
> 
> Well the issue is still present, but I guess it doesn't bother that many people so it's not high priority.

Hi,
Yes, of course. I'd like to know how to reproduce the issue?

**Comment by vassyz** [comment] 2022-12-30 14:40
You don't have to reproduce it, it's the actual `Brave >> About Brave` page

**Comment by XavierJDN** [comment] 2022-12-31 16:08
Hi,
I think, I resolve the issue.
Can someone assign to me the issue?

**Comment by XavierJDN** [comment] 2023-01-02 15:15
I'd like to build my code is release mode to be able to test but an error occurs `ERROR at //brave/components/constants/BUILD.gn:16:3: Assertion failed. assert(brave_services_key != "")` when I run the command `npm run build Release`

**Comment by mahir118** [comment] 2023-01-04 04:36
I am wondering if this is even an issue? Maybe it's the way it's supposed to be. Plus, it doesn't really look unaesthetic. Any thoughts?

**Comment by Cleveho** [comment] 2023-03-10 10:31
The issue is resolved on version [Version 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit)](https://brave.com/latest/)

![image](https://user-images.githubusercontent.com/48880976/224293156-151f17ef-cdbd-4cf3-a564-d1be744c32a2.png)

The issue should be closed now.

**Comment by fallaciousreasoning** [comment] 2023-07-27 02:54
Closing as duplicate of https://github.com/brave/brave-browser/issues/21435. Thanks for your help everyone!

**Closed by fallaciousreasoning** 2023-07-27 02:54 UTC
Labels: bug, good first issue, priority/P4, about-pages/rebrand, OS/Desktop
