### ISSUE TITLE
brave://chrome-urls/ shows list of all internal URLs for chrome instead of brave

### ISSUE THREAD

**Issue by rahulsnkr** [brave/brave-browser#15357] opened 2021-04-18 17:08 UTC
## Description 

On navigating to `brave://chrome-urls`, the user is presented with the complete list of internal URLs that they can access. But the title of the page is `List of Chrome URLs` and all of the URLs in the list start with `chrome://` instead of `brave://`

## Steps to Reproduce

   1. Navigate to brave://chrome-urls
   2. Observe the list of internal URLs.

## Actual result:

![image](https://user-images.githubusercontent.com/28645536/115154040-81506400-a096-11eb-99e9-1d2b5a4ad3d0.png)
![image](https://user-images.githubusercontent.com/28645536/115153277-b2c73080-a092-11eb-8545-7f151095c025.png)

## Expected result:
1. Title of the page should be `Brave URLs`
2. Heading of the page should be `List of Brave URLs`
3. URL of the page should be `brave://brave-urls/` instead of `brave://chrome-urls/`
4. List of internal URLs should start with `brave://` instead of `chrome://`

## Reproduces how often: 

Easily

## Desktop Brave version:

Brave | 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)
-- | --
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | Linux

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Q(10)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment] 2021-04-19 04:26
Dupe of #5775

**Closed by srirambv** 2021-04-19 04:26 UTC
Labels: OS/Android, OS/Desktop
