### ISSUE TITLE
[Android] extensions support 

### ISSUE THREAD

**Issue by LifeIsStrange** [brave/brave-browser#11577] opened 2020-09-02 20:42 UTC
The Kiwi browser has achieved the breakthrough of allowing all chromium extensions to work on Android. 
Such a breakthrough will give it a huge competitive advantage over other browsers. 
The developer of kiwibrowser has told me he was collaborating with you to backport it's changes into brave. 
So this should be the tracking issue of porting the extension code from Kiwibrowser to Brave. 

So a bit of transparency would be nice, when is this work expected to be beta testable?
I'll start using brave once it can use uBlock Origin just like Kiwi.

**Comment by LifeIsStrange** [comment] 2020-09-02 20:44
https://github.com/kiwibrowser/src/issues/24

**Comment by srirambv** [comment] 2020-09-03 03:50
Dupe of #4493

**Closed by srirambv** 2020-09-03 03:50 UTC
Labels: OS/Android
