### ISSUE TITLE
MAC OSX high-CPU load after recent update of Brave

### ISSUE THREAD

**Issue by adilhasan** [brave/brave-browser#11436] opened 2020-08-26 08:01 UTC
Hello,
I just wanted to post this here in case other people have a similar issue. After a recent update of the Brave browser (I updated mine on Mon/24/Aug/20) I noticed that occasionally the browser would have a very high CPU load. I looked at the task manager and saw it was the browser itself taking the CPU. I have the Grammarly plugin installed. I forced that to stop and uninstalled it and now the CPU load is back to what it was.
hope this helps someone,
adil

**Comment by etiennedupont** [comment] 2020-08-26 08:11
Thank you @adilhasan !
I had the exact the same issue, and disabling Grammarly worked on my side.

**Comment by Martina-Neumayer** [comment] 2020-08-27 12:07
Gramarly has been already fixed by their devs.

**Comment by bsclifton** [comment] 2020-08-28 20:43
Thanks for the report folks! Closing as duplicate of https://github.com/brave/brave-browser/issues/11412

**Closed by bsclifton** 2020-08-28 20:43 UTC
Labels: OS/Desktop
