### ISSUE TITLE
incorrect favicon in Tipping banner and Thank you page for Vimeo pubs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5752] opened 2019-08-21 08:51 UTC
## Description 

incorrect favicon in Tipping banner and Thank you page for Vimeo pubs

## Steps to Reproduce

   1. Open brave 0.68.131
   2. Open few verified and not verified Vimeo pubs
   3. Send a one-time tip or monthly tip to Vimeo pubs 
   4. Incorrect favicon displayed in tipping banner and Thank you page

## Actual result:

incorrect favicon in Tipping banner and Thank you page for Vimeo pubs

https://vimeo.com/willchristiansen
![image](https://user-images.githubusercontent.com/38657976/63416651-6f2fa580-c41d-11e9-9c21-2133cf46592d.png)

![image](https://user-images.githubusercontent.com/38657976/63417906-c9ca0100-c41f-11e9-95d7-d11547937d41.png)

![image](https://user-images.githubusercontent.com/38657976/63416720-94bcaf00-c41d-11e9-96ec-398c67afbfb5.png)

https://vimeo.com/user91022604
![image](https://user-images.githubusercontent.com/38657976/63417371-c124fb00-c41e-11e9-98c5-65bca796e26d.png)

![image](https://user-images.githubusercontent.com/38657976/63417958-e2d2b200-c41f-11e9-84ab-fe3d52bd7664.png)

![image](https://user-images.githubusercontent.com/38657976/63417398-ce41ea00-c41e-11e9-9445-b6025c564a73.png)

## Expected result:
The correct favicon should display in Tipping banner and Thank you page

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment] 2019-08-21 09:28
closing as dupe of https://github.com/brave/brave-browser/issues/5720

**Closed by NejcZdovc** 2019-08-21 09:28 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards
