### ISSUE TITLE
Extensions Installed From Chrome Web Store Show `Not from Web Store.` in brave://extensions

### ISSUE THREAD

**Issue by Nihal247** [brave/brave-browser#19584] opened 2021-11-19 09:13 UTC
## Description 
I have installed a couple of extensions in Brave from [Web Store](https://chrome.google.com/webstore/category/extensions), but when I visit the [Extensions page](brave://extensions/), it shows a logo, hovering over it says `Not from Web Store.`

## Steps to Reproduce

   1. Install an extension from [Web Store](https://chrome.google.com/webstore/category/extensions) (for example: [Bitwarden](https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb), [Privacy Badger](https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp), etc.).
   2. Visit the [Extensions page](brave://extensions/).
   3. `Not from Web Store` gets shown up.

## Actual result:
`Not from Web Store.` gets shown up.

![Screenshot (26)](https://user-images.githubusercontent.com/80682093/142595763-bb61a4ae-fc70-443e-b84a-d533c4b64051.png)

## Expected result:
`Not from Web Store.` shouldn't get shown up.

## Reproduces how often: 
Always

## Brave version (brave://version info)
1.32.106

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Don't know
- Can you reproduce this issue with the nightly channel? Don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Don't know

## Miscellaneous Information:
Operating System: Windows 11 Home Single Language (22000.318)

**Comment by htmyname** [comment] 2021-11-21 06:56
The same thing happens to me, and I also noticed that the extensions do not update automatically with this message

**Comment by rebron** [comment] 2021-11-22 21:36
Fix will be in the next 1.32.x release. Closing as duplicate of https://github.com/brave/brave-browser/issues/19069

**Closed by rebron** 2021-11-22 21:36 UTC
Labels: OS/Desktop
