### ISSUE TITLE
Add Session Tabs / Containers to Roadmap

### ISSUE THREAD

**Issue by caspertone2003** [brave/brave-browser#4749] opened 2019-06-06 16:41 UTC
Please add Session Tabs / Containers to Roadmap, at least.

Some people  believe this to be an (almost) unique selling proposion of Brave, and was already implemented and nicely working in muon.

See
https://github.com/brave/brave-browser/issues/34

Thanks.

===========================

From @Pedro7

Please don't post comments saying 'me too', subscribe to the bug only or thumbs up the initial comment.

Why? Because the developers can't afford the time to read all oneliners saying 'me too' and it will be far easier to just set up an ignore filter for the emails regarding bug reports.

Thank you in Advance

**Comment by tomlowenthal** [comment] 2019-06-13 22:13
Having tabs with different security/privacy contexts is something I'm generally quite leery of. There's a lot of potential for someone to make unfortunate mistakes by doing things in the wrong context. And that's even if there's some visual treatment to distinguish those contexts.

**Comment by caspertone2003** [comment] 2019-06-14 12:48
@tomlowenthal 
Thanks for caring.
While that you mention is certainly a risk, I believe an even much higher risk is not having containerization... besides the loss of functionality.
Could you add the label of feature/session-tabs ?
TIA

**Comment by rebron** [comment] 2019-06-21 16:10
Closing. Duplicate of #34.

**Closed by rebron** 2019-06-21 16:10 UTC
Labels: duplicate, feature-request, privacy/feature

**Comment by themotu** [comment] 2019-06-21 21:09
This is literally the only thing that brought me to brave in the first place.

**Comment by caspertone2003** [comment] 2019-10-21 08:32
@bridiver @davidtemkin @BrendanEich 

After considering several months, I wish to state that I felt @rebron closure of the thread quite rude, as if killing free of speach.

Besides, I can understand that the brave team is not wishing for whatever reason to provide session tabs functionality, but, this thread was NOT a duplicate of #34 (session windows) - the reason stated to close it.

On the other hand, I would like to know if @rebron statement "We're not going to do a session tabs implementation do to UE/UX confusion." is an official statement or just his/hers.

Coming back to the session tabs, I remind the Brave browser motto, ‘You are not a product’. It focuses on improving the privacy and security of its users.
So, sacrificing privacy in aras of avoiding potential user errors seems quite not a real argument.

It worked nicely in muon, many users wish it. Firefox has develop a full set of extensions around containers - I saw no complain about user errors....

Not having session tabs in Brave broser, has enticed me to try Firefox... I regret having to give up brave-desktop in favour of ol´d mozilla.

Please reconsider... session tabs are strong munition for user privacy!

CT

**Comment by bsclifton** [comment] 2019-10-22 20:45
Definitely no killing of free speech here - the issue is not locked and everyone is welcome to continue discussion here. Keep in mind, that *at this time* we're thinking Session Windows are the way to go. It's entirely possible to change course and re-open this issue

It's fair to say there are a number of issues we need to fix before we have the time to take this on. So please do continue the discussion. We do read the comments, even if they're closed, and we do appreciate the input 😄

**Comment by bridiver** [comment] 2019-10-22 22:23
re: session tabs vs session windows, this is primarily because of the architectural issues in chromium. A "session" is a kind of linked user and there is a very tight coupling between users and windows that would be very complicated to work around. It's the same functionality, just a different UI

**Comment by caspertone2003** [comment] 2019-10-24 14:12
@bsclifton 
Thanks for the feedback. I already had participated in #34, as I was told session tabs was off-topic there I opened this other. I found the closure of the thread quite rude, considering even that I was told that #34 was covering session tabs...
Whatever, I appreciate your feedback, I was rather sorry to hear from @rebron stating "We're not going to do a session tabs implementation due to UE/UX confusion.".
I am just proposing to reopen this thread and include in the roadmap "to study session tabs". I like the name of containers, it is really very clear ;-)
Of course I understand that there is always a complex priorization balance on your side and that it might not be tomorrow, either the discussion, the decission nor the release of the functionality.
And that technical complexities might withdraw session tabs.

@bridiver 
If session windows do provide same functionality as session tabs, I really do not care about the name. Perhaps you should clarify this in #34, what i understood there is that both do not provided same functinality.... perhaps a communication issue.
In fact, there are some numbers of users complaining for not having session tabs... perhaps they did understood wrongly as myself.

Thanks for taking the time to provide feedback on this and for keeping the topic in your best knowledge storage area ;-)

CT

**Comment by bridiver** [comment] 2019-10-24 20:22
@caspertone2003 when I say "the same functionality" I mean that they will work like session tabs, but at the window level. So just like you have incognito windows, you'll have session windows with their own isolated storage. Again, it's not necessarily our preference, but it's something that is much easier to accomplish within the chromium framework.

**Comment by caspertone2003** [comment] 2019-10-25 09:28
@bridiver 
So, that means that with session windows the only implication is that instead of opening new session tab we will need to open new session window - instead of having several tabs we will have several sessions. is it so?
Should it be that way, I can live with the clutter ....
Thanks again.
CT
