### ISSUE TITLE
Show http(s) and www in address bar

### ISSUE THREAD

**Issue by mb300sd** [brave/brave-browser#9884] opened 2020-05-21 23:54 UTC
## Description 

Biggest annoyance with chrome. And now they have removed the flags that disabled the "feature". Please allow us to display http(s) and www in the URL.

## Steps to Reproduce

Run Brave

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1809 (Build 17763.1217)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Poopooracoocoo** [comment] 2020-05-22 06:05
pretty sure bromite has a patch for this. I think a user facing option in privacy to opt out of http and www elision would be the best solution though

**Comment by Johann999** [comment] 2020-05-22 13:46
is corrected in Chromium Ver. 83.0 (Flag Context menu show full URLs)

**Comment by Poopooracoocoo** [comment] 2020-05-22 14:13
@Johann999 but there's nothing for Android.

**Comment by bsclifton** [comment] 2020-05-22 16:33
Thanks for the report - closing as a duplicate of https://github.com/brave/brave-browser/issues/7449

**Closed by bsclifton** 2020-05-22 16:33 UTC
