### ISSUE TITLE
Extend information on `Ad diagnostics` tab

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#20992] opened 2022-02-09 12:37 UTC
Need to add more information to help in finding of ads delivery issues.

Following data could be added:
- Detected subdivision code

**Comment by tmancey** [comment] 2022-02-15 20:31
Closing issue as a duplicate of https://github.com/brave/brave-browser/issues/17393. See `GetState country and subdivision code`

**Closed** 2022-02-15 20:32 UTC
Labels: closed/duplicate, enhancement, feature/ads, OS/Android, OS/Desktop
