### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by cleberpublitz** [brave/brave-browser#40332] opened 2024-08-07 14:37 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.68.134 Chromium: 127.0.6533.88
Operating System: Mac OS X 14.5.0

URL (if applicable) where crash occurred:
https://bluemed-hom.viva.care
Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. open https://bluemed-hom.viva.care
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/c1220b00-3db3-650c-0000-000000000000

**Comment by rebron** [comment] 2024-08-07 19:08
@cleberpublitz Can you update to 1.68.137 and let us know if you're still seeing the crash?

**Comment by cleberpublitz** [comment] 2024-08-12 14:00
> @cleberpublitz Can you update to 1.68.137 and let us know if you're still seeing the crash?

yes, i still seeing the crash.

**Comment by cleberpublitz** [comment] 2024-08-12 20:37
@rebron its works when disabled IPFS, this issue is related to https://github.com/brave/brave-browser/issues/40102.

**Comment by bsclifton** [comment] 2024-08-13 22:23
Closing as duplicate of https://github.com/brave/brave-browser/issues/40102 - thanks for confirming, @cleberpublitz! 

We have a fix for this coming soon for Release channel. Beta and Nightly are already good to go

**Closed** 2024-08-13 22:24 UTC
Labels: crash, priority/P2, OS/Desktop
