### ISSUE TITLE
Large gaps under Tabs (New tab design)

### ISSUE THREAD

**Issue by cybbro** [brave/brave-browser#34218] opened 2023-11-09 07:49 UTC
## Description 
Brave browser new giant tabs have a very big gap below them. (On Ubuntu 23.10).

![image](https://github.com/brave/brave-browser/assets/10908092/6f091348-c454-46c1-9c94-f60df7db3a69)

## Expected result:
Way smaller gap.

## Brave version (brave://version info)
Brave | 1.61.69 Chromium: 119.0.6045.124 (Official Build) beta (64-bit)
Revision | 802f2a3dd5b30780d7195156af577bc455f97ce9
OS | Linux

**Comment by rebron** [comment] 2023-11-10 19:21
Dupe of this issue possibly and fixed in latest nightly 1.62.x : https://github.com/brave/brave-browser/issues/34229

**Closed** 2023-11-10 20:28 UTC
Labels: feature/tabs-bar, OS/Desktop

**Comment by rebron** [comment] 2023-11-21 18:37
@cybbro Wanted to make sure you were ok with the spacing. Change is in 1.62.41 and higher in Nightly.

**Comment by cybbro** [comment] 2023-11-22 07:43
> @cybbro Wanted to make sure you were ok with the spacing. Change is in 1.62.41 and higher in Nightly.

Oh yes! Everything is perfect now! Thank you!
