### ISSUE TITLE
Don't open webtorrent in tor windows

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1134] opened 2018-09-14 23:46 UTC
Using the BitTorrent protocol over Tor results in poor performance and poor privacy. When using Tor, `.torrent` files should not be opened with webtorrent — instead, they should just be downloaded like any other file. Magnet links should result in a privacy warning. If the user choses to proceed, they could either be opened in-browser or in a desktop client. To reduce linkability, perhaps, Magnet links should be added to webtorrent but not opened until a short while after the Tor session ends

**Comment by srirambv** [comment] 2018-09-29 13:45
`.torrent` files open webtorrent on Tor windows.

**Comment by diracdeltas** [comment] 2018-09-29 22:30
Changing this issue to reflect that webtorrent should not be enabled for Tor at all

**Comment by riastradh-brave** [comment] 2018-10-03 16:07
Marking this as a release blocker since torrents are a leak and this would be a regression from browser-laptop.  Looks like @yrliou is on top of it, will take a look when the PR is ready.

**Closed** 2018-10-03 20:27 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, browser-laptop-parity, feature/tor, feature/tor/leakproofing, feature/webtorrent, release/blocking

**Comment by btlechowski** [comment] 2018-10-10 16:49
Verification passed on

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Windows 7

Used test plan from https://github.com/brave/brave-core/pull/554

**Comment by kjozwiak** [comment] 2018-10-11 04:43
@yrliou when there's no applications associated with `magnet links`, clicking on a magnet link won't do anything under Tor, meaning there's no feedback. I think we should add some type of warning/modal window that tells the user that webtorrent isn't supported under Tor if the user doesn't have a third party application installed.

Here's an example of what we did with browser-laptop (muon):

<img width="929" alt="screen shot 2018-10-11 at 12 42 29 am" src="https://user-images.githubusercontent.com/2602313/46781250-b07c0280-ccee-11e8-8df6-4cfe4f6421bc.png">

Thoughts?

**Comment by tomlowenthal** [comment] 2018-10-11 19:44
What happens when you click a link which has no handler installed in general?

**Comment by riastradh-brave** [comment] 2018-10-12 22:50
> ...that tells the user that webtorrent isn't supported under Tor if the user doesn't have a third party application installed.

Nit: We don't support webtorrent under Tor _at all_, and I wouldn't recommend using a third-party application to make it work automatically either unless you want to shoot yourself in the foot.

**Comment by Teit0** [comment] 2020-05-05 08:34
Currently there doesn't seem to be an option to **not** use Brave to manage magnets. I already have a Torrent client.

**Comment by bsclifton** [comment] 2020-05-05 21:31
@Teit0 I believe you need to visit brave://settings/extensions

And then you can disable `WebTorrent` extension
![Screen Shot 2020-05-05 at 2 31 26 PM](https://user-images.githubusercontent.com/4733304/81118089-1e91a700-8edd-11ea-9db6-0f49f3a27854.png)
