### ISSUE TITLE
Support Linux aarch64

### ISSUE THREAD

**Issue by robd003** [brave/brave-browser#20294] opened 2022-01-02 21:43 UTC
I'd like to run Brave on an ARM based Linux laptop. These are becoming more popular with the HP Elite Folio, Lenovo Yoga and Microsoft Surface Pro all using ARM chips and easily able to run Linux.

Could you guys please build aarch64 binaries in 2022?

**Comment by AlexTalker** [comment] 2022-01-10 17:42
Duplicate of #11836 ?

**Comment by bsclifton** [comment] 2022-01-10 20:58
Yup- definitely a dupe, thanks @AlexTalker 😄 

@robd003 please subscribe to https://github.com/brave/brave-browser/issues/11836 for more updated information

**Closed by bsclifton** 2022-01-10 20:58 UTC
Labels: OS/Desktop
