### ISSUE TITLE
Appearance of Shields controls is dependent upon Rewards Icon being visible

### ISSUE THREAD

**Issue by kaytwo** [brave/brave-browser#21935] opened 2022-03-28 18:58 UTC
## Description 

Appearance of Shields controls is dependent upon Rewards Icon being visible.

## Steps to Reproduce

   1. Disable "Show Brave Rewards icon in address bar" setting
   2. Open a site where there should be a Shields icon
   3. Icon does not appear

## Actual result:

If rewards is on, shields is visible. If rewards is off, shields is invisible (only share action visible on right edge of URL bar)

## Expected result:

Shields should be visible & usable even if you disable the rewards icon.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Not broken yet on Current:

Brave | 1.36.122 Chromium: 99.0.4844.88 (Official Build) (64-bit)
-- | --
Revision | 55132f110218a75dc6a4c2c20269efd6e3059177-refs/branch-heads/4844_73@{#2}
OS | Windows 11 Version 21H2 (Build 22000.588)

Broken on Beta and Nightly:

Brave | 1.38.67 Chromium: 100.0.4896.46 (Official Build) beta (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.588)

Brave | 1.39.5 Chromium: 100.0.4896.46 (Official Build) nightly (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Windows 11 Version 21H2 (Build 22000.588)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
No
- Can you reproduce this issue with the beta channel? 
Yes
- Can you reproduce this issue with the nightly channel? 
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
N/A (Shields cannot be disabled when this bug happens)
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
N/A

**Comment by stephendonner** [comment] 2022-03-28 19:05
Dupe of https://github.com/brave/brave-browser/issues/21830

**Closed by stephendonner** 2022-03-28 19:05 UTC
Labels: OS/Desktop
