### ISSUE TITLE
Add extensions to Tor windows

### ISSUE THREAD

**Issue by ashrafhadden** [brave/brave-browser#2761] opened 2018-12-30 07:56 UTC
## Description 

Brave only has extensions in regular windows, not Private or Tor. Navigating to `chrome://extensions/`in Private window takes you back to `chrome://extensions/` in regular window. Navigating to `chrome://extensions/`in Tor window takes you to blank page with `Extensions is not available to Guest users.` on it.

## Brave version (brave://version info)

Brave | 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X
JavaScript | V8 7.1.302.31
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

Brave | 0.60.5 Chromium: 72.0.3626.28 (Official Build) dev (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Mac OS X
JavaScript | V8 7.2.502.13
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.28 Safari/537.36

### Reproducible on current release:
- Release: **Yes**
- Dev: **Yes**

**Comment by Techguyprivate** [comment] 2018-12-30 10:15
Allowing extensions in private windows or tor  may leave browsing history , traces, cache, cookies & other things . Look at the warning in the picture below. I don't know with high certainty though.
![screenshot from 2018-12-30 15-41-46](https://user-images.githubusercontent.com/43615747/50546182-59b20500-0c1b-11e9-8e9a-56f062b469b0.png)

**Comment by ashrafhadden** [comment] 2019-01-05 01:08
Totally forgot about that hidden toggle, thanks a bunch!

**Comment by rebron** [comment] 2019-01-08 19:52
cc: @posix4e do you have an update?

**Comment by posix4e** [comment] 2019-01-08 20:45
Yep we have been working for this and we have something soon. I'll have my friend helping speak up on the issue.

**Comment by durch** [comment] 2019-01-08 20:50
For sure, started looking into adding privacy pass for tor

**Comment by posix4e** [comment] 2019-01-08 20:55
@durch Is my friend helping on the project.

**Comment by tomlowenthal** [comment] 2019-01-10 21:44
The controls should eventually be the same for Tor windows — just another toggle. But to do that, we ned to get a way from from using guest windows as the basis for Tor, and rebuild them as another type of session more like regular private windows.

**Comment by posix4e** [comment] 2019-01-10 23:09
@tomlowenthal So confirming the steps are

- [ ] Rewrite the tor browser mode to work like private mode and remove the existing tor code
- [ ] Add the ability to add an arbitrary extension to brave tor
- [ ] Add privacy pass extension by default in tor mode. Should we support it with other modes as well? 

Do we wanna install this extension by default, or just keep brave users hitting a ton of captchas til they install the extension?

**Comment by ashrafhadden** [comment] 2019-01-11 03:54
@posix4e I hate captchas and I wasn't even aware of [Privacy Pass](https://chrome.google.com/webstore/detail/privacy-pass/ajhmfdgkijocedmfjonnpjfojldioehi) until you mentioned it, and now that you did I'm definitely installing! :sweat_smile:

I think we can safely assume that users would prefer a default installed extension to having to solve numerous captchas to the point of frustration and then only _**possibly**_ researching for a solution (most would probably remain ignorant like myself). TorBrowser does the same thing with the "HTTPS Everywhere" extension and many others. Also, Privacy Pass is [BSD-3 open source](https://github.com/privacypass/challenge-bypass-extension/blob/master/LICENSE).

**Comment by posix4e** [comment] 2019-01-11 04:35
After further the discussion we will 
- add in privacy pass support by default into tor mode, and hopefully spruce it up so it’s nice
- we will simultaneously add extension support while keeping a close lookout for security and privacy related issues as we go

**Comment by moo-im-a-cow** [comment] 2019-01-23 14:14
i came here to request extensions in tor just so that i could add privacy pass
tor mode on the light web is literally unusable because of the cloudflare recapcha, which most of the time doesnt even let you complete the capcha, because the ip had already been spamming them and they flat out blocked it

**Comment by durch** [comment] 2019-02-26 20:53
Just an update, we're ramping up here, hopefully we'll have something to show soonish :)

**Comment by proteo** [comment] 2019-03-05 05:31
Looking forward for this, thanks!

**Comment by rulatir** [comment] 2019-06-08 14:32
Any progress?

**Comment by gilhrpenner** [comment] 2019-07-20 16:52
Any progress?

**Comment by durch** [comment] 2019-07-22 08:13
We have a PR to add the Privacy Pass extension here -> https://github.com/brave/brave-core/pull/2576. Extensions in TOR are WIP here -> https://github.com/brave/brave-core/pull/2724, once both of those wrap up PP will be a part of Brave and will be usable in both Private and Tor modes.

**Comment by rulatir** [comment] 2019-07-31 11:52
"Once both of those wrap up" is a rather fuzzy estimate.

**Comment by rulatir** [comment] 2019-08-23 14:17
"Once these two prerequisites that have been stalled for months without any sign of progress are satisfied, we will have this feature like immediately-ish".

**Comment by SHHSSH** [comment] 2019-12-04 08:40
Any update on this? We understand the preliminary cautions that should be taken, but for rather secure extensions e.g; NoScript, just as it's in TOR Browser. This would be an added benefit to be available in Brave TOR Windows.

**Comment by desmonk** [comment] 2020-02-23 11:37
Seriously? No progress in over a year now? 

Seems like Brave is a gimmick to me as you should let users choose from what they want to do with extensions. Even the official Tor Browser does not disallow this. Also, those who use Tor Browser are likely to be aware about such privacy implications.

Honestly, after reading your latest **blog entry**, seems like Brave is sleeping with advertisement authorities.

_"Hide Privacy-Harming Ads, But Leave Privacy-Respecting Ones
While Brave uses many of the same filter lists that other tracking and ad blocking tools use, Brave’s mission differs from existing filter list using tools; Brave aims to protect privacy and browsing aesthetics, without harming sites that are privacy-respecting. Put differently, Brave aims to block third-party trackers and ads (which are, in practice, often indistinguishable), without affecting solely first party ads."_

Let the users decide.

![IMG_02323](https://user-images.githubusercontent.com/55331939/75111363-d2023380-5630-11ea-8777-709218d5ff40.png)

**Comment by bsclifton** [comment] 2020-03-02 21:57
No update as of yet; I shared with team. Will ask if someone can update. I know that no progress has been made in one year, but every issue (we have over 2,100) has a priority and work is done in that order

Pull requests are welcome if folks have cycles to handle this

**Comment by desmonk** [comment] 2020-03-11 17:05
Hope something's been done about it soon. I know about project priorities but it is a practice followeded by major browsers and only Brave seems to move in other direction with no supportive answer so far to not do this.

**Comment by chetanpm** [comment] 2020-03-17 03:17
Countries censor websites people want to browse >> people use tor >> cloudfare, apparently hosts almost all these sites and won't allow tor browsers to access even when we are not a bot! 


Brave's tor window is turning out to be very limitedly useful without the ability to use extension to bypass the terrible captchas.

**Comment by rvklein** [comment] 2020-05-14 05:53
I am fully aware of the privacy implications of allowing certain extensions to run within a Tor session. Being able to override this even with a big fat warning dialog popping up would be nice. Really nice. 

It would also be really nice to not have my accessibility tools needlessly taken away from me just for wanting to browse the web more securely. I guess I'll just go back to Firefox when trying to do that for the time being. Oh well.

Hope this gets fixed soon. I'd prefer that my user preference(s) be respected by a piece of software such as a web browser... sometimes even if my preferences are a bad idea.

**Comment by SHHSSH** [comment] 2020-05-15 02:57
@rvklein Does Brave not even allow noscript in tor windows?

**Comment by bsclifton** [comment] 2020-05-15 06:48
@SHHSSH you can should be able to disable scripts on a per-host basis, but the disabling is not remembered

**Comment by SHHSSH** [comment] 2020-05-20 03:03
@bsclifton How would that really function for forward browsing though? You'd need a whitelist that is defaulted to allow incoming scripts, otherwise it would work too well by defaulting to disable incoming scripts, therefore the site malfunctions. Anyone could manually enable the required components, but it becomes tedious.

Sure, if you're just using the one site it's no issue, but if you're browsing it's a different story. Now I know some may think, who browses on TOR? Isn't that contradicting of its main purpose to a degree? Well, like you somewhat indicated, if you're prioritising a particular site you'd become accustom to trusting links from sources, hence external/forward browsing.

All this could be resolved by allowing *certain* extensions to be enabled in TOR Windows. Are there any other discussions or documentation that Brave, as a team, has briefed and touched upon in regards to TOR Windows? Is it a little under the rug atm?

**Comment by NuBz-GeN** [comment] 2020-11-06 19:37
Over a year later and this still doesn't work.

**Comment by bsclifton** [comment] 2020-11-06 20:32
@NuBz-GeN there are a lot of things to work through and this does have a priority set (relative to other priorities). There was a person working on this over a year ago but that work had been put on hold.

cc: @darkdh who has been solving other Tor issues and @diracdeltas who is familiar with prior work done

**Comment by NuBz-GeN** [comment] 2020-11-07 00:51
I totally understand that, I guess I  worded my curiosity about it
incorrectly.
If i really need tor to block ads so badly there's always the browser from
torproject which brave recommends we use if it is something important
anyway.

Thank you for the response.

**Comment by bsclifton** [comment] 2020-11-10 06:13
I believe @darkdh is looking at this now

**Comment by darkdh** [comment] 2020-11-10 18:51
Currently working on moving tor from session profile to OTR profile (https://github.com/brave/brave-browser/issues/12429) which will be the ground work for extension support. So I will work on this issue next.

**Closed** 2020-12-15 20:55 UTC
Labels: OS/Desktop, QA/Test-Plan-Specified, QA/Yes, feature/extensions, needs-discussion, priority/P4

**Comment by shengchalover** [comment] 2020-12-16 11:24
Wow, two years in and we finally nearing the point extensions are allowed in Tor private tab. Kudos to everyone!

Question: why extensions will not route their traffic through tor? 

![](https://user-images.githubusercontent.com/11330831/102145065-78673180-3e1b-11eb-96b3-78b4e649b3d1.png)

**Comment by bridiver** [comment] 2020-12-16 18:16
@shengchalover extensions operate in one of two modes: split or spanning. In split mode there is a separate extension process for regular, tor and private modes. In spanning mode there is a single process which is attached to the regular profile. The extension itself specifies spanning or split mode (spanning is the default) and many extensions wouldn't function properly if we forced them into split mode (another option we looked at). This is exactly how it works in Chrome for regular/private mode, they just don't bother to tell you about it.

**Comment by bridiver** [comment] 2020-12-16 18:21
also @shengchalover that warning only appears for spanning mode extensions

**Comment by shengchalover** [comment] 2020-12-16 20:19
@bridiver thanks for the input. Is that possible to create a separate toggle to force spanning mode extensions into split mode? Users can then test extensions individually and keep those that work properly. The warning would notify them that this toggle may break extension. Possibly a better option rather then allowing all spanning extensions to do what they want in Tor mode.

**Comment by bridiver** [comment] 2020-12-16 20:27
@shengchalover unfortunately forcing split mode requires quite a bit of upstream patching which was the other part of the reason we went with the warning. We just can't justify the maintenance cost of the patches for such a niche use case. Remember that this only applies if the extension itself is making any network requests or storing other data about your Tor browsing history. We always display the warning because we don't know if the extension is making any requests or not.

**Comment by shengchalover** [comment] 2020-12-16 20:55
@bridiver I was mainly interested in the design considerations that lead to such warning, thanks for clarifying.

In a sense Brave positions itself as privacy preserving browser, so if some features harm the characteristics of the anonymizing layer a bit that should not be a big deal.

Having a Tor network one click away from the main browser window is very handy and eliminates the need for vpn in lots of cases. I am truly glad we now one step closer in making the tor-browsing experience more smooth. Can't wait to run PrivacyPass, 1Password and DarkReader in a Tor tab!

Thanks again for the hard work on bringing this proposal to life!

**Comment by stephendonner** [comment] 2021-01-28 20:55
Verified, following the testplan from https://github.com/brave/brave-core/pull/7304

Brave | 1.20.93 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 11.1 (Build 20C69)

1. added https://chrome.google.com/webstore/detail/1password-extension-deskt/aomjjhallfgjeglblehebfpbcfeobpgk/related?hl=en to Brave Dev
2. clicked on "hamburger" menu -> extensions
3. clicked details
4. enabled Allow in private
<img width="894" alt="Screen Shot 2021-01-28 at 11 41 03 AM" src="https://user-images.githubusercontent.com/387249/106194663-fb421280-6163-11eb-9f84-ce549bd5cf2f.png">

5. file -> New Private Window with Tor
6. opened browser-profile folder, `extensions`, `aomjjhallfgjeglblehebfpbcfeobpgk`
7. chose Duplicate, copied to `~/Downloads/`
8. opened `4.7.5.90_0`
9. edited `manifest.json` to have `"incognito": "split",` saved 

<img width="670" alt="Screen Shot 2021-01-28 at 11 07 57 AM" src="https://user-images.githubusercontent.com/387249/106196451-4bba6f80-6166-11eb-95fd-1aab85364c53.png">

10. enabled Developer mode toggle 
11. clicked Load unpacked, pointed to newly copied and modified `manifest.json`
12. clicked on "hamburger" "menu -> extensions 

<img width="942" alt="Screen Shot 2021-01-28 at 11 32 51 AM" src="https://user-images.githubusercontent.com/387249/106194347-8b338c80-6163-11eb-8179-a21388dbf5c8.png">

13. file -> New Private Window with Tor
14. signed in to 1Password in Brave
15. loaded `wellsfargo.com` and confirmed that 1Password was available for the site, in the Tor Private Window

<img width="1149" alt="Screen Shot 2021-01-28 at 12 14 26 PM" src="https://user-images.githubusercontent.com/387249/106194646-f67d5e80-6163-11eb-8e48-e8b5bf5f3341.png">

**Comment by jawadalkassim** [comment] 2021-02-10 21:04
Privacy Pass is not working in TOR and Private mode still stuck on CAPTCHA page but its working in Default normal mode
