### ISSUE TITLE
Intrusive wireguard software installation on startup

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [brave/brave-browser#33592] opened 2023-10-12 13:01 UTC
To reproduce:

   1. do nothing. not even updating. just keep brave sitting idle opened in taskbar
   2. ??
   3. brave installs wireguard vpn and adds a startup entry in windows. windows notification popus that software has been installed and running on startup without my consent

## Desktop Brave version:
already updated brave (so i don't know which exactly was before), but i was on the previous version before Version 1.59.117 Chromium: 118.0.5993.70. so probably i was on [Release v1.58.137 (Chromium 117.0.5938.153)](https://github.com/brave/brave-browser/releases/tag/v1.58.137)

Looking in registry it adds:
"C:\Program Files\BraveSoftware\Brave-Browser\Application\118.1.59.117\BraveVpnWireguardService\brave_vpn_wireguard_service.exe" --interactive

I know vpn can be disabled from brave > system settings, but i never agreed to install this in the first place and a new process should not run especially for no reason unless I am actually using brave vpn..

**Comment by klepp0906** [comment] 2023-10-13 01:30
I dont think the setting within brave disables the VPN, i think that just disables using wireguard as the protocol.

i remember seeing the notification and forgot about it but just started noticing a ton of dns errors and failures on sites and remembered, looked, and am now looking at how to undo this monstrosity.

**Comment by bsclifton** [comment] 2023-10-18 18:05
Hi folks - thanks for the report. I characterized this problem just now in this issue:
https://github.com/brave/brave-browser/issues/33726

I'm going to close this issue out as a duplicate. Please subscribe to https://github.com/brave/brave-browser/issues/33726 for updates - I'll be triaging with team. Thanks!

**Comment by Ticks-mentracorps-menti-TEMP** [comment] 2023-10-18 18:05
They are already aware of this and will work on this https://github.com/brave/brave-browser/issues/33726 the problem is no Nightly or Beta or Dev user reported the issue and it 'leaked' to Stable.

One way to avoid this behavior, and reason why I never noticed is because I don't install Brave with admin rights.

You either use the Silent installer which will automatically make a Per User install, or when normal installation asks about admin rights say no and it will ask you if you want to continue without admin rights.

But this way Brave can't install services, no update or VPN service, the only thing being added by Brave is an startup process for the updater which can be easily disabled in Task Manager and the same two tasks in the Task Scheduler.

People shouldn't install browsers with admin rights anyway, unless you are sharing your computer with someone else and has many accounts and you don't want to re-use space for all users wanting to use the same Browser.

Not an excuse, Brave should have noticed this and Nightly, Beta and Dev users should have reported it before, the ones who run Brave with admin rights for all users, not the ones like me who never noticed the service being installed because of non-admin rights.

All you can do is uninstall Brave, wait some minutes until even updater gets removed (if not it will get messy), maybe you go to Task Scheduler and run the tasks manually. Once they are removed, you can install without admin rights.

This will not get fixed tomorrow, but it will get fixed soon. It is not like it will harm your computer, but it's understandable why this shouldn't happen, of course, there is also the updater service.

Also, use Autoruns or manually disable the services if not wanting to do this Per User installation.

And no, you won't lose any data, User Data is the one holding the information, you can run Brave in any part of any disk, and it will always pick the User Data. Only if you change build, like from Stable to Nightly, you will have to rename the User Data to be able for Browser to re-pick it.

Brave-Browser to Brave-Browser-Nightly or Brave-Browser-Beta for example.

People making drama about this is a problem, not making excused for Brave but people can actually avoid this if they stop installing their browsers with admin rights when it is not necessary 99% of the time.

**Closed by bsclifton** 2023-10-18 18:05 UTC
Labels: OS/Windows, OS/Desktop

**Comment by sirmrgentleman** [comment] 2023-10-18 19:51
> don't install Brave with admin rights

I have never once seen it mentioned anywhere that Brave (or any other browser) can be installed if you click no on the UAC prompt. I click yes since that is what the browser asked me to do and I trust the Brave devs to not install spyware along with it.  I am not calling the VPN spyware, but it should not have been installed, especially not as a startup task, without my permission. The updater is fine as I want my browser to always be up to date. Also, I would not say that three comments in a GitHub issue could be considered drama.

**Comment by bsdinis1** [comment] 2023-10-19 07:20
I am formatting my drive and reinstalling Windows as I type this.
I just came here to say one thing, FUCK YOU

**Comment by bsclifton** [comment] 2023-10-20 16:21
Locking discussion - let's move comments over to https://github.com/brave/brave-browser/issues/33726
