### ISSUE TITLE
Dropping files onto New Tab doesn't work

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#887] opened 2018-08-30 07:22 UTC
Carried over from https://github.com/brave/browser-laptop/issues/10497

## Steps to reproduce
1. Open a new tab (verify it shows dashboard with tiles/time/# ads blocked/etc)
2. Try dragging any file (image, html file, etc) into browser
3. File does not open in browser

**Comment by rebron** [comment] 2019-02-06 18:50
Looks like this is fixed in 61.x. I can reproduce this issue in 60.x though.

**Comment by rebron** [comment] 2019-03-13 18:21
I closed this prematurely. Drag and dropping files works just not with new tab page.

**Comment by rebron** [comment] 2020-04-29 22:02
Closing. Verified this works on Windows and macOS. Used both image file and html file on New Tab page.

Brave | 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1903 (Build 18362.720)

**Closed by rebron** 2020-04-29 22:02 UTC
Labels: drag-and-drop, feature/new-tab, priority/P5
