### ISSUE TITLE
Webview crashes when opening bookmarked items

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#329] opened 2018-06-13 02:52 UTC
## Description 

Webview crashes when opening bookmarked items
## Steps to Reproduce

   1. Build release version from source
   2. Import bookmarks from attached bookmark file ([bookmarks_5000.zip](https://github.com/brave/brave-browser/files/2096447/bookmarks_5000.zip))
   3. Right click on 0-99 folder and click on `Open all (98) `
   4. Wait till all the bookmark loads in tabs, many tabs has webview crash

 ## Actual result:

Webview crashes when opening bookmarked items

## Expected result:
None of the opened tabs should have webview crash
## Reproduces how often: 

100%

## Brave version (about:brave info)

c84b457 (release build)

### Additional Information

No console logs for any webview crash 
may be related to #218

**Comment by emerick** [comment] 2018-08-02 15:29
@srirambv In light of the findings in https://github.com/brave/brave-browser/issues/481#issuecomment-409965884, I would retest by running from a command prompt or Windows Explorer. Results seem much better for me when I do that.

**Comment by emerick** [comment] 2018-08-03 13:47
Spoke with @srirambv and we think the non-native shell is the root cause as discussed above, so closing this issue. Will reopen if we ever encounter this while using `cmd.exe`.

**Closed by emerick** 2018-08-03 13:47 UTC
Labels: crash/webview, needs-investigation

**Comment by btlechowski** [comment] 2018-09-21 12:14
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

Checked all pages, no crash
