### ISSUE TITLE
NTP background selections should accurately reflect only the current selection

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#25379] opened 2022-09-13 18:19 UTC
## Description 
Selecting a gradient child item results in the Solid colors top-level option being selected.

## Steps to Reproduce

   1. Open NTP
   2. Select gradients
   3. choose a gradient

## Actual result:

<img width="480" alt="image" src="https://user-images.githubusercontent.com/741836/189979779-2277118f-e494-4d41-bbc1-47e5660b81e0.png">

## Expected result:
Gradients should be selected

## Version/Channel Information:

Nightly 1.45.23

**Comment by sangwoo108** [comment] 2022-09-15 08:59
Hi, @petemill ! I was trying to reproduce it but couldn't 😥. Could you try with clean profile if possbile? I'm wondering if there's something related to migration or other preference.

Also https://github.com/brave/brave-browser/issues/25380 too.

**Comment by sangwoo108** [comment] 2022-09-16 03:08
Hi @GeetaSarvadnya ! Could you possibly help me to reproduce this issue and https://github.com/brave/brave-browser/issues/25380 please? I was trying to reproduce them on Nighly and Development version, but I couldn't 😥

**Comment by rebron** [comment] 2022-09-23 19:21
I saw this earlier but I'm not seeing this in later builds.

Couldn't reproduce in:

Brave | 1.45.68 Chromium: 106.0.5249.55 (Official Build) beta (arm64)
-- | --
Revision | 4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
OS | macOS Version 13.0 (Build 22A5342f)
JavaScript | V8 10.6.194.11
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

**Comment by rebron** [comment] 2023-03-29 22:02
cc: @GeetaSarvadnya Can you see if you can reproduce. I couldn't reproduce in 1.45.68 and can't reproduce in 1.49.132

**Comment by GeetaSarvadnya** [comment] 2023-03-30 05:13
@sangwoo108  @rebron Issue is **NOT** reproducible on `Windows 10 x64 - 1.50.108`. 

```
Brave | 1.50.108 Chromium: 112.0.5615.39 (Official Build) (64-bit)
-- | --
Revision | a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}
OS | Windows 10 Version 21H2 (Build 19044.2728)
```

**Comment by rebron** [comment] 2023-07-25 15:47
Closing per last two comments.

**Closed by rebron** 2023-07-25 15:47 UTC
Labels: bug, QA/Yes, release-notes/include, needs-more-info, OS/Desktop, closed/works-for-me
