### ISSUE TITLE
[Linux] Black border around menus on desktop enviroments that do not use compositing

### ISSUE THREAD

**Issue by pitsi** [brave/brave-browser#39040] opened 2024-06-14 04:37 UTC
### Description

After the upgrade to 1.67, there is a big black border around every brave menu, e.g. the one on the right click as you can see in the screenshot below.

### Steps to reproduce

1. Make sure you are running a desktop enviroment (de for short) without compositing or with compositing disabled. Gnome is NOT such a de and I do not know about the other major ones.
2. Upgrade brave to 1.67.
3. Right click somewhere or click on the hamburger menu on the top right corner.

### Actual result

This. The light blue background is part of the page behind it.

![2024-06-14-070738_1280x1024_scrot](https://github.com/brave/brave-browser/assets/5880037/4e42723a-e7a6-492e-8a6a-17a30a3f2e55)

### Expected result

This, minus the dropped shadows.

![2024-06-14-071321_1280x1024_scrot](https://github.com/brave/brave-browser/assets/5880037/82a59af7-908d-41c9-9751-d4907c40eb5f)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave	1.67.115 Chromium: 126.0.6478.56 (Official Build) (64-bit) 
Revision	e1f8b4850805c2eea958bad7220c5e6e9202efaa
OS	Linux
```

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Theoritically, the above is just this gtk4 issue. And this brings the question: was brave built with gtk4 for 1.67? Its dependencies still mention libgtk-3-0 though and it also follows my gtk3 theme.
https://gitlab.gnome.org/GNOME/gtk/-/issues/4815
(please notice the gnome dev's comments there, i.e. "don't disable your compositor")

Moreover, this is not dependant on the gtk3/4 theme. Excluding my beautiful dark theme (numix), I also tried that ugly bright one that comes as the default in gnome (adwaita), but the result was the same. I am not a gnome user, I left it on 2009 when it was still at its **2**.2x versions and I never looked back.

Last but not least, I can not test it on chromium 126 because it has not reached my repo yet.

**Comment by willbprog127** [comment] 2024-06-14 16:14
I am also seeing this, with or without graphical acceleration turned on.

Debian 12 x86_64, Fluxbox, AMD Radeon 540/540X/550/550X / RX 540X/550/550X

**Comment by pitsi** [comment] 2024-06-14 16:32
Since fluxbox does not do compositing, please install a compositing manager like compton, launch it and notice the difference.

Openbox user here, for more than a decade, who wanted to move to fluxbox a few months ago :P

**Comment by willbprog127** [comment] 2024-06-14 16:34
Thanks for the reply. :smile: 
> please install a compositing manager like compton

No thank you.  I am using Fluxbox because I don't like compositing window managers, but I understand what you're saying. :+1:

**Comment by willbprog127** [comment] 2024-06-15 01:28
This issue is also present on non-compositing window manager on MATE desktop.  I do not want to use compositing window manager and other apps work fine.

**Comment by inicula** [comment] 2024-06-15 09:51
Also a problem on my Debian 12 + dwm setup. It was working fine prior to 1.67.

**Comment by pitsi** [comment] 2024-06-15 10:38
Small thing I noticed. Changing the theme to qt or classic under brave://appearance does not fix the issue because it just changes the colors of brave's theme.

**Comment by prss-ad** [comment] 2024-06-15 13:31
Same thing here. Using Qtile with picom, i see a semi transparent blurred shadow . Without picom a thick black border.
Tested with :
Brave Browser 126.1.67.116
Chromium 126.0.6478.55 Fedora Project (40)
![image](https://github.com/brave/brave-browser/assets/107325360/882923a7-7be5-4bce-97d4-ab2a89ea4f96)

**Comment by pitsi** [comment] 2024-06-15 14:32
I also used picom for my screenshot above (I chose one compositing manager at random), but it does not produce any blur on my end.

**Comment by pitsi** [comment] 2024-06-16 10:37
I tried a few workarounds I found here and there that involve editing  `~/.config/gtk-4.0/gtk.css` and  `~/.config/gtk-3.0/gtk.css` and setting the shadow radius to 0px, but nothing worked on brave.

On obfuscate and file-roller, the only gtk4 apps I have installed, the workaround seemed to work though.

**Comment by R0CKH0PP3R** [comment] 2024-06-16 11:58
To more clearly illustrate the regression from v1.66.118:
![brave_picom](https://github.com/brave/brave-browser/assets/49409328/4c2ec2c3-8328-4b7a-adfd-1356925101d5)

Note that the scale changed too.

Distro: Manjaro
Compositor: Picom
Desktop: XFCE4

**Comment by casaschi** [comment] 2024-06-20 09:41
Same issue here, ubuntu 22.04 with Xfce4.

**Comment by R0CKH0PP3R** [comment] 2024-06-21 11:39
Issue remains in v1.67.119.

**Comment by prss-ad** [comment] 2024-06-21 14:53
Yes , still there, running Brave Browser 126.1.69.30 nightly.

**Comment by R0CKH0PP3R** [comment] 2024-06-26 10:49
Issue resolved in v167.123 when using Picom. However, OP's issue remains in absence of compositor.

**Comment by R0CKH0PP3R** [comment] 2024-06-26 14:02
@prss-ad - You need to exclude the gtk frame extents in your picom config:

```
shadow-exclude = [
    "_GTK_FRAME_EXTENTS@:c"
];

blur-background-exclude = [ 
    "_GTK_FRAME_EXTENTS@:c"
];
```

**Comment by prss-ad** [comment] 2024-06-26 16:25
Thanks @R0CKH0PP3R  but that did not work for me, but this did: 

wintypes:
{
  menu = { opacity = 1.0; shadow = false; blur-background=false; }
};

**Comment by zksyncetester** [comment] 2024-06-29 13:01
![1](https://github.com/brave/brave-browser/assets/94652988/c30f76a1-7510-488b-aedd-5d20016f024c)
i have same problem when compositor sttoped google chrome dose not have this problem

**Comment by vargn** [comment] 2024-06-29 18:12
R0CKH0PP3R's solution worked for me. 

However, the context menu of Brave have a fade-in effect when activated. I tried modifying `picom.conf` to remove this effect and have the menu appear instantly, but I couldn't make it work. Anyone know if this is possible?

**Comment by prss-ad** [comment] 2024-06-29 18:20
@vargn  not really sure if this is a fix for you:
wintypes:
{
menu = { fade=false; shadow = false; blur-background=false; }
};

**Comment by pitsi** [comment] 2024-07-02 05:35
I would like to add that the problem is also visible on xfce with compositing disabled and that its "shadow" looks white like on the screenshot above, although it uses the same numix theme. Moreover, I tested it on chromium 126 and it does not happen.

**Comment by pitsi** [comment] 2024-08-22 17:08
1.69 seems to have finally fixed the issue. I checked it on both openbox and xfce.
If anyone else can confirm it, please do so as to close the issue.

**Comment by prss-ad** [comment] 2024-08-22 17:14
Seems so. Working fine with or without picom on fedora 40 with qtile.

**Comment by casaschi** [comment] 2024-08-22 17:15
1.69 fixed for me: xfce on ubuntu 22.04 on arm64

**Comment by bsclifton** [comment] 2024-08-22 22:48
Glad to see this is fixed! I'll go ahead and close the issue. But please do continue reporting back here after updating.

If anyone is still having the issue, we can collect more information and take a look. Thanks!

**Closed by bsclifton** 2024-08-22 22:48 UTC
Labels: bug, OS/Linux, OS/Desktop

**Comment by xuges** [comment] 2024-12-12 03:31
This is a GTK4 known issue when using without a compositor. Developer can use `gdk_display_is_composited()` function to check it, and can be use CSS to fix it.

example: 

popover contents {
	border: 1px solid rgb(150,150,150);
	border-radius: 0;
	box-shadow: none;
	margin-top: -12px;
}  

popover arrow {
	background: transparent;
	border-color: transparent;
}

see: https://bbs.archlinux.org/viewtopic.php?id=294262
