### ISSUE TITLE
Reddit tipping banner text alignment issue

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5447] opened 2019-07-30 12:33 UTC
## Description 

Reddit tipping banner text alignment issue

## Steps to Reproduce

   1. Open 0.68.113
   2. Open https://www.reddit.com/r/brave_browser/
   3. Click on inline Tip link on any Reddit post
   4. Content is not displayed completely in the post text field also a lot of empty space in Tip amount banner

## Actual result:

Reddit tipping banner text alignment issue

![image](https://user-images.githubusercontent.com/38657976/62128419-00fe3400-b2f2-11e9-8566-1e5c898babca.png)

the text `iO...` cuts off the banner in the post text field:

![image](https://user-images.githubusercontent.com/38657976/62129191-be3d5b80-b2f3-11e9-98df-8f4c3afafafb.png)

## Expected result:
the post text field content should be wrapped in the tipping banner

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @NejcZdovc

**Comment by LaurenWags** [comment] 2019-07-30 13:43
seems similar to https://github.com/brave/brave-browser/issues/4566

**Comment by kjozwiak** [comment] 2019-08-02 17:04
@NejcZdovc we should probably crop the banner when someone tips something large that might cause the above. Maybe implement a character limit of some type?

**Comment by NejcZdovc** [comment] 2019-08-02 17:06
yeah we should limit content height and just hide everything else

**Comment by NejcZdovc** [comment] 2020-04-10 13:15
closing as dupe of https://github.com/brave/brave-browser/issues/4566

**Closed by NejcZdovc** 2020-04-10 13:15 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards, priority/P4
