### ISSUE TITLE
Restore all from deleted publisher doesn't restore all 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1441] opened 2018-10-05 23:25 UTC
## Description 

Restore all doesn't get removed after restoring all deleted sites

## Steps to Reproduce

   1. Enable Rewards on 0.55.1
   2. Visit 8-10 sites so that its listed on the auto-contribute list
   3. Delete 2-3 sites from list 
   4. Click on `Show all` to see the full list of publishers
   5. Click on `Restore All` from the publisher window. Removed site gets added but still shows 1 excluded site

## Actual result:

![restore all1](https://user-images.githubusercontent.com/17010094/46564235-1a05a680-c8d4-11e8-9d0e-f3865bb90736.gif)

## Expected result:
Restore all should not show any value for excluded list. Defeats the purpose of restore all

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes on beta 
- Does it reproduce on browser-laptop? No. 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @LaurenWags @kjozwiak @NejcZdovc

**Comment by LaurenWags** [comment] 2018-10-08 15:50
Did not reproduce on macOS. After clicking 'Restore All' link the entire line went away and all sites were restored to the list.

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

![1441](https://user-images.githubusercontent.com/28145373/46619560-5f9ebb00-caf0-11e8-80ad-4a92255ca6e1.gif)

**Comment by jasonrsadler** [comment] 2018-10-09 13:14
@LaurenWags I think it happens when we have 11 or more sites.

**Comment by LaurenWags** [comment] 2018-10-09 14:09
@jasonrsadler hm, I tried with 12 sites on dev (I can't get more than 10 on Beta due to another issue) and I'm still not able to repro

Brave | 0.56.2 Chromium: 70.0.3538.35 (Official Build) dev (64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

![1441-part2](https://user-images.githubusercontent.com/28145373/46674965-70603700-cbab-11e8-85e4-a3644aa15b9f.gif)

**Comment by jasonrsadler** [comment] 2018-10-09 14:14
@LaurenWags disregard. I was reproducing on beta. Just tried again on dev macOS and seems to be working.

**Comment by LaurenWags** [comment] 2018-10-11 00:59
@srirambv @NejcZdovc @rebron Reproduced with steps from https://github.com/brave/brave-browser/issues/1441#issuecomment-428593480


Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Mac OS X

**Comment by LaurenWags** [comment] 2018-11-01 14:02
@jasonrsadler I definitely did not click x more than once, however I just tried the steps from https://github.com/brave/brave-browser/issues/1441#issuecomment-428593480 and was unable to reproduce the issue using 

Brave | 0.56.7 Chromium: 70.0.3538.77 (Official Build) beta(64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

**Comment by NejcZdovc** [comment] 2018-11-04 16:19
Will close this one and let's retest it in the latest master, where https://github.com/brave/brave-core/pull/797 will land as well

**Closed by NejcZdovc** 2018-11-04 16:19 UTC
Labels: bug, feature/rewards

**Comment by btlechowski** [comment] 2018-12-12 01:20
Verification passed on

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7 x64

Used Test Plan from https://github.com/brave/brave-core/pull/797
