### ISSUE TITLE
sometimes geolocation no longer working (uses old endpoints)

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11862] opened 2020-09-25 18:33 UTC
## Description 

Starting with 1.14.x geolocation no longer works on macOS Mojave. It seems on 1.13.x and prior we were proxying thru location.brave.com, however with 1.14.x that proxy doesn't seem to be there so geolocation fails.

Note, this is working for @kjozwiak using Catalina. Additionally, @btlechowski checked Linux and Windows and geolocation is working there as well.

## Steps to Reproduce

   1. Install any of the following: 1.14.81, 1.14.84 (current release), 1.15.x, 1.16.x.
   2. Navigate to https://browserleaks.com/geo and/or https://html5demos.com/geo/.
   3. Allow location from prompt.
   

## Actual result:

Location service fails:

<img width="1088" alt="1 14 81" src="https://user-images.githubusercontent.com/28145373/94303074-42609280-ff3b-11ea-9de0-576daf71ff03.png">
<img width="999" alt="1 14 84" src="https://user-images.githubusercontent.com/28145373/94303076-4391bf80-ff3b-11ea-919d-65f2a8ac45f9.png">

## Expected result:
Should work as it did in 1.13.86:
<img width="1127" alt="1 13 86" src="https://user-images.githubusercontent.com/28145373/94302996-265cf100-ff3b-11ea-9d03-49b74136118e.png">

## Reproduces how often: 

easy

## Brave version (brave://version info)

```
Brave	1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit)
Revision	ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS	macOS Version 10.14.6 (Build 18G3020)
```

```
Brave	1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)
Revision	a81aa729a8e1fd413943a339393c82e7b8055ddc-refs/branch-heads/4183@{#1864}
OS	macOS Version 10.14.6 (Build 18G3020)
```

```
Brave | 1.15.63 Chromium: 86.0.4240.55 (Official Build) dev (x86_64)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | macOS Version 10.14.6 (Build 18G3020)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes, 1.14.x
- Can you reproduce this issue with the beta channel? yes, 1.15.x
- Can you reproduce this issue with the nightly channel? yes, 1.16.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? no, used version 85.0.4183.121 (Official Build) (64-bit)

## Miscellaneous Information:

cc @rebron

**Comment by rebron** [comment] 2020-09-28 16:33
I'm able to reproduce the first screenshot in this version:

Brave | 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)
-- | --
Revision | a81aa729a8e1fd413943a339393c82e7b8055ddc-refs/branch-heads/4183@{#1864}
OS | macOS Version 10.16 (Build 20A5374i)

macOS version is wrong in that string though, I'm on 11.0 Beta (20A5374i)

Following your steps, our geolocation fallback is working on:

Brave | 1.15.61 Chromium: 86.0.4240.42 (Official Build) beta (x86_64)
-- | --
Revision | 418ccfc2b69112bd79d5ffb38b533642e64e6af8-refs/branch-heads/4240@{#773}
OS | macOS Version 10.16 (Build 20A5374i)


Brave | 1.16.41 Chromium: 86.0.4240.55 (Official Build) nightly (x86_64)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | macOS Version 10.16 (Build 20A5374i)

![Screen Shot 2020-09-28 at 9 29 56 AM](https://user-images.githubusercontent.com/5951041/94460189-3825da80-016d-11eb-89e5-9d4ac0660b09.png)

with the experimental brave://flags/#enable-core-location-implementation enabled, I'm getting the most accurate result starting with 1.15.x and 1.16.x (doesn't work in 1.14.x)
![Screen Shot 2020-09-28 at 9 21 13 AM](https://user-images.githubusercontent.com/5951041/94460446-994dae00-016d-11eb-86f8-14d6c0f5dee5.png)

**Comment by kjozwiak** [comment] 2020-09-28 18:47
I ran through the above on Friday and tried again today but couldn't reproduce the above on `macOS 10.15.6 x64 Catalina` using the following builds:

Using `1.16.43 Chromium: 86.0.4240.55` - **`PASSED`** (proxying through `location.brave.com`)

```
Brave | 1.16.43 Chromium: 86.0.4240.55 (Official Build) nightly (x86_64)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | macOS Version 10.15.6 (Build 19G73)
```

| https://browserleaks.com/geo  | https://html5demos.com/geo |
|:-------------:|:-------------:|
| <img width="1915" alt="Screen Shot 2020-09-28 at 2 19 30 PM" src="https://user-images.githubusercontent.com/2602313/94471071-8e5b4380-0196-11eb-97e5-4d9a2f268f3c.png"> | <img width="1914" alt="Screen Shot 2020-09-28 at 2 20 29 PM" src="https://user-images.githubusercontent.com/2602313/94471061-8b605300-0196-11eb-9338-eb0fc05940ac.png"> |

Using `1.15.65 CR: 86.0.4240.55` - **`PASSED`** (proxying through `location.brave.com`)

```
Brave | 1.15.65 Chromium: 86.0.4240.55 (Official Build) dev (x86_64)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | macOS Version 10.15.6 (Build 19G73)
```

| https://browserleaks.com/geo  | https://html5demos.com/geo |
|:-------------:|:-------------:|
| <img width="1908" alt="Screen Shot 2020-09-28 at 1 47 36 PM" src="https://user-images.githubusercontent.com/2602313/94471233-cd899480-0196-11eb-930d-44f481315952.png"> | <img width="1903" alt="Screen Shot 2020-09-28 at 1 49 27 PM" src="https://user-images.githubusercontent.com/2602313/94471227-ca8ea400-0196-11eb-9898-0eed75b028da.png"> |

Using `1.14.84 CR: 85.0.4183.121` - **`FAILED`** (not being proxies through `location.brave.com` and using `location.services.mozilla.com` instead)

```
Brave | 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)
-- | --
Revision | a81aa729a8e1fd413943a339393c82e7b8055ddc-refs/branch-heads/4183@{#1864}
OS | macOS Version 10.15.6 (Build 19G73)

```

| https://browserleaks.com/geo  | https://html5demos.com/geo |
|:-------------:|:-------------:|
| <img width="1870" alt="Screen Shot 2020-09-28 at 2 43 56 PM" src="https://user-images.githubusercontent.com/2602313/94472862-5e616f80-0199-11eb-9e38-74b72aaf3c91.png"> | <img width="1894" alt="Screen Shot 2020-09-28 at 2 45 00 PM" src="https://user-images.githubusercontent.com/2602313/94472852-5b667f00-0199-11eb-915e-fbbb4a7c19c4.png"> |

**Comment by LaurenWags** [comment] 2020-11-02 12:53
@rebron https://github.com/brave/brave-browser/issues/10724 doesn't have a test plan so I can't be 100% sure it's working as expected.

However, I can navigate to https://browserleaks.com/geo or https://html5demos.com/geo/ and geolocation works using Nightly.


Brave | 1.18.26 Chromium: 87.0.4280.40 (Official Build) nightly (x86_64)
-- | --
Revision | 349b9adbfb2784db684617c7731a57d1e61b3be0-refs/branch-heads/4280@{#863}
OS | macOS Version 10.14.6 (Build 18G6032)

**Comment by kjozwiak** [comment] 2020-11-18 05:04
Reproduced on `macOS 10.15.7 x64` using the following build (@iefremov also reproduced the issue):

```
Brave | 1.17.69 Chromium: 87.0.4280.60 (Official Build) (x86_64)
-- | --
Revision | 12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS | macOS Version 10.15.7 (Build 19H2)
```

As per the discussion via Slack, geolocations seem to be using the wrong endpoints. Once you've given macOS the needed permissions for Brave to use the Location Services, you'll get the following:

**`Example A`** | **`Example B`** | **`Example C`**
-----------------|------------------|-----------------|
<img width="433" alt="Screen Shot 2020-11-17 at 11 30 48 PM" src="https://user-images.githubusercontent.com/2602313/99485964-d1859780-2939-11eb-87b4-ddffda9111bf.png"> | <img width="705" alt="Screen Shot 2020-11-17 at 11 30 58 PM" src="https://user-images.githubusercontent.com/2602313/99485972-d4808800-2939-11eb-9702-8731809d0d76.png"> | <img width="1277" alt="Screen Shot 2020-11-18 at 12 04 15 AM" src="https://user-images.githubusercontent.com/2602313/99486100-01cd3600-293a-11eb-9d9e-5cc75182151c.png">



Please see https://bravesoftware.slack.com/archives/C7VLGSR55/p1605674399117500 for more context.

**Comment by kjozwiak** [comment] 2020-11-18 16:45
So it looks like it's now working with `1.17.70 CR: 87.0.4280.60`. However, the strange part is that `1.17.70 CR: 87.0.4280.60` doesn't include any fixes/code changes to anything related to geolocations. So it's possible that we have a bug in our build infra where sometimes it breaks and uses the wrong endpoint. @mihaiplesa @iefremov and @simonhong or taking a look to see what could have happened.

Removing from the `1.17.x` milestone and removing the `release/blocking` label.

**Comment by kjozwiak** [comment] 2020-12-02 00:46
Removing `OS/macOS` till we know 100% this only affects `macOS`.

**Comment by bsclifton** [comment] 2020-12-08 18:57
Talking with @simonhong - we think this must be related to the build. I'll try to verify also (haven't had a chance yet, apologies)

**Comment by kjozwiak** [comment] 2021-01-05 06:37
@bsclifton any updates on this one? Probably should figure this one out before we accidently release a build that breaks geolocation. We usually don't run through geolocation checks for minor CR/HF releases. Maybe we should add it them until we figure out the above?

**Comment by iefremov** [comment] 2021-01-05 15:02
@kjozwiak I guess the problem is not specific to geolocation, rather it is something general that affects CI. I.e. it easily can hit any other feature :D 

posting a link to slack discussion just for context and cc @mihaiplesa 
https://bravesoftware.slack.com/archives/C7VLGSR55/p1605716007144900?thread_ts=1605674399.117500&cid=C7VLGSR55

**Comment by mihaiplesa** [comment] 2021-01-06 18:44
@iefremov I've just fixed that issues and it only affected PR builds.

**Comment by mihaiplesa** [comment] 2021-01-15 17:48
This has been isolated to one of the release build nodes which had an old `/.npmrc` file overriding what was defined during the build process. Issue should be fixed with next builds for each channel.

**Comment by kjozwiak** [comment] 2021-01-15 17:50
Thanks @mihaiplesa 👍 Closing this off and we'll check it with the next RC. @brave/legacy_qa for the next few releases, including minor Chromium bumps, we should keep an eye on geolocation to make sure we're using the correct endpoints.

**Closed by kjozwiak** 2021-01-15 17:50 UTC
Labels: OS/Desktop, QA/Yes, bug, feature/geolocation, priority/P2, release/blocking

**Comment by iefremov** [comment] 2021-01-15 19:11
Thanks @mihaiplesa , good catch!!

**Comment by kjozwiak** [comment] 2021-01-18 18:56
Verification **PASSED** on `macOS 11.1 x64` using the following build:

```
Brave | 1.19.85 Chromium: 88.0.4324.89 (Official Build) (x86_64)
--- | ---
Revision | 4534be84786f5269fb52e9bf82643af61e2fedaf-refs/branch-heads/4324@{#1721}
OS | macOS Version 11.1 (Build 20C69)
```

Ensured that we're always using `location.brave.com` when requesting for geolocation permissions as per the following:

**`https://browserleaks.com/geo`** | **`https://html5demos.com/geo`**
---------------------------------------|---------------------------------------
<img width="1609" alt="Screen Shot 2021-01-18 at 1 01 07 PM" src="https://user-images.githubusercontent.com/2602313/104952961-83216300-5993-11eb-9c4a-fd92ddf937b1.png"> | <img width="1506" alt="Screen Shot 2021-01-18 at 1 03 39 PM" src="https://user-images.githubusercontent.com/2602313/104952970-86b4ea00-5993-11eb-989d-812ed437afb8.png">

**`https://www.lcbo.com (Before Request)`** | **`https://www.lcbo.com (After Request)`**
---------------------------------------|---------------------------------------
<img width="1456" alt="Screen Shot 2021-01-18 at 1 04 26 PM" src="https://user-images.githubusercontent.com/2602313/104953656-d0ea9b00-5994-11eb-9a8d-18a98e1cf2f8.png"> | <img width="1455" alt="Screen Shot 2021-01-18 at 1 04 41 PM" src="https://user-images.githubusercontent.com/2602313/104953668-d3e58b80-5994-11eb-9062-cf72c8e0f0e9.png">

**Comment by kjozwiak** [comment] 2021-01-18 18:59
@rebron mind checking this on your end as well when you have some time? The more people that check the better as this was dependent on the nodes that were used to build the releases. Want to make sure it's working for everyone 👍

**Comment by LaurenWags** [comment] 2021-01-20 14:27
@kjozwiak a little late but checked this on M1 and confirmed we're using `location.brave.com` when requesting for geolocation permissions.

```
Brave	1.19.86 Chromium: 88.0.4324.96 (Official Build) (arm64)
Revision	68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS	macOS Version 11.1 (Build 20C69)
```

<img width="1340" alt="Screen Shot 2021-01-20 at 9 23 39 AM" src="https://user-images.githubusercontent.com/28145373/105188264-b4b83c80-5b01-11eb-8175-d2321d4ea654.png">
