### ISSUE TITLE
Brave Crashed Twice - No Crash Report Sent

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#13723] opened 2021-01-22 15:32 UTC
Have you searched for similar issues? Yes

## Description 
I'm certain the crash I'm about to report has occurred twice though it may have happened three times already.

So quite often I open New Private Window without opening a normal window and when I want to run a private search I use Private with Tor Window and it is by having both these types of windows open that I noticed the crashes occur.

I also noticed after immediately opening a new normal window and checking brave://crashes showed that no report was generated which is why created this issue.

## Steps to Reproduce

   1. Open a Private Window with just a few tabs open
   2. Open a Private with Tor Window and go to Youtube and open a video
   
## Reproduces how often: 
I've seen this exact crash occur in almost exactly the same environment that past couple of days. I can't say 100% of the time though because I have used a private window and tor window simultaneously without issue. 

## Desktop Brave version:
Version 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit) (openSuse)
  
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? I'm not going to try
- Does the issue resolve itself when disabling Brave Rewards? I'm not going to try
- Is the issue reproducible on the latest version of Chrome? I'm not going to try

## Miscellaneous Information:

- 1 Ad per hour
- Auto-Contribute Off
- No signed into Crypto Wallets

**Comment by Johann999** [comment] 2021-01-23 14:25
I have the same issue.
After a crash  no crash report is created (brave://craches ist empty).

**Comment by kjozwiak** [comment] 2021-01-24 05:37
Just curious, is there anything in the following directory?
* `~/.config/BraveSoftware/Brave-Browser/Crash Reports`

**Comment by NumDeP** [comment] 2021-01-25 07:48
You mean right now? Not as of this moment; it's empty but I'll check again after another crash occurs.

**Comment by btlechowski** [comment] 2021-01-26 01:22
Crash reporting on Linux has been broken for quite some time.
Probably dupe of https://github.com/brave/brave-browser/issues/4296, but I will let @NumDeP decide.

**Comment by NumDeP** [comment] 2021-01-26 08:50
[On Linux chrome://crashes doesn't show crash reports](#4296) seems like a different issue though it interlinks. I suspect the engineers won't bother fixing that issue as it technically isn't the reason for the crash. However, it would be nice of them to fix them simultaneously. It just goes to show how well Brave has been working for us Linux users :)

@btlechowski Can I ask if you guys did happen to actually receive Linux crash reports, particularly this one, even though they weren't created on our side?

As for this particular issue, even though I was the first to create it, you should go ahead and close this in favour of [Crash on opening .onion link](#13736) as I'm positive it's identical and a couple of the main engineers are discussing the issue already.

**Comment by btlechowski** [comment] 2021-01-26 20:44
Closing in favor of https://github.com/brave/brave-browser/issues/13736

I think crash reporting is just broken on Linux https://github.com/brave/brave-browser/issues/4296

**Closed by btlechowski** 2021-01-26 20:44 UTC
Labels: OS/Desktop, OS/Linux, crash, needs-investigation
