### ISSUE TITLE
Disqus and Facebook embedded comments not working properly.

### ISSUE THREAD

**Issue by geekyBoogiepop** [brave/brave-browser#4450] opened 2019-05-14 23:39 UTC
## Description 
Cannot see more comments using "Show more replies" option with disqus.com or facebook embedded comments.

## Steps to Reproduce

   1. Go to https://www.xda-developers.com/oneplus-7-pro-review/ as an example.
   2. Find the "Show more replies" option.
   3. Click it.

## Actual result:

Not working. Just stay the same.

## Expected result:
Show more replies to the main comment.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

Brave | 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes, already updated to 0.64.75
- Can you reproduce this issue with the beta channel?
Not tested
- Can you reproduce this issue with the dev channel?
Not tested
- Can you reproduce this issue with the nightly channel?
Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No. It doesn't.
- Does the issue resolve itself when disabling Brave Rewards?
No. It doesn't.
- Is the issue reproducible on the latest version of Chrome? 
No. It isn't.

## Miscellaneous Information:

I'm not using any kind of extension, just vanilla brave. I'm using Ubuntu 18.04 (elementary 5.0) 64 bits. This issue happens on every site with disqus or facebook embedded comments, even though they are allowed in brave settings.
Another website with Facebook comments: https://animeflv.net/ (click any video, look comments).
The issue is not reproducible on either Chrome or Firefox, even using ublock origin.

**Comment by rebron** [comment] 2019-05-14 23:44
@geekyBoogiepop 
With your steps to reproduce: https://www.xda-developers.com/oneplus-7-pro-review/ I clicked on the 'Show more replies' option and nothing happened but I also saw that there were 19 comments and I counted that 19 comments were displayed. 

It doesn't look like there are any more replies to show. Can you check again?

**Comment by geekyBoogiepop** [comment] 2019-05-15 00:34
Yes, I checked, even with more articles. Already tested with firefox and chrome and the issue is not there.
Here you have more examples:
https://www.xda-developers.com/google-play-console-new-features-google-io-2019/
https://www.xda-developers.com/oneplus-oxygenos-user-feedback/
https://www.xda-developers.com/google-more-information-desktop-mode-android-q/

In the following image you can see the first article (google play console) using Firefox. After the guy 
wrote "No, it hasn't" the conversation is ongoing. These comments are not properly loaded in Brave. This also happens with facebook comments, but after upgrading to 0.64.75 this issue seems to be solved, but not with disqus. Thank you for replying.

![image](https://user-images.githubusercontent.com/32626891/57740735-828ce100-7676-11e9-852d-293048ab6c2b.png)

**Comment by ryanbr** [comment] 2019-06-01 02:55
The issue maybe with disqus, The first 2 of the  sample pages loaded fine. the 3rd page took a while to load disqus, then it did eventually loaded. 

At a guess its only intermittent because disqus is third-party server outside of xda-developers (and other sites). So if there is any issues/slowdowns at discord end, it affect any number of sites using it.

**Comment by ryanbr** [comment] 2019-06-04 19:41
@geekyBoogiepop is the issue still there?

**Comment by geekyBoogiepop** [comment] 2019-06-04 22:26
@ryanbr yes, it is still there. No issues on Firefox, Chrome, Vivaldi even using ublock.

**Comment by ryanbr** [comment] 2019-06-08 07:45
Heres a video I made, not sure what I'm missing; https://www.youtube.com/watch?v=hdMyI-466C

**Comment by ryanbr** [comment] 2020-12-09 11:06
@geekyBoogiepop   just revisiting this, site has changed a bit (more than a year since it was reported), was able to view posts on Disqus, on https://www.xda-developers.com/oneplus-7-pro-review/

**Comment by ryanbr** [comment] 2021-02-26 00:35
Closing, no issues with Brave, Disqus comments are loading fine. Facebook comments will load fine also (but brave://settings/socialBlocking  needs be enabled)

**Closed by ryanbr** 2021-02-26 00:35 UTC
Labels: feature/shields/webcompat, priority/P5
