### ISSUE TITLE
Disabled Brave ads but still getting notifications

### ISSUE THREAD

**Issue by itmecho** [brave/brave-browser#16674] opened 2021-06-29 08:27 UTC
## Description 
I have disabled brave rewards on both profiles I use but I still get notifications. I'm running Arch linux and installed from `aur/brave-bin`.

## Steps to Reproduce

   1. Go to rewards settings
   2. Disable ads

   3. I still get notifications

## Actual result:
I still get ad notifications.
![image](https://user-images.githubusercontent.com/8384983/123763275-85310b80-d8bb-11eb-87d9-2dc5babf87af.png)
![image](https://user-images.githubusercontent.com/8384983/123763324-90843700-d8bb-11eb-8b85-306224816394.png)

## Expected result:
Ad notifications should stop

## Reproduces how often: 
I've tried toggling the ads setting a few times but it doesn't make any difference. I still get multiple notifications per hour.

## Brave version (brave://version info)
```


Brave | 1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | Linux
JavaScript | V8 9.1.269.36
User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Command Line | /usr/lib/brave-bin/brave --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,LegacyTLSEnforced,DnsOverHttps,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,AutoupgradeMixedContent,SafetyTip --disable-features=HandwritingRecognitionWebPlatformApi,FledgeInterestGroups,InterestCohortFeaturePolicy,TrustTokens,DirectSockets,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,LiveCaption,AutofillServerCommunication,AutofillEnableAccountWalletStorage,FledgeInterestGroupAPI,TextFragmentAnchor,EnableProfilePickerOnStartup,IdleDetection,NotificationTriggers,WebOTP,SubresourceWebBundles,NetworkTimeServiceQuerying,LangClientHintHeader,InterestCohortAPIOriginTrial,FirstPartySets,SignedExchangeSubresourcePrefetch,SignedExchangePrefetchCacheForNavigations,FederatedLearningOfCohorts --flag-switches-begin --flag-switches-end
Executable Path | /usr/lib/brave-bin/brave
Profile Path | /home/iain/.config/BraveSoftware/Brave-Browser/Profile 2
Variations | AdServingStudy:MaximumAdNotificationsPerDay=60BraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0hBraveAds.UserActivityStudy:Triggers=EMPTY/Threshold=0.0/IdleTimeThreshold=5EphemeralStorageStudy:EnabledPermissionLifetimeReleaseStudy:Enabled

```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  ???
- Can you reproduce this issue with the nightly channel?  ???

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No 
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:
Installed from the AUR: https://aur.archlinux.org/packages/brave-bin.
```
Linux orion 5.12.12-arch1-1 #1 SMP PREEMPT Fri, 18 Jun 2021 21:59:22 +0000 x86_64 GNU/Linux
```

**Comment by rebron** [comment] 2021-07-06 17:02
cc: @tmancey

**Comment by tmancey** [comment] 2021-07-06 17:25
@itmecho hi. I work on the ads team here at Brave, would you be willing to sync up for a screen-share so I can help diagnose the cause? Thanks

**Comment by itmecho** [comment] 2021-07-07 07:59
Hi @tmancey, Sure!

**Comment by tmancey** [comment] 2021-07-16 14:53
@itmecho Can please email your available times to tmancey@brave.com. Apologies for the delay.

**Comment by tmancey** [comment] 2021-07-20 18:59
@itmecho can you please email me a screenshot of brave://rewards-internals, thank you

**Comment by itmecho** [comment] 2021-07-22 08:22
I've sent you an email.

I have 2 profiles which I have open together:

Profile 1:
![brave-rewards-1](https://user-images.githubusercontent.com/8384983/126609538-23c8ff14-cb03-4b07-925f-d2b342c2ae04.png)

Profile 2:
![brave-rewards-2](https://user-images.githubusercontent.com/8384983/126609658-0727c6cd-be62-43dd-95e9-e57805b820e5.png)

**Comment by tmancey** [comment] 2021-08-05 14:43
Hi
Hi

For each profile could you please send a screenshot of brave://rewards <brave://rewards> and also can you send a screenshot of the profile menu (expanded).

Thank you,
Terry

**Comment by tmancey** [comment] 2021-11-15 21:09
@itmecho I am unable to reproduce this issue. More than happy to jump on a call if you are still experiencing the issue. I will close this issue until I hear from you. Thank you, Terry

**Closed by tmancey** 2021-11-15 21:09 UTC
Labels: bug, priority/P3, QA/Yes, release-notes/exclude, feature/ads, OS/Desktop
