### ISSUE TITLE
After exiting Fullscreen, Vertical tab has graphical artifacts (macOS)

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#33816] opened 2023-10-23 01:03 UTC
Reporter: @Voldemorten

https://github.com/brave/brave-browser/issues/32183#issuecomment-1686082978

> Just wanted to update. When I do it on Version 1.57.47 Chromium: 116.0.5845.96 (Official Build) (x86_64)
Now the tabs are disappearing in vertical pane, and it looks like they somehow get "behind" the address bar. Then when you disable vertical tabs, they glitch in the top. Reenable vertical tabs and they appear horizontal in the vertical pane. Disable and reenable again, and we're back to normal.
> 
> I've uploaded a video of it here: https://youtu.be/hEtXWgdekYc

---

https://github.com/brave/brave-browser/issues/32183#issuecomment-1773493059

Reporter says that it happens again `[Version 1.59.122 Chromium: 118.0.5993.96 (Official Build) (x86_64)](https://brave.com/latest/)`, but Nightly seems fine.

---

I wasn't able to reproduce it myself. We should keep track of it.

**Comment by Voldemorten** [comment] 2023-10-23 06:33
Let me know, if you need any extra information or there's something I need to test out

**Comment by anthonytw** [comment] 2023-10-27 13:46
Same has been happening for me for a while (Intel Mac, Sonoma now but previous version as well).

**Comment by Voldemorten** [comment] 2023-11-15 08:44
It's also a problem when using osx' "Enter full screen" mode

**Comment by bsclifton** [comment] 2024-08-21 22:06
Marked this as a P2 - it can look like you lost your tabs.

In my case:
- vertical tabs enabled
- several pinned tabs
- maximize the window (green button)
- seems fine; tab contents is fullscreen
- click maximize again (green button) to restore

![image](https://github.com/user-attachments/assets/f34eb331-1a37-4241-99e5-2ded89756581)


At this point, there are graphical artifacts. *Also, no tabs are shown*.
If I quit and relaunch Brave, it's OK. The tabs were not lost.

**Comment by bsclifton** [comment] 2024-08-21 22:17
I'm going to close as I wasn't able to reproduce this issue... and the issue I found (above) seems to be related to Chromium 128

**Closed by bsclifton** 2024-08-21 22:17 UTC
Labels: OS/macOS, priority/P2, QA/Yes, feature/vertical-tabs
