### ISSUE TITLE
Enable shields panel on extension sites

### ISSUE THREAD

**Issue by mrzealot** [brave/brave-browser#2030] opened 2018-11-07 07:44 UTC
## Description 

A minor thing regarding extensions and Brave interaction is that the shields panel is always greyed out when visiting an internal chrome:// or chrome-extension:// protocol site, but blocking still works even on extension pages. The fact that the blocking works there too is great, but if the counter is non-zero, then imho the icon should be colored and clickable to show what was blocked, just like normal. 

## Steps to Reproduce

   1. Install an extension that accesses content on its own (i.e., chrome-extension:// protocol) site that would be blocked otherwise. (e.g., the Panda reader, haafibkemckmbknhfkiiniobjpgkebko)
   2. Visit its main site at chrome-extension://haafibkemckmbknhfkiiniobjpgkebko/index.html#/?module=panda5

## Actual result:

The shield icon (even though it's still greyed out) now shows the number of blocks it did.

## Expected result:
The shield icon should be colored and clickable to show blocking stats.

## Brave version (brave://version info)

Brave | 0.55.22 Chromium: 70.0.3538.77 (Official Build) (64-bit)
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows

### Reproducible on current release:
It's also reproducible on
Brave | 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows

**Comment by srirambv** [comment] 2018-11-07 14:10
cc: @tomlowenthal

**Comment by tomlowenthal** [comment] 2018-11-07 22:49
Dupe of #1380 .

**Closed by tomlowenthal** 2018-11-07 22:49 UTC
Labels: feature/extensions, feature/shields
