### ISSUE TITLE
[Desktop] Pinned tabs close on CMD + W

### ISSUE THREAD

**Issue by TanayB11** [brave/brave-browser#10432] opened 2020-06-23 18:57 UTC
##  Description 
Pinned tabs close when the user presses CMD + W. They should remain pinned to the side and not close until either the user right clicks to close te tab or un-pins the tab and then closes it.

## Steps to Reproduce

   1. Pin a tab (tab X)
   2. Open that tab X
   3. Press CMD + W for Mac or CTRL + W on Windows

## Actual result:
Tab X closes.

## Expected result:
Tab X should not close, as expected from other browsers.

## Reproduces how often: 
Easily reproduced.

## Brave version (brave://version info)

```
Brave	1.10.95 Chromium: 83.0.4103.106 (Official Build) (64-bit)
Revision	ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS	macOS Version 10.15.5 (Build 19F101)
JavaScript	V8 8.3.110.13
Flash	(Disabled)
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode,MixedContentSiteSetting,DnsOverHttps --disable-features=TextFragmentAnchor,LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication,NotificationTriggers,AllowPopupsDuringPageUnload,AutofillEnableAccountWalletStorage,TabHoverCards,SmsReceiver,VideoPlaybackQuality --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-sync
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/tanay/Library/Application Support/BraveSoftware/Brave-Browser/Default
```

## Version/Channel Information:
- Can you reproduce this issue with the current release? **Yes**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  **No**
- Does the issue resolve itself when disabling Brave Rewards? **No**

**Comment by bsclifton** [comment] 2020-06-23 19:52
Thanks for the report, @TanayB11 - we've captured what we think should be the solution with https://github.com/brave/brave-browser/issues/4963 if you wanted to read through and subscribe 

I'll close this issue as a duplicate of https://github.com/brave/brave-browser/issues/3581

**Closed by bsclifton** 2020-06-23 19:52 UTC
Labels: OS/Desktop
