### ISSUE TITLE
BAT Points text needed on BR slide of desktop onboarding flow

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#6602] opened 2019-10-24 18:34 UTC
Small copy change on the final BR screen of onboarding. Use revised copy for Japan:

Change -> "Get paid to view relevant ads that respect your privacy"

To -> "Collect points when you view relevant ads that respect your privacy"
![Screen Shot 2019-10-24 at 11 31 24](https://user-images.githubusercontent.com/71029/67514679-0c8f9b80-f652-11e9-8bad-873b6d77f65e.png)

**Comment by rebron** [comment] 2019-10-30 22:45
Closing. Duplicate of #6654

**Comment by kjozwiak** [comment] 2019-10-31 00:55
Going to re-open this one as https://github.com/brave/brave-browser/issues/6654 will address changing `BAT` -> `BAP` and `tokens` -> `points`. This particular issue addresses a small change within the onboarding text of `brave://rewards`.

**Closed** 2019-11-08 17:10 UTC
Labels: 1.0, QA/Blocked, QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards, l10n, release-notes/exclude

**Comment by GeetaSarvadnya** [comment] 2019-11-11 05:11
Verification passed on


Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3897
![image](https://user-images.githubusercontent.com/38657976/68562475-cf0f7880-046f-11ea-9ad3-77a936a20779.png)
