### ISSUE TITLE
No `You've earned an Ads Reward!` toast notification after accepting ad grant

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#28189] opened 2023-02-01 07:34 UTC
## Description 

No `You've earned an Ads Reward!` toast notification after accepting ad grant

Found while testing https://github.com/brave/brave-browser/issues/25581 - it's a refiling.  Worked with @GeetaSarvadnya who doesn't see it, either.

## Steps to reproduce 

1. install `1.48.152`
2. switch to `Rewards` staging environment via `QA Preferences` menu
3. tap on the `BAT` icon
4. tap on `Start using Brave Rewards`
5. (I connected to `Uphold`)
6. have someone send you an ad grant
7. wait
8. confirm the 1st toast notification
9. accept it
10. wait for the AJAX spinners to finish

## Actual result 

The balance updates silently; no `You've earned an Ads Reward!` toast notification pops up

example | example | example
---------|---------|----------
![Screenshot_20230131-224659](https://user-images.githubusercontent.com/387249/215978871-d95c4d98-bfa0-4c92-9db1-ba003f9d68bd.png) | ![Screenshot_20230131-224706](https://user-images.githubusercontent.com/387249/215978877-2b098d15-5c9c-4e3a-b846-8338101568d9.png) | ![Screenshot_20230131-224941](https://user-images.githubusercontent.com/387249/215978882-c194267a-d288-4744-b753-0ece2287d1cd.png)

## Expected result

![191965534-ec8deae7-2132-45cc-b254-c0d853516462](https://user-images.githubusercontent.com/387249/215979391-dc684b7e-6802-4644-8e83-66248eba47d8.png)

## Issue reproduces how often 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL`
   - Android version: `9`
   
## Brave version

`1.48.152`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @deeppandya @Miyayes @LaurenWags @GeetaSarvadnya

**Comment by GeetaSarvadnya** [comment] 2023-02-01 11:33
Reproduced the issue on  `Samsung Galaxy Android version 12` - running on `Bravemonoarm64.apk_1.48.141`

**Comment by Miyayes** [comment] 2023-02-01 17:09
This will be a wontfix since vBAT going away very soon.

**Closed** 2023-02-01 17:10 UTC
Labels: bug, closed/wontfix, feature/rewards, QA/Yes, QA/Test-Plan-Specified, regression, OS/Android
