### ISSUE TITLE
Domain blocked by Crypto Wallet Extention false positive ETH Phishing.

### ISSUE THREAD

**Issue by Arcbot-ArcusBD** [brave/brave-browser#7610] opened 2020-01-06 16:48 UTC
## Description 
Hello,

Checking my website I found it's being blocked by Brave's Crypto Wallet extension, which directed me to the repository for ETH Phishing Detect to file a report regarding this issue. Ran my domain through the ETH Phishing Detector's test page and turned blank, so I'd like to know what would be the next step in order to get my site to show in Brave.

## Steps to Reproduce
   1. Attempt to navigate to https://www.arcus.mx
   2. Click link "please file an issue" at the bottom of the page.
   3. Go to ETH Phishing Detect
   4. Click the link to the interactive page
   5. Introduce the domain that failed to load in the input and click check button

## Actual result:
The check states that the domain hasn't been blocked, however Brave's Crypto Wallet extension doesn't allows to navigate to the site. 

## Expected result:
Navigate to the site normally since it's not a risk.

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Windows 10 OS Version 1809 (Build 17763.914)
JavaScript | V8 7.9.317.31
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=NewExtensionUpdaterService,PasswordImport,SimplifyHttpsIndicator,WebUIDarkMode --disable-features=LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication,UnifiedConsent,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,SyncUSSBookmarks --flag-switches-begin --flag-switches-end --enable-features=WebUIDarkMode,SimplifyHttpsIndicator,PasswordImport,NewExtensionUpdaterService --disable-features=WebXR,AllowPopupsDuringPageUnload,SyncUSSBookmarks,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,WebXrGamepadModule,UnifiedConsent,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\windw\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Haven't tested
- Can you reproduce this issue with the dev channel? Haven't tested
- Can you reproduce this issue with the nightly channel? Haven't tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
None

**Comment by srirambv** [comment] 2020-01-06 16:55
Unable to navigate from blocked phishing page is a known issue https://github.com/brave/brave-browser/issues/6734. Going to close this issue as dupe of #6734 and added +1 there

**Closed by srirambv** 2020-01-06 16:55 UTC
