### ISSUE TITLE
Rewards Panel crashes when conversion rates cannot be obtained

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#5170] opened 2019-07-08 02:47 UTC
## Description 

If server to obtain BAT conversion rates is unreachable, Rewards Panel will crash.

## Steps to Reproduce

   1. Disconnect internet
   2. Start Brave
   3. Open Rewards Panel

## Actual result:
Panel crashes and BAT icon disappears with error in term:
```
[72257:775:0707/223100.361977:FATAL:api_response_validator.cc(75)] 
Check failed: false. Error validating response to `braveRewards.fetchBalance`: 
Error at parameter 'balance': Missing required property 'rates'
```

## Expected result:
Obviously obtaining rates should fail, but not crash panel

## Reproduces how often: 
always

## Brave version (brave://version info)

0.68 and 0.69 

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Not tested but probable (new balance call related; landed here)
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment] 2019-11-15 08:56
I can't reproduce this one, closing.

**Closed by NejcZdovc** 2019-11-15 08:57 UTC
Labels: feature/rewards, priority/P2
