### ISSUE TITLE
"Add Site" bug

### ISSUE THREAD

**Issue by Areckleh** [brave/brave-browser#23774] opened 2022-06-29 18:27 UTC
## Description 

When clicking 'Add Site', Edit site window opens but closes when clicked to add Website Title/URL - unable to add website title or URL when clicked on.

1. Issue persists on Version 1.40.107 Chromium: 103.0.5060.53 (Official Build) (arm64)

- Window disappears when clicked

3. Issue persists on Version 1.41.82 Chromium: 103.0.5060.66 (Official Build) beta (arm64)

- Window disappears when clicked

5. No issue on Version 1.42.39 Chromium: 103.0.5060.66 (Official Build) nightly (arm64)

- Successfully add URL and Website header 

Clip below from Official Build 1.40.107 

https://user-images.githubusercontent.com/43886134/176508212-6ff441b0-1279-47c4-8dbb-b77adf59e935.mov

Clip below from Nightly 1.42.39

https://user-images.githubusercontent.com/43886134/176509074-9b998674-3bc5-4693-bf48-f4a50d033092.mov

**Comment by rebron** [comment] 2022-07-01 04:11
Hi @Areckleh thanks for filing. This is a dupe of https://github.com/brave/brave-browser/issues/23689 and will get fixed in 1.41.x. Looks like you have it confirmed working in 1.42.x

**Closed by rebron** 2022-07-01 04:11 UTC
Labels: OS/Desktop
