### ISSUE TITLE
Nightly crashes when closing a vertical tab with middle click

### ISSUE THREAD

**Issue by Coffeeling** [brave/brave-browser#39516] opened 2024-07-01 21:30 UTC
### Description

Middle click a tab to close it, Nightly crashes. No error messages, just bluntly ceases to exist. Upon reboot, says Brave wasn't closed cleanly, remembers tabs that were open and can restore them.

### Steps to reproduce

1. Middle-click to close a tab.

### Actual result

Brave crashes

### Expected result

Tab should close normally.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave	1.69.65 Chromium: 127.0.6533.26 (Official Build) nightly (64-bit) 
Revision	2c13a0566fdd2ef6a495035fd1efe1b123bc7d48
OS	Windows 11 Version 23H2 (Build 22631.3737)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by bsclifton** [comment] 2024-07-09 21:41
@Coffeeling I can't reproduce - have you updated Brave since posting this? Does it still happen?

If so, please visit brave://crashes and upload a crash repot. You should be able to exit Brave and relaunch to force it to send the report (after you already clicked)

There should be an ID next to the `Uploaded Crash Report ID` field - please let us know that value.

**Comment by Coffeeling** [comment] 2024-07-14 00:15
> @Coffeeling I can't reproduce - have you updated Brave since posting this? Does it still happen?
> 
> If so, please visit brave://crashes and upload a crash repot. You should be able to exit Brave and relaunch to force it to send the report (after you already clicked)
> 
> There should be an ID next to the `Uploaded Crash Report ID` field - please let us know that value.

I've updated, and an update has resolved the issue. This should be closed as far as I'm concerned.

**Comment by rebron** [comment] 2024-07-23 14:04
Closing per last comment.

**Closed by rebron** 2024-07-23 14:04 UTC
Labels: crash, OS/Windows, priority/P2, needs-more-info, OS/Desktop
