### ISSUE TITLE
Please correct the help dialog

### ISSUE THREAD

**Issue by ToddAndMargo** [brave/brave-browser#3757] opened 2019-03-18 05:18 UTC
$ /usr/bin/brave-browser -h
       NAME
            brave-browser - the web browser from Google

Please update -h to correctly state that Brave comes from Chromium and not Google:
https://www.cnet.com/news/brave-browser-matures-with-move-to-chromium-foundation/

**Comment by bsclifton** [comment] 2019-03-18 07:10
Great catch, @ToddAndMargo 😄 

I just submitted a patch to fix this- will review with the team

**Comment by srirambv** [comment] 2019-03-18 13:13
Dupe of #392.

**Comment by srirambv** [comment] 2019-03-18 13:14
Didn't realize there was a PR linked. @bsclifton #392 has a lot more things that needs to be fixed

**Comment by bsclifton** [comment] 2019-03-18 17:00
@srirambv no - you are right, that's what this is about too. Closing as dupe

**Closed by bsclifton** 2019-03-18 17:00 UTC
Labels: branding

**Comment by ToddAndMargo** [comment] 2019-03-19 06:36
I do apologize for asking this question here, but when I first signed up to follow a Brave bug, I got ALL the bugs eMailed to me.  So many come to me I can't keep track of the ones I posted and everyone else's.  Is there a way to limit this bug reported to just the bugs I reported?

**Comment by bsclifton** [comment] 2019-03-19 17:15
Hi @ToddAndMargo - yes. You should be able to un-watch the repository and then (on an issue-by-issue basis) use the `subscribe` button (on the right, under milestone)

**Comment by ToddAndMargo** [comment] 2019-03-20 00:47
Sorry, not finding subscribe button or milestone for that matter

**Comment by bsclifton** [comment] 2019-03-21 21:33
@ToddAndMargo ah - you might be on mobile. If you're logged in and on desktop, you'd see watch up at the top:
<img width="893" alt="Screen Shot 2019-03-21 at 2 31 47 PM" src="https://user-images.githubusercontent.com/4733304/54786498-3e391380-4be6-11e9-9af9-5a5b0f742d64.png">

And then in any issue you do want to follow, you should see a subscribe button (mine says unsubscribe since I'm watching all issues)
<img width="1005" alt="Screen Shot 2019-03-21 at 2 31 55 PM" src="https://user-images.githubusercontent.com/4733304/54786524-514be380-4be6-11e9-81aa-8e4e1b885f6c.png">

**Comment by ToddAndMargo** [comment] 2019-03-22 05:40
Wonderful instructions!  Thank you!
