### ISSUE TITLE
Redirect AMP to HTML

### ISSUE THREAD

**Issue by ChildishGiant** [brave/brave-browser#5933] opened 2019-09-08 12:41 UTC
Here is a fairly good explanation as to why this would be good: https://www.reddit.com/r/AmputatorBot/comments/c88zm3/why_did_i_build_amputatorbot/

That post also includes a link to this extension that I imagine could be shipped as default:
https://github.com/da2x/amp2html

**Comment by rebron** [comment] 2019-09-27 16:14
@ChildishGiant What platform were you looking at for this? Android?

**Comment by ChildishGiant** [comment] 2019-09-28 21:16
Yea android was what I had in mind but also iOS if applicable.

**Comment by rebron** [comment] 2020-04-29 16:46
cc: @AndriusA Already working on this in another issue right?

**Comment by fmarier** [comment] 2020-06-09 00:39
Dupe of #8720, which came later but has a few more links.

**Closed by fmarier** 2020-06-09 00:39 UTC
Labels: OS/Android
