### ISSUE TITLE
Unable to Lower Shields

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#3205] opened 2019-02-03 22:51 UTC
## Description 
A user has [reported](https://twitter.com/com4ter2/status/1091526136478253056) that shields cannot be dropped on their cPanel X instance. The user submitted the following video: https://video.twimg.com/tweet_video/DyftD1lWkAUbNDF.mp4.

## Steps to Reproduce
(See video)

## Actual result:
Shields do not lower, but page does refresh.

## Expected result:
Shields lower, and page refreshes.

## Reproduces how often: 
TBD

## Brave version (brave://version info)
0.61.4

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? TBD

**Comment by bershanskiy** [comment] 2019-02-04 06:41
I did a bit of testing and found out the following:
1. Brave is unable to lower shields on non-standard ports (for any application)
Steps to reproduce on current stable release (Version 0.59.34 Chromium: 72.0.3626.81 (Official Build) (64-bit):
- Start server (e.g., on localhost) on a non-standard for HTTP port (e.g., 8000)
- Go to the URL (e.g., localhost)
- Try to lover shields and observe that after reload they are still up
2. I believe this is the same bug (even though I can't see the URL in the video) because cPanel is commonly set up on ports different from 80 and 443.

**Comment by kekukui** [comment] 2019-02-05 08:18
Duplicate of bug https://github.com/brave/brave-browser/issues/1896

**Comment by nip10** [comment] 2019-02-12 19:46
I'm also running into this issue.
I've Hassio running on port 8123 and I can't lower shields. When I try to toggle the on/off button, it goes to off for a fraction of a second and returns to on. In some cases it will crash the tab (probably due to the way Hassio dashboard runs).

Version 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
Windows 10 x64

**Comment by dinuchiriac** [comment] 2019-02-21 11:11
It looks like the issue is fixed in the latest dev build `Version 0.62.5 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)`

**Comment by mesqueeb** [comment] 2019-03-06 02:01
Unable to lower shields on `localhost`.
+1

**Comment by bsclifton** [comment] 2019-03-19 20:26
Closing as duplicate of https://github.com/brave/brave-browser/issues/1896

As shared above, this is fixed in our Beta / Dev / Nightly channels 😄 Coming in our next release for Release channel

**Closed by bsclifton** 2019-03-19 20:26 UTC
Labels: duplicate
