### ISSUE TITLE
Automatically crash every time it runs

### ISSUE THREAD

**Issue by dev-coco** [brave/brave-browser#25165] opened 2022-09-02 13:52 UTC
## Steps to Reproduce

The browser opens and then runs down and closes automatically.

## Reproduces how often: 

Every time reproduced

## Brave version (brave://version info)

v1.43.88

## Version/Channel Information:

v1.43.81 works fine

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No

- Does the issue resolve itself when disabling Brave Rewards? 
No

- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:

objc[3300]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x246548b68) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/105.1.43.88/Libraries/libGLESv2.dylib (0x10ab320e8). One of the two will be used. Which one is undefined.
[3294:259:0902/094054.385551:ERROR:profile_attributes_storage.cc(849)] Failed to PNG encode the image.
[3294:259:0902/094054.385593:ERROR:profile_attributes_storage.cc(849)] Failed to PNG encode the image.
[0902/094055.502715:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5)

**Comment by ThunderE75** [comment] 2022-09-02 16:13
If you still encountering the problem, open a private window, navigate to `brave://flags/` & Click on the "reset all" button on the top right. This will reset all the flags to it's default configuration. This fixed the crashes for me.

This issue was also discussed in this brave community thread https://community.brave.com/t/brave-opens-than-closes-immediately-after/428260

**Comment by rebron** [comment] 2022-09-02 16:58
@dev-coco What OS and architecture are you running? Are you using Arm M1 or M2 on a mac?

**Comment by dev-coco** [comment] 2022-09-02 21:17
> @dev-coco What OS and architecture are you running? Are you using Arm M1 or M2 on a mac?

M1 Ventura 13.0

**Comment by dev-coco** [comment] 2022-09-02 21:19
> If you still encountering the problem, open a private window, navigate to `brave://flags/` & Click on the "reset all" button on the top right. This will reset all the flags to it's default configuration. This fixed the crashes for me.
> 
> This issue was also discussed in this brave community thread https://community.brave.com/t/brave-opens-than-closes-immediately-after/428260

However, as soon as I open the browser, it crashes without a chance to type `brave://flags`

**Comment by dev-coco** [comment] 2022-09-02 23:47
> objc[3300]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x246548b68) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/105.1.43.88/Libraries/libGLESv2.dylib (0x10ab320e8). One of the two will be used. Which one is undefined.
> [3294:259:0902/094054.385551:ERROR:profile_attributes_storage.cc(849)] Failed to PNG encode the image.
> [3294:259:0902/094054.385593:ERROR:profile_attributes_storage.cc(849)] Failed to PNG encode the image.
> [0902/094055.502715:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5)

No, I can't open the browser. It crashes automatically after running, and then displays the following error.
```Shell
objc[3300]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x246548b68) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/105.1.43.88/Libraries/libGLESv2.dylib (0x10ab320e8). One of the two will be used. Which one is undefined.
[3294:259:0902/094054.385551:ERROR:profile_attributes_storage.cc(849)] Failed to PNG encode the image.
[3294:259:0902/094054.385593:ERROR:profile_attributes_storage.cc(849)] Failed to PNG encode the image.
[0902/094055.502715:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5)
```

**Comment by dev-coco** [comment] 2022-09-02 23:48
> Hi @dev-coco Can you launch brave via terminal? https://support.brave.com/hc/en-us/articles/360044860011-How-Do-I-Use-Command-Line-Flags-in-Brave-
> 
> open -a "Brave Browser.app" --args https://www.brave.com or open -a "Brave Browser.app" -n
> 
> Should be able to go into brave://flags from there

No, I can't open the browser. It crashes automatically after running, and then displays the following error.
```Shell
objc[3300]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x246548b68) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/105.1.43.88/Libraries/libGLESv2.dylib (0x10ab320e8). One of the two will be used. Which one is undefined.
[3294:259:0902/094054.385551:ERROR:profile_attributes_storage.cc(849)] Failed to PNG encode the image.
[3294:259:0902/094054.385593:ERROR:profile_attributes_storage.cc(849)] Failed to PNG encode the image.
[0902/094055.502715:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5)
```

**Comment by bsclifton** [comment] 2022-09-03 00:06
1.43.x does feature Chromium 105. @dev-coco @donefool does the latest Chrome work for you? (if you have it installed)

**Comment by dev-coco** [comment] 2022-09-03 01:13
> 1.43.x does feature Chromium 105. @dev-coco @donefool does the latest Chrome work for you? (if you have it installed)

Chrome is work, but brave still don't work

**Comment by bsclifton** [comment] 2022-09-06 05:53
@dev-coco let's try this - I'm on macOS and I verified these steps should work

Open a command line and try running this:
`"/Applications/Brave Browser.app/Contents/MacOS/Brave Browser" -- "https://brave.com"`

This should open Brave and have it opened to brave.com. If that works, go into the URL bar and put in "brave://flags". Once there, hit `Reset all` in the top right.  That should get you sorted - please let us know!

If that doesn't work, can you please try installing an older version of Brave?  You can download 1.42.97 from here:
https://github.com/brave/brave-browser/releases/download/v1.42.97/Brave-Browser-universal.dmg

With that older version, you can then visit brave://flags and try to do the `Reset all`

**Comment by dev-coco** [comment] 2022-09-06 11:54
> @dev-coco let's try this - I'm on macOS and I verified these steps should work
> 
> Open a command line and try running this: `"/Applications/Brave Browser.app/Contents/MacOS/Brave Browser" -- "https://brave.com"`
> 
> This should open Brave and have it opened to brave.com. If that works, go into the URL bar and put in "brave://flags". Once there, hit `Reset all` in the top right. That should get you sorted - please let us know!
> 
> If that doesn't work, can you please try installing an older version of Brave? You can download 1.42.97 from here: https://github.com/brave/brave-browser/releases/download/v1.42.97/Brave-Browser-universal.dmg
> 
> With that older version, you can then visit brave://flags and try to do the `Reset all`

It's work, thanks.

**Comment by bsclifton** [comment] 2022-09-06 17:46
Great, thanks for confirming @dev-coco! I'm going to close this as a duplicate of https://github.com/brave/brave-browser/issues/25156

**Closed by bsclifton** 2022-09-06 17:46 UTC
Labels: crash, OS/Desktop

**Comment by unknowguy2** [comment] 2023-06-29 10:12
i am having same problem but in windows 10

**Comment by 00000o1** [comment] 2023-10-08 05:28
@unknowguy2 recommend you open a new issue for this!

**Comment by xXilixaXx** [comment] 2024-01-21 16:25
> 1.43.x does feature Chromium 105. @dev-coco @donefool does the latest Chrome work for you? (if you have it installed)

i have the same problem but windows 10 and chrome does the same thing
