### ISSUE TITLE
"Send a Tip" sometimes not appearing when you've already tipped the same publisher

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#2272] opened 2018-11-28 20:06 UTC
## Description 

When tipping the same publisher for the second time, sometimes the `Send a Tip` disappears and re-appears after a few seconds/minutes. It's pretty variable in terms of when `Send a Tip` reappears. Sometimes it reappears pretty quickly and sometimes it takes a few minutes.

There's been a few internal reports of this occurring as well. @mandar-brave @bsclifton @LaurenWags @davidtemkin and myself have ran into this in one form or another.

## Steps to Reproduce

   1. launch `0.56.15 Chromium: 70.0.3538.110` and enable Rewards via `brave://rewards`
   2. once enabled, either accept a grant or restore a wallet with some BAT
   3. visit http://clifton.io and send a 5 BAT tip
   4. once the tip has been sent, try tipping again (eventually the `Send a Tip` area won't appear)

## Actual result:

If you've already tipped the same publisher and wanted to do it again, sometimes the `Send a Tip` area disappears under the Rewards panel. It eventually reappears but varies on how long.

![tippingissue](https://user-images.githubusercontent.com/2602313/49178527-f7b16780-f31d-11e8-934f-02834ed00e64.gif)

<img width="789" alt="screen shot 2018-11-27 at 6 14 14 pm" src="https://user-images.githubusercontent.com/2602313/49181066-642f6500-f324-11e8-8b6b-3aa2789088b9.png">

## Expected result:

The `Send a Tip` section of the Rewards panel should always be visible.

## Reproduces how often: 

This issue is about 90% reproducible. Shouldn't be hard to get it into that state.

## Brave version (brave://version info)

Brave | 0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit)
-- | --
Revision | ca97ba107095b2a88cf04f9135463301e685cbb0-refs/branch-heads/3538@{#1094}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Reproduced using the following builds as well:

Brave | 0.58.10 Chromium: 71.0.3578.53 (Official Build) dev(64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X

Brave | 0.57.8 Chromium: 71.0.3578.53 (Official Build) beta(64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X

**Comment by NejcZdovc** [comment] 2018-12-21 07:49
@kjozwiak can we retest this on 0.61. I just tried it and can't reproduce

**Comment by eljuno** [comment] 2019-01-18 05:10
+1 from community https://community.brave.com/t/site-not-verified-cannot-send-tips/42775?u=eljuno

**Comment by kjozwiak** [comment] 2019-01-23 02:47
> @kjozwiak can we retest this on 0.61. I just tried it and can't reproduce

I can still reproduce this with the following builds:

Brave | 0.59.26 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Mac OS X

Example:

![tippingissue](https://user-images.githubusercontent.com/2602313/51579199-13ed0300-1e8e-11e9-9eb6-768d4fffdd52.gif)

However, I couldn't reproduce this with the following `dev` build:

Brave | 0.60.16 Chromium: 72.0.3626.64 (Official Build) dev(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Mac OS X

Example:

![tippingissuedev](https://user-images.githubusercontent.com/2602313/51579278-5f9fac80-1e8e-11e9-974a-aac15b3d06f7.gif)

@NejcZdovc you'll notice that sometimes the `wallet balance` is displayed as `0` under the Rewards panel if you try tripping a second time around right after the first tip was sent. I'm assuming this is happening because the first tip didn't get processes yet and Rewards hasn't been updated. It usually gets updates anywhere between 2-3sec to ~1min. When the `wallet balance` appears as `0` in this situation, you'll get a `insufficient funds` error when you try tipping even though you have the funds.

It looks like `dev` tries to complete the first tip before allowing users to tip again right after. Could this be why we're running into issues on `beta`? You get into a broken state when you try sending tip after tip even though the initial tips haven't beeb processed?

Is the behaviour that I'm seeing on `dev` expected?

**Comment by NejcZdovc** [comment] 2019-01-23 04:44
I notice this 0 as well. Let's close this one as it's fixed on 0.60 and open new one for 0 BAT

**Closed by NejcZdovc** 2019-01-23 04:44 UTC
Labels: QA/Yes, bug, feature/rewards, needs-investigation, priority/P3
