### ISSUE TITLE
Public key for brave-keyring-1.0-1.fc30.noarch.rpm is not installed

### ISSUE THREAD

**Issue by nat1on** [brave/brave-browser#3802] opened 2019-03-20 07:33 UTC
## Description 
Installation of brave-browser on CentOS Linux release 7.6.1810 as documented here:
https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

will always fail with:

Public key for brave-keyring-1.0-1.fc30.noarch.rpm is not installed

## Steps to Reproduce
Follow the steps for Release Channel Installation / Centos/RHel

1. sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

2. cat << EOF | sudo tee /etc/yum.repos.d/brave-browser-release.repo
[brave-browser-release]
name=Brave Browser Release Channel repository
baseurl=https://brave-browser-rpm-release.s3.brave.com/x86_64/
enabled=1
EOF

3. sudo yum install brave-browser brave-keyring

## Actual result:
warning: /var/cache/yum/x86_64/7/brave-browser-release/packages/brave-keyring-1.0-1.fc30.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID e3ffc656: NOKEY                      ]  0.0 B/s |    0 B  --:--:-- ETA 
Public key for brave-keyring-1.0-1.fc30.noarch.rpm is not installed
brave-keyring-1.0-1.fc30.noarch.rpm                                                                                                                                                         | 6.0 kB  00:00:01     

Public key for brave-keyring-1.0-1.fc30.noarch.rpm is not installed

rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n' | grep -i brave
gpg-pubkey-c2d4e821-5bc51032    gpg(Brave Software <support@brave.com>)
gpg-pubkey-6a8a26f9-5b4e234c    gpg(Brave Software (Brave Core Nightly Key) (We're reinventing the browser as a user-first platform for speed and privacy.) <support@brave.com>)

rpm -Kv /var/cache/yum/x86_64/7/brave-browser-release/packages/brave-keyring-1.0-1.fc30.noarch.rpm 
/var/cache/yum/x86_64/7/brave-browser-release/packages/brave-keyring-1.0-1.fc30.noarch.rpm:
    Header V4 RSA/SHA512 Signature, key ID e3ffc656: NOKEY
    Header SHA1 digest: OK (7e5712704016fcbacb94788263b9759a9ffd1781)
    V4 RSA/SHA512 Signature, key ID e3ffc656: NOKEY
    MD5 digest: OK (4fd92957d630cbecce6aa32ca8e21ab5)

rpm -Kv /var/cache/yum/x86_64/7/brave-browser-release/packages/brave-browser-0.61.51-1.x86_64.rpm 
/var/cache/yum/x86_64/7/brave-browser-release/packages/brave-browser-0.61.51-1.x86_64.rpm:
    Header V4 RSA/SHA512 Signature, key ID e3ffc656: NOKEY
    Header SHA1 digest: OK (6d0a8b36b1e83117636c17c0f6e3103a94b8167c)
    V4 RSA/SHA512 Signature, key ID e3ffc656: NOKEY
    MD5 digest: OK (9243f34167b9c49e7795b0457c4d1468)

## Expected result:
rpm packages install correctly.

## Reproduces how often: 
everytime

## Brave version (brave://version info)
brave-browser x86_64 0.61.51-1

### Reproducible on current release:
no, the beta is signed properly

rpm -Kv /var/cache/yum/x86_64/7/brave-browser-beta/packages/brave-browser-beta-0.62.32-1.x86_64.rpm 
/var/cache/yum/x86_64/7/brave-browser-beta/packages/brave-browser-beta-0.62.32-1.x86_64.rpm:
    Header V4 RSA/SHA512 Signature, key ID 6a8a26f9: OK
    Header SHA1 digest: OK (f39d84b0c3d1d6dffbee3965d07e81c4877ac32c)
    V4 RSA/SHA512 Signature, key ID 6a8a26f9: OK
    MD5 digest: OK (a1d9a2432fc08ac89852e8c3dac11276)

**Comment by srirambv** [comment] 2019-03-25 12:49
Will be fixed by https://github.com/brave/devops/issues/743

**Comment by bsclifton** [comment] 2019-03-25 19:34
@srirambv @mbacchi is this the same as https://github.com/brave/brave-browser/issues/3617?

**Comment by srirambv** [comment] 2019-04-03 15:01
Actually can close this as dupe of #3617

**Closed by srirambv** 2019-04-03 15:01 UTC
Labels: OS/Linux, setup/installer

**Comment by ckaspro** [comment] 2020-02-02 08:30
This seems to have happend again for me:
on Fedora 30 I got:
Public key for brave-browser-1.2.43-1.x86_64.rpm is not installed
Public key for brave-keyring-1.7-1.noarch.rpm is not installed

I could install brave-browser with:
sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

...but am unable to install the keyring.

**Comment by fartwhif** [comment] 2020-04-03 01:20
`warning: /var/cache/dnf/brave-browser-rpm-release.s3.brave.com_x86_64-4b8ac32b87fdc4aa/packages/brave-browser-1.5.122-1.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 82d3dc6c: NOKEY
Public key for brave-browser-1.5.122-1.x86_64.rpm is not installed
Public key for brave-keyring-1.8-1.noarch.rpm is not installed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: GPG check FAILED`

it's rearing its ugly head again, boys
