### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by joemccall86** [brave/brave-browser#37293] opened 2024-04-03 15:17 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.64.109 Chromium: 123.0.6312.58
Operating System: Mac OS X 14.3.1

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. "Install" the PWA for https://silverbullet.md
2. Select anywhere in the opened PWA
3. Right-click

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/eac61f00-686b-ba0b-0000-000000000000

**Comment by rebron** [comment] 2024-04-10 20:02
closing as dupe of https://github.com/brave/brave-browser/issues/36995 and fixed with 1.64.113 and higher. 
@joemccall86 When you get a chance, can you update to our latest 1.64.116 via brave://settings/help

**Closed by rebron** 2024-04-10 20:02 UTC
