### ISSUE TITLE
After scrolling down in a long enough browser history, it jumps back to the beginning: Unable to see older history

### ISSUE THREAD

**Issue by arsinclair** [brave/brave-browser#41072] opened 2024-09-14 13:51 UTC
### Description

When going to [brave://history](brave://history) and holding PageDown to scroll down, at some point the screen resets to the beginning. I'm unable to see the browsing history of even 12 days ago, I think on average there's 150-200 entries per day.

### Steps to reproduce

See description.

### Actual result

See description.

### Expected result

The history should scroll as much as I want to without resetting the view to the beginning.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

[Version 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit)](https://brave.com/latest/)

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment] 2024-09-16 23:10
Closing as dupe of https://github.com/brave/brave-browser/issues/40923
Thanks for the report.

**Closed by rebron** 2024-09-16 23:10 UTC
Labels: OS/Desktop
