### ISSUE TITLE
Home Page Background Issue

### ISSUE THREAD

**Issue by rhrakib555** [brave/brave-browser#20159] opened 2021-12-18 06:03 UTC
## Description 

Brave Browser has no option to set custom image on homepage as homepage background.
Whatever, I only need a "Black/Dark" wallpaper/theme as homepage background. But there has no single way to do it. It would be better if there has "Black Theme" & "Black Wallpaper as homepage background" as built in the Brave Browser.

Developer should take a view & take necessary steps.

## Steps to Reproduce

   1. Add "Black Theme" in the Brave Browser as built in; which works across UI, Homepage, Toolbar etc.

## Expected result:
Brave will add black/dark UI & black homepage background.

**Comment by thefallofbecause** [comment] 2021-12-19 22:21
See #15252

**Comment by rhrakib555** [comment] 2021-12-20 04:13
> See #15252

Many thanks.
But is it implemented yet?
I don't think so.

**Comment by bsclifton** [comment] 2021-12-20 07:04
Closing as duplicate of https://github.com/brave/brave-browser/issues/15252 (thanks for the assist, @thefallofbecause! 😄)

@rhrakib555 that issue is assigned and @simonhong is working on it now 😄 You can follow along a work-in-progress here:
https://github.com/brave/brave-core/pull/11622

**Closed by bsclifton** 2021-12-20 07:04 UTC
