### ISSUE TITLE
[Android] Ad notifications is not limited to 3 in notification tray

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10140] opened 2020-06-08 12:19 UTC
## Description 
Ad notifications is not limited to 3 in notification tray

## Steps to reproduce 

   1. Upgrade to 1.9.79
   2. Enable rewards
   3. Wait for ads notification to stack up. Not limited to 3 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/84029498-1d5a0b00-a9b0-11ea-8f29-d1c404f7a608.png)

## Expected result
Should be stacked to 3 notifications in tray

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Maybe

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.9.79

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Note: No beta/nightly installed on the device so all notifications in the tray is from the release build

**Comment by srirambv** [comment] 2020-06-10 11:15
Not sure if adding PWA's from Brave causes this increased notifications in-tray. I started noticing the issue after adding a bunch of PWA's on home screen.

**Comment by yachtcaptain23** [comment] 2020-06-11 20:17
Reproduced after stopping and restarting Brave.

**Comment by tmancey** [comment] 2020-06-13 12:23
Restarted Brave 1.9.79 on a Pixel 3 and cannot reproduce

**Comment by yachtcaptain23** [comment] 2020-06-16 17:37
We're moving to custom notifications, so this ticket will no longer be relevant. Closing.

**Closed by yachtcaptain23** 2020-06-16 17:37 UTC
Labels: OS/Android, QA/Yes, bug, feature/ads, needs-investigation, regression
