### ISSUE TITLE
Crashes when using Search bar in Incognito or Tor mode

### ISSUE THREAD

**Issue by 09kkthxbb** [brave/brave-browser#33021] opened 2023-09-15 01:44 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

**Brave Version:** 1.60.23 Chromium: 117.0.5938.62
**Operating System:** Windows NT 10.0.22621

**URL (if applicable) where crash occurred:**
Not URL, but any search keywords

**Can you reproduce this crash?**
Yes, this bug existed starting from 1.60.20 onwards. Brave will not crash when you use it in normal Mode.

**What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)**
1. Open Brave Browser in either Incognito or Tor Mode.
2. Type and search any keywords or phrases directly in Search bar (URL address bar)
3. Press Enter

My temporary workaround is to type URL of search engine site and search through it. Brave will not crash in Incognito or Tor mode when you type URL format (ex: https://www.example.com) instead of keyword.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/f9a30200-0209-b80a-0000-000000000000

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment] 2023-09-15 03:10
https://github.com/brave/brave-core/pull/20173

**Comment by rebron** [comment] 2023-09-15 04:32
Closing as dupe of https://github.com/brave/brave-browser/issues/32976

**Closed by rebron** 2023-09-15 04:32 UTC
Labels: crash, feature/tor, priority/P2, feature/search
