### ISSUE TITLE
Add clear rewards data and clear payment data

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#926] opened 2018-09-02 10:31 UTC
User should be able to remove rewards data (auto contribute, donation, tipping) and remove payment data (previous payments). This should delete the data on disk.

From browser laptop
![image](https://user-images.githubusercontent.com/9574457/44954993-2305f100-aeac-11e8-9ab9-107695e2998f.png)

**Comment by diracdeltas** [comment] 2018-11-27 20:48
Marking this as p3 and privacy related because currently there is no way to delete browsing history associated with rewards unless the user deletes the files on disk. if rewards is enabled, browsing history is logged to `publisher_info_db`.  @NejcZdovc please correct me if i'm wrong.

cc @tomlowenthal

**Comment by tomlowenthal** [comment] 2018-11-28 19:42
I think the right solution would be to extend <brave://settings/clearBrowserData> to include controls for Brave Rewards.

For the simply view, we should add a "Brave Rewards data" item which removes all attention info created from the indicated time period.

On the advanced tab, we should add a couple of items.
- "Brave Rewards auto-contribute list" should remove attention history and auto-contribute items for the applicable time period.
- "Brave Rewards contribution history" should remove records of tips and contributions from the time period, replacing them with "private contribution" or something to that effect.

@mandar-brave @NejcZdovc Could someone on the Rewards team indicate whether there are any other ways that information equivalent to browsing-history might be stored?

**Comment by jasonrsadler** [comment] 2018-12-10 22:07
What is defined as "applicable time period"? Currently we store auto-contribute information based on month and year. The options available when clearing data are "last hour", "last 24 hours", "last 7 days", and "last 4 weeks". How should we handle clearing data based on what is chosen?

**Comment by tomlowenthal** [comment] 2018-12-11 19:50
@jasonrsadler Are you saying that we have no way of knowing what auto-contribute info was added in the last hour, the last 24 hours, or last 7 days?

**Comment by jasonrsadler** [comment] 2018-12-11 19:51
Correct. @NejcZdovc to confirm but I believe we are only storing the month and the year.

**Comment by NejcZdovc** [comment] 2018-12-11 20:06
@tomlowenthal that is correct we accumulate time per month and not per visit

**Comment by diracdeltas** [comment] 2018-12-11 20:52
Personally I would be happy if someone just added an option for "Clear Brave rewards and payment data since the beginning of time". 

Having time intervals can be a follow-up but I don't think it's strictly necessary (we didn't have this in b-l)

**Comment by NejcZdovc** [comment] 2018-12-11 20:58
I think we shouldn't change it. We should adjust place where we have clear like @diracdeltas said

**Comment by tomlowenthal** [comment] 2018-12-12 19:15
I think we should do both, but I'm okay with only having "from the beginning of time" as a first pass.

Brave Rewards is basically another browser history repository separate from the regular browser history. People should have at least the same degree of transparency and control that they have over their regular browser history.

Those time intervals are really useful tools. Let's say I open a regular tab instead of a private one, and browse for a minute before realizing my mistake. That's what "from the last hour" is for, and it's a valuable feature. I shouldn't have to blow away my entire auto-contribute list to do this.

**Comment by mandar-brave** [comment] 2018-12-16 23:43
@tomlowenthal let's discuss the time based ask on the product meeting - worth a debate. Considering the data, unlike browsing or bookmarks, is not very usable as such it's not clear to me that a time-based approach is needed but let's open it to @rebron as well.

@jasonrsadler for now, the options you have presented 
- Delete all-time auto-contribute
- Delete all-time Rewards (Should remove all ledger data incl. auto-contribute, recurring tips, tips, statements, and current in-wallet transactions)

are fine.

However, the wallet and the wallet balance remain intact.

cc @NejcZdovc

**Comment by rebron** [comment] 2018-12-19 22:03
@mkarolin @jasonrsadler @bradleyrichter @mandar-brave making sure this one is on your radar as well. https://github.com/brave/brave-browser/issues/492 
Need decision if we want these options for clear on exit as well.

**Comment by tomlowenthal** [comment] 2018-12-19 22:05
If you're going to clear auto-contribute on exit, you'd be better-off just not enabling that feature.

**Comment by jasonrsadler** [comment] 2018-12-19 22:42
👍 @tomlowenthal.

Per slack convo, I think #492 uses a different tab and shouldn't have rewards included. Either let the user explicitly clear rewards, or if they want it cleared on exit, just disable.

**Comment by jasonrsadler** [comment] 2019-01-02 14:00
Per convo with @bridiver, updating requirements defined so far:
1. Allow clearing auto-contribute list in Rewards.
2. Allow clearing all Rewards data (minus wallet).

**Comment by jasonrsadler** [comment] 2019-01-03 18:35
cc @davidtemkin and @mandar-brave 
How should #3 in above comment above be handled?

**Comment by mandar-brave** [comment] 2019-01-07 18:23
@jasonrsadler if the contribution is in progress, gray out the clear and re-enable it once completed. Thanks!

**Comment by rebron** [comment] 2019-03-28 23:09
cc: @anthonypkeane

**Comment by NejcZdovc** [comment] 2020-06-04 08:45
closing as this will be implemented in https://github.com/brave/brave-browser/issues/10064

**Closed** 2020-07-15 05:36 UTC
Labels: QA/Yes, feature/rewards, release-notes/include

**Comment by LaurenWags** [comment] 2020-08-14 14:31
Verified passed with

```
Brave | 1.13.71 Chromium: 84.0.4147.125 (Official Build) dev (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/6020
* Confirmed link exists on each Clear browsing data tab:
<img width="1016" alt="Screen Shot 2020-08-14 at 10 27 57 AM" src="https://user-images.githubusercontent.com/28145373/90260044-f6d5a780-de18-11ea-9280-3eddd4419d13.png">
<img width="1011" alt="Screen Shot 2020-08-14 at 10 28 10 AM" src="https://user-images.githubusercontent.com/28145373/90260048-f89f6b00-de18-11ea-9b33-a8f42955612c.png">
<img width="1010" alt="Screen Shot 2020-08-14 at 10 28 20 AM" src="https://user-images.githubusercontent.com/28145373/90260052-fa692e80-de18-11ea-86b5-1583642a847b.png">

* Confirmed clicking on the link from each tab opens the Manage Your Wallet dialog
<img width="701" alt="Screen Shot 2020-08-14 at 10 28 50 AM" src="https://user-images.githubusercontent.com/28145373/90260084-0523c380-de19-11ea-9af1-d825590d987f.png">

* Confirmed link displays using light theme also:
<img width="515" alt="Screen Shot 2020-08-14 at 10 30 13 AM" src="https://user-images.githubusercontent.com/28145373/90260212-2e445400-de19-11ea-83ad-3b1ded6229f6.png">

* Encountered https://github.com/brave/brave-browser/issues/11235 while testing
