### ISSUE TITLE
chrome.ipfs: launch|shutdown should control getResolveMethodType

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#13237] opened 2020-12-17 21:18 UTC
This issue is part of IPFS integration.
Tested version: `brave-browser-nightly-1.20.36-linux-amd64` 

## Background

`chrome.ipfs.launch` executed on empty profile triggers go-ipfs download, initializes the repo and starts the IPFS node.
This is good! makes it possible to integrate `launch` and `shutdown` with backend selector in IPFS Companion extension _Preferences_:

> ![2020-12-17--22-03-28](https://user-images.githubusercontent.com/157609/102543529-b7171900-40b3-11eb-8857-4c974192685f.png)
> This screenshot comes from wip work tracked in https://github.com/ipfs-shipyard/ipfs-companion/issues/947

## The bug(?)

I noticed that  calling `chrome.ipfs.launch` from IPFS Companion does not change value returned by `chrome.ipfs.getResolveMethodType`. 

The node is installed and started, IPFS node is running, but the `ResolveMethodType` setting remains at  `ask` which will result in redundant backend selection prompt: user already chose Brave, no need to ask them again when they load something via  `ipfs://`

## Expected behavior

Would it be possible for:
-  `launch` to flip it to `local` 
- `shutdown` to `gateway`
?

This way, when node Brave backend was selected via _Preferences_ screen above, no additional confirmation needs to happen, and if Companion user decides to use a different backend, then node can be shut down automatically and with `ResolveMethodType` equal `gateway` it will  continue to work nicely with external nodes (for example: if  "external" node type is selected via Companion, it  will redirect `dweb.link` to gateway provided by IPFS Desktop)  

## Alternative behavior

make `chrome.ipfs.launch` trigger "IPFS consent" dropdown, and return `false` if user chose to not enable node.

**Comment by bbondy** [comment] 2021-01-10 04:36
I think this is not a bug. I think it was probably posted because before `launch` was incorrectly starting the node.  Closing, but let me know if you disagree.

**Closed by bbondy** 2021-01-10 04:36 UTC
Labels: OS/Desktop, feature/ipfs
