### ISSUE TITLE
weird black theme white borders

### ISSUE THREAD

**Issue by Terottaja** [brave/brave-browser#6373] opened 2019-10-09 13:28 UTC
## Description 

Strange styling for some black themed UI elements

## Steps to Reproduce

**First issue:** Top right hamburger menu white borders
![image](https://user-images.githubusercontent.com/31454692/66484848-7172bf80-eab0-11e9-8903-8503d508120e.png)

   1. Enable dark theme
   2. Click on the hamburger icon on the top right
   3. See how the borders are

**Seconds issue:** Hovering over tabs brings out a black box with white borders
![image](https://user-images.githubusercontent.com/31454692/66485108-e34b0900-eab0-11e9-8cb4-17b06ea1fe18.png)

   1. Create a tab or hover over existing one
   2. You should see a black box with the tab title with a white border which look something out of Windows high contrast mode

Also, i dont really like this 
![image](https://user-images.githubusercontent.com/31454692/66485508-9d427500-eab1-11e9-8b98-8b9bf5b1c450.png)
But maybe its for others, idk. just me i guess

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

`Brave	0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
Revision	58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS	Windows 8.1 (Build 9600)
JavaScript	V8 7.7.299.11
Flash	(Disabled)
User Agent	Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Command Line	"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-features=NewExtensionUpdaterService,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AudioServiceOutOfProcess,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,UnifiedConsent --flag-switches-begin --enable-features=NewExtensionUpdaterService,WebUIDarkMode,SimplifyHttpsIndicator,WebRtcHideLocalIpsWithMdns --flag-switches-end
Executable Path	C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\Administrator\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
`

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

Specific to Brave

**Comment by srirambv** [comment] 2019-10-10 12:34
Tab hover tooltip is same on Chrome as well. 
![Screenshot from 2019-10-10 08-31-47](https://user-images.githubusercontent.com/17010094/66569051-b0e4ee80-eb38-11e9-8293-5ebbdc3f3e5e.png)

Hamburger menu is probably a Windows specific theming issue. cc: @simonhong

**Comment by Terottaja** [comment] 2019-10-10 13:24
> Tab hover tooltip is same on Chrome as well.
> ![Screenshot from 2019-10-10 08-31-47](https://user-images.githubusercontent.com/17010094/66569051-b0e4ee80-eb38-11e9-8293-5ebbdc3f3e5e.png)
> 
> Hamburger menu is probably a Windows specific theming issue. cc: @simonhong

The hamburger menu thing appears on my Windows 8.1 machine, wasn't like this before updating.

**Comment by Terottaja** [comment] 2019-10-25 06:36
No longer reproducible as seen below,
![image](https://user-images.githubusercontent.com/31454692/67548574-cba78d80-f70a-11e9-9bca-3d63239b0def.png)
![image](https://user-images.githubusercontent.com/31454692/67548612-e548d500-f70a-11e9-8fd4-778f489b65d2.png)
Should this be closed?

**Comment by srirambv** [comment] 2019-10-25 12:51
@Terottaja  Thanks for the update. Looks like the new chromium fixed it with hovercards. We can close the issue for now and reopen it if it reproduces again

**Closed by srirambv** 2019-10-25 12:51 UTC
Labels: OS/Windows, design, feature/themes, priority/P4
