### ISSUE TITLE
Brave Ads are not displayed on Wayland

### ISSUE THREAD

**Issue by Leuug** [brave/brave-browser#13866] opened 2021-01-31 23:40 UTC
## Description 
Brave Ads are not working on Wayland. I am using the Fedora 33 version of Brave and when I use Xorg they work well, but on Wayland they don't appear.

## Wayland version (1.18.0-2.fc33)

**Comment by lxwulf** [comment] 2021-02-02 07:48
Yes same problem here. Using Fedora 33 with KDE and Xwayland.

Version 1.21.37 Chromium: 88.0.4324.96 (Official Build) nightly (64-bit)
Xwayland Version: 1.20.10

**Comment by Digitalone1** [comment] 2021-03-18 07:10
Just FYI. Ubuntu 21.04 will ship with Wayland by default. This means Brave ad notifications will not work on the most used Linux distribution. Combining this with other little distributions that uses Gnome Wayland and Wayland will be the standard display protocol in the future, it's not a good sign.

**Comment by Pedroassuncao** [comment] 2021-04-04 16:28
Someone have a solution? i am getting no ads on fedora 34 beta with wayland too

**Comment by Digitalone1** [comment] 2021-04-09 12:53
> Someone have a solution? i am getting no ads on fedora 34 beta with wayland too

I'm afraid devs don't have any clue on how to resolve this issue, except to invite people to use the X session, and since Linux has only around 1% market share, it's probably they don't even care.

But from the next April 22 this issue will become more noticeable when lots of users will switch to Ubuntu 21.04 which has Wayland as the default session.

**Comment by tmancey** [comment] 2021-05-14 13:38
Closing issue as supersceded by https://github.com/brave/brave-browser/issues/9592

**Comment by CodeDead** [comment] 2021-07-29 12:14
As a Wayland user, I'm still not receiving any notifications from Brave at all, even with the latest update. I tried logging back into Xorg and low and behold, notifications were back, so this issue should be reopened in my opinion @tmancey .

Brave notifications still do not work on Wayland.

**Comment by Leuug** [comment] 2021-07-29 14:50
I'm still not receiving ads notification too.

**Comment by tmancey** [comment] 2021-07-29 15:06
@Leuug we are reopening this issue

**Comment by Digitalone1** [comment] 2021-07-29 20:18
You closed it because custom ad notifications were implemented. Aren't they supposed to solve the issue?

**Comment by tmancey** [comment] 2021-07-30 20:48
Closing as a duplicate of https://github.com/brave/brave-browser/issues/13833

**Closed by tmancey** 2021-07-30 20:48 UTC
Labels: OS/Linux, feature/ads, needs-investigation

**Comment by YadavGulshan** [comment] 2022-01-11 15:54
Hey I'm on fedora 35, and I'm still can't see any ads in my distro... Still that wayland issue.... Can you please look into it.

**Comment by tmancey** [comment] 2022-01-12 14:57
@YadavGulshan please see workarounds at https://github.com/brave/brave-browser/issues/13833

**Comment by xenithorb** [comment] 2023-05-23 18:04
Now on Fedora 38, same result.

**Comment by tmancey** [comment] 2023-05-23 18:19
@xenithorb I work here at Brave, would you like a screen share so we can investigate? Thanks

**Comment by xenithorb** [comment] 2023-05-23 18:47
Hey there, Just read through the other thread #13833 and enabled `--ozone-platform=wayland`. Checked GPU flags and "Ozone Platform" is now set to "wayland" properly. Will report back if this workaround doesn't fix it. 

I'm currently using:

* Fedora 38
* KDE (Wayland Session)
* Brave v1.51.118 (FLATHUB FLATPAK)

**Comment by jemadux** [comment] 2025-03-08 17:11
anyway to work on archlinux with gnome on 2025?
