### ISSUE TITLE
follow-up to #12203 add `No` button or `Do not ask again option` to show default browser dialog

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#14469] opened 2021-03-04 15:50 UTC
## Description 

Default browser dialog prompt frequency may be too aggressive with asks on 2nd, 3rd, and 4th launches (and finally 8th and 20th launches). Consider adding a `No` button or `Do not ask again` as option to never ask again. Alternatively, could consider removing 3rd ask.

## Steps to Reproduce

See test plan: 
https://github.com/brave/brave-core/pull/7716

## Expected result:
![image-2](https://user-images.githubusercontent.com/5951041/110162210-45da2e80-7da3-11eb-9ddd-bf0763e51051.png)

"No" or "Never ask again" option, alternatively less frequent ask.

## Brave version (brave://version info)

Brave | 1.21.73

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment] 2021-03-04 15:53
cc: @simonhong @bsclifton

**Comment by emarsk** [comment] 2021-03-04 18:44
So, does it stop eventually? Because I'm back to Chrome if it doesn't. And I hope the counter doesn't ever get reset.

It should ask just the first time, if ever.

**Comment by karenkliu** [comment] 2021-03-04 19:24
@rebron @bsclifton Let's remove the 3rd launch ask so it doesn't feel like it's asking every time. 

So 2nd, 4th, 8th, 20th launch.

**Comment by nmarley** [comment] 2021-03-04 19:25
Can you please just give us an option to never see this again? Asking every 2nd, 4th, 8th... seems very annoying still.

**Comment by karenkliu** [comment] 2021-03-04 19:27
We think you might change your mind if you have more time to experience Brave 😉

**Comment by nmarley** [comment] 2021-03-04 19:48
> We think you might change your mind if you have more time to experience Brave 😉

I've been using Brave for a year or two now, but don't want to make it default. And my current experience is not encouraging.

Are those our only options? Either endure the "Make this default" nags or just don't use Brave?

**Comment by karenkliu** [comment] 2021-03-04 19:58
@nmarley We're definitely keeping an eye for more feedback like yours about this newly introduced 'set default browser' nag and will tweak the experience. 

I'm curious though - aside from the default browser nag, what's the main issue you've seen with Brave in the past couple years that turns you off from using Brave as your daily driver?

**Comment by zmre** [comment] 2021-03-04 21:16
My default browser is actually a [browser chooser](https://www.choosyosx.com/). I use different browsers for different purposes. Brave is my default for some things, but not everything. For example, I use site specific browsers for some sites to isolate them from a privacy perspective and to allow me to alt-tab to them. And that's how I want it to stay.

As I close browsers regularly, I'm seeing this nag multiple times in the same day, which is exceptionally annoying.

It's good to know that it will eventually stop, but your UI didn't clue me into the fact that the nag won't last forever, which made me think this was going to be a perpetual problem. I don't think you want your other users thinking the same thing.

Please consider a "Don't Ask Again" option or, worst case if you can't get on board with that,  give some info explaining that you'll only ask X more times before the nag stops.

And now I'm going to go launch/quit/launch/quit until I get back to the happy place. Then I'll hope the counter doesn't reset after the next update.

**Comment by davidgsd** [comment] 2021-03-04 22:17
Do Brave developers really think people need to be asked 5+ times in a row, 8th, 20th etc. ad nauseum, presumably after every Brave update? This kind of assumption on the part of developers that users are not savvy enough to decide for themselves which browsers they want to use and which one they want to be their default without being asked 5 times will definitely become a self-fulfilling prophecy as savvier users look at other options. Thank you

**Comment by JuanCab** [comment] 2021-03-04 22:31
Its particularly irritating that since Brave has gone through a few updates recently, it seems to "reset" the default browser check.  I also use a browser chooser and frankly, I have zero interest in ANY browser other than my chooser being the default.  Please allow users to CONTROL the browser instead of forcing this dialog box up so many times.

**Comment by JuanCab** [comment] 2021-03-04 22:33
> We think you might change your mind if you have more time to experience Brave 😉

Yeah, the more times you nag us the more I have a negative opinion of Brave.  Sorry to be snarky, but I chose Brave because I didn't want a Chromium browser with the Google overhead.  There are other choices that respect the user's ability to make a decision about their default browser... or their ability to go to the preferences and reset the default browser later if they choose to.

**Comment by JuanCab** [comment] 2021-03-04 22:39
> @rebron @bsclifton Let's remove the 3rd launch ask so it doesn't feel like it's asking every time.
> 
> So 2nd, 4th, 8th, 20th launch.

No, no, no.  Please only ask one time. Being aggressive like this is a BIG turn off and inconsistent with the behavior people expect from browsers.  If you keep asking, users will assume the setting isn't 'sticking' and will think Brave is buggy in this regard.  Honestly, its what I thought which is why I came to github to report it as an error!

If you want to break the standard operating procedure used by other browsers and plan on re-asking several times, you really  checkbox saying "Don't ask again."  This makes it clear to the user that saying "not now" isn't enough to truly turn off the feature.

I really suspect if you don't do something like this, people will keep reporting this behavior as 'buggy' in the future.

**Comment by karenkliu** [comment] 2021-03-04 22:51
I hear you - all of this feedback is welcome and helpful. As mentioned, we're definitely keeping tabs on feedback like this and will tweak the experience.

>presumably after every Brave update

☝️ The counter should *not* be resetting after every update, so if this is happening it's a bug.

**Comment by ocdtrekkie** [comment] 2021-03-04 23:09
Removing the ability to disable default browser nags is vehemently anti-user, and shows a surprising choice to be more user hostile than *Google* manages to be.

The answer is simple: The same place in settings where the option to make it default exists, must also be a single option to disable it asking. Every other browser has this. Yours doesn't. Fix it.

**Comment by rebron** [comment] 2021-03-05 03:10
@ocdtrekkie "Vehemently" more user hostile than Google? Really? That one hurts. Issue has been filed, work and fix is underway. In the meantime, launch Brave 21 times as the quick workaround, and I'm not being facetious as I get that this type of dialog prompt can be deeply annoying.  

There's always a cognitive load when there's several choices to a dialog, here it would be three "not now", "set as default" and adding a third "don't show again" and having the three options isn't always the best choice. We went with ask five times and don't ever show again. In other places like with widevine component or presenting an option for translations, we went with the three options as those would show in context every time.

**Comment by ocdtrekkie** [comment] 2021-03-05 03:22
If you ask someone the same question more than once, it means you aren't taking no for an answer, @rebron. Asking more than once, for that matter, five times, is a statement of disrespect.

Please remember that your users know what they want. If they wanted Brave to be the default, they'd do so the first time you ask. Or, they'd go into browser Settings and click the button there. Or their OS' default apps settings page. Sure, maybe asking *one* more time after the user has had time to spend with the browser might be defensible, but five is not.

Remember that for every default user a repetitive ask has gained you, you burned your reputation and goodwill with others, possibly irreparably, in exchange.

**Comment by zmre** [comment] 2021-03-05 03:38
For what it's worth, I think Safari asks once per version. It's vaguely annoying, but not a huge deal since they don't update all that often. 

Brave's approach bothered me in part because I was repeatedly saying no in a single day.

It bothered me enough that I checked preferences and then when Internet hunting for a fix.

In finding this thread, I found a workaround, but the whole magic "open it 21 times to fix the problem" thing is something I wouldn't wish on anyone. And I did it. Also, that magic number isn't communicated in the app.  And whatever cognitive load was saved by removing a button choice was eaten up many times over in trying to find a way to stop the nagging.

I think of Brave's user base as being more technically sophisticated than average. Possibly I'm way off base on that, but regardless, it doesn't feel like you're giving your users much credit here.

I'm writing this in the hopes that it will persuade you to do more than just tweak the nag intervals.  The problem is solved for me, but I hope to save others from a similarly negative experience.

**Comment by rebron** [comment] 2021-03-05 05:22
@zmre I appreciate the feedback and sharing your use case (and using Brave multiple times in a day it seems like). We're getting to a point where we are attracting more mainstream users and we want to remind them about this setting. Being in settings at all is by definition buried and this is one of the important ones we do want to highlight. 

It's clear the ask is a "no" or "do not ask again option" (both will mean the same thing as don't show again) and that's how I've labelled the issue and that's what we're exploring. A negative user experience is not what we want.

@ocdtrekkie I can see persistent (in the positive) or annoying or overly aggressive (in the negative). Disrespectful? I really hope not. I hope we haven't irreparably lost you as a user because of this dialog and that on your own you'll make us your default browser. Earning goodwill is tough, I agree.

**Comment by zpcc** [comment] 2021-03-05 07:42
The counter seems not working if I start brave.exe with `--incognito`. And I think a 'No' button is really necessary.

**Comment by metalim** [comment] 2021-03-05 09:12
Was looking for a method to turn off those annoying notifications, found this thread. Discussion is hilarious, authors believing it's good to ask for acceptance on 2nd, 3rd, 4th, 8th AND 20th launch is beyond my understanding of how user loyalty should be acquired. Good luck, guys.

**Comment by githubmarker** [comment] 2021-03-05 18:37
Agreed with others. 
Asking a YES/NO question and only giving the user a "Not Now" option is impolite.

As a random sample of user frustration and confusion, here's a thread created yesterday.
https://www.reddit.com/r/BATProject/comments/lxt36b/brave_asking_to_be_default_again/

I came across it while searching for: brave stop asking default.
It wasn't that helpful, which is why my next search was: brave github issues.

**Comment by bbondy** [comment] 2021-03-05 18:54
We're sorry for the misstep, we'll get it fixed, landed, uplifted to release channel, and released to production asap 👍

**Comment by rebron** [comment] 2021-03-05 19:17
We working on a two step fix for this:
1) Only asking twice https://github.com/brave/brave-browser/issues/14502 on 3rd and 20th browser opens. Fix in release soon.
2) Adding `Do not show again` checkbox. Prelim designs added.
https://user-images.githubusercontent.com/5951041/110162210-45da2e80-7da3-11eb-9ddd-bf0763e51051.png

**Comment by ocdtrekkie** [comment] 2021-03-05 21:59
3rd and 20th sounds good to me. That's not obnoxious, and the checkbox is good too.

Thanks!

**Comment by raymondyu11365** [comment] 2021-03-05 23:14
I use different browsers for different stuff (one for work, one for emails/personal stuff, one for youtube/news/fun stuff). The brave default browser popup annoys me because I use it for youtube/news/funstuff and I don't want opening links for work to popup in brave instead of my work browsers.

Great to see you peeps at brave being transparent on what you're doing.

**Comment by aa956** [comment] 2021-03-08 11:15
Although complete and final opt-out option would be ideal it would be nice to document this behavior, e.g. in the popup itself, something like this:

> ### Set Brave as your default browser
> **We're asking this question 2nd time out of 8 total**
> **[Not now]** **[Set as default]**

Reason for request for additional explanation in the dialog itself is that seeing this popup first few times I've tried to uninstall and reinstall the Brave to get rid of the popup suspecting malicious extension (using different browsers for different tasks: work, personal, legacy web application etc. and will not change the default one that is not Brave).

**Comment by VAggrippino** [comment] 2021-03-09 20:48
Every other browser has a checkbox that can be unchecked, labeled something like _Always check if Brave is my default browser_. "Playful snark" my ---... This was a conscious decision to irritate users.

**Comment by LodeHere** [comment] 2021-03-13 12:21
After some years of enjoying Brave as a most user friendly browser with many options to customize it -which I have done to exactly my taste- the sudden appearance of the constant question it I want to make Brave my default browser feels like a an aggressive Foot-in the Door sales tactic. 
After every time you say politely "No, thank you" to the salesman he rings the bell again and when you open he again puts his foot in your door.... 
I wonder if that idea came from a new member entering the Brave team who worked in an aggressive sales department for a commercial company....

The thought has passed my mind to uninstall Brave and check now and then if that trick has stopped. So I can install Brave again without the frustration felt every time I open that otherwise great browser.

**Closed** 2021-04-06 22:48 UTC
Labels: OS/Desktop, QA/Yes, feature/settings, priority/P3, release-notes/include

**Comment by stephendonner** [comment] 2021-04-14 20:43
Hi @simonhong I extended and modified the testplan you posted in https://github.com/brave/brave-core/pull/8253, for a few more scenarios/combinations; mind taking a look and providing feedback here?  Thanks in advance!

### Scenario One - Not now (button)

1. set Chrome as the default browser
2. new profile for Beta
3. launch Brave Beta (1st)
4. uncheck `Set Brave as your default browser`
5. click the `Start Brave` button
6. click on the `Skip welcome tour`link and create a new-tab page
7. shut down and relaunch Brave Beta
8. shut down and relaunch Brave Beta (3rd)
9. confirm you get `Set Brave as your default browser` prompt
10. click the `Not now` button
11. shut down and relaunch Brave Beta 17 more times
12. confirm you get `Set Brave as your default browser` prompt (20th launch)
13. continue to shut down and relaunch Brave Beta a few more times
14. confirm you no longer get prompted to set Brave as your default browser

### Scenario Two - Don't ask again (checkbox)

1. set Chrome as the default browser
2. new profile for Beta
3. launch Brave Beta (1st)
4. uncheck `Set Brave as your default browser`
5. click the `Start Brave` button
6. click on the `Skip welcome tour`link and create a new-tab page
7. shut down and relaunch Brave Beta
8. shut down and relaunch Brave Beta (3rd)
9. confirm you get `Set Brave as your default browser` prompt
10. click on `[x] Don't ask again`
11. click on `Not now`
12. shut down and relaunch Brave Beta 17 more times
13. confirm you no longer get prompted to set Brave as your default browser

### Scenario Three - Don't ask again (checkbox), multiple profiles

1. set Chrome as the default browser
2. new profile for Beta
3. launch Brave Beta (1st)
4. uncheck `Set Brave as your default browser`
5. click the `Start Brave` button
6. click on the `Skip welcome tour`link and create a new-tab page
7. shut down and relaunch Brave Beta
8. shut down and relaunch Brave Beta (3rd)
9. confirm you get `Set Brave as your default browser` prompt
10. click on `[x] Don't ask again`
11. click on `Not now`
12. shut down and relaunch Brave Beta 17 more times
13. confirm you no longer get prompted to set Brave as your default browser
14. create a new profile and close all other profiles
15. launch Brave Beta a few more times using the new profile
16. confirm you no longer get prompted to set Brave Beta as your default browser

### Scenario Four - Set as default (button)

1. set Chrome as the default browser
2. new profile for Beta
3. launch Brave Beta (1st)
4. uncheck `Set Brave as your default browser`
5. click the `Start Brave` button
6. click on the `Skip welcome tour`link and create a new-tab page
7. shut down and relaunch Brave Beta
8. shut down and relaunch Brave Beta (3rd)
9. confirm you get `Set Brave as your default browser` prompt
10. click on the `Set as default` button
11. confirm you get the `Do you want to change your default browser to "Brave" or keep using "Chrome"?` dialog
12. click on the `Use "Brave"` button
13. shut down and relaunch Brave Beta
14. open `brave://settings/?search=default` and confirm it says `Brave is your default browser`
15. shut down and relaunch Brave a few more times
16. confirm you're never prompted for the default browser again

/cc @brave/legacy_qa for visibility/potential feedback, too

**Comment by simonhong** [comment] 2021-04-14 23:38
@stephendonner Looks great 👍

**Comment by phineas12** [comment] 2021-08-20 00:12
This is still broken on Android, where it's a far more irritating full screen takeover.
https://github.com/brave/brave-browser/issues/17014

**Comment by fiveangle** [comment] 2024-11-22 17:52
It's  back at it's old tricks on macOS

(╯°□°)╯︵ ┻━┻)

**Comment by Targren** [comment] 2024-12-29 02:44
On Windows as well ([Version 1.73.104]). It just asked me again when I told it "no" a long time ago.

And having it stapled to the top item of the menu now is even more obnoxious.
