### ISSUE TITLE
Should set as pinned state only when it's actually pinned

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#26301] opened 2022-10-26 21:01 UTC
## Steps to Reproduce

1. Install 1.46
2. launch Brave
3. Click `Pin` button
4. Setting should not changed to pinned
5. Allow from os notification (Allow should be done within 20s after clicking pinned)
6. Settings should be changed to pinned

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.46.80 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 11 Version 21H2 (Build 22000.1098)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@simonhong @rebron

**Comment by simonhong** [comment] 2022-10-26 23:17
Pin state is expected behavior now. Checkbox is only in effective when user clicks `Set Brave as..` button.
@rebron Should we pin always when user checks?

Regarding to default browser state, Browser should not be set as a default when user clicks `Maybe later`.
I tested and can't repro. Can you check again?

**Comment by MadhaviSeelam** [comment] 2022-10-27 00:08
@simonhong - so this might be happening with a fresh installs 
Scenario 1: Fresh installs

- Install 1.46.80
- launch Brave
- either select  not select `Pin to taskbar` in the first run dialog
- Click `May be later`
- go to `brave://settings/getStarted`

<img width="467" alt="image" src="https://user-images.githubusercontent.com/98358127/198160164-48568c86-9af7-4d4c-918e-40e77db5ae58.png">

Scenario 2: Pin Brave to taskbar

- new profile
- already Brave is pinned to taskbar
- launch Brave
- Click `May be later`
- go to `brave://settings/getStarted`

<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/198160371-64a3f7e9-aefa-45d8-94af-14d5721024eb.png">

**Comment by MadhaviSeelam** [comment] 2024-04-02 20:46
Reproduced this issue still after double notification of `Pin to taskbar` issue fix in https://github.com/brave/brave-browser/issues/36470

App notifications in OS settings turned on

https://github.com/brave/brave-browser/assets/98358127/27fc7d43-229b-44df-84e3-ac15db853656

App notifications in OS settings turned off

https://github.com/brave/brave-browser/assets/98358127/176ee966-bd6c-4b6c-81c4-1545dba22966

**Comment by mherrmann** [comment] 2024-04-04 14:47
During my recent work on #36470, I don't think I ever got the initial popup by Brave that has the checkbox for pinning to the taskbar:

![image](https://github.com/brave/brave-browser/assets/1076393/75f7e873-76f6-4d62-bb7f-753037137816)

Maybe it only appears on older Windows versions than the one I have.

I did get the OS-level notifications.

![image](https://github.com/brave/brave-browser/assets/1076393/a7a91e0d-49dc-4635-afaf-54290141df42)

The OS-level notifications come from upstream.

One thing I saw in the code is that we have our own logic for pinning, in `brave_shell_integration_win.cc`. It felt strange to me that we have such code when similar code exists upstream.

My suspicion is that the problem can be fixed by invoking upstream's implementation for pinning to the task bar. And that we should clean up our associated code if it is no longer used. To that end, it would be interesting to find out if the initial run popup still gets shown on some Windows versions.

**Comment by simonhong** [comment] 2024-04-17 00:58
We've not been using first-run dialog for a long time as we prefer welcome page flow to first run dialog.
So, this os task bar notification will not be shown by first run dialog anymore.
However, we still have `Pin` settings at brave://settings/getStarted
It seems Windows want to double check whether user want to pin or not by using that os notification.
If user doesn't click `Yes`, it's still not pinned but settings state becomes pinned because we have assumption that
pin request will be done w/o more user action. but it's changed in Windows.
Although, settings page has proper state after reloading, I think we need to find more better way to make it pinned w/o showing os notiification if possible. Or should update settings page after getting final pin state.

**Comment by simonhong** [comment] 2024-04-22 02:52
Checking

**Comment by simonhong** [comment] 2024-04-22 06:17
It's very difficult to debug as pin/unpin Win api is undocumented api.
At first, it worked as expected w/o user consent but it seems changed.
To pin brave to task bar, user should agree via os notification.
Not sure what we can do here.
Should we change UX or settings text such as `Ask to Windows to pin to task bar` and sub label like `To pin to task bar,  user should allow from os notification`. WDYT? @rebron @aguscruiz

**Comment by aguscruiz** [comment] 2024-04-22 12:04
How about something like:

**Title**: Pin to task bar
**Description**: Click Pin and confirm in the following Windows notification.

@rebron @sangwoo108 ?

**Comment by simonhong** [comment] 2024-04-24 03:11
Updated this issue's title and description as we don't use first run dialog.

**Closed** 2024-04-24 22:37 UTC
Labels: bug, OS/Windows, priority/P2, QA/Yes, release-notes/include, OS/Desktop, retention

**Comment by MadhaviSeelam** [comment] 2024-05-02 19:10
Verification `In progress` using
```
Brave | 1.67.59 Chromium: 124.0.6367.118 (Official Build) nightly (64-bit)
-- | --
Revision | 96b3194901e5b7509e4e2d7408e73b67c552aa77
OS | Windows 11 Version 23H2 (Build 22631.3527)
```

Case 1: Pin Brave to taskbar via first notification during initial install
<details>

1. Installed 1.67.59
2. launched Brave
3. clicked `Yes` on `Would you like to pin `Brave Nightly to your taskbar?
4. clicked context menu on taskbar Brave icon 
5. opened brave://settings/getStarted in a new tab 

#### Confirmed Brave is pinned to taskbar
#### Confirmed `Brave is already pinned` text shown in `brave://settings/getStarted`

step 3| step 4| step 5
----- | ----- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/fbb2a216-14fe-43fe-9e53-3010e70f7aae)|![image](https://github.com/brave/brave-browser/assets/98358127/fb74379d-fdd8-466e-89dc-ff8a846b2951)|![image](https://github.com/brave/brave-browser/assets/98358127/f7f47495-8019-4622-9067-a3133e733a27)
</details>

Case 2: Do not Pin Brave to taskbar during initial install but Pin via `brave://settings/getStarted`

<details>

0. Unpin Brave if it's pinned
1. Installed 1.67.59
2. launched Brave
3. clicked `No` on `Would you like to pin `Brave Nightly to your taskbar?
4. clicked context menu on taskbar Brave icon 
5. verified Brave is not pinned to taskbar
6. opened `brave://settings/getStarted` in a new tab 
7. clicked `Pin` button
8. clicked `Yes` on the OS notification `Would you like to pin Profile 1 - Brave to your taskbar?`
9. verified `Pin` button is dismissed

#### Confirmed Brave is pinned to taskbar
#### Confirmed `Brave is already pinned` text shown in `brave://settings/getStarted`

step 3| step 5 | step 7 | step 8 | step 9
----- | ----- | ------ | ------ | -----
![image](https://github.com/brave/brave-browser/assets/98358127/b0697ee2-f0ef-4b13-8198-676e250e2dc4)|![image](https://github.com/brave/brave-browser/assets/98358127/8fe63d7c-7b9a-4d27-883c-116169a1865d)|![image](https://github.com/brave/brave-browser/assets/98358127/98d88800-3b9a-4a8b-8241-3bdc0d9a2319)|![image](https://github.com/brave/brave-browser/assets/98358127/5f0b6959-d5c4-42b1-ab86-912bacfeb694)|![image](https://github.com/brave/brave-browser/assets/98358127/3c916e79-98b7-42d0-8b31-e56582528b50)
</details>

Case 3: Pin Brave to taskbar via `brave://settings/getStarted` 
<details>

0. Unpin Brave if it's pinned
1. Installed 1.67.59
2. launched Brave
3. ignore or do not click anything on the OS notification `Would you like to pin `Brave Nightly to your taskbar?
4. clicked context menu on taskbar Brave icon 
5. verified Brave is not pinned to taskbar
6. opened `brave://settings/getStarted` in a new tab 
7. clicked `Pin` button
8. clicked `Yes` on the OS notification `Would you like to pin Profile 1 - Brave to your taskbar?`
9. verified `Pin` button is dismissed
10. click `x` on first notification 

#### Confirmed Brave is pinned to taskbar
#### Confirmed `Brave is already pinned` text shown in `brave://settings/getStarted`

![image](https://github.com/brave/brave-browser/assets/98358127/e375d0a9-f165-4ed8-a234-1c9c9c2a5d69)
![image](https://github.com/brave/brave-browser/assets/98358127/dd5b23aa-e895-4c7c-a55f-d343912858cf)
![image](https://github.com/brave/brave-browser/assets/98358127/0fd52a73-6ab2-48f4-9dcd-b80095ad9bec)
![image](https://github.com/brave/brave-browser/assets/98358127/597d9252-4187-454b-a842-97cda7865e5f)

</details>

**Comment by MadhaviSeelam** [comment] 2024-05-10 17:53
Verification `PASSED` using
```
Brave | 1.66.104 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | 6213f85e37bb676772fb221ce11a41c2b1be0fe2
OS | Windows 11 Version 23H2 (Build 22631.3527)
```

Case 1: Pin Brave to taskbar via `brave://settings/getStarted`  - `PASSED`
<details>

1. Installed `1.66.104`
2. launched Brave
3. clicked context menu on taskbar Brave icon 
4. verified Brave is not pinned to taskbar
5. opened `brave://settings/getStarted` in a new tab 
6. clicked `Pin` button
7. clicked `Yes` on the OS notification `Would you like to pin Profile 1 - Brave to your taskbar?`
8. verified `Pin` button is dismissed in `brave://settings/getStarted` page
9. clicked context menu on taskbar Brave icon 


#### Confirmed Brave is pinned to taskbar
#### Confirmed `Brave is already pinned` text shown in `brave://settings/getStarted`

step 4 | step 5| step 7| step 8 | step 9
------ | ----- | ----- | ---- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/c20630fe-ab0c-4fed-9df7-907cebfae2da)|![image](https://github.com/brave/brave-browser/assets/98358127/04763ece-553e-4b4e-93e2-76eca5010ea7)|![image](https://github.com/brave/brave-browser/assets/98358127/f1f39a86-3b22-4af4-9957-ade87b2090b4)|![image](https://github.com/brave/brave-browser/assets/98358127/dbfb9916-5f47-48ce-acc9-d4e176bbc94b)|![image](https://github.com/brave/brave-browser/assets/98358127/d0666d7f-4c7c-42ce-b60f-143145491f7b)
</details>

Case 2: Pin to taskbar via Brave icon context menu - `PASSED` 
<details>

0. Unpin Brave if it's pinned
1. Installed 1.66.104 
2. launched Brave
4. clicked context menu on taskbar Brave icon 
5. verified Brave is not pinned to taskbar
6. clicked Brave icon context menu in the taskbar
7. clicked `Pin to taskbar`
8. opened `brave://settings/getStarted` in a new tab 

#### Confirmed Brave is pinned to taskbar
#### Confirmed `Pin` button is dismissed in `brave://settings/getStarted` and `Brave is already pinned` text shown

step 5 | step 7 | step 8
------ | ----- | -----  
![image](https://github.com/brave/brave-browser/assets/98358127/16e414ee-8b1c-4027-b91c-ec1be9053fc0)|![image](https://github.com/brave/brave-browser/assets/98358127/e9e8ff28-9ae7-47bd-8035-f1010108b239)|![image](https://github.com/brave/brave-browser/assets/98358127/df51d97b-71e1-4803-936f-7e71d4619037)
</details>

Case 3: Do not pin Brave via OS notification - `PASSED`
<details>

0. Unpin Brave if it's pinned
1. Installed `1.66.104`
2. launched Brave
3. clicked context menu on taskbar Brave icon 
4. verified Brave is not pinned to taskbar
5. opened `brave://settings/getStarted` in a new tab 
6. clicked `Pin` button
7. clicked `No, thanks` on the OS notification `Would you like to pin Profile 1 - Brave to your taskbar?`
8. verified `Pin` button is still shown in `brave://settings/getStarted` page
9. clicked context menu on taskbar Brave icon 

#### Confirmed Brave is not pinned to taskbar
#### Confirmed `Pin` button is not dismissed in `brave://settings/getStarted` 

step 4 | step 7 | step 9
------ | ----- | -----  
![image](https://github.com/brave/brave-browser/assets/98358127/792b273c-881a-4b9b-b068-965b165b5a67)|![image](https://github.com/brave/brave-browser/assets/98358127/4d6f9adc-3f8e-4861-baeb-116430cc29cc)|![image](https://github.com/brave/brave-browser/assets/98358127/d3bfe6c1-ae7a-461e-bde3-d182cefd9316)
