### ISSUE TITLE
Intermittent Test Failure: RewardsContributionBrowserTest.RecurringTipForUnverifiedPublisher

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#12556] opened 2020-11-06 20:13 UTC
```
11:51:10  [  FAILED  ] RewardsContributionBrowserTest.RecurringTipForUnverifiedPublisher, where TypeParam =  and GetParam() =  (19333 ms)
11:51:10  
11:51:10  [706/706] RewardsContributionBrowserTest.RecurringTipForUnverifiedPublisher (19499 ms)
11:51:10  1 test failed:
11:51:10      RewardsContributionBrowserTest.RecurringTipForUnverifiedPublisher 
```

**Comment by NejcZdovc** [comment] 2020-11-06 20:28
closing as dupe of https://github.com/brave/brave-browser/issues/12295

**Closed by NejcZdovc** 2020-11-06 20:28 UTC
Labels: OS/Desktop
