### ISSUE TITLE
Click on Browser back button resets the newtab stats

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#2018] opened 2018-11-06 23:22 UTC
## Description 

Click on Browser back button resets the newtab stats

## Steps to Reproduce

   1.  Launch browser and open newtab and check stats are  properly visible
   2. Go to www.google.com from newtab by typing it in omnibox
   3.  Press backbutton to go newtab again

## Actual result:

All newtab stats are zero

## Expected result:
stats should not be all zero

## Reproduces how often: 

Easily

## Brave version (brave://version info)

All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

I think the cause of https://github.com/brave/brave-browser/issues/1490 is related with this.
`chrome://adblock/` also has same issue.

**Comment by srirambv** [comment] 2018-11-06 23:44
dupe of https://github.com/brave/brave-browser/issues/307

**Comment by srirambv** [comment] 2018-11-06 23:44
@simonhong assigned #307 to you

**Closed by srirambv** 2018-11-06 23:44 UTC

**Comment by simonhong** [comment] 2018-11-06 23:57
@srirambv Oops. we have one already. Thanks!
I'm working this this issue now
