### ISSUE TITLE
Invalid wallet is created on clean install

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#13026] opened 2020-12-03 07:19 UTC
This is a regression introduced in 1.18.68. Not reproducible on 1.18.66

## Steps to Reproduce

   1. Install 1.18.68
   2. Run Brave
   3. Enable Rewards
   4. Check logs

## Actual result:

Invalid wallet is created
Failed to fetch unblinded tokens
```
[7228:12184:1203/074116.757:INFO:refill_unblinded_tokens.cc(72)] Failed to refill unblinded tokens due to an invalid wallet
```

## Expected result:
Wallet is created without problems
Able to fetch unblinded tokens

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Reproducible on

Brave | 1.18.68 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Not reproducible on 

Brave | 1.20.5 Chromium: 87.0.4280.67 (Official Build) nightly (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

cc @brave/legacy_qa @marshall @rebron

**Comment by emerick** [comment] 2020-12-07 17:59
@btlechowski This happens every time with `1.18.68`? It seems a little odd, because no functional change was introduced between `1.18.66` and `1.18.68` from what I can see...

**Comment by emerick** [comment] 2020-12-07 21:45
I'm seeing the following on Windows with `1.18.68`, but it's a little different from what's described in the issue description and doesn't result in an invalid wallet:

```
[20304:15416:1207/163851.497:VERBOSE1:ads_impl.cc(542)] Failed to refill unblinded tokens
[20304:15416:1207/163851.498:VERBOSE1:refill_unblinded_tokens.cc(309)] Retry refilling unblinded tokens in 0 hours, 0 minutes, 10 seconds at 4:39 PM
```

**Comment by btlechowski** [comment] 2020-12-07 22:05
@emerick Thank you for looking into it.

The only change that was introduced between 1.18.66 and 1.18.68 was `Uplift of #7281 (squashed) to beta`. Not sure if this is related.

The message you are seeing happens if you already claimed to many unblinded tokens (server side check). 

The issue was easy to reproduce. @GeetaSarvadnya reproduced it. 

It could be that it was some server glitch.

**Comment by emerick** [comment] 2020-12-07 22:33
@btlechowski Thanks for the info, I wonder if https://github.com/brave/brave-core/pull/7281 had an unintended consequence. Will check in with @zenparsing.

@GeetaSarvadnya Are you still able to repro the problem? If you're able to test it again, I'd appreciate it. If you're no longer seeing it, it could be a temporary service problem as @btlechowski mentioned.

**Comment by btlechowski** [comment] 2020-12-08 11:01
I am not able to reproduce on 1.18.68. Not sure what happened.

Let's wait for @GeetaSarvadnya to check on her end.

**Comment by GeetaSarvadnya** [comment] 2020-12-08 12:31
I can still reproduce the issue in `1.18.68`

```
[2612:17400:1208/175852.445:INFO:refill_unblinded_tokens.cc(72)] Failed to refill unblinded tokens due to an invalid wallet
```

**Comment by GeetaSarvadnya** [comment] 2020-12-08 12:39
The issue is still reproducible for me in `1.18.68` I have tried 3 times, it was reproducible twice.

```
[14264:16160:1208/180701.941:INFO:refill_unblinded_tokens.cc(72)] Failed to refill unblinded tokens due to an invalid wallet
```

**Comment by emerick** [comment] 2020-12-08 12:47
@GeetaSarvadnya OK, thank you for testing. Could you give me a copy of your full log for one of the failure attempts? Thank you.

**Comment by GeetaSarvadnya** [comment] 2020-12-08 13:28
@emerick Sure, Please check the DM.

**Comment by zenparsing** [comment] 2020-12-08 15:02
@GeetaSarvadnya does this also repro on 1.18.69? It looks like some fixes are in 1.18.69 that are not in 1.18.68 (in particular https://github.com/brave/brave-core/pull/7276).

**Comment by emerick** [comment] 2020-12-08 16:07
@zenparsing Thanks for pointing that out. I also noticed that the first sign of a problem in the log file is ads-related:

```
[14264:16160:1208/180700.053:INFO:ads_service_impl.cc(381)] Failed to get wallet
```

**Comment by GeetaSarvadnya** [comment] 2020-12-08 16:41
@zenparsing The issue is not reproducible in `1.18.69`

**Comment by emerick** [comment] 2020-12-08 16:44
Thanks for checking @GeetaSarvadnya, that's great. @btlechowski could you try with `1.18.69` and confirm that version works OK for you? If so, then I think we could close this issue out.

**Comment by GeetaSarvadnya** [comment] 2020-12-09 05:40
@emerick @btlechowski has already verified the issue in `1.18.69` and mentioned in the QA Channel that the issue is not reproducible in `1.18.69`

**Comment by emerick** [comment] 2020-12-09 14:16
@GeetaSarvadnya OK, thanks for the update! I'll close this one out as it appears to work as expected now in `1.18.69`. Thank you both for all of the help.

**Closed by emerick** 2020-12-09 14:16 UTC
Labels: OS/Desktop, QA/Test-Plan-Specified, QA/Yes, feature/rewards, release/blocking

**Comment by GeetaSarvadnya** [comment] 2020-12-09 15:19
Verification passed on

```

Brave | 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.630)


```
- Verified the STR from the description and ensured unblinded tokens are refilled and Ads are served to user
```
[17828:2868:1209/204242.832:VERBOSE1:refill_unblinded_tokens.cc(95)] Refill unblinded tokens
[17828:2868:1209/204242.832:VERBOSE1:refill_unblinded_tokens.cc(105)] RequestSignedTokens
[17828:2868:1209/204242.832:VERBOSE2:refill_unblinded_tokens.cc(106)] POST /v1/confirmation/token/{payment_id}
[17828:2868:1209/204242.837:VERBOSE1:refill_unblinded_tokens.cc(344)] Generated and blinded 50 tokens
```
![image](https://user-images.githubusercontent.com/38657976/101648577-f6b08600-3a5f-11eb-87c2-609d9f7c04a3.png)
