### ISSUE TITLE
Prompt users to create a Solana account in dapp request solana.connect

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#24089] opened 2022-07-17 00:35 UTC
Current we reject the request with internal error if users don't have any Solana accounts setup.
We should guide users to create one instead of internal error, otherwise users wouldn't know what went wrong exactly.
ex. https://github.com/brave/brave-browser/issues/24074

**Comment by srirambv** [comment] 2022-07-18 08:19
Dupe of #23898?

**Closed** 2022-07-18 16:58 UTC
Labels: OS/Desktop, feature/wallet/solana, feature/wallet/dapps
