### ISSUE TITLE
hover over small news item publisher overlap

### ISSUE THREAD

**Issue by OliverRedman** [brave/brave-browser#16216] opened 2021-06-02 23:01 UTC
## Description 

Hover effect overlaps with writing on small news item publisher.

## Steps to Reproduce

   1. hover over a small news items publisher on desktop
   2. 
   3. 

## Actual result:

![Screenshot 2021-06-02 at 23 55 31](https://user-images.githubusercontent.com/72112325/120562383-326c4d00-c3fe-11eb-91e4-2d0772707ea3.png)

## Expected result:
There is enough space that the two don't overlap.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.24.85 Chromium: 90.0.4430.212&nbsp;(Official Build)&nbsp;(arm64)
-- | --
Revision | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | macOS Version 11.3.1 (Build 20E241)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? no idea
- Can you reproduce this issue with the nightly channel?  no idea

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? yes

**Comment by srirambv** [comment] 2021-06-03 13:31
Dupe of #14195

**Closed by srirambv** 2021-06-03 13:31 UTC
Labels: OS/Desktop
