### ISSUE TITLE
BAT confirmations are initialized on clean profile

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#10085] opened 2020-06-04 12:19 UTC
Follow up to https://github.com/brave/brave-browser/issues/9544

## Steps to Reproduce

   1. Clean profile
   2. Run Brave with: 
   In `1.10.x` use `--enable-logging=stderr --vmodule=brave_ads=3`
   in `1.11.x` use `--enable-logging=stderr --vmodule="*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/bat-native-ledger/*"=6`
   3. Check the log for `Initializing confirmations`
   4. Check if file `Default/rewards_service/confirmations.json` is created

## Actual result:

`Initializing confirmations` is recorded in the logs
`Default/rewards_service/confirmations.json` is created

## Expected result:
`Initializing confirmations` is not recorded in the logs
`Default/rewards_service/confirmations.json` is not created

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Verification passed on

Brave | 1.10.82 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @tmancey

**Comment by tmancey** [comment] 2020-06-04 18:50
Fixed in nightly

**Comment by bsclifton** [comment] 2020-06-05 18:21
@tmancey can we close this issue?

**Closed** 2020-06-05 18:32 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/ads, priority/P3

**Comment by LaurenWags** [comment] 2020-06-26 18:18
Verified passed with

```
Brave | 1.11.78 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from description. Confirmed `Initializing confirmations` is not recorded in the logs. Confirmed `Default/rewards_service/confirmations.json` is not created.
* Reproduced issue on 1.10.97 with Rewards never enabled. Upgraded to 1.11.x. Confirmed `Initializing confirmations` is not recorded in the logs. However, since `Default/rewards_service/confirmations.json` was created with 1.10.97, it does still exist.

-----
