### ISSUE TITLE
Follow up of #8781 - Pinned sites are being duplicated after upgrade

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#9299] opened 2020-04-17 18:58 UTC
## Description 

Follow up of #8781 - Pinned sites are being duplicated after upgrade

## Steps to Reproduce

   1. Clen profile 1.7.x
   2. Open 6 different sites
   3. Pin 3 sites in NTP keep reaming 3 sites as it is
   4. Upgrade to 1.8.x
   5. On the existing NTP, 3 pinned tabs and remaining 3 unpinned tabs are shown correctly
   6. Open a NTP
   5. Out of 6 sites, 3 Pinned sites are duplicated and remaining 3 sites are lost in 1.8.x

Note: The issue is reproducible in both 1.7.92 and 1.7.95 
## Actual result:

3 Pinned sites are duplicated and remaining 3 sites are lost in 1.8.x

Before upgrade 1.7.x
![image](https://user-images.githubusercontent.com/38657976/79603306-b899d700-8109-11ea-9cbc-04507607d0ba.png)
After upgrade to 1.8.x
![image](https://user-images.githubusercontent.com/38657976/79603337-cbaca700-8109-11ea-8fee-fa5cd6efa327.png)

## Expected result:
Pinned tabs and all other tabs remain the same after upgrade

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.8.77 Chromium: 81.0.4044.92 (Official Build) dev (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not sure
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @cezaraugusto @rebron

**Comment by GeetaSarvadnya** [comment] 2020-04-17 18:59
Before upgrade in 1.7.92 

![image](https://user-images.githubusercontent.com/38657976/79604352-8ee1af80-810b-11ea-824e-157f5d57c2e5.png)

After upgrade to 1.8.x
![image](https://user-images.githubusercontent.com/38657976/79604417-ae78d800-810b-11ea-82cf-2b27f3eb61f6.png)

**Comment by bsclifton** [comment] 2020-04-17 20:34
cc: @cezaraugusto - may be related to the fix you did for top site migration ☹️

**Comment by cezaraugusto** [comment] 2020-04-22 15:45
@bsclifton this is fixed but needs uplift. https://github.com/brave/brave-core/pull/5219

**Comment by bsclifton** [comment] 2020-04-22 18:23
Closing as duplicate of https://github.com/brave/brave-browser/issues/9008 😄

**Closed by bsclifton** 2020-04-22 18:23 UTC
Labels: OS/Desktop, QA/Test-Plan-Specified, QA/Yes, bug, has fix/needs uplift
