### ISSUE TITLE
Auto-contribute last site remove

### ISSUE THREAD

**Issue by jdkuki** [brave/brave-browser#4601] opened 2019-05-24 19:59 UTC
## Description 

When a single site is in the auto contribution section of brave://rewards, it does not disappear when the button is clicked to remove it. Requires refresh of page.

## Steps to Reproduce

   1. Clean profile
   2. Join Rewards
   3. Navigate to verified site for at least 8 seconds
   4. Open brave://rewards
   5. Remove site from auto contribute list
   6. Text asking to restore should appear, however the site should remain in the list.
   7.  Refresh page, site should be gone. 

## Actual result:

![actual mov](https://user-images.githubusercontent.com/8422122/58353321-0a1ae280-7e23-11e9-9975-a724ffee6681.gif)

## Expected result:
![expected mov](https://user-images.githubusercontent.com/8422122/58353323-0dae6980-7e23-11e9-8ff6-2c4e30045092.gif)

## Reproduces how often: 

Easily reproduced on development build

## Brave version (brave://version info)

| Brave  | 0.67.42 Chromium: 75.0.3770.38 (Developer Build) (64-bit) |
| ------------- | ------------- |
| Revision  | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}|
| OS  | Mac OS X  |

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

**Comment by jdkuki** [comment] 2019-05-24 23:52
The commit that introduced the issue is `c47c337cd2f4843df2b906c6eec2e70ffe06e578` with `publisher_info_database.cc:495` in `brave-core`. The issue is the events the button press triggers are `ExcludePublisher()` then `SaveNormalizedPublisherList()`. `SaveNormalizedPublisherList()` is responsible for sending the event to refresh the list, however, it errors because the list is empty after the single publisher is excluded. I would think the approach would be to add a size check before `SaveNormalizedPublisherList` and emit the refresh event somewhere else. I having trouble deducing where `SaveNormalizedPublisherList` is being called from to add such a check. Removing the check in `publisher_info_database.cc` does fix the issue without any immediate consequences

**Comment by srirambv** [comment] 2019-05-26 12:32
Dupe of #4561

**Closed by srirambv** 2019-05-26 12:32 UTC
