### ISSUE TITLE
[Desktop] brave://discards is blank

### ISSUE THREAD

**Issue by dentistformyeye** [brave/brave-browser#10451] opened 2020-06-24 19:45 UTC
## Description 
brave://discards should show information for each tab open in the browser and should allow for manual freezing/discarding of tabs, but a blank, white screen shows up instead.

## Steps to Reproduce

   1. Start the Brave Desktop app.
   2. Go to [DuckDuckGo](https://duckduckgo.com/) in the current new tab.
   3. Open a new tab and go to chrome://discards. On Brave, this will change to brave://discards automatically.

## Actual result:
Blank, white page.

## Expected result:
![image](https://user-images.githubusercontent.com/51429646/85619277-0d892a80-b630-11ea-8b64-3cfd89ab8242.png)

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.15.4 (Build 19E266)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Haven't tried.
- Can you reproduce this issue with the dev channel? Haven't tried.
- Can you reproduce this issue with the nightly channel? Haven't tried.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A.
- Does the issue resolve itself when disabling Brave Rewards? N/A.
- Is the issue reproducible on the latest version of Chrome? No. chrome://discards works normally on Chrome 83.0.4103.116 (tested on WIndows 10). OS might not matter though.

## Miscellaneous Information:
chrome://discards is listed in chrome://chrome-urls on Brave Desktop (though not for Brave Android).

**Comment by srirambv** [comment] 2020-06-25 04:58
This is a regression possibly on CR 83. I remember it used to work before. Thanks for reporting

**Comment by dentistformyeye** [comment] 2020-06-25 18:33
I remember the bug existed as far back as Brave Desktop 1.8.XX (81.0.4044.129). I don't remember if the bug was in 1.7.XX (81.0.4044.113).

**Comment by jonathansampson** [comment] 2020-09-22 19:26
This page fails to load completely due to the following errors:

> Refused to load the script 'chrome://brave-resources/br_elements/shared_vars_css.m.js' because it violates the following Content Security Policy directive: "script-src chrome://resources chrome://test 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

and

```
(WEBUI context) extensions::safeMethods:20: Uncaught TypeError: Illegal invocation{TypeError: Illegal invocation
    at Object.define (extensions::safeMethods:20:22)
    at extensions::guestViewContainerElement:67:28
    at registerElement (extensions::guestViewContainerElement:56:28)
    at extensions::chromeWebView:220:1}
```

**Comment by bsclifton** [comment] 2020-12-30 07:00
This is fixed with Chromium 88 (Nightly) 😄 I bet we broke this in Chromium 84 upgrade when Polymer UI needed to be adjusted

**Comment by hornetnz** [comment] 2021-01-05 00:07
When will this fix be released?

**Comment by kjozwiak** [comment] 2021-01-05 04:48
> When will this fix be released?

As per @bsclifton, this appears to have been fixed via CR88 which is scheduled to hit the release channel on `January 19, 2021` as per https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule.


> This is fixed with Chromium 88 (Nightly) 😄 I bet we broke this in Chromium 83/84 upgrade when our code touching Polymer UI needed to be adjusted

If that's the case, can we close this off and move it into https://github.com/brave/brave-browser/milestone/155?

**Comment by bsclifton** [comment] 2021-01-15 06:08
@kjozwiak SGTM - will close this and add to milestone. We can call out on release notes since our rebase on Chromium 88 seems to have addressed the root cause

**Closed by bsclifton** 2021-01-15 06:08 UTC
Labels: OS/Desktop, QA/Yes, about-pages/misc, bug, priority/P4, regression, release-notes/include

**Comment by GeetaSarvadnya** [comment] 2021-01-15 11:14
Verification passed on

```

Brave | 1.19.84 Chromium: 88.0.4324.87 (Official Build) (64-bit)
-- | --
Revision | dd01ff8f58c65af81127ad5c105c79d5b571d8f3-refs/branch-heads/4324@{#1702}
OS | Windows 10 OS Version 2004 (Build 19041.685)

```
- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/104718507-fd15da00-5750-11eb-9601-a6d3b744cc81.png)
