### ISSUE TITLE
[C130] - Logs show profile_resetter.cc(116)] Check failed: config_fetcher_. error in Win 11 x64

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#41386] opened 2024-10-03 16:27 UTC
### Description

After launching Brave with standard logging (` --args --enable-logging=stderr`) for the upgrade check from `CR129 --> CR130` with PR builds, noticed an error `[44852:35992:1002/150034.497:ERROR:profile_resetter.cc(116)] Check failed: config_fetcher_.`  This line is not shown/present when I did the upgrade in Release, Beta or Nightly (with 129 builds)

### Steps to reproduce

1. Installed 1.72.58
2. launched Brave with `--args --enable-logging=stderr`
3. Upgrade to 130 PR build
4. observe the logs

### Actual result

Upgrade was successful but the logs show 

```[38476:31412:1002/150737.811:ERROR:profile_resetter.cc(116)] Check failed: config_fetcher_.```

```
C:\Program Files\BraveSoftware\Brave-Browser-Nightly\Application>[38476:31412:1002/150729.106:WARNING:external_provider_impl.cc(513)] Malformed extension dictionary for extension: odbfpeeihdkbihmopkbjmoonfanlbfcl.  Key external_update_url has value "", which is not a valid URL.
[38476:31412:1002/150729.396:WARNING:CONSOLE(4)] "crbug/1173575, non-JS module files deprecated.", source: chrome://resources/js/load_time_data_deprecated.js (4)
[38476:31412:1002/150732.320:ERROR:usb_descriptors.cc(146)] Failed to read length for configuration 1.
[38476:31412:1002/150732.320:ERROR:usb_descriptors.cc(146)] Failed to read length for configuration 2.
[38476:31412:1002/150732.320:ERROR:usb_descriptors.cc(105)] Failed to read all configuration descriptors. Expected 3, got 1.
[38476:31412:1002/150732.320:ERROR:device_event_log_impl.cc(201)] [15:07:32.320] USB: usb_device_win.cc:95 Failed to read descriptors from \\?\usb#vid_0b95&pid_1790#00d76dd4#{a5dcbf10-6530-11d2-901f-00c04fb951ed}.
[38476:31412:1002/150737.811:ERROR:profile_resetter.cc(116)] Check failed: config_fetcher_.
[38476:31412:1002/150738.322:WARNING:CONSOLE(1)] "Could not find style data in module named null", source: chrome://resources/polymer/v3_0/polymer/polymer_bundled.min.js (1)
[38476:31412:1002/150738.323:WARNING:CONSOLE(1)] "Could not find style data in module named null", source: chrome://resources/polymer/v3_0/polymer/polymer_bundled.min.js (1)
```

### Expected result

No error message should be shown

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.72.48 Chromium: 130.0.6723.19 (Official Build) nightly (64-bit)
-- | --
Revision | 70b441e85b783a65b0088d92c496fa56d6509945
OS | Windows 11 Version 23H2 (Build 22631.4169)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@emerick @rebron 
cc: @brave/qa-team

**Comment by mherrmann** [comment] 2024-10-08 13:44
@rebron I understand this is related to updates, but I think the problem actually lies somewhere else.

**Comment by emerick** [comment] 2024-10-08 13:55
I believe the problem is with this patch https://github.com/brave/brave-core/blob/master/patches/chrome-browser-profile_resetter-brandcode_config_fetcher.cc.patch#L9-L10:

```
+  std::move(fetch_callback_).Run(); // tell caller we're done
+  return; // but don't actually do anything (this feature is disabled in Brave)
```

It is calling fetch_callback_ synchronously from the `ProfileResetter` constructor:

```
  config_fetcher_ = std::make_unique<BrandcodeConfigFetcher>(
      g_browser_process->system_network_context_manager()
          ->GetURLLoaderFactory(),
      base::BindOnce(&ProfileResetter::OnDefaultSettingsFetched,
                     base::Unretained(this)),
      GURL("https://tools.google.com/service/update2"), brandcode_);
```

and then tries to access `config_fetcher_` from the callback here, before it has finished being constructed:

```
void ProfileResetter::OnDefaultSettingsFetched() {
  CHECK(config_fetcher_, base::NotFatalUntil::M135);
  DCHECK(!config_fetcher_->IsActive());
}
```

I think the simple fix here is for us to change our patch to run the callback asynchronously. Feel free to reassign to me!

**Closed** 2024-10-09 13:00 UTC
Labels: bug, OS/Windows, QA/Yes, release-notes/exclude, Chromium/upgrade major, OS/Desktop

**Comment by kjozwiak** [comment] 2024-10-09 15:57
The above requires `1.71.111` or higher for verification 👍

**Comment by GeetaSarvadnya** [comment] 2024-10-14 15:03
Verification **PASSED** on

```
Brave | 1.71.112 Chromium: 130.0.6723.44 (Official Build) (64-bit)
-- | --
Revision | 7d51df656b247f9432ee714a6d160142a1e11c13
OS | Windows 10 Version 22H2 (Build 19045.5011)
```
- Confirmed that `Logs show profile_resetter.cc(116)] Check failed: config_fetcher_. error` isn't shown when profile is upgraded from `1.70.x` to `1.71.112`

**Comment by MadhaviSeelam** [comment] 2024-10-14 22:54
Verification `PASSED` using
```
Brave | 1.71.112 Chromium: 130.0.6723.44 (Official Build) (64-bit)
-- | --
Revision | 7d51df656b247f9432ee714a6d160142a1e11c13
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

Confirmed the error `[38476:31412:1002/150737.811:ERROR:profile_resetter.cc(116)] Check failed: config_fetcher_.` is no longer shown when upgraded from `CR129 --> CR130` using `1.70.126 Chromium: 129.0.6668.100`  to `1.71.112 Chromium: 130.0.6723.44`
