### ISSUE TITLE
Fingerprinting protection mode unintentionally breaks several popular sites

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1025] opened 2018-09-07 17:56 UTC
Carried over from https://github.com/brave/browser-laptop/issues/2965

Several popular sites are broken (or were broken with `browser-laptop`) if you enable fingerprinting:
- Google Hangouts
- icloud.com
- dropbox PDF documents
- Google sheets
- messenger.com
- maps.google.com
- fonts.google.com
- photos.google.com
- sketchfab.com

**Comment by snyderp** [comment] 2018-10-01 03:31
I'm not able to re-create on on some of these.  Specifically, the following work with default config:
* maps.google.com
* Google sheets
* https://fonts.google.com/
* messenger.com
* photos.google.com
* https://sketchfab.com/

**Comment by tomlowenthal** [comment] 2018-11-07 22:55
@bsclifton Could you give more detailed repro steps?

**Comment by ericdstoltz** [comment] 2018-11-18 07:12
I'm running into this problem with google maps.  It seems to effect smooth zoom functionality.  With fingerprinting block turned off the maps zoom smoothly similar to chrome and safari.  With it turned on the zoom function is impacted so that it is almost unusable.

**Comment by bsclifton** [comment] 2018-11-19 20:31
@tomlowenthal the original issue has reports which include steps

**Comment by anto-christo** [comment] 2018-12-14 05:09
I am not sure whether this is related to this issue but I just ran into this.

fonts.google.com

### With Shield disabled:
![disabled](https://user-images.githubusercontent.com/22641196/49984014-1190b280-ff8c-11e8-83e6-27adfe98b56f.png)  

### With Shield enabled:
![enabled](https://user-images.githubusercontent.com/22641196/49984021-1bb2b100-ff8c-11e8-9e61-7b8e0ce01038.png)

As you can see, the example fonts are not being rendered with shield up.

**Comment by srirambv** [comment] 2018-12-14 05:39
@anto-christo You have `Device recognition blocked` so any kind of fingerprinting will not work. May be the site requires you to allow fingerprinting to show the fonts correctly. Try setting it to `3rd party device recognition blocked` and see if it works.

**Comment by anto-christo** [comment] 2018-12-14 05:45
@srirambv , setting it to `3rd party device recognition blocked` did work. As you pointed out, the site needs fingerprinting. Maybe to display fonts in regional languages. Thanks for pointing it out !!

**Comment by tomlowenthal** [comment] 2018-12-14 18:50
Looks like it's essentially working as intended.

**Comment by bsclifton** [comment] 2019-07-11 19:33
+1 from https://github.com/brave/brave-browser/issues/5073

There is a possibility we could have a more obvious UX to let people know device recognition was blocked and may be affecting their experience

**Comment by Yuki2718** [comment] 2020-04-28 08:50
Is this only for popular sites? Fingerprinting protection breaks games on `kizi.com` such as `https://kizi.com/games/down-the-mountain`.

![kizi](https://user-images.githubusercontent.com/58900598/80467447-c278d100-8978-11ea-9928-82ea695cfe89.png)

**Comment by pes10k** [comment] 2020-04-28 17:39
@Yuki2718 we're in the process of moving to a new system of protecting against fingerprinting that should address the vast majority of these cases https://github.com/brave/brave-browser/issues/8787. 

This is under implementation right now.  The immediate fix is to disable fingerprinting attempts on sites like this that you trust.  But the linked to meta-issue will be the "real" fix, that should be released before too long

**Comment by Yuki2718** [comment] 2020-04-29 14:47
@pes10k Okay, the coming change looks promising. How about creating a centralized issue tracker which gathers all the problem arising from fingerprinting protection so that any issue can be reported there and you can address each issues in an optimal way (per-site configuration for problematic sites)?

**Comment by pes10k** [comment] 2020-04-30 15:41
Currently we try to use GH labels for that, instead of needing to continually update issue text.  So, i think opening new issues (feel free to CC me and @ryanbr ) would be ideal, and we can label them accordingly.

It would also be fine to report those issues as comments on https://github.com/brave/brave-browser/issues/8787

Thanks!

**Comment by pes10k** [comment] 2020-09-01 21:42
I'm going to close this since its not actionable in its current form , and we're using #8787 going forward to track webcompat issues.  Thanks everyone!

**Closed by pes10k** 2020-09-01 21:42 UTC
Labels: feature/shields/fingerprint, feature/shields/webcompat, needs-investigation, priority/P4
