### ISSUE TITLE
The "Fingerprinting protection" setting returns to its default option when you clear the 'Site Settings'

### ISSUE THREAD

**Issue by BugReporter2** [brave/brave-browser#4495] opened 2019-05-18 16:04 UTC
## Description 
The "_Fingerprinting protection_" setting returns to its default option when you clear the `Site Settings`.

## Steps to Reproduce

   1. Go to Brave Settings and change the "_Fingerprinting protection_" setting from the default option, such as to "Block all fingerprinting" option.
   2. Clear `Site Settings` from Brave settings.
   3. The "_Fingerprinting protection_" setting has returned to its default option.

![Brave_Bug](https://user-images.githubusercontent.com/50286047/57972022-28558e00-799e-11e9-8af2-4969e4768b80.jpg)

## Actual result:
The "_Fingerprinting protection_" setting returns to its default option when you clear the `Site Settings`.

## Expected result:
The _Fingerprinting protection_ setting should remain on the user-selected option after you clear the `Site Settings`.

## Reproduces how often: 
Easily reproduced. This bug always happens.

## Brave version (brave://version info)
Brave: 0.64.76
Chromium: 74.0.3729.157
OS: Windows 10 OS Build 17763.437

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes.
- Can you reproduce this issue with the beta channel?
Yes.
- Can you reproduce this issue with the dev channel?
Yes.
- Can you reproduce this issue with the nightly channel?
Yes.

This has also happened in previous versions of Brave Browser.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No.
- Does the issue resolve itself when disabling Brave Rewards?
No.
- Is the issue reproducible on the latest version of Chrome? 
This is a Brave specific issue.

## Miscellaneous Information:
No miscellaneous Information.

**Comment by srirambv** [comment] 2019-05-18 16:56
Dupe of #2400

**Closed by srirambv** 2019-05-18 16:56 UTC
