### ISSUE TITLE
[Android] Only show shields onboarding when there is something actually blocked

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11092] opened 2020-08-05 11:24 UTC
## Description 
 Only show shields onboarding when there is something actually blocked

## Steps to reproduce 

   1. Clean install Beta/Nightly build
   2. Open `chrome://chrome-urls` via auto suggestion on the new tab
   3. Shows Shields onboarding that new items are blocked

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/89407288-6b705e00-d716-11ea-94c3-0525e32983a3.png)

## Expected result
Should only show when shields is enabled on page

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet):All
   - Android version:All
   
## Brave version
1.12.x beta and 1.14.x nightly builds 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @karenkliu @deeppandya

**Comment by srirambv** [comment] 2020-08-05 11:50
Should only show the onboarding when there is something actually blocked on a page. Visiting sites like brave.com/wikipedia.org which doesn't have any blocked items should not show the onboarding.

**Comment by deeppandya** [comment] 2020-08-10 07:00
@srirambv can you verify this on nightly ? for me it seems to be working fine. i will check if we need to uplift it to 1.12

**Comment by kjozwiak** [comment] 2020-08-10 22:25
> @srirambv can you verify this on nightly ? for me it seems to be working fine. i will check if we need to uplift it to 1.12

Running through the above on the following builds so we can get https://github.com/brave/brave-core/pull/6382 uplifted:

```
Brave Nightly 1.14.19 CR: 84.0.4147.105
```

* ensured that running through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/11092#issue-673464647 didn't reproduce the original issue regarding the modal appearing when a user loads an internal link with a fresh profile.
* ensured that the modal was appearing correctly when visiting a website for the first time when shields blocks ads

Also went through the following cases:

* ensured that the `You just blocked some trackers & ads` modal doesn't appear under `chrome://newtab` when onboarding is completed
  * also ensured that the `You just blocked some trackers & ads` modal isn't being displayed on `chrome://newtab` when skipping onboarding
* ensured that the modal isn't being displayed via `chrome://rewards` when a user goes straight to the Rewards page after installation
* ensured that the `You just blocked some trackers & ads` modal doesn't appear under `chrome://newtab`, `chrome://rewards` or `chrome://chrome-urls` under PB once it's been viewed in the regular mode
  * also ensured that the `You just blocked some trackers & ads` modal correctly appears in PB if it hasn't been viewed in the regular mode.

**Comment by kjozwiak** [comment] 2020-08-12 02:26
Closing as https://github.com/brave/brave-core/pull/6382 was merged. @srirambv will create a follow up issue to the problems he was noticing re: the tooltip not being displayed when a single ad/element is blocked rather than multiple ads/elements.

**Closed by kjozwiak** 2020-08-12 02:26 UTC
Labels: OS/Android, QA/Yes, bug, onboarding, release-notes/exclude

**Comment by srirambv** [comment] 2020-08-12 09:07
Verification passed on Samsung Tab A with Android 10 running 1.12.112 x64 build
- Verified Shields onboarding doesn't show up when internal pages are opened
- Verified Shields onboarding doesn't show up when a site with 0 items blocked
- Verified Shields onboarding show up when a site with ads/tracker blocked is visited
- Verified clicking on `Take a look` opens up the shields
- Verified clean install and visit a site that has ads/trackers blocked in Private tab shows shields onboarding.
--------
Verification passed on OnePLus 6T with Android 10 running 1.12.112 x64 build
- Verified Shields onboarding doesn't show up when internal pages are opened
- Verified Shields onboarding doesn't show up when a site with 0 items blocked
- Verified Shields onboarding show up when a site with ads/tracker blocked is visited
- Verified clicking on `Take a look` opens up the shields
- Verified clean install and visit a site that has ads/trackers blocked in Private tab shows shields onboarding.

**Comment by srirambv** [comment] 2020-08-12 12:48
cc: @anthonypkeane @bsclifton @deeppandya  on follow up issue
