### ISSUE TITLE
No app image in notification prompt

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#18219] opened 2021-09-20 16:30 UTC
## Description 

When receiving notification prompt after install of Brave, there's no image on the notification prompt.

## Steps to Reproduce

   1. Clean install https://github.com/brave/brave-browser/releases/tag/v1.30.81 for macOS ARM
   2. Wait until you see notification prompt
   3. Notice no image for notification prompt.

## Actual result:

<img width="373" alt="Screen Shot 2021-09-20 at 9 10 14 AM" src="https://user-images.githubusercontent.com/5951041/134038193-396b1811-db27-4a47-ab3f-158962ad7920.png">

## Expected result:
Notification with app image.

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.30.81

## Version/Channel Information:

- Can you reproduce this issue with the current release? No. But release candidate.
- Can you reproduce this issue with the beta channel? No.
- Can you reproduce this issue with the nightly channel? Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Related. Also seeing the following in notifications.
<img width="238" alt="Screen Shot 2021-09-20 at 9 26 37 AM" src="https://user-images.githubusercontent.com/5951041/134039171-2b0237ee-6299-4ce2-bff3-bd13daae9fb9.png">

**Comment by kjozwiak** [comment] 2021-09-20 17:00
Duplicate of https://github.com/brave/brave-browser/issues/18154. @tmancey & @stephendonner have been looking into it.

**Closed by kjozwiak** 2021-09-20 17:00 UTC
Labels: OS/Desktop
