### ISSUE TITLE
Allow opening PDFs in desktop app

### ISSUE THREAD

**Issue by margual56** [brave/brave-browser#13879] opened 2021-02-01 22:34 UTC
## Description 
The only two options currently supported are to either open PDFs with Brave or download them. Even Chrome has the option to open them directly on the default desktop app ([according to this article](https://www.addictivetips.com/web/force-chrome-to-open-pdfs-in-an-external-app/)).

## Steps to Reproduce
   1. Try to open a PDF on an external editor by just clicking the link (you can't)
   2. Cry because you are stuck reading the PDF on your 120-tabs window (or downloading it and then having to remember to delete it).

## Actual result:
In [brave://settings/content/pdfDocuments](brave://settings/content/pdfDocuments) there is only the option to use brave or download and open it manually.

## Expected result:
In [brave://settings/content/pdfDocuments](brave://settings/content/pdfDocuments) should be an option to automatically open the PDF on the default PDF viewer

## Reproduces how often: 
Always

## Desktop Brave version:
All of them (I believe)

## Miscellaneous Information:
PS: Love this browser! Keep up the good work!

**Comment by rebron** [comment] 2021-05-06 21:18
Closing as duplicate of #8590

**Closed by rebron** 2021-05-06 21:18 UTC
Labels: OS/Desktop, closed/duplicate
