### ISSUE TITLE
Allow video play when using container APIs

### ISSUE THREAD

**Issue by Sondro** [brave/brave-browser#4673] opened 2019-05-31 21:41 UTC
## Description 

Not sure if this is a duplicate of #2792, but both Chrome and Safari mobile allow you to use APIs to build your own video container interface to play videos.

Right now the autoplay block catches the playing event.

## Steps to Reproduce

API examples provided here: https://ginpei.github.io/html5-youtube.js/

**Comment by rebron** [comment] 2019-06-21 15:31
Yes. Closing. Dupe of #2792 Thanks for additional examples.

**Closed by rebron** 2019-06-21 15:31 UTC
Labels: feature/autoplay
