### ISSUE TITLE
Problem Translate Web

### ISSUE THREAD

**Issue by SWxEng** [brave/brave-browser#25990] opened 2022-10-13 17:23 UTC
Hi
.
Problem Translate Web in Brave 

![image](https://user-images.githubusercontent.com/55116927/195664169-7f1fda66-c157-40f4-9ced-0994479e336a.png)

![image](https://user-images.githubusercontent.com/55116927/195664211-a67ecfe1-c3b1-4de1-969c-57ed140c96cc.png)

Brave version / 1.44.112 Chromium: 106.0.5249.119 (Official Build) (64-bit) 2022-10-12 
.
OS / Windows 10 Version 21H2

**Comment by rebron** [comment] 2022-10-14 16:14
Closing as dupe of https://github.com/brave/brave-browser/issues/24303. Will be resolved when we close that issue.
cc: @atuchin-m

**Closed by rebron** 2022-10-14 16:14 UTC
Labels: OS/Desktop

**Comment by SWxEng** [comment] 2022-10-14 16:18
OK , Thank You
