### ISSUE TITLE
allow deletion of embedded cookie setting

### ISSUE THREAD

**Issue by cjwijtmans** [brave/brave-browser#11515] opened 2020-08-30 16:02 UTC
## Description 

allow deletion of embedded cookie setting

## Steps to Reproduce

   1. go to brave://settings/content/cookies
   2. see "embedded" cookies with trash icon
   3. click trash icon

## Actual result:

nothing happens, cookie setting is still there

## Expected result:

cookie setting is deleted

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Windows 10 OS Version 2004 (Build 19041.450)

## Version/Channel Information:

- Can you reproduce this issue with the current release? **Yes**
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **N/A**
- Does the issue resolve itself when disabling Brave Rewards? **N/A**
- Is the issue reproducible on the latest version of Chrome?

**Comment by dentistformyeye** [comment] 2020-08-31 03:27
Duplicate of #11259

**Comment by bsclifton** [comment] 2020-08-31 05:52
Closing as duplicate of https://github.com/brave/brave-browser/issues/11259

**Closed by bsclifton** 2020-08-31 05:52 UTC
