### ISSUE TITLE
Implement client model parameters component

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#8396] opened 2020-02-25 07:41 UTC
For requirements search "Purchase Intent MiniSpec" on shared drive, section "Parameter Updates".

Related PRs:

- CI: https://github.com/brave/devops/pull/2807
- crx packager: https://github.com/brave/brave-core-crx-packager/pull/105

**Comment by tmancey** [comment] 2020-05-03 06:05
Closing issue as a duplicate of https://github.com/brave/brave-browser/issues/9147

**Closed by tmancey** 2020-05-03 06:05 UTC
Labels: duplicate, enhancement, feature/ads
