### ISSUE TITLE
Microsoft broke the option to overwrite the Edge protocol

### ISSUE THREAD

**Issue by SteaceP** [brave/brave-browser#19867] opened 2021-12-02 02:43 UTC
## Description 
The option to make Brave as the default Edge protocol handler is broken.

## Steps to Reproduce

   1. Go to brave://settings/system
   2.  Expand "Additional Settings" click on the "System" option.
   3.  Activate "make default" in the "Default Microsoft-Edge protocol handler" option.
   4.  Search something in Windows Search <-- Edge open and the "make default" button reappears in Brave settings

## Actual result:
Broken

## Expected result:
Working

## Reproduces how often: 
Every time since the last Windows/Edge Update

## Brave version (brave://version info)
Brave | 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 11 Version 21H2 (Build 22000.348)

## Version/Channel Information:

I tried with the beta for the purpose of this issue and it's not working either.

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the nightly channel? Don't know

**Comment by Nihal247** [comment] 2021-12-02 03:04
Yeah, it's not a good gesture from Microsoft to other third party apps.

Dupe of #19786

**Comment by rebron** [comment] 2021-12-08 20:29
Closing as dupe of #19786 Thanks for the report @SteaceP

**Closed by rebron** 2021-12-08 20:29 UTC
Labels: closed/duplicate, OS/Desktop
