### ISSUE TITLE
Suggest using Lingvanex's translation API 

### ISSUE THREAD

**Issue by tachibana-shin** [brave/brave-browser#23000] opened 2022-05-23 10:47 UTC
Hi,

Brave doesn't have a website translator which is the only reason I can't switch from Chrome -> Brave (Google Translate Extension didn't work for me)

I don't know why translate.brave.com isn't ready yet but i suggest in its development Brave will use Lingvanex to do translation API like Vivaldi did

Thank for read

**Comment by CavaleriOmar** [comment] 2022-05-26 06:48
Or like FIrefox-Translator (totally offline)?

**Comment by diracdeltas** [comment] 2022-05-26 22:56
this is already being worked on: https://github.com/brave/go-translate/pull/12

**Comment by rebron** [comment] 2022-07-07 16:08
Closing as duplicate of https://github.com/brave/go-translate/pull/12 and https://github.com/brave/brave-browser/issues/23538

**Closed by rebron** 2022-07-07 16:08 UTC
Labels: priority/P3, OS/Desktop, brave-translate
