### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by faandg** [brave/brave-browser#40152] opened 2024-07-31 10:42 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.68.128 Chromium: 127.0.6533.73
Operating System: Linux 6.9.10-1-MANJARO

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. use vertical tabs
2. add tab to group
3. right-click tab that was added to a group and choose _pin_
4. crash
(TBH idk what I was expecting to happen here, it just happened)

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/a6bd0800-3daa-5d0c-0000-000000000000

**Comment by bsclifton** [comment] 2024-08-22 17:13
Thanks for the report! This is a duplicate of https://github.com/brave/brave-browser/issues/40365 - will close this out 😄

**Closed by bsclifton** 2024-08-22 17:13 UTC
Labels: crash, OS/Linux, priority/P2, feature/vertical-tabs
