### ISSUE TITLE
[Android] Request to also publish in F-Droid

### ISSUE THREAD

**Issue by stevenleeS0ht** [brave/brave-browser#9682] opened 2020-05-08 04:25 UTC
Currently, Brave for Android only publish on F-Droid. But for the device not support GMS, it would be inconvenient to obtain such nice web browser. It would be a good idea to publish this App on F-Droid.

**Comment by srirambv** [comment] 2020-05-08 04:42
Closing as dupe of #7027

**Closed by srirambv** 2020-05-08 04:42 UTC
Labels: OS/Android
