### ISSUE TITLE
Add 'outline: none;' rule to turn off fuzzy gray border on button click/focus in the site banner

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#1832] opened 2018-10-25 05:02 UTC
## Description 

Button elements on the site banner will display this fuzzy gray border on button click by default. Which looks very unfortunate. **Define 'outline:none;' in button focus state** so we can avoid displaying this artifact. 

![screen shot 2018-10-24 at 9 33 09 pm](https://user-images.githubusercontent.com/4369856/47477090-5f810980-d7d8-11e8-886e-5b57cc73af58.png)
![screen shot 2018-10-24 at 9 49 35 pm](https://user-images.githubusercontent.com/4369856/47477092-5f810980-d7d8-11e8-9f5f-fd55aa21b03d.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment] 2018-10-25 07:02
@jenn-rhim duplicate of https://github.com/brave/brave-browser/issues/1438?

**Comment by kjozwiak** [comment] 2018-10-25 17:17
Thanks @jenn-rhim, going to close and mark this as a duplicate. Notice that you've responded under #1438 👍

**Closed by kjozwiak** 2018-10-25 17:17 UTC
Labels: feature/rewards
