### ISSUE TITLE
Enable extensions in Tor profile

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#6303] opened 2019-10-03 16:37 UTC
We currently don't support extensions in Tor profile, this issue is to track to enable them. To be extra careful to not have any leakage, it could be whitelist only at first.

**Comment by bsclifton** [comment] 2020-03-04 06:06
@yrliou is this issue a duplicate of https://github.com/brave/brave-browser/issues/2761?

**Comment by yrliou** [comment] 2020-03-04 06:21
@bsclifton Yes, feel free to close as duplicate, BTW I think that issue should remove private window from the title since it is actually supported but just behind a switch.

**Closed** 2020-03-04 06:27 UTC
Labels: feature/tor
