### ISSUE TITLE
"Try Again" message displayed after connecting KYC'd Uphold account in certain cases

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#11826] opened 2020-09-23 18:08 UTC
## Description 

If you have claimed an Ad grant and you then connect a KYC'd Uphold account, you will get the "Try Again" message on brave://rewards page.

Note, this does not occur if you do not have any Ad grant BAT to transfer to Uphold. i.e. you have a clean profile and connect a KYC'd uphold account without having any BAT to transfer to Uphold.

## Steps to Reproduce

   1. Clean profile, enable Rewards
   2. Restore a wallet with an Ad grant
   3. Claim ad grant
   4. Click on Verify Wallet
   5. Login with KYC'd Uphold account

## Actual result:

When you are directed back to brave://rewards page you get the "Try again" message. Note, this message only shows for about 10s, before timing out, so you need to watch for it.  If you click "Try again" you are connected and your BAT gets transferred.

<img width="969" alt="Screen Shot 2020-09-23 at 1 49 17 PM" src="https://user-images.githubusercontent.com/28145373/94051855-2bd50280-fda6-11ea-963c-ff433d0afd65.png">

## Expected result:
No "Try Again" message, your account should be connected as expected.

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.14.84, 1.15.x

Brave | 1.15.60 Chromium: 86.0.4240.42 (Official Build) dev (x86_64)
-- | --
Revision | 418ccfc2b69112bd79d5ffb38b533642e64e6af8-refs/branch-heads/4240@{#773}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes, 1.14.x
- Can you reproduce this issue with the beta channel? yes 1.15.x
- Can you reproduce this issue with the nightly channel? no 1.16.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

reproduced by @kjozwiak 
cc @NejcZdovc

**Comment by NejcZdovc** [comment] 2020-09-23 18:27
@LaurenWags what do you see in logs?

**Comment by LaurenWags** [comment] 2020-09-23 18:32
there didn't seem to be anything. I cleared logs right before connecting to Uphold but no errors were shown.

**Comment by NejcZdovc** [comment] 2020-09-24 06:22
@LaurenWags please check redirect url as well, maybe there is something in there telling us what the problem is

**Comment by kjozwiak** [comment] 2020-09-24 06:22
> there didn't seem to be anything. I cleared logs right before connecting to Uphold but no errors were shown.

Same boat. I reproduced this several times and checked the following areas:

* Output via terminal/CLI (same approach @LaurenWags mentioned above)
* Checked browser console (didn't see anything)
* Checked via `brave://inspect/#extensions`

Couldn't really see anything useful/helpful. But it's really easy to reproduce.

**Comment by LaurenWags** [comment] 2020-09-24 12:28
@NejcZdovc not sure what you mean, is the redirect URL different if there isn't any BAT to transfer to Uphold? This only occurs when there's BAT to transfer from browser to Uphold. If you have a clean profile and just connect your KYC'd wallet this doesn't occur.

**Comment by NejcZdovc** [comment] 2020-11-03 08:48
@kjozwiak @LaurenWags can you try on the latest Nightly. I can't reproduce it. Thank you

**Comment by LaurenWags** [comment] 2020-11-03 20:54
Unable to reproduce using below build and STR from description on staging env:

```
Brave | 1.18.30 Chromium: 87.0.4280.40 (Official Build) nightly (x86_64)
-- | --
Revision | 349b9adbfb2784db684617c7731a57d1e61b3be0-refs/branch-heads/4280@{#863}
OS | macOS Version 10.14.6 (Build 18G6032)
```

**Comment by kjozwiak** [comment] 2020-11-03 21:29
I wasn't able to reproduce the issue either @NejcZdovc. Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/11826#issue-707573018 five different times and didn't run into the original problem. Used the following build:

```
Brave | 1.18.30 Chromium: 87.0.4280.40 (Official Build) nightly (x86_64)
-- | --
Revision | 349b9adbfb2784db684617c7731a57d1e61b3be0-refs/branch-heads/4280@{#863}
OS | macOS Version 10.15.7 (Build 19H2)
```

Going to close this off 👍

**Closed by kjozwiak** 2020-11-03 21:29 UTC
Labels: OS/Desktop, QA/Yes, feature/rewards
