### ISSUE TITLE
In latest Android Beta versions - Brave Rewards icon can't be hidden 

### ISSUE THREAD

**Issue by gbil** [brave/brave-browser#20821] opened 2022-02-01 11:09 UTC
## Description 
In the latest Android Beta versions (at least the 2 last ones) the Brave Rewards icon can't be hidden through the Appearance settings, toggling that setting does nothing in practice 

## Steps to Reproduce

   1. Go in Settings -> Appearance menu
   2. Set "Show Brave Rewards icon in address bar" to off 
   3. Click on Relaunch Now popup 

## Actual result:
- The Brave Rewards icon remains in the address bar
- The toggle in the settings is back to enabled

## Expected result:
- The Brave Rewards icon to be removed from the address bar
- The toggle in the settings to remain disabled 

## Reproduces how often: 
Every time

## Brave version (info found on brave://version)
Brave: 1.36.80 Chromium: 98.0.4758.74 (Official Build) beta (64-bit)
Revision: d0fe1ec4df090cd3eb02b591228505e12ea476e9-refs/branch-heads/4758@{#935}
OS: Android 12; Build/SP1A.2108212.016

## Version/Channel Information:
Specific channel, used to work fine in previous beta versions 

- Can you reproduce this issue with the current release? NO
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the dev channel? haven't tested
- Can you reproduce this issue with the nightly channel? haven't tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:
Tested in at least 2 Android devices, different OS level, both had Brave Beta before and it happened after some Beta update

**Comment by Miyayes** [comment] 2022-02-08 07:41
This is a dupe of https://github.com/brave/brave-browser/issues/20633. Thanks.

**Closed by Miyayes** 2022-02-08 07:41 UTC
Labels: feature/rewards, OS/Android
