### ISSUE TITLE
No Brave ads displaying in macOS Catalina 10.15.4

### ISSUE THREAD

**Issue by eduayme** [brave/brave-browser#9595] opened 2020-05-03 06:59 UTC
## Description 
I have not seen any notification ad after 7 days using Brave browser and setting 5 ads per hour when I installed it.

## Brave version (brave://version info)
V1.8.86

**Comment by bsclifton** [comment] 2020-05-04 06:01
cc: @tmancey - this might be the case we ran into

**Comment by tmancey** [comment] 2020-05-05 11:56
@eduayme Could you please let me know:

- Your locale preferences which can be found in macOS under "Preferences > Language & Region" 
- Can you please let me know the make/model of your mouse (a strange question I know...)

**Comment by eduayme** [comment] 2020-05-05 12:20
@tmancey 

- Locale preferences: 

1. Preferred languages (in order): English - Primary, Spanish (Spain), Catalan, French
2. Region: Spain
3. First day of the week: Monday
4. Calendar: Gregorian
5. Time format: 24-Hour Time (selected)
6. Temperature: ºC (Celsius)
7. List sort order: Universal

- Model of my mouse:
1. Touchpad from Apple MacBook Pro Intel Core i7 2.6GHz/16GB/256GB SSD/Radeon Pro 555X/15.4"

**Comment by tmancey** [comment] 2020-05-05 12:22
@eduayme Thank you. Would you be willing to screen-share so I can help diagnose the issue? If so, you can contact me at tmancey@brave.com so we can arrange. Thanks

**Comment by eduayme** [comment] 2020-05-05 12:39
@tmancey Sure, no problem.

**Comment by tmancey** [comment] 2020-05-29 08:35
Duplicate of https://github.com/brave/brave-browser/issues/9874

**Closed by tmancey** 2020-05-29 08:35 UTC
Labels: duplicate, feature/ads, needs-investigation
