### ISSUE TITLE
Crash report was sent when  `Automatically send diagnostic reports` is disabled in `brave://settings/privacy`

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#27493] opened 2022-12-21 17:38 UTC
## Steps to Reproduce

1. new profile 
2. launch Brave
3. click Skip on `brave://welcome` page 
4. click Skip on  `Import Settings` page 
5. leave default option `Send diagnostic reports if you experience a crash or freeze` 
6. open `brave://settings/privacy`
7. disable `Automatically send diagnostic reports` and relaunch Brave
8. visit `brave://crash` to generate a crash incident
9. open `brave://crashes`

## Actual result:

`Crash reporting is disabled` text is shown but the report was sent.

step 5|step 7|step 8|step 9
---|----|----|----
<img width="477" alt="image" src="https://user-images.githubusercontent.com/98358127/208967036-72c738ef-e485-4b7d-bf57-43e79c50332d.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/208966986-c6ef65f1-cfbb-4160-acf3-2952d68d3a43.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/208967368-4ca06a41-728b-42e4-980b-f3f1a9b067c2.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/208967607-5360b319-3ed3-4af8-9e6f-59b97cd60e93.png">

## Expected result:
<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/208968121-03876b14-0e95-40b0-bf63-b92cc7644a5f.png">

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.47.136 Chromium: 108.0.5359.128 (Official Build) beta (64-bit)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @nullhook 
cc: @stephendonner @btlechowski

**Comment by GeetaSarvadnya** [comment] 2022-12-30 11:08
Reproduced the issue on windows 10 x64  - 1.47.149 Chromium: 109.0.5414.46 (Official Build) beta (64-bit)

**Comment by bsclifton** [comment] 2023-01-04 18:00
I can't reproduce with `1.47.161` (Windows 10 x64) - using Beta 🤔

**Comment by bsclifton** [comment] 2023-01-05 00:56
Just got off call with @MadhaviSeelam - I understand what is being reported now 😄 

- crash reporting enabled in brave://welcome
- crash reporting disabled in brave://settings/privacy
- brave://crash visited
- visit brave://crashes

The crash reports are not being sent, **which is correct**! However, it seems that in other instances (ex: if you DON'T enable crash reporting in brave://welcome) the crash is never recorded (ex: `crashpad` folder is empty; nothing shows on brave://crashes).

I suspect there is a process running for crashpad and once it's started, the crashes are recorded to the profile directory. @iefremov @atuchin-m is this accurate? I think it's safe to close this issue - as behavior seems OK to me.  But wanted to ask for clarification on conditions where crashes are recorded sometimes and sometimes they're not

**Comment by bsclifton** [comment] 2023-01-05 17:50
Closing out as no reports are sent 👍 Would be good to understand about the crashpad service - but we can follow up about that offline

**Closed by bsclifton** 2023-01-05 17:50 UTC
Labels: bug, release/blocking, priority/P2, QA/Yes, QA/Test-Plan-Specified, needs-more-info, feature/settings, onboarding, OS/Desktop
