### ISSUE TITLE
Brave Rewards popup has white sections at the top and bottom

### ISSUE THREAD

**Issue by echosa** [brave/brave-browser#1554] opened 2018-10-12 15:41 UTC
## Description 
The Brave Rewards popup has white sections at the top and bottom. See screenshot below.

## Steps to Reproduce
   1. Open the Brave Rewards popup

## Actual result:
There's white bars at the top and bottom.

<img width="375" alt="screen shot 2018-10-12 at 10 40 28 am" src="https://user-images.githubusercontent.com/133786/46879301-44db8780-ce0b-11e8-9b48-3e8576d0d954.png">

## Expected result:
There shouldn't be bars.

## Reproduces how often: 
100%

## Brave version (chrome://version info)
Brave | 0.56.2 Chromium: 70.0.3538.35 (Official Build) dev (64-bit)
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  Yes
- Does it reproduce on browser-laptop? No

**Comment by srirambv** [comment] 2018-10-12 16:10
Dupe of #1028 since Brave Rewards is also an extension

**Closed by srirambv** 2018-10-12 16:10 UTC
