### ISSUE TITLE
Ads not being blocked on 9to5google.com and 9to5mac.com

### ISSUE THREAD

**Issue by thanuj10** [brave/brave-browser#7400] opened 2019-12-16 06:51 UTC
## Description 
Ads are not being blocked on `https://www.9to5google.com` and `https://www.9to5mac.com`

## Steps to Reproduce
   1. Visit 9to5mac.com/9to5google.com 
   2. Wait for page to load fully
   3. Ads are also loaded and visible. 

## Actual result:
Ads are also loaded along with the  webpage on its homepage and its subsequent articles.

## Expected result:
Ads are blocked on both homepage and article pages.

## Reproduces how often: 
Very Easily reproduced.

## Brave version (brave://version info)
 - Brave | 1.4.25 Chromium: 79.0.3945.79 (Official Build) nightly (64-bit)
 - Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
 - OS | Windows 10 OS Version 1903 (Build 18362.418)

## Version/Channel Information:
- Can you reproduce this issue with the current release? Not tested
- Can you reproduce this issue with the beta channel? Not Tested
- Can you reproduce this issue with the dev channel? Not Tested
- Can you reproduce this issue with the nightly channel? Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:
N/A

**Comment by srirambv** [comment] 2019-12-16 12:48
cc: @ryanbr  issue happens on release version too

**Comment by ryanbr** [comment] 2019-12-16 20:51
These ads aren't easy to remove, but will be fixed in our cosmetic/ubo stuff. See this related thread; 
https://www.wilderssecurity.com/threads/ublock-a-lean-and-fast-blocker.365273/page-166#post-2878614

**Comment by kjozwiak** [comment] 2020-01-07 06:54
+1 from myself. Seeing this on all the current channels including `1.5.13 CR: 79.0.3945.88`

**Comment by Wolfenstein98k** [comment] 2020-01-24 00:10
Using latest mobile Brave (1.7.0), confirmed as still a bug.

**Comment by ryanbr** [comment] 2020-01-24 00:13
Have been testing this, seems to be a limitation in Chrome. Having the same issue with uBo+Chrome.. Firefox+uBo seems to be okay

**Comment by Wolfenstein98k** [comment] 2020-01-24 04:00
Thanks ^

In the context of mobile - I've tested this with Firefox, with uBlock Origin installed as mobile add-on, and the ads are blocked. There also appears to be no WW redirect.

But with Brave, same mobile and connection, the WW redirect is forced every time and the ads show every time. Definitely a Brave issue.

**Comment by ryanbr** [comment] 2020-01-24 10:22
Possibly more movement, a new filter suggested:

`9to5google.com,9to5mac.com,9to5toys.com,dronedj.com,electrek.co,marketrealist.com##+js(set, String.prototype.charCodeAt, trueFunc)`

https://www.reddit.com/r/uBlockOrigin/comments/el4ng5/ads_on_9to5googlecom/ffek56d/

I'll see how this works for us, if it doesn't I'll logged a issue report.

**Comment by ryanbr** [comment] 2020-01-24 10:29
We need to support `##+js(set,...)` to fix this site.

**Comment by rebron** [comment] 2020-02-14 17:30
cc: @ryanbr Looks like this issue is fixed in release/beta/etc. Not sure if you addressed this one already.

**Comment by ryanbr** [comment] 2020-07-05 01:01
Everything should working now @thanuj10 Just re-checked. site is clean of ads.

**Closed by ryanbr** 2020-07-05 01:01 UTC
Labels: closed/fixed-by-component-update, closed/works-for-me, feature/shields/adblock, priority/P3
