### ISSUE TITLE
Google Meet: Unable to Join Meeting

### ISSUE THREAD

**Issue by 2bithacker** [brave/brave-browser#2495] opened 2018-12-12 18:47 UTC
## Description 

Unable to join meetings on Google Meet (aka Hangouts)

## Steps to Reproduce

   1. Go to meet.google.com (login required)
   2. Click on "Start a new meeting"
   3. Click on "Start meeting"

## Actual result:

Browser displays an "Aw, Snap! Something went wrong while displaying this webpage." error.

## Expected result:

Browser should display the meeting.

## Reproduces how often: 

Easily reproduced. Just started happening to me today, was able to join a meeting on Monday without a problem.

## Brave version (brave://version info)

Brave: 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
Revision: 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS: Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? I don't know, haven't tested.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No, I currently have shields disabled for meet.google.com and the problem continues to occur.
- Is the issue reproducible on the latest version of Chrome? No, it works fine with Chrome 71.0.3578.80

**Comment by 2bithacker** [comment] 2018-12-13 17:14
And today it appears to be working again.

**Comment by vrcca** [comment] 2019-01-14 11:09
@2bithacker I am able to join the meeting, but the same problem occurs when trying to share screen. Maybe we could rewrite the issue to address this issue?

**Comment by JohnTheodore** [comment] 2019-05-12 00:02
I'm having a similar issue I think? It's hangouts related I believe. I usually make and receive calls from my gmail tab. I just switched to brave a couple days ago. Someone called, and I could see the phone modal pop up, but I couldn't click answer. This seems similar to this issue: https://github.com/brave/browser-laptop/issues/12113

Not sure if I'm crashing this issue, or if I should go make another issue. Let me know if the latter.

**Comment by BrendanEich** [comment] 2019-10-23 17:57
Does lowering shields help? @bsclifton @jonathansampson @rebron can we triage these and dedup? Thanks.

**Comment by bsclifton** [comment] 2019-10-31 22:23
Related: no audio in Google Meet (work-around is to allow autoplay):
https://github.com/brave/brave-browser/issues/4621

**Comment by rebron** [comment] 2020-03-24 04:51
Duplicate of #4621 and fixed in 1.4.96, a few versions ago. Sharing a screen shouldn't be an issue now either.

**Closed by rebron** 2020-03-24 04:51 UTC
Labels: google, needs-investigation, priority/P2, webcompat
