### ISSUE TITLE
Dailymotion website does not load w/Shields up - must close tab and revisit to display

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#4240] opened 2019-04-25 21:25 UTC
## Description 

When navigating to https://dailymotion.com/ the site does not load under default Shields or no Shields. A few of the header elements display but the site then continues to load infinitely:
![dailymo](https://user-images.githubusercontent.com/3299098/56769224-65df4680-6765-11e9-87b6-12e6021d94c2.gif)

When Shields are lowered, unless you navigate away from the site (close the tab), the page will timeout. Only after timeout and/or closing the tab and revisiting the site will it display as intended:
![dailymo2](https://user-images.githubusercontent.com/3299098/56769261-8ad3b980-6765-11e9-9990-bfdf724aaec9.gif)

## Steps to Reproduce

   1. Visit DailyMotion.com with default Shields settings
   2. Turn Shields down when site doesn't load
   3. On page timeout, refresh the page and/or close the tab (this can be done before timeout) and try to visit the site again

## Actual result:

The site only loads after the page is refreshed after timeout with Shields down.

## Expected result:
The page should load as expected with Shields up or down.

## Reproduces how often: 

Always

## Brave version (brave://version info)

v0.63.48

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Kind of?
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No.

## Miscellaneous Information:

User report: https://www.reddit.com/r/brave_browser/comments/bhd8s8/cant_play_videos_from_dailymotion_page_wont_even/

**Comment by srirambv** [comment] 2019-04-26 15:04
Dupe of #1580

**Closed by srirambv** 2019-04-26 15:04 UTC
Labels: feature/shields/webcompat
