### ISSUE TITLE
Brave using 100% disk  and not closing process

### ISSUE THREAD

**Issue by aquaspy** [brave/brave-browser#8829] opened 2020-03-24 12:20 UTC
## Description 
Brave uses 100% disk and the process remains opened when you close it (and 100% disk still being used until you kill brave process)

## Steps to Reproduce

   1.  Download and install brave latest version
   2. Use it for a while (about a day for me)
   3. Wait until the computer slow completely, look at the task manager and see brave using 100% disk even when the process is closed

## Reproduces how often: 
I don't know.

## Brave version (brave://version info)
1.5.115

## Version/Channel Information:
Current
## Other Additional Information:

I don't know if it is reproducible on latest chrome.

**Comment by bsclifton** [comment] 2020-03-24 22:13
@aquaspy can you please use the Task manager in Brave to help us narrow this down? You can find via the Hamburger menu (3 lines, top right) => More Tools => Task Manager

I suspect that the `Bat Ledger Service` is taking up all the CPU, which we have recently found a cause for (captured with https://github.com/brave/brave-browser/issues/8846). If you can confirm that would be great 😄

**Comment by bsclifton** [comment] 2020-03-26 16:37
pretty sure this is related to the `Bat Ledger Service`- going to close this as a duplicate of https://github.com/brave/brave-browser/issues/8846

**Closed by bsclifton** 2020-03-26 16:37 UTC
Labels: duplicate, needs-more-info

**Comment by aquaspy** [comment] 2020-03-26 22:38
@bsclifton  yes, it was Bat ledger service. Thanks for fast reply. Keep the good work!
