### ISSUE TITLE
Limit URL requests to whitelisted schemes in windows with Tor

### ISSUE THREAD

**Issue by riastradh-brave** [brave/brave-browser#5357] opened 2019-07-23 21:43 UTC
In https://github.com/brave/brave-core/pull/2647, to fix https://github.com/brave/brave-browser/issues/4312, we lost some logic to block URL requests outside a small whitelist that are safe through Tor or don't need Tor:

> ```
>   if (request_url.SchemeIsHTTPOrHTTPS()) {
>     auto* proxy_service = ctx->request->context()->proxy_resolution_service();
>     return tor_profile_service->SetProxy(proxy_service, request_url, false);
>   } else if (request_url.SchemeIs(content::kChromeUIScheme) ||
>              request_url.SchemeIs(extensions::kExtensionScheme) ||
>              request_url.SchemeIs(content::kChromeDevToolsScheme)) {
>     // No proxy for internal schemes.
>     return net::OK;
>   } else {
>     return net::ERR_DISALLOWED_URL_SCHEME;
>   }
> ```
> https://github.com/brave/brave-core/pull/2647/commits/d7db72e9d64a3b6451b98cf0bee76979cd8fecfb#diff-de4449937f0f4de57a0104b7b425bafbL47-L57

We should find a place to restore that so that we do not inadvertently allow URL requests with schemes that are unsafe through Tor.  (It is conceivable that all URL schemes are safe, but this seems unlikely and requires a much more substantial audit than we have conducted in order to inspire confidence.)

**Comment by diracdeltas** [comment] 2019-07-23 22:18
is this just a dupe of https://github.com/brave/brave-browser/issues/4461 ?

**Comment by riastradh-brave** [comment] 2019-07-24 22:46
For posterity: it is not quite a duplicate because #4461 is about external protocol handlers, while this is about internally handled protocols.  But Anthony's change should fix both in one swell foop.

**Closed** 2019-08-07 19:44 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/tor, feature/tor/leakproofing, regression
