### ISSUE TITLE
Ethereum`blocktimer.dappstar.eth` FQDN fails to resolve

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15094] opened 2021-04-02 17:46 UTC
## Description 

Ethereum`blocktimer.dappstar.eth` FQDN fails to resolve

## Steps to Reproduce

   1. new profile
   2. load `http://blocktimer.dappstar.eth/`
   3. on the interstitial page, click on the blue `Proceed using Cloudflare server` button

## Actual result:

DNS-lookup error: `This site can't be reached`

<img width="844" alt="Screen Shot 2021-04-02 at 10 39 53 AM" src="https://user-images.githubusercontent.com/387249/113439659-d9515000-939f-11eb-9d33-99a8a77c5cf5.png">

## Expected result:

This works using `nightly` build 

Brave | 1.24.43 Chromium: 90.0.4430.41 (Official Build) nightly (x86_64)
-- | --
Revision | e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}
OS | macOS Version 11.2.3 (Build 20D91)

<img width="966" alt="Screen Shot 2021-04-02 at 10 41 01 AM" src="https://user-images.githubusercontent.com/387249/113440013-790ede00-93a0-11eb-8580-5eed9a322ccb.png">

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 1.23.58 Chromium: 89.0.4389.114 (Official Build) beta (x86_64)
-- | --
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | macOS Version 11.2.3 (Build 20D91)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

/cc @yrliou @rebron

**Comment by bbondy** [comment] 2021-04-06 18:58
Working for me on release, is it maybe relating to a bad cached DNS entry?
Try reloading?

**Comment by yrliou** [comment] 2021-04-06 20:01
@stephendonner I just tried on release & beta with fresh profile, both work for me.
Are there any additional steps, or you did some steps in the default profile before opening a new one?

**Comment by stephendonner** [comment] 2021-04-06 21:14
@yrliou sadly, still doesn't work for me in a new profile on `beta` (but works on `nightly`).  I haven't modified any DNS settings, either :-(

Beta:

Brave | 1.23.64 Chromium: 89.0.4389.114 (Official Build) beta (x86_64)
-- | --
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | macOS Version 11.2.3 (Build 20D91)



Nightly: 

Brave | 1.24.50 Chromium: 90.0.4430.51 (Official Build) nightly (x86_64)
-- | --
Revision | 32e5fa33a31641bded70a90e60121060691e7125-refs/branch-heads/4430@{#927}
OS | macOS Version 11.2.3 (Build 20D91)



Are there any additional steps to try to troubleshoot/debug I can do?  Thanks in advance!


![eth-dns](https://user-images.githubusercontent.com/387249/113779105-0e340e80-96e2-11eb-9404-59f713b68ada.gif)

**Comment by kjozwiak** [comment] 2021-04-09 02:50
So it looks like it's working on all three channels for me as well. However, with `1.23.68 Chromium: 90.0.4430.51`, I did see the error that @stephendonner mentions above but the website reloaded by itself within ~2 seconds without be refreshing it/clicking on reload. I tried it ~5 times on new profiles after that and couldn't reproduce what I saw on the first load. But in general, seems like it's working on my `Win 10 x64` machine.

**`1.25.4 Chromium: 90.0.4430.51`** | **`1.24.56 Chromium: 90.0.4430.51`** | **`1.23.68 Chromium: 90.0.4430.51`**
----------------------------------------|-----------------------------------------|--------------------------------------------
![image](https://user-images.githubusercontent.com/2602313/114120890-66723880-98bb-11eb-98e9-aeeb766238b8.png) | 
![image](https://user-images.githubusercontent.com/2602313/114121033-a507f300-98bb-11eb-850f-4a7dc0092afe.png) | ![image](https://user-images.githubusercontent.com/2602313/114121548-8a824980-98bc-11eb-816e-cd4791f4ffde.png)

**Comment by srirambv** [comment] 2021-04-09 03:52
Works fine for me as well. Tried with and without setting custom DNS provider in `brave://settings/security`

**Comment by GeetaSarvadnya** [comment] 2021-04-09 04:35
It's working for me on all the channels. I have made any changes to DNS settings in `brave://settings/security`

**`1.23.68`**                                       | **`1.24.56`**                                       | **`1.25.6`**
----------------------------------------|-----------------------------------------|--------------------------------------------
![image](https://user-images.githubusercontent.com/38657976/114128888-08753d80-991b-11eb-9754-34f60481d24b.png) | ![image](https://user-images.githubusercontent.com/38657976/114128903-10cd7880-991b-11eb-8cd2-a927db1bc4e5.png) | ![image](https://user-images.githubusercontent.com/38657976/114128923-1cb93a80-991b-11eb-9db5-6ee3db8cd4b9.png)

**Comment by srirambv** [comment] 2021-04-09 08:55
Ok I was able to repro the issue on Release channel build 1.23.68 while testing #14690. Error Page showed and even after reloading the page couple of times it didn't load the page. 
<img width="1440" alt="Screenshot 2021-04-09 at 09 52 33" src="https://user-images.githubusercontent.com/17010094/114155631-9b14dd00-9919-11eb-8a9c-963ad9904670.png">

**Comment by srirambv** [comment] 2021-04-16 16:09
Seems like there are a few failed requests for the page after enabling Cloudflare resolver
<img width="1312" alt="Screenshot 2021-04-16 at 17 03 37" src="https://user-images.githubusercontent.com/17010094/115052413-d4c78400-9ed5-11eb-99d3-239625e06f93.png">

**Comment by stephendonner** [comment] 2021-07-01 05:31
This is now working for me, using 


Brave | 1.28.37 Chromium: 91.0.4472.124 (Official Build) nightly (x86_64)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}

<img width="1792" alt="Screen Shot 2021-06-30 at 10 28 49 PM" src="https://user-images.githubusercontent.com/387249/124070395-a21c2a80-d9f2-11eb-8695-504ebb540aa6.png">


@srirambv how about you?

**Comment by srirambv** [comment] 2021-07-01 07:33
Yes this seems to be fixed now for me as well. There is no dealy/errors when loading via cloudflare dns. @stephendonner we should be good to close this one out now

**Closed** 2021-08-06 07:42 UTC
Labels: bug, priority/P4, feature/wallet, OS/Desktop, closed/works-for-me
