### ISSUE TITLE
Search History appearing on the Address Bar

### ISSUE THREAD

**Issue by krish-98** [brave/brave-browser#26894] opened 2022-11-21 13:41 UTC
I don't know why my previous search histories are appearing on the address bar

It shouldn't appear there in the first place

**Comment by bE7rwls** [comment] 2022-12-09 15:05
Same problem when using google search engine. And it doesnt matter if suggestions and autocomplete are disabled or not

**Comment by CQ-0** [comment] 2022-12-22 11:20
Yeah, #12292 was closed as a dupe of #22948, which supposedly fixed the issue, but it is still present. I just moved over from Edge which is also Chromium based and noticed this immediately, and it's holding me back from migrating completely.

**Comment by praxeolf** [comment] 2022-12-29 11:31
Same problem even after configuring all settings relating to search. This [extension](https://github.com/slymax/cloak) fixes it for now.

**Comment by bsclifton** [comment] 2022-12-30 06:42
@krish-98 can you confirm it doesn't show when you go under brave://settings/appearance and uncheck `Browsing History` under `Show autocomplete suggestions in address bar` (or just disable the whole top level `Show autocomplete suggestions in address bar`)

@CQ-0 which version of Brave did you try this on? I'll mark this as a regression as it did work. The default setting is having it checked

**Comment by krish-98** [comment] 2023-01-01 05:40
@bsclifton **Show autocomplete suggestions in address bar** is turned off yet browser histories are appearing on the address bar

My Brave is up to date
Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)

**Comment by CQ-0** [comment] 2023-01-01 10:08
@bsclifton I'm on the latest version on version of Brave: 
Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)

I have unchecked all 4 options under `Show autocomplete suggestions in address bar` in brave://settings/appearance, and disabled the whole top level `Show autocomplete suggestions in address bar`. Additionally, I have also unchecked `Auto-complete searches and URLs` under brave://settings/privacy. Re-enabled them, restarted, disabled, restarted again, and it still behaves the same.

Going to brave://omnibox/ and checking `Connect window omnibox`, then clicking the omnibox on a new tab shows that the "Provider" for the suggestions is "LocalHistoryZeroSuggest". Changing the `#omnibox-max-zero-suggest-matches` in flags to `Enabled 5` limits the suggestions to only 5. Therefore, there should should definitely be a fix for this issue that has been bugging users for years if another Chromium browser doesn't behave this way.

**Comment by CQ-0** [comment] 2023-01-01 10:09
> Same problem even after configuring all settings relating to search. This [extension](https://github.com/slymax/cloak) fixes it for now.

Unfortunately this doesn't work for me for some reason.

**Comment by rebron** [comment] 2023-01-03 19:10
cc: @fallaciousreasoning

**Comment by rebron** [comment] 2023-01-05 01:04
@krish-98 and @bE7rwls Both of you are using Google search engine as the default correct? I can reproduce with just Google but not any other search engine.

**Comment by rebron** [comment] 2023-01-05 01:10
I can reproduce on 1.46.144 Chromium: 108.0.5359.128 (Official Build) (arm64) but looks like it's fixed in 1.47.x and higher. 1.47.x is targetted for release next week.

**Comment by ZeroCool940711** [comment] 2023-01-05 06:05
> @krish-98 and @bE7rwls Both of you are using Google search engine as the default correct? I can reproduce with just Google but not any other search engine.

I also have this issue and think google is the only search engine having this issue on brave, the others work properly but when you set google as your default search engine you can't disable the search history and it's always shown on the address bar, no matter if it was a search made directly from the address bad that sent you to google or a search made after you manually went to google and searched for something, it will always show up on the address bar, even if you have disabled google's own search history and made it so its not saving anything for you, it will still show up on the brave's address bar which is really concerning.

**Comment by bsclifton** [comment] 2023-01-10 19:08
Huge thanks for confirming it's fixed in 1.47 and newer @rebron 😄 If it was a regression upstream it may have been fixed with the Chromium upgrade (as 1.47 upgrades us to Chromium 109)

**Comment by bsclifton** [comment] 2023-01-13 05:29
This should be closed now as 1.47 was released today 😄

**Comment by bE7rwls** [comment] 2023-01-13 09:27
![3](https://user-images.githubusercontent.com/67607468/212285252-6c735698-c3fa-4562-aee0-e616ad7ba29e.png)
1.47.171 cleared cache, same problem

**Comment by rebron** [comment] 2023-01-17 20:27
@bE7rwls Are these your settings in brave://settings/appearance?
<img width="715" alt="Screenshot 2023-01-17 at 12 25 24 PM" src="https://user-images.githubusercontent.com/5951041/213005360-d55dbaa8-b4b5-45b0-91e9-e06943564d46.png">

**Comment by rebron** [comment] 2023-01-17 20:32
@bE7rwls Below is what I'm getting in 1.47.171. Can you provide the OS, maybe platform specific?

<img width="637" alt="Screenshot 2023-01-17 at 12 30 34 PM" src="https://user-images.githubusercontent.com/5951041/213006231-84636cdf-192f-4a51-af59-c8570cd1e938.png">

**Comment by bE7rwls** [comment] 2023-01-17 21:19
Windows 10 22h2 19045.2486, Autocomplete suggestions - off, Auto-complete searches and URLs - off. Btw, could this have something to do with having multiple profiles in Brave?

**Comment by ZeroCool940711** [comment] 2023-01-17 21:25
> Windows 10 22h2 19045.2486, Autocomplete suggestions - off, Auto-complete searches and URLs - off. Btw, could this have something to do with having multiple profiles in Brave?

I'm pretty sure the issue is specific with Google being the default search engine, this issue only happens when you have Google set as your default search engine, if you use any other search engine the search history is gone from the address bar correctly if you disable the options for it and you have your privacy back. I still don't understand how something like this that compromises your privacy no matter how you look at it, still hasn't being fixed in such a long time, it's practically an issue that has being around for years, every couple of releases it gets patched and temporarily fixed but it always comes back.

**Comment by rebron** [comment] 2023-01-17 22:21
@bE7rwls Are you also in the US region or are you somewhere else? The google search is different per region.

**Comment by rebron** [comment] 2023-01-17 23:45
@bE7rwls Thanks for helping us with this issue. I wanted to ask if you had sync enabled.

**Comment by bE7rwls** [comment] 2023-01-17 23:46
EU region, sync enabled 
![123123](https://user-images.githubusercontent.com/67607468/213036861-b7568e07-d18e-46b5-bd81-73d71d8c249c.png)

**Comment by MadhaviSeelam** [comment] 2023-01-18 16:22
Reproduced the issue in Win 11 x64.   This issue was reproduced in Win 10 and macOS as well. @GeetaSarvadnya @stephendonner, please feel free to add your test results.   

cc: @rebron @fallaciousreasoning 

```
Brave | 1.47.171 Chromium: 109.0.5414.87 (Official Build) (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

1. new profile
2. launch Brave 
3. open `brave://settings/search`
4. select `Google`
5. open `brave://settings/appearance`
6. Unselect `Browsing History`, `Top sites`, and `Suggested Sites`
7. open `brave://settings/privacy`
8. disable `Autocomplete searches and URLs`
9. open a new tab enter few search terms in the URL bar (eg. clouds, rains)
10. open a new tab and click in the URL bar  (do not enter anything)

Actual results: Search history shows up
Expected results: Search results shouldn't autocomplete

<image width="500" alt="image" src="https://user-images.githubusercontent.com/98358127/213231256-328d502d-a508-41cd-9110-3cb786093831.png">

**Comment by stephendonner** [comment] 2023-01-18 22:55
I was also able to reproduce this using `1.47.171` on `macOS`:


example | example | example
---------|----------|---------
<img width="1140" alt="Screen Shot 2023-01-17 at 4 42 01 PM" src="https://user-images.githubusercontent.com/387249/213313110-9e00e919-0f23-45ad-8497-884900f411dc.png"> | <img width="1140" alt="Screen Shot 2023-01-17 at 4 48 09 PM" src="https://user-images.githubusercontent.com/387249/213313114-4f872d95-0af1-4c68-ba14-e8a6f044ebd5.png"> | <img width="1140" alt="Screen Shot 2023-01-17 at 4 52 32 PM" src="https://user-images.githubusercontent.com/387249/213313116-4250b494-5dcc-472d-bc05-cfc4c68fd618.png">

**Closed** 2023-01-26 02:12 UTC
Labels: feature/history, priority/P2, regression, feature/settings, OS/Desktop

**Comment by stephendonner** [comment] 2023-02-08 01:34
## Verified `PASSED` using 

Brave | 1.49.89 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)



Followed the steps to reproduce from https://github.com/brave/brave-browser/issues/26894#issuecomment-1387342514.

#### Confirmed I didn't see anything, at all, autocompleted/present in the URL bar, pressing `down`, `spacebar`, etc.

example | example | example | example | example
---------|----------|---------|---------|----------
<img width="1159" alt="Screen Shot 2023-02-07 at 5 25 33 PM" src="https://user-images.githubusercontent.com/387249/217405355-ba5f0b91-6c89-4dd0-b071-d5a8f1b7cde9.png"> | <img width="1159" alt="Screen Shot 2023-02-07 at 5 26 12 PM" src="https://user-images.githubusercontent.com/387249/217405358-29f1579c-4ed1-41c2-99a3-39ceed6369c1.png"> | <img width="1159" alt="Screen Shot 2023-02-07 at 5 31 37 PM" src="https://user-images.githubusercontent.com/387249/217405636-5e225528-dad0-4e29-b204-aee62e622e4d.png"> | <img width="1159" alt="Screen Shot 2023-02-07 at 5 27 49 PM" src="https://user-images.githubusercontent.com/387249/217405362-43d1f0f0-46e0-4bc1-bebd-a0aeb2f69fca.png"> | <img width="1159" alt="Screen Shot 2023-02-07 at 5 28 07 PM" src="https://user-images.githubusercontent.com/387249/217405363-17729a42-7709-410d-95f4-11d0d0ce9dc4.png">

**Comment by fallaciousreasoning** [comment] 2023-02-08 02:15
For those who want the fix, it's available in the latest Nightly - should be in stable in the next couple of months.

**Comment by stephendonner** [comment] 2023-02-08 18:12
> For those who want the fix, it's available in the latest Nightly - should be in stable in the next couple of months.

Around March 7th: https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#release-channel-dates

**Comment by MadhaviSeelam** [comment] 2023-02-17 22:00
Verification `In progress` using
```
Brave | 1.49.101 Chromium: 110.0.5481.104 (Official Build) beta (64-bit)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | Windows 11 Version 22H2 (Build 22621.1265)
```

**Comment by LaurenWags** [comment] 2023-03-01 20:57
Verification in progress with

```
Brave	1.49.114 Chromium: 110.0.5481.177 (Official Build) beta (64-bit) 
Revision	f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS	Linux
```

**Comment by bE7rwls** [comment] 2023-03-10 17:48
Hello, updated to v1.49.120. The results are still showing up on the adress bar. Or the fix is gonna be in future updates? (Autocomplete suggestions - off, Auto-complete searches and URLs - off, cache cleared)
![brave_yn1sibsXgm](https://user-images.githubusercontent.com/67607468/224387187-5ca19d4a-7497-4bf8-8516-e34dfc0e152f.png)

**Comment by fallaciousreasoning** [comment] 2023-03-12 20:00
@bE7rwls could you send me a screenshot of your settings from Step 6 in this comment?
https://github.com/brave/brave-browser/issues/26894#issuecomment-1450834549

**Comment by krish-98** [comment] 2023-03-13 15:11
I don't know how they closed this issue which hasn't even been solved yet.

**Comment by bE7rwls** [comment] 2023-03-15 15:51
But the initial problem is that it should only show suggestions from the browser history when I start typing something, not when I just click on the address bar. It only works correctly using any other search engine than Google. Is it possible to fix?

1.open brave://settings/search
2.select Google
3.open brave://settings/appearance
4. show autocomplete suggestions in address bar - on
5. select Browsing History, Top sites, and Suggested Sites
6.open a new tab enter few search terms in the URL bar (eg. clouds, rains)
7. open a new tab and click in the URL bar (do not enter anything)

Expected results: Google search history is not showing up
Actual results: Google search history shows up


1.open brave://settings/search
2.select any other search engine, e.g. Bing
3.open brave://settings/appearance
4. show autocomplete suggestions in address bar - on
5. select Browsing History, Top sites, and Suggested Sites
6.open a new tab enter few search terms in the URL bar (eg. clouds, rains)
7. open a new tab and click in the URL bar (do not enter anything)

Expected results: Bing search history is not showing up
Actual results: Bing search history is not showing up
