### ISSUE TITLE
[C128] Google Lens menu shows up when entering a webpage

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#40379] opened 2024-08-09 06:23 UTC
### Description

Google Lens menu shows up when entering a webpage

### Steps to reproduce

1. Upgrade to `1.70.58
2. Enter a wrong domain 
3. Google Lens menu shows up
4. Clicking on it opens modal 
5. Learn more in modal loads `https://support.google.com/chrome/answer/15086890?visit_id=638587806479638069-3328244170&p=search_from_page&rd=1`

### Actual result

https://github.com/user-attachments/assets/19a9f846-9a44-405c-b3f7-39da74b29c53

Learn more loads `https://support.google.com/chrome/answer/15086890?visit_id=638587806479638069-3328244170&p=search_from_page&rd=1`

### Expected result

Remove Google Branding

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.70.58 Chromium: 128.0.6613.18 (Official Build) nightly (64-bit)
-- | --
Revision | 4092fbd4ef3e2bd48c3e47e8afd7770bfb9e111f
OS | Windows 11 Version 23H2 (Build 22631.3880)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @mkarolin @rebron @brave/qa-team

**Comment by mkarolin** [comment] 2024-08-09 16:05
I can't reproduce it on `128.0.6613.27`.

I believe this was fixed upstream with https://chromium.googlesource.com/chromium/src/+/eccfa6eb0ab35

```
commit eccfa6eb0ab357b691a55c0235b3e20c144e01e9
Author: Erik Chen <erikchen@chromium.org>
Date:   Mon Aug 5 22:01:53 2024 +0000

    [128][lensoverlay] When Lens is disabled, hide the lens omnibox button.

    The logic was previously checking for existence of
    LensOverlayController, when it instead should be checking
    LensOverlayEntryPointController::IsEnabled().

    (cherry picked from commit 3ee261053307fba8081e3f15398baba5f1b97c8f)

    Bug: 355345089, 356393283
```

Requires version `1.70.62` to verify.

**Comment by rebron** [comment] 2024-08-13 21:26
@GeetaSarvadnya Sounds like we can close this issue based on your last comment.

**Comment by GeetaSarvadnya** [comment] 2024-08-14 15:06
@srirambv Can you check this on latest nightly version please? Thanks!

**Closed** 2024-08-14 15:08 UTC
Labels: bug, QA/Yes, release-notes/exclude, regression, Chromium/waiting upstream, branding, OS/Desktop

**Comment by srirambv** [comment] 2024-08-14 15:16
Can't repro anymore on the latest nightly.

**Comment by GeetaSarvadnya** [comment] 2024-08-15 06:34
Verification **PASSED** on

```
Brave | 1.69.146 Chromium: 128.0.6613.27 (Official Build) (64-bit)
-- | --
Revision | 3bd0f984ce99277bd556cac8dd198aba4467a22f
OS | Windows 10 Version 22H2 (Build 19045.4780)
```
Confirmed that Google Lens menu isn't shown on `github.com.com`
![Google lens icon](https://github.com/user-attachments/assets/729d2532-efa7-4b28-97bc-03fa4d4bd725)
