### ISSUE TITLE
Expire geolocation permission after 24 hours

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#5946] opened 2019-09-09 17:39 UTC
When a site receive permission from the user to perform geolocation, this permission only lasts for 24 hours in Safari. We should match this.

There might be a need for exceptions however (e.g. Google Maps).

We should make sure that this doesn't regress #1353 however.

**Comment by fmarier** [comment] 2021-08-21 00:56
@pes10k @ShivanKaul Now that we have the UI to allow users to do this from the permission drop-down, maybe we should change the default for some sensitive permissions like geolocation?

**Comment by pes10k** [comment] 2021-08-22 14:44
The default in the dropdown is currently "until the page session is over", the shortest option. What did you have in mind @fmarier ?

<img width="326" alt="Screen Shot 2021-08-22 at 9 43 27 AM" src="https://user-images.githubusercontent.com/76526/130359324-e488d254-783f-450b-bb78-45a7e63deaad.png">

**Comment by fmarier** [comment] 2021-08-23 17:32
Oh, I guess it's already pretty tight then. If you have the original issue for these permission dialogs handy, we can dupe this one and close it.

**Comment by pes10k** [comment] 2021-08-23 20:53
Sure thing, sounds good @fmarier.  Marking this closed as dupe of https://github.com/brave/brave-browser/issues/14126

**Closed by pes10k** 2021-08-23 20:53 UTC
Labels: privacy, priority/P3, privacy/chromium-redqueen, privacy/permissions
