### ISSUE TITLE
TOO MANY REDIRECTS caused by Brave's user agent behavior

### ISSUE THREAD

**Issue by mikegrima** [brave/brave-browser#6966] opened 2019-11-16 18:51 UTC
## Description 
Hello:

With recent Brave releases, there was a change to the user-agent behavior that breaks authentication on sites that utilize [zmartzone/mod_auth_openidc](https://github.com/zmartzone/mod_auth_openidc). Effectively, Brave now randomizes the number of `Brave`s in the user-agent, which some authentication systems rely on.

The issue is documented in more detail here: https://github.com/zmartzone/mod_auth_openidc/issues/452

Can an option be added to disable this behavior? This currently breaks Brave for use on our internal sites.

## Steps to Reproduce

   1.  Go to an internal authenticated site that uses [zmartzone/mod_auth_openidc](https://github.com/zmartzone/mod_auth_openidc)
   2.  `ERR_TOO_MANY_REDIRECTS`

## Brave version (brave://version info)
```
Brave | 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
```

**Comment by fmarier** [comment] 2019-11-17 07:16
Is there a public test site that can be used to demonstrate the problem?

**Comment by mikegrima** [comment] 2019-11-17 23:56
That's a great question. I have not encountered any issues with public sites -- only our internal sites. 

@drkancharla is there an easy way to demonstrate this behavior -- like a docker image that could be set up to make it easy to test?

**Comment by bsclifton** [comment] 2019-12-04 16:13
Definitely a bug with the custom user-agent logic we have:
https://github.com/brave/brave-core/blob/66ceaf3491778f7d9a62f215c8fb47b318c9b181/browser/net/brave_site_hacks_network_delegate_helper.cc#L62-L76

Appears it will always do a substitution, leading to multiple `Brave` strings in the UA

**Comment by bsclifton** [comment] 2019-12-10 07:14
Marking as `QA/No` since I don't believe there are steps to reproduce. But we have an automated test in https://github.com/brave/brave-core/pull/4143

**Closed** 2019-12-10 08:50 UTC
Labels: QA/No, bug, release-notes/include

**Comment by iefremov** [comment] 2019-12-10 08:53
I've reproduced on netflix.com - it redirected me to the russian site :) After the redirect "Brave Brave" is visible in User-Agent in devtools

**Comment by mikegrima** [comment] 2019-12-10 20:03
@bsclifton I'm happy to test this with a pre-release version.

**Comment by mikegrima** [comment] 2019-12-10 20:09
Confirmed that the nightly works 🎉

Thank you all for getting this done!

**Comment by bsclifton** [comment] 2019-12-10 20:48
@mikegrima awesome! Thanks for confirming 😄👍

**Comment by mikegrima** [comment] 2020-01-18 02:02
Is it possible to move this to an earlier release? I would really like to start using Brave at work again.
