### ISSUE TITLE
Add a "Disable autoupdate" feature (disable updates)

### ISSUE THREAD

**Issue by jstnbr** [brave/brave-browser#32648] opened 2023-08-31 16:41 UTC
I noticed this old thread and see a lot of conflicting views. I'm very happy with the solution mentioned here adding a flag. I don't see the flag setting. Where is it?

I am running v1.57.57 on macOS Catalina.

>              We know that there are a bunch of ways to disable auto-updates, (including https://www.chromium.org/administrators/turning-off-auto-updates ), but they're varying degrees of convoluted. So to make things neater, we're going to implement a flag allowing auto-updates to be disabled manually. I still want to emphasize that this is a dangerous flag to set, but we appreciate needs like @360fun's to avoid auto-updates on limited connections.

_Originally posted by @tildelowengrimm in https://github.com/brave/brave-browser/issues/5576#issuecomment-525437745_

**Comment by vazh2100** [comment] 2023-12-12 17:08
Yes. Where is the feature of disabling auto update?
I don't like auto updates. These disturb me, when I launch browser and click on address line and start typing.  That interrupt my input.

**Comment by bsclifton** [comment] 2023-12-12 19:22
Thanks for the feedback folks - I'm going to close this as a duplicate of https://github.com/brave/brave-browser/issues/5576

We still need to figure out the proper solution there. It's an older issue with a few proposed solutions. As of this writing, the recommended way to disable auto-updates is using a work-around described here:
https://support.google.com/chrome/a/answer/6350036?hl=en#zippy=%2Cturn-off-chrome-browser-updates

Maybe I can work with support to get a Brave version of this article created (or we can update the existing group policy page, at https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy). We don't have templates for this yet - that's captured with https://github.com/brave/brave-browser/issues/26503. So a person would need to create a registry key manually to disable updates.

**Closed by bsclifton** 2023-12-12 19:22 UTC

**Comment by vazh2100** [comment] 2023-12-13 06:54
> Thanks for the feedback folks - I'm going to close this as a duplicate of #5576
> 
> We still need to figure out the proper solution there. It's an older issue with a few proposed solutions. As of this writing, the recommended way to disable auto-updates is using a work-around described here: https://support.google.com/chrome/a/answer/6350036?hl=en#zippy=%2Cturn-off-chrome-browser-updates
> 
> Maybe I can work with support to get a Brave version of this article created (or we can update the existing group policy page, at https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy). We don't have templates for this yet - that's captured with #26503. So a person would need to create a registry key manually to disable updates.

I am a linux user. Your recommendations not applicable for me.

**Comment by bsclifton** [comment] 2023-12-13 08:22
@vazh2100 Linux and macOS can use group policy also. I'll put together some examples tomorrow for each OS

**Comment by vazh2100** [comment] 2023-12-13 16:36
> @vazh2100 Linux and macOS can use group policy also (Linux by creating a file). I'll put together some working examples tomorrow for each OS. For an example of what that would look like, check out [#25394 (comment)](https://github.com/brave/brave-browser/issues/25394#issuecomment-1336865132)
> 
> But you're right - if you use a package manager, you would need to avoid updating Brave yourself

Thank you. It would be great.
