### ISSUE TITLE
`qrcode_generator::QRCodeGeneratorBubbleController::ShowBubble` crash when creating QR code for PDF files

### ISSUE THREAD

**Issue by Nicola-Sergio** [brave/brave-browser#20959] opened 2022-02-07 22:48 UTC
## Description 

When trying to generate the qr code of a pdf viewing page, brave suddenly crashes. I've tried the same feature on other browsers with the same sample site, and everything works.

## Brave version 
1.35.100 Chromium: 98.0.4758.87

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- In which file does the problem lie?

**Comment by kjozwiak** [comment] 2022-02-08 01:43
Thanks for the report @Nicola-Sergio 👍 Managed to reproduce the issue using the following STR:

* load https://bitcoin.org/bitcoin.pdf or https://basicattentiontoken.org/static-assets/documents/BasicAttentionTokenWhitePaper-4.pdf
* right click on the document and select `Create QR code for this page`

Callstack from BackTrace via https://brave.sp.backtrace.io/p/brave/triage?filters=(_rxid%3Da1e00400-d4e4-b007-0000-000000000000)&aggregations=((fingerprint%3Bissues%3Binvariants%2Chead)%2C(fingerprint%3Bissues%3Btags%2Chead)%2C(fingerprint%3Bissues%3Bticket%2Chead)%2C(fingerprint%3Bissues%3Bassignee%2Chead)%2C(fingerprint%3Bissues%3Bstate%2Chead)%2C(fingerprint%3Bfirst_seen%2Chead)%2C(callstack%2Chead)%2C(timestamp%2Cbin%2C32)%2C(timestamp%2Crange)%2C(uname.sysname%2Cdistribution%2C3)%2C(ver%2Cmax)%2C(ver%2Cmin)%2C(guid%2Cunique)%2C(classifiers%2Chead))&similarity=false:

```
[ 00 ] qrcode_generator::QRCodeGeneratorBubbleController::ShowBubble(GURL const &,bool)
[ 01 ] RenderViewContextMenu_Chromium::ExecuteCommand(int,int)
[ 02 ] _tailMerge_esent.dll
[ 03 ] _tailMerge_esent.dll
[ 04 ] views::HWNDMessageHandler::Close()
[ 05 ] static void * base::internal::PartitionMalloc(const struct base::allocator::AllocatorDispatch *, unsigned __int64, void *)
[ 06 ] 0x7ffe4a1d1aed
[ 07 ] _tailMerge_esent.dll
[ 08 ] _tailMerge_esent.dll
[ 09 ] _tailMerge_esent.dll
[ 10 ] _tailMerge_esent.dll
[ 11 ] views::HWNDMessageHandler::Close()
[ 12 ] _tailMerge_esent.dll
[ 13 ] _tailMerge_esent.dll
[ 14 ] views::HWNDMessageHandler::Close()
[ 15 ] static void * base::internal::PartitionMalloc(const struct base::allocator::AllocatorDispatch *, unsigned __int64, void *)
[ 16 ] _tailMerge_esent.dll
[ 17 ] gwp_asan::internal::`anonymous namespace'::AllocFn(base::allocator::AllocatorDispatch const *,unsigned __int64,void *)
[ 18 ] _tailMerge_esent.dll
[ 19 ] static void * base::`anonymous namespace'::AllocFn(const struct base::allocator::AllocatorDispatch *, unsigned __int64, void *)
[ 20 ] views::HWNDMessageHandler::Close()
[ 21 ] _tailMerge_esent.dll
[ 22 ] malloc
[ 23 ] static void * base::`anonymous namespace'::AllocFn(const struct base::allocator::AllocatorDispatch *, unsigned __int64, void *)
[ 24 ] views::HWNDMessageHandler::Close()
[ 25 ] views::SubmenuView::GetMenuItems()
[ 26 ] views::MenuItemView::DestroyAllMenuHosts()
[ 27 ] BraveRenderViewContextMenu::ExecuteCommand(int,int)
[ 28 ] ui::MenuModel::GetModelAndIndexForCommandId(int,ui::MenuModel * *,int *)
[ 29 ] views::MenuModelAdapter::ExecuteCommand(int,int)
[ 30 ] views::internal::MenuRunnerImpl::OnMenuClosed(views::internal::MenuControllerDelegate::NotifyType,views::MenuItemView *,int)
[ 31 ] class views::MenuItemView * views::MenuController::ExitTopMostMenu()
[ 32 ] void views::MenuController::ExitMenu()
[ 33 ] ui::PropertyHandler::GetProperty<ui::ElementIdentifier>(ui::ClassProperty<ui::ElementIdentifier> const *)
[ 34 ] void views::MenuController::Accept(class views::MenuItemView *, int)
[ 35 ] struct views::MenuController::MenuPart views::MenuController::GetMenuPartByScreenCoordinateUsingMenu(class views::MenuItemView *, const class gfx::Point & const)
[ 36 ] base::ElapsedTimer::ElapsedTimer()
[ 37 ] views::MenuController::OnMouseReleased(views::SubmenuView *,ui::MouseEvent const &)
[ 38 ] aura::Window::GetEventHandlerForPoint(gfx::Point const &)
[ 39 ] wm::DefaultScreenPositionClient::ConvertPointFromScreen(aura::Window const *,gfx::PointF *)
[ 40 ] ui::ViewProp::GetValue(HWND__ *,char const *)
[ 41 ] views::MenuItemView::GetMenuController()
[ 42 ] gfx::ToFlooredPoint(gfx::PointF const &)
[ 43 ] views::MenuItemView::GetMenuController()
[ 44 ] views::Widget::OnMouseEvent(ui::MouseEvent *)
[ 45 ] views::TooltipManagerAura::UpdateTooltipManagerForCapture(views::Widget *)
[ 46 ] aura::WindowTargeter::FindTargetForEvent(ui::EventTarget *,ui::Event *)
[ 47 ] ui::EventDispatcherDelegate::DispatchEvent(ui::EventTarget *,ui::Event *)
[ 48 ] _tailMerge_esent.dll
[ 49 ] ui::EventProcessor::OnEventFromSource(ui::Event *)
[ 50 ] operator new(unsigned __int64)
[ 51 ] ui::EventSource::SendEventToSinkFromRewriter(ui::Event const *,ui::EventRewriter const *)
[ 52 ] ui::LatencyInfo::AddLatencyNumber(ui::LatencyComponentType)
[ 53 ] views::DesktopWindowTreeHostWin::HandleMouseEvent(ui::MouseEvent *)
[ 54 ] ui::MouseEvent::MouseEvent(CHROME_MSG const &)
[ 55 ] ui::IsMouseEventFromTouch(unsigned int)
[ 56 ] __int64 views::HWNDMessageHandler::HandleMouseEventInternal(unsigned int, unsigned __int64, __int64, bool)
[ 57 ] extensions::ExtensionFunctionDispatcher::Dispatch(mojo::StructPtr<extensions::mojom::RequestParams>,content::RenderFrameHost *,int,base::OnceCallback<void >)
[ 58 ] mojo::core::RequestContext::~RequestContext()
[ 59 ] _tailMerge_esent.dll
[ 60 ] RtlSetLastWin32Error
[ 61 ] 0xaaaaaaaa00000003
```

CCing @iefremov @rebron

**Comment by Nicola-Sergio** [comment] 2022-02-08 16:53
Thank you so much for your guidance @kjozwiak , but how can I log into backtrace since I don't have a login account ?

**Comment by kjozwiak** [comment] 2022-02-19 04:12
> Thank you so much for your guidance @kjozwiak , but how can I log into backtrace since I don't have a login account ?

Unfortunately access is only given to Brave employees but I added the crash stack that you were running via https://github.com/brave/brave-browser/issues/20959#issuecomment-1032125617 so someone from Brave can take a look and investigate. @rebron who's our desktop product manager assigned it a `P2` as per https://github.com/brave/brave-browser/issues/20959#event-6029509748 which means it should get fixed sooner than later 👍

**Comment by kjozwiak** [comment] 2022-06-14 05:13
Closing as this looks fixed. Probably fixed in one of the many chromium bumps we've had between then and now. Went through the following builds using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/20959#issuecomment-1032125617 and couldn't reproduce the issue.

```
Brave | 1.41.59 Chromium: 103.0.5060.42 (Official Build) nightly (64-bit)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | Windows 11 Version 21H2 (Build 22000.708)
```

```
Brave | 1.39.122 Chromium: 102.0.5005.115 (Official Build) (64-bit)
-- | --
Revision | 174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}
OS | Windows 11 Version 21H2 (Build 22000.708)
```

Example of the above working:

![image](https://user-images.githubusercontent.com/2602313/173498272-e26af977-e82e-4507-a3a6-f2ac548a8a17.png)

**Closed by kjozwiak** 2022-06-14 05:13 UTC
Labels: bug, crash, priority/P2, QA/Yes, OS/Desktop, feature/pdf
