### ISSUE TITLE
default to .com for FTX widget

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#16790] opened 2021-07-06 17:57 UTC
## Description 

Non en-US users should see the FTX widget default to .com and see FTX.com. Currently non en-US users are seeing .us and FTX.us

<img width="295" alt="Screen Shot 2021-07-06 at 10 58 40 AM" src="https://user-images.githubusercontent.com/5951041/124675030-b63bae00-de70-11eb-9f54-9837bc7e0af0.png">

## Steps to Reproduce/Actual result:

   1. Go to the new tab page and open up FTX widget from a non en-US version of Brave starting with 1.26.67 and higher
   2. Notice that you are defaulted to .us links
 

## Expected result:
Non en-US users should default to .com links
en-US users should remain defaulted to .us 

## Reproduces how often: 

Easily

## Brave version (brave://version info)

1.26.67

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a 
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by srirambv** [comment] 2021-07-07 04:24
Dupe of #16121

**Closed** 2021-07-12 07:44 UTC
Labels: OS/Desktop, QA/Yes, closed/duplicate, feature/widgets, priority/P3, release-notes/exclude
