### ISSUE TITLE
brave crashing when visiting `brave://local-state` right after installing

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#25931] opened 2022-10-12 04:00 UTC
## Description 

Brave crashes whenever you visit `brave://local-state` right after installing Brave. Seems to be working fine when installing via the `APK` and not GPS.

## Steps to reproduce 

   1. install Brave via the GPS
   2. open Brave and either run through onboarding or skip onboarding (doesn't really matter)
   3. visit `brave://local-state` and Brave will crash (see crash stack attached below)

## Actual result 

```
2022-10-11 23:46:39.264 25877-25877/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.brave.browser, PID: 25877
    java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.play.core.splitinstall.receiver.SplitInstallUpdateIntentService flg=0x40200010 pkg=com.brave.browser (has extras) } in h73@3beff81
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1800)
        at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.UnsupportedOperationException: Only one module supported.
        at Mg2.a(chromium-MonochromePublic6432.aab-stable-414410524:94)
        at T73.c(chromium-MonochromePublic6432.aab-stable-414410524:0)
        at fa3.d(chromium-MonochromePublic6432.aab-stable-414410524:0)
        at fa3.a(chromium-MonochromePublic6432.aab-stable-414410524:0)
        at h73.onReceive(chromium-MonochromePublic6432.aab-stable-414410524:0)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
        at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:942) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7872) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

## Expected result

Brave shouldn't be crashing when visiting `brave://local-state` right after installing Brave.

## Issue reproduces how often 

100% reproducible when using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details

   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6` (Phone)
   - Android version: `Android 13`
   
## Brave version

```
Brave | 1.44.105 Chromium: 106.0.5249.91 (Official Build) (64-bit)
--- | ---
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | Android 13; Build/T1B2.220916.004
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by samartnik** [comment] 2022-10-13 15:33
It's the upstream error, since it's start working after a while after the crash we will just wait for the upstream fix.

![Screenshot_20221012_153057_com android chrome](https://user-images.githubusercontent.com/30602739/195640621-b3044086-ecb9-45ec-b14e-45c266933b18.jpg)

**Comment by kjozwiak** [comment] 2022-10-13 22:50
@samartnik seeing the crash on `Chrome BETA` that's on `C107` as well. I can't reproduce the `dev_ui` portion of the issue but it definitely seems like an upstream issue. Thanks for taking a look/investigating. Added a video as an example of how the crash looks on `Chrome` when visiting `chrome://local-state` after a fresh/clean install:

https://user-images.githubusercontent.com/2602313/195724796-bd9660d7-5702-492f-87de-0c0f60a6876b.mp4

**Comment by deeppandya** [comment] 2022-10-19 18:45
able to reproduce on chrome so need to wait for upstream fix.

**Comment by MickenCZ** [comment] 2023-03-19 18:13
For me, the same crash happens on brave://gpu
On mobile Edge, this actually works, so this might be a Brave problem.

**Comment by deeppandya** [comment] 2023-11-08 19:47
@samartnik please verify on latest upstream changes.

**Comment by samartnik** [comment] 2023-11-08 20:29
this was fixed in the upstream

**Closed** 2023-11-08 20:29 UTC
Labels: crash, priority/P2, QA/Yes, release-notes/include, Chromium/waiting upstream, OS/Android
