### ISSUE TITLE
Font Size at reddit.com/message/unread

### ISSUE THREAD

**Issue by norsehealer** [brave/brave-browser#4742] opened 2019-06-06 01:29 UTC
## Description 

Font size is much larger on the /message/ page vs the rest of the site.

## Steps to Reproduce

   1. open reddit
   2. get a reply to your comment
   3. see that the page has a 18 font size with "larger" checkbox in the Inspect part.

## Actual result:

Font size is much larger on the /message/ page vs the rest of the site.
side by side screenshot  https://i.imgur.com/IK9Cshl.png

## Expected result:
normal font size across all of the reddit website.

## Reproduces how often: 

every time I visit the page. 

## Brave version (brave://version info)

Brave | 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)
-- | --
Revision | 78e4f8db3ce38f6c26cf56eed7ae9b331fc67ada-refs/branch-heads/3729@{#1013}
-- | --
OS | Windows 10 OS Build 14393.1944

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? nope, still a bigger font size with shields down.
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?  works normally on Chrome, added screenshot above.

**Comment by rebron** [comment] 2019-06-21 16:09
@norsehealer Can you check to see your zoom level? Are you at 100% or at a different value?

**Comment by norsehealer** [comment] 2019-06-21 18:28
@rebron the image linked indicates no zoom level (would have shown a magnify glass). 

There are sites where I do have to keep a 90% so the font isnt huge as posted. 
It’s mostly Reddit for me that has the bigger font size for me.

**Comment by srirambv** [comment] 2019-06-23 11:33
What is the font size set to in `brave://settings/appearance`?

**Comment by norsehealer** [comment] 2019-06-24 01:52
and the settings were set to large.  not sure how I overlooked that. 

I find it odd that it was the only website actually showing a larger font size though.  maybe there's a bug there!?

**Comment by bsclifton** [comment] 2019-06-24 04:50
Closing as it sounds like the issue is resolved! 😄 

Some sites may be overriding this default behavior by forcing a font size, which would make it hard to detect. Also might not be noticeable if you're browsing at 90%.  Whatever the case, please do report back if you find a pattern and you suspect there is a bug 😄

**Closed by bsclifton** 2019-06-24 04:50 UTC
Labels: need-more-info
