### ISSUE TITLE
actionless close button in Site settings->Cookies

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#12539] opened 2020-11-05 15:59 UTC
For some items in Site settings,the close button has no action

## Steps to reproduce 

1. Clean Profile
1. Open Settings -> Site Settings -> Cookies
1. Tap close button at the top right corner

Also reproduces for all other settings in `Settings -> Site Settings` except:
- Desktop Mode
- Video playback in Brave

## Actual result 
The close button has no action
![image](https://user-images.githubusercontent.com/34715963/98262457-ebac9680-1f85-11eb-81ad-28a3f42803e1.png)

## Expected result
The close button closes the settings

Note: On Chrome there is no close button at all
![Screenshot_20201104-182728_Chrome](https://user-images.githubusercontent.com/34715963/98262565-0ed74600-1f86-11eb-990b-e1288e434f69.jpg)

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? yes
- Can you reproduce this issue with the current Play Store Beta version? yes
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86):ARM
   - Device type (Phone, Tablet, Phablet):Tablet
   - Android version:9.0
   
## Brave version
1.16.74

cc @brave/legacy_qa @serg @samartnik @AlexeyBarabash

**Comment by srirambv** [comment] 2020-11-05 16:51
Dupe of #12181

**Closed by srirambv** 2020-11-05 16:51 UTC
Labels: OS/Android, bug, feature/settings
