### ISSUE TITLE
Polish vertical tab UI for the initial version

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#24717] opened 2022-08-17 03:37 UTC
- [x] #25893
- [x] #25853
- [x] #25894
- [x] #26021
- [x] #26463
- [x] #26540
- [x] https://github.com/brave/brave-browser/issues/26540
- [x] #26573
- [x] #29205
- [x] The vertical tab strip should (almost certainly) be to the side of the infobar and bookmarks bar. This is to avoid the "flash" of it's top moving up and down when switching between tabs which have those top bars and tabs which do not. - also reported by our users. https://github.com/brave/brave-browser/issues/25910
- [x] #26680
- [x] #26577
- [x] #26736
- [x] #26770
- [x] #26801
- [x] #26855
- [x] #27066
- [x] https://github.com/brave/brave-browser/issues/26762
- [x] #27462
- [x] #27442
- [x] Keep vertical layout for pinned tabs when it's floating mode
- [x] #27597

---

Future candidates

- [ ] #26688
- [ ] https://github.com/brave/brave-browser/issues/26304
- [ ] Split pinned tabs from scroll area

**Comment by Coffeeling** [comment] 2022-10-25 13:47
Are there plans to make vertical tabs' collapse state window specific? Right now it's global for a profile, which is awkward if you eg. want to put a site on the side to monitor and work in a bigger window.

Vertical tabs also seem to mess up tabbed PWAs/site shortcuts.

**Comment by emkay5771** [comment] 2022-10-25 19:06
Are there plans to make a unified title bar, as Edge has when vertical tabs are turned on? It would allow users to reclaim vertical space.

**Comment by sangwoo108** [comment] 2022-10-25 23:22
@Coffeeling Thank you for your feedback. There's nothing fixed and we're exploring many options. 

> Are there plans to make vertical tabs' collapse state window specific?

Currently, this behavior is intended for now, but if users find it inconvenient, we're willing to change it. cc @rebron @petemill 

> Vertical tabs also seem to mess up tabbed PWAs/site shortcuts.

Thank you for letting me know that. Need to check out.

**Comment by sangwoo108** [comment] 2022-10-25 23:23
Hi, @emkay5771 . It's merged yesterday on Nightly. 

https://github.com/brave/brave-core/pull/15523

Hope you can find it useful.

**Comment by emkay5771** [comment] 2022-10-25 23:44
> Hi, @emkay5771 .
> 
> > 
> 
> Are there plans to make a unified title bar, as Edge has when vertical tabs are turned on? It would allow users to reclaim vertical space.
> 
> It's merged yesterday on Nightly.
> 
> [brave/brave-core#15523](https://github.com/brave/brave-core/pull/15523)
> 
> Hope you can find it useful.

Thanks! Looking forward.

**Comment by bsclifton** [comment] 2022-10-28 08:21
Hi folks - I used this for a few hours today and wanted to share some feedback 😄 
1. It's impossible to tell which tabs are pinned. I have 8 or 9 pinned tabs and in the regular view, they're just an icon. With vertical tabs, it shows the whole tab (icon AND the title). When you hover over it, there is no X- that's the only way you know
2. Dragging a tab out of the tabs area to make a new window made a VERY small window (width-wise). It didn't use the width of my current window
3. To the right of the container where the tabs are... it would be great to get a grab handle so that you can resize the tabs area (to make it skinnier or wider). Many of my tab titles are long and it would be nice to read them - but I can't resize to make it wider

And then reported a bug here:
https://github.com/brave/brave-browser/issues/26347
Backtrace link is https://brave.sp.backtrace.io/p/brave/debug?filters=(_deleted%3D0%2C_rxid%3De1b80100-c482-0f09-0000-000000000000)&fingerprint=446085d490b03797aeda282273bfe938dd6b6b7062329c938338f064a9997116&debug=(%223cc26d9%22,0,0)

**Comment by Coffeeling** [comment] 2022-10-28 20:14
Testing a non-tabbed PWA on Nightly, it completely removes the title bar. Alt+F still gets me to the app menu, but not having any window controls is kind of nasty.

As a small bit of polish, the color line that indicates that a tab is part of a tab group should be noticeably thicker - it's not very visible on a fullscreen browser window.



> Hi folks - I used this for a few hours today and wanted to share some feedback 😄
> 
> 1. It's impossible to tell which tabs are pinned. I have 8 or 9 pinned tabs and in the regular view, they're just an icon. With vertical tabs, it shows the whole tab (icon AND the title). When you hover over it, there is no X- that's the only way you know
> 2. Dragging a tab out of the tabs area (detach) to make a new window made a VERY small window (width-wise). It didn't use the width of the original window
> 3. To the right of the container where the tabs are... it would be great to get a grab handle so that you can resize the tabs area (to make it skinnier or wider). Many of my tab titles are long and it would be nice to read them - but I can't resize to make it wider

On 1. I think I'll be the broken record and suggest aping Microsoft. The Edge team have really thought their vertical tab design through. Pity about the rest of the product.

![](https://user-images.githubusercontent.com/105751/196674142-2134528b-6d16-4248-ac88-6311fb14d7e3.png)

![](https://user-images.githubusercontent.com/54371213/192157322-d79d733f-ac2a-4d45-b8d3-2c2da51a3a6c.png)

Now that I got vert tabs working on my main profile, they've been really awesome to work with, even in this WIP state they are in. They're fast becoming my favourite thing in Brave.

**Comment by emkay5771** [comment] 2022-10-31 15:58
Not sure if this was intentional, but today's update seems to have broken vertical tabs, as well as merged the top and tab bars.

![image](https://user-images.githubusercontent.com/52011243/199052511-3c57b0ae-d2d9-4399-a0d3-5b97dd3974d9.png)

**Comment by sangwoo108** [comment] 2022-11-01 00:15
Hi, @emkay5771. Please check out the context menu on tabs. There should be "Use vertical tabs" item.

**Comment by emkay5771** [comment] 2022-11-01 00:52
Thanks... was the title and address bar merge added to user facing toggles, as well?

**Comment by emkay5771** [comment] 2022-11-01 17:22
One other thing that I noticed... When using vertical tabs in minimized view, upon hovering over the tab bar, it essentially becomes impossible to close the tab, as the "X" moves. In edge, the panel remains expanded until the mouse moves beyond the border of the expanded view, bypassing this issue. Is there a different solution for this in the pipeline? Thanks again for all of your work on what I'd assume is a relatively niche feature. 
C:\Users\emkay\Pictures\Screenpresso\2022-11-01_13h21_26.mp4

**Comment by colorprint** [comment] 2022-11-02 07:55
#brave-vertical-tabs stopped to work in the latest nightly build...

**Comment by sangwoo108** [comment] 2022-11-02 08:39
> #brave-vertical-tabs stopped to work in the latest nightly build...

Hi, @colorprint . Could you checkout thw context menu on tabs? there should be an item "Use vertical tabs"

**Comment by colorprint** [comment] 2022-11-02 08:51
> > #brave-vertical-tabs stopped to work in the latest nightly build...
> 
> Hi, @colorprint . Could you checkout thw context menu on tabs? there should be an item "Use vertical tabs"

Yes, it works now, thanks!

**Comment by sangwoo108** [comment] 2022-11-04 10:35
> One other thing that I noticed... When using vertical tabs in minimized view, upon hovering over the tab bar, it essentially becomes impossible to close the tab, as the "X" moves. In edge, the panel remains expanded until the mouse moves beyond the border of the expanded view, bypassing this issue. Is there a different solution for this in the pipeline? Thanks again for all of your work on what I'd assume is a relatively niche feature. Brave Behavior: https://user-images.githubusercontent.com/52011243/199297235-5138ec8b-4b46-4f63-95ec-a01eec66d9e4.mp4
> 
> Edge Behavior: https://user-images.githubusercontent.com/52011243/199297582-63ae1873-b5b0-4ffe-ac32-857bef48db4a.mp4

@emkay5771 @friedITguy 
Thank you for very detailed explanation. Actually, this is not intended behavior and it's Windows specific bug. Let me fix this soon.

**Comment by RedCard1nal** [comment] 2022-11-07 03:06
Is it the case that the tab heights are now connected to the height of the sidebar tab heights? I noticed recently that the tab heights increase and was wondering if it's possible to add an option to make the tab heights smaller. After all most of us use this feature to save vertical space.

**Comment by sangwoo108** [comment] 2022-11-07 03:15
> Is it the case that the tab heights are now connected to the height of the sidebar tab heights? I noticed recently that the tab heights increase and was wondering if it's possible to add an option to make the tab heights smaller. After all most of us use this feature to save vertical space.

yes, that's correct. https://github.com/brave/brave-browser/issues/26463

**Comment by Coffeeling** [comment] 2022-11-10 01:51
The tabs-hidden vertical tabs window doesn't have a draggable window border along the top.

**Comment by RedCard1nal** [comment] 2022-11-10 06:41
> The tabs-hidden vertical tabs window doesn't have a draggable window border along the top.

Do you mean that it's not resizable at the top? For me on nightly I can drag the window using the very top area of window but I can't resize it from the top of the window. I actually like being able to drag the window.

**Comment by Coffeeling** [comment] 2022-11-10 10:36
> > The tabs-hidden vertical tabs window doesn't have a draggable window border along the top.
> 
> Do you mean that it's not resizable at the top? For me on nightly I can drag the window using the very top area of window but I can't resize it from the top of the window. I actually like being able to drag the window.

Yes. 

Top: Edge
Under: Brave Nightly
![image](https://user-images.githubusercontent.com/54371213/201068833-a0e98f4d-2715-4967-834d-8e50b11f3491.png)

**Comment by anonghuser** [comment] 2022-12-06 00:15
Aside of nightly, is this available in dev or beta builds?
Sorry, I know it's a bit of an off-topic tangent, but how can I see changelogs for those, or even just raw commit lists if their more rapid nature complicates keeping changelogs, to search for inclusion of some feature? There is no info on the download pages that I could find.

**Comment by sangwoo108** [comment] 2022-12-06 00:52
Hi, @anonghuser ! This feature could be enabled from a page, `brave://flags`. Please type "Vertical tabs" and enable it. I believe the flag is in all channels, so you can try using it. But, there could be differences between them.

**Comment by sangwoo108** [comment] 2022-12-07 05:17
> Noticed that in nightly with tab scolling disabled, there seems to be a chunk taken out of the vertical tab bar (see attatched image)... Is that intended behavior? ![image](https://user-images.githubusercontent.com/52011243/205967512-835474ea-a9c2-489b-a552-c44d40a33b7b.png)

Hi, @emkay5771 That's not intended one and I haven't seen it before even with the same flag.  Could you file a bug and tell us more about your env, such as OS and etc?

**Comment by emkay5771** [comment] 2022-12-07 15:20
> > > Noticed that in nightly with tab scolling disabled, there seems to be a chunk taken out of the vertical tab bar (see attatched image)... Is that intended behavior? ![image](https://user-images.githubusercontent.com/52011243/205967512-835474ea-a9c2-489b-a552-c44d40a33b7b.png)
> > 
> > 
> > Hi, @emkay5771 That's not intended one and I haven't seen it before even with the same flag. Could you file a bug and tell us more about your env, such as OS and etc?
> 
> Hi @sangwoo108. I can confirm that I am also experiencing this bug. Would you like me to file a bug report as well? Or would you prefer me to comment with my env info on the issue @emkay5771 creates?

Personally, I'd prefer if you could issue the bug report. Not sure of the exact process, to be honest. Thanks!

**Comment by friedITguy** [comment] 2022-12-07 17:57
> > > > Noticed that in nightly with tab scolling disabled, there seems to be a chunk taken out of the vertical tab bar (see attatched image)... Is that intended behavior? ![image](https://user-images.githubusercontent.com/52011243/205967512-835474ea-a9c2-489b-a552-c44d40a33b7b.png)
> > > 
> > > 
> > > Hi, @emkay5771 That's not intended one and I haven't seen it before even with the same flag. Could you file a bug and tell us more about your env, such as OS and etc?
> > 
> > 
> > Hi @sangwoo108. I can confirm that I am also experiencing this bug. Would you like me to file a bug report as well? Or would you prefer me to comment with my env info on the issue @emkay5771 creates?
> 
> Personally, I'd prefer if you could issue the bug report. Not sure of the exact process, to be honest. Thanks!

Sure thing! I have created the new issue. You can find it here: #27218

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment] 2023-03-30 19:56
@sangwoo108
In Windows - 1.52.5 Chromium: 112.0.5615.49 (Official Build) nightly (64-bit).

This is what happens when you attach/re-attach tabs from another window. The issue happens on both collapsed (which I usually use) and float mode.

![2023-03-30_13-28-34](https://user-images.githubusercontent.com/122518587/228944812-b1d4d832-07f3-49d5-9ce1-560df6bb85e3.gif)

As you can see, it displays some of the title of the tab, which doesn't look fine, and the only way to 'fix it' is by expanding and collapsing the VT, if Brave is in window mode and you maximize the window, it goes back to normal, or just moving a tab around:

![2023-03-30_13-44-23](https://user-images.githubusercontent.com/122518587/228947464-3fb1f995-35c6-42ea-92d9-7f4273932043.gif)

I am comparing this behavior to the video you showed in this PR using it on MacOS https://github.com/brave/brave-core/pull/17690 where it looks fine when you re-attach the tabs.

**Comment by sangwoo108** [comment] 2023-03-30 23:14
> @sangwoo108 In Windows - 1.52.5 Chromium: 112.0.5615.49 (Official Build) nightly (64-bit).
> 
> This is what happens when you attach/re-attach tabs from another window. The issue happens on both collapsed (which I usually use) and float mode.
>

Really appreciate your report. Let me check out that.

**Comment by Coffeeling** [comment] 2023-03-31 00:21
There's also some (mostly visually) odd behavior when selecting multiple tabs. If I select a tab and shift-click on a tab above it, everything behaves normally. If I shift-click on a tab below, it feels like it replaces all the tabs or something, like they jump out, and back in again. They do fall into the same place they used to be in, but it feels like there'll be some odd behavior that might happen as a consequence.

**Comment by sangwoo108** [comment] 2023-03-31 01:43
> There's also some (mostly visually) odd behavior when selecting multiple tabs. [...]


Yeah, I remember that report. I wasn't able to find a clear way to reproduce it on Mac but it looks like it happens on Windows easily. Let me try to fix it.

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment] 2023-04-02 00:59
Well, I found another issue.
Don't know if it is Windows specific as well, I am using win11 and Brave 1.52.8 Chromium: 112.0.5615.49 (Official Build) nightly (64-bit) .

But it has to do when selecting tabs from top to bottom, first problem only happens on window mode where the window just snaps to the left side of the screen, the second problem happens on both, maximize and window mode, and it is worst because the browser just vanishes, and the only way to fix it is by Show Desktop button (button right corner) or alt+f4, because Windows arrow keys (windows snapping features) don't work.


https://user-images.githubusercontent.com/122518587/229324672-ce6a831e-d792-486b-b768-03d1a5d56f2d.mp4

Alt+Tab shows the window is still there, and doing the Show Desktop, when you click to restore all windows, brave appears normal, in the same maximized state like if it never vanished.

So, hope someone can reproduce it as well.

**Comment by pjolt** [comment] 2023-04-02 12:23
I see the same behaviour. 
[Version 1.52.8 Chromium: 112.0.5615.49]
Win 11, 22H2, 22621.1413. 

Since i´m using dual monitor with my secondary monitor being on my left i noticed when it disappears it actually gets transitioned far left outside of the actual view. So everything moving left is the theme here afaik.  

For me with 2 tabs open the process of selecting tabs _sometimes_ require me to use CTRL+left mouse to get the Brave UI to shift left and then it can switch to require me to use SHIFT+left mouse to get it to shift left.

Regardless of number of tabs open selection always has to be in order, 1>2>3 etc to get this shifting behaviour. 

Another observation is that when going maximized, closing all tabs one by one and then quit + restart of brave resulted in it always requiring 4 tabs at minimum before it starts to shift left, tested with both CTRL and SHIFT and both starts happening at 4 tabs. Also still requires to select tabs in order, i.e 1>2>3>4.

**Comment by sangwoo108** [comment] 2023-04-03 07:33
@Emi-TheDhamphirInLoveUnderTheFrozenStar @pjolt Thanks for letting me know those. Unfortunately, I'm not able to reproduce those on my device but they strongly feel like they're related to the jumping problems.

**Comment by sangwoo108** [comment] 2023-04-05 01:22
@Coffeeling @Emi-TheDhamphirInLoveUnderTheFrozenStar @pjolt , A patch to fix the jumping problem was merged on Nightly. Hopefully, that should work.

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment] 2023-04-09 18:24
On Windows, when Ctrl+Shift+A is done, the search tabs panel appears next to the Vertical tab strip, but the button itself is located far away from there, between Brave's menu `☰` and the minimize button. ![image](https://user-images.githubusercontent.com/122518587/230788112-14efc8c8-0a26-4f5f-b1d1-dd64c0fc4aea.png), shouldn't the Search tabs button match what the shortcut is doing? or what I have seen in MacOS in many PRs screenshots/videos, where the button is on the same VT tab strip, right on the same place as the expand/collapse button?

There is even a little flash when the Vertical tab strip is expanded, when you do the shortcut, it can be seen the **first time** after Brave Browser is opened, like, re-enforcing where the Search Tabs button should be on Windows, instead of the other side of the screen 300 miles from the Vertical tab strip
![brave_2023-04-09_11-46-23](https://user-images.githubusercontent.com/122518587/230788425-8ff85c9a-5137-4947-97f6-8684ca447849.gif)

So, it is a small little tiny detail on Windows I noticed it since last year, but thought it was okay until I noticed recently how the panel popups up right next to the tab strip as well, even if the button is still far away from there.
Of course, I like having the button **always** displaying on Windows and not hiding, but for consistency and looks, having it on Vertical Tab strip seems better, even if it has to be tab strip has to be expanded for the button to be used.

**Comment by sangwoo108** [comment] 2023-04-10 00:23
> he search tabs panel appears next to the Vertical tab strip, but the button itself is located far away from there,

Ah, yeah. IIRC, only on Windows 10 the tab search button is on the frame. I forgot that. Let me move the search bubble to below the original button, as it was. I really appreciate that.

**Comment by sangwoo108** [comment] 2023-04-18 04:08
Hi, @Emi-TheDhamphirInLoveUnderTheFrozenStar . As per https://github.com/brave/brave-browser/issues/24717#issuecomment-1490862226 , this behavior is rather flaky so it's taking some time to find solution. Sorry for the dealy.

**Comment by sangwoo108** [comment] 2023-04-21 02:34
Hi, folks. We're moving context menu related to vertical tab strip to brave://settingsappearnce page. Please don't be surprised when you lose the menu.

https://github.com/brave/brave-core/pull/18146

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment] 2023-04-21 20:46
@sangwoo108 great improvements and bugfixes 👍🎉

however, I installed Brave 1.52.65, which has Chromium 113.0.5672.53, and you fixed with the unpinned tab issue and you moved the settings to appearance, and well, something broke creating groups in **InPrivate mode** when `brave://flags/#tab-groups-save` is on. Normal windows works fine, as far as I can see.

I report it because I was testing the unpinned tab fix and then I had to track down what made the browser crash, but I don't even use that feature, so I can disable it and move on, to save groups and improve tabs experience with auto grouping features and all that, I use the extension [Tab Groups Extension](https://chrome.google.com/webstore/detail/tab-groups-extension/nplimhmoanghlebhdiboeellhgmgommi), so just reporting because I noticed it, not because it will affect my experience.

**Comment by sangwoo108** [comment] 2023-04-22 01:39
> something broke creating groups in InPrivate mode when brave://flags/#tab-groups-save is on. Normal windows works fine, as far as I can see.

Thanks @Emi-TheDhamphirInLoveUnderTheFrozenStar for reporting. Let me look into that.

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment] 2023-05-13 13:48
@sangwoo108 The icon ![image](https://github.com/brave/brave-browser/assets/122518587/66ac6dd2-6740-4d8c-8d52-27f169240a34) stays the same regardless of mode, it never changes between Expand/Minimize/hover.
Mentioning that here because I don't know if it is has to do with the whole Leo icons PRs and you might be aware of it.

**Comment by sangwoo108** [comment] 2023-05-14 22:59
> @sangwoo108 The icon stays the same regardless of mode, ...

Thanks, I missed that. The design guide says it should have ink drop effect when it's expanded, but I missed that.

**Comment by sangwoo108** [comment] 2023-05-15 00:29
Let me close this ticekt. Rest of items are scheduled for the next iteration.

**Closed** 2023-05-15 00:29 UTC
Labels: priority/P3, QA/No, release-notes/exclude, OS/Desktop, feature/vertical-tabs
