### ISSUE TITLE
Brave nightly //// I can't turn off (brave rewards) icon in address bar. please help! me!!! I try anything !!! please helap me!!!

### ISSUE THREAD

**Issue by tee4341** [brave/brave-browser#12548] opened 2020-11-06 04:23 UTC
Brave nightly //// I can't turn off (brave rewards) icon in address bar. please help! me!!!
I try anything !!! please helap me!!!

https://www.img.in.th/image/sIOOAl

!!!! option. is hide not use anything!!

https://www.img.in.th/images/b5c94f2845b6715a399aa437c9738517.jpg

**Comment by srirambv** [comment] 2020-11-06 05:23
Dupe of #12533

**Closed by srirambv** 2020-11-06 05:23 UTC
Labels: OS/Android
