### ISSUE TITLE
Extract intent signal from all amazon searches for Brave Ads Purchase Intent

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#10265] opened 2020-06-15 16:19 UTC
The purchase Intent classifier does not attempt to extract an intent signal for all amazon.com searches. Update the search pattern in `search_providers.h` to attempt intent signal extraction on all amazon.com searches.

**Comment by tmancey** [comment] 2020-07-10 10:21
Closing as a duplicate of https://github.com/brave/brave-browser/issues/8487

**Closed by tmancey** 2020-07-10 10:21 UTC
Labels: QA/Yes, enhancement, feature/ads, priority/P3, release-notes/include
