### ISSUE TITLE
Stats on `NTP` are showing wrong results when switching the tabs

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#35090] opened 2024-01-02 19:31 UTC
## Description 

Stats on `NTP` are showing wrong results when switching the tabs.

## Steps to reproduce 

   1. Fresh install and launch Brave
   2. Open https://amazon.com
   3. Open `NTP` > Check the `Stats` numbers
   4. Use the `tab switch` button to change the tab > Observe

## Actual result 

Stats on `NTP` are showing wrong results when switching the tabs.

https://github.com/brave/brave-browser/assets/128532965/bbef1b94-8f6d-453c-8a28-ad03cb25e269

## Expected result

Stats results must show the same numbers when switching the tabs.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? YES
- Can you reproduce this issue with the current Play Store Beta version? YES
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): ANY
   - Android version: ANY
   
## Brave version

```
Brave build: 1.61.109
Chromium: 120.0.6099.144 (Official Build) (64-bit) 
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Another [issue](https://github.com/brave/brave-browser/issues/11093) related to the `Stats`.

**Comment by srirambv** [comment] 2024-01-03 04:42
Known issue for a very long time. Dupe of https://github.com/brave/brave-browser/issues/9946

**Closed by srirambv** 2024-01-03 04:42 UTC
Labels: bug, QA/Yes, OS/Android
