### ISSUE TITLE
can't change cookie settings - all cookies are blocked

### ISSUE THREAD

**Issue by SimpelMe** [brave/brave-browser#26025] opened 2022-10-14 09:31 UTC
## Description 

Can't change the cookie settings. Not in brave://settings/cookies (block all cookies is set and all three radios are greyed out) and not in the shield.

## Steps to Reproduce

   1. go to brave://settings/cookies
   2. switch cookie radios

## Actual result:

Can't set any radio in cookie settings. Selecting any other than "block all cookies" in the shield instantly switching back to "block all cookies".

## Expected result:
Change radios and keep switched setting in the shield.

## Reproduces how often: 

It's doing this permanent.

## Brave version (brave://version info)

Brave | 1.44.112 Chromium: 106.0.5249.119 (Offizieller Build) (arm64)
Überarbeitung | 9f2101830b56fd2ea1408287f6c74e253ebcb7c6-refs/branch-heads/5249@{#797}
Betriebssystem | macOS Version 12.6 (Build 21G115)

## Version/Channel Information:

- Can you reproduce this issue with the current release? It's the current downloaded release.
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment] 2022-10-14 16:06
Closing. Dupe of https://github.com/brave/brave-browser/issues/25411. Please re-open if encountering something different.

**Closed by rebron** 2022-10-14 16:06 UTC
Labels: OS/Desktop

**Comment by SimpelMe** [comment] 2022-10-14 16:21
It could be related to #25411 but current problem of this issue is, that cookies can’t be accepted. Parts of the internet aren’t usable with my current released brave at the moment. Or do you have a work around for me?
