### ISSUE TITLE
Having the print preview open in one tab blocks all requests on other tabs

### ISSUE THREAD

**Issue by MRVDH** [brave/brave-browser#5538] opened 2019-08-05 10:27 UTC
## Description 
Having the print preview open in one tab blocks all requests on other tabs

## Steps to Reproduce
- open the print preview in tab 1
- try to navigate to any page on tab 2

## Actual result:
"Waiting for extension PDF Viewer..."

## Expected result:
Non-blocking requests

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Windows 10 OS Version 1803 (Build 17134.885)

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:
![image](https://user-images.githubusercontent.com/6686385/62457994-2ff62900-b77c-11e9-9a25-d65b6443a35a.png)
![image](https://user-images.githubusercontent.com/6686385/62458054-4dc38e00-b77c-11e9-9003-185e1cfb5ccb.png)
![image](https://user-images.githubusercontent.com/6686385/62457882-fae9d680-b77b-11e9-8cc7-82fcbd88faf2.png)

**Comment by rebron** [comment] 2019-08-16 16:53
Closing. Should be fixed with 68.x, pdf changes.

**Closed by rebron** 2019-08-16 16:53 UTC
Labels: QA/Yes, extension/PDFJS

**Comment by LaurenWags** [comment] 2019-08-16 20:12
Verified passed with

Brave | 0.68.130 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

* reproduced issue using STR above on 0.67.125. Could not reproduce issue on 0.68.130.
