### ISSUE TITLE
Google Account broken in Brave with Shields up

### ISSUE THREAD

**Issue by Snaid1** [brave/brave-browser#22465] opened 2022-04-21 14:48 UTC
## Description 
When trying to log into my google account for gmail, google docs, or account management with shields up, I get a "Error 400 (Bad Request)!!1" error. This doesn't occur if shields are down. 

## Steps to Reproduce

   1. open Brave
   2. go to gmail.com with shields up
   3. log into gmail
   4. view error

## Actual result:
![image](https://user-images.githubusercontent.com/23465479/164477884-84f46ec5-bf82-4847-bec5-b5a93ec0713a.png)

## Expected result:
be able to view my email or google docs with shields up like usual

## Reproduces how often: 
has happened to me every time I've tried today. It's been a couple days since I logged in on my PC so the issue may have been around longer than that and I didn't notice.

## Brave version (brave://version info)

Brave | 1.37.116 Chromium: 100.0.4896.127 (Official Build) (64-bit)
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | Windows 10 Version 2004 (Build 19041.1415)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? no

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? yes
- Does the issue resolve itself when disabling Brave Rewards? no difference
- Is the issue reproducible on the latest version of Chrome? no (chrome doesn't have shields)

## Miscellaneous Information:
Testing was performed with and without shields (without shields showing expected behavior). as well as removing all extensions (no change), clearing cache and cookies (no change), and trying other web browsers (no issues in other browsers).

**Comment by JakobJingleheimer** [comment] 2022-04-24 08:09
This started with the most recent Brave release (I think v1.37.116). All inside-the-wall pages of google are broken (gMail, gCal, gDrive, etc).

**Comment by JakobJingleheimer** [comment] 2022-04-28 08:59
This is affecting a handful of other sites too

**Comment by saaste** [comment] 2022-04-30 19:26
I'm unable to access https://maps.google.fi even with shields down. It keeps redirecting me to https://consent.google.fi.

**Comment by JakobJingleheimer** [comment] 2022-05-03 19:55
@antonok-edm sorry, I don't know if this something you work on, but this seems to be getting no attention from maintainers and it's quite a breakage with very little workaround (basically the only option is to disable SiteShield for everything).

**Comment by JakobJingleheimer** [comment] 2022-05-04 18:31
Huzzah, fixed for me too (version 1.38.111 Chromium: 101.0.4951.54 • May 3, 2022)

**Comment by rebron** [comment] 2022-05-20 20:39
Closing as duplicate of https://github.com/brave/brave-browser/issues/22493 and fixed in 1.38.109.

**Closed by rebron** 2022-05-20 20:39 UTC
Labels: OS/Desktop
