### ISSUE TITLE
Torrents are fully downloaded to memory, potential OOM

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1228] opened 2018-09-21 09:24 UTC
## Steps to Reproduce

   1. Go to https://webtorrent.io/free-torrents
   2. Click on Tears of Steel magnet link
   3. Start downloading the torrent and observe brave memory usage

## Actual result:

Torrent is fully downloaded to memory. Even when torrent is finished downloading, memory is not released. It is released only when the torrent tab is closed and the media associated with it is closed.

Tears of Steel has 571 MB. 
![image](https://user-images.githubusercontent.com/34715963/45872185-a8840f00-bd8f-11e8-8b2f-0d90d1257a5a.png)

## Expected result:
Torrent content is periodically written to disk. 

## Reproduces how often: 

always

## Brave version (chrome://version info)

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

cc @yrliou @bridiver 

Related issues: #289 #855

**Comment by kjozwiak** [comment] 2018-09-24 17:02
Great catch @btlechowski 👍

**Comment by Brave-Matt** [comment] 2018-10-31 19:06
Just had a reddit user report this:
https://www.reddit.com/r/brave_browser/comments/9swo0b/whats_the_path_of_downloaded_files_throught/

**Comment by tomlowenthal** [comment] 2018-11-02 00:13
This looks like a dupe of #1199.

**Closed by tomlowenthal** 2018-11-02 00:13 UTC
Labels: bug, feature/webtorrent
