### ISSUE TITLE
Shields global settings can't be changed in private windows

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#1721] opened 2018-10-18 21:24 UTC
## Description 
Global shield settings are not retained for Private tabs

## Steps to Reproduce

1. Clean profile on 0.55.18
2. Change Default Global Shields settings for Adblocker/Cookie/Fingerprint
3. Open any site in normal tab 
4. Check whether Global shield settings are retained for normal tabs
5. Open any site in Private tab
6. Check whether Global shield settings are retained for Private tabs
7. Observe that Global shield settings are not retained for PT

## Actual result:
Global shield settings are not retained for Private tabs
![global shield settings issue on private tabs](https://user-images.githubusercontent.com/38657976/47185028-f158c480-d349-11e8-8496-91f235e002af.gif)

## Expected result:
Global shield settings should retained for Normal and Private tabs

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? No
- Does it reproduce on browser-laptop? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

@btlechowski Thanks for Reproducing the issue on Windows 7

@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by simonhong** [comment] 2018-10-18 21:46
I think this is expected behavior because private window uses off the record profile.

**Comment by bsclifton** [comment] 2018-10-18 22:44
Possibly related: https://github.com/brave/brave-browser/issues/1373

**Comment by Brave-Matt** [comment] 2018-10-24 20:20
+1 from Community: https://www.reddit.com/r/brave_browser/comments/9r1khf/cant_login_to_google_account_on_incognito/

**Comment by tomlowenthal** [comment] 2018-10-25 00:41
I feel like the actual bug here is that global settings are accessible from private windows, not that changes aren't persistent?

**Comment by bsclifton** [comment] 2018-10-26 16:11
Closing as a duplicate of https://github.com/brave/brave-browser/issues/1373

I'll update the issue text there to include when a public site setting doesn't exist (in which case it should inherit from the global one)

**Closed by bsclifton** 2018-10-26 16:11 UTC
Labels: OS/Windows, feature/private-browsing, feature/shields
