### ISSUE TITLE
Reset brave reward is not working

### ISSUE THREAD

**Issue by newuser-web** [brave/brave-browser#15351] opened 2021-04-18 01:35 UTC
## Description 
When you click on reset brave rewards from the setting it is not resetting brave rewards data. Previous data is available after resetting.

## Steps to reproduce 

   1. Settings > Brave rewards> Reset brave rewards
   2. 
   3. 

## Expected result
All previous data of brave rewards should be deleted
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version: 10
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment] 2021-04-19 04:21
Dupe of #8780 &  #8776

**Closed by srirambv** 2021-04-19 04:21 UTC
Labels: OS/Android
