### ISSUE TITLE
Video panel is black while ads play

### ISSUE THREAD

**Issue by cowwoc** [brave/brave-browser#17295] opened 2021-08-02 12:21 UTC
Version 1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit)

1. Open https://www.jpost.com/international/following-op-ed-in-the-jerusalem-post-cnn-apologizes-to-dore-gold-675605
2. Click play button on video in top of article
3. Video panel will remain black for ~30 seconds
4. Subsequently actual video will play

I think that the black screen corresponds to period of time during which ads are supposed to be playing. It's fine to skip ads but for users who don't think to wait, they will think the video panel is broken. Is there a way to skip the ads immediately and/or overlay information on the black screen to explain the ads will end soon?

**Comment by rebron** [comment] 2021-08-02 15:45
cc: @ryanbr

**Comment by ryanbr** [comment] 2021-08-03 11:53
Hey @cowwoc  Just trying to reproduce the issue, I press play a couple of times (I wasn't sure if the video player registered the click initially) but the 30min CNN video clip played back okay.

Retested again, and just the one click for playback was needed, and no blank video panel.  Does disabling (or enabling) hardware acceleration via `brave://settings/system` help?

**Comment by cowwoc** [comment] 2021-08-03 13:31
Hi @ryanbr 

That's odd. I tried disabling hardware acceleration and it did not help. What I see on my end is:

* When I hover over the video, I can only see a big red play button
* I click it.
* A bar appears at the bottom containing a play, mute and other controls. For the first 15 seconds the screen remains black and the play button looks pressable (as if the video is paused). If you press the play button it turns into a pause button for a fraction of a session, then reverts back to a play button.
* 15 seconds later, the video starts playing and the play button automatically turns into a pause button.

I tried in Private Mode (no extensions enabled) and got the same results. It's odd that this isn't reproducible on your end. What else can we try?

PS: I can reproduce the same behavior in Chrome if and only if I enable Adblock Plus. When ad-blocking is disabled the video plays right away.

**Comment by rebron** [comment] 2021-08-11 23:33
@ryanbr I was able to reproduce. Does seem like we're blocking the video ad (about 30 seconds) before the actual video and it's a black window until the CNN video which does load.

**Comment by ryanbr** [comment] 2021-08-12 00:29
Sorry for the delay @cowwoc   This is what I'm seeing: (Testing to Brave release and Beta)

https://gif.fanboy.co.nz/gif/jpost-video.gif

Does Brave Beta make a difference? also does enabling ads/trackers = Aggresive help?

**Comment by ryanbr** [comment] 2021-08-12 01:33
Okay a few discussions with @rebron regarding the delay brief playback delay (5-7secs) is caused by the preroll advert, I can replicate it in other browsers.

I'll try to get around the delay. may have a fix for this, Just need to see what's needed and if it's worth any privacy trade off.

**Comment by ryanbr** [comment] 2021-08-12 01:52
@cowwoc  Try adding this into `brave://adblock` -> `@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=jpost.com`

Allowing another google script isn't good for privacy.  The delay is annoying, it should be a manual filter for the time being just for user privacy

**Comment by cowwoc** [comment] 2021-08-12 13:51
@ryanbr Thanks for tracking this down. Adding `@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=jpost.com` as a filter fixes this problem. Is it possible to ship with this filter by default?

**Comment by ryanbr** [comment] 2021-08-13 00:52
Too minor as a default filter (privacy here), if it prevented the video from playing completely it might've been treated differently. @cowwoc

**Comment by cowwoc** [comment] 2021-08-13 01:24
Fair enough. Shall we close this issue?

**Comment by ryanbr** [comment] 2021-08-13 01:26
Yeah, seems to be mostly resolved.

**Closed by ryanbr** 2021-08-13 01:26 UTC
Labels: feature/shields/adblock, OS/Desktop
