### ISSUE TITLE
Tip options in BR panel shows up only after page is reloaded second time 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#1663] opened 2018-10-17 18:26 UTC
## Description 
After page load, even if you wait for  8 sec/ 10 sec/ 30 sec/50 sec/1 min, click on BAT icon will not display tip popup completely. Page refresh is required to see the popup completely. 

## Steps to Reproduce

   1.  Launch brave with clean profile
   2.  Enable Rewards 
   3.  Accept the grants
   4. Open any website, wait until page loads successfully. ( Wait for 8 secs)
   5. Click o BAT icon (displayed in the URL bar)
   6. Observer that the Tip site popup is not displayed completely
   7. Refresh the page
   8. Click on BAT icon
   9. Tip popup loads completely

## Actual result:
After a website load, even if you wait for  8 sec/ 10 sec/ 30 sec/50 sec/1 min, click on BAT icon will not display tip popup completely. Page refresh is required to see the popup completely. 
![tip site popup issue](https://user-images.githubusercontent.com/38657976/47108426-3ce77180-d269-11e8-951a-1a7c047cb168.gif)

## Expected result:
The popup should show completely, once the minimum page time is reached after the website load.

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes
- Does it reproduce on browser-laptop? NA

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by NejcZdovc** [comment] 2018-10-18 06:44
closing as dupe of https://github.com/brave/brave-browser/issues/1517

**Closed by NejcZdovc** 2018-10-18 06:44 UTC
Labels: QA/Yes, feature/rewards
