### ISSUE TITLE
Remove topbar and non-search settings from brave://settings for guest windows

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#15053] opened 2021-03-31 19:53 UTC
## Description 

When opening brave://settings in a guest window, we shouldn't show the topbar or non-search related settings.

## Steps to Reproduce

   1. Launch Brave
   2. Hamburger menu -> Open Guest Window
   3. From the newly opened Guest window: Hamburger menu -> Settings

## Actual result:

We show a navigation topbar in Guest windows that includes features that are inaccessible from a Guest window (e.g., Brave Rewards) and we show settings that aren't

## Expected result:
We shouldn't show the navigation topbar in Guest windows (especially since it has things like "Brave Rewards" which require a regular profile and will crash in non-regular profiles). In addition, we should only show search-related settings here (as Chrome does).

@rebron suggested it should look like this instead:

<img width="1239" alt="screen_shot_2021-03-31_at_12 43 44_pm" src="https://user-images.githubusercontent.com/5033691/113202654-ff101500-9238-11eb-9008-31f3cdfec160.png">

## Reproduces how often: 

Easily reproduced.

## Desktop Brave version:

Latest master.

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment] 2021-04-13 16:30
cc: @spylogsster Can you take a look at this one as well since you were in here already via: https://github.com/brave/brave-core/pull/8445

**Comment by jcsavage2** [comment] 2021-04-16 01:01
Hello! I would like to investigate this issue. is it still available and are you looking for help? I'd love to give this a shot!

**Comment by jcsavage2** [comment] 2021-04-23 23:12
@spylogsster @emerick 
Hello! After investigating this issue, it looks like this is fixed. I attached a picture below of the Guest Window that matches the image posted by @rebron. The issue here is still marked as open, just FYI!
<img width="1680" alt="Screen Shot 2021-04-23 at 7 10 21 PM" src="https://user-images.githubusercontent.com/47196473/115938176-c0503200-a467-11eb-83c4-b2ceaf99272c.png">

**Comment by jcsavage2** [comment] 2021-04-23 23:18
@spylogsster @rebron @emerick 
Hello! After investigating this issue, it looks like it is still marked as open even though it is resolved, just FYI! I attached a screenshot of my attempt to reproduce this issue below:
<img width="1680" alt="Screen Shot 2021-04-23 at 7 18 02 PM" src="https://user-images.githubusercontent.com/47196473/115938432-a105d480-a468-11eb-9cbf-06de7ad2d5bf.png">

**Comment by rebron** [comment] 2023-07-28 20:46
We can probably change this to wontfix. wdyt @emerick? The top navigation in guest doesn't have Rewards there and bookmarks and history show a proper warning. 

Other settings for Shields and Social Media blocking seem fine.

**Comment by emerick** [comment] 2023-07-31 14:09
Yes, wontfix makes sense for this.

**Closed** 2023-08-01 18:40 UTC
Labels: closed/wontfix, feature/global-settings, priority/P4, OS/Desktop
