### ISSUE TITLE
Add `Set as desktop background` option in right-click menu on images

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17134] opened 2021-07-23 14:37 UTC
## Description

Suggestion to add "Set as desktop background" option in the right-click menu when a user right clicks on an image.

https://www.reddit.com/r/brave_browser/comments/opodoi/id_love_to_see_this_feature_to_be_added_to_brave/

**Comment by rebron** [comment] 2021-07-23 20:38
Closing as duplicate of #7922

**Closed by rebron** 2021-07-23 20:38 UTC
Labels: OS/Desktop, feature-request
