### ISSUE TITLE
Blocking Geolocation API has no effect on private browsing

### ISSUE THREAD

**Issue by oldhen** [brave/brave-browser#28136] opened 2023-01-30 13:58 UTC
## Description 
In private browsing, when location is disallowed (either globally or per-site), browser still prompts to allow location when visiting sites.

## Steps to Reproduce

   1. Start private browsing
   2. Ensure "Don't allow sites to see your location" is selected in settings
   3. Visit site with geolocation, or run command `navigator.geolocation.getCurrentPosition(console.log)`

## Actual result:
Prompt appears, asking user to allow location query

## Expected result:
User should not be prompted

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Version 1.47.186 Chromium: 109.0.5414.119 (Official Build) (64-bit)
Windows 10

## Version/Channel Information:
Current release

## Other Additional Information:
When prompted, selecting to disallow location "Forever" takes effect for remainder of session, but is "forgotten" when browser is closed & restarted

## Miscellaneous Information:
N/A

**Comment by diracdeltas** [comment] 2023-01-31 21:05
cc @rebron @pes10k

**Comment by pes10k** [comment] 2023-02-01 16:49
This is intentional behavior, and something we've intentionally changed about upstream Chrome/Chromium.

In order to make sure a private window cannot learn about what a user does in the standard profile, we need to i) as completely-as-possible isolate the private window from the standard profile, and ii) start from a clean profile each time you start a new private session.

Chrome does not completely isolate the private browsing session, and allows the private browsing window to inherit certain settings from the main window (geolocation = block is one of those). The issue here is if a site in a private window is able to gather enough inherited or shared settings (or other side effects) they can probabilistically link a private window session with a normal-window session. 

Brave's change here reduces the chance of session linking by not inheriting or persisting permissions settings in private windows.  We think this is the right approach given Brave's security and privacy focus.

I'm going to close this as not a bug, but happy to discuss further if you'd like

**Closed by pes10k** 2023-02-01 16:49 UTC
Labels: OS/Desktop

**Comment by atlasshruggedbyaynrand** [comment] 2023-08-15 23:55
Wait, this is being done on purpose? I've had this annoying me for a while ever since google.com started asking for my location on most new sessions. This has to be the silliest Brave design decision and honestly I'll just go back to Chrome at this point. You can find many people complaining about this on other websites and are completely clueless about what's happening. I usually browse the web with my keyboard (Vimium) and pop-ups steal the page focus all the time. This is quite like being sent back to 2007 where things that you don't want on screen suddenly start popping up and there's little you can do about it.

This "probabilistic link" argument seems to be complete garbage. Would you care to explain how exactly an "attacker" could use that?

It is extremely easy to do browser fingerprinting in ways that the user can't avoid at all, and you don't even need to go as far as canvas fingerprinting. Have any of you seen an analytics dashboard? I run multiple websites and I'm tracking users every single day, *including* Brave users, and I can easily track their clicks, pages visited, time spent on each page, full IP, location and visit times, all using popular open-source software. This is is how most of the web is run. I'm pretty sure I could infer sleep/wake times from many of my users if I really wanted to. More nefarious actors, such as Meta/Facebook, will fingerprint you in ways that you'd need to alter and recompile your browser to avoid, but somehow not remembering my location options is a "privacy mechanism"? What?

What if I'm blocking all sites from seeing my location, which I would guess is the use case for most people affected by this? You screen/taskbar size is already leaking way more information than that.
