### ISSUE TITLE
Redirect IPFS resources to the configured gateway isn't working 

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#25405] opened 2022-09-14 15:50 UTC
![image](https://user-images.githubusercontent.com/106654560/190200494-e28c479e-81ae-4d83-90da-f75c7644ac59.png)
Seems this feature isn't working because there is no redirect for https://unstoppabledomains.mypinata.cloud/ipfs/QmTZ4vvV926DN2HwZpd8djLyovFptqk3Xbct71YwJxt28A

## Steps to Reproduce

   1. Enable the feature
   2. Disable DNSLink redirect feature(Cause it may also cause redirect)
   3. Load https://unstoppabledomains.mypinata.cloud/ipfs/QmTZ4vvV926DN2HwZpd8djLyovFptqk3Xbct71YwJxt28A

## Actual result:
Url is just loaded https://unstoppabledomains.mypinata.cloud/ipfs/QmTZ4vvV926DN2HwZpd8djLyovFptqk3Xbct71YwJxt28A

## Expected result:
Gateway url like localhost/ipfs/QmTZ4vvV926DN2HwZpd8djLyovFptqk3Xbct71YwJxt28A should be loaded

## Reproduces how often: 
100%

## Brave version (brave://version info)
1.45

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  Yes 
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards?  No 
- Is the issue reproducible on the latest version of Chrome? No

**Comment by stephendonner** [comment] 2022-09-14 20:07
Dupe of https://github.com/brave/brave-browser/issues/21454.

**Closed by stephendonner** 2022-09-14 20:07 UTC
Labels: bug, QA/Yes, release-notes/include, feature/ipfs, OS/Desktop
