### ISSUE TITLE
[Rewards] Reset settings UI is not working.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#38099] opened 2024-05-06 18:09 UTC
Brave Nightly (1.67.70 Chromium: 125.0.6422.26 (Official Build) nightly (64-bit)), but also reproduced in CR124 (1.67.66) by @GeetaSarvadnya:

1. Open Brave with profile where Rewards are enabled.
2. Navigate to brave://rewards/
3. Click Reset
4. In the popup try clicking the checkbox
**Expected result:**
Checkbox is checked, Reset button gets enabled
**Actual result:**
Checkbox is not checked

5. Try checking the box again, this time the box gets checked
**Expected result:**
Reset button gets enabled
**Actual result:**
Reset button stays disabled

This is not currently reproducible on Beta or Release.

cc: @zenparsing

**Comment by zenparsing** [comment] 2024-05-06 18:43
It looks like this was caused by a breaking change to the `Checkbox` component, which updates the `onChanged` [signature](https://github.com/brave/leo/pull/600).

**Comment by zenparsing** [comment] 2024-05-06 19:42
The following files use the `Checkbox` component, and may also be broken:

```
components/ai_chat/resources/page/components/feedback_form/index.tsx
components/brave_new_tab_ui/containers/newTab/settings/search.tsx
components/brave_rewards/resources/page/components/reset_modal.tsx
components/brave_wallet_ui/components/desktop/hardware-wallet-connect/hardware_wallet_connect.styles.ts
components/brave_wallet_ui/components/desktop/popup-modals/filter-modals/filter-components/filter-accounts-section.tsx
components/brave_wallet_ui/components/desktop/popup-modals/filter-modals/filter-components/network-chekboxes.tsx
components/brave_wallet_ui/page/screens/onboarding/network_selection/onboarding_network_selection.tsx
components/brave_wallet_ui/page/screens/onboarding/restore-from-recovery-phrase/restore-from-recovery-phrase.tsx
components/brave_wallet_ui/page/screens/send/components/ordinals-warning-message/ordinals-warning-message.tsx
```

**Comment by kjozwiak** [comment] 2024-05-07 03:54
There's also more context/STR re: the above being reproducible on `Android` via https://github.com/brave/brave-browser/issues/38112. Adding the `OS/Android` label as @deeppandya mentioned it's the same issue as the code is shared by both platforms.

**Comment by LaurenWags** [comment] 2024-05-07 11:47
cc @srirambv since a bunch of items mentioned in https://github.com/brave/brave-browser/issues/38099#issuecomment-2096777457 are for wallet and should be checked.

**Comment by zenparsing** [comment] 2024-05-07 12:17
The issue has been fixed on the Nala side at https://github.com/brave/leo/pull/657. 

@fallaciousreasoning what is the best way to get this fix in to brave-core? This issue only affects Nightly.

**Comment by fallaciousreasoning** [comment] 2024-05-07 23:17
https://github.com/brave/brave-core/pull/23246 is my PR updating Nala - mind reviewing?

I might get @bsclifton to have a look too, so we can merge faster

**Comment by fallaciousreasoning** [comment] 2024-05-07 23:17
If we don't get it merged before branching things will be more complicated :laughing:

**Comment by zenparsing** [comment] 2024-05-08 01:43
@fallaciousreasoning reviewed 👍  full speed ahead 🚀

**Comment by zenparsing** [comment] 2024-05-08 13:10
Fixed by https://github.com/brave/brave-core/pull/23246

**Closed by zenparsing** 2024-05-08 13:10 UTC
Labels: feature/rewards, priority/P2, QA/Yes, release-notes/exclude, QA/Test-Plan-Specified, regression, OS/Android, OS/Desktop

**Comment by kjozwiak** [comment] 2024-05-08 16:30
@zenparsing we'll probably want this uplifted into `1.66.x` as it's a recent regression that's affecting `release` as well. CCing @LaurenWags @Miyayes

**Comment by LaurenWags** [comment] 2024-05-17 19:43
Verification in progress with

```
Brave | 1.67.86 Chromium: 125.0.6422.60 (Official Build) beta (x86_64)
-- | --
Revision | a1f8e8f462d422d4b924fa9c34246f68862b21ad
OS | macOS Version 13.6.7 (Build 22G720)
```

**Comment by hffvld** [comment] 2024-05-21 22:08
### IN PROGRESS...

Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240426.022 release-keys
Brave build: 1.67.85 
Chromium: 125.0.6422.60 (Official Build) beta (64-bit) 
```
---------------------------
<details>
<summary> Clean profile - Unconnected </summary>

**STEPS:**
1. Install and launch Brave `1.67.x`
2. Close and relaunch Brave to pull Griffin
3. Join `Rewards`
4. View any ad, for example, a `notification` or `inline` ad
5. Tap `Reset` > Tap the checkbox
6. Tap `Reset` > Verify

**ACTUAL RESULTS:**
- Verified that the checkbox on the `Reset Brave Rewards` pop-up can be selected/deselected
- Verified that the actual `Reset` on the `Reset Brave Rewards` pop-up is working

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/5586f3ab-f9ab-4259-a789-c82170459544) | ![2](https://github.com/brave/brave-browser/assets/128532965/f279165a-1f12-43da-ae09-c844c80d09fc) | ![3](https://github.com/brave/brave-browser/assets/128532965/6fb66e01-9037-439b-a682-faece923a501) | ![4](https://github.com/brave/brave-browser/assets/128532965/43e4094e-e185-4a58-b3a6-2fc301cfdf33) |
</details>

<details>
<summary> Clean profile - Unconnected </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

<details>
<summary> Clean profile - Unconnected </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>
