### ISSUE TITLE
Browser Hangs when switching default shields setting 

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#39085] opened 2024-06-16 19:12 UTC
### Description

Switching from standard -> aggressive ad blocking caused very noticeable UI jank/freezes and a long series of ios reported hangs ranging from around 500ms to over 1s

Switching from aggressive back to standard triggered it again and then I think a third time, but after that I couldn't replicate and all of my background tabs seemed to be in an unloaded state

### Steps to reproduce

1. Change adblock default setting

### Actual result

UI janks/hangs and tabs reloaded/unloaded

### Expected result

Nothing should happen except changing the default setting. On desktop we do not reload/unload tabs when the default setting changes as this would be very disruptive

### Reproduces how often

Easily reproduced

### Brave version

1.67 (115)

### Device/iOS version

iphone 15 pro

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by iccub** [comment] 2024-06-19 18:05
Duplicate of https://github.com/brave/brave-browser/issues/39117

**Closed by iccub** 2024-06-19 18:05 UTC
Labels: OS/iOS
