### ISSUE TITLE
chrome://settings/searchEngines do not display correctly

### ISSUE THREAD

**Issue by onplus** [brave/brave-browser#3714] opened 2019-03-14 11:35 UTC
## Actual result:

settings-brave-default-extensions-page
![image](https://user-images.githubusercontent.com/31188782/54353626-78a72b80-468f-11e9-9374-ce5473007297.png)

## Brave version (brave://version info)

0.61.51 Chromium: 73.0.3683.75
Windows 10 OS Build 17763.379

**Comment by rebron** [comment] 2019-03-16 04:29
Dupe of https://github.com/brave/brave-browser/issues/3444

**Closed by rebron** 2019-03-16 04:29 UTC
