### ISSUE TITLE
Fails loading chedder.com article on Nightly with Shield activated

### ISSUE THREAD

**Issue by chkk525** [brave/brave-browser#5713] opened 2019-08-19 07:39 UTC
## Description 

Fails loading chedder.com article and shows blank page.

## Steps to Reproduce

1. Open an article i.e https://cheddar.com/media/portland-mayor-to-hate-groups-we-don-t-want-you-here
2. Wait for page load (or scroll a little to bottom)
3. Screen turn into blank

Notes
## Actual result:

![ダウンロード](https://user-images.githubusercontent.com/3054915/63247348-cd367e80-c29f-11e9-8f12-b2597d4ad5b4.gif)

## Reproduces how often: 

- Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release?
No
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment] 2019-08-30 16:30
@chkk525 Can you add the version of nightlies that you're seeing this in. I can't reproduce in current nightly with shields up. Version 0.71.44 Chromium: 76.0.3809.132 (Official Build) nightly (64-bit)

**Comment by chkk525** [comment] 2019-09-03 11:33
@rebron 
Brave | 0.71.56 Chromium: 76.0.3809.132 (Official Build) nightly （64 ビット）
I reproduced it right now...

**Comment by kjozwiak** [comment] 2019-10-07 05:10
@chkk525 are you still able to reproduce this on the latest `Nightly`? There was a lot of work that went into Brave Shields plus a major Chromium bump. I couldn't reproduce using `0.72.72 Chromium: 77.0.3865.90 (Official Build) nightly`.

**Comment by ryanbr** [comment] 2020-01-22 22:51
Seems okay now? can @chkk525 confirm ?

**Comment by chkk525** [comment] 2020-01-26 12:36
seems okay now @ryanbr

**Comment by ryanbr** [comment] 2020-03-07 02:04
Okay closing this.

**Closed by ryanbr** 2020-03-07 02:04 UTC
Labels: webcompat
