### ISSUE TITLE
where is "brave://settings/clearBrowserData" ??

### ISSUE THREAD

**Issue by usernamer-git** [brave/brave-browser#28261] opened 2023-02-02 19:42 UTC
## Description 

Can't find the options to clear cookies,history,etc...
Where is "brave://settings/clearBrowserData" ??
Why remove essential features??

## Steps to Reproduce

   1. into your address bar: "brave://settings/clearBrowserData"
   2. Shortcut: Ctrl+Shift+Del

## Actual result:

Just show Tor options session

## Expected result:
Show options to clear browser data, cookies, history ...
https://support.brave.com/hc/en-us/articles/360048833872-How-Do-I-Clear-Cookies-And-Site-Data-In-Brave-
https://www.whatismybrowser.com/guides/clear-cache-history-cookies/brave

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

Versão 1.48.154 Chromium: 110.0.5481.52 (deb 64 bits)

## Android Device details:
   - Install type (ARM, x86): arm
   - Device type (Phone, Tablet, Phablet): phone
   - Android version: 11

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? no tested
- Can you reproduce this issue with the nightly channel? no tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no tested

**Comment by stephendonner** [comment] 2023-02-02 22:03
Confirming, using 

Brave | 1.48.154 Chromium: 110.0.5481.52 (Official Build) (x86_64)
-- | --
Revision | 979113183ded4544a2c443aceb1629c430907e52-refs/branch-heads/5481@{#636}
OS | macOS Version 11.7.3 (Build 20G1116)

I see this on `brave://settings/privacy`, too, where whole section(s) are missing.

<img width="1312" alt="Screen Shot 2023-02-02 at 1 58 31 PM" src="https://user-images.githubusercontent.com/387249/216459189-7170c7ed-da43-4240-a83c-1542963ed72d.png">

This apparently doesn't reproduce on `1.48.149`.

**Comment by stephendonner** [comment] 2023-02-02 22:04
@usernamer-git thank you for filing; we'll get this fixed ASAP!

/cc @rebron @kjozwiak @mkarolin @emerick

**Comment by stephendonner** [comment] 2023-02-02 22:18
This exception is thrown in the dev console:

`Uncaught Error: Assertion failed: Could not find value for isGoogleSignInFeatureEnabled
    at assert (assert_ts.js:15:11)
    at LoadTimeData.getValue (load_time_data.js:47:9)
    at LoadTimeData.getBoolean (load_time_data.js:134:28)
    at settings-privacy-page (settings.js:2420:1441)
    at addBraveTemplateModifications (shared.rollup.js:141:1037)
    at SettingsPrivacyPageElement.BravePolymer_PrepareTemplate (shared.rollup.js:141:6516)
    at SettingsPrivacyPageElement._finalizeClass (polymer_bundled.min.js:1:47261)
    at SettingsPrivacyPageElement.finalize (polymer_bundled.min.js:1:44964)
    at SettingsPrivacyPageElement._initializeProperties (polymer_bundled.min.js:1:48728)
    at new <anonymous> (polymer_bundled.min.js:1:16820)
`

cc @ShivanKaul

**Comment by kjozwiak** [comment] 2023-02-03 08:27
Closing

**Closed by kjozwiak** 2023-02-03 08:27 UTC
Labels: bug, privacy, release/blocking, priority/P1, QA/Yes, QA/Test-Plan-Specified, regression, OS/Android, OS/Desktop, QA/Test-All-Platforms

**Comment by LaurenWags** [comment] 2023-02-03 13:30
Verified with

```
Brave | 1.48.155 Chromium: 110.0.5481.77 (Official Build) (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 12.6.3 (Build 21G419)
```

Confirmed "Privacy and security" section is displayed as expected under brave://settings/privacy.
Confirmed no assertion in devtools console.
Confirmed able to open and display "Clear browsing data" modal from this section.
Confirmed able to navigate to "Clear browsing data" modal directly from URL bar by entering brave://settings/clearBrowserData.
Confirmed able to navigate to "Clear browsing data" modal directly by using cmd+shift+del (on macOS).


Example | Example | Example
---- | ---- | ----
<img width="1401" alt="1" src="https://user-images.githubusercontent.com/28145373/216615085-85487284-ee46-4f09-a2d9-415dd1c73c9b.png"> | <img width="1798" alt="2" src="https://user-images.githubusercontent.com/28145373/216615086-98403ced-51e8-4466-ba16-cd0117f6f92a.png"> | <img width="1400" alt="3" src="https://user-images.githubusercontent.com/28145373/216615089-29c74050-820f-43da-aacd-9cf76f7f5cbc.png">

**Comment by LaurenWags** [comment] 2023-02-03 16:09
Removed `QA/Test-All-Platforms` label per discussion with @kjozwiak @rebron

**Comment by stephendonner** [comment] 2023-02-07 00:04
I checked on `Brave` `1.48.154`, `Chromium` `110.0.5481.52` on a `Google Pixel XL` (`arm64`) running `Android 9`, and couldn't reproduce the issue - likely Android doesn't use this code.

Also checked with `1.48.157`, `Chromium`, `110.0.5481.77`, and couldn't reproduce any problems

Removing `OS/Android`

example | example | example | example | example
---------|---------|-----------|---------|---------
![Screenshot_20230206-155846](https://user-images.githubusercontent.com/387249/217114476-07cb75fd-94aa-4b24-a1fa-c54ed4c93b23.png) | ![Screenshot_20230206-155854](https://user-images.githubusercontent.com/387249/217114479-d125b216-bb57-4ecf-8266-b22a012a5367.png) | ![Screenshot_20230206-155900](https://user-images.githubusercontent.com/387249/217114481-ec2eafae-e984-4c6b-9631-ae2fe3478ce4.png) | ![Screenshot_20230206-155917](https://user-images.githubusercontent.com/387249/217114482-67ae5f2e-2a74-40a2-b0bb-e45f00265b94.png) | ![Screenshot_20230206-160157](https://user-images.githubusercontent.com/387249/217114485-89d4420b-4e12-43cf-86e9-6c63aa7e75bd.png)
