### ISSUE TITLE
Custom OpenSearch engine not being picked up on Brave Android

### ISSUE THREAD

**Issue by TheFireKahuna** [brave/brave-browser#13254] opened 2020-12-18 21:59 UTC
## Description
On Android, going directly with to the base URL of a OpenSearch based engine and then searching with it (either the word 'time', or '%s', does not lead to the site reliably being shown in the custom search options of Brave.

## Steps to reproduce 
   1. Go to either https://suche.uferwerk.org/ or https://searx.be/ and search any term
   2. Return after to the Search Engine options of either type

## Actual result 
Does not appear in the list

## Expected result
Appears in the list

## Issue reproduces how often
Consistently

## Version/Channel Information:
- Can you reproduce this issue with the current Play Store version? 
Issue appears on the current mainline app.

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy Note 8
   - Android version: 9.0 (Pie)
   
## Brave version
1.17.75

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

### Additional info
Works fine on Windows.

**Comment by nullpenguinexception** [comment] 2021-09-27 08:24
A year passed, still no improvements.

**Comment by catfluoride** [comment] 2021-11-23 09:19
I need to bump this. I'm experimenting the same issue on latest Android stable (1.32.106) or beta.

In mu humble opinion, allowing to input search engine strings would be a better solution, rather than expecting Brave to guess by itself.

**Comment by TBDwarf** [comment] 2021-11-23 19:27
Same problem with SearX !

**Comment by K33k0** [comment] 2023-09-25 18:13
Having the same issue trying to add Searxng which looking at the [documentation](https://github.com/searxng/searxng/blob/1df4588279aba55b40010e286191dcf4518ffd16/searx/infopage/en/about.md?plain=1#L32) definitely supports opensearch

**Comment by bsclifton** [comment] 2024-05-07 19:22
Closing as duplicate of https://github.com/brave/brave-browser/issues/38129

**Closed by bsclifton** 2024-05-07 19:22 UTC
Labels: needs-investigation, feature/search, OS/Android
