### ISSUE TITLE
The Brave rewards extension menu uses variable names instead of plain English

### ISSUE THREAD

**Issue by PopeRigby** [brave/brave-browser#1510] opened 2018-10-11 00:49 UTC
## Description 

The Brave rewards extension menu uses variable names instead of plain English.

## Steps to Reproduce

   1. Open Brave rewards extension menu
   2. Observe

## Actual result:

The Brave rewards extension menu shows variable names ([Screenshot](https://photos.app.goo.gl/Ckaediic7tfrGjDT9))

## Expected result:
The Brave rewards extension menu shows plain English

## Reproduces how often: 

Easily reproduced

## Brave version (chrome://version info)

- 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)

- cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}

- Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
**Yes**
- Does it reproduce on browser-laptop? 
**No**

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?
**No**
- Is the issue reproducible on the latest version of Chrome? 
**No**

**Comment by srirambv** [comment] 2018-10-11 02:08
Dupe of https://github.com/brave/brave-browser/issues/1424

**Closed by srirambv** 2018-10-11 02:08 UTC
