### ISSUE TITLE
Brave cloud print message needs to be removed Follow up to #1279

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1527] opened 2018-10-11 14:30 UTC
## Description 

Brave cloud print message needs to be removed from Print dialogue

## Steps to Reproduce

   1. Open any page and press <kbd>Ctrl</kbd>+<kbd>P</kbd>
   2. Brings up the print dialogue
   3. Click on Change to select available printers
   4. Device page shows Cloud print and has a sign in button which tries to connect to `no-thanks.invalid` 

## Actual result:

![cloudprint](https://user-images.githubusercontent.com/17010094/46811317-82271300-cd40-11e8-9bea-f112c02daa48.gif)

## Expected result:
Should remove the entire bottom div which contains that message

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)  
-- | -- 
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes
- Does it reproduce on browser-laptop? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment] 2018-10-11 14:37
There is a close button at the end which closes it but we should hide the entire message itself and not give an option to close it

**Comment by petemill** [comment] 2018-10-11 20:20
If the user is already installed to some google services, this message doesn't show and somehow the print preview dialog knows. Is that a concern @bbondy ?

![image](https://user-images.githubusercontent.com/741836/46831448-54e65f00-cd58-11e8-8293-ee37934ab7e1.png)

**Comment by petemill** [comment] 2018-10-12 05:30
Confirmed that we want to remove the signed-in state feature too: Removing the dropdown and label. Should add a test plan for this state:
- Sign in to google
- Visit print preview
- Change printer
- Confirm signed-in google accounts do not show in a list

**Comment by rebron** [comment] 2018-10-12 14:33
Related https://github.com/brave/brave-browser/issues/1402 but don't want to blow out the scope of this issue. Let's remove what we can.

**Comment by petemill** [comment] 2018-10-15 17:38
Duplicate of https://github.com/brave/brave-browser/issues/1402 which covers more detail

**Closed by petemill** 2018-10-15 17:38 UTC
Labels: QA/Yes, about-pages/rebrand, bug

**Comment by srirambv** [comment] 2018-10-17 03:01
Verification Passed on 

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

* Verified Cloud print message is not shown when user is not signed into any Google service in a tab
![image](https://user-images.githubusercontent.com/17010094/47059434-5a4c0b00-d197-11e8-9e9d-b072c7110f6b.png)
