### ISSUE TITLE
ring.com flagged as mistyped bing.com

### ISSUE THREAD

**Issue by alexwykoff** [brave/brave-browser#4415] opened 2019-05-13 05:59 UTC
## Description 
From the field : User reports that visiting ring.com gives a redirect page suggesting bing.com
https://twitter.com/VuongN/status/1126898812126158848

## Steps to Reproduce

   1. visit ring.com

## Actual result:
A page suggesting bing.com is displayed. Clicking on 'ignore' sends user to the appropriate page.

## Expected result:
Ring.com should naturally display.

## Reproduces how often: 
100%

## Brave version (brave://version info)
I repro'd in nightly. I believe user discovered in prod.

## Version/Channel Information:

- Can you reproduce this issue with the current release? I believe user did this.
- Can you reproduce this issue with the beta channel? Didn't check yet.
- Can you reproduce this issue with the dev channel? Didn't check yet.
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A this is basic nav
- Does the issue resolve itself when disabling Brave Rewards? N/A this is basic nav
- Is the issue reproducible on the latest version of Chrome? No. Chrome works fine.

**Comment by bsclifton** [comment] 2019-05-13 06:08
Closing as dupe of https://github.com/brave/brave-browser/issues/4304

**Closed by bsclifton** 2019-05-13 06:08 UTC
Labels: feature/shields/webcompat, needs-investigation
