### ISSUE TITLE
Print recovery key page becomes unresponsive

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3132] opened 2019-01-28 13:15 UTC
## Description 

Print recovery key page becomes unresponsive

## Steps to Reproduce

   1. Clean profile 0.59.30
   2. Enable Rewards
   3. Click on Settings->Backup->Print

## Actual result:

Click on Print keeps loading the page, at somepoint page becomes unresponsive. Click on `Exitpages` in Unresponsive popup causes webview crash.

![image](https://user-images.githubusercontent.com/38657976/51838269-cd832280-232b-11e9-92e9-0a742e30a3ee.png)

Click on `Exitpages`

![image](https://user-images.githubusercontent.com/38657976/51838423-3e2a3f00-232c-11e9-96de-4c5dacde4f57.png)

Webview Crash: Please note, I am not getting uploaded crash report id's, hence providing only local id

![image](https://user-images.githubusercontent.com/38657976/51838490-6d40b080-232c-11e9-94d0-7b90d826654f.png)

## Expected result:
No webview crash, page should be responsive

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.59.30 Chromium: 72.0.3626.71 (Official Build) (64-bit)
-- | --
Revision | f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional Information

@brave/legacy_qa

**Comment by kjozwiak** [comment] 2019-01-28 20:47
I can't reproduce this 100% of the time but managed to get it in the state @GeetaSarvadnya mentioned above a few times.

`macOS 10.14.2 x64` using `0.59.31 Chromium: 72.0.3626.71`:

* https://stats.brave.com/dashboard#crash/5c4f640a860db0001f7db836

`Win 10 x64 VM` using `0.59.31 Chromium: 72.0.3626.71`

* https://stats.brave.com/dashboard#crash/5c4f5ce791550e001fdf2ea5
* https://stats.brave.com/dashboard#crash/5c4f5ce6860db0001f7d7dd1

**Comment by srirambv** [comment] 2019-01-29 06:54
I kind of reproduced this on Linux but have to wait for like 3-4 mins for that popup window to show up. It could be due to the fact that the print dialogue opens up an `about:blank` page which is in a loading loop state so might need to be verified on older release builds as well.

**Comment by kjozwiak** [comment] 2019-01-29 07:42
> I kind of reproduced this on Linux but have to wait for like 3-4 mins for that popup window to show up. It could be due to the fact that the print dialogue opens up an `about:blank` page which is in a loading loop state so might need to be verified on older release builds as well.

yup, took me a while to reproduce as well. I managed to reproduce it once within ~1min but the remaining times I needed to wait at least ~5min or even more. Sometimes I would even wait 10-20min without reproducing.

**Comment by srirambv** [comment] 2019-01-29 07:44
To be honest I feel the print option is kind of redundant here. User would either copy and paste it in their notes or just save the file. Printing (even to a pdf) would probably be the least used option. 

_Go green stop printing_

**Comment by jasonrsadler** [comment] 2019-03-30 15:49
@kjozwiak @srirambv @GeetaSarvadnya Having problems reproducing on 0.64.x/0.65.x. Does this still happen on latest release version?

**Comment by GeetaSarvadnya** [comment] 2019-04-03 05:28
@jasonrsadler Issue is not Reproducible. Verified on below brave versions.

`0.61.52` - Not Reproducible
`0.62.50` - Not Reproducible
`0.64.30` - Not Reproducible
`0.64.10` - Not Reproducible
`0.59.34` and `0.59.35` - Not Reproducible

**Comment by kjozwiak** [comment] 2019-04-03 05:43
Thanks for checking @GeetaSarvadnya :+1: Lets close this off for now and re-open if we run into this again.

**Closed** 2019-04-03 05:44 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, priority/P3
