### ISSUE TITLE
Follow up of #2400 - Shields settings is lost after clearing data and relaunching 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8813] opened 2020-03-23 13:28 UTC
## Description 

Found while testing #2400

Follow up of #2400 - Shields settings is lost after clearing data and relaunching 
## Steps to Reproduce

   1. Visit brave.com and disable shields
   2. Visit github.com and change site shields settings from default to custom
   3. Clear browsing data from all time and select all checkboxes
   4. Restart browser after data is cleared
   5. Open brave.com, shields is auto-enabled
   6. Open github.com, site shields settings are lost and reverted back to default settings

## Actual result:

Shields settings is lost after clearing data and relaunching

## Expected result:
Clear data shouldn't reset shields settings

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.7.67 Chromium: 80.0.3987.149 (Official Build) beta (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @simonhong @tomlowenthal @diracdeltas @bbondy

**Comment by btlechowski** [comment] 2020-03-23 15:51
Test plan from original fix(https://github.com/brave/brave-core/pull/4361) mentions a new setting in `Clear browsing data`. It is missing.

Brave | 1.7.70 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/77335508-870a3780-6d26-11ea-9b2c-59ef0aff85c3.png)

**Comment by abh-oss01** [comment] 2020-03-24 02:25
is it fixed now?
did u commit?

**Comment by bridiver** [comment] 2020-03-24 15:59
This is the correct behavior and is a duplicate of https://github.com/brave/brave-browser/issues/2400

**Closed by bridiver** 2020-03-24 15:59 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/shields, priority/P2

**Comment by bridiver** [comment] 2020-03-24 16:00
I also updated the status to closed/invalid because this is the correct and expected behavior. The labels have been updated to make that clear.

**Comment by abh-oss01** [comment] 2020-03-24 16:15
it clearly said "follow up"

**Comment by abh-oss01** [comment] 2020-03-24 16:16
@bridiver it clearly said "follow up"

**Comment by GeetaSarvadnya** [comment] 2020-03-24 16:16
https://github.com/brave/brave-browser/issues/2400#issuecomment-603330357 - Closing this as the issue in invalid
