### ISSUE TITLE
Brave Beta doesn't import settings from Brave Stable

### ISSUE THREAD

**Issue by jt1122zz** [brave/brave-browser#21752] opened 2022-03-18 12:54 UTC
## Description 
Brave Beta doesn't detect existing settings from a Brave Stable (Sparky Linux).

## Steps to Reproduce
   1. Install Brave stable.
   2. Define bookmarks.
   3. Install Brave Beta.
   4. Import bookmarks->detects Chromium, Firefox settings but amazingly not the Brave stable settings.

## Actual result:
Cannot import settings.

## Expected result:
To be able to import bookmarks + passwords + everything else defined in the stable install.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Beta 1.37.92

## Version/Channel Information:
Unknown

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by rebron** [comment] 2022-03-18 16:46
Closing as duplicate of https://github.com/brave/brave-browser/issues/1357

**Closed by rebron** 2022-03-18 16:46 UTC
Labels: OS/Desktop
