### ISSUE TITLE
dark text on inactive tabs when dark mode is enabled or when in incognito

### ISSUE THREAD

**Issue by Nicodemus111** [brave/brave-browser#22188] opened 2022-04-09 05:33 UTC
## Description 
the text is unreadably dark on incognito tabs and regular tabs when the default brave dark theme is enabled. chrome web store themes work properly.

## Steps to Reproduce
im not really sure how to reproduce it but it might just happen when you update it to the latest version on windows 10.

## Actual result:
![image](https://user-images.githubusercontent.com/96658552/162557232-a540828b-9fc7-4f08-8af1-c21254819e9b.png)
![image](https://user-images.githubusercontent.com/96658552/162557293-b6ebeb96-a2bf-4710-b9ca-aedc25aa276b.png)

## Expected result:
white text instead of black.

## Reproduces how often: 
always reproduces.

## Version/Channel Information:
1.37.111 Chromium: 100.0.4896.79 (Official Build) (64-bit) 
8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
Windows 10 Version 21H1 (Build 19043.1586)

found on latest release channel version and latest nightly version.

## Other Additional Information:
the same update is the one that made the download progress wheel my windows theme color so it might be something to do with windows themes. 

## Miscellaneous Information:
i do have 7ztsp and ultra ux theme patcher installed as well as curtains installed so those might be affecting it but disabling my custom theme doesnt affect it so those could also be unrelated. i had all of this software installed before the update.

**Comment by rebron** [comment] 2022-04-11 22:49
Closing as dupe of https://github.com/brave/brave-browser/issues/22027 Thanks for the report. Fixed and will be part of the next release this week.

**Comment by Nicodemus111** [comment] 2022-04-11 22:50
thank you!

**Closed by rebron** 2022-04-11 22:49 UTC
Labels: OS/Desktop
