### ISSUE TITLE
Prevent connection to gstatic at startup

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1715] opened 2018-10-18 19:37 UTC
## Description 

Prevent connection to gstatic at startup

## Steps to Reproduce

   1. Launch new profile
   2. Use Charles Proxy to capture network events
   3. gstatic shows up which should have been blocked with #1684 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/47179238-95f7e980-d2eb-11e8-9c61-b3407572e362.png)

## Expected result:
All gstatic links should be blocked

## Reproduces how often: 

Easy 

## Brave version (brave://version info)

Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment] 2018-10-18 19:41
Reproduced on Windows 7 x64.

Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 7 x64

![image](https://user-images.githubusercontent.com/34715963/47179537-99589880-d31e-11e8-872c-74489ef55d84.png)

**Comment by diracdeltas** [comment] 2018-10-18 19:50
@mihaiplesa is already working on this AFAIK. the problem is that https://static1.brave.com/chrome/config/plugins_3/plugins_mac.json 301's to gstatic instead of proxying.

**Comment by mihaiplesa** [comment] 2018-10-18 19:58
@diracdeltas @bkero is back on it

**Comment by diracdeltas** [comment] 2018-10-18 21:09
appears to be fixed

**Comment by bbondy** [comment] 2018-10-18 21:30
Closing given last comment. Thanks.

**Closed by bbondy** 2018-10-18 21:30 UTC
Labels: bug, privacy

**Comment by btlechowski** [comment] 2018-10-19 15:14
Verification passed on

Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 7 x64

Brave no longer connects to gstatic.com

![image](https://user-images.githubusercontent.com/34715963/47227095-4c2e0280-d3c2-11e8-96b0-42aa80475082.png)
