### ISSUE TITLE
Shortcuts are broken in Brave Dev 0.62.11

### ISSUE THREAD

**Issue by Cyvet** [brave/brave-browser#3540] opened 2019-03-01 09:54 UTC
## Description 
Shortcuts, created in More tools > Shortcuts > Open in new window are not able to open on themselves anymore.
When added to the windows start menu in folder Brave Apps, clicking this shortcut does nothing anymore, while a week ago this was possible.

## Steps to Reproduce

   1. More Tools > Create Shortcut > Open as new window
   2. Close Brave
   3. Click this shortcut in windows startmenu > brave apps **Nothing happens**

## Brave version (brave://version info)
0.62.11 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)
Windows OS version 1903 18346.1

### Reproducible on current release:
Brave Browser Dev

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No, All websites in shortcuts don't work
- Is the issue reproducible on the latest version of Chrome?  Latest Chrome Canary Does not have this issue.

**Comment by rebron** [comment] 2019-03-01 19:37
@rebron These shortcuts are for webapps that we and chrome are not supporting. Note to myself to file a separate issue to remove "Create Shortcuts" from More Tools menu.

**Comment by bsclifton** [comment] 2019-03-19 20:15
@rebron can we close this issue? (in favor of an issue to remove `Create Shortcuts`?)

**Comment by theNailz** [comment] 2019-03-21 08:15
@rebron Could you elaborate on "These shortcuts are for webapps that we and chrome are not supporting."? I can't find any recent posts about this; only that the checkbox "Open as window" had been removed from Chrome ~v69 and restored in v72.

How is opening a tab in a new window a web app that's different from a regular web page?

**Comment by GauthamVarmaK** [comment] 2019-03-26 04:56
This issue exists in other builds of Brave as well.

> @rebron Could you elaborate on "These shortcuts are for webapps that we and chrome are not supporting."? I can't find any recent posts about this; only that the checkbox "Open as window" had been removed from Chrome ~v69 and restored in v72.
> 
> How is opening a tab in a new window a web app that's different from a regular web page?

Opening in a new window is nothing but a PWA (Progressive Web Applications are web applications that load like regular web pages or websites but can offer the user functionality such as working offline, push notifications, and device hardware access traditionally available only to native applications)

@rebron Can you close this issue as it is a duplicate of #3750 (https://github.com/brave/brave-browser/issues/3750)

**Comment by rebron** [comment] 2019-03-26 06:27
Closing. Dupe of #3750. Was previously thinking we needed to remove the shortcut but we should match working behavior in Chrome.

**Closed by rebron** 2019-03-26 06:27 UTC
