### ISSUE TITLE
Brave shields panel has blank area on right on Windows

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#683] opened 2018-08-03 16:21 UTC
## Description 

In the current master, the Brave shields panel has a blank area on its right side on Windows. It looks like the width of a scrollbar element, although that may just be coincidental.

## Steps to Reproduce

1. Start Brave on Windows
2. Click the Brave shields icon
3. Look at the shields panel

## Actual result:
![image](https://user-images.githubusercontent.com/5033691/43653845-56512086-9717-11e8-92a7-5a2767b55143.png)

## Expected result:

Same as above, but without the whitespace on the right.

## Reproduces how often: 
100% of the time for me.

## Brave version (about:brave info) 
Brave	0.54.0 Chromium: 69.0.3497.12 (Developer Build) (64-bit) 
Revision	e8e14b69c41a5a461c15fa5d1065ec28c49890ac-refs/branch-heads/3497@{#54}
OS	Windows
JavaScript	V8 6.9.427.5
Flash	(Disabled)
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.12 Safari/537.36
Command Line	"c:\work\brave-browser\src\out\debug\brave.exe" --enable-tab-audio-muting --disable-domain-reliability --disable-chrome-google-url-tracking-client --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select --flag-switches-begin --flag-switches-end
Executable Path	c:\work\brave-browser\src\out\debug\brave.exe
Profile Path	C:\Users\emerick\AppData\Local\BraveSoftware\Brave-Browser-Development\User Data\Default
Variations	AccountConsistencyVariations:DiceMigration
AdFramePriority:LowPriorityAdFrameEnabled
AudioService:AudioProcess_LaunchOnStartup_v3
AutofillDynamicForms:Enabled
AutofillFieldMetadata:Enabled
AutofillResetFullServerCardsOnAuthError:Enabled
AutofillSmallFormSupport:Enabled
AutomaticTabDiscarding:Enabled_Once_10‑gen2
BackgroundPagePriority:LowPriorityEnabled
BackgroundVideoOptimizations:BackgroundOptimizationEnabled1sOrLessMediaSource
BetterMultiTabsLoading:PageAlmostIdleSignalEnabled2
BlinkSchedulerDedicatedWorkerThrottling:Enabled
BlinkSchedulerHighPriorityInputOnCompositorThread:Enabled
BlockTabUnders:Enabled
BookmarkInProductHelp:Enabled_1
BrowserBlacklist:Enabled
BrowserScheduler:RedirectWithDefaultInitParams
BundledConnectionHelp:HTTPHelpCenterEnabled
CSSExternalScanner:Enabled_ScanAndPreload
CertificateTransparencyLogAuditing:Enabled
DataReductionProxyRobustConnection:Enabled
DefaultBrowserInfobar:SettingsTextNotNow
DefaultEnableGpuRasterization:DefaultEnableGpuRasterization
DefaultPassthroughCommandDecoder:DefaultPassthroughCommandDecoder
DelayRequestsOnMultiplexedConnections:Enabled
DynamicExpectCT:DynamicExpectCTEnabled
EmitGoogleSearchDomainMixingMetrics:Enabled
EnableAppContainer:Enabled
EnableCastDiscovery:Enabled
EnableCsrssLockdown:Enabled
ExtensionContentVerification:EnforceStrict
ExtensionInstallVerification:Enforce
FrameAndTaskTypePriorityDuringLoading:LowPriorityForHiddenFrameDuringLoading
GuestViewCrossProcessFrames:Enabled
HTTPBadPhase3:NotSecureWarning
Html5ByDefault:Enabled
ImprovedRecoveryComponent:ImprovedRecoveryComponent
IncognitoWindowInProductHelp:Enabled
InstanceID:Enabled
LocalScreenCasting:Enabled
LowPriorityIframes2:Enabled
MediaFoundationH264Encoding:Enabled
ModernMediaControls:Enabled
NTPBirthdayFeatures:NewTabPageAllBirthday_Enabled
NTPUseGoogleLocalNtp:Enabled
NativeCrxBindings:Enabled
NativeNotifications:Enabled
NetworkQualityEstimator:Enabled
NewTabInProductHelp:Enabled_1
NoSearchDomainCheck:Enabled
OmniboxBundledExperimentV1:DesktopExperiments
OverflowIconsForMediaControls:Enabled
PWAFullCodeCache:Enabled
PassiveDocumentEventListeners:Enabled
PassiveEventListenersDueToFling:Enabled
PasswordProtectionForEnterprise:V1Enabled
PermissionPromptUIViews:BlockPromptsEnabled
PersistentHistograms:EnabledOnDisk5
QUIC:Enabled
RendererSchedulerWakeUpThrottling:RendererSchedulerWakeUpThrottling
ReportingAPIAndNetworkErrorLogging:ReportingAndNELEnabled
ResourceLoadScheduler:Enabled_bg_limit_3_2
SafeBrowsingAdSamplerTrigger:AdSampler_NormalRate
SafeBrowsingSuspiciousSiteTrigger:Enabled
SafeBrowsingThreatDomDetailsTagAttributes:AdIdentifiers
SavePreviousDocumentResources:until‑dcl
ScrollAnchorSerialization:Enabled
ServiceWorkerPaymentApps:Enabled
ServiceWorkerScriptFullCodeCache:Enabled
SettingsEnforcement:enforce_always_with_extensions_and_dse
SettingsResetPrompt:Enabled
SimplifyHttpsIndicator:EvToSecure
SitePerProcess:SitePerProcess_Enabled
SocketReadIfReady:Enabled
StabilityDebugging:Enabled
TLS13Variant:Draft23V4
ThrottleDelayable:MaxDelayable_v1_3g_15_Weight3
TokenBinding:TokenBinding
TranslateRankerModel:20180123_launch
TranslateUserEvents:Enabled
TriggeredResetFieldTrial:On
UKM:Enabled
UseHeuristicLanguageModel:Experiment
V8AsmJSToWasm:AsmJsToWebAssembly
V8CacheInlineScriptCode:CacheInlineScriptCode
V8ContextSnapshot:Enabled
VideoCaptureService:Enabled2
VideoSurfaceLayer:Enabled
VizHitTestDrawQuad:Enabled
VsyncAlignedInput:Enable
WorkStealingInScriptRunner:Enabled2
Linker	lld-link

### Reproducible on current release:
I didn't check, this is on master.

**Comment by srirambv** [comment] 2018-08-03 16:34
Dupe of https://github.com/brave/brave-browser/issues/222 😄

**Closed by srirambv** 2018-08-03 16:34 UTC
