### ISSUE TITLE
[Desktop] Unable to remove allow cookie policy entries

### ISSUE THREAD

**Issue by Geordon** [brave/brave-browser#10532] opened 2020-07-01 04:46 UTC
## Description 
Unable to remove entries in brave://settings/content/cookies -> Allow

## Actual result:

Nothing happens when clicking on the garbage can icon

## Expected result:

Clicking on garbage can should remove the entry

## Reproduces how often: 
every time

## Brave version (brave://version info)

Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.15.5 (Build 19F101)

<img width="1335" alt="Screen Shot 2020-06-30 at 11 10 55 PM" src="https://user-images.githubusercontent.com/5634184/86203680-337c6680-bb2b-11ea-8ebb-92405e4851e0.png">

**Comment by dentistformyeye** [comment] 2020-07-02 15:45
Duplicate of #8604

**Comment by Geordon** [comment] 2020-07-02 20:54
Thank you.

**Closed** 2020-07-07 06:57 UTC
Labels: OS/Desktop
