### ISSUE TITLE
macOS Big Sur icon sizing incorrect

### ISSUE THREAD

**Issue by karlnippoldt** [brave/brave-browser#16771] opened 2021-07-03 07:55 UTC
The size of the Brave icon on macOS Big Sur is inconsistent with other apps, showing up a bit larger than it should.

![Screen Shot 2021-07-03 at 12 53 04 AM](https://user-images.githubusercontent.com/7821608/124347374-45a73f80-db99-11eb-929b-c972ab6aeb79.png)

**Comment by rebron** [comment] 2021-07-06 16:31
Closing as duplicated/wontfix https://github.com/brave/brave-browser/issues/14801 
Size is as intended and matches other apps.

**Closed by rebron** 2021-07-06 16:31 UTC
Labels: OS/Desktop
