### ISSUE TITLE
vertical lines overlapping under `brave://settings/appearance` in `Tabs` section

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#30100] opened 2023-05-02 23:37 UTC
## Description 

It's really hard to see but looks like there's two small vertical lines that are overlapping the other vertical lines via `brave://settings/appearance` under the `Tabs` section. See screenshot for example of the issue.

## Steps to Reproduce

   1. ensure that `vertical` tabs are enabled on your channel (enable `brave://flags/#brave-vertical-tabs` if not)
   2. go into `brave://settings/appearance` and notice the issue (see screenshot for an example)

## Actual result:

![bugSettings](https://user-images.githubusercontent.com/2602313/234990852-ee4d237e-cc51-43ce-ad03-7b92cc12720e.png)

## Expected result:

It should be a single vertical line so it looks cleaner and not like we're stacking multiple vertical lines in one area.

## Reproduces how often: 

100% reproducible when using the STR/Cases outlined above.

## Brave version (brave://version info)

```
Brave | 1.53.13 Chromium: 113.0.5672.63 (Official Build) nightly (64-bit)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes` (once `1.51.x` goes out which is tomorrow)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @rebron @brave/qa-team

**Comment by rebron** [comment] 2023-05-03 07:46
cc: @fallaciousreasoning @aguscruiz

**Comment by joshuakatt** [comment] 2023-07-12 03:15
Kindly assign this to me. I would like to take care of this!

**Comment by fallaciousreasoning** [comment] 2023-07-13 00:16
@joshuakatt I've assigned you :smile: Feel free to reach out if you have any questions

**Comment by ItIsOHM** [comment] 2023-07-26 12:34
Hey @joshuakatt are you working on this? I'm a beginner so I'd like to work on this :D

**Comment by joshuakatt** [comment] 2023-07-26 19:42
> 

Hi @ItIsOHM Thanks for reaching out, but I'm currently working on this already!

**Comment by ItIsOHM** [comment] 2023-07-26 19:48
No worries! A side question, is there a way or some sort of an app that gives me an alert whenever a "good first issue", or generally any specified label issue is raised? It'll make it easier for newbies like me to keep up with the latest beginner friendly issues :D

Sorry if it's wrong to discuss it here I just wasn't sure where to ask this.

**Comment by fallaciousreasoning** [comment] 2023-07-27 02:52
Hey @ItIsOHM, thanks for your interest! I don't think there is sorry, unless you're a member of the Brave organisation - the closest is probably refreshing the [issues with that label](https://github.com/brave/brave-browser/labels/good%20first%20issue) unfortunately (and that's not very helpful).

**Comment by fallaciousreasoning** [comment] 2023-07-28 01:04
@ItIsOHM I just tagged you on another issue, if you want to take a look

**Comment by shreyansh1410** [comment] 2023-08-04 16:37
Hey @fallaciousreasoning, can you assign me on any beginner friendly project?

**Comment by satvik2131** [comment] 2023-09-21 15:15
Hey , is anyone working on this issue , or is this issue is resolved ?

**Comment by fallaciousreasoning** [comment] 2023-09-24 20:11
The issue isn't resolved yet, feel free to submit a PR :smile:

**Comment by harshdevl** [comment] 2023-10-05 22:26
@fallaciousreasoning To submit a PR do I have to make changes in the brave/brave-core repo or I can directly submit changes to this repo?

**Comment by simonhong** [comment] 2023-10-06 00:35
This issue will be fixed by my another PR(https://github.com/brave/brave-core/pull/20409)

**Closed** 2023-10-11 03:42 UTC
Labels: bug, good first issue, feature/user-interface, priority/P5, QA/Yes, feature/settings, OS/Desktop

**Comment by kjozwiak** [comment] 2023-10-18 01:36
The above requires `1.60.95` or higher for `1.60.x` verification 👍 Can technically be verified alongside https://github.com/brave/brave-browser/issues/33128.
