### ISSUE TITLE
Brave browser shakes and hangs

### ISSUE THREAD

**Issue by s3rgeym** [brave/brave-browser#35690] opened 2024-01-30 12:55 UTC
## Steps to Reproduce

1. launch Brave.
2. Press `Super + Right` to move window to the right side of [the] screen.
3. Open any tab with dialog `Leave Page` and etc.
4. Try to close the tab.

![image](https://github.com/brave/brave-browser/assets/12753171/93f0c022-2d07-4b99-90b9-8a0d283f6cdb)

## Actual result:

Brave browser shakes and hangs.

![image](https://github.com/brave/brave-browser/assets/12753171/75d99be2-b001-4a88-a645-7cd0ecb8205e)

## Brave version (brave://version info)

```bash
Brave Browser 121.1.62.153 
```

OS: Arch Linux
KDE Version: 5.27.10

It's Chromium, Brave or KDE Bug. I DONT Know

https://github.com/brave/brave-browser/assets/12753171/3eca96bd-6b24-4d51-a87e-bbe2970dfe87

**Comment by s3rgeym** [comment] 2024-01-30 12:57
It's the only way to Close Brave:

```bash
killall brave
```

**Comment by gcvl** [comment] 2024-01-30 18:24
Similar to #35648 ?

**Comment by gcvl** [comment] 2024-01-30 18:39
Maybe related to https://bugs.chromium.org/p/chromium/issues/detail?id=1522159&q=dialog&can=2 ?

**Comment by Vampiloup** [comment] 2024-01-30 19:16
Same thing here, after a Brave Update 👍 
Linux Manjaro, KDE / Plasma.

After a while, the poor Plasma goes unresponsive too.

**Comment by bsclifton** [comment] 2024-01-31 18:35
Update from one user (might help provide a clue):

> I turned off the built-in window tiling manager (in the OS) and that seems to have solved it

**Comment by gcvl** [comment] 2024-01-31 19:36
> Update from one user (might help provide a clue):
> 
> > I turned off the built-in window tiling manager (in the OS) and that seems to have solved it
> 
> I added some notes to the Chromium crbug - thanks for linking @gcvl 🙂 I also reached out to folks on Chromium Slack channel

Also https://bugs.chromium.org/p/chromium/issues/detail?id=1523382&q=dialog&can=2 !

**Comment by bluesky-ca** [comment] 2024-02-03 05:59
On Mint 21.1 running Cinnamon closing a window with 2 or more tabs causes the shake issue and a crash - if there is only one tab  no problem.   
Is there a way to set the "Don’t show this again" option for the window closing prompt - if I can set that directly in the config file it might at least avoid this issue ?

**Comment by bsclifton** [comment] 2024-02-12 21:31
This might be captured upstream with https://issues.chromium.org/issues/41495488

If so, I see a fix landed Feb 8th with https://chromium-review.googlesource.com/c/chromium/src/+/5274770

I'll need to check if this is being uplifted and included in a 121 update

**Comment by bsclifton** [comment] 2024-02-12 21:37
cc: @emerick @kjozwiak - I added to 1.62 milestone so that we can check during next Chromium bump if the fix is included for this

Triaged as a P1 since it causes very bad issues for folks - several folks internally are having this too. It may also fix https://github.com/brave/brave-browser/issues/35648 as @gcvl shared above

**Comment by unclev** [comment] 2024-02-15 04:37
From my observations this happens after popup box.

**Comment by unclev** [comment] 2024-02-15 06:40
> It seems related to https://bugs.chromium.org/p/chromium/issues/detail?id=1522159&q=dialog&can=2 . If I disable the fonts scaling in my system, this doesn't happen anymore.

The glitch happens only if both _Global scale_ and _Force font DPI_ KDE settings are in use <u>at the same time</u> (changing _Global scale_ automatically changes _Force font DPI_).

OS: OpenSUSE Tumbleveed 20240126
KDE Version: 5.27.10

It's Chromium or KDE Bug. The Edge bowser is aslo suffer from this error. It seems none of the other software affected.

**Comment by s3rgeym** [comment] 2024-02-15 14:52
This is chromium-based browsers bug (Chrome, Chromium, Edge, Vivaldi,
Brave, Yandex Browser and etc)

чт, 15 февр. 2024 г. в 09:40, Victor Kulichenko ***@***.***>:

**Comment by bsclifton** [comment] 2024-02-15 19:11
OK they did not include this fix in 121 unfortunately. When I did add the merge request label, it did get merged to 122 though! 😄 So that is when this is going to be fixed

**Comment by bsclifton** [comment] 2024-02-15 19:14
@kjozwiak we can recheck with 1.63 😄 Chromium folks uplifted with https://chromium-review.googlesource.com/c/chromium/src/+/5273356

**Comment by rebron** [comment] 2024-02-21 00:28
per @emerick Should be fixed with 122.0.6261.43. 
Latest RC should be good. https://github.com/brave/brave-browser/releases/tag/v1.63.157

**Comment by kjozwiak** [comment] 2024-02-22 05:33
> per @emerick Should be fixed with 122.0.6261.43. Latest RC should be good. https://github.com/brave/brave-browser/releases/tag/v1.63.157

Closing as per the above as it's been fixed via `122.0.6261.43` and we'll be releasing `1.63.x` with `122.0.6261.57`. Hopefully we can get some confirmations from users once `1.63.x` goes out tomorrow.

**Closed by kjozwiak** 2024-02-22 05:33 UTC
Labels: release/blocking, OS/Linux, priority/P1, Chromium/waiting upstream, OS/Desktop, Chromium/reported upstream

**Comment by LaurenWags** [comment] 2024-02-22 17:22
Confirmed `release-notes/exclude` label with @rebron @kjozwiak
