### ISSUE TITLE
Brave Feature: Picture in Picture not working after upgrading to latest version.

### ISSUE THREAD

**Issue by kushthedude** [brave/brave-browser#6733] opened 2019-11-02 20:58 UTC
## Description 

Picture in Picture is not working on MacOS Mojave after upgrading brave to latest version.

## Expected result:

Picture in Picture should be working as before
## Brave version (brave://version info)

Brave | 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | macOS Version 10.14.6 (Build 18G87)
JavaScript | V8 7.7.299.13

**Comment by kushthedude** [comment] 2019-11-02 20:59
PS: I have tried all the steps mentioned [here](https://reclaimthenet.org/how-to-activate-pip-picture-in-picture-in-the-brave-browser/)

**Comment by rebron** [comment] 2019-12-20 18:10
@kushthedude This might be website/video player dependent. Can you give us the example site where you're running into this issue?

Going to mark this as a dupe of: https://github.com/brave/brave-browser/issues/824

**Closed by rebron** 2019-12-20 18:10 UTC
