### ISSUE TITLE
Import/Export Bookmarks on Android

### ISSUE THREAD

**Issue by tdadvocate** [brave/brave-browser#25543] opened 2022-09-22 04:25 UTC
## Description
A real way to import/export bookmarks because sync still only works half of the time. 

### Additional information
Sync always fights with me so I went back to using Chrome on desktop and am considering doing the same on Android because of this issue that's been ongoing since 2017 from what I have learned. I also constantly have issues where some updates have deleted all of the app data so I've lost both my bookmarks and my open tabs. This could have been resolved by a simple export option. Even if it just exports them to a simple text file which is incredibly easy and would not hinder chromium in any way, shape, or form. I've looked at all the past threads relating to this and it seems the excuse for not even a simple solution is "no time" or "chromium holds us back". These are clear scapegoats when literally all you would need to do to at least make people feel better is a simple text export. You could even just use the fact of manual imports by having them add the bookmarks back in one by one manually off of this text document that you exported. I see no reason that at this point in development you can't even provide a simple solution to a VERY long standing problem the users consistently keep coming back to request every few months over the last 5+ years. I'm sorry but it just seems like blatant disrespect at this point and it seems like most users have begun to get fed up from what I've been reading on some of the forums while attempting to find any solution to this besides the bromite one.

**Comment by Brave-Matt** [comment] 2022-09-23 18:50
Duplicate of this issue:
https://github.com/brave/brave-browser/issues/11485

**Closed by Brave-Matt** 2022-09-23 18:50 UTC
Labels: OS/Android
