### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#24287] opened 2022-07-27 05:53 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.41.99  Chromium: 103.0.5060.134
Operating System: Mac OS X 12.2.1

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. open lk.gosuslugi.ru
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/62d70c00-0d65-8e08-0000-000000000000

**Comment by aseren** [comment] 2022-07-27 06:41
Crash is not reproduced on Brave v1.41.100.

**Comment by rebron** [comment] 2022-07-27 21:35
Closing as dupe of https://github.com/brave/brave-browser/issues/24164

**Closed by rebron** 2022-07-27 21:35 UTC
Labels: crash
