### ISSUE TITLE
Started ad conversion timer is called twice for the same creative_instance_id

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#8644] opened 2020-03-11 22:50 UTC
Found while testing https://github.com/brave/brave-browser/issues/6536

`Started ad conversion timer` is called twice for the same creative_instance_id. It could be that is called for wrong creative_instance_id. It could be that the issue is purely visual and that log function needs fixing. 

## Steps to Reproduce

   1. Create catalog that has two ads. Each ad in its separate creativeSetId and each having distinct urlPattern
   2. Trigger Ad1
   3. Trigger Ad2
   4. Open urlPattern for Ad1
   5. Write down `Started ad conversion timer`
   6. While conversion of Ad1 is on a timer, open urlPattern for Ad2
   7. Write down `Started ad conversion timer`

Important: Conversions for both ads were successful 
Note: Tested on staging

## Actual result:

`Started ad conversion timer` is called twice for the same creative_instance_id
It is called for the same ad twice.
```
[3770:1:0311/230532.137139:INFO:ad_conversions.cc(179)] Started ad conversion timer for creative_instance_id 36c84fcb-6388-45d8-81ed-5a5d986cd7ef with creative set id de5a82e1-17d6-47e0-a368-17f8f56dfeb3 which will trigger on 2020-03-11 22:11:00.000 UTC
[3770:1:0311/231100.150433:INFO:ad_conversions.cc(179)] Started ad conversion timer for creative_instance_id 36c84fcb-6388-45d8-81ed-5a5d986cd7ef with creative set id de5a82e1-17d6-47e0-a368-17f8f56dfeb3 which will trigger on 2020-03-11 22:13:57.000 UTC
```
Full log [adslog.log](https://github.com/brave/brave-browser/files/4321338/adslog.log)

## Expected result:
Each `Started ad conversion timer` call should have different creative_instance_id

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.7.54 Chromium: 80.0.3987.132 (Official Build) nightly (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Ubuntu 18.04 LTS

Brave | 1.7.54 Chromium: 80.0.3987.132 (Official Build) nightly (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

cc @brave/legacy_qa @tmancey @jsecretan @rebron

**Comment by tmancey** [comment] 2020-03-12 01:39
https://github.com/brave/brave-browser/issues/8645 will resolve this issue

**Comment by tmancey** [comment] 2020-03-13 21:14
Fixed by https://github.com/brave/brave-browser/issues/8645

**Comment by btlechowski** [comment] 2020-03-17 15:23
Notice that `Started ad conversion timer` is triggered twice for the same ad, though 2 different ads were actually converted.

**Comment by tmancey** [comment] 2020-03-22 11:16
> Notice that `Started ad conversion timer` is triggered twice for the same ad, though 2 different ads were actually converted.

Can you raise a new issue with steps, thanks

**Comment by btlechowski** [comment] 2020-04-20 16:48
@tmancey What about this issue? It is still open.

**Comment by tmancey** [comment] 2020-04-21 07:55
Cannot reproduce the issue with latest nightly, can you please retest

**Closed** 2020-06-03 08:04 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/ads, priority/P2

**Comment by btlechowski** [comment] 2020-06-03 19:51
Not reproducible anymore

Brave | 1.10.80 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Verified test plan from the description.
Two conversion timers are set and are triggered when expected:
```
{
	"ad_conversions": [{
			"creative_set_id": "de5a82e1-17d6-47e0-a368-17f8f56dfeb3",
			"timestamp_in_seconds": "1591375286",
			"uuid": "36c84fcb-6388-45d8-81ed-5a5d986cd7ef"
		}, {
			"creative_set_id": "c6ea8956-2be0-4a8a-993a-4ce653af18a4",
			"timestamp_in_seconds": "1591391498",
			"uuid": "ad364789-8177-4d18-b462-bf63257cb763"
		}
	]
}
```
