### ISSUE TITLE
Wallet address is not shown when FIL transaction is in progress

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#24187] opened 2022-07-21 16:13 UTC
![image](https://user-images.githubusercontent.com/106654560/180262624-69f925e2-7274-46cf-9ae9-bcdea4471bd8.png)

**Comment by yrliou** [comment] 2022-07-21 19:43
Closing this as @bbondy confirmed it's because he has some old accounts created before our formal release which has un-migrated preference of accounts that cause missing account names.
In this case, users need to reset their account or modify the Preference file to remove these bad account metas of filecoin.

**Closed by yrliou** 2022-07-21 19:43 UTC
Labels: priority/P2, QA/Yes, OS/Desktop, feature/wallet/filecoin
