### ISSUE TITLE
Add a right click menu option when selecting a blank space in the vertical tabs panel

### ISSUE THREAD

**Issue by ahXN00** [brave/brave-browser#38564] opened 2024-05-24 18:38 UTC
### Platforms

Windows

### Description

I am currently using the latest nightly build.Brave Version 1.68.44 Chromium: 125.0.6422.112 

In the vertical tab, the right click popup menu only shows if i click it over an tab, please make right click popup menu also available for empty space in vertical tab. I added a screenshot below which is from another browser, so that you can understand what i meant.

While using split view , i found out that if i want to use split view ,i only have option new split view, but no option to add one or more existing tab in the opened tabbed split view. Please add this option.

![image](https://github.com/brave/brave-browser/assets/53382135/e276e34a-b3c8-49f6-9831-027854fb9030)

**Comment by rebron** [comment] 2024-05-28 20:27
@ahXN00 If you select two tabs via command or alt click, you can open those two tabs in a split view via right click menu. We'll need to add additional UI to make this more obvious.

If you hover over a a tab, it's actually not a right click menu but a tooltip/card.

You're right that we should show a right click context menu when clicking on an empty space in the vertical tabs pane.

**Comment by mirceavesa** [comment] 2024-07-31 11:16
Hi! I love using the vertical tabs, but I wish that the "+ New Tab button" would be in a better location instead of the bottom corner. The option to right click on empty space of the panel would also help address this, of course. Thanks!

**Comment by rebron** [comment] 2024-11-13 21:59
Closing as dupe of https://github.com/brave/brave-browser/issues/41825

Fixed here: https://github.com/brave/brave-core/pull/26334#issuecomment-2469328195

**Closed by rebron** 2024-11-13 21:59 UTC
Labels: feature/context-menu, priority/P4, feature-request, OS/Desktop, feature/vertical-tabs
