### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by seankuendig** [brave/brave-browser#34942] opened 2023-12-16 13:03 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.100 Chromium: 120.0.6099.62
Operating System: Mac OS X 14.1.0

URL (if applicable) where crash occurred: 

Can you reproduce this crash? 
Yes, but it takes some time to reproduce.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open new brave tab.
2. Let your mac go to sleep for 5+ minutes
3. Click on a folder in your bookmark bar
4. Brave crashes

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/0e000500-100a-300b-0000-000000000000

**Comment by rebron** [comment] 2023-12-21 18:00
closing as dupe of https://github.com/brave/brave-browser/issues/34909.
Hi @seankuendig  Can you update to the latest 1.61.109 that released today and see if this is still an issue for you.

**Closed by rebron** 2023-12-21 18:00 UTC
