### ISSUE TITLE
Optimize multiple initializations of content_cosmetics.bundle.js during frame load

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#17935] opened 2021-09-08 10:56 UTC
## Description 
The problem is content_cosmetics.bundle.js sometimes is injected and initialized twice during each main frame load.
(see the picture in attachment) 

The reason is that webpack bundle mechanisms aren't designed for multiple injections.
In addition, some caching mechanisms don't work correctly (for example _parseDomainCache).

The bundle should be injected once, with no double execution/code-optimization during frame load.
The native code should call some exported functions.

## Steps to Reproduce
1. Visit a very simple HTML page like https://example.com
2. Open Developer Tools: Performance
3. Click record page load time.
4. Look for large "Evaluate Script" tasks after ParseHTML task.

## Actual result:
See two large tasks spawned by injecting content_cosmetics.bundle.js (better to use built from source version to see the stack details). The script was injected from native code: https://github.com/brave/brave-core/blob/713692eb65af2adf39c9375d5c6f87f5afd830a6/components/cosmetic_filters/renderer/cosmetic_filters_js_handler.cc#L196-L198

## Expected result:
Only one such task.

## Reproduces how often: 
Easily reproduced

![image](https://user-images.githubusercontent.com/45488748/132497446-fefd1656-e49a-450b-82c9-543832984722.png)

**Comment by iefremov** [comment] 2021-09-08 11:14
cc cc @antonok-edm @pes10k @SergeyZhukovsky

**Comment by antonok-edm** [comment] 2021-09-08 17:52
@iefremov perhaps you can verify, but I believe this is fixed by https://github.com/brave/brave-core/pull/9995:

![2021-09-08-101708_945x498_scrot](https://user-images.githubusercontent.com/22821309/132559440-c6d02a3c-8f52-45ee-9b68-7f0fb8957b98.png)

**Comment by SergeyZhukovsky** [comment] 2021-09-10 13:55
@atuchin-m the description of the issue is incorrect. The bundle isn't injected on every frame at all. We do that only in the main frame https://github.com/brave/brave-core/blob/master/components/cosmetic_filters/renderer/cosmetic_filters_js_handler.cc#L341
In most cases the injection happens only once and as I mentioned above on the main frame only.

**Comment by atuchin-m** [comment] 2021-09-10 15:08
@pes10k 
Agreed, especially after removing extension implementation (which was not limited to main frames).
I've corrected the description: added `sometimes` and `during each main frame load`

**Closed** 2021-09-14 12:54 UTC
Labels: perf, QA/Yes, release-notes/exclude, OS/Android, features/shields/cosmetic-filtering, OS/Desktop

**Comment by stephendonner** [comment] 2021-09-17 17:37
**Verified `PASSED`** using 


Brave | 1.31.51 Chromium: 94.0.4606.50 (Official Build) nightly (x86_64)
-- | --
Revision | 0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}
OS | macOS Version 11.6 (Build 20G165)

### Steps:
1. clean profile
2. launched Brave
3. opened Developer Tools' `Performance` tab
4. loaded `https://example.com`
5. clicked on the `Record` icon
6. reloaded the page
7. clicked on the `Stop` icon
8. compared `beta` to `nightly`

#### Confirmed:

1. The `main` process time went from `343ms` -> `12ms`, with a huge chunk of that reduction coming from Scripting (`103ms` -> `6ms`).
2. Page load ranges went down, from:

`beta:` `3.68s - 4.02s`

to

`nightly:` `2.46s - 2.47s`

`beta` | `nightly`
-------|---------
<img width="1727" alt="Screen Shot 2021-09-17 at 10 14 28" src="https://user-images.githubusercontent.com/387249/133829682-f62860fd-320a-4115-ab40-fbf8c36c3ce0.png"> | <img width="1703" alt="Screen Shot 2021-09-17 at 10 15 19" src="https://user-images.githubusercontent.com/387249/133829722-da2358b1-b1f4-43a4-b3f2-9c8413f7f6ba.png">

**Comment by srirambv** [comment] 2021-10-07 10:49
Verification passed on Oppo Reno 5 with Android 11 running 1.31.73 x64 build
- Verified load time went down fro 260 ms to 89 ms 

1.30.87 Release | 1.31.73  Beta
-- | --
![image](https://user-images.githubusercontent.com/17010094/136367167-8df0f4ac-c2cf-4a76-a1c0-f6d1753c2e80.png) | ![image](https://user-images.githubusercontent.com/17010094/136369940-d305e609-9e10-41d9-afeb-94160e3d21d4.png)
