### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by LaptopBushman** [brave/brave-browser#38336] opened 2024-05-15 14:18 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.65.133 Chromium: 124.0.6367.208
Operating System: Windows NT 10.0.22621

URL (if applicable) where crash occurred: youtube.com

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open laptop
2. Launch Brave
3. Laoding
4. Wait 1-2 minutes

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/80f81200-bb03-f30b-0000-000000000000

**Comment by iefremov** [comment] 2024-05-15 19:45
@LaptopBushman unfortunately the dump is corrupted. Can you reproduce a couple more times and upload more dumps? Also do you have anything on brave://flags? What extensions do you have installed?

**Comment by LaptopBushman** [comment] 2024-05-16 17:06
i Have Google Docs Offline **extension**.  I have nothing on brave://flags--- in fact i've never heard of it until now. As for reproducing it...hmm.. i'll try.

**Comment by bsclifton** [comment] 2024-05-16 22:52
No useful info here in stack trace
https://brave.sp.backtrace.io/p/brave/debug?filters=JTVCJTVCJTIyX2RlbGV0ZWQlMjIlMkMlMjJlcXVhbCUyMiUyQyUyMjAlMjIlNUQlMkMlNUIlMjJfcnhpZCUyMiUyQyUyMmVxdWFsJTIyJTJDJTIyODBmODEyMDAtYmIwMy1mMzBiLTAwMDAtMDAwMDAwMDAwMDAwJTIyJTVEJTVE&fingerprint=9fa0abb2b33bd3a7f93700535e21658db9aa68b790d6fd7d6eff84d3459e7fd1&debug=(%2275ec3c0%22,0,0)


Calllstack
```
[ 0 ] 0x7ffd2b0616d7
[ 1 ] 0x7ffd2b043347
[ 2 ] 0x7ffd2b0616d7
```


Looks like it happened on YouTube.com. @LaptopBushman do you have the Playlist feature enabled? brave://flags/#playlist
We should be restricting that to Nightkly / Beta for the moment - but at the moment it's toggleable on Release

**Comment by LaptopBushman** [comment] 2024-05-17 04:45
The playlist feature is disabled
i don't have an account on stack trace and i can't create one, it seems. 
Thank you, @bsclifton .

**Comment by LaptopBushman** [comment] 2024-05-17 04:47
moreover, i can't reproduce the crash anymore, @iefremov .

**Comment by iefremov** [comment] 2024-05-17 06:04
thanks @LaptopBushman , closing it for now

**Closed by iefremov** 2024-05-17 06:04 UTC
Labels: crash, priority/P2, OS/Desktop

**Comment by LaptopBushman** [comment] 2024-05-19 15:53
I have some really important stuff on there, regarding study and job prospects so i would appreciate it if you **don't** forget about it.
