### ISSUE TITLE
Cannot change the F12 menu settings

### ISSUE THREAD

**Issue by Lemonawa** [brave/brave-browser#21127] opened 2022-02-16 05:40 UTC
**Description of the issue:**
**How can this issue be reproduced?**

1.Press F12 Botton
2.Click on the gear icon
3.Change to any language
4.Reload
5.Still English

**Expected result:**
Change to the language I want(Chinese - 中文）
**Brave Version( check `About Brave`):**
1.35.101 or the latest Brave Nightly
**Additional Information:**
none

**Comment by Lemonawa** [comment] 2022-02-16 05:47
Like this:
#20491

**Comment by cyress** [comment] 2022-02-16 12:10
Related tickets: #20075, #19530, #19509, #19871, #20491, #21018

**Comment by bsclifton** [comment] 2022-03-18 08:05
Should be fixed with https://github.com/brave/brave-core/pull/12600 - duplicate of https://github.com/brave/brave-browser/issues/20491

Fix is in Nightly and will be uplifted to Beta and Release channels. Thanks for your patience, folks 😄

**Closed by bsclifton** 2022-03-18 08:05 UTC
Labels: feature/dev-tools, OS/Desktop

**Comment by Lemonawa** [comment] 2022-03-18 08:07
> Should be fixed with [brave/brave-core#12600](https://github.com/brave/brave-core/pull/12600) - duplicate of #20491
> 
> Fix is in Nightly and will be uplifted to Beta and Release channels. Thanks for your patience, folks 😄

OK, Let me test it

**Comment by bsclifton** [comment] 2022-03-18 17:25
@Lemonawa awesome, let us know 😄 I specifically tried your use-case (changing language) and it worked great 👍 I verified BEFORE the fix that the same set of steps I tried did not work

**Comment by Lemonawa** [comment] 2022-03-18 17:35
> @Lemonawa awesome, let us know 😄 I specifically tried your use-case (changing language) and it worked great 👍 I verified BEFORE the fix that the same set of steps I tried did not work

Success. Thank you! 😊
