### ISSUE TITLE
[Desktop] Close Profile button no longer available

### ISSUE THREAD

**Issue by scho** [brave/brave-browser#9528] opened 2020-04-29 08:09 UTC
## Description 
Profiles can no longer be closed. The "Close $profile" is missing. 

## Steps to Reproduce

   1. Make sure you have more than one profile
   2. Select a profile and open two tabs A and B
   3. Close the window
   4. Select a different profile
   5. Select the first profile

## Actual result:
A blank window is shown.

## Expected result:
The window shows the tabs A and B

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.15.4 (Build 19E287)

## Version/Channel Information:
I don't know.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? => No
- Does the issue resolve itself when disabling Brave Rewards? => No
- Is the issue reproducible on the latest version of Chrome?  => I don't know

## Miscellaneous Information:
The "Close $profile" button was removed. Bringing it back would solve this issue.

**Comment by rebron** [comment] 2020-06-12 16:57
@scho I couldn't reproduce your issue. Is this still happening for you in our latest release 1.9.80? 

There is no more close profile button in the menu as you mentioned and we're not adding it back but closing out the window should close out the profile/window you're on (your example, profile 2) and bringing back profile 1 in your steps should show that profile 1 with tabs A and B in it and not a blank window.

**Comment by rebron** [comment] 2021-10-06 17:31
Closing as stale. @scho Let me know if this is still an issue for you in 1.30.87.

**Closed by rebron** 2021-10-06 17:31 UTC
Labels: needs-more-info, OS/Desktop
