### ISSUE TITLE
[Desktop] Grid sites in new tab UI makes white favicon disappear

### ISSUE THREAD

**Issue by l3lackcurtains** [brave/brave-browser#11650] opened 2020-09-10 08:57 UTC
## Description 

The background color of grid sites in the new tab UI makes the white favicon disappear.
## Steps to Reproduce

   1. Go to a new tab
   2. If the recent site you have visited has a white favicon, it will disappear because of the white background
   3. Example: Github favicon

## Actual result:

![favicon_hidden](https://user-images.githubusercontent.com/9688803/92704274-b1b57000-f307-11ea-9880-f5e7cf370b14.png)

## Expected result:
![expected](https://user-images.githubusercontent.com/9688803/92704479-d578b600-f307-11ea-9130-fca32d35dea1.png)

Or another compatible background color.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment] 2020-09-10 15:39
cc: @karenkliu Thoughts? A background color that will work for both dark and light favicons?

**Comment by karenkliu** [comment] 2020-09-10 18:20
@rebron We need to stop using hard background colors and instead dynamically generate the background color for tiles similar to how iOS has it implemented:

> Default color: #A7ACB2
>
> Icon color is derived in the following order:
> - “theme-color” meta tag value, if available return this color.
> - “msapplication-navbutton-color” meta tag value, if available return this color.
> - “apple-mobile-web-app-status-bar-style” meta tag value, if available return this color.
> - Final sample attempt - sample color from three points on website 
> Desktop version - https://github.com/brave/browser-laptop/blob/6ac06a4bcb60e2fd2a4bba6795dbe240f399c234/app/extensions/brave/content/scripts/themeColor.js
> Mobile version - https://github.com/brave/browser-ios/blob/97d2eddeb023660d47c05de0215f2157471655da/Client/Assets/ThemeColor.js(uses y=1 vs y=3 for more accurate sampling — mobile site headers are smaller) 
>- Determine if color result is too light to be displayed. Text will always appear white over color, if background color lacks contrast (several sites may return white) we fallback to default color.
> 
> Checking if a color is too light
> - Color RGB value is converted to grayscale format and checked against our acceptable value, > 50% white would require a fallback to default color #A7ACB2
> - iOS uses internal color function getWhite() which returns a white color alpha based on %. You can achieve a similar check in javascript by using W3C recommended formula for accessibility (accepted answer here https://stackoverflow.com/questions/3942878/how-to-decide-font-color-in-white-or-black-depending-on-background-color)
> 
>

**Comment by bsclifton** [comment] 2020-09-10 19:30
Thanks for the report @l3lackcurtains

This is a duplicate of https://github.com/brave/brave-browser/issues/9030

I'll close this and share links to the comments there

**Closed by bsclifton** 2020-09-10 19:30 UTC
Labels: OS/Desktop, feature/new-tab
