### ISSUE TITLE
Restored sites got deleted after page reload, when rewards page opened in multiple windows

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3264] opened 2019-02-07 20:18 UTC
## Steps to Reproduce

   1. Clean profile `0.60.19`
   2. Enable rewards through rewards panel 
   3. Add any site to a-c table (Window 1)
   4. Right click on the site in a-c table and open it in new window ( Window2)
   5. Open Rewards page in Window2 through rewards panel
   6. Make sure site which is added in step 3 is available in a-c table in Window2
   7. Go to Window1, delete the site from a-c table
   8. Go to Window2 and see site deleted from there as well
   9. Click on `Restore All` on Window1 and see that site got restored and visible in a-c table
  10. Go to Window2 and see site is not visible in a-c table, Refresh the rewards page and see site is not 
       restored
  11. Go to Window1 and reload the rewards page.
  12. Site which was restored got deleted after page reload

## Actual result:
Restored sites got deleted after page reload, when rewards page opened in multiple windows

## Expected result:
Restored sites should not get deleted 

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.60.19 Chromium: 72.0.3626.81 (Official Build) beta (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Windows 10

### Reproducible on current release: No
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional Information
On single Rewards page it perfectly works fine, issue arises only when there are multiple rewards pages.

@brave/legacy_qa @NejcZdovc

**Comment by LaurenWags** [comment] 2019-02-08 16:15
Reproduced with

Brave | 0.60.23 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

**Comment by LaurenWags** [comment] 2019-02-08 16:18
Could not reproduce with current released version:

Brave | 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

**Comment by LaurenWags** [comment] 2019-02-08 16:42
Additionally, I followed the STR from the issue and then also did the following after step 12:
13. Visited a new site in window1 for min amount of time. Verified it was added to the ac table on both windows. Note: % is acting as if the first site is still visible, when it is not.
14. Visited a second new site in window2 for min amount of time. Verified it was added to the ac table on both windows. Note: % is acting as if the first site is still visible, when it is not.
Here's what I see in a-c table and in publisher_info_db:
![screen shot 2019-02-08 at 11 40 40 am](https://user-images.githubusercontent.com/28145373/52492012-5f91f300-2b96-11e9-9842-be0b235e9e91.png)
![screen shot 2019-02-08 at 11 41 31 am](https://user-images.githubusercontent.com/28145373/52492107-8ea86480-2b96-11e9-8d1f-4bd15b454374.png)
![screen shot 2019-02-08 at 11 41 44 am](https://user-images.githubusercontent.com/28145373/52492113-90722800-2b96-11e9-960d-e93a2b3bf8c3.png)

**Comment by LaurenWags** [comment] 2019-02-14 16:47
@GeetaSarvadnya can you check this one on latest 0.61.x?

**Comment by NejcZdovc** [comment] 2019-03-07 09:23
this one was fixed with https://github.com/brave/brave-core/pull/1803

**Closed by NejcZdovc** 2019-03-07 09:23 UTC
Labels: QA/Yes, bug, feature/rewards, priority/P3, regression

**Comment by GeetaSarvadnya** [comment] 2019-03-13 12:47
@LaurenWags Issue is Reproducible on `0.61.51`


Brave | 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

**Comment by GeetaSarvadnya** [comment] 2019-03-13 12:56
Verification passed on 


Brave | 0.63.5 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 10 OS Build 17134.523
