### ISSUE TITLE
Feature - Create a more organised context-menu layout.

### ISSUE THREAD

**Issue by dave90dave** [brave/brave-browser#13849] opened 2021-01-30 11:57 UTC
## Description 

The context menu layout is a bit messy.
Maybe it is time for a better organised context menu?

## Steps to Reproduce

   1. Open brave
   2. Click to open the context menu, at the top right of the brave browser 

## Actual result:

Right now, it looks like this:
![Schermafdruk van 2021-01-30 12-48-41](https://user-images.githubusercontent.com/7985017/106355689-f7e08f80-62f9-11eb-811a-069dd5ad28f5.png)

## Expected result:
I hope that it could be improved with a better layout:

Take for example the layout of mozilla firefox:
![Schermafdruk van 2021-01-30 12-53-59](https://user-images.githubusercontent.com/7985017/106355794-8bb25b80-62fa-11eb-8041-99b1bd85b849.png)

This is how it COULD look like.

- Simple
- Organised
- Covers the most used aspects of the browser
- Easy to find where you are looking for (Improved productive value)
- (And really great icons) :+1: 

## Brave version (info found on brave://version)

1.19.88

##Keep up the good work, Brave!

**Comment by Sky2883** [comment] 2021-01-30 13:42
1235

**Comment by Sky2883** [comment] 2021-01-30 13:43
1389

**Comment by Sky2883** [comment] 2021-01-30 13:43
13849

**Comment by rebron** [comment] 2021-02-05 21:37
We do need to address some minor changes to organize the context menu. I disagree that Firefox's current app menu has a better layout.

**Comment by lil5** [comment] 2021-07-02 05:25
I agree that adding icons is a necessary improvement.

Icons improves accessibility for those with reading difficulties or sight difficulties.

**Comment by rebron** [comment] 2022-06-03 20:42
Closing as duplicate of https://github.com/brave/brave-browser/issues/18011

**Closed by rebron** 2022-06-03 20:42 UTC
Labels: priority/P3, feature/settings, OS/Desktop
