### ISSUE TITLE
Geolocation not using correct service

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12952] opened 2020-11-30 22:14 UTC
## Description 

Sometimes builds do not use the correct service (`location.brave.com`) for geolocation and instead use `location.services.mozilla.com`.

## Steps to Reproduce

   1. Navigate to `https://browserleaks.com/geo` or `https://html5demos.com/geo/`.
   2. Allow site to know your location from the bubble
   3. Wait

## Actual result:

Location is not identified. If you use Little Snitch, Charles Proxy, etc you will see that it is trying to use `location.services.mozilla.com`.

## Expected result:
Should use `location.brave.com` for geolocation.

## Reproduces how often: 

easily if you get a build that is affected

## Brave version (brave://version info)

1.19.39, 1.19.41 on both intel and arm64 macOS although when this happens it is not specific to macOS, it can occur on any OS

## Version/Channel Information:

- Can you reproduce this issue with the current release? intermittently yes
- Can you reproduce this issue with the beta channel? intermittently yes
- Can you reproduce this issue with the nightly channel? intermittently yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @kjozwiak

**Comment by kjozwiak** [comment] 2020-12-01 01:13
Duplicate of https://github.com/brave/brave-browser/issues/11862. We can either close this one off or close the other one and keep this one. However, https://github.com/brave/brave-browser/issues/11862 has more info/context. @rebron I'll let you decide which issue you prefer leaving opened 👍

**Closed** 2020-12-01 20:04 UTC
Labels: OS/Desktop, QA/Yes, closed/duplicate, intermittent-issue
