### ISSUE TITLE
Add callback to SetContributedAutoInclude

### ISSUE THREAD

**Issue by jdkuki** [brave/brave-browser#4642] opened 2019-05-29 23:03 UTC
## Description 

During a `RewardsServiceImpl::SetContributedAutoInclude` the RewardsService calls the Ledger which in turn eventually calls `RewardsServiceImpl::OnExcludedSitesChanged` to respond. `SetContributedAutoInclude` should be changed to use a callback function to handle the response of the ledger call rather than the extra layer of indirection.

## Steps to Reproduce

n/a

## Actual result:

n/a

## Expected result:

n/a

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment] 2019-07-25 17:52
dupe of https://github.com/brave/brave-browser/issues/5319

**Closed by NejcZdovc** 2019-07-25 17:52 UTC
Labels: duplicate, feature/rewards
