### ISSUE TITLE
Unable to save Network Throttling profiles in DevTools

### ISSUE THREAD

**Issue by martynasmartynas** [brave/brave-browser#21018] opened 2022-02-10 10:43 UTC
## Description 
Unable to save Network Throttling profiles in DevTools

## Steps to Reproduce

   1. Open Dev tools and go to settings
   2. Select Throttling 
   3. Add custom profile
   4. Save
   5. open new tab and go to any website
   6. Open dev tools
   7. No throttling profile is available

## Actual result:
Not available for other tabs newly added profiles, when I restart all profiles are gone.

## Expected result:
When I save new profile, it will be available to other tabs and when quit and open Brave it still there.

## Brave version (brave://version info)
1.35.101 Chromium: 98.0.4758.87 (Official Build) (arm64)

**Comment by cyress** [comment] 2022-02-16 12:08
Related tickets: #20075, #19530, #19509, #19871, #20491

**Comment by bsclifton** [comment] 2022-03-18 08:05
Should be fixed with https://github.com/brave/brave-core/pull/12600 - duplicate of https://github.com/brave/brave-browser/issues/20491

Fix is in Nightly and will be uplifted to Beta and Release channels. Thanks for your patience, folks 😄

**Closed by bsclifton** 2022-03-18 08:05 UTC
Labels: OS/Desktop
