### ISSUE TITLE
Outlook notifications unavailable

### ISSUE THREAD

**Issue by ryanccn** [brave/brave-browser#6559] opened 2019-10-20 20:01 UTC
## Description 

Notifications for new mail in Outlook  is unavailable. When I turn on notifications in Chrome, a push notification from Outlook pops out alerting me that notifications have been enabled. However, on Brave, nothing happened. I could not receive any form of notifications.

I tried with some other demos of push notifications, and only one of them worked.

## Steps to Reproduce

   1. https://web-push-book.gauntface.com/demos/notification-examples/ (successful)
   2. Anyone using Outlook, turn on the notifications and see if you get any. (failure)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

/ | /
-- | --
Brave | 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | macOS Version 10.15 (Build 19A583)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No**
- Does the issue resolve itself when disabling Brave Rewards? **No**
- Does the issue resolve itself when using Brave Nightly? **No**
- Is the issue reproducible on the latest version of Chrome?  **No**

**Comment by bsclifton** [comment] 2019-10-22 21:33
This has been fixed in 0.72.x and newer (which is currently the developer channel). This will be making it's way towards release which will happen on December 10th 😄 

I'll close this issue as it's a duplicate of https://github.com/brave/brave-browser/issues/2301

Thanks for the report 😄

**Closed by bsclifton** 2019-10-22 21:33 UTC
Labels: feature/notifications
