### ISSUE TITLE
Shields menu text is not visible

### ISSUE THREAD

**Issue by DBLouis** [brave/brave-browser#1150] opened 2018-09-16 06:34 UTC
## Description 
Text in shields menu is not visible (see screenshot)

## Steps to Reproduce
1. Download latest dev release and run it
2. Go to any website
3. Open shields menu

## Actual result:
![brave_shields_invisible](https://user-images.githubusercontent.com/6025361/45593626-75561000-b98a-11e8-9041-443da748f383.png)

## Reproduces how often: 
Always

## Brave version
v0.55.4

### Reproducible on current release:
No

### Additional Information
Void Linux (Kernel 4.18)
i3 window manager

I have tried dark/light classic and gtk+ themes, changing the system gtk theme.
If not all fonts are packaged with the release maybe I am missing one.

**Comment by jaromero** [comment] 2018-10-16 17:01
I haven't looked too much in depth into this, but it _seems_ that the text is just not there at all, at least when inspecting the popup with the Dev Tools.

![screenshot from 2018-10-16 11-52-55](https://user-images.githubusercontent.com/794031/47033587-d6643580-d13a-11e8-952e-441432de9897.png)

On this screenshot I just manually added the text into the <option> element via Dev Tools. Notice how the <option> elements from the other <select> earlier are completely empty.

**Comment by tomlowenthal** [comment] 2018-10-31 20:44
@srirambv Could you see if this is fixed on new builds?

**Comment by DBLouis** [comment] 2018-10-31 20:52
Still not working in v0.57.3

**Comment by DBLouis** [comment] 2018-11-06 17:42
In v0.57.6 the menu is prettier but still no text

**Comment by MafiaInc** [comment] 2018-11-14 11:47
In additional I have some strange i18n prefixes on the text in "Brave Rewards" menu:
![image](https://user-images.githubusercontent.com/1325853/48480528-661d0280-e813-11e8-9bba-122aaf529cd8.png)

I'm not sure whether it worth opening separate issue for that one? :)

**Comment by srirambv** [comment] 2018-11-14 12:39
@MafiaInc Please log an another issue for the rewards panel with translation strings. Also please mention the OS details. This could be specific to Arch based distros. I don't see this problem on Ubuntu
![image](https://user-images.githubusercontent.com/17010094/48483077-71a30600-e7e0-11e8-8f89-424c28f12e88.png)

**Comment by MafiaInc** [comment] 2018-11-14 13:03
@srirambv Issue: #2138 opened

**Comment by cptMikky** [comment] 2018-11-19 13:18
I can confirm this issue on Arch. Version 0.56.12 Chromium: 70.0.3538.77 (Official Build) unknown (64-bit).

This somehow feels like a font problem - what font is used on the Shield?

**Comment by DBLouis** [comment] 2018-11-21 15:42
Still in 0.58.9

**Comment by bartduisters** [comment] 2018-11-30 06:48
Still in 0.56.15-1

**Comment by rodrigogolive** [comment] 2018-12-11 13:36
same thing here (Slackware 14.2, Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) unknown (64-bit))
![shields](https://user-images.githubusercontent.com/1218078/49804167-0abe3180-fd39-11e8-8e35-83654b250354.png)

**Comment by petemill** [comment] 2018-12-13 05:40
This strikes me as something going wrong with our translation layer (either JS or outside) and not a font issue since there is _some_ text on the page, the text that is hidden is not in the DOM at all, and the text that is displaying Ok is non-translated (domain names and numbers).

**Comment by cptMikky** [comment] 2018-12-13 08:47
I've tried to manually extract and run Brave from the Ubuntu package (v 0.57.18) on my Arch and the shield **works** so apparently there is something wrong with the plain tar.gz release.

**Comment by DBLouis** [comment] 2018-12-13 09:07
Still in v0.59.6

**Comment by rodrigogolive** [comment] 2018-12-13 13:16
> @posix4e do you have an idea of what can be causing this? this seems related to arch based distros only. other distributions doesn't seem to be affected. can't repro on ubuntu for example

just to say, I'm on Slackware and it doesn't work either.

> I've tried to manually extract and run Brave from the Ubuntu package (v 0.57.18) on my Arch and the shield **works** there so apparently there is something wrong with the plain zip release.

yup, I'm running it from the zip as well (the slackware package is just a repackage of it too).

**Comment by pat-san** [comment] 2018-12-18 08:41
I hope it will be fixed soon, still in beta 59.8 & dev 60.2.
We need fonts, us on linux

**Comment by kirkins** [comment] 2018-12-23 04:03
I'm also seeing the i18n issue on Ubuntu 18.04 


![](https://i.imgur.com/e1iaoIF.png)

**Comment by RainmakerRaw** [comment] 2019-01-05 14:52
I had to uninstall Brave on Arch for this reason, also. The issue persists in latest brave-bin (0.58.18-1) and brave-dev-bin (0.60.6-1). Using Cinnamon 4.0.8 with Mutter.

**Comment by cezaraugusto** [comment] 2019-01-17 20:03
un-assigning myself as this is platform specific and I won't be able to help much. cc @posix4e who could answer better regarding Linux-related issues

**Comment by whezzel** [comment] 2019-01-23 21:13
@rjocoleman great find. I have just tested this with brave-beta-0.59.28 on my arch install. Extracting the resources from the debian package and inserting them into the zip distribution, fixes this issue.

**Comment by cezaraugusto** [comment] 2019-01-29 15:35
cc @bbondy your assumption re packaging is correct. not sure who could take this

related https://github.com/brave/brave-browser/issues/3104

**Comment by Miyayes** [comment] 2019-02-09 15:14
+1 https://www.reddit.com/r/brave_browser/comments/aot2j4/brave_shield_display_error/

**Comment by simonhong** [comment] 2019-02-28 23:42
Duplicated with https://github.com/brave/brave-browser/issues/3399 and fixed by https://github.com/brave/brave-browser/pull/3446.

**Closed by simonhong** 2019-02-28 23:42 UTC
Labels: OS/Linux, bug, feature/shields, priority/P2
