### ISSUE TITLE
[Desktop] Search engine updates - Follow up to 10890

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#11182] opened 2020-08-11 20:39 UTC
Follow up to https://github.com/brave/brave-browser/issues/10890

Yahoo is not added in some locales
I marked this issue as `OS/Linux` only as @LaurenWags tested Sweden(https://github.com/brave/brave-browser/issues/10890#issuecomment-671948094) and it worked.

## Steps to Reproduce

1. Delete profile
1. Run Brave with `LANG=sv_SE.UTF-8 LANGUAGE=sv_SE /usr/bin/brave-browser --enable-logging=stderr`
1. Open `brave://settings/searchEngines`

Reproducible on:
Sweden (sv_SE) 
Finland(fi_FI)

Not reproducible on:
France(fr_FR) 
Spain (es_ES) 

## Actual result:

Yahoo is not included in the list
![image](https://user-images.githubusercontent.com/34715963/89945996-836a4500-dc22-11ea-9bab-897726203111.png)

## Expected result:
Yahoo is included in the list

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @bsclifton @rebron @deeppandya

**Comment by LaurenWags** [comment] 2020-08-11 20:53
Does not reproduce on macOS using

```
Brave | 1.12.108 Chromium: 84.0.4147.105 (Virallinen koontiversio) (64-bittinen)
-- | --
Päivitetty versio | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
Käyttöjärjestelmä | macOS Versio 10.14.6 (Build 18G3020)
```

Confirmed both Sweden and Finland work as expected.

**Comment by rebron** [comment] 2020-09-11 17:03
@btlechowski Can you double check Windows? Per @LaurenWags above looks like macOS is working.

**Comment by btlechowski** [comment] 2020-09-11 17:08
@GeetaSarvadnya was verifying https://github.com/brave/brave-browser/issues/10890 on Windows.
@GeetaSarvadnya can you check on Windows?

**Comment by bsclifton** [comment] 2021-01-14 19:18
Closing as Yahoo has been removed

**Closed by bsclifton** 2021-01-14 19:18 UTC
Labels: OS/Desktop, OS/Linux, QA/Test-Plan-Specified, QA/Yes, closed/invalid, feature/search, priority/P3
