### ISSUE TITLE
Leo abruptly stops generating responses mid sentence

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#33607] opened 2023-10-12 20:29 UTC
## Description 

There are reports that Leo stops generating responses if it's long enough. I can replicate it with asking `is vegetable oil healthy?`

## Steps to Reproduce

   1. Go to the chat window
   2. Unlink it from the current page
   3. Ask `is vegetable oil healthy?`

## Actual result:

![Screenshot from 2023-10-12 14-56-48](https://github.com/brave/brave-browser/assets/12011303/f9c8447d-3040-47af-8994-d4d4358fb843)

## Expected result:
Leo generates response in full.

**Comment by bbondy** [comment] 2023-10-16 17:12
easier to reproduce with:
> is vegetable oil healthy? what are the factors to consider? Give me 15 different points.

**Comment by bbondy** [comment] 2023-10-18 13:51
Moving this out of MVP in favor of a short term (easier to implement) solution to make the problem less bad with https://github.com/brave/brave-browser/issues/33717

**Comment by bbondy** [comment] 2023-10-18 19:50
I asked @nvonpentz if there's a response cut off indication in the server response, and there is:
> There should be a "stop_reason" in the json response body that's either "stop_sequence" or "max_tokens" for when 'we exceeded max_tokens_to_sample or the model's maximum' per https://docs.anthropic.com/claude/reference/complete_post

**Comment by bbondy** [comment] 2023-10-18 19:52
@aguscruiz should we maybe for now show some kind of `Response limit exceeded` message so it doesn't look as bad? We could perhaps also trim to the last sentence termination punctuation mark when it is set. But if you for example ask to list out 15 items and only 11 are listed, then it is still somewhat obvious some truncation happened.

**Comment by aguscruiz** [comment] 2023-10-18 21:43
@bbondy is there a solution we can offer the user to generate a full response other than switching to a premium model? If there's not, we can use the - premium response limit message  - we have already, since it's the only way to move forward

https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=2725%3A11616&mode=design&t=MPHT8PRyYWgBwS9g-1

**Closed** 2024-01-24 18:19 UTC
Labels: bug, priority/P3, QA/Yes, release-notes/exclude, OS/Android, OS/Desktop, browser-ai
