### ISSUE TITLE
Feature Request: Add Extensions for Brave Android

### ISSUE THREAD

**Issue by Nihal247** [brave/brave-browser#17487] opened 2021-08-14 08:35 UTC
## Description
I use extensions a lot. Currently I use Firefox, because it provides extensions for it's Android version.
If you guys can make a few useful extensions available for Brave Android, I'll be really glad!
Please consider making HTTPS Everywhere and Bitwarden at least, it'll ease my life!

Thank you devs!

**Comment by srirambv** [comment] 2021-08-16 04:22
Dupe of #4493

**Closed by srirambv** 2021-08-16 04:22 UTC
Labels: OS/Android
