### ISSUE TITLE
youtube ads

### ISSUE THREAD

**Issue by pipiscrew** [brave/brave-browser#8593] opened 2020-03-09 16:13 UTC
using the latest version (v1.4.96), youtube keep on the middle of the video showing ads... something that is not happening when addon **adblockplus** is active.

reading a [reply](https://community.brave.com/t/which-addons-does-brave-integrate/43838) on FEB 2019 by @tomlowenthal  :

> We do everything that HTTPS Everywhere does, most of what uBlock Origin or Ad Block Plus do in their default modes, some of what Privacy Badger does, and a bunch of things that none of them do. Our implementations are generally faster than theirs, because ours are native and theirs are add-ons. 

do you consider make this change ?

**Comment by rebron** [comment] 2020-05-01 15:23
Closing as duplicate of #3348.

**Closed by rebron** 2020-05-01 15:23 UTC
