### ISSUE TITLE
Crash: Mozilla documentation pages with embedded iframes kills entire browser

### ISSUE THREAD

**Issue by sos0** [brave/brave-browser#40329] opened 2024-08-07 01:37 UTC
### Description

- Not reproducible on incognito.
- Not reproducible on Google Chrome.

### Steps to reproduce

1. Open a new tab from a browser with an existing Brave Profile.
2. Visit https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input 
3. Scroll down (may not be needed)
4. Browser crashes

### Actual result

Navigating to [this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) is sufficient enough to crash the entire browser.

### Expected result

The link should load normally.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.134 Chromium: 127.0.6533.88 (Official Build) (arm64) 

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [X] in the latest version of Chrome

**Comment by zcraber** [comment] 2024-08-10 14:57
Possible duplicate of #40102

**Comment by kjozwiak** [comment] 2024-08-13 18:56
> Possible duplicate of #40102

Going to close this off as a duplicate as per the above. The above will be resolved by https://github.com/brave/brave-core/pull/25035 in the next `1.68.x` release which will occur sometime this week. If we don't get another `C127`, it will go out next week via `1.69.x`.

**Closed by kjozwiak** 2024-08-13 18:56 UTC
Labels: crash, priority/P2, OS/Desktop
