### ISSUE TITLE
Image from RSS Feed is not displayed

### ISSUE THREAD

**Issue by zsoerenm** [brave/brave-browser#21538] opened 2022-03-08 18:58 UTC
## Description 
Images from RSS Feed won't be displayed, if the image is encoded in `<content:encoded>`
See for example this feed: https://www.tagesschau.de/xml/rss2/
or this feed: https://www.heise.de/rss/heise.rdf
In both cases Brave News does not display an image, even though it is inside `<content:encoded>`.
Heise example:
```
<item>
  <title>
    Neue Prozessorgeneration von Apple: M1 Ultra mit zwei M1 Max
  </title>
  <link>
    https://www.heise.de/news/Neue-Prozessorgeneration-von-Apple-M1-Ultra-mit-zwei-M1-Max-6543050.html?wt_mc=rss.red.ho.ho.rdf.beitrag.beitrag
  </link>
  <description>
    Das neue Prozessor-Flaggschiff kombiniert zwei der leistungsstarken M1 Max mit einer Die-zu-Die-Verbindung.
  </description>
  <guid isPermaLink="true">http://heise.de/-6543050</guid>
  <pubDate>Tue, 08 Mar 2022 19:43:00 +0100</pubDate>
  <content:encoded>
    <p><a href="https://www.heise.de/news/Neue-Prozessorgeneration-von-Apple-M1-Ultra-mit-zwei-M1-Max-6543050.html?wt_mc=rss.red.ho.ho.rdf.beitrag.beitrag"><img src="https://www.heise.de/scale/geometry/450/q80//imgs/18/3/3/5/9/6/9/0/m1ultra-0a0cc6028bd0005c.png" class="webfeedsFeaturedVisual" alt="" /></a></p><p>Das neue Prozessor-Flaggschiff kombiniert zwei der leistungsstarken M1 Max mit einer Die-zu-Die-Verbindung.</p>
  </content:encoded>
</item>
```

## Steps to reproduce 

   1. Add https://www.tagesschau.de/xml/rss2/ to your RSS Feed
   2. Brave News shows feeds from Tagesschau without images.

## Actual result 
Brave News shows feeds from Tagesschau without images.

## Expected result
Brave News shows feeds from Tagesschau with images.

## Version/Channel Information:
Brave nightly 

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 7
   
## Brave version
Brave Nightly 1.38.28

**Comment by mattmcalister** [comment] 2022-03-10 16:24
Closing as duplicate of https://github.com/brave/brave-browser/issues/21589

**Closed by mattmcalister** 2022-03-10 16:24 UTC
Labels: priority/P3, OS/Android, feature/brave-news
