### ISSUE TITLE
Ad Block filter universal syntax broken

### ISSUE THREAD

**Issue by JakobJingleheimer** [brave/brave-browser#17013] opened 2021-07-17 10:37 UTC
## Description 

Until recently, excluding a domain prefix to a filter would cause that filter to be applied universally to all sites. For instance `##.foo` would block any element with a css classname of "foo" on _any_ site. This has stopped working.

Non-universal syntax still works (prepending the filter with a domain).

## Steps to Reproduce

1. Manually add a custom filter via `brave://adblock/` such as `##.foo`
1. Visit a site with an element with that class
1. Element is not blocked

## Actual result:

The custom filter is ignored

## Expected result:

The custom filter is applied

## Reproduces how often:

Easily reproduced

## Brave version (brave://version info)

Brave: V1.26.77 (it was broken in the previous version too)
OS: macOS 11.4 (ARM & Intel)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Maybe
- Can you reproduce this issue with the nightly channel? Maybe

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

N/A

**Comment by ryanbr** [comment] 2021-07-17 13:34
Can confirm. Add the following `github.com##.btn-primary` vs `##.btn-primary` (which hides the green button on https://github.com/brave/brave-browser/issues

cc: @antonok-edm

**Comment by JakobJingleheimer** [comment] 2021-08-31 21:29
Nudge. There have been multiple releases since this was reported a couple months ago. This was a great feature. Any chance of a fix soon?

**Comment by antonok-edm** [comment] 2021-09-07 21:11
Just looked into this. GitHub appears to have a `generichide` rule, which means that any global CSS rules should not be applied - this is working "as intended."

https://github.com/easylist/easylist/blob/36cd41e27b9bd46950f783e3ad0ae2f3d50fde52/easylist/easylist_allowlist.txt#L255

@ryanbr do you know what the intended way of reverting a `generichide` rule in another list is? Is `badfilter` the only option? If so, I don't think there's an easy way to prevent this behavior until later planned work where the adblock engines (default, regional, custom, etc.) will be combined into a single engine.

**Comment by ryanbr** [comment] 2021-09-07 23:04
@JakobJingleheimer   adding `github.com##.foo` rather than `##.foo` would get around this.   (specific to github.com in this case)
@antonok-edm Was added to prevent unintended cosmetics being used on Github in error. This was only recently implemented, the filter is quite new.

**Comment by ryanbr** [comment] 2021-09-07 23:10
As a test try `https://www.bleepingcomputer.com/` add `##.bc_logo` into brave://adblock (which should hide the logo, top left)

**Comment by antonok-edm** [comment] 2021-09-07 23:14
@JakobJingleheimer you're right, it does look like it happens on some other sites too - I think my changes in https://github.com/brave/brave-core/pull/9995/files#diff-e445b72318a833eb8c97e6945d9a13b3efc44710de6449146579c48da455711b might help as well.

**Comment by antonok-edm** [comment] 2021-09-08 18:01
I'll consider this fixed by https://github.com/brave/brave-core/pull/9995, but @JakobJingleheimer please let me know if there are still any problems with it in 1.31.x

**Closed by antonok-edm** 2021-09-08 18:01 UTC
Labels: feature/shields/webcompat, OS/Desktop

**Comment by JakobJingleheimer** [comment] 2021-09-10 17:30
@antonok-edm thank you! I shall check when it's released. I just checked, and it seems I have [the latest release of Brave (v1.29.79)](https://brave.com/latest/). I see in this repo though, that there are [more recent releases](https://github.com/brave/brave-core/releases), which I assume are Nightly? Or does this repo's version not correspond to Brave's version numbering?

**Comment by antonok-edm** [comment] 2021-09-10 17:56
Yes, at the moment 1.31.x is Nightly and 1.30.x is Beta. Our [release schedule](https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule) is on the wiki if you're curious.
