### ISSUE TITLE
Google Maps Highway/Freeway icons render incorrectly

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#37075] opened 2024-03-25 18:15 UTC
## Description 

When looking at Google Maps in Brave, the freeway/highway icons showing the names/numbers of these highways are rendered off-center:

In Brave
![image](https://github.com/brave/brave-browser/assets/3299098/e534607d-a252-47bf-ac8a-a54bc935733e)

In Chrome
<img width="1217" alt="image" src="https://github.com/brave/brave-browser/assets/3299098/be9e80a2-0db8-4aa8-8757-ac4b119d3fcb">

Note that all other icon types (as far as I can see) render correctly — it's only the highway/freeway signs.

## Reproduces how often: 

Always

## Brave version (brave://version info)

1.65.109 +

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment] 2024-03-25 21:04
cc: @ShivanKaul @arthuredelstein Looks like a fingerprinting issue. Toggling the fingerprinting setting seems to fix the issue.

**Comment by rogerdc** [comment] 2024-03-26 23:23
It can also be "fixed" by toggling hardware acceleration in settings as well. 

When I toggle just fingerprinting, the highway signs are better, but not fully fixed. If I toggle hardware acceleration, they appear completely normal. 

Fingerprint protection off, hardware acceleration off: 
![GM FingerprintingProtection off HardwareAcceleration off](https://github.com/brave/brave-browser/assets/4684857/363c1125-58a4-43ab-bdec-8088c98b7f99)

Fingerprint protection off, hardware acceleration on: 
![GM FingerprintingProtection off HardwareAcceleration on](https://github.com/brave/brave-browser/assets/4684857/7f6acfa6-abe7-40ab-8a47-2cb84c7251be)

Fingerprint protection on, hardware acceleration off: 
![GM FingerprintingProtection on HardwareAcceleration off](https://github.com/brave/brave-browser/assets/4684857/c3766b34-285c-4685-8df0-c22866f8fbb3)

Fingerprint protection on, hardware acceleration on:
![GM FingerprintingProtection on HardwareAcceleration on](https://github.com/brave/brave-browser/assets/4684857/4b66753b-79ae-44e2-81fe-3e8d6561c4c6)

**Comment by bobby-driggs** [comment] 2024-04-16 17:32
+1 for me: Brave version: 1.64.122

If I turn off hardware acceleration the icons render fine, but If I turn it back on they're messed up again.

With hardware acceleration on, if I go to the pages Brave Shield, and allow fingerprinting, then the icons render fine.

I am curious on what Google maps / brave is doing such that allowing fingerprinting renders the icons correctly?

**Comment by ShivanKaul** [comment] 2024-04-30 04:43
Just an update here that this is connected to Brave's canvas fingerprinting protections. If you disable "Block fingerprinting" this should be resolved. We're looking into a deeper fix, stay tuned.

**Comment by ShivanKaul** [comment] 2024-05-02 18:04
We merged in a scriptlet fix that caused Google Maps to fallback to 2D canvas, but looks like that's causing significant performance issues for some people. We will revert that, and fix this separately.

**Closed** 2024-05-03 18:12 UTC
Labels: bug, QA/Yes, release-notes/include, OS/Desktop, closed/fixed-by-component-update, webcompat/fingerprinting, webcompat/browser

**Comment by kjozwiak** [comment] 2024-05-06 03:37
The above requires `1.65.129` or higher for `1.65.x` verification 👍

**Comment by LaurenWags** [comment] 2024-05-07 12:23
Verification in progress with

```
Brave | 1.65.129 Chromium: 124.0.6367.118 (Official Build) (x86_64)
-- | --
Revision | 044ca9dfdf2f9053cb9a344d13924d255079e9a9
OS | macOS Version 13.6.6 (Build 22G630)
```

**Comment by GeetaSarvadnya** [comment] 2024-05-08 05:48
Verification **PASSED** on

```
Brave | 1.65.130 Chromium: 124.0.6367.159 (Official Build) (64-bit)
-- | --
Revision | 67843557ad274aba4b206391773c789c174b7fad
OS | Windows 10 Version 22H2 (Build 19045.4291)
```
Reproduced the issue on `1.65.126 Chromium: 124.0.6367.118`

![image](https://github.com/brave/brave-browser/assets/38657976/7b609f47-587c-41a0-bfc6-e96d2c40b71a)

Using the STR/information provided via https://github.com/brave/brave-browser/issues/37075#issue-2206388927, ensured that Google Maps was still loading/appearing correctly when using the default shield settings as per the following:

Brave  | Chrome
--------|--------
![image](https://github.com/brave/brave-browser/assets/38657976/4045b38e-370c-4264-9e26-24ed393d177d) | ![image](https://github.com/brave/brave-browser/assets/38657976/7ecdbb49-0cf1-4ca2-82b4-257669845262)

**Comment by dsmurl** [comment] 2025-03-17 03:43
Is there a way to fix this from the application side?  Can I change the imports for the scripts that support the google maps or something that fixes this occurring on my site?
