### ISSUE TITLE
Old stack tab layout

### ISSUE THREAD

**Issue by faragsamy2024** [brave/brave-browser#36381] opened 2024-02-26 22:45 UTC
It's been two years since we lost this feature, and I remember being promised that the feature would come back again, but nothing seems to happen.

Since then, I've been using Kiwi browser, which is open source, so it is doable to retrieve this feature, I don't understand why we still don't have this feature till now.

**Comment by bsclifton** [comment] 2024-03-05 23:30
I'm going to close this as a duplicate of https://github.com/brave/brave-browser/issues/22028

RE: can't understand why we still don't have this feature
The code was removed upstream (history in the issue above). We did make an attempt to bring the code back in (see https://github.com/brave/brave-core/pull/12684), but it's a lot maintenance-wise. We only have a limited set of developers / resources when it comes to Android, Chromium upgrading, and QA.

I would like to acknowledge this was a useful feature for folks and that we understand folks want it. Hopefully this resolves some of the doubt. Thanks!

**Closed by bsclifton** 2024-03-05 23:30 UTC
Labels: OS/Android
