### ISSUE TITLE
BR Panel still shows notification for grant even after grant claimed

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1637] opened 2018-10-17 01:24 UTC
## Description 
If you claim a grant from brave://rewards page and then later click on the BAT logo, the Brave Rewards Panel still displays the notification that a grant is waiting for you.

## Steps to Reproduce

   1. Clean profile on 0.55.16.
   2. Enable Rewards.
   3. From brave://rewards claim a grant.
   4. Open a new tab.
   5. Click on the BAT logo.

## Actual result:
Brave Rewards Panel shows that you have claimed a grant and also a notification that one is waiting for you:
<img width="384" alt="screen shot 2018-10-16 at 7 58 42 pm" src="https://user-images.githubusercontent.com/28145373/47056297-a7c17b80-d189-11e8-8824-e373972daaba.png">

## Expected result:
Once grant is claimed on brave://rewards, notification should not be displayed on panel.

## Reproduces how often: 
easy

## Brave version (brave://version info)

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? n/a - code not available there yet
- Does it reproduce on browser-laptop? n/a

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @NejcZdovc @jenn-rhim

**Comment by NejcZdovc** [comment] 2018-10-17 06:05
closing as dupe of https://github.com/brave/brave-browser/issues/1615

**Closed by NejcZdovc** 2018-10-17 06:05 UTC
Labels: bug, feature/rewards
