### ISSUE TITLE
Missing images in brave:rewards

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1869] opened 2018-10-26 22:55 UTC
## Steps to Reproduce

   1. Clean install
   2. Go to brave:rewards

## Actual result:

Images for Ads, Auto-Contribute, Tips are missing
![image](https://user-images.githubusercontent.com/34715963/47595800-664b8000-d982-11e8-9e3f-06587c8732f9.png)
![image](https://user-images.githubusercontent.com/34715963/47595806-6b103400-d982-11e8-99e9-a0fa8cc07844.png)

## Expected result:
![image](https://user-images.githubusercontent.com/34715963/47595853-a90d5800-d982-11e8-93c1-f83b2deecd59.png)

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.55.21 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows 7 x64

Reproduced on Win 10 x64 by @kjozwiak 
Not reproducible on Linux and Mac (checked by @kjozwiak and @srirambv )

### Reproducible on current release:
no

cc @NejcZdovc @GeetaSarvadnya @LaurenWags

**Comment by NejcZdovc** [comment] 2018-10-27 04:01
cc @bridiver I think that we need to pull your PR to 55 as well, because this was not a problem before

**Comment by NejcZdovc** [comment] 2018-10-27 16:38
this only happens on release, can't reproduce on 0.55.x branch directly

**Comment by kjozwiak** [comment] 2018-10-29 00:33
> this only happens on release, can't reproduce on 0.55.x branch directly

Getting the same results as @NejcZdovc, using Win 10 x64, went through the following:

* `0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)` - **couldn't reproduce**
* `0.56.6 Chromium: 70.0.3538.67 (Official Build) beta (64-bit)` - **couldn't reproduce**
* `0.55.21 Chromium: 70.0.3538.77 (Official Build) (64-bit)` - **reproduced**

**Comment by NejcZdovc** [comment] 2018-10-30 06:47
closing as this is not a problem in 56

**Closed by NejcZdovc** 2018-10-30 06:47 UTC
Labels: OS/Windows, QA/Yes, feature/rewards, regression

**Comment by GeetaSarvadnya** [comment] 2018-11-01 06:58
Verification Passed on

Brave | 0.56.7 Chromium: 70.0.3538.77 (Official Build) beta (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows
