### ISSUE TITLE
Brave crash on OSX 10.15.2 (19C57)

### ISSUE THREAD

**Issue by dziugasmikalkenas-home24** [brave/brave-browser#7797] opened 2020-01-17 11:41 UTC
## Description 

Crash after starting the application. Used latest stable build. Also tried with Nightly Channel v1.5.39

## Steps to Reproduce

   1. Downloaded latest stable version from https://laptop-updates.brave.com/latest/osx (also tried with Nightly Channel v1.5.39)
   2. Added to Applications.
   3. Start it.

## Actual result:

Application doesn't open. Console logs show:

```
default	13:27:16.243837+0200	Brave Browser	[0117/132716.243247:ERROR:file_io.cc(89)] ReadExactly: expected 8, observed 0
default	13:27:16.244102+0200	Brave Browser	[0117/132716.244032:ERROR:crash_report_database_mac.mm(96)] mkdir : No such file or directory (2)
default	13:27:16.251487+0200	Brave Browser	FRONTLOGGING: version 1
default	13:27:16.251511+0200	Brave Browser	Registering, pid=23655
default	13:27:16.253426+0200	Brave Browser	CHECKIN: pid=23655
default	13:27:16.264137+0200	Brave Browser	CHECKEDIN: pid=23655 asn=0x0-0x5d05d foreground=1
default	13:27:16.278614+0200	Brave Browser	Registered, pid=23655 ASN=0x0,0x5d05d
default	13:27:16.278739+0200	Brave Browser	Registered, pid=23655 cgConnectionID=38377
default	13:27:16.280040+0200	Brave Browser	BringForward: pid=23655 asn=0x0-0x5d05d bringForward=1 foreground=1 uiElement=0 launchedByLS=1 modifiersCount=1 allDisabled=0
default	13:27:16.280095+0200	Brave Browser	BringFrontModifier: pid=23655 asn=0x0-0x5d05d Modifier 0 hideAfter=0 hideOthers=0 dontMakeFrontmost=0 mouseDown=0/0 seed=0/0
default	13:27:16.280302+0200	Brave Browser	BringForward: pid=23655 asn=0x0-0x5d05d
default	13:27:16.280467+0200	Brave Browser	SetFrontProcess: asn=0x0-0x5d05d options=0
default	13:27:16.285331+0200	Brave Browser	Current system appearance, (HLTB: 1), (SLS: 0)
default	13:27:16.292268+0200	Brave Browser	Post-registration system appearance: (HLTB: 1)
default	13:27:16.431351+0200	Brave Browser	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x7fa066408d90
 (
    "<NSAquaAppearance: 0x7fa067a021e0>",
    "<NSSystemAppearance: 0x7fa067a02c30>"
)>
```

## Expected result:

App should open.

## Reproduces how often: 
Every time when trying to open application.

## Brave version (brave://version info)
Latest stable

## Version/Channel Information:
Same with Nightly Channel v1.5.39

**Comment by matthewpennell** [comment] 2020-01-20 19:08
+1

I'm experiencing crashes on OSX too, same version. For me it seems to be related to attempting to use Cmd key for anything - copy, paste, cmd+click to open in new tab, all randomly seem to crash the browser (not every time, but maybe 1 in 5).

**Comment by kjozwiak** [comment] 2020-07-14 19:29
@dziugasmikalkenas-home24 @matthewpennell it's been a while but are you guys still experiencing the above crashes? We've had several Chromium bumps and bug fixes since this issue was created so hopefully reliability has improved. I'll close off the issue in the next few days if I don't hear anything back.

**Comment by dziugasmikalkenas-home24** [comment] 2020-07-15 06:57
Tried this one: https://github.com/brave/brave-browser/releases/tag/v1.11.96

Still doesn't work, same issue. Gave up on this a while ago, so I don't mind if the issue is closed, especially since there are not that many reports on this. Well, at least not in this issue https://github.com/brave/brave-browser/issues/7797 anyways.

**Comment by matthewpennell** [comment] 2020-07-15 08:39
Can't help either, sorry - switched to Safari, and then eventually replaced the Mac with a new PC. Brave continues to work fine on my laptop though, it was just the desktop that was crashing.

**Comment by kjozwiak** [comment] 2020-07-15 16:30
Thanks @dziugasmikalkenas-home24 @matthewpennell, appreciate the feedback and apologies we couldn't fix this in a timely manner. We've been chasing macOS startup crashes for a while but having a hard time reproduce internally. CCing @bsclifton in case he has any more info as he's been looking into crashes.

@dziugasmikalkenas-home24 assuming you've updated to `macOS 10.15.5`? BTW, this is a startup crash correct?

**Comment by bsclifton** [comment] 2020-07-20 01:47
Hi folks - I'm curious if anyone has the accessibility keyboard enabled? There is for sure a known issue when that is enabled with it causing a crash. We have an open issue for this with a lot of good notes:
https://github.com/brave/brave-browser/issues/7546

**Comment by dziugasmikalkenas-home24** [comment] 2020-07-20 06:35
> Thanks @dziugasmikalkenas-home24 @matthewpennell, appreciate the feedback and apologies we couldn't fix this in a timely manner. We've been chasing macOS startup crashes for a while but having a hard time reproduce internally. CCing @bsclifton in case he has any more info as he's been looking into crashes.
> 
> @dziugasmikalkenas-home24 assuming you've updated to `macOS 10.15.5`? BTW, this is a startup crash correct?

Yes, I am running 10.15.5, and yes this is a startup crash. After clicking on Brave icon or launching via cli - nothing happens, it doesn't start.

**Comment by dziugasmikalkenas-home24** [comment] 2020-07-20 06:37
> Hi folks - I'm curious if anyone has the accessibility keyboard enabled? There is for sure a known issue when that is enabled with it causing a crash. We have an open issue for this with a lot of good notes:
> #7546

I don't think this is related, because browser doesn't even open.

**Comment by Housebound** [comment] 2020-07-23 14:23
> > Hi folks - I'm curious if anyone has the accessibility keyboard enabled? There is for sure a known issue when that is enabled with it causing a crash. We have an open issue for this with a lot of good notes:
> > #7546
> 
> I don't think this is related, because browser doesn't even open.

I use the accessibility keyboard on my iMac running OS 10.15.6 . This is essential for me as MS has now progressed to leave me unable to use my hands. I’m typing this with a mouth operated mouse. I am also using Brave latest build as well as Nightly Version 1.13.40 Chromium: 84.0.4147.89 (Official Build) nightly (64-bit). For example I have just clicked on Nightly and it has opened, clicked on 'Google' web page which opens successfully but when I then try to open another webpage - Crash....Writing this on Safari but would much prefer Brave.

**Comment by kjozwiak** [comment] 2020-07-31 04:07
@Housebound are you basically seeing https://github.com/brave/brave-browser/issues/7546#issuecomment-640800995? Sounds like the exact same issue.

**Comment by Housebound** [comment] 2020-07-31 08:36
I am currently using 'Nightly' in the hope that each upgrade will fix this issue but as yet no joy. I rely on the Mac accessibility keyboard so it’s been months of frustration.

**Comment by rebron** [comment] 2020-09-08 18:38
Closing as duplicate of #8149

**Closed by rebron** 2020-09-08 18:38 UTC
Labels: OS/macOS, bug, closed/duplicate, crash
