### ISSUE TITLE
Special URLs for top YouTubers not compatible with Brave

### ISSUE THREAD

**Issue by kirkins** [brave/brave-browser#2732] opened 2018-12-24 19:01 UTC
## Description 

Most users have a url in this pattern:

https://youtube.com/user/<name>

or

https://youtube.com/channel/<name>

Bart Baker, Philip De Franco, and other top YouTubers have a special URL without a prefix 

https://youtube.com/BartBaker

https://www.youtube.com/PhilipDeFranco

In addition to the normal url pattern.

As this url is an edge case it is not supported by Brave. Brave instead associates https://youtube.com/BartBaker with the YouTube website itself.

## Steps to Reproduce

   1. Go to https://youtube.com/BartBaker
   2. Open tip banner
   3. See it is associated with YouTube and not Bart Baker

## Actual result:

![](https://i.imgur.com/MW3Pd1r.png)

## Expected result:

Tip Bart Baker instead of YouTube.

## Reproduces how often: 

Always

## Brave version (brave://version info)

0.58.17 Chromium: 71.0.3578.98 (Official Build) unknown (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

No

**Comment by jnki** [comment] 2018-12-24 22:39
seems it's not just for top youtubers
I'm a nobody and my youtube url is in that format too.
https://www.youtube.com/jenoki
same issue happens of course

**Comment by srirambv** [comment] 2018-12-25 13:54
@kirkins can you verify this on 0.58.18? Also you might need to wait till the verified pubs list is downloaded. There would be some latency between the time you enable rewards and open the tip panel.

**Comment by NejcZdovc** [comment] 2018-12-27 06:15
closing as dupe of https://github.com/brave/brave-browser/issues/1886

**Closed by NejcZdovc** 2018-12-27 06:15 UTC
Labels: feature/rewards, need-more-info
