### ISSUE TITLE
Crash when restoring wallet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#38914] opened 2024-06-10 08:44 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.69.3 Chromium: 126.0.6478.40
Operating System: Android 14

URL (if applicable) where crash occurred: Wallet restore

Can you reproduce this crash? No, happened once

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Restore Wallet via seed
2. Enable only Bitcoin Testnet 
3. Finish onboarding, Wallet crashes
4. Doesn't load the wallet UI even after removing app from memory and restarting

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/e6a01200-f3b3-160c-0000-000000000000

cc: @simoarpe

**Comment by simoarpe** [comment] 2024-06-10 09:00
Do we have any other information about this crash? I'm not able to reproduce it following the provided steps.

* Is there a stacktrace available? 
* Was there a pending transaction to confirm?
* Was the crash observed on a physical or emulated device?
* Do we know which accounts should have been restored other than Ethereum and Solana?

**Comment by iefremov** [comment] 2024-06-11 12:29
@simoarpe this is a semi-automatically generated report. You can find all available details on backtrace, see https://share.backtrace.io/api/share/U5wamjq5x3Oip45kheCmrK2

to get the backtrace link filter by `rxid_ equal <crashid>`

**Comment by simoarpe** [comment] 2024-07-05 16:24
I was not able to observe this issue anymore. I'm closing this now.
If it comes up again, feel free to reopen.

**Closed by simoarpe** 2024-07-05 16:24 UTC
Labels: bug, crash, priority/P2, QA/Yes, release-notes/exclude, feature/web3/wallet
