### ISSUE TITLE
Unable to delete sites from Auto Contribute Table

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#1965] opened 2018-11-02 05:06 UTC
Upgraded From beta 0.20 to 0.22 on Brave-Core.
Had few sites as i was cleaning up the contribution table for testing.

Unable to remove any of the 4 sites left on the contribution table. I was able to delete 2 and now stuck with the 4 on the image

![image](https://user-images.githubusercontent.com/35932307/47894861-499bc600-de22-11e8-99ea-40ec6e60ebaf.png)

cc @kjozwiak @NejcZdovc

**Comment by NejcZdovc** [comment] 2018-11-04 17:18
I think this one is dupe of https://github.com/brave/brave-browser/issues/1693

**Closed by NejcZdovc** 2018-11-04 17:18 UTC
Labels: feature/rewards, priority/P3
