### ISSUE TITLE
Still no way to turn off Brave Shields on localhost

### ISSUE THREAD

**Issue by SilencerWeb** [brave/brave-browser#3290] opened 2019-02-09 04:08 UTC
## Description 
Still no way to turn off Brave Shields on localhost

## Brave version (brave://version info)
0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)

**Comment by srirambv** [comment] 2019-02-09 04:12
Dupe of  #1896.

**Closed by srirambv** 2019-02-09 04:12 UTC
