### ISSUE TITLE
Crash while opening brave://sync in incognito

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#15717] opened 2021-05-10 16:12 UTC
STR:
1. launch brave, open private or TOR window
2. navigate to brave://sync via omnibox
3. crash

current nightly

Brave | 1.26.11 Chromium: 90.0.4430.93 (Official Build) nightly (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}

current beta

Brave | 1.25.53 Chromium: 90.0.4430.93 (Official Build) beta (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}

 

https://brave.sp.backtrace.io/p/brave/debug?time=month&filters=((callstack.functions%2Ccontains%2CGetSyncStatusDictionary))&debug=(fb60eb,0)

```
[ 00 ] signin::IdentityManager::GetPrimaryAccountInfo(signin::ConsentLevel) const
[ 01 ] settings::PeopleHandler::GetSyncStatusDictionary() const
[ 02 ] settings::PeopleHandler::HandleGetSyncStatus(base::ListValue const*)
[ 03 ] content::mojom::WebUIHostStubDispatch::Accept(content::mojom::WebUIHost*, mojo::Message*)
[ 04 ] mojo::InterfaceEndpointClient::HandleValidatedMessage(mojo::Message*)

```

**Comment by mariospr** [comment] 2021-05-10 16:50
Just adding some extra info: checked today whether this could have been somehow caused by my mojo migration merged on Friday (see https://github.com/brave/brave-core/pull/8671), but it's not the case (i.e. reverted my changes and still got the crash)

Additionally, I've also checked as per a comment from @iefremov whether the change I proposed in https://github.com/brave/brave-core/pull/8731 could have an impact but, as I already suspected, it doesn't change a thing either.

**Closed** 2021-05-14 15:25 UTC
Labels: OS/Desktop, QA/Yes, crash, feature/sync, priority/P2, release-notes/exclude

**Comment by AlexeyBarabash** [comment] 2021-05-17 09:33
Uplifts are created but current Nightly `1.26.21` doesn't have the fix, will update here once the new Nightly build will be available.

**Comment by kjozwiak** [comment] 2021-05-18 01:49
@AlexeyBarabash just double checking, this fix was only for `Desktop` correct? I can't reproduce the crash using `1.26.21 Chromium: 91.0.4472.57` on `Android` but can reproduce it easily on `Desktop`.

**Comment by AlexeyBarabash** [comment] 2021-05-18 02:01
@kjozwiak yes, the fix is for Desktop only. On Android there is no crash.

**Comment by GeetaSarvadnya** [comment] 2021-05-20 12:23
Verification passed on

```

Brave | 1.24.86 Chromium: 90.0.4430.212&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.985)

```
- Verified the STR from https://github.com/brave/brave-browser/issues/15717#issue-884559503
- Ensured there is no crash in PT/TOR/Guest when brave://sync is opened via omnibox
