### ISSUE TITLE
Brave should be brave:// handler

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1774] opened 2018-10-22 12:31 UTC
## Description 

Clicking on brave:// links should open in Brave.

## Steps to Reproduce

   1. Post a brave:// link Slack like brave://flags
   2. Click on it

## Actual result:

Nothing happens after you click to allow to open the link in Slack.

## Expected result:

The link should open in Brave.

## Reproduces how often: 

Always

## Brave version (brave://version info)

0.55.18

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  yes
- Does it reproduce on browser-laptop?  n/a

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  no
- Is the issue reproducible on the latest version of Chrome?  n/a

### Additional Information

We need to register fro the brave:// protocol

**Comment by Liunkae** [comment] 2018-12-19 18:49
Duplicate of #326

**Closed** 2021-03-12 07:32 UTC
Labels: closed/duplicate, priority/P5
