### ISSUE TITLE
Wrong source lis hard coded!

### ISSUE THREAD

**Issue by grandtoubab** [brave/brave-browser#2176] opened 2018-11-18 08:27 UTC
Debian 10 Buster

## Description 
the source list  hard coded in postinstall script and /opt/brave.com/brave/cron/brave-browser script refer to google .
Why?

# sources.list setting for brave-browser updates.
REPOCONFIG="deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"

## Steps to Reproduce

   1. define source
deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ bionic main
   2. 
insatall key
curl https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key add -
   3. refresh source
sudo apt update
install brave
sudo apt install brave-browser

## Actual result:
the source file is broken
root@debian:/etc/apt/sources.list.d# cat brave-browser.list 
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main

## Expected result:

Don't touch the user source file please
## Reproduces how often: 
Each time

## Brave version (brave://version info)
apt policy brave-browser
brave-browser:
  Installé : 0.56.12
  Candidat : 0.56.12
 Table de version :
 *** 0.56.12 500
        500 https://brave-browser-apt-release.s3.brave.com bionic/main amd64 Packages
        100 /var/lib/dpkg/status

Consequence

Sudo apt purge brave-browser

Conclusion
Your work is not finished

**Comment by srirambv** [comment] 2018-11-20 04:30
Dupe of https://github.com/brave/brave-browser/issues/1084

**Closed by srirambv** 2018-11-20 04:30 UTC

**Comment by nkogkneeto** [comment] 2018-12-04 04:04
Using Fedora 29 here and I'm getting an invalid dnf/yum repo created after installing brave via Download page instructions

/etc/yum.repos.d/brave-browser.repo
`[brave-browser]
name=brave-browser
baseurl=http://dl.google.com/linux/brave-browser/rpm/stable/x86_64
enabled=1
gpgcheck=1
gpgkey=https://dl.google.com/linux/linux_signing_key.pub
`
