### ISSUE TITLE
unable to tip more than 100 BAT

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5884] opened 2019-09-04 01:52 UTC
## Description 
While testing user wallets I noticed that there's a notification on the Uphold authorization screen which says you will need to reauthorize once you have 100 BAT in transactions. After tipping 100 BAT to various verified/KYC'd publishers (so that the BAT left my wallet), when I tried to tip over the 100 BAT, I was not forced to reauthorize. I just got the generic tip error message.

## Steps to Reproduce

1. Clean install, enable rewards, connect KYC'd account
2. If account doesn't have at least 100 BAT in Brave Browser card, add it.
3. Tip sites until I've tipped 100 BAT to various sites.
4. Try to tip again.

## Actual result:
![Screen Shot 2019-09-03 at 9 32 28 PM](https://user-images.githubusercontent.com/28145373/64219737-b0e83380-ce94-11e9-954a-315a9a9ffbcc.png)

## Expected result:
Expected to be disconnected (green Verified would changed to gray Disconnected button) and notification about the wallet being unreachable would be displayed.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
Per discussion with @mandar-brave the limit was supposed to be increased. Possibly that didn't happen. Also, here's the uphold screen which mentions the 100 BAT limit:
![Screen Shot 2019-09-03 at 9 36 42 PM](https://user-images.githubusercontent.com/28145373/64219784-ea20a380-ce94-11e9-9f1a-1110d502d760.png)

**Comment by LaurenWags** [comment] 2019-09-04 02:11
Note - this also happens with the following STR:
1. Clean install, enable rewards, connect KYC'd account
2. If account doesn't have at least 100 BAT in Brave Browser card, add it.
3. Set monthly budget to 100 BAT. Visit only verified, KYC'd publishers.
4. Let contribution go thru.
5. Now try to tip a site.

![Screen Shot 2019-09-03 at 10 09 27 PM](https://user-images.githubusercontent.com/28145373/64220534-b7c47580-ce97-11e9-9307-fa43e69c5a5d.png)

**Comment by LaurenWags** [comment] 2019-09-04 02:11
When this is fixed, will need to check that you actually get put in Disconnected state once you hit the transaction limit because right now there are errors when trying to do over 100 BAT in transactions.

**Comment by NejcZdovc** [comment] 2019-09-17 15:09
@mandar-brave what should we do?

**Comment by mandar-brave** [comment] 2019-09-17 15:30
@NejcZdovc even if we hit Uphold limits, we need to ask user to re-auth and reset the token with a fresh 100 BAT. By failing and no re-authing;
a) we can't retry the current transaction
b) we will fail on every future transaction

Do we not get a clear error when we hit the limits.

**Comment by NejcZdovc** [comment] 2019-09-17 17:50
I mean not sure how re-auth would work if limit for one time is 100. So if user want's to do 150 will Uphold even allow it?

**Comment by mandar-brave** [comment] 2019-09-17 21:07
@NejcZdovc re-authing token resets value to allow new set of transactions up to 100.
Uphold is moving default ceiling to 250 BAT which will help.

Uphold setting for token expiry now is > 250 BAT transactions or 2 months, whichever comes first. At that point user has to re-auth to get token expiry reset.

**Comment by NejcZdovc** [comment] 2019-09-18 04:59
@mandar-brave yes I am aware of that, what I am saying if user want's to tip 500 BAT this will not go through not re-auth will work as limit is max to 250. We need to limit tip amounts on publisher side to match uphold amounts so user will not be put in this situation

**Comment by mandar-brave** [comment] 2019-09-18 05:00
Fair! we will have to cap Creator max to 250 BAT for the moment!

**Comment by marshall** [comment] 2020-12-02 17:24
duplicate of #3718

**Closed by marshall** 2020-12-02 17:24 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/rewards, needs-discussion
