### ISSUE TITLE
DevTools - "Panel layout" preference is no longer saved

### ISSUE THREAD

**Issue by cyress** [brave/brave-browser#19530] opened 2021-11-17 15:03 UTC
## Description 
The DevTools settings for the "Panel layout" preference (`DevTools > Settings > Preferences > Appearance > Panel Layout`) is no longer saved or reset to the default value each time the DevTools are opened.
This behavior occurs in the normal and private browser window.

## Steps to Reproduce
1. Open a website (e.g. https://brave.com/)
2. Open the DevTools (for example via the keyboard shortcuts)
macOS: <kbd>Command</kbd>+<kbd>Option</kbd>+<kbd>I</kbd>
Win: <kbd>Control</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>
3. Open the DevTools settings (gear-icon in the upper right)
4. Change the selected default value for the `Panel layout` preference from `auto` to `horizontal`
5. Close the DevTools settings
6. The panels under `Elements` are now horizontally aligned
7. Close the DevTools
8. Reopen the DevTools
9. The panels under `Elements` are aligned automatically and the setting for `Panel layout` is back to `auto`

## Actual result:
After changing the `Panel layout` preference default value, closing and reopening the DevTools the selected value is reset to the default value `auto`.

## Expected result:
After changing the `Panel layout` preference, closing and reopening the DevTools the previous selected value is still set and the `Elements` panels are still aligned accordingly.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | macOS Version 12.0.1 (Build 21A559)

## Version/Channel Information:
- Can you reproduce this issue with the current release? **YES**
- Can you reproduce this issue with the beta channel? **N/A**
- Can you reproduce this issue with the nightly channel? **N/A**

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? **No**
- Does the issue resolve itself when disabling Brave Rewards? **No**
- Is the issue reproducible on the latest version of Chrome? **No**
  - This behavior does not occur in the latest Chrome version (96.0.4664.45)

**Comment by it-can** [comment] 2021-11-26 08:05
I have a similair problem, some devtools settings are not saved, like ```Log XMLHttpRequests``` very annoying, also on the latest mac os x

**Comment by jdahdah** [comment] 2021-11-26 11:05
Can't change the theme of DevTools to dark mode either. I just says "*reload required" when I change the setting, but there is no reload button and neither opening & closing DevTools nor restarting Brave have any effect.

**Comment by xyzith** [comment] 2022-01-12 03:09
I have same problem. Add custom device won't save either.

**Comment by laamp** [comment] 2022-01-20 03:18
I've also been experiencing this problem. It seems to be specific to Brave. This bug doesn't seem to currently exist in Chrome.

**Comment by bsclifton** [comment] 2022-03-18 07:59
Should be fixed with https://github.com/brave/brave-core/pull/12600 - duplicate of https://github.com/brave/brave-browser/issues/20491

**Closed by bsclifton** 2022-03-18 07:59 UTC
Labels: OS/Desktop
