### ISSUE TITLE
how do i enable hardware accelerated video decoding on manjaro ?

### ISSUE THREAD

**Issue by D0nnieD4rk0** [brave/brave-browser#17588] opened 2021-08-20 09:00 UTC
ive tried practically everything at this point even enabling vulkan in about://flags (which should be taking care of everything but it doesnt cover video decoding for some reason) please ive looked practically everywhere and cant find a solution

**Comment by Dark-Matter7232** [comment] 2021-08-20 16:58
## Here are the steps
1: ```sudo su```
2: ```pacman -S lbva gstreamer libva-intel libva-utils``` 
3: ```echo "export LIBVA_DRIVER_NAME=radeonsi" >> /etc/environment``` (if you are amd user) or ```echo "export LIBVA_DRIVER_NAME=i965" >> /etc/environment``` (if you are intel user)
4: ```rm -rf /usr/share/applications/brave-browser.desktop```
5: ```cd /usr/share/applications/```
6: ```wget https://p.anuragcodes.me/ibhw4QH3 -O brave-browser.desktop```
7: ```exit```
8: **Profit**  

### Note
If you wish to launch brave from command line, add this alias ```alias brave="brave  --use-gl=desktop --enable-features=VaapiVideoDecoder"```

**Comment by rebron** [comment] 2021-08-20 20:36
Closing as dupe of https://github.com/brave/brave-browser/issues/17564

**Closed by rebron** 2021-08-20 20:36 UTC
Labels: OS/Desktop

**Comment by D0nnieD4rk0** [comment] 2021-08-21 11:33
> ## Here are the steps
> 1: `sudo su`
> 2: `pacman -S lbva gstreamer libva-intel libva-utils`
> 3: `echo "export LIBVA_DRIVER_NAME=radeonsi" >> /etc/environment` (if you are amd user) or `echo "export LIBVA_DRIVER_NAME=i965" >> /etc/environment` (if you are intel user)
> 4: `rm -rf /usr/share/applications/brave-browser.desktop`
> 5: `cd /usr/share/applications/`
> 6: `wget https://p.anuragcodes.me/3I197vuv -O brave-browser-vaapi.desktop`
> 7: `exit`
> 8: go to brave://flags, enable `Override software rendering list`
> 9: **Profit**
> 
> ### Note
> If you wish to launch brave from command line, add this alias `alias brave="brave --use-gl=desktop --enable-features=VaapiVideoDecoder"`

does any other driver other than 1965 like iHD work with brave ?

**Comment by Dark-Matter7232** [comment] 2021-08-21 17:35
> > ## Here are the steps
> > 1: `sudo su`
> > 2: `pacman -S lbva gstreamer libva-intel libva-utils`
> > 3: `echo "export LIBVA_DRIVER_NAME=radeonsi" >> /etc/environment` (if you are amd user) or `echo "export LIBVA_DRIVER_NAME=i965" >> /etc/environment` (if you are intel user)
> > 4: `rm -rf /usr/share/applications/brave-browser.desktop`
> > 5: `cd /usr/share/applications/`
> > 6: `wget https://p.anuragcodes.me/3I197vuv -O brave-browser-vaapi.desktop`
> > 7: `exit`
> > 8: go to brave://flags, enable `Override software rendering list`
> > 9: **Profit**
> > ### Note
> > If you wish to launch brave from command line, add this alias `alias brave="brave --use-gl=desktop --enable-features=VaapiVideoDecoder"`
> 
> does any other driver other than i965 like iHD work with brave ?

they do

**Comment by D0nnieD4rk0** [comment] 2021-09-18 17:39
the results are all the same 
rn im wondering how many distros have the same shit desighn as manjaro cuz if its all of em im done with linux

**Comment by D0nnieD4rk0** [comment] 2021-09-18 17:40
too bad i cant reopen the issue

**Comment by Samueru-sama** [comment] 2023-01-13 20:19
> wget https://p.anuragcodes.me/3I197vuv -O brave-browser-vaapi.desktop

This gives me an error. Is it down?

**Comment by Dark-Matter7232** [comment] 2023-01-26 15:20
> > wget https://p.anuragcodes.me/3I197vuv -O brave-browser-vaapi.desktop
> 
> This gives me an error. Is it down?

yes
