### ISSUE TITLE
Updater process behaving like malware

### ISSUE THREAD

**Issue by georgir** [brave/brave-browser#22993] opened 2022-05-22 11:14 UTC
After installing Brave, I got this BraveUpdate.exe process constantly running on my PC. This is unacceptable, any application should by default only run when I start it explicitly and not do things to my computer on its own, especially since I've not even made it my default browser.

**Comment by diracdeltas** [comment] 2022-05-23 02:56
cc @mherrmann

**Comment by mherrmann** [comment] 2022-05-23 05:19
Hi @georgir, we're aware of this and have begun looking at solutions. You can see more details and follow our progress in https://github.com/brave/brave-browser/issues/21745. I'll close this issue as a duplicate of that other one.

**Closed by mherrmann** 2022-05-23 05:19 UTC
