### ISSUE TITLE
Remove dApp detection for nytimes.com and calendar.google.com

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#12709] opened 2020-11-15 14:58 UTC
## Description 

Users are being prompted for Crypto Wallet on the New York Times website (https://nytimes.com). Issue is similar to https://github.com/brave/brave-browser/issues/11865 (which dealt with archive.org). 

## Steps to Reproduce

(edited by bbondy)
   1. Navigate to https://nytimes.com, you need to be signed up for an account. @diracdeltas has an account.
   2. Alternately, use calendar.google.com which also has the Dapp prompt when it shouldn't

## Expected result:

**No** Crypto Wallets bar should appear.

## Actual result:

The Crypto Wallets bar appears.

## Reproduces how often: 

Very easily. Reproduced on first try on Version 1.16.72 Chromium: 86.0.4240.183 (Official Build) (x86_64), MacOS.

## Brave version (brave://version info)

Version 1.16.72 Chromium: 86.0.4240.183 (Official Build) (x86_64)

Also reproduced on Version 1.18.51 Chromium: 87.0.4280.49 (Official Build) beta (x86_64)

**Comment by rebron** [comment] 2020-11-16 17:37
dupe of https://github.com/brave/brave-browser/issues/12482?

**Comment by bsclifton** [comment] 2020-11-19 18:46
cc: @marshall

**Closed** 2020-12-04 20:45 UTC
Labels: OS/Desktop, QA/Yes, feature/crypto-wallets, release-notes/include

**Comment by btlechowski** [comment] 2020-12-09 10:55
`QA/Blocked` till we get a new build (> 1.18.69)

**Comment by btlechowski** [comment] 2020-12-09 13:54
Verification passed on

Brave | 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified test plan from the description
Crypto wallet bar is not shown

![image](https://user-images.githubusercontent.com/34715963/101638298-2c3c7b80-3a2e-11eb-9ab2-1ffd3b1ea15d.png)
