### ISSUE TITLE
[Android] Show `brave://` in URL bar instead of `chrome://`

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#18431] opened 2021-09-29 14:17 UTC
## Description

Pages like `brave://rewards` and other `brave://` will show `chrome://` in the URL bar on Android. 

## Solution

Make sure `brave://` is always shown in URL bar.

**Comment by srirambv** [comment] 2021-09-29 15:18
Dupe of #9427

**Closed by srirambv** 2021-09-29 15:18 UTC
Labels: feature/rewards, priority/P4, OS/Android, parity
