### ISSUE TITLE
gpu difference between chrome and brave

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6506] opened 2019-10-16 17:34 UTC
## Description 
`Viz Hit-test Surface Layer` is different on Chrome and Brave for the same chromium version.

This has been the case for me for several versions (using macOS), but @kjozwiak sees them as the same on his macOS. I'm currently using High Sierra, he has Mojave.

## Steps to Reproduce

   1. Open Brave, visit brave://gpu
   2. Open Chrome which is using same chromium version as your Brave instance, visit chrome://gpu
   3. Compare `Viz Hit-test Surface Layer` setting.

## Actual result:
They differ.
Using C77:
<img width="1474" alt="gpu-compare-c77" src="https://user-images.githubusercontent.com/28145373/66943356-f31a9e00-f018-11e9-8bca-8c2f1e7506f4.png">

Using C78:
<img width="1548" alt="gpu-compare-c78" src="https://user-images.githubusercontent.com/28145373/66943375-fada4280-f018-11e9-9bbd-d342521bad10.png">

## Expected result:
Expected them to be the same.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | macOS Version 10.13.6 (Build 17G5019)

Brave | 0.71.94 Chromium: 77.0.3865.90 (Official Build) dev (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

Brave | 0.73.1 Chromium: 78.0.3904.50 (Official Build) nightly (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes 0.69.135, yes 0.70.117 
- Can you reproduce this issue with the beta channel? unsure, probably
- Can you reproduce this issue with the dev channel? yes (0.71.94 is my dev version)
- Can you reproduce this issue with the nightly channel? yes (0.73.1 is my nightly version)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? no

## Miscellaneous Information:
cc @bsclifton @kjozwiak

**Comment by btlechowski** [comment] 2019-10-16 18:32
Not reproducible on Ubuntu 


Brave | 0.70.117 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Linux

![image (2)](https://user-images.githubusercontent.com/34715963/66947938-0c8d0b80-f054-11e9-8d40-88a1fa8aa3e0.png)

**Comment by kjozwiak** [comment] 2019-10-16 22:01
Originally when I was comparing `0.70.117 CR: 78.0.3904.50` against `Chrome 78.0.3904.50`, I received the same results when viewing `brave://gpu` & `chrome://gpu`. Example:

<img width="914" alt="Screen Shot 2019-10-16 at 12 14 04 PM" src="https://user-images.githubusercontent.com/2602313/66962176-5bc84180-f03e-11e9-8600-90775b9c8955.png">

However, Google pushed a new CR78 a ~3-4hrs ago and `Viz Hit-test Surface Layer` are different when comparing `0.70.117 CR: 78.0.3904.50` against `Chrome 78.0.3904.63`. Example:

<img width="1280" alt="Screen Shot 2019-10-16 at 5 53 22 PM" src="https://user-images.githubusercontent.com/2602313/66962325-b8c3f780-f03e-11e9-88b7-703a99293c02.png">

Perhaps we're being placed into field trails in Chrome where `Viz Hit-test Surface Layer` is being enabled? Really wished there was a mapping for the variations in `chrome://version`.

**Comment by GeetaSarvadnya** [comment] 2019-10-18 03:43
The issue is Reproduced in Windows 10 x64 - `0.70.118`

![image](https://user-images.githubusercontent.com/38657976/67064267-85d94b00-f187-11e9-90c5-6d451545c67d.png)

**Comment by LaurenWags** [comment] 2019-10-18 16:06
@GeetaSarvadnya to confirm, you are comparing Chrome 78 to Brave using Chromium 78, correct?

**Comment by mkarolin** [comment] 2019-10-21 22:24
From what I can tell, this feature is still disabled by default in C78. The change to enable it by default is here: https://chromium.googlesource.com/chromium/src/+/55112a03100d6f33ce83a84e9df89db94bcf4356 and has only landed in C79 (https://storage.googleapis.com/chromium-find-releases-static/551.html#55112a03100d6f33ce83a84e9df89db94bcf4356).

I thought that the feature is then enabled in Chrome via experiments, but when I check chrome://flags this particular one is set to Default for me. 

There's also this curious tidbit in `chrome/test/chromedriver/chrome_launcher.cc`:
<pre>
    // In theory the following switch should have no effects, but its absence
    // would cause VizHitTestSurfaceLayer feature to be enabled on Chromium
    // builds, causing a test failure due to https://crbug.com/996865.
    "force-fieldtrials",
</pre>

So, I think the feature is properly disabled in our build, but I can't quite tell why it is enabled in Chrome.

**Comment by bsclifton** [comment] 2019-10-22 20:40
Good call, @mkarolin - this might be a `wontfix` 👍 Field trials would explain the different

@GeetaSarvadnya confirmed it was C78 earlier- I'm curious what variations are exposed. You can view those by visiting chrome://version in Chrome. If you see entries there, it's possible one is for VizHitTestSurfaceLayer

**Comment by rebron** [comment] 2019-11-19 19:38
Closing out as wontfix. Difference is Chrome has fields trial enabled likely changing these values for some users.

**Closed by rebron** 2019-11-19 19:38 UTC
Labels: OS/macOS, QA/Test-Plan-Specified, QA/Yes
