### ISSUE TITLE
Ads (not sponsored NTPs) do not work on the Wayland display server

### ISSUE THREAD

**Issue by TheCultLeader666** [brave/brave-browser#16318] opened 2021-06-09 19:47 UTC
## Description 

Notification ads do not work when running the Wayland display server, but work fine on XOrg. 

## Steps to Reproduce

   1. Start up a desktop environment such as GNOME on the Wayland display server
   2. Wait for an ad to appear, see none, check logs and see errors 
   3. Relog and this time use the XOrg display server
   4. See ads

## Actual result:

Ads do not show, and this error appears in the rewards logs:
`[Jun 08, 2021, 1:54:02.0 PM:ERROR:publisher.cc(763)] Publisher info not found`

## Expected result:

Ads show, and no error appears

## Reproduces how often: 

easy

## Brave version (brave://version info)

Brave | 1.26.54 Chromium: 91.0.4472.88&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | 109e9cd038b94a631aea7d40ee3d56c1278f2597-refs/branch-heads/4472@{#1385}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Yes
- Can you reproduce this issue with the nightly channel
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Does the issue resolve itself when disabling Brave Rewards? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A

## Miscellaneous Information:

#16109 
This is not a personal issue, as I have seen someone on Reddit with the same problem, and the issue has also persisted between distros and installations.

**Comment by Bundy01** [comment] 2021-06-09 20:05
I use Cinnamon (xorg) and the ads are still blocked :/

**Comment by TheCultLeader666** [comment] 2021-06-09 20:07
> I use Cinnamon (xorg) and the ads are still blocked :/

Sorry I thought I had figured it out, but this is probably still a problem that should be addressed. Have you tried using the nightly build? I know there are new custom ad notifs there

**Comment by Bundy01** [comment] 2021-06-09 21:31
Good point. I just tested nightly and it works. I get the ads and no error in rewards-internals.

**Comment by Digitalone1** [comment] 2021-06-14 11:56
I thought this was fixed with custom ad notification, which are available in nighty, but not in release yet. 

@tmancey Am I wrong? Were custom ad notifications tested on Wayland?

**Comment by tmancey** [comment] 2021-06-14 16:56
Custom ads are under test in nightly and beta for Linux. Not all users will see custom ad notifications at this time. I have only tested on official builds. However as custom ad notifications are unrelated to system notifications I expect them to work.

**Comment by Digitalone1** [comment] 2021-06-14 17:05
Custom ad notifications should be the only way to get BAT ads on Linux Wayland since system ad notifications are broken.

**Comment by tmancey** [comment] 2021-06-14 17:22
I only test official packages. right now as above custom ads are being tested and will roll out to more users if the tests are successful. Thank you

**Comment by TheCultLeader666** [comment] 2021-06-14 18:27
I would argue that Arch is a major distribution to overlook, especially since you have official packages for lesser used distros like openSUSE

**Comment by TheCultLeader666** [comment] 2021-06-14 18:32
> However as custom ad notifications are unrelated to system notifications I expect them to work.

You might not be able to count on this, because browser notifications still work perfectly on Wayland currently, it's just the ads that fail to show and throw errors in the log

**Comment by Digitalone1** [comment] 2021-06-14 18:42
> I would argue that Arch is a major distribution to overlook, especially since you have official packages for lesser used distros like openSUSE

It's not really needed to have packages for every distribution. Brave on AUR is the one labeled as "Linux" on the release list, so can be considered as official. And the rpm/deb packages for Fedora/Ubuntu can be used on Arch too, the only difference is the folder where files are stored.

> You might not be able to count on this, because browser notifications still work perfectly on Wayland currently, it's just the ads that fail to show and throw errors in the log

But they closed the issues related to Wayland because of the custom ad notifications. So I assume they have tasted them on Wayland... or I hope so, at least,

**Comment by TheCultLeader666** [comment] 2021-06-14 18:49
> Brave on AUR is the one labeled as "Linux" on the release list, so can be considered as official.

It's explicitly labeled as "unofficial"

**Comment by TheCultLeader666** [comment] 2021-06-14 18:49
> Brave on AUR is the one labeled as "Linux" on the release list, so can be considered as official.

It's explicitly labeled as "unofficial"

**Comment by Digitalone1** [comment] 2021-06-14 18:58
> > Brave on AUR is the one labeled as "Linux" on the release list, so can be considered as official.
> 
> It's explicitly labeled as "unofficial"

That's the page on the website, but in github releases it's not labelled as unofficial: brave-browser-1.25.72-linux-amd64.zip

Anyway, you can still install rpm/deb packages in Arch, the PKGBUILD should be slightly modified, but it's possible. Google Chrome on AUR is made from the official deb package.

**Comment by Digitalone1** [comment] 2021-06-15 11:05
> I only test official packages.

Where do you test them? I suggest Ubuntu 21.04 or Fedora 34 which default to use Wayland.

**Comment by tmancey** [comment] 2021-07-26 14:35
During a screen-share with https://github.com/brave/brave-browser/issues/17159 I noticed that Wayland is not triggering idle events. @aseren any ideas?

**Comment by Digitalone1** [comment] 2021-07-27 15:51
Don't know if it is of any help, but chromium engine does not support Wayland natively (different from Firefox), it's using Xwayland. Experimental native support is added with Ozone platform, but it seems not resolving the system ad notification issue. 

Does custom ad notification solve it permanently and independently from any display server on Linux?

**Comment by tmancey** [comment] 2021-07-28 14:07
@Digitalone1 thank you

**Comment by tmancey** [comment] 2021-07-30 20:45
Closing as a duplicate of https://github.com/brave/brave-browser/issues/13866

**Closed by tmancey** 2021-07-30 20:45 UTC
Labels: OS/Desktop, feature/ads, needs-investigation
