### ISSUE TITLE
Browser Closes Randomly

### ISSUE THREAD

**Issue by Cloverwave** [brave/brave-browser#24165] opened 2022-07-20 22:34 UTC
Nothing complicated.

I recently watched the 2018 Tetris Effect playstation trailer, i was instantly hooked.
So, i went to github to see if I could pirate it, (couldn't). Broadening my search,
I searched Tetris on Github and it instantly closed. Did this many times, same result.

halp?
(no idea what is wrong with this).

**Comment by Ryan-Goldstein** [comment] 2022-07-20 22:38
Also reported here: https://github.com/brave/brave-browser/issues/24164

**Comment by rebron** [comment] 2022-07-21 00:07
Closing as dupe of #24164

**Closed by rebron** 2022-07-21 00:07 UTC
Labels: OS/Desktop
