### ISSUE TITLE
Playback Popup When Changing Volume

### ISSUE THREAD

**Issue by dmoa** [brave/brave-browser#6166] opened 2019-09-25 16:27 UTC
#3436  Steps to Reproduce

Simply have a youtube tab open, or any playback type of website, and change volume from anywhere, even other applications!

## Actual result:
![braveq](https://user-images.githubusercontent.com/44374106/65620309-7ec08200-dfb9-11e9-925f-4a226fb637e8.PNG)

Is there any way to disable this?

Any help is appreciated!

**Comment by rebron** [comment] 2019-09-26 16:49
dupe of https://github.com/brave/brave-browser/issues/5220?

**Comment by dmoa** [comment] 2019-09-26 18:52
sure.
Is there a solution though?

**Comment by dmoa** [comment] 2019-09-30 15:39
> dupe of #5220?

is there a solution though?

**Comment by dmoa** [comment] 2019-09-30 15:41
Ok, got it working after looking at this:
[https://www.reddit.com/r/brave_browser/comments/cbx93y/posting_again_anyone_else_having_this_problem_not/](reddit thread)

If that link dies, here is the tutorial for anyone else:

1. Type brave://flags into the address bar
2. Search for a flag called #hardware-media-key-handling
3. Disable the flag and relaunch the browser when prompted.

**Closed** 2019-09-30 15:42 UTC

**Comment by bsclifton** [comment] 2019-09-30 16:50
@dmoa thanks for digging in - that was supposed to have been disabled... maybe existing profiles kept the old setting

Sorry that you ran into it, but also thank you for sharing 😄 I put your steps into the prior issue we had captured:
https://github.com/brave/brave-browser/issues/5220
