### ISSUE TITLE
Browser apps (Shortcuts) crashing immediately on start

### ISSUE THREAD

**Issue by dudutwizer** [brave/brave-browser#14759] opened 2021-03-16 10:17 UTC
## Description 
Brave Browser App crash on launch.

## Steps to Reproduce

   1.  Open any web-based application, i.e web.whatsapp.com
   2. Click on "More tools" -> "Create Shortcut"
   3. Try to launch the app
   
## Actual result:
The new window of the webpage/app open then immediately crash 

## Expected result:
Should stay open

## Reproduces how often: 
Easily reproduced

## Version/Channel Information:
Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (x86_64)

## Other Additional Information:

Console message:
`identifier=app_mode_loader, pid=5335, auid=501, euid=501, binary_path=/Users/*username*/Applications/Brave Browser Apps.localized/WhatsApp.app/Contents/MacOS/app_mode_loader attempted to call TCCAccessRequest for kTCCServiceAccessibility without the recommended com.apple.private.tcc.manager.check-by-audit-token entitlement`

macOS: BigSur 11.2.3 (20D91)

**Comment by Brave-Matt** [comment] 2021-04-15 17:59
+1 on Community:
https://community.brave.com/t/chrome-apps-crashing-brave/234077

**Comment by Greigh** [comment] 2021-04-15 18:36
I am the above Community Brave member, it seems that it happens in Chrome as well. So it must be a Chromium issue.

**Comment by iefremov** [comment] 2021-05-14 11:14
probably a dupe of https://github.com/brave/brave-browser/issues/7205

**Closed by iefremov** 2021-05-14 11:14 UTC
Labels: OS/Desktop, OS/macOS, crash
