### ISSUE TITLE
Add support for keyboard remapping

### ISSUE THREAD

**Issue by AustinGitHub** [brave/brave-browser#29516] opened 2023-04-05 06:36 UTC
Hi, 

As an avid user of both windows and mac (more mac than windows nowadays). I would find it very handy if there was a way to remap our keys on the brave browser. Brave automatically sets the keys for the users whereas I can use powerToys on windows application to remap my keys but they don't get remapped over to brave browser because it's being restricted. Can you please add support for this. 

Mainly because I'd like to remap my alt key and control key on my windows since then I can make it similar to my mac keyboard. Being a programmer and using laptop all day, swapping between OS's gets very confusing on the hands. Would appreciate if I could remap my keys. My remapped keys works on chrome browser, but brave browsers alters the key mapping and this is bit frustrating. Thanks!

**Comment by rebron** [comment] 2023-04-06 23:34
Will be closing as dupe of https://github.com/brave/brave-browser/issues/354 
We're in process with a fix via brave://commands and in settings Did you mean this as a feature request to carry over preferences/keyboard mappings from powerToys?

**Comment by AustinGitHub** [comment] 2023-04-07 00:51
@rebron Yes, or if I can remap on brave itself that is fine too, it doesn't need to carry over from powerToys

**Comment by rebron** [comment] 2023-04-25 16:43
Dupe of #354 https://github.com/brave/brave-browser/issues/29349

**Closed by rebron** 2023-04-25 16:43 UTC
Labels: closed/duplicate, OS/Desktop
