### ISSUE TITLE
Monthly tip value is not trimmed in Rewards Panel

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4502] opened 2019-05-20 15:44 UTC
Followup to https://github.com/brave/brave-browser/issues/2245

## Steps to Reproduce

   1. Clean install
   2. Join Rewards
   3. Go to `kjozwiak.github.io`
   4. Set a monthly tip of 1 BAT
   5. Re-Open Rewards panel

## Actual result:

After `1.0 BAT` there is `(`
![image](https://user-images.githubusercontent.com/34715963/58034223-5960ca80-7b26-11e9-9ded-9712da71dfad.png)

## Expected result:
Just `1.0 BAT` is shown

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.65.97 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @ryanml @NejcZdovc

**Comment by LaurenWags** [comment] 2019-05-20 17:14
Reproduced on macOS

Brave | 0.65.97 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

**Comment by NejcZdovc** [comment] 2019-05-21 05:02
closing as dupe of https://github.com/brave/brave-browser/issues/4503

**Closed by NejcZdovc** 2019-05-21 05:02 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/rewards

**Comment by GeetaSarvadnya** [comment] 2019-08-02 11:45
Verification passed on


Brave | 0.68.115 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-ui/pull/489
- Verified the STR mentioned in the description

![image](https://user-images.githubusercontent.com/38657976/62367999-e8d42200-b548-11e9-9501-53c7f60ba013.png)

![image](https://user-images.githubusercontent.com/38657976/62368023-f7bad480-b548-11e9-844d-1a32ca306dc7.png)

![image](https://user-images.githubusercontent.com/38657976/62368074-1faa3800-b549-11e9-8a37-69ae934f5401.png)
