### ISSUE TITLE
Linux GTK+ Dark makes low contrast in menu

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#7245] opened 2019-12-06 11:09 UTC
## Description 

From certain point I see low contrast text in menus with my old settings `Brave colors: Dark; Themes: GTK+` on Ubuntu 16

## Steps to Reproduce

   1. Take Ubuntu 16, install Brave Beta/Dev/Nightly 
   2. Setup the settings like
![image](https://user-images.githubusercontent.com/24739341/70318047-c53b2400-1827-11ea-888e-50e1567deffe.png)

## Actual result:

   3. Click menu button in top-right corner, see
![image](https://user-images.githubusercontent.com/24739341/70318143-0a5f5600-1828-11ea-85c5-c2b17339ec73.png)
The same is for the context menu
![image](https://user-images.githubusercontent.com/24739341/70318774-7f7f5b00-1829-11ea-96e5-765f609ce189.png)

## Expected result:
   3. On Stable version this gives 
![image](https://user-images.githubusercontent.com/24739341/70318374-8e194280-1828-11ea-894d-f75ff8446a69.png)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.4.5 Chromium: 79.0.3945.56 (Official Build) nightly (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:
With Dark+Classic all is good 
![image](https://user-images.githubusercontent.com/24739341/70318549-fc5e0500-1828-11ea-9371-07225a1c48fa.png)

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

CC @petemill

**Comment by btlechowski** [comment] 2019-12-10 19:32
Reproduced on Ubuntu 18.04 LTS. This is reproducible with `GTK+` theme and not with default `Classic` theme

Brave | 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)
-- | --
Revision | 99b6d241cf84f7fa7434ae8a59f9e74eb1464280-refs/branch-heads/3945@{#888}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/70562127-1763a880-1b8c-11ea-9e92-0884e950f30d.png)
![image](https://user-images.githubusercontent.com/34715963/70562140-1af72f80-1b8c-11ea-96ed-4912a1f170b2.png)


Not reproducible on 

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

cc @rebron @brave/legacy_qa

**Comment by srirambv** [comment] 2019-12-10 19:54
Pretty sure this is Unity related issue. No such issue with Ubuntu 19.04 
![Screenshot from 2019-12-10 14-40-18](https://user-images.githubusercontent.com/17010094/70563835-f6379380-1b5c-11ea-84a0-c1b9101b7b08.png)

**Comment by eldk** [comment] 2019-12-14 21:28
Hello,

https://community.brave.com/t/linux-update-gives-unreadable-menus-black-on-black/98141

Thanks,

Eric

**Comment by timolson** [comment] 2019-12-18 18:25
From a user perspective, this problem makes Brave unusable.  Please prioritize.  Comment written using Firefox, because this problem has forced me to switch.  -_-

**Comment by rebron** [comment] 2019-12-18 19:34
cc: @simonhong Can you take a look?

**Comment by simonhong** [comment] 2019-12-18 21:36
@rebron Ok, I confirmed that this doesn't happen on my local with `GNOME Shell` (Ubuntu 19.04)
will check with `Unity`.

**Comment by Nicolab** [comment] 2019-12-21 23:31
Thanks @simonhong 
Do you know when there will be an update fixing this issue in the stable release?

**Comment by simonhong** [comment] 2019-12-22 00:33
@Nicolab If the fix(https://github.com/brave/brave-core/pull/4261) is merged only `1.4 nightly`, `February 25, 2020` is the 1.4 stable target release date.
If we uplift this to current beta(`1.2` or `1.3`), you can get this more quickly.
(FYI, our release schedule -  @https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule)
Do we want uplifting this? @rebron

**Comment by Nicolab** [comment] 2019-12-23 09:45
Ok thank you @simonhong

**Closed** 2019-12-23 23:20 UTC
Labels: OS/Linux, QA/Yes, feature/user-interface, priority/P4, regression

**Comment by rebron** [comment] 2019-12-24 17:47
@simonhong Yes, can you create uplifts for 1.2 and 1.3. 
@Nicolab 1.2 in release is targeted for week of January 6th.

**Comment by Nicolab** [comment] 2019-12-29 00:19
Great! Thanks @rebron

**Comment by btlechowski** [comment] 2020-01-03 15:47
Verification passed on

Brave | 1.2.40 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4261

![image](https://user-images.githubusercontent.com/34715963/71732782-6a0d4900-2e48-11ea-8785-535305ac76b9.png)
https://github.com/brave/brave-core/pull/4261
![image](https://user-images.githubusercontent.com/34715963/71732924-b062a800-2e48-11ea-881a-bf5eea351607.png)

**Comment by timolson** [comment] 2020-01-22 19:28
The "Save Password" dialog is still suffering this issue.
