### ISSUE TITLE
Lost BATs

### ISSUE THREAD

**Issue by m-kru** [brave/brave-browser#7981] opened 2020-01-30 10:19 UTC
`Linux arch 5.4.10-arch1-1 #1 SMP PREEMPT Thu, 09 Jan 2020 10:14:29 +0000 x86_64 GNU/Linux`

`Brave Browser 79.1.2.43 unknown`

Yesterday I had 0.3 BAT, but suddenly the value has been reset to 0.0. I thought that maybe after the next BAT increase the value will be fixed (0.4), however right now it indicates 0.1.
![bats](https://user-images.githubusercontent.com/26227737/73440572-c719f300-4351-11ea-8e13-5a93ea55069e.png)

I do not understand how this happened as Auto-Contribute setting is off, I haven't set any Monthy Contributions and I haven't tipped anyone.
![settings_bat](https://user-images.githubusercontent.com/26227737/73440632-e749b200-4351-11ea-92cd-36b5b85b349b.png)

What is interesting is the fact, that Brave correctly displays information about the ads that have been presented to me (except the timestamp).
![ads](https://user-images.githubusercontent.com/26227737/73440722-1d873180-4352-11ea-8b79-1c1c62c564d3.png)

Can anyone explain me what has happened and where is my 0.3 BAT :smiley:?

**Comment by tmancey** [comment] 2020-01-30 10:25
@m-kru Are you available for a screen-share so I can investigate, if so, can you please email me @ tmancey@brave.com

**Comment by m-kru** [comment] 2020-01-30 10:34
@tmancey If I screen-share you will have access to more than Brave. I do not like this idea.

**Comment by tmancey** [comment] 2020-01-30 10:36
@m-kru We use Zoom for screen-sharing, and we do not have access to your computer unless you grant this. I will not need to control your computer, and I can guide you.

Let us try to work out the issue without a screen-share if that makes you feel better.

Can you please take a screenshot of the Ads panel at brave://rewards/

**Comment by m-kru** [comment] 2020-01-30 10:38
@tmancey 
![d](https://user-images.githubusercontent.com/26227737/73442396-0f86e000-4355-11ea-9303-b3f33f2bd20c.png)

**Comment by tmancey** [comment] 2020-01-30 10:41
Thank you.

Could you please let me know your locale?

Would you be happy to send me the following files via email (please check the files in a text editor before sending to make sure you are happy with the privacy):

`Default/ads_service/client.json`
`Default/rewards_service/confirmations.json`

Alternatively, I just need to view these files on your screen.

**Comment by m-kru** [comment] 2020-01-30 10:47
@tmancey sent.

**Comment by tmancey** [comment] 2020-01-30 10:58
@m-kru 

Can you please send screenshots of your systems locale and time zone as here I am seeing 0.3 BAT using your profile, so I need to ascertain what is different about our systems. Thanks for your help it is much appreciated

**Comment by m-kru** [comment] 2020-01-30 11:05
@tmancey done.

**Comment by bzrudi** [comment] 2020-01-30 13:04
Just want to second this behaviour. I lost 0.2 or 0.3 BAT yesterday. Today I get new rewards counted but the ones from yesterday seem lost.
Brave Info:
Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
Locale: de_DE
OS: Ubuntu 19.10
I can also second that the date in the Ads History info screen is wrong and defaults 1/1/1970.

**Comment by tmancey** [comment] 2020-01-30 16:14
@m-kru @bzrudi We have found the cause of the issue. I am closing this issue as it is rectified at our end, and our support team will reach out. Thank you, Terry

**Comment by m-kru** [comment] 2020-01-30 19:52
@tmancey you have written the issue was fixed server-side, however this evening I had the same story .I have lost 0.1 BAT that I have earned today.

**Comment by diposs** [comment] 2020-01-31 01:31
Crazy questions would all the lost bat be rebound or just the lucky ones to bind after the server-side fix was implemented. 
This problem has existed for days. I think first report on the 27th January 17:29.
https://community.brave.com/t/half-my-bat-rewards-disappeared/104125 
So if it takes 24hours to bind lets say since 26th January, and today is 30th that is about 3 days worth of ads to reconcile.
Brave confirmation binds every 24 hours.

**Comment by tmancey** [comment] 2020-01-31 09:31
@diposs Can you please send me the diagnostic information at brave://rewards-internals to tmancey@brave.com

**Comment by tmancey** [comment] 2020-01-31 09:32
> @tmancey you have written the issue was fixed server-side, however, this evening I had the same story. I have lost 0.1 BAT that I have earned today and it is 0.0 again.

@m-kru Sorry to hear this has happened again, I am investigating and will be in touch

**Comment by tmancey** [comment] 2020-01-31 09:33
@m-kru @bzrudi Can you please send me the diagnostic information at brave://rewards-internals to tmancey@brave.com

**Comment by diposs** [comment] 2020-02-02 00:05
@tmancey I have no issue as I am based in Nigeria but just wanted you to know it was first reported on the 27th. Happy to see the needful has been done by this post issued https://community.brave.com/t/estimated-pending-rewards-bug-january-31-2020/104727

**Comment by tmancey** [comment] 2020-02-04 02:10
Closing issue as it is now resolved server-side, thank you

**Closed by tmancey** 2020-02-04 02:10 UTC
Labels: QA/No, feature/ads, needs-investigation, priority/P1
