### ISSUE TITLE
Add X-Brave-Partner to CORS-safelisted request header

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#6021] opened 2019-09-15 12:58 UTC
With pre-flighted request for CORS being enabled in Chromium we need to add X-Brave-Partner header to the safe listed request header to avoid Allow-Cross-Origin-Request-Headers error.

**Comment by bsclifton** [comment] 2019-09-15 20:49
Closing as duplicate of https://github.com/brave/brave-browser/issues/5952

**Closed by bsclifton** 2019-09-15 20:49 UTC
