### ISSUE TITLE
Can't read google play books

### ISSUE THREAD

**Issue by jrizz43** [brave/brave-browser#5289] opened 2019-07-18 19:46 UTC
## Description 

Cannot open a book from google play books due to cookies getting the following error

## Steps to Reproduce

   1. go to play.google.com/books
   2. click on any of my books
   

## Actual result:

![image](https://user-images.githubusercontent.com/22685746/61486933-4de52080-a96a-11e9-828d-85d5e4a03129.png)

## Reproduces how often: 

Every time

## Brave version (brave://version info)

0.66.100 Chromium: 75.0.3770.142 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:
I have followed the steps on adding the site to allowed cookies and refreshed/restarted and it doesn't resolve the issue
- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment] 2019-07-18 19:52
Looks like we're blocking books.googleusercontent.com

**Comment by rebron** [comment] 2019-07-18 19:53
cc: @ryanbr

**Comment by ryanbr** [comment] 2019-07-19 03:32
Can reproduce. Only quick fix is tuning of 'Allow all cookies'. I didn't see any tracking blocks being active.

@jrizz43 Just allow all cookies in the Sheilds, see if that helps. (it worked for me)

**Comment by jrizz43** [comment] 2019-07-19 12:15
Yeah that fixes it but would be nice if we didn't have to do that. Thanks
for the info!

**Comment by ryanbr** [comment] 2021-02-26 01:27
@jrizz43  Is this still reproducible?

**Comment by ryanbr** [comment] 2021-04-21 00:22
Re-tested this, and I'm unable to reproduce this, no shield changes needed to reading books. I have 9 books in my catalog, none caused issues when browsing the pages of the books.

@jrizz43  Closing this ticket, do retest with default shields settings.

**Closed by ryanbr** 2021-04-21 00:22 UTC
Labels: feature/shields/webcompat, google, priority/P3, workaround/allow-all-cookies
