### ISSUE TITLE
Cannot enable Twitter web notifications after update to v0.60.55

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#3464] opened 2019-02-22 21:54 UTC
## Description 

After the update to v0.60.55 (release), Twitter web notifications no longer function in Brave. This is not strictly because they don't function - but rather because they can't be set from within your Twitter profile settings.

## Steps to Reproduce
   1. Login to Twitter.com in Brave
   2. On Twitter, `Profile --> Settings & Privacy --> Web Notifications`
   3. Click `Turn on` to enable web notifications for Twitter
   4. Page prompts you to select `Allow` in browser modal - do so.

## Actual result:

After clicking allow, the page refreshes and changes are not saved. Notifications are not enabled and the page looks as if you had just arrived there, but now the `Turn on` button is unresponsive.

## Expected result:
Web notifications should be enabled.

## Reproduces how often: 

Always

## Brave version/Reproducible on 
Current release: Yes - v0.60.55 
Dev/Beta builds: Yes - v0.62.6/v0.61.36

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

Initial user report was very detailed and well written, found here. I also attached short recording of the behavior.
https://community.brave.com/t/unable-to-turn-on-twitter-web-notifications/45690/3

![twitternotis](https://user-images.githubusercontent.com/3299098/53273564-2e8ee380-36a9-11e9-8127-ee68fa617eeb.gif)

**Comment by rashbaugh3** [comment] 2019-03-05 04:52
I did a Safeboot with Networking and only opened Brave, not Firefox. Same problem with Twitter notifications.

**Comment by bbondy** [comment] 2019-03-05 15:24
@Brave-Matt is this still an issue?

**Comment by Brave-Matt** [comment] 2019-03-12 17:04
@bbondy @rebron 
Just tested on v0.61.51 and it is still an issue - in fact, the option to click the "web notifications" button is no longer present and now displays the following message:
![image](https://user-images.githubusercontent.com/3299098/54220216-26f37b00-44ae-11e9-8c2d-4156d52bf857.png)

**Comment by siffreinsg** [comment] 2019-08-06 15:36
Still an issue in the new Twitter UI. It will ask for permission, however the "switch" (see screen) stays off and the animation seems broken.
![image](https://user-images.githubusercontent.com/25729768/62554021-b1c77e80-b870-11e9-8da5-5ad21de968f1.png)

**Comment by jonathansampson** [comment] 2019-08-12 04:54
Worth noting that this issue exists even when the Brave and Rewards extensions are disabled:
```
> brave.com --disable-brave-extension --disable-brave-rewards-extension
```

**Comment by bsclifton** [comment] 2019-08-12 06:03
Likely a duplicate of https://github.com/brave/brave-browser/issues/2301

I'm curious if Twitter is trying to push a message and making sure you acknowledge it before enabling (or browser would prompt you first time, "allow notifications from x?")

**Comment by Miyayes** [comment] 2019-10-27 04:17
+1 https://www.reddit.com/r/BATProject/comments/dnay4q/when_will_the_twitter_notifications_bug_be_fixed/f59b6mk/?context=3

**Comment by Brave-Matt** [comment] 2019-12-06 23:55
Still an issue: 
https://community.brave.com/t/unable-to-activate-browser-notifications/94142/4

**Comment by thommesborg** [comment] 2019-12-16 06:43
Still an issue, yes. When I click on "enable push notifications" I'll get informed that my **browser won't support push-notifications**. 

Here's a screenie of the result:
<img width="1355" alt="Bildschirmfoto 2019-12-16 um 07 39 23" src="https://user-images.githubusercontent.com/40795115/70884928-a4b55b80-1fd7-11ea-9d6d-fffaeeeb5fa5.png">

**Comment by rashbaugh3** [comment] 2019-12-16 07:40
Issue not resolved as a side effect of other updates. Gonna need specific attention.

**Comment by bsclifton** [comment] 2020-01-07 22:30
Closing as a duplicate of https://github.com/brave/brave-browser/issues/2362

**Closed by bsclifton** 2020-01-07 22:30 UTC
Labels: priority/P3, webcompat
