### ISSUE TITLE
Dragging clickable element breaks click in general

### ISSUE THREAD

**Issue by tmvkrpxl0** [brave/brave-browser#38310] opened 2024-05-14 05:32 UTC
## Description 

If I drag any clickable element, Brave no longer responds to click

## Steps to Reproduce

   1. Go to random website
   2. Drag element
   3. It's now unusable

## Actual result:

https://github.com/brave/brave-browser/assets/41675181/e22f8408-ad60-4f8c-9624-62b7ad32f4d8

## Expected result:
It should work normally

## Reproduces how often: 

Easily reproduced, It happens always.
Too easy in fact I sometimes do this accidentally while clicking.

## Brave version (brave://version info)

Brave: 1.65.132 Chromium: 124.0.6367.202
Revision: ef7b9d19db96d7f4363674bbcd02b74c5f055091
OS: Linux
## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
Yes
- Can you reproduce this issue with the nightly channel? 
Untested

## Other Additional Information:
It used to be fine on x11, this started to happen after I switched to wayland.
- Does the issue resolve itself when disabling Brave Shields? 
No, but irrelevant.
- Does the issue resolve itself when disabling Brave Rewards? 
Untested, but irrelevant as well.
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

I always launch brave with those flags:
`brave-browser --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime`

**Comment by tmvkrpxl0** [comment] 2024-05-14 05:35
In the video, after I dragged, the mouse is stuck in "hold"
I am clicking various element but it doesn't register

**Comment by tmvkrpxl0** [comment] 2024-05-16 03:49
I misread issue template and answered wrongly: it doesn't fix itself when I disable shield.

**Comment by rebron** [comment] 2024-05-16 21:37
@tmvkrpxl0 Are you still seeing an issue with our latest release 1.66.110?

**Comment by bsclifton** [comment] 2024-05-16 21:57
Something you might try @tmvkrpxl0 is to visit brave://settings/appearance and then try changing what is used. So you can pick GTK theme for example.  This might not fix the issue - but worth a try.  You can try changing the value to different settings and please let us know

**Comment by tmvkrpxl0** [comment] 2024-05-17 01:49
> @tmvkrpxl0 Are you still seeing an issue with our latest release 1.66.110?

1.66.110 is not yet available on stable channel for me yet. I instead tested with beta channel whose version is higher. It works fine there. so I think yes?

**Comment by Neon095** [comment] 2024-05-18 08:30
I hava that exact same issue as well, im on kde arch and it only happens when using wayland

**Comment by Daniel-S-Allen** [comment] 2024-05-26 17:33
Still facing this issue on Arch with Plasma 6 and Wayland in version 1.66.115-1. Problem seems to be fixed on beta, but was not fixed in 1.66.110

**Comment by bsclifton** [comment] 2024-06-04 16:31
Sounds like this is fixed in Beta (1.67) and newer... 

@fallaciousreasoning @fmarier can you reproduce with release but not Beta / Nightly? If so, we can close this out and put in 1.67 milestone for QA verification

**Comment by fmarier** [comment] 2024-06-04 19:34
I can't reproduce on `1.67.100 Chromium: 125.0.6422.112 (Official Build) beta (64-bit) `.

**Comment by fallaciousreasoning** [comment] 2024-06-05 00:19
I can't repro in 1.68

**Comment by bsclifton** [comment] 2024-06-05 19:00
OK great - I'll close this and put into the 1.67 milestone for QA testing. No change on our side - was likely an upstream bug/fix

**Closed by bsclifton** 2024-06-05 19:00 UTC
Labels: OS/Linux, needs-more-info, OS/Desktop

**Comment by bsclifton** [comment] 2024-06-05 19:09
Found the upstream bug 😄 Fix is in Chromium 126
https://issues.chromium.org/issues/336449364
