### ISSUE TITLE
Unable to claim grants from both BR panel and Rewards settings page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3382] opened 2019-02-15 11:46 UTC
## Description 
Unable to claim grants from both BR panel and Rewards settings page. After multiple click on `claim` button in BR panel notification, captcha doesn't display. In Rewards settings page `CLAIM` button will not be shown untill we reload the page for 3 to 4 times, this is not stable, sometimes button will be shown immediately. Click on `CLAIM` button in rewards settings page also doesn't show captcha.

*Note* : Verified the versions `0.60.28`, `0.60.27`, `0.60.26`, `0.60.25` ,`0.60.23`, `0.60.19` and `0.59.35` - Seeing the same behaviour, unable to claim grants from BR panel as well as from Rewards settings page.

## Steps to Reproduce

   1. Clean profile `0.60.29`
   2. Enable grants through Rewards panel
   3. Click on `claim` button in rewards panel notification
   4. Observer that no captcha display
   5. Click on `CLAIM` button in rewards settings page
   6. Observer that no captcha display

## Actual result:

Unable to claim grants as there is no CAPTCHA display. 

![unable to claim grants - 0 60 29](https://user-images.githubusercontent.com/38657976/52854411-554a9880-3144-11e9-9532-1867dd6bee6f.gif)

## Expected result:
Should be able to claim grants from both BR panel and Rewards settings page

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.60.29 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 10

### Reproducible on current release: Yes
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

@brave/legacy_qa @NejcZdovc @evq

**Comment by NejcZdovc** [comment] 2019-02-15 11:49
@GeetaSarvadnya if this is reproducible on release something is going on with the server

**Comment by srirambv** [comment] 2019-02-15 11:51
I was able to see the CATPCHA come up on BR panel when i clicked 3-4 on claim button but it had the target change 3-4 times as well. After that it didnt show the CAPTCHA again.

**Comment by kjozwiak** [comment] 2019-02-15 16:36
@srirambv @GeetaSarvadnya can you guys try this on `0.59.35` and see if you can reproduce?

**Comment by GeetaSarvadnya** [comment] 2019-02-18 07:48
@kjozwiak Issue is still reproducible on both 0.59.35 and 0.60.34 - production environmnet.
Since it's server side issue i am removing release blocking label. @kjozwiak Thanks!

**Comment by GeetaSarvadnya** [comment] 2019-02-21 13:07
1+ https://community.brave.com/t/cannot-claim-you-have-a-grant-waiting-for-you/45622/4

**Comment by NejcZdovc** [comment] 2019-03-07 10:19
closing this one as I think nothing can be done here

**Closed by NejcZdovc** 2019-03-07 10:19 UTC
Labels: closed/not-actionable, feature/rewards

**Comment by kjozwiak** [comment] 2019-03-07 15:54
@NejcZdovc assuming this was related to a server side issue?

**Comment by NejcZdovc** [comment] 2019-03-07 15:57
correct, it looks like server error

**Comment by iller75** [comment] 2019-03-14 16:31
Got this issue still, running the latest version and can't claim my token grant.

**Comment by samgiligich** [comment] 2019-04-09 19:45
Me too!

**Comment by kjmagill** [comment] 2019-04-26 06:55
Still experiencing this issue on 0.63.48 (Official Build) (64-bit). First ~10 attempts did nothing, and now the 'Claim' button has disappeared from both the BR Panel & Rewards settings page without any captcha/confirmation/etc

**Comment by LaurenWags** [comment] 2019-04-26 14:43
@kjmagill I'm fairly certain the promo for that notification has probably ended. I think you're encountering what is described here - https://github.com/brave/brave-browser/issues/3761. So in the event that a grant promotion has ended, we should notify the user.

**Comment by kjmagill** [comment] 2019-04-26 18:38
@LaurenWags Thanks for the explanation. That makes sense, since I've had Brave installed for some time but just recently switched Rewards back on & seen the Claim message.

**Comment by LaurenWags** [comment] 2019-04-26 18:45
no problem, thanks for reporting. I'm going to link your original comment to the issue for tracking.

**Comment by benhall847** [comment] 2019-04-28 15:15
I seem to never receive notifications for reward claims.
I've used brave for a couple years now and I've never been able to claim rewards.
Only just now am I receiving BAT from ads.
