### ISSUE TITLE
Add support for VLOG to help reduce noise in logs for INFO

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#3663] opened 2019-03-11 16:09 UTC
## Description 
We should create a separate VLOG macro (with Chromium matching log levels) for ads that proxies back to the client. See LOG macro for implementation.

Example implementation for ledger: https://github.com/brave/brave-core/pull/1479

**Comment by tmancey** [comment] 2020-01-20 13:06
Closing issue as a duplicate of https://github.com/brave/brave-browser/issues/7242

**Closed by tmancey** 2020-01-20 13:06 UTC
Labels: feature/ads, priority/P3
