### ISSUE TITLE
Swap button indefinitely disabled on unknown error

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#19738] opened 2021-11-25 16:27 UTC
Swap button stuck in loading state indefinitely in case of an unknown error.

https://user-images.githubusercontent.com/3684187/143476076-3addb875-fa56-4357-a834-311539a1b546.mov

**Comment by srirambv** [comment] 2021-11-26 02:38
Dupe of #19730

**Closed by srirambv** 2021-11-26 02:38 UTC
Labels: bug, priority/P2, QA/Yes, release-notes/include, feature/wallet, OS/Desktop, front-end-change
