### ISSUE TITLE
[Feature] Restart Shortcut

### ISSUE THREAD

**Issue by asddsaz** [brave/brave-browser#1459] opened 2018-10-08 23:47 UTC
Feature: A Hotkey for restarting brave

Whenever I'm in TOR, I press ctrl-u and it wiped the data and restarts. I would be awesome to have the same thing in Brave.

**Comment by srirambv** [comment] 2018-10-09 00:54
Dupe of #1010

**Closed by srirambv** 2018-10-09 00:54 UTC
Labels: feature/tor, priority/P5, suggestion
