### ISSUE TITLE
Sidebar navigation

### ISSUE THREAD

**Issue by sudipghimire533** [brave/brave-browser#7146] opened 2019-11-28 13:10 UTC
## Description 
Feature request to add a side bar like opera do in our brave. Plus a option to add own site there.

## Steps to Reproduce

   1. Open Brave
   2. Try to pin website to sidebar
   3. Null Reasult

## Actual result:
Not Sucess

## Expected result:
Got the side bar to open messenger while prowsing other sites.

## Reproduces how often: 
Every Time

## Brave version (brave://version info)

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Linux
JavaScript | V8 7.8.279.23

## Version/Channel Information:
all channel

- Can you reproduce this issue with the current release?
yes
- Can you reproduce this issue with the beta channel?
yes
- Can you reproduce this issue with the dev channel?
yes
- Can you reproduce this issue with the nightly channel?
yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
no
- Does the issue resolve itself when disabling Brave Rewards?
no
- Is the issue reproducible on the latest version of Chrome? 
yes

**Comment by bsclifton** [comment] 2019-12-13 06:53
@sudipghimire533 are you proposing being able to pin any website you visit to a sidebar? (which could be shown/hidden). And once pinned, you'd be able to navigate like the regular site?

We have a few other sidebar projects that are mildly related https://github.com/brave/brave-browser/issues/464, https://github.com/brave/brave-browser/issues/1063

**Comment by k3mist** [comment] 2020-03-15 07:15
@bsclifton i think he's referring to this; https://blogs.opera.com/desktop/2015/03/sidebar-extensions-speed-dial-syncing-customizable-shortcuts-opera-developer-29/

initially i know many users would be simply happy with the ability to view/manage bookmarks and history. honestly would be a great addition. especially for researchers.

we have so much horizontal room but the google team refuses to add support even though most modern websites only use about 60-70% of the available screen width for readability.

https://bugs.chromium.org/p/chromium/issues/detail?id=20785
https://bugs.chromium.org/p/chromium/issues/detail?id=45365

and probably dozens more tickets if you search hard enough

its truly a waste of space

![Screenshot_20200315_030226](https://user-images.githubusercontent.com/439440/76697146-9e339000-6669-11ea-8a25-1f6fccd973de.png)

the only workaround right now is [this chrome extension](https://chrome.google.com/webstore/detail/bookmark-sidebar/jdbnofccmhefkmjbkkdkfiicjkgofkdh/) which is actually quite good. but due to recent security updates some chromium versions ago it no longer can integrate directly into the browser and its basically just an overlay 

![Screenshot_20200315_030836](https://user-images.githubusercontent.com/439440/76697217-f15a1280-666a-11ea-9b1e-46c403222bcf.png)

**Comment by bsclifton** [comment] 2020-05-12 19:26
Thanks @k3mist - will close this as a duplicate of https://github.com/brave/brave-browser/issues/464 (unless I misunderstood something). Subscribe there for updates 😄

**Closed by bsclifton** 2020-05-12 19:26 UTC
Labels: feature-request, needs-more-info
