### ISSUE TITLE
Rendering a website according to web standards

### ISSUE THREAD

**Issue by kuckir** [brave/brave-browser#41552] opened 2024-10-10 16:52 UTC
### Description

Is there any chance that Brave will render my website according to web standards? You can find the web standards at https://www.w3.org/

### Steps to reproduce

1. Open www.photopea.com 

### Actual result

Website looks like this:
![Image](https://github.com/user-attachments/assets/6c620966-f63d-4b02-93c3-33271e1b889a)

### Expected result

It should look like this: 
![Image](https://github.com/user-attachments/assets/0d0582d7-8af5-45da-b91e-c315b8db7b53)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Latest: Version 1.70.126 Chromium: 129.0.6668.100 (Official Build) (64-bit)

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

As I undrstand, you are trying to stretch the website, in order to make my ads invisible. However, if people decide to pay me for Premium and I remove ads, you still stretch the editor, making it unusable: 
![Image](https://github.com/user-attachments/assets/01c68dcf-3f0d-4edf-9355-1e603eafda30)

Many people reported it to me, and I don't know how to help them :( 

https://www.reddit.com/r/photopea/comments/1fzs0xa/comment/lr3nhu5/
https://github.com/photopea/photopea/issues/7226

I understand, that you think it is wrong for creators of websites to make money. But if you decide to remove ads, at least do it properly and don't make the life of your users harder.

P.S. I had to write this from a different Github account, since you have blocked my original account @photopea many years ago, when I was discussing a different bug here.

**Comment by not-nullptr** [comment] 2024-10-10 20:45
https://saastrappers.com/interviews/ivan-kutskir-photopea/ you do not get to complain about "creators of websites making money" when you pull in $200,000 a MONTH. this issue is disingenuous at best

**Comment by kuckir** [comment] 2024-10-10 23:47
@not-nullptr I disagree with you. If a person is offering me an apple for X dollars, the fact that the person already made 1$ / 1000$ / $100000000 selling apples does not give a right to steal that apple from the person.

**Comment by not-nullptr** [comment] 2024-10-11 00:19
if this issue is about ad blocking then why fish for sympathy with that comment about the brave developers thinking it's wrong for website creators to make money?

**Comment by fl0werpowers** [comment] 2024-10-11 13:30
The "stretching" seems to be related to a specific ad provider shown. I can replicate the issue in Arc with uBlock Origin by refreshing the page: sometimes it renders correctly, other times it doesn't.

**Comment by Afrodark** [comment] 2024-10-20 07:46
"i don't understand why you think you have the right to complain about adblockers when you already earn so much money"

You do not understand this, because of the collective socialist belief, that someone is evil, because he earns a lot of money. This comes from one of the 7 sins, the envy (one of the worst). That's how this thoughts are born.

At least "Greed" (if you want to call it so), brings prosperity and thrive to humanity, because of the desire of reaching more. This leads to more taxes paid and more money for the government, who shares it. 

Every product and service needs to be paid, it doesn't matter if public or private. Charity cannot pay everything.

**Comment by XOCODE-OP** [comment] 2024-10-20 13:20
guys GUYS,
it's a technical issue, I don't care how much money someone makes or how. Let's focus on the bug at hand.

So I appreciate Brave blocking these ads very successfully, however I am a paid customer for this and now you're screwing up the design for those people, which is silly, and not intended, it's a bug.
I am assuming it only happens for paid customers, correct me if I am wrong.
But in any case, this is fixed by removing Brave Shields, pretty sure ublock origin blocks the ads without breaking the page.
I assume its because Brave added a thing to slide away the dead space when the ads are blocked, so you gotta fix the code which also does it when ads are not even showing - Which would be a general bug, this could happen on ANY page where there are ads that happen to be disable because of a premium account.

So please focus on the technical bug here.

Love you Brave, big ups.

**Comment by ryanbr** [comment] 2024-10-26 05:47
> however I am a paid customer for this and now you're screwing up the design for those people, which is silly, and not intended, it's a bug.

Which bug is this?

**Comment by XOCODE-OP** [comment] 2024-10-26 11:08
the right hand side of the screen shows a row of ads.
so I assume the code like blocked the element in a way where it pushed them out or something.
so it works in ad mode.
but in paid mode you would see what you see in the screenshot above where the right side is cut off, indicating that it also does this in paid mode when the ads arent even there, so now its pushing the actual UI out.

That being said, this was a bug at the time this was reported and currently I cannot reproduce it.
Not sure if that is because Brave fixed it somehow or because the dev of Photopea got so annoyed by the reports that they adjusted their code to play nice with Brave's behavior now. Or maybe it's still a bug but I just cant reproduce it anymore.

**Closed** 2024-10-26 12:25 UTC
Labels: feature/shields/adblock, OS/Desktop

**Comment by ShivanKaul** [comment] 2024-10-26 16:01
The issue title is extremely misleading so I have changed it. It looks like the report was actually talking about photopea.com being broken for Premium/paying customers. It doesn't look like that issue can be reproduced now. Please let us know if that is not the case. Thanks.

**Comment by kuckir** [comment] 2024-10-28 14:38
I do not consider it to be fixed. www.Photopea.com still looks different in Brave than in other browsers (when you open it for the first time and start the editor).

My "business strategy" is, that anyone can use www.photopea.com for free, but it will run only on 80% of their screen. I encourage users to pay for a Premium account, to be able to use it on 100% of their screen.

Your web browser is re-building the structure of my website, to allow your users to use this "premium feature" without paying for it. Please, don't do it.

**Comment by XOCODE-OP** [comment] 2024-10-28 15:11
it would probably help to be technical and specific for the claim of "looks different".
Im sure it doesnt rebuilt every single html tag, so lets be specific

I'm sure Brave doesnt have special code for one website, so we they won't spend time debugging one specific page like that trying to understand where the difference is.

the claim about w3 standards is silly because we all understand the Brave Shields are the to manipulate the existing code, so obviously it would change the page. It just has to do it in a way where it doesnt overstretch the viewport like we saw initially.

Currently I dont see any difference, so it depends what the persisting issues actually would be.

**Comment by kuckir** [comment] 2024-10-28 15:59
You are very wrong. Brave DOES have special code for one website (Photopea). We would be able to see this code if Brave was open-source.

The issue is already described at the top - Photopea looks differently in Brave than in other browsers.

**Comment by kuckir** [comment] 2024-10-28 16:15
Also, it looks like nothing was fixed, because I still receive about five reporst a day from my Premium users who use www.photopea.com in Brave.

E.g. here: https://github.com/photopea/photopea/issues/7278

**Comment by ShivanKaul** [comment] 2024-10-29 06:19
> We would be able to see this code if Brave was open-source.

Brave is open source: https://github.com/brave/brave-core/

@kuckir I'm genuinely trying to engage with you in a productive manner because I care about Brave users being able to use and support any website they want, while still blocking privacy-harmful 3rd party ads and trackers. Your attitude thus far has been extremely unhelpful and misleading. You have made several incorrect claims in this issue: "Brave is not following web standards", "Brave is not open source". If you want to engage productively with us to make sure your site is fixed and usable for Brave users, for both your free and Premium users, please let us know. I see @ryanbr has already responded to https://github.com/photopea/photopea/issues/7278, an issue that you pre-emptively closed. 

Just a reminder that Brave (and I) believe that users deserve a private and user-first Web, so [we will actively work](https://github.com/brave/brave-browser/wiki/Blocking-goals-and-policy#blocking-goals-and-policy) against adblock-hostile website behaviour.

**Comment by kuckir** [comment] 2024-10-29 07:09
If Brave is open-source, could you show me a part of your code, which treats a website differently if it is "photopea.com"? Either it is located in a different repository, or you did not make this part of your code open-source.

I tihnk it is completely unacceptable, that you call ads in my website "harmful". Hundreds of thousands of people use Photopea daily with ads. I also visit all websites on the internet the way they were created (including the ads the authors wanted me to see), without letting anyone process (and possibly modify) every content that I see on the web.

**Comment by XOCODE-OP** [comment] 2024-10-29 09:02
I dont understand why you are making this assumption.
Brave has **built-in** ad blockers, which have the purpose of doing this to ads in general.
I don't know why you assume there is custom code for just one website.

**Comment by kuckir** [comment] 2024-10-29 13:04
Open any website in Brave, right-click it and choose "Inspect". Switch to "Console" and run the following script:

    window.innerWidth

When you do it in Photopea, it shows a different value than for any other website. Can you see it?

Brave DOES HAVE a special code for Photopea, and if you had access to the full source code of Brave, you would be able to see it somewhere in that code. Maybe @ShivanKaul could tell us more?

The expected value is described here: https://developer.mozilla.org/en-US/docs/Web/API/Window/innerWidth so yes, I think we can clearly say that Brave is breaking web standards.

**Comment by kuckir** [comment] 2024-10-29 15:59
I have found Photopea mentioned in these three files of your code: https://github.com/search?q=repo%3Abrave%2Fadblock-lists%20photopea&type=code  I don't know what you call "source code" and "blocking lists", but since you decided to make your software use a certain piece of data (which leads to incorrect rendering of my website), you should take responsibility for such a decision.

BTW. what does it mean that you marked this issue as "completed"? Does it mean that "window.innerWidth" in Photopea will work according to web standards? If yes, do you know when will the issue disappear from your web browser?
