### ISSUE TITLE
Fingerprint breaks youtube

### ISSUE THREAD

**Issue by ajaichemmanam** [brave/brave-browser#10223] opened 2020-06-11 14:20 UTC
## Description 
random lines when mouse hovering over youtube video

## Steps to Reproduce
Install latest brave nightly

   1. Enable fingerprinting (default)
   2.  Play a youtube video. 
   3. Move mouse over the video

## Actual result:
<img width="1374" alt="Screenshot 2020-06-11 at 7 46 54 PM" src="https://user-images.githubusercontent.com/10387750/84397675-8e9df600-ac1c-11ea-9a08-afa5f6219766.png">

## Expected result:
No lines 

## Reproduces how often: 
Every time

## Brave version (brave://version info)
1.11.60 latest

## Version/Channel Information:
Last few builds in brave nightly

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
Yes

The issue is fixed when fingerprint is allowed .

**Comment by srirambv** [comment] 2020-06-15 11:44
+1 from @ypitrey  via #10237 

I also noticed this. Disabling fingerprinting fixes the issue instantly. Setting it to standard also doesn't fix it.

cc: @pes10k

**Comment by pes10k** [comment] 2020-06-15 15:46
Thank you for the reports, its being looked into now 👍

**Comment by pes10k** [comment] 2020-06-15 15:47
cc @pilgrim-brave

**Comment by kjozwiak** [comment] 2020-06-16 18:39
@ajaichemmanam looks like this is happening when you have `Fingerprinting blocked (strict, may break sites)` selected via the shields. If you switch it back to `Fingerprinting blocked (standard)`, does it resolve the issue?

![fingerprintingYT](https://user-images.githubusercontent.com/2602313/84814128-01bdb880-afdf-11ea-80bc-d8b3cb93fd60.gif)

Possibly occurring due to #10285.

**Comment by ajaichemmanam** [comment] 2020-06-17 12:02
It doesn't resolve. The issue is there in aggressive as well as standard fingerprint blocking.

**Comment by ajaichemmanam** [comment] 2020-06-17 12:05
> +1 from @ypitrey via #10237
> 
> I also noticed this. Disabling fingerprinting fixes the issue instantly. Setting it to standard also doesn't fix it.
> 
> cc: @pes10k
It doesn't resolve. The issue is there in aggressive as well as standard fingerprint blocking.

**Comment by ajaichemmanam** [comment] 2020-06-17 12:07
Yes. #10285 causes the shield change to not get applied. If you change fingerprint in settings  to standard, the issue gets fixed.

**Comment by pes10k** [comment] 2020-06-18 00:24
Thanks for confirming @ajaichemmanam then!  I'm closing this since the issue is shields / UX side, and not farbling / fingerprinting itself (we accept that strict fingerprinting protections will have errors like this, so don't consider them bugs).  If you see breakage though on standard / default fingerprinting protections though, please let us know

Thanks again!

**Closed by pes10k** 2020-06-18 00:24 UTC
Labels: OS/Desktop, QA/Yes, bug, feature/shields/fingerprint, feature/shields/webcompat
