### ISSUE TITLE
Split GetBalance 

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#20496] opened 2022-01-13 19:06 UTC
## Description 

Follow up from https://github.com/brave/brave-core/pull/11687#discussion_r784213133
Split it to GetEthBalance and GetFILBalance and use `chainId` instead of CoinType probably

**Comment by bbondy** [comment] 2022-02-03 17:05
Duplicate of https://github.com/brave/brave-browser/issues/20873 ?

**Closed** 2022-02-03 18:46 UTC
Labels: priority/P3, OS/Desktop
