### ISSUE TITLE
The 'autoplay was blocked on this page' pop-up is really annoying

### ISSUE THREAD

**Issue by dlfsjdfjodifjsodifjsdo** [brave/brave-browser#3654] opened 2019-03-11 10:09 UTC
let us turn this off

using Brave dev on windows 7

**Comment by gabrielhug** [comment] 2019-03-11 18:49
To clarify what I think you're getting at: In brave://settings/content/autoplay when autoplay is globally blocked the 'Autoplay was blocked on this page' notification is still shown on sites not in the autoplay block list.

You can hide these notifications globally by adding two autoplay block rules: http://* and https://*

**Comment by rebron** [comment] 2019-03-15 16:18
cc: @srirambv likely a dupe.

**Comment by rebron** [comment] 2019-03-16 04:27
Closing. Dupe of https://github.com/brave/brave-browser/issues/3623

**Closed by rebron** 2019-03-16 04:27 UTC

**Comment by ganar** [comment] 2019-03-30 18:22
> To clarify what I think you're getting at: In brave://settings/content/autoplay when autoplay is globally blocked the 'Autoplay was blocked on this page' notification is still shown on sites not in the autoplay block list.
> 
> You can hide these notifications globally by adding two autoplay block rules: http://* and https://*

This worked for me, although is not at all clear to me why it works that way. Brave has simplified many things for me, this widget should have a more complete set of preferences in the _onlick_ event.
