### ISSUE TITLE
[ads] Reset brave://rewards estimated earnings at midnight local time

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#25750] opened 2022-10-01 01:24 UTC
## Description

On the 1st of the month, estimated earnings resets to 0.0. However, the countdown payout banner (which says "Your x earnings will arrive in n days") sometimes does not appear immediately (depending on local time vs UTC time?), causing confusion.

## Solution

The instant estimated earnings resets to 0.0, the countdown payout banner should appear.

**Comment by Miyayes** [comment] 2023-04-15 10:51
@tmancey Was there anything here you needed to share with Zenparsing to get this ready to implement?

**Comment by tmancey** [comment] 2024-05-04 17:55
@Miyayes payment tokens stored on the server are in UTC. Implementing this change will result in a disparity between client-side and server-side earnings. This could be deemed acceptable considering the minimum estimated earnings multiplier, currently set at 80%. What are your thoughts on this? cc @iambrianfung

**Comment by tmancey** [comment] 2024-06-06 21:02
@btlechowski we believe this was fixed by another issue. Thanks

**Closed by tmancey** 2024-06-06 21:02 UTC
Labels: enhancement, feature/rewards, QA/Yes, feature/ads, OS/Android, OS/Desktop

**Comment by tmancey** [comment] 2024-07-25 17:22
@btlechowski I could not reproduce so would be great if QA could test too. Thanks
