### ISSUE TITLE
sends failing on Binance Smart chain on 1.54

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#31221] opened 2023-06-22 11:03 UTC
## Description 

See thread here -->  https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1687430969302859

Sends failing on v1.54.73 on desktop. Working successfully on Main release. Was able to reproduce 3 times and @srirambv also tested it. Attaching error that I got. 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

![Screenshot 2023-06-22 at 12 47 29](https://github.com/brave/brave-browser/assets/12224304/d93aa241-f48e-4078-bd33-2e3929737b1a)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by onyb** [comment] 2023-10-27 10:27
Unable to reproduce in 1.59 and 1.62. Could've been an issue with the RPC. @srirambv Can we close this?

**Comment by srirambv** [comment] 2024-12-17 09:31
Closing the issue as stale. Not able to reproduce it any more

**Closed by srirambv** 2024-12-17 09:31 UTC
Labels: priority/P2, feature/web3/wallet, OS/Android, OS/Desktop
