### ISSUE TITLE
Brave Shows a 404 Error Message on Any of The Cloudflare DDoS Protection Page.

### ISSUE THREAD

**Issue by Bj007pro** [brave/brave-browser#8868] opened 2020-03-26 09:53 UTC
## Description 

Brave shows a 404 error message on any of the Cloudflare DDoS Protection page.

## Steps to Reproduce

   1. Go to a website that use Cloudflare's DDoS Protection
   2. Brave's 404 Error Message should show.

## Actual result:

I assume for the 404 message to not show at all.

## Expected result:

For the 404 Error message to not show on Cloudflare's DDoS Protection page because it is not a lost, removed, or deleted web page. 

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

https://pastebin.com/jRrA170j

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
   No it does not
.
- Does the issue resolve itself when disabling Brave Rewards?
  No it does not.

- Is the issue reproducible on the latest version of Chrome? 
   This is a Brave specific message so it can not be reproduced on Chrome.

## Miscellaneous Information:

Here's a screenshot:

![image](https://user-images.githubusercontent.com/24400879/77637129-0e230e00-6fba-11ea-9021-1441576481bb.png)

**Comment by bsclifton** [comment] 2020-03-27 16:45
Closing as duplicate of https://github.com/brave/brave-browser/issues/8401 and https://github.com/brave/brave-browser/issues/8716

**Closed by bsclifton** 2020-03-27 16:45 UTC
Labels: duplicate
