### ISSUE TITLE
Twitch.tv stream is pausing itself when unmuting while browser AutoPlay setting is disabled

### ISSUE THREAD

**Issue by nastavoi** [brave/brave-browser#16102] opened 2021-05-27 10:29 UTC
## Description 

Twitch.tv stream is pausing itself when unmuting while browser AutoPlay setting is disabled.

## Steps to Reproduce

   1. Turn off AutoPlay globally in the browser settings 
   2. Go to https://www.twitch.tv/ and open any online twitch.tv stream in current or new tab (doesn't matter)
   3. Stream is paused and muted by default
   4. Click play button at the bottom left of the Player to start the stream
   5. Video starts playing muted
   6. Click mute/unmute button at the bottom left of the Player to unmute the stream
   7. Stream pauses itself while still being muted

To actually unmute and play it you need to first unmute it while paused and then click the play button at.

## Actual result:

Active twitch.tv stream is pausing itself when unmuting it in the web video Player while browser AutoPlay setting is disabled.

## Expected result:
Active twitch.tv stream remains active when muting/unmuting it in the web video Player while browser AutoPlay setting is disabled.

## Reproduces how often: 

Easily reproduced. If AutoPlay setting is enabled I can mute/unmute active stream without it pausing by itself.

## Brave version (brave://version info)

Brave - 1.26.43 Chromium: 91.0.4472.77 (Oficjalna wersja) beta (64-bitowa)
Wersja - 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
System operacyjny - Windows 10 OS Version 2009 (Build 19042.985)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?

## Miscellaneous Information:

I've noticed that e.g. Youtube also behaves this way and it's rather annoying. 

EDIT: Also noticed just now that it seems the weird behaviour has already been reported in #13586.

**Comment by rebron** [comment] 2021-05-28 17:07
@nastavoi This does look like a dupe of #13586 I'll close this one out and +1 that main issue.

**Closed by rebron** 2021-05-28 17:07 UTC
Labels: OS/Desktop, feature/autoplay, needs-investigation, priority/P4
