### ISSUE TITLE
`Whoops!  We couldn't locate your receipt.` error message after clicking `Connect my subscription now` on desktop

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#27539] opened 2022-12-24 10:19 UTC
## Description 

`Whoops!  We couldn't locate your receipt` error message after clicking `Connect my subscription now` on desktop

## Steps to Reproduce

   1. set up `Brave VPN` on iOS or Android, via their in-app purchase
   2. log in to `account.bravesoftware.com`
   3. link those purchased credentials via `account.bravesoftware.com/?intent=connect-receipt-test&product=vpn`
   4. launch desktop Brave
   5. click `Refresh Brave VPN`
   6. log in to `account.bravesoftware.com` using the same account as in `step 2`
   7. load `account.bravesoftware.com/?intent=connect-receipt-test&product=vpn`
   8. click on `Connect my subscription now`

## Actual result:

Get a `Whoops!  We couldn't locate your receipt.` error message

### `iOS`

example | example | example | example | example | example
----------|----------|-----------|-----------|-----------|---------
![IMG_0405](https://user-images.githubusercontent.com/387249/209431613-e6b4fb2c-c6be-49cf-9020-bd6dc8e3947c.jpg) | ![IMG_0406](https://user-images.githubusercontent.com/387249/209431615-503eda15-eea5-402f-b693-5cca5a0f253e.jpg) | ![IMG_0408](https://user-images.githubusercontent.com/387249/209431620-5c0cd976-18a5-49c5-8239-b55a91465d9d.jpg) | ![IMG_0409](https://user-images.githubusercontent.com/387249/209431625-7ce410a2-7beb-452c-9a4b-06b3fca397e6.jpg) | ![IMG_0410](https://user-images.githubusercontent.com/387249/209431635-831237af-8fe0-432a-9dd6-1db6ec0af01f.jpg) | ![IMG_0411](https://user-images.githubusercontent.com/387249/209431642-0f79d367-913e-4513-a2b6-0d97d48c6135.jpg)

### macOS

example | example | example
---------|------------|----------
![desktop-4](https://user-images.githubusercontent.com/387249/209430845-398d1665-7300-47da-9292-5507d62466bf.png) | ![desktop-5](https://user-images.githubusercontent.com/387249/209431362-72c8f98f-18ee-4cca-9be4-4b821434da05.png) | ![desktop-6](https://user-images.githubusercontent.com/387249/209431365-9b405962-da99-4586-a5e7-5723c3100cfd.png)

## Expected result:

Unsure; just FYI, this is pretty edge-case, I think, though we should still address it

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.145 Chromium: 109.0.5414.46 (Official Build) beta (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 10 Version 22H2 (Build 19045.2364)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @mattmcalister @husobee @AlanBreck @bsclifton @brave/qa-team

**Comment by AlanBreck** [comment] 2022-12-24 14:52
This is expected behavior since the desktop device wouldn't have a receipt. I don't think there's any path for the user to get to that screen on desktop anyhow, though, right?

The only scenario I could imagine them getting there is if the user tried to use Apple Handoff at that screen.

**Comment by stephendonner** [comment] 2022-12-28 19:23
> This is expected behavior since the desktop device wouldn't have a receipt. I don't think there's any path for the user to get to that screen on desktop anyhow, though, right?
> 
> The only scenario I could imagine them getting there is if the user tried to use Apple Handoff at that screen.

Yeah, this isn't part of a real flow - it's contrived but wanted to get it logged, just in case.

**Comment by bsclifton** [comment] 2023-03-22 22:11
Thanks for logging 😄 I'll close as `wontfix` for now... but if we want to address this, we can probably have a better error on the account.brave.com side (ex: are you on the device you purchased the subscription on?)

**Closed by bsclifton** 2023-03-22 22:11 UTC
Labels: closed/wontfix, needs-discussion, QA/Yes, QA/Test-Plan-Specified, OS/Desktop, feature/vpn
