### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by spillai** [brave/brave-browser#24223] opened 2022-07-22 18:13 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.41.99  Chromium: 103.0.5060.134
Operating System: Mac OS X 11.6.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Simple Github search in the top left
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/c4e00400-0d65-8e08-0000-000000000000

**Comment by neeythann** [comment] 2022-07-22 18:18
update to 1.41.100

duplicate of https://github.com/brave/brave-browser/issues/24164

**Closed** 2022-07-25 09:26 UTC
