### ISSUE TITLE
Button highlight overlaps on the URL bar when vertical tabs are enabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30395] opened 2023-05-17 06:24 UTC
## Description 

Button highlight overlaps on the URL bar when vertical tabs are enabled

## Steps to Reproduce

   1. Enable Vertical tabs
   2. Hover over Search tabs/Minimize/Restore/Close buttons
   3. Hover state overlaps on the urlbar 

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/b42f1a0a-8a1c-4cda-a278-96894129e05f

## Expected result:
Hover state should not overlap on the URL bar

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.52.100 Chromium: 113.0.5672.92 (Official Build) beta (32-bit) 
-- | --
Revision | `b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}`
OS | Windows 11 Version 22H2 (Build 23451.1000)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Note: Windows only issue
cc: @rebron @fallaciousreasoning @sangwoo108 @MadhaviSeelam

**Comment by fallaciousreasoning** [comment] 2023-05-17 22:42
Out of interest, why does Windows keep the Search button up there? On Linux it moves to the vertical tabs panel
![image](https://github.com/brave/brave-browser/assets/7678024/c4326951-cc20-499b-9f28-522211a5004b)

**Comment by sangwoo108** [comment] 2023-05-17 23:33
On Windows 10, tab search button is attached to the window frames. It's upstream implmentation but I'm not sure why 😅

**Comment by srirambv** [comment] 2023-05-18 02:58
I think what Windows does is right. Search tabs should be on the right side because if the vertical tabs are set to collapsed permanently (no hover state), then there is no way to search the tabs. Linux and macOS should probably follow what Windows is doing IMO

**Comment by fallaciousreasoning** [comment] 2023-05-18 20:45
FWIW @srirambv, I quite like having it next to the vertical tabs - it feels a bit more natural to me (I dunno why). I normally use the keyboard shortcut to open it so I hadn't noticed there was no button when it was collapsed, but yeah, that is a problem.

**Comment by rebron** [comment] 2023-05-19 17:32
Good eye @srirambv. We'll go platform specific here with the tab search placement. Windows will have the title bar on by default whereas macOS and Linux will not. I agree with both @fallaciousreasoning and @srirambv. My preference is tab search in the vertical tabs space when I'm on macOS/Linux (fits the space and feels in context with a search icon) but like it better in the title bar on Windows since we're not moving it from original placement.

**Comment by sangwoo108** [comment] 2023-05-30 07:10
@srirambv , does it happen when a window is not maximized?

**Closed** 2023-07-31 12:09 UTC
Labels: OS/Windows, QA/Yes, release-notes/exclude, OS/Desktop, feature/vertical-tabs

**Comment by MadhaviSeelam** [comment] 2023-08-15 00:02
Verification `PASSED` using 
```
Brave | 1.58.88 Chromium: 116.0.5845.82 (Official Build) beta (64-bit)
-- | --
Revision | acf16e35d5897fd4bf9b1b5a93b56aff2ed64bba
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

Reproduced using original STR from https://github.com/brave/brave-browser/issues/30395#issue-1713208698 in `1.56.20`

![image](https://github.com/brave/brave-browser/assets/98358127/45ff4583-ee0b-474c-99db-fcdb6d8951a4)

### Confirmed no URL bar overlap happened when hovered over Search tabs/Minimize/Restore/Close buttons

https://github.com/brave/brave-browser/assets/98358127/7e884a21-9835-4516-b1c7-e2554bf19d62
