### ISSUE TITLE
Is it possible to have search suggestion without autocomplete? 

### ISSUE THREAD

**Issue by DableUTeeF** [brave/brave-browser#27600] opened 2023-01-01 09:16 UTC
## Description 
I moved from Chrome to Firefox to get away from address bar autocomplete. Now that I'm planning to move from Firefox to Brave, is it possible to set the browser to suggest what I type but not autocomplete it? 

## Steps to Reproduce

   1. Disable "Show autocomplete suggestions in address bar"
   2. Type a word in address bar
   3. Enable "Show autocomplete suggestions in address bar"
   4. Type a word in address bar

## Actual result:
   1. No autocomplete but also no suggestion when "Show autocomplete suggestions in address bar" is disabled.
   2. Both autocomplete and suggestion were used when "Show autocomplete suggestions in address bar" is enabled.
   3. No setting for something in-between

## Expected result:
I'd like to have a setting where I can enable suggestion but disable autocomplete. For example, if I type "mail" I want it to suggest "mail.google.com" but if I press enter it just search with the word "mail".

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Linux

**Comment by rebron** [comment] 2023-01-06 16:19
If you go to brave://settings/appearance and uncheck everything but keep the main toggle on
<img width="698" alt="Screenshot 2023-01-06 at 8 17 25 AM" src="https://user-images.githubusercontent.com/5951041/211052918-7fc32db7-c8ca-4677-8cf3-ed8b13834c2b.png">

And then go to brave://settings/privacy and turn autocomplete on
<img width="719" alt="Screenshot 2023-01-06 at 8 17 59 AM" src="https://user-images.githubusercontent.com/5951041/211052985-9f2c85f4-c462-4a94-8dca-649201797b57.png">

I think that should do it.

**Comment by rebron** [comment] 2023-01-06 16:20
@DableUTeeF I'm going to close this one out. Please re-open if that didn't work for you.

**Closed by rebron** 2023-01-06 16:20 UTC
Labels: question, OS/Desktop, closed/works-for-me

**Comment by DableUTeeF** [comment] 2023-01-06 16:47
I tried that but that will just autocomplete my search as per `Actual Result` number 2. 

Without `Autocomplete searches and URLs` and without ticking anything under `Show autocomplete suggestions in address bar` it'll not suggest anything (Actual result: 1).

Without `Autocomplete searches and URLs` and ticking `Browsing History` under `Show autocomplete suggestions in address bar` it'll suggest but also autocomplete (Actual result: 2).

**Comment by DableUTeeF** [comment] 2023-01-06 16:49
@rebron I don't think I can re-open this myself.

**Comment by DableUTeeF** [comment] 2023-01-06 16:55
OK I think I figured out what you meant.

What I need "isn't" suggestion from the search engine, but rather the history.

The solution you provided will not autocomplete if the search engine is brave, but it doesn't give me the sites I visited similar to how **Show autocomplete suggestions in address bar** does.

**Comment by XavierJDN** [comment] 2023-01-09 01:41
hey,
I'd like to fix this issue.
I create a new preferences to be able to manage the inline and the suggestion.
the problem is: OmniboxController::StartAutocomplete is responsible to fetch and after render( by invoke event) for the inline and dropbox suggestions.
So, I need to take the responsability of the dropdown suggestions out.
Am I right?
Annexe documentation on omnibox: https://docs.google.com/document/d/1Dk_U-zXiMFynKOYYKrS6VKUXrON_ta2mYnAyHa-Uvc0/edit#

**Comment by DableUTeeF** [comment] 2023-01-09 08:41
@XavierJDN Can you also re-open this thread? As it clearly isn't solved but I can't do it.

**Comment by XavierJDN** [comment] 2023-01-09 12:08
I can't do it too. @rebron can you do it?
If you can  answer my question or tell me some people that have the knowledge to answer my questions. It'll be appriciate.
