### ISSUE TITLE
DevTools/Audits doesn't work

### ISSUE THREAD

**Issue by Im-On-Fire** [brave/brave-browser#6246] opened 2019-10-01 07:09 UTC
This problem originally has been happened to me on Ubuntu 16.04. Lately, I've upgraded it to Ubuntu 18.04, but the problem still remais.

![Снимок экрана от 2019-10-01 10-03-24](https://user-images.githubusercontent.com/52078784/65941184-13503780-e433-11e9-9bd5-bb126c5d0063.png)

As you can see on this screen, after the message "Light house is warming up" nothing happens :c 

My brave version is 0.68.142. Chromium: 77.0.3865.90. (64 bit)

**Comment by silviolobo** [comment] 2019-10-01 20:50
I can confirm that happens on Windows too.

**Brave:** 0.68.142 Chromium: 77.0.3865.90 (Official Build) (64-bit)
**OS:** Windows 10 OS Version 1809 (Build 17763.348)

**Comment by rebron** [comment] 2019-10-11 16:39
duplicate of https://github.com/brave/brave-browser/issues/815

**Closed by rebron** 2019-10-11 16:39 UTC
Labels: duplicate
