### ISSUE TITLE
Implement auto-select via `onFocus` in country selection / geo declaration dropdown - Follow up to 28321

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#29606] opened 2023-04-10 17:39 UTC
## Description 

Logging as a follow up to https://github.com/brave/brave-browser/issues/28321

Per discussion with @Miyayes, in addition to the OS country being at the top of the list, it should also be displayed alphabetically within the list.

So in the example of United States, it should be at the top of the list (which it is in 1.51.x), but it should also be displayed alphabetically within the list, which it is not.

## Steps to Reproduce

   1. Clean install 1.51.x
   2. Close and relaunch to pull griffin
   3. Open rewards icon in URL bar
   4. Navigate to country selection list

## Actual result:

Country is listed first (as expected) but not also alphabetically within the list

Example | Example
--- | ---
<img width="1183" alt="US1" src="https://user-images.githubusercontent.com/28145373/230958700-d881490b-5047-4fe1-8800-45b1f96169c0.png"> | <img width="1203" alt="US2" src="https://user-images.githubusercontent.com/28145373/230958702-ec4bba92-09c4-486a-9a70-e8f4756420c9.png">

## Expected result:

Country should be listed in both places

## Reproduces how often: 

easily

## Desktop Brave version:

```
Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 13.3.1 (Build 22E261)
```

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a 1.50.x
- Can you reproduce this issue with the beta channel? yes 1.51.x
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes

**Comment by szilardszaloki** [comment] 2023-04-13 18:41
@Miyayes Just double-checking, as previously we agreed on not implementing it like that. Thanks!

**Comment by szilardszaloki** [comment] 2023-04-13 20:35
@Miyayes May I suggest a separator line (as a disabled `<option>` element) instead of duplicating the default country? 🙂 

![image](https://user-images.githubusercontent.com/5390451/231876709-9b3d972c-82b4-43d7-b64a-313bd5c439c2.png)

**Comment by szilardszaloki** [comment] 2023-04-14 20:11
@Miyayes Can we rename this issue to something like "Implement auto-select via `onFocus`", or should we close this and open another one? cc: @zenparsing

**Comment by Miyayes** [comment] 2023-04-15 09:55
Renaming issue.

**Comment by Miyayes** [comment] 2023-04-18 13:13
@zenparsing We can even hold this to 1.53.x, since 1.52.x seems pretty overloaded

**Closed** 2023-05-01 17:24 UTC
Labels: feature/rewards, priority/P3, QA/Yes, OS/Desktop

**Comment by MadhaviSeelam** [comment] 2023-06-08 00:10
Verification `In progress` using 
```
Brave | 1.53.83 Chromium: 114.0.5735.110 (Official Build) beta (64-bit)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```
Verified using original STR in description

#### Confirmed Country listed in both places

ex | ex | ex | ex
--- | --- | --- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/edab0b97-7389-4674-a56e-b365fc252ee3)|![image](https://github.com/brave/brave-browser/assets/98358127/f4997a43-fc67-4894-8d1f-20ddf02e2996)|![image](https://github.com/brave/brave-browser/assets/98358127/97780486-6e6d-4ec9-b8cf-5f99a84e9f6e)|![image](https://github.com/brave/brave-browser/assets/98358127/d646a1da-84ee-48e8-8fdc-d34b248c1e76)

**Comment by stephendonner** [comment] 2023-06-09 23:18
## Verification `IN-PROGRESS` using

```
Brave 1.53.87 Chromium: 114.0.5735.110 (Official Build) beta (64-bit) 
Revision 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS Linux
```
