### ISSUE TITLE
[Desktop] Brave hangs for 10-15 seconds before startup

### ISSUE THREAD

**Issue by Rex109** [brave/brave-browser#10801] opened 2020-07-18 10:42 UTC
## Description 

Brave with "Continue running background apps when Brave is closed" disabled takes from 10 to 15 seconds to fully initialize and start working

## Steps to Reproduce

   1. Open the browser

## Actual result:

Takes 10 to 15 seconds to open

## Expected result:
Open smoothly as chrome/chromium

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)

Brave | 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by mwdiers** [comment] 2020-07-18 16:15
This is a known issue. See #9481

**Comment by Rex109** [comment] 2020-07-18 17:10
> This is a known issue. See #9481
> 
> FWIW: My problem was far worse. I was up to almost a minute. Until this is fixed, the solution is simple: Clear cookies and site data. For me, this took a _long_ time. After that, Brave started instantly.

Got it working, yeah the problem seems to be related to that issue

**Comment by bsclifton** [comment] 2020-07-19 05:50
Closing as duplicate of https://github.com/brave/brave-browser/issues/9481 - thanks for the report @Rex109 😄

**Closed by bsclifton** 2020-07-19 05:50 UTC
Labels: OS/Desktop
