### ISSUE TITLE
Can't claim free token grants (Prove that you are human)

### ISSUE THREAD

**Issue by ChildishGiant** [brave/brave-browser#1780] opened 2018-10-22 18:57 UTC
## Description 
The "Prove that you are human!" task is impossible to solve. Even when getting it right many times in a row, or purposely getting it wrong.

## Steps to Reproduce
   1. Attempt to claim free BAT tokens

## Actual result:
https://gfycat.com/FoolishClosedBarasinga
![](https://thumbs.gfycat.com/FoolishClosedBarasinga-size_restricted.gif)

## Expected result:
When dragging the BAT logo onto the correct triangle, I am verified as human.

## Reproduces how often: 
Happens every time I attempt to claim the free grants.

## Brave version (brave://version info)
```
Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows
JavaScript | V8 7.0.276.28
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-tab-audio-muting --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave,kAutofillServerCommunication --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\Allie\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | c134752e-f685ead32c707b42-dcf7018a411b6d4e-3f4a17dfd01ab0d3-419732d93e006338-3f4a17df1a0d11d4-3f4a17dfe202a358-3f4a17dfebeb14fc-3f4a17dfb7e2524c-3f4a17dfb3888d8d-afba0f916c18ba9d-3d98b3028982496f-3f4a17df61832c80-3f4a17dfcc20827f-77c422c9041608a-3f4a17df2db4845-ace4e13874785582-3f4a17df241fff6c-4eda1c579853922b-3f4a17df125b7f68-3f4a17df9ca1387e-3f4a17df1c752ce9-1c752ce941e765a5-3f4a17df1149accc-3f4a17dfab3d6cfd-3f4a17df776de70c-e0278d3ded9149a9-3f4a17dfa5cb8590-3f4a17df34d450b1-3f4a17df6c6c4f61-3f4a17df15d89564-80f9a33e76b48ab8-d4bd105cc70841c8-a25670078ee5ed19-c3125ea274658432-fa79b94ced7ba060-3f4a17df121ae2bc-65969d679e201a2b-3f4a17df652e14d1-f4950e9927212adc-27212adc591576c8-3f4a17df249dd49a-3f4a17df5274eb09-3f4a17dfceff87ec-3f4a17df44827ee5-3f4a17df8ca44045-3f4a17df8f1e27f-3f4a17df345b5b61-3f4a17dfedbcf7c5-ddf1844d77bbdddc-3f4a17df5485fc4d-3f4a17dfde47491b-3f4a17df93731dca-3f4a17df9b4c4257-3f4a17df8fa604e0-ace4e13843f62d3b-3f4a17df9e5c75f1-30e1b12b6fa07eb4-7282ca762981bcb4-3f4a17df2b86fd96-3f4a17df5139837c-3f4a17df4934552d-3f4a17df7f8176d9-3f4a17df296e6ad7-4cfc7c42f7217a71-b204717823a898eb-fc93cf747a5ba892-3f4a17dfd1cd70a5-675921444ea303a6-3f4a17dfb19465ab-b19465ab6e6e0c7e-3f17a7d895876445-400575afd92562a9-441539fd2b33233e-881ca6c94da5ae82-3f4a17df56302f8c-2f882e7014c5a050-61ceed182c1d398c-3f4a17dfcc54eb06-3f4a17dfb2612322-8a9180b2cac0a91c-3f4a17dfdf072bba-9a6c5085f56e0452-3f4a17df8576baf1-3f4a17dff3ea30a0-3f4a17df3038aa2e-3f4a17df51b9b54d-3f4a17df4bc337ce-535cb40a9a2f4e5b-4bc735ae1354da85-f1a864dc17507c76-3f4a17df6844d8aa-669a04e0494d8760-3f4a17df34baa302-cf4f6ead587fa7b2-726d8ace3a4029d-d7f231f3bbb8f811-3f4a17df94e68624-803f8fc4cc73f8a1-3f4a17df8834fcca-3f4a17df11d91db8-d93a0620ea0f933d-3f4a17df493ac2c5-803f8fc4
```

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes, it was also reproduceable on the (currently) latest dev build

```
Brave | 0.57.1 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows
JavaScript | V8 7.0.276.28
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser-Dev\Application\brave.exe" --enable-tab-audio-muting --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser-Dev\Application\brave.exe
Profile Path | C:\Users\Allie\AppData\Local\BraveSoftware\Brave-Browser-Dev\User Data\Default
Variations | c134752e-f685ead32c707b42-dcf7018a411b6d4e-3f4a17dfd01ab0d3-419732d93e006338-3f4a17dfebeb14fc-3f4a17dfb3888d8d-afba0f916c18ba9d-3d98b30261832c80-3f4a17dfcc20827f-77c422c9041608a-3f4a17df2db4845-ace4e13874785582-3f4a17df241fff6c-4eda1c579853922b-3f4a17df125b7f68-3f4a17df9ca1387e-3f4a17df1c752ce9-1c752ce941e765a5-3f4a17df1149accc-3f4a17dfab3d6cfd-3f4a17df776de70c-e0278d3ded9149a9-3f4a17dfa5cb8590-3f4a17df34d450b1-3f4a17df6c6c4f61-3f4a17df76b48ab8-d4bd105cc70841c8-a25670078ee5ed19-c3125ea274658432-fa79b94ced7ba060-3f4a17df27212adc-27212adc591576c8-3f4a17df5274eb09-3f4a17dfceff87ec-3f4a17df44827ee5-3f4a17df8ca44045-3f4a17df8f1e27f-3f4a17dfedbcf7c5-ddf1844d77bbdddc-3f4a17df5485fc4d-3f4a17dfde47491b-3f4a17df93731dca-3f4a17df9b4c4257-3f4a17df8fa604e0-ace4e13843f62d3b-3f4a17df9e5c75f1-30e1b12b6fa07eb4-7282ca762981bcb4-3f4a17df2b86fd96-3f4a17df5139837c-3f4a17df4934552d-3f4a17df7f8176d9-3f4a17dff7217a71-b204717823a898eb-fc93cf74d1cd70a5-675921444ea303a6-3f4a17dfb19465ab-b19465ab6e6e0c7e-3f17a7d895876445-400575afd92562a9-441539fd2b33233e-881ca6c94da5ae82-3f4a17df56302f8c-2f882e7014c5a050-61ceed182c1d398c-3f4a17dfcc54eb06-3f4a17dfb2612322-8a9180b2cac0a91c-3f4a17dfdf072bba-9a6c5085f56e0452-3f4a17df8576baf1-3f4a17dff3ea30a0-3f4a17df3038aa2e-3f4a17df51b9b54d-3f4a17df4bc337ce-535cb40a9a2f4e5b-4bc735ae1354da85-f1a864dc17507c76-3f4a17df6844d8aa-669a04e0494d8760-3f4a17df34baa302-cf4f6ead587fa7b2-726d8ace3a4029d-d7f231f3bbb8f811-3f4a17df94e68624-803f8fc4cc73f8a1-3f4a17df8834fcca-3f4a17df11d91db8-d93a0620493ac2c5-803f8fc4
```

**Comment by NejcZdovc** [comment] 2018-10-22 19:01
@ChildishGiant thank you for the report. We already have one issue for this one which was fixed today and should go out today/tomorrow.

closing as dupe of https://github.com/brave/brave-browser/issues/1350

**Closed by NejcZdovc** 2018-10-22 19:01 UTC

**Comment by ChildishGiant** [comment] 2018-10-22 19:41
Sorry for the dupe, I had a look but didn't find it.
