### ISSUE TITLE
Add an entry in Leo settings to disable Leo assistant for autocomplete

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#33443] opened 2023-10-05 16:20 UTC
## Description 

Add a link in brave://settings/leo-assistant pointing to the setting for disabling Leo in autocomplete. 
The link should lead to the autocomplete settings section.
This is for discoverability because people may look in Leo settings to turn off the autocomplete if they don't want to use Leo.

Here are the settings it will link to in brave://settings/appearance:
<img width="720" alt="280461896-9d9e8b76-0a85-4d73-9af9-dd87ffb70fe4" src="https://github.com/brave/brave-browser/assets/831718/6e145f50-c44a-4737-a8c4-28c6dd2ea414">

**Comment by aka13-404** [comment] 2023-11-04 09:26
I find it so annoying, that someone went ahead, and greenlit a release with an unremovable entry in the autocomplete list, with a feature the majority will not use. What was even the point? I advertise brave to friends and colleagues, who are tired of google pushing unnecessary annoying stuff to chrome without giving the option to opt out. 

There is literally no point in using brave, if it is the same stuff, but from a different group of people. 
Can't make this up, ANY text in the adress bar now opens up an entry, leading to a big fat advertisement of "advanced smart assistants". At least the cryptowallet, cryptorewards, cryptoeverything can be disabled from view. There isn't even a close button for the said advertisement. 

You guys do a great job, no questions there, but moves like that is why people switch from vanilla chrome in the first place.

**Comment by sangwoo108** [comment] 2023-11-04 11:05
Hi, @aka13-404 . I believe you can disable the Autocomplete suggestion from the settings menu

Please go to `brave://settings/appearance` > `Toolbar` and disable the `Leo AI assistant`. 

<img width="720" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/9d9e8b76-0a85-4d73-9af9-dd87ffb70fe4">

The reason why we put this here is consistency with other Autocomplete options. - [related thread](https://github.com/brave/brave-browser/issues/30556#issuecomment-1736757559)

**Comment by bbondy** [comment] 2023-11-04 12:10
@aka13-404 I modified the original issue to be more clear that the setting already exists for those that don't want an entry point into Leo. I made it say add a link to those settings within the Leo section so that people that go to Leo settings can find it more easily.

**Comment by aka13-404** [comment] 2023-11-04 12:37
> Hi, @aka13-404 . I believe you can disable the Autocomplete suggestion from the settings page
> 
> Please go to `brave://settings/appearance` > `Toolbar` and disable the `Leo AI assistant`.
> 
> <img alt="image" width="720" src="https://user-images.githubusercontent.com/5474642/280461896-9d9e8b76-0a85-4d73-9af9-dd87ffb70fe4.png">
> The reason why we put this here is consistency with other Autocomplete options. - [related thread](https://github.com/brave/brave-browser/issues/30556#issuecomment-1736757559)

Thank you, that did it. I would never have found it on my own. Appreciate it! Not getting autocompletion suggesting leo anymore.

**Comment by kjozwiak** [comment] 2023-11-20 21:20
@bbondy @mattmcalister maybe we should think about moving it from `brave://settings/appearance` into `brave://settings/leo-assistant`? Seem like some users who want it disabled have a hard time finding the setting. For example, https://github.com/brave/brave-browser/issues/34404. User also wondering why it's not included under `Leo` as per https://github.com/brave/brave-browser/issues/34404#issuecomment-1817293598.

**Comment by bbondy** [comment] 2023-11-21 14:26
Well some subset of users will also go to the url bar auto complete section to look for it. So if it wasn't there they'd also not be able to find it. I think this issue tracks providing a link to the setting so it is effectively in both spots.

**Closed** 2023-12-14 01:06 UTC
Labels: priority/P3, needs-discussion, QA/Yes, feature/settings, OS/Desktop, browser-ai

**Comment by stephendonner** [comment] 2023-12-14 20:21
## Verified `PASSED` using

```
Brave | 1.63.42 Chromium: 120.0.6099.115 (Official Build) nightly (x86_64)
-- | --
Revision | 170e1e58f272c95056d5b1e6f0680a6a401ae3e4
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.63.42`
2. launched Brave
3. opened `brave://settings/leo-assistant`
4. clicked on `Adjust autocomplete suggestions`
5. confirmed I landed on `brave://settings/appearance?highlight=%23autocomplete-suggestion-sources`
6. deselected `Leo AI Assistant`
7. opened a new-tab window
8. typed a search term

### Confirmed `Leo`'s AI-autocomplete-disabling works

example | example | example | example | example
---------|---------|----------|---------|----------
<img width="1752" alt="Screen Shot 2023-12-14 at 12 13 05 PM" src="https://github.com/brave/brave-browser/assets/387249/58709b53-5704-427b-87eb-c093f7f4c527"> | <img width="1752" alt="Screen Shot 2023-12-14 at 12 13 08 PM" src="https://github.com/brave/brave-browser/assets/387249/6ec40131-74ec-4d71-8c18-7da832962c11"> | <img width="1752" alt="Screen Shot 2023-12-14 at 12 13 11 PM" src="https://github.com/brave/brave-browser/assets/387249/38210d22-e318-445d-ad4c-a5f3abdb357d"> | <img width="1752" alt="Screen Shot 2023-12-14 at 12 17 13 PM" src="https://github.com/brave/brave-browser/assets/387249/1f771cdb-4ee8-4123-9945-dc62b09cf9c4"> |<img width="1752" alt="Screen Shot 2023-12-14 at 12 17 23 PM" src="https://github.com/brave/brave-browser/assets/387249/51371e45-204d-4b06-ba4f-3b199c7f04ff">
