### ISSUE TITLE
Bug : website imgur.com

### ISSUE THREAD

**Issue by franco27** [brave/brave-browser#1065] opened 2018-09-09 17:02 UTC
Developer Channel v0.55.2 , with Windows 10 x64

Hello

1/ go to the imgur.com website and login (here identified with a Twitter account)
2/ the window does not appear and i cannot to select and add an image when I click on this button:

[img]https://i.imgur.com/XgkxNZf.png[/img]

3/ I disabled all blockages (the lion's head is grayed out) and allowed popup windows to be displayed
4/ I disconnected my account imgur and I identified myself again
5/when I click on this button, the window still does not appear.

Normally, it is a Windows Explorer window that should be displayed

same problem to add a file in Google Drive
(for download no problem)
 
If you want additional information, do not hesitate.

**Comment by bsclifton** [comment] 2018-09-10 07:04
Closing as a duplicate of https://github.com/brave/brave-browser/issues/1074

**Closed by bsclifton** 2018-09-10 07:04 UTC
