### ISSUE TITLE
Crash Report - Open link cause Brave to crash (Inconsistent)

### ISSUE THREAD

**Issue by typlosion14** [brave/brave-browser#24479] opened 2022-08-05 21:08 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.42.86  Chromium: 104.0.5112.81
Operating System: Windows NT 10.0.22000

URL (if applicable) where crash occurred: https://support.brave.com/hc/en-us/articles/360017905872-How-do-I-enable-or-disable-automatic-crash-reporting-

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Go to google
2. Click on a random link
3. Brave crash

It's completely inconsistent some link work other not

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/bbfc0100-efc0-a008-0000-000000000000

**Comment by JeanSebastienV** [comment] 2022-08-07 18:01
Is the option _Speedreader_ activated in your settings ? `brave://settings/appearance`

I have the same issue on speedreader compatible URLs: #24494

I think that on the contrary, all this is very consistant. You won't have any more problem by disabling Speedreader until the bug is fixed.

**Comment by Darzon65** [comment] 2022-08-08 07:14
Thanks @JeanSebastienV, I had the same issue and it took me a while to find this post but disabling Speedreader worked for me!

**Comment by typlosion14** [comment] 2022-08-08 07:16
Thanks, Disable Speedreader fix the issue

**Comment by rebron** [comment] 2022-08-08 21:33
Closing as dupe of https://github.com/brave/brave-browser/issues/24479

**Closed by rebron** 2022-08-08 21:33 UTC
