### ISSUE TITLE
Brave fails to set itself as the default browser

### ISSUE THREAD

**Issue by rajinder-yadav** [brave/brave-browser#16012] opened 2021-05-20 22:13 UTC
## Description 

After setting brave as the default browser, I still see firefox for some options.

```sh
$ xdg-mime query default x-scheme-handler/http
firefox.desktop

$ xdg-mime query default x-scheme-handler/https
firefox.desktop
```

Only this one is set correctly

```sh
$ xdg-settings get default-web-browser
brave-browser.desktop
```

As a result Firefox is getting opened by some app as the default browser.

## Steps to Reproduce

   1. open setting
   2. set brave to be default browser

## Actual result:

see description

## Expected result:

brave set as default browser

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment] 2021-05-28 18:47
@rajinder-yadav what distro of Linux are you on? If you're on Arch, we already have a ticket tracking this here:
https://github.com/brave/brave-browser/issues/2377

**Comment by rajinder-yadav** [comment] 2021-05-28 19:00
@bsclifton openSUSE Tumbleweed

**Comment by fmarier** [comment] 2021-09-29 01:24
It does look like something is broken on that distro (one of the ones supported by our official packages).

If I do the following on Ubunty 20.04:

1. Run `xdg-mime default firefox.desktop x-scheme-handler/https`
2. Open `brave://settings/getStarted`

Brave correctly detects that it's not the default:
![Screenshot from 2021-09-28 18-22-49](https://user-images.githubusercontent.com/167821/135187043-31578ae1-32e5-453a-ac5f-9fe6f84871c3.png)

and when I click "Make Default", the missing association is changed:
```
$ xdg-mime query default x-scheme-handler/https
brave-browser-beta.desktop
```

**Comment by chromium-santa** [comment] 2023-01-23 09:55
unable to reproduce

**Comment by spylogsster** [comment] 2023-01-23 09:56
unable to reproduce, closing to recheck

**Closed by spylogsster** 2023-01-23 09:56 UTC
Labels: OS/Linux, priority/P3, QA/Yes, release-notes/include, needs-more-info, OS/Desktop

**Comment by wknapik** [comment] 2023-01-24 19:42
https://github.com/brave/brave-browser/issues/2377#issuecomment-805224810

**Comment by newbie-02** [comment] 2024-06-11 10:30
Kali, debian based: 
brave installed acc. the curl ... receipe, 
deactivated gnome-keyring, suspicious and annoying, 
brave works, says to be default, 
all these xdg mime questions: 'default-browser.desktop', 
applications to open something in a browser, e.g. jupyter trying 
to open ' http://localhost:8888/....' go to firefox 
:-(
