### ISSUE TITLE
Closing last tab not exit browser

### ISSUE THREAD

**Issue by bigfoxtail** [brave/brave-browser#21667] opened 2022-03-15 14:34 UTC
Close the last tab without exiting the browser and open a new tab.
When will this feature be available? Both Vivaldi and Opera have this feature.
I really like this feature.

**Comment by rebron** [comment] 2022-03-18 17:38
Closing as dupe of https://github.com/brave/brave-browser/issues/1002

**Closed by rebron** 2022-03-18 17:38 UTC
Labels: OS/Windows, OS/Desktop
