### ISSUE TITLE
[Feature Request] Mute Tab

### ISSUE THREAD

**Issue by norsehealer** [brave/brave-browser#14396] opened 2021-02-28 16:16 UTC
I'd like an option to just mute a tab, instead of the current "mute site". 

This would allow me to hear on other tabs at the same site but keep one tab muted.

**Comment by nicolasff** [comment] 2021-03-01 00:56
Hello,

This isn't an official response as I'm not a Brave employee or even contributor, but the 🔈 icon on a tab mutes just the tab, not the website. I just tried it on the latest stable version, 1.20.110 (Chromium: 88.0.4324.192), by doing this:

1. First I opened two tabs with YouTube videos and waited until both started playing at the same time.
2. Then I clicked on the speaker icon on the first tab at it muted just that tab, while the second was still audible – and now I could actually understand what was being said in it.
3. I clicked on the speaker icon on the second tab and it was muted as well, meaning no sound was playing any more.
4. I clicked on the speaker icon on the first tab and I could start hearing it again.
5. I clicked on the speaker icon on the second tab and now both were playing at the same time again.

When the icon is clicked to mute it is crossed over to indicate that the tab is muted. No other tabs from the same website are muted. Each click on this icon switches the tab between audible and muted without affecting other tabs.

To be clear, I mean these icons:
![image](https://user-images.githubusercontent.com/7276/109439825-c2a48b80-79e4-11eb-9449-a948d1d0d09a.png)

It is my understanding that this is how the feature is supposed to work. If this isn't the behavior you're observing, I would suggest providing all the information that is requested in the [New Issue template](https://github.com/brave/brave-browser/blob/master/.github/ISSUE_TEMPLATE/desktop.md), such as which OS and version this happened on, a series of steps to reproduce the issue, what you were expecting vs what actually happened, etc.

**Comment by norsehealer** [comment] 2021-03-01 01:57
Yes, that works. however it only works when sound is actively being played.  I have a tab opened with discord and i accidently muted the tab but I have no method to unmute it.  

I was more thinking of when i have something open on twitch and just want the tab muted, to r-click the tab and select "mute tab", actually forgot about speaker icon on tab at the top.

**Comment by rebron** [comment] 2021-03-01 16:20
> Yes, that works. however it only works when sound is actively being played. I have a tab opened with discord and i accidently muted the tab but I have no method to unmute it.
> 
Did you mean, you muted the site? Since we have the speaker icon, plus the media controls I'm going to ahead and close this one out since we already have a method of muting a tab.

We also can't mute a tab that's not playing, that's what mute site is for, turning off autoplay completely or using the media control menu. 

![Screen Shot 2021-03-01 at 8 20 17 AM](https://user-images.githubusercontent.com/5951041/109526025-fa541780-7a66-11eb-8a0b-f9898c03d4da.png)

**Closed by rebron** 2021-03-01 16:20 UTC
Labels: OS/Desktop, audio, feature/context-menu, feature/tabs-bar
