### ISSUE TITLE
Freeze on Ubuntu 19.10

### ISSUE THREAD

**Issue by nicolo-ribaudo** [brave/brave-browser#6705] opened 2019-11-01 11:45 UTC
## Description 

When switching from another application to Brave, it sometimes freezes the whole screen (also the dash and the other parts of the gnome shell). Audio and video recording still work.
This happens both when switching from a full-screen window to brave, and when I have a small window on top of the browser and click on Brave in another part of the screen to focus it.

## Steps to Reproduce

   1. Open Brave
   2. Open something else
   3. Use that something else
  4. Go back to Brave

If you can't reproduce it, going back to the other window and then focusing Brave again won't reproduce the issue; you need to wait for some time.

## Reproduces how often: 

Between 10% and 20% of the times I switch to the Brave window.

## Brave version (brave://version info)

```

Brave             | 0.70.121 Chromium: 78.0.3904.70 (Build ufficiale) (a 64 bit)
Revisione         | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
Sistema operativo | Linux
```

## Other Additional Information:

- I have tried to disable all the Brave extensions (both built-in and installed by me), but it didn't solve the problem.
- It worked perfectly on Ubuntu 19.04. Then I formatted my PC, installed Ubuntu 19.10, installed Brave and got this problem.
- I installed `Chromium 78.0.3904.70 snap` and it doesn't have this problem.

## Miscellaneous Information:

I will attach my `journalctl -b` when it freezes again.

**Comment by sTiKyt** [comment] 2019-11-05 21:09
@nicolo-ribaudo between 10% and 20% usually called 15%

**Comment by nicolo-ribaudo** [comment] 2019-11-17 00:48
After opening the issue, I wasn't able to reproduce it anymore.

**Comment by Naahuel** [comment] 2019-12-31 21:50
This has been happening to me on **Pop!_OS 19**. _Exactly_ as described by @nicolo-ribaudo. In my case it happens almost EVERY time I switch back to Brave with alt-tab. I've disabled all extensions, no difference.

**Gnome Shell**
`GNOME Shell 3.34.1`

**brave://version**
```
Brave | 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Linux
JavaScript | V8 7.9.317.32
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,NotificationTriggers,LookalikeUrlNavigationSuggestionsUI,AudioServiceOutOfProcess,SmsReceiver,WebXR,WebXrGamepadModule,UnifiedConsent,AllowPopupsDuringPageUnload,SyncUSSBookmarks --flag-switches-begin --enable-smooth-scrolling --disable-features=AutofillServerCommunication,NotificationTriggers,LookalikeUrlNavigationSuggestionsUI,AudioServiceOutOfProcess,SmsReceiver,WebXR,WebXrGamepadModule,UnifiedConsent,AllowPopupsDuringPageUnload,SyncUSSBookmarks,ExtensionsToolbarMenu,TabGroups --flag-switches-end --disable-webrtc-apm-in-audio-service
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/nahuel/.config/BraveSoftware/Brave-Browser/Profile 1

```

**System**
```
OS: Pop!_OS 19.10 x86_64 
Host: 81FV Lenovo Legion Y530-15ICH 
Kernel: 5.3.0-7625-generic 
Uptime: 1 day, 10 hours, 14 mins 
Packages: 2699 (dpkg) 
Shell: zsh 5.7.1 
Resolution: 1920x1080 
DE: GNOME 3.34.1 
WM: GNOME Shell 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: tilix 
CPU: Intel i5-8300H (8) @ 4.000GHz 
GPU: NVIDIA GeForce GTX 1050 Mobile 
GPU: Intel UHD Graphics 630 
Memory: 6809MiB / 15887MiB 
```

**journalctl -e** (with two consecutive freezes):
```
Dec 31 18:45:01 pop-os CRON[22363]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 31 18:45:01 pop-os CRON[22364]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Dec 31 18:45:01 pop-os CRON[22363]: pam_unix(cron:session): session closed for user root
Dec 31 18:45:02 pop-os tracker-store[21823]: OK
Dec 31 18:45:02 pop-os systemd[2172]: tracker-store.service: Succeeded.
Dec 31 18:45:03 pop-os ulauncher.desktop[2739]: 2019-12-31 18:45:03,384 | WARNING | ulauncher.search.apps.app_watcher: _add_file_sync() | Cannot add /usr/share/applications/mutter.desktop to DB -> /usr/share/appli
Dec 31 18:45:05 pop-os gnome-shell[2470]: [15408:15408:1231/184505.045554:ERROR:gcm_channel_status_request.cc(145)] GCM channel request failed.
Dec 31 18:45:05 pop-os gnome-shell[2470]: Usage of object.actor is deprecated for ArgosButton
                                          get@resource:///org/gnome/shell/ui/environment.js:242:29
                                          _processOutput@/home/nahuel/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/button.js:139:5
                                          wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                          _update/<@/home/nahuel/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/button.js:95:11
                                          spawnWithCallback/<@/home/nahuel/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/utilities.js:268:7
                                          readStream/<@/home/nahuel/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/utilities.js:280:7
Dec 31 18:45:05 pop-os gnome-shell[2470]: Usage of object.actor is deprecated for ArgosButton
                                          get@resource:///org/gnome/shell/ui/environment.js:242:29
                                          _processOutput@/home/nahuel/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/button.js:141:9
                                          wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                          _update/<@/home/nahuel/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/button.js:95:11
                                          spawnWithCallback/<@/home/nahuel/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/utilities.js:268:7
                                          readStream/<@/home/nahuel/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com/utilities.js:280:7
Dec 31 18:45:36 pop-os /usr/lib/gdm3/gdm-x-session[2206]: nvLock: client timed out, taking the lock
Dec 31 18:45:48 pop-os slack.desktop[2719]: [12/31/19, 18:45:48:261] info: [DND] (T02CTQY6K) Checking for changes in DND status for the following members: UDBCKULNQ,UEK198Q2K,UDHPXGZM2,UDVP2TF8B,UELBVDMLM,UF1RT85R
Dec 31 18:45:48 pop-os slack.desktop[2719]: [12/31/19, 18:45:48:261] info: [DND] (T02CTQY6K) Will check for changes in DND status again in 5 minutes
Dec 31 18:46:56 pop-os slack.desktop[2719]: [12/31/19, 18:46:56:261] info: [DND] (THSJ3309Y) Checking for changes in DND status for the following members: UJ5SRDT1D,UP2CH7N31,UJ3DPTQ2G,UJ5UFB95M,UJ5S3DV7H,UHT09487
Dec 31 18:46:56 pop-os slack.desktop[2719]: [12/31/19, 18:46:56:262] info: [DND] (THSJ3309Y) Will check for changes in DND status again in 5 minutes
Dec 31 18:47:05 pop-os gnome-shell[2470]: [15408:15408:1231/184705.134891:ERROR:gcm_channel_status_request.cc(145)] GCM channel request failed.
Dec 31 18:47:35 pop-os /usr/lib/gdm3/gdm-x-session[2206]: nvLock: client timed out, taking the lock

```

My uneducated guess tells me these are the lines indicating the crash?
`/usr/lib/gdm3/gdm-x-session[2206]: nvLock: client timed out, taking the lock`

**Comment by rebron** [comment] 2020-01-03 17:47
@nicolo-ribaudo Can you turn off hardware acceleration in the UI and see if that works.

**Comment by nicolo-ribaudo** [comment] 2020-01-03 18:27
I am not able to reproduce it anymore; I reopened the issue for @Naahuel

**Comment by bsclifton** [comment] 2020-01-03 21:56
Going to close this as a duplicate of https://github.com/brave/brave-browser/issues/7581

**Closed by bsclifton** 2020-01-03 21:56 UTC
Labels: OS/Linux, need-more-info
