### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Dhruvin-delemont** [brave/brave-browser#36891] opened 2024-03-18 09:50 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.63.174 Chromium: 122.0.6261.128
Operating System: Windows NT 10.0.19045

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. First I type brave://new-tab-page/ in URL and hit
Image:-
![image](https://github.com/brave/brave-browser/assets/139969810/ce7ca5bb-ff39-44a8-8048-a604a3880f1f)

2. After I clicked on the Google search bar Brave was immediately close
Image :- 
![image](https://github.com/brave/brave-browser/assets/139969810/7c266392-db9f-42d7-99cd-75984f04739b)

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/37f41000-7ff7-a70b-0000-000000000000

**Comment by rebron** [comment] 2024-03-20 18:07
Fixed with https://github.com/brave/brave-core/pull/22231
and closing as dupe of https://github.com/brave/brave-browser/issues/36393

**Closed by rebron** 2024-03-20 18:07 UTC
