### ISSUE TITLE
Add import from Opera support

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#995] opened 2018-09-07 01:08 UTC

**Comment by jonathansampson** [comment] 2020-08-04 00:25
Looks like the Chromium team punted [this request](https://bugs.chromium.org/p/chromium/issues/detail?id=487&q=opera%20importer&can=1) back in 2008. From what I can tell, we'd need to author [a distinct importer](https://source.chromium.org/chromium/chromium/src/+/master:chrome/utility/importer/) for Opera, and [present it as an option](https://source.chromium.org/chromium/chromium/src/+/master:chrome/utility/importer/importer_creator.cc) with the others.

This request has come up from time to time in the past:

![twitter com_dasunteekz_status_1264796717343551491](https://user-images.githubusercontent.com/815158/89239403-af504f80-d5be-11ea-869d-9d123dd980e0.png)
![twitter com_dasunteekz_status_1264796717343551491 (1)](https://user-images.githubusercontent.com/815158/89239453-dad33a00-d5be-11ea-9eee-4e8311112a0c.png)

For now, the only workaround I'm aware of is to export bookmarks from Opera, and import them into Brave.

**Comment by bsclifton** [comment] 2022-09-12 05:00
Closing as duplicate of https://github.com/brave/brave-browser/issues/23738 which was recently resolved 😄

**Closed by bsclifton** 2022-09-12 05:00 UTC
Labels: feature/importer
