### ISSUE TITLE
Jump focus to the current page from Address bar by Esc

### ISSUE THREAD

**Issue by Guchman** [brave/brave-browser#3201] opened 2019-02-02 19:11 UTC
Hi, there is annoying bug on Mac.
1. Open some page
2. Cmd+L to jump Address bar
3. Press Esc

I expect to go back to the page. But nothing happens.
It's more like chromium bug, cause same in Chrome. But Vivaldi browser fix this behaviour.
Fix this too, please. It's very annoying for mouseless keyboard surfers:)

**Comment by srirambv** [comment] 2019-02-04 02:35
cc @rebron

**Comment by agentofuser** [comment] 2019-06-23 13:59
I confirm. This is a Chromium issue that is very detrimental to keyboard accessibility.

I have to do 'Command+F xxxx' every time to work around, and I do this dozens of times a day.

It would be super nice if Brave could fix this ♿🙏

**Comment by Brave-Matt** [comment] 2019-07-19 06:57
+1 from Community:
https://community.brave.com/t/esc-key-doesnt-remove-focus-from-the-address-bar/71399

**Comment by Brave-Matt** [comment] 2019-07-19 07:01
Big +1 from me. 
It's an accessibility issue - Vivaldi, Opera, MS Edge, and Safari all offer this by default.  
~Related to: #4178

**Comment by rossmoody** [comment] 2019-07-19 20:54
Did a little digging on this one. I'm curious, from a usability perspective what does escape do that tab doesn't currently do to move focus from address bar to the page?

**Comment by Guchman** [comment] 2019-07-20 15:54
@rossmoody tab will move focus on NEXT element. Such as "brave shields" or plugins bar.
What I'm actually expect is returning focus to the site frame.
I'm using "Surfingkeys" plugin for mouseless navigation and it's really matters to have correct behaviour

**Comment by rossmoody** [comment] 2019-07-20 16:03
Tab on Mac moves the focus to the first element in the window. Are you on windows? If you press tab while the address bar is focused where does the focus go?

**Comment by Guchman** [comment] 2019-07-21 10:22
@rossmoody No, I'm on Mac.
cmd+L:
![image](https://user-images.githubusercontent.com/10250050/61589987-6e0b1e80-abba-11e9-9ca4-936f243da12b.png)
And then Tab:
![image](https://user-images.githubusercontent.com/10250050/61589994-824f1b80-abba-11e9-9454-ec6cea4da20c.png)

**Comment by rossmoody** [comment] 2019-07-21 21:43
@rebron @petemill Any idea why I might be having a different behavior than what's reported here?

I downloaded Surfingkeys extension and tried this behavior on Release, Beta and Dev and every case moved focus to first element in browser window and not shields when pressing tab. 

![tab-hover-1](https://user-images.githubusercontent.com/29072694/61597452-ce538d80-abc5-11e9-9b99-22a973d1d3d9.gif)

**Comment by agentofuser** [comment] 2019-07-31 22:45
I'm on macOS Nightly and I can confirm that tabbing while focus is on the omnibox moves the focus to the Brave Shields icon, then to BAT icon, then to every extension, then to the settings hamburger menu, and _then_ to the page.

**Comment by peauc** [comment] 2022-07-18 14:15
Is there any news on this issue ? 
@rossmoody The main problem I see with using tab is that it moves your selection to the next element, sometimes it can scroll the page.
I would expect pressing `Esc` to simple move the active focus to the current tab.

I'm using Vimium and it makes Braves close to unusable.

**Comment by fallaciousreasoning** [comment] 2023-04-12 23:41
Note: on Linux this seems to be working correctly for me. If I'm typing in the webpage, press CTRL+L, and then escape the focus goes back to the input on the webpage.

Is this working for you guys now?

**Comment by fallaciousreasoning** [comment] 2023-05-17 02:58
Closing, as this seems to work now.

**Closed by fallaciousreasoning** 2023-05-17 02:58 UTC
Labels: enhancement, feature/keyboard-shortcuts, priority/P5, repros-on-chrome, OS/Desktop
