### ISSUE TITLE
Site banner doesn't auto resize based on browser size

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1658] opened 2018-10-17 16:35 UTC
## Description 

Site banner doesn't auto resize based on browser size

## Steps to Reproduce

   1. Install 0.55.16 
   2. Enable rewards and add funds
   3. Visit a site and click on BR button-> Send Tip
   4. Shows banner page, resize browser window, banner doesn't resize and remains in its original size

## Actual result:

![tip](https://user-images.githubusercontent.com/17010094/47101689-cb77d680-d208-11e8-808e-413ebe0ddcf5.gif)

## Expected result:
Banner should auto resize based on browser window size

## Reproduces how often: 

Easy 

## Brave version (brave://version info)

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
- Does it reproduce on browser-laptop? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @petemill @bradleyrichter @jenn-rhim @brave/legacy_qa

**Comment by LaurenWags** [comment] 2018-10-17 22:48
Reproduced on macOS

Brave | 0.57.1 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

**Comment by petemill** [comment] 2018-10-18 00:00
I knew about this and we took the decision to not have it resize, because in order to get it auto-sizing height according to the content given an initial fixed width of the tab width we lose the ability to change the size. And even when I forced the size change, there were rendering issues. There are ways we could spend some time resolving the issue, but I didn't make the issue to follow-up, so thanks for doing that @srirambv

**Comment by kjozwiak** [comment] 2018-10-18 01:53
Reproduced on `Win 10 x64` using the following build:

Brave | 0.55.17 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows

**Closed** 2023-04-20 11:48 UTC
Labels: feature/rewards, priority/P5, QA/Yes, QA/Test-Plan-Specified
