### ISSUE TITLE
[Android] Continue button and text should be restyled to match spec

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26743] opened 2022-11-14 17:24 UTC
## Description 

Continue text is not shown clearly as the button color and text color is same in the geo selection modal popup
## Steps to reproduce 

   1. Clean profile 1.46.109
   2. Tab on the BR panel and click on the `Start using brave rewards`
   3. `Continue` text is not shown clearly in the geo selection modal popup

## Actual result 

Continue text is not shown clearly as the button color and text color is same in the geo selection modal popup
![image](https://user-images.githubusercontent.com/38657976/201725333-fbfa9f98-f63b-498f-898e-fcdbfe518346.png)

## Expected result

button color should be gray to differentiate the text color and button color, not sure about the design @Miyayes can suggest

Desktop
![image](https://user-images.githubusercontent.com/38657976/201725126-997d8e2a-6838-4d5c-93ef-b6eac780d680.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Galaxy Tab A7
   - Android version: version 12
   
## Brave version
1.46.109

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @deeppandya @Miyayes

**Comment by Miyayes** [comment] 2022-11-14 17:48
I think this is mostly a matter of bolding the text. I know bold weight on Android needs adjustment, since it tends to be thin. @sujitacharya2005

**Comment by deeppandya** [comment] 2022-11-15 21:21
@Miyayes this should be fixed with rewards 2.5 changes as i have introduced weights for fonts.

**Comment by Miyayes** [comment] 2022-11-23 17:28
Use the right shade of gray for the continue button.

**Closed** 2022-12-06 14:17 UTC
Labels: bug, feature/user-interface, feature/rewards, QA/Yes, QA/Test-Plan-Specified, OS/Android

**Comment by stephendonner** [comment] 2023-01-29 09:42
## Verified `PASSED` using `Brave` `1.48.141`, `Chromium`, `109.0.5414.119` on a `Google Pixel XL` (`arm64`)  running `Android 9`

### Steps:
1. installed `1.48.141`
2. launched Brave
3. tapped through onboarding
4. tapped on the `BAT` icon in the URL bar
5. tapped `Start using Brave Rewards`
6. looked at the (disabled) `Continue` button (compared color/styling against `1.47.146`)

#### Confirmed the `Continue` text is slightly more readable due to `font-weight`

### `Light` theme

`1.48.141` | `1.47.146`
-----------|----------
![Screenshot_20230129-181500](https://user-images.githubusercontent.com/387249/215317957-c33664e0-4959-4b72-8845-7c52bb91178a.png) | ![Screenshot_20230129-182136](https://user-images.githubusercontent.com/387249/215317961-b0387412-76be-41b0-b3f9-08ab80a61375.png)

#### `Dark` theme

`1.48.141` | `1.47.146`
-----------|----------
![Screenshot_20230129-181748](https://user-images.githubusercontent.com/387249/215318040-f29e7c1b-2b84-4eec-b394-fd886c8beda3.png) | ![Screenshot_20230129-182204](https://user-images.githubusercontent.com/387249/215318042-8777ef6d-3664-4709-9459-63dfc3fb1249.png)
