### ISSUE TITLE
Problem opening an embed PDF

### ISSUE THREAD

**Issue by bitcoinuser** [brave/brave-browser#1757] opened 2018-10-20 20:49 UTC
Brave Browser Version 0.55.18 Chromium: 70.0.3538.67 (Versão oficial) 64 bits
OS: Ubuntu 64

PDF.js v2.0.673 (compilação: 31012570)
Mensagem: Missing PDF "https://pje.tjdft.jus.br/pje/downloadBinario.seam".

![captura de tela de 2018-10-20 17-48-16](https://user-images.githubusercontent.com/1178856/47260353-60d8cc00-d490-11e8-942f-a919f6432862.png)

**Comment by srirambv** [comment] 2018-10-21 12:34
Dupe of #1287 . @bitcoinuser please use the template to fill out details. Just the screenshot doesn't give all the information.

**Closed by srirambv** 2018-10-21 12:34 UTC

**Comment by bitcoinuser** [comment] 2018-11-10 13:11
I still reproduce this issue on Brave version: Versão 0.56.12 Chromium: 70.0.3538.77 (Versão oficial) 64 bits

**Comment by srirambv** [comment] 2018-11-10 13:57
@bitcoinuser can please open a new issue with details filled in the template. Just a screenshot and browser version wont help. Please include the site details and steps mentioned in the template.

**Comment by bitcoinuser** [comment] 2018-11-10 14:10
Ok, posted here: https://github.com/brave/brave-browser/issues/2092
