### ISSUE TITLE
Brave Translate not working when Google Translate is active

### ISSUE THREAD

**Issue by tutkun** [brave/brave-browser#26569] opened 2022-11-06 10:59 UTC
## Description
Brave Translate button does not work when Google Translate Extension is installed and active in Brave Browser. Is this just me or is there a bug?

## Steps to Reproduce
  1. Open Brave Browser.
  2. Download the Google Translate plugin from https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb if it is not installed.
  3. After the installation is complete, click the Translate button of Brave Browser on the site you want to translate. Here the button will have a "hover" effect. But the popup menu will not open.
  4. Type "brave://extensions/" in the Url in Brave Browser and hit enter.
  5. Turn off the Checkbox button under Google Translate.
  6. Repeat step three. This time the popup will appear.

## Actual result:
Google Translate is turned off:
<img width="428" alt="Ekran Resmi 2022-11-06 13 44 28" src="https://user-images.githubusercontent.com/195842/200166778-cc2bf392-e11f-4fc1-917e-ab2d1986f5e2.png">

Google Translate is turned on:
<img width="498" alt="Ekran Resmi 2022-11-06 13 57 49" src="https://user-images.githubusercontent.com/195842/200166835-73dc41ed-d017-4833-9e54-a28de1f028dd.png">

## Brave version (brave://version info)
1.45.118 Chromium: 107.0.5304.91 (Resmi Derleme) (x86_64)

## Miscellaneous Information:

**Comment by rebron** [comment] 2022-11-11 19:12
Closing as dupe of https://github.com/brave/brave-browser/issues/24715. Will be fixed in the next release next Wednesday.

**Closed by rebron** 2022-11-11 19:12 UTC
Labels: OS/Desktop, brave-translate

**Comment by tutkun** [comment] 2022-11-11 22:05
> Closing as dupe of #24715. Will be fixed in the next release next Wednesday.

Hello @rebron, is it possible for you to improve your translation feature a bit in the next version?

Like this;
As with the Google Translate Extension, if the user selects some text, a small icon will appear, and clicking the icon will show the selected text translated into a bubble. This will be very useful.

Thank you.
