### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by tsaro** [brave/brave-browser#37148] opened 2024-03-27 17:58 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.64.109 Chromium: 123.0.6312.58
Operating System: Mac OS X 13.4.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Randomly right clicking causes this crash, doesn't seem to happen on any particular site but has happened multiple times on gmail.  This seems to be more reproducible on windows from "create shortcut" mode opening in dedicated windows. 
2. Entire browser crashes including any dedicated shortcut windows

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/ad770000-686b-ba0b-0000-000000000000

**Comment by rebron** [comment] 2024-03-27 23:04
@tsaro Can you update to the latest 1.64.113 and let us know if you're still experiencing the problem. I think dupe of https://github.com/brave/brave-browser/issues/36995

**Comment by iefremov** [comment] 2024-10-02 12:18
stale

**Closed by iefremov** 2024-10-02 12:18 UTC
Labels: crash, priority/P2
