### ISSUE TITLE
Request for script block/whitelist to also block/whitelist subdomains

### ISSUE THREAD

**Issue by yt-dddd775500** [brave/brave-browser#7538] opened 2019-12-30 06:57 UTC
## Description 

Whitelisting or blocking scripts for a domain doesn't whitelist or block scripts for subdomains.

## Steps to Reproduce

   1. (this assumes that javascript is disabled in the browser settings) Whitelist scripts for a domain [reddit.com]
   2. visit a subdomain [old.reddit.com]
   3. scripts are enabled in the main domain [reddit.com] but remain disabled in the subdomain [old.reddit.com].

## Actual result:

Whitelisting/blocking a domain does not change the whitelist/block setting for any subdomains.

## Expected result:
Whitelisting/blocking a domain also whitelists/blocks all subdomains.

Whitelisting/blocking [reddit.com] would also whitelist/block [old.reddit.com].

Whitelisting/blocking [imgur.com] would also whitelist/block [m.imgur.com].

## Brave version (brave://version info)

Any Android version of Brave Browser.

**Comment by bsclifton** [comment] 2021-04-12 06:42
May be a duplicate of https://github.com/brave/brave-browser/issues/5290

**Comment by bsclifton** [comment] 2022-08-15 16:43
Closing as a duplicate of https://github.com/brave/brave-browser/issues/12782 - that issue should capture all the details needed to accomplish this 😄

**Closed by bsclifton** 2022-08-15 16:43 UTC
Labels: feature/shields, priority/P4, feature/shields/!scripts
