### ISSUE TITLE
closing all "BraveUpdate.exe" processes when uninstalling Brave

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#7406] opened 2019-12-16 18:40 UTC
## Description 

When you currently uninstall Brave on Win, you'll notice that sometimes there's a `BraveUpdate.exe` process still running. Sometimes there's even multiple `BraveUpdate.exe` processes running. When this happens, it usually means the uninstaller won't remove everything from `C:\Program Files (x86)\BraveSoftware` due to `C:\Program Files (x86)\BraveSoftware\Update\BraveUpdate.exe` still running.

## Steps to Reproduce

   1. install any version of Brave on a Win
   2. uninstall Brave using `Uninstall a program` via the `Control Panel`
   3. check `Task Manager` and you'll sometimes see `BraveUpdate.exe` still running

## Actual result:

![Annotation 2019-12-10 140357](https://user-images.githubusercontent.com/2602313/70933099-47d29900-2009-11ea-9dbe-9f90c4b89b94.jpg)

## Expected result:

Every process that's related to Brave should be closed once an uninstall is initiated.

## Reproduces how often: 

100% reproducible using the above STR. Quick note though, sometimes `BraveUpdate.exe` isn't running so it really depends on timing. However, if you attempt to uninstall while `BraveUpdate.exe` is running, you'll run into the above issue.

## Brave version (brave://version info)

Brave | 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)
--- | ---
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Windows 10 OS Version 1909 (Build 18363.535)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @mbacchi @simonhong @bsclifton @brave/legacy_qa

**Comment by simonhong** [comment] 2019-12-16 22:51
@kjozwiak This is expected behavior for now. As you said, it's timing issue.
Uninstall browser doesn't mean uninstall installer directly.
After uninstalling all browser, installer can run for some time because installer uninstall itself when it doesn't have any application for update check. It checks this periodically. So it seems normal :)

**Comment by bsclifton** [comment] 2019-12-17 17:34
I believe this is expected behavior too. When you reboot, it should clean itself up

I didn't notice this behavior until we used a test Omaha server for 1.0 testing... because the `BraveUpdate.exe` needs to be replaced with the version pointing at the dev Omaha server

**Comment by mbacchi** [comment] 2020-03-20 21:58
Can we close this or is it something we need to investigate further?

**Comment by simonhong** [comment] 2020-03-20 23:45
I think we can close this.
As wrote above, this is expected behavior.

**Closed** 2020-03-21 17:06 UTC
Labels: OS/Windows, QA/Test-Plan-Specified, QA/Yes, bug, installer/omaha, priority/P4, setup/installer
