### ISSUE TITLE
Unable to send NFT to a different account 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26667] opened 2022-11-10 14:33 UTC
## Description 

Unable to send NFT to a different account 

## Steps to Reproduce

   1. Add Solana NFT to portfolio
   2. Add a new Solana Account
   3. Try to send to second solana Account, fails

## Actual result:

https://user-images.githubusercontent.com/17010094/201118892-d9eb9a9e-9f82-457f-a326-bf2e15eeb287.mp4

## Expected result:
Should be able to send NFT to a second account

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.47.61 Chromium: 107.0.5304.110 (Official Build) nightly (64-bit)
-- | --
Revision | `2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @yrliou

**Comment by yrliou** [comment] 2022-11-10 19:02
The error @srirambv was seeing was due to a regression caused by another PR unrelated to Solana NFT work.
However, there's indeed a bug for sending Solana NFT in https://github.com/brave/brave-core/pull/15844, the amount is not correctly set to 1 and is divided by network decimals (9), which introduces a tx trying to send out 0.000001 NFT instead of 1.

**Comment by yrliou** [comment] 2022-11-10 20:46
Fixed by https://github.com/brave/brave-core/pull/15883

**Closed by yrliou** 2022-11-10 20:46 UTC
Labels: bug, QA/Yes, release-notes/exclude, feature/web3/wallet, OS/Desktop

**Comment by kjozwiak** [comment] 2022-11-11 05:01
The above requires `1.45.125` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment] 2022-11-15 10:47
Verification passed on 

Brave | 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit)
-- | --
Revision | `2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}`
OS | Linux

- Verified steps from issue description
- Verified Solana NFT doesn't show any preset values when selected on Send tab
- Verified Solana NFT is listed under the NFT heading in send tab. 
- Verified balance of other SPL tokens are shown correctly
- Encountered [#26684](https://github.com/brave/brave-browser/issues/26684) & [#26685]( https://github.com/brave/brave-browser/issues/26685)

https://user-images.githubusercontent.com/17010094/201900363-27184472-51bc-4eb8-9f73-50da4eb0e17e.mp4

---------------------

Verification passed on 

Brave | 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit) 
-- | --
Revision | `2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from issue description
- Verified Solana NFT doesn't show any preset values when selected on Send tab
- Verified Solana NFT is listed under the NFT heading in send tab. 
- Verified balance of other SPL tokens are shown correctly
- Encountered [#26684](https://github.com/brave/brave-browser/issues/26684) & [#26685]( https://github.com/brave/brave-browser/issues/26685)

https://user-images.githubusercontent.com/17010094/201899703-76b3f87c-d023-4e29-9cc1-43416898d905.mp4

---------------------

Verification passed on 

Brave | 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit) 
-- | --
Revision | `2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from issue description
- Verified Solana NFT doesn't show any preset values when selected on Send tab
- Verified Solana NFT is listed under the NFT heading in send tab. 
- Verified balance of other SPL tokens are shown correctly
- Encountered [#26684](https://github.com/brave/brave-browser/issues/26684) & [#26685]( https://github.com/brave/brave-browser/issues/26685)

https://user-images.githubusercontent.com/17010094/201900867-51f1bd89-f9cd-4422-8afb-db61a959264d.mov
