### ISSUE TITLE
network-audit intermittently fails on Linux

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#6189] opened 2019-09-26 22:12 UTC
On CI, only on Linux, occasionally fails with an error similar to:
<pre>
15:00:47  undefined:17221
15:00:47  {"phase":2,"source":{"id":82,"type":8}]}
15:00:47                                        ^
15:00:47  
15:00:47  SyntaxError: Unexpected token ] in JSON at position 77930745
15:00:47      at JSON.parse (<anonymous>)
15:00:47      at start (/home/ubuntu/jenkins/workspace/ois-rebrand-linux-changelog-6093/lib/start.js:144:23)
15:00:47      at Command.listener (/home/ubuntu/jenkins/workspace/ois-rebrand-linux-changelog-6093/node_modules/commander/index.js:315:8)
15:00:47      at Command.emit (events.js:203:13)
15:00:47      at Command.parseArgs (/home/ubuntu/jenkins/workspace/ois-rebrand-linux-changelog-6093/node_modules/commander/index.js:654:12)
15:00:47      at Command.parse (/home/ubuntu/jenkins/workspace/ois-rebrand-linux-changelog-6093/node_modules/commander/index.js:474:21)
15:00:47      at Object.<anonymous> (/home/ubuntu/jenkins/workspace/ois-rebrand-linux-changelog-6093/scripts/commands.js:155:4)
15:00:47      at Module._compile (internal/modules/cjs/loader.js:868:30)
15:00:47      at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
15:00:47      at Module.load (internal/modules/cjs/loader.js:731:32)
</pre>

**Comment by mkarolin** [comment] 2019-09-26 22:12
I believe this started happening with C77

**Comment by rebron** [comment] 2019-10-15 18:48
cc: @diracdeltas Can you take a look?

**Comment by diracdeltas** [comment] 2019-10-15 19:29
@jumde does this error look familiar to you? i vaguely remember you may have fixed something like this in the past

**Comment by jumde** [comment] 2019-10-15 21:19
This looks like a parsing error, most of the errors that I have looked at involved process being terminated early/not-at-all. I can look at this, not seen this error on mac though.

**Comment by bsclifton** [comment] 2019-12-03 04:59
Problem appears to be here:
https://github.com/brave/brave-browser/blob/9cc247b54a0e76b63c406cd34271f4edb72c72ec/lib/start.js#L140-L143

(introduced with https://github.com/brave/brave-browser/pull/2787)

Going to look at a better solution to that problem...

**Comment by diracdeltas** [comment] 2019-12-03 19:49
> Going to look at a better solution to that problem...

maybe only do the json hack if the platform is windows?

**Comment by bsclifton** [comment] 2019-12-04 07:09
@diracdeltas interestingly enough, it seems the output is always malformed (when testing on Linux). Maybe the way the process gets terminated doesn't let it clean up properly?

**Comment by diracdeltas** [comment] 2019-12-04 19:31
@bsclifton i wonder if that's because it's sending SIGKILL instead of SIGTERM? https://github.com/brave/brave-browser/pull/7182/files#diff-c1a0ca0ae9997d37108b9580a48466bcR98

**Comment by bsclifton** [comment] 2019-12-04 19:42
@diracdeltas yes - I think that's definitely part of the problem. Before that was introduced (with https://github.com/brave/brave-browser/pull/4036) it was hanging indefinitely.  I'm curious if SIGTERM for all cases would work? I suspect there was an issue with it (@jumde would know)

Important to note though: because this is abruptly being terminated, there are logs which haven't been flushed (because the JSON isn't terminated properly). **This means the integrity of the check is questionable, since there is currently the band-aid in place which corrects the missing line ending**. There could be entries (which might be considered violations) which haven't been written to the log which are dropped when the process is terminated

I'm going to create a new issue for the integrity - maybe you can help me prioritize? 😄

**Comment by bsclifton** [comment] 2020-02-03 18:14
Closing as a duplicate of https://github.com/brave/brave-browser/issues/7207

**Closed by bsclifton** 2020-02-03 18:14 UTC
Labels: QA/No, audit-non-blocking, dev-concern, priority/P3, release-notes/exclude
