### ISSUE TITLE
"OK" Button on Token Grant does nothing

### ISSUE THREAD

**Issue by aphelionz** [brave/brave-browser#2774] opened 2019-01-01 15:41 UTC
## Description 

When visiting any site and clicking the Brave "triangle" logo, the token grant and corresponding "OK" button does not respond to clicks. 

![screenshot_20190101_104155](https://user-images.githubusercontent.com/106148/50574216-dc6cc880-0db1-11e9-8440-85ba9b65a035.png)

## Steps to Reproduce

   1. Visit any site
   2. Click the brave logo to the right of the address bar
   3. Click the "OK" button under token grant.

## Actual result:

4. Nothing happens, it is unresponsive.

## Expected result:

4. I am taken to the token grant page or to more information

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Version 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Have not tried.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by aphelionz** [comment] 2019-01-06 00:54
Another interesting thing is that other controls in that same popup seem to be affected as well. For example, I cannot toggle the "Include in Auto-Contribute" slider for GitHub here:

![screenshot_20190105_195359](https://user-images.githubusercontent.com/106148/50730793-b03fa780-1123-11e9-800e-6f55ca0711db.png)

**Comment by NejcZdovc** [comment] 2019-01-10 11:21
closing as dupe of https://github.com/brave/brave-browser/issues/2883

**Closed by NejcZdovc** 2019-01-10 11:21 UTC
Labels: feature/rewards, needs-investigation, priority/P2, regression
