### ISSUE TITLE
[Android] Replace "chrome://" with "brave://" on Android

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#10117] opened 2020-06-05 19:06 UTC
## Description

On Android, pages like `rewards-internals` are under `chrome://` and not under `brave://`. In order to reach parity with desktop, `brave://` should resolve as expected.

**Why should this be considered a priority?**

1. **Optics:** Given the high number of requests we make to users (in public) to send us their `rewards-internals` or check other settings (e.g., relating to ad block, browser version info, etc.), `chrome://` pages are more visible to end-users than one might expect. 

2. **User disorientation:** Navigating to `chrome://` pages is very disorienting to users, as they don't understand why their **Brave Browser** uses/asks for `chrome://` pages. This is especially the case for users who emphatically quit Google Chrome for Brave.

3. **Support duplication:** Because of the inconsistency between desktop and Android, support docs must always written to cover both `brave://` and `chrome://` cases, which adds unnecessary complexity to support instructions.

**Comment by srirambv** [comment] 2020-06-06 03:41
Closing as dupe of #9427

**Closed by srirambv** 2020-06-06 03:41 UTC
Labels: OS/Android
