### ISSUE TITLE
middle click closes pinned tab

### ISSUE THREAD

**Issue by cjwijtmans** [brave/brave-browser#4144] opened 2019-04-17 15:55 UTC
## Description 
middle click closes pinned tab

## Steps to Reproduce
   1. open tab
   2. pin tab
   3.  middle click tab

## Actual result:
pinned tab closes

## Expected result:
pinned tab does not close

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)
Revision | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS | Windows 10 OS Build 17763.437

## Version/Channel Information:
-

## Other Additional Information:
A pinned tab is an important tab. Which means we should avoid accidentally closing it with a middle click. It requires an extra step by right clicking and closing it. This behaviour is in other browsers.

## Miscellaneous Information:
-

**Comment by rebron** [comment] 2019-04-19 16:12
Closing. Expected behavior, not going to deviate from other browsers for this ue.

**Closed by rebron** 2019-04-19 16:12 UTC

**Comment by cjwijtmans** [comment] 2019-04-20 10:11
> Closing. Expected behavior, not going to deviate from other browsers for this ue.

I think you are misreading dude. the brave browser IS deviating.

**Comment by cjwijtmans** [comment] 2019-04-20 10:13
Please re-open, or i will spam this issue. Or ban me from this trash browser issue page. Whatever you like.

**Comment by srirambv** [comment] 2019-04-20 14:45
This is default behaviour in Chromium based browsers unless heavily customized. Middle click on links open in new tab and middle click on tab closes it (irrespective of pinned/normal tab).  We do not want to deviate from Chromium behaviour.

**Comment by rebron** [comment] 2019-04-20 15:55
@cjwijtmans left click to focus, middle click to close, and right click for context menu. Middle click like right click is already a special action. To remove functionality, and to use middle click to open the context menu as you're proposing (redundant since right click does that), and then deviating (not always wrong) from what other apps are doing aren't the right things to do. There will be an immediate issue filed on add middle click to close pinned tab.

Further, users can go back to history to recently closed tabs to restore their important pinned tab. Should've explained more before closing sorry.
