### ISSUE TITLE
No feedback at unsuccessful wallet restore attempt

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#27569] opened 2022-12-29 17:14 UTC
On wallet restoration screen, entered my seed phrase, the new password, and clicked 'Restore'. Inaccurate seed phrase was entered but I'm at the Unlock screen with no feedback. It took a moment to realize that something was wrong. 
@minkyeongshin @jamesmudgett 

<img width="1523" alt="Screenshot 2022-12-29 at 9 06 06 AM" src="https://user-images.githubusercontent.com/4369856/209986606-9a27b0fe-b22d-45bb-bc32-91535f718bec.png">
<img width="1523" alt="Screenshot 2022-12-29 at 9 06 10 AM" src="https://user-images.githubusercontent.com/4369856/209986637-a01012a8-7fc7-4ea2-bd9c-1ba28a61b000.png">

**Comment by Douglashdaniel** [comment] 2023-01-12 20:40
Closing as duplicate of https://github.com/brave/brave-browser/issues/25973

**Closed by Douglashdaniel** 2023-01-12 20:40 UTC
Labels: closed/duplicate, usability, feature/web3/wallet, OS/Desktop
