### ISSUE TITLE
Unable to add bookmark to subfolder

### ISSUE THREAD

**Issue by markoshust** [brave/brave-browser#625] opened 2018-07-22 16:57 UTC
## Description 
Unable to add bookmark to bookmark subfolder

## Steps to Reproduce
   1. Create bookmark subfolder by going to Bookmarks>Bookmarks, then create Subfolder of "Other Bookmarks" named "Foo"
   2. Load new browser tab info, and try to bookmark page
   3. "Foo" is not displayed or selected. Can only bookmark pages under Bookmarks Toolbar or Other Bookmarks

## Actual result:
<img width="354" alt="screen shot 2018-07-22 at 12 55 44 pm" src="https://user-images.githubusercontent.com/437029/43048010-993bc788-8dae-11e8-866e-071ec89fe3ed.png">

## Expected result:
I expect the dropdown menu in the screenshot above to show:
```
Bookmarks Toolbar
Other Bookmarks
- Foo
```

## Reproduces how often: 
Always

## Brave version (about:brave info) 
0.23.39

### Reproducible on current release:
Yes

**Comment by bsclifton** [comment] 2018-07-22 17:00
Thanks for the report @markoshust! This is a duplicate of https://github.com/brave/browser-laptop/issues/12962

Also, please note that `brave-browser` is for our upcoming Brave Core product. The current live product can be found at https://github.com/brave/browser-laptop/issues/

**Closed by bsclifton** 2018-07-22 17:00 UTC
