### ISSUE TITLE
When a tab is pinned and unpinned, the last unpinned tab do not have ability to close (`x) the tab in Expanded view

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#29800] opened 2023-04-18 00:57 UTC
## Description 

Found while testing https://github.com/brave/brave-browser/issues/29692.   When a tab is pinned and unpinned, the last unpinned tab do not have ability to close (`x) in Expanded view.  However, if I clicked Minimize tabs button and reopen the vertical tab view, the `x` is shown to close the tab

## Steps to Reproduce

   1. Install 1.51.93
   2. launch Brave
   3. visit a site (pinterest.com) in a new tab 
   4. enable vertical tabs via brave://flags
   5. enable vertical tabs in the context menu via `Use vertical tabs`
   6. added few more tabs in the vertical view (facebook, instagram)
   7. Pin all the tabs and unpin them
   8. verify all of the unpinned tabs show `x` 

## Actual result:

The last unpinned tab (facebook) doesn't have `x` in the Expanded view.  Minimized and expanded the vertical view to show the `x`

https://user-images.githubusercontent.com/98358127/232640916-8698bc0d-fb59-4ec8-8710-bb0a62f60789.mp4

## Expected result:
Tab should have `x` when tab is unpinned

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @sangwoo108 
cc: @brave/qa-team

**Comment by sangwoo108** [comment] 2023-04-18 01:10
Just checking, Do you mean that pinned tabs should show close button when vertical tab strip is floating on mouseover? I'm a little bit unsure about `Tab should have x when tab is unpinned`,as it seems to show close buttons when it's unpinned.

**Comment by MadhaviSeelam** [comment] 2023-04-18 15:13
@sangwoo108 so the last tab (facebook) that was unpinned doesn't have `x`.   (it's 0:40).  It's almost disabled state. 
![image](https://user-images.githubusercontent.com/98358127/232645983-eb5d7f13-9bc1-4dab-90d4-a298640ca429.png)

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment] 2023-04-18 21:42
@sangwoo108 the problem is bigger than the issuer (tried to) explain.

All you need to reproduce this is to be in expanded mode, then have two tabs (or more) and then pin one of the tabs and unpin it.

What breaks is the **mouse** interaction with the **first tab**, triggered by the unpinning of the tab or all tabs. What I mean by saying that, is that the unpinned tab is not the one broken, but **any** tab that is on top/first breaks, so if you move the tab or close it, whatever tab is now the top one will not have mouse interaction.

**This's the reason reason why the close (x) button doesn't appear**, it's not because the tab doesn't have it, but because mouse interaction broke. You can't Left or right click or hover on the tab. 
Keyboard shortcuts still work, so that's why you can switch to the tab, close it, move it and do anything you want with the tab, but not if you want to use the mouse on it.

The only way to fix it is to 'minimize tabs' and then expand them again.

I recorded the problem the exact problem, I had to use keyboard shortcuts like ctrl+1, ctrl+shift+pagedown/up, ctrl+w and ctrl+shift+t to show how the problem is in the first tab, doesn't matter if the unpinned tab get closed or moved.

![brave_2023-04-18_15-18-50](https://user-images.githubusercontent.com/122518587/232909408-29bd807f-7c07-45e1-bf70-1f8be2e412e5.gif)

If you can't reproduce it in your OS, I have Windows (11 Version 21H2 (Build 22000.1817)) and the OP is using Windows as well, so might be a Windows thing and I am currently using Brave 1.52.53.

**Comment by sangwoo108** [comment] 2023-04-18 23:26
> @sangwoo108 so the last tab (facebook) that was unpinned doesn't have x. (it's 0:40). It's almost disabled state.

> @sangwoo108 the problem is bigger than the issuer (tried to) explain.


@MadhaviSeelam , @Emi-TheDhamphirInLoveUnderTheFrozenStar  Thanks for clarification! Let me check out again.

**Closed** 2023-04-21 00:04 UTC
Labels: bug, priority/P3, QA/Test-Plan-Specified, OS/Desktop, feature/vertical-tabs

**Comment by kjozwiak** [comment] 2023-04-26 00:27
The above requires `1.51.105` or higher for `1.51.x` verification 👍

**Comment by MadhaviSeelam** [comment] 2023-04-27 21:37
Verification `PASSED` using 
```
Brave | 1.51.106 Chromium: 113.0.5672.53 (Official Build) (64-bit)
-- | --
Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```

Installed 1.51.106
launched Brave
enabled vertical tabs flas via brave://flags/#brave-vertical-tabs
visited a site (pinterest.com) in a new tab
enabled `Use vertical tabs` in the context menu
added few more tabs in the vertical tab view (facebook, instagram)
Pinned tabs and unpinned
verify all of the unpinned tabs show x

Confirmed all unpinned tabs show `x` and able to remove the tabs

example | example | example | example 
---- | ---- | ----- | -----
<image width = "600" alt="image" src="https://user-images.githubusercontent.com/98358127/234996193-cc326107-584f-4a23-8181-6416a3f7bd51.png">|<image width = "600" alt="image" src="https://user-images.githubusercontent.com/98358127/234995753-e2239922-b0e1-487d-b764-81403ff33c69.png">|<image width = "600" alt="image" src="https://user-images.githubusercontent.com/98358127/234995806-5d39cfc3-66cf-4165-a41c-bf0dfefa427f.png">|<image width = "600" alt="image" src="https://user-images.githubusercontent.com/98358127/234996472-031d6216-f38f-4027-8070-b7ececfef3c1.png">
