### ISSUE TITLE
add widget stack transition

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#9248] opened 2020-04-15 23:46 UTC
## Description 
When selecting a widget in the widget stack, there should be a transition animation to smooth out the selection, otherwise it's jarring.

Using the spaceindown effect.
example: https://www.minimamente.com/project/magic/ 

## Steps to Reproduce

   1. Go to the New Tab page.
   2. Select widget in the background, either Brave Rewards or Binance to move it to the front.
   3. Notice that the selection happened abruptly.

## Expected result:
Smoother transition when making a widget selection.

## Reproduces how often: 
Easily.

## Brave version (brave://version info)

Brave | 1.9.21 Chromium: 81.0.4044.92 (Official Build) nightly (64-bit)
-- | --
Revision | 32921c79b6f01a0fb2deef0e1d45b42f96581051-refs/branch-heads/4044@{#883}
OS | macOS Version 10.15.5 (Build 19F53f)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment] 2020-04-15 23:46
cc: @ryanml @karenkliu

**Comment by ryanml** [comment] 2020-10-06 06:26
Closing as a dupe of https://github.com/brave/brave-browser/issues/8856

**Closed by ryanml** 2020-10-06 06:26 UTC
Labels: QA/Yes, feature/widgets, priority/P3

**Comment by bbondy** [comment] 2020-10-13 13:39
Please add `closed/duplicate` label so the issue will be ignored. 
`QA/yes` isn't needed, but also won't be looked at so not a big deal on that.
