### ISSUE TITLE
Rewards tab remains blank, browser console shows errors about 'this.props.rewardsData.adsData' 

### ISSUE THREAD

**Issue by ztickm** [brave/brave-browser#12572] opened 2020-11-07 16:06 UTC
## Steps to Reproduce

   1. Go to the Rewards Tab

## Actual result:

The page loads the `cr-toolbar tab` but the actual content div `id="root"` stays empty.
The dev console prints this: 
```
brave_rewards_page.bundle.js:76 TypeError: Cannot destructure property 'adsEnabled' of 'this.props.rewardsData.adsData' as it is undefined.
    at Xf.componentDidMount (brave_rewards_page.bundle.js:3609)
    at Ro (brave_rewards_page.bundle.js:76)
    at jo (brave_rewards_page.bundle.js:76)
    at brave_rewards_page.bundle.js:76
    at Object.t.unstable_runWithPriority (brave_rewards_page.bundle.js:85)
    at Sl (brave_rewards_page.bundle.js:76)
    at xl (brave_rewards_page.bundle.js:76)
    at Cl (brave_rewards_page.bundle.js:76)
    at Al (brave_rewards_page.bundle.js:76)
    at Zo (brave_rewards_page.bundle.js:76)
no @ brave_rewards_page.bundle.js:76
n.callback @ brave_rewards_page.bundle.js:76
Ja @ brave_rewards_page.bundle.js:76
Ha @ brave_rewards_page.bundle.js:76
Ro @ brave_rewards_page.bundle.js:76
jo @ brave_rewards_page.bundle.js:76
(anonymous) @ brave_rewards_page.bundle.js:76
t.unstable_runWithPriority @ brave_rewards_page.bundle.js:85
Sl @ brave_rewards_page.bundle.js:76
xl @ brave_rewards_page.bundle.js:76
Cl @ brave_rewards_page.bundle.js:76
Al @ brave_rewards_page.bundle.js:76
Zo @ brave_rewards_page.bundle.js:76
Ul @ brave_rewards_page.bundle.js:76
Fl @ brave_rewards_page.bundle.js:76
jl.render @ brave_rewards_page.bundle.js:76
(anonymous) @ brave_rewards_page.bundle.js:76
Tl @ brave_rewards_page.bundle.js:76
Ll @ brave_rewards_page.bundle.js:76
render @ brave_rewards_page.bundle.js:76
initialize @ brave_rewards_page.bundle.js:3609
```
and this
```
brave_rewards_page.bundle.js:3609 Uncaught TypeError: Cannot destructure property 'adsEnabled' of 'this.props.rewardsData.adsData' as it is undefined.
    at Xf.componentDidMount (brave_rewards_page.bundle.js:3609)
    at Ro (brave_rewards_page.bundle.js:76)
    at jo (brave_rewards_page.bundle.js:76)
    at brave_rewards_page.bundle.js:76
    at Object.t.unstable_runWithPriority (brave_rewards_page.bundle.js:85)
    at Sl (brave_rewards_page.bundle.js:76)
    at xl (brave_rewards_page.bundle.js:76)
    at Cl (brave_rewards_page.bundle.js:76)
    at Al (brave_rewards_page.bundle.js:76)
    at Zo (brave_rewards_page.bundle.js:76)
```
## Expected result:

The content loads
## Reproduces how often: 

Easily reproduced in my case, it does it everytime

## Brave version (brave://version info)

> Brave | 1.16.72 Chromium: 86.0.4240.183 (Official Build) (64-bit)
> Revision | 0b568b034b8f7994697cb341eeca5979b84151cc-refs/branch-heads/4240@{#1374}
> OS | Linux

## Version/Channel Information:

I don't know, but the error happened after I updated from an outdated version to a previous update, I updated it again once 1.16.72 came out.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
Nah
- Does the issue resolve itself when disabling Brave Rewards? 
It's about Brave Rewards
- Is the issue reproducible on the latest version of Chrome? 
No, said feature not available in Chrome

**Comment by tmancey** [comment] 2020-11-09 11:48
@ztickm Do you know which version you upgraded from please? Thank you

**Comment by ztickm** [comment] 2020-11-09 22:47
@tmancey I'm pretty sure it was version 0.73 or something around that, I had installed both Brave and Brave Dev at the same time, I hadn't updated the Dev edition since I installed it, it's at :
> Version 0.73.65 Chromium: 78.0.3904.87 (Official Build) dev (64-bit)

The outdated Brave Dev's reward page works.
I've checked the local storage under "Application" in the dev tools, the object `adsData` isn't present in the new version at all, while it is in the new version:
* Old version:
```
createdTimestamp: 1573597012910, enabledMain: true, enabledAds: true, enabledAdsMigrated: true,…}
adsData: {adsEnabled: true, adsPerHour: 5, adsUIEnabled: true, adsIsSupported: true,…}
adsAdNotificationsReceivedThisMonth: 0
adsEnabled: true
adsEstimatedPendingRewards: 0
adsIsSupported: true
...
```
* New version:
```
{createdTimestamp: 1548251526572, enabledMain: true, enabledAds: true, enabledContribute: false,…}
addresses: {BAT: {address: "REDACTED",…},…}
adsHistory: [{,…}, {,…}, {,…}, {,…}, {,…}, {,…}, {,…}, {,…}, {,…}, {,…}, {,…}, {,…}, {,…}]
autoContributeList: []
balance: {total: 0, wallets: {}}
connectedWallet: false
contributeLoad: true
...
```

**Comment by ztickm** [comment] 2020-11-16 19:26
### Update:

Today I updated to `1.16.76`, the page now works with no errors to the console.
The local storage now shows the object `adsData` and its children.

The Release versions suggest nothing has changed regarding rewards, the origin of the problem remains unknown to me. Anyone knows how / where this particular local data is assigned / accessed?

**Comment by tmancey** [comment] 2020-11-16 22:45
@ztickm Great news. I will leave the issue open and prioritize to investigate further over the next few days.

**Comment by inian** [comment] 2021-01-01 04:06
Hi, this is happening to me reliably. 
![image](https://user-images.githubusercontent.com/2155545/103433304-ca84c100-4c29-11eb-9bad-0e6b91c75365.png)

Brave version - Version 1.18.77 Chromium: 87.0.4280.101 (Official Build) (x86_64)

**Comment by tmancey** [comment] 2021-01-04 18:44
@inian Did you restore a user profile? If so, do you know from which version? Thanks

**Comment by inian** [comment] 2021-01-05 20:35
I did not restore a user profile @tmancey. I do have multiple user profiles on Brave though..and the rewards page doesn't work on any profile

**Comment by tmancey** [comment] 2021-01-13 12:01
@inian I am investigating the cause of the issue. Thanks

**Comment by tmancey** [comment] 2021-01-22 15:14
@inian Would you be willing to screen-share as I am unable to reproduce. Thanks

**Comment by inian** [comment] 2021-01-22 17:03
I have tried disabling the extensions I have and it still doesn't solve the issue

https://user-images.githubusercontent.com/2155545/105521415-d2aaba80-5d16-11eb-8df6-019dca0583e5.mov

**Comment by tmancey** [comment] 2021-01-26 08:15
@inian Did you see my message above concerning a screen-share please?

**Comment by inian** [comment] 2021-01-27 06:21
Hey Terry, ah I thought you meant a screen recording of the issue. 

I have sent an email to the email mentioned on your github profile. Let's schedule a time for the screenshare.

**Comment by tmancey** [comment] 2021-01-27 14:00
Closing issue. If @inian experiences the same issue he will reach out again.

**Comment by waaronking** [comment] 2021-02-07 08:01
@tmancey This is still happening in Brave v1.19.92 (Feb 5, 2021). There's another thread on reddit with a handful of people reporting the same thing. I use multiple profiles and the reward settings work on one and not the other. I've also never restored a profile.

**Comment by tmancey** [comment] 2021-02-10 11:45
@waaronking Thank you, I will reopen the ticket to retest with multiple profiles. Thanks

**Comment by StanBoyet** [comment] 2021-03-01 08:03
@tmancey I do experience the same issue, using multiple profiles indeed.

**Comment by tmancey** [comment] 2021-03-02 18:15
Closing as duplicate of https://github.com/brave/brave-browser/issues/13209

**Comment by tmancey** [comment] 2021-05-14 11:57
@waaronking @StanBoyet Could you please let me know if this is still happening for you in 1.24.x or above. Thanks

**Closed** 2021-05-14 12:14 UTC
Labels: OS/Desktop, closed/works-for-me, feature/ads, feature/rewards

**Comment by waaronking** [comment] 2021-05-21 21:21
@tmancey Apologies for the delay. This is still a problem for me in Brave v1.24.82 (May 20, 2021). I've attached a screenshot with the error stack trace. One profiles loads the Brave rewards page fine. The other fails.

<img width="1440" alt="Screen Shot 2021-05-21 at 3 17 45 PM" src="https://user-images.githubusercontent.com/1868863/119199426-413f2100-ba48-11eb-842e-92cf4292ffc9.png">

**Comment by zenparsing** [comment] 2021-05-24 14:58
@waaronking In the dev console for the page that shows the above error, if you execute `localStorage.clear()` and refresh the page, do you still get the error?

**Comment by waaronking** [comment] 2021-05-25 21:41
@zenparsing great news! Clearing the local storage fixed the problem on my end. Thanks for your help!
