### ISSUE TITLE
Brave in Ubuntu 18.04 does not import passwords from Firefox.

### ISSUE THREAD

**Issue by hainjedaf** [brave/brave-browser#4302] opened 2019-05-04 23:55 UTC
## Description 
OS: Ubuntu 18.04
Firefox 66.0.3 (64-bit)
Brave version 0.63.48 Chromium: 74.0.3729.108 (64-bits)

Upon brave first start, walked through import feature. 
Selected to import everything from firefox.
Tried to open anything on brave but no passwords present.
Look in Brave settings: no passwords present

## Steps to Reproduce

   0. open firefox
   1. Clean firefox (delete everything except passwords since first use)
   2. close firefox
   3. open brave
   4. follow brave instructions to import data from firefox
   5. see that all bookmarks are present
   6. try to log on to something of which I know my password is stored in firefox (e.g. google)
    ---> no data for user or password present.
   7. check brave settings for stored passwords: none present
   8. reset brave to original settings and delete brave user.
   9. close brave
   10. start over at step 0.

## Actual result:
Everything except sites/usernames/passwords imported

## Expected result:
Everything imported, including sites/usernames/passwords

## Reproduces how often: 
Always

## Brave version (brave://version info)
Versie 0.63.48 Chromium: 74.0.3729.108 (Officiële build) (64-bits)

## Version/Channel Information:
Version included in Ubuntu repositories

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
no
- Does the issue resolve itself when disabling Brave Rewards?
no
- Is the issue reproducible on the latest version of Chrome?
no

**Comment by rebron** [comment] 2019-05-10 15:56
cc: @kjozwiak

**Comment by LaurenWags** [comment] 2019-05-14 18:37
duplicate of https://github.com/brave/brave-browser/issues/2198 ?

**Comment by kjozwiak** [comment] 2019-05-14 18:42
@LaurenWags yup, looks like this a duplicate. Going to close this off in favour of #2198.

**Closed by kjozwiak** 2019-05-14 18:42 UTC
Labels: OS/Linux, feature/importer
