### ISSUE TITLE
The reddit website is unaccessable via Brave Browser, loading the page causes a weird loading loop

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#32093] opened 2023-08-05 18:49 UTC
## Description 
The website https://reddit.com/ is unaccessable due every attempt to visit it, causes a loading looü

## Steps to Reproduce

   1.  Type reddit.com in the adress bar
   2. hit enter
   3. see the result

## Actual result:
See attachment

## Expected result:
That the side loads normally

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.56.20 Chromium: 115.0.5790.171 (Offizieller Build) (32-Bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes.
- Can you reproduce this issue with the beta channel? 
Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No.
- Does the issue resolve itself when disabling Brave Rewards? 
No.
- Is the issue reproducible on the latest version of Chrome? 
Not tested.

https://github.com/brave/brave-browser/assets/137927933/ab28a730-96c5-4399-b279-76203ca275c9

## Miscellaneous Information:
-

**Comment by CT-66** [comment] 2023-08-25 17:50
Same for me

**Comment by claytondecker** [comment] 2023-09-02 18:17
I'm experiencing the same issue, and have been since mid August. It seems to occur on Windows and Android. Disabling Shields doesn't resolve it, and the issue occurs in private windows as well. It appears that the browser hangs when it hits a redirect loop. I haven't had this issue with any site other than Reddit.

**Comment by arthuredelstein** [comment] 2024-02-02 18:22
I tested on macOS and Windows, and the site seems to be working. @ghost @clayondecker are you still seeing this issue?

**Comment by claytondecker** [comment] 2024-02-02 18:36
@arthuredelstein I was able to isolate it to a custom filter list that strips tracking parameters. Since then that list has been updated and doesn't conflict. However I'm not sure how it was causing the issue even with shields disabled. Initially, query stripping seams like a strange cause because it was occurring on direct links without any URL queries

**Comment by ryanbr** [comment] 2024-02-13 22:21
Probably caused by the `rdt` param removal.  Affected Chromium browsers not just Brave. We can safely close this, we have had no recent issues with reddit.

Fix in uBO: https://github.com/uBlockOrigin/uAssets/commit/05d5cad43e0

Fixed for us: https://github.com/brave/adblock-lists/commit/0f4c618a006823276f10bbfe490bcf957d86937b 



User reports:
```
https://github.com/uBlockOrigin/uAssets/issues/18938#issuecomment-1693238481
https://community.brave.com/t/unable-to-open-reddit-com-urls-in-private-tabs/503125/4

```

**Closed by ryanbr** 2024-02-13 22:21 UTC
Labels: OS/Windows, webcompat, OS/Android, OS/Desktop, privacy/query-filter
