### ISSUE TITLE
s/migragion/migration typo in IPFS log message

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16559] opened 2021-06-22 19:50 UTC
## Description 

s/migragion/migration typo in IPFS log message

## Steps to Reproduce

   1. launch Brave with `--use-dev-goupdater-url`
   2. load `ipns://brantly.eth`
   3. click on `Use a local node`
   4. wait
   5. look in the console-log output

## Actual result:

`Could not add migragion to IPFS: nothing downloaded by ipfs fetcher`

<img width="682" alt="Screen Shot 2021-06-22 at 12 45 12 PM" src="https://user-images.githubusercontent.com/387249/122989575-d25f2b80-d357-11eb-8645-40c191b5de64.png">

## Expected result:
Should be spelled `migration`

## Reproduces how often: 

Unsure how to reliably produce the above (error) condition

## Brave version (brave://version info)

Brave | 1.27.76 Chromium: 91.0.4472.114 (Official Build) dev (x86_64)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS Version 11.4 (Build 20F71)

**Comment by spylogsster** [comment] 2021-06-23 17:07
duplicate of https://github.com/brave/brave-browser/issues/16128, 0.9.0 is not released

**Closed by spylogsster** 2021-06-23 17:07 UTC
Labels: OS/Desktop, feature/ipfs

**Comment by stephendonner** [comment] 2021-06-25 15:14
Epic; filed a dupe of my own issue, so sorry!
