### ISSUE TITLE
Links that open new tabs sometime don’t load

### ISSUE THREAD

**Issue by boogybren** [brave/brave-browser#36544] opened 2024-03-04 23:28 UTC
## Steps to Reproduce 
  1. Click on any link that will open a new tab in Brave. One from Mail or Messages app are easy to reproduce. 
  2. Observe that the new tab opened and the URL is on the address bar, but the page never loads. 
  3. Tap the address bar and tap Go to load the page.  

## Brave Version: 1.62 (24.2.9.10)

- Can you reproduce this issue with the most recent build from TestFlight? I don’t have access to TestFlight
- Can you reproduce this issue with the previous version of the current build from TestFlight? I don’t have access to TestFlight
- Can you reproduce this issue with the current build from AppStore? Yes

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Mobile Safari? No

**Comment by boogybren** [comment] 2024-03-05 00:38
This is the result after tapping a link from an email. 

![IMG_0266](https://github.com/brave/brave-browser/assets/1570269/4c2c186e-8e83-4c7f-9e68-60c4ae0ada17)

**Comment by boogybren** [comment] 2024-03-05 00:41
Uploading RPReplay_Final1709599254.mp4…

**Comment by iccub** [comment] 2024-03-06 18:24
dupe of https://github.com/brave/brave-browser/issues/36026

**Closed by iccub** 2024-03-06 18:24 UTC
Labels: closed/duplicate, OS/iOS
