### ISSUE TITLE
`show_picker_on_startup` not correctly saving to state in multi-profile configuration

### ISSUE THREAD

**Issue by ChrisUMB** [brave/brave-browser#41286] opened 2024-09-28 23:09 UTC
### Description

I have multiple profiles configured, A and B. When I launch Brave, it prompts me to choose a profile. I deselect "show on startup" in the bottom right, and select my profile. Then, I close Brave, launch it again, and it prompts me regardless, with "show on startup" reselected.

### Steps to reproduce

1. Create more than one profile
2. Launch Brave
3. Deselect "show on startup" in profile prompt
4. Close Brave
5. Launch Brave, you should be prompted to choose a profile anyway

### Actual result

Prompted to choose a profile.

### Expected result

Should not be prompted to choose a profile and should be opened directly to the home page.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.70.119 Chromium: 129.0.6668.70 (Official Build) (64-bit)
Revision | a15c836a4df987f118ece1645f54b081019049de
OS | Windows 11 Version 23H2 (Build 22631.4169)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

I was able to mitigate the issue by opening `User Data/Local State` and setting the `show_picker_on_startup` to `false` manually. Now when I open Brave, it doesn't prompt me for a user profile selection. I imagine something is just not saving the deselection of the checkbox properly.

**Comment by Brave-Matt** [comment] 2024-10-03 21:08
Seeing some other users encounter this issue is well —  these users are on Linux systems:
https://community.brave.com/t/checkbox-for-show-on-startup-on-the-whos-using-brave-start-screen-not-working-launches-when-unchecked/571427

cc @rebron

**Comment by rebron** [comment] 2024-10-04 18:41
Closing as dupe of https://github.com/brave/brave-browser/issues/41194 and fix should be coming in the next release.

See: https://github.com/brave/brave-browser/issues/41194#issuecomment-2394104775

**Closed by rebron** 2024-10-04 18:41 UTC
Labels: OS/Desktop

**Comment by DylanManiatakes** [comment] 2024-10-07 21:56
Still an issue on MacOS update did not fix it
