### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by xHalo13x** [brave/brave-browser#41837] opened 2024-10-23 17:39 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.71.114 Chromium: 130.0.6723.58
Operating System: Windows NT 10.0.19045

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.  I was just browsing websites, thats all.
2.  Mainly Youtube.com
3.  It could be any website from what I see.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/b8730100-9344-cf0c-0000-000000000000

**Comment by iefremov** [comment] 2024-10-24 21:04
dupe of https://github.com/brave/brave-browser/issues/36333

**Closed** 2024-10-24 21:04 UTC
Labels: crash, priority/P2

**Comment by iefremov** [comment] 2024-10-24 21:15
@xHalo13x have you been using Brave Leo AI ?

**Comment by xHalo13x** [comment] 2024-10-25 00:10
> [@xHalo13x](https://github.com/xHalo13x) have you been using Brave Leo AI ?

Not at all.
