### ISSUE TITLE
[Android] Feature request: "Check again" button in reward pop-up

### ISSUE THREAD

**Issue by Occhioverde** [brave/brave-browser#11241] opened 2020-08-14 19:28 UTC
I have noticed that, very often, websites that I know for sure are verified (mine or DuckDuckGo, for example) do not appear as such within the pop-up of donations.

Obviously, when I know that a website is certainly verified I proceed quietly to make the donation, but if I don't know its actual status I remain in doubt whether to confirm the transaction or whether to save my BATs to send them to other creators.

So I would like to ask: would it be possible to implement on Android the "Check again" button already present on the desktop versions?

![Donations pop-up on DuckDuckGo](https://user-images.githubusercontent.com/18429412/90285559-747ad100-de74-11ea-9c3a-adc5ee48a6fb.jpg)
_Donations pop-up on DuckDuckGo. As you can see the site seems to be unverified despite receiving BAT donations for some time._

**Comment by srirambv** [comment] 2020-08-17 04:02
Dupe of #10005

**Closed by srirambv** 2020-08-17 04:02 UTC
