### ISSUE TITLE
Can't play videos in LinkedIn with shields up

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1184] opened 2018-09-18 21:42 UTC
Carried over from https://github.com/brave/browser-laptop/issues/14663
> ### Steps to Reproduce
> 1. Login to LinkedIn
> 2. Click on play videos

**Comment by GeetaSarvadnya** [comment] 2018-10-10 11:52
1+ https://community.brave.com/t/embedded-videos-on-linkedin-feed-dont-work/34554

**Comment by mrzealot** [comment] 2019-01-23 14:39
Works fine for me in 0.58.21 (it is also tagged as a legacy Muon issue), so I think this can be closed.

**Comment by bbondy** [comment] 2019-01-23 19:47
Can't reproduce either. Closing.

**Closed by bbondy** 2019-01-23 19:47 UTC
Labels: feature/shields/webcompat, priority/P5, workaround/shields-down
