### ISSUE TITLE
[Desktop] All thumbnail icons are pixelated

### ISSUE THREAD

**Issue by XavierCLL** [brave/brave-browser#11541] opened 2020-09-01 18:31 UTC
## Description 

Using a HiDPI or not all thumbnail icons of websites are pixelated in "top sites" and in the "bookmarks bar":

![Screenshot_20200901_112436](https://user-images.githubusercontent.com/11801453/91891477-f117f880-ec45-11ea-8a20-942ec01a0423.png)

![Screenshot_20200901_112530](https://user-images.githubusercontent.com/11801453/91891482-f412e900-ec45-11ea-910f-475d8125dd66.png)

## Version info

Brave 1.13.82
Archlinux
Tested in two different resolutions (computers): 2560x1440 (DPI:166) and 1920x1080 (DPI:96)

**Comment by bsclifton** [comment] 2020-09-04 07:52
Duplicate of https://github.com/brave/brave-browser/issues/480

**Closed by bsclifton** 2020-09-04 07:52 UTC
Labels: OS/Desktop, OS/Linux/arch
