### ISSUE TITLE
Brave doesn't find Flash installation on the OS

### ISSUE THREAD

**Issue by r3pek** [brave/brave-browser#8336] opened 2020-02-20 20:31 UTC
## Description 

I'm using Fedora 31 as OS and installed brave-browser from the provided repository.
I've also installed flash from the adobe repos.
Brave isn't able to detect (and use), the flash instalation.

## Steps to Reproduce

   1. Install brave browser
   2. Install flash plugin
   3. Visit https://helpx.adobe.com/flash-player.html and find that flash isn't detected

## Actual result:

Flash player isn't detected

## Expected result:
Should detect installed flash plugin

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Brave | 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit)
-- | --
Revision | dc00a510e4c2ae25c4d084cc3d946fc782249224-refs/branch-heads/3987@{#917}
OS | Linux
JavaScript | V8 8.0.426.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,WebXR,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --load-media-router-component-extension=1 --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/r3pek/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Didn't try
- Can you reproduce this issue with the dev channel?
Didn't try
- Can you reproduce this issue with the nightly channel?
Didn't try

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
Chrome uses its internal plugin

## Miscellaneous Information:

Adobe Flash isn't shown in brave://components

Oficial flash plugin is installed in:
/usr/lib/adobe-flashplugin/
/usr/lib64/flash-plugin/

**Comment by bsclifton** [comment] 2020-03-11 20:29
Thanks for the report, @r3pek! I believe this issue is a duplicate of https://github.com/brave/brave-browser/issues/1562

Can you please check that issue out- there's a work-around shared there. I'll close this issue as a duplicate- but if your issue is not the same, we can re-open this one if you're able to provide more info. Thanks!

**Closed by bsclifton** 2020-03-11 20:29 UTC
Labels: plugin/flash
