### ISSUE TITLE
Invalid or corrupted PDF file.

### ISSUE THREAD

**Issue by avndp** [brave/brave-browser#2135] opened 2018-11-14 11:36 UTC
## Description 
For embedded PDFs, browser is saying "Invalid or corrupted PDF file.  More Information"

## Steps to Reproduce
I've been using our office website (which is restricted only to few IPs), hence I can share only the screenshots. 

Screenshot link: https://i.imgur.com/5fkMXR1.png

## Actual result:
https://i.imgur.com/5fkMXR1.png

## Expected result:
It should show the PDF file there.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Brave	0.57.6 Chromium: 71.0.3578.31 (Official Build) beta (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? - YES. I'm using the Brave beta build.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? - NO, even though the shield is off, it's still showing the same error.
- Is the issue reproducible on the latest version of Chrome? - NO, Chrome is showing the file properly.

### Additional Information
Earlier it has not showed any PDF file, but now it's showing in some websites. Whereas, in few cases it is still showing the same error as said above.

**Comment by srirambv** [comment] 2018-11-14 12:34
Dupe of #1033

**Closed by srirambv** 2018-11-14 12:34 UTC
