### ISSUE TITLE
[Desktop] -  contributed amount has gone over the wallet balance

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10442] opened 2020-06-24 16:34 UTC
## Description 

The contributed amount has gone over the wallet balance
## Steps to Reproduce

   1. Clean profile 
   2. Launch brave using `brave.exe --enable-logging --vmodule="*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/bat-native-ledger/*"=6 --rewards=staging=true,reconcile-interval=3,short-retries=true`
   3. Enable rewards
   4. Claim UGP grants of 30 BAT
   5. Add DDG and https://www.3zsistemi.si/ to AC table
   6. Setup recurring tips of 1 BAT to DDG and https://www.3zsistemi.si/
   7. Send a one-time tips of 1 BAT to DDG and https://www.3zsistemi.si/
   8. Wait for 1st AC to happen
   9. After AC, 20 BAT is contributed for Auto contribution and 2 BAT is contributed of recurring tips and 2 BAT is sent for one-time tips
  10. Wallet balance is `7 BAT` instead of `6 BAT`
  11. Open DB and check `unblinded_tokens` table, recurring tip for DDG is not being contributed as redeem_id is not present in unblinded_tokens table
  12. Add https://www.3zsistemi.si/ table and trigger 2nd AC
  13. After AC , the wallet balance becomes 0.0 BAT as expected. But the total contributed amount displayed in summary is `32 BAT ` - Not sure why 2 BAT extra got contributed when wallet balance is only 30 BAT. 
 
   
   
Note: Please let me know if you need DB file or profile for further investigation I can share the profile in DM

## Actual result:

 The contributed amount has gone over the wallet balance
![image (3)](https://user-images.githubusercontent.com/38657976/85594255-632bfa00-b665-11ea-9aad-462916a868c4.png)

## Expected result:

 the contributed amount shouldn't go over the wallet balance
## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.11.75 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Windows 10 OS Version 1903 (Build 18362.900)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not in 1.10.x
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by NejcZdovc** [comment] 2020-06-24 16:46
@GeetaSarvadnya is this one specific to 1.11 or can you reproduce it on 1.10 as well?

**Comment by GeetaSarvadnya** [comment] 2020-06-24 16:47
@NejcZdovc Yup, it's happening only in 1.11.x. Not in 1.10.x

**Comment by LaurenWags** [comment] 2020-06-24 17:33
@NejcZdovc I looked at @GeetaSarvadnya DB and her recurring tips for ddg (1 BAT each, 2 BAT total) were not in the `unblinded_tokens` table of her DB, but they were listed in `contribution_info`. I'll try to reproduce this also.

**Comment by LaurenWags** [comment] 2020-06-24 20:27
Not able to reproduce on macOS using

```
Brave | 1.11.75 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Step 10: wallet summary displays as expected:
<img width="422" alt="Screen Shot 2020-06-24 at 4 18 22 PM" src="https://user-images.githubusercontent.com/28145373/85624082-58f30700-b637-11ea-8200-7164349f647b.png">

Step 11 here's my `contribution_info` and `unblinded_tokens` tables:
<img width="857" alt="Screen Shot 2020-06-24 at 4 16 53 PM" src="https://user-images.githubusercontent.com/28145373/85624117-65775f80-b637-11ea-97a7-750b93a4182a.png">
<img width="1202" alt="Screen Shot 2020-06-24 at 4 19 03 PM" src="https://user-images.githubusercontent.com/28145373/85624122-67412300-b637-11ea-909f-5bec8a967edc.png">

Step 13: wallet summary displays as expected (note, 24 BAT for AC not 26 like @GeetaSarvadnya )
<img width="408" alt="Screen Shot 2020-06-24 at 4 23 12 PM" src="https://user-images.githubusercontent.com/28145373/85624174-7de77a00-b637-11ea-8aa7-13b740716b16.png">

Here are my `contribution_info` and `unblinded_tokens` tables after second contribution:
<img width="829" alt="Screen Shot 2020-06-24 at 4 23 55 PM" src="https://user-images.githubusercontent.com/28145373/85624214-8b046900-b637-11ea-8356-b8d641cac4b5.png">
<img width="1192" alt="Screen Shot 2020-06-24 at 4 24 21 PM" src="https://user-images.githubusercontent.com/28145373/85624215-8c359600-b637-11ea-8fb1-231fe0eef794.png">

**Comment by NejcZdovc** [comment] 2020-06-25 09:40
@GeetaSarvadnya so this is 100% reproducible for you?

**Comment by GeetaSarvadnya** [comment] 2020-06-25 10:55
@NejcZdovc Yes, I tried 2times both times issue was reproduced.

**Comment by zenparsing** [comment] 2020-07-14 02:42
So far I've not been able to reproduce on master (macOS).

**Comment by LaurenWags** [comment] 2020-07-14 12:58
@GeetaSarvadnya could you try on latest Nightly and see if this still reproduces for you?

**Comment by kjozwiak** [comment] 2020-07-16 03:33
Moving this out as it's too late for `1.11.x` as we're slated to release tomorrow. We'll need to get either @NejcZdovc or @zenparsing to reproduce this or it will be difficult to fix.

**Comment by NejcZdovc** [comment] 2020-07-24 06:11
@GeetaSarvadnya is this still a problem on 1.12/1.13?

**Comment by GeetaSarvadnya** [comment] 2020-07-27 08:43
The issue is not reproducible in 1.12.x 

1st AC:
![image](https://user-images.githubusercontent.com/38657976/88521892-3a57a580-d013-11ea-9c5c-f734cae7ed6e.png)

2nd AC:
![image](https://user-images.githubusercontent.com/38657976/88521855-2ca22000-d013-11ea-9e16-8afb1dffca5d.png)

**Closed** 2020-07-27 08:54 UTC
Labels: OS/Desktop, QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards
