### ISSUE TITLE
Switch to the last opened tabs like firefox

### ISSUE THREAD

**Issue by jannomeister** [brave/brave-browser#11787] opened 2020-09-21 12:53 UTC
First of all, thank you so much for this wonderful browser. But I just to ask a question, how can I configure brave to allow switch tab switch to the last opened tab like firefox?

**Comment by rebron** [comment] 2020-09-22 16:17
Hi @jannomeister There isn't a setting right now for this. I'm going to mark this a duplicate of #913. Work has been in progress for that one.

**Closed by rebron** 2020-09-22 16:17 UTC
Labels: OS/Desktop
