### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by fsclavo** [brave/brave-browser#29044] opened 2023-03-13 21:52 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.49.120  Chromium: 111.0.5563.64
Operating System: Linux 5.15.0-67-generic

URL (if applicable) where crash occurred:

Can you reproduce this crash? No, I can't

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. I was typing on the search box on "https://console.cloud.google.com/getting-started?hl=es&pli=1" 
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/397e0600-c5e7-be09-0000-000000000000

**Comment by rebron** [comment] 2023-03-16 19:52
Closing as dupe of https://github.com/brave/brave-browser/issues/29083

**Closed by rebron** 2023-03-16 19:52 UTC
