### ISSUE TITLE
Widgets from New Tab Page cannot be removed

### ISSUE THREAD

**Issue by m77e4t** [brave/brave-browser#20290] opened 2022-01-02 14:03 UTC
## Description  
Top sites visited and privacy stats widget are still viewable and cannot be removed/stopped. They are not the ones seen on a normal New Tab Page by default. From New Settings/Newtabpage/, I turned off sponsored images and background images and cancelled all 3 widgets from Widget stack for full back screen experience. 

But on the newly configured new tab page were these two widgets which would not budge off no matter what. If I visit a new site like github(dot)com or brave(dot)com, these two sites will appear in top site widget. It is possible to remove them sites temporarily. If I revisit the same site or some random site, they fill up the slots one by one.

At least I can remove a top site temporarily but, privacy stats neither can be stopped nor removed from New Tab Page. 

## Steps to reproduce 

   1. Disable Sponsored images and background images from new tab page settings
   2. Disable all widgets from widget stack section
   3. 

## Actual result  
![photo6237638733092466568](https://user-images.githubusercontent.com/96620334/147878084-42717507-a09d-4211-96c3-4de2bfc802a1.jpg)
![photo6237638733092466569](https://user-images.githubusercontent.com/96620334/147878086-b73fa04c-c3f9-47e4-a6a4-7385e9235a9a.jpg)
![photo6237638733092466570](https://user-images.githubusercontent.com/96620334/147878087-f7a1d497-819e-4381-8a9e-de8ade2531e8.jpg)

## Expected result
Privacy Stats and Top Site widgets will appear

## Issue reproduces how often 
Easily Reproducable

## Version/Channel Information:

 Possibly all.

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):Phone
   - Android version:Android 11
   
## Brave version
Brave 1.33.106, Chromium 96.0.4664.110

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment] 2022-01-03 05:08
This is expected behaviour. Don't think we will be changing it to be completely blank when widgets and bg images are disabled. 

cc: @jamesmudgett @anthonypkeane

**Comment by m77e4t** [comment] 2022-01-03 07:44
![Screenshot from 2022-01-03 01-39-50](https://user-images.githubusercontent.com/96620334/147908302-076e47e6-27bb-4e4a-b4f9-ad20c5c205c7.png)

This on Desktop/PC. Here, all widgets and background images are turned off.

I have created another issue about a bug on android, could you take a look.

**Comment by deeppandya** [comment] 2022-01-05 16:47
CC @jamesmudgett @anthonypkeane for visibility.

**Comment by wknapik** [comment] 2022-03-02 16:57
> This is expected behaviour. Don't think we will be changing it to be completely blank when widgets and bg images are disabled.

How is this expected? The user disables all widgets, the UI allows them to do it and then the widgets are not disabled.

I find this quite annoying, because I keep having to remove sites added to NTP.

**Comment by m77e4t** [comment] 2022-03-19 05:24
I have found a temporary workaround. Turn ON clear data on exit. Then every time you exit the browser, the top sites added to the widget (which should not be there) are automatically removed. But the current 'Clear data on exit' is not on par with the desktop brave/chromium where you select what data exactly you want to clear. The android feature just clears everything (cookies, cache, history). But luckily, bookmarks and Tabs which are already opened are still available later on.

Just like you, it was quite frustrating/irritating for me when the sites used to accumulated, and then I had to manually delete remove them one by one. But via this workaround it solved the nonsense.

**Comment by asavageiv** [comment] 2022-05-01 10:48
How do you even get to the widget stack? I can't find it in settings?

**Comment by bsclifton** [comment] 2022-05-12 05:23
Closing as the widget stack has been removed

**Closed by bsclifton** 2022-05-12 05:23 UTC
Labels: feature/new-tab, priority/P3, OS/Android

**Comment by m77e4t** [comment] 2022-05-14 13:36
![photo6339075986494174815](https://user-images.githubusercontent.com/96620334/168427862-60df0cf4-40f0-498e-a9ef-c2dc506bd6ca.jpg)

The issue should be re-opened.

The privacy stats 'thing' still cannot be completely removed from blank NTP. I tried to remove it on Brave Beta android, and it still was irremovable. The only thing which changed were those annoying recently visited sites are not pestering me and are now completely gone.

It actually got worse, as earlier you were able to remove Privacy stat from settings on a non-blank NTP (meaning on default background images) but now you cannot even do that.

 https://old.reddit.com/r/brave_browser/comments/up0bcd/android_how_to_hide_privacy_stats_report_and_how/
 
![photo6339075986494174821](https://user-images.githubusercontent.com/96620334/168428072-2d7d5dba-cd6c-49f7-88e4-3b3f85444ca1.jpg)

**Comment by m77e4t** [comment] 2023-01-23 13:09
Now, it has been removed as the issue stated, as seen on brave beta android 1.48 (or 1.47). The NTP is completely blank in dark colour the way the issue said.

It will soon land on brave stable.

![photo_6229019356499654160_y](https://user-images.githubusercontent.com/96620334/214047306-a1154339-3993-4573-aadc-9123ed7ec25f.jpg)

![photo_6229019356499654159_y](https://user-images.githubusercontent.com/96620334/214047312-820810bb-57f2-4b06-add3-d100bfb13aef.jpg)
