### ISSUE TITLE
Changed key shortcut for `Cmd + arrow left` combination without ability to change [MacOS]

### ISSUE THREAD

**Issue by wojtishek** [brave/brave-browser#31881] opened 2023-07-26 08:00 UTC
## Description 
For a long time I was using combinations `Cmd + arrow left` and `Cmd + arrow right` to navigate Back and Forward in my tab history. From new update `Cmd + arrow left` is set to Zoom in function without possibility to change. Also `Cmd + arrow right` is still working as Forward in history.

## Steps to Reproduce
   1. Open some page
   2. Click on some link
   3. Push `Cmd + arrow left`

## Brave version (brave://version info)
```
Brave | 1.56.11 Chromium: 115.0.5790.102 (arm64)
Version | 90efd4b0ad6aa15eeafcdabd5817ae939f7ba059-refs/branch-heads/5790_90@{#9}
OS | macOS 13.5 (22G74)
```

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes

## Other Additional Information: 
- Is the issue reproducible on the latest version of Chrome? No

**Comment by wojtishek** [comment] 2023-07-28 13:07
Same behavior when is address bar focused - `Cmd + arrow left` don't jump cursor to the beginning of url, instead it zooms in the content in browser.

**Comment by wojtishek** [comment] 2023-07-28 13:12
textarea in Brave
![2023-07-28 15 10 44](https://github.com/brave/brave-browser/assets/9982805/09fcd2fb-84ed-45a1-84cf-f7adc701e646)

address bar
![2023-07-28 15 09 05](https://github.com/brave/brave-browser/assets/9982805/f6b27b62-4484-4337-88bf-84c7ec95b813)

**Comment by rebron** [comment] 2023-07-29 06:46
Closing as dupe of https://github.com/brave/brave-browser/issues/31871 We have a fix in progress in that issue @wojtishek

**Closed by rebron** 2023-07-29 06:46 UTC
Labels: needs-investigation, OS/macOS, feature/keyboard-shortcuts, OS/Desktop

**Comment by sachasmart** [comment] 2023-12-03 00:25
This is hella annoying! Why would Brave every think of doing this. I thought for some reason Apple had pushed an update.

I'm running into this now and its a headache. Firing up firefox shortly

> textarea in Brave ![2023-07-28 15 10 44](https://private-user-images.githubusercontent.com/9982805/256830325-09fcd2fb-84ed-45a1-84cf-f7adc701e646.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NjMzMjAsIm5iZiI6MTcwMTU2MzAyMCwicGF0aCI6Ii85OTgyODA1LzI1NjgzMDMyNS0wOWZjZDJmYi04NGVkLTQ1YTEtODRjZi1mN2FkYzcwMWU2NDYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDNUMDAyMzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VlYzc3NGU5ODc0MTJiY2RkMmNkOWY4YWY5MWJiNjBlMmE4Nzk2ZGIzNjZhNWU1MTU4YzIzOTBhOTMxNmIwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XlxWMG6FGJ6GUnNWXxtkKaM4lJ58QVcezqI6G2GwAMg) [ ![2023-07-28 15 10 44](https://private-user-images.githubusercontent.com/9982805/256830325-09fcd2fb-84ed-45a1-84cf-f7adc701e646.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NjMzMjAsIm5iZiI6MTcwMTU2MzAyMCwicGF0aCI6Ii85OTgyODA1LzI1NjgzMDMyNS0wOWZjZDJmYi04NGVkLTQ1YTEtODRjZi1mN2FkYzcwMWU2NDYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDNUMDAyMzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VlYzc3NGU5ODc0MTJiY2RkMmNkOWY4YWY5MWJiNjBlMmE4Nzk2ZGIzNjZhNWU1MTU4YzIzOTBhOTMxNmIwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XlxWMG6FGJ6GUnNWXxtkKaM4lJ58QVcezqI6G2GwAMg) ](https://private-user-images.githubusercontent.com/9982805/256830325-09fcd2fb-84ed-45a1-84cf-f7adc701e646.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NjMzMjAsIm5iZiI6MTcwMTU2MzAyMCwicGF0aCI6Ii85OTgyODA1LzI1NjgzMDMyNS0wOWZjZDJmYi04NGVkLTQ1YTEtODRjZi1mN2FkYzcwMWU2NDYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDNUMDAyMzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VlYzc3NGU5ODc0MTJiY2RkMmNkOWY4YWY5MWJiNjBlMmE4Nzk2ZGIzNjZhNWU1MTU4YzIzOTBhOTMxNmIwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XlxWMG6FGJ6GUnNWXxtkKaM4lJ58QVcezqI6G2GwAMg) [ ](https://private-user-images.githubusercontent.com/9982805/256830325-09fcd2fb-84ed-45a1-84cf-f7adc701e646.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NjMzMjAsIm5iZiI6MTcwMTU2MzAyMCwicGF0aCI6Ii85OTgyODA1LzI1NjgzMDMyNS0wOWZjZDJmYi04NGVkLTQ1YTEtODRjZi1mN2FkYzcwMWU2NDYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDNUMDAyMzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VlYzc3NGU5ODc0MTJiY2RkMmNkOWY4YWY5MWJiNjBlMmE4Nzk2ZGIzNjZhNWU1MTU4YzIzOTBhOTMxNmIwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XlxWMG6FGJ6GUnNWXxtkKaM4lJ58QVcezqI6G2GwAMg)
> 
> address bar ![2023-07-28 15 09 05](https://private-user-images.githubusercontent.com/9982805/256830401-f6b27b62-4484-4337-88bf-84c7ec95b813.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NjMzMjAsIm5iZiI6MTcwMTU2MzAyMCwicGF0aCI6Ii85OTgyODA1LzI1NjgzMDQwMS1mNmIyN2I2Mi00NDg0LTQzMzctODhiZi04NGM3ZWM5NWI4MTMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDNUMDAyMzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTBlOTg4NzMyNmIzOWJmMzUxYTIzMGYzYjUzNDVkNmEwZGJhOGFkNzVmNDhhMzRjMjJhNjQxYzY3Zjc1MmViMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lzxxSFbKJRiHxruJmxYrJbpUvCE7hXZLXtKTQ8Qtsp8) [ ![2023-07-28 15 09 05](https://private-user-images.githubusercontent.com/9982805/256830401-f6b27b62-4484-4337-88bf-84c7ec95b813.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NjMzMjAsIm5iZiI6MTcwMTU2MzAyMCwicGF0aCI6Ii85OTgyODA1LzI1NjgzMDQwMS1mNmIyN2I2Mi00NDg0LTQzMzctODhiZi04NGM3ZWM5NWI4MTMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDNUMDAyMzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTBlOTg4NzMyNmIzOWJmMzUxYTIzMGYzYjUzNDVkNmEwZGJhOGFkNzVmNDhhMzRjMjJhNjQxYzY3Zjc1MmViMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lzxxSFbKJRiHxruJmxYrJbpUvCE7hXZLXtKTQ8Qtsp8) ](https://private-user-images.githubusercontent.com/9982805/256830401-f6b27b62-4484-4337-88bf-84c7ec95b813.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NjMzMjAsIm5iZiI6MTcwMTU2MzAyMCwicGF0aCI6Ii85OTgyODA1LzI1NjgzMDQwMS1mNmIyN2I2Mi00NDg0LTQzMzctODhiZi04NGM3ZWM5NWI4MTMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDNUMDAyMzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTBlOTg4NzMyNmIzOWJmMzUxYTIzMGYzYjUzNDVkNmEwZGJhOGFkNzVmNDhhMzRjMjJhNjQxYzY3Zjc1MmViMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lzxxSFbKJRiHxruJmxYrJbpUvCE7hXZLXtKTQ8Qtsp8) [ ](https://private-user-images.githubusercontent.com/9982805/256830401-f6b27b62-4484-4337-88bf-84c7ec95b813.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NjMzMjAsIm5iZiI6MTcwMTU2MzAyMCwicGF0aCI6Ii85OTgyODA1LzI1NjgzMDQwMS1mNmIyN2I2Mi00NDg0LTQzMzctODhiZi04NGM3ZWM5NWI4MTMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDNUMDAyMzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTBlOTg4NzMyNmIzOWJmMzUxYTIzMGYzYjUzNDVkNmEwZGJhOGFkNzVmNDhhMzRjMjJhNjQxYzY3Zjc1MmViMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lzxxSFbKJRiHxruJmxYrJbpUvCE7hXZLXtKTQ8Qtsp8)
