### ISSUE TITLE
Improve webcompat reporter

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#20095] opened 2021-12-14 23:09 UTC
Brave includes a "webcompat reporter" that users can use to report when a site isn't broken. The current version does not have enough information to be actionable in most cases, frustrating users (they took the time to report a problem, but we can't fix it) and leaving sites broken.

<img width="377" alt="Screen Shot 2021-12-14 at 5 05 42 PM" src="https://user-images.githubusercontent.com/76526/146093477-3404d1b4-d3dc-47b4-8a95-559d4f4a1c84.png">

This issue is to improve the WebCompat reporter, through the following steps:

- [ ] Have the WebCompat reporter send the full URL of the page being reported (currently only the protocol and origin is reported)
- [ ] Have the WebCompat reporter show the user the full URL to the user when confirming the user wants to send the report
- [ ] Include an optional "additional details" box on the form, so that the user can provide any extra context that would assist community / support with reproducing and resolving the issue on the webpage.
- [ ] Include an optional "contact me / follow up with me" box on the form, so that community / support can follow up with the reporter (if desired).
- [ ] Update the server side / data collector so that reports are automatically deleted every 3 weeks
- [ ] Add UI / UX in the stats page (where these reports are currently visible) so that the stats user can delete a report if needed (for example, if the report includes sensitive / identifying information)

**Comment by pes10k** [comment] 2021-12-14 23:11
(@ryanbr , do you think 3 weeks would be sufficient?

**Comment by ryanbr** [comment] 2021-12-14 23:38
Yeah 3 weeks fine, maybe to add an optional submission of Extensions in use also?

**Comment by porteron** [comment] 2021-12-17 18:39
Looks good, once you implement the new field to be sent we can go ahead and update the `go-vault` webcompat API to make sure we're in sync to capture. 

Sending the entire URL should be fine, although maybe we want to establish the max character length we'll accept.

**Comment by porteron** [comment] 2021-12-17 19:18
Tracking the needed implementation here on my end: https://github.com/brave-intl/go-vault/issues/81

**Comment by bradleyrichter** [comment] 2022-01-19 23:40
@antonok-edm This represents the changes in the UX mentioned above:

![image](https://user-images.githubusercontent.com/13509546/150235867-e867f01b-09dd-4396-b4d8-e70f81a0d174.png)

**Comment by DJAndries** [comment] 2022-01-28 19:51
Screenshots of implementation (ignore the "Contact details (optional)" placeholder, it is now "Email address (optional)")

![report dark](https://user-images.githubusercontent.com/5621455/151612219-fd1377e9-75c1-4df3-8ad9-82189709c6ad.png)
![report light](https://user-images.githubusercontent.com/5621455/151612255-7f3def30-e893-4d17-b2d8-e04a23a32806.png)

**Comment by bradleyrichter** [comment] 2022-01-28 20:59
@DJAndries @pes10k @antonok-edm I thought we decided to include mentions of twitter and other rather than just email?

![image](https://user-images.githubusercontent.com/13509546/151620651-c9eaa62d-83b5-4b91-b3d6-aa20e42682eb.png)

**Comment by pes10k** [comment] 2022-01-28 21:10
me too (from our slack chat @ryanbr and @antonok-edm ). Was there a reason to flip it back?

**Comment by DJAndries** [comment] 2022-01-28 21:19
Apologies, I had not seen this new mock up. Will update accordingly.

**Comment by pes10k** [comment] 2022-01-28 21:19
thanks thanks @DJAndries !

**Comment by DJAndries** [comment] 2022-01-29 00:04
New screenshot:
![Screenshot from 2022-01-28 15-55-50](https://user-images.githubusercontent.com/5621455/151637475-f2661d45-8bb0-4805-9418-2ac869c4a23a.png)

I removed the IP address collection bit from the disclaimer, since we do not collect the IP whatsoever.

**Comment by pes10k** [comment] 2022-01-29 18:19
Removing the IP line seems great. Strong +1 from me

**Comment by DJAndries** [comment] 2022-02-28 23:51
Client and server-side complete, closing

**Closed by DJAndries** 2022-02-28 23:51 UTC
Labels: privacy/feature, feature/shields/webcompat, OS/Android, privacy-pod, OS/Desktop

**Comment by LaurenWags** [comment] 2022-03-03 18:21
@brave/legacy_qa when checking this, please confirm with server-side team that data is being received as expected.

**Comment by GeetaSarvadnya** [comment] 2022-03-04 08:41
Verification is inprogress

```

Brave | 1.37.82 Chromium: 99.0.4844.51 (Official Build) beta (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1526)


```

**Comment by GeetaSarvadnya** [comment] 2022-03-04 09:21
@porteron We would need your help to test the server-side data receive part. Please let me know once you have some time today.

**Comment by stephendonner** [comment] 2022-03-04 16:19
@GeetaSarvadnya you have to use the VPN to reach `https://stats.brave.com`.

**Comment by porteron** [comment] 2022-03-04 18:06
@GeetaSarvadnya I can confirm data is coming in on the server-side for the new fields. Seeing records with the additionalDetails and contactInfo.

**Comment by stephendonner** [comment] 2022-03-17 03:46
@porteron are you also able to confirm my data submission for brave.com from earlier today?  🙏 Thanks!

**Comment by porteron** [comment] 2022-03-17 04:49
@stephendonner Confirmed.
```
77,611
winx64-bc
99.0.4844.51
https://github.com/
https://github.com/brave/brave-browser/issues/20095
[sdonner@brave.com](mailto:sdonner@brave.com)
Just a test for https://github.com/brave/brave-browser/issues/20095
March 17, 2022, 4:44 AM
```

**Comment by stephendonner** [comment] 2022-03-17 20:08
Verified `PASSED` using 


Brave | 1.37.96 Chromium: 99.0.4844.74 (Official Build) dev (x86_64)
-- | --
Revision | fee9a47e86e981802390cb0d41c5ed7ea93c4f6f-refs/branch-heads/4844@{#1060}
OS | macOS Version 11.6.3 (Build 20G415)

- Verified the description from the issue https://github.com/brave/brave-browser/issues/20095#issue-1080382731
- Logged a follow up issue https://github.com/brave/brave-browser/issues/21522

Client-side validation:

Light mode | Dark mode
-----|------
<img width="1090" alt="Screen Shot 2022-03-17 at 1 04 48 PM" src="https://user-images.githubusercontent.com/387249/158886550-7134571d-9465-4470-b5d6-c1dbd037c1ed.png"> | <img width="1668" alt="Screen Shot 2022-03-17 at 1 05 15 PM" src="https://user-images.githubusercontent.com/387249/158886578-0fc61c50-a201-4767-aded-3328cbb26ee5.png">



- Confirmed WebCompat reporter sends the full URL of the page being reported
- Confirmed Email, Twitter, etc. fields are shown in the WebCompat reporter contact me (optional) section as per the new mockup https://github.com/brave/brave-browser/issues/20095#issuecomment-1024631167
- Confirmed New UI is been added in stats page where the web compat report are listed
- Confirmed webcompat reports are listed in https://stats.brave.com:
```
osx-bc
99.0.4844.74
https://github.com/
https://github.com/brave/brave-browser/issues/20095
sdonner@brave.com
Just a test for https://github.com/brave/brave-browser/issues/20095
March 17, 2022, 6:43 PM
```

**Comment by btlechowski** [comment] 2022-03-22 00:07
Verification passed on

Brave | 1.37.100 Chromium: 99.0.4844.83 (Oficjalna wersja) beta (64-bitowa)
-- | --
Revision | b11086e62d7c1a44b0942ac5568d22a425c7ae35-refs/branch-heads/4844_74@{#5}
OS | Ubuntu 18.04 LTS

Verified test plan from the description 

Light mode:
![image](https://user-images.githubusercontent.com/34715963/159381499-f41e1efa-0840-4602-a5e8-1de228cf0166.png)

Dark mode:
![image](https://user-images.githubusercontent.com/34715963/159381547-84cb118c-12d7-483c-bb54-ac8100595adb.png)

Logged: https://github.com/brave/brave-browser/issues/21801

- Confirmed WebCompat reporter sends the full URL of the page being reported
- Confirmed Email, Twitter, etc. fields are shown in the WebCompat reporter contact me (optional) section as per the new mockup https://github.com/brave/brave-browser/issues/20095#issuecomment-1024631167
- Confirmed New UI is been added in stats page where the web compat report are listed
- Confirmed webcompat reports are listed in https://stats.brave.com: IN PROGRESS

**Comment by btlechowski** [comment] 2022-03-22 00:08
@porteron are you also able to confirm my data submission for brave.com from blechowki@brave.com? Thanks in advance :)

**Comment by porteron** [comment] 2022-03-22 01:36
@btlechowski Confirmed I see the entry.
```
March 21, 2022, 11:56 PM
linux-bc
https://github.com/
test
[blechowski@brave.com](mailto:blechowski@brave.com)

```

**Comment by bsclifton** [comment] 2022-03-24 06:30
Removed `OS/Android` label as this is only on Desktop 👍
