### ISSUE TITLE
Make brave available through Flatpak and Flathub

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1000] opened 2018-09-07 05:42 UTC
Carried over from https://github.com/brave/browser-laptop/issues/11999

## Description
Brave should be avaliable through [flatpak](http://flatpak.org/) because it is an alternative to snap that feels better because it is not run by a big company as cononical. Here is a great page with the advantages between the two: https://www.maketecheasier.com/snap-packages-vs-flatpacks/

## Current status
With [browser-laptop](https://github.com/brave/browser-laptop), some good progress was made by @Garbee. As the developer channel becomes mainstream, we'll want to evaluate packaging this version instead

**Comment by Garbee** [comment] 2018-09-07 18:04
OK so the new generic linux builds are available on the [releases page](https://github.com/brave/brave-browser/releases) for this repo. The site currently still links to the old laptop instructions and not the [new docs](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux) (which conveniently also is missing the generic instructions anyways.)

So what I did for my initial builds, which I will repeat again here with the initial containers, is simply pull the generic build into an image. Copy in the logo and setup a desktop file to run the program and allow it into the system for setting it as a default web browser. Overall pretty straightforward, but the more complex issue to figure out before releasing it is how to handle versioning.

I'm going to have a conversation on how to handle this with other Flathub maintainers. What I'd *like* to do is have `com.brave.Brave` be what we install now since all we have is dev builds. Then when stable comes, transition that to being stable-only builds. With a secondary `com.brave.BraveDev` for the development channel. But I know there are other methods like saying `com.brave.Brave//{version/branch}` if we only wanted one listing. I don't know the full set of trade-offs between these methods yet, but that is something I am investigating before this goes live.

**Comment by x80486** [comment] 2018-11-11 21:10
Hello! Has there been any progress with this one?

**Comment by Garbee** [comment] 2018-11-12 17:03
Not on my end. Initially trying to pull up to the new brave-core system I got a package built, but the application would never run enough to show a GUI. It crashed out without any trace of an error. Doing some debug traces didn't yield any significant results either other than a few dead ends.

I've since switched to Hackintoshing my systems, so working on making and maintaining a Flatpak isn't a high priority anymore personally.

**Comment by Jacalz** [comment] 2019-05-13 18:54
Is there any new on this? I would love to have Brave available through Flatpak as it would make it work on a lot of different Linux distros. It is especially useful since the Snap app doesn’t have great desktop integration and is slow, which to be fair is a limitation of Snap. Flatpak is also more widely available, fully open source and offers much better desktop integration. A great choice for a privacy minded browser 👍

**Comment by Razva** [comment] 2019-07-14 15:36
July 2019, still no Flatpak. Come on guys, be _Brave_ and do this for us! :)

**Comment by henk717** [comment] 2019-07-30 14:59
Brave availability is quite poor on Arch, Suse and other smaller distro's.
Flatpak support would be a great universal way of getting this browser on any distro.

**Comment by maniadevice** [comment] 2019-08-06 22:59
Flatpak has wider first-class support from a lot of distros. It would be great to have Brave on Flatpak and get Brave a wider audience, that it deserves. Please consider this.

**Comment by srirambv** [comment] 2019-08-08 12:45
cc: @rebron  @bsclifton  to add a priority to this

**Comment by bsclifton** [comment] 2019-08-12 20:28
At the moment, we don't have plans to *officially* support Flatpak/Flathub and other formats. However, if someone did want to work with us, we can definitely help you get started 😄

**Comment by akarshanbiswas** [comment] 2019-08-30 06:27
@bsclifton Hi. Unfortunately the chromium setuid sandbox is not compatible with bubblewrap(flatpak Sandbox). So we need to disable it at the root label without showing any warning. I think this is going nowhere.

**Comment by t-nelis** [comment] 2019-11-20 00:19
[This document](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_sandboxing.md) mentions:

> The [user] namespace sandbox aims to replace the setuid sandbox. It has the advantage of not requiring a setuid binary. It's based on (unprivileged) user namespaces in the Linux kernel. It generally requires a kernel >= 3.10, although it may work with 3.8 if certain patches are backported.
> 
> Starting with M-43, if the kernel supports it, unprivileged namespaces are used instead of the setuid sandbox. Starting with M-44, certain processes run in their own PID namespace, which isolates them better.

The summary also seems clear:

> Setuid sandbox [...] Enabled by default (old kernels) and maintained
> User namespaces sandbox [...] Enabled by default (modern kernels) and actively developed

Chromium 43 was released in 2015 and Linux 3.10 in 2013.

Now, AFAICT Flatpak would already isolate the full application in a single user namespace, even when `--no-sandbox` is passed to Chromium (this is independent from contained processes). Yet, Chromium sandboxing isolates some of its subsystems and tabs from each other, and as such requires nested user namespaces. (I haven't validated both these claims thoroughly but I'm somewhat confident it's accurate.) So, in other words: while using `--no-sandbox` would protect the host from Brave, internal Brave subcomponents wouldn't be protected from each other and this is why Chromium sandboxing is still desirable.

I've [confirmed](http://man7.org/linux/man-pages/man7/user_namespaces.7.html) nested user namespaces are fully supported by the kernel, and that since 3.8 unprivileged processes can create them. However, Flatpak and similar systems [block this](https://github.com/flatpak/flatpak/blob/1f35dda1b50cceb24c471b19ac886dc91bf8a0b4/common/flatpak-run.c#L2481-L2485) for security reasons (I haven't researched the details yet but given this is widespread and seemingly well discussed upstream it seems legitimate and not an oversight).

Flatpak offers a higher-level API to allow sandboxed applications to run sub-processes in nested sandboxes in a secure way; see [flatpak-spawn](https://flatpak.readthedocs.io/en/latest/flatpak-command-reference.html#flatpak-spawn). I gathered that a patch to Chromium was submitted which leveraged this, but it was rejected given how specific it is to Flatpak, though apparently the Chromium team expressed they'd reconsider if Flatpak were to become more dominant. Again: I haven't yet learned the details of how this API works and I haven't verified the claims, it seemed legitimate.

As a result, there is a [seemingly active collaboration](https://discourse.gnome.org/t/sandboxing-portal/1651) between the Flatpak team and the Snap team (the other major player) to agree on a common high-level API that could be used in a new patchset to be presented again to the Chromium team (and leveraged by all other application vendors who need "granular sub-sandboxing").

It seems there is still a bit of work to be done on the Snap side, and as always with these things potential deviations from flatpak-spawn in the common API semantics (as a result of these discussions) might generate some work on the Flatpak side as well, but all parties seem enthusiastic about making this happen.

I'd thus like to offer a more hopeful perspective: it seems this _is_ going somewhere.

FYI: This impacts many other projects obviously, it may be useful to track those as well just in case somebody gets creative. [Electron](https://github.com/flatpak/flatpak/issues/3044). [Riot](https://github.com/flathub/im.riot.Riot/issues/59). [Chrome](https://github.com/flathub/flathub/pull/566). [Skype](https://github.com/flathub/com.skype.Client/issues/70). [Signal](https://github.com/flathub/org.signal.Signal/issues/92). [Exodus](https://github.com/flathub/io.exodus.Exodus/pull/40). There is definitely some pressure to make this work for everybody (especially given this isn't specific to Flatpak). I haven't verified this, but it seems that if you see a project where "things work" (e.g. with a Flatpak package or a Snap package) it is probably because either they disabled "sub-sandboxing" or whitelisted the application to allow the relevant syscalls necessary for creating nested user namespaces, neither of which are apparently good options.

Some people argue the status quo (no "sub-sandboxing") is still very acceptable for them (this all depends on any individual's threat model after-all, remember the Chromium sandboxes in particular are second-level security measures to begin with and it _is_ isolated from the host), so there might be value in a Flatpak with `--no-sandbox` even before a proper solution is ready (as long as the security guarantees can be made clear enough that end-users can make an informed decision of whether to use it or keep waiting).

**Comment by HadetTheUndying** [comment] 2019-11-26 05:24
Just posting to show interest in this, as it would enable the browser to be run in distributions not using glibc.

**Comment by JaneSmith** [comment] 2019-12-05 16:37
Posting here to show my interest in it as well. Personally, I think this should be a much higher priority. Flatpak is the future of application packaging on Linux. It works on all distros, has sandboxing with a permissions system, along with many other benefits.

In my case, I am running Fedora Silverblue, which actually uses Flatpak as its native package manager. Flatpak is how applications are supposed to be installed on Fedora Silverblue. This means that I can't even really use Brave. Technically I can get it to work, but it requires some hacky workarounds (altering the base OS image via rpm-ostree), and I would rather not have to resort to that.

**Comment by Nonononoki** [comment] 2020-01-12 20:56
Posting here to show interest. Flatpak is getting more and more popular and it just works.

**Comment by JaneSmith** [comment] 2020-01-13 09:53
For what it's worth, getting Brave up on Flathub would also solve issue #6865. Flathub is the de facto repository for Flatpak applications, so any Flathub-enabled system would have Brave discoverable and installable via the GNOME Software GUI - as well as other Flatpak-aware tools like KDE Discover.

**Comment by peakgeek** [comment] 2020-01-18 18:00
+1 Commenting to highlight interest. 
I've been a regular Brave user since early 2017 and I continue to be amazed by this project. It's a bummer that you have to choose between using an Arch-based distro or being able to use Brave (other than the community snap). A Flatpak option would be killer.

**Comment by jwsp1** [comment] 2020-02-02 10:44
+1 from here. It would make brave easily available for 'average' linux users.

**Comment by Chocod2** [comment] 2020-02-22 21:51
Also posting to show interest. I would like to see Brave browser on Flathub.

**Comment by t-nelis** [comment] 2020-03-07 18:15
Riot [apparently](https://github.com/flathub/im.riot.Riot/pull/88) successfully used [zypack](https://github.com/refi64/zypak) for addressing the sandbox-related issue.

**Comment by Spacesurfer** [comment] 2020-03-25 15:39
Bi-weekly comment showing interest in Brave become available through a Flatpak install and integration within Flathub. 

Just an FYI, that pesky Gecko based browser is to have a stable build available through Flathub in April ;)

**Comment by msmoljan** [comment] 2020-03-28 21:15
Also interested in Brave on Flathub!

**Comment by fmarier** [comment] 2020-04-07 19:49
[Firefox 75 was just released](https://www.mozilla.org/en-US/firefox/75.0/releasenotes/) with support for Flatpack. There might be code/configuration we could borrow there.

**Comment by fmarier** [comment] 2020-04-07 19:50
> It's a bummer that you have to choose between using an Arch-based distro or being able to use Brave (other than the community snap).

Just wanted to point out that we've supported RPM/DEB based distros with officially-supported packages (including timely updates) for a while now: https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

**Comment by t-nelis** [comment] 2020-04-07 22:09
In addition to Riot using zypak to solve this issue (as [previously reported](https://github.com/brave/brave-browser/issues/1000#issuecomment-596122985)), the Exodus project [has just done the same](https://github.com/flathub/io.exodus.Exodus/pull/40).

**Comment by rajmondburgaj** [comment] 2020-04-15 19:09
Is there any plan soon to do this  ? Would great if the would have this option to install from flathub

**Comment by fmarier** [comment] 2020-04-15 19:14
Due to time constraints, this is not something we are planning to do in the short term. If someone would like to take this on and create an unofficial flatpack for Brave, that would be a good first step towards our integrating it into our build process.

**Comment by Bakan0** [comment] 2020-04-21 20:47
@fmarier 
I would like to take this on as my first flatpak contribution! Is there someone specifically I should talk to/work with?

JMV

**Comment by TheEvilSkeleton** [comment] 2020-04-24 23:07
@bsclifton As you can see, I have sent an issue to Flathub. Let's hope they will package it as Flatpak.

**Comment by eljuno** [comment] 2020-05-11 17:00
+1 from Community https://community.brave.com/t/flatpak-for-endless-os/125944?u=eljuno

**Comment by mwleeds** [comment] 2020-07-02 17:50
Relatedly, there's ongoing work to make a sandboxed Chrome Flatpak: https://github.com/flathub/flathub/pull/1630

**Comment by x80486** [comment] 2020-08-01 14:50
...and since the Flatpak for Chrome just made it to the Flathub's beta repo, it should be easier to do this one now :partying_face:

**Comment by KizunaH** [comment] 2020-08-12 03:14
https://github.com/brave/brave-browser/issues/11184

**Comment by analotia** [comment] 2020-09-24 09:32
I just made a flatpak for this based on the Chrome flatpak. I've made it public: https://github.com/analotia/com.brave.Brave 

It's working fine so far except for print support

**Comment by analotia** [comment] 2020-09-24 09:33
To install the flatpak: 
```
git clone https://github.com/analotia/com.brave.Brave --recurse-submodules
sudo flatpak-builder --install --install-deps-from=flathub _build com.brave.Brave.yaml --force-clean
flatpak run com.brave.Brave
```

**Comment by analotia** [comment] 2020-09-24 10:18
Update: the issue with printing seems to be caused by the zypak. So it's not really possible for me to fix.

**Comment by x80486** [comment] 2020-09-24 11:58
@analotia, if it's working already, why don't you go ahead and try to push it to Flathub's beta repo (where Chrome is at still) until it gets stable along with Chrome?

**Comment by analotia** [comment] 2020-09-24 12:54
@x80486, sorry but I don't know how to. I'll try to search on how I could do that. Hopefully it's easy to get started

**Comment by analotia** [comment] 2020-09-24 13:04
Done! Seemed easy to get started, all it takes is a pull request to https://github.com/flathub/flathub. I was somewhat worried i'll have to send emails and stuff 

We'll see how this goes... https://github.com/flathub/flathub/pull/1852

**Comment by analotia** [comment] 2020-09-24 13:10
Now you can just do:
`flatpak install --user https://dl.flathub.org/build-repo/27261/com.brave.Brave.flatpakref`

To try out the flatpak

**Comment by x80486** [comment] 2020-09-24 13:42
It would nice if someone from Brave (@fmarier or @bsclifton) helps @analotia with some questions and stuff specific to the browser — probably some recommendations. The pull request is on Flathub already.

**Comment by JayDoubleu** [comment] 2020-09-26 17:04
It's almost 2021. flatpak and snaps are here to stay.
Snaps are default in latest ubuntu LTS, flatpaks are common for fedora workstation and default in fedora silverblue.
I think it's time to simply acknowledge that they are here to stay and start building packages for it please :)

**Comment by analotia** [comment] 2020-09-26 18:20
@JayDoubleu 

you could try out the new flatpak now: `flatpak install https://dl.flathub.org/build-repo/27407/com.brave.Brave.flatpakref`

I think it's pretty ready and it's working fine now. We have benefited massively from the `com.google.Chrome` flatpak work.   

If you get a "Action Required" page please follow the instructions, otherwise you'll have a broken flatpak

**Comment by JayDoubleu** [comment] 2020-09-26 18:26
Is there a code on GitHub which provisions mentioned flatpak ?

**Comment by analotia** [comment] 2020-09-26 18:28
What do you mean? @JayDoubleu 

This is built by a bot run by the flathub people

**Comment by JayDoubleu** [comment] 2020-09-26 18:29
Isn't anyone allowed to just publish anything onto flathub ?

**Comment by analotia** [comment] 2020-09-26 18:31
> Isn't anyone allowed to just publish anything onto flathub ?

Not really. You need to get it approved by flathub. Anyone is allowed to send a pull request though

**Comment by analotia** [comment] 2020-09-26 18:33
Are you confusing flathub with flatpak? The two aren't the same. 

* flatpak is the package manager  
* flathub is the repo  


Unlike snaps, flatpak has repositories which could be run by anybody. Whereas on snaps, it's centralized to one hard coded repo

**Comment by elechner** [comment] 2020-10-06 06:07
Glad to see that a flatpak of Brave is finally in the works. Thanks for getting the ball running, @analotia . When do you think Brave will be available on flathub-beta and approved by Brave Software?

**Comment by analotia** [comment] 2020-10-06 07:30
@elechner It seems like it won't be approved by Brave for a while. However according to fmarier it is very likely this will start of as an "unofficial repo" but will eventually be maintained by brave officially.

**Comment by Dani3I** [comment] 2020-10-06 10:18
Hi, if I want to test Brave I should install it from the last command from "flathubbot" from this: https://github.com/flathub/flathub/pull/1852 or is there another preferred version?

**Comment by analotia** [comment] 2020-10-06 10:25
@Dani3I You should install from the last command from @flathubbot

**Comment by x80486** [comment] 2020-10-12 15:38
For the record, @analotia just got this one in. You can install Brave from Flathub "beta" (for now) using:

```shell
$ flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
$ flatpak install flathub-beta com.brave.Browser
```

> The same instructions apply for Google Chrome — in case you are interested :wink:

**Comment by andirsun** [comment] 2020-10-15 20:56
> For the record, @analotia just got this one in. You can install Brave from Flathub "beta" (for now) using:
> 
> ```shell
> $ flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
> $ flatpak install flathub-beta com.brave.Browser
> ```
> 
> > The same instructions apply for Google Chrome — in case you are interested wink

```
andirsun@andirsunpc:~/projects/tingo/backend/rest-api$ flatpak install flathub-beta com.brave.Browser
Looking for matches…
error: The application com.brave.Browser/x86_64/beta requires the runtime org.freedesktop.Platform/x86_64/20.08 which was not found

```

**Comment by x80486** [comment] 2020-10-15 21:01
That's weird. I can only think that it failed because it's using the `flathub-beta` repository and it cannot resolve the dependencies from `flathub`. You might want to file an issue in the `flatpak` repository about this.

In any case, just install `org.freedesktop.Platform/x86_64/20.08` from `flathub` first, and once you have that one, try the initial command again.

**Comment by tannercrook** [comment] 2020-10-22 16:04
I tried installing the flatpak beta:
`flatpak install org.freedesktop.Platform/x86_64/20.08`
and got:
```
The application com.brave.Browser/x86_64/beta requires the runtime org.freedesktop.Platform/x86_64/20.08 which was not found
```

When I tried to install from `flathub`, it had already been installed. 
```
Skipping: org.freedesktop.Platform/x86_64/20.08 is already installed
```
I also tried the `runtime/org.freedesktop.Platform/x86_64/20.08beta` runtime to no avail either.
```
flatpak install flathub-beta com.brave.Browser
Looking for matches…
error: The application com.brave.Browser/x86_64/beta requires the runtime org.freedesktop.Platform/x86_64/20.08 which was not found
```

**Comment by x80486** [comment] 2020-10-22 16:20
You might want to file an issue in the Flathub's Brave [repo](https://github.com/flathub/com.brave.Browser/). As it stands, this issue should be already closed :wink:

**Comment by JayDoubleu** [comment] 2020-10-23 12:27
This beta worked for me. The only issue I have at the moment is a latency within the flatpak.
When running speed-tests side by side Brave <> Brave flatpak, the flatpak version adds ~5ms extra to the ping.

**Comment by Zlopez** [comment] 2021-01-12 11:23
I installed the beta and noticed this:

![Screenshot from 2021-01-12 12-22-08](https://user-images.githubusercontent.com/6943409/104308370-d5184380-54d0-11eb-9b3c-792a00e9d51e.png)

I tried to find out what this means, but it redirects me to help center home page. Is this something only related to flatpak beta?

**Comment by JayDoubleu** [comment] 2021-01-12 12:37
@Zlopez if you are on fedora then this is caused by `fedora-chromium-config` package installed on fedora. Uninstall it and the "managed" notification will go away.

**Comment by Zlopez** [comment] 2021-01-12 12:41
Thanks, I didn't knew that something like this is actually on Fedora.

**Comment by rany2** [comment] 2021-01-12 12:51
@Zlopez Maintainer here. It has nothing to do with Fedora. 

It's only to disable the "Set this as default browser" which Flatpak cannot set because of the sandboxing. This way the browser doesn't try to set itself as the web default browser

**Comment by Zlopez** [comment] 2021-01-12 12:57
@rany2 Thanks for the clarification.

If I understood it correctly the `Your browser is managed by your organization` is only there because that prevents Flatpak browsers to try to set itself as default browser. But you are still able to set is as default by yourself.

**Comment by rany2** [comment] 2021-01-12 12:58
> @rany2 Thanks for the clarification.
> 
> If I understood it correctly the `Your browser is managed by your organization` is only there because that prevents Flatpak browsers to try to set itself as default browser. But you are still able to set is as default by yourself.

That is right

**Comment by JayDoubleu** [comment] 2021-01-12 13:20
Well, perhaps this isn't the cause on flatpak in this instance. However `fedora-chromium-config` package on fedora is responsible for `Your browser is managed by your organization` displayed in all chromium based browsers :)

**Comment by Zlopez** [comment] 2021-01-13 10:34
After trying the Brave in Flatpak for one day as my primary browser here is list of what worked and what not for me:

* Browsing the web  - No issue here
* Playing videos - No issue here
* Videoconferencing - No issue here, works even better than in Firefox Flatpak
* Settings as default in GNOME - No issue here
* New start - The browser didn't remembered any cookies, needed to login to all sites again (2-factor needed, which should be needed only for new device). I checked the settings and there is no deletion of anything on exit.
* Opening links from another flatpak (Thunderbird) - took plenty of time and then opened multiple times
* Extensions - I tried Feedly notifier, Watch on LBRY and Treely (I'm really missing tree style tabs in almost every browser), no issue here

**Comment by JayDoubleu** [comment] 2021-01-13 14:03
Tried it some time ago but a bug which is not keeping sessions persistent is quite a big deal.
There are some issues created on https://github.com/flathub/com.brave.Browser

**Comment by Zlopez** [comment] 2021-01-14 09:34
I would say, that the issue is that the Brave needs to have write permissions to some folder on host to be able to save session pernamently.

It's strange that the browser configuration and even the opened tabs are remembered, but the cookies and cache is lost.

**Comment by rany2** [comment] 2021-01-14 09:57
The issue seems to be with the password backend used. You could fix this by adding `--password-store basic`

**Comment by Zlopez** [comment] 2021-01-14 19:20
Found out another issue, Brave in Flatpak doesn't know how to communicate with FIDO key, it just timed out after some time.

I tried the same with Firefox in Flatpak and there was no issue.

**Comment by rany2** [comment] 2021-01-14 20:55
That is an issue with all Chromium-based browsers 

> Found out another issue, Brave in Flatpak doesn't know how to communicate with FIDO key, it just timed out after some time.
> 
> I tried the same with Firefox in Flatpak and there was no issue.

**Comment by Zlopez** [comment] 2021-06-04 09:24
I'm using Brave in flatpak as a daily driver for few months now and I think that it could be moved to stable. It works really well without any major issue I could consider beta issue.

**Comment by alosarjos** [comment] 2021-07-29 04:52
I think it's a good moment to think about this. Last release (1.27) is broken in some systems because of upstream Chromium (The official Chromium Arch package is using some [patches ](https://github.com/archlinux/svntogit-packages/commit/0a33c5ddb3ed1f224b74d331ef9ab97fe6005bb4#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a) until it's fixed upstream.)

With the flatpak version this issue is not happening

**Comment by srirambv** [comment] 2021-09-19 11:39
+1 from @vikdevelop via#18190

**Comment by tunix** [comment] 2021-11-01 12:27
@Zlopez - does it work with extensions.gnome.org ?

**Comment by TheCultLeader666** [comment] 2021-11-06 01:35
@tunix @Zlopez because of the nature of flatpak sandboxing, the browser extension has no way of connecting with the native host. This is an issue with every flatpak browser.

**Comment by alvarlagerlof** [comment] 2021-11-15 13:11
Is there not a point in making it available if it works well enough?

**Comment by JayDoubleu** [comment] 2021-11-15 13:16
I'm still waiting for @brave-dev  to make a little effort in making their browser available to half of linux community (flatpak) who don't use snaps. Just a single sRPM file published to fedora would make it available in flatpak and non-flatpak fedora users at the same time. 👀

**Comment by JaneSmith** [comment] 2021-11-15 16:24
I just want to chime in and point out that Valve's upcoming new portable Linux PC — the Steam Deck — will be making use of a similar approach to Fedora Silverblue. That is, an immutable base OS with third-party applications installed via modern Flatpaks. Further evidence that Flatpak is the solution most everyone is uniting on and standardising on. Having a modern Flatpak package for this application will make it much easier for users to install on the Steam Deck.

**Comment by bayazidbh** [comment] 2021-11-16 07:58
@TheCultLeader666 is there any Flatseal setting that I could modify to allow it? `host-os` and `host-etc` maybe?

**Comment by alvarlagerlof** [comment] 2021-11-16 10:23
> @TheCultLeader666 is there any Flatseal setting that I could modify to allow it? `host-os` and `host-etc` maybe?

There are many issues, but see https://github.com/flathub/org.chromium.Chromium/issues/52

**Comment by TheCultLeader666** [comment] 2021-11-16 11:35
> @TheCultLeader666 is there any Flatseal setting that I could modify to allow it? `host-os` and `host-etc` maybe?

I do not think so, and honestly more holes in the sandbox is not a good idea. I would just keep a native browser around.

**Comment by JaneSmith** [comment] 2021-11-16 15:29
For GNOME extensions, personally I'd just go with the local installation method rather than using the browser add-on. I'm not sure why the browser add-on is a thing in the first place — it just seems unnecessary and even invasive. All you need to do is download the GNOME extension that you want, and put it into `~/.local/share/gnome-shell/extensions/` with the correct UUID folder name. [See here](https://linuxconfig.org/how-to-install-gnome-shell-extensions-from-zip-file-using-command-line-on-ubuntu-18-04-bionic-beaver-linux) for a  guide on doing this. I prefer this method as it doesn't involve any dodgy browser add-ons or sandbox holes, and just works. It still gets shown in the Extensions app like normal.

**Comment by tunix** [comment] 2021-11-17 08:12
Actually I've always had trouble with that method. Either the downloaded pack was different than what the browser installed or I wasn't able to figure out the directory name/structure etc. Of course, this has nothing to do with Brave itself but GNOME. 😄 
So when do we move Brave to stable or (even better) to flathub itself?

**Comment by TheCultLeader666** [comment] 2021-11-17 12:58
> So when do we move Brave to stable or (even better) to flathub itself?

Pretty sure that stable is the same thing as flathub @tunix, since brave is currently in the flathub repo, and there's only 2 flathub repos, beta and stable.

But yes, it would be nice to get brave into stable.

**Comment by alvarlagerlof** [comment] 2021-11-17 22:48
> But yes, it would be nice to get brave into stable.

Are you aware of some sort of list of what an "MVP" stable Brave flatpak would be? To some extent I think it not being there in the stable repo is worse that it being there, but with some corner-cases not working.

**Comment by TheCultLeader666** [comment] 2021-12-11 00:38
Are ad notifications in a working state in the flatpak? I have not seen any. I am on wayland, but I was under the impression that the custom notifications had made their way into stable.

**Comment by Amanse** [comment] 2022-01-26 15:48
is it available publically for testing?

**Comment by JayDoubleu** [comment] 2022-01-26 16:03
> is it available publically for testing?

Brave is available on flathub beta remote. Been using it for quite a while now and it seems stable enough. The reason why it is still in beta is largely due to all chrome/chromium based browsers are still in beta on flathub as there's still few issues yo resolve.

**Comment by BryanQuigley** [comment] 2022-01-26 16:05
I've also been using it for quite a while and it works great :).  

I have not dug deeper but Chromium is now available in non-beta: https://flathub.org/apps/details/org.chromium.Chromium

**Comment by mihaiplesa** [comment] 2022-04-07 19:18
Brave should move to stable in Flathub this week https://github.com/flathub/com.brave.Browser/issues/53

**Comment by fmarier** [comment] 2022-04-07 19:37
Once it's available, we should link to it from https://brave.com/linux/#unofficial-packages.

**Comment by mihaiplesa** [comment] 2022-04-09 17:46
Available now at https://flathub.org/apps/details/com.brave.Browser

**Comment by Rots** [comment] 2022-04-09 20:15
> Available now at https://flathub.org/apps/details/com.brave.Browser


Emmmm...

> NOTE: This package is not verified by, affiliated with, or supported by Brave Software.

And...

> Developer
> Brave Software

**Comment by 239** [comment] 2022-04-11 07:57
Developer != Publisher (package maintainer)

**Comment by fmarier** [comment] 2022-04-12 18:38
I've just updated our installation instructions to link to the Flatpak: https://brave.com/linux/#flatpak

Thanks to everyone who contributed to this effort!

**Closed by fmarier** 2022-04-12 18:38 UTC
Labels: help wanted, suggestion, OS/Linux, priority/P5, setup/installer

**Comment by NayamAmarshe** [comment] 2022-07-24 09:13
The flatpak launch times are a lot longer than native package, any particular reason why?
