### ISSUE TITLE
Shields button overlays Tweet button in the Twitter App

### ISSUE THREAD

**Issue by etridgely** [brave/brave-browser#12652] opened 2020-11-11 22:00 UTC
## Description 

The Brave Shields button overlays "Tweet" text when clicking on a TWTR link in the Twitter app.

## Steps to reproduce 

   1. Open Twitter on Android
   2. Click on any link
   3. The Brave Shields icon overlays the "Tweet" CTA.

## Actual result 

![Screenshot_20201111-131527](https://user-images.githubusercontent.com/5757423/98868155-8bee3980-2424-11eb-919c-88301bb52f69.png)

## Expected result

Shields should not cover the "Tweet" text.

## Issue reproduces how often 

Easily reproducible.  It happens every time.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): Google Pixel
   - Android version: 10
   
## Brave version
v1.16.74

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment] 2020-11-12 06:10
Dupe of #9113

**Closed by srirambv** 2020-11-12 06:10 UTC
Labels: OS/Android, QA/Yes, priority/P3
