### ISSUE TITLE
Add token Next button can't be scrolled to

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#10748] opened 2020-07-15 14:36 UTC
## Description 

https://twitter.com/MillstoneGlobal/status/1283175157557858304

I also reproduced:
<img width="1215" alt="Screen Shot 2020-07-15 at 10 34 28 AM" src="https://user-images.githubusercontent.com/831718/87558426-14cbb300-c687-11ea-9300-d07308aca331.png">

## Steps to Reproduce

   1. Go to about://wallet
   2. Click on Add Token on the bottom left
   3. Make your window small enough vertically so it cuts off the Next button

## Actual result:

You can't scroll to the Next button

## Expected result:

You should be able to scroll to the Next button

## Reproduces how often: 

Always

## Brave version (brave://version info)

All versions

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no 
- Does the issue resolve itself when disabling Brave Rewards?  no
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by srirambv** [comment] 2020-07-15 14:53
Dupe of https://github.com/brave/brave-browser/issues/10704? its a regression

**Comment by bbondy** [comment] 2020-07-15 15:50
Possibly but I'll keep it since it is more specific. We can close them at the same time most likely.

**Closed** 2020-07-16 01:57 UTC
Labels: OS/Desktop, feature/crypto-wallets

**Comment by srirambv** [comment] 2020-07-16 06:40
Verification passed on 

Brave | 1.12.86 Chromium: 84.0.4147.85 (Official Build) beta (64-bit)
-- | --
Revision | e20c13e958edc3707db3d26d513780a7f6331a4b-refs/branch-heads/4147@{# 837}
OS | Linux
Component | `0.1.56`

- Verified making browser window small enough still shows scroll bars on Add token view
![image](https://user-images.githubusercontent.com/17010094/87635774-88c59400-c737-11ea-8b6a-f21648c700fc.png)
