### ISSUE TITLE
Website logo on new tab page

### ISSUE THREAD

**Issue by ristein** [brave/brave-browser#13456] opened 2021-01-10 08:40 UTC
## Description 
when typing an url or search on a new tab page there is a logo of some website. Is this a bug or advertisment?

## Steps to reproduce 

   1. open browser
   2. click magnifier
   3. 

## Actual result 
![Screenshot_20210110-093414_Brave](https://user-images.githubusercontent.com/55446611/104118179-621f9900-5327-11eb-8934-4efafbd498bd.png)
![Screenshot_20210110-093125_Brave](https://user-images.githubusercontent.com/55446611/104118181-6350c600-5327-11eb-9fcd-b3563eecbc00.png)

## Expected result
normal logo

## Issue reproduces how often 
easily since today morning

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): arm64, I guess
   - Device type (Phone, Tablet, Phablet): Oneplus 7 pro
   - Android version: 10
   
## Brave version
1.18.77

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by DevinCharles** [comment] 2021-03-27 05:47
I'm pretty sure this is a "feature" not a "bug." Check "Settings," under "Search Engine." "Standard Tab," you can pick a default search engine. Whatever you pick will show it's favicon to the left. Presumably, you've set 3Dmensions as your default search engine?

**Comment by ristein** [comment] 2021-03-27 06:05
no, my search engine is duckduckgo.
Today I have another icon there, but I don't remember what website this is:
![Screenshot_20210327-070358_Brave](https://user-images.githubusercontent.com/55446611/112711715-c683da80-8eca-11eb-8490-356b3e1c4661.png)

**Comment by DevinCharles** [comment] 2021-03-27 06:24
Looks like "https://www.mz-web.de/"

Sounds like a bug then, if your search engine is set to DuckDuckGo. I can replicate this, but only if I select that site as my search engine.

**Comment by ristein** [comment] 2021-03-27 06:51
ok, thanks.
could be a bug from duckduckgo also

**Comment by bsclifton** [comment] 2021-04-07 19:00
Thanks for the report! 😄 This is a duplicate of https://github.com/brave/brave-browser/issues/12116 - closing in favor of that issue

**Closed by bsclifton** 2021-04-07 19:00 UTC
Labels: closed/duplicate, misc/icons, feature/url-bar, feature/search, OS/Android
