### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by kunal-kiwi** [brave/brave-browser#35478] opened 2024-01-22 11:13 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.120 Chromium: 120.0.6099.234
Operating System: Mac OS X 14.2.1

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. I have migrated from M2 pro to M3 pro but now the browser is crashing, i have removed brave entirely and reinstalled it but i have again started getting crashes.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/7e840a00-802f-5e0b-0000-000000000000

**Comment by bsclifton** [comment] 2024-03-06 06:11
This specific report was deleted - but others with same signature can be found on backtrace with
https://brave.sp.backtrace.io/p/brave/debug?time=quarter&filters=JTVCJTVCJTIyX2RlbGV0ZWQlMjIlMkMlMjJlcXVhbCUyMiUyQyUyMjAlMjIlNUQlNUQ%3D&fingerprint=cabe27fe069b06121c0bb5f8bb349fcd0d3234ad1bb283976c744d33f0670c59&debug=(%226bf26eb%22,0,0)

Callstack
```
[ 00 ] base::ImmediateCrash() ( immediate_crash.h:146 )
[ 01 ] logging::CheckFailure() ( check.h:192 )
[ 02 ] power_metrics::MachTimeToNs(unsigned long long, mach_timebase_info const&) ( mach_time_mac.mm:17 )
[ 03 ] power_metrics::GetCoalitionResourceUsageRate(coalition_resource_usage const&, coalition_resource_usage const&, base::TimeDelta, mach_timebase_info, std::__Cr::optional<power_metrics::EnergyImpactCoefficients>)::$_0::operator()(unsigned long long, unsigned long long) const ( resource_coalition_mac.mm:176 )
[ 04 ] power_metrics::GetCoalitionResourceUsageRate(coalition_resource_usage const&, coalition_resource_usage const&, base::TimeDelta, mach_timebase_info, std::__Cr::optional<power_metrics::EnergyImpactCoefficients>) ( resource_coalition_mac.mm:194 )
[ 05 ] CoalitionResourceUsageProvider::EndIntervals(std::__Cr::optional<power_metrics::CoalitionResourceUsageRate>*, std::__Cr::optional<power_metrics::CoalitionResourceUsageRate>*) ( coalition_resource_usage_provider_mac.mm:134 )
[ 06 ] PowerMetricsReporter::ReportMetrics(UsageScenarioDataStore::IntervalData const&, base::TimeDelta, ProcessMonitor::Metrics const&) ( power_metrics_reporter.cc:259 )
[ 07 ] PowerMetricsReporter::OnBatteryAndAggregatedProcessMetricsSampled(ProcessMonitor::Metrics const&, base::TimeDelta, std::__Cr::optional<base::BatteryLevelProvider::BatteryState> const&) ( power_metrics_reporter.cc:229 )
[ 08 ] base::OnceCallback<void (std::__Cr::optional<base::BatteryLevelProvider::BatteryState> const&)>::Run(std::__Cr::optional<base::BatteryLevelProvider::BatteryState> const&) && ( callback.h:154 )
[ 09 ] base::BatteryLevelProviderMac::GetBatteryState(base::OnceCallback<void (std::__Cr::optional<base::BatteryLevelProvider::BatteryState> const&)>) ( battery_level_provider_mac.mm:52 )
[ 10 ] ProcessMonitor::SampleAllProcesses(ProcessMonitor::Observer*) ( process_monitor.cc:283 )
[ 11 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) ( callback.h:154 )
[ 12 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:326 )
[ 13 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:0 )
[ 14 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) ( callback.h:154 )
[ 15 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:326 )
[ 16 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:0 )
[ 17 ] base::MessagePumpCFRunLoopBase::RunWork() ( message_pump_apple.mm:444 )
[ 18 ] base::apple::CallWithEHFrame(void () block_pointer)
[ 19 ] 0x18572b9ac
```

**Comment by bsclifton** [comment] 2024-03-06 06:11
Closing as a duplicate of https://github.com/brave/brave-browser/issues/35256

**Closed by bsclifton** 2024-03-06 06:11 UTC
Labels: crash, OS/macOS, priority/P2
