### ISSUE TITLE
Crash when returning to first tab on new profile

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#29860] opened 2023-04-19 17:27 UTC
## Description 
Crash when returning to first tab on new profile

```
2023-04-19 13:21:27.429 1541-1541/? I/LayerHistory: com.brave.browser/com.google.android.apps.chrome.Main$_20871#27815 Max (can't resolve refresh rate)
2023-04-19 13:21:27.543 1577-1759/? D/SGM:GameManager: identifyForegroundApp. com.brave.browser, mCurrentUserId: 0, callerUserId: 0
2023-04-19 13:21:27.543 1577-1759/? D/SGM:PkgDataHelper: getGamePkgData(). com.brave.browser
2023-04-19 13:21:28.139 1541-1541/? I/LayerHistory: com.brave.browser/com.google.android.apps.chrome.Main$_20871#27815 Max (can't resolve refresh rate)
2023-04-19 13:21:28.227 1577-1649/? V/WindowManager: Relayout Window{c674455 u0 com.brave.browser/com.google.android.apps.chrome.Main}: viewVisibility=0 req=1080x2400 d0
2023-04-19 13:21:28.230 20871-20871/? I/ViewRootImpl@7f1c9f1[Main]: updateBoundsLayer: t = android.view.SurfaceControl$Transaction@7c2bce4 sc = Surface(name=Bounds for - com.brave.browser/com.google.android.apps.chrome.Main@0)/@0xfd0154d frame = 590
2023-04-19 13:21:28.746 1577-1759/? D/SGM:GameManager: identifyForegroundApp. com.brave.browser, mCurrentUserId: 0, callerUserId: 0
2023-04-19 13:21:28.746 1577-1759/? D/SGM:PkgDataHelper: getGamePkgData(). com.brave.browser
2023-04-19 13:21:28.915 1541-1541/? I/LayerHistory: com.brave.browser/ChromeChildSurface#27826 Max (can't resolve refresh rate)
2023-04-19 13:21:28.915 1541-1541/? I/LayerHistory: com.brave.browser/com.google.android.apps.chrome.Main$_20871#27815 Max (can't resolve refresh rate)
2023-04-19 13:21:29.152 1541-1541/? I/LayerHistory: com.brave.browser/ChromeChildSurface#27826 Max (can't resolve refresh rate)
2023-04-19 13:21:29.153 1541-1541/? I/LayerHistory: com.brave.browser/com.google.android.apps.chrome.Main$_20871#27815 Max (can't resolve refresh rate)
2023-04-19 13:21:29.206 1577-5657/? V/WindowManager: Relayout Window{c674455 u0 com.brave.browser/com.google.android.apps.chrome.Main}: viewVisibility=0 req=1080x2400 d0
2023-04-19 13:21:29.209 20871-20871/? I/ViewRootImpl@7f1c9f1[Main]: updateBoundsLayer: t = android.view.SurfaceControl$Transaction@7c2bce4 sc = Surface(name=Bounds for - com.brave.browser/com.google.android.apps.chrome.Main@0)/@0xfd0154d frame = 617
2023-04-19 13:21:29.531 1577-5977/? V/WindowManager: Relayout Window{c674455 u0 com.brave.browser/com.google.android.apps.chrome.Main}: viewVisibility=0 req=1080x2400 d0
2023-04-19 13:21:29.535 20871-20871/? I/ViewRootImpl@7f1c9f1[Main]: updateBoundsLayer: t = android.view.SurfaceControl$Transaction@7c2bce4 sc = Surface(name=Bounds for - com.brave.browser/com.google.android.apps.chrome.Main@0)/@0xfd0154d frame = 636
2023-04-19 13:21:29.551 1577-8268/? D/SGM:GameManager: identifyGamePackage. com.brave.browser, mCurrentUserId: 0, callerUserId: 0, callingMethodInfo: com.android.server.ssrm.SortingMachine.isGame(SortingMachine.java:162)
2023-04-19 13:21:29.552 1577-8268/? D/SGM:PkgDataHelper: getGamePkgData(). com.brave.browser
2023-04-19 13:21:29.569 20871-20871/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.brave.browser, PID: 20871
    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positiondA{7f991ea position=4 id=-1, oldPos=3, pLpos:3 scrap [attachedScrap] update tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{934a589 VFE...... ......ID 0,168-1080,2032 #7f010981 app:id/recyclerview}, adapter:hA@eefab47, layout:androidx.recyclerview.widget.LinearLayoutManager@6d0698e, context:org.chromium.chrome.browser.ChromeTabbedActivity@2b73772
        at androidx.recyclerview.widget.b.k(chromium-MonochromePublic6432.aab-stable-415011424:556)
        at D71.b(chromium-MonochromePublic6432.aab-stable-415011424:59)
        at androidx.recyclerview.widget.LinearLayoutManager.a1(chromium-MonochromePublic6432.aab-stable-415011424:1)
        at androidx.recyclerview.widget.LinearLayoutManager.M0(chromium-MonochromePublic6432.aab-stable-415011424:54)
        at androidx.recyclerview.widget.LinearLayoutManager.e0(chromium-MonochromePublic6432.aab-stable-415011424:839)
        at androidx.recyclerview.widget.RecyclerView.s(chromium-MonochromePublic6432.aab-stable-415011424:366)
        at androidx.recyclerview.widget.RecyclerView.r(chromium-MonochromePublic6432.aab-stable-415011424:64)
        at androidx.recyclerview.widget.RecyclerView.onLayout(chromium-MonochromePublic6432.aab-stable-415011424:8)
        at android.view.View.layout(View.java:24958)
        at android.view.ViewGroup.layout(ViewGroup.java:6784)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:24958)
        at android.view.ViewGroup.layout(ViewGroup.java:6784)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:24958)
        at android.view.ViewGroup.layout(ViewGroup.java:6784)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:24958)
        at android.view.ViewGroup.layout(ViewGroup.java:6784)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at org.chromium.chrome.browser.compositor.CompositorViewHolder.onLayout(chromium-MonochromePublic6432.aab-stable-415011424:6)
        at android.view.View.layout(View.java:24958)
        at android.view.ViewGroup.layout(ViewGroup.java:6784)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.s(chromium-MonochromePublic6432.aab-stable-415011424:390)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(chromium-MonochromePublic6432.aab-stable-415011424:47)
        at android.view.View.layout(View.java:24958)
        at android.view.ViewGroup.layout(ViewGroup.java:6784)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:24958)
        at android.view.ViewGroup.layout(ViewGroup.java:6784)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:24958)
        at android.view.ViewGroup.layout(ViewGroup.java:6784)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:24958)
        at android.view.ViewGroup.layout(ViewGroup.java:6784)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:24958)
        at android.view.ViewGroup.layout(ViewGroup.java:6784)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:1418)
2023-04-19 13:21:29.803 1577-5427/? W/ActivityManager: crash : com.brave.browser,12063
```

## Steps to reproduce 

1. Install 1.50.x
2. Complete onboarding, don't set brave as default.
3. Open another tab (keep first tab)
4. Enable news via NTP card on second tab
5. Confirm feed is showing in current tab
6. Enable rewards (US)
7. Allow notifications when dialog presented
8. Skip through rewards tutorial
9. Switch to original tab using tab tray

## Actual result 

https://user-images.githubusercontent.com/17885425/233151282-644873e3-e564-43da-b878-4bb88ac95382.mp4

## Expected result
Should not crash

## Issue reproduces how often 
Intermittent

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? No (0/5)

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Device
   - Android version: 13
   
## Brave version
Reproducible on `1.50.114`, `Samsung GS 21`
Reproducible on  `1.50.121`, `Samsung GS 21`
Reproducible on `1.51.87, Chromium 112.0.5615.49` (Beta Channel)

**Comment by kjozwiak** [comment] 2023-04-19 18:12
@Uni-verse nice fine 👍 Managed to reproduce using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/29860#issue-1675326395 on `Pixel 6` running `Android 14`. It mentions it's `Android 13` but it's definitely `Android 14` as the OS is still not displaying `Android 14` via OS settings.

```
Brave | 1.50.121 Chromium: 112.0.5615.138 (Official Build) (32-bit)
--- | --
Revision | 2258f2fcaeb07bc95c992b7ca47f0b43ead9865c-refs/branch-heads/5615@{#1282}
OS | Android 13; Build/UPB1.230309.014
```

@SergeyZhukovsky wonder if it's due to the first NTP not having the favourite icons loaded etc.. It might be in a state where changing back from a previous tab will crash due to the tab not being loaded completely. Could be a completely different reason though. Just a guess.

**Comment by SergeyZhukovsky** [comment] 2023-04-19 18:15
So no crash on nightly right @Uni-verse ? I think that's the crash I fixed recently and haven't uplifted it yet as wanted to take a look how it performs on nightly https://github.com/brave/brave-browser/issues/29634

**Comment by SergeyZhukovsky** [comment] 2023-04-19 19:34
That is fixed in the context of that issue https://github.com/brave/brave-browser/issues/29634. Closing as a dup.

**Closed by SergeyZhukovsky** 2023-04-19 19:34 UTC
Labels: bug, crash, priority/P2, QA/Yes, release-notes/include, OS/Android

**Comment by Uni-verse** [comment] 2023-04-21 19:34
> So no crash on nightly right @Uni-verse ? I think that's the crash I fixed recently and haven't uplifted it yet as wanted to take a look how it performs on nightly #29634

Sorry for the late reply @SergeyZhukovsky, you are correct on this, does not occur on Nightly channel
