### ISSUE TITLE
Browser crash on launch

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#38037] opened 2024-05-03 11:16 UTC
## Description 
Browser crash on launch

## Steps to reproduce 

   1. Update Nightly to 1.67.61
   2. Launch browser
   3. Browser crashes

## Actual result 
Browser crash on launch

## Expected result
No crash when launching Brave

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 14
   
## Brave version
1.67.61

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky @samartnik @hffvld @Uni-verse

**Comment by deeppandya** [comment] 2024-05-03 12:18
@srirambv closing the issue here as duplicate of : https://github.com/brave/brave-browser/issues/38034

**Closed by deeppandya** 2024-05-03 12:18 UTC
Labels: bug, crash, QA/Yes, release-notes/exclude, OS/Android
