### ISSUE TITLE
The image gallery for businesses in Google search/maps doesn't work

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#22772] opened 2022-05-10 15:45 UTC
## Description 

https://bravesoftware.slack.com/archives/C2FQMN4AD/p1652195842062559

Browsing images for a business in Google results isn't working in a clean profile on Linux across channels.

## Steps to Reproduce

   1. Search for a business (e.g. https://www.google.com/search?q=fulu+mandarijn+amsterdam)
   2. Click on the image in the box on the side
   3. A gallery is displayed, but clicking on the next image doesn't do anything

## Actual result:

Unusable gallery

## Expected result:
Usable gallery

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.38.111 Chromium: 101.0.4951.54 (Official Build) (64-bit)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

Looks like the "block trackers & ads" feature is breaking this.
Tested on Linux on 101.1.38.111 (release), 101.1.39.95 (beta), 101.1.40.40 (nightly).

**Comment by LaurenWags** [comment] 2022-05-10 15:49
Reproduced on macOS with the following versions:
* `1.38.111 Chromium: 101.0.4951.54`
* `1.38.109 Chromium: 101.0.4951.41`

Did not reproduce with 
* `1.37.116 Chromium: 100.0.4896.127`

Following STR, seems like last working version was `1.38.104 Chromium 101.0.4951.41` as the next version, `1.38.105 Chromium 101.0.4951.41` does not work.

**Comment by LaurenWags** [comment] 2022-05-10 15:50
cc @rebron @brave/qa-team

**Comment by kjozwiak** [comment] 2022-05-10 16:02
After investigating, looks like this is related to `de-amp`. Once disabled, the above issue that @LaurenWags mentioned isn't reproducible anymore. This is similar to the issue that @A-t-s-u-s-h-i reported ~8 days ago which was fixed via https://github.com/brave/adblock-resources/pull/68.

CC'd @ShivanKaul & @pes10k but looks like both are on PTO. Hopefully this doesn't require a client fix and we can push out a fix via the adblock component.

**Comment by LaurenWags** [comment] 2022-05-10 21:39
Re-checked with 1.38.111 and below component. Issue no longer reproduces.


<img width="298" alt="Screen Shot 2022-05-10 at 5 37 33 PM" src="https://user-images.githubusercontent.com/28145373/167726269-d7b183bb-9781-4673-a429-40d74551244d.png">

Closing as `closed/fixed-by-component-update`.

**Closed by LaurenWags** 2022-05-10 21:39 UTC
Labels: QA/Yes, regression, feature/shields/webcompat, OS/Desktop
