### ISSUE TITLE
Add options to hide "Brave VPN" toggle in menu.

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [brave/brave-browser#23237] opened 2022-06-03 15:51 UTC
Having the "Brave VPN" toggle at the very top of the menu, with no option to hide it for people who do not subscribe to it, feel like Microsoft or Google showing down your throat ads for their own products.

**Make it an optional display like the Brave Rewards icon.**

Source: https://www.reddit.com/r/brave_browser/comments/v41fz3/please_tell_me_theres_a_way_to_remove_this_new/

**Comment by bsclifton** [comment] 2022-06-07 19:39
Thanks for the report! We've addressed this (fixed in in Nightly; we're uplifting to release channel)

I'll close this out as a duplicate of https://github.com/brave/brave-browser/issues/23240

**Closed by bsclifton** 2022-06-07 19:39 UTC
Labels: OS/Android

**Comment by Codel1417** [comment] 2022-10-03 21:10
> Thanks for the report! We've addressed this (fixed in in Nightly; we're uplifting to release channel)
> 
> I'll close this out as a duplicate of #23240

The nightly just moved the VPN icon, not hiding it.
