### ISSUE TITLE
Removing a device from sync chain doesn't remove it from devices list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2527] opened 2018-12-13 12:39 UTC
## Description 

Removing a device from sync chain doesn't remove it from devices list

## Steps to Reproduce

   1. Install 0.58.12 and 0.59.6
   2. Enable Sync on 0.58.12 and copy code to 0.59.6
   3. Ensure both devices are listed on both versions under sync
   4. Remove second device from 0.58.12

## Actual result:

https://drive.google.com/open?id=1pRap44wpQjWFTWXJ6tZIJRtV2rgz9ecZ

## Expected result:
Should remove the device from the list after its removed from sync chain

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

Brave | 0.59.6 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @cezaraugusto @brave/legacy_qa  to verify on other platfroms
Not a serious bug that release needs to be blocked on this @rebron @bbondy

**Comment by darkdh** [comment] 2018-12-13 18:37
please do not test with different channels.
the usage of `--user-data-dir` is shared through DM

**Comment by darkdh** [comment] 2018-12-17 19:21
@cezaraugusto we need to prevent user from clicking remove multiple times(sending duplicated delete record) while delete record is sending under the hood

**Comment by darkdh** [comment] 2018-12-18 04:08
@cezaraugusto we also need to dismiss the remove modal when user click "Remove"
considering this 
1. Have 3 devices in sync chain: a, b, c
2. Remove c from a
3. You can notice the device list on a contains only two devices but the modal is still there

**Comment by darkdh** [comment] 2018-12-18 23:00
move above front end issues to https://github.com/brave/brave-browser/issues/2629
This issue will be closed by https://github.com/brave/brave-core/pull/1135 which addresses the root cause

**Closed** 2018-12-19 19:16 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/sync, priority/P3, release-notes/exclude, release/not-blocking

**Comment by GeetaSarvadnya** [comment] 2018-12-26 15:14
Verification passed on 


Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Windows

- Verified the STR mentioned in the issue
- Verified the test plan mentioned in https://github.com/brave/brave-core/pull/1135
 step 7 fails, unable to connect devices with old /new code word. Logged issue #2737

**Comment by 8thHalfHour** [comment] 2024-08-06 16:21
As of today, I am experiencing this issue on MacBook Pro M1 running Sonoma v14.6 with Brave Beta v1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (arm64).
