### ISSUE TITLE
Craigslist reply doesn't work, even with shields down

### ISSUE THREAD

**Issue by kirkins** [brave/brave-browser#488] opened 2018-07-05 15:54 UTC
Go to an add on craigslist and try using reply button

https://montreal.craigslist.ca/pet/d/reliable-experienced-dog/6634922149.html

Ends up with an error. I tried turning off shields and get the same issue.

Works fine on Firefox.

**Comment by Miyayes** [comment] 2018-07-05 16:31
Some more information: Reproduced on latest version (0.23.19) on MacOS.

In dev console, I get server returning 404 (`Failed to load resource: the server responded with a status of 404 (Not Found)` on the `/reply/mon/pet/6634922149:1` endpoint, which is what is called when a user clicks "Reply"). 

According to network log in Chrome (where CL works), clicking "reply" makes a call out to Google's ReCAPTCHA. That could be the step that's failing in Brave.

Main solution for ReCAPTCHA failures, according to community.brave, has been to disable "Strict Site Isolation". However, I do not have Strict Site Isolation enabled. Have tried toggling and disabling every shield setting one by one, but it doesn't seem to solve the issue.

**Comment by srirambv** [comment] 2018-07-05 16:58
Issue needs to be logged on https://github.com/brave/browser-laptop/issue/. This repo is specific to brave-core,

**Comment by srirambv** [comment] 2018-07-05 18:05
Dupe of https://github.com/brave/browser-laptop/issues/14352. @kirkins please log any browser-laptop related issues on https://github.com/brave/browser-laptop/issue/

**Comment by bsclifton** [comment] 2018-12-31 16:59
Re-opening after locking https://github.com/brave/browser-laptop/issues/14352

Let's share notes and findings here

**Comment by fmarier** [comment] 2019-02-19 20:56
I just tried it on https://vancouver.craigslist.org/van/tag/6822686173.html and it works fine.

I did notice that they now use ReCAPTCHA though. It's possible I've much more trackable (by Google) than others reporting this issue since I'm logged into GSuite.

**Comment by noppojp** [comment] 2019-02-27 05:14
For me, in Linux Mint, it does not work using Firefox or Chrome.
Works in **Chromium** though!!

**Comment by chetu01** [comment] 2019-02-28 12:44
I am not able to Reply to craiglists job. I have tried multiple browsers on mac and windows. 
Is this global issue?

What is solution to it?

**Comment by noppojp** [comment] 2019-03-01 03:03
Sorry Chouhan!  i only posted that i could get the link for the email when i used Chromium in Linux Mint.  Didn't work with Google Chrome or Firefox, but with Chromium it did work.  i'm not a programmer - sorry.

CW Tokyo, Japan mailto:noppojp@yahoo.com 

    On Thursday, February 28, 2019, 9:44:23 PM GMT+9, Chetan Chouhan <notifications@github.com> wrote:  
 
 
I am not able to Reply to craiglists job. I have tried multiple browsers on mac and windows.
Is this global issue?

What is solution to it?

**Comment by m-naumann** [comment] 2019-03-21 11:17
I think it's rather a craigslist only issue.

For https://montreal.craigslist.org it works with Brave, Firefox, Chromium (at least for me from Germany), but only without VPN

For https://sfbay.craigslist.org/ it does not work with any of these, no matter what the settings are, neither with nor without VPN. Other users are also experiencing that: https://forums.craigslist.org/?act=searchFrameMaker&SQ=Reply+button&forumID=9

Due to their "not so good" error messages it's hard to find out the actual reason, though.

I get 
* "sorry, something went wrong" when using a VPN, at sfbay and montreal
* "An error has occurred. Please try again later." when trying to reply to any sfbay listing without VPN

**Comment by pes10k** [comment] 2020-07-07 16:07
It works just fine for me in nightly, i think this can be closed

**Comment by bsclifton** [comment] 2020-07-07 16:25
Works for me too on Release (1.10.97). Closing - let's update / re-open if this happens again 😄

**Closed by bsclifton** 2020-07-07 16:25 UTC
Labels: priority/P5, webcompat

**Comment by codechaitu** [comment] 2023-05-27 18:26
*Solution for Tokyo CL:*
If someone is facing issue, Just add `?lang=en&cc=us` to the end of URL to enable replies.`

**Comment by pes10k** [comment] 2023-05-28 22:22
@ryanbr can you take a look and see if this has creeped back in? If it query-param-filter related?
