### ISSUE TITLE
Allow users to mute Brave Ad notifications for a chosen period of time

### ISSUE THREAD

**Issue by lisa-wolfgang** [brave/brave-browser#15263] opened 2021-04-13 15:28 UTC
## Description 
When users are using Brave for school, work, or generally focusing on a task, Brave Ads are typically a distracting nuisance. This has become even more of an issue during the COVID-19 pandemic, where more people are using their browser on their personal computer to do work or school. In order to mute ads temporarily, users must either dig into their OS's settings and mute notifications or open the Brave Rewards settings and turn off ads, then remember to re-enable them when they're done with their focus session.

It would be useful to have a temporary mute option in the Brave Rewards section of the toolbar that is quickly and easily accessible. There might be options for 15 minutes, 1 hour, 8 hours, etc.

This might be a bit of an ask, but it would also be useful to be able to schedule "focus time". (It would make sense for this to go on the Brave Ads settings page.) For example, the user could set weekdays from 9AM to 5PM as a time period where Brave Ads will not show.

**Comment by tmancey** [comment] 2021-07-30 21:34
Closing issue as a duplicate of https://github.com/brave/brave-browser/issues/17110

**Closed by tmancey** 2021-07-30 21:34 UTC
Labels: OS/Desktop, blocked, closed/duplicate, feature-request, feature/ads, needs-discussion
