### ISSUE TITLE
Support for LaTeX

### ISSUE THREAD

**Issue by mvxxx** [brave/brave-browser#7063] opened 2019-11-22 15:20 UTC
## Description 

On some websites, there is a huge problem with latex equations. 

## Steps to Reproduce

   1. Visit https://bit.ly/33egJUS
   2. Compare this website with google chrome or other browser

## Actual result:

Lack of latex equations.

## Expected result:
latex equations

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.01

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? I am not sure
- Does the issue resolve itself when disabling Brave Rewards? I am not sure
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment] 2020-01-17 17:58
@mvxxx I'm not able reproduce what you're seeing. Can you add screenshots or point out the specific code that's different from Brave vs. Chrome? Equations look like they're coming through properly.

**Comment by mvxxx** [comment] 2020-01-18 16:20
@rebron 
normal: <a href="http://i.imgur.com/rmxdfRX.png">
  <img src="http://imgur.com/rmxdfRXl.png" />
</a>

brave-browser:
<a href="http://i.imgur.com/fH76Nqe.png">
  <img src="http://imgur.com/fH76Nqel.png" />
</a>

I have that problem on both laptop and PC (in both of them I am using Xubuntu). This is the main reason why I can't start using brave-browser instead of other browsers.

**Comment by mvxxx** [comment] 2020-01-18 16:24
@rebron Given problem occurs only on certain websites. For example, math stack exchange works correctly but a lot of others fails.

**Comment by rebron** [comment] 2020-01-24 17:05
<img width="953" alt="Screen Shot 2020-01-24 at 9 02 59 AM" src="https://user-images.githubusercontent.com/5951041/73088053-5a51b500-3e88-11ea-8cce-5c087b5c22f7.png">
@mvxxx Do you have some script blocking settings turned on?

**Comment by mvxxx** [comment] 2020-01-31 13:47
@rebron - No, I don't have anything turned on. That happened also when I had used brave on raw Xubuntu - I am not sure if it depends on OS but maybe Xfce has some problem with that.

**Comment by bsclifton** [comment] 2020-03-30 05:36
@mvxxx is this still an issue with later versions of Brave? (ex: current release is 1.5.115). I tried and it looks great to me on macOS.

You are running Xubuntu, correct? Some Linux users have had some graphics issues unfortunately (artifacts, etc) which may be visible by comparing chrome://gpu in Brave versus Chrome. I would try to disable `Use hardware acceleration when available` if this does happen still:
brave://settings/?search=hardware

Please let us know! Thanks 😄

**Comment by mvxxx** [comment] 2020-03-30 08:12
@bsclifton Yes, I use Xubuntu. I am not sure if it was related to GPU/driver because on my laptop I have only I don't have dedicated GPU, only integrated with CPU. Anyway, after that release (checked `brave-browser --version` == 1.5.115) it seems to work correctly! ;) Thanks for the support! :-)

**Comment by bsclifton** [comment] 2020-03-30 15:35
@mvxxx thanks for the quick follow up 😄 Super glad to hear this worked! I'll go ahead and close the issue as we have other issues tracking GPU problems

While this may not be a problem with your driver per-se (especially since it works in Chrome for you)... it could be a problem with the blacklisted drivers / GPUs that Chromium is looking for during start up. If the specified hardware/driver is there, Chromium will automatically disable HW accel). We need to be matching what Chrome has and often because of field trials (on the Chrome side) we  end up deviating

**Closed by bsclifton** 2020-03-30 15:35 UTC
Labels: OS/Linux, gpu/driver, workaround/disable-hw-acceleration
