### ISSUE TITLE
after group of bookmarks deleted on device2, deletion is not synced to device1

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3261] opened 2019-02-07 16:46 UTC
## Description 
I deleted a chunk (100) bookmarks on device2 and the bookmarks were not deleted on device1. However, deleting a chunk of bookmarks on device1 does delete the bookmarks on device2.

## Steps to Reproduce

   1. Clean profiles using 0.59.35 on both laptops (I was syncing macOS <-> macOS)
   2. Designate one to be macOS1/device1. Import 5k bookmarks. 
[brave_sortish_5000 - ordered.html.zip](https://github.com/brave/brave-browser/files/2841825/brave_sortish_5000.-.ordered.html.zip)

   3. On the other device (macOS2/device2) import 1k bookmarks. 
[brave_sortish_1000 -ordered.html.zip](https://github.com/brave/brave-browser/files/2841831/brave_sortish_1000.-ordered.html.zip)

   4. Start sync chain on macOS1 and join on macOS2.
   5. In about 10-15 minutes devices should be synced fully.
   6. On macOS2, drill into the 0-99 folder all the way down to the 1109 folder. Delete the first 100 bookmarks in this folder (1-100).

## Actual result:
This bookmark deletion will never get synced to macOS1. 
![screen shot 2019-02-07 at 11 42 42 am](https://user-images.githubusercontent.com/28145373/52427218-8b957180-2acd-11e9-86be-5207bee87b96.png)

## Expected result:
In the image above, 1-100 should not be there.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
I took the STR a bit further and did the below, which worked successfully
* On macOS1, drill into Imported folder and navigate to 1000-1099 folder.
* Delete the first 50 bookmarks (1000-1050)
* Wait 5 minutes, this deletion is synced to macOS2.

**Comment by AlexeyBarabash** [comment] 2019-02-13 15:06
Could not reproduce on `0.62.0` master, trying on `0.59.35` stable.

**Comment by AlexeyBarabash** [comment] 2019-02-13 17:15
Could not reproduce it on `0.59.35`  also , but on step 5 devices were not synced completely in more than a hour, the last inner folder on device 2 had 3395 of 3956 bookmarks, 75-518 were missing. On example of bookmark 444 I could see device 1 had sent it, but device 2 had never received.

**Comment by AlexeyBarabash** [comment] 2019-04-11 15:35
I could not reproduce this issue:
![image](https://user-images.githubusercontent.com/24739341/55970333-058dd680-5c88-11e9-8437-205e2d10b8eb.png)


Brave | 0.65.44 Chromium: 74.0.3729.61 (Developer Build) (64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Linux

I think, it had been fixed by https://github.com/brave/sync/pull/284.

**Closed by AlexeyBarabash** 2019-04-11 15:35 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/sync, release-notes/include
