### ISSUE TITLE
How do I remove or disable rewards completely?

### ISSUE THREAD

**Issue by dfmabbas** [brave/brave-browser#2966] opened 2019-01-15 10:50 UTC
Hello. I want to `remove or disable` **rewards** `completely` from the browser, how do I do this?
Currently there is an icon at the load address bar after the deactivation.
##### Please guide me.

**Comment by NejcZdovc** [comment] 2019-01-15 11:20
closing as dupe of https://github.com/brave/brave-browser/issues/1475

**Closed by NejcZdovc** 2019-01-15 11:20 UTC

**Comment by mleskov** [comment] 2019-10-05 13:04
Here everywhere teach as turn off the icon of the Rewards. But the main question is how to completely disable Brave Rewards? That there was no Bat process at all. Deleting icons does not remove the unnecessary processes off the Bat.  
![80b66d1f5467b1d19f78775e069172f76e94b11c854861b9d669d668dde96d7b](https://user-images.githubusercontent.com/56195270/66255212-ceb1fc80-e7a2-11e9-9974-bdf1051c08e7.png)

**Comment by niico100** [comment] 2019-11-23 08:52
There is a spam ad on the new tabs page - I don't think 1475 is therefore a dupe. I - and many users - would like to 100% remove any reference to Rewards totally from ever appearing.

**Comment by NejcZdovc** [comment] 2019-11-23 09:03
@niico100 what do you mean spam ad? Can you please share a print screen of it? Thank you
