### ISSUE TITLE
Generate new Tor Connection.

### ISSUE THREAD

**Issue by clicky6** [brave/brave-browser#18128] opened 2021-09-15 09:13 UTC
[start]

Brave has the ability to auto connect to Tor Onion sites.
I also use Tor as a browser, and so, I noticed something that is missing in Braves Tor connectivity.
That is the ability to reset and generate a new Tor connection.

In Brave, whenever I use a Tor window, the connection is always the same, (so it seems) as the country identifiers are always the same country.
That is to say, for example, I get adds as if I were in “England”.
In Brave, it is always the same country.

With Tor, you can reset and form a new connection, and, it is apparent as you see ads etc… for “Germany” or “Japan” etc…

If there is a way to reset / force a new Tor connection in Brave, Id like to be informed of how to do so.

If there is not, matching Tors functionality would be a service to Brave users.
Since, as of now, I do not use Braves Tor connection option, and use Tor directly to connect via a new Tor pathway each time.

[end]

**Comment by srirambv** [comment] 2021-09-15 10:41
Possible dupe of #11822

**Comment by diracdeltas** [comment] 2021-09-15 21:40
i think we can close this because the feature is available in the hamburger menu, just somewhat hard to find
![Uploading Screen Shot 2021-09-15 at 2.39.26 PM.png…]()

**Closed** 2021-09-15 22:14 UTC
Labels: OS/Desktop
