### ISSUE TITLE
Duplicate text in restore wallet modal

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2481] opened 2018-12-12 07:25 UTC
## Description 

Duplicate text in restore wallet modal

## Steps to Reproduce

   1. Open advance settings in rewards
   2. Switch to restore
   3. `Enter your recovery code or` is duplicated below the text input area

## Actual result:

![screenshot from 2018-12-12 12-51-53](https://user-images.githubusercontent.com/17010094/49853362-ee8bc480-fe0c-11e8-868c-15b603a3f818.png)

## Expected result:
Should not have duplicate text

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Issue reproduced on macOS by @kjozwiak 
Related to #2446

**Comment by LaurenWags** [comment] 2018-12-12 14:18
Issue does not reproduce on `macOS x64 10.12.6` for me. I have different text below the Restore box which says `Restoring with a recovery key will replace your current wallet. So make sure you empty or back up your current wallet before restoring.`

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

![screen shot 2018-12-12 at 9 14 16 am](https://user-images.githubusercontent.com/28145373/49875220-74e4de00-fdee-11e8-8278-cef8dce3870e.png)

**Comment by kjozwiak** [comment] 2018-12-12 15:58
Seeing the same thing as @LaurenWags, seems to be affecting Windows and Linux platforms only.

**Comment by btlechowski** [comment] 2018-12-12 16:35
Not reproducible on Windows 7 x64 nor Windows 10 x64

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7 x64

![image](https://user-images.githubusercontent.com/34715963/49884012-2b1ee680-fe34-11e8-8276-a0e37d8abd72.png)

**Comment by simonhong** [comment] 2018-12-13 01:56
@srirambv Can you re-install latest version and check again?
https://github.com/brave/brave-core/pull/909 fixes this and it is merged into 0.58.x and 0.59.x.
I newly installed beta/dev version on linux(ubuntu) and I can't see duplicated strings.

**Comment by srirambv** [comment] 2018-12-13 11:45
@simonhong  Here's a recording of clean install on 0.59.x beta build and can still reproduce it https://drive.google.com/open?id=1LTpd88oib9mfzJ1-E-vrY5bDt5P51beV

**Comment by rebron** [comment] 2018-12-18 05:30
@NejcZdovc any idea on this one? Would like a fix for 58.x but can move out if we can't get a fix in time.

**Comment by kjozwiak** [comment] 2018-12-18 06:16
As mentioned under https://github.com/brave/brave-browser/issues/2446#issuecomment-448108789, this is still reproducible under the following build:

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
--- | ---
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Linux

**Comment by kjozwiak** [comment] 2018-12-18 22:44
Copying response from https://github.com/brave/brave-browser/issues/2446#issuecomment-448399376.

> Removing `P3` and adding the `needs-investigation`. Both @NejcZdovc & @btlechowski can't reproduce the issues on their VM's but @srirambv and myself can. We need to figure out what the difference is any why some users are seeing the above and some aren't.
> 
> I did a quick Zoom call with @NejcZdovc and he was using the same Ubuntu version but couldn't reproduce the issue. Maybe some type of dependency issue? I tried it on my Mint laptop and I could reproduce the same issue even though the `deb` installer told me all dependencies were installed.
> 
> We need more information.

**Comment by NejcZdovc** [comment] 2019-01-30 04:34
closing as this one was closed as well https://github.com/brave/brave-browser/issues/2446

**Closed by NejcZdovc** 2019-01-30 04:34 UTC
Labels: OS/Linux, QA/Yes, bug, copy/content/text, feature/rewards, needs-investigation, release-notes/exclude
