### ISSUE TITLE
Tabs hang indefinitely when opening Twitter emojis 

### ISSUE THREAD

**Issue by Aninstance** [brave/brave-browser#3809] opened 2019-03-20 14:45 UTC
## Description

Browser tab hangs indefinitely when attempting to add a Twitter emoji to a tweet on the official Twitter.com website, after clicking on the emoji icon (smiley face) on the tweet input field.

Eventually a message appears asking whether the tab should be closed.

The tab's session is not recoverable after clicking aforesaid icon to add an emoji. A force close is required (obviously resulting in loss of the unsent tweet. The text cannot be copied to clipboard prior to closing the tab, as the page is entirely unresponsive and text is unselectable).

## Steps to Reproduce

As description.

## Actual result:

As description.

## Expected result:

The tab not to hang and for the emoji to be added to the tweet.

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

Brave | 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Linux

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds? 

Unknown.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?

No.

- Is the issue reproducible on the latest version of Chrome? 

Unknown.

**Comment by rebron** [comment] 2019-03-22 16:23
Closing. QA can't reproduce. Can you try with a newer version, we're on 61.52?

**Comment by Aninstance** [comment] 2019-03-22 16:33
The issue is reproducible on my machine - the bug manifests every time I attempt to click on the Twitter Emoji button. I'll open a new bug if this persists on a new version, as and when the upgrade is available.  I'm using the Ubuntu snap package, which is 0.59.35.

**Comment by kamleshrao** [comment] 2019-03-28 09:51
I am able to reproduce this since more than a months time.  I am regularly performing updates, but still not helping.  I have even formatted my Ubuntu 16.04 LTS and installed Ubuntu 18.04 LTS.  But the problem still exists.  

I wonder what went wrong with twitter emojis.  This was not happening before.

I am facing this problem only on Ubuntu.  Everything is working well on Windows 10 laptop.

Please reopen this issue (verify on Ubuntu and not on Windows) and help in getting it fixed.

My Brave version on Ubuntu 18.04LTS is: 

> Version 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)

**Comment by Aninstance** [comment] 2019-03-28 11:28
Thanks for confirming the bug @kamleshrao, and on updated versions. This is a strange one. I'm running Kubuntu 18.04.02 LTS. 

Which version are you on now? Are you using the snap package, or do you install by other methods?

The issue manifests 100% of the time on my system and results in being unable to close the frozen tab. If that's the only tab open, I need to force close the browser (i.e. kill the process) as the entire window becomes completely unresponsive.

**Comment by kamleshrao** [comment] 2019-03-28 15:45
I get exact same behavior what you mentioned.  Use the trick of "Ctrl+T" which opens a new tab and then I close the frozen tab. 

I used the official Brave documentation to install it on my Ubuntu 18.04 LTS.  Below are the commands: 

```
curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -

source /etc/os-release

echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ $UBUNTU_CODENAME main" | sudo tee /etc/apt/sources.list.d/brave-browser-release-${UBUNTU_CODENAME}.list

sudo apt update

sudo apt install brave-browser brave-keyring
```

And, here is my Unix version details: 

```$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
``` 
I also confirm that this issue does not appear on Windows 10 OS. Hope someone from Brave support reopens this issue and gives fix.

**Comment by kamleshrao** [comment] 2019-04-02 07:01
I am still facing this problem @rebron - Can you please reopen this and look into this issue.

Hope this issue, does not reduce the number of Brave users. Please do the needful.

**Comment by kjozwiak** [comment] 2019-04-03 06:47
Re-opening as we're getting a few reports of this issue still occurring, specifically Linux. Community reports:

* https://twitter.com/aninstanceofdan/status/1113177844136505344
* https://twitter.com/plus530/status/1113176372015378432

**Comment by kamleshrao** [comment] 2019-04-03 06:54
Thanks for reopening the issue.  Will be happy to review it or share more details, if you need any.

**Comment by srirambv** [comment] 2019-04-03 13:00
I just tried this on my Ubuntu installation and there is no tab hang. Running the current release version (0.61.52)
```
$ uname -a
Linux 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Is the browser language set different?

**Comment by Aninstance** [comment] 2019-04-03 14:02
@srirambv I just upgrade my Ubuntu 18.04 LTS and tested, but the issue persists. In my case, language is set to UK English.

Developer console shows a lot (literally hundreds) of simultaneous pending network requests  - stalled at 1.30s - for the emoji png files. E.g.:

`Request URL: https://abs.twimg.com/emoji/v2/72x72/1f533.png
Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
DNT: 1
Referer: https://twitter.com/
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36`

I'm wondering if this could be triggering some kind of abuse mitigation?

As an aside, I'm assuming the User-Agent is identified like as part of counter fingerprinting measures.

**Comment by kamleshrao** [comment] 2019-04-03 14:09
@srirambv Did you try logging in to Twitter website and selecting a emoji while composting a tweet?

**Comment by srirambv** [comment] 2019-04-03 16:06
@kamleshrao Yes. that's exactly what I did

@Aninstance ok was able to reproduce it this time. I see the tab just freezes up and is useless. However I am able to use the browser by opening new tabs but still can't close the browser via close button. I see these error show up when i try to add an emoji in tweet window

```
[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://abs.twimg.com/a/1554171232/font/edge-icons-Regular.woff
(index):1 Refused to connect to 'data:text/plain,' because it violates the following Content Security Policy directive: "connect-src https://rmpdhdsnappytv-vh.akamaihd.net https://prod-video-eu-central-1.pscp.tv https://prod-video-ap-south-1.pscp.tv https://*.giphy.com https://dwo3ckksxlb0v.cloudfront.net https://prod-video-us-east-2.pscp.tv https://prod-video-cn-north-1.pscp.tv https://vmaprel.snappytv.com https://smmdhdsnappytv-vh.akamaihd.net https://*.twimg.com https://embed.pscp.tv https://api.twitter.com https://prod-video-eu-west-1.pscp.tv https://*.video.pscp.tv https://rmmdhdsnappytv-vh.akamaihd.net https://clips-media-assets.twitch.tv https://prod-video-ap-northeast-2.pscp.tv https://prod-video-us-west-2.pscp.tv https://pay.twitter.com https://prod-video-us-west-1.pscp.tv https://analytics.twitter.com https://vmap.snappytv.com https://*.twprobe.net https://prod-video-ap-northeast-1.pscp.tv https://smdhdsnappytv-vh.akamaihd.net https://prod-video-eu-west-3.pscp.tv https://syndication.twitter.com https://sentry.io https://rmdhdsnappytv-vh.akamaihd.net https://media.riffsy.com https://mmdhdsnappytv-vh.akamaihd.net https://prod-video-ca-central-1.pscp.tv https://embed.periscope.tv https://smpdhdsnappytv-vh.akamaihd.net https://prod-video-sa-east-1.pscp.tv https://vmapstage.snappytv.com https://upload.twitter.com https://proxsee.pscp.tv https://mdhdsnappytv-vh.akamaihd.net https://prod-video-ap-southeast-2.pscp.tv https://prod-video-cn-northwest-1.pscp.tv https://prod-video-eu-west-2.pscp.tv https://canary-video-us-east-1.pscp.tv https://dev-video-us-west-2.pscp.tv https://prod-video-us-east-1.pscp.tv blob: 'self' https://prod-video-ap-northeast-3.pscp.tv https://vmap.grabyo.com https://prod-video-ap-southeast-1.pscp.tv https://mpdhdsnappytv-vh.akamaihd.net https://dev-video-eu-west-1.pscp.tv".

abs.twimg.com/:1 Refused to frame '' because it violates the following Content Security Policy directive: "frame-src 'self' https://twitter.com https://*.twimg.com https://player.vimeo.com https://pay.twitter.com https://ton.twitter.com https://syndication.twitter.com https://vine.co twitter: https://www.youtube.com https://platform.twitter.com https://upload.twitter.com".

(index):1 Refused to load the script 'data:text/plain,' because it violates the following Content Security Policy directive: "script-src https://ssl.google-analytics.com https://twitter.com 'unsafe-eval' https://*.twimg.com https://api.twitter.com https://analytics.twitter.com https://publish.twitter.com https://ton.twitter.com https://syndication.twitter.com 'nonce-w0OCryhgbqOS8ALt/i8qEQ==' https://www.google.com https://platform.twitter.com https://www.google-analytics.com blob: 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

2(index):1 Refused to connect to 'data:text/plain,' because it violates the following Content Security Policy directive: "connect-src https://rmpdhdsnappytv-vh.akamaihd.net https://prod-video-eu-central-1.pscp.tv https://prod-video-ap-south-1.pscp.tv https://*.giphy.com https://dwo3ckksxlb0v.cloudfront.net https://prod-video-us-east-2.pscp.tv https://prod-video-cn-north-1.pscp.tv https://vmaprel.snappytv.com https://smmdhdsnappytv-vh.akamaihd.net https://*.twimg.com https://embed.pscp.tv https://api.twitter.com https://prod-video-eu-west-1.pscp.tv https://*.video.pscp.tv https://rmmdhdsnappytv-vh.akamaihd.net https://clips-media-assets.twitch.tv https://prod-video-ap-northeast-2.pscp.tv https://prod-video-us-west-2.pscp.tv https://pay.twitter.com https://prod-video-us-west-1.pscp.tv https://analytics.twitter.com https://vmap.snappytv.com https://*.twprobe.net https://prod-video-ap-northeast-1.pscp.tv https://smdhdsnappytv-vh.akamaihd.net https://prod-video-eu-west-3.pscp.tv https://syndication.twitter.com https://sentry.io https://rmdhdsnappytv-vh.akamaihd.net https://media.riffsy.com https://mmdhdsnappytv-vh.akamaihd.net https://prod-video-ca-central-1.pscp.tv https://embed.periscope.tv https://smpdhdsnappytv-vh.akamaihd.net https://prod-video-sa-east-1.pscp.tv https://vmapstage.snappytv.com https://upload.twitter.com https://proxsee.pscp.tv https://mdhdsnappytv-vh.akamaihd.net https://prod-video-ap-southeast-2.pscp.tv https://prod-video-cn-northwest-1.pscp.tv https://prod-video-eu-west-2.pscp.tv https://canary-video-us-east-1.pscp.tv https://dev-video-us-west-2.pscp.tv https://prod-video-us-east-1.pscp.tv blob: 'self' https://prod-video-ap-northeast-3.pscp.tv https://vmap.grabyo.com https://prod-video-ap-southeast-1.pscp.tv https://mpdhdsnappytv-vh.akamaihd.net https://dev-video-eu-west-1.pscp.tv".
```

**Comment by srirambv** [comment] 2019-04-03 16:49
Reproducible on `0.62.50` as well

**Comment by kamleshrao** [comment] 2019-04-03 17:48
I updated my packages few minutes back and now got the Brave Version updated to below one: 

```
Version 0.62.50 Chromium: 73.0.3683.86 (Official Build) (64-bit)
```

I am glad that Emojis are working well for me now on Ubuntu 18.04 LTS.  Can someone confirm if there was a fix rolled out today? Will be happy to know what was the fix! 

@Aninstance can you verify from our side too?

**Comment by Aninstance** [comment] 2019-04-03 18:08
@kamleshrao I'm glad it's working for you on the new release. I'm running the Snap package, which has yet to be upgraded to the newer version, so unable to confirm immediately. I note, however, that @srirambv reports above that the issue did persist for them on version 0.62.50.

**Comment by kamleshrao** [comment] 2019-04-03 18:19
@Aninstance OOPS! I closed Brave and reopened it. And now the problem is again back.  Emoji's still hanging. 

I am really unaware how it worked earlier. 

Tried reopening browser multiple times and problem still exists :-(

**Comment by Aninstance** [comment] 2019-04-04 11:21
@kamleshrao I don't have the preview option on my Twitter account yet; must be a phased roll-out. Interested to know if that resolves the issue, at least so far as Twitter is concerned; the underlying issue would nevertheless persist. Tabs should not freeze - and refuse to close - in any event, so I'd have thought this would merit a look at error handling, if nothing else.

**Comment by srirambv** [comment] 2019-04-04 14:02
@bbondy @rebron to prioritize the issue. Tab becomes useless and can't close browser once you run into the issue. I can see how it can be annoying to users who are on Twitter web.

**Comment by kamleshrao** [comment] 2019-04-04 14:20
Thanks @srirambv for understanding the feeling of Twitter Web users. Let me know if you need any additional information or help in verification from my Ubuntu environment. 

@Aninstance I am yet to switch to new Twitter Preview. I remember switching once in 2018 and didn't like it. Later I switched back to original view.

**Comment by Aninstance** [comment] 2019-04-04 15:49
I've been fiddling around with config options in brave://flags/ and although I haven't yet found anything permanently mitigates the issue, I did notice a curious pattern that seems to replicate 100% of the time on my system. Thought maybe this might be of help in debugging.

- Navigate to brave://flags/
- Make a configuration change. It does not matter what setting is changed - any change to any configuration will do.
- Restart the browser.
- Navigate to the Twitter web app, click Tweet and attempt to add an emoji. This should work as expected, without any issue.
- Open another instance of Twitter in a new tab. Again, adding emojis to a Tweet works without issue.
- Close the browser.
- Reopen the browser, navigate to Twitter once more and try to add an emoji to a Tweet. The issue has now returned.

Strangely, it appears that the action of changing a configuration and restarting the browser somehow mitigates the issue, however the bug returns again in any subsequent browser session.

Perhaps this is something to do with some kind of caching that's only cleared upon restart of the browser following a config change? Just speculation. I have looked at config options concerning caching of various sorts, but disabling those has no permanent affect on the problem.

It does appear to be related to the downloading of the emoji png files (from the pbs.twimg.com domain) - the request stalls when the bug manifests. But, no idea whether the stalling of the request is a cause or symptom.

**Comment by kamleshrao** [comment] 2019-04-08 04:04
Just FYI - I updated my Brave on Ubuntu to below version, but still having this issue open. 

```
Version 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)
```

**Comment by jaec** [comment] 2019-04-18 16:03
I have exactly the same problem. 

Brave | 0.62.51 Chromium: 73.0.3683.103 (Build oficial) (64 bits)
-- | --
Revisión | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}

Runing on Ubuntu 18.04.

**Comment by kamleshrao** [comment] 2019-05-03 11:37
Checked today with latest update, but still having same issue. 

My current Brave version on Ubuntu is: 

`Version 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)`

**Comment by xtat** [comment] 2019-05-11 01:51
Reproduced in Debian - Brave Browser 73.0.62.51

**Comment by rebron** [comment] 2019-05-14 18:10
cc: @simonhong

**Comment by srirambv** [comment] 2019-06-12 12:30
This is still reproducing in the current release build `0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)`

**Comment by simonhong** [comment] 2019-06-13 05:15
@srirambv Can you repro this with `--disable-gpu`?
I'm using brave with that option on linux vm(parallels) and can't repro this.

**Comment by Aninstance** [comment] 2019-06-13 08:57
@simonhong I've just tested running with the `--disable-gpu` arg on `Version 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)` Ubuntu Snap package, and confirm the issue ***does not*** occur there. 

So passing `--disable-gpu` to disable the GPU rendering (presumably) does indeed mitigate the issue. When not passing `--disable-gpu`, the issue does manifest, as before.

**Comment by simonhong** [comment] 2019-06-13 10:09
@Aninstance Thanks for checking! That's why I can't repro this issue on my local.
Without `--disable-gpu`, only black window is launched on parallels vm.
@rebron I think I can't take this issue. I don't have available machine that can run brave w/o `--disable-gpu`.

**Comment by kjozwiak** [comment] 2019-06-13 15:44
> @Aninstance Thanks for checking! That's why I can't repro this issue on my local.
> Without `--disable-gpu`, only black window is launched on parallels vm.
> @rebron I think I can't take this issue. I don't have available machine that can run brave w/o `--disable-gpu`.

There's an issue with CR74 that @tmancey also ran into with `parallels` where it's basically displaying a completely black screen. It's also reproducible on Chrome. Example:

<img width="1066" alt="Screen Shot 2019-04-05 at 6 12 40 PM" src="https://user-images.githubusercontent.com/2602313/59446945-7a88a400-8dd0-11e9-8cf6-ee5f29f0f8d7.png">

@rebron we'll need someone who has VMWare or VirtualBox installed.

**Comment by tmancey** [comment] 2019-06-13 15:53
@kjozwiak @rebron you can pass `--disable-gpu` due to bad drivers for latest 18.04 patches

**Comment by srirambv** [comment] 2019-06-13 16:00
@simonhong doesnt work for me. It still hangs with `--disbale-gpu`

![image](https://user-images.githubusercontent.com/17010094/59448189-a147da00-8dd2-11e9-9c75-4d2763691607.png)

**Comment by jaec** [comment] 2019-06-13 16:59
@simonhong doesnt work for me either. It still hangs with --disbale-gpu

BTW, I'm scrolling the emojis list before it is fully loaded.

**Comment by bsclifton** [comment] 2019-06-28 19:03
+1 from https://twitter.com/gobinathco_/status/1144678980584267776

**Comment by houruomu** [comment] 2019-07-03 04:32
It is not reproducible on my version though.
Windows 10, Version 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)

**Comment by kamleshrao** [comment] 2019-07-03 05:12
@houruomu We all are facing this issue on Ubuntu/Linux OS.  There is no issue on Windows OS.

**Comment by houruomu** [comment] 2019-07-03 08:34
@kamleshrao Sorry I should have searched for Windows before posting my response.

**Comment by rebron** [comment] 2019-10-08 15:56
@srirambv Can you check this again with 69.x? Possibly fixed chromium bump?

**Comment by xtat** [comment] 2019-10-08 18:52
Seems to have gone away on my systems

**Comment by srirambv** [comment] 2019-10-08 19:18
@rebron  seems to be working on release build on Linux.

**Comment by bsclifton** [comment] 2019-10-08 23:04
@Aninstance @kamleshrao @jaec can you please try the latest release (should be 0.69.132) and report back? Based on our testing, it should be working (thanks for confirming, @srirambv! 😄)

**Comment by Aninstance** [comment] 2019-10-08 23:30
@bsclifton I'm unable to provide useful data here, as I'm running `0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)` on my Kubuntu 18.04 box (snap package) - and the issue seems to have been resolved. No issues at all with the Twitter emojis now. However, I note that others were still having the same issue as of later versions than I'm on. If you still feel my testing on a later version would nevertheless be valuable, of course I'd be happy to do that - just let me know (the snap seems to be lagging behind somewhat).

**Comment by kjozwiak** [comment] 2019-10-09 07:16
@Aninstance probably a good idea moving over to our official packages [1] rather than using `Snap`. `0.63.48` is pretty old and is using a very outdated `Chromium`. Stable is already on `CR 77`. Definitely your choice but there's some risk using an older CR!

* [1] - https://brave-browser.readthedocs.io/en/latest/installing-brave.html

**Comment by jaec** [comment] 2019-10-09 13:25
@bsclifton It appears to be resolved now.

**Comment by bsclifton** [comment] 2019-10-09 15:53
@jaec great- thanks for confirming! And thanks everybody for your patience 😄

**Closed** 2019-10-09 15:52 UTC
Labels: OS/Linux, bug, perf, priority/P2

**Comment by kamleshrao** [comment] 2019-12-01 05:17
This really took a long time to get it resolved.  I tested it on below Ubuntu (64-bit) version and I confirm that Smileys are working fine for me now.

> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.3 LTS
> Release:	18.04
> Codename:	bionic
> 

Below is the Brave version:

> Version 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
