### ISSUE TITLE
Private windows should use the sunglasses icon instead of the incognito secret-agent hat-and-glasses icon

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1385] opened 2018-10-01 23:41 UTC
Instead of the people menu or the incognito hat-and-glasses, private windows should have the sunglasses logo.

![46332729-7e71ee80-c5d2-11e8-8779-dd39edcb3289](https://user-images.githubusercontent.com/639937/46367088-9af14380-c631-11e8-8f52-06a3b20e85f4.png)

**Comment by srirambv** [comment] 2018-10-02 00:13
Dupe of https://github.com/brave/brave-browser/issues/738

**Comment by tomlowenthal** [comment] 2018-10-02 16:36
Hold up on implementing for a hot second, a sunglasses icon is incoming.

**Comment by tomlowenthal** [comment] 2018-10-02 17:55
@rossmoody can provide the asset for this.

**Closed** 2018-10-05 00:14 UTC
Labels: QA/Yes, feature/private-browsing

**Comment by btlechowski** [comment] 2018-10-10 14:31
Verification passed on

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/46743719-f8c50180-cca9-11e8-9b67-5bcee0880a0d.png)
