### ISSUE TITLE
P3A timestamps don't update even when value is changed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13927] opened 2021-02-03 06:07 UTC
## Description 

`Brave.Search.DefaultEngine.4` timestamp doesn't update even when the value is being changed 

## Steps to Reproduce

   1. Install 1.20.96 beta build
   2. Keep default search engine during onboarding
   3. Check P3A Value for `Brave.Search.DefaultEngine.4` ensure its set to 1 (Google) and sent is set to true
   4. Make note of the timestamp
   5. Change default SE to Ecosia
   6. Check `Brave.Search.DefaultEngine.4` P3A metric, successfully updates the value to 7
   7. Keep browser idle for a while and check timestamp, remains same as in step 4 doesn't update, sent is still set to `true`

## Actual result:

Brave.Search.DefaultEngine.4 timestamp doesn't update even when value is being changed 

## Expected result:
Should update timestamp when the data is sent. If its not sent to server, sent should be set to `false`

## Reproduces how often: 

Easy

## Desktop Brave version:

Brave | 1.20.97 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | `68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}`
OS | Windows 10 OS Version 2004 (Build 19041.746)

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Mostly 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

 @GeetaSarvadnya verified and confirmed bug on Desktop

cc: @iefremov @AlexeyBarabash

**Comment by GeetaSarvadnya** [comment] 2021-02-03 06:08
Reproduced in Desktop Windows 10 x64 - `1.20.97`

**Comment by bsclifton** [comment] 2021-02-08 20:27
The timestamps are when the upload happens. For some values, it seems to be instantly. For others (maybe when it already has a value), the entire period (ex: week) may need to elapse before it's sent (and then timestamp gets updated).

I believe this is expected behavior and we can close; following up on Slack via https://bravesoftware.slack.com/archives/CDNJ9SVUL/p1612813551092200?thread_ts=1612368782.066900&cid=CDNJ9SVUL

**Comment by iefremov** [comment] 2021-02-24 11:10
@GeetaSarvadnya do we have any new input for this issue?

**Comment by GeetaSarvadnya** [comment] 2021-04-26 08:50
@iefremov Apologies for the delay in response.

As @bsclifton mentioned, the TS changes instantly for few metrics, but for few metrics, the TS doesn't change even after the response value change. I have tested both `1.1.18` and the current RC `1.23.x` the behavior is same since P3A is implemented https://github.com/brave/brave-browser/issues/6285 . 

The question here is the flag changes from `false` to `true` even when the TS remained unchanged. For e.g In the below case, when Google SE is set the response value is `1`, and TS changes and flag value from `false` to `true` which is correct and expected. When SE is set to DDG, the response value changed from `1` to `2` which is expected, but the TS remained the same and the flag is `true` which is creating confusion when the flag is `true` the response value is sent to the server and upload TS is captured, but in this case for DDG, although the flag value is `true` the TS is not updated. The TS is updated for the 1st Response value, but for the subsequent response values the TS is not updated even though the flag is `true`. 

**TS when Google SE is set:**
```
"Brave.Search.DefaultEngine.4": {
            "sent": true,
            "timestamp": 1612330881.376311,
            "value": "1"
```
**TS when DDG SE is set**

```
"Brave.Search.DefaultEngine.4": {
            "sent": true,
            "timestamp": 1612330881.376311,
            "value": "2"
         },
```

**Comment by iefremov** [comment] 2021-04-26 10:35
@GeetaSarvadnya thanks for checking this - I think that this behavior is totally expected, because TS update is bound to the upload schedule and not to the value change. So it is updated every time we upload the metric

**Comment by GeetaSarvadnya** [comment] 2021-04-26 11:18
Based on https://github.com/brave/brave-browser/issues/13927#issuecomment-775429548 and https://github.com/brave/brave-browser/issues/13927#issuecomment-826722994 closing the issue as expected.

**Closed by GeetaSarvadnya** 2021-04-26 11:18 UTC
Labels: OS/Android, OS/Desktop, QA/Yes, bug, features/P3A, priority/P3, release-notes/exclude
