### ISSUE TITLE
Broken image in rewards panel

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2259] opened 2018-11-27 21:50 UTC
## Steps to Reproduce

1. Clean install
2. Enable rewards through rewards panel

## Actual result:

- Token grant image is broken
- ~weird text: `MISSING: noActivity`~
- ~rewards height is too big~
![image](https://user-images.githubusercontent.com/34715963/49113161-17e91400-f295-11e8-9ca6-f891dc3b43b5.png)

## Expected result:
Rewards panel in Beta 0.57.7 
![image](https://user-images.githubusercontent.com/34715963/49113277-6e565280-f295-11e8-8e52-bb1594108b42.png)

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.58.10 Chromium: 71.0.3578.53 (Official Build) dev (32-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Windows 7

Reproduced on MacOS, Brave 0.58.10 by @LaurenWags 

### Reproducible on current release:
Does not reproduce on Release(0.56.15) nor Beta(0.57.7) Channels

Not reproducible on 

Brave | 0.58.9 Chromium: 71.0.3578.53 (Official Build) dev (64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Windows

This is a recent regression

cc @kjozwiak @srirambv @GeetaSarvadnya @NejcZdovc @ryanml @emerick

**Comment by ryanml** [comment] 2018-11-27 22:00
@btlechowski the first two problem (missing image and string) will for sure be fixed.

As for the new panel height, this was a design update made by @jenn-rhim in myself so there is not a flickering of height as you move between the panel and summary.

**Comment by kjozwiak** [comment] 2018-11-27 22:07
> @btlechowski the first two problem (missing image and string) will for sure be fixed.

Thanks @ryanml, can we get this fixed in `dev` before `0.58.x` becomes `BETA` next week? Couldn't reproduce with the latest `beta` so definitely a new regression:

Brave | 0.57.7 Chromium: 71.0.3578.53 (Official Build) beta(64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X

**Comment by ryanml** [comment] 2018-11-27 22:08
@kjozwiak - definitely, I should be able to have this out EOD actually.

**Comment by petemill** [comment] 2018-11-27 22:42
This is two separate issues, we should split them up

**Comment by petemill** [comment] 2018-11-27 22:44
Issue for missing string - https://github.com/brave/brave-browser/issues/2261

**Closed** 2018-11-27 22:56 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/rewards, regression

**Comment by LaurenWags** [comment] 2018-11-28 16:59
@ryanml @jenn-rhim re: https://github.com/brave/brave-browser/issues/2259#issuecomment-442233715 and panel height, this is what you see when on a site. it looks odd to have the white space at the bottom. can this be adjusted? 
<img width="403" alt="screen shot 2018-11-28 at 11 55 19 am" src="https://user-images.githubusercontent.com/28145373/49168240-122b1700-f305-11e8-90c3-60bacb8511c8.png">

**Comment by ryanml** [comment] 2018-11-28 19:44
@laurenwags this will be fixed with: https://github.com/brave/brave-core/pull/957

**Comment by kjozwiak** [comment] 2018-11-28 20:31
Hope we can land this before `0.58.x` moves into `beta` or this will need to get uplifted 👍

**Comment by LaurenWags** [comment] 2018-11-28 20:53
awesome, thanks @ryanml 😄

**Comment by LaurenWags** [comment] 2018-12-10 23:19
Verified passed with

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

![screen shot 2018-12-10 at 6 18 16 pm](https://user-images.githubusercontent.com/28145373/49767827-17df1000-fca8-11e8-8040-ff26d88f7c35.png)
