### ISSUE TITLE
[Desktop] Save All Files button in webtorrents does nothing

### ISSUE THREAD

**Issue by seamus91g** [brave/brave-browser#11608] opened 2020-09-05 18:19 UTC
I'm on Windows with version V1.13.82.
When downloading a torrent in Brave, the 'Save All Files' option does nothing. 
The hyperlink links to nothing: 
<a href="#" class="inactive">Save All Files...</a>

## Steps to Reproduce
Download a torrent in brave. Click 'Save All Files' and watch as nothing happens. 

## Expected result:
Files to download. 

## Brave version (brave://version info)

V1.13.82

**Comment by diracdeltas** [comment] 2020-09-08 23:27
cc @feross @yrliou

**Comment by kjozwiak** [comment] 2020-10-16 18:35
Seems to be working on `macOS 10.15.6 x64` when clicking on `Save All Files` under https://webtorrent.io/torrents/big-buck-bunny.torrent using the following build:

```
Brave | 1.15.75 Chromium: 86.0.4240.99 (Official Build) (x86_64)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | macOS Version 10.15.7 (Build 19H2)
```

I tried the above on `Win 10 x64` and couldn't reproduce the issue either. However, I did notice that it takes a while to generate the `.zip` file after you've clicked `Save All Files`. It took macOS ~15 seconds to display the OS download modal as the file was ~260Mbs.

@seamus91g mind trying with the latest version? Were you downloading something large? Maybe it was taking a while to generate the `zip` file so it seems like it wasn't working. We could definitely do a better job adding some UI to let users know that the `zip` is being generated.

**Comment by seamus91g** [comment] 2020-10-16 18:47
I tried it just now on V1.15.75 and it worked. 
It's possible that it was just delayed by being a large file, I don't quite remember what the torrent was. The one I tried just now was very small and it worked instantly.

**Comment by kjozwiak** [comment] 2020-10-19 17:43
Awesome, thanks for checking @seamus91g. Much appreciated. I'll close this one off as `invalid` but I did create a follow up issue so we can add some type of UI/UX feedback when saving large files via https://github.com/brave/brave-browser/issues/12198. If you have any suggestions/comments, you can add them into that issue.

Thanks again for the report 👍

**Closed by kjozwiak** 2020-10-19 17:43 UTC
Labels: OS/Desktop, feature/webtorrent

**Comment by feross** [comment] 2020-10-21 20:24
Thanks @kjozwiak – agree that the UX for this could/should be better!

**Comment by krnl0138** [comment] 2023-10-27 11:01
Bump. It does nothing with 6.5Gb torrent of 160 small files. Don't know why, but I can only play and save them one by one, which isn't optimal. Had to seed it to myself into qbittorrent, but yeah.. not nice

**Comment by brmscheiner** [comment] 2024-08-21 07:45
This is happening for me too. Does nothing no matter how long I wait 
OSX Sonoma 14.4.1
Brave 1.65.133

**Comment by kjozwiak** [comment] 2024-09-03 19:19
> This is happening for me too. Does nothing no matter how long I wait OSX Sonoma 14.4.1 Brave 1.65.133

Should update Brave to the latest versions as `1.65.133` is pretty old. We're currently on `1.69.162 Chromium 128.0.6613.120`. We also bumped/upgraded `WebTorrent` to the latest version as per https://github.com/brave/brave-browser/issues/35385 via the initial `1.69.x` release. Can always see the latest version via https://github.com/brave/brave-browser/blob/master/CHANGELOG_DESKTOP.md.

**Comment by anees-kodappana** [comment] 2024-09-29 12:28
This is still not working, Brave Version `1.70.119 Chromium: 129.0.6668.70 (Official Build)  (arm64)`
