### ISSUE TITLE
Customize Dashboard - Layout Issue

### ISSUE THREAD

**Issue by phoogm** [brave/brave-browser#11480] opened 2020-08-27 17:22 UTC
## Description 
Customize Dashboard menu - Layout Issue

## Steps to Reproduce
   1. Click on the home button
   2. Click on the Customize option on the new tab page
   3. Observe the placements of the sliders relative to the scrollbar and the apparent red selection highlight

## Actual result:
![Brave Customize Issue](https://user-images.githubusercontent.com/56597375/91473766-9b37ff00-e899-11ea-9255-cb76615db080.png)

## Expected result:
Expect spacing between the right end of the sliders and the scrollbar
Expect scrollbar to only show when the actual content exceeds the window size
Not sure of this red selection highlight is intentional design, one could assume it could be removed without any functionality impacted.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
macOS Version 10.15.6 (Build 19G2021)

## Version/Channel Information:
Current production version

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields?  N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Thanks for looking into, best regards.

**Comment by thefallofbecause** [comment] 2020-08-27 20:07
For the sake of debugging help, I'm running 1.13.82 on macOS 10.14.6 and do not see the scrollbar, so it could be something specific to Mojave.

As for the red selection box, that is for accessibility purposes to indicate focus on selection or keyboard navigation.

**Comment by srirambv** [comment] 2020-08-28 05:04
Dupe of #11374 

@thefallofbecause is correct on the focus selection. That is for keyboard accessibility.

**Closed by srirambv** 2020-08-28 05:04 UTC
Labels: OS/Desktop
