### ISSUE TITLE
For media publishers, (youtube, twitch), sometimes publisher panel will switch back to site name rather than publisher name

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#3043] opened 2019-01-22 14:34 UTC
## Description 

When opening panel on twitch or youtube publisher video, panel will switch back to youtube.com or twitch.tv instead of publisher. 

Intermittent if panel is opened before page finishes loading.

## Steps to Reproduce

STR from @LaurenWags originally added under https://github.com/brave/brave-browser/issues/3043#issuecomment-460784873:

1. Clean install of 0.60.19
2. Enable Rewards
3. Navigate to youtube.com
4. Click on a video (I experienced this on every video I tried)
5. Once video starts playing click on BAT icon - it says creator info
6. Click elsewhere, panel closes.
7. Repeat steps 5 and 6 a few times and when you open the panel on the 3rd or so try, you'll see the creator info change to youtube.com. Doesn't matter if the creator is verified or not.

**Comment by LaurenWags** [comment] 2019-02-05 20:09
I can reproduce this really easily on 0.60.19. Steps:

**Comment by LaurenWags** [comment] 2019-02-05 20:13
Same steps from https://github.com/brave/brave-browser/issues/3043#issuecomment-460784873 on released version 0.59.35 do not produce this issue.

**Comment by kjozwiak** [comment] 2019-02-05 20:44
Reproduced using @LaurenWags STR on `Win 10 x64` using the following build:

Brave | 0.60.19 Chromium: 72.0.3626.81 (Official Build) beta(64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Windows

Example:

![rewardsissue](https://user-images.githubusercontent.com/2602313/52302960-adbbb200-295c-11e9-9e0f-51180e4d9c56.jpg)

Added the STR that @LaurenWags mentioned into the original comment.

**Comment by kjozwiak** [comment] 2019-02-05 20:53
@rebron @bbondy QA believes this should be uplifted into `0.60.x` when fixed. Fixing this will make tipping more reliable. It's pretty bad as you'll eventually see "YouTube" listed instead of the actual publisher.

**Comment by NejcZdovc** [comment] 2019-02-06 07:45
@kjozwiak @LaurenWags can you reproduce this one on the latest 0.61?

**Comment by NejcZdovc** [comment] 2019-02-06 07:46
I found one case (you need old profile), but can't reproduce it with a clean profile on the latest master

**Comment by NejcZdovc** [comment] 2019-02-06 08:09
created new issue for case that I found https://github.com/brave/brave-browser/issues/3244

**Comment by NejcZdovc** [comment] 2019-02-06 15:03
@LaurenWags that was my fear. I think a lot was fixed with this one https://github.com/brave/brave-core/pull/1457 which is publisher update refactor. cc @kjozwiak @rebron for what to do?

**Comment by kjozwiak** [comment] 2019-02-12 00:01
As discussed during our weekly BR/Ads meeting, @NejcZdovc is going to see if it's possible to resolve this issue with an alternative fix rather than pulling in https://github.com/brave/brave-core/pull/1457 which is a large change. If the alternative fix doesn't work, we'll need to have a discussion about potentially uplifting https://github.com/brave/brave-core/pull/1457  or leaving the issue in `0.60.x` and getting this fixed in `0.61.x`. However, this is pretty bad and we should have this fixed in `0.60.x`. CCing @rebron @bbondy

**Comment by NejcZdovc** [comment] 2019-02-12 10:15
setting milestone to 0.61 as it looks like it was fixed in that milestone

**Closed by NejcZdovc** 2019-02-12 10:15 UTC
Labels: QA/Yes, feature/rewards, priority/P2, regression

**Comment by btlechowski** [comment] 2019-02-19 17:51
Verification passed on 

Brave | 0.60.40 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows 7

Used STR from the description. 
youtube works great. The publisher name is always updated, even when autoplay opens a video from other publisher.
For twitch, logged: https://github.com/brave/brave-browser/issues/3417
