### ISSUE TITLE
Unable to backspace/erase text in address bar after minimizing - Brave Developer build v0.60.5 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#2775] opened 2019-01-01 18:04 UTC
## Description 
Brave dev build has an issue with address bar input after being restored from minimized state. When restored, the window displays and the focus is on the address bar (as intended), but anything typed here cannot be erased (that is, pressing backspace does not do anything). 

## Steps to Reproduce

1. Open a new tab and click in the address bar.
2. Minimize Brave.
3. Restore Brave again and verify that the cursor is still in the address bar.
4. Type the beginning of a URL and verify that it works.
5. Try to erase characters by using Backspace. This does not work. Alt/D selects the address bar content but the control characters are still non-functional

## Actual result:

Characters in address bar are not deleted when backspace is hit.

## Expected result:
Characters to be deleted as normal.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

v0.60.5 Chromium: 72.0.3626.28 (Official Build) dev (64-bit)

### Reproducible on current release: No
- Does it reproduce on brave-browser dev/beta builds? Yes

### Additional Information
Original report from Community user:
https://community.brave.com/t/address-bar-focus-problem/41298

**Comment by rebron** [comment] 2019-01-08 20:14
@Brave-Matt can't reproduce between myself and QA, is this still reproducible? post a .gif/video?

**Comment by fallaciousreasoning** [comment] 2023-05-17 03:00
I can't repro either, so I'm going to close this (I've been looking at the [feature/keyboard-shortcuts](https://github.com/brave/brave-browser/labels/feature%2Fkeyboard-shortcuts) label, sorry to necro)

**Closed by fallaciousreasoning** 2023-05-17 03:00 UTC
Labels: needs-investigation, feature/keyboard-shortcuts
