### ISSUE TITLE
Unable to preview Brave in Windows task bar

### ISSUE THREAD

**Issue by mtcdood** [brave/brave-browser#5270] opened 2019-07-17 13:39 UTC
## Description 
Brave is white when covered by another window.

## Steps to Reproduce
   1. Open a page in Brave
   2. Place a maximized window over Brave
   3. Try to view the preview of Brave in the task bar

## Actual result:
The DOM render window appears as white box

## Expected result:
The DOM render window appears as the page

## Reproduces how often: 
Always

## Brave version (brave://version info)
0.66.99 Chromium: 75.0.3770.100

## Version/Channel Information:
- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Untested
- Can you reproduce this issue with the dev channel?
Untest
- Can you reproduce this issue with the nightly channel?
Untested

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome?
No

## Miscellaneous Information:
Disabling #omnibox-ui-white-background-on-blur is supposedly able to fix it but doesn't.

**Comment by bsclifton** [comment] 2019-07-18 17:59
Thanks for the report, @mtcdood! Closing as a dupe of https://github.com/brave/brave-browser/issues/4795

Will give it a +1 on your behalf

**Closed by bsclifton** 2019-07-18 17:59 UTC
