### ISSUE TITLE
crash reports contain guid and env

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#8865] opened 2020-03-25 21:48 UTC
## Description 
Crash reports contain a guid and env info

## Steps to Reproduce

   1.  go to `brave://crash`
   2. go to `brave://crashes` and ensure the crash has been sent
   3. lookup the crash id on backtrace

## Actual result:
unique guid is present
env vars are also stripped by backtrace so this can't be verified directly through the UI, but we are definitely sending them

## Expected result:
guid should be 0 or not present

## Reproduces how often: 
always

## Brave version (brave://version info)

- Can you reproduce this issue with the current release?
yes
- Can you reproduce this issue with the beta channel?
yes
- Can you reproduce this issue with the dev channel?
yes
- Can you reproduce this issue with the nightly channel?
yes

**Comment by bsclifton** [comment] 2020-05-17 21:18
Looks like this was never tested @bridiver because the milestone is missing. This was merged into 1.8 - did you want to give things a look in Backtrace?

I'll go ahead and posthumously assign the 1.8 milestone to this and remove `QA/Yes`

**Comment by bsclifton** [comment] 2020-05-18 21:21
Found this was not working as expected during troubleshooting session with @NejcZdovc 

@bridiver suggested a patch which I just verified

**Closed** 2020-05-18 23:14 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, privacy, release-notes/include

**Comment by kjozwiak** [comment] 2020-06-16 03:59
Verification **PASSED** on `macOS 10.15.5 x64` using the following build:

```
Brave | 1.11.64 Chromium: 83.0.4103.97 (Official Build) dev (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | macOS Version 10.15.5 (Build 19F101)
```

Reproduced the original issue using `1.10.90 CR: 83.0.4103.97` by crashing via Brave using `brave://crash` and `brave://gpucrashes`. Checked BackTrace the above crashes were displaying the `guid`

* ensured that we're blanking out the `guid` now that the above fix has landed
* ensured that it's not appearing in BackTrace when looking up the `Uploaded Crash Report ID`

Examples:

**Being sent via `1.10.90 CR: 83.0.4103.97`**

<img width="1415" alt="Screen Shot 2020-06-15 at 11 57 03 PM" src="https://user-images.githubusercontent.com/2602313/84730414-19a42680-af64-11ea-8280-68781fbb0ed0.png">

**Not being sent via `1.10.90 CR: 83.0.4103.97`**

<img width="1476" alt="Screen Shot 2020-06-15 at 11 53 10 PM" src="https://user-images.githubusercontent.com/2602313/84730484-43f5e400-af64-11ea-952c-3c31131e11ce.png">

**Comment by kjozwiak** [comment] 2020-06-16 04:01
@bsclifton @bridiver is there a way to see if the `env` is being sent? I couldn't see `evn` in the URL or the `Summary` under Charles Proxy when sending the into to `https://cr.brave.com`. Is the above good enough for a verification?

**Comment by bsclifton** [comment] 2020-06-16 05:52
@kjozwiak yup- above looks perfect! 😄 👌  I don't think `env` will show unless it's set. So this is great
