### ISSUE TITLE
Can't disable "allow all trackers and ads" in shield settings - puppeter

### ISSUE THREAD

**Issue by G4tes** [brave/brave-browser#35022] opened 2023-12-22 06:24 UTC
I using brave in Puppeter and I want to automatically disable 'Trackers & ads blocking' when the browser is opened for the first time, but I don't know which flags I should use.

I found this article, but it didn't help me : 
https://support.brave.com/hc/en-us/articles/360044860011-How-Do-I-Use-Command-Line-Flags-in-Brave-

Hopefully, you guys can help me

![image](https://github.com/brave/brave-browser/assets/50048258/b344c796-5fc6-4b71-9339-a742eca5f6e2)

**Comment by rebron** [comment] 2023-12-27 20:45
cc: @ShivanKaul @Brave-Matt

**Comment by ShivanKaul** [comment] 2024-01-03 23:49
Dupe of https://github.com/brave/brave-browser/issues/3076

Sounds useful. We should update https://github.com/brave/brave-browser/wiki/Custom-Brave-switches with the new switches if/when we have them.

**Closed by ShivanKaul** 2024-01-03 23:49 UTC
Labels: question, priority/P5, OS/Desktop
