### ISSUE TITLE
"Provide additional details" link in brave://crashes points to https://bugs.chromium.org/

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#4652] opened 2019-05-30 17:18 UTC
## Description

`Provide additional details` link found in `brave://crashes` points to a [https://bugs.chromium.com/](https://bugs.chromium.org/p/chromium/issues/entry?template=Crash%20Report&comment=IMPORTANT%3A%20Your%20crash%20has%20already%20been%20automatically%20reported%20to%20our%20crash%20system.%20Please%20file%20this%20bug%20only%20if%20you%20can%20provide%20more%20information%20about%20it.%0A%0A%0AChrome%20Version%3A%2075.0.67.70%0AOperating%20System%3A%20Mac%20OS%20X%2010.14.5%0A%0AURL%20(if%20applicable)%20where%20crash%20occurred%3A%0A%0ACan%20you%20reproduce%20this%20crash%3F%0A%0AWhat%20steps%20will%20reproduce%20this%20crash%3F%20(If%20it%27s%20not%20reproducible%2C%20what%20were%20you%20doing%20just%20before%20the%20crash%3F)%0A1.%0A2.%0A3.%0A%0A****DO%20NOT%20CHANGE%20BELOW%20THIS%20LINE****%0ACrash%20ID%3A%20crash%2Fb9efe191221f441f&labels=Restrict-View-EditIssue%2CStability-Crash%2CUser-Submitted) page.
![image](https://user-images.githubusercontent.com/3299098/58650073-99604400-82c2-11e9-8d51-08ff575f915e.png)

This should probably point to Community if the ideas is to have users submit further information surrounding their crashes. 

## Reproduces how often: 

Always

## Brave version (brave://version info)

- Version 0.67.69 Chromium: 75.0.3770.38 (Official Build) nightly (64-bit)
- Version 0.65.112 Chromium: 75.0.3770.38 (Official Build) beta (64-bit)
- Version 0.67.70 Chromium: 75.0.3770.38 (Official Build) dev (64-bit)
- Version 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? ✅  
- Can you reproduce this issue with the beta channel? ✅
- Can you reproduce this issue with the dev channel? ✅
- Can you reproduce this issue with the nightly channel? ✅

**Comment by srirambv** [comment] 2019-05-30 17:29
Dupe of #889

**Closed by srirambv** 2019-05-30 17:29 UTC
Labels: about-pages/rebrand, feature/user-interface
