### ISSUE TITLE
Approve ERC20 tokens show 0 amount value on transaction confirmation screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30299] opened 2023-05-12 09:39 UTC
## Description 
Approve ERC20 tokens show 0 amount value on transaction confirmation screen

## Steps to reproduce 

   1. Select an ERC20 token to swap
   2. Select Approve token
   3. Transaction confirmation shows 0 even though you have input a value for the token swap

## Actual result 

https://github.com/brave/brave-browser/assets/17010094/d0211344-252d-4561-8d4b-8e1602f18cd5

## Expected result
Show the actual input value for approval

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
1.52.92

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @onyb @Pavneet-Sing

**Comment by Pavneet-Sing** [comment] 2023-06-02 10:29
Not able to reproduce this on any GPS version or master. (Will close this once confirmed)
[Discussion thread](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1683803169104129)
[swap-tx-issue.webm](https://github.com/brave/brave-browser/assets/11755381/4ae11912-7395-4a8d-94cb-54302e41355e)

**Comment by HEagle18** [comment] 2023-06-02 16:23
@srirambv to check if this can be closed.

**Closed** 2023-06-06 08:00 UTC
Labels: bug, priority/P3, QA/Yes, release-notes/include, feature/web3/wallet, OS/Android
