### ISSUE TITLE
Wallet creation failed Please check your Internet connection.

### ISSUE THREAD

**Issue by litux** [brave/brave-browser#3441] opened 2019-02-21 17:50 UTC
Using the latest version of Brave `Version 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)` MacOS 10.13.6

Clicking the Brave icon, wallet amount = 0.0 clicking either "Add funds" or "Reward Settings" gives the same error:

`Wallet creation failed
Please check your Internet connection.`

My internet connection is fine, using Github ... . Never used the wallet reward function before. So earn a reward does not work..

## Description 

Wallet creation failed Please check your Internet connection.

## Steps to Reproduce

   1. Clicking the Brave icon, wallet amount = 0.0
   2. clicking either "Add funds" or "Reward Settings"
   3. 

## Expected result:

The possibility to either add funds or to be able to change the wallet settings

## Reproduces how often: 

Always

## Brave version (brave://version info)

Version 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 
No and Yes

### Additional Information

MacOS 10.13.6

**Comment by NejcZdovc** [comment] 2019-03-05 08:10
closing as dupe of https://github.com/brave/brave-browser/issues/3396. Will fix this asap

**Closed by NejcZdovc** 2019-03-05 08:10 UTC
Labels: feature/rewards

**Comment by touchy-feely** [comment] 2020-04-28 05:03
I just got this error message when I tried installing Brave wallet on my new (old) Mac.
OSX version: 10.11.6 (15G22010) 
Wallet creation failed Please check your Internet connection.
My internet connection is good. I'm writing this is Brave.
Thanks
Dan
