### ISSUE TITLE
[Desktop] Home page clock format

### ISSUE THREAD

**Issue by rickgao12** [brave/brave-browser#11102] opened 2020-08-06 04:30 UTC
## Description 

Allow the clock on the home page to sync to the date format of your computer or maybe allow different types of clocks.
I'm used to the military time, for example 11:30PM would be 23:30. Or maybe add AM/PM on clocks for more clarity

## Steps to Reproduce

   1. Open new tab 
   2. Customize
   3. Show clock 

## Expected result:
Able to change clock format on home page.

## Reproduces how often: 
Easily reproduced

**Comment by srirambv** [comment] 2020-08-06 10:51
What OS is this? Should be fixed as part of CR74 update Should have been fixed as part of https://github.com/brave/brave-browser/issues/2439. Can you please mention OS details and locale you are using?

**Comment by rickgao12** [comment] 2020-08-06 14:19
I'm using Windows 10 Home, and my OS build is 17134.1304 (don't know if that helps). It also says im up to date on windows

**Comment by rebron** [comment] 2020-08-08 00:45
Closing as dupe of #7951

**Closed by rebron** 2020-08-08 00:45 UTC
Labels: duplicate
