### ISSUE TITLE
Unable to send a tip due to `Wallet creation failed` message in BR panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3403] opened 2019-02-18 11:29 UTC
## Description 

Issue is reported by community user. 
https://community.brave.com/t/wallet-creation-failed/45342

When user enabled the rewards on older version and upgraded the profile to latest version, they are getting `wallet creation failed` message in the BR panel for all the sites. Due to which they are unable to send a tip to any pubs, even though wallet is created.

## Steps to Reproduce ( Steps may not be reliable - I personally did not reproduce the issue with below STR)

   1. Enable rewards in older version
   2. Upgrade the profile to 0.60.23
   3. Accept the UGP grants.
   4. Make sure Rewards is enabled and wallet balance shows up the UGP claimed grants
   5. Open few publishers ( verified or non verified)
   6. Click on BR Panel for any site
   7. Wallet creation failed message is displayed

## Actual result:

Unable to send tip due to `Wallet creation failed` message in BR panel for all the pubs

![5ed73c1f05c5d43241800fe6deb44bd3ff2fd9d3](https://user-images.githubusercontent.com/38657976/52947609-3a269580-339d-11e9-8585-6ef4c191d2c9.png)
![54c2b86c5164ccfda3d1d95d9304ec54ec196b5b](https://user-images.githubusercontent.com/38657976/52947615-3eeb4980-339d-11e9-97ef-2cc13a628bba.png)

## Expected result:
Should not get wallet creation failed message, should be able to send a tip 

## Reproduces how often: 

Not sure as it's reported by user

## Brave version (brave://version info)

Brave | 0.60.23 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 10

### Reproducible on current release: not sure
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

Reported by community

https://community.brave.com/t/wallet-creation-failed/45342

**Comment by Liunkae** [comment] 2019-02-19 14:05
Related: #2649, #3046, #3396

**Comment by NejcZdovc** [comment] 2019-03-05 14:55
closing as dupe of https://github.com/brave/brave-browser/issues/2997

**Closed by NejcZdovc** 2019-03-05 14:55 UTC
Labels: QA/Yes, feature/rewards, needs-investigation
