### ISSUE TITLE
Broken UI for Profile Manager

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#37027] opened 2024-03-22 20:02 UTC
## Description 

Profile Manager on latest Nightly seems broken, the text and image is askance. 

## Steps to Reproduce

   1. Go to "manage Profiles" (on Mac, click "cmd + shift + m" and press the gear)
   2. See screenshot

## Actual result:

<img width="1028" alt="image" src="https://github.com/brave/brave-browser/assets/5284154/d8eb0c5b-9c49-4262-a001-75188b37472b">

## Expected result:
<img width="1023" alt="image" src="https://github.com/brave/brave-browser/assets/5284154/6a1f3d19-113c-4b25-82cb-8f255ade1802">

## Reproduces how often: 

Always on Nightly, but not on Release/Beta

## Brave version (brave://version info)

1.66.26 Chromium: 123.0.6312.58 (Official Build) nightly (arm64) 
Desktop macOS

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

**Comment by rebron** [comment] 2024-04-08 16:56
closing as dupe of https://github.com/brave/brave-browser/issues/36975

**Closed by rebron** 2024-04-08 16:56 UTC
Labels: closed/duplicate
