### ISSUE TITLE
add 2fa to sync

### ISSUE THREAD

**Issue by 424344** [brave/brave-browser#24657] opened 2022-08-14 07:43 UTC
## Description 

I should be given the option to enable 2FA when creating a new sync chain, with qrcode or words code.
The 2FA should be compatible with existing apps, like Authy or Google Authenticator.
When adding a new device to existing sync chain I'll be asked to enter the 2FA code if I enabled it during sync chain creation.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by diracdeltas** [comment] 2022-08-15 06:57
cc @fmarier

**Comment by fmarier** [comment] 2022-08-15 18:55
This would make sense once/if we switch to an account-based system as described in #19949. It would prevent users from accessing their sync account without the right password/passphrase AND 2FA code.

Right now, both authentication and data encryption are using the key in the QR code and so we would need to move to an account-based model in order to be able to add a 2FA requirement.

I'm going to mark this as a duplicate of #19949.

**Closed by fmarier** 2022-08-15 18:55 UTC
Labels: OS/Android, OS/Desktop
