### ISSUE TITLE
Use brave:// schema on brave://about

### ISSUE THREAD

**Issue by bershanskiy** [brave/brave-browser#6438] opened 2019-10-11 16:21 UTC
## Description 

Page located at `chrome://chrome-urls/` or `brave://chrome-urls/` or `chrome://about/` and also accessible as `about://about` uses `chrome://` in the links. Instead, all links should use `brave://` to match the style.

This list is generated in the following two files:
https://github.com/chromium/chromium/blob/master/chrome/browser/ui/webui/about_ui.cc
https://github.com/chromium/chromium/blob/master/ios/chrome/browser/ui/webui/about_ui.cc

## Steps to Reproduce

   1. Open `chrome://chrome-urls/`
   2. See links starting with `chrome://`, e.g. `chrome://about`

## Actual result:

Links starting with `chrome://`, e.g. `chrome://about`.

## Expected result:
Links should start with `brave://`.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Brave	0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
Revision	58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS	Linux
JavaScript	V8 7.7.299.11
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Command Line	/usr/bin/brave-browser-stable --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-features=NewExtensionUpdaterService,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AudioServiceOutOfProcess,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path	/opt/brave.com/brave/brave-browser
Profile Path	/home/anton/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Did not try.
- Can you reproduce this issue with the dev channel? Did not try.
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

**Comment by srirambv** [comment] 2019-10-11 16:27
Dupe of #5775

**Closed by srirambv** 2019-10-11 16:27 UTC
