### ISSUE TITLE
Widevine support for Linux

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#413] opened 2018-06-22 21:28 UTC
STR in linux
1. Start browser with clean profile
2. Load https://bitmovin.com/demos/drm
3. Check No drm
4. Install widevine via content settings bubble
5. Check widevine is enabled
6. Restart browser and check widevine is enabled

**Comment by manoynmonic** [comment] 2018-10-26 01:50
Would love to see widevine support for Brave in Linux.

**Comment by ankur-gupta** [comment] 2018-11-05 19:13
I would love to get Widevine support on linux as well. As of Nov 5, 2018, I cannot watch Netflix, Amazon prime, or purchased Youtube videos on brave (`Version 0.55.22 Chromium: 70.0.3538.77 (Official Build) 64-bit)`) on Ubuntu (`17.10`). 

When I opened Netflix, I saw the little icon in the URL bar which asked for Widevine Cdm to be installed. I clicked on the install link and nothing happened. The icon in the URL went away but it doesn't look like Widevine Cdm was installed because (1) I still cannot watch Netflix, Amazon Prime video, or purchased Youtube videos and (2) `brave://components` doesn't show Widevine. 

As a control, I performed the exact same steps on MacOS Mojave and Widevine was indeed installed and I was able to watch Netflix, Amazon, and purchased Youtube. So, it looks like Widevine installation didn't work in Ubuntu. Is there any way for me to retrigger the Widevine installation?

**Comment by rsteppleton** [comment] 2018-11-06 20:40
Is there at least some kind of workaround?

**Comment by ayeganov** [comment] 2018-11-14 13:38
An update on this would be very appreciated.

**Comment by Brave-Matt** [comment] 2018-12-05 22:07
+1/many from Reddit. https://www.reddit.com/r/brave_browser/comments/a3a982/widevine_support_for_linux/

**Support team 2 cents:** While I'm very aware of the workload/time constraints we're currently under, I think this particular issue necessitates a priority reevaluation. Users frequently ask about this - both requesting the feature be implemented or an update on it's progress - and haven't been given any information surrounding it. 
cc @rebron for any updates/info on this issue.

**Comment by rebron** [comment] 2018-12-06 00:51
Don't have any new updates to share. We definitely acknowledge the feature request, others on the team have seen it as well. We see the number of requests for it. We don't have plans right now to get to this issue in the near term weighted against other feature requests. 

The more feedback we get from more people, we'll of course re-evaluate.

**Comment by srirambv** [comment] 2018-12-06 03:08
Agree on prioritising it to p4 at least. There has been a significant increase in Linux userbase now for bc. We need to get Linux up to speed similar to Windows/Mac

**Comment by arooni** [comment] 2018-12-15 02:40
Following this b/c on Ubuntu no widevine makes me just want to use chrome instead.  Want to keep being brave using Brave.

**Comment by mausworks** [comment] 2018-12-17 16:41
On *Chromium* (on Arch Linux) there is the [`chromium-widewine` package in the AUR](https://aur.archlinux.org/packages/chromium-widevine/), which has to be installed separately from Chromium. 

Now: I'm not a Chromium (nor Brave) developer; but shouldn't the functionality be here very similar?

**Comment by srirambv** [comment] 2019-01-02 11:16
>We're Linux people, we don't need fancy clickers, guides and wizards like mac or windows people. We'd be happy with a simple separate package, much like what Arch does with Chromium. At least for now.

>Seriously, not even a workaround? Man... 

You can't just copy/paste and make it wok. There's a lot of work required for it make it work. I agree its frustrating but the issue is already marked as P3 so its already climbed the priority scale. Just a matter of time that it lands on Linux. 

Regarding the Arch repo package, I am not sure if that is a Chromium maintained package or a user maintained. But from the looks of it on package comment there is only people complaining it not working so you can understand the complexity involved in getting it done on Linux.

**Comment by cptMikky** [comment] 2019-01-02 11:23
Well, from a simple user perspective, the Arch package does nothing more than copying a single file to Chromium's lib directory. Same thing apparently worked for Vivaldi - another chromium-based browser.

And that's it. That's all the complexity involved in getting Widevine working in Chromium/Linux.

**Comment by ADmad** [comment] 2019-01-02 14:38
> Same thing apparently worked for Vivaldi - another chromium-based browser.

As of [Vivaldi 2.2](https://vivaldi.com/blog/vivaldi-update-focus-on-details/) you don't even need to copy it manually, Widevine is automatically installed.

**Comment by OLucasZanella** [comment] 2019-01-02 23:11
> [..] the issue is already marked as P3 so its already climbed the priority scale. Just a matter of time that it lands on Linux.

I've found posts about this problem from years ago. I guess I won't hold my breath.

**Comment by jonathansampson** [comment] 2019-01-06 20:32
+1 from a user on Twitter.

**Comment by Brave-Matt** [comment] 2019-01-09 21:30
Several +1's from Reddit, again:
https://www.reddit.com/r/brave_browser/comments/ae0t7i/anyone_can_help_me/

**Comment by Brave-Matt** [comment] 2019-01-17 21:34
+1 from Twitter:
![image](https://user-images.githubusercontent.com/3299098/51350291-accde980-1a5c-11e9-8f18-e292f8b3bb0d.png)

**Comment by eljuno** [comment] 2019-01-28 20:18
+1 from Community https://community.brave.com/t/widevinecdm-and-netflix/43602?u=eljuno

**Comment by bbondy** [comment] 2019-01-28 23:46
@simonhong is working on this.

**Comment by Soffioo** [comment] 2019-02-05 14:36
News from developers about Widevine for Brave on Linux?

**Closed** 2019-02-14 04:51 UTC
Labels: OS/Linux, QA/Test-Plan-Specified, QA/Yes, plugin/Widevine, priority/P3

**Comment by sk8darr** [comment] 2019-02-15 17:03
So.. Closed and when this will be released for final users?

**Comment by StarFscker** [comment] 2019-02-28 01:37
Netflix is responsible for roughly a third of all internet traffic. 

There's no reason that this shouldn't be the highest priority issue.

**Comment by aduh95** [comment] 2019-02-28 03:10
@StarFscker it is already working on Brave 62, you can install it already, instructions are here: https://brave-browser.readthedocs.io/en/latest/installing-brave.html#development-channel-installation

**Comment by bsclifton** [comment] 2019-02-28 07:57
Thanks for the feedback, @StarFscker - as mentioned above, you can try the Dev channel

Stay tuned as this patch flows to Beta (March 12th) and then Release (~April 2nd).  Our release schedule can be found here:
https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#release-channel-dates

**Comment by StarFscker** [comment] 2019-03-02 05:19
Thank you for the update.

**Comment by srirambv** [comment] 2019-03-19 19:04
Verification passed on 

Brave | 0.62.32 Chromium: 73.0.3683.75 (Official Build) beta(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/54634260-36e3ff80-4a58-11e9-8dcd-9a6edf507a68.png)

**Comment by richardkentgates** [comment] 2019-03-23 11:53
I am still having this issue. No puzzle piece in the address bar, no settings for DRM or Widevine anywhere I can see. Widevine error, Netflix Error Code: M7701-1003.

Operating System: KDE neon 5.15
KDE Plasma Version: 5.15.3
KDE Frameworks Version: 5.56.0
Qt Version: 5.12.0
Kernel Version: 4.15.0-46-generic
OS Type: 64-bit
Processors: 2 × Pentium® Dual-Core CPU E5700 @ 3.00GHz
Memory: 3.7 GiB of RAM

**Comment by mkhamat** [comment] 2019-03-24 20:04
I thought Brave is ready to use finally, but stumbled upon another issue. Hope this one is the last, come on guys :+1:

**Comment by bsclifton** [comment] 2019-03-26 23:44
@richardkentgates what version of Brave? This is only on 0.62.x and newer (ex: our beta channel)

**Comment by richardkentgates** [comment] 2019-03-27 13:12
Ok. Oversight on my part. 0.60.48

**Comment by bsclifton** [comment] 2019-04-03 21:09
Quick heads up for folks watching this issue - this is now LIVE on our release channel! 🎉 

Please give it a download and report back your experience 😄 Things should be working great. There are some UI improvements we'd like to make, but we'll get there. 

For example, we want to make it more obvious when the Widevine component needs to be installed - this is captured with https://github.com/brave/brave-browser/issues/1940 and is also complete, but is on our Beta channel at the moment. Will be in our next planned release (0.63.x) for Release channel

**Comment by bsclifton** [comment] 2019-04-03 21:22
cc: @richardkentgates @mkhamat @Soffioo @sk8darr @StarFscker

**Comment by mkhamat** [comment] 2019-04-09 12:45
@bsclifton thigs works pretty well, thank you!

**Comment by bsclifton** [comment] 2019-04-09 18:02
Huge thanks to @simonhong for the work that resolved this issue 😄

**Comment by enchance** [comment] 2020-05-13 17:03
It's 2020 is there a fix for this already? Every time I try watching Netflix on Brave in Linux I get the M7701-1003 error which says in **bold letters** something about the "Widivine Content Decryption Module."

**Comment by the94air** [comment] 2020-05-13 17:49
This issue has been fixed long time ago. Make sure to update your browser @enchance.

**Comment by Stupendoussteve** [comment] 2020-05-13 18:25
brave://settings/extensions

Make sure Widevine is enabled.

**Comment by enchance** [comment] 2020-05-14 12:41
I don't know how I could have missed that. Thanks man.

**Comment by bspriester** [comment] 2022-04-19 01:12
I just reinstalled Brave Version 1.37.116 Chromium: 100.0.4896.127 (Official Build) (64-bit) on Ubuntu, and I show Widevine as enabled, but I still get a "Pardon the interruption...Error Code M7701-1003" when trying to watch a video on Netflix. Are there other factors I'm not taking into account for being able to stream videos in Brave on Ubuntu? Netflix works on both Firefox and Chrome on this machine. Thanks.

**Comment by simonhong** [comment] 2022-04-19 02:30
@bspriester Did you restart after enabling widevine?

**Comment by bspriester** [comment] 2022-04-19 19:15
@simonhong Yeah it's been enabled for multiple reboots.
