### ISSUE TITLE
Move regional filter lists to new category, append country flags

### ISSUE THREAD

**Issue by blox814123** [brave/brave-browser#41318] opened 2024-10-01 15:08 UTC
### Platforms

Linux, macOS, Windows

### Description

The filter lists are confusing, as they are all grouped together with no differentiation for users. I suggest looking at the way uBO does it. uBO groups regional lists into one category and adds a country flag to each list for better usability.

**Comment by rebron** [comment] 2024-10-04 18:30
cc: @ShivanKaul @antonok-edm

**Comment by ShivanKaul** [comment] 2024-10-17 22:10
This is a dupe of https://github.com/brave/brave-browser/issues/41233

**Closed by ShivanKaul** 2024-10-17 22:10 UTC
Labels: closed/duplicate, feature-request
