### ISSUE TITLE
Remove extra "chrome://rewards says" dialog boxes in Rewards reset flow 

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#31962] opened 2023-07-28 20:36 UTC
## Description 

`chrome://rewards says` message is shown when trying to reset Brave Rewards

## Steps to reproduce 

   1. Launch Brave
   2. Enable Rewards Staging server
   3. Enable Rewards > Connect Custodian
   4. When landed on `Brave Rewards` screen tap `Reset` in top right corner
   5. Select checkbox > Reset > Observe

## Actual result 

`chrome://rewards says` message is shown when trying to reset Brave Rewards

![Screen_13-35-15](https://github.com/brave/brave-browser/assets/128532965/e526c8a3-dcd6-411a-943b-5bdca8f38537)

## Expected result

`Chrome` must not be shown

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 7 [phone]
   - Android version: Android 14 [panther_beta-user 14 UPB4.230623.007 release-keys]
   
## Brave version

Brave build: 1.58.52 
Chromium: 116.0.5845.51 (Official Build) canary (64-bit) 
Revision: d5ec9991d084625358dae86ed02de8dc760d1985

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment] 2023-08-02 16:08
@deeppandya We should remove the dialog completely. The user already puts the checkbox before "Reset" button becomes pressable.

**Comment by GeetaSarvadnya** [comment] 2023-08-02 16:11
Reproduced on Windows 10 x64 - 1.57.32
![image](https://github.com/brave/brave-browser/assets/38657976/b21389c8-43f2-4431-b84a-1b345004571a)

**Comment by szilardszaloki** [comment] 2023-08-03 14:40
I think I've already fixed this globally on a branch that never got merged unfortunately. That's not the only place where we show `chrome://... says`, and IIRC, it's not even specific to Rewards.

**Comment by szilardszaloki** [comment] 2023-08-03 14:41
@Miyayes Would you want to keep the dialog if it showed `brave://rewards says`?

**Comment by emerick** [comment] 2023-08-03 14:44
@szilardszaloki He mentioned in yesterday's meeting that the dialog is redundant in this particular flow since a user already has to confirm the reset via the checkbox (though I'm personally open to either approach).

**Comment by szilardszaloki** [comment] 2023-08-03 14:55
@emerick Yeah, read that above, and that also makes sense, was just curious if otherwise we would've kept it. 🙂
Sync has that, too:
![image](https://github.com/brave/brave-browser/assets/5390451/73f86373-1932-4593-9cfd-4877ac062bfe)
And that'll be true for any JavaScript popup box (`alert()`, `confirm()`, `prompt()`). We should fix this globally.

**Comment by Miyayes** [comment] 2023-08-03 14:58
> @Miyayes Would you want to keep the dialog if it showed `brave://rewards says`?

I would still remove it and not keep it.

**Closed** 2023-08-03 17:53 UTC
Labels: bug, feature/rewards, priority/P3, QA/Yes, release-notes/exclude, OS/Android, OS/Desktop

**Comment by szilardszaloki** [comment] 2023-08-03 20:31
Globally changes `chrome://... says` to `brave://... says`: https://github.com/brave/brave-core/pull/19561
