### ISSUE TITLE
Sync all history, not just typed URLs in URL bar

### ISSUE THREAD

**Issue by urbenlegend** [brave/brave-browser#11820] opened 2020-09-23 16:17 UTC
## Description 
Currently Brave only syncs history for items that have been typed into the URL bar. This functionality is of limited use as most history is from clicking on links.

## Steps to Reproduce

   1. Open Brave on two devices
   2. Type a URL into one device.
   3. Notice that it gets synced to other devices.
   4. Click on any link.
   5. Notice that clicked links do not get synced to other devices

## Actual result:

Clicked links do not get synced to other devices, only ones typed into URL bar.

## Expected result:
All history gets synced.

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

Brave: 1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit)
Revision: ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS: Windows 10 OS Version 2004 (Build 19041.508)

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 2XL Phone
   - Android version: 1.14.83

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Not tested

**Comment by srirambv** [comment] 2020-09-23 16:45
Same as #11196. This feature was not implemented. Closing as dupe of #11196

**Closed by srirambv** 2020-09-23 16:45 UTC
Labels: OS/Android, OS/Desktop
