### ISSUE TITLE
Desktop push notifications don't work

### ISSUE THREAD

**Issue by corrideat** [brave/brave-browser#41930] opened 2024-10-28 17:52 UTC
### Description

Attempting to create a push notification subscription fails on desktop -- tested on macOS and Windows 10.

```
service-worker.js:49 Error creating subscription AbortError: Registration failed - push service error
setupPushSubscription @ service-worker.js:49
await in setupPushSubscription
handler @ service-worker.js:121
(anonymous) @ service-worker.js:124
service-worker.js:57 Uncaught (in promise) AbortError: Registration failed - push service error
```

This issue does _not_ seem to occur in Android, where push subscriptions appear to be successfully created.

NOTE: The official [push notification test](https://support.brave.com/hc/en-us/articles/360058972091-Push-Notification-Test) _does_ work, but, despite name including the word 'push', it doesn't really test _push_ notifications, only notifications. This can be corroborated by noticing that the button has an `onclick` handler set to `initializeNote`, which calls `showNotification()`, and that `showNotification` is defined as follows (i.e., there's no server-side push involved):

```
function showNotification() {
			var notification = new Notification('Test Notification', {
				body: 'Success! Notifications are working!'
			});
		}
```

### Steps to reproduce

1. Visit <https://simple-push-demo.vercel.app/>
2. Grant the notification permission
3. Enter some notification text and send it
4. Receive the notification

Alternatively,

1. Clone and start this app: <https://github.com/ApelegHQ/webpush-demo>
2. Grant the notification permission
3. Start receiving notifications

Both sequences of steps are working and tested successfully in Edge (Windows), Chrome (Windows), Firefox (macOS and Windows), Opera (Windows) and Safari (macOS).

### Actual result

Right after granting the notifications permission, it fails as the app attempts to create a push subscription. It seems like the following is failing:

```js
      await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: publicKey,
      })
```

### Expected result

A push subscription is created.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Version 1.71.118 Chromium: 130.0.6723.70 (Official Build) (arm64)

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by diracdeltas** [comment] 2024-10-28 18:33
dupe of https://github.com/brave/brave-browser/issues/2362; generally enabling "use google services for push" in brave://settings/?search=push fixes it.

**Comment by taoeffect** [comment] 2024-10-28 18:33
Seems like this might be related to #2362.

- Enabling "Use Google services for push notifications" in the Brave privacy settings seems to fix it: brave://settings/privacy
 
  ![Image](https://github.com/user-attachments/assets/c05d7ef3-aade-4f27-a9a8-1dc700a9f242)

- Shouldn't it be enabled by default then if this is the only way for Push Notifications to work? And shouldn't there be a warning when disabling it?

Note, enabling this setting results in an odd connection request over a non 443 port from Brave that seems unrelated to Push Notifications:

![Image](https://github.com/user-attachments/assets/7c628cbd-989e-4c26-b0e9-5d04a9de5f63)

**Closed by diracdeltas** 2024-10-28 18:33 UTC
Labels: OS/Desktop
