### ISSUE TITLE
Reddit media is being blocked by Brave Shields

### ISSUE THREAD

**Issue by mil1i** [brave/brave-browser#1999] opened 2018-11-05 23:03 UTC
## Description 

Reddit now hosts it's own videos/gifs instead of using imgur, etc. Using the current Brave Dev build, media that is hosted by Reddit will not play unless Shields are disabled for the site.

## Steps to Reproduce

   1. Visit www.reddit.com
   2. Locate a posted video hosted by reddit (https://www.reddit.com/r/Seattle/comments/9uhb5h/snoqualmie_falls_with_foliage_thanks_wa/)
   3. Video will not play while shields active.

## Actual result:

Even just disabling Ads and Trackers blocked does not alleviate the issue. You must fully disable shields on reddit.com in order for the media to play. The below is one of the items listed as blocked. Not sure if the one below is an add, there was another from redditstatic.com that ends in ads.js that gets blocked as well.

https://www.redditmedia.com/gtm/jail?id=GTM-5XVNS82

## Expected result:
Play media files posted on reddit.

## Reproduces how often: 

Every reddit hosted media item.

## Brave version (brave://version info)

Brave | 0.57.4 Chromium: 71.0.3578.31 (Official Build) dev (64-bit)
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Unsure.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  Yes
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by bsclifton** [comment] 2018-11-09 20:44
+1 from me

1. Visit https://www.reddit.com/r/HadToHurt/comments/9vbmyu/skier_hits_a_gate_and_definitely_need_a_hug/
2. Try to watch video
3. Nothing happens at all. Shields shows only Ads/Trackers being blocked
4. Put shields down (I don't want to do this)
5. Video now works fine

**Comment by Brave-Matt** [comment] 2018-12-05 00:35
+1 from many users (thread below). The thread itself is about imgur albums specifically, but I can confirm that any media uploaded to reddit will either not display or fail to upload all together. 

This includes uploading imgur albums (wont upload or can't view), regular images to posts (upload _does go through_, but image isn't displayed in the post itself, and embedded videos.
Reddit thread: https://www.reddit.com/r/brave_browser/comments/a2uw8t/imgur_albums_on_reddit_still_broken_on_brave/

Also worth noting that this issue seems a bit inconsistent - some users report the same as me (nothing really works), some say it works for imgur albums but not for inserting media, etc.

**Comment by thanuj10** [comment] 2018-12-11 05:35
+1 Here too. 
Confirmed this bug is reproducible on Version 0.59.2 Dev build.

**Comment by Brave-Matt** [comment] 2018-12-12 22:30
+1 from reddit:
https://www.reddit.com/r/brave_browser/comments/a4w2i5/help_brave_browser_wen_shield_is_on_videos_dont/

**Comment by kjozwiak** [comment] 2018-12-18 07:20
@rebron @bsclifton @bbondy we should fix this in `0.59.x`. Makes using reddit under Brave pretty frustrating when a lot of the media can't be played within the browser.

**Comment by iefremov** [comment] 2018-12-18 10:50
Looks like this is a dupe of https://github.com/brave/brave-browser/issues/2252
Reveting https://github.com/brave/brave-core/pull/754/files fixes it for me.

**Comment by TDeisinger** [comment] 2018-12-19 19:54
This issue still occurs on 60.3 Dev

**Comment by Brave-Matt** [comment] 2019-01-01 19:51
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/ab1wqg/unusual_brave_browser_behavior/

**Comment by iefremov** [comment] 2019-01-09 12:37
Should work now since #2252 is fixed.

**Closed by iefremov** 2019-01-09 12:37 UTC
Labels: feature/shields/webcompat, priority/P4

**Comment by eixan** [comment] 2019-01-13 00:38
webm's on reddit won't play when you press the play button on reddit's interface. 

Version 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)

**Comment by bergmul** [comment] 2021-05-06 14:46
+1 on 1.24.82.

![image](https://user-images.githubusercontent.com/31454439/117318339-9eed3e00-ae8a-11eb-95b7-73fd15687d28.png)
