### ISSUE TITLE
Crashing while trying to click either profile button or settings

### ISSUE THREAD

**Issue by ObviouslyGreen** [brave/brave-browser#40019] opened 2024-07-25 21:24 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.68.128 Chromium: 127.0.6533.73
Operating System: Windows NT 10.0.22631

URL (if applicable) where crash occurred:

Can you reproduce this crash?

Browser crashes while clicking either of these two buttons
![image](https://github.com/user-attachments/assets/0e474915-99ce-4e41-b804-00a102ab5588)

Brave also crashes while using the shortcut to see the profile menu (ctrl shift m). Settings works if visited directly via brave://settings

Browser also crashes if try to launch via a shortcut / profile directory parameter, while "Default" does not crash
`"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --profile-directory="Profile 1"`

Saw https://github.com/brave/brave-browser/issues/40005, but none of my profiles are using IDR_PROFILE_AVATAR_28 and visiting the icon directly works
![image](https://github.com/user-attachments/assets/d3d85124-105d-43e9-9d44-08b7fc3b913e)

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Haven't recreated / tested with a fresh install, but clicking settings or profile icon crashes the browser

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/34a50800-7e4f-570c-0000-000000000000

**Comment by bsclifton** [comment] 2024-07-26 04:54
Thanks for reporting - I believe this is the same underlying issue as https://github.com/brave/brave-browser/issues/40005

The visiting directly is a bit misleading - the problem comes when it tries to get the bitmap for use inside the window itself. I believe when you are pressing profile button, that's when it tries to make the call and crashes.

I'll close as a duplicate of https://github.com/brave/brave-browser/issues/40005 - we have a fix incoming. Stay tuned!

**Closed by bsclifton** 2024-07-26 04:54 UTC
Labels: crash
