### ISSUE TITLE
Uploading files to github does not work with the 0.57.18

### ISSUE THREAD

**Issue by sobolevn** [brave/brave-browser#2485] opened 2018-12-12 12:27 UTC
## Description 

Files can not be uploaded to github from brave. It does work from other browsers.

## Steps to Reproduce

   1. Install the correct brave version (0.57.18)
   2. Try to upload any file to github
   3. Face this error

## Actual result:

```
Access to XMLHttpRequest at 'https://github-production-user-asset-6210df.s3.amazonaws.com/' from origin 'https://github.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
content.bundle.js:1 .form-actions github.com
```

## Expected result:

I expect a file to be uploaded.

## Reproduces how often: 
 
This happens to both people I know who use `brave`.

## Brave version (brave://version info)

```

Brave | 0.57.18 Chromium: 71.0.3578.80 (Официальная сборка) (64 бит)
-- | --
Версия | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
ОС | Mac OS X
JavaScript | V8 7.1.302.28
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
Командная строка | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave,AutofillServerCommunication,UnifiedConsent --flag-switches-begin --flag-switches-end
Путь к исполняемому файлу | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Путь к профилю | /Users/sobolev/Library/Application Support/BraveSoftware/Brave-Browser/Default
Варианты | c134752e-f685ead32c707b42-dcf7018a411b6d4e-3f4a17dfb7d3b6c2-3f4a17dfd01ab0d3-755bc7553e006338-3f4a17df1a0d11d4-2f9febdfe202a358-3f4a17df66df3e9d-a85d0b2f2b6b7805-d13c2832ebeb14fc-3f4a17dfb7e2524c-3f4a17dfb3888d8d-afba0f916c18ba9d-3f4a17df8982496f-3f4a17df61832c80-3f4a17dfcc20827f-77c422c591560a-29acad49041608a-3f4a17df241fff6c-ddf208789853922b-3f4a17df125b7f68-3f4a17df9ca1387e-3f4a17df1c752ce9-1c752ce9776de70c-e0278d3ded9149a9-3f4a17df34d450b1-3f4a17df31362330-3f4a17dfc70841c8-a256700714bdbe54-e8c7a65b8ee5ed19-c3125ea274658432-fa79b94ced7ba060-3f4a17df121ae2bc-65969d679e201a2b-3f4a17df652e14d1-f4950e9927212adc-27212adc249dd49a-3f4a17df5274eb09-3f4a17dfceff87ec-3f4a17df44827ee5-3f4a17df332a4d9b-8e8e4a2b8f1e27f-3f4a17df345b5b61-3f4a17dfedbcf7c5-ddf1844d77bbdddc-3f4a17df5485fc4d-3f4a17df93731dca-3f4a17df9b4c4257-3f4a17df43f62d3b-3f4a17df4ae380f4-3f4a17df165e16d1-3f4a17df9e5c75f1-30e1b12b6fa07eb4-7282ca762981bcb4-3f4a17df5139837c-3f4a17df4934552d-3f4a17df7f8176d9-3f4a17df6c66bd8d-b204717823a898eb-fc93cf747a5ba892-3f4a17df4ea303a6-3f4a17dfb19465ab-b19465ab6e6e0c7e-3f17a7d895876445-2b71ffe4d92562a9-441539fdfc369826-3f4a17df2b33233e-881ca6c94da5ae82-3f4a17df56302f8c-2f882e7014c5a050-61ceed18cc54eb06-803f8fc4b2612322-8a9180b2ad6d27cc-3e870323df072bba-9a6c5085f56e0452-3f4a17df8576baf1-3f4a17df3038aa2e-3f4a17df51b9b54d-3f4a17df7345ea6-3f4a17df4bc337ce-f483b7fd9a2f4e5b-4bc735aeddf77e2c-63745fe11354da85-522c33b817507c76-3f4a17df494d8760-3f4a17dfbbb8f811-3f4a17df94e68624-803f8fc4cc73f8a1-3f4a17dfb4e8892d-3f4a17df8834fcca-3f4a17df11d91db8-d93a06206204e469-3f4a17dfea0f933d-3f4a17df493ac2c5-803f8fc4


```

**Comment by lk-geimfari** [comment] 2018-12-12 12:33
+1 The same issue

Brave version (brave://version info):
```
Brave	0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
Revision	2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS	Mac OS X
JavaScript	V8 7.1.302.28
Flash	(Disabled)
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave,AutofillServerCommunication,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/likid_geimfari/Library/Application Support/BraveSoftware/Brave-Browser/Default
Variations	c134752e-f685ead3
2c707b42-dcf7018a
411b6d4e-3f4a17df
b7d3b6c2-3f4a17df
d01ab0d3-755bc755
3e006338-3f4a17df
66df3e9d-a85d0b2f
ebeb14fc-3f4a17df
b7e2524c-3f4a17df
b3888d8d-afba0f91
61832c80-3f4a17df
cc20827f-77c422c
9041608a-3f4a17df
241fff6c-ddf20878
9853922b-3f4a17df
125b7f68-3f4a17df
9ca1387e-3f4a17df
1c752ce9-1c752ce9
776de70c-e0278d3d
ed9149a9-3f4a17df
34d450b1-3f4a17df
31362330-3f4a17df
c70841c8-a2567007
14bdbe54-e8c7a65b
8ee5ed19-c3125ea2
74658432-fa79b94c
ed7ba060-3f4a17df
121ae2bc-65969d67
9e201a2b-3f4a17df
27212adc-27212adc
249dd49a-3f4a17df
5274eb09-3f4a17df
ceff87ec-3f4a17df
44827ee5-3f4a17df
332a4d9b-8e8e4a2b
8f1e27f-3f4a17df
edbcf7c5-ddf1844d
77bbdddc-3f4a17df
5485fc4d-3f4a17df
93731dca-3f4a17df
9b4c4257-3f4a17df
43f62d3b-3f4a17df
4ae380f4-3f4a17df
165e16d1-3f4a17df
9e5c75f1-30e1b12b
6fa07eb4-7282ca76
2981bcb4-3f4a17df
5139837c-3f4a17df
4934552d-3f4a17df
7f8176d9-3f4a17df
6c66bd8d-b2047178
23a898eb-fc93cf74
7a5ba892-3f4a17df
4ea303a6-3f4a17df
b19465ab-b19465ab
6e6e0c7e-3f17a7d8
95876445-2b71ffe4
d92562a9-441539fd
fc369826-3f4a17df
2b33233e-881ca6c9
4da5ae82-3f4a17df
56302f8c-2f882e70
14c5a050-61ceed18
cc54eb06-803f8fc4
b2612322-8a9180b2
ad6d27cc-3e870323
df072bba-9a6c5085
f56e0452-3f4a17df
8576baf1-3f4a17df
3038aa2e-3f4a17df
51b9b54d-3f4a17df
7345ea6-3f4a17df
4bc337ce-f483b7fd
9a2f4e5b-4bc735ae
ddf77e2c-63745fe1
1354da85-522c33b8
17507c76-3f4a17df
494d8760-3f4a17df
bbb8f811-3f4a17df
94e68624-803f8fc4
cc73f8a1-3f4a17df
b4e8892d-3f4a17df
8834fcca-3f4a17df
11d91db8-d93a0620
6204e469-3f4a17df
ea0f933d-3f4a17df
493ac2c5-803f8fc4
```

**Comment by srirambv** [comment] 2018-12-12 14:15
Dupe of #2034

**Closed by srirambv** 2018-12-12 14:15 UTC

**Comment by lk-geimfari** [comment] 2018-12-12 14:31
Oh, sorry, we did not notice that issue is already created.
