### ISSUE TITLE
Follow up to #12737: Use frame URL as root context when adblocking

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#13290] opened 2020-12-23 17:04 UTC
Follow up to https://github.com/brave/brave-browser/issues/12737. The issue is still reproducible

## Steps to Reproduce

Steps in https://github.com/brave/brave-core/pull/7247

## Actual result:

Videos are blocked from playing due to Adblock
![image](https://user-images.githubusercontent.com/34715963/103019689-80c01a80-4547-11eb-800d-a726cc52e849.png)

## Expected result:
Able to play the videos

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

Brave | 1.19.66 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Ubuntu 18.04 LTS

cc @antonok-edm @brave/legacy_qa @rebron

**Comment by GeetaSarvadnya** [comment] 2020-12-23 17:16
Reproduced in `Windows 10 x64 - 1.19.66 `

**Comment by antonok-edm** [comment] 2020-12-23 17:36
Hmm, I think the website was updated since then, I see the same result in uBlock Origin :sweat_smile:

@ryanbr can you take a look?

**Comment by ryanbr** [comment] 2020-12-28 00:36
@btlechowski @GeetaSarvadnya  this is fixed in Beta and Nightly. Landed a temp fix for Brave Release

**Comment by ryanbr** [comment] 2020-12-30 08:03
Just re-check this, should be safe to close. No anti-adblock messages on video playback. @btlechowski @GeetaSarvadnya

**Closed** 2021-01-04 06:25 UTC
Labels: OS/Android, OS/Desktop, QA/Test-Plan-Specified, QA/Yes, bug, feature/shields/adblock

**Comment by kjozwiak** [comment] 2021-01-04 16:00
Verification **PASSED** on `Win 10 x64` using the following builds:

```
Brave | 1.20.58 Chromium: 88.0.4315.7 (Official Build) nightly (64-bit)
-- | --
Revision | 9b020863b2987261f6dcd018c6b388041c035f98-refs/branch-heads/4315@{#15}
OS | Windows 10 OS Version 2009 (Build 19042.685)
```

```
Brave | 1.19.72 Chromium: 87.0.4280.101 (Official Build) beta (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2009 (Build 19042.685)
```

```
Brave | 1.18.77 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2009 (Build 19042.685)
```

Visited https://www.motorsport.com/f1/news/wolff-hamilton-contract-talks-2021/4911380/ and ensured I could play the video as per the following;

![image](https://user-images.githubusercontent.com/2602313/103553709-d7005800-4e7b-11eb-98eb-763e6214aa4a.png)

**Comment by srirambv** [comment] 2021-01-05 11:48
Verification passed on OnePlus 6T with Android 10 running 1.19.74 x64 build
- Verified video could be played on the page 
<img width=300 src=https://user-images.githubusercontent.com/17010094/103642982-d9ca7e00-4f4b-11eb-859b-3d9b20df23da.png>
