### ISSUE TITLE
Add on Fdroid playstore sucks 

### ISSUE THREAD

**Issue by WilliamShockleyfake** [brave/brave-browser#16092] opened 2021-05-26 20:25 UTC
There is no good browser on Fdroid for those who don't use Google services. Plz add brave on fdroid

**Comment by srirambv** [comment] 2021-05-27 15:57
Dupe of #7027

**Closed by srirambv** 2021-05-27 15:57 UTC
Labels: OS/Android

**Comment by Krusty27** [comment] 2021-05-30 08:32
Well you can try Bromite or Fennec
