### ISSUE TITLE
Adblock exception filters don't work properly anymore.

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [brave/brave-browser#32001] opened 2023-08-01 01:35 UTC
## Description 

Hey @antonok-edm
Something is really broken in latest Nightly with the Adblocker, and I would say it is kind of serious, since if my theory is true, then that means it will affect most Exception rules.

Exception rules are not working when using the `||` or the domain part in the URL to whitelist in the rule or both.

So for example:

using `@@||example.com/test/script.js` doesn't work, but it will work if you do a `@@test/script.js` for example.

To test it it is pretty simple, because yesterday it was working and it stopped working today with `1.58.61 Chromium: 116.0.5845.51 (Official Build) nightly (64-bit)`

You can shall be able to see it if you go to https://account.brave.com/plans/?intent=checkout&product=talk, all Brave account scripts should be blocked looking like this:

![image](https://github.com/brave/brave-browser/assets/122518587/3702824c-fcb7-4afe-8d4b-e262f2c71931)

using `@@||brave.com` doesn't work, it actually blocks more scripts, from 8 in the screenshot now it blocks 13, same with  `@@account.brave.com` doesn't work either.

But if you use `@@_app/assets/` it works, but if you do a `@@||_app/assets/` it won't work again.

I had to end up using `@@*$domain=brave.com` because I always whitelist scripts in Brave domains anyway.

It was working yesterday, so something about the new Nigthly messed something up.

Yesterday I used `games.msn.com`, and it was working fine.
When I went to `https://www.games.msn.com/en/mssolitairecollection/default.htm` and hit play, the game never loaded.

It doesn't do it because EasyList Cookie blocks `||microsoft.com/mscc/` and this rule doesn't have the 'games' subdomain as an exception:
`@@||wcpstatic.microsoft.com/mscc/lib/v2/wcp-consent.js$domain=azure.com|blogs.bing.com|blogs.windows.com|customsearch.ai|halowaypoint.com|mcr.microsoft.com|nonprofit.microsoft.com|pcmanager-en.microsoft.com|pcmanager.microsoft.com|setup.microsoft.com|todo.microsoft.com|web.groupme.com|zone.msn.com`

So the problem of the game not loading happens in uBlock as well.

So, I created an exception rule, long time ago, plus other rules to block the ad videos better.

But today I had problems loading the game after working fine yesterday, and I have tried many exception rules, until I realize, it doesn't work properly, and it fails to work properly in this tests I made, when I was using `microsoft.com` or `wcpstatic.microsoft.com` or the rule started with `||`

So this is what is works and what fails. 

`@@||wcpstatic.microsoft.com/mscc/lib/v2/wcp-consent.js$domain=games.msn.com` ❌
`@@||wcp-consent.js` ❌
`@@wcpstatic.microsoft.com/mscc/lib/v2/wcp-consent.js` ❌
`@@wcpstatic.microsoft.com/mscc/lib/$domain=msn.com` ❌
`@@||wcpstatic.microsoft.com^$domain=msn.com` ❌
`@@wcpstatic.microsoft.com^$domain=msn.com` ❌
`@@wcp-consent.js` ✅
`@@mscc/lib/v2/wcp-consent.js$domain=games.msn.com`✅
`@@microsoft.com/mscc/lib/v2/wcp-consent.js$domain=games.msn.com` ❌

I mean, I don't know what happened but it is affecting all lists, Default, Regional or Custom lists or filters. 
I just got a random exception list from Brave Unbreak list

`@@||flamingo.gomobile.jp^$script,domain=7net.omni7.jp`

you go to that page, and it has the `https://flamingo.gomobile.jp/omni77netfilter/latest/flamingo.js` blocked

remove the domain part of the rule `@@omni77netfilter/latest/flamingo.js$script,domain=7net.omni7.jp` works again.

`@@||flamingo$domain=7net.omni7.jp` ❌
`@@flamingo$domain=7net.omni7.jp` ✅
`@@||gomobile.jp^$domain=7net.omni7.jp` ❌
`@@gomobile.jp^$domain=7net.omni7.jp` ❌

The point is clear lol, I can reproduce this 100% with  `1.58.61 Chromium: 116.0.5845.51 (Official Build) nightly (64-bit)` in a complete new profile.

Yesterday it was working fine or I think so, because I remember loading MSN without problems at night, and I remember checking Brave checkout page few days ago and no problems, so, should be something in `.61` or pretty recent.

Anyway! take care and hope you can reproduce this as well.

Note:
Tested Android, with the MSN games and the the `@@||wcpstatic.microsoft.com/mscc/lib/v2/wcp-consent.js$domain=games.msn.com` and it works fine in 1.58.61 build, so if it is a problem, would be in the Desktop build.

**Comment by antonok-edm** [comment] 2023-08-01 04:44
confirmed, thanks for the quick and detailed report as always @Emi-TheDhamphirInLoveUnderTheFrozenStar!

The issue only seems to be present in Aggressive blocking mode. I had a working build of 1.58.57 which didn't show this issue but I can see it happening in Nightly now. The evidence seems to be pointing towards https://github.com/brave/brave-core/pull/17368. Investigating now.

**Comment by antonok-edm** [comment] 2023-08-01 05:26
found it - should get fixed with https://github.com/brave/brave-core/pull/19512

As per the "minute or so", that appears to be my [old friend DNS](https://www.cyberciti.biz/media/new/cms/2017/04/dns.jpg).

**Closed** 2023-08-01 14:28 UTC
Labels: bug, feature/shields/adblock, priority/P1, QA/Yes, release-notes/exclude, OS/Desktop

**Comment by MadhaviSeelam** [comment] 2023-08-14 20:29
Verification `In progress` using
```
Brave | 1.58.88 Chromium: 116.0.5845.82 (Official Build) beta (64-bit)
-- | --
Revision | acf16e35d5897fd4bf9b1b5a93b56aff2ed64bba
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

<img width="952" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d54ad400-3bb3-4bdd-9c7c-58f72bc10dfc">
