### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by AdityaG-BS** [brave/brave-browser#34890] opened 2023-12-14 09:54 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.101 Chromium: 120.0.6099.71
Operating System: Mac OS X 14.0.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Just randomly open a few tabs and keep surfing 

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/7fa70100-100a-300b-0000-000000000000

**Comment by bsclifton** [comment] 2023-12-14 18:43
Thanks for the report @AdityaG-BS - this is a duplicate of https://github.com/brave/brave-browser/issues/34785

Can you please check for updates? There is a fix for this in version [1.61.104](https://github.com/brave/brave-browser/releases/tag/v1.61.104)

**Closed by bsclifton** 2023-12-14 18:43 UTC
Labels: crash
