### ISSUE TITLE
(macOS) High CPU usage, sometimes crashes

### ISSUE THREAD

**Issue by hvstms** [brave/brave-browser#35436] opened 2024-01-19 10:50 UTC
## Description 

2-4 times a day brave freezes and I can only see the 'loading cursor'. No interactions with the window, everything else on the machine works perfectly. In the Activity Monitor, ~100% of CPU use is displayed instead of the usual 0-5%, other metrics look fine to me.

## Steps to Reproduce

I am not sure how to trigger the behaviour. I have removed all extension (except DashLane) and turned off the two Leo (AI assistant) settings available (I would like to have a single 'turn off' button); these did not help at all.

## Actual result:

Unresponsive browser, which I have to force quit and relaunch every time.

## Expected result:
Working browser.

## Reproduces how often: 

A few times a day.

## Brave version (brave://version info)

1.61.120

## Version/Channel Information:

I don't know.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? I don't know.
- Does the issue resolve itself when disabling Brave Rewards? I don't know.
- Is the issue reproducible on the latest version of Chrome? I don't know.

**Comment by hvstms** [comment] 2024-01-19 12:21
<img width="974" alt="image" src="https://github.com/brave/brave-browser/assets/33235641/a328267d-e9c6-4a88-b111-359c850c89a4">

I think it might happen after being idle for a while.

**Comment by rebron** [comment] 2024-01-19 20:36
@hvstms Is there anything in brave://crashes If so, can you paste the id from there into this issue.
cc: @atuchin-m for any other ideas and other information we may need.

**Comment by rebron** [comment] 2024-01-19 20:37
@hvstms Can you also paste the information from brave://version/

**Comment by hvstms** [comment] 2024-01-19 21:40
@rebron 

Thank you for taking the time!

Yes, under crashes I can see some instances, that have been submitted automatically, it seems. However, there is only one instance from January instead of ~20.

Brave | 1.61.120 Chromium: 120.0.6099.234 (Official Build) (arm64)
Revision | 362207c81bff0740a8b6cff62dd91c6789f5698f
OS | macOS Version 13.4.1 (c) (Build 22F770820d)
JavaScript | V8 12.0.267.17
User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --disable-domain-reliability --enable-dom-distiller --enable-distillability-service --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Linker | lld
Variations Seed Type | Safe
Active variations | AllowCertainClientHintsStudy:EnabledBraveAIChatEnabledStudy:EnabledBraveAdblockMobileNotificationsListDefault:EnabledBraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=6/MaximumInlineContentAdsPerDay=20/AdServingVersion=2BraveAutoTranslateStudy:AutoTranslateDisabledBraveCleanupSessionCookiesOnSessionRestore:DisabledBraveDebounceStudy:EnabledBraveForgetFirstPartyStorage:EnabledBraveGoogleSignInPermissionStudy:EnabledBraveHttpsByDefaultRolloutStudy:EnabledBraveP3AConstellationReleaseRollout:EnabledBraveRewardsWebUiPanelStudy:EnabledBraveScreenFingerprintingBlockerStudy:EnabledBraveSearchAdStudy:EnabledInProcessDesktopClampPlatformVersionClientHint:DisabledCloseWatcher:Disabled_EmergencyKillSwitchCookieListDefaultStudy:EnabledCrossPlatformVPNStudy:EnabledDefault1pBlockingStudy:DisabledDisableReduceLanguage:EnabledEphemeralStorageStudy:EnabledFirstPartyEphemeralDomainBlockStudy:EnabledForceDisableBlinkFeatures:EnabledMacCoreLocationBackendStudy:EnabledPartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledSmilAutoSuspendOnLagKillSwitch:Disabled_EmergencyKillSwitchSpeedreader TTS:EnabledUserActivityStudy:TriggersWhatsNewStudy:Enabled

**Comment by atuchin-m** [comment] 2024-01-23 05:22
@hvstms could you make and share a sample of the hanging process when the problem appears?
Double click on the process in Activity Monitors, then 'Sample, then 'Save'
<img width="564" alt="Screenshot 2024-01-23 at 12 17 58" src="https://github.com/brave/brave-browser/assets/45488748/eea14e8c-4898-4ed6-8f4f-5e42b954366e">
<img width="942" alt="Screenshot 2024-01-23 at 12 18 34" src="https://github.com/brave/brave-browser/assets/45488748/1894c8fb-81cc-4392-81a2-2369400a03dd">

**Comment by hvstms** [comment] 2024-02-01 15:10
It has happened again. Attaching the requested sample.

[hvstms_daily_crashing_sample.txt](https://github.com/brave/brave-browser/files/14127207/hvstms_daily_crashing_sample.txt)

**Comment by atuchin-m** [comment] 2024-02-01 16:27
Thanks for the report @hvstms.
The data shows some hang in `accessibility` code.
Probably it's https://bugs.chromium.org/p/chromium/issues/detail?id=1517187
Also bug looks OS-code related (mostly `AppKit` in the stacks)

Could you try to reset OS accessibility settings: https://bugs.chromium.org/p/chromium/issues/detail?id=1517187#c17?

**Comment by atuchin-m** [comment] 2024-02-01 16:30
Another similar issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1519844

**Comment by ollietreend** [comment] 2024-02-07 11:59
I've been having a similar issue – in fact, it seems similar enough that I'm adding to this discussion rather than opening a new issue. Brave is constantly using > 100% CPU on my MacBook, even immediately after opening the app following a full system reboot.

Here's a screenshot of the task manager while I have zero tabs open:

<img width="1059" alt="Task manager window showing the main Browser process using 135.8% CPU" src="https://github.com/brave/brave-browser/assets/7735945/84c6a056-6567-428b-aa53-e8235fd0e2d1">

I've noticed it happening for a few weeks now. I've tried disabling extensions, clearing cache, removing service workers that I don't need, etc. Sometimes it _doesn't_ use 100% CPU, but most of the time it does. And I can't figure out what's triggering it.

I can use the browser itself completely normally. It is still responsive and you'd never know anything was wrong if it wasn't for my laptop's warmth and increased battery drain. Except for: I'm unable to cleanly quit Brave. Whenever I quit the app, all the windows close, but it remains open in the macOS dock. And it doesn't close by itself until I force quit.

Coincidentally – and probably not related – but I noticed the Spotify desktop app was also chewing through 100% CPU. It turned out I needed to _disable_ Spotify's access to the 'Downloads' folder in the macOS system settings (Privacy & Security > Files and Folders). This immediately stopped Spotify's CPU drain.

Since Spotify and Brave are both built upon Chromium, I wondered if the same Privacy & Security tweak would work for Brave. But it appears I can't revoke Brave's access to the 'Downloads' folder – Brave doesn't show up in the list of apps under Files and Folders.

**Comment by bsclifton** [comment] 2024-02-26 06:23
@ollietreend there's a setting in brave://settings/system under `Performance` that you might check and try toggling on/off. 

It's an energy saver and specific for laptops:
https://support.brave.com/hc/en-us/articles/13380606172557-How-do-I-use-the-Energy-Saver-feature-in-Brave

Please let us know! This is something we inherit from Chromium. It should be enabled by default but can be disabled

**Comment by ollietreend** [comment] 2024-02-26 15:31
Thanks @bsclifton. I worked out what it was in the end.

I had the Notion PWA installed, and I think at some point something went dodgy with the service worker. The web app itself stopped loading, so I stopped using it. I'd already uninstalled the app from macOS by dragging the `Notion.app` 'Brave app' to the trash and emptying it – but I didn't realise it still existed in `brave://apps`, and it was still running in the background.

I didn't realise PWA apps still live on after they've been deleted from the OS.

**Comment by bsclifton** [comment] 2024-02-26 21:20
Thanks for the follow up

cc: @rebron @petemill @fallaciousreasoning @simonhong on the finding about deleting the OS shortcut not updating brave://apps

This might be expected behavior at the moment as I'm not sure if Brave is notified when the shortcut is removed (ex: any event fires)

**Comment by bsclifton** [comment] 2024-02-27 22:56
OK will close this issue as there's no follow up on original steps (asking to reset accessibility settings). The root cause for original issue described is https://issues.chromium.org/issues/41490170

Thanks @ollietreend for sharing the PWA information. This is great info too!

**Closed by bsclifton** 2024-02-27 22:56 UTC
Labels: needs-investigation, OS/macOS, perf, OS/Desktop
