### ISSUE TITLE
Need more than 12 sites on the favourites tab in the new tab.

### ISSUE THREAD

**Issue by mohakdev** [brave/brave-browser#22769] opened 2022-05-10 13:29 UTC
## Description 

This feature is not only requested by me but many other people in #7493
I don't understand why brave provides so less favourite sites. I mean is there a good reason for this ?? Most browsers allow more favourite sites than that. Now people can use bookmarks but I think it would be way better to add support for more favourite sites

**Comment by rebron** [comment] 2022-05-10 22:37
Closing as duplicate of https://github.com/brave/brave-browser/issues/6619

**Closed by rebron** 2022-05-10 22:37 UTC
Labels: OS/Desktop
