### ISSUE TITLE
Tab contrast is too low on un-focused windows

### ISSUE THREAD

**Issue by bradsk88** [brave/brave-browser#15277] opened 2021-04-14 00:21 UTC
## Description 
I often open multiple browser windows across multiple monitors. This means that open browser windows will be visible, but un-focused.

The current color scheme is very low contrast when the window is unfocused.  Making it difficult to know which tab is open in the window.

## Steps to Reproduce

   1. Open two browser windows.
   2. Open multiple tabs in window A
   3. Click window B to remove focus from window A

## Actual result:
![image](https://user-images.githubusercontent.com/2147630/114636589-9a1add00-9c84-11eb-9e50-202c5a1a533b.png)

## Expected result:
![image](https://user-images.githubusercontent.com/2147630/114636649-b9196f00-9c84-11eb-937e-da8d49f12ea9.png)

## Brave version (brave://version info)

Version 1.21.57 Chromium: 88.0.4324.152 (Official Build) unknown (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the nightly channel? Unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment] 2021-04-16 16:12
@bradsk88 What Linux version are you on?

**Comment by bradsk88** [comment] 2021-04-16 20:53
@rebron 

```
Operating System: Manjaro Linux
KDE Plasma Version: 5.21.3
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.10.23-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
``

**Comment by rebron** [comment] 2021-07-20 20:21
cc: @simonhong

**Comment by simonhong** [comment] 2021-07-21 09:32
Hmm, below macOS tabs seems same. I will check the tab colors.
<img width="580" alt="Screen Shot 2021-07-21 at 6 31 39 PM" src="https://user-images.githubusercontent.com/6786187/126466687-25b881c3-bc53-4312-8070-f4acc860c188.png">

**Comment by simonhong** [comment] 2021-07-21 13:34
In dark theme, 
Inactive tab's bg color is same with inactive window's frame color. It's `color_utils::HSLShift(kDarkFrame, { -1, -1, 0.6 })`
and active tab's bg color in inactive window is `SkColorSetRGB(0x30, 0x34, 0x43)`.
Should we adjust these colors for increasing contrast between active & inactive tab in inactive window? cc @karenkliu

**Comment by karenkliu** [comment] 2021-07-21 18:03
@simonhong This seems like a dupe of this issue https://github.com/brave/brave-browser/issues/15134

**Closed** 2021-07-21 18:05 UTC
Labels: OS/Desktop, OS/Linux, feature/tabs-bar
