### ISSUE TITLE
Strict fingerprint blocking prevents sites from detecting color scheme preference

### ISSUE THREAD

**Issue by kdkasad** [brave/brave-browser#17550] opened 2021-08-19 01:55 UTC
## Description 
When fingerprint blocking is set to "Strict", Brave no longer matches `(prefers-color-scheme: dark)` in sites even if the preferred color scheme is set to `Dark` in `brave://settings`.

This means that sites which would normally display a dark color scheme based on your browser's settings only show the light theme. The only solution is setting fingerprint blocking to "Standard."

## Steps to Reproduce

   1. Set "_Brave colors_" to "*Dark*" in `brave://settings`.
   2. Set fingerprint blocking to "*Strict*".
   3. Go to any site.
   4. In the JS console, type the following:
```js
window.matchMedia('(prefers-color-scheme: dark)').matches
```
   5. The output will show `false` even though it should be `true`.

## Actual result:
The media query `(prefers-color-scheme: dark)` evaluates to `false`.

## Expected result:
The media query `(prefers-color-scheme: dark)` should evaluate to `true`.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

**Brave:** `1.28.105 Chromium: 92.0.4515.131 (Official Build) (64-bit)`
**Revision:** `6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}`
**OS:** `Linux`

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
yes
- Can you reproduce this issue with the beta channel? 
yes
- Can you reproduce this issue with the nightly channel? 
yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
yes
- Does the issue resolve itself when disabling Brave Rewards? 
no
- Is the issue reproducible on the latest version of Chrome? 
no

## Miscellaneous Information:
It's possible that this is intended, but if so, I believe there should be an extra option to allow sites to access your color scheme preferences rather than having to disable strict fingerprint blocking for all sites which use this color scheme detection method.

**Comment by Tonev** [comment] 2021-08-19 02:56
It's an intentional behavior related to https://github.com/brave/brave-browser/issues/15265.

@ShivanKaul added a flag that allows users to opt out of the dark theme blocking while using strict fingerprinting protection. The flag is currently available in `Brave Nightly`, so until it's uplifted into the stable channel you have to either use `Standard` fingerprinting protection on a per-site basis or global level, alternatively you can use `Brave Nightly`.

https://github.com/brave/brave-core/pull/9735

**Comment by rebron** [comment] 2021-08-20 00:17
@ShivanKaul Ok to close this one out? Looks like it's working as intended.

**Closed** 2021-08-20 23:57 UTC
Labels: OS/Desktop
