### ISSUE TITLE
Ability to Modify NTP SI from Settings

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#8760] opened 2020-03-19 21:44 UTC
## Description 
Users who are attempting to modify/disable New Tab Page Sponsored Images are at times looking within about:settings (Brave's global Settings) and failing to locate controls for NTP SIs. Presently, this feature is controlled from the New Tab Page itself, by clicking the Dashboard button at the bottom-right.

## Brave version (brave://version info)
1.5.113

## Additional Information
Sponsored Images are enabled and disabled from within general Settings on iOS and Android.

## Designs
Add a "New Tab Page" section in Settings.

![new tab page](https://user-images.githubusercontent.com/2388823/77491694-b8a10280-6dfb-11ea-9d9c-1a765fd9272a.png)

The controls shown in Settings are duplicates linked to the controls on the new tab page:

![Screen Shot 2020-03-20 at 3 43 29 PM](https://user-images.githubusercontent.com/2388823/77211554-9177c780-6ac1-11ea-97d0-c1798003b32b.png)

## Assets
[icon asset.zip](https://github.com/brave/brave-browser/files/4362041/icon.asset.zip)

**Comment by mandar-brave** [comment] 2020-03-19 21:52
@rebron please prioritize. Please make settings a dupe of what is available on NTP.
cc @bradleyrichter

**Comment by karenkliu** [comment] 2020-03-20 22:46
Designs added!

**Closed** 2020-04-13 17:00 UTC
Labels: bug, feature/ads, feature/new-tab, priority/P3

**Comment by GeetaSarvadnya** [comment] 2020-05-05 08:33
Verification passed on
```

Brave | 1.9.55 Chromium: 81.0.4044.129 (Official Build) dev (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1803 (Build 17134.1006)
```
- Verified the test plan from https://github.com/brave/brave-core/pull/5151 and also verified https://github.com/brave/brave-core/pull/5310#issuecomment-622331329
- Verified that Toggling an option in New Tab Settings reflected on the NTP dashboard settings and vice versa.
![image](https://user-images.githubusercontent.com/38657976/81047270-b2f90b00-8ed7-11ea-9eae-fadc2b8532aa.png)
- Verified that, If Background images toggle is OFF, Sponsored images is also in disabled state.
![image](https://user-images.githubusercontent.com/38657976/81047365-e50a6d00-8ed7-11ea-8528-456d528cbf1f.png)
- Verified that new tab section `brave://settings/newTab` order is reflected as as mentioned in the brave/brave-browser#8760 (comment).
![image](https://user-images.githubusercontent.com/38657976/81047534-3a467e80-8ed8-11ea-9e35-db6dcab67d0b.png)
