### ISSUE TITLE
Forced into Brave Rewards ? 

### ISSUE THREAD

**Issue by PascalDk** [brave/brave-browser#21290] opened 2022-02-24 08:33 UTC
## Description 

I misclicked on the Brave Reward button from the 3dots menu, and it opened a message overlaying the whole window and making it unusable. 

Now I just can't do anything else than entering Brave Rewards. 

- If I click on the back button it makes me leave the app. 

- I can't type another url or open the menu since the message is overlaying the screen and blocking everything else. 

- If I close the app and reopen, that problem is still there 

I just hope it's a bug and not a marketing trick. 

## Steps to reproduce

   1. Install Brave beta 
   2. Click on the Brave Rewards Menu under the 3dots menu for the first time 
   3. Get stucked (OR get forced into Brave Rewards even if you didn't want to be there) 

## Actual result 
![Screenshot_20220224-090717.jpg](https://user-images.githubusercontent.com/5103378/155485419-def3db00-4034-4a51-802c-68b13a3edef0.jpg)

*Take a quick tour, 
Start using Brave Reward, 
Read Terms of Service 
Read Privacy Policy* 

... are the only thing you can do 

## Expected result 
Should not happen

## Issue reproduces how often 
Issue is reproducible anytime you fresh install Brave Beta from the Playstore 

## Device details
OnePlus 6T
Android 11
Oxygen OS 11.1.22
   
## Brave version
Beta 1.37.72

**Comment by diracdeltas** [comment] 2022-02-25 06:14
Definitely a bug not a marketing trick, maybe it should either have a button to close the modal or allow user to open a new tab while in this state. cc @anthonypkeane @Miyayes

**Comment by srirambv** [comment] 2022-02-25 09:36
This is already known and should be fixed as part of #20447. Current work around is to click `Take a tour` and the skip it when it opens in the panel and it should allow to use URL bar/menu. Second work around is to background the app and long press on Brave icon and open a new tab.

**Comment by srirambv** [comment] 2022-02-25 09:37
Going to close this as a dupe of #20447. Its currently at P4 maybe we can bump the priority and get it fixed sooner than later. @Miyayes

**Closed by srirambv** 2022-02-25 09:37 UTC
Labels: OS/Android
