### ISSUE TITLE
brave:// pages are not considered secure

### ISSUE THREAD

**Issue by Liunkae** [brave/brave-browser#3848] opened 2019-03-22 03:40 UTC
## Description 
brave:// pages are considered not secure in the URL bar. Also, I thought that these pages used to be marked as local "Brave" pages, but they no longer are.

## Steps to Reproduce
   1. Go to brave://settings.
   2. Click the information icon in the URL bar.

## Actual result:
![](https://user-images.githubusercontent.com/19424103/54799128-d4daf400-4c29-11e9-882c-bfba8d3280c0.png)

## Expected result:
The pages should be considered secure because they are local pages.

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave | 0.64.8 Chromium: 73.0.3683.75 (Official Build) nightly(64-bit)
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes, 0.64.8 nightly.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Not applicable.
- Is the issue reproducible on the latest version of Chrome? I don't think so.

**Comment by srirambv** [comment] 2019-03-22 14:13
Dupe of #3411

**Closed by srirambv** 2019-03-22 14:14 UTC
