### ISSUE TITLE
Unable to verify humanity in Brave Rewards: cannot drag BAT icon in claim CAPTCHA 

### ISSUE THREAD

**Issue by Mitsunee** [brave/brave-browser#20428] opened 2022-01-10 21:28 UTC
## Description 
I cannot complete the captcha to claim my monthly BAT payout as the brave icon is not draggable.

![image](https://pbs.twimg.com/media/FIxPKfeWUA4rr9W?format=png&name=orig)

As a [joke](https://twitter.com/Mitsunee/status/1480646323212853249) I even tried to add `position: relative` and my best guess for `top` and `left`, but that did nothing. Pretty sure that's no solution in the first place, as it could easily be automated with puppeteer.

I initially intended to do a bunch of donations (both monthly and one-time) via Brave to thank content creators on youtube and open source developers on here for another year of awesome work, but I don't see if those went through yet as the total is entirely different from what I can see in Uphold (it's actually more than I owned before any donations). Not sure if that's related in any way.

## Steps to Reproduce

   1. Enable Brave Rewards Ads
   2. Wait a month
   3. Attempt to claim payout via button on brave://rewards (top most element in rightside column)

## Actual result:
The normal behaviour for non-draggable img elements appears and the captcha puzzle is not solved no matter where I drag the element

## Expected result:
The captcha appears as solved and I get my "rewards".

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
  - Yes

I don't know how to install other version, so I redacted those questions

## Other Additional Information:

None applied.

## Miscellaneous Information:
The latest update of brave has introduced a ton of other issues, many of which have their own ticket on here already, like tabs not being draggable properly anymore (they always split off into new windows now) and dragging things into the bookmarks bar doesn't work anymore either. I can't seem to drag the corner of the textarea I'm typing into either, won't go any bigger in either dimension. I can however still drag scrollbars and videos on my Watch Later playlist on YouTube.

**Comment by serkonda7** [comment] 2022-01-11 09:18
I have the same problem with latest AUR version.

**Comment by Mitsunee** [comment] 2022-01-11 17:25
Non-Update: none of my tips have gone through so basically my Brave Rewards is frozen because of this broken captcha. Definitely gonna keep ads disabled now.

**Comment by Miyayes** [comment] 2022-01-13 16:26
This seems like a larger Linux issue in general, possibly from upstream Chromium. For users experiencing this, can you also try and "drag and drop" your tabs? It seems like all drag and drop operations are having issues. cc: @simonhong @

**Comment by serenovah** [comment] 2022-01-13 16:42
I'm on Linux and having the same issue. It's been a few days now that I haven't been able to move tabs or remerge a popped out tab with the window it came from.

For me the tabs issue is a bigger issue than the reward to be honest. I constantly have a large number of tabs open because i'm always doing reasearch, and not being able to organize my tabs is a big hinderance to my workflow.

Kubuntu 21.20
KDE Plasma: 5.22.5
KDE Frameworks version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-25-generic (64-bit)
Graphics Platform: X11

Brave Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)

**Comment by Mitsunee** [comment] 2022-01-13 19:52
There is already a ticket for the broken tabs, this one here is for the Brave Rewards extension

**Comment by Dialga** [comment] 2022-01-14 13:18
I'm also affected by this bug on Arch Linux and was about to raise an issue, so this must be a widespread problem.

**Comment by theRoboxx** [comment] 2022-01-14 16:49
Same here on Linux Mint:

OS: Linux Mint 20.2 x86_64 
Kernel: 5.4.0-94-generic 
DE: Plasma 
WM: KWin 
WM Theme: Breeze 
Theme: Breeze Dark [Plasma], Breeze [GTK2/3] 

Brave-stable: Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)
and
Brave-beta: Version 1.35.77 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)

**Comment by serenovah** [comment] 2022-01-14 16:54
> 

This is the one I could find a link to, my apologies. I can certainly also post in that thread as well!

**Comment by Torkin1** [comment] 2022-01-14 22:07
I'm experiencing this issue too.
```
$ neofetch
             .',;::::;,'.                daniele@T540p 
         .';:cccccccccccc:;,.            ------------- 
      .;cccccccccccccccccccccc;.         OS: Fedora release 35 (Thirty Five) x86_64 
    .:cccccccccccccccccccccccccc:.       Host: ThinkPad T540p 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 5.15.13-200.fc35.x86_64 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 19 mins 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 4625 (rpm), 23 (flatpak) 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: bash 5.1.8 
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 1920x1080 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: Plasma 5.23.4 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: KWin 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   WM Theme: Gently-Blur 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Theme: Gently [Plasma], Breeze [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Icons: Breeze Chameleon Dark [Plasma], Breeze Chameleon Dark [GTK2/3] 
cccccc;dNMWXXXWM0::cccccccccccccc:,      Terminal: yakuake 
cccccccc;.:odl:.;cccccccccccccc:,.       CPU: Intel i7-4700MQ (8) @ 3.400GHz 
:cccccccccccccccccccccccccccc:'.         GPU: NVIDIA GeForce GT 730M 
.:cccccccccccccccccccccc:;,..            GPU: Intel 4th Gen Core Processor 
  '::cccccccccccccc::;,.                 Memory: 4379MiB / 15679MiB

$ dnf list installed | grep brave
brave-browser.x86_64                             1.34.80-1                               @brave-browser-rpm-release.s3.brave.com_x86_64_  
brave-keyring.noarch                             1.9-1                                   @brave-browser-rpm-release.s3.brave.com_x86_64_

Version 1.34.80  Chromium: 97.0.4692.71 (Official Build)  (64 bit)
```

**Comment by arch-btw** [comment] 2022-01-17 02:28
- https://community.brave.com/t/after-clicking-on-brave-rewards-i-cannot-drag-bat-img-into-target-img-so-i-cannot-claim-bat-rewards/310719

- https://community.brave.com/t/im-unable-to-complete-brave-rewards-captcha/322133

- https://old.reddit.com/r/brave_browser/comments/s0tfp7/cant_claim_bat_because_captcha_doesnt_work/

**Comment by Mitsunee** [comment] 2022-01-17 07:50
Unsubscribing from this issue as there's no development on this apparently and people just post random crap. Issue Tracker on this repo is actually useless, my older ticket about Emojis not working is open to this day because noone ever even properly adressed the issues and all I get are wild theories like "it's linux fault", when no other application has these problems.

**Comment by error256** [comment] 2022-01-17 09:21
@Mitsunee I think it's assumed that it probably is the same issue as https://github.com/brave/brave-browser/issues/20386, it's just that nobody mentioned it here explicitly.

**Comment by theRoboxx** [comment] 2022-01-18 15:41
The problem is already solved in the upstream version of Chromium but it will take a bit longer for this to be added in brave's stable version.

I fixed it temporary by downgrading the browser to the previous version 1.33.106. If you use the package manager Synaptic you can do it easily like mentioned here:
https://community.brave.com/t/how-to-revert-to-earlier-version-of-brave-for-linux/99490

**Comment by Torkin1** [comment] 2022-01-18 15:51
I confirm that the workaround mentioned by @theRoboxx works as expected. I was able to claim my BATs in such version of brave. To do the same on dnf: 
```
sudo dnf downgrade brave-browser 1.33.106 -y
```

**Comment by Miyayes** [comment] 2022-01-18 19:33
Depending on where the fix lands in Chromium upstream, the fix will either land in 1.35 of Brave (Feb 1st) or 1.36 March.

**Comment by arch-btw** [comment] 2022-01-18 21:10
For those looking for some last working versions (thanks @theRoboxx )

Stable: https://github.com/brave/brave-browser/releases/tag/v1.33.106

Nightly: https://github.com/brave/brave-browser/releases/tag/v1.33.1

Dev: https://github.com/brave/brave-browser/releases/tag/v1.31.83

Beta: https://github.com/brave/brave-browser/releases/tag/v1.31.82

In arch linux you can edit the package build before installing from the AUR.

Find the line where it says:

pkgver=

And change it to the last working version.
Then change the sha512sum line for that package too.

I'm sure there's an easier way but this worked for me.

**Comment by Miyayes** [comment] 2022-01-21 17:23
Please update to the latest version. This should be fixed in Brave 1.34.81 release channel (new hotfix just released).

**Closed by Miyayes** 2022-01-21 17:23 UTC
Labels: feature/rewards, OS/Linux, priority/P2, Chromium/waiting upstream, OS/Desktop

**Comment by Torkin1** [comment] 2022-01-22 14:06
The problem with dragging tabs around seems resolved. When my BAT prize will be ready to be claimed, I'll let you know if i will be able to claim it.

**Comment by debian-user-france1** [comment] 2022-04-15 05:24
> This seems like a larger Linux issue in general, possibly from upstream Chromium. For users experiencing this, can you also try and "drag and drop" your tabs? It seems like all drag and drop operations are having issues. cc: @simonhong @

It is not claimable but tabs work. Feels like cheating from the company, but I rather have brave ads for supporting brave than other webapges...

Why is that issue marked as solved.
