### ISSUE TITLE
Unusual behaviour of Brave new tab when 'Tab to Search' is used

### ISSUE THREAD

**Issue by PunnyBoi** [brave/brave-browser#4267] opened 2019-04-28 10:27 UTC
## Description 
When using 'Tab to Search' option in the new tab, the tab kind of refreshes itself and then I again have to press the tab key. This issue is loosely related to #3756 (which I know is fixed in the latest release). Please see the GIF for clarity.

## Steps to Reproduce
   1. Open any website in the first tab.
   2. Open new tab and type y (assuming you watch youtube a lot, the brave automatically highlights youtube.com). Press tab immediately (to use 'Tab to Search' feature). 
   3. You will notice the 'Tab to Search' field will be active for milliseconds and then it reverts back to the URL. It acts like as if you didn't press the tab key.

You have to perform step 2 really quick in order to reproduce the issue.

## Actual result:
![Result](https://user-images.githubusercontent.com/42476181/56862935-cc669d80-69cd-11e9-98d9-201e5638ddbb.gif)

I opened a new tab, typed y, pressed tab, it changed to search bar, it reverted back to 'youtube.com', after a second I pressed tab again, it again changed to search bar and this time didn't change back to 'youtube.com'.

## Expected result:
The search bar should remain and should not revert back to the URL.

## Reproduces how often: 
Very often

## Brave version (brave://version info)
0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit) 

## Version/Channel Information:
Version 0.60.45 Chromium: 72.0.3626.109 didn't have this issue.

- Can you reproduce this issue with the current release? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No

**Comment by warwickmm** [comment] 2019-05-14 17:38
I have the same issue on Version 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit).  Opening a new tab and quickly trying to use a search engine keyword (e.g., `g` for a google search) briefly shows "Search Google" in the omnibox, only for it to disappear and result in `g <search term>` appearing in the omnibox.

Similar to in issue #3756, this only occurs if the current page has some content loaded.  When opening a new tab from a blank tab, I cannot reproduce this.

**Comment by PunnyBoi** [comment] 2019-05-15 13:28
I don't know why other people are not reporting this issue. Aren't they fast enough :p
Also, @rebron, is it possible to increase the priority of this issue? This issue is really annoying, and sometimes I have to wait for a second or two so that the new tab loads completely.

**Comment by rebron** [comment] 2019-05-15 15:10
@PunnyBoi If you go to Manage Search engines, do you see YouTube in other search engines? Try adding a keyword, edit using the menu on the right, and I use 'yt' as my keyword. Looks like there's a conflict with autocomplete and open search with the keystrokes you're using.

**Comment by PunnyBoi** [comment] 2019-05-15 15:52
Hii. That sounds right but then why was I not facing this issue in the old build? Because of this issue, I am still using build 0.60.45 Chromium: 72.0.3626.109, and it is working perfectly fine. What you said is a workaround solution, but for me, it's not a correct solution. Also, I am reluctant to change the keyword to 'yt' because I am using the above technique for youtube over three years (earlier I was on chrome).

**Comment by warwickmm** [comment] 2019-05-16 01:02
I experience the issue even with keywords configured in Manage Search engines.  If I open a new tab and quickly type a keyword (for example, `g` for a google search) followed by a search term, the omnibox shows
```
g <search term>
```
instead of 
```
Search Google| <search term>
```
The "Search Google" does appear initially, but is then mysteriously cleared away, and the keyword remains.

Again, this only occurs when the new tab is opened from a tab that has content loaded.

Also, I do not experience this with Version 0.64.75 Chromium: 74.0.3729.131 (Official Build) unknown (64-bit) on Arch Linux.  I can reproduce this 100% of the time with Version 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit) on Windows 7.

**Comment by PunnyBoi** [comment] 2019-05-27 12:06
@rebron, any update on this issue?

**Comment by PunnyBoi** [comment] 2019-06-19 07:11
@rebron, I tried your method too but it didn't help. I changed the youtube keyword as 'yt' but when I quickly type yt and press tab, the search bar appears once and then disappers. I know you are very busy but please look into this issue, it's really annoying. I am again reminding you that this issue was not present in Version 0.60.45 Chromium: 72.0.3626.109. Also, I am pretty sure that if you remove the image from the new tab (which take seconds to load), this issue will be resolved because I can see that the tab to search bar goes away when the image is completely loaded.

**Comment by rebron** [comment] 2019-07-18 19:41
@PunnyBoi Are you still seeing this on 66.100? It's our current release.

**Comment by warwickmm** [comment] 2019-07-18 19:43
I'm still seeing this on Version 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit) on Windows.  I haven't been able to test 66.100.

**Comment by PunnyBoi** [comment] 2019-07-19 07:41
I just updated brave to 66.100 and I can confirm that I am still seeing this.

**Comment by bsclifton** [comment] 2019-07-22 07:01
@PunnyBoi is it possible you have the mouse near the URL bar? I have experienced bugs before where the mouse accidentally triggers a selection since multiple options may be shown for auto-complete

For example, if you put the mouse in the bottom left corner and do the `y` and `tab` really quick, does it still happen? I suspect your mouse is in the URL bar. Whatever the case, definitely a bug 😄 Just hoping to narrow it down

**Comment by warwickmm** [comment] 2019-07-22 22:40
I can confirm that this is not caused by the location of the mouse cursor.  The text in the omnibar is cleared when the new tab page is rendered (in my case, the purple "this is a private window" background).

I should note that I am using this over RDP, so perhaps the effect is more pronounced?

**Comment by PunnyBoi** [comment] 2019-07-25 04:58
@bsclifton I don't think that the case. The bug is definitely related to the load time of the new tab page because currently, I am using [dark new tab](https://chrome.google.com/webstore/detail/dark-new-tab/mnjmegebbljjhpljjfjmkhgmokpmdbpo) extension and with it, I am not facing this issue anymore.

You will notice one thing in the Gif I uploaded initially that the tab is showing 'loading...' and the search bar is working fine but as soon as the new tab page loads entirely and the tab shows 'New Tab', the search bar just disappears. This indicates that the search bar is directly affected by the loading of the new tab.

**Comment by warwickmm** [comment] 2019-08-02 21:20
I can confirm that this is still an issue with Version 0.67.123 Chromium: 76.0.3809.87 (Official Build) (64-bit) on Windows 7.

**Comment by warwickmm** [comment] 2020-05-06 17:36
I can no longer reproduce this with version 1.8.86.  It appears to be fixed for me.

**Comment by bsclifton** [comment] 2020-05-06 22:26
@PunnyBoi are you able to re-test also? I'll go ahead and close this- but please re-open if it's still happening. Thanks! 😄

**Closed by bsclifton** 2020-05-06 22:26 UTC
Labels: feature/search, priority/P5

**Comment by PunnyBoi** [comment] 2020-05-09 18:40
@bsclifton Yes I tested it and I think it's fixed. Thank you so much man. Keep it up.
