### ISSUE TITLE
Hang and 100% CPU on legitimate website

### ISSUE THREAD

**Issue by anykeyh** [brave/brave-browser#6621] opened 2019-10-26 16:12 UTC
## Description 

Brave starst spinning, hanging and using 100% cpu when I visit this (legit) website. Chrome doesn't.

## Steps to Reproduce

   1. Visiting this website with Brave browser:
`https://skepticalscience.com/translation.php?a=305&l=12`

In my case, my Brave is then hanging, fan are running loud on the laptop, and I need to force quit the application. All tabs are impacted (e.g. I cannot go to another tab as the GUI is frozen).

## Actual result:

100% CPU and all GUI is frozen. Need to force quit.

## Expected result:

Not actual result 🤣 

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Windows 10 OS Version 1903 (Build 18362.418)
JavaScript | V8 7.8.279.17
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=NewExtensionUpdaterService,PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,UnifiedConsent,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,SyncUSSBookmarks --flag-switches-begin --load-media-router-component-extension=1 --flag-switches-end
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\****\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default

## Version/Channel Information:

Didn't test on other channels

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
=> Not tested.

- Is the issue reproducible on the latest version of Chrome? 
=> No.

**Comment by rebron** [comment] 2019-11-15 17:49
closing dupe of #5406 I'll +1 that for you.

**Closed by rebron** 2019-11-15 17:49 UTC
Labels: needs-investigation, perf
