### ISSUE TITLE
Opening new tab causes browser to crash when brave://flags has News disabled

### ISSUE THREAD

**Issue by DeiAsPie** [brave/brave-browser#25182] opened 2022-09-02 20:37 UTC
## Description 

On latest release(1.43.88) the browser crashes when trying to open tab while having set `brave://flags/#brave-news` to `Disabled`

## Steps to Reproduce

   1. Get 1.43.88 release
   2. Set `brave://flags/#brave-news` to `Disabled`
   3. Relaunch
   4. Try opening a new tab

## Actual result:

Crash of browser when attempting to open a new tab

## Expected result:
Open the new tab as usual 

## Reproduces how often: 

Easily reproduced/Always on this release so far even on the flatpak version

## Brave version (brave://version info)

1.43.88 Chromium: 105.0.5195.68 (Official Build) (64-bit) 

## Version/Channel Information:

Brave's official repos for non-opensuse rpm systems

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No, as still not 105.x.x.x
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by stephendonner** [comment] 2022-09-02 22:21
Thanks for finding this @DeiAsPie ; I can confirm also, using


Brave | 1.45.23 Chromium: 105.0.5195.68 (Official Build) nightly (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 13.0 (Build 22A5331f)

cc @petemill @mattmcalister @rebron

**Comment by stephendonner** [comment] 2022-09-02 22:32
Incident ID: `f95e0300-74c0-c508-0000-000000000000`

```
[ 00 ] 0x11f1f2cc0
[ 01 ] 0x123bce789
[ 02 ] 0x123bcb829
[ 03 ] 0x1235fd43d
[ 04 ] 0x122ecf249
[ 05 ] 0x11fa56b89
[ 06 ] 0x11f3a7d4c
[ 07 ] 0x121a5c1aa
[ 08 ] 0x1219e442a
[ 09 ] 0x1219f3a34
[ 10 ] 0x11edbd672
[ 11 ] 0x1219f201f
[ 12 ] 0x7ff80a4cb074
[ 13 ] 0x7ff80a4cb023
[ 14 ] 0x7ff80a4cadfd
[ 15 ] 0x7ff80a4c9a7b
[ 16 ] 0x7ff80a4c9060
[ 17 ] RunCurrentEventLoopInMode
[ 18 ] ReceiveNextEventCommon
[ 19 ] _BlockUntilNextEventMatchingListInModeWithFilter
[ 20 ] _DPSNextEvent
[ 21 ] -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
[ 22 ] 0x124d74d1f
[ 23 ] 0x11edbd672
[ 24 ] 0x12199c631
[ 25 ] -[NSApplication run]
[ 26 ] 0x12126b446
[ 27 ] 0x120a7a33f
[ 28 ] 0x1200d5358
[ 29 ] 0x1200d497c
[ 30 ] 0x120b173e2
[ 31 ] 0x120b17223
[ 32 ] 0x1210f356d
[ 33 ] 0x1203d2db1
[ 34 ] 0x1206b8e66
[ 35 ] 0x1206b888c
[ 36 ] 0x11edba16a
[ 37 ] 0x107f8472b
[ 38 ] 0x7ff80a0c0310
```

**Comment by MadhaviSeelam** [comment] 2022-09-02 22:39
Reproducible in Win 11 x64 
```
Brave | 1.43.85 Chromium: 105.0.5195.68 (Official Build) (64-bit)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

**Comment by bsclifton** [comment] 2022-09-06 06:12
Closing as a duplicate of https://github.com/brave/brave-browser/issues/25156

**Closed** 2022-09-07 23:07 UTC
Labels: bug, crash, priority/P2, QA/Yes, release-notes/include, QA/Test-Plan-Specified, OS/Desktop, feature/brave-news

**Comment by kjozwiak** [comment] 2022-09-08 08:02
The above requires `1.43.92` or higher for `1.43.x` verification 👍

**Comment by GeetaSarvadnya** [comment] 2022-09-12 08:23
Verification is inprogress

```
Brave | 1.43.92 Chromium: 105.0.5195.102 (Official Build) (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1889)

```

**Comment by LaurenWags** [comment] 2022-09-12 12:17
Verification in progress with

```
Brave | 1.43.92 Chromium: 105.0.5195.102 (Official Build) (64-bit)
```

Using STR and test plan from https://github.com/brave/brave-core/pull/15025#issue-1365071381, reproduced the issue using `1.43.89 Chromium: 105.0.5195.102`. Crash observed when attempting to open a new tab.

**Comment by btlechowski** [comment] 2022-09-12 13:58
Verification passed on

Brave | 1.43.92 Chromium: 105.0.5195.102 (Official Build) (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Ubuntu 18.04 LTS

Verified https://github.com/brave/brave-core/pull/15025#issue-1365071381

Reproduced in 1.43.88
Verified in 1.43.92
