### ISSUE TITLE
Missed rebranding

### ISSUE THREAD

**Issue by bcat1023** [brave/brave-browser#15876] opened 2021-05-15 15:05 UTC
## Description 

I noticed that at brave://about/ it still acts and looks like chrome with chrome branding

## Steps to Reproduce

   1. Type brave://about/ into the address bar

## Actual result:

Paged still marked as a chrome page

## Expected result:

Marked as a brave page rather than chrome

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.24.85 Chromium: 90.0.4430.212 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
          Yes
- Can you reproduce this issue with the beta channel? 
          Yes
- Can you reproduce this issue with the nightly channel? 
          Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
          No
- Does the issue resolve itself when disabling Brave Rewards? 
           No
- Is the issue reproducible on the latest version of Chrome? 
          Technically no because on chrome its meant to be branded as chrome

## Miscellaneous Information:

Missed Rebranding

**Comment by srirambv** [comment] 2021-05-17 03:03
Dupe of #5775

**Closed by srirambv** 2021-05-17 03:03 UTC
Labels: OS/Desktop
