### ISSUE TITLE
 Add Customization toolbar options & tabs on bottom setting

### ISSUE THREAD

**Issue by rpgmaniac** [brave/brave-browser#13526] opened 2021-01-12 22:31 UTC
I just changed to brave after using Firefox for almost 20 years but I just discover that there is zero options to customize the toolbar with various tools like I could do in Firefox, I have my PC connected to a 55 inch Smart TV & I use my PC from there most of the times when I'm doing anything else aside from gaming, I wanna have the option to add tools like 'Zoom Control' & 'Full Screen' also I wanna be able to add a 'Search' tool for the sole purpose of changing on the fly to a different search engine like from Google to DuckDuckGo for example, last give us the option plz to move the tabs bellow the web search & bookmark toolbar, this is very important, having the tabs on top is very inconvenient, oh & something else that is also very inconvenient is the placement of the bookmark button, can you plz move it left from Brave Shields button? the current placement is seriously very awkward. 

I would like to believe that you are gonna take seriously those concerns of mine as fixing those issues will be the key to make the thousands (if not millions) of people who are gonna try your browser the following days to feel like home, at the current state it is certain imo that a big portion will feel alienated from the lack of customization options like I'm feeling myself currently, I hope you are gonna do anything in your power to address those issues in the fastest possible manner, your browser have the opportunity to grow tremendously but this won't happen if the above issues I point out don't get fixed as soon as possible.

**Comment by bsclifton** [comment] 2021-01-15 05:53
Closing as a duplicate of [Suggestion: Tabs on bottom setting](https://github.com/brave/brave-browser/issues/181) and [The UI should allow for advanced customization](https://github.com/brave/brave-browser/issues/774)

**Closed by bsclifton** 2021-01-15 05:53 UTC
Labels: OS/Desktop, feature/settings
