### ISSUE TITLE
Web page not loaded.

### ISSUE THREAD

**Issue by owen7298** [brave/brave-browser#37719] opened 2024-04-19 08:46 UTC
## Description 

[worldhistory.org
](https://www.worldhistory.org/Flour_War/)
The main page is functioning properly, but the article page displays oddly.

- Brave's version is latest.

**Comment by rebron** [comment] 2024-04-19 17:04
cc: @ryanbr

**Comment by rebron** [comment] 2024-04-19 17:29
closing as dupe of https://github.com/brave/brave-browser/issues/37718

**Closed as completed by rebron** 2024-04-19 17:29 UTC
Labels: closed/duplicate, workaround/shields-down, OS/Desktop
