### ISSUE TITLE
After resume from hibernate, brave freezes with 100% CPU usage for ever

### ISSUE THREAD

**Issue by DontTrustMicrosoft-MicrosoftIsAsshole** [brave/brave-browser#4430] opened 2019-05-14 16:48 UTC
//searched for hibernate/resume/standby/freez with zero hits on github. The "community" bug report section has this, but it got auto closed?!

windows:
https://community.brave.com/t/brave-browser-not-responsive-will-not-connect-when-computer-comes-out-of-hibernate/19477

## Description 
After wake up from hibernate, Brave window won't render and is frozen for ever with 100% CPU usage

## Steps to Reproduce

   1. Run brave
   2. Put system to hibernate to disk
   3. wake up the system
   4. brave is frozen and will not respond to any interaction, whole window won't render

## Actual result:

brave needs to be killed and restarted every time

## Expected result:

brave respond. Work like Chrome, Chromium and or Firefox

## Reproduces how often: 

every time

## Brave version (brave://version info)

Brave | 0.63.55 Chromium: 74.0.3729.131 (Offizieller Build)unknown (64-Bit)
-- | --
Überarbeitung | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
Betriebssystem | Linux
JavaScript | V8 7.4.288.26
Flash | (Deaktiviert)
User-Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
Befehlszeile | /usr/lib/brave-bin/brave --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=NewExtensionUpdaterService,DesktopPWAWindowing,fill-on-account-select --disable-features=AutofillServerCommunication,DefaultEnableOopRasterization,AudioServiceOutOfProcess,AutofillSaveCardSignInAfterLocalSave,NetworkService,UnifiedConsent --flag-switches-begin --flag-switches-end
Ausführbarer Pfad | /usr/lib/brave-bin/brave
Profilpfad | /home/ken/.config/BraveSoftware/Brave-Browser/Default
Varianten | c134752e-f685ead32c707b42-dcf7018a411b6d4e-3f4a17dfd01ab0d3-5ac89438927cedd-3f4a17dfb0271b40-360900151a0d11d4-2f9febdf16e0dd70-3f4a17dfba11b117-5b05287a4ca682fe-3f4a17df4b8c3f4-3f4a17dfb7e2524c-c92d551c411c711e-3f4a17df6c18ba9d-3f4a17df8f029c91-3f4a17df8982496f-3f4a17df61832c80-3f4a17dfcc20827f-77c422c591560a-29acad42db4845-ace4e1389853922b-3f4a17df7038b844-3f4a17df9ca1387e-3f4a17df776de70c-e0278d3ded9149a9-3f4a17df34d450b1-3f4a17dfd8343fa3-3f4a17dfb517d646-3f4a17df8ee5ed19-c3125ea274658432-fa79b94c9e201a2b-3f4a17df591576c8-3f4a17df5274eb09-3f4a17dfd6d4ee9a-3f4a17dfceff87ec-3f4a17dfdac832a5-3f4a17df44827ee5-3f4a17df3f79ac13-3d47f4f48f1e27f-3f4a17df345b5b61-3f4a17df5485fc4d-3f4a17df93731dca-ba4d7bd29b4c4257-3f4a17df8fa604e0-ace4e13843f62d3b-3f4a17df165e16d1-3f4a17df9e5c75f1-30e1b12b2594bdf4-3f4a17df6fa07eb4-7282ca762981bcb4-3f4a17df5139837c-3f4a17df4934552d-3f4a17df7f8176d9-3f4a17df9504402-3f4a17df73a8d7f1-1b1a7908f7217a71-b204717823a898eb-fc93cf742b08b14-3f4a17df7a5ba892-3f4a17dfd1cd70a5-3f4a17df4ea303a6-3f4a17dfac8d4708-5460eccbb19465ab-b19465abe5373d71-e23a25d96e6e0c7e-3f17a7d895876445-2b71ffe42b33233e-881ca6c94da5ae82-3f4a17df56302f8c-2f882e70e3981599-f9910918fd56acdf-3f4a17df3dba712-a2d707c64750a89c-60f3cfdacec9a952-9a6c5085f56e0452-3f4a17df8576baf1-3f4a17dfd00fcbde-3f4a17df930e30f5-3f4a17df9a2f4e5b-9ded16b91354da85-f1a864dc494d8760-3f4a17dff9e5da91-508355f5fcdd9ed9-fcdd9ed985963571-859635713a4029d-d7f231f3b0ea13bc-3f4a17df47a2af3f-3f4a17df94e68624-803f8fc4cc73f8a1-3f4a17dfb4e8892d-a2d707c67e91b7bd-c6da37cb6204e469-3f4a17df41ddf744-c78ce173

brave://version/ does not show GPU, but I suspesct this is far more important:
GPU Nvidia 1060GTX, Driver: nvidia 418.74
OS: Arch Linux
uname -r 5.0.13-arch1-1-ARCH
Desktop:  i3 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

-> no access to other version then official

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
-> no
- Does the issue resolve itself when disabling Brave Rewards?
-> no
- Is the issue reproducible on the latest version of Chrome?

-> NO, works perfectly Version 74.0.3729.131 (Offizieller Build) Arch Linux (64-Bit)

## Miscellaneous Information:

runing brave in console prints this error after resume fail:

"[5173:5173:0514/182502.262270:ERROR:raster_decosterDecoder context lost via ARB/EXT_robustness GL_UNKNOWN_CONTEXT_RESET_KHR
[5173:5173:0514/182502.262298:ERROR:raster_decoasterDecoderImpl: Context reset detected after 
[5173:5173:0514/182502.262312:ERROR:gpu_servicexiting GPU process because some drivers can't rrs. GPU process will restart shortly."

But this will never "restart shorty" but hang forever

**Comment by rebron** [comment] 2019-05-24 16:18
cc: @kjozwiak and @srirambv to reproduce

**Comment by srirambv** [comment] 2019-06-12 12:19
Haven't been able to reproduce this exactly. In general Linux has a slowness when coming out of hibernation(maybe its  just too lazy to work after waking up) but haven't seen any slowness or freeze in the app. Had Dev and Release profiles running when device went to sleep and worked fine after waking up

**Comment by FuckMicr0soft** [comment] 2019-06-12 13:50
Nothing I can add to help. 100% reproducible on my i3 tiling and also xfce4 desktop (just for cross checking). It's not slow, the process is dead and needs to be killed. Maybe you guys are not running latest kernel + nvidia drivers (or the inital mentioned ones)?
uname -r : 5.1.8-arch1-1-ARCH
nvidia 430.26-1
I did a screen capture, but it just shows the frozen window with 100% cpu in htop and the error prints from the console. So nothing new. ( Firefox, Chromium are not effected) Maybe I'll report on Arch bug tracker. Thanks for testing though.

**Comment by kjozwiak** [comment] 2019-08-07 06:03
@FuckMicr0soft, are you still experiencing the above issue? Maybe it was fixed in one of the Chromium bumps since originally reported?

**Comment by FuckMicr0soft** [comment] 2019-08-07 12:11
Hi all, chromium itself was never effected. I can not reproduce on Intel GPUs , the only one I have right now... I'd like to wait until I have access to my main PC with Nvidia descrete GPU again.

**Comment by FuckMicr0soft** [comment] 2019-11-01 18:13
Still freezing. 100% reproducable on Arch Linux
Brave Version 0.70.121 Chromium: 78.0.3904.70 
nvidia driver 435.21
linux kernel 5.3.7

**Comment by DontTrustMicrosoft-MicrosoftIsAsshole** [comment] 2020-04-28 18:00
Can't reproduce anymore. Everything works as expected!
kernel 5.6.7-arch1-1
nvidia 440.82-1
brave  Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) unknown (64-bit)
Thanks for closing

**Closed** 2020-04-28 18:00 UTC
Labels: OS/Linux, needs-investigation
