### ISSUE TITLE
Changing href of settings, history, etc icons located on homepage from chrome://..... to brave://..... 

### ISSUE THREAD

**Issue by uraashif** [brave/brave-browser#25467] opened 2022-09-18 07:20 UTC
## Description 

On homepage of browser, the history, settings etc icons having href value as `chrome://......` but after clicking on them it's taking to `brave://......`. If possible, change it to `brave://......` on homepage.

![Screenshot 2022-09-18 124533](https://user-images.githubusercontent.com/48546357/190890530-31369a50-c6eb-4a98-9659-15d4f9495eec.png)

**Comment by mbiesiad** [comment] 2022-09-18 14:06
Confirmed. Good catch! @uraashif 
Overall, brave://settings/ - `leftMenu` or `nav-items` shows `chrome://` instead of `brave://`

Best wishes,

**Comment by uraashif** [comment] 2022-09-18 14:58
Yeah in settings also!

**Comment by rebron** [comment] 2022-09-23 17:35
Closing as dupe of https://github.com/brave/brave-browser/issues/2566 +1 for you

**Closed by rebron** 2022-09-23 17:35 UTC
Labels: OS/Desktop
