### ISSUE TITLE
Twitter Push Notifications "Unsupported Browser"

### ISSUE THREAD

**Issue by Areckleh** [brave/brave-browser#20869] opened 2022-02-03 15:15 UTC
## Description 
Enabling Twitter push notifications from the Browser returns "Unsupported Browser".

## Steps to Reproduce

   1. Open Twitter Settings
   2. Enable push notifications

## Actual result:
Browser returns "Unsupported Browser"
![image](https://user-images.githubusercontent.com/43886134/152368604-5ca6e1fd-cc62-4c33-bab9-e99ed04952ed.png)

## Expected result:
Receive Twitter push notifications from the Brave browser.

## Brave version (brave://version info)

Brave | 1.34.81 Chromium: 97.0.4692.99 (Official Build) (arm64)
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | macOS Version 12.0.1 (Build 21A559)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Not enabled
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by stephendonner** [comment] 2022-02-04 06:17
Hi @Areckleh can you try toggling the `Use Google services for push notifications` preference to `ON`, as shown below.

Restart, try again, if you would, and report back as to whether that works?  Thanks!

<img width="1782" alt="Screen Shot 2022-02-03 at 10 15 31 PM" src="https://user-images.githubusercontent.com/387249/152481551-58d644af-0a75-40a3-b81b-3d5516d7c5a4.png">

**Comment by srirambv** [comment] 2022-02-04 11:12
Dupe of #14612

**Closed by srirambv** 2022-02-04 11:12 UTC
Labels: OS/Desktop

**Comment by Areckleh** [comment] 2022-04-20 21:24
@srirambv After enabling and relaunching the browser it I noticed that my tabs showed this behavior and the pages were blank (including Github). I had to toggle the setting back off.
<img width="1292" alt="Screen Shot 2022-04-20 at 4 22 29 PM" src="https://user-images.githubusercontent.com/43886134/164325437-4dde7155-7d78-4139-8d74-a1de4f98b68d.png">
