### ISSUE TITLE
Fix deps *brave_process* target in //brave/browser/

### ISSUE THREAD

**Issue by Gyuyoung** [brave/brave-browser#12084] opened 2020-10-12 02:06 UTC
```
$ gn check . //brave/browser/*
ERROR at //brave/browser/brave_rewards/extension_rewards_service_observer.cc:15:11: Include not allowed.
#include "chrome/browser/profiles/profile.h"
          ^--------------------------------
It is not in any dependency of
  //brave/browser:browser_process
The include file is in the target(s):
  //chrome/browser:browser
which should somehow be reachable.
___________________
ERROR at //brave/browser/brave_rewards/extension_rewards_notification_service_observer.cc:13:11: Include not allowed.
#include "chrome/browser/profiles/profile.h"
          ^--------------------------------
It is not in any dependency of
  //brave/browser:browser_process
The include file is in the target(s):
  //chrome/browser:browser
which should somehow be reachable.
___________________
ERROR at //brave/browser/brave_drm_tab_helper.cc:13:11: Include not allowed.
#include "chrome/browser/browser_process_impl.h"
          ^------------------------------------
It is not in any dependency of
  //brave/browser:browser_process
The include file is in the target(s):
  //chrome/browser:browser
which should somehow be reachable.
___________________
ERROR at //brave/browser/brave_drm_tab_helper.cc:14:11: Include not allowed.
#include "chrome/browser/profiles/profile.h"
          ^--------------------------------
It is not in any dependency of
  //brave/browser:browser_process
The include file is in the target(s):
  //chrome/browser:browser
which should somehow be reachable.
___________________
ERROR at //brave/browser/brave_content_browser_client.h:14:11: Include not allowed.
#include "chrome/browser/chrome_content_browser_client.h"
          ^---------------------------------------------
It is not in any dependency of
  //brave/browser:browser_process
The include file is in the target(s):
  //chrome/browser:browser
which should somehow be reachable.

```

**Comment by mariospr** [comment] 2021-04-21 11:12
Closing this one as it's a duplicate of https://github.com/brave/brave-browser/issues/12623

**Closed by mariospr** 2021-04-21 11:12 UTC
Labels: OS/Desktop, dev-concern
