### ISSUE TITLE
Brave Shields is breaking smooth zooming on Google Maps

### ISSUE THREAD

**Issue by DannyyyOnGit** [brave/brave-browser#38010] opened 2024-05-02 05:47 UTC
## Description 
Zooming the map in and out usually has a smooth transition between each level but it breaks when Brave Shields is enabled. 

## Steps to Reproduce

   1. Visit: https://www.google.com/maps (with Brave Shields enabled)
   2. Go to any location
   3. Use Mousewheel to zoom in/out

## Actual result:
There is no smooth transition effect between Map zoom levels.

## Expected result:
There should be a smooth transition effect like it is with Brave Shields disabled.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.65.126 Chromium: 124.0.6367.118 (Official Build) (64-bit) 

## Version/Channel Information:
Unsure if this is a regression or not but it might be.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
Yes

## Miscellaneous Information:
I'm using Windows 10. Testers might want to try out Linux and OSX as well.

**Comment by kassi** [comment] 2024-05-02 15:04
Same on MacOS after update to Version 1.65.126 Chromium: 124.0.6367.118 (Offizieller Build) (arm64).

**Comment by TEMP-ad** [comment] 2024-05-02 16:44
This happens because of `brave-google-maps-fix.js` scriptlet.

Since that was added in the lists in https://github.com/brave/adblock-lists/blob/master/brave-lists/brave-specific.txt then not much can be done unless it is reverted, because it is a default list.
In my opinion these type of scriptlets should first go to the experimental rules, at least, to see how it performed and if it didn't break anything bigger like it did.

The problem is simple, what would be better: to have misaligned route icons or not a smooth performance? this won't be fixed if you turn Fingerprinting off, because it has to do with the scriptlet, but just turning the fingerprinting (canvas) off, would fix the issue without that rule.

So I don't know why it hasn't been removed from brave-specific and find a better workaround.

For anyone who doesn't know, Brave adblocker supports adding scriptlet exceptions, the problem is, it only works when the rules are on the same _engine_.
There is t he _Regional/custom lists_ engine and the _Default_ engine, so you could add a exception like: `google.*#@#+js(brave-google-maps-fix)`, but can't be done today without turning the Default lists off and load them as custom lists, which can also cause some small issues in some instances with some rules. But this is why you can't do much about it.

**Comment by TEMP-ad** [comment] 2024-05-02 16:44
@arthuredelstein I tag you since you created the scriptlet and added the adblocking rule. In case you are not aware of this.

**Comment by rebron** [comment] 2024-05-02 21:14
cc: @ShivanKaul

**Comment by ShivanKaul** [comment] 2024-05-02 21:40
This should be fixed now with the revert: https://github.com/brave/adblock-lists/pull/1707

**Comment by NayamAmarshe** [comment] 2024-05-11 05:24
Not just smooth zoom, it lags a lot (on M1 Mac) with or without the shield! Google maps is totally unusable for me. It works absolutely fine on Firefox and Safari.

**Comment by ShivanKaul** [comment] 2024-05-11 06:26
Can you try updating the browser to the latest version and checking if that fixes it?

**Comment by NayamAmarshe** [comment] 2024-05-11 11:16
> Can you try updating the browser to the latest version and checking if that fixes it?

I created a new issue here: https://github.com/brave/brave-browser/issues/38241

As the issue I'm having is reproducible even without the shields and even on Chrome.

**Comment by ShivanKaul** [comment] 2024-05-11 14:36
That might have to do with your hardware acceleration then. In any case, doesn't look related to Brave Shields or Brave if you have the issue on Chrome too. Closing.

**Closed** 2024-05-11 14:36 UTC
Labels: closed/duplicate, google, OS/Desktop

**Comment by martinandersson** [comment] 2024-12-12 06:02
Please reopen. @NayamAmarshe may have a separate issue, but is not the ticket creator @DannyyyOnGit.

I also wish to add that I am having the same issue, on Brave version 1.73.101. Zooming is so laggy Google Maps is unusable. Graphics acceleration is enabled.

On Chrome everything works just fine.

**Comment by bug-Nihad** [comment] 2026-05-06 14:52
Enable smooth scrolling from here. 
brave://flags/#smooth-scrolling
It worked for me.
