### ISSUE TITLE
Creating a Solana Account via panel doesn't switch to Solana network/account 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22909] opened 2022-05-18 04:31 UTC
## Description 

Creating a Solana Account via panel doesn't switch to Solana network/account. 

## Steps to Reproduce

   1. Clean profile on 1.40.64 build
   2. Open wallet and switch to accounts tab
   3. Select panel and click on network
   4. Select Solana so create account prompt is shown
   5. Select Yes, Solana wallet is created but still retains to Ethereum

## Actual result:

https://user-images.githubusercontent.com/17010094/168957447-1a3c23d8-01f8-4ef4-aa44-909ff289a259.mov

## Expected result:
Should switch to Solana Account after its created

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.40.64 Chromium: 102.0.5005.50 (Official Build) nightly (64-bit)
-- | --
Revision | `f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}`
OS | Windows 11 Version 22H2 (Build 22621.1)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by Douglashdaniel** [comment] 2022-05-18 05:48
Is there some other step that you are taking to reproduce this?
I'm not seeing on `1.40.64`

https://user-images.githubusercontent.com/40611140/168966248-963e0150-4366-4a08-8e0d-bdefd0b1fb9a.mov

**Comment by srirambv** [comment] 2022-05-20 07:40
No specific steps. I just select Accounts and then create a new Soalana Account. I can see the Solana account getting created and then switches to Ethereum. This happens on RC build as well. 

https://user-images.githubusercontent.com/17010094/169478454-fec054ce-12c2-4a3e-91ea-17569434c893.mov

**Comment by srirambv** [comment] 2022-05-20 07:58
@Douglashdaniel FWIW I was able to repro it on macOS as well but just happened once and not all the time similar to Windows

**Comment by Douglashdaniel** [comment] 2023-02-22 20:53
Closing since we now create `Solana` accounts by default on `Wallet` creation.
Tested with `Filecoin` though and is working as expected.

https://user-images.githubusercontent.com/40611140/220756267-7fa1daa3-0605-4514-8ba4-42bc6492e939.mov

**Closed by Douglashdaniel** 2023-02-22 20:53 UTC
Labels: bug, needs-investigation, priority/P3, QA/Yes, closed/not-actionable, feature/web3/wallet, OS/Desktop, front-end-change
