### ISSUE TITLE
`Load new content` button doesn't appear to work, and remains after click

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26265] opened 2022-10-26 02:09 UTC
## Description 

`Load new content` button doesn't appear to work, and remains after click

This is pretty similar to https://github.com/brave/brave-browser/issues/20409, but that's on Android

## Steps to Reproduce

   1. install `1.47.14`
   2. launch Brave
   3. open `brave://flags`
   4. set `brave://flags/#brave-news-v2` to `Enabled`
   5. click `Relaunch`
   6. open a new-tab page
   7. click `Customize`
   8. click `Turn on Brave News`
   9. click on `Follow` on the `Brave` channel
   10. click to `Unfollow` the `Top Sources` category/channel
   11. dismiss the dialog
   12. wait
   13. when it appears, click on `Load new content`
   14. nothing (seemingly) happens

## Actual result:

Nothing seems to happen, and the `Load new content` button doesn't dismiss, either

## Expected result:

It should at least dismiss, if it can't find new content

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.14 Chromium: 107.0.5304.62 (Official Build) nightly (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @mattmcalister @rebron @fallaciousreasoning @petemill @srirambv

**Comment by fallaciousreasoning** [comment] 2022-10-31 01:14
I think this should be fixed now the backend has been updated. I just tested and couldn't reproduce.

**Closed by fallaciousreasoning** 2022-10-31 01:14 UTC
Labels: bug, QA/Yes, QA/Test-Plan-Specified, OS/Desktop, feature/brave-news
