### ISSUE TITLE
Sign-In Authentication Does not work on Google Keep App

### ISSUE THREAD

**Issue by cosmeao** [brave/brave-browser#8908] opened 2020-03-29 14:50 UTC
## Description 
Official Google Keep - Notes and Lists app/extension found in the Chrome Web Store does not allow for signing in. Upon opening of the Brave/Chrome app a pop-up appears letting the user know that it has failed to authenticate credential and that one should sign in. One clicks the provided "Sign-In" button, the popup disappears, and then no sign-in screen/tab/window opens -- essentially nothing happens. Without being able to sign-in, I have no access to my notes. The problem does not occur on the official Google Chrome browser.

Link to App/Extension: https://chrome.google.com/webstore/detail/google-keep-notes-and-lis/hmjkmjkepdijhoojdojkdfohbdgmmhki?hl=en

## Steps to Reproduce

   1. Open Brave
   2. Navigate to Chrome Web Store: 
   3. Search and navigate to the official Google Keep - Notes and Lists app install landing page.
   4. Install  Google Keep - Notes and Lists app on Brave.
   5. Open Google Keep - Notes and Lists app.
   6. Click on the "Sign-In" button after a failed authentication.
   7. Nothing happens.

## Actual result:
Nothing happens when clicking the provided "Sign-In" button. 

## Expected result:
Opening of a secondary screen/tab/window to enter login credentials.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Any Brave version, Any OS.

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Nope
- Does the issue resolve itself when disabling Brave Rewards? Nope
- Is the issue reproducible on the latest version of Chrome? Nope, works great on Chrome!

**Comment by kjozwiak** [comment] 2020-03-30 22:49
@cosmeao thanks for filing this? Going to close this off as a duplicate of https://github.com/brave/brave-browser/issues/3650. Can you head into that GH issue and a +1? Thanks!

**Closed by kjozwiak** 2020-03-30 22:49 UTC
