### ISSUE TITLE
declarativeNetRequest Rules don't get added on browser launch

### ISSUE THREAD

**Issue by ericplane** [brave/brave-browser#30854] opened 2023-06-06 12:18 UTC
## Description 
Whenever using a chrome extension which adds declarativeNetRequest rules it will only work after reloading the extension after browser startup. Brave doesn't check for these rules on browser startup so I need to reload the extension to get it to work allowing the content security policies rather than blocking them.

## Steps to Reproduce

   1. Have a Chrome Extension which uses declarativeNetRequests (Manifest v3)
   2. Restart your browser
   3. You will now see that whatever that extension was adding to a website is not getting added until you reload that extension. (Just shows content-security-policy errors in Console)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.52.119 Chromium: 114.0.5735.90 (Official Build) (64-bit) 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
Only is an issue on the latest Brave not Chromium (Google Chrome, etc works normally)

**Comment by rebron** [comment] 2023-06-09 18:51
@ericplaneRBLX Do you have a pointer to an extension that we can look at?

**Comment by ericplaneRBLX** [comment] 2023-06-09 19:21
The extension I used to find out about this issue is a subscription based extension so I don't really. The only thing I could offer is screensharing the issue and such via Discord.

**Comment by ericplaneRBLX** [comment] 2023-06-09 19:29
@rebron The extension I used to find out about this issue is a subscription based extension so I don't really. The only thing I could offer is screensharing the issue and such via Discord.

**Comment by ericplaneRBLX** [comment] 2023-06-09 19:42
The issue only appears in exensions with Manifest v3 and when using the declarativenetrequest feature of the manifest linking it to a json table with all the rules works fine but when you restart your browser you get content-security policy errors and all the svgs don't load from a third-party website but everything else works.

**Comment by papegaaij** [comment] 2023-06-11 19:29
Users from our extension report this same issue. The code that registers the rules is not very complicated. It is placed in the main body of the service worker script and looks like this:
```
if (chrome.declarativeNetRequest) {
    chrome.runtime.onInstalled.addListener((details) => {
        const RULES = [ ... ];
        chrome.declarativeNetRequest.updateDynamicRules({
            removeRuleIds: RULES.map(r => r.id),
            addRules: RULES,
        });
    });
}
```

**Comment by nrothGIT** [comment] 2023-06-13 04:55
Hey we think we're maybe seeing a related/the same issue:

We've a simple brave/chrome extension (for you.com) that basically lets the user toggle their default search engine preferences via extension. The gist of the code is below, but basically a user can send a message for a couple different things and the rulesets (which redirect your default search to the appropriate endpoint) are set below.

```
} else if (req === "code") {
    chrome.declarativeNetRequest.updateEnabledRulesets({
      enableRulesetIds: ["ruleset_1"],
      disableRulesetIds: ["ruleset_2", "ruleset_3", "ruleset_4"],
    });
    chrome.tabs.create({ url: "https://code.you.com/" });
  } else if (req === "youchat") {
    chrome.declarativeNetRequest.updateEnabledRulesets({
      enableRulesetIds: ["ruleset_3"],
      disableRulesetIds: ["ruleset_1", "ruleset_2", "ruleset_4"],
    });
    chrome.tabs.create({
      url: "https://you.com/search?q=" + queries[index] + "&tbm=youchat",
    });
  }
```

We think this was working fine until quite recently, but now is a no-op, in that rulesets don't seem to get changed despite message going through. This still works on slightly older versions of Brave (haven't pinned down exact breaking point yet) so seems perhaps related to a recent change? it continues to work fine on Edge/Chrome.

If it helps, the code/published extension is here with that pinned commit: 

https://github.com/You-OpenSource/You-Chrome-Extension/blob/e61ddc713217098f752eeafe2883ccee8fd00c7b/public/background.js


Thanks so much for all you do, Brave is great!

**Comment by andrzejgrzelak** [comment] 2023-07-02 16:22
@rebron I just linked an issue to a simple extension that is not working because of that bug.

**Comment by haozi** [comment] 2023-07-10 07:07
Waiting for the Brave's team to resolve

**Comment by kokofixcomputers** [comment] 2023-07-13 20:07
> @ericplaneRBLX Do you have a pointer to an extension that we can look at?

You can try scratch addons just get some messages on your scratch account then open scratch addons then try to mark messages as read. It works on Chrome but not on Brave

**Comment by ericplaneRBLX** [comment] 2023-08-18 22:29
@rebron Any update on this? It's been almost 3 months and it's a big issue when owning an extension.

**Comment by Kulsgam** [comment] 2023-08-20 10:20
I found a temporary hack which can solve this. In the manifest specify a content script, which sends a certain message "x" to the background script. Then for that message run `chrome.runtime.reload()`.

**Comment by haozi** [comment] 2023-08-22 12:40
> I found a temporary hack which can solve this. In the manifest specify a content script, which sends a certain message "x" to the background script. Then for that message run `chrome.runtime.reload()`.

But, how do it only once?

**Comment by Kulsgam** [comment] 2023-08-29 01:36
> > I found a temporary hack which can solve this. In the manifest specify a content script, which sends a certain message "x" to the background script. Then for that message run `chrome.runtime.reload()`.
> 
> But, how do it only once?

Mind clarifying what you mean by once?
If you want an example you can check out the [source code](https://github.com/Kulsgam/Discord-type-indicator-blocker) of the extension I made

**Comment by pietervanheijningen** [comment] 2023-09-02 20:19
Would really appreciate a fix by now. My extension with 30k+ users has not been working in brave now for months because of this: https://github.com/pietervanheijningen/clickbait-remover-for-youtube/issues/56 

Really don't think brave should deviate much from standard chromium behaviour. Especially with the extension API.

**Comment by sharkiller** [comment] 2023-09-15 20:10
how is this not solved yet? its breaking so many manifest v3 extensions that use declarativeNetRequest.

static rules in brave is working the same as session rules, that get removed on a browser restart. static rules should be always active.  

i dont know why they ask for "more info" when is so easy to reproduce.

**Comment by komprimiert** [comment] 2023-10-08 21:32
> I found a temporary hack which can solve this. In the manifest specify a content script, which sends a certain message "x" to the background script. Then for that message run `chrome.runtime.reload()`.

this assumes that you have access to the extension right? because the extension I use isn't made by me

**Comment by Kulsgam** [comment] 2023-10-11 07:57
> > I found a temporary hack which can solve this. In the manifest specify a content script, which sends a certain message "x" to the background script. Then for that message run `chrome.runtime.reload()`.
> 
> this assumes that you have access to the extension right? because the extension I use isn't made by me

Yes, it can only be used for extensions you are developing.
If that extension isn't by you, maybe you can contact the developer or even mod the extension to support it for brave.
Or just wait until brave fixes this (spoiler - it's probably after GTA 6 gets released)

**Comment by jslay88** [comment] 2023-10-20 05:00
[Here is a repo for repro](https://github.com/jslay88/test_extension)

**Comment by carl-jin** [comment] 2023-10-24 12:37
Due to this issue, several of my extensions are unable to function properly, and I have received continuous 1-star ratings over the past week. This has caused significant harm to me. If you are willing to fix this problem, I am willing to generously pay a sum of money.

**Comment by kokofixcomputers** [comment] 2023-10-24 23:18
> > I found a temporary hack which can solve this. In the manifest specify a content script, which sends a certain message "x" to the background script. Then for that message run `chrome.runtime.reload()`.
> 
> this assumes that you have access to the extension right? because the extension I use isn't made by me

No... You don't need to write the extension yourself. Here is what i did based on the instructions to temporary resolve this:

1. Click the more button at the top-right
2. Click the extensions button
3. locate the extension that is having problems and click details (in my case ScratchAddons)
<img width="1364" alt="image" src="https://github.com/brave/brave-browser/assets/113046561/69a0b01a-d814-4110-9688-8ae75863a035">

4. Click the background process or if you only have one process click it (shown in the picture)
<img width="1074" alt="image" src="https://github.com/brave/brave-browser/assets/113046561/16ea51f0-3030-4e1b-a458-c234dcea6fa6">

5. a new window should open up, click console (shown in the picture)
<img width="1059" alt="image" src="https://github.com/brave/brave-browser/assets/113046561/843141bb-9b21-4962-b2a0-3c048768f415">
7. type in `chrome.runtime.reload()` and press enter
<img width="1039" alt="image" src="https://github.com/brave/brave-browser/assets/113046561/a3af0859-73f4-49ce-9099-fcfac1baa3b5">
8. Try using the extension again.

**Comment by komprimiert** [comment] 2023-10-25 00:32
> > > I found a temporary hack which can solve this. In the manifest specify a content script, which sends a certain message "x" to the background script. Then for that message run `chrome.runtime.reload()`.
> > 
> > 
> > this assumes that you have access to the extension right? because the extension I use isn't made by me
> 
> No... You don't need to write the extension yourself. Here is what i did based on the instructions to temporary resolve this:
> 
> 1. Click the more button at the top-right
> 2. Click the extensions button
> 3. locate the extension that is having problems and click details (in my case ScratchAddons)
> 
> <img alt="image" width="1364" src="https://user-images.githubusercontent.com/113046561/277830253-69a0b01a-d814-4110-9688-8ae75863a035.png">
> 4. Click the background process or if you only have one process click it (shown in the picture)
> 
> <img alt="image" width="1074" src="https://user-images.githubusercontent.com/113046561/277829078-16ea51f0-3030-4e1b-a458-c234dcea6fa6.png">
> 5. a new window should open up, click console (shown in the picture)
> 
> <img alt="image" width="1059" src="https://user-images.githubusercontent.com/113046561/277829317-843141bb-9b21-4962-b2a0-3c048768f415.png"> 7. type in `chrome.runtime.reload()` and press enter <img alt="image" width="1039" src="https://user-images.githubusercontent.com/113046561/277830437-a3af0859-73f4-49ce-9099-fcfac1baa3b5.png"> 8. Try using the extension again.

That seems like a good solution; unfortunately there isn't anything at all at inspect views for me.

**Comment by jslay88** [comment] 2023-10-25 00:38
This is no different than just flipping the toggle switch off and on, on
the extension itself…

**Comment by jslay88** [comment] 2023-10-27 15:43
@rebron I think there has been more than enough information collected within this issue to start triage. Can we please get the `needs-more-info` label removed and get the priority bumped?

**Comment by kokofixcomputers** [comment] 2023-10-27 18:35
Yes. There is already enough information about this and has been complained for a long time.

**Comment by kokofixcomputers** [comment] 2023-10-27 18:37
@komprimiert Can you give some screenshots?

**Comment by komprimiert** [comment] 2023-10-27 19:54
@kokofixcomputers I mean as mentioned method 2 works for me though but yes:
![image](https://github.com/brave/brave-browser/assets/82711003/bd8fb4fa-0e11-4e77-aa12-d48f89855d6c)

**Comment by kokofixcomputers** [comment] 2023-10-28 03:00
> @kokofixcomputers I mean as mentioned method 2 works for me though but yes: ![image](https://user-images.githubusercontent.com/82711003/278746396-bd8fb4fa-0e11-4e77-aa12-d48f89855d6c.png)

Oh yes, I can see that there is no inspect views, sometimes when i open the extension popup and reload the extension details page you will see the inspect views. But... if method 2 works then you problobly don't have to worry about it

**Comment by Kulsgam** [comment] 2023-10-28 03:20
> Due to this issue, several of my extensions are unable to function properly, and I have received continuous 1-star ratings over the past week. This has caused significant harm to me. If you are willing to fix this problem, I am willing to generously pay a sum of money.

@carl-jin just use what I found -> https://github.com/brave/brave-browser/issues/30854#issuecomment-1696642903

**Comment by Emi-HoloGhostRevisionist88** [comment] 2023-11-07 08:59
Hi @bbondy,

Can Brave team prioritize a fix for this? As you can see there is enough information to reproduce this, but basically any extension with declarativeNetRequest will not work on start, so extensions have to be disabled and then re-enable for them to work, something not good for any user or even developers since they get people making issues for their extensions for something Brave is 100% at fault.

This issue started happening when Brave got Chromium 114 with build `Nightly v1.53.43 (Chromium 114.0.5735.26)` on **May 16th**, the previous version `Nightly v1.53.42 (Chromium 113.0.5672.92)` on May 15th worked fine with Manifestv3-declarativeNetRequest extensions.

It's been 175 days or 5 months 22 days since this started happening, almost half a year where many extensions have failed to work properly as they should. And while Google delayed the force of the Manifestv3, Brave should still work with them without issues.

**Comment by sharkiller** [comment] 2023-11-08 05:27
> > Due to this issue, several of my extensions are unable to function properly, and I have received continuous 1-star ratings over the past week. This has caused significant harm to me. If you are willing to fix this problem, I am willing to generously pay a sum of money.
> 
> @carl-jin just use what I found -> [#30854 (comment)](https://github.com/brave/brave-browser/issues/30854#issuecomment-1685247036) and [#30854 (comment)](https://github.com/brave/brave-browser/issues/30854#issuecomment-1696642903)

thats not a fix, and thats not even work when you do redirects. thats only work for injected code on pages. 
declarativeNetRequest do much more than just inject things in pages. they can edit headers, blocks, redirects...

**Comment by jslay88** [comment] 2023-11-09 23:05
@LaurenWags @kjozwiak @thypon @fmarier @aekeus @bbondy @BrendanEich @bsclifton @darkdh 

We shouldn't have to start @'ing C level people to get attention on an issue as small as this, but I feel like there is no other way to get any movement from Brave.

**Comment by sharkiller** [comment] 2023-11-09 23:08
is so funny how a core component of manifest v3 that is declarativeNetRequest is broken for more than 6 months... 
then people want to take brave seriously?

**Comment by jslay88** [comment] 2023-11-09 23:11
> is so funny how a core component of manifest v3 that is declarativeNetRequest is broken for more than 6 months... then people want to take brave seriously?

I know ignoring an issue which has been repro'd for months isn't that way at any software company I've worked for, works. Quite embarrassing to any other devs.

**Comment by kokofixcomputers** [comment] 2023-11-09 23:17
> > is so funny how a core component of manifest v3 that is declarativeNetRequest is broken for more than 6 months... then people want to take brave seriously?
> 
> I know ignoring an issue which has been repro'd for months isn't that way at any software company I've worked for, works. Quite embarrassing to any other devs.

Yeah... It's weird.

**Comment by bsclifton** [comment] 2023-11-10 02:52
Hi folks!

Thanks for the loads of good information! Since we have enough info here, I've cleaned up the comments a bit. Thanks to those that shared information, repro steps, and screenshots. We'll work on getting this prioritized

I've assigned a P3 for now - stay tuned for updates. I'll unlock this again after things cool down a bit

**Closed** 2024-01-04 13:53 UTC
Labels: bug, feature/extensions, priority/P3, OS/Desktop

**Comment by goodov** [comment] 2024-01-08 08:09
Hey everyone! This is now fixed in `nightly` starting with version `1.63.94`. After some testing we might uplift it into `beta`/`release` channels.

**Comment by goodov** [comment] 2024-01-08 08:13
Test case:

1. Install https://chromewebstore.google.com/detail/clickbait-remover-for-you/omoinegiohhgbikclijaniebjpkeopip
2. Ensure it works on `youtube.com`
3. Restart the browser
4. Ensure the extension still works as expected

The step (4) failed on versions prior to `1.63.94`, i.e. extension didn't work without manual off/on on `brave://extensions/`.

**Comment by stephendonner** [comment] 2024-01-08 23:31
## Verified `PASSED` using 

```
Brave | 1.63.102 Chromium: 120.0.6099.199 (Official Build) nightly (x86_64)
-- | --
Revision | e04c47f4648bb8a13cad74d386e61d33a80d70be
OS | macOS Version 14.3 (Build 23D5043d)
```

### Steps:
1. installed `1.63.102`
2. launched Brave
3. installed `https://chromewebstore.google.com/detail/clickbait-remover-for-you/omoinegiohhgbikclijaniebjpkeopip`
4. loaded `youtube.com`
5. played a video
6. restarted Brave
7. played a different video
8. opened `brave://extensions`

### Confirmed I was able to use the provided extension both before and after restart, without additional tweaks

example | example | example | example | example | example
---------|----------|---------|----------|---------|---------
<img width="1312" alt="Screenshot 2024-01-08 at 3 24 39 PM" src="https://github.com/brave/brave-browser/assets/387249/d3490b31-4893-4b1a-9aec-1464ebcab042"> | <img width="1312" alt="Screenshot 2024-01-08 at 3 24 42 PM" src="https://github.com/brave/brave-browser/assets/387249/dfcbb7e0-b7b7-4c0d-b5a7-b314d9c1f3be"> | <img width="1312" alt="Screenshot 2024-01-08 at 3 24 45 PM" src="https://github.com/brave/brave-browser/assets/387249/cadcb057-db27-4735-8e21-27edcff1efb9"> | <img width="1312" alt="Screenshot 2024-01-08 at 3 25 10 PM" src="https://github.com/brave/brave-browser/assets/387249/c7205c9c-4a31-4bb5-ad7e-25174cb0554b"> | <img width="1312" alt="Screenshot 2024-01-08 at 3 25 27 PM" src="https://github.com/brave/brave-browser/assets/387249/9bd51253-9aac-43d9-95ea-03d30dcce296"> | <img width="1312" alt="Screenshot 2024-01-08 at 3 25 41 PM" src="https://github.com/brave/brave-browser/assets/387249/633e16bd-3dbd-4350-a80c-2576ceac84fa">

**Comment by leteaaDEV** [comment] 2024-01-25 04:43
When is it expected to get released in latest builds?

**Comment by bsclifton** [comment] 2024-01-25 06:01
Hi @leteaaDEV - this is merged already into both Nightly and Beta builds. 
1.63 is scheduled to hit Release channel on February 20th

**Comment by MadhaviSeelam** [comment] 2024-01-27 00:21
Verification `In progress` using
```
Brave | 1.63.134 Chromium: 121.0.6167.85 (Official Build) beta (64-bit)
-- | --
Revision | cdcba6ef408b305ce19b1a9b3fabbb5e9e3b36bf
OS | Windows 11 Version 23H2 (Build 22631.3085)
```
### Steps:
1. installed `1.63.134`
2. launched Brave
3. installed `https://chromewebstore.google.com/detail/clickbait-remover-for-you/omoinegiohhgbikclijaniebjpkeopip`
4. loaded `youtube.com`
5. played a video
6. restarted Brave
7. played a different video
8. opened `brave://extensions`

example | example | example 
---------|----------|--------- 
![image](https://github.com/brave/brave-browser/assets/98358127/80491cbd-f9c4-48e4-910c-80e89e9078aa)|![image](https://github.com/brave/brave-browser/assets/98358127/384a2fd4-81e9-4b4a-b607-b9876d7cc95f)|![image](https://github.com/brave/brave-browser/assets/98358127/500e1900-0562-4967-b408-d96528826278)

**Comment by ESUITDEV** [comment] 2024-01-28 03:53
This issue still exists in the latest version of Brave.
Brave:  v1.62.153
sys: MacOS v13.1
ext: https://chromewebstore.google.com/detail/esuit-ad-blocker-for-face/jkbklfkombochacjoeagggbiohipcbaj

This extension uses declarativeNetRequest to define rules that remove Facebook's CSP rules, but when I use cmd + q to exit Brave and then reopen the Brave browser to visit the FB page, declarativeNetRequest does not take any effect on FB. I have to manually disable this extension and then re-enable it in order for the declarativeNetRequest rules to be applied correctly.

I have now reported this issue to the users and have been working to get them back to Chrome as at least Chrome provides stable support.

**Comment by ericplane** [comment] 2024-01-28 08:32
Hello @ESUITDEV the fix is currently only in nightly and beta builds 1.63 the devs said it will be in the release build which will drop around February 20th.

**Comment by kjozwiak** [comment] 2024-01-30 07:47
The above requires `1.62.155` or higher for `1.62.x` verification 👍

**Comment by LaurenWags** [comment] 2024-01-30 12:43
Removed `QA/Test-All-Platforms` - per discussion with @goodov QA will check this on Windows and macOS.

cc @brave/qa-team

**Comment by MadhaviSeelam** [comment] 2024-01-30 17:38
Verification `PASSED` using
```
Brave | 1.62.155 Chromium: 121.0.6167.85 (Official Build) (64-bit)
-- | --
Revision | 91c989228daf153ef41bd965f268fabc7b9dbbf0
OS | Windows 11 Version 23H2 (Build 22631.3085)
```

Reproduced the issue from https://github.com/brave/brave-browser/issues/30854#issuecomment-1880542650


1.62.153 before browser restart | 1.62.153 after browser restart | 1.62.153 after extension toggle off/on
-- | -- | --
![image](https://github.com/brave/brave-browser/assets/98358127/26463b39-7404-4bae-bd9a-f851285580ef)|![image](https://github.com/brave/brave-browser/assets/98358127/0fef3a32-f6ca-4ccb-a074-dfd0b0ee0830)|![image](https://github.com/brave/brave-browser/assets/98358127/3310159b-2cd3-4586-9758-783c2f738515)

Clean profile: 

1. installed 1.62.153
2. launched Brave
3. installed https://chromewebstore.google.com/detail/clickbait-remover-for-you/omoinegiohhgbikclijaniebjpkeopip
4. loaded youtube.com
5. played a video
6. restarted Brave

### Confirmed extension worked as expected without manual toggle off/on

example | example 
----- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/6d605bd7-43b3-47f7-840e-2da3adf38bb7)|![image](https://github.com/brave/brave-browser/assets/98358127/ff274378-34c8-4bec-a9e4-953cfb2eb32d)


Upgrade: 

1. Installed 1.62.153
2. launched Brave
3. installed `https://chromewebstore.google.com/detail/clickbait-remover-for-you/omoinegiohhgbikclijaniebjpkeopip`
4. loaded youtube.com videos
5. restarted browser
6. upgraded to 1.62.155

### Confirmed extension worked as expected without manual toggle off/on
### Confirmed when selected option of `lowercase` title shown correct case

before restarting browser | restart browser | After upgrade w/out extension toggle restart
----- | ----- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/dcfcd788-d2c0-4625-8ec4-6175f6d8e8c5)|![image](https://github.com/brave/brave-browser/assets/98358127/0eb62cbf-6ac1-4767-8223-9f815e4fd07b)|![image](https://github.com/brave/brave-browser/assets/98358127/05c8dc91-aac8-4b86-834e-f762872a2e71)
