### ISSUE TITLE
Geolocation requests on private windows are a major privacy concern and can't be turned off

### ISSUE THREAD

**Issue by atlasshruggedbyaynrand** [brave/brave-browser#32276] opened 2023-08-16 01:29 UTC
## Description 
Ever since #24720, geolocation permissions are not inherited in private windows. What this effectively means is that:

1. There is no way to turn off geolocation requests in private windows.
2. This is default behavior and probably shouldn't be, even if an option to turn off geolocation requests in private windows is eventually added.

More than that, a website being ALLOWED to ask for your location in a private window is an absurd concept in and of itself. The fact that this is default behavior and can't be turned off on a browser that supposedly has privacy as its major selling point is simply laughable. According to #28136, this was a change done on purpose from Chromium upstream. Apparently, nobody thought of its consequences and this joke has been present in your codebase for an entire year now.

## Steps to Reproduce
1. Start private browsing
2. Ensure "Don't allow sites to see your location" is selected in settings
3. Visit site with geolocation, or run command `navigator.geolocation.getCurrentPosition(console.log)`

## Actual result:
Prompt appears, asking user to allow location query.

## Expected result:
User should not be prompted.

## Reproduces how often: 
Easily reproduced

## Desktop Brave version:
1.56.20

## Version/Channel Information:
-

## Other Additional Information:
-

## Miscellaneous Information:
Related issue: #28136. If you are an end-user annoyed by this, you can also find a temporary solution at #28136.

**Comment by diracdeltas** [comment] 2023-08-22 04:52
cc @pes10k

**Comment by pes10k** [comment] 2023-08-22 18:12
yes, we made the intentional choice to strengthen the protections that private browsing mode provides; its a clean, empty profile that is completely partitioned from your main profile. This is a decision with tradeoffs (the inconvenience of being prompted, vs the protection of a complete firewall between the main profile and the private profile), and we think this is the correct decision for the majority of our users.

If what you want though, is the ability to have some settings persist (such as disabling geolocation) but want cookies and other site-set storage to be automatically cleared when you close the browser (or site), our "forgetful browsing" feature solves exactly that use case.  Please see https://brave.com/privacy-updates/25-forgetful-browsing/

> …is simply laughable. 
> …nobody thought of its consequences and this joke has been present…

This is our work place. We greatly appreciate your feedback, issues, and bug reports, but it is not appropriate or welcome to be rude. Again, we're extremely grateful for feedback and your time, but if you'd like to continue participating in our issue tracking system, please avoid insults going forward

**Comment by pes10k** [comment] 2023-08-22 18:12
im closing this issue now since this is expected behavior, though will continue responding here if more dicussion would be helpful

**Closed by pes10k** 2023-08-22 18:12 UTC
Labels: privacy, OS/Android, OS/Desktop
