### ISSUE TITLE
Search string is replaced for duckduckgo upon upgrade in German locale

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6424] opened 2019-10-10 23:05 UTC
Follow up to https://github.com/brave/brave-browser/issues/6187

The expected behavior is based on https://github.com/brave/internal/issues/647

## Steps to Reproduce

   1. Set system locale to German/Germany
   2. Install 0.69.x https://github.com/brave/brave-browser/releases/tag/v0.69.123
   3. Check duckduckgo search string in `chrome://settings/searchEngines`
   4. Upgrade to 0.70.x
   5. Check duckduckgo search string in `chrome://settings/searchEngines`

## Actual result:
Search string is replaced after upgrade
Search string: `https://duckduckgo.com/?q=%s&t=bravened`
![image](https://user-images.githubusercontent.com/34715963/66612634-b0913580-ebc2-11e9-946c-9d9fc177fdea.png)

## Expected result:
Search string is not replaced after upgrade
Search string: `https://duckduckgo.com/?q=%s&t=brave`
![image](https://user-images.githubusercontent.com/34715963/66612459-25b03b00-ebc2-11e9-8335-fd695cdb3da8.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.70.112 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1903 (Build 18362.175)

Brave | 0.70.112 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron @bsclifton

**Comment by GeetaSarvadnya** [comment] 2019-10-14 12:12
The issue is NOT reproducible when upgrade build (DE/Germany) from in the latest released version 0.69.139 to 0.70.113
![image](https://user-images.githubusercontent.com/38657976/66750358-df9cf500-eea9-11e9-8106-0a9043bec0e4.png)

**Comment by LaurenWags** [comment] 2019-10-14 14:27
Reproduced on macOS when upgrading from `0.69.135` to `0.70.115`.

Prior to upgrade - using 0.69.135:
<img width="912" alt="Screen Shot 2019-10-14 at 10 21 10" src="https://user-images.githubusercontent.com/28145373/66758874-24566b00-ee6d-11e9-9a12-4fd19e020f3d.png">

After upgrade - using 0.70.115:
<img width="865" alt="Screen Shot 2019-10-14 at 10 25 38" src="https://user-images.githubusercontent.com/28145373/66758891-2b7d7900-ee6d-11e9-9b1e-8ffa4ec7b5e2.png">


Brave | 0.70.115 Chromium: 77.0.3865.90 (Offizieller Build) beta (64-Bit)
-- | --
Überarbeitung | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
Betriebssystem | macOS Version 10.13.6 (Build 17G5019)

**Comment by bsclifton** [comment] 2019-10-15 04:56
Closing in favor of https://github.com/brave/brave-browser/issues/6469

**Closed by bsclifton** 2019-10-15 04:56 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/search
