### ISSUE TITLE
claiming grant from NTP widget does not remove claim banner from brave://rewards

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6741] opened 2019-11-03 22:05 UTC
## Description 
If you claim a grant (UGP or Ads) from the NTP widget, the panel opens to claim the grant as expected and you can successfully claim from there. 

Then, if you go to brave://rewards, the claim banner is still there. Refresh of page and reopening the tab do not make the banner go away.

## Steps to Reproduce

   1. Clean profile (staging)
   2. Enable rewards.
   3. On widget, claim the UGP grant.
   4. Panel opens, complete captcha. Close successful message.
   5. Go to brave://rewards page.

## Actual result:
below is an example using Ad grant, but same thing happens for UGP grant:
<img width="429" alt="Screen Shot 2019-11-03 at 5 09 50 PM" src="https://user-images.githubusercontent.com/28145373/68092784-cfe74f80-fe5c-11e9-8b1b-41474867f51d.png">

If you attempt to claim from this banner and complete captcha, you get this:
<img width="417" alt="Screen Shot 2019-11-03 at 5 10 29 PM" src="https://user-images.githubusercontent.com/28145373/68092790-e1305c00-fe5c-11e9-97d9-e822a4f51a65.png">

## Expected result:
Once Ad or UGP grant is claimed, banner should not be shown on brave://rewards page

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.73.55 Chromium: 78.0.3904.87 (Official Build) nightly (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
cc @mandar-brave @ryanml @brave/legacy_qa

**Comment by LaurenWags** [comment] 2019-11-03 22:23
Note - Issue does not reproduce with the following STR:
1. Clean profile (staging)
2. Enable Rewards (used panel)
3. Saw BAT logo notification about UGP grant, clicked on BAT logo.
4. Clicked on 'Claim' button on panel notification
5. Completed captcha, got successful message. Closed successful message.
6. Navigated to brave://rewards page
--> no claim banner notification
<img width="1155" alt="Screen Shot 2019-11-03 at 5 23 11 PM" src="https://user-images.githubusercontent.com/28145373/68092948-a0d1dd80-fe5e-11e9-9979-066cad99fb56.png">

**Comment by mandar-brave** [comment] 2019-11-03 22:56
@NejcZdovc seems duplicate of the issue we were observing on iOS.
if there is a PR to fix that, that may fix the redundant grant claim issue.

**Comment by NejcZdovc** [comment] 2019-11-04 07:19
@mandar-brave this is a different issue as here we have old logic, where iOS has VG

**Closed** 2019-11-14 22:12 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/new-tab, feature/rewards

**Comment by btlechowski** [comment] 2019-12-04 00:44
Verification passed on

Brave | 1.3.50 Chromium: 79.0.3945.56 (Official Build) nightly (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Ubuntu 18.04 LTS

Verified test plan from the description.

![image](https://user-images.githubusercontent.com/34715963/70102176-a0805a00-1637-11ea-9553-79a3a24bad4d.png)
