### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by EatFecalMatterAndDie** [brave/brave-browser#25192] opened 2022-09-03 05:03 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.43.89  Chromium: 105.0.5195.102
Operating System: Windows NT 10.0.19044

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Click New Tab button in normal browsing session
2. Watch browser close

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/a3c30200-74c0-c508-0000-000000000000

**Comment by bsclifton** [comment] 2022-09-06 06:11
Thanks for the report! This is a duplicate of https://github.com/brave/brave-browser/issues/25156

**Closed by bsclifton** 2022-09-06 06:11 UTC
