### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by pentatonicfunk** [brave/brave-browser#34979] opened 2023-12-20 11:30 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.104 Chromium: 120.0.6099.115
Operating System: Mac OS X 14.2.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?
Consistenly when i use browser normally, with many tabs. But when i actually wanna reproduce with just opening random tabs, it doesn't crash.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Use browser as usual, open with many tabs
2. "Close tabs to the right"
3. Crashed

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/c99d0e00-100a-300b-0000-000000000000

Also discussed here: https://community.brave.com/t/crashed-quit-unexpectedly/521982

**Comment by rebron** [comment] 2023-12-21 17:59
closing as dupe of https://github.com/brave/brave-browser/issues/34909.
Hi @pentatonicfunk  Can you update to the latest 1.61.109 that released today and see if this is still an issue for you.

**Closed by rebron** 2023-12-21 17:59 UTC

**Comment by pentatonicfunk** [comment] 2023-12-22 10:32
updated, so far so good, been couple of hours in version 1.61.109 no crash yet.
Great job guys
