### ISSUE TITLE
Why the folder icon that shows in bookmarks bar doesn't show when we go to bookmark manager.

### ISSUE THREAD

**Issue by clicky6** [brave/brave-browser#18021] opened 2021-09-11 05:18 UTC
Why the folder icon that shows in bookmarks bar doesn't show when we go to bookmark manager (brave://bookmarks/).

Fix this issue the folder icon doesn't show up everywhere it only shows on bookmarks bar but doesn't show when we go to bookmark manager (brave://bookmarks/).
![100](https://user-images.githubusercontent.com/89839714/132937158-9672f089-a2b6-4507-9a02-2d9b7ca87b7d.png)
It is showing in bookmarks bar but why not showing in bookmark manager.
![99](https://user-images.githubusercontent.com/89839714/132937178-2ffffca7-4ffb-43a9-80f1-a43e9028592f.png)

**Comment by bsclifton** [comment] 2021-09-12 06:10
Thanks for the report @clicky6! I'm going to close this as a duplicate of https://github.com/brave/brave-browser/issues/7312

Subscribe there for updates

**Closed by bsclifton** 2021-09-12 06:10 UTC
Labels: OS/Desktop
