### ISSUE TITLE
Add the ability to import inline during onboarding process

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#2475] opened 2018-12-12 00:03 UTC
<img width="1008" alt="screen shot 2018-12-11 at 4 01 20 pm" src="https://user-images.githubusercontent.com/29072694/49838169-330c5700-fd5e-11e8-87a2-25894c98a7d0.png">

**Comment by rebron** [comment] 2019-06-13 17:22
Closing. Dupe of https://github.com/brave/brave-browser/issues/1530

**Closed by rebron** 2019-06-13 17:22 UTC
Labels: duplicate
