### ISSUE TITLE
The `Dashboard Settings` menu in NTP doesn't support dark theme 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5452] opened 2019-07-30 16:14 UTC
## Description 

Found while testing #4523 
The `Dashboard settings` menu in NTP doesn't support dark theme 

## Steps to Reproduce

   1. Set OS theme as dark
   2. Launch brave 0.68.113
   3. Go to settings and set theme  `Same as Window`
   4. Open NTP
   5. Click on `Dashboard Settings` menu 
   6. `Dashboard Settings` menu is not changed to Dark it is still white

## Actual result:

The `Dashboard Settings` menu in NTP doesn't support dark theme 

![image](https://user-images.githubusercontent.com/38657976/62146423-fe600680-b312-11e9-9e57-a74792bb7f73.png)

![image](https://user-images.githubusercontent.com/38657976/62146388-eee0bd80-b312-11e9-9978-f04191480d8c.png)

## Expected result:
As per the comments mentioned in Design spec https://github.com/brave/brave-browser/issues/4523#issue-446774468, the dark theme should be supported for `Dashboard Settings` menu

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa

**Comment by imptrx** [comment] 2019-07-30 18:29
I believe this is a duplicate of https://github.com/brave/brave-browser/issues/5014. The dark mode work was de-scoped from the original issue(https://github.com/brave/brave-core/pull/2668#issuecomment-503316064) and is currently being worked on 😃

**Comment by kjozwiak** [comment] 2019-07-30 18:59
Closing & Labelling as `Duplicate` as per https://github.com/brave/brave-browser/issues/5452#issuecomment-516538097.

**Closed by kjozwiak** 2019-07-30 18:59 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/new-tab
