### ISSUE TITLE
Dev tools window settings are not respected or remembered

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#20075] opened 2021-12-13 18:50 UTC
## Description 

Brave does not respect or retain any settings changed in the dev tools window. For example, changing the Dev tools window theme or panel layout to anything other than the default setting will have no effect. Further, restarting the browser and/or the dev tools window _reverts_ any settings that were changed.
![image](https://user-images.githubusercontent.com/3299098/145870204-ac96b95a-ac62-4b51-8504-31f8701a02fb.png)

Note that I did not test _every setting_, but users should be able to change/customize these settings to their liking. Also note that the dev tools window theme _does_ respect the theme selected in the browser.

## Steps to Reproduce

   1. Open Brave
   2. Open Dev tools --> Settings
   3. Test changing layout and/or dev tools theme settings

## Actual result:

Dev tools appearance does not change

## Expected result:
New settings should be respected

## Reproduces how often: 

Easily

## Brave version (brave://version info)

v1.32.115 Chromium: 96.0.4664.93 (Official Build) (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

User reports:
https://community.brave.com/t/dev-tools-dark-mode-not-working/303366/14

**Comment by ali-wetrill** [comment] 2021-12-16 19:33
I would further add to this that the dev tools window just follows the setting in `brave://settings/appearance`

**Comment by craigjennings11** [comment] 2022-01-07 15:32
Just updated to `1.34.80` and this bug still persists. This is extremely annoying as a developer because every time I open devtools I have to reconfigure it.

**Comment by cyress** [comment] 2022-01-07 16:06
Since it seems like it could take a while to fix the problem, I'm temporarily using an outdated version of Brave. 😟
This is the last version in which the DevTools still work properly.
https://github.com/brave/brave-browser/releases/tag/v1.31.91

Related tickets: #19530, #19509, #19871

**Comment by cyress** [comment] 2022-01-13 09:34
@kjozwiak Yes, exactly. The problem only occurred in the Brave DevTools, not in the Chrome DevTools.
As also described here #19530.

**Comment by kjozwiak** [comment] 2022-01-17 19:12
> @kjozwiak Yes, exactly. The problem only occurred in the Brave DevTools, not in the Chrome DevTools. As also described here #19530.

Added this into the `General` board so we can get it triaged/prioritized in our next desktop meeting 👍

**Comment by cyress** [comment] 2022-01-19 14:15
The problem is maybe related to the new "[Syncing DevTools settings across devices](https://developer.chrome.com/blog/new-in-devtools-97/#sync)" feature, which is enabled by default.
With this feature, as the name suggests, you can sync your DevTools customization (e.g. theme, panel layout, etc.) across your devices. It requires to turn on the Chrome profile sync.

When i try to disable this experimental feature (`DevTools > Settings > Experiments > Sync DevTools settings with Chrome Sync`) and reload the DevTools, they don't open up again.
After this there is no way to open up the DevTools again (Brave menu, keyboard shortcuts, right click menu, etc.).
To get the DevTools working again you must delete the localstorage data (macOS: `~/Library/Application Support/BraveSoftware/Brave-Browser/Default/Local Storage`). Among other things, this will also delete your DevTools settings and reset them to the default values.

**Comment by KnifeFed** [comment] 2022-02-24 13:24
> The problem is maybe related to the new "[Syncing DevTools settings across devices](https://developer.chrome.com/blog/new-in-devtools-97/#sync)" feature, which is enabled by default.

For me, It's enabled by default in `Experiments` but under `Preferences` it's not enabled in the `Sync` section. If I enable it, then restart devtools, guess what? It doesn't persist.

![](https://user-images.githubusercontent.com/85502276/155532124-066d6abc-4b5e-4308-8477-c726cdd9fb30.png)

**Comment by cyress** [comment] 2022-03-02 10:49
Hello @kjozwiak, @rebron and @bsclifton!
I just wanted to ask if there is maybe any news about this problem?

It's been 3.5 months since Devtools stopped saving/remembering the selected settings. The release v1.31.91 from 09 Nov 2021 is the last working one.

The Devtools don't need to support the new "[Syncing DevTools settings across devices](https://developer.chrome.com/blog/new-in-devtools-97/#sync)" feature either. It would be really great if the locally set settings were simply saved again.

I'm glad the ticket is already assigned to the "P4 Backlog". But when I see how many tickets are still ahead, i'm a little bit afraid it could take many months for this ticket to be processed.

Nevertheless, many thanks in advance! ✌️

**Comment by Brave-Matt** [comment] 2022-03-17 21:08
+1 from community:
https://community.brave.com/t/dev-tool-panel-layout-selection-doesnt-persist/359911/2

**Comment by bsclifton** [comment] 2022-03-18 07:57
Closing this issue as a duplicate of https://github.com/brave/brave-browser/issues/20491

Recently fixed by @goodov with https://github.com/brave/brave-core/pull/12600

**Closed** 2022-03-18 07:57 UTC
Labels: bug, feature/dev-tools, feature/global-settings, priority/P4, feature/themes, OS/Desktop
