### ISSUE TITLE
[Android] Include option for users to hide privacy stats from the NTP

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#22921] opened 2022-05-18 17:46 UTC
## Description 
Users should have a way to hide the privacy stats widget from their NTP if desired. I've seen several users make this request and think that it is reasonable and valid, especially considering we allow this option on the desktop version of the browser. 
![image](https://user-images.githubusercontent.com/3299098/169108450-8a032189-33f7-438a-a6ad-bfe6a235d9c2.png)

Possible solutions/suggestions:
- Add overflow/three dots menu to stats widget that offers option to hide them
- Include a toggle option in `Settings --> New Tab Page` that allows user to toggle the widget on/off
- Include option in `Settings` or `Main menu` to display privacy report (whether widget is toggled on/off or not)

@bradleyrichter @jenn-rhim @SergeyZhukovsky 
### Additional information

**Community thread:**
https://community.brave.com/t/how-to-hide-brave-stats-in-android/384365
**Internal Slack convo:**
https://bravesoftware.slack.com/archives/C0816QH3R/p1651262346660889

**Comment by bradleyrichter** [comment] 2022-05-18 17:50
The first desire is to add back the settings toggles as you suggested: 

"Include a toggle option in Settings --> New Tab Page that allows user to toggle the widget on/off"


No other UI work is needed until we have privacy stats complete including the label and click area in the stats widget.

**Comment by timchilds** [comment] 2022-05-18 20:27
We could go with the following copy to keep Settings --> New Tab Page consistent:

Show stats widget
On/Off

![image](https://user-images.githubusercontent.com/28269287/169149431-53c68837-5ecd-4091-a576-b9860d59c55b.png)

@rmcfadden3 does that copy sound good to you?

**Comment by rmcfadden3** [comment] 2022-05-18 20:29
@timchilds — yeah, copy looks good! ship it!

**Comment by angelog0** [comment] 2022-05-18 20:44
I have the same issue and opened a similar ticket (#22853). 

Some year ago I removed Brave from all systems because of this.. then I saw that this was in some manner fixed and I reinstalled it. I find the reintroduction of this issue very irritating. I do not understand the usefulness for the user to know that 32k ads are blocked or that 63 minutes are saved etc.. It is only garbage on the device screen. Why should a programmer waste time in implementing that?

**Comment by angelog0** [comment] 2022-05-18 20:49
BTW, I find that collecting that data is not exactly in line with the policy of the **Secure, Fast & Private Web Browser** ...

**Comment by deeppandya** [comment] 2022-05-18 23:12
@timchilds @bradleyrichter wouldn't it make sense to keep the settings text similar to desktop version ? we have `Show Brave stats` and `Show top sites` in the settings for desktop with switch to toggle.

**Comment by timchilds** [comment] 2022-05-18 23:19
Keeping it consistent with desktop makes sense to me. Unless @bradleyrichter / @rmcfadden3 think otherwise.

**Comment by rmcfadden3** [comment] 2022-05-19 01:01
@deeppandya & @timchilds — sorry, I think I'm missing something. I thought this task was for Settings toggles on whether to "Show background images" and "Show sponsored images" … But @deeppandya looks like you're commenting on a different set of settings RE: showing stats & top sites?

Correct me if I'm totally garbling things here.

**Comment by timchilds** [comment] 2022-05-19 01:21
@rmcfadden3 this ticket is to include a setting for users to hide the privacy stats from the NTP. 

The two options discussed for the copy:

**Option 1**
Show stats widget
On/Off

**Option 2**
Show Brave stats
On/Off

Option 2 is what we current have on desktop. Let us know which option you think we should use? Option 2 makes sense to me to keep things consistent.

**Comment by rmcfadden3** [comment] 2022-05-19 01:24
@timchilds — oh wow. Apologies. I completely missed that.

Yes, keeping consistent with desktop LGTM.

**Comment by bradleyrichter** [comment] 2022-05-19 01:46
yep. Following desktop will be fine.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/13509546/169186152-d4661fcd-a695-459c-8844-5812886baf3d.png">

**Comment by deeppandya** [comment] 2022-06-08 12:59
@srirambv https://github.com/brave/brave-core/pull/13519 only updates code for top sites. It doesnt update anything for brave stats as we need more information to remove it.

**Comment by kjozwiak** [comment] 2022-06-14 19:01
> @srirambv [brave/brave-core#13519](https://github.com/brave/brave-core/pull/13519) only updates code for top sites. It doesnt update anything for brave stats as we need more information to remove it.

Removing the `1.41.x`  milestone as this wasn't fixed/addressed as per the above. https://github.com/brave/brave-core/pull/13519 only gives the user the ability to disable `Top Sites` and not the `Stats`.

**Comment by Jpersh27** [comment] 2022-07-04 23:50
Hello, I would like to know why this issue hasn't been addressed yet? And why users privacy is not being taken seriously?

There is no reason why your browser needs to keep track of any of my following browser habits: 

1.) Trackers & Ads Blocked

2.) Estimated Data Saved

3.) Estimated Time Saved

All that tells me is that even though your ad blocker saves me time, and data, you are still learning my browser habits and behaviors by logging that information.

It takes up a lot of space on my new tab page and is Intrusive and would like to opt out if the collection of these stats and remove this widget from my browser.

Can anyone aware of this certain issue provide an update on when this issue will get fixed or why it willn't be or a reason for why there's been no discussion the past 3 weeks? @bradleyrichter @timchilds @rmcfadden3 @deeppandya @srirambv @kjozwiak 

Thank you.

**Comment by Jpersh27** [comment] 2022-07-04 23:52
Hello, I would like to know why this issue hasn't been addressed yet? And why users privacy is not being taken seriously?

There is no reason why your browser needs to keep track of any of my following browser habits: 

1.) Trackers & Ads Blocked

2.) Estimated Data Saved

3.) Estimated Time Saved

All that tells me is that even though your ad blocker saves me time, and data, you are still learning my browser habits and behaviors by logging that information.

It takes up a lot of space on my new tab page and is Intrusive and would like to opt out of the collection of these stats and remove this widget from my browser.

Can anyone aware of this certain issue provide an update on when this issue will get fixed or why it willn't be or a reason for why there's been no discussion the past 3 weeks? @bradleyrichter @timchilds @rmcfadden3 @deeppandya @srirambv @kjozwiak 

Thank you.

**Comment by Jpersh27** [comment] 2022-07-07 00:56
Hello again, 

 It has been 3 days now and I haven't been acknowledged in anyway or given a reason for why this issue is being ignored or still unresolved.

It would be much appreciated if someone would respond back with some form of details. At this point I feel as though that any issues being raised by the community are being ignored and put on the “back burner " till further notice for whenever you deem it necessary to address them.

Please persuade me otherwise @bradleyrichter @timchilds @rmcfadden3 @deeppandya @srirambv @kjozwiak because at this point any information is better than being ignored and shunned by the development team.@

Thank you.

**Comment by Jpersh27** [comment] 2022-07-07 00:57
Hello again, 

 It has been 3 days now and I haven't been acknowledged in anyway or given a reason for why this issue is being ignored or still unresolved.

It would be much appreciated if someone would respond back with some form of details. At this point I feel as though that any issues being raised by the community are being ignored and put on the “back burner " till further notice for whenever you deem it necessary to address them.

Please persuade me otherwise @bradleyrichter @timchilds @rmcfadden3 @deeppandya @srirambv @kjozwiak because at this point any information is better than being ignored and shunned by the development team.

Thank you.

**Comment by der-p** [comment] 2022-07-09 03:10
Is there a chance that this will be fixed soon? It's really annoying to me. @bradleyrichter @timchilds @deeppandya @srirambv @kjozwiak @ShivanKaul @bradleyrichter @jamesmudgett @kylehickinson

**Comment by der-p** [comment] 2022-07-23 07:17
@deeppandya Thank you for your answer.  I understand that brave shields is an important feature for you.  In general, features provided by Brave should be as optional as possible, since not every user needs and wants all of them.  and I think it's not just about where the data is stored.  it's about a clean look and feel too.  since the desktop version already has the option, the way to implement it properly is already obvious imo.  anyway, i'll keep an eye on this and use another chromium fork until then.

**Comment by angelog0** [comment] 2022-08-01 00:10
I just upgraded to 1.42.83: same situation described in this issue. Nothing changed since April and, frankly, I am annoyed each time to revert to 1.37 which is the last that works as expected. I do not understand because the Brave developers do not revert their changes regarding this issue to the 1.37 version. ALL THIS IS VERY ANNOIING. I will wait another TWO weeks then I will remove Brave from ALL my device (Win, GNU/Linux, macOS, Android) because I use the same browser on all my systems. I already did so a few year ago. Now I will do that definitively. I am afraid...

**Comment by Sam-Sibley** [comment] 2022-08-18 19:30
@anthonypkeane Here is my suggestion for the setting page to toggle off Privacy Report.
@rmcfadden3 Please check this, i am calling them "widgets" to group it with Top sites. Also i have removed the "Show" verb from the item as it is unnecessary as it has a toggle and the state of it directly below.
<img width="414" alt="Hide Privacy Stats" src="https://user-images.githubusercontent.com/99699532/185478478-6a9166d2-82ec-4697-9192-894b49478fa6.png">

**Comment by rmcfadden3** [comment] 2022-08-18 19:40
@Sam-Sibley — yeah, this lgtm. I think "widgets" is widely understood as a term. Ship it!

**Comment by Jpersh27** [comment] 2022-09-12 22:53
So @anthonypkeane and @Sam-Sibley and @rmcfadden3 why has this Option not been released yet? 

It has been 4 months since this issue was opened. Also been 25 days since you said “ship it". 

An explanation would be great, Yes or No?? But I know I'm asking for to much at this point....

**Comment by deeppandya** [comment] 2022-09-21 17:53
@timchilds we can definitely do that.

**Comment by eataiwo** [comment] 2022-11-22 06:21
Any update on when this fix will be added ?

**Comment by snhv** [comment] 2022-11-28 21:50
Please please allow us to remove the stat in NTP. The mockups proposed here all look good.

**Comment by deeppandya** [comment] 2022-12-02 17:59
Updated design 
![Screenshot_20221202-125626_Brave - Nightly.jpg](https://user-images.githubusercontent.com/5146988/205356354-ffd4aeeb-5de9-40cb-b9a8-7d921546592c.jpg)
![Screenshot_20221202-125615_Brave - Nightly.jpg](https://user-images.githubusercontent.com/5146988/205356363-94812519-5b11-4d9d-8c63-c9a718c682e4.jpg)

**Comment by angelog0** [comment] 2022-12-02 21:17
Ok @deeppandya, this has been already described in previous posts in some manner.. but **_WHEN_** this will be released???

**Comment by deeppandya** [comment] 2022-12-02 21:18
> Ok @deeppandya, this has been already described in previous posts in some manner.. but **_WHEN_** this will be released???

We have the changes ready to merge. So I will be available on nightly soon.

**Comment by snhv** [comment] 2022-12-02 21:26
> > Ok @deeppandya, this has been already described in previous posts in some manner.. but **_WHEN_** this will be released???
> 
> We have the changes ready to merge. So I will be available on nightly soon.

Thanks. That is great to hear!

**Closed** 2022-12-02 21:46 UTC
Labels: feature/new-tab, design/needs-mock-up, privacy/feature, QA/Yes, release-notes/include, OS/Android, privacy/triaged

**Comment by stephendonner** [comment] 2023-01-22 08:39
## Verified `PASSED` using `1.48.134` on a `Google Pixel XL` (`arm64`) running `Android 9`

### Steps:
1. installed `1.48.134`
2. launched Brave
3. tapped the 3-dots menu
4. tapped `Settings`
5. tapped `New Tab Page`
6. confirmed defaults:
`Show Top Sites` == `On`
`Show Brave Stats` == `On`
7. toggled various combinations of `On` / `Off` for the two prefs above

Case 1: `Show Top Sites` on & `Show Brave Stats` on - `PASSED`
<details>

new-tab page | prefs
-----------------------|------------------------
![Screenshot_20230122-003238](https://user-images.githubusercontent.com/387249/213907150-44c7e247-10ca-4093-bc1d-3e2131f07ac4.png) | ![Screenshot_20230122-003249](https://user-images.githubusercontent.com/387249/213907151-78618257-e358-4faf-8d48-4a4ac8d5177d.png)

</details>

Case 2: `Show Top Sites` on & `Show Brave Stats` off - `PASSED`
<details>

new-tab page | prefs
-----------------------|------------------------
![Screenshot_20230122-001007](https://user-images.githubusercontent.com/387249/213907228-3671ecb0-e543-4df2-894a-7a8c9b2d015c.png) | ![Screenshot_20230122-001018](https://user-images.githubusercontent.com/387249/213907229-89710c1a-aad8-442d-bf09-4a5291970af0.png)

</details>

Case 3: `Show Top Sites` off & `Show Brave Stats` off - `PASSED`
<details>

new-tab page | prefs
-----------------------|------------------------
![Screenshot_20230122-001934](https://user-images.githubusercontent.com/387249/213906997-704259e9-0c62-4899-b6c8-80ba91b02ec3.png) | ![Screenshot_20230122-001837](https://user-images.githubusercontent.com/387249/213907007-9d978dac-60a6-4ef8-a258-3683c0d49204.png)

</details>

Case 4: `Show Top Sites` off | `Show Brave Stats` on - `PASSED`
<details>


new-tab page | prefs
-----------------------|------------------------
![Screenshot_20230122-000920](https://user-images.githubusercontent.com/387249/213907079-e7f3e4b1-91a1-42cd-b0c4-7c06bdcbe8c1.png) | ![Screenshot_20230122-000930](https://user-images.githubusercontent.com/387249/213907080-a96ea899-c551-446f-8593-15c0f21f2359.png)

</details>
