### ISSUE TITLE
New tab custom background images

### ISSUE THREAD

**Issue by edkazcarlson** [brave/brave-browser#14459] opened 2021-03-04 05:03 UTC
I was thinking about starting to work on allowing users to add custom new tab background images, but wanted to know if someone was already currently working on that before I start.

**Comment by rebron** [comment] 2021-03-11 01:16
Closing this one out as a dupe of #5838 . @edkazcarlson Would love your help in that issue. We have designs and ideas with how we wan to implement.

**Closed by rebron** 2021-03-11 01:16 UTC
Labels: OS/Desktop
