### ISSUE TITLE
Add new tab background options

### ISSUE THREAD

**Issue by indig0F10w** [brave/brave-browser#13049] opened 2020-12-04 12:18 UTC
Greetings,

There is no option to set custom background or turn it off completely. Backgrounds and gradient choice are very eye straining for me and they don't conform to dark mode theme Brave already has.

Possible fix, give users option to turn off the background attribute as shown in screencap.

![PClmyzUSxz](https://user-images.githubusercontent.com/17021548/101162819-18aaa280-3633-11eb-9fc2-81a1b0a1ce9c.gif)

**Comment by rebron** [comment] 2020-12-07 18:53
Closing as duplicate of #8061. There's also #11962 and #353 but we'll address in #8061

**Closed by rebron** 2020-12-07 18:53 UTC
Labels: closed/duplicate
