### ISSUE TITLE
Crypto Wallet not retaining label on Lock/restart

### ISSUE THREAD

**Issue by DefiDebauchery** [brave/brave-browser#18026] opened 2021-09-12 04:33 UTC
## Description 
After adding labels to accounts in the Crypto Wallet, these are lost when the Wallet is locked. Upon re-opening the Wallet, my initial account is correct, but the rest of them have been renamed related to their position.

## Steps to Reproduce

   1. Create Label for Secondary Account(s) in Crypto Wallet
   2. Lock Wallet
   3. Unlock Wallet; observe labels have been renamed.

## Actual result:
Adding Labels --
![Before](https://user-images.githubusercontent.com/75273961/132972209-5f637f1b-01e1-4d6f-a915-6e11b71803d2.png)

After Lock and Unlock --
![After](https://user-images.githubusercontent.com/75273961/132972210-b8ef4d4b-de11-4cc5-ab7c-7610a9d7f800.png)

## Expected result:
Account details are retained without issue (or frustration)

## Reproduces how often: 
Every time the Wallet is Locked/Closed (e.g. browser restart)

This has been happening for as long as I've used Brave (over a year), but haven't seen a lot of discussion on it.

## Brave version (brave://version info)
Brave | 1.29.79 Chromium: 93.0.4577.63 (Official Build) (x86_64)
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 11.5.2 (Build 20G95)

## Version/Channel Information:
Current

**Comment by srirambv** [comment] 2021-09-14 11:27
Dupe of #11705. This is a known issue with Imported wallets either via Private key/Json. This will most likely be a wontfix issue as we will soon migrate to native wallets

**Closed by srirambv** 2021-09-14 11:27 UTC
Labels: OS/Desktop, feature/ethereum-remote-client

**Comment by DefiDebauchery** [comment] 2021-09-14 14:30
Thanks; I looked for similar tickets, but must have searched terms that do not appear in that referenced ticket :)
