### ISSUE TITLE
Disable "Clear on Exit" by default + more control

### ISSUE THREAD

**Issue by eljuno** [brave/brave-browser#16214] opened 2021-06-02 22:42 UTC
## Description 

Brave for Android will have `Clear on exit` option with 1.26.x release, but this setting is enabled by default when users upgraded from prev. version. To avoid user confusions, please disable this setting by default.

Also, please provide more control about which type of data cleared on exit -- basically more option like desktop. The current switch is unclear as it's only to enable/disable. User don't know which data selected/cleared.

## Steps to reproduce 

   1. Install Brave Beta 1.25.x
   2. Upgrade to 1.26.x
   3. Check the above setting

## Actual result 

`Clear on exit` switch enabled by default

![IMG_20210603_054115](https://user-images.githubusercontent.com/25360853/120561236-58a9e100-c42e-11eb-865f-e86b8ffce86e.jpg)

## Expected result

The setting is disabled by default

## Issue reproduces how often 

Easy

## Version/Channel Information:

Beta/Nightly 1.26.x and higher

- Can you reproduce this issue with the current Play Store version? NDA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes
   
## Brave version

1.26.x

**Comment by Tonev** [comment] 2021-06-03 04:57
+1

Users must have control over what browsing data they want to clear. If a user wants to clear their browsing history on exit, it doesn't necessarily mean they want cookies gone as well, for example - clearing their browsing history won't sign them out of websites every time they close the browser, whereas clearing cookies will.

**Comment by anthonypkeane** [comment] 2021-06-03 16:54
>Brave for Android will have Clear on exit option with 1.26.x release, but this setting is enabled by default when users upgraded from prev. version. To avoid user confusions, please disable this setting by default.

Yes, default should be OFF

>Also, please provide more control about which type of data cleared on exit -- basically more option like desktop. The current switch is unclear as it's only to enable/disable. User don't know which data selected/cleared.

ON clears everything "Clears all browsing data". In a later release we will look to add more options here should we get user feedback.

Thanks

**Comment by Tonev** [comment] 2021-06-04 05:48
@anthonypkeane 

Disabling "Clear data on exit" by default is a step into the right direction, but unfortunately it's not enough as of the moment. I'll try to go into detail because the problem is deeper than people think at first.

Let's begin over here:
https://github.com/brave/brave-core/pull/8790

The mentioned pull request introduces the global Shields settings functionality, along with an aggressive mode for ads & trackers blocking, a strict fingerprinting protection, and eventually an option to clear the browsing data on exit.

Here comes the issue, which makes the "Clear data on exit" option hardly compatible with the aggressive ads & trackers mode and the strict fingerprinting protection:

- https://github.com/brave/brave-browser/issues/15347
- https://github.com/brave/brave-browser/issues/16217

Since the "Clear data on exit" option includes the clearing of the browsing data for "Site and Shields Settings", and that can't be changed anyhow, the following will happen:

- A lot of users will enable the aggressive mode for ads & trackers blocking, along with a strict fingerprinting protection
- Then a lot of users will enable the "Clear data on exit" option, because it's a highly anticipated option
- Closing the browser will lead to the following: https://github.com/brave/brave-browser/issues/16217

In other words, if users want to use all 3 new features (aggressive blocking of ads & trackers, a strict fingerprinting protection, and want to clear their browsing on exit), they'll have to re-adjust the Shields settings every single time they open their browser, because clearing the browsing data for "Site and Shields Settings" will reset the global Shields setting every single time users close their browser.

My suggestions until https://github.com/brave/brave-browser/issues/15347 is fixed:

- Allow users to choose which browsing data they want to clear on exit so they can disable the clearing of the browsing data for "Site and Shields Settings"
- If the previous suggestion is a lot of work for the remaining time until the next major release, simply exclude the clearing of the browsing data for "Site and Shields Settings" from the "Clear data on exit" feature
- If, for some reason, the option above is not possible either, introduce a warning dialog that informs users of the consequences of clearing the browsing data

If you proceed with the implementation of the "Clear data on exit" feature in its current state, you'll give users a false sense of stronger privacy protection. A lot of users won't notice that their global Shields settings have reset to their default values after they close their browser (clear their browsing data).

CC: @pes10k as this is potentially a privacy issue as of the moment.

**Comment by kjozwiak** [comment] 2021-06-04 17:59
Closing this as https://github.com/brave/brave-core/pull/9012 was merged into `1.26.x` which fixes the above.

**Closed by kjozwiak** 2021-06-04 17:59 UTC
Labels: OS/Android, QA/Yes, enhancement, feature/global-settings, release/blocking, suggestion

**Comment by srirambv** [comment] 2021-06-08 13:10
Verification passed on OnePlus 6T with Android 10 running 1.26.53 build
- Verified setting is disabled on upgrade 
--------
Verification passed on Samsung Tab A with Android 10 running 1.26.53 build
- Verified setting is disabled on upgrade
