### ISSUE TITLE
Opening Brave Rewards Crashes Brave

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#2459] opened 2018-12-11 18:35 UTC
Steps to reproduce:
1. Click BAT pyramid icon at the right end of the URL bar.
2. Click "Rewards Settings" in the blurple header section.

Alternate steps:
1. Open a new tab and type `brave://rewards` into the URL bar. 

A new "Rewards" tab opens with a loading spinner. A second passes. Brave crashes.
Reproduces 100% of the time: just did it three times in a row.

Version info:
Brave | 0.59.2 Chromium: 71.0.3578.80 (Official Build) dev (64-bit)
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

**Comment by NejcZdovc** [comment] 2018-12-11 18:54
closing as dupe of https://github.com/brave/brave-browser/issues/2375

**Closed by NejcZdovc** 2018-12-11 18:54 UTC
Labels: bug, crash, feature/rewards, priority/P2
