### ISSUE TITLE
[feature request] Allow to change the IPFS gateway in Brave on Android!

### ISSUE THREAD

**Issue by markg85** [brave/brave-browser#18194] opened 2021-09-19 19:13 UTC
Hi,

The app (Brave on Android in this case) defaults to dweb.link as gateway.
I would like to change the gateway but how?

On the desktop there are settings for this but they don't seem to exist on the mobile side of things.

**Comment by NikharPandya** [comment] 2021-09-25 23:57
@markg85 
The feature is not available on android yet but for desktop refer to the bottom links 

- https://brave.com/ipfs-support/

- https://github.com/brave/brave-browser/issues/10220

@bbondy  wrote an excellent document at brave.com

**Comment by NikharPandya** [comment] 2021-09-25 23:59
@markg85 
Close the issue if the links are satisfactory

**Comment by markg85** [comment] 2021-09-26 10:42
> @markg85
> Close the issue if the links are satisfactory

No they are not.

#10220 quite clearly mentions the targeted platforms (Windows, macOS, Linux). I'm asking about the **mobile** version of brave (specifically on android). While i did mention mobile i might have been more explicit about that so i'll edit my post to reflect it more clearly.

**Comment by NikharPandya** [comment] 2021-09-26 15:27
Currently you can not change in android

**Comment by markg85** [comment] 2021-09-26 15:43
> Currently you can not change in android

Previously it was a question to ask how it could be changed. But if you're sure there is no way currently to change this on mobile then this now is a feature request :)

**Comment by NikharPandya** [comment] 2021-09-26 17:09
Yes

**Comment by NikharPandya** [comment] 2021-09-26 17:10
@markg85 
You can change the title and labels for feature request

**Comment by markg85** [comment] 2021-09-26 19:27
> @markg85
> You can change the title and labels for feature request

I cannot add labels, apparently. Feel free to do so if you have the privilege to do so.

**Comment by NikharPandya** [comment] 2021-09-27 03:30
@bsclifton

**Comment by lidel** [comment] 2022-08-12 16:43
I believe this can be closed as a duplicate of https://github.com/brave/brave-browser/issues/14771

**Closed** 2024-09-02 10:08 UTC
Labels: closed/wontfix, feature/web3/ipfs, feature-request, OS/Android
