### ISSUE TITLE
Sound/Video freezes occasionally

### ISSUE THREAD

**Issue by pilsnerbeer** [brave/brave-browser#7890] opened 2020-01-23 16:07 UTC
## Description 

several times a day sound will freeze (with the "BSOD" stuttering, which makes it more annoying) and wont resume unless the website is reloaded. I noticed this happening mostly on youtube, when I'm playing music from another tab in Google Music. But I found it happening on other websites, too. - regardless if they're the only tabs playing music or not.

## Steps to Reproduce

Unsure about the exact steps. For me it usually occurs when playing from two tabs (GMusic and YT). But few minutes ago it happened on my Nextcloud instance and that was the only tab playing music. 

## Actual result:
Music stutters , followed by freeze. Website must be reloaded.

## Reproduces how often: 
Happens several times a day

## Brave version (brave://version info)

Brave | 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1903 (Build 18362.592)

**Comment by pilsnerbeer** [comment] 2020-01-24 19:20
I have now switched browsers to try and see if I can replicate the issue there - perhaps its a system issue and the problem is elsewhere. 
It seems the issue is easiest reproduced when, as mentioned, playing video or audio stream simultaneously on two tabs - Gmusic, youtube, twitter videos, whatever it is. Sooner or later, the issue  will appear. 

I have noticed this error popping out on Youtube whenever the issue appeared:

![Screenshot_4](https://user-images.githubusercontent.com/36133540/73097154-c531d900-3ee6-11ea-98eb-a30fa10610f2.png)

**Comment by rebron** [comment] 2020-01-24 19:58
@pilsnerbeer Are you seeing the autoplay blocked icon in the url bar? Could be something else though. Let us know if it's also reproducible in Chrome and if you have example videos/sites where we can reproduce the issue you're seeing.

**Comment by pilsnerbeer** [comment] 2020-01-24 20:19
>Are you seeing the autoplay blocked icon in the url bar? 

No, I dont think this is the cause of the problem. 

I dont use Chrome but I have been trying Firefox for a few hours and nothing so far. 

Example of when you can come across the issue (must be patient, happens several times an hour):
- Youtube video playing on one tab + browsing Twitter feed and playing a video. As soon as its played (on Twitter), Youtube will freeze.
- Google Music + Youtube ; my most often used combination. Have Music play some songs, click on a YT video. As soon as it plays, GMusic freezes.
- I think it could be observed on any other platform, key is to have two tabs playing music at the same time (or one playing, followed by the second one). Although it occurred to me that the issue was seen on a single tab with single source of music.

**Comment by captnblood** [comment] 2020-01-31 17:28
i have same problem. videos suddenly refuse to play, ask me to restart computer, says something is wrong with my audio. if i open firefox with same video, then both browser can play it. 
if i close firefox, then brave refuse to play video again, same audio error message as before.
if i restart brave, then everything works again, for a limited period of time.
this problem exist at least since 1.5.43 (i started used brave then) i updated brave a few times, but problem still there.

**Comment by rebron** [comment] 2020-03-06 18:09
@pilsnerbeer We can't reproduce. Is it possible for you to try in another Chromium browser to help us diagnose, Chrome, Edge, or Vivaldi? Looks like a driver issue with video decoding.

**Comment by pilsnerbeer** [comment] 2020-03-06 18:19
I probably figured it out; I stopped allowing SS3svc32.exe on startup (Sonic Suite 3 from ASUS, which came preinstalled on my laptop) and the freezes stopped.

**Comment by rebron** [comment] 2020-03-06 21:48
Closing out. Thanks for following up @pilsnerbeer Glad you didn't have to download another browser to help us test. I was cringing as I wrote that :-)

**Closed by rebron** 2020-03-06 21:48 UTC
Labels: feature/video
