### ISSUE TITLE
Extensions page has "Brave Web Store" link that goes to Chrome Web Store (misleading)

### ISSUE THREAD

**Issue by iamVP7** [brave/brave-browser#1001] opened 2018-09-07 05:52 UTC
## Description 
Find extensions and themes in the Brave Web Store  is not going to take me to Brave extension store it is taking to Chrome extension store which feels bit miss leading as of now.

## Steps to Reproduce

   1.  Visit chrome://extensions/
   2.  Check the message
   

## Actual result:

![miss_leadin](https://user-images.githubusercontent.com/3106852/45200736-cfbae680-b28f-11e8-8a43-aed1d6138c5e.png)

## Expected result:
I actually thought i will go to brave specific extension store but went to chrome store.

## Reproduces how often: 
always

## Brave version (about:brave info) 

I am not able to visit about:brave   is it like i should goto  chrome://settings/help

### Reproducible on current release:
yes

**Comment by srirambv** [comment] 2018-09-07 12:45
This should be fixed once #1013 is fixed

**Comment by Jacalz** [comment] 2018-11-09 15:41
Duplicate of https://github.com/brave/brave-browser/issues/800

**Closed by Jacalz** 2018-11-09 15:41 UTC
Labels: feature/brave-pages, feature/extensions
