### ISSUE TITLE
Image upload failed during the Uphold KYC process

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#2993] opened 2019-01-16 22:48 UTC
## Description 

I tried to complete the KYC process with Uphold, but stuck at ID photo upload. Uphold keeps giving me the same error message as if there is a '**network communication problem**', which I couldn't connect the dots to the Shields. But I was able to finish the process after turning off the Shields.

![screen shot 2019-01-16 at 2 47 03 pm](https://user-images.githubusercontent.com/4369856/51283607-9c0a6e80-199d-11e9-8e1c-b9e102571b1c.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by corymcdonald** [comment] 2019-04-01 18:04
@dlipeles Saw the same thing on sandbox.uphold.com

**Comment by dlipeles** [comment] 2019-05-09 16:36
Have received support requests from publishers on this issue too, @diracdeltas I think we talked about this one briefly at brave together

**Comment by diracdeltas** [comment] 2019-05-09 17:07
@tomlowenthal we should maybe move this to p2 since it is disproportionately likely to affect publishers

**Comment by tomlowenthal** [comment] 2019-05-10 14:52
@diracdeltas If we're planning to uplift a fix, P2 makes sense. But I don't think anyone is even working on it right now?

**Comment by diracdeltas** [comment] 2019-06-26 18:06
this is a dupe of https://github.com/brave/brave-browser/issues/4139

**Closed** 2019-06-26 18:07 UTC
Labels: duplicate, feature/shields/webcompat, priority/P3
