### ISSUE TITLE
clicking on "Save Torrent File" attempts to download the file twice

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1399] opened 2018-10-02 19:53 UTC
## Description 

Clicking on `Save Torrent File` under the webtorrent page when clicking/loading `.torrent` links attempts to download the `.torrent` file twice which triggers `website is attempting to download multiple files` notification. Clicking on `Save Torrent File` should only download the `.torrent` file once. This wasn't happening under `muon`.

## Steps to Reproduce

   1. install & run either `beta` or `dev`
   2. in a new tab, load https://webtorrent.io/torrents/big-buck-bunny.torrent
   3. click on `Save Torrent File`
   4. you'll receive the `[websites domain] wants to Download multiple files`
   5. click on `Allow`
   6. click on `Save Torrent File` again and you'll notice Brave attempting to download two `.torrent`

If you click on `Block`, you'll only download a single file, however, we shouldn't be triggering the `multiple downloads` notification when someone decides they want to download the `.torrent` file.

## Actual result:

![torrentissue](https://user-images.githubusercontent.com/2602313/46372950-a1e07c00-c65a-11e8-828b-3f1b6cdb1385.gif)

## Expected result:

Brave shouldn't trigger the `[websites domain] wants to Download multiple files` notification. Clicking on `Save Torrent File` should only save one `.torrent` file.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (chrome://version info)

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds? 

Not reproducible under `0.24.x` which is the latest `muon` live release.

- Does it reproduce on browser-laptop? 

Reproducible on both `dev` and `beta`

Brave | 0.56.1 Chromium: 70.0.3538.22 (Official Build) dev (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

### Additional Information

* Reproduced by @LaurenWags on macOS as well
* Reproduced by @srirambv on Win 10
* Reproduced by @btlechowski on Win 7

**Comment by yrliou** [comment] 2018-10-17 01:18
I think it was an issue of Button component in brave-ui which was fixed by @petemill recently.
https://github.com/brave/brave-ui/issues/197
I just tried with 0.55.16 and cannot reproduce it, @LaurenWags also got the same result as me on 0.55.16.
Please give it a try again with 0.55.16, and feel free to reopen it if it is still an issue, thanks.

**Closed by yrliou** 2018-10-17 01:18 UTC
Labels: QA/Yes, bug, feature/webtorrent
