### ISSUE TITLE
About Speed Dial

### ISSUE THREAD

**Issue by rhrakib555** [brave/brave-browser#19975] opened 2021-12-07 12:16 UTC
## Description 

Currently Brave has no in built “Speed Dial” feature. It’s heck of an important & needy feature people like us. While in Desktop there has 3rd party speed dials in the Chrome store, but there has privacy issues as well. So, I don’t want to use any 3rd party extension & invade my privacy.

On Smartphone (Android), it’s heck of a pain in the ass that Brave mobile browser doesn’t even support chromium extension. And there has no buit in Speed Dial feature. So, unlile desktop on Android there has no way.

So, I’m requesting to the Developers community that please consider to add Speed Dial feature both on Desktop & Mobile client of Brave Browser.
Thanks.

## Steps to Reproduce

   1. Please add "Speed Dial" feature as built-in feature in both PC & Mobile version of Brave Browser.
 
## Expected result:
Brave Browser will add "Speed Dial" feature in both PC & Mobile version of Brave.

## Brave version (info found on brave://version)
 96.0

## Other Additional Information:
Brave developer should add a speed dial as like Opera Browser has the speed dial shown on homepage.

**Comment by thefallofbecause** [comment] 2021-12-07 12:53
On desktop click the 3 dots near the frequently visited sites. You can switch it to favourites.

**Comment by rhrakib555** [comment] 2021-12-08 06:23
> On desktop click the 3 dots near the frequently visited sites. You can switch it to favourites.

All I need a full featured "Speed Dial" feature.
The so called 'favorie widget' is too odd & annoying to use. Even widget doesn't support more than 5 or 7 shortcuts. But I need more shortcuts to be placed on my homepage.
It's for desktop btw.

On Mobile; there has no way.... Mobile client is even more annoying to use.

**Comment by thefallofbecause** [comment] 2021-12-08 08:04
> Even widget doesn't support more than 5 or 7 shortcuts.

It supports 12.

**Comment by rebron** [comment] 2021-12-08 20:02
Closing as a duplicate of https://github.com/brave/brave-browser/issues/11236.

We have some design ideas for expanding Top Sites from the current 12 available. We won't be doing a "Speed Dial" type interface though which is similar to Top Sites just larger and centered. Browser Extensions should fill in the gap there.

**Closed by rebron** 2021-12-08 20:02 UTC

**Comment by rhrakib555** [comment] 2021-12-10 06:24
> Closing as a duplicate of #11236.
> 
> Browser Extensions should fill in the gap there.

Still no fill in the gaps for mobile Brave browser as Brave (mobile) doesn't support any extension.
Meh... 🙄

**Comment by rhrakib555** [comment] 2021-12-11 05:16
> Closing as a duplicate of #11236.
> 
> We have some design ideas for expanding Top Sites from the current 12 available. We won't be doing a "Speed Dial" type interface though which is similar to Top Sites just larger and centered. Browser Extensions should fill in the gap there.

Moreover, Brave doesn't support manually adding URL shortcut.
After I visited any site, Brave placed the shortcut automatically which is annoying. Nobody wants that every visited site as shortcut on homepage.
Please, give us an option to manually add url shortcut as per our choice; not automatically.

**Comment by thefallofbecause** [comment] 2021-12-11 14:01
They do support manually adding sites. As I said above click the three dots next to the top sites box and select "Favourites". You can now manually add your own sites here.

**Comment by tortino** [comment] 2021-12-11 14:21
> They do support manually adding sites. As I said above click the three dots next to the top sites box and select "Favourites". You can now manually add your own sites here.

not on android!

**Comment by rhrakib555** [comment] 2021-12-11 14:55
> They do support manually adding sites. As I said above click the three dots next to the top sites box and select "Favourites". You can now manually add your own sites here.

On Mobile version of Brave you simply can't do anything but nothing. No speed dial, no favorite shortcut, no manually adding shortcut, no customization of homepage, no nothing....

On desktop, there has only little bit of option hidden beneath, still no customization available.

**Comment by byander** [comment] 2026-04-14 11:39
Keep this issue open, because this feature is so important. Many people don't migrate to Brave (Desktop and Mobile) because Speed Dial is missing.
