### ISSUE TITLE
White theme in a dark theme

### ISSUE THREAD

**Issue by Kitanit** [brave/brave-browser#30766] opened 2023-06-02 07:23 UTC
On Linux Mint 21.1 Cinnamon, after the latest stable update (Brave: 1.52.117 Chromium: 114.0.5735.90), when I reopen the browser if the dark theme is turned on, the white one is turned on even if the dark one is in the settings, it is fixed by turning on the white one and turning back the dark one

https://github.com/brave/brave-browser/assets/65107731/1d1c135f-e13c-4e2d-aab2-bd22dde326a5

**Comment by kraizelburg** [comment] 2023-06-02 08:03
This is only temporary until you close and open the browser again. It is a known bug in latest linux version.

**Comment by pedrof04** [comment] 2023-06-02 10:24
Same problem here on Linux Mint 21.1 Mate.

**Comment by SFToro** [comment] 2023-06-02 22:31
Same problem. Linux Mint 21.1 xfce
> This is only temporary until you close and open the browser again. It is a known bug in latest linux version.
After I reopen the browser the light version is set again...

**Comment by zquestz** [comment] 2023-06-02 22:34
Confirmed on Arch with Cinnamon. Would be great to see this fixed.

**Comment by Misza13** [comment] 2023-06-03 14:22
Same here on Manjaro, package brave-browser 1.52.117-2.
Switching to light then dark fixes it until the next restart of the browser.

When I use GTK theme instead of classic, then most of the UI stays dark, but icons on the new tab page have white backgrounds after restart and some pages (like YouTube) load in light mode. Again, switch to light, then dark fixes until restart.

**Comment by Pieter-Visscher** [comment] 2023-06-03 19:05
issue is also present on Debian 12.

**Comment by solo-dante** [comment] 2023-06-03 19:58
> Same problem here on Linux Mint 21.1 Mate.

+1

**Comment by charanravi-online** [comment] 2023-06-04 04:20
Issue is reproduced on Ubuntu 22.04.2 LTS as well.

**Comment by DustyGanteng** [comment] 2023-06-04 05:44
> Same problem here on Linux Mint 21.1 Mate.

+1
workaround: `gsettings set org.gnome.desktop.interface color-scheme prefer-dark`

**Comment by solo-dante** [comment] 2023-06-04 05:53
> `gsettings set org.gnome.desktop.interface color-scheme prefer-dark`

Thanks @DustyGanteng  that worked.

**Comment by Terraminator** [comment] 2023-06-04 09:15
same thing for me. Thank you @DustyGanteng. worked for me!

**Comment by pedrof04** [comment] 2023-06-04 19:41
Thank you very much @DustyGanteng , worked on Linux Mint 21.1 Mate.

**Comment by AuracleTech** [comment] 2023-06-05 15:55
![image](https://github.com/brave/brave-browser/assets/40531871/11f65e8f-324f-4e96-9e97-66e7eda4cc12)

Linux Mint XFCE 21.1 64bit x86_64

**Comment by Brave-Matt** [comment] 2023-06-05 17:11
@rebron @fallaciousreasoning can we have someone take a look at this? Likely an easy fix and good for quality of life for Linux users.

**Comment by rebron** [comment] 2023-06-06 18:40
@Kitanit Are you seeing this in Chrome as well or is this specific to Brave? We want to see if this is an upstream issue.

**Comment by Kitanit** [comment] 2023-06-06 18:52
> @Kitanit Are you seeing this in Chrome as well or is this specific to Brave? We want to see if this is an upstream issue.
Sorry I don't use Chrome

**Comment by zsolaj** [comment] 2023-06-07 08:24
It also ignores the "Show tab search button" switch. It fixes itself once the setting gets enabled and disabled again, but only until the next browser start.
The issue started at the same time as the issue in the title, so I guess they're linked.
(Linux Mint 21.1 Cinnamon, kernel 5.15.0-73, Brave version 1.52.122 /did this on the previous stable release, too/)

**Comment by rur0** [comment] 2023-06-07 18:10
experiencing same issue, after re-opening the setting is on dark but the theme is light

**Comment by yendrrek** [comment] 2023-06-07 20:50
Same problem on Fedora 37.

**Comment by successtheman** [comment] 2023-06-07 21:40
Latest build 1.52.122 on Ubuntu with Plasma/KDE still has the issue present 

> > Same problem here on Linux Mint 21.1 Mate.
> 
> +1 workaround: `gsettings set org.gnome.desktop.interface color-scheme prefer-dark`

Tried this but it doesn't seem to have any impact when using Plasma/KDE

**Comment by digitalextremist** [comment] 2023-06-07 22:46
Nice @DustyGanteng, @solo-dante, @AuracleTech, @successtheman. Thanks.

Can go back to `Classic` versus `GTK` after using that workaround.

**Comment by salif** [comment] 2023-06-11 14:43
Same problem on Arch Linux Cinnamon, brave version 1.52.122.
![11](https://github.com/brave/brave-browser/assets/35408721/d4516f5e-c77e-4166-aa38-0c3a8723054b)
![12](https://github.com/brave/brave-browser/assets/35408721/660fe250-8fd5-4b19-800c-9d0ebd0f0e37)

When I change "Brave colors" to "Light" then to "Dark", it works fine, until I close the browser

![13](https://github.com/brave/brave-browser/assets/35408721/98888d19-6575-4b14-8701-1430674543ba)

The "gsettings" command doesn't fix it

**Comment by Septem151** [comment] 2023-06-14 13:44
Also getting this in Arch linux, latest kernel

**Comment by digitalextremist** [comment] 2023-06-14 22:52
Coffee for @simonhong ☕ 😉 ! Thanks for looking at this one.

**Comment by simonhong** [comment] 2023-06-15 03:13
Hello, I'm looking at this issue but can't repro on my local(ubuntu 20.04.6, gnome 3.36.8 and X11)
so reading theme related code now :)
and need some help from users that can repro this issue.
Anyone can share `dark_mode` value in brave://local-state after startup when this issue happens?
`dark_mode` 1 means dark is configured and `2` means light is configured.

**Comment by zquestz** [comment] 2023-06-15 04:03
> Hello, I'm looking at this issue but can't repro on my local(ubuntu 20.04.6, gnome 3.36.8 and X11) so reading theme related code now and I'm trying to install plasma desktop for repro.
> 
> Need some help from users that can repro this issue. Anyone can share `dark_mode` value in brave://local-state after startup when this issue happens? `dark_mode` 1 means dark is configured and `2` means light is configured.

`"dark_mode": 1`

It is definitely set, just not respected on launch. It claims to be in dark mode, but shows the light UI.

**Comment by simonhong** [comment] 2023-06-15 04:21
> > Hello, I'm looking at this issue but can't repro on my local(ubuntu 20.04.6, gnome 3.36.8 and X11) so reading theme related code now and I'm trying to install plasma desktop for repro.
> > Need some help from users that can repro this issue. Anyone can share `dark_mode` value in brave://local-state after startup when this issue happens? `dark_mode` 1 means dark is configured and `2` means light is configured.
> 
> `"dark_mode": 1`
> 
> It is definitely set, just not respected on launch. It claims to be in dark mode, but shows the light UI.

Thanks for checking @zquestz 👍🏼

**Comment by simonhong** [comment] 2023-06-15 06:58
I saw similar issue on my machine. Dark theme is selected but light theme is activated.

Still can't repro with relaunching scenario but I got this when I change `Windows colors` from Settings>Appearance.
Not sure but maybe both could have same root cause?
![image](https://github.com/brave/brave-browser/assets/6786187/11b1afd9-48ed-4ca0-b425-eb36266c98eb)

**Comment by Cakez0r** [comment] 2023-06-15 11:24
Same on Fedora 38 with i3

![brave1](https://github.com/brave/brave-browser/assets/1033671/bcfe1d63-297f-4f31-a8eb-16fc7b2a56e5)

![brave2](https://github.com/brave/brave-browser/assets/1033671/ef55b9db-7bab-4cf8-96e0-548ba9bb2dc2)

**Comment by simonhong** [comment] 2023-06-15 12:00
> Same on Fedora 38 with i3
> 
> `Version 1.52.117 Chromium: 114.0.5735.90 (Official Build) (64-bit)`
> 
> ![brave1](https://user-images.githubusercontent.com/1033671/246094417-bcfe1d63-297f-4f31-a8eb-16fc7b2a56e5.png)
> 
> ![brave2](https://user-images.githubusercontent.com/1033671/246094430-ef55b9db-7bab-4cf8-96e0-548ba9bb2dc2.png)

Thanks @Cakez0r . Did you set light theme as you os system theme?

**Comment by simonhong** [comment] 2023-06-15 12:15
Can I have some more help for testing?
I made test nightly build([brave-browser-nightly_1.54.61_amd64.deb](https://build-artifacts.brave.com/brave-browser-build-pr/linux_dark_theme/5c17287e1b6ae9eb267658621103082a27fb1e79/linux/brave-browser-nightly_1.54.61_amd64.deb) and [brave-browser-nightly-1.54.61-1.x86_64.rpm](https://build-artifacts.brave.com/brave-browser-build-pr/linux_dark_theme/5c17287e1b6ae9eb267658621103082a27fb1e79/linux/brave-browser-nightly-1.54.61-1.x86_64.rpm)) with my [draft PR](https://github.com/brave/brave-core/pull/18922).
Unfortunately, my machine doesnt' have this issue so can't verify this test build could fix or not.
It would be really great help if anyone can install this build and test whether this issue is resolved or not. Thanks all :)

**Comment by digitalextremist** [comment] 2023-06-15 13:38
@simonhong I am testing this on a fresh install of `Linux Mint 21.1` shortly.

**Comment by digitalextremist** [comment] 2023-06-15 13:41
The issue is resolved in the nightly build you posted @simonhong. Confirmed on a fresh install manifesting the issue!

Nice work! Any one else reproduce the success, or are there still failing cases outside `Linux Mint 21.1`?

**Comment by simonhong** [comment] 2023-06-15 13:45
> The issue is resolved in the nightly build you posted @simonhong. Confirmed on a fresh install manifesting the issue!
> 
> Nice work! Any one else reproduce the success, or are there still failing cases outside `Linux Mint 21.1`?

@digitalextremist  Thank you for all the help, it is much appreciated! 👍🏼

**Comment by digitalextremist** [comment] 2023-06-15 14:46
It seems there is another confirmation with `Linux 21.0` ( not `21.1` ) 

https://community.brave.com/t/dark-mode-resests-after-browser-is-closed/489864/50

**Comment by digitalextremist** [comment] 2023-06-15 20:45
Seems there are two threads of testers with @simonhong here on `GitHub` but another glowing response, solving the issue on another `Linux 21.1` system.

**Comment by simonhong** [comment] 2023-06-15 23:28
> Seems there are two threads of testers with @simonhong here on `GitHub` but another glowing response, solving the issue on another `Linux 21.1` system.

@digitalextremist Many thanks!!!

**Closed** 2023-06-16 07:49 UTC
Labels: OS/Linux, priority/P3, QA/Yes, release-notes/include, needs-more-info, feature/themes, OS/Desktop

**Comment by Cakez0r** [comment] 2023-06-16 14:21
> Thanks @Cakez0r . Did you set light theme as your os system theme?

As far as I'm aware, there is no concept of a system theme in i3.  I have done my best to apply dark theme as default to various UI frameworks. Happy to dump any config files or run tests that would be useful to you.

```
$ cat ~/.config/gtk-3.0/settings.ini 
[Settings]
gtk-theme-name=Qogir-Dark
gtk-icon-theme-name=Qogir-dark
gtk-font-name=Sans 10
gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=0
gtk-toolbar-style=GTK_TOOLBAR_BOTH
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintslight
gtk-xft-rgba=rgb
```
```
$ cat ~/.gtkrc-2.0 
# DO NOT EDIT! This file will be overwritten by LXAppearance.
# Any customization should be done in ~/.gtkrc-2.0.mine instead.

include ".gtkrc-2.0.mine"
gtk-theme-name="Qogir-Dark"
gtk-icon-theme-name="Qogir-dark"
gtk-font-name="Sans 10"
gtk-cursor-theme-name="Adwaita"
gtk-cursor-theme-size=0
gtk-toolbar-style=GTK_TOOLBAR_BOTH
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle="hintslight"
gtk-xft-rgba="rgb"
```

```
$ cat ~/.config/qt5ct/qt5ct.conf 
[Appearance]
color_scheme_path=/usr/share/qt5ct/colors/darker.conf
custom_palette=true
standard_dialogs=default
style=Fusion
```

**Comment by Cakez0r** [comment] 2023-06-16 14:46
Still not working for me in the nightly build `Version 1.54.59 Chromium: 114.0.5735.110 (Official Build) nightly (64-bit)`
![brave3](https://github.com/brave/brave-browser/assets/1033671/11eadcc8-d4bd-40dc-bd72-1635545326ae)

**Comment by simonhong** [comment] 2023-06-17 00:43
> Works for me also in your test build. Thank you!

@Cakez0r Thanks for your help! Current nightly channel includes this fix :)

**Comment by felipeabou** [comment] 2023-06-19 20:29
I had this issue and your fix worked for me. I'm using Linux Mint 21.1.

Thank you very much, @simonhong !!!

**Comment by kjozwiak** [comment] 2023-06-28 21:51
The above requires `1.53.107` or higher for `1.53.x` verification 👍

**Comment by LaurenWags** [comment] 2023-06-29 13:41
Verification in progress with

```
Brave	1.53.107 Chromium: 115.0.5790.40 (Official Build) (64-bit) 
Revision	071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}
OS	Linux
```

**Comment by TzourCode** [comment] 2023-07-07 20:10
> > Same problem here on Linux Mint 21.1 Mate.
> 
> +1 workaround: `gsettings set org.gnome.desktop.interface color-scheme prefer-dark`

Thanks mate worked for me to!!! @DustyGanteng 💪

Linux Mint 21.1 Cinnamon
