### ISSUE TITLE
[Desktop] Update prompt: link formatting issue & invalid link

### ISSUE THREAD

**Issue by intel352** [brave/brave-browser#10143] opened 2020-06-08 16:39 UTC
## Description 
Update pop-up has text regarding an update, attempts to provide a link to a changelog. The html is printed rather than formatted correctly, and the link itself is invalid because it used "master" branch which changed since the mentioned release, rather than using a release tag.

See screenshot

<img width="606" alt="Screen Shot 2020-06-08 at 12 28 48 PM" src="https://user-images.githubusercontent.com/77607/84056903-e1f61700-a984-11ea-995c-d8afefaedcff.png">

## Brave version (brave://version info)

Brave | 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.3 (Build 19D76)

**Comment by bsclifton** [comment] 2020-06-08 16:50
Thanks for the report 😄 This is a duplicate of https://github.com/brave/brave-browser/issues/9274 which was fixed in 1.10 (our next release). We have an issue captured to get rid of this on macOS altogether:
https://github.com/brave/brave-browser/issues/9562

**Closed by bsclifton** 2020-06-08 16:50 UTC
Labels: OS/Desktop
