### ISSUE TITLE
Pending list isn't displayed if a one time tip/recurring tip sent to connected pubs from KYC'd account

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8963] opened 2020-04-01 13:18 UTC
## Description 

Pending list isn't displayed if a one-time tip/recurring tip sent to connected pubs from KYC'd account
## Steps to Reproduce

   1. Clean profile 1.7.81 launch brave with staging flag with short reconcile interval `brave.exe --rewards=staging=true,reconcile-interval=2`
   2. Enable Rewards 
   3. Connect to KYC'd staging uphold account (should have a balance)
   4. Setup a recurring tip for the connected publisher
   5. Send a one time tip to the connected pub
   6. One time tip is displayed under Tips panel - which is not expected 
   7. There is no `Show all pending contributions` display in brave://rewards - which is not expected
   

## Actual result:

Pending list isn't displayed if a one-time tip/recurring tip sent to connected pubs from KYC'd account

## Expected result:
![image](https://user-images.githubusercontent.com/38657976/78140931-62117500-7448-11ea-803b-90190a56db47.png)

![image](https://user-images.githubusercontent.com/38657976/78140894-532ac280-7448-11ea-98d0-757c8b4ddc56.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.7.81 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @NejcZdovc

**Comment by LaurenWags** [comment] 2020-04-01 13:23
Reproduced on macOS on both dev and nightly

Brave | 1.7.81 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)



Brave | 1.8.59 Chromium: 81.0.4044.83 (Official Build) nightly (64-bit)
-- | --
Revision | 5718ca617723806b9aacfb41108a0d911d1bde74-refs/branch-heads/4044@{#853}
OS | macOS Version 10.14.6 (Build 18G3020)

**Comment by NejcZdovc** [comment] 2020-04-01 13:24
closing as dupe of https://github.com/brave/brave-browser/issues/8945

**Closed by NejcZdovc** 2020-04-01 13:24 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards, regression
