### ISSUE TITLE
Wallet pages becomes blank when ledger is connected

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19091] opened 2021-10-29 05:09 UTC
## Description 

Wallet pages becomes blank when ledger is connected

## Possible Steps to Reproduce

   1. Connect Ledger wallet
   2. Start fresh brave profile 
   3. Create Wallet, once onboarding is done browser shows empty page with errors in console

## Actual result:

Windows (on Accounts page) | Linux (Onboarding page)
-- | --
![image](https://user-images.githubusercontent.com/17010094/139378718-d4b9e6e9-73d6-4ec5-a494-7fcc11e9f529.png) | ![image](https://user-images.githubusercontent.com/17010094/139379156-96514bc9-fe7c-482d-beff-2a1e5d5734ec.png)

## Expected result:
No error no blank page

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.84 Chromium: 95.0.4638.54 (Official Build) beta (x86_64)
-- | --
Revision | `d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel?  Maybe

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @spylogsster

**Comment by yrliou** [comment] 2021-11-03 18:31
I don't think step 1 is relevant since we create a new profile in step 2 and didn't try to actually connect the ledger to our wallet.
From the console log, it looks like some bad access when state is not fully ready yet.
However I can't seem to reproduce it locally, need some help from @srirambv for reproducible steps.

**Comment by bbondy** [comment] 2021-12-03 14:28
Closing because I think this is probably no longer valid. If it is though feel free to re-open @srirambv

**Closed by bbondy** 2021-12-03 14:28 UTC
Labels: bug, priority/P2, release-notes/exclude, needs-more-info, feature/wallet, OS/Desktop
