### ISSUE TITLE
Clear CSS rule context menu settings are missing

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#14945] opened 2021-03-25 07:39 UTC
## Description 

Clear CSS rule context menu settings are missing

## Steps to Reproduce

   1. Open Brave nightly `1.24.25`
   2. Open Brave.com 
   3. Right-click on the `Download Brave` button
   4. Clear CSS rule context menu settings are missing

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/112435076-46defa00-8d6a-11eb-8fb9-7c72469e809a.png)
![image](https://user-images.githubusercontent.com/38657976/112435159-62e29b80-8d6a-11eb-84ab-1ec1b4cb5169.png)

## Expected result:
![image](https://user-images.githubusercontent.com/38657976/112435375-a5a47380-8d6a-11eb-9135-2dc58e55193a.png)
![image](https://user-images.githubusercontent.com/38657976/112435418-b523bc80-8d6a-11eb-8ad9-082f25f2a5d6.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.24.25 Chromium: 90.0.4430.30 (Official Build) nightly (64-bit)
-- | --
Revision | 5674335ff855e43f3bccf8cfc29a779bdf0d067f-refs/branch-heads/4430@{#532}
OS | Windows 10 OS Version 2004 (Build 19041.867)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes in 1.23.48 CR 89
- Can you reproduce this issue with the nightly channel? Yes 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @mkarolin @rebron

**Comment by LaurenWags** [comment] 2021-03-25 13:11
@rebron we probably we want this fixed for 1.23.x

**Comment by Brave-Matt** [comment] 2021-03-25 17:48
+1 Came to open an issue for this

**Comment by HGhostRevisionist88** [comment] 2021-03-25 20:27
These buttons are missing not because of a bug or anything, it is an intended change by Brave team some weeks ago, the old deprecated right click cosmetic menu feature not working anymore, so they finally integrated with the brave://adblock/ page which is good since the old system was terrible since it didn't allow any edit or anything and you could only clear the rules entirely from Brave or a website.

You can read here https://github.com/brave/brave-core/pull/8156

@antonok-edm says: "I'm not opposed to re-implementing the "Clear CSS rules for this site" option (we could detect any rules of the form this.site##cssSelector and clear them), but I think that's best addressed by a follow-up if there happens to be demand for it."

So the Clear CSS buttons are not "missing" per say and to be honest they are now kind of pointless if you think about it, which I guess is the reason antonok decided to remove them since you can go to brave://adblock/ and manipulate the rules there: disable by 'comment' them, edit, delete, move, regroup etc like you can do in any other adblocker unlike before, the old deprecated system wasn't really great, and I wouldn't understand why would anyone want to clear all the rules in a site like that, when you can just go to the adblock and do it better and have all the control about them.

**Comment by antonok-edm** [comment] 2021-03-25 20:49
Correct, this is working as intended. Thanks for catching, @HGhostRevisionist88.

I suppose it is reasonable that there will be questions about the missing buttons though, so we should be prepared for those.

**Comment by LaurenWags** [comment] 2021-03-26 12:31
@Brave-Matt could you link the appropriate documentation once it's available so anyone else who comes here can find it?

**Comment by Brave-Matt** [comment] 2021-04-06 22:11
I've updated the documentation for this. Note that the bottom-most section is more of a CSS "lesson" than how to use the feature itself so I left it alone as I think it does a good job as is. Please let me know if anyone thinks I should change this anyway. Other than that the doc is updated to reflect the most recent changes:
https://support.brave.com/hc/en-us/articles/360018039072

**Comment by rebron** [comment] 2021-04-13 16:44
Closing per last comment and fixed with https://github.com/brave/brave-browser/issues/14978

**Closed by rebron** 2021-04-13 16:44 UTC
Labels: OS/Desktop, QA/No, feature/CSS-element-block, priority/P3, release-notes/exclude, support
