### ISSUE TITLE
twitter.com in Rewards Panel on a publisher page after tweeting about a tip

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#5544] opened 2019-08-05 17:13 UTC
## Steps to Reproduce

1. Claim grant
2. Open `https://www.reddit.com/user/jsadler-brave`
3. Tip the publisher
4. Tweet about the tip
5. On Twitter page open Brave Panel
6. Switch to the reddit page
7. Open Brave Panel
8. Wait 30 seconds

![5544](https://user-images.githubusercontent.com/34715963/62483176-5eddc080-b7b7-11e9-9022-be499b146f84.gif)

## Actual result:

twitter.com as publisher in Rewards Panel on a reddit publisher page

![image](https://user-images.githubusercontent.com/34715963/62481907-0b1da800-b7b4-11e9-8b1c-5d6eb73344a0.png)

Note: Reloading the reddit page does not fix the issue
Note: Reopening the reddit page fixes the issue

## Expected result:
reddit publisher in Rewards Panel on a reddit publisher page
![image](https://user-images.githubusercontent.com/34715963/62482017-4ae48f80-b7b4-11e9-810e-44089d2709fa.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.68.118 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @NejcZdovc

**Comment by btlechowski** [comment] 2019-08-05 17:37
Reproduced on a youtube publisher

![image](https://user-images.githubusercontent.com/34715963/62483558-428e5380-b7b8-11e9-87a8-b939fe961fef.png)

Reproduced on `https://www.3zsistemi.si/`

![image](https://user-images.githubusercontent.com/34715963/62483614-69e52080-b7b8-11e9-887d-6f8a010d0ab4.png)

Brave | 0.68.118 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Ubuntu 18.04 LTS

**Comment by LaurenWags** [comment] 2019-08-05 17:55
@btlechowski does this reproduce on 0.67.x also? (specifically, your comment here https://github.com/brave/brave-browser/issues/5544#issuecomment-518328560 since reddit tipping isn't in 0.67.x)

**Comment by btlechowski** [comment] 2019-08-05 18:27
Reproduced on release


Brave | 0.67.123 Chromium: 76.0.3809.87 (Official Build) (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Ubuntu 18.04 LTS


![image](https://user-images.githubusercontent.com/34715963/62486386-6c974400-b7bf-11e9-90ec-8e054b95a48c.png)

**Comment by LaurenWags** [comment] 2019-08-05 18:34
thanks for checking @btlechowski !

**Comment by LaurenWags** [comment] 2019-08-06 14:21
Reproduced on macOS also:

Brave | 0.68.119 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

**Comment by NejcZdovc** [comment] 2020-04-10 11:50
@LaurenWags @btlechowski is this still a problem on latest Nightly?

**Comment by LaurenWags** [comment] 2020-04-10 13:28
I could not reproduce, but I did encounter and log https://github.com/brave/brave-browser/issues/9136.

Will let @btlechowski recheck before closing.

**Comment by NejcZdovc** [comment] 2020-10-01 07:22
closing as stale

**Closed by NejcZdovc** 2020-10-01 07:22 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/rewards, priority/P5
