### ISSUE TITLE
Unable to do a swap on jup.ag

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#24061] opened 2022-07-14 11:58 UTC
## Description 

Tried to do a swap on Jupiter (jup.ag) and was unable to do it. Tried on 1.43

attached screenshots just showing what happened when I wanted to do that swap. Asked for permissions and then said I didn't have a signature.

## Steps to Reproduce

   1. Try swapping 0.05 SOL to USDC on jup.ag
   2. 
   3. 

## Actual result:

<img width="328" alt="Screenshot 2022-07-14 at 13 43 12" src="https://user-images.githubusercontent.com/12224304/178977071-e05a306a-279c-42de-bf5e-6008f4b8a2fa.png">

<img width="441" alt="Screenshot 2022-07-14 at 13 43 22" src="https://user-images.githubusercontent.com/12224304/178977104-be319be4-6042-4852-9c6d-ee71cb3b6885.png">

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by yrliou** [comment] 2022-07-19 02:22
It's actually a bug on Jupiter side, they have a fix in progress, closing this one as it's not a bug on Brave side.

**Closed by yrliou** 2022-07-19 02:22 UTC
Labels: bug, priority/P2, OS/Desktop, feature/wallet/solana, feature/wallet/dapps
