### ISSUE TITLE
Fix cosmetic filters not being applied inside of child frames

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#22781] opened 2022-05-11 08:38 UTC
## Description 
Some cosmetics aren't being applied 

## Steps to Reproduce

   1.  Enable Fanboy Annoyances in brave://adblock
   2. Open `https://instapundit.com/513971/#respond`
   3. Expect the social elements to be filtered.

## Actual result:

![21d1ffc267cdb12a53798e74e74b55b697953d47_2_690x469](https://user-images.githubusercontent.com/1659004/167805879-14abc66b-81f0-4338-a4ad-2bd14ce40c7b.jpeg)

## Expected result:
Social cosmetics should be removed/filtered out.

## Reproduces how often: 

Easily, when Annoyances/Social list is enabled.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes	
- Can you reproduce this issue with the beta channel? Yes	
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @antonok-edm 

Related thread: https://community.brave.com/t/block-something-using-browser-instead-of-ublock-origin/368569/

**Comment by ryanbr** [comment] 2022-05-18 22:27
https://www.thedailybeast.com/massachusetts-officials-confirm-first-us-monkeypox-case-this-year

`<div class="Cheat__out-of-page-ads">` not being filtered/hidden

**Comment by mckealty** [comment] 2022-06-26 21:51
Hi all! I promise I am not being pushy, I have never submitted a bug/request before so I was wondering how long something like this usually takes. 

I appreciate this being submitted for me, I would like to rely on as few addons as possible and this will help.

Thank you again.

**Comment by antonok-edm** [comment] 2022-06-27 17:47
I'm not able to reproduce the first issue - @mckealty if you're still experiencing it could you please post more information about your browser version and Shields settings?

As per the second issue - I don't see any `.Cheat__out-of-page-ads` elements unhidden, but I do see that `##.Cheat__top-ad` isn't working and `thedailybeast.com##.Cheat__top-ad` is required to fix it.

**Comment by mckealty** [comment] 2022-06-28 03:12
> ~I'm not able to reproduce the first issue - @mckealty if you're still experiencing it could you please post more information about your browser version and Shields settings?~ Just noticed there were two sets of share buttons, this issue refers to the Disqus ones. Those are still appearing, and adding `instapundit.com##.share-bar` doesn't fix it.

Thanks! Is there something I can add to my rules/filters to get rid of those buttons? Or will it need to be update on your end?

**Comment by antonok-edm** [comment] 2022-06-30 02:25
@mckealty It should be fixed once https://github.com/brave/brave-core/pull/14020 is merged; that'll show up in an upcoming Nightly version. I can give you a heads up once it's available.

**Closed** 2022-07-01 03:21 UTC
Labels: priority/P4, QA/Yes, release-notes/include, QA/Test-Plan-Specified, feature/shields/webcompat, OS/Android, OS/Desktop

**Comment by antonok-edm** [comment] 2022-07-01 23:31
@mckealty It should be fixed in v1.42.50+; please feel free to follow up if you see any more issues :smiley:

**Comment by mckealty** [comment] 2022-07-06 22:55
@antonok-edm Ok sounds good! I would tip you some BAT but for some reason tip buttons have never shown up in my browser. If and when I figure it out I'll send some your way. Thank you for the work you did on this!

**Comment by stephendonner** [comment] 2022-07-13 05:02
@antonok-edm looks like we need https://github.com/brave/brave-core/pull/14056 uplifted to 1.42.x in order to be able to test this?  I'm not seeing this flag in `1.42.61`:

<img width="1002" alt="Screenshot 2022-07-12 at 10 00 44 PM" src="https://user-images.githubusercontent.com/387249/178654483-12d3f652-6bbf-4978-8d55-11a680e4657a.png">

**Comment by antonok-edm** [comment] 2022-07-14 22:10
@stephendonner I didn't realize these landed in separate releases, so I've started [an uplift](https://github.com/brave/brave-core/pull/14196). However, you should still be able to test the flag's `Enabled` behavior without the uplift - before adding the option it was always-on.

**Comment by LaurenWags** [comment] 2022-07-15 15:13
Marking as `QA/Blocked` until https://github.com/brave/brave-core/pull/14196 is uplifted to 1.42.x

**Comment by Uni-verse** [comment] 2022-07-27 04:54
Verification `PASSED` on `Samsung GS 21` & `Tab S7` using

```
Brave	1.42.80 Chromium: 104.0.5112.57 (Official Build) (64-bit) 
Revision	212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}
OS	Android 12; Build/SP1A.210812.016
```

Using STR from https://github.com/brave/brave-browser/issues/22781#issue-1232218841

- Verified enabling `Fanboy Annoyances List` in `brave://adblock` will filter out social elements when visiting `https://instapundit.com/513971/#respond`
- Verified Feature flag `Enable cosmetic filtering in child frames` is set to default in `brave://flags`

<details><summary>Flags/Adblock feature</summary>

Flags | Adblock
-|-
![screenshot-1658896069201](https://user-images.githubusercontent.com/17885425/181163589-159a991d-2368-4cc6-b142-3d971d559e42.png) | ![screenshot-1658896301226](https://user-images.githubusercontent.com/17885425/181163608-ac8df2ba-7e43-4431-a2d1-47d5b6432345.png)
![screenshot-1658894027767](https://user-images.githubusercontent.com/17885425/181163695-f2c424f4-a94b-4e6c-8615-e48e9cca8d06.png) | ![screenshot-1658895447582](https://user-images.githubusercontent.com/17885425/181163715-006c1226-cae8-4be9-9eb7-ff9b7c29e07b.png)

</details>


<details><summary>https://instapundit.com</summary>

Filter Enabled | Filter Disabled
-|-
![screenshot-1658895660106](https://user-images.githubusercontent.com/17885425/181162823-73714eae-1313-4520-8ba7-d26bb8b0c8e8.png) | ![screenshot-1658895693220](https://user-images.githubusercontent.com/17885425/181162757-1c0bb97d-df22-4cc1-b259-be43149b057d.png)
![screenshot-1658896282287](https://user-images.githubusercontent.com/17885425/181162899-b88db781-377b-4f56-b2a3-3aeffc714be2.png) | ![screenshot-1658896264661](https://user-images.githubusercontent.com/17885425/181162894-1a0061d1-a4bd-4820-affb-42c635797a0d.png)

</details>

**Comment by Uni-verse** [comment] 2022-07-27 05:24
Verification `PASSED` using 

Brave | 1.42.78 Chromium: 103.0.5060.134 (Official Build) beta (x86_64)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | macOS Version 12.3.1 (Build 21E258)

Using STR from https://github.com/brave/brave-browser/issues/22781#issue-1232218841

- Verified enabling `Fanboy Annoyances List` in `brave://adblock` will filter out social elements when visiting `https://instapundit.com/513971/#respond`
- Verified Feature flag `Enable cosmetic filtering in child frames` is set to default in `brave://flags`
- Verified that unchecking/disabling `Fanboy Annoyances List` in brave://adblock will bring back the social elements again.

Filter ON | Filter OFF
-|-
![Screen Shot 2022-07-26 at 10 19 42 PM](https://user-images.githubusercontent.com/17885425/181167493-fd4e8166-d595-4b3f-966a-d392869d52ef.png) | ![Screen Shot 2022-07-26 at 10 20 10 PM](https://user-images.githubusercontent.com/17885425/181167498-60e1ca08-ac2f-44ec-8ef5-037454aa7ceb.png)

Flags | Adblock
-|-
![Screen Shot 2022-07-26 at 10 13 57 PM](https://user-images.githubusercontent.com/17885425/181167745-d767e091-5a31-48a6-ab5f-2ee6ff6cacfa.png) | ![Screen Shot 2022-07-26 at 10 19 09 PM](https://user-images.githubusercontent.com/17885425/181167767-e5c17d54-6836-44df-8e24-e5055e8f1ab4.png)

**Comment by mckealty** [comment] 2022-10-11 07:29
Awesome, thanks so much!
