### ISSUE TITLE
Crash on exit with sync enabled after closing tor window 

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#7459] opened 2019-12-19 14:27 UTC
The combination of Sync and Tor crashes Brave on exit.
Reproduces on all channels (1.1.x, 1.2.x, 1.3.x, 1.4.x)
Does not reproduce on 1.0.x.

## Steps to Reproduce

   1. Clean install
   2. Make a sync chain
   3. Open some pages
   4. Open Tor Window
   5. Close Tor Window
   6. Go to `Hamburger Menu->Exit` or close Brave with `x`

## Actual result:

Crash on Exit
![image](https://user-images.githubusercontent.com/34715963/71180637-e31a7700-2272-11ea-8cec-145b3c5ae3f3.png)
After relaunching Brave, user is prompted to `Restore pages?`
![image](https://user-images.githubusercontent.com/34715963/71180761-1f4dd780-2273-11ea-8bd8-85fbac2e972f.png)

Crash dump id:   92d41f84b9805f7c

## Expected result:
No crash

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Ubuntu 18.04 LTS

cc @rebron @bsclifton @brave/legacy_qa @darkdh @AlexeyBarabash @riastradh-brave @tomlowenthal

**Comment by btlechowski** [comment] 2019-12-19 14:51
This is a regression introduced in 1.1.x.
Reproduced on 1.1.20, 1.1.21, 1.1.22 on Ubuntu 18.04 LTS
**Does not reproduce on 1.0.1** on Ubuntu 18.04 LTS

Reproduced on

Brave | 1.2.30 Chromium: 79.0.3945.79 (Official Build) beta (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Windows 7 Service Pack 1 (Build 7601.24530)

Uploaded Crash Report ID 102dfd61c9d51388 (Local Context: 122782ce-1bad-4833-8c81-b81f2387e1a9)

Reproduced on

Brave | 1.3.68 Chromium: 79.0.3945.79 (Official Build) dev (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Windows 7 Service Pack 1 (Build 7601.24530)

Uploaded Crash Report ID 9cac187a5e9b8405 (Local Context: 57fd5d33-bcdf-443f-b0e1-5694c73af721)

Reproduced on

Brave | 1.4.25 Chromium: 79.0.3945.79 (Official Build) nightly (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Windows 7 Service Pack 1 (Build 7601.24530)

Uploaded Crash Report ID 4297e486d6d05602 (Local Context: 70e3049c-b8e7-4a9f-a5e8-6ebb0dc30693)

**Comment by kjozwiak** [comment] 2019-12-19 16:11
Looks like the following are the two crash signatures:

#### Linux crashes @btlechowski reported above:

```
bookmarks::BookmarkModel::SetUndoDelegate(bookmarks::BookmarkUndoDelegate*)
```

#### Win crashes @btlechowski reported above:

```
base::win::GenericScopedHandle::Close()
```

**Comment by bsclifton** [comment] 2019-12-19 19:03
cc: @yrliou

**Comment by LaurenWags** [comment] 2019-12-19 20:44
Could not reproduce on macOS. Note - there is no `Exit` in hamburger menu on macOS. Also, if I close the last open window on macOS using the `x`, Brave process continues to run. Not sure if maybe this difference keeps macOS from crashing.


Brave | 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | macOS Version 10.13.6 (Build 17G5019)

**Comment by yrliou** [comment] 2020-01-22 06:44
OTR profile would return nullptr for BookmarkUndoService, we should be able to fix this acting the same as OTR profile.

**Comment by AlexeyBarabash** [comment] 2020-11-20 17:17
Tried today - cannot reproduce, maybe sync v1 issue. Closing.

**Closed by AlexeyBarabash** 2020-11-20 17:17 UTC
Labels: OS/Desktop, QA/Test-Plan-Specified, QA/Yes, crash, feature/sync, feature/tor, priority/P2
