### ISSUE TITLE
Token value doesn't match up with claimed amount

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1557] opened 2018-10-12 22:06 UTC
## Description 

Token value doesn't match up with claimed amount

## Steps to Reproduce

   1. Enable Rewards
   2. Claim Token 
   3. If you are lucky you'll get more than you asked for

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/46896051-4330b480-ce49-11e8-8eb0-19dbe9d197e9.png)

## Expected result:
Token Grant value should match the claimed amount

## Reproduces how often: 

Intermittent. Issue reproduced by @kjozwiak @LaurenWags and @alexwykoff 

## Brave version (chrome://version info)

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes
- Does it reproduce on browser-laptop? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment] 2018-10-19 16:18
@NejcZdovc is this still an issue?

**Comment by NejcZdovc** [comment] 2018-10-19 16:29
I never reproduced this error, so not sure

**Comment by NejcZdovc** [comment] 2018-10-22 17:49
@kjozwiak @srirambv is this still a problem?

**Comment by kjozwiak** [comment] 2018-10-25 03:28
> @kjozwiak @srirambv is this still a problem?

@NejcZdovc I couldn't reproduce this after accepting 20 grants on both the `production` and `staging` servers:

* under `staging`, accepted 20 grants. Received 20 BAT, summary displayed 20 BAT every time
* under `production`, accepted 20 grants. Received 25 BAT, summary displayed 25 BAT every time

This might be fixed as I haven't seen it in a while. @GeetaSarvadnya @btlechowski @srirambv mind trying it a few times as well and see if you can still reproduce the issue? If we can't reproduce this, we can close this off and just keep an eye on the summary to see if it happens again.

**Comment by GeetaSarvadnya** [comment] 2018-10-25 13:55
Tested the issue on Brave beta 0.56.6. Tried the above STR multiple times. Issue is not reproducible. Seems issue is fixed.


Brave | 0.56.6 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows

**Comment by btlechowski** [comment] 2018-10-25 14:58
Not reproducible on Win 7 x64. Checked production server several times on Beta channel.

Brave | 0.56.6 Chromium: 70.0.3538.67 (Official Build) beta (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 7 x64

**Comment by NejcZdovc** [comment] 2018-11-02 10:02
was it possible that you first recovered a wallet and then do claim? This will be solved by https://github.com/brave/brave-core/pull/777. If that is not the case, based on the fact that can't be reproduced I will close this issue. Let's reopen if we have some new STR

**Closed by NejcZdovc** 2018-11-02 10:02 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards, needs-investigation, priority/P5
