### ISSUE TITLE
PDF rendering broken

### ISSUE THREAD

**Issue by SplittyDev** [brave/brave-browser#2366] opened 2018-12-05 11:23 UTC
## Description 
Unable to view a PDF embedded into a webpage using an iframe.

Error message:
```
PDF.js v2.0.673 (build: 31012570)
Message: Missing PDF "https://www.foo.bar/admin/baz.php?order=1234&showpdf=1".
```

## Steps to Reproduce
I don't know how to reproduce this, since it's happening in a private e-commerce backend.
Opening the link in the error message directly renders the PDF correctly.

## Actual result:

PDF controls are shown, but instead of the PDF content there is this error:
```
Missing PDF file. [Less Information] [Close]
PDF.js v2.0.673 (build: 31012570)
Message: Missing PDF "https://www.foo.bar/admin/baz.php?order=1234&showpdf=1".
```

## Expected result:
Render the PDF correctly.

## Reproduces how often: 
Happens every time.

## Brave version (brave://version info)

```
Brave | 0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit)
Revision | ca97ba107095b2a88cf04f9135463301e685cbb0-refs/branch-heads/3538@{#1094}
OS | Linux
JavaScript | V8 7.0.276.40
```

### Reproducible on current release:
Does it reproduce on brave-browser dev/beta builds?<br>
Yes, on the following dev build:
```
Brave 0.58.10 Chromium: 71.0.3578.53 (Official Build) dev(64-bit)
Revision 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
```

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No.
- Is the issue reproducible on the latest version of Chrome? No.

**Comment by srirambv** [comment] 2018-12-05 11:48
Possible duplicate of https://github.com/brave/brave-browser/issues/1033. Please check on the next build if this issue is fixed. You can reopen the issue if it still happens after you upgrade to the release build.

**Closed by srirambv** 2018-12-05 11:48 UTC
