### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by papafred01** [brave/brave-browser#40538] opened 2024-08-19 18:16 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.68.141 Chromium: 127.0.6533.120
Operating System: Windows NT 10.0.19045

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/52491100-ebf9-720c-0000-000000000000

**Comment by bsclifton** [comment] 2024-08-20 19:02
Closing as duplicate of https://github.com/brave/brave-browser/issues/40540

**Closed by bsclifton** 2024-08-20 19:02 UTC
Labels: crash
