### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by vascobarbosa** [brave/brave-browser#40330] opened 2024-08-07 13:52 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.68.134 Chromium: 127.0.6533.88
Operating System: Mac OS X 14.0.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.https://developer.mozilla.org/en-US/docs/Web/CSS/font-size <- scrolling this website!
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/35020b00-3db3-650c-0000-000000000000

**Comment by rebron** [comment] 2024-08-07 19:09
@vascobarbosa Can you update to 1.68.137 and let us know if you're still seeing the crash?

**Comment by zenparsing** [comment] 2024-08-07 19:26
@vascobarbosa Try disabling this flag on `brave://flags`

<img width="744" alt="Screenshot 2024-08-07 at 3 26 00 PM" src="https://github.com/user-attachments/assets/2d2ab9d3-f295-4c48-94cd-3c04393a6c7a">

Does that help?

**Comment by vascobarbosa** [comment] 2024-08-07 19:29
It worked, didn't crash this time. whats happening ?

**Comment by zenparsing** [comment] 2024-08-07 19:34
I think that the browser is attempting to clear cached IPFS data when the site is visited (it's unclear why), and that procedure is interacting poorly with a recent Chromium update. IPFS node support has been removed in 1.69 (now Beta).

**Comment by sos0** [comment] 2024-08-08 00:18
Probably duplicate of #40329

**Comment by zcraber** [comment] 2024-08-10 14:57
Possible duplicate of #40102

**Comment by kjozwiak** [comment] 2024-08-13 18:58
> **DO NOT CHANGE BELOW THIS LINE** Crash ID: crash/35020b00-3db3-650c-0000-000000000000

Checked `BackTrace` and the above looks similar to the crash that was mentioned via https://github.com/brave/brave-browser/issues/40102#issuecomment-2262777553. So definitely related. Going to close this off as a duplicate. The above will be resolved by https://github.com/brave/brave-core/pull/25035 in the next `1.68.x` release which will occur sometime this week. If we don't get another `C127`, it will go out next week via `1.69.x`.

```
[ 00 ] base::OnceCallback<void (unsigned long long)>::Run(unsigned long long) && ( immediate_crash.h:176 )
[ 01 ] ChromeBrowsingDataRemoverDelegate::OnTaskComplete(ChromeBrowsingDataRemoverDelegate::TracingDataType, unsigned long long, base::TimeTicks, bool) ( chrome_browsing_data_remover_delegate.cc:1506 )
[ 02 ] base::OnceCallback<void ()>::Run() && ( callback.h:156 )
[ 03 ] base::internal::PostTaskAndReplyRelay::RunReply(base::internal::PostTaskAndReplyRelay) ( post_task_and_reply_impl.h:63 )
[ 04 ] void base::internal::DecayedFunctorTraits<void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&>::Invoke<void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay>(void (*&&)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&) ( bind_internal.h:671 )
[ 05 ] void base::internal::InvokeHelper<false, base::internal::FunctorTraits<void (*&&)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&>, void, 0ul>::MakeItSo<void (*)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>>(void (*&&)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>&&) ( bind_internal.h:930 )
[ 06 ] void base::internal::Invoker<base::internal::FunctorTraits<void (*&&)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&>, base::internal::BindState<false, true, false, void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay>, void ()>::RunImpl<void (*)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>, 0ul>(void (*&&)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>&&, std::__Cr::integer_sequence<unsigned long, 0ul>) ( bind_internal.h:1067 )
[ 07 ] base::internal::Invoker<base::internal::FunctorTraits<void (*&&)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&>, base::internal::BindState<false, true, false, void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay>, void ()>::RunOnce(base::internal::BindStateBase*) ( bind_internal.h:980 )
[ 08 ] base::OnceCallback<void ()>::Run() && ( callback.h:156 )
[ 09 ] base::TaskAnnotator::RunTaskImpl(base::PendingTask&) ( task_annotator.cc:203 )
[ 10 ] void base::TaskAnnotator::RunTask<base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*)::$_3>(perfetto::StaticString, base::PendingTask&, base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*)::$_3&&) ( task_annotator.h:90 )
[ 11 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) ( thread_controller_with_message_pump_impl.cc:484 )
[ 12 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:346 )
[ 13 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:0 )
[ 14 ] base::OnceCallback<void ()>::Run() && ( callback.h:156 )
[ 15 ] base::TaskAnnotator::RunTaskImpl(base::PendingTask&) ( task_annotator.cc:203 )
[ 16 ] void base::TaskAnnotator::RunTask<base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*)::$_3>(perfetto::StaticString, base::PendingTask&, base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*)::$_3&&) ( task_annotator.h:90 )
[ 17 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) ( thread_controller_with_message_pump_impl.cc:484 )
[ 18 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:346 )
[ 19 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:0 )
[ 20 ] base::MessagePumpCFRunLoopBase::RunWork() ( message_pump_apple.mm:449 )
[ 21 ] invocation function for block in base::MessagePumpCFRunLoopBase::RunWorkSource(void*) ( message_pump_apple.mm:421 )
[ 22 ] base::apple::CallWithEHFrame(void () block_pointer)
[ 23 ] __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
[ 24 ] __CFRunLoopDoSource0
[ 25 ] __CFRunLoopDoSources0
[ 26 ] __CFRunLoopRun
[ 27 ] CFRunLoopRunSpecific
[ 28 ] RunCurrentEventLoopInMode
[ 29 ] ReceiveNextEventCommon
[ 30 ] _BlockUntilNextEventMatchingListInModeWithFilter
[ 31 ] _DPSNextEvent
[ 32 ] -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
[ 33 ] __71-[BrowserCrApplication nextEventMatchingMask:untilDate:inMode:dequeue:]_block_invoke ( chrome_browser_application_mac.mm:335 )
[ 34 ] __71-[BrowserCrApplication nextEventMatchingMask:untilDate:inMode:dequeue:]_block_invoke ( chrome_browser_application_mac.mm:335 )
[ 35 ] base::apple::CallWithEHFrame(void () block_pointer)
[ 36 ] -[NSApplication run]
[ 37 ] base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*) ( message_pump_apple.mm:807 )
[ 38 ] base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*) ( message_pump_apple.mm:807 )
[ 39 ] base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) ( message_pump_apple.mm:161 )
[ 40 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ( thread_controller_with_message_pump_impl.cc:654 )
[ 41 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ( run_loop.cc:0 )
[ 42 ] base::RunLoop::Run(base::Location const&) ( run_loop.cc:134 )
[ 43 ] content::BrowserMainLoop::RunMainMessageLoop() ( browser_main_loop.cc:1085 )
[ 44 ] content::BrowserMainRunnerImpl::Run() ( browser_main_runner_impl.cc:160 )
[ 45 ] content::BrowserMain(content::MainFunctionParams) ( browser_main.cc:34 )
[ 46 ] content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) ( content_main.cc:332 )
[ 47 ] content::ContentMain(content::ContentMainParams) ( content_main.cc:345 )
[ 48 ] content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) ( content_main.cc:332 )
[ 49 ] content::ContentMain(content::ContentMainParams) ( content_main.cc:345 )
[ 50 ] ChromeMain ( chrome_main.cc:192 )
[ 51 ] start
[ 52 ] start
```

**Closed by kjozwiak** 2024-08-13 18:58 UTC
Labels: closed/duplicate, crash, QA/No, release-notes/exclude, OS/Desktop
