### ISSUE TITLE
Can't reclaim half a gigabytes diskspace after Brave installation

### ISSUE THREAD

**Issue by FrederikSchack** [brave/brave-browser#32693] opened 2023-09-03 15:06 UTC
## Description 
Quick install and uninstall of Brave Browser Nightly Silent Install, leaves half a gigabyte of files somewhere.
This is on a Windows 10 Enterprise LTSC 2021, with all automatic updates disabled and no other software installed.
Around 150 mb data in AppData wasn't cleaned out, but I have no idea where the rest of the data are residing.

## Steps to Reproduce

   1. Check disk size
   2. Install Brave
   3. Uninstall Brave
   4. Check disk size 

## Actual result:
Half a gigabyte of diskspace is occupied somewhere, after uninstalling.

## Expected result:
That it shouldn't be difficult to reclaim the diskspace taken by Brave.

## Brave version (brave://version info)
BraveBrowserStandaloneSilentNightly

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment] 2023-09-08 15:39
cc: @mherrmann

**Comment by mherrmann** [comment] 2023-09-18 06:20
I've checked. For me, 340 MB are taken up by `C:\Program Files (x86)\BraveSoftware\Update` immediately after uninstallation. This accounts for practically all of the difference described by @FrederikSchack (340 + 150 MB = ~ 0.5 GB).

@FrederikSchack I believe the difference is caused by Brave Update still being around on your system - for a while. Once Brave Update realizes that no more copies of Brave are installed on your system, it uninstalls itself. It checks this every few hours. So in other words, almost all space should be reclaimed within a few hours.

In my tests, `Get-Volume` gave 24.56 GB free before, and 24.54 GB free after.

**Comment by bsclifton** [comment] 2024-02-12 20:38
@FrederikSchack does the above help answer your question? I'll close this out for now - but please feel free to re-open if you have follow up questions

**Closed by bsclifton** 2024-02-12 20:38 UTC
Labels: OS/Windows, setup/installer, OS/Desktop
