### ISSUE TITLE
Disable domain reliability reporting

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#1734] opened 2018-10-19 19:10 UTC
The domain reliability subsystem tracks whether the browser has difficulty contacting Google-owned sites and uploads reports to Google. Gated behind the "Automatically send usage statistics and crash reports" preference, but the entire subsystem should be disabled and/or removed.

As a defense in depth, we could also disable the uploader class here: https://cs.chromium.org/chromium/src/components/domain_reliability/uploader.cc?l=73

**Comment by srirambv** [comment] 2018-10-26 16:07
dupe of https://github.com/brave/brave-browser/issues/889 ?

**Comment by pilgrim-brave** [comment] 2018-10-26 20:11
No, this is a separate issue.

**Closed** 2018-11-15 17:20 UTC
Labels: audit-release, privacy/connect
