### ISSUE TITLE
Importing bookmarks and passwords not working

### ISSUE THREAD

**Issue by dacomboman** [brave/brave-browser#6538] opened 2019-10-18 00:42 UTC
Have tried many times to import bookmarks and passwords from Firefox or Edge and even if a confirmation message popups to say it was successful, nothing really happens.

Can import from html but that's not what i want to do.

**Comment by dacomboman** [comment] 2019-10-22 01:45
What is odd... importing from Firefox on Solus went just fine!

**Comment by rebron** [comment] 2019-10-25 16:40
closing dupe of https://github.com/brave/brave-browser/issues/2198

**Closed by rebron** 2019-10-25 16:40 UTC
Labels: bug, feature/importer

**Comment by dacomboman** [comment] 2019-12-12 00:37
Latest edition has Firefox import all fixed up!
Thank you! ;)

**Comment by bsclifton** [comment] 2019-12-12 06:03
Awesome, thanks for confirming, @dacomboman 😄👍
