### ISSUE TITLE
Brave rewards shows thousands of errors that increase with every process relaunch

### ISSUE THREAD

**Issue by tiagosiebler** [brave/brave-browser#6867] opened 2019-11-11 13:33 UTC
## Description 

- In the URL bar I can see the little "Brave Rewards" triangle.
- When some kind of error happens in processing a contribution, a little counter increases in value, showing how many errors happened.
- Every time I close and reopen brave, this number will increase by several thousand (~5 new errors per second).
- Right now this error counter is at 23k!

## Steps to Reproduce

   1. Use Brave on macOS
   2. Somehow trigger this error loop, unclear how.
   3. Quit brave
   4. Open brave again
   5. Errors will keep going up.

## Actual result:

<img width="1308" alt="Screenshot 2019-11-11 at 13 30 30" src="https://user-images.githubusercontent.com/14090872/68590983-a2fff180-0487-11ea-9e87-b89c3677eee9.png">

Zoomed in:
<img width="95" alt="Screenshot 2019-11-11 at 13 31 30" src="https://user-images.githubusercontent.com/14090872/68590991-a5fae200-0487-11ea-8bc2-dcf86b317ffb.png">

If I click on it:
<img width="381" alt="Screenshot 2019-11-11 at 13 31 40" src="https://user-images.githubusercontent.com/14090872/68590994-a85d3c00-0487-11ea-88ee-8aa38086168f.png">

Hitting "x" will reduce the error counter, once per click. But it's not practical to click this 20k times...

## Expected result:
- Shows error once and once only.

## Reproduces how often: 

Easily reproduces each time browser is restarted. Does not go away.

## Brave version (brave://version info)

```
Brave | 0.70.123 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.14.6 (Build 18G103)
JavaScript | V8 7.8.279.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=NewExtensionUpdaterService,PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,UnifiedConsent,SyncUSSBookmarks --flag-switches-begin --enable-features=NewExtensionUpdaterService,PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator,fill-on-account-select --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/tsiebler/Library/Application Support/BraveSoftware/Brave-Browser/Default
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?
=> Yes, on the latest version.

- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
=> No

- Does the issue resolve itself when disabling Brave Rewards?
=> No
- Is the issue reproducible on the latest version of Chrome? 
=> Not applicable, brave-specific feature

**Comment by tiagosiebler** [comment] 2019-11-30 18:24
This is becoming worse. The error count is ridiculously high, and each time I restart brave it gets worse. CPU usage maxes out and I've noticed RAM usage peak as well:
<img width="539" alt="Screenshot 2019-11-30 at 18 20 11" src="https://user-images.githubusercontent.com/14090872/69904468-a3ace900-139e-11ea-915e-078ff285176a.png">

Help?

**Comment by NejcZdovc** [comment] 2019-12-01 09:12
@tiagosiebler sorry to hear about this problem. Just to double check you are not using the latest version correct (1.01)?

Can you please give me some more information:
- do you have AC enabled?
- did you do any tips so far?
- do you have any recurring tips?
- if you go to brave://rewards-internals/, does it looks something like this (of course ID's will be different in your case)
![image](https://user-images.githubusercontent.com/9574457/69911909-a05b4100-1422-11ea-9306-8a0e65b0075b.png)
- if you go to `‎⁨ ⁨~Library⁩/Application Support⁩/⁨BraveSoftware⁩/Brave-Browser⁩/Default` and open `ledger_state` do you have any `current_reconcile` entries?

Thank you so much for helping me find out why this is happening?

**Comment by tiagosiebler** [comment] 2019-12-01 10:55
Thanks for helping! 
> * do you have AC enabled?
What is AC referring to? 

> * did you do any tips so far?
No manual ones, though it does automatically do contributions - I haven't changed that. I suspect that's what's failing, as I haven't topped up my BAT balance.

> * do you have any recurring tips?
Nothing manually setup. 

> * if you go to brave://rewards-internals/, does it looks something like this (of course ID's will be different in your case)
>   ![image](https://user-images.githubusercontent.com/9574457/69911909-a05b4100-1422-11ea-9306-8a0e65b0075b.png)

It looks like that's the part that's failing - this page is very long:
<img width="383" alt="Screenshot 2019-12-01 at 10 49 05" src="https://user-images.githubusercontent.com/14090872/69912928-a81de400-1428-11ea-88b2-f4406fed85e3.png">

The last entry at the page end is "Current Reconcile 6178"

> * if you go to `‎⁨ ⁨~Library⁩/Application Support⁩/⁨BraveSoftware⁩/Brave-Browser⁩/Default` and open `ledger_state` do you have any `current_reconcile` entries?

This file is large, 4.1MB. current_reconciles is a huge object with roughly 200k lines below it. Would it help to manually clear the object, removing all keys? Or is there an easier way?

Thanks again @NejcZdovc !

**Comment by NejcZdovc** [comment] 2019-12-01 13:53
Thanks for this info. I have two more. 

1) Do you have the latest Brave and does this still happens?

2) Do you have any balance in your wallet?

**Comment by tiagosiebler** [comment] 2019-12-01 15:08
Yes latest update based on the auto update on relaunch.

The wallet has roughly 20 bat but it might not be enough for the auto contribution from previous usage.

**Comment by tiagosiebler** [comment] 2019-12-02 09:31
So in desperate times, I made a backup of the file and cleared the `current_reconciles` object while brave wasn't running. Relaunched brave - while I can't read the number errors anymore since it's too tiny in size (I think it's at 35k?) I don't think it's going up anymore. So the remaining ask is how can I flush out the error count.

Sure, issue could happen again, but at this stage I don't want to lose more time fighting it (or the lag from the CPU usage it causes on relaunch).

**Comment by NejcZdovc** [comment] 2019-12-04 07:50
You can clear your notifications with going into `⁨~Library⁩/Application Support⁩/⁨BraveSoftware⁩/Brave-Browser⁩/Default` and opening `Preferences` file. In there you find `notifications` that looks like this for me now `"notifications": "{\"displayed\":[],\"notifications\":[{\"args\":[],\"id\":\"rewards_notification_grant_36baa4c3-f92d-4121-b6d9-db44cb273a02\",\"timestamp\":1575445646,\"type\":2}]}",` and change it to `"notifications": "{}"`. This should clear them. Path to `notifications` is `brave->rewards->notifications`

@tiagosiebler I think that I am getting closer figuring out what is happening. Could you maybe please open your backup file of `ledger_state` and check if `userId` is populated. Thank you

**Comment by tiagosiebler** [comment] 2019-12-04 12:00
@NejcZdovc it is not populated:
![Screenshot 2019-12-04 at 11 59 47](https://user-images.githubusercontent.com/14090872/70140878-a0ab4480-168d-11ea-9f91-5b301cb36724.png)

**Comment by tiagosiebler** [comment] 2019-12-04 12:17
hmm the notification clear didn't work and I just had to clear current_reconcile again because the error account was rising sharply again

**Comment by NejcZdovc** [comment] 2019-12-04 12:25
@tiagosiebler thank you very much for helping me with this one. I spend the whole day today debugging and trying to reproduce it. I have some fixes, but sadly I still don't understand what is putting you in this loop. Would you maybe have some time for a zoom call. If so please send me an email to nejc @ brave.com

**Comment by tiagosiebler** [comment] 2019-12-05 10:07
Thanks for spending time on this! @NejcZdovc I've dropped you an email, I'm flexible today for a chat to try and debug this together.

**Comment by NejcZdovc** [comment] 2019-12-06 07:02
@tiagosiebler logged an issue for notifications https://github.com/brave/brave-browser/issues/7239

**Comment by tiagosiebler** [comment] 2019-12-16 10:39
@NejcZdovc just restarted brave because I saw there was an update. The error count is going up again - not sure if the latest has the fixes you've made so far?

**Comment by NejcZdovc** [comment] 2019-12-16 10:52
@tiagosiebler sadly that landed in only in 1.4 version, so it will take some time to be released

**Comment by tiagosiebler** [comment] 2019-12-16 11:11
Darn, is there an ETA for 1.4?

**Comment by NejcZdovc** [comment] 2019-12-16 12:13
Our release dates are here https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#release-channel-dates

**Comment by NejcZdovc** [comment] 2019-12-16 12:14
@kjozwiak maybe we can uplift it into 1.3?

**Comment by tiagosiebler** [comment] 2020-01-08 16:36
Bump - this just got extremely bad to the point where brave wasn't even letting me interact with it anymore, completely frozen at 100% CPU usage. 

I had to manually go into the ledger_state and Prefernces files to clear those massive objects, before relaunching. Now it's fine again. Please prioritise so I don't need to do this regularly, it easily costs up to 30 minutes of productivity, if not more, trying to deal with the lag then the issue itself....

**Comment by tiagosiebler** [comment] 2020-04-06 15:01
Hey @NejcZdovc & @kjozwiak - hope you're both well. I haven't seen this number fly up like crazy anymore, but I do still have a very high number of errors that doesn't seem to ever clear itself:
<img width="181" alt="Screenshot 2020-04-06 at 16 01 22" src="https://user-images.githubusercontent.com/14090872/78572825-dfa9fc00-781f-11ea-8ef6-910513249485.png">

It's so high I can't even really read it...is there a way to clear it for good, forget there were ever this many errors?

**Comment by NejcZdovc** [comment] 2020-04-10 12:29
@tiagosiebler let me fix this for you with https://github.com/brave/brave-browser/issues/7239

**Comment by NejcZdovc** [comment] 2020-04-10 12:29
closing this one as main issue was resolved, will finalize it in #7239

**Closed by NejcZdovc** 2020-04-10 12:29 UTC
Labels: feature/rewards, needs-more-info

**Comment by tiagosiebler** [comment] 2020-04-10 14:20
Thanks, would be nice to be rid of these errors @NejcZdovc - please let me know once there's an ETA

**Comment by NejcZdovc** [comment] 2020-04-10 16:06
@tiagosiebler will work on it next week

**Comment by tiagosiebler** [comment] 2020-04-10 16:14
Thanks!
