### ISSUE TITLE
Linkedin.com keeps reloading.

### ISSUE THREAD

**Issue by rkavalap** [brave/brave-browser#3038] opened 2019-01-21 23:49 UTC
https://github.com/brave/browser-laptop/issues/12645

Re-opening the above issue. I tried re-installing the problem returned about ~24hrs. 

Attaching the repro video
I am happy to provide any more information. 
[linkedin.zip](https://github.com/brave/brave-browser/files/2780799/linkedin.zip)

**Comment by rebron** [comment] 2019-02-15 16:55
@rkavalap Can you try logging in with shields down?

**Comment by ruckc** [comment] 2019-02-18 00:02
I don't use brave, but it's happening to me in a native chrome browser, no extensions.

**Comment by srirambv** [comment] 2019-02-18 02:48
I can't reproduce this on the dev build. Works just fine. No infinite reload after logging in with shields up

**Comment by coakleypa** [comment] 2019-02-18 14:39
Happening me on native Chrome.

**Comment by sx01g4r** [comment] 2019-02-22 16:30
The same thing is happening with me, there seems an issue with Linkedin cookies. Actually I logged in with two different account in same browser. Just deleted all cookies and logged in again. its fine now.

**Comment by rkavalap** [comment] 2019-02-22 18:17
@rebron @srirambv @sx01g4r 
I agree with website working after deleting cookies. That's something i tried in the recent past when it happened.  If you can provide me ways to capture any additional diagnostic info, I can try doing that to isolate the problem.

**Comment by rebron** [comment] 2019-02-26 19:50
Closing out. Looks like after deleting cookies you're good to go.

**Closed by rebron** 2019-02-26 19:50 UTC
Labels: waiting upstream
