### ISSUE TITLE
`Connect` button is overlapping on `Automatic- Use the best server available` text

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#41616] opened 2024-10-14 11:32 UTC
### Description

Found while testing https://github.com/brave/brave-browser/issues/38186
`Connect` button is overlapping on `Automatic- Use the best server available` text 

### Steps to reproduce

1. NA

### Actual result

![Image](https://github.com/user-attachments/assets/52229dd8-470b-409c-8c49-dfbe665dbf5b)

### Expected result

connect button should not overlap on the text

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.71.112 Chromium: 130.0.6723.44 (Official Build) (arm64)
-- | --
Revision | 7d51df656b247f9432ee714a6d160142a1e11c13
OS | macOS Version 12.5 (Build 21G72)

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/legacy_qa @aguscruiz @simonhong

**Comment by aguscruiz** [comment] 2024-10-14 11:42
This is the expected behavior. The connect button always shows above the text below

**Comment by srirambv** [comment] 2024-10-14 12:27
Dupe of https://github.com/brave/brave-browser/issues/40930

**Closed** 2024-10-14 12:31 UTC
Labels: feature/user-interface, priority/P3, QA/Yes, release-notes/exclude, OS/Desktop, feature/vpn
