### ISSUE TITLE
Consider adding overseas territories as part of supported Brave Ads regions

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4347] opened 2019-05-08 14:17 UTC
## Description 

Consider adding overseas territories as part of supported region

cc @tmancey @jsecretan @lukemulks

**Comment by GeetaSarvadnya** [comment] 2019-05-08 16:51
1+ https://community.brave.com/t/no-ads-shown-at-all/58611/15

**Comment by Jeshii** [comment] 2019-05-09 02:00
Need this in Japan!

**Comment by GeetaSarvadnya** [comment] 2019-05-28 09:04
1+ https://community.brave.com/t/did-you-forget-us-territories/62855/2

**Comment by eljuno** [comment] 2019-06-11 21:14
+1 from communityfor New Caledonia (France)

https://community.brave.com/t/no-ads-in-new-caledonia/64539?u=eljuno

**Comment by GeetaSarvadnya** [comment] 2019-06-24 04:05
+1 from community US territory (Puerto Rico)

https://community.brave.com/t/ads-enabled-but-not-earning-bat/66148/17

**Comment by jwchong** [comment] 2019-09-23 11:18
Consider adding International Ads. If not, please show a message to indicate that the user region is not supported, to avoid confusion from users expecting to earn BAT.

**Comment by tmancey** [comment] 2019-09-23 20:45
@jwchong You should see a message along the lines of "Ads are not supported in your region" on the chrome://rewards/ page. Thanks

**Comment by jwchong** [comment] 2019-09-25 15:22
@tmancey Please refer to below screenshots. I did not see "Ads are not supported in your region" anywhere, and I did not receive any BAT after 1 month usage (few hours usage daily).

Another question is, do we receive BAT for using iOS Brave app?

<img width="1060" alt="Screenshot 2019-09-25 at 11 12 43 PM" src="https://user-images.githubusercontent.com/24342851/65615035-45a10580-dfeb-11e9-9e09-e7de02457d34.png">
<img width="1059" alt="Screenshot 2019-09-25 at 11 13 05 PM" src="https://user-images.githubusercontent.com/24342851/65615036-45a10580-dfeb-11e9-8f62-7da87d526e7e.png">

Thanks.

**Comment by tmancey** [comment] 2019-09-30 18:33
Brave rewards is coming to iOS, with regards to you not receiving any BAT could you please let me know your region so we can investigate further? Thanks

**Comment by jwchong** [comment] 2019-09-30 22:05
I am in Malaysia.

**Comment by eljuno** [comment] 2020-03-07 05:23
Covered here #7817?

**Comment by tmancey** [comment] 2020-03-10 09:23
Closing issue as a duplicate of #7817

**Closed by tmancey** 2020-03-10 09:23 UTC
Labels: feature/ads, needs-discussion, suggestion

**Comment by GeetaSarvadnya** [comment] 2020-03-10 09:28
@tmancey Sound good. Thanks for referencing the issue.
