### ISSUE TITLE
Warn more about HTTP in Tor

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1136] opened 2018-09-15 00:06 UTC
Tor exit relays may be more nefarious than a typical ISP, and nobody picks their exits manually so there's less of a trust relationship. HTTP over Tor should be even more ⚠️ than HTTP elsewhere.

**Comment by arthuredelstein** [comment] 2022-09-27 21:26
Resolved as duplicate of #23030

**Closed by arthuredelstein** 2022-09-27 21:26 UTC
Labels: feature/tor, priority/P5
