### ISSUE TITLE
Claim UGP grants popup alignment issue in 1.26.x

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#15891] opened 2021-05-17 08:40 UTC
## Description 

Claim UGP grants popup alignment issue in 1.26.x

## Steps to Reproduce

   1. Clean profile 1.26.x
   2. Claim UGP grants
 

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/118459318-4420d580-b719-11eb-96cf-2ead19a8e9e1.png)

## Expected result:

No alignment issues
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.26.21 Chromium: 91.0.4472.57 (Official Build) nightly (64-bit)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | Windows 10 OS Version 2004 (Build 19041.985)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @emerick @zenparsing

**Comment by LaurenWags** [comment] 2021-05-17 14:16
Likely duplicate of https://github.com/brave/brave-browser/issues/15890#issuecomment-842361550

**Comment by zenparsing** [comment] 2021-05-19 14:57
Closing as duplicate.

**Closed by zenparsing** 2021-05-19 14:57 UTC
Labels: OS/Desktop, QA/Test-Plan-Specified, QA/Yes, closed/duplicate, feature/rewards, regression
