### ISSUE TITLE
New Tab Page uses 'chrome' links for History, Bookmarks, and Preferences

### ISSUE THREAD

**Issue by JimB-Dev** [brave/brave-browser#17156] opened 2021-07-25 21:46 UTC
## Description 
Internal hyperlinks on New Tab Page link to 'chrome://' (instead of 'brave://') locations.

## Steps to Reproduce

   1. Open a new tab to get to the NTP
   2. Hover over any of the Preferences, Bookmarks, or History buttons in the bottom-right corner
   3. Note that they all link to chrome:// locations instead of the Brave-branded brave://locations

## Actual result:
![image](https://user-images.githubusercontent.com/57846932/126914370-4ef460db-580d-4362-8d08-68b698d1b01b.png)

## Expected result:
Use brave:// internal links.

## Reproduces how often: 
Easily/consistently.

## Brave version (brave://version info)
1.27.108

## Miscellaneous Information:
Issue looks to be stemming from here: https://github.com/brave/brave-core/blob/master/components/brave_new_tab_ui/components/default/footer/footer.tsx#L96-L102

**Comment by bsclifton** [comment] 2021-07-26 08:24
Thanks for the report @JimB-Dev - closing as a duplicate of https://github.com/brave/brave-browser/issues/2566

**Closed by bsclifton** 2021-07-26 08:24 UTC
Labels: OS/Desktop
