### ISSUE TITLE
`Person 1` profile keeps coming back after being deleted - Cannot delete the 'Default' user profile

### ISSUE THREAD

**Issue by maurelian** [brave/brave-browser#4599] opened 2019-05-24 18:55 UTC
## Test plan
See https://github.com/brave/brave-core/pull/13929

## Description 

- Recently a new profile named 'Person 1' started appearing in the menu. I cannot delete this account, and it is the default option when switching profiles, so it's quite annoying.

### Approach 1:
   1. See undesired profile in menu named `Person 1`.
   2. Go to "Manage People", click on 3-dots button for `Person 1`, click 'Delete this person'
   3. Exit and restart brave. 
   4. `Person 1` is back

###  Approach 2: 
   1. See undesired profile in menu named `Person 1`.
   2. Open brave://version, look for Profile Path, which is `~/.config/BraveSoftware/Brave-Browser/Default`
  3. Delete that directory.
  4. Restart Brave.
  5. `Person 1` is back. The directory is back.

## Actual result:

![image](https://user-images.githubusercontent.com/23033765/58350116-02fbd080-7e33-11e9-91a4-c585252af3ef.png)

## Expected result:

`Person 1` does not come back. 

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

Brave | 0.62.51 Chromium: 73.0.3683.103 (Official Build)unknown (64-bit)
Revision | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS | Linux

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?

No.

- Does the issue resolve itself when disabling Brave Rewards?

Doubtful.

- Is the issue reproducible on the latest version of Chrome? 

No. There is no unwanted profile when I open Chrome version 74.0.3729.131 (Official Build) (64-bit)

**Comment by Corgi** [comment] 2019-06-04 14:21
I also have this issue. I use Brave on a Windows machine and a Mac, and this issue only manifests on the Windows install.

**Comment by rebron** [comment] 2019-06-07 15:43
cc: @kjozwiak To see if this is an issue on Windows. 

Also need to update reproducible steps.

**Comment by srirambv** [comment] 2019-06-07 17:03
Here's the proper reproducible steps
1. Start a clean profile
2. Click on people icon and click on Manage people
3. Add a new person in Manage people window
4. Click on `Person 2` window and click on people icon, lists `Person 1` in the list
5. In manage people window, click on 3 dots of `Person 1` and delete it
6. Open `Person 2`window and click on people icon, still lists `Person 1` there. Clicking that will create a new `Person 1` window

**Comment by kjozwiak** [comment] 2019-06-11 15:07
@srirambv can you reproduce the above on Win as well or this strictly occurring on Linux only?

**Comment by srirambv** [comment] 2019-06-11 15:09
Yet to check on Windows.

**Comment by srirambv** [comment] 2019-06-12 12:07
This seems to be a problem on Linux only. Verified the same steps from https://github.com/brave/brave-browser/issues/4599#issuecomment-499962715 on Windows and it doesn't show `Person 1` option in people menu drop down after its removed.

**Comment by sumitkumar1209** [comment] 2019-07-15 10:38
Happening to me on 
macOS v10.14.5 

and 

Brave desktop 
Version 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)

**Comment by theAeon** [comment] 2019-07-16 23:52
Happening on Win here


Brave | 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1903 (Build 18362.239)


Others have reproduced the issues here:
https://www.reddit.com/r/brave_browser/comments/btoibq/how_do_i_stop_person_1_profile_from_creating

**Comment by GeetaSarvadnya** [comment] 2019-07-24 19:17
This issue is Reproducible on Windows 10 x64


Brave | 0.67.112 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 10 OS Version 1803 (Build 17134.523)

**Comment by aapit** [comment] 2019-08-06 10:27
This error is still occurring in Brave on Linux.

Brave version: `0.67.123`
OS: `Ubuntu 19.04`

**Comment by georgewitteman** [comment] 2019-09-09 15:39
I have this issue on `macOS 10.14.6` and Brave `Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)`

**Comment by yatoh** [comment] 2019-09-24 07:29
I have the same issue.

OS: `Windows 10`
Brave: `Version 0.68.140 Chromium: 77.0.3865.90 (Build officiel) (64 bits)`

**Comment by iranmarcius** [comment] 2019-09-28 01:30
Happening here:


Brave | 0.68.142 Chromium: 77.0.3865.90 (Versão oficial) 64 bits
Revision| 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
SO | Windows 10 OS Version 1903 (Build 18362.356)

**Comment by iranmarcius** [comment] 2019-09-29 13:50
I thought it would happen only when I deleted "person 1" profile, as a a consequence of Brave recreating and selecting the default profile automatically.

But it's not it. From time to time, even with a pre-existent "person 1" profile Brave keeps selecting when open.  It's not a huge problem, of course, but it's a litte bit anoying.

**Comment by Brave-Matt** [comment] 2019-10-09 19:55
+1 from reddit
https://www.reddit.com/r/brave_browser/comments/dffjwp/user_profile_person_1_keeps_appearing_everytime/

**Comment by luangjokaj** [comment] 2019-10-09 20:02
I have the same issue. When I installed Brave, I created +2 new accounts, then deleted the first "original" account. After restarting Brave "Person 1" always keeps coming back.


**Brave** | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
**Revision** | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
**OS** | macOS Version 10.15 (Build 19A583)

**Comment by LaurenWags** [comment] 2019-10-09 20:31
Reproduced on macOS

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

Reproduced using scenario from https://github.com/brave/brave-browser/issues/4599#issuecomment-540166679

**Comment by garroch** [comment] 2019-11-07 00:12
Reproduced on Windows 10, also using scenario from https://github.com/brave/brave-browser/issues/4599#issuecomment-540166679 

Version: 0.70.122 Chromium: 78.0.3904.87 (Official Build) (64-bit)
OS: Windows 10 Home v.1903 build 18362.418

**Comment by glgomes** [comment] 2019-11-13 16:27
This error is still happening:

Version 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)

**Comment by garroch** [comment] 2019-11-14 14:54
I had previously reported this issue on Win10 / Brave 0.70.122, but this appears to be resolved in 1.0.0. 

I completely uninstalled Brave 0.70.122 (selecting the option to erase all website data on uninstall), then reinstalled a fresh copy of 1.0.0.

**Comment by chiselwright** [comment] 2020-01-08 16:31
Seeing the issue on:

OS|macOS Catalina 10.15.2
--|-----------------
Brave|Version 1.2.41 Chromium: 79.0.3945.88 (Official Build) (64-bit)

**Comment by Jammerlee** [comment] 2020-01-27 04:17
Also having this issue on Windows 10 x64

**Comment by alexanderlarsen** [comment] 2020-03-23 08:35
I have this issue as well. 

Win 10 x64
Brave: Version 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)

**Comment by MrTheRich** [comment] 2020-04-08 15:21
Still having this issue as well. 

Win 10 x64
Vrave: Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)

**Comment by Jecht5** [comment] 2020-09-05 05:32
Still having this issue as well.

Win 10
Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)

**Comment by IcyMidnight** [comment] 2021-02-15 10:34
I'm seeing this as well recently. I noticed because Brave suddenly has a profile icon over the app icon that I don't recall seeing before.

I only have one user profile in Brave.

Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)

**Comment by arnaudjuracek** [comment] 2021-02-17 10:38
I have the issue as well.

macOs Mojave 10.14.6
Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (x86_64)

**Comment by AnghusMcleod** [comment] 2021-02-20 16:22
Confirmed as well; i even tried renaming my profile to Profile 1, only to have Brave create a Profile 2 🤦 

Windows 10.0.18363 Build 18363
Version 1.20.103 Chromium: 88.0.4324.152

**Comment by RattleTotem** [comment] 2021-03-09 06:13
I have the same issue, Profile 2 keeps reappearing.

Windows 10, 10.0.19041 Build 19041
Version 1.21.74 Chromium: 89.0.4389.72 (Official Build) (64-bit)

**Comment by p-lau** [comment] 2021-03-16 06:16
Found a solution on Windows:

**Make sure Brave application is not running.**

1. Go to wherever your main Profile folder is stored, in my case, that folder is stored in:
`C:\Users\{$Username}\AppData\Local\BraveSoftware\Brave-Browser\User Data`

2. Rename it to `Default` (I deleted every other profile until there is only my main Profile, named `Profile 2`)

3. Start your Brave application.

I guess it's because whenever Brave gets an update and restarts, it tries to find the `Default` profile, but since some people, like me, deleted the first profile and kept the next one `Profile #`, it automatically creates a new profile folder `Default`.

Windows 10, 10.0.19041 Build 19041
Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)

**Comment by andyraddatz** [comment] 2021-03-16 19:14
@p-lau 's solution worked for me, except I still had an empty "Profile 2" after restart, then deleting Profile 2 worked as expected.  Seems that the list of profiles is saved somewhere so that deleting the folder for Profile 2 does not make Brave forget it exists.  Replacing the contents inside Default will at least allow you to get back to a single profile.

**Comment by RattleTotem** [comment] 2021-03-17 06:12
+1 The solution worked for me too. Same as @andyraddatz, I had two Profile 1's, although that may have been the consequence of my taskbar shortcut being assigned to Brave - Profile 1, instead of just Brave.

**Comment by IcyMidnight** [comment] 2021-03-17 11:37
FWIW, @p-lau's solution did not work for me. I tried to do the same, but ended up with two empty profiles named after my primary profile. I tried to get back to working, but couldn't. I tried deleting all profiles and ended up with two new ones each time I tried. I eventually gave up, deleted the `Brave-Browser\User Data` directory and had to start over. Thankfully I have Brave Sync turned on so it wasn't *too* painful, though there are a number of settings that don't properly sync. I now only have one profile, though, so that's something.

**Comment by Jecht5** [comment] 2021-03-17 12:13
my situation totally same as @IcyMidnight. but I am not as lucky as him, my previous profile now turned to empty profiles

**Comment by bsclifton** [comment] 2021-03-18 08:02
Got several +1's on this from https://github.com/brave/brave-browser/issues/14504

Verified this happens on Windows with Brave. Will try to narrow it down here

## Chrome
Here's what happens w/ Chrome (which works as expected):
1. Delete `%USERPROFILE%\AppData\local\Google\Chrome` profile root directory
1. Launch Chrome; new folder `Default` is created (`%USERPROFILE%\AppData\local\Google\Chrome\User Data\Default`)
1. Created 2nd user `Bubba`
1. Quit
1. Verified it created `Profile 1` folder on disk (`%USERPROFILE%\AppData\local\Google\Chrome\User Data\Profile 1`)
1. Relaunch
1. Delete `Person 1` in the profile manager
1. `%USERPROFILE%\AppData\local\Google\Chrome\User Data\Default` is not deleted yet
1. Quit Chrome
1. Verify `%USERPROFILE%\AppData\local\Google\Chrome\User Data\Default` is deleted
1. Check `Local State` JSON at profile root (`%USERPROFILE%\AppData\local\Google\Chrome\User Data\Local State`)
    ```json
      "profile": {
        "info_cache": {
          "Profile 1": {
            "active_time": 1616054098.736232,
            "avatar_icon": "chrome://theme/IDR_PROFILE_AVATAR_41",
            "background_apps": false,
            "gaia_given_name": "",
            "gaia_id": "",
            "gaia_name": "",
            "hosted_domain": "",
            "is_consented_primary_account": false,
            "is_ephemeral": false,
            "is_guest": false,
            "is_omitted_from_profile_list": false,
            "is_using_default_avatar": true,
            "is_using_default_name": false,
            "local_auth_credentials": "",
            "managed_user_id": "",
            "metrics_bucket_index": 2,
            "name": "Bubba",
            "shortcut_name": "Bubba",
            "user_name": ""
          }
        },
        "last_active_profiles": [],
        "last_used": "Profile 1",
        "metrics": {
          "next_bucket_index": 3
        },
        "profile_counts_reported": "13260527680566501",
        "profiles_created": 2
      },
      "profile_network_context_service": {
        "http_cache_finch_experiment_groups": "None None None"
      },
      "profiles": {
        "profiles_deleted": [
          "C:\\Users\\brian\\AppData\\Local\\Google\\Chrome\\User Data\\Default"
        ]
      },
    ```
1. Relaunch Chrome
1. Go to profile manager; verify no Person 1

## Brave
- Following same steps as Chrome
- Steps 1 - 12 work as expected 👍 
- Step 13 has the problem 🙀 Relaunching after deleting `Default` will create `Default` profile folder again (and then show `Person 1` in the profile manager)
- Deleting `Person 1` over and over again does NOT add additional entries to `profiles_deleted` in `Local State` JSON

**Comment by diogodh** [comment] 2021-03-27 23:55
Also with this issue. So annoying...

**Comment by saeedrahman** [comment] 2021-04-11 13:29
Adding my name to list...

**Comment by ubeutenm** [comment] 2021-04-16 16:10
Will this ever be fixed?

**Comment by afxgak** [comment] 2021-05-07 07:38
Yeah, will this ever be fixed? I am on mac os big sur m1 macbook.

**Comment by harogaston** [comment] 2021-05-13 01:38
2 years... it's sad

**Comment by JuliusHimself** [comment] 2021-05-18 14:42
The same issue on mac on every startup.

**Comment by woodl3y** [comment] 2021-05-31 01:43
Issue still happening for me also. Running Arch Linux with Brave 1.25.68

**Comment by pandito** [comment] 2021-06-20 01:23
Still happening in Manjaro Linux and Windows 10 with Versión 1.25.73 Chromium: 91.0.4472.106 (Build oficial) (64 bits)

**Comment by Brave-Matt** [comment] 2021-06-21 17:16
@rebron this still comes up all the time -- do we need more information or something before this can get resolved?

**Comment by 73R3WY** [comment] 2021-08-13 13:50
+1 , and I thought I'm the only one encountering this issue but it seems like it's been two years old already :) . A new profile `Profile 1` is created every time Brave is updated and on fresh launch from startup. I'm using macOS 11.5.1 and Brave Version 1.28.105 Chromium: 92.0.4515.131 (Official Build) (x86_64) as of this writing. Hope it will be fixed already. 🤞

**Comment by trentycents** [comment] 2021-08-22 05:59
Why has this bug been going on for this long without being fixed. Please explain, why, why, oh why?

**Comment by fusionneur** [comment] 2021-08-23 22:10
> Why has this bug been going on for this long without being fixed. Please explain, why, why, oh why?

cause you didn't work it out :(

**Comment by trentycents** [comment] 2021-08-24 00:43
> > Why has this bug been going on for this long without being fixed. Please explain, why, why, oh why?
> 
> cause you didn't work it out :(

Cause I didn't work it out? Does this suggest you're aware how to work it out? In that event and given the number of people unable to fix this, it would be greatly appreciated if you could explain how to work it out, in the event you actually know

**Comment by Adeynack** [comment] 2021-08-24 07:48
What I ended up doing -- but it is a workaround, not a fix -- is:

- close _Brave_ completely
- rename one of the `Person n` (where `n` is a number) folder as `default`
- start _Brave_
- (There was a few additional step to make it happy that I sadly do not recall at this moment)

If there is a _default_ profile, _Brave_ is happy and won't recreate this _Person 1_ named profile anymore.

**Comment by Jammerlee** [comment] 2021-08-24 16:51
There's already a folder called "default" there. Changing folder names and/or swapping things around doesn't fix the problem

**Comment by Adeynack** [comment] 2021-08-24 22:10
> There's already a folder called "default" there. Changing folder names and/or swapping things around doesn't fix the problem

This topic is about the `default` folder re-appearing after being deleted.

**Comment by matthiasseghers** [comment] 2021-09-09 09:20
Also having this issue on Version 1.29.79 on Mac

**Comment by FBorowiec** [comment] 2021-09-17 09:51
still there on Linux - I find it quite annoying. Anyone know of a solution?

**Comment by RWiggers** [comment] 2021-09-30 14:22
After years it still happening? Shame on development team

**Comment by Adeynack** [comment] 2021-09-30 14:23
@FBorowiec @matthiasseghers 

[That workaround](https://github.com/brave/brave-browser/issues/4599#issuecomment-904406495) has fixed (or patched) it for me.

**Comment by fusionneur** [comment] 2021-09-30 22:18
For me it turned out that the pinned shortcut on taskbar might have been actually recreating the profile. Unpinned it and also used the tips from the workaround above to get the profile removed for good, and eventually recreated the pinned shortcut.

In my case, it was a bit tricky because my current profile was the "Default" one (i don't know if this is normal behaviour), so i renamed "Default" into "Default-something", openned brave and then the default profile was created. I closed Brave, removed Default folder and renamed "Default-something" back into Default. Also upon reopening several times, I removed Profile1 which was being created every time. I am not sure what action and in which stage the issue was exactly fixed it and I cannot reproduce the issue and the fix now. Hope it helps..

**Comment by steffenlohaus** [comment] 2022-02-09 07:08
Does one find the according directory with the profile folders **on a M1 Mac Book** already? Couldn't retrace the path here 🤷‍♂️

**Comment by Adeynack** [comment] 2022-02-09 08:39
> Does one find the according directory with the profile folders **on a M1 Mac Book** already? Couldn't retrace the path here 🤷‍♂️

@steffenlohaus : Are you talking about the folder where the profiles are saved? It would be `~/Library/Application Support/BraveSoftware/Brave-Browser`.

**Comment by steffenlohaus** [comment] 2022-02-09 18:43
Thank you @Adeynack . Unfortunately the folder doesn't there. I attached a screenshot of that path.

<img width="637" alt="Screenshot 2022-02-09 at 19 42 05" src="https://user-images.githubusercontent.com/646578/153268301-d6c23a2e-947c-47bd-9d1e-3e1d4d56e6cc.png">
e

**Comment by leotm** [comment] 2022-02-18 17:22
Similar worked for me ^

I removed the initial `Default` folder being re-created

Then renamed original `Profile 1` folder (_Person 1_) to `Default`

**Comment by cartierjf** [comment] 2022-02-20 16:28
Did not work for me. `Profile 1` folder is not present in `~/Library/Application Support/BraveSoftware/Brave-Browser` anymore and does not get recreated when relaunching Brave, but `Profile 1` still appears in the list of users.

**Comment by steffenlohaus** [comment] 2022-02-21 16:14
@cartierjf Please double-check the path. You mentioned "Library" in root. I found the magic place below my user directory.

See: "I went to the folder where the profiles are stored ~/**Users/{username}/**Library/Application Support/BraveSoftware (**pressing option in while being in the Finder enables the "Library" point in the "Go" menu**)."

**Comment by matthiasseghers** [comment] 2022-03-11 18:40
> @FBorowiec @matthiasseghers 
> 
> 
> 
> [That workaround](https://github.com/brave/brave-browser/issues/4599#issuecomment-904406495) has fixed (or patched) it for me.

Can confirm that the referred workaround did indeed fix the issue. As long as there is a "Default" profile folder a person (named person 1 as default name) won't be added.

**Comment by 0xjohnnycage** [comment] 2022-03-11 18:55
> @cartierjf Please double-check the path. You mentioned "Library" in root. I found the magic place below my user directory.
> 
> See: "I went to the folder where the profiles are stored ~/ **Users/{username}/** Library/Application Support/BraveSoftware (**pressing option in while being in the Finder enables the "Library" point in the "Go" menu**)."

`~/` is a shortcut for `/Users/{username}/`

**Comment by ourichermath** [comment] 2022-04-23 17:28
On Linux here.  Same problem.  I deleted the Default folder and renamed one of my Profile'n'  folders to Default.  I can now access that profile through the Default profile.  BUT, if I Edit that profile, the name/appearance won't change.  I also tried this by copying the contents of one of the Profle'n' folders into an empty Default folder.  But, I have the same problem:  I cannot rename the profile or change its icon.

**Comment by andybones** [comment] 2022-04-30 18:04
Here's what worked for me.
In my main profile, go to brave://version and see what your "Profile Path" is. For me it was Profile 4.
So I went to C:\Users\YourName\AppData\Local\BraveSoftware\Brave-Browser\User Data\ 
Make a backup of your Profile just in-case.
I cut everything in C:\Users\YouName\AppData\Local\BraveSoftware\Brave-Browser\User Data\Profile 4 and pasted it in and over-write everything in C:\Users\YourName\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
This fixed it for me. Profile 1 no longer gets created.

**Comment by abozaid-ibrahim** [comment] 2022-05-10 07:11
The same issue happens for my mac, very annoying, hopefully you fix it soon.

**Comment by user4302** [comment] 2022-05-11 05:11
> This error is still happening in Version 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)
> 
> There is a workaround:
> 
> 1. Go to your .config folder (something like /home/youruser/.config/BraveSoftware/Brave-Browser);
> 2. Backup your Default, Profile 1, Profile 2, Profile 3... folders somewhere else (if anything goes wrong you can restore to your original state);
> 3. Close all Brave windows, delete the contents of Default folder and move the contents of any other profile to the Default folder. Then you can delete empty folder;
> 4. Restart Brave.

this is the "solution" i used that works.
remember to keep the backups of the profiles.

im surprised its still not fixed after ~3 years  :l

**Comment by bridiver** [comment] 2022-07-04 22:32
We know what causes this, unfortunately we have to wait a month or two to merge the fix to avoid adding another variable to a comparison we're making to improve privacy with p3a.

**Comment by 0mars** [comment] 2022-07-13 17:13
having this too, WTF is this!! thought it's a malware or something!

**Comment by im0rca** [comment] 2022-09-09 11:55
Still aint fixed :')

**Comment by anomaly999** [comment] 2022-10-23 09:39
Any updates on a fix for this?  Still getting this annoying "Profile 1" being created every time even if I delete it!

**Comment by MeerKatDev** [comment] 2022-11-08 10:52
> We know what causes this, unfortunately we have to wait a month or two to merge the fix to avoid adding another variable to a comparison we're making to improve privacy with p3a.

a month or two passed already btw

**Comment by spylogsster** [comment] 2022-11-08 15:27
@DJAndries @bridiver can we take a look again on it? thanks

**Comment by omegadefender** [comment] 2023-01-08 09:01
Looks like this is going to be resolved soon, but for Windows users... don't delete the contents of the Default folder at C:\Users\{urUserName}\AppData\Local\BraveSoftware\Brave-Browser\User Data just copy-paste in the contents from the folder of one of your other profiles, and then delete the original folder of the profile you just copied into default. You will need to rename profile1 to whatever you called the profile you copied in, but you will see all your bookmarks etc have been copied.

**Closed** 2023-01-20 19:30 UTC
Labels: bug, priority/P3, QA/Yes, release-notes/include, feature/profile-manager, OS/Desktop

**Comment by brendon-wong** [comment] 2023-02-06 04:35
I am still experiencing this issue on Brave "Version 1.47.186 Chromium: 109.0.5414.119 (Official Build) (arm64)" on MacOS 13.1. I am have been regularly deleting Profile 1 and it keep reappearing on restart.

**Comment by MeerKatDev** [comment] 2023-02-06 08:26
Same version, same issue

**Comment by brendon-wong** [comment] 2023-02-06 23:52
Great! I was a bit thrown off by the discussion being closed but figured that might be the case given it was added to the 1.49.x - Nightly milestone. Will report back after updating post-March 7th!

**Comment by stephendonner** [comment] 2023-02-17 20:21
## Verification `IN-PROGRESS` using 

Brave | 1.49.100 Chromium: 110.0.5481.100 (Official Build) beta (x86_64)
-- | --
Revision | 4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS | macOS Version 11.7.4 (Build 20G1120)

**Comment by GeetaSarvadnya** [comment] 2023-02-20 10:30
Verification in progress on

```
Brave | 1.49.100 Chromium: 110.0.5481.100 (Official Build) beta (64-bit)
-- | --
Revision | 4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS | Windows 10 Version 21H2 (Build 19044.2604)

```

**Comment by bsclifton** [comment] 2023-03-01 08:09
Get out of here, Person 1! Hopefully we never see you around here again 😛

**Comment by btlechowski** [comment] 2023-03-08 17:16
Verification passed on

Brave | 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit) 
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Ubuntu 18.04 LTS

#### Tested and confirmed the following scenarios, without seeing `Profile 1` or similar, appearing

### Shared Steps:
<details>

1. installed `1.49.x`
2. launched Brave (this creates `Profile 1` which is fine at this step)
3. created the specified # of profiles, either/both `Bubba 1` and `Bubba 2`
4. restarted 
6. deleted `Profile 1` (auto-created on launch in step 2)
7. restarted
8. checked to see if the deleted `Profile 1` has now returned
9. (remaining steps only for single-profile case: additionally selected `Create a New Profile` from the top-level app menu)
10. typed `Blah` and saved
11. confirmed only `Blah` and the correct `Bubba(s)` -- and only those -- were present

</details>

In addition to the below, focus-tested around profile creation/management 👍 

#### Case 1: create a new profile, restart, delete, restart - `PASSED`
<details>

![image](https://user-images.githubusercontent.com/34715963/223781035-dbfb29c9-05a9-4db7-ab2b-d007dc9c53b4.png)
![image](https://user-images.githubusercontent.com/34715963/223781412-89941113-433a-4cba-8bfd-a78461bebc97.png)


</details>

#### Case 2: create two new profiles, restart, delete one, restart - `PASSED`
<details>

![image](https://user-images.githubusercontent.com/34715963/223781884-be722a04-c21e-48b2-ad0b-90aa216a6a30.png)
![image](https://user-images.githubusercontent.com/34715963/223782099-ad4cb4b8-977e-4e88-b1f8-2c286b48b0ac.png)


</details>

#### Case 3: create two new profiles, restart, delete both, restart - `PASSED`
<details>

![image](https://user-images.githubusercontent.com/34715963/223782919-3f10916c-958c-44b2-b456-a89978769e6f.png)
![image](https://user-images.githubusercontent.com/34715963/223783187-eb736a27-2f8d-4833-921f-0eba8dd02c1d.png)




</details>
