### ISSUE TITLE
Serial API

### ISSUE THREAD

**Issue by mathieunicolas** [brave/brave-browser#32008] opened 2023-08-01 12:33 UTC
Hi, for educational purpose I need to be able to communicate with a micro:bit card through serial port.
I don't understand why I can't find any "serial api" related option in the flags, did I do something wrong, or is there any problem with the Serial API on Brave ?

Thanks, cheers from France !

**Comment by bsclifton** [comment] 2023-08-01 16:38
@mathieunicolas it has been disabled by default for privacy reasons. See https://github.com/brave/brave-browser/issues/13902 for more information.

You should be able to enable via brave://flags/#brave-web-serial-api (may require a browser restart after enabling)

Please let me know if that helps!

**Comment by mathieunicolas** [comment] 2023-08-01 17:02
hi @bsclifton and thanks for your answer !
Looking for the option in flags is the first thing I did, but I can't find the brave-web-serial-api option. It's just not appearing.
The only one I can find is related to bluetooth ([#enable-bluetooth-spp-in-serial-api](chrome://flags/#enable-bluetooth-spp-in-serial-api)).
I run Brave on Debian and my version is `Version 1.56.14 Chromium: 115.0.5790.114 (Official Build)  (64-bit)`

What's wrong ?

**Comment by bsclifton** [comment] 2023-08-01 18:04
Good question... curious if @fmarier would have some ideas?

**Comment by fmarier** [comment] 2023-08-01 18:27
The flag is brand new. It will be coming in Brave 1.58, which is currently on the Nightly channel.

**Comment by fmarier** [comment] 2023-08-01 18:28
I'll mark this as a duplicate of the issue for adding the flag: https://github.com/brave/brave-browser/issues/24404

**Closed by fmarier** 2023-08-01 18:28 UTC
Labels: question, OS/Desktop

**Comment by bsclifton** [comment] 2023-08-01 18:29
Thanks, @fmarier! 😄 

@mathieunicolas please check out the comments in https://github.com/brave/brave-browser/issues/24404 for more info 🙂

**Comment by mathieunicolas** [comment] 2023-08-01 18:38
Waw, nice sync, the option comes to Brave when I need it !
Thanks a lot for your super-quick answers, and for your amazing work on Brave

**Comment by fmarier** [comment] 2023-08-01 19:42
@mathieunicolas Vous êtes le bienvenu !
