### ISSUE TITLE
YouTube fullscreen video flickering

### ISSUE THREAD

**Issue by Heithwald** [brave/brave-browser#3864] opened 2019-03-23 08:25 UTC
Hi.

## Description 
YouTube videos have playback issues when entering fullscreen. The UI instead of disappearing in a few seconds, puts the video flickering, both the frames and the UI, FPS drops significantly.

## Steps to Reproduce
   1. Open any YouTube video
   2. Click fullscreen
   3. Wait a few seconds until the UI is expected to disappear 

## Actual result:
Video flickering, FPS drop, unwatchable.

## Expected result:
**Proper video playback**

## Reproduces how often: 
**Easily reproduced**

## Brave version (brave://version info)
Brave | 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Windows 10 OS Build 17134.648

### Reproducible on current release:
**Yes**

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? - **No**
- Is the issue reproducible on the latest version of Chrome? - **No**

### Additional Information
**None**

**Comment by bsclifton** [comment] 2019-03-26 23:45
@Heithwald can you please try turning OFF hardware acceleration (in brave://settings)?

**Comment by Heithwald** [comment] 2019-03-28 18:50
> @Heithwald can you please try turning OFF hardware acceleration (in brave://settings)?

Hi. 

Seems like it did help, thanks.

**Comment by rebron** [comment] 2019-03-29 16:00
Closing.

**Closed by rebron** 2019-03-29 16:00 UTC
Labels: OS/Windows, feature/video, gpu/driver

**Comment by AMDphreak** [comment] 2019-08-25 19:58
This is still a problem. And disabling HW acceleration (I assume h264 pipeline) is less than ideal for the future. Can this be reopened?

**Comment by Arastys** [comment] 2019-09-20 17:18
I also have this issue, including on sites other than YouTube (BBC iplayer, local plex server).

Completely disabling HW acceleration isn't really an acceptable workaround. I'm guessing this is a problem with Brave interacting with the NVIDIA driver as manually setting Brave's vertical sync option appears to resolve this, at least when the Global option is Fast.

Workaround:
Open the NVIDIA control panel, Manage 3D settings, Program Settings and set Brave.exe to Adaptive vertical sync (other options may work aside from Fast). Globally I use the Fast setting.

**Comment by AMDphreak** [comment] 2019-09-21 04:48
> Open the NVIDIA control panel, Manage 3D settings, Program Settings and set Brave.exe to Adaptive vertical sync (other options may work aside from Fast). Globally I use the Fast setting.

I have Fast mode vertical sync set for all apps by default.

**Comment by Snaxeko** [comment] 2020-01-14 21:43
The bug is caused by Brave, Chrome works perfectly with **Nvidia Fast Sync**. Are there any plans to fix it ? As it works perfectly with Chrome or other chromium browsers, this issue should be reopened.
Thank you @Arastys for your workaround, it also works with the classical vsync.

**Comment by fusionneur** [comment] 2020-07-20 11:34
Can confirm that the issue is still present when fast vertical sync is set in nvidia.

**Comment by daath** [comment] 2020-08-20 23:08
This is still an issue. Full screen videos on youtube are unwatchable with Brave.

**Comment by Snaxeko** [comment] 2020-10-12 19:24
Issue is still here, why did you closed it @bbondy ? The workaround doesn't fix anything, it's very annoying to switch everytime you play or use the browser (and reopen it everytime) the vertical sync scheme.

**Comment by bbondy** [comment] 2020-10-13 15:58
@Snaxeko I didn't close it. It looks like it was closed here:
https://github.com/brave/brave-browser/issues/3864#issuecomment-478052843

Probably because of this report:
https://github.com/brave/brave-browser/issues/3864#issuecomment-477725950

Since there must be more than 1 issue going on, it would be best to post a new issue. Thank you!

**Comment by fusionneur** [comment] 2021-01-28 12:55
now the whole browser flickers whenever a borderless game is in behind of browser

**Comment by rekurzion** [comment] 2021-03-15 21:23
this is a problem for me regardless if i am in fullscreen or not. youtube videos (all i have tested at the moment) suffer greatly from this.

**Comment by bsclifton** [comment] 2021-03-15 21:27
@rekurzion have you tried disabling hardware acceleration? I don't think there's much we can do until the root cause is discovered/fixed

**Comment by thesoorajsingh** [comment] 2021-07-19 05:26
This is still an issue with the browser where it makes the video unwatchable, however, Turning off Hardware accelaration is not an option for someone who requires it (say for webGL). There is a workaround that i recently discovered. Heading to brave://flags and switching the ANGLE graphics backend to OpenGL instead of leaving it on automatic (Which I assume uses D3D11 drivers) seems to fix the flickering issue
![image](https://user-images.githubusercontent.com/50406680/126107331-1d1c9df5-0a50-4958-830e-4305202b5a9f.png)

**Comment by christopherjtaylor** [comment] 2021-09-08 03:04
> This is still an issue with the browser where it makes the video unwatchable, however, Turning off Hardware accelaration is not an option for someone who requires it (say for webGL). There is a workaround that i recently discovered. Heading to brave://flags and switching the ANGLE graphics backend to OpenGL instead of leaving it on automatic (Which I assume uses D3D11 drivers) seems to fix the flickering issue
> 
> EDIT: I'm not sure if some users might have a problem with using OpenGL as their default backend / if they require D3D11 but fo general users who might need hardware acceleration, this fixes the issue.
> ![image](https://user-images.githubusercontent.com/50406680/126107331-1d1c9df5-0a50-4958-830e-4305202b5a9f.png)

Haven't had an issue with flickering on videos since installing Brave a few months ago. For me, this issue was introduced with the update to 1.29.77. The ANGLE graphics backend fix recommended here fixed the issue for me.
