### ISSUE TITLE
Brave Stats Bug

### ISSUE THREAD

**Issue by RetsuThere** [brave/brave-browser#25702] opened 2022-09-29 15:01 UTC
## Brave Stats Bug
When I was trying to turn off or on the brave stats found in **Customise dashboard**  I found that even if I enable brave stats it does not respond.

## Steps to Reproduce
From where I was able to reproduce it bug. (Running macOS version 12.6 and on Version 1.44.101 Chromium: 106.0.5249.65)

1. Open a new tab in Brave browser.
2. Click Customise dashboard.
3. Click brave stats.
4. And try enabling or disabling brave stats It does not respond to our clicks.

## Actual result:
It does not respond to the clicks for enabling of disabling brave stats.

![Brave Browser bug](https://user-images.githubusercontent.com/114663230/193064791-8dc58110-533b-4ae2-8ece-4dc5bb928cbe.jpeg)
![Brave Browser bug unedited](https://user-images.githubusercontent.com/114663230/193064766-343c144e-08f6-4b5e-9d2d-2f879cc303f1.jpeg)

## Expected result:
The brave stats should appear or disappear.

## Reproduces how often: 
Always and every time.

## Brave version
Installed build: macOs Monterey version 12.6 
Brave version: 1.44.101 Chromium: 106.0.5249.65 (Official Build) (x86_64) Stable version

**Comment by stephendonner** [comment] 2022-09-29 15:18
Duplicate of https://github.com/brave/brave-browser/issues/24985.

**Closed by stephendonner** 2022-09-29 15:18 UTC
Labels: OS/Desktop
