### ISSUE TITLE
[Android] Request write permissions for stats sharing

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#15298] opened 2021-04-14 16:48 UTC
## Description 

Not having the storage write permission already added results in a crash when trying to share stats 

## Steps to reproduce 

   1. Disable Storage permission (if it's set to Allow)
   2. Navigate to a web page
   3. Press the shields button and then the share icon or
   3.1 Wait for one the blocked ads+ trackers tier numbers to be hit and press the share button on the tooltip.

## Actual result 

The app crashes with a permission error

## Expected result

If the write permission is not set the user should be presented with a request permission to allow storage write.
The flow of the stats share feature should not be interrupted and the app should not crash.
(We need storage write permission to temporary store the image containing the stats in order be share it)

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.25.13
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards?N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by srirambv** [comment] 2021-05-12 07:01
@anthonypkeane can't have open issues in the milestone unless its release blocking. @alexsafe can you confirm if the issue is fixed with brave/brave-core#8557?

Moving out of 1.25.x until confirmed. If this still needs to be fixed and should be part of 1.25.x need to have a PR done and get it uplifted to 1.25.x 

cc: @kjozwiak @bsclifton

**Closed** 2021-05-12 18:44 UTC
Labels: OS/Android, QA/Yes, bug, release-notes/include

**Comment by srirambv** [comment] 2021-05-19 08:50
Verification passed on OnePlus 6T with Android 10 running 1.25.60 x64 Beta build
- Verified clicking on share button prompts for requesting access to storage
--------------
Verification passed on Samsung Tab A with Android 10 running 1.25.60 x64 Beta build
- Verified clicking on share button prompts for requesting access to storage

OnePlus 6T | Samsung Tab A
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/118784058-93851400-b887-11eb-9a2f-f940937b2314.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/118784029-8cf69c80-b887-11eb-87a3-41043f8a6069.png>

**Comment by kjozwiak** [comment] 2021-05-27 01:58
Probably a good idea to recheck these as it was reverted from `1.25.x` which is the channel most of the QA was done for this feature. Depending on a fix, this might go into a `1.25.x` HF.

**Comment by srirambv** [comment] 2021-06-03 10:59
Verification passed on OnePlus 6T with Android 10 running 1.26.50 x64 Beta build
- Verified clicking on share button prompts for requesting access to storage
--------------
Verification passed on Samsung Tab A with Android 10 running 1.26.50 x64 Beta build
- Verified clicking on share button prompts for requesting access to storage

OnePlus 6T | Samsung Tab A
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/120633279-df2be600-c461-11eb-82a0-eb4c547c51d1.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/120633188-c3c0db00-c461-11eb-92c0-c7408086066a.png>

Logged follow up issue #16221
