### ISSUE TITLE
Crash on Navigation/Search

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#1442] opened 2018-10-06 00:03 UTC
## Description 
Crash when attempting to navigate.

## Steps to Reproduce
1. Focus the omnibar
2. Navigate or perform a search

## Actual result:
Browser crashes.

## Expected result:
No crash.

## Reproduces how often: 
Not often, but several times a day.

## Brave version (chrome://version info)
Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Windows
JavaScript | V8 7.0.276.21
Flash | 31.0.0.108 C:\WINDOWS\system32\Macromed\Flash\pepflashplayer64_31_0_0_108.dll
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.35 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser-Beta\Application\brave.exe" --disable-chrome-google-url-tracking-client --disable-domain-reliability --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --enable-tab-audio-muting --no-pings --enable-tab-audio-muting --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor --flag-switches-begin --flag-switches-end

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes
- Does it reproduce on browser-laptop? No

### Additional Information
Crash ID `92129e0523cff77b`

**Comment by onmyouji** [comment] 2018-10-06 11:11
I’m also having the same issue. The browser crashes after searching a query in the address bar, I’m using Google as my search engine. It happens randomly, not sure how to reproduce it.

Windows 10 x64 Version 1709
Brave Version 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)

[4468e634-5b75-4f58-9e39-1a8415078df8.zip](https://github.com/brave/brave-browser/files/2452981/4468e634-5b75-4f58-9e39-1a8415078df8.zip)

**Comment by Draylar** [comment] 2018-10-07 23:19
Also getting this issue in the same versions listed above. I wanted to comment to say that the crash _also_ occurs while using search bars from popular sites such as Reddit and YouTube-- not just the Brave search bar. I've searched for a pattern in crashes, but it seems to be random-- I just triggered a single letter crash through YouTube's search bar, but failed to reproduce it with a minute of spamming search.

**Comment by jonathansampson** [comment] 2018-10-08 17:59
I've also experienced this while using the _Search_ option in the context menu.

**Comment by andrewcking** [comment] 2018-10-10 00:45
Also seeing what @Draylar is, crashing while searching even within a site (amazon youtube). Not sure how that could be the case but I have observed it quite frequently.

**Comment by Brave-Matt** [comment] 2018-10-10 22:12
Several reports of this on this Community thread:
https://community.brave.com/t/crash-while-navigating-to-search-results/34151/14
To save time I've pulled each crash report out here so you don't have to dig through the thread:
Crash report 1: https://gist.github.com/jiripospisil/587d4026636af213d7afe7a039869f54
Crash report 2: https://gist.github.com/jiripospisil/8713c1b249fba88c4c57de90d34117ae
Crash report 3: https://gist.github.com/jiripospisil/3078062a5876a1fd152b9fbe070ce2a5
Crash report 4: https://gist.github.com/jiripospisil/a77e4940e0b887300affc30ffd6a7be3

**Comment by capouch** [comment] 2018-10-11 07:54
This bug also affects 0.56.2.  I'm a fairly heavy user; 1-2 crashes per day.  Random times, but always after typing into the search bar--crash occurs upon hitting 'Enter.'

**Comment by Liunkae** [comment] 2018-10-12 18:29
I'm also experiencing this crash several times a day when searching.

Configuration: DuckDuckGo, Brave 0.56.2, macOS 10.14.

Uploaded Crash Report ID b8e9eabf32df4c1d (Local Crash ID: 13d63802-1132-4fd2-903b-f2ff775c0a55)

I'll also attach the crash log here: [Crash-1442-macOS.txt](https://github.com/brave/brave-browser/files/2474198/Crash-1442-macOS.txt)

**Comment by jonathansampson** [comment] 2018-10-13 03:06
I believe @simonhong is currently working on this.

**Comment by simonhong** [comment] 2018-10-13 04:34
@jonathansampson Oh, I didn't take this yet. Today I fixed similar area fix(omnibox UI) but not this one.

**Comment by jonathansampson** [comment] 2018-10-14 14:04
@simonhong Thanks. Any idea when you'll be able to take this? I hit this crash _at least_ a dozen times on a typical day.

**Comment by simonhong** [comment] 2018-10-15 02:57
I'm trying to reproduce on my local machine to get call stack.

**Comment by simonhong** [comment] 2018-10-15 10:28
Hmm, Today I tried to find reproduce step for some time. But, can't reproduce by myself.
Is there a pre-condition or some specific set of keywords causes this?

**Comment by onmyouji** [comment] 2018-10-15 18:53
@simonhong On my system, visiting this page (while not logged in to DropBox) consistently causes Brave to crash: 
https://www.dropbox.com/s/kdklrowv683yq1a/HashcatCheatSheet.v2018.1b%20(2).pdf?dl=0

Windows 10 Home x64 version 1709
Brave Version 0.55.13 Beta

**Comment by capouch** [comment] 2018-10-15 18:59
Navigating to that link works just fine for me.

Linux Slackware 14.2-current running as a VirtualBox VM, Brave 0.56.4.

**Comment by simonhong** [comment] 2018-10-16 00:45
I think this crash was fixed by https://github.com/brave/brave-core/pull/595/files.
I assume that this crash was happened after cloing private window.
I'll close this issue and feel free to re-open if you see again.

**Closed by simonhong** 2018-10-16 00:45 UTC
Labels: crash

**Comment by monaxle** [comment] 2019-03-21 16:48
Exactly this started to happen with my Brave install today. Every time today I type anything into the omnisearch bar and press enter Brave closes. Also closes when navigating to a site from saved bookmarks. Can't think of anything notable I may have done leading up to this. Auto upload of crash reports now enabled.  Should I open another issue or is this good to go here?

**Comment by AaronFaltesek** [comment] 2019-06-09 21:10
I'm having the same problem as @monaxle

**Comment by Alexowo** [comment] 2020-11-14 23:39
just having this problem at the moment. looks like it was never fixed?
