### ISSUE TITLE
[Android] issues with bottom toolbar on certain upgrades

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8778] opened 2020-03-20 13:29 UTC
## Description 
Bottom toolbar isn't quite right on certain upgrades.

## Steps to reproduce 

   1. Install tabs 1.5.9. Don't visit any sites.
   2. Close, remove from memory.
   3. Upgrade to 1.5.113 and launch
   4. Tap on tab tray
---> see weirdness (wrong bottom toolbar, additional tab tray icon in upper right corner)
   5. Visit a site, open tab tray
---> no change (still see weirdness)
   6. Close and relaunch
---> Now bottom toolbar is toggled off (toolbar displays at top)

## Actual result 
See the following on tab tray view:
1. tab count icon in upper right corner
2. bottom toolbar is wrong - it should only have `+` and 3 dots menu
![Screenshot_20200320-081057](https://user-images.githubusercontent.com/28145373/77167731-f7962780-6a8c-11ea-9a84-b005ed478c08.jpg)

## Expected result
(image is from 1.5.111 after performing same steps)
![Screenshot_20200320-082056](https://user-images.githubusercontent.com/28145373/77167755-01b82600-6a8d-11ea-8ef4-f50b7ac41c04.jpg)

## Issue reproduces how often 
easily with STR

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? yes

## Device details
   - Install type (ARM, x86): 
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.5.113

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information
happens with 1.5.113, maybe related to https://github.com/brave/brave-browser/issues/8713 and https://github.com/brave/brave-browser/issues/8768

cc @srirambv

**Comment by GeetaSarvadnya** [comment] 2020-03-20 18:02
Reproduce in Samsung Galaxy J3 version 5.1.1 running BraveModernarm 1.5.113

**Comment by GeetaSarvadnya** [comment] 2020-03-26 12:25
Enable Background video playback in 1.5.9 and then upgrade to 1.5.117 leads to the bottom toolbar toggled off (toolbar displays at the top) and the `Enable Background video playback` option becomes disabled in 1.5.177

**Comment by LaurenWags** [comment] 2020-03-26 12:48
seeing the same as @GeetaSarvadnya from https://github.com/brave/brave-browser/issues/8778#issuecomment-604400797 on my x86 (Android 6) device.

**Comment by srirambv** [comment] 2020-03-26 13:42
Issue doesn't reproduce on Samsung Tab A with Andriod 9.0 or OnePlus 6t with Android 10. Looks to be an issue with lower end devices

**Comment by GeetaSarvadnya** [comment] 2020-03-31 11:29
The issue still persists in `BraveModernarm 1.5.118.apk`

**Comment by LaurenWags** [comment] 2020-03-31 12:11
I'm actually seeing something different than @GeetaSarvadnya - after launching 1.5.118 my toolbar is no longer on the bottom, it is on the top.

**Comment by GeetaSarvadnya** [comment] 2020-03-31 12:49
This is reproducible when we upgrade from Android (1.5.9) to Android core build (1.5.118)
The issue isn't reproducible when we upgrade  from Android (1.5.7) to Android (1.5.9)

**Comment by GeetaSarvadnya** [comment] 2020-03-31 13:34
@LaurenWags @srirambv When I follow these steps from https://github.com/brave/brave-browser/issues/8778#issuecomment-604400797 in 1.5.118 - after upgrade browser opens up and relaunches again and bottom toolbar jumps at the top

**Comment by kjozwiak** [comment] 2020-04-06 22:00
Going to close this off after talking to @SergeyZhukovsky. `1.5.120` is at 100% on the release channel so most of the migrations have been completed. We did get some reports of users experiencing issues but we'll create new issues if those need to be addressed.

However, now that `1.5.120` is released and users are migrating, there's nothing we can do with this particular issue.

@GeetaSarvadnya @srirambv @LaurenWags if feel differently, please create a follow up issue 👍

**Closed by kjozwiak** 2020-04-06 22:00 UTC
Labels: OS/Android, QA/Yes, android-core-release, bug
