### ISSUE TITLE
Brave rewards shows chrome://rewards in URL bar

### ISSUE THREAD

**Issue by mhatvan** [brave/brave-browser#12760] opened 2020-11-18 12:16 UTC
## Steps to reproduce 

   1. Open Brave Rewarsd
   2. Check the displayed URL

## Actual result 

Shows `chrome://rewards` on Android

## Expected result
Should be `brave://rewards` like on Desktop

**Comment by srirambv** [comment] 2020-11-18 12:35
Will be fixed when https://github.com/brave/brave-browser/issues/9427 is done. Closing as dupe of https://github.com/brave/brave-browser/issues/9427

**Closed by srirambv** 2020-11-18 12:35 UTC
Labels: OS/Android
