### ISSUE TITLE
Add vertical tabs feature in Brave like it is present in Microsoft Edge

### ISSUE THREAD

**Issue by clicky6** [brave/brave-browser#17821] opened 2021-09-02 05:34 UTC
![image](https://user-images.githubusercontent.com/89839714/131787541-0dc24c5c-32c0-4259-9627-a47b1a444cf5.png)

![image](https://user-images.githubusercontent.com/89839714/131787566-8169dd19-d364-4ffe-a483-17daea446acd.png)

Add **vertical tabs** feature like in Microsoft Edge so that it increases productivity and we can find pages easily and browse easily without mess of all websites.

**Vertical Tabs** is much more better than Classic horizontal tab bar.

**Comment by bsclifton** [comment] 2021-09-02 06:15
Closing as duplicate of https://github.com/brave/brave-browser/issues/464

**Closed by bsclifton** 2021-09-02 06:15 UTC
Labels: OS/Desktop
