### ISSUE TITLE
New vertical tabs UI top bar is huge

### ISSUE THREAD

**Issue by Coffeeling** [brave/brave-browser#31191] opened 2023-06-21 12:48 UTC
The new vertical tabs UI polish that just landed on Nightly uses a lot of screen real estate:

![image](https://github.com/brave/brave-browser/assets/54371213/20fbf5fd-154b-47a2-9ddd-4164a1fb7d6b)

Given that one of the points of a vertical tab UI is to conserve vertical screen real estate, why is the new one, so to say, thicc?

The vertical tabs themselves are also bigger than the ones currently in Edge, let alone the original barebones implementation which was delightfully compact.

**Comment by Coffeeling** [comment] 2023-06-21 12:52
@rebron

**Comment by rebron** [comment] 2023-06-23 15:57
Closing as dupe of https://github.com/brave/brave-browser/issues/31218

Thanks for reporting @Coffeeling. The url bar height increase came with chromium 115. We're addressing it and going back to the proper/original height.

**Closed by rebron** 2023-06-23 15:57 UTC
Labels: OS/Desktop
