### ISSUE TITLE
Alignment issue when I open links from twitter

### ISSUE THREAD

**Issue by afroz1198** [brave/brave-browser#13746] opened 2021-01-25 08:57 UTC
![Screenshot_2021-01-25-14-19-52-54](https://user-images.githubusercontent.com/30230183/105682977-1b31c600-5f19-11eb-8434-9386dce0dce1.jpg)
**Note**: I noticed `powered by Brave`

**Comment by srirambv** [comment] 2021-01-25 09:33
Dupe of #9113

**Closed by srirambv** 2021-01-25 09:33 UTC
Labels: OS/Android
