### ISSUE TITLE
Multiple sites hang for 8+ seconds on every page load

### ISSUE THREAD

**Issue by cowwoc** [brave/brave-browser#22178] opened 2022-04-08 16:51 UTC
I've seen Brave "hang" when hitting certain websites. The only one that I can routinely reproduce the problem on is cibc.com. This is a very annoying problem when it occurs on the login page of a website. Every time I hit cibc.com I have to wait 8 seconds to type anything.

## Steps to Reproduce

   1. Disable SHIELDS UP for all of cibc.com
   2. Open https://www.cibc.com/en/personal-banking/mortgages/resource-centre/pay-your-mortgage-faster.html
   3. Try scrolling down the page using the keyboard arrows

## Actual result:

   4. You will be able to navigate for about 1 second, then the keyboard will stop working for about 8 seconds before coming back.
   5. Surprisingly, scrolling using the mouse works well. It is only the keyboard that stops responding.
 
Every time the keyboard hangs, I can hear my CPU fan spin up and the Brave process seems to use 100% of a single CPU core.

## Expected result:

3. CPU usage should not peak. Keyboard should remain responsive.

## Reproduces how often: 

100% reproducible.

## Desktop Brave version: 
1.37.111 Chromium: 100.0.4896.79 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Didn't check.
- Can you reproduce this issue with the nightly channel? Didn't check.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by cowwoc** [comment] 2022-04-09 13:50
Actually, the mouse hangs too. Scrolling using the mouse works but any other sort of interaction (e.g. right-click on page) hangs as long as the keyboard does. So it's essentially impossible to interact with the webpage while the browser is frozen.

**Comment by cowwoc** [comment] 2022-11-06 02:40
This issue is getting worse. Now I am beginning to get a "page is not responding" error on top of the hang I have been seeing for the past year.

Can someone please investigate this issue?

**Comment by cowwoc** [comment] 2022-11-06 02:53
Per the profiler, 99.5% of the time seems to be spent in `getChannelData`.

**Comment by fde31** [comment] 2022-11-09 20:20
came across this issue when investigating performance issues related to `AudioBuffer.getChannelData`. Potentially related to #26507

**Comment by cowwoc** [comment] 2022-11-21 17:35
@pilgrim-brave The situation is much improved in the version 1.47.91 nightly build (thanks to https://github.com/brave/brave-core/pull/15894) but is still present. The hang is around 1-2 seconds long now.

**Comment by cowwoc** [comment] 2022-11-21 17:42
I stand corrected. The hang is still 8+ seconds long. Here is a clarification:

1. If you hit the site with SHIELDS UP the hang is ~2 seconds long.
2. If you disable shields, then the hang increases to ~8 seconds long.

So unfortunately, @pilgrim-brave's change did not fix anything here.

**Comment by bradsk88** [comment] 2022-11-26 22:26
Some other places I'm seeing this:
- [Mint Login Page](https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown)
- [Ebay Login Page](https://signin.ebay.ca/ws/eBayISAPI.dll?SignIn&ru=https%3A%2F%2Fwww.ebay.ca%2Fmys%2Fhome%3Fsource%3DGBH)

All are only affected when shields are down.

**Comment by kylethielk** [comment] 2022-11-28 16:08
I'm also seeing this consistently across many different sites. Consistently happens on https://app.gusto.com/login for me as an example. 

Even in Private Mode with no extensions enabled. Happens with shields up or down. Similar to #26507, the hangup seems to always be in `getChannelData`. 

![Screen Shot 2022-11-28 at 10 08 10 AM](https://user-images.githubusercontent.com/3186142/204325683-e0677830-e009-44f0-a05e-d711b7926d69.png)

**Comment by iefremov** [comment] 2022-12-07 18:28
this is a dupe of https://github.com/brave/brave-browser/issues/26562. The fix is about to roll out in all channels

**Closed by iefremov** 2022-12-07 18:28 UTC
Labels: OS/Android, OS/Desktop

**Comment by iefremov** [comment] 2022-12-07 18:29
Thanks for reporting @cowwoc . Sorry for missing this report - the problem could've been resolved much earlier if we noticed.
