### ISSUE TITLE
Disable 'popular website' url suggestions

### ISSUE THREAD

**Issue by MareinK** [brave/brave-browser#9477] opened 2020-04-26 23:37 UTC
When typing in the url/search bar, matching url suggestions for popular websites are shown, regardless of the user having visited these sites or not. For example, when typing 'git', the suggestions include 'github.com'. I would appreciate it if there was an option to disable these so that the suggestions are less cluttered.

**Comment by rebron** [comment] 2020-05-07 00:08
Duplicate of #9572 and fixed in 1.10.29 and higher with https://github.com/brave/brave-core/pull/5438
Toggle `Show top sites in autocomplete suggestions`

**Closed by rebron** 2020-05-07 00:08 UTC
