### ISSUE TITLE
Linking with Uphold is broken when sent into e-mail verification flow

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#16269] opened 2021-06-07 17:42 UTC
## Description

When faced with Uphold email verification step ("approve this sign in attempt"), OAuth/verification/linking does not occur.

1. Be in wallet Disconnected state **(edit: @kjozwiak says this is reproducible from a fresh profile/unverified state as well, which makes this more urgent)**
2. Press the "Disconnected" button in the Rewards panel in order to OAuth/verify again with Uphold
3. Get sent to Uphold login page
4. Enter username/password
5. Get sent to "e-mail verification" page, where Uphold sends e-mail to verify the sign in attempt
6. Open e-mail and confirm the sign in attempt 
7. Get sent to Uphold dashboard, but (re)verification is not completed (still in Disconnected state) — there is no redirect back to brave://rewards settings page

Note: It seems like when logging in through this flow, the login isn't actually sticky (no cookie?). So, doing the flow again will ask you to log in again, even though you just did.

### Workaround for support

Here is a workaround in case a user experiences the above:

1. Go to Uphold.com and log in independently of the Brave Rewards verification flow
2. Once logged in, go into Brave Rewards and verify wallet
3. Follow steps
4. Wallet verification should be successful (in "Wallet verified" state) 

cc: @brave/rewards-support

**Comment by kjozwiak** [comment] 2021-06-08 04:45
@Miyayes I actually ran into this a few times today when I nuked my entire profile on Nightly and started a fresh profile due to accidentally launching my previous profile using staging flags which screwed things up and I stopped getting ads. I couldn't get past the "verification" email step after a few attempts and needed to login into Uphold separately before I could login/link the wallet via `brave://rewards`.

We should get this fixed sooner than later IMO. I would say this is either a `P2` or `P3`. @Miyayes possible to get this fixed in `1.26.x` in terms of getting dev resources on this? CCing @LaurenWags

**Comment by emerick** [comment] 2021-06-09 16:13
@szilardszaloki mentioned that this might be related to a string type mismatch that he had noticed.

**Comment by emerick** [comment] 2021-06-09 16:19
From @jumde:

> I took a quick look at this issue yesterday, it looks like uphold is not handling the redirect correctly. Their verification link - `https://sandbox.uphold.com/login?token=<code>` opens the dashboard instead of navigating to the link that triggered this check. Their emails should ideally have a verification link of the form `https://sandbox.uphold.com/login?token=<code>&redirect_url=<last_link>`

**Comment by szilardszaloki** [comment] 2021-06-09 16:40
Yeah, think I know where this comes from.
I built a debug Brave and reproduced this issue a while ago.
We have a failing `DCHECK` [here](https://github.com/brave/brave-core/blob/29126467dc01d4dfad64e411c94026dccf0f500d/browser/brave_ads/ads_tab_helper.cc#L104).
I took a couple of screenshots of the stack trace and the affected code and sent them to @tmancey. Not sure if he had a chance to look into it.
Disabling ads resolves the issue.

**Comment by Miyayes** [comment] 2021-06-09 19:21
+1 https://www.reddit.com/r/brave_browser/comments/nvtdoq/brave_and_uphold_reconnect/

**Comment by Brave-Matt** [comment] 2021-06-14 17:53
+1s from Community:
https://community.brave.com/t/verifying-android-wallet-steps-dont-done/258947/3

**Comment by szilardszaloki** [comment] 2021-06-15 07:48
To be resolved by @tmancey's https://github.com/brave/brave-core/pull/9123.

**Comment by tmancey** [comment] 2021-06-15 13:54
Resolved by https://github.com/brave/brave-browser/issues/16410

**Closed by tmancey** 2021-06-15 13:54 UTC
Labels: OS/Android, OS/Desktop, QA/Yes, feature/rewards, priority/P2

**Comment by kjozwiak** [comment] 2021-07-20 20:18
Going to label this as `QA/No` as the email verification loop was addressed by Uphold a few days ago. Both @szilardszaloki and myself confirmed that it's working but there's still some issues regarding needing to run through the process twice to successfully link your wallet with uphold.

We'll use https://github.com/brave/brave-browser/issues/16879 to track the progress of the issue and the fixes that Uphold pushes.
