### ISSUE TITLE
CAPTCHA being shown all the time in Brave

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#12359] opened 2020-10-28 14:57 UTC
## Test plan
See https://github.com/brave/brave-core/pull/6993

## Original issue description
Have you searched for similar issues? Yes. #1677 is the closest thing I found but I think that as specific to tor and sightly different.

 
## Description 
I'm finding too many captch notifications on freelancing sites such as Fiverr and Upwork either when opening multiple tabs of the same site at once or after opening new tabs of the same site after a while on the same site.
It can be a problem if you've right-click and open links on the site to view later and you don't even realise that the captch has been created and even if you comply with captcha and finish it, it shows that you've completed it with a green tick, however, the site become permanently stuck and you've lost the page that you were on refreshing the page doesn't help as you don't even know what that specific tab was and we should even have to refresh. Brave is supposed to reduce the amount of time and save time but quite often it doesn't. I've noticed more and more that I'm wasting time with Brave just trying to get sites to work or refreshing sites or fixing tab issues and we should have to.

Furthermore, turning Shields off and on doesn't help after the fact. Sites simply become stuck with Shields on or off.

## Steps to Reproduce
I don't know exactly how to reproduce it as it occurs randomly but a lot of the times when I have around a dozen or more tabs of the same site open either at once or randomly.

## Actual result:
![Screenshot_20201010_200530](https://user-images.githubusercontent.com/31957540/97451953-28e0ab00-192c-11eb-9129-074f95cc81c5.png)

![Screenshot_20201027_174556 2](https://user-images.githubusercontent.com/31957540/97452021-37c75d80-192c-11eb-83e2-823f9e3edfb5.png)

![Screenshot_20201027_154223](https://user-images.githubusercontent.com/31957540/97452032-3ac24e00-192c-11eb-89ba-87ecfa99dec9.png)

## Expected result:
I'll let you figure it out )

## Reproduces how often: 
At least once every time I'm on the site and that's not to say just on one tab but in every tab that I have opened of that site, so it completely disrupts the workflow.

## Brave version (brave://version info)
Version 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit) (openSuse)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? I didn't try.
- Is the issue reproducible on the latest version of Chrome? This is most likely a Brave specific issue.

**Comment by NumDeP** [comment] 2020-10-28 18:09
I may have said this before but the stat on Brave's dashboard which shows the number of hours saved is simply untrue if you factor in the amount of time a user wastes with issues similar to this.

I know I have no right to tell you what to do but this issue has been such an annoyance for so long I'd greatly appreciate if the team figured out a way to fix issues like this without us users having to do anything on our side, otherwise we'd be just wasting more time and disrupt important workflow.

Thanks )

**Comment by bsclifton** [comment] 2020-10-28 20:32
Thanks for reporting - we have been looking into this and have attempted some fixes, no luck yet

Previously reported with https://github.com/brave/brave-browser/issues/12289

**Comment by bsclifton** [comment] 2020-11-02 16:53
Fixed in master (1.18.x) with https://github.com/brave/brave-core/pull/6554 and fixed in 1.16 with https://github.com/brave/brave-core/pull/6993. 1.17.x will get the fix when Chromium 87 is uplifted

**Closed by bsclifton** 2020-11-02 16:53 UTC
Labels: OS/Android, OS/Desktop, QA/Yes, priority/P1, release-notes/include

**Comment by kjozwiak** [comment] 2020-11-03 03:29
@jonathansampson @pes10k @bsclifton and a few others have confirmed that the above change which was included in `1.16.71 CR: 86.0.4240.111` have improved things 👍

**Comment by kjozwiak** [comment] 2020-11-03 03:34
Verification **PASSED** on `macOS 10.15.7 x64` using the following build:

```
Brave | 1.16.71 Chromium: 86.0.4240.111 (Official Build) (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.15.7 (Build 19H2)
```

* ensured that logging into https://www.bell.ca, https://www.rogers.com & https://www.paypal.com didn't produce/display a reCAPTCHA

Tried running through https://levalet.com/en/customer/account/login/ as per the STR/Case outlined via https://github.com/brave/brave-core/pull/6993#issue-512847061 but kept running into the following error:

```
You cannot proceed with such operation, your reCaptcha reputation is too low.
```

However, Chrome seems to be running onto the same issue so considering the above as a pass as the other websites worked plus several confirmations as per https://github.com/brave/brave-browser/issues/12359#issuecomment-720594323.

@LaurenWags once you've checked on `Mojave`, you can label as `QA/Pass`. @fmarier let me know if you disagree with the above.

**Comment by hornetnz** [comment] 2020-12-11 13:41
This exact issue seems to have come back within the last few days. Can anyone else confirm?
Version 1.17.73 Chromium: 87.0.4280.67 (Official Build) (x86_64)
