### ISSUE TITLE
Brave Ads intermittently crashes when opening a new tab

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#9393] opened 2020-04-22 16:04 UTC
[ 00 ] Browser::Browser
[ 01 ] brave_ads::AdsServiceImpl::OnViewAdNotification
[ 02 ] bat_ads::mojom::BatAds_GetAdNotification_ForwardToCallback::Accept
[ 03 ] mojo::InterfaceEndpointClient::HandleValidatedMessage
[ 04 ] mojo::internal::MultiplexRouter::ProcessIncomingMessage
[ 05 ] mojo::internal::MultiplexRouter::ProcessTasks
[ 06 ] mojo::internal::MultiplexRouter::LockAndCallProcessTasks
[ 07 ] base::TaskAnnotator::RunTask
[ 08 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl
[ 09 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork
[ 10 ] base::MessagePumpGlib::Run
[ 11 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run
[ 12 ] base::RunLoop::Run
[ 13 ] ChromeBrowserMainParts::MainMessageLoopRun
[ 14 ] content::BrowserMainLoop::RunMainMessageLoopParts
[ 15 ] content::BrowserMainRunnerImpl::Run
[ 16 ] content::BrowserMain
[ 17 ] content::ContentMainRunnerImpl::Run
[ 18 ] service_manager::Main
[ 19 ] content::ContentMain
[ 20 ] ChromeMain

https://brave.sp.backtrace.io/p/brave/triage?filters=((callstack%2Cregex%2C%22(BatAds%7CAdsService%7CAdsImpl%7CConfirmationsImpl)%22))&aggregations=((ver%2Cdistribution)%2C(guid%2Cunique)%2C(classifiers%2Chead))&fingerprint=0000000000000000000000000000000000000000000000000000000000000094

**Comment by tmancey** [comment] 2020-04-22 16:11
2 crashes have occured

**Comment by Durss** [comment] 2020-05-28 18:15
Seems like a duplicate of issue #8476
I still get between 2 to 5-6 crashes a day when a new tab opens.

**Comment by tmancey** [comment] 2020-05-29 07:12
@Durss Are the crashes you are experiencing when click on Brave Ad notifications to view the ad, or just general browsing please?

**Comment by Durss** [comment] 2020-05-29 09:02
Woops my bad i missread and didn't see it was related to ads. You can ignore my comment then sorry :)

**Closed** 2020-08-03 07:15 UTC
Labels: QA/Yes, bug, crash, feature/ads, priority/P1, release-notes/include

**Comment by LaurenWags** [comment] 2020-08-07 17:07
Verified passed with

```
Brave | 1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/6304#issuecomment-669748784 
* Ran thru the above ~10x, confirmed no crashes observed on brave://crashes

------------

**Comment by srirambv** [comment] 2020-08-11 14:08
Verification passed on OnePlus 6T with Android 10 running 1.12.111 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/6304#issuecomment-669748784
