### ISSUE TITLE
Wrong message for sites with expired certificates

### ISSUE THREAD

**Issue by levicki** [brave/brave-browser#17130] opened 2021-07-23 12:29 UTC
## Description 

When visiting a website that has a certificate which has recently expired the wrong message is displayed to the user, suggesting that their computer clock is wrong and offering a button to adjust it while not allowing the site to be visited anyway.

**Brave message**
![image](https://user-images.githubusercontent.com/16415478/126779562-424524ab-abe4-4367-9b97-fd8b0d5ddf1c.png)

**Website certificate**
![image](https://user-images.githubusercontent.com/16415478/126779584-d09730fb-fc52-43ee-a7ba-a5edb3a99e2c.png)

**Website certificate details**
![image](https://user-images.githubusercontent.com/16415478/126779770-030d1803-3ef2-4fd8-9554-d829890f8348.png)

My clock is synchronized to my domain controller which in turn is synchronized to relevant NTP servers so clock being incorrectly set is virtually impossible.

## Steps to Reproduce

1. Visit regex101.com right now.

Alternatively (when regex101.com certificate is renewed):

1. Bring up a blank website utilizing a certifcate with short validity and wait for it to expire
2. Visit the website

## Actual result:

You get the wrong system clock warning.

## Expected result:

You get a certificate expired warning, and you should be allowed to override.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.26.77 Chromium: 91.0.4472.164 (Official Build) (64-bit)
541163496c9982c98f61819bab7cf2183ea8180f-refs/branch-heads/4472@{#1569}
Windows 10 OS Version 2009 (Build 19043.1110)

When we are at that, Windows version is misdetected as well.

It is 21H1, not 2009 -- there is no such version as 2009, after 2004 there is only 20H2 and 21H1.

**Windows Version**
![image](https://user-images.githubusercontent.com/16415478/126781191-3985a356-3366-43af-a0c0-4c4d28dd9197.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Did not try
- Can you reproduce this issue with the nightly channel? Did not try

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Did not try (but probably yes)

## Miscellaneous Information:

N/A

**Comment by Tonev** [comment] 2021-07-23 15:44
Duplicate of https://github.com/brave/brave-browser/issues/16137.

**Comment by diracdeltas** [comment] 2021-07-23 20:17
closing as duplicate, should be fixed soon

**Closed by diracdeltas** 2021-07-23 20:17 UTC
Labels: OS/Desktop, closed/duplicate
