### ISSUE TITLE
No way to turn off Brave Shields on localhost

### ISSUE THREAD

**Issue by SilencerWeb** [brave/brave-browser#2321] opened 2018-12-02 06:01 UTC
There is no way to turn off Brave Shields on localhost (any port)

Brave version: 0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit)

**Comment by tomlowenthal** [comment] 2018-12-03 19:56
Sounds like a duplicate of #1896.

**Closed by tomlowenthal** 2018-12-03 19:56 UTC
