### ISSUE TITLE
Grant notification shows up too often (follow up to #1798)

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2454] opened 2018-12-11 15:30 UTC
## Description 

Follow up to https://github.com/brave/brave-browser/issues/1798. Grant notfication shows up every single time the BR panel button is clicked. This is annoying even while testing. There should be a time out before the notification is shown next.

## Steps to Reproduce

   1. Install 0.58.11 and enable rewards
   2. Click on BR panel in URL bar, grant notification is shown
   3. Dismiss notification by clicking ok button and close the panel
   4. Click the BR panel again
   5. And then 
       ![img](http://p.fod4.com/p/media/39f78a7bf9/7z6PPXkSQTWdHxJSPA57_c12.gif)

## Actual result:

https://youtu.be/UYDJNt4FPso

## Expected result:
Should not show every time the panel is opened

## Reproduces how often: 

Easy 

## Brave version (brave://version info)

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @NejcZdovc @brave/legacy_qa

**Comment by LaurenWags** [comment] 2018-12-11 15:39
Reproduces on macOS

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

**Comment by kjozwiak** [comment] 2018-12-11 20:36
Reproducible on Win 10 x64 as well. Affecting all platforms.


Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
--- | ---
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows

**Comment by kjozwiak** [comment] 2018-12-12 16:23
Moving to `0.58.x` after a quick discussion with @davidtemkin and @NejcZdovc. This might end up annoying folks. The general rule that we take with notifications is that users should only be seeing it once and shouldn't be prompted the same notification over and over.

**Comment by kjozwiak** [comment] 2018-12-12 17:33
![notification](https://user-images.githubusercontent.com/2602313/49887359-1cbbd500-fe0a-11e8-9fa9-f5f45d30a8c6.gif)

**Comment by mandar-brave** [comment] 2018-12-12 19:50
@NejcZdovc moving it to P2 based on user feedback and above conversation.
cc @davidtemkin @rebron

**Comment by NejcZdovc** [comment] 2018-12-12 20:47
@mandar-brave it's already set to daily. There is just an additional check on the panel. So the easiest thing to do is just remove check from the panel and that is it

**Comment by davidtemkin** [comment] 2018-12-12 23:42
@NejcZdovc logic should be that user is notified once per grant; red dot only appears once for that grant. 

However, the check still needs to be there, right? we do want to show the notification if a previously unseen grant is available when user clicks (i.e., the browser hasn't done the daily check since the new grant went live). But only once for one grant, never bring back notification for the same grant.

**Closed** 2018-12-20 19:51 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/rewards, priority/P2, release-notes/exclude

**Comment by GeetaSarvadnya** [comment] 2018-12-24 17:30
Verification passed on


Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Windows
