### ISSUE TITLE
Feature request: Multi-Account Containers like Firefox's one

### ISSUE THREAD

**Issue by RoiArthurB** [brave/brave-browser#6346] opened 2019-10-08 03:27 UTC
Hello, 

# Request

I really love the idea of the Brave Browser, the new financial offer, and everything. But I'm a Firefox user and I'm concerned about privacy and what blocks me to Brave is the multi-account container plugin ( https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/ )...

My usage of it is to create a unique container for GAFAM's services and has a unique profile (cookies, etc) for them where I can use all services in the same container. For example, I have a Facebook container where I'm using Messenger, Instagram & Facebook and outside this container pages can't see my Facebook cookies/login!

# Elements of solution

So, thanks to chromium native sandboxing ( https://chromium.googlesource.com/chromium/src/+/lkgr/docs/design/sandbox_faq.md ) I think a similar option could be implemented in Brave.

# Actual workaround

I know that I can use chromium profiles and isolate my browsing that way. But it's too hard to use (I want my container on the same window because I'm running 20 of them, I don't want 20 Brave windows on my computer... I'll be lost too quickly on them !) and I'm afraid plugins will relaunch themselves (which could quickly be RAM and CPU expensive).

**Comment by bsclifton** [comment] 2019-10-08 23:40
related https://github.com/brave/brave-browser/issues/1053

**Comment by RoiArthurB** [comment] 2019-10-09 01:34
@bsclifton you've right, do you know where the development of this feature is? Is it in the exp version of Brave ?

**Comment by NumDeP** [comment] 2019-12-20 18:54
Hi @bsclifton I don't wish for this to be closed as Arthur's points need to be taken on board but how different would this be to [Session WIndows/Tabs #34](#34)?

Surely this would be just an enhancement on top of it.

**Comment by bsclifton** [comment] 2019-12-30 19:38
Good point, @NumDeP - this could be similar to Session Windows/Tabs. But to @RoiArthurB 's point, that issue is scoped to only have Session Windows... meaning you'd have to have one window per unique session (and 20 windows already known to be undesirable)

**Comment by bsclifton** [comment] 2019-12-30 19:39
@riastradh-brave is this a dupe of https://github.com/brave/brave-browser/issues/1053?

In either case, can you provide an update in https://github.com/brave/brave-browser/issues/1053? Thanks 😄

**Comment by RoiArthurB** [comment] 2019-12-31 10:19
Hi all !

>  but how different would this be to Session WIndows/Tabs #34?

@NumDeP you link this exact issue... So yes it's similar on the way that it's the same web page/issue ^^"

> that issue is scoped to only have Session Windows

Actually my point is to have different sessions within tabs (as Multi-Account Containers does in Firefox)

>  is this a dupe of #1053?

I think it is. Or at least it's very closely link !

**Comment by MicrosoftTakeover** [comment] 2020-02-15 22:52
https://github.com/brave/brave-browser/issues/34

**Comment by bsclifton** [comment] 2020-02-17 06:36
Thanks all- will close this as a dupe of https://github.com/brave/brave-browser/issues/34 (session windows)

**Closed by bsclifton** 2020-02-17 06:36 UTC
Labels: closed/duplicate, suggestion, feature-request

**Comment by robinhood018** [comment] 2022-01-28 07:08
Any news on this?

**Comment by marbv1** [comment] 2023-06-23 18:22
I'm switching from Firefox to Brave, due to the webapp that the company where I work seems to work better on chromium based browsers, and I'm trying to adapt my workflow to meet the privacy level that I used to have with Firefox Multi-Account Containers.

My first thought was that using different profiles to access different websites would solve this, but in practice it's not that simple...
Suppose I receive a link via e-mail (outlook) to a document that is on my company webapp. If I simple click on it, it will open a new tab on my default profile on Brave, instead of opening it on the profile that I use just for work...
Or if I'm on a news website, and click on, lets say, an Instagram link, it will just open another tab on the current profile, instead of opening it on the profile that I use just for Meta websites, as posted by @RoiArthurB...

I think Firefox Multi-Account Containers is superior in this way, once you can assign websites to always open on specific containers...

Is there any workaround for this on Brave that I'm not aware?

**Comment by FetchFast** [comment] 2024-02-26 03:19
Perhaps we could simply allow opening a new Window with different profiles more easily? 
The drawback for profiles is that the extensions need to be mirrored to each profile. It's a lot less convienient than Firefox. Brave users are interested in privacy and security. This feature would be a very useful aspect to that. I'm using Firefox more as a result. It reduces tracking.

**Comment by gliptak** [comment] 2024-02-26 16:00
also with profiles, credentials might need to be duplicated

**Comment by Adamantt777** [comment] 2024-09-07 05:06
Yes, the Brave Multi-Account Containers extension is a very needed feature. I hope it gets created soon. Big thanks to anyone who can create it in the future.
