### ISSUE TITLE
Tipping banner does not scale properly based on viewport size 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#2867] opened 2019-01-09 06:30 UTC
**Issue:** Tipping banner does not scale properly based on viewport size. If viewport size is smaller than usual because of, e.g., docked dev tools, the tipping banner will appear shorter horizontally, and users will have to scroll side to side inside it to use it.

Even when the developer tools are later closed, the tipping banner does _not_ scale back to proper size, but remains horizontally short.

_UX symptom:_ Users cannot click outside the banner to close it, but instead need to press the X button. But the X button is outside view, so users have to know to scroll sideways to get to it.

**Reproduce:** 

1. Open a website you'd like to tip
2. Open dev tools (docked on right side)
3. Open tipping banner

![image](https://user-images.githubusercontent.com/11497541/50880608-921ec380-1411-11e9-81ab-cf42cc9d40c9.png)

**Comment by NejcZdovc** [comment] 2020-04-10 12:59
closing as dupe of https://github.com/brave/brave-browser/issues/1658

**Closed by NejcZdovc** 2020-04-10 12:59 UTC
Labels: feature/rewards, priority/P5
