### ISSUE TITLE
"Incognito tab" in settings instead of "private tab"

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#15951] opened 2021-05-18 20:39 UTC
## Description 
![screenshot_20210518-132221](https://user-images.githubusercontent.com/167821/118719210-09807100-b7dd-11eb-9ecd-b32c27a05096.png)

## Steps to reproduce 

   1. Open settings.
   2. Look under *Search engine*.

## Issue reproduces how often 
Always

## Brave version

Beta 1.25.60 (90.0.4430.212)

**Comment by srirambv** [comment] 2021-05-19 06:45
Dupe of #10105

**Closed by srirambv** 2021-05-19 06:45 UTC
Labels: OS/Android
