### ISSUE TITLE
Rewards Panel always shows 0% attention on twitch

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3409] opened 2019-02-19 00:20 UTC
Follow up from https://github.com/brave/brave-browser/issues/3329

## Steps to Reproduce

1. Clean profile.
2. Launch Brave and enable rewards.
3. Visit some twitch stream so you have some attention % values in auto contribute table.
4. Show Rewards Panel

Note twitch sites tested:
https://www.twitch.tv/neoness007
https://www.twitch.tv/redpwnie
https://www.twitch.tv/videos/344762635

## Actual result:

Rewards Panel show 0%, attention even though a-c table shows >0%
![image](https://user-images.githubusercontent.com/34715963/52982112-6c0f1a80-33e4-11e9-8d4a-d285886fae33.png)
![image](https://user-images.githubusercontent.com/34715963/52982123-7d582700-33e4-11e9-9d5a-141b4a13a8ef.png)

## Expected result:
Rewards Panel shows the same value as a-c table

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.60.40 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows 7

@brave/legacy_qa @NejcZdovc

**Comment by btlechowski** [comment] 2019-02-19 00:22
Verification passed on 

Brave | 0.60.40 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows 7

Verified STR from the description.
![image](https://user-images.githubusercontent.com/34715963/52982163-cf00b180-33e4-11e9-8288-99359689fa26.png)
![image](https://user-images.githubusercontent.com/34715963/52982178-d922b000-33e4-11e9-82bb-7b7de55fd554.png)

Logged https://github.com/brave/brave-browser/issues/3409

**Comment by LaurenWags** [comment] 2019-02-20 13:55
Reproduced on macOS

Brave | 0.60.44 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Mac OS X

![screen shot 2019-02-20 at 8 54 55 am](https://user-images.githubusercontent.com/28145373/53096461-399d1480-34ed-11e9-8e06-0b8c019c3ea7.png)
![screen shot 2019-02-20 at 8 54 46 am](https://user-images.githubusercontent.com/28145373/53096464-3b66d800-34ed-11e9-8336-dea087f275db.png)

**Comment by NejcZdovc** [comment] 2019-03-07 09:14
fixed with https://github.com/brave/brave-browser/issues/3497

**Comment by btlechowski** [comment] 2019-03-20 16:44
I am still able to easily reproduce the issue.

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

Only difference is that sometimes, the correct Attention is shown, but if I close the Panel and open it again 0 attention is shown.

![image](https://user-images.githubusercontent.com/34715963/54702683-a381fb80-4b37-11e9-90eb-d26a8bf89dea.png)

@NejcZdovc would you like me to report another issue or reopen this one?

**Comment by NejcZdovc** [comment] 2019-03-20 16:46
@btlechowski so you can't reproduce it like old times, but new STR is to close and open panel again?

**Comment by btlechowski** [comment] 2019-03-20 16:59
@NejcZdovc I can reproduce with the STR from the description, but sometimes when I keep the Panel opened I get a proper attention value. Closing the Panel and Opening it again shows again 0 attention value.

**Comment by NejcZdovc** [comment] 2019-03-20 17:01
@btlechowski pls create new issue with this close/open STR, will check other STR as well

**Comment by GeetaSarvadnya** [comment] 2019-03-20 17:29
The issue is still Reproducible on 

Brave | 0.63.15 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

The Panel shows Attention % rate Zero. But, A-C table has Attention greater than Zero

Panel:
![image](https://user-images.githubusercontent.com/38657976/54705843-ae528580-4b63-11e9-93b0-77c2cd90e49e.png)

A-C table:

![image](https://user-images.githubusercontent.com/38657976/54705879-bf02fb80-4b63-11e9-826b-c4c54e4d18ba.png)

**Comment by Miyayes** [comment] 2021-12-29 16:01
@btlechowski Is this still an issue with the new Rewards panel?

**Comment by btlechowski** [comment] 2022-01-26 23:49
I was able to reproduce on clean profile, but after restart the Attention is changed after watching a stream. This could be related to https://github.com/brave/brave-browser/issues/13391.

Brave | 1.35.92 Chromium: 97.0.4692.99 (Official Build) beta (64-bit)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}}
OS | Ubuntu 18.04 LTS

Clean profile:
![image](https://user-images.githubusercontent.com/34715963/151265828-0a4f2bb4-14e1-482f-914d-5a31524e07cf.png)

After restart:
![image](https://user-images.githubusercontent.com/34715963/151265508-ad66ad79-f160-4630-924c-5ae164095558.png)

**Comment by szilardszaloki** [comment] 2022-02-10 15:18
The following use case is steadily reproducible:
1. new profile
2. enable `Rewards`
3. visit a Twitch page (e.g. https://www.twitch.tv/redpwnie) `==>` only `twitchBase.ts` is loaded (`twitchAutoContribution.ts` is not `==>` we can't populate `Attention`)
4. restart browser `==>` neither `twitchBase.ts`, nor `twitchAutoContribution.ts` is loaded (because of a [known issue](https://github.com/brave/brave-browser/issues/11825))
5. refresh page `==>` both `twitchBase.ts` and `twitchAutoContribution.ts` are loaded (`==>` populating `Attention` works fine)

In `3.` the precondition of `twitchAutoContribution.ts` (`"auto-contribution-enabled": true`) is not fulfilled, because `Greaselion.json` gets parsed earlier than `Rewards` gets enabled (at browser startup).

**Closed** 2022-02-10 16:59 UTC
Labels: feature/rewards, priority/P3, QA/Yes, QA/Test-Plan-Specified, closed/not-actionable, greaselion
