### ISSUE TITLE
Invisible block of unresponsive space when browser window is Full Screened

### ISSUE THREAD

**Issue by bean-z** [brave/brave-browser#33646] opened 2023-10-16 04:55 UTC
## Description 

This is a MacOS issue. When I full screen my browser window, an region of the browser window becomes unresponsive as if there were an invisible rectangular block on top. It shows up after I've used the browser for a while and switches positions in a way I can't predict.

Buttons in the region don't light up when the mouse hovers over them. The mouse cursor doesn't change to the text cursor symbol when I hover over an affected text box, which sometimes includes part of the address bar.

## Steps to Reproduce

   1. Open the browser.
   2. Full screen the browser window.
   3. Do whatever you would normally do. For a few hours? A day?
   4. Repeatedly click the address bar and other spots. If nothing happens, repeat 3 and 4.

## Actual result:

Trying to click the address bar, which was obstructed by the invisible block:

https://github.com/brave/brave-browser/assets/143631489/317a7bab-faef-4adc-94ef-496670a48d9e

Trying to hover over the Close Window button and then click the Exit Full Screen button, which somehow were obstructed:

https://github.com/brave/brave-browser/assets/143631489/3119aae4-29ff-461c-b67d-bf17e456e32b

In this video captured a few minutes after the above two videos, the invisible block was in a different place, below the address bar:

https://github.com/brave/brave-browser/assets/143631489/8262d092-b4c3-449d-b605-29bd38373f9b

I couldn't turn off Brave Shields because the invisible block was in the way of the toggle.

https://github.com/brave/brave-browser/assets/143631489/f73362e4-edad-4b8f-9be2-fa3589e9680d

## Expected result:
The browser window detects mouse movements and clicks properly.

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)

Brave | 1.59.117 Chromium: 118.0.5993.70 (Official Build) (x86_64)
-- | --
Revision | 766577bee8f040990afcb32677dcab38ffcf0f06
OS | macOS Version 13.6 (Build 22G120)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Haven't tried
- Can you reproduce this issue with the nightly channel? Haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Haven't tried

## Miscellaneous Information:

When the browser window is not in Full Screen, everything works as expected. When I Full Screen the window again, the invisible block appears again.

**Comment by Geppe98** [comment] 2023-10-16 08:17
I have the same exact issue

**Comment by eaufavor** [comment] 2023-10-16 16:03
Same 1.59.117  arm64

**Comment by eaufavor** [comment] 2023-10-16 21:59
I followed https://github.com/brave/brave-browser/issues/33657 to disable memory saver. That assumes to fix the apparently issue for me.

**Comment by bean-z** [comment] 2023-10-17 02:06
I already had Memory Saver deactivated. I had Energy Saver on. Deactivating both doesn't get rid of the obstruction for me.

**Comment by bigpurpletoast** [comment] 2023-10-18 08:09
> I already had Memory Saver deactivated. I had Energy Saver on. Deactivating both doesn't get rid of the obstruction for me.

I've done the same and even tried turning off hardware acceleration and I also still encounter this issue, the invisible block is mostly near the tabs for me.

**Comment by bigpurpletoast** [comment] 2023-10-18 09:12
Okay so I just enabled the flag "GPU rasterization" and I believe the bug is gone now.

**Comment by bigpurpletoast** [comment] 2023-10-18 10:35
Nevermind the bug came back. :[

The thing is that Brave works properly for a couple of minutes after you open it but then this invisible block systematically comes back. Argh it's so frustrating. :(

**Comment by bordeux** [comment] 2023-10-18 14:24
Aha! Uff, im not alone with it. It appears also randomly, during normal browsing.

**Comment by bigpurpletoast** [comment] 2023-10-18 14:45
> Aha! Uff, im not alone with it. It appears also randomly, during normal browsing. Mac 14 pro m2 14inch

Ugh, I really hope that they are aware of this issue and that they will fix it because i's genuinely annoying. :c

**Comment by SethuSenthil** [comment] 2023-10-18 21:43
This issue is making the browser nearly unusable, hope the fix it soon!

**Comment by bigpurpletoast** [comment] 2023-10-19 12:46
Guys, has anyone tried this?

>You can find it here chrome://settings/help, where it shows the version number, and a button that said to relaunch Chrome to finish installing the update. It has worked since I did that.

Obviously it's for Chrome but Brave is based on Chrome so the same button exists, just replace "Chrome" by "Brave" in the link. Apparently it resolves the issue.

**Comment by bordeux** [comment] 2023-10-19 12:57
Issue is on this version too
![image](https://github.com/brave/brave-browser/assets/784536/89163a5e-0330-4174-b594-05b04f07c1d4)

**Comment by bordeux** [comment] 2023-10-19 18:29
I was able to easily reproduce issue each time. Now i know probably what is the reason :) 
Testd on version
<img width="744" alt="image" src="https://github.com/brave/brave-browser/assets/784536/6312c84e-8c44-46d6-b35a-de6a55398c0d">

1. Open brave in window mode
2. Put lets say "p" letter in omnibox
3. Make brave full screep
4. Issue appears.

https://www.youtube.com/watch?v=jONh_Shzvmc

**Comment by bigpurpletoast** [comment] 2023-10-19 20:12
Ok nevermind 2.0,

 the bug is back BUT it appeared much later after I updated Brave and the invisible block is at the top right corner so it makes it infinitely more bearable. Still I wish they would freaking fix this tho, it's really frustrating; A lot of people have reported this bug, it occurs on Chromium, Chrome AND Brave (since all of these browsers are based on Chrome) and they still haven't fixed it, like what's going on???

**Comment by bigpurpletoast** [comment] 2023-10-19 20:29
I'm going to try to enable the GPU rasterization flag again since I have now updated Brave but honestly at this point I'm not expecting anything to fix this issue. :(

**Comment by zenparsing** [comment] 2023-10-19 20:41
This appears to be an upstream issue (Chromium bug report [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1492984)). There seems to be a fix working its way through Chromium (118.0.5993.96).

**Comment by quarties** [comment] 2023-10-20 08:38
In my case, the unclickable area was about 1/3 of the screen height starting a bit from the top edge (so I could click and switch tabs, as a small top part of each tab was clickable), and about 80-90% of the screen width, which was centered (so I could click elements close the left/right edge).

I'm running the latest stable Brave build (no flags enabled). Turning off the memory saver and turning it back on immediately fixed the issue for me, and it's still working (between restarts as well).

**Comment by rebron** [comment] 2023-10-20 22:27
We released 1.59.122 with 118.0.5993.96 a few hours ago. Can folks here update and let us know if you're still seeing the issue. brave://settings/help to trigger the update.

**Comment by bordeux** [comment] 2023-10-20 22:30
@rebron  hero! 

Now the scenario from my video is gone.

**Comment by bean-z** [comment] 2023-10-20 23:44
The fix is working for me.

**Comment by bean-z** [comment] 2023-10-21 15:45
Update: I am having the issue again. Right now I can click the omnibox and the bookmarks bar, but there's still an invisible obstruction covering the top part of the webpage.

**Comment by cidus** [comment] 2023-10-21 16:35
It's still happening for me as well, the area seems smaller though, for me it's the top right corner (right on discord's search text field)
I have bitwarden extension installed, it popups right over this area, maybe it's related?

**Comment by bigpurpletoast** [comment] 2023-10-21 16:51
> It's still happening for me as well, the area seems smaller though, for me it's the top right corner (right on discord's search text field) I have bitwarden extension installed, it popups right over this area, maybe it's related?

I don't think it's related, all of my extensions are disabled right now and I encounter the same exact problem, the invisible block is indeed smaller is located at the top right corner of the page.

This update didn't do much tbh... Two days ago I updated Brave before the fix through brave://settings/help and the invisible block had already gotten smaller and moved to the top right corner of the page.

**Comment by bordeux** [comment] 2023-10-21 20:28
Update: Hotfix not fully working. Just got this same issue

**Comment by bean-z** [comment] 2023-10-22 19:55
The invisible obstruction is now blocking my omnibox and bookmarks bar again. The bottom halves of my tabs are obstructed as well.

https://github.com/brave/brave-browser/assets/143631489/e3029234-7a29-4238-b739-db327c36883e

**Comment by SethuSenthil** [comment] 2023-10-22 20:01
Yeah, the issue is more bearable in the update tho. Still, for some reason, my search in the page box is missing (the box that pops up when u do command F or Command G)

**Comment by herrjemand** [comment] 2023-10-23 02:40
Gonna add that shortcuts are unresponsive as well. Only get new tab opened after like 3 or 4 cmd+t pressed

**Comment by trivikr** [comment] 2023-10-23 03:26
> We released 1.59.122 with 118.0.5993.96 a few hours ago

The Brave 1.59.122 fixed the issue for me on macOS Sonoma on 2021 14-inch M1 MacBook Pro.

**Comment by superg28** [comment] 2023-10-23 13:47
Have this same issue on Brave 1.59.122. Noticed though when exiting full screen, for a second or so have the icon in the mac os top bar. While this is there the problem persists and functionality is back once it clears
![Screenshot 2023-10-23 at 14 46 25](https://github.com/brave/brave-browser/assets/3284154/4daae2da-be41-4063-9b27-71533b76c0fc)

**Comment by bigpurpletoast** [comment] 2023-10-23 16:46
At least the unresponsive block had gotten smaller right after the update and I was able to click on the search bar and the bookmarks but now it's just back to being huge and the bookmarks and the search bar are unresponsive again.

**Comment by jimiljojo** [comment] 2023-10-23 19:50
I think it has something to do with the top Menu overlay added on Ventura. If you have multiple displays, you can drag it to another screen, and the issue will move to that screen. 

It's making it unusable at certain times, hope this helps fix it. 

![image](https://github.com/brave/brave-browser/assets/4116653/b1cd846f-53e9-4882-ba81-abd5c81a50b5)

**Comment by bean-z** [comment] 2023-10-23 20:49
I have only one display, so I'm not familiar with this overlay. I wouldn't fully rule out the overlay, but I would expect it to affect the very tops of my tabs (which isn't the case).

Separately, since [eaufavor](https://github.com/eaufavor) mentioned having the issue on arm64, I should note that I'm using Intel.

**Comment by eaufavor** [comment] 2023-10-24 15:37
Yeah this issue still happens to me on 1.59.122 arm64. Disabling memory saver was a placebo.
I initially noticed this issue on my single display. It happened to my secondary display as well after I plugged it in.

**Comment by bigpurpletoast** [comment] 2023-10-24 15:49
Yeah, I can confirm that disabling memory saver, hardware acceleration, enabling the flag "GPU Rasterization" or updating the browser do not solve the issue.

**Comment by bigpurpletoast** [comment] 2023-10-25 01:55
The issue apparently got resolved for Chromium so since Brave is based on Chromium I hope an update is coming very soon.

**Comment by bordeux** [comment] 2023-10-25 08:23
@rebron is possible to rebuild brave for macos with latest chromium fix today?

**Comment by rebron** [comment] 2023-10-25 17:00
@bordeux @bigpurpletoast https://github.com/brave/brave-browser/releases/tag/v1.59.124 Here and we'll be releasing through our update channels and website in a couple more hours.

**Comment by eaufavor** [comment] 2023-10-25 22:59
1.59.124 arm64 has no issue so far after a few hours of usage.

**Comment by rebron** [comment] 2023-10-26 03:54
@bordeux @bigpurpletoast @bean-z Can you update to the latest 1.59.24 and let us know if you're still seeing the issue? brave://settings/help to trigger the update if you haven't gotten one yet.

**Comment by herrjemand** [comment] 2023-10-26 04:28
So far works well!

**Comment by bigpurpletoast** [comment] 2023-10-26 04:33
> So far works well!

Yes, there's no more unresponsive areas.

**Comment by SethuSenthil** [comment] 2023-10-26 05:20
Yup! Same here, the latest update seems to have fixed the issues

**Comment by bean-z** [comment] 2023-10-26 15:05
Working so far for me.

**Comment by bordeux** [comment] 2023-10-26 15:09
@rebron  testing since your last comment and no issues so far, tested all scenarios and i cannot reproduce the issue \o/

**Comment by rebron** [comment] 2023-10-31 17:49
Closing per last several comments. Fixed with 1.59.124

**Closed by rebron** 2023-10-31 17:49 UTC
Labels: needs-more-info, OS/Desktop

**Comment by lukesmith96** [comment] 2026-02-02 21:28
I keep having this issue 2/2/2026 an invisible box in the middle of the screen while in full screen. Memory saved initially disabled I have tried to re-enable, no change. Restart fixes for about a day. Box is ~the middle of the screen about 150px WxH
