### ISSUE TITLE
search google for image

### ISSUE THREAD

**Issue by phanirithvij** [brave/brave-browser#7508] opened 2019-12-22 05:08 UTC
## Description 

I want the `search google for image` option in my context menu
It shouldn't be removed but be disabled by default

## Steps to Reproduce

   1. Open any website which has an image
   2. Right click on the image
   3. You don't see the option

## Actual result:

![image](https://user-images.githubusercontent.com/29627898/71317439-180f0f80-24a7-11ea-9994-5c8622fa74b5.png)

## Expected result:
![image](https://user-images.githubusercontent.com/29627898/71317433-09285d00-24a7-11ea-8934-e369ca37a28b.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Windows 10 OS Version 1909 (Build 18363.476)
JavaScript | V8 7.9.317.32
Flash | 32.0.0.293 C:\WINDOWS\system32\Macromed\Flash\pepflashplayer64_32_0_0_293.dll
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,WebXR,UnifiedConsent,WebXrGamepadModule,AllowPopupsDuringPageUnload,SyncUSSBookmarks --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service -- https://imgflip.com/memegenerator/204520241/SrGrafo-152
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\Rithvij\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default

**Comment by srirambv** [comment] 2019-12-29 16:18
Unable to reproduce. Can you share the link where you are seeing this?

**Comment by bsclifton** [comment] 2019-12-30 05:50
@phanirithvij what is your default search engine? You can view at brave://settings/searchEngines

I don't believe it'll show unless you have Google as your default option. There is something in the search manifest which allows that to be exposed; it works for Bing too, but not DuckDuckGo, Qwant, or StartPage (likely others too)

**Comment by phanirithvij** [comment] 2019-12-30 17:28
Oh, my default search engine is 🦆🦆💨. I see. I understand now. You may
close this.

**Comment by rebron** [comment] 2019-12-30 17:34
Closing per original reporter.

**Closed by rebron** 2019-12-30 17:34 UTC
Labels: feature/context-menu, need-more-info
