### ISSUE TITLE
brave://bookmarks tab icon uses star icon instead of Brave bookmarks icon - follow up to 2494

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8492] opened 2020-03-02 20:39 UTC
## Description 

Per https://github.com/brave/brave-browser/issues/2494#issuecomment-494114305 we should also address the favicon in the brave://bookmarks tab and use our own branded icon instead of the star icon.

## Steps to Reproduce

   1. Navigate to brave://bookmarks
   2. Look at tab icon

## Actual result:

See star icon on tab
<img width="969" alt="Screen Shot 2020-03-02 at 3 35 41 PM" src="https://user-images.githubusercontent.com/28145373/75715636-bbe11c80-5c9b-11ea-8c18-1538941dc4f7.png">

## Expected result:
Tab favicon should show our own branded icon, not the star icon

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.5.105 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment] 2020-04-17 20:06
@karenkliu Can we get an icon for this one? This one has been bothering me too.

**Comment by karenkliu** [comment] 2020-04-17 20:58
@rebron This issue is a dupe of https://github.com/brave/brave-browser/issues/7312

**Comment by rebron** [comment] 2020-04-17 21:56
<img width="136" alt="Screen Shot 2020-04-17 at 2 47 03 PM" src="https://user-images.githubusercontent.com/5951041/79616612-536ac500-80ba-11ea-9964-18fc06136538.png">

Need icon for above similar to:

<img width="43" alt="Screen Shot 2020-04-17 at 2 47 45 PM" src="https://user-images.githubusercontent.com/5951041/79616681-7a28fb80-80ba-11ea-955a-28c53a58e405.png">

**Comment by karenkliu** [comment] 2020-04-17 22:22
@rebron Oops, sorry you're right, that's a different issue. 

Actually the one you need in the tab title is probably this icon:

![Screen Shot 2020-04-17 at 3 12 19 PM](https://user-images.githubusercontent.com/2388823/79618041-d5a8b880-80bd-11ea-991c-a00b4ac2b144.png)

Here you go! 
[bookmark icon.zip](https://github.com/brave/brave-browser/files/4495509/bookmark.icon.zip)

**Comment by simonhong** [comment] 2020-06-01 01:00
WebUI's favicon is determined by `ChromeWebUIControllerFactory::GetFaviconResourceBytes()`

**Closed** 2020-06-02 22:21 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, branding, bug, feature/bookmarks, priority/P3

**Comment by kjozwiak** [comment] 2020-06-16 04:10
Verification **PASSED** on `macOS 10.15.5 x64` using the following build:

```
Brave | 1.11.64 Chromium: 83.0.4103.97 (Official Build) dev (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | macOS Version 10.15.5 (Build 19F101)
```

| 1.10.90 CR: 83.0.4103.97 (Old)  | 1.11.64 CR: 83.0.4103.97 (New) |
| ------------- | ------------- |
| <img width="483" alt="Screen Shot 2020-06-16 at 12 08 33 AM" src="https://user-images.githubusercontent.com/2602313/84731048-b0251780-af65-11ea-8db3-20735db0d1bc.png">  | <img width="498" alt="Screen Shot 2020-06-16 at 12 09 00 AM" src="https://user-images.githubusercontent.com/2602313/84731071-bca97000-af65-11ea-9bed-0af87d259245.png"> |
