### ISSUE TITLE
Brave Forgets Autoplay Settings

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#1336] opened 2018-09-28 03:57 UTC
## Description 
Brave doesn't appear to remember autoplay settings for any given domain.

## Steps to Reproduce
1. Navigate to reddit.com/r/gifs
2. Allow autoplay for this domain
3. Refresh the page

## Actual result:
User is presented with an autoplay-blocked prompt.

## Expected result:
Page should remember user's previous decision, and autoplay content.

## Reproduces how often: 
Always.

## Brave version (chrome://version info)
0.55.10

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No.
- Is the issue reproducible on the latest version of Chrome? No.

### Additional Information
![autoplay-doesnt-stick](https://user-images.githubusercontent.com/815158/46187292-94b53d00-c2a8-11e8-88aa-ab30c69bd063.gif)

**Comment by yrliou** [comment] 2018-09-28 04:10
Duplicate of https://github.com/brave/brave-browser/issues/1120, I think it is caused by the same reason.

**Closed** 2018-09-28 04:11 UTC
