### ISSUE TITLE
Retry initialization requests for referral codes

### ISSUE THREAD

**Issue by corymcdonald** [brave/brave-browser#7742] opened 2020-01-15 22:00 UTC
## Description 

During friday 1/10 to monday 1/13 the promo server's static IP was not routing correctly. Due to this referrals that were downloaded during that time would never get confirmed. 

## Expected result:
We should retry initialization requests so that if the promo server is down publishers will still get paid for those referrals.

## Reproduces how often: 
Anytime the promo server is down.

@emerick feel free to add more details :)

**Comment by bsclifton** [comment] 2020-02-27 17:25
Marked as `P2` since this can cause data loss - we'll definitely want to fix sooner than later. Would be good to harden that logic a bit

**Comment by keur** [comment] 2020-04-10 17:10
xposting the test plan cc @bsclifton 

### Test Plan

  1. Set `"BRAVE_REFERRALS_SERVER"` environment variable to point at a [vault updater](https://github.com/brave/vault-updater) server. If you want to use staging or pre (probably the best idea) talk to @keur or @aubrey. 
  2. Set `BRAVE_REFERRALS_LOCAL`, if testing locally  
  3. Set `"BRAVE_REFERRALS_API_KEY"` corresponding to a valid promo services key (again, talk to @keur or @aubrey for more information).
  4. Set `kReportInitializationFrequency` to something reasonable for testing (< 1 minute). 
  5. Make the testing vault updater either non-routeable or return a non 2xx code
  6. Wait for the browser to retry until it gets a `download_id`.
  7. Ensure the browser no longer sends out initialization requests.

**Comment by bsclifton** [comment] 2020-04-13 18:11
issue was resolved with https://github.com/brave/brave-core/pull/5200 but reverted with https://github.com/brave/brave-core/pull/5226

Needs re-implementation. Problem was with building on Android

**Closed** 2020-05-10 09:47 UTC
Labels: QA/Yes, feature/referral-promo, priority/P2, release-notes/include

**Comment by LaurenWags** [comment] 2020-05-11 14:23
@bsclifton @rebron is milestone for this issue correct?

**Comment by bsclifton** [comment] 2020-05-11 20:04
@LaurenWags yup, 1.9.x is correct; for some reason merging https://github.com/brave/brave-core/pull/5238 didn't auto-close this issue. You're good to go! 😄

**Comment by LaurenWags** [comment] 2020-05-14 19:00
Marking as `QA/Blocked` pending https://github.com/brave/brave-browser/issues/9783

**Comment by srirambv** [comment] 2020-05-15 06:25
@LaurenWags Probably mark it as Windows/Mac OS only

**Comment by LaurenWags** [comment] 2020-05-19 20:04
Verified passed with

```
Brave | 1.9.66 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Used modified version of test plan from https://github.com/brave/brave-browser/issues/7742#issuecomment-612125836 since `kReportInitializationFrequency` cannot be set using a GH build. We did confirm that if the server is down/you do not get a `download_id`, that when you restart the browser, the server is pinged again and if the server is up at this time you do get the expected `download_id` (@keur confirmed my `download_id` on the server).

* Confirmed no regressions when using macOS and a standard promoCode tagged .pkg (such as Brave-Browser-Dev-KAM253.pkg)

* Note, there was an issue on macOS only where the profile folder could be created improperly if the .pkg was named like `Brave-Browser-Dev-kam253.pkg`, however this was logged with https://github.com/brave/brave-browser/issues/9785 and testing notes can be found on that issue.

-----
