### ISSUE TITLE
Kindly resolve this issue. 🙏

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#33115] opened 2023-09-19 10:13 UTC
After installing the web browser my desktop getting automatically filled with these similar folders. Kindly resolve the issue. 😢

![Brave Browser](https://github.com/brave/brave-browser/assets/145432904/adc1458c-626a-45d4-a867-7fdd4bc63c98)

**Comment by Dev-X-Innovate** [comment] 2023-09-19 17:47
> After installing the web browser my desktop getting automatically filled with these similar folders. Kindly resolve the issue. 😢
> 
> ![Brave Browser](https://user-images.githubusercontent.com/145432904/268919766-adc1458c-626a-45d4-a867-7fdd4bc63c98.png)

To resolve the issue of folders appearing on your desktop after installing a web browser, follow these steps:

Check for Malware: Run a full antivirus scan to ensure there are no malicious programs causing the problem.

Uninstall Suspicious Software: Remove any recently installed or suspicious software from your computer.

Check Browser Extensions: Remove any unusual or suspicious browser extensions or add-ons.

Reset Browser Settings: If the issue persists, reset your browser settings to their default state.

Reinstall the Browser: Uninstall the browser and reinstall it from the official website.

Contact Support: If the problem continues, reach out to the browser's support team or community forums for assistance.

**Comment by kenherbert** [comment] 2023-09-20 06:34
Duplicate of https://github.com/brave/brave-browser/issues/28600

**Comment by rebron** [comment] 2023-09-29 22:09
Closing as dupe of #28600

**Closed by rebron** 2023-09-29 22:09 UTC
Labels: OS/Desktop
