### ISSUE TITLE
Ensure that Tor "New Identity" doesn't over-promise or under-deliver on what Tor Browser uses the same words to mean

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#3065] opened 2019-01-24 00:53 UTC
Inspired by comments in https://github.com/brave/brave-browser/issues/2734#issuecomment-453632499

**Comment by diracdeltas** [comment] 2020-09-25 20:49
I'm not sure I understand this issue. AFAICT we never implemented the UI for new identity/circuit in brave-core, which means it's a regression from muon. #11822

**Comment by diracdeltas** [comment] 2020-09-25 20:53
Actually I think we can close this because the button in the hamburger menu now says "New Tor connection for this site"

**Closed by diracdeltas** 2020-09-25 20:53 UTC
Labels: feature/tor, feature/user-interface, needs-discussion, priority/P4
