### ISSUE TITLE
Click Selection Functionality in the Menu bar, and other places

### ISSUE THREAD

**Issue by Tectract** [brave/brave-browser#8575] opened 2020-03-06 18:45 UTC
Clicking in the menu bar once should not highlight the whole address. It should place the cursor in the menu bar in between two characters. Double-clicking should then select a word, and triple-clicking should select the entire address URL.

This is another "mac feature" that was designed backwards, and there was a HUGE thread with like 100,000 comments and flame wars, in the old mac forums.

It's still broken. I feel like I'm using kid gloves with the mouse because I have to triple-click just to place the cursor where I want it. This "whole URL selection" is like "whole word" selection in Word. I never asked for that, never wanted it, just gets in the way, on an every day basis.

**Comment by rebron** [comment] 2020-03-06 18:56
@Tectract We appreciate the feedback and passionate frustration but we do want to focus that energy so that we can actually do something about it. 

community.brave.com is best for more of your general thoughts and feedback  because we really need these issues to be way better formed by 1) following our issues template and 2) having these issues b clearer and have reproducible steps that our team can actually work on. 

cc: @Brave-Matt from our community team.

**Comment by Brave-Matt** [comment] 2020-03-06 19:28
@Tectract ,
As @rebron said, community.brave.com is the best place to voice your concerns. Additionally, it's also the same behavior on Windows machines, and it's also the same across all browsers (tested with Chrome, Firefox, Opera, Vivaldi, Edge, and Brave). 

Also, I'm not sure what your situation is but for me, I only have to click twice to insert the cursor in-between two characters - first click highlights everything, second click places the cursor where I click in the text field.

While I apologize for the inconvenience, I can't imagine this particular issue will be a priority any time soon.

**Comment by Tectract** [comment] 2020-03-07 14:51
Ah yes, now it only takes two clicks. But it's still backwards. It should insert the cursor FIRST, then select the whole URL on a double-click instead. I lknow it's not a priority but it's a "death by a thousand cuts" issue. It's something that like a million people were passionate about, 20 years ago when the decision was made, and some of us still are, lol.

**Comment by rebron** [comment] 2020-04-24 18:12
Closing. wontfix per https://github.com/brave/brave-browser/issues/8575#issuecomment-595923839
Changing selection behavior in the url bar is not something we'll be doing.

**Closed by rebron** 2020-04-24 18:12 UTC

**Comment by Tectract** [comment] 2020-04-24 18:50
It's really sad that the Brave devs are not interested in fixing any of the "death by a thousand cuts" issues that were introduced by the Chrome team. It's really sad that you are making us use this interface which was broken to make it more like a mac and less like the old linux gnome II interface, which is the golden standard of user interfaces for power users.
