### ISSUE TITLE
Crash Report when disconnecting monitor 

### ISSUE THREAD

**Issue by mat926** [brave/brave-browser#36589] opened 2024-03-06 19:29 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.63.165 Chromium: 122.0.6261.94
Operating System: Windows NT 10.0.19045

URL (if applicable) where crash occurred:

Can you reproduce this crash? Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Disconnected an extending desktop monitor
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/eb930000-38c5-9e0b-0000-000000000000

**Comment by bsclifton** [comment] 2024-03-06 21:53
Backtrace
https://brave.sp.backtrace.io/p/brave/debug?filters=JTVCJTVCJTIyX2RlbGV0ZWQlMjIlMkMlMjJlcXVhbCUyMiUyQyUyMjAlMjIlNUQlMkMlNUIlMjJfcnhpZCUyMiUyQyUyMmVxdWFsJTIyJTJDJTIyZWI5MzAwMDAtMzhjNS05ZTBiLTAwMDAtMDAwMDAwMDAwMDAwJTIyJTVEJTVE&fingerprint=0578a7a001f6174efdcded16730183053bd60de72a0d5f90b59ce9bbc47e891d&debug=(%226c08fd9%22,0,0)

Callstack
```
[ 00 ] VideoOverlayWindowViews::GetWorkAreaForWindow() ( video_overlay_window_views.cc:679 )
[ 01 ] VideoOverlayWindowViews::OnDisplayMetricsChanged(display::Display const &,unsigned int) ( video_overlay_window_views.cc:656 )
[ 02 ] display::DisplayChangeNotifier::NotifyDisplaysChanged(std::__Cr::vector<display::Display,std::__Cr::allocator<display::Display> > const &,std::__Cr::vector<display::Display,std::__Cr::allocator<display::Display> > const &) ( display_change_notifier.cc:79 )
[ 03 ] display::win::ScreenWin::UpdateAllDisplaysAndNotify() ( screen_win.cc:919 )
[ 04 ] views::HWNDMessageHandler::OnDisplayChange(unsigned int,gfx::Size const &) ( hwnd_message_handler.cc:1797 )
[ 05 ] malloc(unsigned __int64) ( allocator_shim_override_ucrt_symbols_win.h:86 )
[ 06 ] operator new(unsigned __int64) ( new_scalar.cpp:35 )
[ 07 ] gfx::WindowImpl::WndProc(HWND__ *,unsigned int,unsigned __int64,__int64) ( window_impl.cc:310 )
[ 08 ] base::win::WrappedWindowProc<&gfx::WindowImpl::WndProc>(HWND__ *,unsigned int,unsigned __int64,__int64) ( wrapped_window_proc.h:77 )
[ 09 ] UserCallWinProcCheckWow(struct _ACTIVATION_CONTEXT *,__int64 (*)(struct tagWND *,unsigned int,unsigned __int64,__int64),struct HWND__ *,enum _WM_VALUE,unsigned __int64,__int64,void *,int)
[ 10 ] DispatchClientMessage
[ 11 ] __fnEMPTY
[ 12 ] KiUserCallbackDispatch
[ 13 ] ZwUserPeekMessage
[ 14 ] _PeekMessage
[ 15 ] PeekMessageW
[ 16 ] base::MessagePumpForUI::ProcessNextWindowsMessage() ( message_pump_win.cc:501 )
[ 17 ] base::MessagePumpForUI::DoRunLoop() ( message_pump_win.cc:207 )
[ 18 ] base::MessagePumpWin::Run(base::MessagePump::Delegate *) ( message_pump_win.cc:79 )
[ 19 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool,base::TimeDelta) ( thread_controller_with_message_pump_impl.cc:649 )
[ 20 ] base::RunLoop::Run(base::Location const &) ( run_loop.cc:136 )
[ 21 ] content::BrowserMainLoop::RunMainMessageLoop() ( browser_main_loop.cc:1096 )
[ 22 ] content::BrowserMainRunnerImpl::Run() ( browser_main_runner_impl.cc:159 )
[ 23 ] content::BrowserMain(content::MainFunctionParams) ( browser_main.cc:34 )
[ 24 ] RunBrowserProcessMain(content::MainFunctionParams,content::ContentMainDelegate *) ( content_main_runner_impl.cc:708 )
[ 25 ] content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams,bool) ( content_main_runner_impl.cc:1295 )
[ 26 ] std::__Cr::basic_string<char,std::__Cr::char_traits<char>,std::__Cr::allocator<char> >::operator basic_string_view() ( string:1109 )
[ 27 ] content::ContentMainRunnerImpl::Run() ( content_main_runner_impl.cc:1140 )
[ 28 ] RunContentProcess(content::ContentMainParams,content::ContentMainRunner *) ( content_main.cc:335 )
[ 29 ] content::ContentMain(content::ContentMainParams) ( content_main.cc:348 )
[ 30 ] ChromeMain(HINSTANCE__ *,sandbox::SandboxInterfaceInfo *,__int64) ( chrome_main.cc:196 )
[ 31 ] Load(base::FilePath *,base::CommandLine const &) ( main_dll_loader_win.cc:105 )
[ 32 ] MainDllLoader::Launch(HINSTANCE__ *,base::TimeTicks) ( main_dll_loader_win.cc:169 )
[ 33 ] wWinMain(HINSTANCE__ *,HINSTANCE__ *,wchar_t *,int) ( chrome_exe_main_win.cc:401 )
[ 34 ] invoke_main() ( exe_common.inl:118 )
[ 35 ] __scrt_common_main_seh() ( exe_common.inl:288 )
[ 36 ] BaseThreadInitThunk
[ 37 ] RtlUserThreadStart
```

**Comment by bsclifton** [comment] 2024-03-06 21:54
Thanks for the report - this issue is a duplicate of https://github.com/brave/brave-browser/issues/35528 so I will close

Good news is - we have a fix with https://github.com/brave/brave-core/pull/22468 😄 We'll work on getting this merged and pushed out to release channel.

**Closed by bsclifton** 2024-03-06 21:54 UTC
Labels: crash, OS/Windows, priority/P2, OS/Desktop

**Comment by mat926** [comment] 2024-03-09 19:32
Hello I have updated to Brave Version 1.63.169 Chromium: 122.0.6261.111 (Official Build) (64-bit)] and I am still getting the crash. Here is the latest crash report ID: 2ef30700-38c5-9e0b-0000-000000000000
