### ISSUE TITLE
Different theme choice in different profiles affects other profiles

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#5373] opened 2019-07-24 18:28 UTC
When having multiple profiles, if profile A changes the preference for Theme, profile B is affected.

## Steps to Reproduce
1. Open Settings page in current profile window (Profile A)
2. Set Theme to Light
2. Open profile B window
 --> Observe Profile A and Profile B have same theme (light or dark)
3. Open Settings page in both Profile A window and Profile B window
4. Change theme selection in Profile B to Dark

#### Expected
Profile B change to Dark. Profile A stays light - both the browser toolbar, and the Settings page background.

##### Actual
Profile B and Profile A both change to Dark - both the browser toolbar and the Settings page background.

**Comment by simonhong** [comment] 2019-07-24 22:48
Yes, I think this is the limitation of current chromium architecture because dark mode is managed in ui layer and there is no concept in that layer.

**Comment by petemill** [comment] 2019-07-24 22:52
@simonhong edge canary 77.0.228.0 (based on chromium) has the same issue!

**Comment by simonhong** [comment] 2019-07-24 22:56
right, I saw that :) Need to think how to overcome :)

**Comment by LaurenWags** [comment] 2019-10-03 17:15
Other ways to reproduce
From @petemill using Mojave:
(pre-req: have multiple profiles):
1. macOS is set to dark
2. Change Brave to 'Light'
3. Restart browser
4. Dialogs, webui and infobars are dark, but toolbar is light

From me using High Sierra:
1. Clean profile on Nightly (0.72.68), Nightly defaults to dark.
2. Create a new profile so you now have two
3. Go to brave://settings on second profile
4. Change Brave colors to Light
5. Second profile window appears light (settings page, toolbar, hamburger menu, etc.
<img width="1200" alt="Screen Shot 2019-10-03 at 1 10 54 PM" src="https://user-images.githubusercontent.com/28145373/66148603-4d5e3c80-e5df-11e9-86c1-cfd717ec42b0.png">

6. First profile is now in an in-between state. Toolbar is dark, but hamburger menu and settings page are light.
<img width="1196" alt="Screen Shot 2019-10-03 at 1 11 04 PM" src="https://user-images.githubusercontent.com/28145373/66148611-50592d00-e5df-11e9-8446-cd0d0d69d762.png">

7. Restart Nightly.
8. First profile window is now as expected (toolbar, settings page, hamburger menu, etc) are dark.
<img width="1195" alt="Screen Shot 2019-10-03 at 1 12 26 PM" src="https://user-images.githubusercontent.com/28145373/66148701-84345280-e5df-11e9-9d54-7f9b30d1bf87.png">

9. Second profile window is now in an in-between state - Toolbar is light, but settings page and hamburger menu are dark.
<img width="1200" alt="Screen Shot 2019-10-03 at 1 13 17 PM" src="https://user-images.githubusercontent.com/28145373/66148748-9f06c700-e5df-11e9-869b-6b6be435a798.png">

10. This flip flop about which profile is in which state (inbetween or expected) will continue - it looks like maybe related to which profile you had active when closing the browser.

**Comment by bsclifton** [comment] 2019-11-05 04:46
@simonhong were you still checking this and https://github.com/brave/brave-browser/issues/5557 out?

**Comment by simonhong** [comment] 2019-12-09 04:31
@rebron @bsclifton @petemill  Brave theme inconsistency can happen easily when a user uses multi profiles.
How about making brave theme option to browser wide prefs?
I think it's the easiest solution for use and assume that edge might have same policy.
WDYT?

**Comment by petemill** [comment] 2019-12-09 06:44
Yes I agree @simonhong. It's not possible to align native theme properly otherwise.

**Comment by bsclifton** [comment] 2019-12-09 06:44
@simonhong I like that approach 😄

**Comment by LaurenWags** [comment] 2019-12-09 14:33
++ on @simonhong suggestion

**Comment by simonhong** [comment] 2019-12-10 00:21
Thanks for feedback @LaurenWags @bsclifton @petemill :)
I'll start this :)

**Comment by LaurenWags** [comment] 2019-12-10 00:22
something we should consider when checking upgrade cases - if a user is currently in a position where one or more profiles have different themes set, which one gets globally set on upgrade? I'd probably vote the theme on the Default profile, but unsure if there are other things to consider here?

**Comment by simonhong** [comment] 2019-12-10 00:27
@LaurenWags Migration theme option from profile to local state(global pref) will be done only once.
When it happens, I think options from firstly activated profile would be used for migration.
After that, it becomes the global option.
Actually, determining which profile is default or not is difficult. WDYT?

**Comment by LaurenWags** [comment] 2019-12-10 00:32
As long it's documented which one we should expect I'm good with whatever 😄 thanks @simonhong!

**Comment by simonhong** [comment] 2019-12-10 00:35
I used same policy for migrating Widevine prefs.
Widevine had similar issue. (https://github.com/brave/brave-browser/issues/6747)
If user think migrated theme is not his/her default theme option, just need one time option changing :)

**Closed** 2019-12-18 23:09 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/settings, feature/themes, priority/P4

**Comment by GeetaSarvadnya** [comment] 2020-02-13 10:34
Verification passed on


Brave | 1.4.84 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/4210
- Verified that theme change in one Profile affects all other profiles
- Have 3 profiles P1, P2 and P3 in 1.3.x and set different themes in each profile and upgrade to 1.4.x 
after the upgrade ensured that all three profiles have the same theme.

**Comment by drzamich** [comment] 2021-02-21 17:38
It would actually be nice for Brave to support different theming in different profiles. I like to separate work and private browsing. When having different themes in profiles, I can immediately know which profile I'm on so that I don't accidentally share my browsing history when on screen sharing for instance.
