### ISSUE TITLE
Browser crashes upon start when the system is about to enter DST

### ISSUE THREAD

**Issue by jugolm** [brave/brave-browser#40926] opened 2024-09-08 04:30 UTC
### Description

Right before the start of DST, several Windows users in Chile were temporarily unable to open Brave as summer time was rolling out in their systems. They had to solve the issue by manually playing around the timezone settings. The link below shows an example video.
https://www.reddit.com/r/brave_browser/comments/1fbofvo/why_brave_dont_open/?sort=new

As the time change has already rolled out, the issue may be already gone, but it may happen later for other timezones.

### Steps to reproduce

As it's related to the start of DST, it may be difficult to reproduce; however, it probably involves a mismatch between the client's time and servers' real time.

### Actual result

Browser crashes instantly.

https://www.reddit.com/r/brave_browser/comments/1fbofvo/why_brave_dont_open/?sort=new

### Expected result

Browser opens

### Reproduces how often

No steps to reproduce

### Brave version (brave://version info)

Brave | 1.69.162 Chromium: 128.0.6613.120 (Build oficial) (64 bits)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment] 2024-09-12 22:16
Closing as dupe of https://github.com/brave/brave-browser/issues/41028

**Closed by rebron** 2024-09-12 22:16 UTC
Labels: closed/duplicate, needs-investigation, needs-more-info, OS/Desktop
