### ISSUE TITLE
Another instance of DuckDuckGo is added to search engines on upgrade for AU/NZ/IE locale

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6453] opened 2019-10-12 00:54 UTC
Follow up to https://github.com/brave/brave-browser/issues/6187
Users who have set custom search engine to `duckduckgo` in AU/NZ/IE will have another instance of DuckDuckGo added to search engines upon upgrade to 0.70.x

## Steps to Reproduce

   1. Set system locale to AU
   2. Install 0.69.x
   3. Set default search engine to `duckduckgo` in `chrome://settings/searchEngines`
   4. Upgrade to 0.70.x
   5. Check list of search engines in `chrome://settings/searchEngines`

## Actual result:

DuckDuckGo is listed twice
Another instance of DuckDuckGo is added to search engines
The search strings are different from each other.
![image](https://user-images.githubusercontent.com/34715963/66691970-83b05180-ec9a-11e9-9ab8-98013e35a9db.png)

## Expected result:
DuckDuckGo is listed once

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.70.112 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron @bsclifton

**Comment by LaurenWags** [comment] 2019-10-14 14:11
Reproduced on macOS.

Also, I have a 3rd DDG listed - it's in `Other Search Engines` section.

Default DDG:
<img width="936" alt="Screen Shot 2019-10-14 at 10 08 19 am" src="https://user-images.githubusercontent.com/28145373/66757727-c6c11f00-ee6a-11e9-869a-edff74022c0e.png">

Added DDG entry to `Default search engines` section on upgrade:
<img width="943" alt="Screen Shot 2019-10-14 at 10 09 01 am" src="https://user-images.githubusercontent.com/28145373/66757756-d50f3b00-ee6a-11e9-90c1-b0f1ea5baed8.png">

Additional DDG entry under `Other search engines`:
<img width="940" alt="Screen Shot 2019-10-14 at 10 09 42 am" src="https://user-images.githubusercontent.com/28145373/66757766-dd677600-ee6a-11e9-818a-4f989033b28f.png">


Brave | 0.70.115 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

**Comment by LaurenWags** [comment] 2019-10-14 19:44
Occurs for DE as well if DDG was set to be the default SE prior to upgrade:
<img width="667" alt="Screen Shot 2019-10-14 at 15 43 53" src="https://user-images.githubusercontent.com/28145373/66778370-74e3bd80-ee99-11e9-817f-d65eccdcbc1d.png">


Brave | 0.70.115 Chromium: 77.0.3865.90 (Offizieller Build) beta (64-Bit)
-- | --
Überarbeitung | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
Betriebssystem | macOS Version 10.13.6 (Build 17G5019)

**Comment by LaurenWags** [comment] 2019-10-14 19:45
something to note - the 'Default' DDG no longer has the shortcut as `:d`, the new one does. Not sure if that's part of the problem?

**Comment by GeetaSarvadnya** [comment] 2019-10-15 03:37
Reproduced in Windows 10 x64- 0.70.113.  DDG was set in 060.x prior upgrade after upgrade another instance of DDG added in the search engines

![image](https://user-images.githubusercontent.com/38657976/66798234-fdf70500-ef2a-11e9-830a-ec9ced3a8c1d.png)

**Comment by bsclifton** [comment] 2019-10-17 18:30
Although it's confusing, this is following the proper behavior. So it's not a bug- it just looks weird.

`Default search engines` will always show the 5 pre-populated engines, no matter what. Your default will also show in there too (ex: if you set youtube.com as your default, it moves itself from `Other search engines` to `Default search engines` and puts `(Default)` next to it)

Will try to think about a way to resolve this- maybe we can not add pre-populated entries if the default is basically the same (search keyword matches or most URL matches)?

**Comment by bsclifton** [comment] 2019-10-17 23:59
We can keep this issue open and in the milestone for now - but my proposal would be to leave it as-is (as awkward as it looks)

Here's why it shows there...
- When an engine is set as the default, it's added to `Default/Secure Preferences`
- The code is pulling prepopulated engines and then merging in the default option

Possible solutions include:
- Creating a template URL service instance and removing the duplicate entry from `Default/Web Data`
- Filtering out the duplicate entry

Both solutions require the code in `chromium_src/components/search_engines/template_url_prepopulate_data.cc` to either:
1. fetch the profile in order to get a reference to the template url service. I ran into a race condition which causes the app to crash (profile has a lock on it, at the time it's requesting access). 
2. have a different interface where the caller passes default engine ID (breaking the interface that we're overriding from Chromium)

I'm not sure this one is worth fixing, given the extra complexity it would introduce
cc: @rebron

**Comment by bsclifton** [comment] 2019-10-21 07:47
Removing from milestone, per the above notes

**Comment by bsclifton** [comment] 2019-11-05 04:52
Given that this isn't a bug, I'm going to close as `wontfix` (notes above describing)

**Closed by bsclifton** 2019-11-05 04:52 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/search, priority/P5, release-notes/exclude
