### ISSUE TITLE
Griffin studies/experiments not being applied on first launch - follow up to #34150

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#35232] opened 2024-01-10 05:20 UTC
## Description 

As per https://github.com/brave/brave-browser/issues/34150#issuecomment-1881694801, looks like Griffin studies/experiments are not being applied on first launch. However, it does work correctly on second launch (which is the current/old behaviour). As per @mherrmann, this should only work via the `stub/online` installers as per https://github.com/brave/brave-browser/issues/34150#issuecomment-1882520192.

## Steps to Reproduce

**`Against Production`**

* install `1.62.134 Chromium: 120.0.6099.199` via https://github.com/brave/brave-browser/releases/download/v1.62.134/BraveBrowserBetaSetup.exe
* once the browser launches, check `brave://version` and notice that there's no Griffin studies being listed
* visit https://www.cnn.com and click on any of the articles and click on the `Speedreader` icon (notice that TTS is not present)
* restart the browser and notice that the Griffin studies are now being applied
  * `Speedreader TTS:Speedreader: TTS enabled`
* visit the same article and notice that the TTS option is now available (which means that the Griffin study as been applied)

## Actual result:

![seedNotWorking](https://github.com/brave/brave-browser/assets/2602313/888309a8-8961-453d-b46b-22589299d82d)

## Expected result:

![seedWorking](https://github.com/brave/brave-browser/assets/2602313/cbd22718-4a02-48e6-a247-26074bdeb430)

## Reproduces how often: 

100% reproducible when running through the STR/Cases mentioned above.

## Brave version (brave://version info)

```
Brave | 1.63.101 Chromium: 120.0.6099.199 (Official Build) nightly (64-bit)
-- | --
Revision | 8d3f0a563e185b6a763cc8e210ab24775dfb9047
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` (#34150 only landed in `1.62.x` and below)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by mherrmann** [comment] 2024-01-10 18:58
The problem is that the update server returns `variations_compressed_seed` but not `variations_seed_signature`.

**Comment by mherrmann** [comment] 2024-01-12 10:18
I fixed this via https://github.com/brave/devops/pull/11138.

**Comment by mherrmann** [comment] 2024-01-12 10:19
@kjozwiak this should be fixed. Because the fix was purely server-side, this means that Beta (and other channels) should already have it. For me, Beta works as expected now.

**Closed by mherrmann** 2024-01-12 10:18 UTC
Labels: OS/Windows, QA/Yes, release-notes/include, OS/Desktop, griffin

**Comment by MadhaviSeelam** [comment] 2024-01-23 18:27
Verification `In progress` using
```
Brave | 1.61.120 Chromium: 120.0.6099.234 (Official Build) (64-bit)
-- | --
Revision | 362207c81bff0740a8b6cff62dd91c6789f5698f
OS | Windows 11 Version 22H2 (Build 22621.3007)
```

1. installed 1.62.150 Chromium 121.0.6167.85 via https://github.com/brave/brave-browser/releases/download/v1.62.150/BraveBrowserSetup.exe
2. once the browser launched, opened brave://version
3. verified Griffine studies are listed in the page eg. Speedreader TTS: Enabled 
4. opened https://www.cnn.com/travel/japanese-kobe-beef-croquettes-43-year-wait-list-intl-hnk/index.html in a new tab
5. clicked Speedreader button in the URL bar
6. Confirmed TTS button is available in the Speedreader toolbar
7. clicked TTS button and played
8. Confirmed TTS functionality worked as expected.
9. restarted the browser and brave://version shows Speedreader Griffin study.

example | example | example | example 
----- | ----- | ----- | -----
<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/422e308e-0c7d-4380-ae82-0fe05b0a0255">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/357b341a-b5f8-442a-a6e6-9fff240c5ae4">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/176c490b-f82f-41b4-ac69-dfb56dcc3d0b">|<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/4cc211a2-0848-47f1-b306-6da75f9e86f8">

**Comment by GeetaSarvadnya** [comment] 2024-01-24 15:46
Verification INPROGRESS on

```
Brave | 1.62.151 Chromium: 121.0.6167.85 (Official Build) (64-bit)
-- | --
Revision | ebbd33e41da941bb33944e03c2a24df87cae4927
OS | Windows 10 Version 22H2 (Build 19045.3930)

```

**Comment by kjozwiak** [comment] 2024-01-24 20:13
## `Win x86` verification(s):

### `Stub` installers (Online Installer/Griffin applied on first startup)

#### Using `1.62.x` stub installer (will pull/install `1.61.x` at this point)

Verification **PASSED** on `Win 10 x86` using the following build(s):

```
Brave | 1.61.120 Chromium: 120.0.6099.234 (Official Build) (32-bit)
-- | --
Revision | 362207c81bff0740a8b6cff62dd91c6789f5698f
OS | Windows 10 Version 22H2 (Build 19045.3996)
```

* downloaded/installed https://github.com/brave/brave-browser/releases/download/v1.62.151/BraveBrowserSetup32.exe
* ensured that `Brave` launched automatically once installed using the `stub (online)` installer
* visited `brave://version` and ensured that the Griffin studies are being applied on first launch
* ensured that `Speedreader TTS:Enabled` was being applied by visiting [CNN](https://www.cnn.com/politics/live-news/new-hampshire-primary-01-23-24/index.html) and ensuring `TTS` was visible/enabled when viewing article in `Speedreader`
* ensured that `BraveGoogleSignInPermissionStudy:Enabled` was being applied by visiting [ChartHop](https://app.charthop.com/account/login) and ensuring that the `Allow use of third-party cookie for legacy Google Sign-In` modal appeared.
* Restarted `1.61.120 Chromium: 120.0.6099.234` several times and ensured that Griffin studies still visible under `brave://version`

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/2602313/959ef455-9f75-4efc-a97b-ae53a8c0e3b4) | ![image](https://github.com/brave/brave-browser/assets/2602313/a30b1e5f-3e85-495f-bdb9-b4966cfecd54) | ![image](https://github.com/brave/brave-browser/assets/2602313/6c456f41-2d39-4b8d-a803-35d1a43095fb)

#### Using `1.63.x` stub installer

Verification **PASSED** on `Win 10 x86` using the following build(s):

```
Brave | 1.63.131 Chromium: 121.0.6167.85 (Official Build) beta (32-bit)
-- | --
Revision | b69a41804b058724f2aa0f10f4c7c759d09dc8cf
OS | Windows 10 Version 22H2 (Build 19045.3996)
```

* downloaded/installed https://github.com/brave/brave-browser/releases/download/v1.63.131/BraveBrowserBetaSetup32.exe
* ensured that `Brave` launched automatically once installed using the `stub (online)` installer
* visited `brave://version` and ensured that the Griffin studies are being applied on first launch
* ensured that `Speedreader TTS:Enabled` was being applied by visiting [CNN](https://www.cnn.com/politics/live-news/new-hampshire-primary-01-23-24/index.html) and ensuring `TTS` was visible/enabled when viewing article in `Speedreader`
* ensured that `BraveWebViewRoundedCornersStudy:Enabled` was being applied by ensuring that active tabs appeared rounded
* Restarted `1.63.131 Chromium: 121.0.6167.85` several times and ensured that Griffin studies still visible under `brave://version`

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/2602313/b741419a-25fa-45da-9aa8-c46690ef4207) | ![image](https://github.com/brave/brave-browser/assets/2602313/71fd3614-b133-4411-82d9-6faa021871b3) | ![image](https://github.com/brave/brave-browser/assets/2602313/af03ed8b-c7c8-49fe-8a59-8bb46a138fdb)

### `Standalone` installers (Offline Installers/Griffin `NOT` applied on first launch)

#### Using `1.62.x` standalone installer

```
Brave | 1.62.151 Chromium: 121.0.6167.85 (Official Build) (32-bit)
-- | --
Revision | ebbd33e41da941bb33944e03c2a24df87cae4927
OS | Windows 10 Version 22H2 (Build 19045.3996)
```

* downloaded/installed https://github.com/brave/brave-browser/releases/download/v1.62.151/BraveBrowserStandaloneSetup32.exe
* ensured that `Brave` launched automatically once installed using the `standalone (offline)` installer
* visited `brave://version` and ensured that the Griffin studies are **NOT** being applied on first launch
* restart `1.62.151 Chromium: 121.0.6167.85` and ensured that Griffin studies are being applied/appearing via `brave://version`
* ensured that `Speedreader TTS:Enabled` was being applied by visiting [CNN](https://www.cnn.com/politics/live-news/new-hampshire-primary-01-23-24/index.html) and ensuring `TTS` was visible/enabled when viewing article in `Speedreader`
* ensured that `BraveGoogleSignInPermissionStudy:Enabled` was being applied by visiting [ChartHop](https://app.charthop.com/account/login) and ensuring that the `Allow use of third-party cookie for legacy Google Sign-In` modal appeared.
* Restarted `1.62.151 Chromium: 121.0.6167.85` several times and ensured that Griffin studies still visible under `brave://version`

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------
![image](https://github.com/brave/brave-browser/assets/2602313/701a71b9-b964-4a71-bf24-47e4f8a5a26a) | ![image](https://github.com/brave/brave-browser/assets/2602313/976002c2-63c5-4359-9650-1f5d83e32d3b) | ![image](https://github.com/brave/brave-browser/assets/2602313/e2536e6f-1b13-4a49-8536-5a144c1e96b1) | ![image](https://github.com/brave/brave-browser/assets/2602313/b1941531-bc9a-427e-a382-e7b70b19ba2c)

#### Using `1.63.x` standalone installer

```
Brave | 1.63.131 Chromium: 121.0.6167.85 (Official Build) beta (32-bit)
-- | --
Revision | b69a41804b058724f2aa0f10f4c7c759d09dc8cf
OS | Windows 10 Version 22H2 (Build 19045.3996)
```

* downloaded/installed https://github.com/brave/brave-browser/releases/download/v1.63.131/BraveBrowserStandaloneBetaSetup32.exe
* ensured that `Brave` launched automatically once installed using the `standalone (offline)` installer
* visited `brave://version` and ensured that the Griffin studies are **NOT** being applied on first launch
* restart `1.63.131 Chromium: 121.0.6167.85` and ensured that Griffin studies are being applied/appearing via `brave://version`
* ensured that `Speedreader TTS:Enabled` was being applied by visiting [CNN](https://www.cnn.com/politics/live-news/new-hampshire-primary-01-23-24/index.html) and ensuring `TTS` was visible/enabled when viewing article in `Speedreader`
* ensured that `BraveWebViewRoundedCornersStudy:Enabled` was being applied by ensuring that active tabs appeared rounded
* Restarted `1.63.131 Chromium: 121.0.6167.85` several times and ensured that Griffin studies still visible under `brave://version`

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------
![image](https://github.com/brave/brave-browser/assets/2602313/87dedec9-a25a-4927-bd20-c14f0891e5dc) | ![image](https://github.com/brave/brave-browser/assets/2602313/ca041072-8c1a-48a0-9a69-2b32f0c9de05) | ![image](https://github.com/brave/brave-browser/assets/2602313/ad157a4d-08b2-48ee-9abe-43c98b2824d7) | ![image](https://github.com/brave/brave-browser/assets/2602313/349f43a6-4f0c-4ae5-bab1-7490405bbd68)
