### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by thickpilk** [brave/brave-browser#34813] opened 2023-12-10 04:51 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.101 Chromium: 120.0.6099.71
Operating System: Windows NT 10.0.19045

URL (if applicable) where crash occurred:

Can you reproduce this crash? 
Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Attempt to import Passwords from Microsoft Edge (bookmarks, history, etc work fine).
2. Brave crashes.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/332e0800-8bde-260b-0000-000000000000

**Comment by thickpilk** [comment] 2023-12-10 04:56
I got around it by exporting a CSV from Edge, and importing that. This worked fine, once I found out where the option to import via CSV was.

**Comment by Sp0kzz** [comment] 2023-12-10 12:50
my Brave is crashing whenever i click "cookies and site data". thinking about going back to Chrome this ain't worth it

**Comment by bsclifton** [comment] 2023-12-12 20:36
This should be a duplicate of https://github.com/brave/brave-browser/issues/34822

We have a fix for this and will have a release coming up for 1.61 that fixes this issue in the next few weeks- stay tuned!

**Closed by bsclifton** 2023-12-12 20:36 UTC
