### ISSUE TITLE
[Android] Add `Logged out` toast notification in Rewards panel when user goes into `Logged out` state

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20603] opened 2022-01-20 17:50 UTC
## Description

When user is verified with a custodian and then their access token expires (for example), they are moved into the `Logged out` state. We should show a toast notification indicating this to the user like we do on desktop. That is, every time the user transitions into the logged out state, be sure to show them this toast notification. 

![image](https://user-images.githubusercontent.com/11497541/150394325-e13b8379-f415-4926-b68a-fd052d81a57f.png)

**Comment by LaurenWags** [comment] 2022-01-20 18:14
duplicate of https://github.com/brave/brave-browser/issues/9576#issuecomment-1002138214?

**Closed** 2022-12-06 14:17 UTC
Labels: feature/rewards, priority/P3, QA/Yes, OS/Android, rewards-2.0, parity

**Comment by stephendonner** [comment] 2023-01-26 02:07
## Verification `IN-PROGRESS` using `Brave` `1.48.140` on `Google Pixel XL` (`arm64`) running `Android 9`

### Shared steps:


### `Uphold` - `PASSED`
<details>

example | example | example | example | example | example
---------|---------|----------|----------|----------|---------
![Screenshot_20230125-175005](https://user-images.githubusercontent.com/387249/214741235-9d2fce8b-2816-4f4c-8a55-ed5b895fe1af.png) | <img width="1312" alt="Screen Shot 2023-01-25 at 5 51 57 PM" src="https://user-images.githubusercontent.com/387249/214740698-b74de3ac-456f-4244-bbe8-5fdfe0e3caa3.png"> | ![Screenshot_20230125-175228](https://user-images.githubusercontent.com/387249/214741315-aa52f8fe-2a9f-4df2-936c-f374fff8d89b.png) | ![Screenshot_20230125-175312](https://user-images.githubusercontent.com/387249/214741341-5f122dc5-aa66-4719-96a8-676efeb024cf.png) | ![Screenshot_20230125-175727](https://user-images.githubusercontent.com/387249/214741343-408cc29a-c732-406f-a5a3-0efa21a6e6b2.png)

</details>

### `Gemini` - `PENDING`
<details>

</details>

### `bitFlyer` - `PENDING`
<details>

</details>
