### ISSUE TITLE
Extreme CPU usage on MacOS

### ISSUE THREAD

**Issue by SephReed** [brave/brave-browser#8901] opened 2020-03-28 03:12 UTC
## Description 
Brave Brave Helper, not the renderer, is using 100% CPU with no tabs open.  Just the landing screen.

![Screen Shot 2020-03-27 at 10 08 18 PM](https://user-images.githubusercontent.com/14002040/77813558-94515a00-7077-11ea-9877-0579e11ac088.png)
<img width="1259" alt="Screen Shot 2020-03-27 at 10 08 33 PM" src="https://user-images.githubusercontent.com/14002040/77813560-95828700-7077-11ea-91a9-666d0244c42b.png">

## Steps to Reproduce
Open browser. 

## Actual result:
Uses 100% CPU.  Fan goes into full blast.

## Expected result:
Should use almost no CPU.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)

```
Brave	1.5.112 Chromium: 80.0.3987.132 (Official Build) (64-bit)
Revision	fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS	macOS Version 10.14.3 (Build 18D109)
JavaScript	V8 8.0.426.26
Flash	32.0.0.303 /Library/Internet Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,WebXR,VideoPlaybackQuality,NotificationTriggers,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,AudioServiceOutOfProcess,SmsReceiver,WebXrGamepadModule --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/seph-play/Library/Application Support/BraveSoftware/Brave-Browser/Default
```

## Miscellaneous Information:

Is there a way to see a little deeper into Brave?  I'd like to know what processes it's doing that take so much.  Like a task manager for the browser itself.  These things are OS's anyways.

**Comment by rebron** [comment] 2020-03-28 03:26
<img width="751" alt="Screen Shot 2020-03-27 at 8 24 06 PM" src="https://user-images.githubusercontent.com/5951041/77813826-eccd2b00-7068-11ea-9502-91930a12a600.png">

There's a task manager in the more tools section off the menu. If you can update to 1.5.115, we believe we fixed th issue with this fix #8779

**Comment by kjozwiak** [comment] 2020-03-28 21:04
@SephReed if you're still having issues with the `1.5.115` which is the latest build, you might be running into https://github.com/brave/brave-browser/issues/8846.

If you run through the info that @rebron provided via https://github.com/brave/brave-browser/issues/8901#issuecomment-605387854, let us know which service/tab is the one that's causing the spikes. If you notice it's `Utility: BAT Ledger Service`, it's related to https://github.com/brave/brave-browser/issues/8846.

**Comment by SephReed** [comment] 2020-04-01 18:33
It is the BAT ledger Service

**Comment by bsclifton** [comment] 2020-04-01 18:36
Awesome! Thanks for confirming 😄 I'll close this as a duplicate of https://github.com/brave/brave-browser/issues/8846

**Closed by bsclifton** 2020-04-01 18:36 UTC
Labels: bug, needs-more-info, perf
