### ISSUE TITLE
in beta version a text in configuration is truncated in italian translation

### ISSUE THREAD

**Issue by tortino** [brave/brave-browser#17018] opened 2021-07-18 15:42 UTC
## Description 

the beta version has a text truncated in the configuration page.
the stable version is not truncated.

![image](https://user-images.githubusercontent.com/26486758/126073401-c80fc074-40a8-4ef4-94e2-7facb96813b3.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment] 2021-07-22 14:56
Thanks @tortino for the report. Closing as dupe of https://github.com/brave/brave-browser/issues/17109 as it has more information and additional steps.

**Closed by rebron** 2021-07-22 14:56 UTC
Labels: OS/Desktop, l10n, priority/P2
