### ISSUE TITLE
Filecoin Receiving account is not shown in panel 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28229] opened 2023-02-02 07:31 UTC
## Description 

Filecoin Receiving account is not shown in panel 

## Steps to Reproduce

   1. Initiate a Filecoin send transaction
   2. Click on review order
   3. Panel opens but doesn't list the receiving address

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/216259562-a605845f-ae54-4678-9ee3-abc9d0dac5fd.png)

## Expected result:
Should show the receiving address

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @cypt4

**Comment by josheleonard** [comment] 2023-02-03 20:39
regression caused by:
https://github.com/brave/brave-core/pull/15891/files#diff-db0841fffaec0c55469ca8bec60514e543e426e12ab0b47df32b96fba0d7af68R178

**Comment by kjozwiak** [comment] 2023-02-06 04:13
Closing as the above was fixed via https://github.com/brave/brave-core/pull/17027 which was uplifted/merged into `1.48.x`. The above will require `1.48.157` or higher for `1.48.x` verification 👍

**Closed by kjozwiak** 2023-02-06 04:13 UTC
Labels: bug, priority/P2, QA/Yes, release-notes/exclude, regression, feature/web3/wallet, OS/Desktop, feature/web3/wallet/filecoin

**Comment by srirambv** [comment] 2023-02-06 12:42
Verification passed on 

Brave | 1.48.157 Chromium: 110.0.5481.77 (Official Build) (64-bit)
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | Windows 11 Version 22H2 (Build 22621.1105)

- Verified steps from issue description and [brave/brave-core#17027](https://github.com/brave/brave-core/pull/17027)
- Verified Filecoin receiving account is shown on panel and on transaction page
- Verified Solana receiving account is shown on panel and on transaction page

https://user-images.githubusercontent.com/17010094/216974338-9cbf19a0-4d64-4232-88f2-95f99e045c59.mp4
