### ISSUE TITLE
Printing from Google web apps (Docs, Sheets, etc) saves to PDF instead of opening print dialog

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#3694] opened 2019-03-12 20:45 UTC
## Test plan
See https://github.com/brave/brave-core/pull/2342

## Description 

Haven't run into this on any other sites, but when trying to print from Google Docs, Sheets, Slides ,etc, Brave offers to save this file as a PDF, rather than open the print dialog as expected. This happens with Shields up or down and can reproduced on Linux, macOS and Windows 10.

## Steps to Reproduce

   1. Visit google Sheets or any google app in Brave
   2. Try to print sheet content to a home or office printer (or at all)
   3. Follow the in-browser dialog, click `Next` 

## Actual result/Expected

Brave tries to save content as PDF//Should launch print system dialog
![print](https://user-images.githubusercontent.com/3299098/54233833-0685e980-44cb-11e9-9f00-9c04e5de88de.gif)

## Reproduces how often: 

Always 

## Brave version (brave://version info)
Happens on all Brave release channels
v0.60.48
v0.61.13
v0.63.4

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

2 users reporting:
https://community.brave.com/t/brave-browser-problem-google-sheets-internal-print-function-instead-of-opening-printer-downloads-sheet-automatically-as-pdf-bug/33193

**Comment by rebron** [comment] 2019-03-12 20:48
cc: @fmarier pdf related?

**Comment by yodaross** [comment] 2019-03-12 22:00
Can you print as pdf?

**Comment by simonhong** [comment] 2019-03-14 01:29
I'm looking this.

**Comment by simonhong** [comment] 2019-03-14 09:13
There is some difference between chrome and brave when click print button in docs.
After loading https://docs.google.com/presentation/d/1ou3qdnFhKdjR6gKZgDwx3YHDwVUF7y8eoqM3rhErMMQ/edit#slide=id.p, press print button.
Brave and chrome uses different request url.
Chrome: `https://docs.google.com/presentation/d/1ou3qdnFhKdjR6gKZgDwx3YHDwVUF7y8eoqM3rhErMMQ/export/pdf?id=1ou3qdnFhKdjR6gKZgDwx3YHDwVUF7y8eoqM3rhErMMQ&pageid=p&attachment=false`
Brave: `https://docs.google.com/presentation/d/1ou3qdnFhKdjR6gKZgDwx3YHDwVUF7y8eoqM3rhErMMQ/export/pdf?id=1ou3qdnFhKdjR6gKZgDwx3YHDwVUF7y8eoqM3rhErMMQ&pageid=p`

Brave doesn't have `attachment=false` query string.
What makes this difference?

**Comment by simonhong** [comment] 2019-03-14 13:08
I found the root cause of this issue.
Google web apps checks `Chrome PDF Viewer` from `navigator.plugins` list.
<img width="431" alt="Screen Shot 2019-03-14 at 22 05 03" src="https://user-images.githubusercontent.com/6786187/54359176-7059eb00-46a5-11e9-9706-db3c3ef0834c.png">
If list includes `Chrome PDF Viewer`, it attaches more queries.
Brave doesn't have `Chrome PDF Viewer` plugin.

**Comment by simonhong** [comment] 2019-03-14 23:26
Chromium build has same issue and fixed by changing plugin name from `Chromium PDF Viewer` to `Chrome PDF Viewer` in chrome/common/chrome_content_client_constants.cc`.
So, I think absence of this plugin in brave caused this issue.

**Closed** 2019-05-31 07:34 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, extension/PDFJS, priority/P4, release-notes/include, webcompat

**Comment by btlechowski** [comment] 2019-07-30 01:27
Verification passed on

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

Verified test plan from https://github.com/brave/brave-core/pull/2342
PDF printed successfully.

**Comment by andrew-pyle** [comment] 2020-09-08 16:44
Brave user here. I have been printing successfully from Google Sheets in Brave in past months, but today, this issue seems to be happening again. 

Instead of opening the Print dialog window, after the `Next` button, I get a PDF save automatically. Maybe Chromium has made some changes here?

Brave requested this URL after clicking the `Next` button: `https://docs.google.com/spreadsheets/u/1/d/{id-omitted here}/pdf?id={id-omitted here}`.

Clicking this button usually brings up the chrome print dialog.

Mentioning @simonhong because he troubleshot this problem successfully last year.

**Comment by SneakyLeif** [comment] 2020-09-28 14:55
I’m running into the same exact issue. The only way to print a Google Sheets doc to a printer is to first export as PDF, and then print the PDF. Printing the PDF works fine in Brave, though! Very annoying.

Brave version:
Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)

**Comment by linuxturtle** [comment] 2022-02-22 23:27
This issue is still happening for me with the latest build on Linux.

Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)](https://brave.com/latest/)
