### ISSUE TITLE
[Desktop] Brave Shields cannot be disabled through “brave://settings/shields”

### ISSUE THREAD

**Issue by byyxx128** [brave/brave-browser#10565] opened 2020-07-05 03:55 UTC
## Description 
As I wanted to disable Brave Shields for a while, I found setting in `brave://settings/shields`. However, after I set `Allow Ads and Tracking` for every configuration and restart the browser, everything will be restored... I do not why it happened.

## Steps to Reproduce

   1. Launch the browser.
   2. Turn to `brave://settings/shields`
   3. `Allow Ads and Tracking` for every configuration.
   4. Restart the browser.

## Actual result:
Every setting will be restored to default.

## Expected result:
Every setting should be still `Allow Ads and Tracking`.

## Reproduces how often: 
Easily reproduced

## Version/Channel Information:
Can be reproduced on the following versions:
https://github.com/brave/brave-browser/releases/tag/v1.12.72
https://github.com/brave/brave-browser/releases/tag/v1.11.88

- Can you reproduce this issue with the current release?  **Yes**
- Can you reproduce this issue with the beta channel? **Yes**
- Can you reproduce this issue with the dev channel? **Yes**
- Can you reproduce this issue with the nightly channel? **Yes**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
The issue is I cannot disable Brave Shields...🤔

May be related
https://community.brave.com/t/72740

**Comment by rebron** [comment] 2020-08-31 15:28
cc: @Brave-Matt Are we seeing additional reports of Brave Shields settings not sticking?

**Comment by bsclifton** [comment] 2020-09-01 18:40
I believe this is a duplicate of one of the following:
- https://github.com/brave/brave-browser/issues/7163
- https://github.com/brave/brave-browser/issues/5721
- https://github.com/brave/brave-browser/issues/6708

**Comment by mredigonda** [comment] 2020-09-03 19:04
I'm experiencing this problem too in Brave Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit). I try to set "Trackers & ads blocking" to disabled but after restart of the browser that setting gets back to default "standard".

**Comment by bsclifton** [comment] 2021-02-08 07:10
Closing as this issue (as it's captured); it works as expected (testing on `1.19.92`)

If you have touched the shield settings though (clicked to turn off shields on a site, etc) the global settings will be overridden by the local site setting (which is expected behavior). 

The following issues capture problems that are actionable:
- [Global Shields preferences not respected on some sites](https://github.com/brave/brave-browser/issues/7163)
- [Site settings should have a way to be set to default (inherit from global)](https://github.com/brave/brave-browser/issues/5721)

**Closed by bsclifton** 2021-02-08 07:10 UTC
Labels: OS/Desktop, design, feature/global-settings, feature/settings, needs-more-info, priority/P3
