### ISSUE TITLE
Implement Protection from Tracking via TLS Session Reuse 

### ISSUE THREAD

**Issue by DiagonalArg** [brave/brave-browser#2850] opened 2019-01-08 10:57 UTC
It is possible to track based on the [re-use of TLS session information](https://www.theregister.co.uk/2018/10/19/tls_handshake_privacy/).  Firefox has a way to stop this, using [a hidden setting](https://bugzilla.mozilla.org/show_bug.cgi?id=967977).  It does not appear that there is any equivalent in Chromium.  EFF's Privacy Badger has [an issue](https://github.com/EFForg/privacybadger/issues/2164) requesting turning off of session-id reuse.  Could you do this in Brave?

**Comment by diracdeltas** [comment] 2019-01-08 22:21
closing as dupe of https://github.com/brave/brave-browser/issues/1852, please re-open if it's a different issue

**Closed by diracdeltas** 2019-01-08 22:21 UTC

**Comment by DiagonalArg** [comment] 2019-01-08 23:17
Ah, ok.  This is the same as #1852
