### ISSUE TITLE
"Manage Funds" on chrome://rewards doesn't do anything

### ISSUE THREAD

**Issue by echosa** [brave/brave-browser#1172] opened 2018-09-18 13:33 UTC
## Description 
Like the title says, clicking "Manage Funds" on `chrome://rewards` doesn't do anything, except write "panelWithdrawFunds" to the JS console.

## Steps to Reproduce
   1. Go to chrome://rewards
   2. Have a wallet set up
   3. Click "Manage Funds" on the right

## Actual result:
Nothing, except a console write.

## Expected result:
Something more than writing to console. Whatever that link is supposed to do.

## Reproduces how often: 
100%

## Brave version (chrome://version info)
Brave | 0.55.3 Chromium: 70.0.3538.12 (Official Build) dev (64-bit)
Revision | ad61584ca32115f953ce656dd75b44f1c502a75d-refs/branch-heads/3538@{#179}
OS | Mac OS X

### Reproducible on current release:
N/A

**Comment by srirambv** [comment] 2018-09-18 13:47
@NejcZdovc  dupe of #923 ?

**Comment by echosa** [comment] 2018-09-18 13:49
FWIW, the "Add Funds" link works fine, or, at least, it does something (pops up a modal with some deposit options).

**Comment by srirambv** [comment] 2018-09-18 13:55
Rewards is still in development. Here's a list of all rewards related [issues](https://github.com/brave/brave-browser/issues?q=is%3Aissue+is%3Aopen+label%3Afeature%2Frewards)

**Comment by NejcZdovc** [comment] 2018-09-18 14:59
@srirambv yeah this will be implemented as part of 923

**Closed** 2018-09-18 15:12 UTC
