### ISSUE TITLE
Able to send tabs to devices even when tab sync is disabled on one of them

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25475] opened 2022-09-19 10:15 UTC
## Description 
Able to send tabs to devices even when tab sync is disabled on one of them

## Steps to reproduce 

   1. Create sync chain on Android device 1running  1.45.44
   2. Enable all sync items from data preferences
   3. Add a second Android device to the sync chain running 1.443.94 (CR105) and enable all sync items
   4. Send a tab from device 1 to device 2, works fine device 2 gets the tab as notification
   5. Turn off tab sync/history sync from device 2, nothing changes in device 1 still has Sync all enabled
   6. Send a different tab from device 1 to device 2 , still sends the tab to the second device
   7. Quit and relaunch browser on both devices and try to send a different tab from device 1 to device 2, device 2 still receives the open tab
   
## Actual result 
Device 2 still receives even when Open tabs sync is disabled on device 2 

## Expected result
Device 2 should not receive any open tab notification when open tabs sync is disabled on the device

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Not checked
- Can you reproduce this issue with the current Play Store Beta version? Not checked
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
Device 1: Oppo Reno 5 with Android 12 running 1.45.44
Device 2: Samsung Tab A with Android 10 running 1.43.94
  
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @AlexeyBarabash

**Comment by srirambv** [comment] 2022-09-19 10:39
Issue also happens with just Bookmark sync enabled on both devices. 
![image](https://user-images.githubusercontent.com/17010094/191000234-1382d6d2-c208-46c1-9709-c444ced7715c.png)

**Comment by AlexeyBarabash** [comment] 2022-09-19 18:47
I have reproduced the same behavior on the current Stable Chrome `105.0.5195.136`.

**Comment by AlexeyBarabash** [comment] 2022-09-20 10:15
The commit
https://github.com/chromium/chromium/commit/88839da732f9d8bc8bb181d16ef106b18dc531a8
brought such behavior: to send tab from the device A to the device B (A=>B), it is enough only for device B to have `Open tabs` sync type switched on.

And even more:
by default the field `send_tab_to_self_receiving_enabled` is set to true:
https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/sync/device_info_sync_client_impl.cc;l=65;drc=5e23336d543816202a70de6dc6cdf721350adf22;bpv=1;bpt=1

Happened since this commit:
https://github.com/chromium/chromium/commit/41153d8c546533b998a0ccfe3119651e4f7affc5#diff-3ed5be57922886d35586c0841cf19d49904f990bb4f58780b480d885a0321eccR54

More details at
https://chromium-review.googlesource.com/c/chromium/src/+/3483939
https://bugs.chromium.org/p/chromium/issues/detail?id=1299833
 
I had missed this change, but it was done intentionally.
So send tab to self works if two devices are in the sync chain, without regard to any flags or settings.

Closing this issue.

**Closed by AlexeyBarabash** 2022-09-20 10:15 UTC
Labels: bug, feature/sync, QA/Yes, release-notes/exclude, regression, OS/Android
