### ISSUE TITLE
Blocking NTPSI ad through 30-day history does not work

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#17743] opened 2021-08-27 21:07 UTC
Users have another way of blocking NTPSI ads (new tab page customization), but we should determine what to do with blocking NTPSI through 30-day history

## Steps to Reproduce

   1. Follow steps from `Blocked NTP SI ad - Untargeted segment` from https://github.com/brave/internal/issues/794

## Actual result:

Blocking NTPSI ad through 30-day history does not work

## Expected result:
TBD by design

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.29.67 Chromium: 92.0.4515.159 (Official Build) beta (64-bit)
-- | --
Revision | 0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}
OS | Linux

cc @tmancey @jsecretan @rebron @brave/legacy_qa

**Comment by tmancey** [comment] 2022-02-15 19:59
Will be resolved by https://github.com/brave/brave-core/pull/11945

**Comment by tmancey** [comment] 2022-02-15 20:04
Closing as a duplicate of https://github.com/brave/brave-core/pull/11945 as if ads are enabled we will be serving NTP SI ads from the ads library

**Closed by tmancey** 2022-02-15 20:04 UTC
Labels: blocked, feature/ads, OS/Desktop
