### ISSUE TITLE
Add support to adblock for custom remote filter lists 

### ISSUE THREAD

**Issue by superusercode** [brave/brave-browser#8474] opened 2020-02-29 17:42 UTC
## Description 
This was initially intended as part of https://github.com/brave/brave-browser/issues/403#issuecomment-425778061 but is still not possible as of today in nightly. There are language specific lists but the user cannot specify their own (i.e. adguard annoyance).

## Steps to Reproduce

   1.  Go to brave://adblock/
   2.  Cannot add remote filter lists

## Actual result:

![image](https://user-images.githubusercontent.com/60588434/75612371-bbf0e900-5af0-11ea-98ed-4a9ff779feb0.png)

## Expected result:
![image](https://user-images.githubusercontent.com/60588434/75612378-c8754180-5af0-11ea-8ff1-8075b0274754.png)
something like this from ublock origin

## Brave version (brave://version info)

```

Brave | 1.7.30 Chromium: 80.0.3987.122 (Official Build) nightly (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Windows 10 OS Version 1909 (Build 18363.657)
JavaScript | V8 8.0.426.25
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser-Nightly\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --disable-databases --enable-features=WebUIDarkMode,PasswordImport,AutoupgradeMixedContent,PassiveMixedContentWarning,MixedContentSiteSetting,SimplifyHttpsIndicator,DnsOverHttps --disable-features=AllowPopupsDuringPageUnload,VideoPlaybackQuality,AudioServiceOutOfProcess,SmsReceiver,NotificationTriggers,LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser-Nightly\Application\brave.exe
Profile Path | C:\Users\sacha\AppData\Local\BraveSoftware\Brave-Browser-Nightly\User Data\Default
Variations | 5e3a236d-59e286d0
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no

**Comment by rebron** [comment] 2020-04-17 19:43
duplicate of #4891

**Closed by rebron** 2020-04-17 19:43 UTC
Labels: duplicate
