### ISSUE TITLE
AIChat: Fullscreen UI

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#39501] opened 2024-07-01 16:08 UTC
- Wider version of same UX used in Sidebar
- Left-hand collapsible sidebar 
- Option for manually selecting a different model for the conversation
- Blank view includes new Conversation Starters

https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/%F0%9F%94%84-Leo-[IN-PROGRESS]?node-id=15-15519&t=ab48RVF3AIGVH6eS-0

**Comment by petemill** [comment] 2024-11-02 04:28
Duplicate of https://github.com/brave/brave-browser/issues/30554

**Closed by petemill** 2024-11-02 04:28 UTC
Labels: design, QA/Yes, OS/Desktop, browser-ai
