### ISSUE TITLE
The text on the "clear" browsing data button can't be seen clearly

### ISSUE THREAD

**Issue by giwrgosmant** [brave/brave-browser#25290] opened 2022-09-08 13:59 UTC
## Description 
The text on the "clear" browsing data button can't be seen clearly because the orange color of the box overlap it and both are orange, The text inside the box should be other color for better visibility. 
![Brave Delete Button - Text no visibility](https://user-images.githubusercontent.com/51835189/189141219-125b2645-3e29-460c-8389-28faf03826b7.jpg)

## Steps to reproduce 

   1. Settings
   2. Shields & Privacy
   3. Clear/Delete Browsing Data

## Actual result 
The text on the "clear" button can't be seen clearly because the orange color of the box overlap it and both are orange,

## Expected result
The text inside the box should be other color for better visibility.

## Issue reproduces how often 
Always.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Haven't tried.
- Can you reproduce this issue with the current Play Store Nightly version? Havent't tried.

## Device details
   - Install type (ARM, x86): ARM64
   - Device type (Phone, Tablet, Phablet): Phone - POCO F1 (custom ROM)
   - Android version: 12L
   
## Brave version
Brave 1.43.90, Chromium 105.0.5195.102

**Comment by srirambv** [comment] 2022-09-13 17:30
Dupe of #25225. This should be release as part of the next HF

**Closed by srirambv** 2022-09-13 17:30 UTC
Labels: OS/Android
