### ISSUE TITLE
Cannot automatically backup/restore

### ISSUE THREAD

**Issue by InteXX** [brave/brave-browser#4320] opened 2019-05-06 15:19 UTC
There's only one thing that's stopping me from switching to Brave: the inability to automatically back up and restore passwords/settings/history/bookmarks.

This capability is absolutely critical in any modern operating environment. Data disasters do happen; operating systems do get reinstalled.

I suggest assigning this issue a high priority.

**Comment by rebron** [comment] 2019-05-10 16:09
Closing. Dupe of previous issue filed.

**Closed by rebron** 2019-05-10 16:09 UTC
Labels: closed/duplicate

**Comment by InteXX** [comment] 2019-05-10 16:42
@rebron 

Do you have a link to the previous issue? I looked before opening this one, but I didn't find any.

**Comment by bsclifton** [comment] 2019-05-13 06:34
@InteXX sure - the duplicate link is https://github.com/brave/brave-browser/issues/4295
