### ISSUE TITLE
[Desktop] Brave Ads - major UX problem

### ISSUE THREAD

**Issue by tjcrowder** [brave/brave-browser#6913] opened 2019-11-14 09:40 UTC
## Description 

Brave ads have a **major** UX issue. I pretty much instantly turned them off. But I don't want to; Brave, Brave Ads, and Brave Rewards are great ideas and I want them to succeed, I want to support them, I want to use them, and I want to recommend Brave and Brave Ads to other people. This UX is a huge barrier to that -- not just to *my* using them, I think the UX will turn off a lot of people and stand in the way of Brave Ads' success.

## Steps to Reproduce

   1. Turn on Brave Ads in Rewards Settings
   2. Wait for an ad to appear

## Actual result:

A pop-up ad appears through what looks like a system-level notification:

![rewards-ads](https://user-images.githubusercontent.com/27634/68843853-b649d180-06c0-11ea-99be-97ac8d754135.png)

Problems:

* There's nothing to indicate it's a Brave Ad. When I first did this some weeks ago, I thought I had malware on my system. I tweeted @Brave about it a [couple](https://twitter.com/tjcrowder/status/1183382066051895299) of [times](https://twitter.com/tjcrowder/status/1189129493199360002) at the time, never got a response. It has the Brave logo, but nothing identifying it as an ad. The Brave logo is used on basically all Brave windows.
* You have to actively dismiss it. It doesn't just go away. Or if it does, it takes **far** too long to do so.
* It's unstyled.

## Expected result:

* Clearly identified as a Brave Ad.
* Appearing *within* the UI of the browser, not as a popup outside the window. It wouldn't need to be dismissed and could stay there for a while. There may need to be options for where ads should appear. Ideas for options:
    * An ad bar under or above the bookmarks bar
    * An ad bar replacing the bookmarks bar; when you reach up to it, the bookmarks bar could slide down under it (or you could dismiss the ad)
    * A side bar within the main browser window
    * A side bar that appears next to the main browser window, but very clearly attached to it
    * A pop-up, but a good one
* Styled in an attractive way, perhaps even with a link to the thing being advertised.

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

Brave | 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)

Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}

OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?

Yes.

- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

This seems to be designed behavior, so I haven't tried them.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?

N/A

- Does the issue resolve itself when disabling Brave Rewards?

Well, disabling ads would do it, but... :-)

- Is the issue reproducible on the latest version of Chrome? 

N/A

**Comment by NejcZdovc** [comment] 2019-11-14 09:48
cc @jsecretan @davidtemkin @mandar-brave

**Comment by szaimen** [comment] 2019-11-14 16:34
Actually I kind of like this idea.
Notifications aren't the best way to show ads in a UX-matter. 
If you want to place ads prominently, for me the best place would be the New Tab Page.
I actually think the NTP would have been the best place for showing ads from the beginning on.

Then every time you open a new tab (and at least I am doing this very often) you will see an advertisement but aren't in risk of clicking on it accidentally in comparison to the current situation where this happens really often in my experience.
Also then you will not get distracted by these notifications. if your are not using brave and it is running in the background or if you are staying in a web app a long time and want to get work done.

The best solution for this kind of problem would be, if you would enable the user to decide how ads are shown to him/her. So then you could decide if you want e.g. ads in notifications, on the NTP, maybe as popup bubbles while using brave etc.

**Comment by mpaluta** [comment] 2020-01-10 06:12
I find Brave ads more invasive than traditional ads embedded on a web page. Notifications are invasive _by design_.

It is strange to me that Brave has decided to deliver ads via pop up notifications, both on desktop and mobile. Both styles are highly invasive and distracting. I have turned them off until a better solution is created.

@szaimen I love the new tab idea.

**Comment by tmancey** [comment] 2020-05-29 08:43
Blocked until https://github.com/brave/brave-browser/issues/9592 is implemented

**Comment by tmancey** [comment] 2020-10-22 12:33
Closing issue as superseded by https://github.com/brave/brave-browser/issues/9592

**Closed by tmancey** 2020-10-22 12:33 UTC
Labels: OS/Desktop, closed/wontfix, feature/ads, needs-discussion, suggestion

**Comment by tjcrowder** [comment] 2021-05-21 13:22
@tmancey - How do custom notifications solve the problem I've described in this thread? I want to know so I can turn on Brave Ads, but what I see in [screenshots like this](https://github.com/brave/brave-browser/issues/9592#issuecomment-819725033) doesn't look like an improvement. Hopefully I'm just missing something. Thanks!

**Comment by tmancey** [comment] 2021-05-21 14:47
@tjcrowder The ads timeout after 2 minutes. The top-right of the ad notification has a BAT icon to show they are a Brave Ad. Are you running release, beta, or nightly channel build? Thanks

**Comment by tjcrowder** [comment] 2021-05-21 14:58
@tmancey - I'm running release.

Well that's **very** disappointing, I was hoping that the changes would address this issue, but they miss **two-thirds** of the things I flagged up 18 months ago. Please consider reopening this. I won't be enabling ads if they show up as system notifications and I suspect I'm very much not alone. That's just frankly not where they should be. As I said 18 months ago, they should be _within_ the UI of the browser.

I really like what Brave is trying to do and what it stands for, but this UI completely lets the vision down.

Thanks,

-- T.J.

**Comment by tmancey** [comment] 2021-05-21 16:38
@tjcrowder Thank you for your other comments, I will pass them on to the design team. I would recommend checking out our new custom ad notifications in Nightly. You can reposition the ad notifications by dragging with your mouse.
