### ISSUE TITLE
Having local IPFS installed causes crash on certain pages (ex: when scrolling on MDN)

### ISSUE THREAD

**Issue by ovo-Tim** [brave/brave-browser#40102] opened 2024-07-30 07:49 UTC
### Test plan
See https://github.com/brave/brave-browser/issues/40102#issuecomment-2272197145

### Description

A crash is certain to occur when attempting to open [this MDN page](https://developer.mozilla.org/zh-CN/docs/Web/CSS/flex). This won't happen on chromium.

Here are terminal output:
```
[0730/153156.673602:ERROR:file_io_posix.cc(153)] open /home/tim/.config/BraveSoftware/Brave-Browser/Crash Reports/pending/cf3f1adc-3672-48c9-8f27-6b328ed43ab4.lock: File exists (17)
[0730/153156.673658:ERROR:file_io_posix.cc(153)] open /home/tim/.config/BraveSoftware/Brave-Browser/Crash Reports/pending/bba62604-c713-4732-8cf6-ee76e571e97f.lock: File exists (17)
[0730/153156.673668:ERROR:file_io_posix.cc(153)] open /home/tim/.config/BraveSoftware/Brave-Browser/Crash Reports/pending/4b8b4eaf-ea7a-4060-89fa-a4ea7dd0ba37.lock: File exists (17)
[0730/153200.661471:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0730/153200.661612:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0730/153200.661675:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0730/153200.662674:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0730/153200.663734:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0730/153200.668309:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0730/153200.668448:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0730/153200.669609:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0730/153200.669835:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0730/153200.670297:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0730/153200.670644:ERROR:process_memory_range.cc(75)] read out of range
[0730/153200.670876:ERROR:process_memory_range.cc(75)] read out of range
[0730/153200.678094:ERROR:process_memory_range.cc(75)] read out of range
[0730/153200.678109:ERROR:process_memory_range.cc(75)] read out of range
[0730/153200.678596:ERROR:process_memory_range.cc(75)] read out of range
[0730/153200.678604:ERROR:process_memory_range.cc(75)] read out of range
[0730/153200.681958:ERROR:directory_reader_posix.cc(43)] opendir /home/tim/.config/BraveSoftware/Brave-Browser/Crash Reports/attachments/7525a91f-03b4-43f6-aefb-454750934bd2: No such file or directory (2)
[72332:72339:0730/153202.696365:ERROR:ssl_client_socket_impl.cc(883)] handshake failed; returned -1, SSL error code 1, net_error -3
[72332:72339:0730/153202.697459:ERROR:ssl_client_socket_impl.cc(883)] handshake failed; returned -1, SSL error code 1, net_error -3
[1]    72282 trace trap (core dumped)  brave
```

### Steps to reproduce

Simply open [this MDN page](https://developer.mozilla.org/zh-CN/docs/Web/CSS/flex)

### Actual result

Crash

### Expected result

Not crash

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave	1.68.128 Chromium: 127.0.6533.73 (release version) （64 位） 
Revision	800676fd9ede2eb4174bac98c186e53749c7201f
OS	Linux

```
                   -`                 
                  .o+`                 tim@TimTu-Arch
                 `ooo/                 OS: Arch Linux 
                `+oooo:                Kernel: x86_64 Linux 6.10.1-arch1-1
               `+oooooo:               Uptime: 4h 52m
               -+oooooo+:              Packages: 1673
             `/:-:++oooo+:             Shell: zsh 5.9
            `/++++/+++++++:            Resolution: 2560x1600
           `/++++++++++++++:           DE: KDE
          `/+++ooooooooooooo/`         WM: KWin
         ./ooosssso++osssssso+`        GTK Theme: Breeze-Dark [GTK2], Breeze [GTK3]
        .oossssso-````/ossssss+`       Icon Theme: breeze
       -osssssso.      :ssssssso.      Disk: 177G / 806G (24%)
      :osssssss/        osssso+++.     CPU: AMD Ryzen 7 6800H with Radeon Graphics @ 16x 4.785GHz
     /ossssssss/        +ssssooo/-     GPU: AMD Radeon 680M (radeonsi, rembrandt, LLVM 18.1.8, DRM 3.57, 6.10.1-arch1-1)
   `/ossssso+/:-        -:/+osssso+-   RAM: 19942MiB / 30805MiB
  `+sso+:-`                 `.-/+oso: 
 `++:.                           `-/+/
 .`                                 `/
```

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by nienow** [comment] 2024-08-01 03:50
Recently, it crashes for me on every MDN page

**Comment by bsclifton** [comment] 2024-08-01 07:22
@nienow are you on Linux also?

**Comment by zenparsing** [comment] 2024-08-01 11:11
@bsclifton I'm getting this as well

macOS
1.68.134 Chromium: 127.0.6533.88 (Official Build) (x86_64) 

Crash ID: [f7e40200-ea85-600c-0000-000000000000](https://brave.sp.backtrace.io/p/brave/debug?filters=JTVCJTVCJTIyX2RlbGV0ZWQlMjIlMkMlMjJlcXVhbCUyMiUyQyUyMjAlMjIlNUQlMkMlNUIlMjJfcnhpZCUyMiUyQyUyMmVxdWFsJTIyJTJDJTIyZjdlNDAyMDAtZWE4NS02MDBjLTAwMDAtMDAwMDAwMDAwMDAwJTIyJTVEJTVE&fingerprint=b4c0d4f838dab810e6a34b6a50aa08e4bb97fc346f87fff21aaabbffed82239a&debug=(%22816a2a0%22,0,0))

```
[ 00 ] base::OnceCallback<void (unsigned long long)>::Run(unsigned long long) && ( immediate_crash.h:179 )
[ 01 ] ChromeBrowsingDataRemoverDelegate::OnTaskComplete(ChromeBrowsingDataRemoverDelegate::TracingDataType, unsigned long long, base::TimeTicks, bool) ( chrome_browsing_data_remover_delegate.cc:1506 )
[ 02 ] base::OnceCallback<void ()>::Run() && ( callback.h:156 )
[ 03 ] extensions::(anonymous namespace)::ValidateCrxHelper::FinishOnUIThread() ( startup_helper.cc:135 )
[ 04 ] void base::internal::DecayedFunctorTraits<void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&>::Invoke<void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay>(void (*&&)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&) ( bind_internal.h:671 )
[ 05 ] void base::internal::InvokeHelper<false, base::internal::FunctorTraits<void (*&&)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&>, void, 0ul>::MakeItSo<void (*)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>>(void (*&&)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>&&) ( bind_internal.h:930 )
[ 06 ] void base::internal::Invoker<base::internal::FunctorTraits<void (*&&)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&>, base::internal::BindState<false, true, false, void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay>, void ()>::RunImpl<void (*)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>, 0ul>(void (*&&)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>&&, std::__Cr::integer_sequence<unsigned long, 0ul>) ( bind_internal.h:1067 )
[ 07 ] base::internal::Invoker<base::internal::FunctorTraits<void (*&&)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&>, base::internal::BindState<false, true, false, void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay>, void ()>::RunOnce(base::internal::BindStateBase*) ( bind_internal.h:980 )
[ 08 ] base::OnceCallback<void ()>::Run() && ( callback.h:156 )
[ 09 ] base::TaskAnnotator::RunTaskImpl(base::PendingTask&) ( task_annotator.cc:203 )
[ 10 ] void base::TaskAnnotator::RunTask<base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*)::$_3>(perfetto::StaticString, base::PendingTask&, base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*)::$_3&&) ( task_annotator.h:90 )
[ 11 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) ( thread_controller_with_message_pump_impl.cc:484 )
[ 12 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:346 )
[ 13 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:0 )
[ 14 ] base::MessagePumpCFRunLoopBase::RunWork() ( message_pump_apple.mm:449 )
[ 15 ] invocation function for block in base::MessagePumpCFRunLoopBase::RunWorkSource(void*) ( message_pump_apple.mm:421 )
[ 16 ] base::apple::CallWithEHFrame(void () block_pointer)
[ 17 ] base::MessagePumpCFRunLoopBase::RunWorkSource(void*) ( message_pump_apple.mm:420 )
[ 18 ] 0x7ff81625f087
[ 19 ] 0x7ff81625f029
[ 20 ] 0x7ff81625edf4
[ 21 ] 0x7ff81625da71
[ 22 ] 0x7ff81625d112
[ 23 ] 0x7ff820c76a09
[ 24 ] 0x7ff820c76816
[ 25 ] 0x7ff820c76561
[ 26 ] 0x7ff8198cdc61
[ 27 ] 0x7ff81a1e1dc0
[ 28 ] __71-[BrowserCrApplication nextEventMatchingMask:untilDate:inMode:dequeue:]_block_invoke ( chrome_browser_application_mac.mm:335 )
[ 29 ] base::apple::CallWithEHFrame(void () block_pointer)
[ 30 ] -[BrowserCrApplication nextEventMatchingMask:untilDate:inMode:dequeue:] ( chrome_browser_application_mac.mm:334 )
[ 31 ] 0x7ff8198bf075
[ 32 ] base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*) ( message_pump_apple.mm:807 )
[ 33 ] base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) ( message_pump_apple.mm:161 )
[ 34 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ( thread_controller_with_message_pump_impl.cc:654 )
[ 35 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ( thread_controller_with_message_pump_impl.cc:0 )
[ 36 ] base::RunLoop::Run(base::Location const&) ( run_loop.cc:134 )
[ 37 ] content::BrowserMainLoop::RunMainMessageLoop() ( browser_main_loop.cc:1085 )
[ 38 ] content::BrowserMainRunnerImpl::Run() ( browser_main_runner_impl.cc:160 )
[ 39 ] content::BrowserMain(content::MainFunctionParams) ( browser_main.cc:34 )
[ 40 ] content::RunBrowserProcessMain(content::MainFunctionParams, content::ContentMainDelegate*) ( content_main_runner_impl.cc:721 )
[ 41 ] content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams, bool) ( content_main_runner_impl.cc:1302 )
[ 42 ] content::ContentMainRunnerImpl::Run() ( content_main_runner_impl.cc:1154 )
[ 43 ] content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) ( content_main.cc:332 )
[ 44 ] content::ContentMain(content::ContentMainParams) ( content_main.cc:345 )
[ 45 ] ChromeMain ( chrome_main.cc:192 )
[ 46 ] main ( chrome_exe_main_mac.cc:217 )
[ 47 ] 0x7ff815df6366
```

It appears that `ChromeBrowsingDataRemoverDelegate` is attempting to execute an empty `OnceCallback`. We do patch that class quite a bit. I suspect something changed in CR127 that our patch isn't working well with.

**Comment by nienow** [comment] 2024-08-01 18:18
> @nienow are you on Linux also?

I'm on Windows 11.
Version 1.68.134 Chromium: 127.0.6533.88

**Comment by mio9** [comment] 2024-08-02 06:24
Same issue exists on macos as well, [Version 1.68.134 Chromium: 127.0.6533.88 (Official Build) (arm64)](https://brave.com/latest/). Crashed my progress together with it, not amusing

**Comment by mio9** [comment] 2024-08-02 06:27
Follow up, the issue seems to be fixed on Nightly builds, we could use that as a dirty workaround for now

**Comment by bsclifton** [comment] 2024-08-06 05:25
Seems this is fixed in Beta and Nightly... 

I am not able to reproduce but given that @zenparsing can and a fresh profile worked, I suspect this might be due to specific settings. We do have overrides in the code for areas related to where the crash is happening. I tried turning on some settings (clear data on exit, etc) but no luck yet.

**Comment by bsclifton** [comment] 2024-08-06 21:38
OK narrowed this down - it's IPFS related. I believe in Beta and Nightly we removed the IPFS local node (cc: @vadimstruts)  via https://github.com/brave/brave-core/pull/23808

Here are the steps that someone can use to reproduce the issue
1. Fresh profile
2. Go to brave://settings/web3
3. Make sure toggle `IPFS Companion` is ENABLED and install the extension when prompted
4. Extension install page comes up
    - If you don't already have kubo installed, install it
    - pick `Use a Brave local IPFS node`
    - verify IPFS starts up
5. Visit brave://settings/web3 again
6. Make sure toggle `Always start an IPFS node on browser startup?` is ENABLED
7. Close all open tabs and close Brave
8. Re-open Brave
9. Open https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key in a new tab
10. Scroll up and down the page

**Comment by bsclifton** [comment] 2024-08-07 20:27
For folks experiencing this issue - please go to brave://flags/#brave-ipfs and set this to `Disabled`. That should get you in good shape! 1.69 (Beta) and higher have the fix

**Comment by bsclifton** [comment] 2024-08-07 21:41
OK folks - going to close this issue as `wontfix`. 

As noted, it's already fixed on Beta (1.69) and Nightly (1.70). You can also work-around the issue by going to `brave://flags/#brave-ipfs` and setting value to `Disabled`.

We also have the opportunity to use our variation server to push a fix our remotely - by making a study that disables the feature for folks on Release channel (1.68). cc: @rebron to follow up on that

**Comment by bsclifton** [comment] 2024-08-08 21:13
Re-opening after @vadimstruts prepared a fix 😄

**Comment by kjozwiak** [comment] 2024-08-13 18:48
The above requires `1.68.141` or higher for `1.68.x` verification 👍

**Closed** 2024-08-13 18:47 UTC
Labels: crash, priority/P2, QA/Yes, release-notes/include, QA/Test-Plan-Specified, feature/web3/ipfs, OS/Desktop

**Comment by GeetaSarvadnya** [comment] 2024-08-14 08:22
Verification INPROGRESS on

```
Brave | 1.68.141 Chromium: 127.0.6533.120 (Official Build) (64-bit)
-- | --
Revision | b3f23500b575d50584510ea1814ef440d30741a8
OS | Windows 10 Version 22H2 (Build 19045.4651)

```
Verified the test plan from https://github.com/brave/brave-browser/issues/40102#issuecomment-2272197145 and Reproduced the issue on `1.68.137 Chromium: 127.0.6533.100`
![Brave crash](https://github.com/user-attachments/assets/d67937db-3a02-49be-adc1-37889398400c)

Upgraded the profile to `1.68.141 Chromium: 127.0.6533.120` and ensured that brave didn't crash when scroll up/down the page https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key
