### ISSUE TITLE
Removed Profile Returning

### ISSUE THREAD

**Issue by shortstuffsushi** [brave/brave-browser#7900] opened 2020-01-24 16:40 UTC
## Description 
At some point a while back, a second profile appeared when I opened my Brave browser. It isn't one that I added, and I'm not sure what would have caused it. I noticed because suddenly I had the little profile icon both on the application icon and right of my url bar. I didn't want this, so I removed the profile... seemed to work, the additional profile stuff was removed and the UI was cleaned up.

Unfortunately, every time I restart the browser, that profile is coming back, and I have to take the same action each time to remove it. Not sure where this extra one is coming from, or how to keep it from returning.

## Steps to Reproduce

   1. ???
   2. Have second profile
   3. Remove second profile
   4. Close browser
   5. Relaunch browser

## Actual result:
Second profile is returned.

## Expected result:
Second profile should not return

## Reproduces how often: 
This happens every time for me, but I'm not sure it would for others

## Version/Channel Information:
I am running version - 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)

I've not tried any of the other builds.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment] 2020-03-13 17:14
duplicate of #4599

**Closed by rebron** 2020-03-13 17:14 UTC
Labels: duplicate
