### ISSUE TITLE
Detaching Tab groups with `tab-groups-save` flag in incognito ends in crash

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#31431] opened 2023-07-04 00:09 UTC
## Description 

I don't know if it is a similar upstream bug from Chromium like this issue https://github.com/brave/brave-browser/issues/29938, but behaves the same, it works fine in normal windows, but detaching group stabs (to move them to another window or something) ends in a crash.

## Steps to Reproduce

   1. Create tab group
   2. try to detach it
   3. Crashes.

## Normal Window 
![brave_2023-07-03_18-05-53](https://github.com/brave/brave-browser/assets/122518587/fa7c7c44-7c8a-4862-b8af-5db991d4698b)

## InPrivate Window
![brave_2023-07-03_18-06-19](https://github.com/brave/brave-browser/assets/122518587/0728c04c-84b4-4a8a-a425-caa417c03adc)

## Reproduces how often: 

Always

## Brave version (brave://version info)
1.55.93 Chromium: 115.0.5790.56 (Official Build) nightly (64-bit) 

## Operating System
Windows 11 22H2

**Comment by rebron** [comment] 2023-07-05 23:23
cc: @sangwoo108 I think this could be a dupe of https://github.com/brave/brave-browser/issues/29938

**Comment by iefremov** [comment] 2024-06-14 16:22
stale

**Closed by iefremov** 2024-06-14 16:22 UTC
Labels: crash, needs-more-info, OS/Desktop, feature/vertical-tabs
