### ISSUE TITLE
Rewards NTP widget can be slow to show status immediately after enabling rewards

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#8698] opened 2020-03-16 01:15 UTC
## Description 

After enabling rewards with fresh profile, NTP shows proper rewards widget(`Estimated earnings...`).
Some seconds later, it back to display (`Turn on Brave Rewards...`).
After reloading NTP many times, I can see normal widgets again but reverted to default widget again.

## Steps to Reproduce

   1. Start Nightly(`1.8.11`) with fresh profile
   2. Enable rewards and load new tab
   3. Check rewards widget shows properly

## Actual result:

Rewards widget is back to default state(rewards off) in NTP after some seconds later

## Expected result:
Rewards widget should not show default contents after rewards is enabled

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Version 1.8.11 Chromium: 80.0.3987.132 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not tested
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the dev channel? Not tested
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Failed to upload gif file due to size limitation. 
See https://bravesoftware.slack.com/archives/C7VLGSR55/p1584320070272400

**Comment by bsclifton** [comment] 2020-03-16 01:17
Curious if this is related to https://github.com/brave/brave-core/pull/4911

cc: @ryanml

**Comment by bsclifton** [comment] 2020-03-16 17:53
Tested using the [build bisect tool](https://github.com/brave/brave-browser/wiki/Build-Bisect-Tool) and this appears to have been introduced AFTER 1.8.10. Seems to be something in 1.8.11

**Comment by bsclifton** [comment] 2020-03-16 20:07
Re-ran the tool; was able to narrow it down properly to 1.7.51. Caused by one of the following:
- https://github.com/brave/brave-core/pull/4607 Implement purchase intent classifier for brave ads 8047
- https://github.com/brave/brave-core/pull/4805 [Android] Ad notification shows up even when Brave-Beta is not running #7917
- https://github.com/brave/brave-core/pull/4870 Simplifies tip flow from service to shared lib
- https://github.com/brave/brave-core/pull/4865 [Android] Update onboarding with ads region changes

**Comment by bsclifton** [comment] 2020-03-16 21:28
Issue doesn't appear to be related to code after more investigation. It seems the new tab page widget is slow to update sometimes. If you wait there long enough, it will change state into the one that shows the balances. This can take a few seconds sometimes

**Comment by bsclifton** [comment] 2020-03-16 21:34
@simonhong can you try this again?

**Comment by simonhong** [comment] 2020-03-17 00:16
@bsclifton  My issue was not about slowness of widget state updating.
I had same issue with @karenkliu 's issue (https://github.com/brave/brave-browser/issues/8711).
and that bug seems disappeared with latest nightly :)

**Comment by bsclifton** [comment] 2020-03-17 15:57
Perfect! I'll go ahead and close this then 😄

**Closed by bsclifton** 2020-03-17 15:57 UTC
Labels: feature/new-tab, feature/rewards, priority/P5
