### ISSUE TITLE
Profile folder copying issue on windows 10

### ISSUE THREAD

**Issue by erotavlas-turbo** [brave/brave-browser#7528] opened 2019-12-27 17:00 UTC
Hi,

I found an issue about profile folder on windows 10 1909 64 bit. By copying just Default folder or the entire Brave-Browser folder does not work. Some preference are stored (theme, some settings) while other not (extensions). When I enter into settings, brave says that it found wrong configuration and ask me if I want to restore the default settings.
The same works well under GNU/linux.

1. Copy the profile folder Brave-Browser/User Data/Default or the entire folder Brave-Browser.
2. On different machine, replace the folder with Brave-Browser/User Data/Default or Brave-Browser.
3. Start brave.

The issue is always reproducible. Brave Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)

**Comment by srirambv** [comment] 2019-12-27 17:56
Are you copying folder from Windows - Windows or Windows - Linux or Linux - Windows?

**Comment by erotavlas-turbo** [comment] 2019-12-27 18:16
> Are you copying folder from Windows - Windows or Windows - Linux or Linux - Windows?

Of course, the OS is the same.

**Comment by srirambv** [comment] 2019-12-27 18:21
Can you mention which platform you are copying from and to which platform you want to use it?

**Comment by erotavlas-turbo** [comment] 2019-12-27 20:10
> Can you mention which platform you are copying from and to which platform you want to use it?

As I wrote in my first message. By coping the profile folder from GNU/linux to GNU/linux (ubuntu and debian) it works while by copying the profile folder from windows 10 1909 to windows 10 1909 does not work with the problems reported in the first message.

**Comment by bsclifton** [comment] 2019-12-30 16:59
I wonder if this is due to the user owning the files on Windows

@erotavlas-turbo is the original user in the Administrators group? and maybe the 2nd user isn't?

I'll give this a shot and try to reproduce

**Comment by GeetaSarvadnya** [comment] 2019-12-30 17:24
I have copied the profile folder from Windows 10 to Windows 8 - It's working as expected (tabs/settings/bookmarks data is restored correctly)

**Comment by bsclifton** [comment] 2019-12-30 18:02
I was unable to repro on Windows 10 (pro edition). I had my main user and a non-admin user, "Bubba". I copied my profile from %USERPROFILE%\AppData\Local\BraveSoftware\Brave-Browser\ and then switched to the Bubba account. It loaded as expected, including the extensions

@erotavlas-turbo what extensions are you using? Do those extensions require authentication (ex: you need to login?)

**Comment by srirambv** [comment] 2019-12-30 18:12
If the profile is copied and when launched a new profile is created then there is something wrong in the path of the folder. As long as the movement is between the same platform extensions should not be a problem. 

@bsclifton even if there is extension authentication required it should just discard the extension and still load the existing profile.

**Comment by bsclifton** [comment] 2019-12-30 19:19
ah - I might see the problem

@erotavlas-turbo I don't think you can only copy the `Default` folder. You would need to copy the entire directory above the `Default` directory. ex: `%USERPROFILE%\AppData\Local\BraveSoftware\Brave-Browser\`

**Comment by rebron** [comment] 2020-01-03 17:44
Closing. @erotavlas-turbo please re-open if the above comment doesn't work for you.

**Closed by rebron** 2020-01-03 17:44 UTC
Labels: need-more-info

**Comment by erotavlas-turbo** [comment] 2020-01-04 16:15
I'm sorry for the late reply.

> ah - I might see the problem
> 
> @erotavlas-turbo I don't think you can only copy the `Default` folder. You would need to copy the entire directory above the `Default` directory. ex: `%USERPROFILE%\AppData\Local\BraveSoftware\Brave-Browser\`

> I wonder if this is due to the user owning the files on Windows
> 
> @erotavlas-turbo is the original user in the Administrators group? and maybe the 2nd user isn't?
> 
> I'll give this a shot and try to reproduce. Also curious which extensions you are using

I tried to copy both Default folder and the whole Brave-Browser by copy and paste and via script without success. Could be a folder rights problem?
The strange thing is that with firefox profile the same procedure works well.

**Comment by alfredonodo** [comment] 2020-01-14 15:08
I have the same issue of @erotavlas-turbo

**Comment by erotavlas-turbo** [comment] 2020-02-02 16:14
I tried again with the latest version of brave v1.2.43. I can copy the profile across different versions of windows 10 (1909-1903) by losing all the extensions and some setting as default search engine, enabled spelling languages and home button customized options.

In my opinion, there is something that does not work well with windows since the same procedure has not problem with GNU/linux.
