### ISSUE TITLE
enable forward history and button for Brave Today

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#13478] opened 2021-01-11 18:00 UTC
## Description 

When clicking through to a Brave Today article, going back to the new tab page does not show that a user can go back to that article using the Forward button. A user should be able to go back to the article using the Forward button.

## Steps to Reproduce

   1. Open a new tab
   2. Scroll on Brave Today and select an article.
   3. Go back to the new tab page. (Should be back to the same scroll depth or section/anchor of the article snippet)
   4. Notice that Forward button is disabled. Forward button works normally for that window if the user continues to browse from the article onward but is still disabled on the new tab page if returning back to the new tab page. (e.g. go forward to a Brave Today article, click through a few times going forward. Go back to the New Tab page and notice Forward button still disabled). From the new tab page, typing in a url from that window will engage the normal forward button functions.

## Actual result:
Notice grayed out Forward icon. 

![Screen Shot 2021-01-11 at 9 55 09 AM](https://user-images.githubusercontent.com/5951041/104220222-05d67b00-53f4-11eb-93b6-e996a478c7c3.png)

## Expected result:
Forward button should be enabled and a user should be able to go Forward with the article they previously clicked on. 

## Reproduces how often: 

Easy.

## Brave version (brave://version info)

Brave | 1.19.77 Chromium: 87.0.4280.101 (Official Build) beta (arm64)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | macOS Version 11.1 (Build 20C69)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment] 2021-01-11 18:03
cc: @petemill

**Comment by srirambv** [comment] 2021-01-12 04:04
Dupe of #12674

**Closed by srirambv** 2021-01-12 04:04 UTC
Labels: OS/Desktop, feature/brave-today
