### ISSUE TITLE
Rewards disabled, still using memory.

### ISSUE THREAD

**Issue by foamz** [brave/brave-browser#4659] opened 2019-05-31 07:27 UTC
## Description 
The brave rewards extensions runs and consumes memory when I haven't signed up for rewards and enabled "Hide Brave Rewards button".
Hitting "End process" on the "Extension: Brave Rewards" simply respawns it.

Having this extension running, when everything is set to disable it, essentially makes this bloatware.

## Steps to Reproduce
NA

## Actual result:
![image](https://user-images.githubusercontent.com/722612/58688756-a09c5600-8385-11e9-9d1e-70500e89c5e8.png)

## Expected result:
The Brave Rewards extension should not be running at all when disabled.

## Reproduces how often: 
No steps to reproduce

## Brave version (brave://version info)
Brave | 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)
Revision | 78e4f8db3ce38f6c26cf56eed7ae9b331fc67ada-refs/branch-heads/3729@{#1013}
OS | Windows 10 OS Build 17763.529

**Comment by srirambv** [comment] 2019-05-31 11:41
Dupe of #3436

**Closed by srirambv** 2019-05-31 11:41 UTC
