### ISSUE TITLE
[Follow up to #18855][Search] Custom SE for South Korea is not removed after the upgrade flow is done

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#30063] opened 2023-04-29 00:03 UTC
## Description 

Follow up for #18855

## Steps to reproduce 

   1. Install build `1.50.121 Chromium: 112.0.5615.138`
   2. Go through onboarding > Hamburger Menu > Settings > Search engines
   3. Change SE to `DDG` and `Bing` for `Normal tab` and `Private tab` accordingly
   4. Close the app > Upgrade to build `1.51.107 Chromium: 113.0.5672.63`
   5. Launch the app > Hamburger Menu > Settings > Search engines
   6. Change SE to `Naver` or `Daum` > Close and relaunch the app
   7. Hamburger Menu > Settings > Search engines > Observe that `DDG` and `Bing` still not removed

## Actual result 

If a user selected any of the custom SE (DDG, Bing, Qwant or Startpage) before upgrading to a new build, then the previously selected SE is not removed even after the user changed it to any available for South Korea option (Brave, Naver, Daum or Google) and then restarted browser or phone

| Normal tab | Private tab |
| --- | --- |
| ![1](https://user-images.githubusercontent.com/128532965/235271033-4b1f62a9-f6ee-490e-99c9-8e370761b915.png) | ![2](https://user-images.githubusercontent.com/128532965/235271039-53567f68-bd7c-4fb2-8e13-b7887144ba18.png) |

https://user-images.githubusercontent.com/128532965/235271302-93eeb477-e16e-413f-bca6-018f47a4b6b9.mp4

## Expected result

After upgrading to build 1.51.x all custom search engines (DDG, Bing, Qwant and Startpage) must be removed for South Korea

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 6 [phone]
   - Android version: oriole-user 13 TQ2A.230405.003.E1 release-keys
   
## Brave version

1.51.107 Chromium: 113.0.5672.63

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by simonhong** [comment] 2023-05-01 23:25
I think this is expected behavior.
`DDG` and `Bing` were added to provider list explicitely after updating new list because both were previously selected one.
In this case, we don't remove implicitely when user change to default provider from them.

**Comment by bsclifton** [comment] 2023-05-02 18:47
Closing as invalid - thanks for raising 😄 As shared above, this should be expected behavior. I believe if you do a 2nd upgrade (ex: from 1.50 => 1.51 and then 1.51 => 1.52) those extra entries will be cleaned up.

**Closed by bsclifton** 2023-05-02 18:47 UTC
Labels: bug, feature/search, QA/Yes, OS/Android
