### ISSUE TITLE
Move "social media blocking" setting in brave://settings to brave://settings/shields

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#28658] opened 2023-02-21 23:58 UTC
Currently we have toplevel option in brave://settings called "Social media blocking" that has four (soon to be three) toggles.

I'd be nice to move these options somewhere else for a couple of reasons:
1. to move more of the content filtering options to the same place brave://settings/shields/filters
2. the formatting of the text label wraps to two lines (the only top level option that does) and so looks awkward
3. featuring these options as top level options (parallel to "Shields" and "Search engine" etc) is promoting a very niche setting with pretty valueable settings real-estate

**Comment by rebron** [comment] 2023-09-14 14:39
Closing as dupe of https://github.com/brave/brave-browser/issues/32956 and fixed in latest nightly, 1.60.x

**Comment by deeppandya** [comment] 2023-11-20 10:40
@pes10k what should be the priority of this issue ?

**Comment by pes10k** [comment] 2023-11-20 15:08
If it’s something that could be done quickly (a day or two) then I say medium to high priority, just so we can get a bit more polish out the door quickly and get the issue closed  if it’ll be more than that though, low priority is fineOn Nov 20, 2023, at 04:40, Deep Pandya ***@***.***> wrote:﻿
@pes10k what should be the priority of this issue ?

**Closed** 2024-12-09 14:52 UTC
Labels: design, priority/P3, QA/Yes, feature/settings, OS/Android
