### ISSUE TITLE
crash via `brave_ads::TabManager::OnNotifyTabDidChange`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#30726] opened 2023-05-31 19:17 UTC
## Description 

Looks like we have a crash via `brave_ads::TabManager::OnNotifyTabDidChange`. There's several entries on my `Win 11 x64` machine under `brave://crashes`. However, not 100% sure when it's occurring or any STR. Created issues after discussing with @tmancey who mentioned there's a fix in the pipeline.

## Steps to Reproduce

Honestly, not 100% when the crash occurred as I found the crashes via `brave://crashes`.

## Actual result:

```
[ 00 ] brave_ads::TabManager::OnNotifyTabDidChange(int,std::Cr::vector<GURL,std::Cr::allocator<GURL> > const &,bool,bool) ( tab_manager.cc:268 )
[ 01 ] _tailMerge_esent.dll
[ 02 ] _tailMerge_esent.dll
[ 03 ] _tailMerge_esent.dll
[ 04 ] _tailMerge_esent.dll
[ 05 ] _tailMerge_esent.dll
[ 06 ] _tailMerge_esent.dll
[ 07 ] brave_ads::AdsClientNotifier::NotifyTabDidChange(int,std::Cr::vector<GURL,std::Cr::allocator<GURL> > const &,bool,bool) ( ads_client_notifier.cc:82 )
[ 08 ] bat_ads::mojom::BatAdsClientNotifierStubDispatch::Accept(bat_ads::mojom::BatAdsClientNotifier *,mojo::Message *) ( bat_ads.mojom.cc:1715 )
[ 09 ] static unsigned int bat_ads::mojom::BatAdsClientNotifier::NotifyTabDidChange_Sym::IPCStableHash() ( bat_ads.mojom.cc:630 )
[ 10 ] _tailMerge_esent.dll
[ 11 ] mojo::InterfaceEndpointClient::HandleIncomingMessageThunk::Accept(mojo::Message *) ( interface_endpoint_client.cc:358 )
[ 12 ] partition_alloc::internal::SpinningMutex::AcquireSpinThenBlock() ( spinning_mutex.cc:57 )
[ 13 ] _tailMerge_esent.dll
[ 14 ] mojo::internal::ArraySerializationHelper<mojo::internal::Pointer<url::mojom::internal::Url_Data>,0,0>::ValidateElements(mojo::internal::ArrayHeader const *,mojo::internal::Pointer<url::mojom::internal::Url_Data> const *,mojo::internal::ValidationContext *,mojo::internal::ContainerValidateParams const *) ( array_internal.h:213 )
[ 15 ] mojo::internal::Array_Data<mojo::internal::Pointer<url::mojom::internal::Url_Data> >::Validate(void const *,mojo::internal::ValidationContext *,mojo::internal::ContainerValidateParams const *) ( array_internal.h:321 )
[ 16 ] _tailMerge_esent.dll
[ 17 ] mojo::internal::ValidateRequestGeneric(mojo::Message *,char const *,base::span<std::Cr::pair<unsigned int,mojo::internal::GenericValidationInfo> const ,-1>) ( generated_code_util.cc:98 )
[ 18 ] _tailMerge_esent.dll
[ 19 ] _tailMerge_esent.dll
[ 20 ] _tailMerge_esent.dll
[ 21 ] mojo::internal::MultiplexRouter::Accept(mojo::Message *) ( multiplex_router.cc:708 )
[ 22 ] _tailMerge_esent.dll
```

## Expected result:

Brave shouldn't be crashing when using/interacting with ads.

## Reproduces how often: 

Not 100% as per the above. I don't have any STR/Cases. But there was ~2-3 instances of the above crash via `brave://crashes` do it doesn't seem like it's something that occurs often.

## Brave version (brave://version info)

```
Brave | 1.54.19 Chromium: 114.0.5735.53 (Official Build) nightly (64-bit)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Not sure` (will need @tmancey to take a look which branches are affected)
- Can you reproduce this issue with the beta channel? `Not sure` (will need @tmancey to take a look which branches are affected)
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `Yes` (assuming it will fix the issue when rewards/ads are disabled)
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @btlechowski

**Comment by kjozwiak** [comment] 2023-05-31 19:17
@tmancey if you end up having STR/Cases that reproduces the above, can you please add the cases into the associated PR and add the `QA/Yes` label.

**Comment by tmancey** [comment] 2023-06-09 20:16
Unfortunately I was unable to reproduce, however I have not seen the same crash in backtrace after the fix. Thanks

**Comment by iefremov** [comment] 2024-05-14 20:00
actually we have something on backtrace again, in 125 https://brave.sp.backtrace.io/p/brave/explore?filters=JTVCJTVCJTIydmVyJTIyJTJDJTIyYXQtbGVhc3QlMjIlMkMlMjIxMjQlMjIlNUQlMkMlNUIlMjJjYWxsc3RhY2suZnVuY3Rpb25zJTIyJTJDJTIyY29udGFpbnMlMjIlMkMlMjJicmF2ZV9hZHMlM0ElM0FUYWJNYW5hZ2VyJTNBJTNBT25Ob3RpZnlUYWJEaWRDaGFuZ2UlMjIlNUQlNUQ%3D&aggregations=((ver%2Cmax)%2C(uname.sysname%2Cdistribution)%2C(callstack%2Chead))&

**Comment by tmancey** [comment] 2024-05-14 21:02
@iefremov this was fixed by https://github.com/brave/brave-browser/issues/38266, thanks

**Comment by iefremov** [comment] 2024-05-15 06:47
Thanks @tmancey I guess we can close the issue then

**Closed by iefremov** 2024-05-15 06:47 UTC
Labels: bug, crash, priority/P2, QA/No, release-notes/exclude, feature/ads, OS/Desktop
