### ISSUE TITLE
Brave translate is not available for existing users after migration/upgrade when `Google translate` extension is pinned to toolbar

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#24715] opened 2022-08-17 01:05 UTC
## Description 

When existing users pin `Google translate` extension to toolbar  and upgrade, `Brave translate` bubble is not shown.  `Google translate` extension is still available in the upgraded version.  Not sure of the expected functionality

## Steps to Reproduce

1. install 1.42.95
2. launch brave
3. load a `French` language site https://www.lemonde.fr/
4. `Google Translate` extension bubble is shown in the URL bar as expected
5. install `Google translate extension`
6. verified `Google translate extension` is pinned to the toolbar in the upper right corner and displayed in  `brave://extensions` 
7. close the browser but do not close the website tab
8. rename the profile folder to  Beta
9. launch Brave with 1.43.67 
10. confirmed `Brave tranlate` is enabled via griffin in `Brave://version`via BraveTranslateStudy:Enabled
11. verified toggle `ON` as a default for `Offer to translate pages that aren't in a language you read` entry in `brave://settings/languages`

## Actual result:

`Brave translate` extension bubble is not shown in the URL bar
`Google translate` extension available in toolbar

Step4|Step 6Ex2|Step10|actual_result
----|----|----|----
<image width ="850" alt="image" src="https://user-images.githubusercontent.com/98358127/185009771-667de6a4-384b-4584-bcef-e8b8c9cbb1a7.png">|<image width ="850" alt="image" src="https://user-images.githubusercontent.com/98358127/185009836-6662080d-7563-4565-b726-7e1a815b2146.png">|<image width ="850" alt="image" src="https://user-images.githubusercontent.com/98358127/185010112-e5ed4986-ecfb-443e-be53-58717648c026.png">|<image width ="850" alt="image" src="https://user-images.githubusercontent.com/98358127/185010278-1bc49a22-9b80-45e7-b99c-bb3644df9816.png">

## Expected result:
`Brave translate` bubble should be shown?

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.43.67 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.856)
JavaScript | V8 10.4.132.20

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @stephendonner

**Comment by atuchin-m** [comment] 2022-09-12 08:38
@rebron it's expected behavior at time we experimented with the feature.
The reason is not avoid a double translate suggestion for users who use Goggle Translate extension.
That behavior was fixed in the original issue: https://github.com/brave/brave-browser/issues/18593#issuecomment-951706548

@rebron  Are we ready to remove or disable the code checking the extension status? Or we need some migration for such users? 

P.S. We check  that the extension is enabled, not pinned.

**Comment by rebron** [comment] 2022-09-13 07:02
@atuchin-m We can go ahead and disable the code checking status.

**Closed** 2022-09-29 12:23 UTC
Labels: priority/P4, QA/Yes, release-notes/exclude, OS/Desktop, brave-translate

**Comment by stephendonner** [comment] 2022-10-31 20:42
## Verified `PASSED` using 

Brave | 1.46.86 Chromium: 107.0.5304.91 (Official Build) beta (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:
installed `1.42.95`
launched Brave
loaded `https://russian.rt.com/`
confirmed the `Google Translate` extension bubble was shown
clicked `Install`
clicked `Add extension`
test-translated the page
shut down Brave
renamed `Brave-Browser` profile folder to `Brave-Browser-Beta`
launched `1.46.86`
confirmed I saw the `Brave Translate` UI *and* the `Google Translate` extension, co-existing
confirmed I could translate the page from Russian to English
opened `brave://settings/languages` and confirmed `Use Brave Translate` was set to `Enabled` / `On` by default

example | example | example | example | example | example | example | example | example
--|--|--|--|--|--|--|--|--
<img width="1312" alt="Screen Shot 2022-10-31 at 1 26 01 PM" src="https://user-images.githubusercontent.com/387249/199105648-ddd86af4-adad-48a4-aa16-cd4e3f047b66.png"> | <img width="1312" alt="Screen Shot 2022-10-31 at 1 26 05 PM" src="https://user-images.githubusercontent.com/387249/199105654-935ddef3-3c60-48f0-a0bc-6b6e3f4e20a7.png"> | <img width="1312" alt="Screen Shot 2022-10-31 at 1 26 11 PM" src="https://user-images.githubusercontent.com/387249/199105658-482adfb8-fc1c-41ee-ac3a-f842fa0781c8.png"> | <img width="1312" alt="Screen Shot 2022-10-31 at 1 26 49 PM" src="https://user-images.githubusercontent.com/387249/199105660-5e90337f-bbe2-4499-9907-afc4a4b7f2db.png"> | <img width="798" alt="Screen Shot 2022-10-31 at 1 27 08 PM" src="https://user-images.githubusercontent.com/387249/199105667-1b66448c-3bd0-4ea6-89ce-233789f15393.png"> | <img width="1312" alt="Screen Shot 2022-10-31 at 1 27 31 PM" src="https://user-images.githubusercontent.com/387249/199105669-b3c74923-ab24-48fb-b98f-fc568883b05f.png"> | <img width="1312" alt="Screen Shot 2022-10-31 at 1 27 41 PM" src="https://user-images.githubusercontent.com/387249/199105672-20e5d6d1-ce71-4fe2-a92e-f52590a70d15.png"> | <img width="1312" alt="Screen Shot 2022-10-31 at 1 28 21 PM" src="https://user-images.githubusercontent.com/387249/199105676-ec9e99ef-f10e-4005-b675-4a193bf5c70b.png"> | <img width="1312" alt="Screen Shot 2022-10-31 at 1 28 50 PM" src="https://user-images.githubusercontent.com/387249/199105677-36feb5ad-ade0-4c84-a55d-b61082471168.png">

**Comment by kjozwiak** [comment] 2022-11-10 18:43
The above requires `1.45.124` or higher for `1.45.x` verification. Removing `QA Pass-macOS` so it can get rechecked via `1.45.x`. Used the verification that @stephendonner did via https://github.com/brave/brave-browser/issues/24715#issuecomment-1297661209 for the uplift as per https://github.com/brave/brave-core/pull/15888#pullrequestreview-1176311398.

**Comment by GeetaSarvadnya** [comment] 2022-11-11 14:23
Verification PASSED on

```
Brave | 1.45.125 Chromium: 107.0.5304.110 (Official Build) (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```

### Steps:

1. installed `1.42.95`
2. launched Brave
3. loaded `https://russian.rt.com/`
4. confirmed the `Google Translate` extension bubble was shown
5. clicked `Install`
6. clicked `Add extension`
7. test-translated the page
8. shut down Brave
9. renamed `Brave-Browser` profile folder to `Brave-Browser-Beta`
10. launched `1.46.86`
11. confirmed I saw the `Brave Translate` UI *and* the `Google Translate` extension, co-existing
12. confirmed I could translate the page from Russian to English
13. opened `brave://settings/languages` and confirmed `Use Brave Translate` was set to `Enabled` / `On` by default


1.42.95 | 1.42.95 | 1.42.95 | 1.45.125 | 1.45.125 | 1.45.125 | 1.45.125 | 1.45.125
---------|---------|---------|-----------|----------|----------|-----------|------------
![image](https://user-images.githubusercontent.com/38657976/201357579-90bff998-5802-49b4-bc22-668e1d02e014.png) | ![image](https://user-images.githubusercontent.com/38657976/201357710-e77553da-1ea7-43f5-a25d-d3bb129b510e.png) | ![image](https://user-images.githubusercontent.com/38657976/201357818-e449ed38-dde1-4d67-9844-ab15125ae5d1.png) | ![image](https://user-images.githubusercontent.com/38657976/201358436-e3c45a30-f6af-4d35-af91-0b7b61c7f0ad.png) | ![image](https://user-images.githubusercontent.com/38657976/201359313-07f65dc3-e42f-47bc-86d2-1f48d6408d2c.png) | ![image](https://user-images.githubusercontent.com/38657976/201359418-43edc69a-4523-4e2d-a60d-d4659843125f.png) | ![image](https://user-images.githubusercontent.com/38657976/201359519-41db43c1-f542-4805-a968-30a1641474b2.png) | ![image](https://user-images.githubusercontent.com/38657976/201359638-04d6af9b-e611-4ab9-bfdb-add88426adb6.png)
