### ISSUE TITLE
Propagate CBR-FFI errors through for easier debugging

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#3660] opened 2019-03-11 15:55 UTC
## Description 
Certain errors coming out of CBR-FFI can remain hidden because they are not fully propagated to the browser debugging output.  We should make sure that they appropriately wired up.

**Comment by tmancey** [comment] 2020-01-20 13:03
Closing as a duplicate of https://github.com/brave/brave-browser/issues/7240

**Closed by tmancey** 2020-01-20 13:03 UTC
Labels: feature/ads, priority/P3
