### ISSUE TITLE
v.redd.it videos won't work with shields up

### ISSUE THREAD

**Issue by rschuetzler** [brave/brave-browser#2597] opened 2018-12-17 14:26 UTC
## Description 

Scrolling through Reddit's homepage, any links to v.redd.it (the reddit video player) don't work when shields are up. Opening in a private window works.

## Steps to Reproduce

   1. Go to https://www.reddit.com/r/oddlysatisfying/comments/a6xeew/how_a_golf_course_changes_holes/
   2. See that the video at the top does not load.

## Actual result:

Video is blocked. It just shows a loading animation.

## Expected result:
Video plays

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

Brave | 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
Works when disabling the shields, and in the latest version of Chrome.

**Comment by TDeisinger** [comment] 2018-12-18 17:51
I can confirm this happens for me as well.

**Comment by tomlowenthal** [comment] 2018-12-19 18:10
Dupe of #1999

**Closed by tomlowenthal** 2018-12-19 18:10 UTC
Labels: duplicate
