### ISSUE TITLE
Open Wifi portal in Brave

### ISSUE THREAD

**Issue by DenishKakadiya** [brave/brave-browser#4140] opened 2019-04-17 05:14 UTC
## Description 
Whenever we are at public wifi like railway, cafe, or college wifi, we need to login in wifi portal. In Chrome, portal automatically opens when you visit any website. In Firefox also, we get notification for opening portal or we can open portal using "detectportal.firefox.com" link. However, In Brave there is no such feature.  As discribed in issue #2390, we can open wifi portal in Brave by visiting any non-https site(i.e. http://yahoo.com), But normal users won't know about such things. So notification feature for opening wifi portal in Brave will be useful. 

## Steps to Reproduce
To open portal in Firefox,
   1. visit "detectportal.firefox.com"

## Expected result:
![firefox_screenshot](https://user-images.githubusercontent.com/25260231/56262584-eca87980-60fc-11e9-97c2-18598b8cd8e0.png)

## Brave version (brave://version info)
Brave      :- 0.64.47 Chromium: 74.0.3729.61 (Official Build) dev (64-bit)
Revision  :- 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS           :- Windows 10 OS Build 17763.437

**Comment by rebron** [comment] 2019-04-19 16:18
Closing. Based on https://github.com/brave/brave-browser/issues/2390#issuecomment-446715677, not a bug.

**Closed by rebron** 2019-04-19 16:18 UTC
