### ISSUE TITLE
Search history visual bug

### ISSUE THREAD

**Issue by noobToLinux** [brave/brave-browser#41746] opened 2024-10-20 15:39 UTC
### Description

Hello.

As the titles says, there is a visual bug in the search history.

To avoid repeating myself, I add the steps to reproduce

### Steps to reproduce

1. Enter search history.
2. Check the list whithout scrolling and is correct.
3. Starts scrolling down.
4. After two or three long scrolls (around a page), search history list starts to repeat randomly (aparently).
        * This means that some urls are from the beginning of the history at random position in the visual list. (Notes after this clarify)
        * Apparently means that it is only visual, the url is the one that it should be but visually is the same as one of the first.
 5. If I hover the mouse over the checkbox or the three dots for options, the real url appears, but as long as I keep the mouse over it.

### Actual result

To clarify it in a programming perspective.

Lets define the history as a list of python dict, or js object. Just like this.

```py
History = [
    {'Url' : some_url, 'Image/text': the_image_and_text}
]
```
The image is for example youtube logo, and text is YouTube or the title of YouTube Video

Given this, the error is like this:

* History[0:20] Everything correct. (Lets say that in the screen only appears the first 20, the rest you need to scroll)
* History[30:50] Mostly Image/text are from History[0:20], the URLs are correct though.

Same error happens when I search for some URL, the first page is correct, if I scroll the error happens again.

### Expected result

I think there is no need to explain this after previous explanations

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.71.114 Chromium: 130.0.6723.58 (Build oficial) (64 bits) 

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Just visual, not important bug

**Comment by XenoXenonZ** [comment] 2024-10-21 08:39
Running into the same issue. Also seems that if I switch to other pages and switch it back to history the display of the current position resumes correct but if I continue scrolling down the issue happens again

**Comment by rebron** [comment] 2024-10-23 22:08
Hi @noobToLinux and @XenoXenonZ Can you update to the latest 1.71.118 and see if you're still encountering this issue. We've addressed it with that version https://github.com/brave/brave-browser/issues/41763

I'll close as a dupe of #41763 after I hear back from you.

**Comment by XenoXenonZ** [comment] 2024-10-24 04:25
@rebron Looks like it's fixed here on my Brave after the update. Thx for that👍

**Comment by noobToLinux** [comment] 2024-10-24 20:11
@rebron Hello, yes it is fixed now, thanks

**Comment by rebron** [comment] 2024-10-25 19:44
Closing. Thanks for confirming.

**Closed by rebron** 2024-10-25 19:44 UTC
Labels: feature/history, OS/Desktop
