### ISSUE TITLE
[Request]  Hold Brave Browser honest !! Stay at Truth to be trustworthy and reliable

### ISSUE THREAD

**Issue by blackcrack** [brave/brave-browser#10170] opened 2020-06-09 08:24 UTC
https://davidgerard.co.uk/blockchain/2020/06/06/the-brave-web-browser-is-hijacking-links-and-inserting-affiliate-codes/

https://www.androidpolice.com/2020/06/07/brave-browser-caught-adding-its-own-referral-codes-to-some-cryptcurrency-trading-sites/

And this makes international the round !
here Germany
https://winfuture.de/news,116307.html

i be really disappointed about.. 
you are muck around the User ?!!

shame you..

should anyone check it in in Facebook

**Comment by bsclifton** [comment] 2020-06-09 08:31
The issue is resolved now and you can read our response here:
https://brave.com/referral-codes-in-suggested-sites/

We also have a main issue where you can discuss this with others that were similarly upset:
https://github.com/brave/brave-browser/issues/10129

I'll close this issue as it's a duplicate

**Closed by bsclifton** 2020-06-09 08:31 UTC
Labels: OS/Desktop
