### ISSUE TITLE
Tor help page is not easily accessible in a Tor window

### ISSUE THREAD

**Issue by Madis0** [brave/brave-browser#7697] opened 2020-01-10 20:32 UTC
## Description 

The help page describing Tor is behind Cloudflare Captcha, which makes it very hard (if not impossible) to access in a Tor window itself.

## Steps to Reproduce

   1. Open a Tor window
   2. Click on ["Read more about Tor in Brave"](https://support.brave.com/hc/en-us/articles/360018121491)

## Actual result:

The user is given a "Complete the security check to access this page" page.
![Screenshot](https://user-images.githubusercontent.com/8611110/72184434-1cb94a80-33f9-11ea-88f0-64b50803acaf.png)

## Expected result:
A local or externally hosted page that doesn't have the "Cloudflare wall".

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Brave | 1.5.25 Chromium: 79.0.3945.117 (Official Build) unknown (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by bsclifton** [comment] 2020-02-23 06:36
cc: @tomlowenthal @riastradh-brave

**Comment by tomlowenthal** [comment] 2020-02-24 19:10
Dupe of #1647.

**Closed by tomlowenthal** 2020-02-24 19:10 UTC
Labels: feature/tor
