### ISSUE TITLE
$websocket adblock rules don't work or unsupported?

### ISSUE THREAD

**Issue by TheVampireInLoveWithTheCorpsesBlood** [brave/brave-browser#26285] opened 2022-10-26 16:40 UTC
is it a bug or just Brave doesn't support using `$websocket` filter?

It is mentioned in https://github.com/brave/adblock-rust/blob/master/src/filters/network.rs, so, that's why I ask.

what about for example: `$badfilter`? I tested it and nothing.

That even mentions `bug` and `tag`, are they valid? do they do something or need something? because it also mentions `collapse` which seems to block everything when I used `$collapse`

This was mostly about $websocket filter but there is always questions about Brave's adblocker since it doesn't have any documentation or much explaining what is exactly supported by Brave.

**Comment by TheVampireInLoveWithTheCorpsesBlood** [comment] 2022-10-26 19:29
@pes10k I only made this account to report/ask this.
I am sure this is a bug since the network.rs talks about websockets (and badfilter which I asked as well) and there is even a mention of a rule like `|ws://$domain=4shared.com` being fixed/closed [in Aug 12, 2020](https://github.com/brave/adblock-rust/issues/123).
But it was two years ago, maybe it just got unsupported by you and there is no clear documentation or anything about it.

The problem is how Brave Team doesn't want to hear about bugs and problems, I know things can't get fixed with a magical button, but when Brave team doesn't seem to be interested to hear, it's awkward. I have reported many things and always get ignored and maybe even blocked in community brave when reporting big issues with the adblocker.

I tagged you because I don't want this issue to go to the trashcan of opened and never cared issues that are most likely bugs.

**Comment by pes10k** [comment] 2022-10-26 22:51
Thanks for the heads up @TheVampireInLoveWithTheCorpsesBlood.  This should fix it https://github.com/brave/brave-core/pull/15679 (thanks @antonok-edm !) .  Should make its way into nightly in the next day or three, and we'll probably uplift to other channels soon after

**Comment by antonok-edm** [comment] 2022-10-26 22:51
> is it a bug or just Brave doesn't support using $websocket filter?

Thanks for reporting, this was a regression and should be fixed by https://github.com/brave/brave-core/pull/15679.

> what about for example: `$badfilter`? I tested it and nothing.

`$badfilter` is a bit tricky at the moment as it only works within a single adblock engine and we run multiple engines for historical reasons. That should be addressed by https://github.com/brave/brave-browser/issues/5461. In the meantime it's admittedly not very useful.

> That even mentions `bug` and `tag`, are they valid? do they do something or need something? because it also mentions `collapse` which seems to block everything when I used `$collapse`

`$bug` doesn't do anything, it's just for adding reference info. I don't think it was ever used since the original author added it; if that's the case I think we can safely remove it.

`$tag` will also probably be removed at some point, we've been using it for the settings in brave://settings/socialBlocking but we have some better solutions upcoming - see https://github.com/brave/brave-browser/issues/26273. There hasn't ever been any user-facing way to add or toggle new tags, so consider it an internal-only feature.

`$collapse` to my knowledge also has never been used, and I'm not sure what the original intention of it was - we'll get that removed too.

**Closed** 2022-10-27 21:23 UTC
Labels: feature/shields/adblock, QA/Yes, release-notes/include, OS/Desktop

**Comment by kjozwiak** [comment] 2022-10-28 19:44
The above requires `1.45.117` or higher for `1.45.x` verification 👍

**Comment by kjozwiak** [comment] 2022-11-02 03:06
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.45.118 Chromium: 107.0.5304.91 (Official Build) (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Windows 11 Version 22H2 (Build 22621.755)
```

Reproduced the original issue using the STR/Cases outlined via https://github.com/brave/brave-core/pull/15679#issue-1424778127 using `1.45.116 Chromium: 107.0.5304.91` as per the following:

**`Example`** | **`Example`**
----------------|----------------
![image](https://user-images.githubusercontent.com/2602313/199385551-69250b23-f699-4829-ac27-cff99bba30f9.png) | ![image](https://user-images.githubusercontent.com/2602313/199385577-fefdb043-a0dd-4339-a774-04dee86007f3.png)

Verified that `Websockets` appeared disabled/not working once `||websocketstest.com^$websocket` is added into the custom filter area as per the following:

**`Example`** | **`Example`**
----------------|---------------
![image](https://user-images.githubusercontent.com/2602313/199385819-d8b8f923-e908-4ee8-9340-5b340c7f9fe5.png) | ![image](https://user-images.githubusercontent.com/2602313/199385841-e27ff71f-719d-4735-b1e7-ec669847f42d.png)

**Comment by stephendonner** [comment] 2022-11-02 04:57
## Verification `PASSED` using 

Brave | 1.45.118 Chromium: 107.0.5304.91 (Official Build) (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:
1. installed `1.45.118`
2. launched Brave
3. opened `brave://settings/shields/filters`
4. added `||websocketstest.com^$websocket` to the `Custom filters` box at the bottom
5. clicked `Save changes`
6. loaded `https://websocketstest.com/`

#### Confirmed I saw the `WebSockets seem to Not Work for you :(` message


`brave://settings/shields/filters` | `websocketstest.com`
--------------------------------|------------------------
<img width="1164" alt="Screen Shot 2022-11-01 at 9 54 14 PM" src="https://user-images.githubusercontent.com/387249/199401661-b72dc632-a213-424a-972d-db5745e5568a.png"> | <img width="1164" alt="Screen Shot 2022-11-01 at 9 55 21 PM" src="https://user-images.githubusercontent.com/387249/199401668-8ae31a0b-52b3-4126-bc4b-6119a75941b9.png">

**Comment by kjozwiak** [comment] 2022-11-02 06:54
Verification **PASSED** on `PopOS 22.04 x64` using the following build(s):

```
Brave | 1.45.118 Chromium: 107.0.5304.91 (Official Build) (64-bit)
--- | ---
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Linux
```

Reproduced the original issue using the STR/Cases outlined via https://github.com/brave/brave-core/pull/15679#issue-1424778127 using `1.45.116 Chromium: 107.0.5304.91` as per the following:

**`Example`** | **`Example`**
----------------|----------------
![image](https://user-images.githubusercontent.com/2602313/199420075-3962f231-1a13-4ca1-951a-ef5d218b6f0c.png) | ![image](https://user-images.githubusercontent.com/2602313/199420104-501297dd-7cf1-47f6-a612-51d58023df17.png)

Verified that `Websockets` appeared disabled/not working once `||websocketstest.com^$websocket` is added into the custom filter area as per the following:

**`Example`** | **`Example`**
----------------|---------------
![image](https://user-images.githubusercontent.com/2602313/199420479-cdbbb5c9-92e0-4490-b98f-8bfe25c6f8fe.png) | ![image](https://user-images.githubusercontent.com/2602313/199420512-7762be91-d5a0-4d5a-89bb-8e3780475df6.png)
