### ISSUE TITLE
Unable to delete cookie for gmail via Clear On Exit 

### ISSUE THREAD

**Issue by snowbound** [brave/brave-browser#9085] opened 2020-04-08 04:46 UTC
With Google Chrome and MS Edge Chromium if you enter "google.com" in their respective Clear On Exit for cookies then when the browser is closed and restarted any sessions for Gmail are automatically logged out. This is because it deletes the SID subcookie for Google.com

## Steps to Reproduce

   1. enter google.com on Clear on Exit for cookies 
   2. ensure that you are logged into a Gmail account
   3. close Brave
   4. restart Brave
   5. go to gmail.com
## Actual result:
 You are still logged into Gmail account

## Expected result:
You should be logged out of gmail if the deletion of the google.com is occurring. It is not as the google.com still shows up under brave://settings/siteData when Brave is closed and restarted.

## Reproduces how often: 
on demand

## Brave version (brave://version info)
Version 1.8.66 Chromium: 81.0.4044.83 (Official Build) beta (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? NO

## Miscellaneous Information:
Even using [*.]google.com does not log one out of Gmail. One should be able to delete specific cookies which in this case is the SID@mail.google.com one which forces a logout of the gmail account. 

I was told in this [thread](https://community.brave.com/t/google-com-cookies-not-being-cleared-on-exit/107692) on the community to enable “Cookies and Site Data” but when I did that back in February it resulted in a scorched earth of deleting 2FA authorization cookies as well as the YouTube configuration cookie.

**Comment by abampalexnder** [comment] 2020-04-19 18:13
I have got solution for google after 3 weeks brain storming and spent all day and night time to resolve the issue any one need solution can contact on 
Email: abmpanalexander@protonmail.com
on wire @abampalxender

**Comment by snowbound** [comment] 2020-04-19 19:20
FYI got a private response from what I deemed was a spammer. Sigh

**Comment by rebron** [comment] 2020-04-20 21:28
@snowbound Dupe of https://github.com/brave/brave-browser/issues/8842#issuecomment-604492495 

cc: @jumde

**Comment by jumde** [comment] 2020-04-21 22:14
@snowbound - On `v1.9.37` and `v1.8.78`

With: 

- Preferences set to delete cookies on exit:
![Screen Shot 2020-04-21 at 3 11 48 PM](https://user-images.githubusercontent.com/1903815/79919045-7232c980-83e2-11ea-83c8-3044a2b22f0b.png)

If I log into gmail.com, close and re-open the browser. I don't stay logged into gmail.com

Let me know if I'm missing something.

**Comment by snowbound** [comment] 2020-04-22 01:52
@jumde  
I use 2FA I only want to be logged out of gmail. I do not want other cookies such as the 2FA cookie to be deleted. 

When I use Chrome and my current browser MS Edge Chromium and tell it to delete the "google.com" cookie upon exiting the browser I am logged out of all the Gmail accounts I was logged into. The 2Factor Authentication cookie is still intact,

**Comment by bsclifton** [comment] 2020-05-05 20:53
@jumde I believe @snowbound is using the `Clear on exit` feature on content settings in brave://settings/content/cookies

I can definitely understand not wanting to use the `Clear on exit` that @jumde showed, as this clears all cookies and site data

**Comment by snowbound** [comment] 2020-05-05 21:03
Correct @bsclifton I am indeed using "Clear on exit" or would like to but even with the current build of Brave ---Version 1.9.45 Chromium: 81.0.4044.122 (Official Build) beta (64-bit) it is still not working.

**Comment by jumde** [comment] 2020-05-12 04:19
@snowbound - Thanks for your help.

Are you able to repro this if you disable `Allow Google login buttons on third party sites`  in `brave://settings/socialBlocking`? I can repro with the setting enabled, but not with the setting disabled.

**Comment by jumde** [comment] 2020-05-12 04:35
With cookie exceptions the behavior is same in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1081587 - Needs an upstream fix.

**Comment by snowbound** [comment] 2020-05-12 05:46
@jumde Only setting I have enabled in Social Blocking is "Allow Twitter embedded tweets" and I have "google.com" entered under "Clear on exit" . That should force a logout on Gmail accounts like Chrome and Edge Chromium on the next browser start. It does not

**Comment by snowbound** [comment] 2020-09-21 03:34
This issue still persists in 
Version 1.15.54 Chromium: 85.0.4183.102 (Official Build) beta (64-bit)  per this Reddit [post](https://www.reddit.com/r/brave_browser/comments/iw6ft9/am_i_alone_in_not_really_liking_brave/g62aht6?utm_source=share&utm_medium=web2x&context=3)

**Comment by snowbound** [comment] 2020-09-23 13:26
Followup [thread ](https://www.reddit.com/r/brave_browser/comments/iw6ft9/am_i_alone_in_not_really_liking_brave/g623v3x?utm_source=share&utm_medium=web2x&context=3 )on Reditt were I thought it was solved but has reappeared


Brave Community [thread](https://community.brave.com/t/google-com-cookies-not-being-cleared-on-exit/107692/26) on this issue.

**Comment by snowbound** [comment] 2021-01-10 07:01
Clear on Exit appears to have been replaced by "Always clear cookies when windows are closed" and this is still apparently happening on both the release version of Brave as well as Version 1.19.77 Chromium: 87.0.4280.101 (Official Build) beta (64-bit)

**Comment by snowbound** [comment] 2021-01-12 03:59
How is it that the current MS Edge Chromium Beta at least is capable of deleting the google.com cookie on exit yet Version 1.19.77 Chromium: 87.0.4280.101 (Official Build) beta (64-bit) it is an impossible task to accomplish? I have nothing enabled in Allow Google login buttons on third party sites in brave://settings/socialBlocking

**Comment by jumde** [comment] 2021-01-12 04:22
@snowbound - I was able to reproduce this issue. Thanks for all your feedback! Will keep you posted about the progress.

**Comment by snowbound** [comment] 2021-01-12 04:30
Thank you for the feedback I spent countless hours here reinstalling Brave and trying various things thinking it was an issue here.

**Comment by snowbound** [comment] 2021-03-16 03:11
This is close to a year-old bug that along with a sync issue has currently caused me to switch to another Chromium browser. Is there any ETA at all when it will be fixed?

**Comment by snowbound** [comment] 2021-04-03 04:46
Is this issue about to be fixed anytime soon? Why are other Chromium-based browsers not having this issue?

**Comment by snowbound** [comment] 2021-04-30 21:17
It's only security-related on a system that others have access or if the computer is stolen. /s

**Comment by rebron** [comment] 2021-04-30 21:39
<img width="677" alt="Screen Shot 2021-04-30 at 2 33 56 PM" src="https://user-images.githubusercontent.com/5951041/116756669-554faf80-a9c1-11eb-9b4b-9cb70a9e3186.png">

Typing in [*.]google.com above and quitting Brave didn't clear gmail for you on next launch? 
I got logged out out Google. 

OS specific? Am I missing a scenario?

Using :
Brave | 1.24.71 Chromium: 90.0.4430.72 (Official Build) beta (arm64)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | macOS Version 11.3 (Build 20E232)

**Comment by snowbound** [comment] 2021-04-30 22:05
Doing the [*.].google.com removes ALL the google cookies including 2 FA cookies. If one specifies google.com in Chrome or MS Edge then the browser only deletes a HSID or SID subcookie that forces a logout of Gmail. The 2FA cookies and other configuration cookies say for YouTube remain intact. That is what I would prefer to happen. A scorch earth cookie deletion is something I want to avoid

**Comment by snowbound** [comment] 2021-06-18 22:11
I have had to resort to using Cookie AutoDelete extension to do the cookie deletion as it appears Brave is the only Chromium-based browser that is incapable of doing this. I have tried countless other browsers and they have no such issue. As this is a 14+ month old issue that still has not been fixed I doubt it ever will be.

**Comment by bridiver** [comment] 2022-02-04 01:55
I'm not able to reproduce this issue with
![image](https://user-images.githubusercontent.com/34129/152459716-63d05759-841d-437c-ab62-7fb036ed5716.png)

**Comment by snowbound** [comment] 2022-02-04 04:07
If I go into Brave settings and select **All Cookies and Site Data** it displays all the cookies. If I then enter google.com it shows all the cookies with the google.com domain including this cookie

![image](https://user-images.githubusercontent.com/596147/152469883-b4e92a67-1756-4530-bf4e-c0d0eeb2d2dd.png)

If I then go to 

**Always clear cookies when windows are closed** and enter google.com  then the above cookie should be deleted when Brave is closed. It is not. If this cookie is indeed deleted then it will automatically do a force logout of your Gmail accounts. 

If I close Brave down then start it back up and go into All Cookies and Site Data then the google.com cookie is still there!

**Comment by bridiver** [comment] 2022-02-04 11:09
> @bridiver 
> 
> If I go into Brave settings and select **All Cookies and Site Data** it displays all the cookies. If I then enter google.com in the search box in the upper right corner of the page it shows all the cookies with the google.com domain including this cookie
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/596147/152469883-b4e92a67-1756-4530-bf4e-c0d0eeb2d2dd.png)
> 
> 
> 
> If I then go to 
> 
> 
> 
> **Always clear cookies when windows are closed** and enter google.com  then the above cookie should be deleted when Brave is closed. It is not. If this cookie is indeed deleted then it will automatically do a force logout of your Gmail accounts. 
> 
> 
> 
> If I close Brave down then start it back up and go into All Cookies and Site Data then the google.com cookie is still there in Brave Beta v 1.36.83
> 
> 

Can you try it on nightly? I was logged out of gmail when I closed and reopened the browser. What OS?

**Comment by snowbound** [comment] 2022-02-04 14:37
Windows10 Pro 21H2 Only have Beta and release version installed here.

**Comment by Miyayes** [comment] 2022-02-04 16:29
I was able to reproduce on 

```
Brave | 1.36.83 Chromium: 98.0.4758.87 (Official Build) beta (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 12.0.1 (Build 21A559)
```

STR:

1. Log into a Gmail account
2. Go to brave://settings/cookies and make sure "Clear cookies and site data when you close all windows" is toggled ON
3. Completely close the browser and restart the browser
4. Note how Gmail is still logged in and cookies are not deleted

**Notes:** Please note that @snowbound is asking about the (A) "Clear cookies and site data when you close all windows" toggle. There is _another_ setting, (B), that clears data upon browser close/exit: brave://settings/clearBrowserData > On exit. Make sure these are not being confused.

I tested (A) in the above.

**Comment by bridiver** [comment] 2022-02-04 16:59
@Miyayes I believe he is referring to "Always clear cookies when windows are closed" as I posted here https://github.com/brave/brave-browser/issues/9085#issuecomment-1029568336

There is no "clear on exit" settings, but it may have been called that when the issue was filed. Is that correct @snowbound ?

**Comment by snowbound** [comment] 2022-02-04 17:16
Correct

![image](https://user-images.githubusercontent.com/596147/152573094-5787edee-9a73-4f40-953f-368423136f95.png)

**Comment by Miyayes** [comment] 2022-02-04 17:43
I was able to reproduce on Nightly with: 

```
Brave | 1.37.26 Chromium: 98.0.4758.87 (Official Build) nightly (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 12.0.1 (Build 21A559)
```

![image](https://user-images.githubusercontent.com/11497541/152577016-4f875de4-d5bb-425b-91bf-3e8205db101c.png)

**Comment by bridiver** [comment] 2022-02-04 17:59
> I was able to reproduce on Nightly with:
> 
> ```
> Brave | 1.37.26 Chromium: 98.0.4758.87 (Official Build) nightly (x86_64)
> -- | --
> Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
> OS | macOS Version 12.0.1 (Build 21A559)
> ```
> 
> Even when this was set:
> 
> ![image](https://user-images.githubusercontent.com/11497541/152577016-4f875de4-d5bb-425b-91bf-3e8205db101c.png)

That's interesting because with `[*.]google.com` @rebron reported that he couldn't repro https://github.com/brave/brave-browser/issues/9085#issuecomment-830415247

@Miyayes can you post a video of your repro?

**Comment by snowbound** [comment] 2022-02-04 18:40
I have to make something clear. 

I DO NOT want to clear ALL the cookies from Google. Only the cookie that shows up in the list of all cookies as "Google.com" in the list of cookies. This is because if you use [*.]google.com it will delete all cookies including 2FA and other settings such as for YouTube etc.  Deleting the "Google.com" cookie  pictured here 

https://github.com/brave/brave-browser/issues/9085#issuecomment-1029616491

Will force a log out of Gmail accounts automatically upon browser closure or should. Two years ago both Chrome and MS Edge had no problem deleting this cookie.  In fact, I believe it is the HSID sub cookies that forces the logout 

![image](https://user-images.githubusercontent.com/596147/152584722-a5507832-9201-42b4-81fc-ab07a5b8181d.png)

**Comment by bridiver** [comment] 2022-02-04 20:04
So this appears to be caused by the google login setting in `brave://settings/socialBlocking`
![image](https://user-images.githubusercontent.com/34129/152595298-e810524f-91b4-426e-a327-e5c57c39edb5.png)
This setting is defaulted to enabled as a trade-off for webcompat, but may not be needed now that we have partitioned storage. Verifying this can be tricky because there are many different ways that sites can implement google login and this is only required for some of them. cc @pes10k

**Comment by snowbound** [comment] 2022-02-04 20:08
Nope, that toogle has always been off.

**Comment by bridiver** [comment] 2022-02-04 20:20
> @bridiver nope, that toogle has always been off.

@Miyayes was testing with the wrong value `[*.]google.com`, he's checking again now with `google.com`

**Comment by bridiver** [comment] 2022-02-04 20:43
@snowbound when you restart the browser, do you still have a gmail tab open? Does the same thing happen if you close any open gmail tabs before closing the browser?

**Comment by snowbound** [comment] 2022-02-04 23:31
@bridiver no tabs are automatically open on browser startup. I use an extension Session Buddy to restore the tabs open when it last saved the open tabs. That process is manual. I click on Session Buddy select the last saved session and restore the tabs in the current blank window which is a NEW TAB.

**Comment by bridiver** [comment] 2022-02-04 23:35
@snowbound do you have that extension installed on Chrome as well? I haven't heard back from @Miyayes yes about his results with the correct domain, but I'd like to make sure we're eliminating any extensions as a possible part of the problem.

**Comment by bridiver** [comment] 2022-02-04 23:37
also I assume based on your other preferences that you have google auto sign in disabled on Chrome?

**Comment by snowbound** [comment] 2022-02-05 00:57
@bridiver correct Google uses 2FA and Chrome is set to open a new tab on start up and session buddy used there as well. When the tabs are restored I have to login to the 2 Gmail accounts.

**Comment by ShivanKaul** [comment] 2024-06-17 22:01
The Settings UI has gone through several iterations since this issue was reported, we've gotten rid of the global Google Login button. I'm not sure what exactly the ask here is at this point, will close it out. We also have plans to remove the cookie detail page: https://github.com/brave/brave-browser/issues/39033

**Closed by ShivanKaul** 2024-06-17 22:01 UTC
Labels: priority/P3, feature/cookies, Chromium/waiting upstream, Chromium/reported upstream
