### ISSUE TITLE
Follow up to #10771 - purchaseIntentSignalHistory is not extracted for `https://fusafusaraifusutairu.blogspot.jp`

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#14528] opened 2021-03-06 13:48 UTC
Follow up to: #10771

## Steps to Reproduce

Note: Steps from #10771

   1. Set OS locale to Japan
   2. Launch brave 
   3. Enable rewards and open `https://fusafusaraifusutairu.blogspot.jp/` in a new tab
   4. Wait until page is loaded fully
   5. Open `client.json` and look for purchaseIntentSignalHistory
   6. purchaseIntentSignalHistory is empty 

Note  `https://fusafusaraifusutairu.blogspot.jp/` is listed in the component

## Actual result:

purchaseIntentSignalHistory is empty `"purchaseIntentSignalHistory": {},`
![image](https://user-images.githubusercontent.com/34715963/110208868-dd19b180-7e89-11eb-8648-6bca18aba2e4.png)

## Expected result:
purchaseIntentSignalHistory is not empty

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.22.53 Chromium: 89.0.4389.72 (Official Build) beta (64-bit)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @moritzhaller @jsecretan @rebron @tmancey

**Comment by iambrianfung** [comment] 2021-04-21 19:36
i happened to stumble on this. but it looks like that `https://fusafusaraifusutairu.blogspot.jp` does a 302 redirect to `https://fusafusaraifusutairu.blogspot.com`
<img width="1544" alt="Screen Shot 2021-04-21 at 15 33 40" src="https://user-images.githubusercontent.com/24831890/115610719-3f523880-a2b7-11eb-91de-6f0d618d687e.png">

**Comment by tmancey** [comment] 2021-05-14 16:11
Closing issue as caused by a redirect. Please use URLs that do not redirect. Thanks

**Closed by tmancey** 2021-05-14 16:11 UTC
Labels: OS/Desktop, QA/Test-Plan-Specified, QA/Yes, bug, closed/wontfix, feature/ads, release-notes/exclude
