### ISSUE TITLE
[ads] Transition challenge-bypass-ristretto from FFI to CXX

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#32767] opened 2023-09-05 19:22 UTC

**Comment by tmancey** [comment] 2023-10-08 15:32
@aseren is this a duplicate of https://github.com/brave/brave-browser/issues/25938? thanks

**Comment by tmancey** [comment] 2023-10-25 12:59
@aseren I am closing this (as above) as a duplicate of https://github.com/brave/brave-browser/issues/25938

**Closed by tmancey** 2023-10-25 12:59 UTC
Labels: closed/duplicate, dev-concern, QA/Yes, release-notes/exclude, feature/ads, OS/Desktop
