### ISSUE TITLE
links inside welcome screen should open in another tab

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#1781] opened 2018-10-22 19:40 UTC
🦁

**Comment by NejcZdovc** [comment] 2018-10-22 19:41
this is dupe of https://github.com/brave/brave-browser/issues/1739

**Closed** 2018-10-22 19:45 UTC
Labels: about-pages/welcome

**Comment by srirambv** [comment] 2018-10-26 15:03
Verification Passed on 

Brave | 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux

* Verified all links in welcome screen open in individual new tabs

**Comment by bbondy** [comment] 2018-10-30 15:18
Updated milestone to hotfix2 since this will be included in 0.55.x hotfix2.

**Comment by kjozwiak** [comment] 2018-10-30 18:53
Clearing flags as we'll need to check this with the new RC2 just incase. Should be a quick verifcation either way.

**Comment by btlechowski** [comment] 2018-10-30 19:04
Verification Passed on


Brave | 0.55.22 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows 7 x64
