### ISSUE TITLE
Alignment issue for `Monthly Contributions` in BR panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7523] opened 2019-12-26 14:37 UTC
## Description 

Found while testing #7093 
Alignment issue for `Monthly Contributions` in BR panel

## Steps to Reproduce

   1. Clean profileBravebeta 1.2.35 staging env with reconcile flag
   2. Send one-time and monthly tips to verified pubs 
   3. Wait for auto contribution to complete
   4. Click on a-c notification, alignment issue for `Monthly Contributions` 

## Actual result:

Alignment issue for `Monthly Contributions` in BR panel

![image](https://user-images.githubusercontent.com/38657976/71479626-2ba9d580-281b-11ea-805c-63b865e04cff.png)
![image](https://user-images.githubusercontent.com/38657976/71479648-49773a80-281b-11ea-9e19-27a41b7572c2.png)

## Expected result:
`Monthly Contributions` should be aligned in BR panel

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.2.36 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @NejcZdovc @brave/legacy_qa @rebron

**Comment by NejcZdovc** [comment] 2019-12-26 14:47
closing as dupe of https://github.com/brave/brave-browser/issues/7198

**Closed by NejcZdovc** 2019-12-26 14:47 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/rewards
