### ISSUE TITLE
White background causes issues with top site icons

### ISSUE THREAD

**Issue by TheCultLeader666** [brave/brave-browser#14929] opened 2021-03-24 19:34 UTC
## Description 
Some websites have favicons that inherit the browser's theme, so that they are easy to see. However, since top sites use the favicons of webpages, and top sites have a white background, sites which use white favicons to look good in a dark theme (namely GitHub), just appear as a white square.

## Steps to Reproduce

   1. Visit GitHub enough to get it into your top sites/Add it manually in Brave Beta
   2. Notice that the icon is the exact same color as the background
   3. Be confused every time you open a new tab and go to open GitHub

## Actual result:

![Screen Shot 2021-03-24 at 15 24 42](https://user-images.githubusercontent.com/65368815/112371565-1d17cb80-8cb5-11eb-87b8-b3ec0b23f7d2.png)

## Expected result:
The background of top sites could change with the browser theme, the background could be gray, or you could have the option to provide custom icons

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave: 1.23.48 Chromium: 89.0.4389.90 (Official Build) beta (x86_64)
Revision: 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS: macOS Version 11.3 (Build 20E5210c)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
Yes
- Can you reproduce this issue with the nightly channel? 
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
N/A

**Comment by bsclifton** [comment] 2021-03-25 15:51
Closing as this issue is a duplicate of https://github.com/brave/brave-browser/issues/14453

The good news: this was recently fixed by @simonhong with https://github.com/brave/brave-core/pull/8339 😄 The fix will be in the next Nightly build and will work its way through the channels

**Closed by bsclifton** 2021-03-25 15:51 UTC
Labels: OS/Desktop
