### ISSUE TITLE
Spotify web player crashes every 10 minutes

### ISSUE THREAD

**Issue by uNetworkingAB** [brave/brave-browser#40311] opened 2024-08-06 17:29 UTC
### Description

I'm listening to Spotify web player without any addons, or any kind of modification, just vanilla Brave on Windows 11 and Brave keeps crashing every 10 minutes. I get the "oops" process crash (only the tab crashes).

### Steps to reproduce

1. Listen to Spotify
2. Wait 10 minutes
3. Crash under your debugger of choice

### Actual result

Crashes all the time

### Expected result

Google Chrome does not crash

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave is up to date
[Version 1.68.134 Chromium: 127.0.6533.88 (Official Build) (64-bit)](https://brave.com/latest/)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment] 2024-08-06 20:56
@uNetworkingAB Can you go into brave://crashes/ and send the report and paste the crash ID into this issue when you get a chance?

**Comment by uNetworkingAB** [comment] 2024-08-06 21:13
```
Crashes
Crash reporting is disabled.
Crash reporting is not available in Brave.

Crashes (25)
 Show developer details
Crash from Tuesday, August 6, 2024 at 8:39:31 PM
Status:	Not uploaded
Local Crash Context:	915567d9-2a30-4623-beea-99b40f3d2c70
Crash from Tuesday, August 6, 2024 at 7:55:13 PM
Status:	Not uploaded
Local Crash Context:	15098e48-b8dd-4425-9c85-943a8cfd5e96
Crash from Tuesday, August 6, 2024 at 7:26:54 PM
Status:	Not uploaded
Local Crash Context:	3962ae1b-4461-4313-bca2-fe7bf3dd020d
Crash from Tuesday, August 6, 2024 at 7:05:05 PM
Status:	Not uploaded
Local Crash Context:	1dee86b1-4c1d-4d9d-82e8-be857d4b3a2c
Crash from Tuesday, August 6, 2024 at 6:43:04 PM
Status:	Not uploaded
Local Crash Context:	41b76fc4-96cb-47ef-82bc-e2eabb0d12d0
Crash from Tuesday, August 6, 2024 at 6:21:43 PM
Status:	Not uploaded
Local Crash Context:	e8ff3665-3e89-430a-a454-770204e1f447
Crash from Tuesday, August 6, 2024 at 5:58:47 PM
Status:	Not uploaded
Local Crash Context:	4e366cab-ed0d-4c08-969d-32c9a4efb86d

```

**Comment by uNetworkingAB** [comment] 2024-08-06 21:18
Let me send you some new crashes tomorrow

**Comment by uNetworkingAB** [comment] 2024-08-08 03:13
Crash from Thursday, August 8, 2024 at 5:10:30 AM
Status:	Not uploaded
Local Crash Context:	060dcf6c-1ac1-4697-9d6d-0c879d2a4e7f

**Comment by uNetworkingAB** [comment] 2024-08-08 03:14
That one is without Brave shields. But it crashes with shields also. It tends to happen when you swap tab into Spotify, but does not require that to happen. It crashes every 20 minutes or so.

**Comment by uNetworkingAB** [comment] 2024-08-08 03:47
Status:	Uploaded
Uploaded Crash Report ID:	aacb0100-15c1-690c-0000-000000000000
Upload Time:	Thursday, August 8, 2024 at 5:25:33 AM

**Comment by uNetworkingAB** [comment] 2024-08-14 14:02
Can re-confirm that it does not happen on Google Chrome on either platform, only Brave

**Comment by danielbahrami** [comment] 2024-08-31 21:56
@rebron I also experience this problem, and have experienced it for many months. Both on Windows 11 and macOS.

The crash seems to be caused by a memory leak. While playing music, the tab for Spotify will consume more and more memory until Brave eventually can’t consume more. Hence crashing the Spotify tab. This behavior can be observed by enabling the setting “Show memory usage on tab hover preview card” in brave://settings/appearance

I however noticed that the memory leak only occurs while the Spotify tab isn’t the active tab. If you switch back to the Spotify tab, then the memory will be released again.

**Comment by uNetworkingAB** [comment] 2024-08-31 22:02
Yes that sounds very similar to my issue. I have Spotify web player in the background while doing other things and when I switch back to it, it crashes with high probability. But it also crashes on its own (while being non-active tab)

**Comment by iefremov** [comment] 2024-09-27 17:50
closing as duplicate https://github.com/brave/brave-browser/issues/40311

**Closed by iefremov** 2024-09-27 17:50 UTC
Labels: crash, OS/Windows, priority/P2, OS/Desktop
