### ISSUE TITLE
Brave crashes on various Linux ARM64 at launch

### ISSUE THREAD

**Issue by chaimleib** [brave/brave-browser#34120] opened 2023-11-05 09:53 UTC
EDIT: This ticket was originally opened for Asahi Arch Linux running on a MacBook M1 Pro, but the same segfault has been found #34118 on Asahi Ubuntu Linux; and https://github.com/brave/brave-browser/issues/34120#issuecomment-1802575209 Raspberry Pi 400 Ubuntu Jammy and Nintendo Switch Ubuntu Bionic; and #34106 Ubuntu 22.04 ARM64.

## Description 
Brave crashes on startup, without showing a window.

## Steps to Reproduce

   1. `yay -S brave-bin`
   2. `brave`

## Actual result:
```
% brave
[24581:24581:1105/012933.507684:ERROR:policy_logger.cc(157)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled.
[24620:24620:1105/012933.549031:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[24620:24620:1105/012933.549112:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[24620:24620:1105/012933.549144:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[24620:24620:1105/012933.549185:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[24620:24620:1105/012933.549218:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[24620:24620:1105/012933.549245:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[24620:24620:1105/012933.549273:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[24620:24620:1105/012933.549309:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[24620:24620:1105/012933.549692:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[24620:24620:1105/012933.549733:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[24620:24620:1105/012933.549764:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[24620:24620:1105/012933.549793:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[24620:24620:1105/012933.549822:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[24620:24620:1105/012933.549850:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[24620:24620:1105/012933.549879:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[24620:24620:1105/012933.549908:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[1105/012933.555410:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/012933.555461:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/012933.555710:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/012933.556079:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/012933.557346:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/012933.557368:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/012933.557641:ERROR:elf_dynamic_array_reader.h(64)] tag not found
zsh: segmentation fault (core dumped)  brave
```

No window shows.

## Expected result:
Shows window.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
```
% brave --version
Brave Browser 119.1.60.110
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? **Yes**
- Can you reproduce this issue with the beta channel? **Yes**
- Can you reproduce this issue with the nightly channel? **Yes**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No

**Comment by chaimleib** [comment] 2023-11-06 02:16
I also tested the dev branch:

```bash
% curl -LO https://github.com/brave/brave-browser/releases/download/v1.61.63/brave-browser-dev-1.61.63-linux-arm64.zip
% mkdir brave-dev
% cd brave-dev
% unzip ../brave-browser-dev-1.61.63-linux-arm64.zip

% ./brave --version
Brave Browser 119.1.61.63 unknown

% ./brave
[120386:120386:1105/191348.700138:ERROR:policy_logger.cc(157)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled.
[1105/191348.746352:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/191348.746402:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/191348.746643:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/191348.746999:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/191348.748236:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/191348.748257:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/191348.748515:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[120426:120426:1105/191348.749056:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[120426:120426:0100/000000.753222:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[120426:120426:0100/000000.241214:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[120426:120426:0100/000000.241235:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[120426:120426:0100/000000.241248:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[120426:120426:0100/000000.241260:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[120426:120426:0100/000000.241271:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[120426:120426:0100/000000.241281:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
zsh: segmentation fault (core dumped)  ./brave
[120426:120426:0100/000000.241785:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)              
[120426:120426:0100/000000.242008:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[120426:120426:0100/000000.242021:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[120426:120426:0100/000000.242032:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[120426:120426:0100/000000.242042:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[120426:120426:0100/000000.242053:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[120426:120426:0100/000000.242065:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[120426:120426:0100/000000.242076:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
```

**Comment by chaimleib** [comment] 2023-11-06 02:25
Here's nightly:

```bash
% curl -LO https://github.com/brave/brave-browser/releases/download/v1.62.24/brave-browser-nightly-1.62.24-linux-arm64.zip && mkdir brave-nightly && cd brave-nightly && unzip ../brave-browser-nightly-1.62.24-linux-arm64.zip

% ./brave --version
Brave Browser 119.1.62.24 unknown

% ./brave
[122588:122588:1105/192414.622110:ERROR:policy_logger.cc(157)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled.
[122628:122628:1105/192414.666284:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[122628:122628:1105/192414.666343:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[122628:122628:1105/192414.666365:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[122628:122628:1105/192414.666382:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[122628:122628:1105/192414.666398:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[122628:122628:1105/192414.666414:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[122628:122628:1105/192414.666432:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[122628:122628:1105/192414.666447:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[122628:122628:1105/192414.666785:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[122628:122628:1105/192414.666805:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[122628:122628:1105/192414.666821:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[122628:122628:1105/192414.666837:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[122628:122628:1105/192414.666854:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[122628:122628:1105/192414.666869:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[122628:122628:1105/192414.666885:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[122628:122628:1105/192414.666901:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[1105/192414.676508:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/192414.676555:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/192414.676799:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/192414.677152:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/192414.678411:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/192414.678432:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/192414.678684:ERROR:elf_dynamic_array_reader.h(64)] tag not found
```

**Comment by chaimleib** [comment] 2023-11-06 02:30
Beta:
```bash
% curl -LO https://github.com/brave/brave-browser/releases/download/v1.61.61/brave-browser-beta-1.61.61-linux-arm64.zip && mkdir brave-beta && cd brave-beta && unzip ../brave-browser-beta-1.61.61-linux-arm64.zip

% ./brave --version
Brave Browser 119.1.61.61 unknown

% ./brave
[123099:123099:1105/193001.183219:ERROR:policy_logger.cc(157)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled.
[123139:123139:1105/193001.225452:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[123139:123139:1105/193001.225514:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[123139:123139:1105/193001.225537:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[123139:123139:1105/193001.225554:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[123139:123139:1105/193001.225571:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[123139:123139:1105/193001.225594:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[123139:123139:1105/193001.225613:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[123139:123139:1105/193001.225630:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[123139:123139:1105/193001.225995:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[123139:123139:1105/193001.226016:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[123139:123139:1105/193001.226034:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[123139:123139:1105/193001.226050:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[123139:123139:1105/193001.226066:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[123139:123139:1105/193001.226081:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[123139:123139:1105/193001.226097:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[123139:123139:1105/193001.226112:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[1105/193001.230740:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/193001.230788:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/193001.231025:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/193001.231383:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/193001.232612:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/193001.232633:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1105/193001.232885:ERROR:elf_dynamic_array_reader.h(64)] tag not found
```

**Comment by chaimleib** [comment] 2023-11-06 02:44
I was able to get this one working:
https://github.com/brave/brave-browser/releases/download/v1.59.124/brave-browser-1.59.124-linux-arm64.zip

**Comment by chaimleib** [comment] 2023-11-06 02:56
On the v1.60.x series, I was able to get v1.60.1 working, but v1.60.3 is broken. There was no arm64 binary released for v1.60.2.

OK: https://github.com/brave/brave-browser/releases/tag/v1.60.1
Bad: https://github.com/brave/brave-browser/releases/tag/v1.60.3

**Comment by theofficialgman** [comment] 2023-11-08 20:09
confirmed segfaulting on all arm64 hardware current (all previously worked).
Tested on Raspberry Pi 400 (ARM64 Ubuntu Jammy) and Nintendo Switch (Tegra X1 ARM64 Ubuntu Bionic)

@chaimleib you can change the title to brave segfaults on ARM64 since it is no Asahi or Arch specific

**Comment by theofficialgman** [comment] 2023-11-09 00:18
also wanted to confirm that this is NOT an upstream chromium bug. I have built the latest stable (119.0.6045.123) chromium release https://chromiumdash.appspot.com/releases?platform=Linux and have no issues.

**Comment by chaimleib** [comment] 2023-11-09 00:32
The latest Chromium works fine for me too.
```bash
% chromium --version
Chromium 119.0.6045.123 Arch Linux ARM

% chromium
[287885:287885:1108/173206.264306:ERROR:policy_logger.cc(157)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled.
[287933:287933:1108/173206.413929:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[287933:287933:1108/173206.414124:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[287933:287933:1108/173206.414156:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[287933:287933:1108/173206.414185:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[287933:287933:1108/173206.414211:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[287933:287933:1108/173206.414236:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[287933:287933:1108/173206.414260:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[287933:287933:1108/173206.414286:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[287933:287933:1108/173206.414683:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[287933:287933:1108/173206.414711:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[287933:287933:1108/173206.414737:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[287933:287933:1108/173206.414766:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[287933:287933:1108/173206.414795:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[287933:287933:1108/173206.414820:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[287933:287933:1108/173206.414845:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[287933:287933:1108/173206.414870:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[287933:287933:1108/173206.498575:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[287933:287933:1108/173206.508152:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[287933:287933:1108/173206.512008:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!

```

**Comment by chaimleib** [comment] 2023-11-09 00:44
The new brave release today also crashes at launch:
```
% ./brave --version
Brave Browser 119.1.60.114 unknown

% ./brave          
[289163:289163:1108/174242.575031:ERROR:policy_logger.cc(157)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled.
[289202:289202:1108/174242.618137:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[289202:289202:1108/174242.618237:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[289202:289202:1108/174242.618258:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[289202:289202:1108/174242.618275:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[289202:289202:1108/174242.618295:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[289202:289202:1108/174242.618320:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[289202:289202:1108/174242.618335:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[289202:289202:1108/174242.618349:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[289202:289202:1108/174242.618725:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[289202:289202:1108/174242.618746:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[289202:289202:1108/174242.618772:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[289202:289202:1108/174242.618795:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[289202:289202:1108/174242.618817:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[289202:289202:1108/174242.618836:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[289202:289202:1108/174242.618873:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[289202:289202:1108/174242.618902:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[1108/174242.630933:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1108/174242.631002:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1108/174242.631270:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1108/174242.631663:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1108/174242.633011:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1108/174242.633033:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1108/174242.633303:ERROR:elf_dynamic_array_reader.h(64)] tag not found
zsh: segmentation fault (core dumped)  ./brave
```

**Comment by chaimleib** [comment] 2023-11-10 17:49
This repository only has git checkout scripts and configuration data. The main code is in brave-core. There are only a few commits between the working 1.60.1 and 1.60.3, so a git bisect should be possible to track down which commit broke support for ARM64.

https://github.com/brave/brave-core/tree/v1.60.3

Unfortunately, my machine is not running Ubuntu, so I'd have to set up another environment in Docker or something to compile brave. I hope not having an Intel machine won't be a problem, but it looks like setup would take time for me.

**Comment by aneeshlingala** [comment] 2023-11-11 18:36
This issue is also happening to me when running Debian on my ARM Chromebook.

**Comment by chaimleib** [comment] 2023-11-12 02:44
Apparently I can't easily emulate an Intel machine using ARM64 Asahi Arch Linux. I tried installing qemu and virtualbox via pacman/yay, but neither of those would install the things I needed to emulate Intel. I've had a few false starts with Docker, maybe third time's the charm?

**Comment by SergeyZhukovsky** [comment] 2023-11-14 16:11
fixed in the context of https://github.com/brave/brave-browser/issues/33596

**Closed by SergeyZhukovsky** 2023-11-14 16:11 UTC
Labels: closed/duplicate, OS/Desktop
