### ISSUE TITLE
Incorrect title and option selected when closing tabs in background

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#41320] opened 2024-10-01 16:17 UTC
### Description

Incorrect title and option selected when closing tabs in background

### Steps to reproduce

1. Clean profile
2. Open Tab 1 and select Leo from URL bar or on sidebar 
3. Loads Leo optin screen in the tab
4. Open Tab 2 and select Sidebar from URL bar, loads Leo in the second tab 
5. Switch to Reading list in Tab 2 from sidebar
6. Open Tab 3 and select Sidebar, loads Reading list 
7. Close Tab2 in background and switch focus to Tab 1
8. Shows Reading list but Leo button is focused in Side bar
9. Repeat the same steps Leo AI is shown in title when reading list is opened

### Actual result

https://github.com/user-attachments/assets/c4f0a3d0-7afb-48bc-985e-11f1afde2d34

### Expected result

Should show the correct item in sidebar

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.71.102 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | d901535b1091c5f39eb2b5426b8fa8e7f3c5edf0
OS | Windows 11 Version 23H2 (Build 22631.4169)

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @bsclifton @rebron @mkarolin

**Comment by mkarolin** [comment] 2024-10-01 18:14
I think https://github.com/brave/brave-core/pull/25679 should take care of this. cc: @simonhong

**Comment by rebron** [comment] 2024-11-13 22:04
Closed with https://github.com/brave/brave-core/pull/25679 and fixed in this version https://github.com/brave/brave-core/pull/25679#issuecomment-2407270149.

Go ahead and reopen @srirambv if still an issue.

**Comment by rebron** [comment] 2024-11-13 22:05
dupe of https://github.com/brave/brave-browser/issues/41154

**Closed by rebron** 2024-11-13 22:04 UTC
Labels: bug, QA/Yes, release-notes/exclude, OS/Desktop, feature/sidebar
