### ISSUE TITLE
chrome.declarativeNetRequest.updateDynamicRules 

### ISSUE THREAD

**Issue by Sp0kzz** [brave/brave-browser#34799] opened 2023-12-08 16:21 UTC
When are you gonna fix the issue where all extensions that have this in the worker.js/background.js need to be restarted every time the browser is launched ? it's been months and still no fix ?? 
https://github.com/brave/brave-browser/issues/30854

i think this should be prioritized over some shitty ai assistant and more bloat added every update

**Comment by rebron** [comment] 2023-12-08 21:20
Closing as dupe of https://github.com/brave/brave-browser/issues/30854. Can follow progress in that issue unless a different follow-up issue is created.

**Closed by rebron** 2023-12-08 21:20 UTC
Labels: OS/Desktop
