### ISSUE TITLE
Brave crashed when the user clicked on the `Brave VPN` menu option via the Hamburger menu in a Brave VPN enabled profile

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#41084] opened 2024-09-16 11:24 UTC
### Description

Brave crashed when the user clicked on the `Brave VPN` menu option via the Hamburger menu in a Brave VPN enabled profile

### Steps to reproduce

1. Clean profile `1.70.111`
2. Enable Brave VPN
3. Click on the `Brave VPN` menu option via Hamburger menu

### Actual result

Brave crashed

```
Uploaded Crash Report ID:	42291100-9ce4-970c-0000-000000000000
Upload Time:	Monday, September 16, 2024 at 12:50:50 PM
```

### Expected result

should not be any crash

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.70.111 Chromium: 129.0.6668.42 (Official Build) (64-bit)
-- | --
Revision | 91de01e6c866fe9e10c8262e47cc8c292c792de1
OS | Windows 10 Version 22H2 (Build 19045.4894)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @mattmcalister @rebron

**Comment by rebron** [comment] 2024-09-16 17:05
My crash ID: 1afa1200-9ce4-970c-0000-000000000000

Using:

Brave | 1.71.87 Chromium: 129.0.6668.42 (Official Build) beta (arm64)
-- | --
Revision | 5c708d5d9bcfc56422a4c7356708ff1d5cce9df5
OS | macOS Version 15.0 (Build 24A5298h)
JavaScript | V8 12.9.202.16
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

**Comment by bsclifton** [comment] 2024-09-16 23:48
I'm suspecting that https://chromium-review.googlesource.com/c/chromium/src/+/5822648 is the root cause

Basically, there was this issue being tracked upstream https://issues.chromium.org/issues/40232718

This line is what causes the recursion (causing the freeze/crash):
https://github.com/brave/brave-core/blob/c398669775f2d2b545704132abf8678bc079e5ba/browser/ui/views/toolbar/brave_vpn_status_label.cc#L90

`GetHeightForWidth` was updated to call `CalculatePreferredSize` - which is the method we're in 😂

Working on a fix

**Comment by bsclifton** [comment] 2024-09-17 00:07
OK found a solution

The `CalculatePreferredSize` was put in place to solve a UI bug:
https://github.com/brave/brave-browser/issues/22742
![disconnecting](https://user-images.githubusercontent.com/387249/167328033-1048e63e-c6d5-4104-b24d-869f3f69f9a2.png)

The views code upstream must now be doing the calculation properly. When I remove this override, it looks correct now:
![image](https://github.com/user-attachments/assets/91193eef-c224-415d-8004-dd733364c759)

Will push a fix here soon to 1.70.x first - then to master

**Comment by kjozwiak** [comment] 2024-09-17 02:34
Closing as https://github.com/brave/brave-core/pull/25594 was merged into `1.70.x`. The above requires `1.70.114` or higher for `1.70.x` verification 👍

**Closed by kjozwiak** 2024-09-17 02:34 UTC
Labels: release/blocking, priority/P1, QA/Yes, release-notes/exclude, OS/Desktop, feature/vpn

**Comment by GeetaSarvadnya** [comment] 2024-09-17 10:17
Verification INPROGRESS on

```
Brave | 1.70.114 Chromium: 129.0.6668.42 (Official Build) (64-bit)
-- | --
Revision | 62ac7fa937404b201bf90c3848127b18e9d7a9b1
OS | Windows 10 Version 22H2 (Build 19045.4894)
```
**New user:**

**Existing user:**

**Comment by MadhaviSeelam** [comment] 2024-09-17 17:28
Verification `PASSED` using
```
Brave | 1.70.114 Chromium: 129.0.6668.42 (Official Build) (64-bit)
-- | --
Revision | 62ac7fa937404b201bf90c3848127b18e9d7a9b1
OS | Windows 11 Version 23H2 (Build 22631.4169)
```

**_New VPN subscriber_** 

1. Installed 1.70.114
2. launched Brave
3. opened account.bravesoftware.com in a new tab
4. subscribed to VPN as a new user (brave41084newuser@mailinator.com)
5. enabled VPN via VPN panel 
6. verified VPN connected to default region - USA (West)
7. clicked on the `Brave VPN` menu via Hamburger menu 
8. confirmed there is no crash happened
9. enabled/disabled Brave VPN via hamburger menu
10. verified Brave VPN worked as expected
11. opened whatismyipaddress.com in a new tab
12. switched to different region (Portugal) via VPN panel and ensured that region is changed successfully
13. opened whatismyipaddress.com and confirmed that the VPN connected region IP is shown correctly

step 6 | step 7 | step 12 | step 13 
----- | ----- | ----- | ----
![image](https://github.com/user-attachments/assets/47c56a44-c6aa-4c66-a59c-17f9636b259d)|![image](https://github.com/user-attachments/assets/3fcf9c44-bb81-4901-b32b-c3e1596324ed)|![image](https://github.com/user-attachments/assets/4b720a75-eb7c-4593-ab73-af815076c0a5)|![image](https://github.com/user-attachments/assets/0e6d450f-c49c-4758-93e3-ffa917476fbb)

**_Existing VPN Subscriber_**

1. Installed 1.70.114
2. launched Brave
3. opened account.bravesoftware.com in a new tab
4. subscribed to VPN as an existing (refresh39132vpn627@mailinator.com)
5. clicked Refresh Firewall + VPN button
6. clicked on the `Brave VPN` menu via Hamburger menu 
7. confirmed there is no crash happened
8. enabled/disabled Brave VPN via hamburger menu
9. verified VPN connected to default region - USA (West)
12. verified Brave VPN worked as expected
13. opened whatismyipaddress.com in a new tab
14. switched to different region (Ireland) via VPN panel and ensured that region is changed successfully
15. opened whatismyipaddress.com and confirmed that the VPN connected region IP is shown correctly

step 6 - 7 | step 8 | step 9 | step 15
--- | ---- | ---- | -----
![image](https://github.com/user-attachments/assets/469f0cd6-85ca-43a5-9cfd-40f6faad9333)|![image](https://github.com/user-attachments/assets/347eab29-bc9e-43bd-8c3c-af03b3133623)|![image](https://github.com/user-attachments/assets/505eaa5b-c40a-4c55-8bbd-046441e2ac9c)|![image](https://github.com/user-attachments/assets/c3aff036-dd50-49c4-ac3b-168fc8b37d88)

**_Upgrade_** 

1. Installed 1.69.168
2. launched Brave
3. logged into account.bravesoftware.com with basic auth
4. subscribed to VPN as a new user (vpn41084brave@mailinator.com)
5. enabled Brave VPN via VPN panel
6. clicked on the Brave VPN via Hamburger menu
7. verified Brave didn't crash
8. Brave VPN worked as expected when enabled/disabled
9. closed Brave
10. installed 1.70.114
11. relaunched Brave 
12. clicked on Brave VPN via hamburger menu
13. confirmed Brave didn't crash
16. enabled/disabled Brave VPN via hamburger menu
17. verified Brave VPN worked as expected
18. opened whatismyipaddress.com in a new tab
19. switched to different region via VPN panel and ensured that region is changed successfully
20. opened whatismyipaddress.com and confirmed that the VPN connected region IP is shown correctly

step 1| step 7- 8| step 10 | step 12| step 18 
----- | ----- | ---- | ----- | -----
![image](https://github.com/user-attachments/assets/54c04dcb-5507-4b5c-a6e9-1f0d16109e93)|![image](https://github.com/user-attachments/assets/6143b5c0-e1e7-47ea-8d7b-1e96ff387ca3)|![image](https://github.com/user-attachments/assets/587e3df0-704b-4b06-98e9-f05e4e106dfc)|![image](https://github.com/user-attachments/assets/11d0b256-fe46-44df-ac33-c9503a9464c9)|![image](https://github.com/user-attachments/assets/94417caa-2a3f-4140-83a5-17e9f26b5c72)

**Comment by MadhaviSeelam** [comment] 2024-09-18 00:17
Verification `In progress` using
```
Brave | 1.70.114 Chromium: 129.0.6668.42 (Official Build) (arm64)
-- | --
Revision | 62ac7fa937404b201bf90c3848127b18e9d7a9b1
OS | macOS Version 14.6.1 (Build 23G93)
```

<details>
<summary>New VPN subscriber</summary>

1. Installed 1.70.114
2. launched Brave
3. opened account.bravesoftware.com in a new tab
4. subscribed to VPN as a new user (brave41084macosvpn@mailinator.com)
5. clicked VPN button and toggled on via VPN panel
6. clicked Allow
7. verified VPN connected to default region - USA (West)
8. clicked on the `Brave VPN` menu via Hamburger menu 
9. confirmed there is no crash happened
10. enabled/disabled Brave VPN via hamburger menu
11. verified Brave VPN worked as expected
12. opened whatismyipaddress.com in a new tab
13. switched to different region (Switzerland) via VPN panel and ensured that region is changed successfully
14. opened whatismyipaddress.com and confirmed that the VPN connected region IP is shown correctly

step 5-6 | step 7 | step 8 | step 10 | step 14 
----- | ----- | ----- | ---- | -----
![Screenshot at Sep 17 17-10-18](https://github.com/user-attachments/assets/3b07cf23-6d1b-49db-bdce-c8f836589ad1)|![Screenshot at Sep 17 17-10-33](https://github.com/user-attachments/assets/15c02d22-5dce-4eb7-b73b-9bc34ce94831)|![Screenshot at Sep 17 17-10-49](https://github.com/user-attachments/assets/f5e892de-8aa0-487b-96dc-1b4d5c61f5d6)|![Screenshot at Sep 17 17-11-03](https://github.com/user-attachments/assets/ae977806-84d9-4923-a391-2511618faed1)|![Screenshot at Sep 17 17-11-42](https://github.com/user-attachments/assets/c1b45a62-a3ed-4f11-9ab2-2d576ba2ea46)
