### ISSUE TITLE
Shields icon missing unless Reward icon is enabled

### ISSUE THREAD

**Issue by GNOMES** [brave/brave-browser#21843] opened 2022-03-24 11:58 UTC
## Description 

My Shields icon has disappeared in Brave Nightly for the past week now. The icon is only visable if I reenable the Rewards icon (was disabled).

Reinstalling the browser did not help

## Steps to Reproduce

   1. Disable Rewards
   2. Icon is missing

## Actual result:

Brave Shields icon should always be visable if enabled.

## Reproduces how often: 

No steps to reproduce

## Brave version (brave://version info)

Version 1.39.1 Chromium: 100.0.4896.46 (Official Build) nightly (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment] 2022-03-24 20:36
Closing as duplicate of https://github.com/brave/brave-browser/issues/21830

**Closed by rebron** 2022-03-24 20:36 UTC
Labels: OS/Desktop
