### ISSUE TITLE
Fix build dependency

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#8238] opened 2020-02-13 16:20 UTC
Build failed on CI with the following:
<pre>
23:51:44  ../../brave/browser/brave_browser_process_impl.h:14:10: fatal error: 'brave/components/brave_referrals/buildflags/buildflags.h' file not found
23:51:44  #include "brave/components/brave_referrals/buildflags/buildflags.h"
23:51:44           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
23:51:44  1 error generated.
</pre>

`brave/browser/BUILD.gn` needs to add a dependency on `//brave/components/brave_referrals/buildflags`

**Comment by bsclifton** [comment] 2020-02-14 04:37
Closing as a dupe of https://github.com/brave/brave-browser/issues/8249

Fix available here 😄 https://github.com/brave/brave-core/pull/4640

**Closed by bsclifton** 2020-02-14 04:37 UTC
Labels: QA/No, dev-concern, release-notes/exclude
