### ISSUE TITLE
Please add option to add custom background image upon opening the new tab

### ISSUE THREAD

**Issue by Amanraj13** [brave/brave-browser#13715] opened 2021-01-22 06:08 UTC
Please add an option of adding custom background image for tabs. The image that appears automatically is sometime very bright and does not looks good. 
So adding an option to add custom background image for tabs would help users and make the browser more personalised.

Thank You

**Comment by srirambv** [comment] 2021-01-22 07:10
Dupe of #5838

**Closed by srirambv** 2021-01-22 07:10 UTC
Labels: OS/Desktop
