### ISSUE TITLE
Motorola Moto phones failing to load websites in Brave

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#33941] opened 2023-10-26 16:44 UTC
## Description 
We've seen a strange uptick in Motorola phone users who are unable to fully load [most] websites in Brave while other browsers appear to work without issue. Namely, the text on websites appears to have trouble loading or the site/text will load, but then disappear shortly thereafter. 

![image](https://github.com/brave/brave-browser/assets/3299098/5ae369d3-7f4d-4494-babb-1ca331458f1b)

Reports of this have come in from Community, Zendesk and app store reviews.

## Issue reproduces how often 
Easily reproduced for those who have Motorola devices

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? YES
- Can you reproduce this issue with the current Play Store Beta version? NO
- Can you reproduce this issue with the current Play Store Nightly version? N/A

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12, 13
   
## Brave version
1.59.120

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? NO

### Additional information

https://community.brave.com/t/android-12-website-is-only-partally-visble/512385/2
https://community.brave.com/t/text-just-disappeared/511990/17
https://appfigures.com/reviews/266342430751L1dup1NNT_kMlTobSAOzU2g?lang=en
https://appfigures.com/reviews/266342430751L5BrqZgG1O0M-mVcsurpxzg?lang=en
https://appfigures.com/reviews/266342430751LGOdOYqe-GID9ZZ5upkqgrw?lang=en
https://appfigures.com/reviews/266342430751LfdEi6AZtk4fqtx0rFnbjSg?lang=en

**Comment by ronmin2023** [comment] 2023-10-27 19:02
I am have exact same problem I have tried the Beta and after a day the same problem.  It seems that after a reboot of phone, it works for about a day.

**Comment by ChristopherDocherty** [comment] 2023-10-28 14:13
I can also confirm this happened to me on the beta version as well, let me know if i can give any useful info to help you solve it :)

**Comment by Nikhar14** [comment] 2023-11-03 16:00
Same problem, kindly fix.

1 observation - Moto has secure folder option. If I add the app to that secure folder (which ten works as duplicate app, or kind of in different user profile - don't know how to say it technically), that version is working fine so far.

Please fix the issue Asap, as it is making the brave app completely unusable. Other version of Brave has the same issue.

Also, I think this issue is coming from last 2-3 weeks.

Phone Motorola G73

**Comment by ronmin2023** [comment] 2023-11-03 17:22
Brave browser wasn't showing images... I cleared all data from Brave Browser on Moto g power 5g 2023. including user data and it worked for 3 days until I synced my data again.  I only synced bookmarks.  Then Brave stopped showing images again.

So, I rebooted my phone, and Brave still does not show images unless I zoom-in to a site, then the images show.???

**Comment by thestonehead** [comment] 2023-11-09 07:51
This is resolved for me now. Haven't done anything special, the problem just went away.
Brave 1.60.110
Android T1TNS33.14-90-9-2
Motorola Moto G73 5G (XT2237-2)

**Comment by Nikhar14** [comment] 2023-11-09 13:08
That must be temporary, mine gets fixed for like 5mins after the app updates, and then back with the same issue

**Comment by thestonehead** [comment] 2023-11-13 14:44
Yup, went back to not working after a while.

**Comment by RpiController** [comment] 2023-11-14 21:18
Same problem as everyone else. Moto G Power 5G 2023... deleting app until it is resolved.

**Comment by SergeyZhukovsky** [comment] 2023-11-17 21:17
could someone who has a problem try to Enable or Disable that flag `brave://flags/#enable-vulkan`? Just type it in the URL bar.

**Comment by ronmin2023** [comment] 2023-11-17 22:23
Mine was enabled, so I disabled and not any difference.  I do note that by zooming in to a page, images that were not showing begin to show unless I zoom back to normal.

**Comment by SergeyZhukovsky** [comment] 2023-11-20 16:33
@ronmin2023 @dmmaz could you try to go to `brave://flags` into your browser's address bar and select reset all? That is going to reset all flags that you've set to their Default values.

**Comment by ronmin2023** [comment] 2023-11-20 16:41
I did the reset. Brave relaunched, but some images on a webpage only show when I zoom in. If I zoom back out, they disappear.

**Comment by SergeyZhukovsky** [comment] 2023-11-20 18:40
@ronmin2023 could you try to disable `brave://flags/#enable-image-reader`?

**Comment by RpiController** [comment] 2023-11-20 19:54
I don't know if it's related or just a coincidence... but the issue started happening for me right after I disabled "Private Compute Services" in android app settings under "system apps". I re-enabled it later but it didn't fix the problem.

**Comment by SergeyZhukovsky** [comment] 2023-11-20 21:17
> I don't know if it's related or just a coincidence... but the issue started happening for me right after I disabled "Private Compute Services" in android app settings under "system apps". I re-enabled it later but it didn't fix the problem.

I think it's just a coincidence, @RpiController do you mind trying that https://github.com/brave/brave-browser/issues/33941#issuecomment-1819610860?

**Comment by SergeyZhukovsky** [comment] 2023-11-21 17:12
@dmmaz with the `brave://flags/#enable-image-reader` disabled right?

**Comment by ronmin2023** [comment] 2023-11-22 13:54
OK @dmmaz , I disabled. So far so good. I will let you know if it worked  in a day or so.

**Comment by YarnaaH** [comment] 2023-11-22 17:13
Wow, I honestly thought it was my Moto causing problems, I've only had it for a week and this issue started. I'm guessing it's solely one for us Moto users. I'm not tech savvy so I'm hoping one for you guys can figure something out temporarily until Brave fixes the issue.

**Comment by YarnaaH** [comment] 2023-11-22 19:47
Just tried, still not working unfortunately. I contacted Brave support and
they said it's a known issue for Moto users, cause Brave works perfectly on
my Samsung Galaxy but that's my old phone with a broken screen, need it to
work on my Moto

**Comment by ryanbr** [comment] 2023-11-24 06:44
does disabling brave://flags/#disable-accelerated-2d-canvas make a difference?

**Comment by YarnaaH** [comment] 2023-11-24 10:12
Nope, did nothing unfortunately. The only thing that works for about 5 mins is if I completely turn my phone off and back on again, and that only last for a few minutes

**Comment by YarnaaH** [comment] 2023-11-24 12:35
> @dmmaz , I disabled brave://flags/#enable-image-reader. Brave worked for a few days then all of a sudden, stopped. To get it working again, I had to delete all data including user data.

I've deleted multiple times, I even factory reset my phone which I didn't mind because I've literally just bought it. And nothing has helped.

**Comment by NicolaArgos** [comment] 2023-11-28 05:59
Now every time i had this problem i would either disable or enable flags so i could **RELAUNCH** Brave. As i wouldn't have to delete my user data multiple times.
FYI It cant be fixed by disabling or enabling image reader flag or accelerated 2d canvas flags. FOR NOW you just have to **RELAUNCH** Brave everytime.

**Comment by YarnaaH** [comment] 2023-11-28 10:57
> Now every time i had this problem i would either disable or enable flags so i could **RELAUNCH** Brave. As i wouldn't have to delete my user data multiple times. FYI It cant be fixed by disabling or enabling image reader flag or accelerated 2d canvas flags. FOR NOW you just have to **RELAUNCH** Brave everytime.

I'm not very savvy with all this stuff lol. How do I relaunch? I've tried the entire disable stuff and that obviously hasn't work, I'm missing USING Brave now and this is frustrating

**Comment by YarnaaH** [comment] 2023-11-28 12:45
Ah I see! Yeah, it works temporarily for me, but not all the time so I'm just going to have to wait unfortunately until the issue is resolved by Brave, hopefully sometime soon.

**Comment by 1nt0** [comment] 2023-11-30 15:55
So still no fixes for us Moto users :(

**Comment by SergeyZhukovsky** [comment] 2023-11-30 17:15
I've got a G54 model yesterday and trying to replicate the problem on it. So far it works great for now. It would be helpful if anyone could share some info on how to get it triggered faster

**Comment by YarnaaH** [comment] 2023-11-30 17:22
> I've got a G54 model yesterday and trying to replicate the problem on it. So far it works great for now. It would be helpful if anyone could share some info on how to get it triggered faster.

I'm not entirely sure what causes mine. I've been using web WhatsApp that triggers is sometimes or when I go to certain websites to watch things or simple sites. I've literally only used those 3 on Brave and it seems to trigger if I do not close the tabs or it will randomly start to glitch

**Comment by Brave-Matt** [comment] 2023-11-30 17:30
Another user reporting this behavior (using Moto G Power 5G):
https://community.brave.com/t/no-websites-render-with-or-without-shields/518342/7

**Comment by ronmin2023** [comment] 2023-11-30 20:21
I've got a G54 model yesterday and trying to replicate the problem on it. So far it works great for now. It would be helpful if anyone could share some info on how to get it triggered  #faster.

For me, it seems like it would start bad behavior after I  Synced with my other devices. Then, to get it to work again, I had to delete all my cache and user data.

**Comment by YarnaaH** [comment] 2023-11-30 20:42
> I've got a G54 model yesterday and trying to replicate the problem on it. So far it works great for now. It would be helpful if anyone could share some info on how to get it triggered #faster.
> 
> For me, it seems like it would start bad behavior after I Synced with my other devices. Then, to get it to work again, I had to delete all my cache and user data.

See with me, I've deleted, uninstalled, even went as far as factory reset (phones new so I didn't mind) and the bugs still happened. Has it been stable for you for a while? Mine has a habit of doing that for 24 to 48 hours before bugs start. I've also noticed, not sure if this is relevant or not, the less I use Brave the more stable the pages I have open stay.

**Comment by SergeyZhukovsky** [comment] 2023-11-30 22:16
![Screenshot_20231130-171255](https://github.com/brave/brave-browser/assets/12011303/79c615fa-739d-403a-b180-28ef76ce7769)

Anyone please disable the above flag in chrome://flags to get rid of that problem. I'm working on a fix that will auto apply to all affected models. But you can try that flag now to fix it.

**Comment by ronmin2023** [comment] 2023-11-30 22:21
OK--I'll try it.

**Comment by b-for** [comment] 2023-11-30 22:34
Appears to work. Have set my default browser back to Brave. Will see what happens the next days. But big thanks already for the support, Sergey!

**Comment by YarnaaH** [comment] 2023-12-01 01:03
It works for now, so far so good, if there's a change I'll come back

**Closed** 2023-12-01 18:57 UTC
Labels: bug, priority/P2, QA/Yes, release-notes/include, OS/Android

**Comment by RpiController** [comment] 2023-12-01 19:07
@SergeyZhukovsky Uhm, can you make it copy-pasteable at least? Gotta type it out one letter at a time...switching back and forth 20 times 🙄
