### ISSUE TITLE
Intermittent scrambled blue display

### ISSUE THREAD

**Issue by rshmhrj** [brave/brave-browser#13460] opened 2021-01-10 18:32 UTC
## Description 

Intermittently, some tabs go crazy and have a weird blue scrambled look to them.  Some times it is the full page, some times it is just part of the page. Opening a new tab may or may not result in it being scrambled.

## Steps to Reproduce

   1. Navigate to a page and wait.

## Actual result:

Please refer to [a few screenshots here](https://photos.app.goo.gl/LPAbiqnyodtejiRg9)

## Expected result:
No scrambling

## Reproduces how often: 

Extremely rare

## Brave version (brave://version info)

```
Brave | 1.18.77 Chromium: 87.0.4280.101 (Official Build) (x86_64)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | macOS Version 10.15.7 (Build 19H15)
```

## Version/Channel Information:

Have not tried in different channels or newer releases, but this has happened on previous versions as well.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Do not know -- haven't seen it happen

## Miscellaneous Information:

Extensions installed:
- 1Password extension (desktop app required)
- 1Password X – Password Manager
- better-onetab
- Meet Mute
**- Night Eye - Dark mode on any website**    (the interaction between Brave and Night Eye might be related?)
- Todoist for Gmail
- Video Speed Controller

**Comment by ryanbr** [comment] 2021-01-10 23:34
I would test with no extensions installed, and also disabling `Hardware acceleration` in `brave://settings/system` @rshmhrj

**Comment by rshmhrj** [comment] 2021-01-18 19:22
Disabled `Hardware acceleration` in `brave://settings/system` during a bout of scrambling last night.

Force quitting and restarting wasn't helping and disabling the extensions didn't seem to do much, so tried the `Hardware acceleration` switch and it seems to have cured it for now.

Will update again if it comes back.

**Comment by benmontour** [comment] 2021-01-25 14:21
Same issue here today. Multiple pages, not every page though. Startpage.com would reliably do it every time. Some others would not. Some would only do it after you started to scroll down the page a little ways.
Disabling Hardware Acceleration does resolve the issue.
System is MacBook Pro (16-inch, 2019) with AMD Radeon Pro 5300M 4GB & Intel UHD Graphics 630 1536 MB. 
Running macOS Catalina 10.15.7.
![scrambled](https://user-images.githubusercontent.com/8712103/105717923-51098700-5ee6-11eb-82e7-6cdeb1d4382d.png)

**Comment by benmontour** [comment] 2021-01-25 14:27
Upon further investigation this appears to be a rare issue with MBPs and Chromium based browsers.

https://discussions.apple.com/thread/251248169?page=9

https://support.google.com/chrome/thread/35828402?hl=en

**Comment by bsclifton** [comment] 2021-02-08 08:06
Thanks for the detailed report - and thanks for the assist (RE: turning off hardware acceleration) @ryanbr 😄 

I'm going to close this issue as a duplicate of https://github.com/brave/brave-browser/issues/3471

**Closed by bsclifton** 2021-02-08 08:06 UTC
Labels: OS/Desktop
