### ISSUE TITLE
adding favicons for custom chrome:// pages under Task Manager

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1278] opened 2018-09-26 02:04 UTC
## Description 

When viewing custom `chrome://` pages under the Task Manager, you'll notice that the favicons are blank. Shouldn't be hard to add favicons for these custom pages. Example of some pages affected:

* `chrome://newtab`
* `chrome://rewards`
* `chrome://adblock`
* `chrome://version`
* `chrome://welcome`

## Steps to Reproduce

   1. launch b-c and open `chrome://newtab`, `chrome://rewards`, `chrome://version`
   2. open the Task Manager and you'll notice the above processes are missing favicons

## Actual result:

<img width="573" alt="screen shot 2018-09-25 at 9 58 59 pm" src="https://user-images.githubusercontent.com/2602313/46052867-3ce2ce80-c10e-11e8-8b59-bddf5e935d29.png">

## Expected result:

Custom `chrome://` pages should have favicons associated with them.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (chrome://version info)

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Mac OS X (10.13.6 x64)

### Reproducible on current release:

Yes, currently reproducible under the current release which is `0.55.6 Chromium: 70.0.3538.16`. Also reproducible with the latest `master`:

Brave | 0.55.2 Chromium: 70.0.3538.22 (Developer Build) (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X (10.13.6 x64)

**Comment by LaurenWags** [comment] 2018-10-08 19:47
Looks like chrome://welcome now has a favicon. Perhaps due to https://github.com/brave/brave-browser/issues/584 ? Other pages still need favicons though.

![screen shot 2018-10-08 at 3 45 56 pm](https://user-images.githubusercontent.com/28145373/46630149-540fbc00-cb11-11e8-87d9-bb29293c7ad8.png)


Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

**Comment by GeetaSarvadnya** [comment] 2018-12-27 10:57
Favicon for welcome page is missing again in 0.59.12. Looks like regression issue. Logged  #2747
![image](https://user-images.githubusercontent.com/38657976/50477868-4e30c500-09f4-11e9-88f7-60ec8c7077ec.png)

**Comment by rossmoody** [comment] 2019-02-15 05:40
I'd like to help on this one but it feels a little like a moving target. Might be helpful to break the favicons needed out into their own issues.

**Comment by rwhitman2017** [comment] 2019-10-31 18:32
I'll go ahead and take a shot at this issue!

**Comment by bsclifton** [comment] 2019-11-05 05:15
@rwhitman2017 check out our [CONTRIBUTING.md](https://github.com/brave/brave-browser/blob/master/CONTRIBUTING.md) for help getting started - let us know if there's anything we can help with

**Comment by bsclifton** [comment] 2019-11-05 05:18
pulling up task manager now - seems this has been fixed. There are some default icons showing there (like a globe):
<img width="146" alt="Screen Shot 2019-11-04 at 10 17 23 PM" src="https://user-images.githubusercontent.com/4733304/68180440-f1c1fe80-ff50-11e9-85aa-a2caacb47a10.png">

Gonna close this out as it's fixed. @rwhitman2017 feel free to find another issue and reach out 😄

**Closed by bsclifton** 2019-11-05 05:18 UTC
Labels: design, feature/user-interface, good first issue, priority/P4
