### ISSUE TITLE
LightHouse auditing hangs on warmup. 

### ISSUE THREAD

**Issue by Dudecor3** [brave/brave-browser#7220] opened 2019-12-05 17:00 UTC
## Description 
When running audits on websites, when clicking 'run audits', lighthouse hangs on 'warming up' and does not continue to audit website. 

## Steps to Reproduce

   1. Open developer console (F12)
   2. Click on Audits tab. 
   3. Press 'Run Audits' and find that the pop up that runs the audits hangs on warm up.

## Actual result:

![image](https://user-images.githubusercontent.com/13198784/70255918-73d75a00-177f-11ea-899d-7c0a7564a1de.png)

## Expected result:
I expect to see an audit score for: 
    Performance, 
    Accessibility,
    Best Practices,
    SEO & PWA

![image](https://user-images.githubusercontent.com/13198784/70256283-23143100-1780-11ea-8799-0a470ee6e586.png)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)

## Other Additional Information:
- OS: Windows 10 Education: 1809, build 17763.864 / MacOS - Catalina 10.15.1
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by Dudecor3** [comment] 2019-12-05 17:01
If anyone could point me in the right direction in the code base, I'm more than happy to make a pull request and have a go at fixing this myself :)

**Comment by bsclifton** [comment] 2019-12-09 22:55
Thanks for the report, @Dudecor3! This is a duplicate of https://github.com/brave/brave-browser/issues/3199 which was recently fixed in version 1.3 and above (Developer channel and Nightly channel)

It'll be working its way through the other channels... you can fix by grabbing one of those versions and enabling Remote Debugging under brave://settings/privacy

Here's the fix:
https://github.com/brave/brave-core/pull/4044

**Closed by bsclifton** 2019-12-09 22:55 UTC
