### ISSUE TITLE
[Android] Suggestion : add deletion of history when exiting the browser

### ISSUE THREAD

**Issue by Gor3pig** [brave/brave-browser#9346] opened 2020-04-21 09:27 UTC
## Description 
Add deletion of history when exiting the browser : several Chromium-based browsers already do this. There is an option to delete history, cookies, etc. when leaving the browser.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment] 2020-04-21 09:39
Dupe of #6379

**Closed by srirambv** 2020-04-21 09:39 UTC
Labels: OS/Android
