### ISSUE TITLE
progressive web app crashes when moving window

### ISSUE THREAD

**Issue by bong0** [brave/brave-browser#9270] opened 2020-04-16 19:17 UTC
Searched for: "app move screen" - didn't find anything related

## Description 
When moving a PWA off the screen it was opened on, it disappears.
It disappears as well when moving the window /at all/ or clicking into the window.
(some websites support starting a website in native-looking standalone window)

## Steps to Reproduce

   1.  install https://crypt.ee/signin "app" (click plus in searchbar)
   2. open app
   3. move app to second monitor / click on it / drag window within same screen

## Actual result:
app disappears/crashes without notice

## Expected result:
app is visible on second screen now/does not disappear

## Reproduces how often: 
easily reproduced

## Brave version (brave://version info)
```
Brave | 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | macOS Version 10.15.3 (Build 19D76)
JavaScript | V8 8.0.426.30
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=DnsOverHttps,WebUIDarkMode,PasswordImport,SimplifyHttpsIndicator,MixedContentSiteSetting,AutoupgradeMixedContent,PassiveMixedContentWarning --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,LookalikeUrlNavigationSuggestionsUI,VideoPlaybackQuality --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
yes
- Can you reproduce this issue with the beta channel? 
did not test
- Can you reproduce this issue with the dev channel? 
did not test
- Can you reproduce this issue with the nightly channel? 
did not test

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
did not test
- Does the issue resolve itself when disabling Brave Rewards?
did not test
- Is the issue reproducible on the latest version of Chrome?  **NO**

**Comment by bsclifton** [comment] 2020-04-26 21:10
Duplicate of https://github.com/brave/brave-browser/issues/9006 - will give that a +1 😄

**Closed by bsclifton** 2020-04-26 21:10 UTC
Labels: crash, feature/pwa
