### ISSUE TITLE
Tab freezes when you drag it out creating a new window

### ISSUE THREAD

**Issue by Immow** [brave/brave-browser#19126] opened 2021-10-31 23:11 UTC
## Description 
When I drag a tab from the brave browser out, creating a new window it freezes in place. The only way to make Brave respond again is by pressing escape or space https://www.reddit.com/r/brave_browser/comments/qjz1mh/cant_drag_tabs_into_2nd_monitor/ <-- people that have the same problem.

## Steps to Reproduce
   1.  Drag a tab out creating a new window

## Actual result:
Tab gets dragged out (creating a new window) but becomes unresponsive.

## Expected result:
A new window that you can move around and position where you want.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit)

## Version/Channel Information:

Not sure what this means sorry.

## Other Additional Information:

Things I tried:
- restarting the browser
- reboot
- disabling all extensions and rebooting
![lh58ZszHLe](https://user-images.githubusercontent.com/37532647/139604332-9c7c3d34-cd4a-49f3-ad2c-3b8baadc9550.gif)

**Comment by pboksz** [comment] 2021-10-31 23:25
I am getting the same issue using Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit). This seems to have started today.

**Comment by aliabe-creator** [comment] 2021-11-01 05:39
Same version, same architecture, cannot reproduce error. Brave Rewards/Ads enabled. Crypto Wallet enabled (no other extensions enabled). Hardware acceleration enabled. Windows 10 21H1, Intel 10th-gen CPU, 8GB RAM, NVIDIA 10-series GPU. 
@Immow on the Reddit thread, the OP stated that the issue resolved itself. Do you still have the same issue?

**Comment by Immow** [comment] 2021-11-01 07:43
What.... the... it started working again. I rebooted several times and disabled all my extensions. This is so weird. But yes it started working again?????

**Comment by pboksz** [comment] 2021-11-01 08:37
@aliabe-creator , @Immow , Yeah this is working for me today now too. I don't know how that is possible or what caused this, but it is working now. So strange.

**Comment by aliabe-creator** [comment] 2021-11-01 17:15
Well, glad it resolved itself! Could you close the issue?

**Closed** 2021-11-01 20:09 UTC
Labels: OS/Desktop
