### ISSUE TITLE
Two issues with options in Settings / Manage Search Engines

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#1041] opened 2018-09-08 20:41 UTC
## Description 

Observing two separate issues, both within the Settings / Manage Search Engines page. 

*Issue 1: Options available within _Default search engines_*
 - I'm not seeing DuckDuckGo listed among the Default Search Engine option.
 - It would be ideal if DDG could be placed toward the top of the list of Default Search Engines. 
-  It would also be good if Qwant, and other privacy-oriented search engine options could be featured in the default search engine list.
 - The work for this ^ might already be taking place (I suspect so); flagging as we've made the public announcement of the dev channel build availability, and DDG is a publicly known partner.

*Issue 2: Unexpected options under _Other search engines_*
 - Some of the options I see under _Other search engines_ seem unexpected. 
 - For example: Github, Google Drive, Infura Blog, KTLA, Socialblade, Twitter
 - The other search engines appear to be related to browsing history, but I wouldn't typically expect any of the examples above to display under search engine settings. 
 - Each of the examples listed have search querying available within their domains, but wouldn't typically qualify as search engines at the browser level.

## Steps to Reproduce

   1.  Enter: `chrome://settings/searchEngines`
  
## Actual result:

![brave-core-settings-search-engines-09082018](https://user-images.githubusercontent.com/8979240/45258414-da4aae00-b36b-11e8-9b53-be522c80da77.PNG)

## Expected result:
 - Brave search engine partners listed among Default search engine options (search engines we've formed structured partnerships with). 
 - Other search engine options include search engines submitted from contributors via github. 

## Reproduces how often: 

Easily reproduced

## Brave version (about:brave info) 

```

Brave | 0.55.2 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Windows
JavaScript | V8 7.0.242
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3528.4 Safari/537.36
```

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by lukemulks** [comment] 2018-09-08 20:43
cc: @bsclifton (ddg/partner optics - not sure who would be best to assign, but suspect you know) ;-)

**Comment by bbondy** [comment] 2018-09-09 01:16
I don't think the 2nd thing is an issue, anything that supports open search xml will show up in that list if you hit the site.   I think we should add DDG to the list though.  Note that people can still configure it, but I think we should just make it easier.

**Comment by rebron** [comment] 2018-09-09 06:46
I think the issue is anything that supports open search xml will show up on that list, a list the user doesn't know about or can't clear all at once or as part of clear browsing data. Separate priority from the first issue though.

**Comment by bsclifton** [comment] 2018-09-28 17:57
Closing as a duplicate of https://github.com/brave/brave-browser/issues/731

**Closed by bsclifton** 2018-09-28 17:57 UTC
Labels: feature/global-settings, feature/search
