### ISSUE TITLE
Launching Brave VPN from menu causes crash.

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#22819] opened 2022-05-12 21:46 UTC
## Description 
After enabling VPN through the QA menu in developer tools, navigating to the 3-dot menu and selecting Brave VPN at the top will cause the crash

Does not impact 1.40.x (Nightly)

## Steps to reproduce 

   1. Clean install 1.39
   2. Menu > Settings > About Brave
   3. Tap on Application version 3 times to enabled developer options
   4. Go back to main menu and select Developer Options
   5. Next, tap QA preferences and enter password
   6. Enable Brave VPN at the top
   7. Close settings, open 3-dot menu again and select Brave VPN at the top

## Actual result 
Crashes the app

https://user-images.githubusercontent.com/17885425/168173034-3e6d5868-43d6-4921-a75c-493bcf990856.mp4

## Expected result
VPN modal should be displayed

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 12
   
## Brave version
`1.39.101, Chromium 101.0.4951.64`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment] 2022-05-20 17:19
Also reproduces in, and is stopping me from dogfooding VPN, using Brave `1.39.109, Chromium 102.0.5005.50`, on a Google Pixel XL (`arm64`) running `Android 9.0.`

**Comment by kjozwiak** [comment] 2022-05-20 17:55
Closing this as it should be resolved with https://github.com/brave/brave-core/pull/13403. The above requires `1.39.110` or higher for `1.39.x` verification.

**Closed by kjozwiak** 2022-05-20 17:55 UTC
Labels: bug, release/blocking, QA/Yes, OS/Android, feature/vpn

**Comment by kjozwiak** [comment] 2022-05-23 15:40
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)
--- | ---
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | Android 12; Build/SP1A.210812.016
```

Ensured that Brave doesn't crash when enabling/disabling VPN from various locations. As per https://github.com/brave/brave-browser/issues/22819#issuecomment-1133170011, this was due to https://github.com/brave/brave-core/pull/13403 which was resolved.

Verification **PASSED** on `Samsung Galaxy Tablet A` running `Android 11` using the following build(s):

```
Brave | 1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)
--- | ---
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | Android 12; Build/RP1A.200720.012
```

Ensured that Brave doesn't crash when enabling/disabling VPN from various locations. As per https://github.com/brave/brave-browser/issues/22819#issuecomment-1133170011, this was due to https://github.com/brave/brave-core/pull/13403 which was resolved.
