### ISSUE TITLE
[Desktop] No spacing between first tab and window control buttons on MacOS Big Sur

### ISSUE THREAD

**Issue by bmcd243** [brave/brave-browser#10695] opened 2020-07-11 10:37 UTC
## Description 
No spacing between first tab and window control buttons on MacOS Big Sur.

## Actual result:
<img width="260" alt="Screenshot 2020-07-11 at 11 30 50" src="https://user-images.githubusercontent.com/64990696/87222290-80054480-c36a-11ea-9e1d-659dc8ebd0a6.png">

## Brave version (brave://version info)

Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.16 (Build 20A4300b)

**Comment by rebron** [comment] 2020-07-21 17:54
Closing as dupe of #10441

**Closed by rebron** 2020-07-21 17:54 UTC
Labels: OS/Desktop
