### ISSUE TITLE
Hitting the back button on youtube videos doesn't work correctly

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#29432] opened 2023-03-30 21:47 UTC
## Steps to Reproduce

   1. Go to youtube.com
   2. Click on any video
   3. Click the back button
   4. The url in the address bar changes, but the video page is still displayed

## Actual result:

Previous page not loaded

## Expected result:
Previous page loaded

## Reproduces how often: 

A few tries should be enough

## Brave version (brave://version info)

Brave | 1.49.132 Chromium: 111.0.5563.147 (Official Build) (64-bit)
-- | --
Revision | 029fd65a4dd711d1078468ed2206999cec86066b-refs/branch-heads/5563@{#1239}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment] 2023-03-31 08:46
+1 on this. Have seen it a few times on macOS as well but not always.

**Comment by jmartinez77x** [comment] 2023-03-31 23:01
I've experienced this as well

**Comment by Nyxet** [comment] 2023-04-04 06:46
Nonstop here as well.

**Comment by pilsnerbeer** [comment] 2023-04-24 09:44
this needs to be resolved

**Comment by ArtFlag** [comment] 2023-04-26 05:55
Same problem here 🙂

**Comment by asheroto** [comment] 2023-04-27 04:00
I've experienced this too, was about to create a new issue but found this one.

I'm not sure if this only happens when searching through the site, or if it's only when going directly to the search URL. I couldn't get it to happen when I went through the YouTube site to search, but if I went directly to the search URL, I had the issue. Not sure if it happens both ways or not.

**How I reproduced the bug:**
1.) Go to https://www.youtube.com/results?search_query=ghost
2.) Go back
3.) If it works, append a number and increment like "ghost 2", "ghost 3", etc, keep clicking on videos and going back

**The weird thing is that it doesn't happen every time**. It can be hard to reliably reproduce. Here's a video I recorded of my screen showing the link to search "ghost" working, the link to search "ghost 2" working, but when I search "ghost 3" and hit back, it doesn't work. Keep an eye on the URL and you'll see that the URL changes but not the webpage. I don't think the search query itself matters, this is just an example of quickly searching.

Perhaps this has something to do with the page being fully loaded or not, and perhaps it's caused by the YouTube JavaScript on their page updating the page URL, rather than the browser itself? Not sure though!

https://user-images.githubusercontent.com/49938263/234754461-77368250-3d51-41f3-acd6-a3deb75d10ee.mp4

**Comment by neilx11** [comment] 2023-04-29 08:57
I get this too: It seems to happen when I leave browser untouched overnight, and try to pick where I left off the next day; except that I can't, previous history vanishes and current page refreshes and back then gets greyed out and unworkable. It's like somebody doesn't want me continuing my research on something, or when I simply want to play a video from the previous days log that would be on the back button. Also, as of late. Open YouTube browser will refresh sometime after midnight, even if you're a video. The damn page resets, with again, history being lost on the back button, and current page reloading resulting in you having to watch or play the video from the beginning. You have No Choice!! Since when did Russia start controlling our browsers!? You get what I mean now!? I'm looking and hoping for someone to have a solution. I am not a programmer. So I do not have the means or knowledge to fix this problem. If I did, I would probably create an extension to get around this problem. Just like someone created the "Return YouTube Dislike Button", and Easy "YouTube Video Downloader". So I'm hoping some creator will make an extension that will halt these various problems with the YouTube back button. And defeat whatever YouTube (or whoever it is) is trying to do. I don't like my previous history from the next day being erased.

**Comment by Rowsol** [comment] 2023-04-29 17:47
Very annoying but I've seen firefox users complaining about this as well. It's been happening for a year or so it seems.

**Comment by kaytwo** [comment] 2023-05-19 20:15
I'm seeing the same thing on GitHub's new code browser as well - history pops, but content does not change until refreshing the page. Can't repro on Chrome Stable.

**Comment by neilx11** [comment] 2023-05-19 20:37
I am a Firefox user and posted a previous comment in this section.
And I am having the same problem, very annoying!! My previous comment is more detail. And I make a suggestion to any maker of Extensions!! Why youtube is doing this non-sense is beyond me!! Another thing to annoy the user! First, it was "take away user's email notifications!" then it was "use hearts instead of star rating system!" And several other annoyances!

**Comment by linqen** [comment] 2023-06-28 21:38
Same to me (using brave). 
So relief that I found this report on Brave Browser repo.

**Comment by asheroto** [comment] 2023-06-28 21:40
@neilx11 are you having an issue in Brave?

**Comment by ryanbr** [comment] 2023-06-28 21:53
I made a change recently try  Updating `Brave Ad Block Updater - Version: 1.0.348` in `brave://components`. Then refreshing Youtube webpage.

**Comment by asheroto** [comment] 2023-06-28 22:14
Thanks @ryanbr.

I am using 1.0.348 and unfortunately still have the same bug. Looks like it happens in Private windows too.

The way I test it is to go to
https://www.youtube.com/results?search_query=asdf
then
https://www.youtube.com/results?search_query=asdf2
then
https://www.youtube.com/results?search_query=asdf3
and continue on until the bug is reproduced

Interestingly enough I can't get it to happen when you are already on the page and then search for "asdf" etc. It seems to happen when you go to the page directly. Although it may exist when the page is already loaded, I'm not sure, but I've had the most luck reproducing the bug by going to the page directly.

Here's another demo...

https://github.com/brave/brave-browser/assets/49938263/6c6545ac-d913-4558-b21c-b1b1dc75e65b

I'm using the back button on my mouse. It seems to work fine when using the search box inside the YouTube page, but when going to the URL directly, whether typing it in, using it as a search engine, or even clicking on a link from a search engine like Google/Brave/etc the bug will present itself. In the demo above, notice how around second 23 (changing the URL to asdf6) the screen flashes. That's when I press the back button.

**Comment by ryanbr** [comment] 2023-06-28 22:46
With shields up, no extensions. When hitting the back button what does it show in the console?

**Comment by asheroto** [comment] 2023-06-28 23:11
> With shields up, no extensions. When hitting the back button what does it show in the console?

Shields are up...
![image](https://github.com/brave/brave-browser/assets/49938263/a57f9843-95dc-4fa5-a6a4-27024d407064)

All debugging levels turned on in console.

---
When searching https://www.youtube.com/results?search_query=asdf20a on a new profile

<details><summary>Details</summary>
<p>
Shields up...

![image](https://github.com/brave/brave-browser/assets/49938263/d856978e-12c3-4a3d-937b-f5ee81c30b5c)

Shields down...

![image](https://github.com/brave/brave-browser/assets/49938263/e8fc4b6b-3e62-4699-889a-04b950762404)
</p>
</details> 

When searching https://www.youtube.com/results?search_query=asdf20b on a new profile...

<details><summary>Details</summary>
<p>

Shields up...

![image](https://github.com/brave/brave-browser/assets/49938263/5ecde540-2649-4527-aae3-4a2ebaf8f0ef)

Shields down...

![image](https://github.com/brave/brave-browser/assets/49938263/2d1b58c4-bf16-4c35-9996-20e165d313d6)

</p>
</details> 

`brave://components`...
![image](https://github.com/brave/brave-browser/assets/49938263/775ab560-453a-4d74-b3d7-0f3ba012fdfc)

In my tests, I had the issue happen whether shields were up or not, on any profile, and have used `brave://restart`.

Version...
![image](https://github.com/brave/brave-browser/assets/49938263/427e509f-4b2d-4748-8f45-2751d12ded8c)

**Comment by ryanbr** [comment] 2023-06-28 23:29
Try adding @@/generate_204 into brave://adblock custom rules, save and reload YT.

**Comment by asheroto** [comment] 2023-06-29 22:31
Same problem, but keep in mind even with shields down it does the same thing.

**Comment by ledfn** [comment] 2023-07-18 16:33
I'm here to report that this problem still exists.

**Comment by neilx11** [comment] 2023-07-19 03:07
And here too.

**Comment by SixsKcrawford** [comment] 2023-08-03 16:30
This issue is still happening. I have been having this issue for at least a year at this point.

**Comment by linqen** [comment] 2023-08-03 17:13
> Yeah I don't think it's very high on the developers to-do list. I've been experiencing this issue for years, just finally got around to commenting on it a few months ago. 😊

I do think it should be at least medium priority. It's really annoying, on everyday browsing, and I even considered using another browser just because of that. You need to constantly be aware of it, move back and forth slowly, and with the hand ready on F5...

**Comment by Zeenobit** [comment] 2023-08-10 00:15
Just here to bump this. I'm also experiencing the same issue. I also tried adding `@@/generate_204` to custom rules as @ryanbr suggested, but that didn't seem to have any effect.

**Comment by ryanbr** [comment] 2023-08-10 00:38
Yeah, was probably not a filter list issue. Its quite hard to replicate reliably, probably my solution would be to go through the old Brave nightly releases in https://github.com/brave/brave-browser/releases to get a build that doesn't. So we know which Brave first caused it

**Comment by neilx11** [comment] 2023-08-10 02:17
> Yeah, was probably not a filter list issue. Its quite hard to replicate reliably, probably my solution would be to go through the old Brave nightly releases in https://github.com/brave/brave-browser/releases to get a build that doesn't. So we know which Brave first caused it

I do not think this is a brave issue. So it's no use blaming brave browser, and making people do useless reviews of past releases. This thwarts the issue. I think this is a Youtube issue. As it seems to appear on the Edge browser too (and Firefox)! The Back button seems "to forget" past pages. You mentioned one thing that is correct, this problem is hard to replicate. But is annoying when it does occur. I wonder if this is another thing Google "is sneaking" in. To break YouTube yet again, or to prevent users from going back pages for some reason. Google shows itself to be a bad entity. By keeping the community from uniting in manner or another. If anyone has noticed, it has been slowly dividing everyone. This has been going on since it's inception. Slowly ragging and taking over everything people become familiar with. And then slowly, to invade everyone's privacy. By making it a requisite to use and register your real name to use any services it HAS TAKEN OVER. Like a frog coming to a slow boil, and making everyone forget, it has slowly cooked the frog and continues to take over even the most mundane parts of the internet. I ope someone can catch the code if any, that Google is sending to the browser to cause it to forget past history in the back button. And whether or not this is deliberate, and the reason why. YouTube divided everyone when it dropped (ceased) enail delivery notices of new youyube videos from creators. Now, we only get a 1/5th the updates/notices by creators through the red bell button on the upper right. Email notices were so much more reliable and thorough. It's the independence they want to take away from users or something, the "individuality" of the internet. Where people are in unity. Not by an all seeing big brother megalith. I cannot figure out what Google is doing this time with the back button, but I do "sense" something. Again, the purpose of them not wanting people to do a certain "something". What that something is, I do not know! They don't want anybody doing anything with their (them) knowing it!! Period. So it begs the question, who is running Google!? There are more questions too! I hope someone can debug this back button problem, and expose what is going on.

**Comment by ryanbr** [comment] 2023-08-10 03:34
> I do not think this is a brave issue. So it's no use blaming brave browser, ...

I haven't seen other reports in other browsers to be honest, no blaming here. I Assumed it was a Brave issue, but if it occurs in elsewhere then its probably a site bug.

**Comment by asheroto** [comment] 2023-08-10 07:42
Well crap. I just tested in Brave, Chrome, Edge, and Firefox. I was able to reproduce this same issue in all of them except Edge.

Appears to be a site bug then. It's just weird that some browsers it seems to occur on more frequently than others.

When I tested the other browsers before, I never experienced issues, even doing the same process, but now I can reproduce it. Perhaps YouTube has updated some code making it worse. Haha.

**Comment by szilardszaloki** [comment] 2023-09-06 16:13
Did some search in our releases, and found that the first version that does not reproduce the issue (going backwards) is `1.47.7`, so this must have broken in `1.47.8` (https://github.com/brave/brave-core/compare/v1.47.8...v1.47.9). These are not specifically suspicious commits, though, except for
- the minor Chromium bump from `107.0.5304.36` to `107.0.5304.62` (https://github.com/chromium/chromium/compare/107.0.5304.37...107.0.5304.63),
- and [update adblock-rust to v0.5.8](https://github.com/brave/brave-core/commit/231eb943599fd64a91618464f718246327f1526a)

However, I think it's less likely the latter, as it's reported to happen on other browsers, too.

Basically, if there's two adjacent items on the history stack for which `entryTime` is the same, the back button doesn't do the right thing. If you navigate to the second one, and replace the state of the active session history entry with:
```js
history.replaceState({ entryTime: /* a value higher than `history.state.entryTime` for the previous history entry */ }, '')
```
and then hit the back and forward buttons, the next back button hit will take you to the first item correctly:

https://github.com/brave/brave-browser/assets/5390451/93b7df75-1fd8-47d0-92b4-afedcd8a9f1c

The difference between `1.47.7` and `1.47.8` is that the fractional part of `history.state.entryTime` is missing in `1.47.8` (and above), so the timestamp generation logic might have changed there. We could roll our own fix, but best would be if this was addressed upstream. I'll catch up with Chromium folks and report back here.

**Comment by asheroto** [comment] 2023-09-07 02:14
Awesome! I'm so happy you found that. Thank you!

**Comment by linqen** [comment] 2023-09-08 00:08
Thank you so much for your hard work @szilardszaloki , super appreciated ♥

**Comment by szilardszaloki** [comment] 2023-09-08 15:58
Actually, the regression range above is wrong, as it's https://github.com/brave/brave-core/compare/v1.47.7...v1.47.8, and the breaking commit is https://github.com/brave/brave-core/commit/2f98d617d8b18004f966c716cb73cffae0b19479. Working on a fix now — hopefully it won't need a browser release.

**Comment by szilardszaloki** [comment] 2023-09-14 02:01
Closed via https://github.com/brave/adblock-resources/pull/131.

**Closed by szilardszaloki** 2023-09-14 02:01 UTC
Labels: feature/history, priority/P2, release-notes/include, google, OS/Desktop

**Comment by GitAcc53** [comment] 2023-10-17 11:11
"[closed/fixed-by-component-update]" 

It's not fixed at all. I still have the same problem.

**Comment by linqen** [comment] 2023-10-17 11:19
I guess this didn't hit production yet

**Comment by StrangePeanut** [comment] 2023-10-17 11:25
I personally haven't experienced the issue in a while.

**Comment by szilardszaloki** [comment] 2023-10-17 16:19
The changes were shipped via the component updater around September 13.
@GitAcc53 Would you mind letting me know the versions you see in `brave://components` next to `Brave Ad Block Resources Library`, and `Brave Ad Block Updater`?
Thanks!

**Comment by linqen** [comment] 2023-10-17 16:32
For me is still happening as well, versions:

 Ad Block Resources Library - Version: 1.0.71
 Brave Ad Block Updater - Version: 1.0.1714

**Comment by szilardszaloki** [comment] 2023-10-17 16:39
@linqen Would you mind checking what `history.state.entryTime` values you get for the affected sites in Developer Console (like I did [here](https://github.com/brave/brave-browser/issues/29432#issuecomment-1708692111))?

**Comment by GitAcc53** [comment] 2023-10-19 09:07
1.0.72, 1.0.1740
still happening

**Comment by szilardszaloki** [comment] 2023-10-20 15:34
@GitAcc53 @linqen What you're experiencing has the same symptoms with a different underlying cause, unfortunately. It's most probably due to some of YouTube's recent changes to their site that are being released via staged roll-outs (which affect only a certain percentage of users). Will keep an eye on that, and also would appreciate any additional info you might have — including the `history.state.entryTime` values you're getting for the affected sites.

**Comment by GitAcc53** [comment] 2023-11-19 01:03
I couldn't figure out how to get the info from history.state.entryTime values, problem is still happening

**Comment by Kolgann** [comment] 2023-12-04 20:18
I've been encountering this issue for about a year now and can confirm it still happens fairly often for me. Strangely, it's not very consistent; I can go a day or two without seeing it once, and then another day it'll happen pretty much every single time I hit the back button in Youtube. 

Brave Browser - v1.60.125
Brave Ad Block Resources - v1.0.81
Brave Ad Block Updater - v1.0.2644
Windows 11 - 10.0.22621

Annoyingly, I wasn't able to get it to happen again while I was trying to get those history.state.entryTime values, but I did get some values from when the issue is _not_ happening, in case that helps at all.

Test 1 - went to youtube.com/subscriptions, clicked a video, entryTime was 5093.000000000022, then hit back, entryTime was now 5093.
Test 2 - same procedure as above, entryTime was 4486 on the video, and 4485 on the subscriptions page after hitting back.
Test 3 - this time I just went to the youtube.com homepage, clicked a video, entryTime was 9647.000000000022, then hit back, entryTime was now 9647.

Once it decides to start happening again I'll try and get those entryTime values.

I hope this helps somehow, let me know if I can provide any extra info. Thanks!

Btw @GitAcc53 and anyone else who has the issue and feels motivated, you can easily get these values by opening the dev console and typing 'console.log(history.state.entryTime);'.

**Comment by cyfung1031** [comment] 2023-12-28 05:15
The issue is due to the incorrectness of history state. (no entry point is stored in window.history.state)
This is a very old bug and the new YouTube engineers could not solve it.
This is not because of the JS engine used in Brave. It happens for all browsers.

That's why now the engineers trying to put `?si=` `?pp=` in the url.

**Comment by asheroto** [comment] 2023-12-28 05:22
Good info! Thanks for that!

**Comment by Kolgann** [comment] 2023-12-28 22:59
Yes that's very helpful, thank you! I anecdotally hadn't noticed it in other browsers, but it is an intermittent issue and I use Brave far more than any other browser, so it seems reasonable that I just happened to not have encountered it on other browsers yet. Good to know it's not a Brave issue, and just a YouTube bug.

**Comment by Mettwasser** [comment] 2024-09-14 07:38
Still not resolved.
I was using Opera GX for roughly 2 years and recently made the jump to brave.
I have this issue literally the entire time, and it's nerve-wrecking. I haven't had this issue on Opera GX, the solution with "TabView" didn't work for me either. I am seriously considering another browser, because this is a huge dealbreaker for me.

**Comment by bsclifton** [comment] 2024-10-15 20:52
Hi folks - we recently made a change to our variations server which disabled the feature causing this problem (see https://github.com/brave/brave-variations/pull/1224 for more info).  This should be working great now.

@Mettwasser can you please retest? (if you're still using Brave)

**Comment by asheroto** [comment] 2024-10-16 01:13
I tested this out using the latest version on two different computers and could not replicate the original issue. I'm think this might be fixed! Thanks for our work! Hopefully others experience the same result.

**Comment by Mettwasser** [comment] 2024-10-16 06:27
I was staying with brave. Can't currently test it on my main PC, but it for sure works on my laptop. So I am confident it's fixed. Thank you so, so much!

**Comment by linqen** [comment] 2024-10-16 08:10
> Hi folks - we recently made a change to our variations server which disabled the feature causing this problem (see [brave/brave-variations#1224](https://github.com/brave/brave-variations/pull/1224) for more info). This should be working great now. If anyone is experiencing any issues please reply back here!

I tested and looks like it's working! I hope so, because this issue has been around for AGES. Thank you!

**Comment by Mettwasser** [comment] 2024-10-16 18:31
> Hi folks - we recently made a change to our variations server which disabled the feature causing this problem (see [brave/brave-variations#1224](https://github.com/brave/brave-variations/pull/1224) for more info). This should be working great now. If anyone is experiencing any issues please reply back here!
> 
> [@Mettwasser](https://github.com/Mettwasser) can you please retest? (if you're still using Brave)

So yes, I got to test it on my main PC, and I can confirm this is resolved. Thank you for the hard work!
