### ISSUE TITLE
[Android] Sometimes device list contains an empty device name

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#10864] opened 2020-07-22 20:21 UTC
Sometimes device list contains an empty device name.

Reported at https://community.brave.com/t/sync-in-brave-android-beta-nigthly-dont-show-name-of-other-devices/145196/3 .

**Comment by deeppandya** [comment] 2020-07-22 20:29
@AlexeyBarabash i think it's related to dark mode.

**Comment by AlexeyBarabash** [comment] 2020-07-22 20:32
@deeppandya thanks, then it will be easier to reproduce

**Comment by AlexeyBarabash** [comment] 2020-07-22 20:35
![Screenshot_20200722-233307_Brave - Nightly](https://user-images.githubusercontent.com/24739341/88225860-e3994700-cc73-11ea-80cb-3e8bc8d208ad.jpg)

And it is easy to reproduce, just switch to the dark mode

**Comment by srirambv** [comment] 2020-07-23 07:46
Dupe of #8703

**Closed by srirambv** 2020-07-23 07:46 UTC
Labels: OS/Android, bug, feature/sync

**Comment by kmansoft** [comment] 2020-08-04 10:02
Possibly related:

I'm running Beta on two desktop systems (Windows 10 and Linux) and Android.

All three installs are set up to sync with each other - single "sync chain".

And yet, all three installs show only themselves as members of the sync chain. The other two installs which are part of the chain are not shown.
