### ISSUE TITLE
[Desktop]

### ISSUE THREAD

**Issue by lakshmikanthKGit** [brave/brave-browser#11440] opened 2020-08-26 10:32 UTC
## Description 

I have installed Brave browser recently and first tow days i got about 25 advertisement from then i am not receiving any ads.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

![image](https://user-images.githubusercontent.com/14016581/91293349-26c96700-e798-11ea-8252-f36f1fb3db23.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by tmancey** [comment] 2020-08-26 15:33
There is a known issue where some users are not receiving ads. Please upgrade to 1.13.x and wait a few days for the issue to resolve.

Ad campaigns vary by country, and by operating system. In some countries, there may be fewer ads observed throughout the month based on campaign size, delivery pacing, operating systems, content categories and that advertisers have selected to run their ads to.

As we continue to generate additional demand for countries where Brave Ads are available, the consistency should improve over time.

**Comment by tmancey** [comment] 2020-08-26 15:33
Closing issue as a duplicate of https://github.com/brave/brave-browser/issues/11256

**Closed by tmancey** 2020-08-26 15:33 UTC
Labels: OS/Desktop, feature/ads
