### ISSUE TITLE
Add DDG search engines custom UA

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#4822] opened 2019-06-12 03:35 UTC
This task is just to verify the custom HTTP headers work on Android as they do on Desktop.

**Comment by emerick** [comment] 2019-08-15 14:24
Used remote debugging to confirm that `User-Agent` header includes `Brave Chrome` when visiting duckduckgo.com and just `Chrome` when visiting other sites. Will attach screenshots.

**Comment by emerick** [comment] 2019-08-15 14:26
Closing as it appears to be working as intended on Android.

**Closed by emerick** 2019-08-15 14:26 UTC
Labels: QA/No, android-related, priority/P2
