### ISSUE TITLE
[Android] - `Login to uphold to see your balance` text is not shown in BR panel when user is in logged out state

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#28190] opened 2023-02-01 08:24 UTC
## Description 
Found while testing https://github.com/brave/brave-browser/issues/27055
 `Login to uphold to see your balance` text is not shown in BR panel when user is in logged out state
## Steps to reproduce 

   1. Clean profile 1.48.x or upgraded profile
   2. Enable rewards and connect the existing KYC'd uphold/Gemini/bitFlyer wallet 
   3. Get the wallet into a logged-out state
   4. Confirm that the wallet is in the `Logged out` state on the brave://rewards settings page
   5. Confirm that `Login to uphold to see your balance` text is shown below the `Logged out` state
   6. Click on the BR panel
   7. Confirm that the wallet state is in the `Logged out` state 
   8. Observe that there is no `Login to uphold to see your balance` text below the `Logged out` state
   
## Actual result 
`Login to uphold to see your balance` text is not shown in BR panel when user is in logged out state

Settings page | BR panel
----------------|-----------
![Screenshot_20230303-134337_Brave - Beta](https://user-images.githubusercontent.com/38657976/215988876-96212dd7-7dd3-4f8e-8b33-2a7ef6667826.jpg) | ![image](https://user-images.githubusercontent.com/38657976/215988988-980104e7-d4d8-4399-87ca-2b354c7be74d.png)

## Expected result
`Login to uphold to see your balance` text should be shown in BR panel when user is in logged out state

Desktop 
![image](https://user-images.githubusercontent.com/38657976/215989273-8ce011f4-9b2b-42bb-bf21-fad7b2910960.png)

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): ALL
   - Android version: Version 12
   
## Brave version
1.48.x and 1.47.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @Miyayes @deeppandya @sujitacharya2005

**Comment by LaurenWags** [comment] 2023-02-01 12:23
Duplicate of https://github.com/brave/brave-browser/issues/28096

**Closed** 2023-02-01 17:09 UTC
Labels: feature/user-interface, feature/rewards, QA/Yes, QA/Test-Plan-Specified, OS/Android
