### ISSUE TITLE
Follow up of #10860 - Unable to create sync chain due to leading and trailing whitespace in code words 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13681] opened 2021-01-20 16:03 UTC
## Description 

Follow up of #10860 - Unable to create sync chain due to leading and trailing whitespace in code words 

## Steps to Reproduce

   1.  Follow the steps from https://github.com/brave/brave-browser/issues/10860#issue-663978174
   

## Actual result:

Invalid Code Words error is shown

## Expected result:
Leading and trailing whitespace in code words should be trimmed
Sync chain should be created

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.20.84 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2004 (Build 19041.746)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA
## Miscellaneous Information:

cc @brave/legacy_qa @jsecretan @rebron @darkdh @AlexeyBarabash @yrliou @petemill

**Comment by btlechowski** [comment] 2021-01-21 22:20
Not reproducible on Linux. Created sync between 1.20.86(dev) and 1.20.85(beta). Added spaces and enters.

Brave | 1.20.86 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Ubuntu 18.04 LTS

Brave | 1.20.85 Chromium: 88.0.4324.96 (Official Build) beta (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Linux

**Comment by AlexeyBarabash** [comment] 2021-02-08 14:29
cannot reproduce on my dev computer

Brave | 1.22.8 Chromium: 89.0.4389.40 (Developer Build) (64-bit)
-- | --
Revision | 2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}

**Comment by AlexeyBarabash** [comment] 2021-02-08 16:12
Cannot reproduce on my Windows computer, 
Nightly

Brave |	1.22.6 Chromium: 89.0.4389.40 (Official Build) nightly (64-bit)
-- | --
Revision |	2c2ed83cd507b23e4845edd09a7d1dfc727daf4b-refs/branch-heads/4389@{#602}
OS |	Windows 10 OS Version 2004 (Build 19041.746)

Beta
Brave	|1.21.44 Chromium: 88.0.4324.146 (Official Build) beta (64-bit)
-- | --
Revision |	406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}
OS |	Windows 10 OS Version 2004 (Build 19041.746)

**Comment by jonathansampson** [comment] 2021-06-01 16:54
@GeetaSarvadnya Can this issue be closed, since the sync-codes are now being trimmed of leading and trailing whitespace  before being counted?

**Comment by jsecretan** [comment] 2021-11-01 13:39
Closing this because I believe it is fixed, but we can re-open if not the case

**Closed by jsecretan** 2021-11-01 13:39 UTC
Labels: bug, feature/sync, priority/P5, QA/Yes, QA/Test-Plan-Specified, OS/Desktop
