### ISSUE TITLE
Crash Report:  I open MDN webdev in normal window, scrolled for a while and the browser crash. MDN webdev work fine private.

### ISSUE THREAD

**Issue by Ilikestrawberry88** [brave/brave-browser#40356] opened 2024-08-08 11:00 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.68.137 Chromium: 127.0.6533.100
Operating System: Linux 6.5.0-44-generic

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/03920200-15c1-690c-0000-000000000000

**Comment by janswist** [comment] 2024-08-09 19:55
I have exact same issue. Problematic link: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range

Made my browser go into death loop: whenever I restarted the browser and clicked `Restore` browser opened all the tabs INCLUDING the one that made it crash and so whenever it got to that tab it crashed again. Endlessly.

To just get it all back I started digging in sessions file to change url to something else so it couldn't open it (worked halfly bc on the next startup it didn't ask to restore so I kept clicking `Cmd + Shift + T` until it reopened every single window and managed to close MDN site before it crashed.

Now, I think it would be easier to disable internet connection, restore all tabs and then close the problematic site.

It's VERY weird and not sure what MDN has on their site to make it happen, but I'm also not keen to go through this nightmare of losing potentially couple dozen grouped tabs again.

**Comment by zcraber** [comment] 2024-08-10 14:56
Possible duplicate of #40102

**Comment by kjozwiak** [comment] 2024-08-13 18:54
> **DO NOT CHANGE BELOW THIS LINE** Crash ID: crash/03920200-15c1-690c-0000-000000000000

Checked `BackTrace` and the above looks similar to the crash that was mentioned via https://github.com/brave/brave-browser/issues/40102#issuecomment-2262777553. So definitely related. Going to close this off as a duplicate. The above will be resolved by https://github.com/brave/brave-core/pull/25035 in the next `1.68.x` release which will occur sometime this week. If we don't get another `C127`, it will go out next week via `1.69.x`.

```
[ 00 ] base::ImmediateCrash() ( immediate_crash.h:176 )
[ 01 ] logging::CheckFailure() ( check.h:212 )
[ 02 ] base::RepeatingCallback<void (unsigned long)>::Run(unsigned long) && ( callback.h:352 )
[ 03 ] ChromeBrowsingDataRemoverDelegate::OnTaskComplete(ChromeBrowsingDataRemoverDelegate::TracingDataType, unsigned long, base::TimeTicks, bool) ( chrome_browsing_data_remover_delegate.cc:1506 )
[ 04 ] base::OnceCallback<void ()>::Run() && ( callback.h:156 )
[ 05 ] base::internal::PostTaskAndReplyRelay::RunReply(base::internal::PostTaskAndReplyRelay) ( post_task_and_reply_impl.h:63 )
[ 06 ] void base::internal::DecayedFunctorTraits<void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&>::Invoke<void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay>(void (*&&)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&) ( bind_internal.h:671 )
[ 07 ] void base::internal::InvokeHelper<false, base::internal::FunctorTraits<void (*&&)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&>, void, 0ul>::MakeItSo<void (*)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>>(void (*&&)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>&&) ( bind_internal.h:930 )
[ 08 ] void base::internal::Invoker<base::internal::FunctorTraits<void (*&&)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&>, base::internal::BindState<false, true, false, void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay>, void ()>::RunImpl<void (*)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>, 0ul>(void (*&&)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>&&, std::__Cr::integer_sequence<unsigned long, 0ul>) ( bind_internal.h:1067 )
[ 09 ] base::internal::Invoker<base::internal::FunctorTraits<void (*&&)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&>, base::internal::BindState<false, true, false, void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay>, void ()>::RunOnce(base::internal::BindStateBase*) ( bind_internal.h:980 )
[ 10 ] base::OnceCallback<void ()>::Run() && ( callback.h:156 )
[ 11 ] base::TaskAnnotator::RunTaskImpl(base::PendingTask&) ( task_annotator.cc:203 )
[ 12 ] void base::TaskAnnotator::RunTask<base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*)::$_3>(perfetto::StaticString, base::PendingTask&, base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*)::$_3&&) ( task_annotator.h:90 )
[ 13 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) ( thread_controller_with_message_pump_impl.cc:484 )
[ 14 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:346 )
[ 15 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:0 )
[ 16 ] base::MessagePumpGlib::HandleDispatch() ( message_pump_glib.cc:649 )
[ 17 ] base::(anonymous namespace)::WorkSourceDispatch(_GSource*, int (*)(void*), void*) ( message_pump_glib.cc:274 )
[ 18 ] 0x7c5e73508edb
[ 19 ] 0x7c5e7350c6a0
[ 20 ] 0x7c5e7350cf63
[ 21 ] 0x7c5e73604a20
[ 22 ] base::MessagePumpGlib::Run(base::MessagePump::Delegate*) ( message_pump_glib.cc:683 )
[ 23 ] partition_alloc::internal::PartitionTlsGet(unsigned int) ( partition_tls.h:77 )
[ 24 ] partition_alloc::ThreadCache::Get() ( thread_cache.h:269 )
[ 25 ] partition_alloc::PartitionRoot::GetOrCreateThreadCache() ( partition_root.h:2566 )
[ 26 ] void* partition_alloc::PartitionRoot::AllocInternalNoHooks<(partition_alloc::internal::AllocFlags)16>(unsigned long, unsigned long) ( partition_root.h:2195 )
[ 27 ] void* partition_alloc::PartitionRoot::AllocInternal<(partition_alloc::internal::AllocFlags)16>(unsigned long, unsigned long, char const*) ( partition_root.h:2142 )
[ 28 ] void* partition_alloc::PartitionRoot::AllocInline<(partition_alloc::internal::AllocFlags)16>(unsigned long, char const*) ( partition_root.h:528 )
[ 29 ] allocator_shim::internal::PartitionMalloc(allocator_shim::AllocatorDispatch const*, unsigned long, void*) ( allocator_shim_default_dispatch_to_partition_alloc.cc:206 )
[ 30 ] partition_alloc::internal::PartitionTlsGet(unsigned int) ( partition_tls.h:77 )
[ 31 ] partition_alloc::ThreadCache::Get() ( thread_cache.h:269 )
[ 32 ] partition_alloc::PartitionRoot::GetOrCreateThreadCache() ( partition_root.h:2566 )
[ 33 ] void* partition_alloc::PartitionRoot::AllocInternalNoHooks<(partition_alloc::internal::AllocFlags)16>(unsigned long, unsigned long) ( partition_root.h:2195 )
[ 34 ] void* partition_alloc::PartitionRoot::AllocInternal<(partition_alloc::internal::AllocFlags)16>(unsigned long, unsigned long, char const*) ( partition_root.h:2142 )
[ 35 ] void* partition_alloc::PartitionRoot::AllocInline<(partition_alloc::internal::AllocFlags)16>(unsigned long, char const*) ( partition_root.h:528 )
[ 36 ] allocator_shim::internal::PartitionMalloc(allocator_shim::AllocatorDispatch const*, unsigned long, void*) ( allocator_shim_default_dispatch_to_partition_alloc.cc:206 )
[ 37 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ( thread_controller_with_message_pump_impl.cc:654 )
[ 38 ] partition_alloc::internal::PartitionTlsGet(unsigned int) ( partition_tls.h:77 )
[ 39 ] partition_alloc::ThreadCache::Get() ( thread_cache.h:269 )
[ 40 ] partition_alloc::PartitionRoot::GetOrCreateThreadCache() ( partition_root.h:2566 )
[ 41 ] void* partition_alloc::PartitionRoot::AllocInternalNoHooks<(partition_alloc::internal::AllocFlags)16>(unsigned long, unsigned long) ( partition_root.h:2195 )
[ 42 ] void* partition_alloc::PartitionRoot::AllocInternal<(partition_alloc::internal::AllocFlags)16>(unsigned long, unsigned long, char const*) ( partition_root.h:2142 )
[ 43 ] void* partition_alloc::PartitionRoot::AllocInline<(partition_alloc::internal::AllocFlags)16>(unsigned long, char const*) ( partition_root.h:528 )
[ 44 ] allocator_shim::internal::PartitionMalloc(allocator_shim::AllocatorDispatch const*, unsigned long, void*) ( allocator_shim_default_dispatch_to_partition_alloc.cc:206 )
[ 45 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ( thread_controller_with_message_pump_impl.cc:0 )
[ 46 ] base::RunLoop::Run(base::Location const&) ( run_loop.cc:134 )
[ 47 ] partition_alloc::internal::PartitionTlsGet(unsigned int) ( partition_tls.h:77 )
[ 48 ] partition_alloc::ThreadCache::Get() ( thread_cache.h:269 )
[ 49 ] partition_alloc::PartitionRoot::GetThreadCache() ( partition_root.h:2575 )
[ 50 ] partition_alloc::PartitionRoot::RawFreeWithThreadCache(unsigned long, partition_alloc::internal::SlotSpanMetadata*) ( partition_root.h:1781 )
[ 51 ] partition_alloc::PartitionRoot::FreeNoHooksImmediate(void*, partition_alloc::internal::SlotSpanMetadata*, unsigned long) ( partition_root.h:1676 )
[ 52 ] void partition_alloc::PartitionRoot::FreeInline<(partition_alloc::internal::FreeFlags)2>(void*) ( partition_root.h:1581 )
[ 53 ] void partition_alloc::PartitionRoot::FreeInlineInUnknownRoot<(partition_alloc::internal::FreeFlags)2>(void*) ( partition_root.h:1468 )
[ 54 ] allocator_shim::internal::PartitionFree(allocator_shim::AllocatorDispatch const*, void*, void*) ( allocator_shim_default_dispatch_to_partition_alloc.cc:340 )
[ 55 ] gwp_asan::internal::(anonymous namespace)::AlignedFreeFn(allocator_shim::AllocatorDispatch const*, void*, void*) (.63d0ab86e748af47f418354d096b94ea)
[ 56 ] 0x1d58000a4000
[ 57 ] std::__Cr::default_delete<base::RunLoop>::operator()(base::RunLoop*) const ( unique_ptr.h:67 )
[ 58 ] std::__Cr::unique_ptr<base::RunLoop, std::__Cr::default_delete<base::RunLoop>>::reset(base::RunLoop*) ( unique_ptr.h:278 )
[ 59 ] std::__Cr::unique_ptr<base::RunLoop, std::__Cr::default_delete<base::RunLoop>>::operator=(std::__Cr::unique_ptr<base::RunLoop, std::__Cr::default_delete<base::RunLoop>>&&) ( unique_ptr.h:219 )
[ 60 ] ChromeBrowserMainParts::WillRunMainMessageLoop(std::__Cr::unique_ptr<base::RunLoop, std::__Cr::default_delete<base::RunLoop>>&) ( chrome_browser_main.cc:1864 )
[ 61 ] content::BrowserMainLoop::RunMainMessageLoop() ( browser_main_loop.cc:1085 )
[ 62 ] content::BrowserMainLoop::RunMainMessageLoop() ( browser_main_loop.cc:1085 )
[ 63 ] content::BrowserMainRunnerImpl::Run() ( browser_main_runner_impl.cc:160 )
[ 64 ] content::BrowserMain(content::MainFunctionParams) ( browser_main.cc:34 )
[ 65 ] content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams, bool) ( content_main_runner_impl.cc:721 )
[ 66 ] content::ContentMainRunnerImpl::Run() ( content_main_runner_impl.cc:1154 )
[ 67 ] __gconv_destroy_spec
[ 68 ] longjmp
[ 69 ] content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) ( content_main.cc:332 )
[ 70 ] content::ContentMain(content::ContentMainParams) ( content_main.cc:345 )
[ 71 ] GetProfileParamsProcess(base::CommandLine const&) ( process_type.cc:33 )
[ 72 ] std::__Cr::__constexpr_strlen(char const*) ( constexpr_c_functions.h:49 )
[ 73 ] std::__Cr::char_traits<char>::length(char const*) ( char_traits.h:127 )
[ 74 ] unsigned long std::__Cr::__char_traits_length_checked<std::__Cr::char_traits<char>>(std::__Cr::char_traits<char>::char_type const*) ( string_view:269 )
[ 75 ] std::__Cr::basic_string_view<char, std::__Cr::char_traits<char>>::basic_string_view(char const*) ( string_view:345 )
[ 76 ] base::CommandLine::HasSwitch(char const*) const ( command_line.cc:346 )
[ 77 ] ChromeMain ( chrome_main.cc:192 )
```

**Closed by kjozwiak** 2024-08-13 18:54 UTC
Labels: crash, priority/P2, OS/Desktop
