### ISSUE TITLE
2023 refresh flag fix only available in nightly build

### ISSUE THREAD

**Issue by joejoejo** [brave/brave-browser#31849] opened 2023-07-25 14:50 UTC
Description:
The fix for the 2023 Chrome refresh flag bug that crashes the hamburger menu when clicked has been available in the Nightly Build since July 7th or 8th. However, the fix has not yet been rolled out to other channels.

Steps to Reproduce:
Enabling the 2023 refresh flag on any channel other than the nightly channel will cause the browser to crash when the hamburger menu is clicked.

Actual result:
If the 2023 refresh flag is enabled on ANY channel other than the nightly channel, clicking on the hamburger menu will crash the browser.

Expected result:
Like the nightly builds, to have the 2023 refresh flag not crash the hamburger menu when clicked on.

Reproduces how often:
All the time on any channel other than the nightly builds. The 2023 refresh flag causes the browser to crash when it is enabled on any channel other than the nightly channel. However, the fix for this issue has been available since July 7th, so this should no longer be a problem.

Brave version (brave://version info)
The issue affects all builds of Brave that are lower than 1.58.xx, because the fix for the issue has not yet been deployed to any build other than the nightly build.

Version/Channel Information:
Specific to any build that is not in the nightly channel
- Can you reproduce the issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No, because it has been fixed since July 7th.

Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

Miscellaneous Information:
I have posted in most of the 2023 refresh flag threads, but I have not received a response. I am writing this to get someone's attention. You have closed a few threads about this issue and stated that it has been fixed. However, this is not the case, as the fix is not yet in all of the channels. You have a fix, but it has only been deployed to the nightly build, which was first released to the nightly channel on July 7th or 8th. Telling people to move to the nightly build is not productive. Many people do not know how to move their profiles over, and the nightly build is considered the most unstable of Brave builds. If everyone has to be on Brave build 1.58.xx, it will take a few months for the fix to be released to the other channels. This has caused confusion, as people are continuing to create new threads because they cannot find the threads about this issue for the channel they are using or that state that the issue is "fixed" but only for certain channels.

**Comment by joejoejo** [comment] 2023-07-26 13:21
STILL NO RESPONSE FROM ANYBODY BUT NEWER ISSUES ARE GETTIONG RESPONSES?

**Comment by rebron** [comment] 2023-07-29 06:28
@joejoejo There's a very clear warning on that brave://flags page. WARNING: EXPERIMENTAL FEATURES AHEAD!  

I'm not sure why you even have this flag turned on as we're not taking this feature. The fix for the crash is to disable the flag.

**Comment by rebron** [comment] 2023-07-29 06:38
Closing as duplicate of https://github.com/brave/brave-browser/issues/30499
@joejoejo The issue is already fixed with 30499. The fix may or may not get uplifted into channels like beta or release faster if deemed important. 

If what you're looking for is that new hamburger/application menu we're not shipping with that layout, we have our own and it will look similar to that.

**Closed by rebron** 2023-07-29 06:38 UTC
Labels: closed/duplicate, OS/Desktop

**Comment by joejoejo** [comment] 2023-07-29 18:33
Just because somebody from brave said This a duplicate of the thread I made, IT IS NOT Because this one references posts like the one I made WITHOUT SPECIFICALLY MENTIONING IT. HOW IS THIS COMPLETE WHEN THIS IS NOT IN THE RELEASE OR BETA/DEV CHANNEL STOP MARKING THIS AS COMPLETED UNTIL IT IS IN THE RELEASE AND BETA/DEV CHANNELS.
