### ISSUE TITLE
Other bookmarks is missing, breaking bookmarks API

### ISSUE THREAD

**Issue by Johann999** [brave/brave-browser#7639] opened 2020-01-07 17:27 UTC
Dear Brave,

isn't it frustrating if after the update to version 1.2.41 instead of "Other bookmarks"only ">>" sees?!

The bookmark changes are unnecessary, bring no benefits and only annoy the users.
The structure and layout of the bookmarks has proven itself for many years. There was no reason to change this. Brave is now no longer compatible with other Chromium based browser.

Please undo changes to bookmarks.

Thank you

**Comment by bsclifton** [comment] 2020-01-07 20:21
cc: @rebron @darkdh

**Comment by bsclifton** [comment] 2020-01-07 20:43
This was intentionally removed when solving https://github.com/brave/brave-browser/issues/5158

It's needed or it'll be a problem with iOS/Android

Closing as `wontfix` 😄

**Comment by Hardtarget24** [comment] 2020-01-07 22:43
Unfortunately with this new patch the Other Bookmarks folder is no longer anchored to it's own area on the right hand side of the bookmarks bar.  This is an issue for me personally and not expected behaviour from a chromium based browser.  (and honestly although seemingly minor this change, if intended, will most likely force me to stop using Brave and it's really disruptive to my workflow)

I'm hoping this can be fixed somehow.

**Comment by bsclifton** [comment] 2020-01-07 23:11
per @Rob4226 via https://github.com/brave/brave-browser/issues/5158#issuecomment-571471219
> This update on Windows 10 just broke a bookmark extension xBrowserSync and I had no idea why all day until I finally looked here. Is there any way to change it back (with syncing off), unnesting the Other Bookmarks folder? Thank you.

**Comment by bsclifton** [comment] 2020-01-08 00:02
Going to re-open this; @rebron and @darkdh are looking into this, after comment by @nero120 via https://github.com/brave/brave-browser/issues/5158#issuecomment-571818432
>As this change potentially breaks compatibility with any extension that uses the bookmarks api, what's the plan for dealing with that? Will you be launching your own extensions store shortly since extension authors that use the bookmarks api will now need to provide a separate build for brave...?
>
>I suppose you'll need to update [this](https://support.brave.com/hc/en-us/articles/360017909112-How-can-I-add-extensions-to-Brave-) page from:
>
>> Brave offers support for nearly all extensions that are compatible with chromium.
>
>to something like
>
>> Brave offers support for some extensions that are compatible with chromium (up to you to work out which though)
>
>Any guidance would be appreciated!

**Comment by bridiver** [comment] 2020-01-08 22:17
I wasn't personally a big fan of the change to remove "Other Bookmarks", but (unfortunately ;) I don't always get my way. In any case I can tell you with a high degree of certainty that this change is here to stay. We have had extensive (and heated) discussions about this and it's not likely to change. What could change here is how things are presented in the bookmarks api so that Brave looks like it has the same bookmark structure as Chrome. Basically a kind of "shadow" node that is actually a reference to the bookmarks bar, but appears to be "other bookmarks" in the api. However, known breakage in the extensions could easily be fixed without any changes to Brave and at least one of them relies on undocumented node ids which are not part of the API and hence not even guaranteed to be compatible across chromium versions

**Comment by antonycourtney** [comment] 2020-01-08 22:45
( Moving discussion here from #5158 )

> @nero120 I was surprised they didn't have constants for the bookmarks bar and other bookmarks node. I expected to find them in the api docs and use it as a potential fix inside the api

Agree this is disappointing.

For what it's worth, Tabli doesn't depend on a fixed node ID. It does depend on `tree.children[1]` being the "Other Bookmarks" folder, where `tree` is the root returned from `chrome.bookmarks.getTree`. 
Not great, although I also think that looking for "Other Bookmarks" by name off the root also would have broken with this change.

The only mention I've found about the contents of the root folder in the API docs is this (on the `chrome.bookmarks` API page):

![image](https://user-images.githubusercontent.com/4683413/72021946-1faf1200-3224-11ea-8ca5-e661b2c4e81b.png)

After this change in Brave, are there any guarantees about what will be in the root folder in Brave?
Is "Other Bookmarks" replaced by a folder named "Bookmarks", a folder that exists at the same level as "Bookmarks", a sub-folder of "Bookmarks", or something else?  It's really not clear from all the screenshots above.

@bridiver suggested either leaving the parent id blank or using `children.length - 1` as the index when creating the folder used by my extension. 

I'd like to do the right thing for Brave users. My hunch is that my extension creating a "Tabli Saved Windows" folder on the Bookmarks Bar in Brave isn't going to be an ideal user experience.  "Other Bookmarks" is really a pretty reasonable place for this, but it's not entirely obvious to me if there is an approved replacement for that in Brave.

**Comment by nero120** [comment] 2020-01-08 22:52
> For what it's worth, Tabli doesn't depend on a fixed node ID. It does depend on `tree.children[1]` being the "Other Bookmarks" folder, where `tree` is the root returned from `chrome.bookmarks.getTree`.
> Not great, although I also think that looking for "Other Bookmarks" by name off the root also would have broken with this change.

FYI, you can't really query by name (title) since they change for each language!

**Comment by antonycourtney** [comment] 2020-01-08 23:01
> I wasn't personally a big fan of the change to remove "Other Bookmarks", but (unfortunately ;) I don't always get my way. In any case I can tell you with a high degree of certainty that this change is here to stay. We have had extensive (and heated) discussions about this and it's not likely to change. What could change here is how things are presented in the bookmarks api so that Brave looks like it has the same bookmark structure as Chrome. Basically a kind of "shadow" node that is actually a reference to the bookmarks bar, but appears to be "other bookmarks" in the api. However, breakage in the known extensions could easily be fixed without any changes to Brave and at least one of them relies on undocumented node ids which are not part of the API and hence not even guaranteed to be compatible across chromium versions

If Brave provided a root node with a replacement folder for "Other Bookmarks" at position 1 in the children list, I'm pretty sure this would instantly fix the Tabli extension.

**Comment by edsimpsons83** [comment] 2020-01-09 13:55
This is really disappointing and very user hostile. Moved my entire family over to Brave during the holidays for improved security and woke up to txts this morning asking why their bookmarks have moved around. With Chrome controlling ~70 of the browser market, the vast majority of people switching to Brave expect the "Other Bookmarks" folder to be on the right, not mixed in with their normal bookmarks.

**Comment by georapbox** [comment] 2020-01-09 14:30
> This was intentionally removed when solving #5158
> 
> Removing this was needed to prevent problems with syncing Desktop w/ iOS/Android
> 
> Closing as `wontfix` for now
> 
> cc: @rebron @darkdh @jhreis @kjozwiak for additional comments

Even after solving #5158 the sync issues still remain though. Trying to sync my Mac with android ended up with duplicate folders or missing bookmarks.

**Comment by bridiver** [comment] 2020-01-09 15:45
You can always create a folder inside the bookmarks bar, but I seriously doubt we'll change the node structure because we wanted to standardize it across platforms (unlike Chrome which has a separate "mobile bookmarks" folder)

**Comment by bridiver** [comment] 2020-01-09 15:47
There won't be a replacement per se, but we may decide to fake it to avoid other potential breakage. In that case I think it's likely that "Other Bookmarks" would just be an alias for the bookmarks bar

**Comment by bridiver** [comment] 2020-01-09 17:07
> > This was intentionally removed when solving #5158
> > Removing this was needed to prevent problems with syncing Desktop w/ iOS/Android
> > Closing as `wontfix` for now
> > cc: @rebron @darkdh @jhreis @kjozwiak for additional comments
> 
> Even after solving #5158 the sync issues still remain though. Trying to sync my Mac with android ended up with duplicate folders or missing bookmarks.

This is something we have discussed and it seems silly to me that we don't match up bookmarks by name/url/folder. I can't see any reason why anyone would intentionally create a duplicate of a bookmark in the same folder cc @davidtemkin, however that is a separate issue that should have its own ticket.

**Comment by BrendanEich** [comment] 2020-01-11 00:46
@antonycourtney @edsimpsons83 This was a mistake, we will fix as best we can. Sorry about it and please stay tuned.

**Comment by nsy16** [comment] 2020-01-12 00:17
It would be nice to get my xBrowserSync extension working again. Only started using Brave since November last year after considering many alternative browsers.

**Comment by Spencer4134** [comment] 2020-01-13 07:00
Yes, due to lack of 1st-party implementations for every platform (talking about things like Arch Linux here) I have a need for other browsers sometimes, so xBrowserSync functionality is a must. It sounds like based off of what @BrendanEich is saying that you guys are planning on undoing it, but if you go the route of making "Other Bookmarks" an alias, please do **not** make it for the Bookmarks Bar, but instead a folder called "Other Bookmarks" that can be put wherever on the Bookmarks Bar. Otherwise we'll have a mess on our hands with any extensions that sync Bookmarks.

**Comment by mhatvan** [comment] 2020-01-13 10:31
For me it happened that after brave auto-updated, all my 2000+ bookmarks disappeared, because https://www.everhelper.me/synchronizer.php couldn't deal with the changes. 
@nsy16 and others, I recommend to install Brave version 1.1.23 temporarily to have the old bookmarks structure back and sync it, works for me.

**Comment by bridiver** [comment] 2020-01-13 16:23
fyi - we're having a discussion now based on all the feedback and known incompatibilities with extensions and all options are on the table including restoring the other bookmarks node

**Comment by nero120** [comment] 2020-01-13 17:39
> fyi - we're having a discussion now based on all the feedback and known incompatibilities with extensions and all options are on the table including restoring the other bookmarks node

If I may...

- Whatever the final decision, can you please ensure that the bookmarks API is aligned with Chrome, in terms of available containers (Other bookmarks/Boomarks bar/Mobile bookmarks) and properties such as titles, ids (container ids are _mostly_ consistent in Chrome - Bookmarks bar = `'1'` and Other bookmarks = `'2'`), etc, and,
- Is it possible to roll back the changes until a workable solution has been implemented?

**Comment by bridiver** [comment] 2020-01-13 18:48
Rolling the changes back may be what we end up doing, but it's not a simple thing to do at this point. It affects sync among other things so it's not something we can just quickly rollback and release

**Comment by lbdl** [comment] 2020-01-14 10:41
this is somewhat of a deal breaker for many. It is more or less impossible to work productively without the ability to sync bookmarks across devices. I switched happily to Brave over a year ago despite the never ending frustration with no sync, and no comments of the multiple issues surrounding Braves own sync (which is still unusable). XBrowserSync fixed this for me, hooray and now the OtherBookmarks killing kills XbrowserSync and I'm forced to implement ugly hacks around exports/diffs/etc. Might I suggest the attitude that sync is ESSENTIAL for uptake of the platform NOT optional and as such changes that disable the ability to use third party sync tools (i.e. deviating from "standard" bookmark structures without providing a workaround) should not be implemented also the native sync's complete non workability  might be addressed.  I don't wish to to take away from the excellent thing that is the Brave browser team I like the platform and use it pretty much exclusively despite the (quite a few) issues as I am sure they will be sorted in due course. I think this needs to be looked at differently hence my comments. Thanks

**Comment by t3mujin** [comment] 2020-01-14 11:42
Just wanted to add my $0.02 here because I'm have a similar issue with my own sync strategy, despite not using xBrowserSync. I'm using a self-hosted solution so I have installed Floccus on all my browsers that syncs to my own Nextcloud server. Since browsers have slightly different solutions for menu/toolbar boomarks what I do is set them up separately (no big deal there, two syncs instead of one), but with this option of nesting the Other Bookmarks inside the Toolbar bookmarks it messed everything up, and with no easy workaround...

**Comment by bsclifton** [comment] 2020-01-16 23:00
Possibly causing crash in Brave introduced with [Switchmark](https://chrome.google.com/webstore/detail/switchmark/bnocffbiglfjjcgmifcampfmcbkfbhgc) - reported via https://github.com/brave/brave-browser/issues/7638

**Comment by jaredready** [comment] 2020-01-25 22:49
Chiming in as another Chrome convert to say that the removal of Other Bookmarks is really annoying and does not feel well thought out.

I won't pretend to understand the complexities behind bookmark syncing, but I have to say that every browser out there handles it better than Brave does right now. Even extensions developed by single developers handle it better.

If I were involved in the development of bookmark syncing on Brave, I would be seriously considering going back to the drawing board and rearchitecting it from scratch.

Best of luck to you folks, though. I'll still be here as a mostly happy user converting everybody that I can, but I'm having to warn people that bookmark syncing is kind of a mess right now. It's the only real stain on an otherwise great browser.

**Comment by jerrykrinock** [comment] 2020-01-27 06:14
Chiming in as a bookmarks syncing extension and native app developer:  A week or so ago we published updates which accommodate Brave's elimination of _Other Bookmarks_, and our users are no longer complaining.  But if _Other Bookmarks_ were to return, even as a folder with a special _pin to the right_ attribute, this would likely break our extension again :(

The different structures among browsers is an unfortunate fact of life that we have been dealing with for ten years.  It is messy, but we do it.  Of the 8 or so browsers that we support, the only two which currently have the structure are now, surprise, Brave and Vivaldi.  Personally, I think that Brave's new structure, zero hard folders – just put everything in the toolbar, is the best.  The user can define whatever top-level folders they want in there.  Also, there is less cognitive overhead for new users – the name _Other Bookmarks_ is a head scratcher.

By the way, we do not need different extensions – our same extension is used in Brave, Chrome, Edge, Opera and Vivaldi.  Our extension for Firefox runs the same code, but needs an extra key in the package manifest :(  The accommodation of different structures occurs in our native app.  For web-based syncing apps, the accommodation could be done in the server.

I blame the Chrome team for originally not documenting their structure in the `chrome.bookmarks` API at all – we had to reverse-engineer it as discussed above in this thread, and before them, the Netscape team or whomever it was that originally conceived of a separate _Bookmarks Bar_ and _Bookmarks Menu_, which is where all this mess began.

**Comment by jsecretan** [comment] 2020-01-28 13:39
Hi @jerrykrinock is there a way for you to change behavior by versions?  Or anything easy we could do to accommodate your use case?  It's a tough spot to be in because of course many are asking us to bring back the Other Bookmarks node.

**Comment by LaurentOngaro** [comment] 2020-01-28 14:23
For my part, I don't miss the "Other bookmarks" node, I find the new bookmarks structure much cleaner, but the loss of compatibility with synchronization extensions is really annoying

**Comment by jerrykrinock** [comment] 2020-01-28 21:19
@jsecretan: My native app could check the Brave version.  But I probably would not do it this way, because I foresee a high probability of bugs due to race conditions and other unforeseen phenomena.  Instead, I would get the dev version of Brave, reverse-engineer as necessary and update the code in my native app to handle either old or new.  This will be messy, but I've done stuff like this before and survived.

This is the one disadvantage of Brave not registering developers in its own extensions "store" – Brave has does not even know who the extension developers are and has no way to warn developers of breaking changes.  Piggybacking on the Chrome store makes much less work for extension developers, and I very like it, muchos gracias.  What would be most helpful is some kind of channel which developers could "tune" to in order to be advised of upcoming breaking changes.

**Comment by jerrykrinock** [comment] 2020-01-28 21:27
@LaurentOngaro, bookmarks synchronization extensions can be updated to map between browsers that have _Other Bookmarks_, such as Chrome and Edge, and browsers which do not, like Brave and Vivaldi.  Presumably whatever extension you using will be updated eventually.  When it is, you will get best results by leaving the _Other Bookmarks_ in Chrome, Edge or whatever empty, so that no mapping is necessary.

**Comment by antonycourtney** [comment] 2020-02-08 00:55
@bridiver Is this issue still under active review by the Brave team? I'd really like to get Tabli working on Brave again. I can easily apply what I consider the hacky fix (putting "Tabli Saved Windows" on the Bookmarks Bar) to get Tabli working again, but I have held off on that for the past month in the hopes of some clear guidance on what will happen with this issue from Brave devs.

**Comment by ch0rn** [comment] 2020-02-08 15:51
For the love of god bring back the ability to pin a folder to the right hand side.  This is total crap, I personally use 3 different desktop devices all with different resolutions.  So now my damn bookmarks are always in a different place.

**Comment by gabrielmulle** [comment] 2020-02-10 12:47
Today I updated Brave to Version 1.3.113, but it didn't resolve the issue.

**Comment by tlamming** [comment] 2020-02-20 01:53
I was hoping that the update today would have a fix it. Any eta?

**Comment by gabrielmulle** [comment] 2020-02-20 02:12
same here, now Version 1.3.118 and still no bookmarks in my browser

**Closed** 2020-02-20 22:05 UTC
Labels: feature/bookmarks, feature/extensions

**Comment by bsclifton** [comment] 2020-02-23 04:51
Fix has landed and should now be in Nightly (1.7). Next step would be planning the back-port of this


@kjozwiak @rebron @davidtemkin would this be something we want for 1.4? (upcoming release channel). Or would we want to shoot for 1.5? (give the fix a little more time to bake)

**Comment by jerrykrinock** [comment] 2020-02-23 22:59
To summarize: There was some difficulty with bookmarks syncing, and it was determined that the complicated and ill-defined bookmarks structure inherited from Chrome was preventing a clean solution.  Now, after the migration to a simpler structure has been in the field, it is decided to revert to the original structure.  Our _brave_ developers shall, without noticeable disruption, reverse-migrate users, some of whom may have several synced devices, some migrated and some not, using various versions of Brave, back to the original structure.  And then, I presume, solve the _original_ syncing difficulty.

This will be a very impressive accomplishment.

**Comment by nero120** [comment] 2020-02-23 23:02
@jerrykrinock out of interest, what exactly was so difficult about syncing the original chrome bookmarks structure?

**Comment by jerrykrinock** [comment] 2020-02-24 03:06
@nero120 First of all, I'm not with Brave.  I am just an bookmarks-related extension deveIoper who subscribed to this issue because I need to support Brave's past and future changes.

To answer your question, I'm just recalling what I read, maybe it was in the Brave forums or maybe it was in the original issue wherein they decided to remove Other Bookmarks.  And I do recall that, in the original 2009 chrome.bookmarks API, the _Other Bookmarks_ was not properly defined by Google, so I had to do some reverse engineering.  I suspect it has something to do with the fact that synchronizing a tree is complicated enough if there is only one "hard" root item.

**Comment by gabrielmulle** [comment] 2020-02-26 13:19
Another update, another version and another disappointment.
How can a famous browser in 2020 be this broken?
Yeah the fix is in nightly I saw, but I think I just wanted you to be this cautious before you have implemented the change that broke the bookmarks in the first place
This is extremely frustrating in the point of view of an end user.

**Comment by stmuk** [comment] 2020-02-29 09:43
> Fix has landed and should now be in Nightly (1.7, which is slated for Release channel on April 28). Next step would be planning the back-port of this (ex: Dev 1.6/April 7, Beta 1.5/Mar 17, Release 1.4/Feb 25)
> 
> @kjozwiak @rebron @davidtemkin would this be something we want for 1.4? (upcoming release channel). Or would we want to shoot for 1.5 or 1.6? (give the fix a little more time to bake)

I am right in thinking this fix isn't in Version 1.4.95?

**Comment by bsclifton** [comment] 2020-03-02 07:04
@stmuk this is currently only in Nightly (1.7)

Per [our release schedule](https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#release-channel-dates), 1.7 is scheduled to be publicly released on April 28

@rebron @kjozwiak  should this fix be uplifted to 1.6? (scheduled for April 7). It's definitely too late to pull into 1.5 (scheduled for March 17)

**Comment by Johann999** [comment] 2020-03-03 11:25
Please correct the problem as soon as possible.
Thank you very much.

**Comment by jsecretan** [comment] 2020-03-03 21:26
FWIW, @bsclifton I would say to try to uplift into 1.6.

**Comment by bsclifton** [comment] 2020-03-04 06:15
Actually- uplift may not be needed... current plan is to expedite 1.7 to April 7 😄 (skipping the 1.6 version)

**Comment by jerrykrinock** [comment] 2020-03-21 04:46
What is the decision, please?   I were going to parameterize my bookmark extension to expect Other Bookmarks or not based on the Brave version number, would I set the cutoff to 1.6 or 1.7?

**Comment by gabrielmulle** [comment] 2020-04-07 20:00
> Actually- uplift may not be needed... current plan is to expedite 1.7 to April 7 😄 (skipping the 1.6 version)

I've been visiting the "About Brave" today to update brave and finally resolve this issue that is affecting us since January, but until now, no update. Do you know when the update will be released?

**Comment by LaurenWags** [comment] 2020-04-07 20:00
Verified passed with

Brave | 1.7.86 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | macOS Version 10.14.6 (Build 18G3020)

Verified test plan from https://github.com/brave/brave-core/pull/4404

**Migrate previous migration** - **Pass**
* Confirmed STR from test plan for this scenario
* Note, if 'Other Bookmarks' is not at the end of the Bookmark Bar (it is somewhere in the middle), the migration will not occur. In this case, a new 'Other Bookmarks' folder is created as a permanent node

**Virtual "Other Bookmarks" Mapping**
* **Create** - **PASS**
   * Device A macOS Mojave, Device B macOS Mojave, Device C iPad mini iOS 13
   * Confirmed all devices received folders as expected

* **Delete** - **PASS**
   * Device A macOS Mojave, Device B macOS Mojave, Device C iPad mini iOS 13
   * Confirmed empty 'Other Bookmarks' on both desktop devices

* **Move** - **PASS**
   * Device A macOS Mojave, Device B macOS Mojave, Device C Pixel 3 XL

* **Reorder** - **PASS**
   * Device A macOS Mojave, Device B macOS Mojave, Device C Pixel 3 XL

* **Rename** - **FAIL**
   * Device A macOS Mojave, Device B macOS Mojave, Device C Pixel 3 XL
   * Scenario does not behave as expected, logged follow up issue https://github.com/brave/brave-browser/issues/9073

* **Late joined desktop(1)** - **PASS**
   * Device A macOS Mojave, Device B macOS Mojave, Device C Pixel 3 XL

* **Late joined desktop(2)** - **PASS**
   * Device A macOS Mojave, Device B macOS Mojave, Device C Pixel 3 XL

Other Scenarios I executed:

1. Clean profile 1.7.x --> confirmed 'Other Bookmarks' is available on bookmarks manager

2. Clean profile 1.5.x --> confirmed 'Other Bookmarks' is not available on bookmarks manager --> upgrade to 1.7.x --> confirmed 'Other Bookmarks' is available on bookmarks manager

3. Upgrade profile from 1.1.x (Other Bookmarks exists):
 * Installed 1.1.23. (last version with 'Other Bookmarks' folder)
 * Confirmed presence of 'Other Bookmarks'
 * Added bookmarks/folders/both to 'Bookmarks' and 'Other Bookmarks' folders.
 * Upgraded to 1.2.41
 * Confirmed 'Other Bookmarks' is as per https://github.com/brave/brave-browser/issues/5158 (quick checks of this only, sync never enabled)
 * Upgrade normally to 1.5.x
 * Confirmed 'Other Bookmarks' did not return to same place as 1.1.x
 * Upgraded on `test` channel `1.7.x`
--> Confirmed 'Other Bookmarks' is moved to permanent node as expected 
--> Confirmed 'Other Bookmarks' displays on bookmarks bar on right side
--> Confirmed able to add a bookmark to 'Other Bookmarks' after migration
--> Confirmed able to add a folder to 'Other Bookmarks' after migration
--> Confirmed able to add a bookmark into the folder added in step above.

before upgrade to 1.7.x:
<img width="1190" alt="1 5 x from 1 2 x pre migration - addtl scenario1" src="https://user-images.githubusercontent.com/28145373/78713818-d6389680-78e8-11ea-8850-446bc21a16be.png">

after upgrade to 1.7.x:
<img width="1044" alt="1 5 x to 1 7 x migration addtl scenario1" src="https://user-images.githubusercontent.com/28145373/78713825-d89af080-78e8-11ea-8d74-99eda0fa7e8e.png">

**Comment by rebron** [comment] 2020-04-07 20:08
Hi @gabrielmulle. We have a candidate build out now that we're testing, 1.7.86 and looking to make it available this Thursdaay.

**Comment by rebron** [comment] 2020-04-07 20:14
@jerrykrinock Sorry for the super late response but yes 1.6 did not have other bookmarks. Other bookmarks was added back in 1.7.6.

**Comment by jerrykrinock** [comment] 2020-04-07 23:57
Thank you, @rebron.  I found the release calendar a couple weeks ago.  On April 3 I published an update to my apps which will supposedly handle bookmark imports and exports with all versions of Brave, with or without the hard _Other Bookmarks_.  I also posted a support article explaining the situation and advising users to ignore the warnings and circuit breaker tripping which will presumably occur when large numbers of bookmarks are moved back into the resurrected hard _Other Bookmarks_.
