### ISSUE TITLE
Wallet powered by Uphold banner should be removed when wallet is disconnected from Uphold

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#17479] opened 2021-08-13 08:39 UTC
## Description 

Wallet powered by Uphold banner should be removed when wallet is disconnected from Uphold

## Steps to Reproduce

   1. Connect to Uphold
   2. Check wallet bottom banner says `Wallet managed by Uphold`
   3. Disconnect wallet 
   4. Uphold banner is still shown 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/129329360-fcc11d9e-1be8-4b11-a915-db8db3876aa3.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/129329467-b309bf32-bb2f-4eb8-9e8c-c4037ff0a2af.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

1.29.x onwards

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Miyayes @brave/rewards-client @brave/legacy_qa

**Comment by Miyayes** [comment] 2021-08-13 15:41
I think @zenparsing worked on something similar -- not sure if different in this case since it involves Uphold connection first, and then unlinking/explicit disconnecting!

**Comment by srirambv** [comment] 2021-08-13 15:53
Maybe dupe of #17115? But even if user connects and then disconnects it shouldn't say its managed by Uphold IMO.

**Comment by kjozwiak** [comment] 2021-08-13 17:24
This was QA'd via https://github.com/brave/brave-core/pull/9672#issuecomment-897306691 before being uplifted into `1.29.x`. I checked and made sure that once you've connected to Uphold and disconnected, the message goes away. I did a quick double check again just to make sure and it's working as expected. Example:

**`New Profile`** | **`Connected`** | **`Disconnected`**
-------------------|-------------------|----------------------
![Untitled](https://user-images.githubusercontent.com/2602313/129386416-56d4af0d-6bcc-4c9e-8c57-1978b1884166.png) | ![Untitled1](https://user-images.githubusercontent.com/2602313/129396622-a2df0852-29ca-425a-a70f-97e04a7e34e4.png) | ![Untitled2](https://user-images.githubusercontent.com/2602313/129396640-5d9f357a-76c1-419a-8b94-73dd7b751383.png)

Closing as a duplicate of https://github.com/brave/brave-browser/issues/17115 👍 @srirambv nice catch though!

**Closed by kjozwiak** 2021-08-13 17:24 UTC
Labels: bug, feature/rewards, QA/Yes, release-notes/exclude, OS/Desktop, feature/Uphold-wallet
