### ISSUE TITLE
[Desktop] Ads displayed for profile where Ads are off when another profile has ads enabled - follow up to 7441

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#10588] opened 2020-07-07 15:30 UTC
## Description 

Issue originally reported in #7441 still reproduces.

From #7441:
> If a user has a profile with ads/rewards on and one with ads/rewards off, even if a window is not open for the profile with ads on, ad notifications are still presented to the user. 

## Steps to Reproduce

Scenario 1:
1. Using 1.10.97 reproduce the issue as described with steps from https://github.com/brave/brave-browser/issues/7441#issue-539348259
2. Upgrade to 1.11.x
3. Open window for profile B, browse to a site like brave.com
4. Close window. 
5. Browse as normal in window for profile A.
6. Ad notification will be triggered.

Scenario 2 (steps from https://github.com/brave/brave-browser/issues/7441#issue-539348259):
   1. Clean profile (Profile A).
   2. Enable Rewards. Now disable Rewards. Leave window for this profile open.
   3. Add another profile (Profile B).
   4. Enable Rewards, set ads to show 5x per hour.
   5. Visit a site like brave.com in Profile B window and then after page loads, close the window for Profile B.
   6. Browse normally on window for Profile A.

## Actual result:

You are served ad notifications.

## Expected result:
We should respect the profile you are using and not serve ad notifications.

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.11.90 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? unsure, probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/legacy_qa @jsecretan @tmancey

**Comment by tmancey** [comment] 2020-08-05 12:17
Duplicate of https://github.com/brave/brave-browser/issues/11042

**Closed by tmancey** 2020-08-05 12:17 UTC
Labels: OS/Desktop, QA/Yes, bug, feature/ads, priority/P3, release-notes/include
