### ISSUE TITLE
Better coin selection algorithm for bitcoin

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#34254] opened 2023-11-10 12:47 UTC
Some randomized approach like done by sparrow wallet for example
https://github.com/sparrowwallet/drongo/blob/28551247c699c79561180dfe1c2b02db2b742a27/src/main/java/com/sparrowwallet/drongo/wallet/KnapsackUtxoSelector.java

**Comment by yrliou** [comment] 2023-12-04 17:59
Closing as duplicate of https://github.com/brave/brave-browser/issues/34508.

**Closed by yrliou** 2023-12-04 17:59 UTC
Labels: feature/web3/wallet, OS/Desktop, feature/web3/wallet/bitcoin
