### ISSUE TITLE
App crashes when opening in app notification settings

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#26481] opened 2022-11-02 14:38 UTC
## Description 
Crash when navigating to settings > Notifications > In-app notifications

```
2022-11-02 10:31:39.449 9220-9220/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.brave.browser, PID: 9220
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
        at EN2.a(chromium-MonochromePublic6432.aab-stable-414511624:6)
        at androidx.preference.Preference.<init>(chromium-MonochromePublic6432.aab-stable-414511624:76)
        at bY2.<init>(chromium-MonochromePublic6432.aab-stable-414511624:2)
        at org.chromium.chrome.browser.settings.BraveMainPreferencesBase.i3(chromium-MonochromePublic6432.aab-stable-414511624:325)
        at rD.run(chromium-MonochromePublic6432.aab-stable-414511624:3)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8582)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
2022-11-02 10:31:39.450 1584-2890/? D/MdnieScenarioControlService:  packageName : com.brave.browser    className : org.chromium.chrome.browser.settings.BraveSettingsActivity
2022-11-02 10:31:39.683 9971-9971/? W/chromium: [1102/103139.683019:WARNING:exception_snapshot_linux.cc(263)] fpsimd not found
2022-11-02 10:31:39.685 9971-9971/? E/chromium: [1102/103139.685205:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: Permission denied (13)
```

## Steps to reproduce 

   1. Clean install
   2. Navigate to settings > notifications > in-app notifications
   3. Observe

## Actual result 

https://user-images.githubusercontent.com/17885425/199518099-fd722783-a68d-4360-955f-ea0f78f232da.mp4

## Expected result
no crash

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Galaxy devices
   - Android version: 12, 11
   
## Brave version
1.45.116

**Comment by kjozwiak** [comment] 2022-11-02 18:12
Closing as a duplicate of https://github.com/brave/brave-browser/issues/26440 which was already uplifted into `1.45.x`.

**Closed by kjozwiak** 2022-11-02 18:12 UTC
Labels: bug, crash, QA/Yes, regression, OS/Android
