### ISSUE TITLE
Saved passwords removed after browser update

### ISSUE THREAD

**Issue by gigabite-pro** [brave/brave-browser#40069] opened 2024-07-29 04:06 UTC
### Description

- Brave removed all the saved passwords from the Desktop app.
- The passwords are still available on mobile (iOS) and the Sync is on.
- New passwords are not being saved either.

### Steps to reproduce

1. Go to `brave://password-manager/passwords` on a Windows desktop.

### Actual result

- There will be no saved passwords. Just a button to import passwords from a file.
- Importing doesn't work as well as mentioned here #39980.
- Saving new passwords (without importing) has also stopped working.

### Expected result

Should have had all the previously saved passwords synced with other devices.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave: 1.68.131 Chromium: 127.0.6533.73 (Official Build) (64-bit)
Revision: 8167dd98e054f33ff258260aaf64d2eba8110772
OS: Windows 11 Version 23H2 (Build 22631.3958)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by Fahl-Design** [comment] 2024-07-29 10:43
```
brave-browser 1.68.128 [Brave Browser/stable main]
├── ist installiert
└── The web browser from Brave
```
same on debian 12.6

**Comment by rebron** [comment] 2024-07-29 21:38
Dupe of https://github.com/brave/brave-browser/issues/40091

**Closed by rebron** 2024-07-29 21:38 UTC
Labels: OS/Desktop

**Comment by rebron** [comment] 2024-07-29 21:39
@gigabite-pro Thanks for reporting. We have the fix coming in https://github.com/brave/brave-browser/issues/40091 and thanks @Fahl-Design for communicating the workaround.

**Comment by CD4NV** [comment] 2024-07-30 09:55
Same thing. Thanks Brave, after another update they destroyed all my passwords for 3 years. I think it's time to switch to another browser.

**Comment by mdlueck** [comment] 2024-08-01 22:22
> 
> same on debian 12.6
> 
> edit: workaround: run with this flag
> 
> ```
> brave-browser --enable-features=SkipUndecryptablePasswords
> ```

aaahhh.... a little late to find this "workaround" as all of my passwords got wiped out, running Brave on Xubuntu 22.04. I am not pleased at this severe issue running Brave Browser.
