### ISSUE TITLE
Importing account doesn't auto-discover NFTs

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30713] opened 2023-05-31 10:01 UTC
## Description 

Importing account doesn't auto-discover NFTs

## Steps to Reproduce

   1. Clean install 1.52.116 and create wallet
   2. Import Eth/Sol account that has NFTs
   3. Switch to NFT tab, Enable NFT auto-discovery
   4. No NFTs are listed

## Actual result:

Importing account doesn't auto-discover NFTs

## Expected result:
Should auto discover NFTs

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes when 1.52.x goes to release
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? No

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
1.52.116

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe @Pavneet-Sing

**Comment by nvonpentz** [comment] 2023-06-29 16:28
Closing since I could not reproduce. Perhaps the assets did not show immediately, but would have shown given enough time.

**Closed by nvonpentz** 2023-06-29 16:28 UTC
Labels: bug, priority/P3, QA/Yes, release-notes/exclude, feature/web3/wallet, OS/Android, feature/web3/wallet/nft
