### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by reisraff** [brave/brave-browser#1936] opened 2018-10-31 16:19 UTC
## Description 

Should be amazing having a changelog file

## Actual result:

Today I can't see easily what was published in the last release.

## Expected result:

Be able to see in small comments what was introduced in the actual release

**Comment by srirambv** [comment] 2018-10-31 16:46
Dupe of https://github.com/brave/brave-browser/issues/1209

**Closed by srirambv** 2018-10-31 16:46 UTC
