### ISSUE TITLE
Brave ads not appearing with Wayland (Fedora 33)

### ISSUE THREAD

**Issue by zikalify** [brave/brave-browser#14800] opened 2021-03-18 00:19 UTC
## Description 
I'm running Fedora 33 which uses Wayland. I'm seeing new tab page ads but haven't had a pop-up ad. I think it could be due to the fact that Fedora 33 is running Wayland and not X.Org.

## Steps to Reproduce

   1. Install Fedora
   2. Install Brave
   3. Use Brave, no pop-up ads.

## Actual result:
Pop-up ads do not appear

## Expected result:
Pop-up ads should appear

## Reproduces how often: 
I've tried clearing the brave folder in my home directory and nothing changed.

## Brave version (brave://version info)

Brave | 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | Linux
JavaScript | V8 8.9.255.20
User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=PrefetchPrivacyChanges,SafetyTip,AutoupgradeMixedContent,WebUIDarkMode,PasswordImport,ReducedReferrerGranularity,LegacyTLSEnforced,DnsOverHttps --disable-features=AutofillServerCommunication,TabHoverCards,TextFragmentAnchor,SafeBrowsingEnhancedProtectionMessageInInterstitials,IdleDetection,PrivacySettingsRedesign,NotificationTriggers,WebOTP,DirectSockets,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,AutofillEnableAccountWalletStorage,SafeBrowsingEnhancedProtection,SignedExchangeSubresourcePrefetch,LangClientHintHeader,NetworkTimeServiceQuerying --flag-switches-begin --flag-switches-end
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/paulhill/.config/BraveSoftware/Brave-Browser/Default
Variations | 7146a73c-3d47f4f4

## Version/Channel Information:
I've only tested this in the stable version of Brave.

**Comment by rebron** [comment] 2021-03-19 17:52
cc: @tmancey Looks like ad notifications aren't being displayed via Fedora and Wayland

**Comment by mrchilly0** [comment] 2021-03-21 02:03
Can verify. I'm still trying to troubleshoot, but it works in X but not wayland. I can go to test websites and get a popup, other programs (music player) notifications work, but not brave pop-up ads. I have tried 2 notification apps (dunst and mako) with the same results. I'll append a debug log when I can, but I may need some guidance on where to look.

**Comment by tmancey** [comment] 2021-04-06 07:54
Closing as duplicate of https://github.com/brave/brave-browser/issues/13866

**Closed by tmancey** 2021-04-06 07:54 UTC
Labels: OS/Desktop, OS/Linux, closed/duplicate, feature/ads
