### ISSUE TITLE
Tracking issue for cosmetic filters on Android 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14379] opened 2021-02-26 13:55 UTC
## Description 
Tracking issue for cosmetic filters on Android 

## Actual result 
Ad space shown on sites

## Expected result
No ads space shown on site

## Issue reproduces how often 
Issue on Android mobile

nytimes.com | washingtonpost.com
-- | --
![image](https://user-images.githubusercontent.com/17010094/109308420-e4154400-7839-11eb-8616-fc273a5d737f.png) | ![image](https://user-images.githubusercontent.com/17010094/109308350-cea01a00-7839-11eb-84cd-a85c8791a24d.png)

**NOTE: No ad space shown on washingtonpost.com for tablet**

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes after 1.21.x goes live
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.21.69

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by SergeyZhukovsky** [comment] 2021-05-26 19:02
@ryanbr are we ok with that? nytimes I found that it's hidden with aggressive mode enabled. We have it implemented in Nightly build already for Android(Settings->Brave shields & privacy->Block trackers & ads). For washingtonpost I cannot replicate it at all. @srirambv maybe you can check it with aggressive enabled if you see them? I assume it's the same problem as nytimes.

**Comment by ryanbr** [comment] 2021-05-28 01:09
Using cosmetic flag in brave://flags  Tested bot nytimes and wapo. Washington Post seems fine.

Nytimes seems to have an issue, in Easylist we have the following cosmetic. `nytimes.com##.e12j3pa50` @SergeyZhukovsky 

![nytimes-spacing](https://user-images.githubusercontent.com/1659004/119914831-4145a080-bfb5-11eb-85ce-97fc6442afc0.png)

**Comment by antonok-edm** [comment] 2022-10-24 21:25
@ryanbr is this still relevant?

**Comment by Esokrates** [comment] 2022-10-25 11:11
@antonok-edm @ryanbr I still see placeholders here: https://www.heise.de/news/Ausschliesslich-mit-Linux-IBM-fuehrt-seinen-neuen-Mainframe-ein-7261841.html
with strict blocking enabled:

![image](https://user-images.githubusercontent.com/17780185/197758213-b3f710a6-f466-430d-ad82-1289071daed8.png)

**Comment by Esokrates** [comment] 2022-10-25 11:57
Just tested the nytimes and washingtonpost as OP. Despite the gray placeholder no longer being there, they are now replaced by equally big white space which is not much better imho. Especially on mobile where display space is limited, this is not ideal.
Should this be a seperate issue @ryanbr?

**Comment by Esokrates** [comment] 2023-02-07 10:32
So may I ask again, what exactly is missing on brave's side on Android? From what I see you mostly use the same filters as ublock origin. In Firefox mobile I do not have place holders, while on Brave they waste space on some websites.

**Comment by ryanbr** [comment] 2023-02-09 06:12
I get the same blank, empty space heise.de on FF Mobile+uBO. With default filters.
![Screenshot_20230209_185939_Firefox](https://user-images.githubusercontent.com/1659004/217731187-8d4b1cee-aca6-4ab8-9ebb-851664863c17.jpg)

Enabling Easylist Germany helps remove the empty space, works on Android

**Comment by Esokrates** [comment] 2023-02-09 12:22
@ryanbr Here are screenshots as of today from nytimes.com startpage that compare Brave to Firefox:

## Brave:

![image](https://user-images.githubusercontent.com/17780185/217811311-81c5247a-087b-41ae-911d-c34b0918a57c.png)

Here are my filters:

![image](https://user-images.githubusercontent.com/17780185/217811697-4552005e-b596-437e-a75e-3d45d8a00079.png)


## Firefox:

![image](https://user-images.githubusercontent.com/17780185/217811223-1cec9a95-b350-451a-9733-d1839dd48b8c.png)

Here are my filter settings:

![image](https://user-images.githubusercontent.com/17780185/217811798-eb4be1bb-431a-4395-96fe-013368e84454.png)

**Comment by Esokrates** [comment] 2023-02-09 12:29
@ryanbr Regarding the heise.de example: You are right, that one was not reproducible anymore, sorry I should have mentioned that (I already had Easylist Germany enabled).

Here is another example: 

https://www.golem.de/news/joule-statt-watt-ein-faires-verfahren-zur-leistungsmessung-2302-171765.html

Scroll down the article, in Brave there is a big area of white space below the article, while in Firefox there isn't:

## Brave

![image](https://user-images.githubusercontent.com/17780185/217812964-ca088f2f-2bb5-46a4-a665-b17eec0916fb.png)


## Firefox

![image](https://user-images.githubusercontent.com/17780185/217812987-cd66f715-8284-42fb-9355-2d88e21b28c3.png)

**Comment by Esokrates** [comment] 2023-02-09 12:35
On the washingtonpost.com startpage the difference between Brave and Firefox is more subtle but still noticeable:

## Brave

![image](https://user-images.githubusercontent.com/17780185/217813980-f5c5e7e0-3ce5-40f9-8395-84357bffbc3c.png)


## Firefox

![image](https://user-images.githubusercontent.com/17780185/217814016-0bf55593-66e3-479a-bb09-9ddaae91571c.png)

**Comment by ryanbr** [comment] 2023-02-10 00:18
nytimes was using xpath in uBO, which isn't supported in adblock rust.
golem.de, we used ghide to counter older anti-adblock (now removed)
wapo, fix will land.

Some cosmetics are countered with very specific ubo filters (xpath, procedural..)  which isn't supported

**Comment by Esokrates** [comment] 2023-02-10 09:57
@ryanbr Thanks for having a look. Is there any long-term plan to support those specific ubo filters? Or replace them with equally good supported rules?

**Comment by ryanbr** [comment] 2023-02-12 02:55
Hard to say, some are easier to implement than others. Over time features will improve just no eta. covering 90-95% of the uBO filters isn't too bad tbh

**Comment by antonok-edm** [comment] 2023-03-15 04:25
I think it's safe to close this since Android has had parity with Desktop cosmetic filters for a long time now. If any specific problems remain let's track those in separate issues (this one is really long already!).

**Closed** 2023-09-29 19:05 UTC
Labels: priority/P3, QA/Yes, release-notes/exclude, OS/Android, features/shields/cosmetic-filtering
