### ISSUE TITLE
Adblock lists that are used accurately leak, can this be prevented via farbling or other methods?

### ISSUE THREAD

**Issue by Peacock365** [brave/brave-browser#28563] opened 2023-02-16 18:17 UTC
## Description 

The adblock lists used by Brave accurately leak. This adds to the user's fingerprint and can potentially give the user's real location away despite the use of a VPN or Tor, for example when Brave's default lists along with a specific regional list are used. A unique combination of filter lists, or excessive use of filter lists (anything other than the default, basically) can also make tracking specific users very easy.

## Steps to Reproduce

The leak can be tested / verified here: https://browserleaks.com/proxy

## Actual result:

A unique combination of filter lists leaks.

## Expected result:

Only the default filter lists leak or a random combination of filter lists leaks that changes every time.

## Reproduces how often: 

Easily reproduced.

## Desktop Brave version:

Happens independently of Brave version, OS, device used.

## Android Device details:

Happens independently of Brave version, OS, device used.

## Version/Channel Information:

Happens on all channels.

## Other Additional Information:

You might be able to fool websites regarding the lists used, but websites can still find out which specific connections have been blocked. However, it might be impossible to detect which exact list led to the block. However, the use of a regional list may be inferred even if the leak test is fooled.

Can this robustly be prevented? Especially when a regional list is used when Tor is used at the same time, thereby giving away the country the user is actually in - I think we are talking about a fairly massive leak here...

**Comment by Peacock365** [comment] 2023-02-16 18:17
@pes10k

**Comment by pes10k** [comment] 2023-02-16 18:27
Thank you for repeating this @Peacock365 .  This has come up a number of times, and seems to be the target of a research paper every two years ;) 

In short though, i do not think this is a solvable problem. Extensions and filter lists by design change how a page operates, and a site is going to (at some margin) be able to know how the page is modified. We can take steps to make this less obvious in some cases (farbling for example makes it difficult for the page to know _specifically_ what the browser is doing, even if its easy to detect generally), but at root, if stop or change how a page / site can do a thing, the page/site is going to be able to tell.

Brave's solution then has been to broaden the set of interventions as much as possible, so that Brave users can't be distinguished from each other. This includes shipping a large number of filter lists by default (which we're just about to expand too). But, other than try and reduce as much as possible the need to add custom filter lists, there isn't much we can do about filter lists being detectable.

Im going to close this out as non-actionable, but thank you for raising the concern.  Its good for us to keep aware of this, to _reduce_ the need for users to customize Brave as much as possible

**Closed by pes10k** 2023-02-16 18:27 UTC
Labels: OS/Android, OS/Desktop

**Comment by Peacock365** [comment] 2023-02-16 18:31
I have a question though, do you use certain default list + applicable regional list depending on language setting? If so, would it not be possible to enable various regional lists that can reasonably be described as non-breaking? Because let's say, if my VPN uses a Swiss IP address but my browser is using a Spanish regional filter list, this is suboptimal, but would be mitigated if e.g. a German and French filter list is enabled at the same time?

Or, when strict fingerprinting mode is enabled, can't you randomly select and enable regional filters based on browsing session? I don't think this is completely without mitigation.

**Comment by Peacock365** [comment] 2023-02-16 18:47
Various regional filter lists (at least for major languages) being enabled by default would at least make it impossible to identify the real geographical location of a user just based on the one regional filter list used. The strategy of certain default lists + *only one* regional list depending on language setting is suboptimal. 

This issue needs to be solved by the browser developer as any solution I could attempt on my own would, by definition, be unique.

**Comment by pes10k** [comment] 2023-02-22 19:34
The browser already leaks your language (accept-language, etc) so mirroring the same value in the set of enabled filter lists is not additional fingerprinting surface. On Feb 16, 2023, at 12:47, Peacock365 ***@***.***> wrote:﻿
Various regional filter lists (at least for major languages) being enabled by default would at least make it impossible to identify the real geographical location of a user just based on the one regional filter list used. The strategy of certain default lists + only one regional list depending on language setting is suboptimal.
This issue needs to be solved by the browser developer as any solution I could attempt on my own would, by definition, be unique.
