### ISSUE TITLE
Is vertical tabs being worked on? It's the one missing feature stopping me from switching to Brave.

### ISSUE THREAD

**Issue by ihsw** [brave/brave-browser#13459] opened 2021-01-10 15:24 UTC
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by eljuno** [comment] 2021-01-10 22:11
The issue is logged here #464

**Comment by srirambv** [comment] 2021-01-11 04:20
Closing as dupe of #464

**Closed by srirambv** 2021-01-11 04:20 UTC
Labels: OS/Desktop
