### ISSUE TITLE
Estimated pending rewards should reset monthly

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#15005] opened 2021-03-29 21:41 UTC
## Description

Right now, the estimated pending rewards counter in brave://rewards captures the cumulative total and does not reset every single month. Currently, it only decrements when the BAT is paid out or claimed.

The design team would like the estimated ad earnings counter to appear as follows:

1. **Monthly reset:** Estimated pending rewards counter should show the estimated ad earnings for _this_ calendar month only

2. **Arrival notice:** Since there is a delay between when the user receives their payout and the beginning of the calendar month (since payout day is on the 5th), then from the 1st to the 5th of the month, there should be a countdown that says "Your x BAT is on the way and will be here in n days" (not final text).

In the Ads module in brave://rewards, it should be redesigned and broken out by calendar month as so:

![image](https://user-images.githubusercontent.com/11497541/114082153-6ce0c000-987b-11eb-872e-0b3851e4756e.png)

____________

This will bring the behavior more in line with the upcoming Brave Rewards dropdown panel refresh, as well as the Brave Rewards NTP widget.

**Comment by Miyayes** [comment] 2021-03-31 16:16
@jsecretan for review of above.

**Comment by jsecretan** [comment] 2021-03-31 20:23
Yep, all good by me, the vital part is highlighting the estimated amount on the way, because when we had left that out in early versions, users were very unhappy.  Eager to see the design treatment of that.

**Comment by jsecretan** [comment] 2021-03-31 20:28
I should mention, there is some complexity here though.  I do believe we'll be able to pretty closely estimate the payout, by knowing when the payment tokens were checked in (but cc: @tmancey to keep me honest).  However, there are frequently amounts you earned in a month that will "rollover" to the next month, based on how the protocol works.  It would be best if the design treatment had some way of dealing with this.

**Comment by tmancey** [comment] 2021-04-09 10:27
@jsecretan We can infer the exact amount due from the payment balance endpoint for the previous month

**Comment by jsecretan** [comment] 2021-04-09 12:26
Great, thanks @tmancey

**Comment by Miyayes** [comment] 2021-04-28 21:12
### Clarification

_Current behavior:_ Let's say that a browser has "10 BAT estimated pending rewards this month". In reality, due to the protocol, the user will probably only receive 9 BAT in the upcoming payment date. 1 BAT will be rolled over to the next month's estimated pending rewards.

### How it should work with the new changes above

Given the above example with 10 BAT pending, but 9 to be actually paid out, and 1 leftover:

_Once the new month comes:_

1. The browser should say "9 BAT arriving in 4 days"
2. The 1 leftover will just be rolled over to the "current earnings this month"

**Comment by zenparsing** [comment] 2021-05-13 21:00
The NTP rewards widget should be updated to show the same information (including the "X BAT arriving in Y days" notice).

**Closed** 2021-06-04 14:30 UTC
Labels: OS/Android, OS/Desktop, OS/iOS, design, feature/ads, feature/rewards, priority/P2, rewards-ui-2.0

**Comment by LaurenWags** [comment] 2021-06-23 14:49
Labelling as `QA/Blocked` for now, additional information is needed for the test plan as discussed in last week's Rewards meeting with @zenparsing.

**Comment by LaurenWags** [comment] 2021-07-01 15:39
Verification in progress with

```
Brave	1.27.87 Chromium: 91.0.4472.124 (Official Build) beta (x86_64)
Revision	7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS	macOS Version 10.15.7 (Build 19H1217)
```

<details>
<summary>Scenario 1 - not all tokens from June cashed in prior to Jul 1 (some token roll-over) - Production</summary>

Confirmed starting July 1 the new UI showed as expected on brave://rewards ad panel and NTP widget.
Confirmed new UI showed expected ad grant amount per the cashed in tokens from the logs. 
Confirmed that uncashed in tokens from June rolled over to July and are reflected in the "Current earnings this month (estimated)" value. Note, I had also viewed an ad, which is why the "transactionCount" for July does not match "Ads received this month" and this is expected.
Confirmed that the balance values for June match each other as well the amount of the expected ad grant. 

June 30th `OnGetPayments` result:

```
[15518:775:0630/142335.644018:VERBOSE1:ad_rewards.cc(268)] OnGetPayments
[15518:775:0630/142335.644102:VERBOSE6:ad_rewards.cc(270)] URL Response:
  URL: https://ads-serve.brave.com/v1/confirmation/payment/7............
  Response Status Code: 200
  Response: [{"month":"2021-06","transactionCount":"34","balance":"0.2725"}]
```

July 1st `OnGetPayments` result:

```
[17727:775:0701/080739.643931:VERBOSE1:ad_rewards.cc(268)] OnGetPayments
[17727:775:0701/080739.644033:VERBOSE6:ad_rewards.cc(270)] URL Response:
  URL: https://ads-serve.brave.com/v1/confirmation/payment/7........
  Response Status Code: 200
  Response: [{"month":"2021-07","transactionCount":"2","balance":"0.02"},{"month":"2021-06","transactionCount":"34","balance":"0.2725"}]
```

June 30th | July 1st
----- | -----
<img width="650" alt="Jun30-15005 prod env profile1 ad panel" src="https://user-images.githubusercontent.com/28145373/124150544-a9c5e880-da5f-11eb-8780-1c422ed9cdf6.png"> | <img width="648" alt="Jul1-15005 prod env profile1 ad panel" src="https://user-images.githubusercontent.com/28145373/124150582-b0ecf680-da5f-11eb-8593-de8c3224bf7f.png">
<img width="310" alt="Jun30-15005 prod env profile1 NTP widget" src="https://user-images.githubusercontent.com/28145373/124150559-acc0d900-da5f-11eb-8062-df63f34ec220.png"> | <img width="305" alt="Jul1-15005 prod env profile1 NTP widget" src="https://user-images.githubusercontent.com/28145373/124150605-b5191400-da5f-11eb-89ab-1f64815829a1.png">

</details>

<details>
<summary>Scenario 2 - all tokens from June cashed in prior to Jul 1 (no token roll-over) - Production</summary>


Confirmed starting July 1 the new UI showed as expected on brave://rewards ad panel and NTP widget.
Confirmed new UI showed expected ad grant amount per the cashed in tokens from the logs. 
Confirmed that the balance values for June match each other as well the amount of the expected ad grant. 

June 30th `OnGetPayments` result:

```
[15656:775:0630/142932.484251:VERBOSE1:ad_rewards.cc(268)] OnGetPayments
[15656:775:0630/142932.484350:VERBOSE6:ad_rewards.cc(270)] URL Response:
  URL: https://ads-serve.brave.com/v1/confirmation/payment/2.........
  Response Status Code: 200
  Response: [{"month":"2021-06","transactionCount":"18","balance":"0.145"}]
```

July 1st `OnGetPayments` result:

```
[18180:775:0701/100351.034554:VERBOSE1:ad_rewards.cc(268)] OnGetPayments
[18180:775:0701/100351.034588:VERBOSE6:ad_rewards.cc(270)] URL Response:
  URL: https://ads-serve.brave.com/v1/confirmation/payment/2.........
  Response Status Code: 200
  Response: [{"balance":"0","month":"2021-07","transactionCount":"0"},{"month":"2021-06","transactionCount":"18","balance":"0.145"}]
```

June 30th | July 1st
----- | -----
<img width="656" alt="Jun30-15005 prod env profile2 ad panel" src="https://user-images.githubusercontent.com/28145373/124151390-80598c80-da60-11eb-9925-194508a45260.png"> | <img width="642" alt="Jul1-15005 prod env profile2 ad panel" src="https://user-images.githubusercontent.com/28145373/124151415-88193100-da60-11eb-885d-e47c42788d32.png">
<img width="311" alt="Jun30-15005 prod env profile2 NTP widget" src="https://user-images.githubusercontent.com/28145373/124151404-83ed1380-da60-11eb-8649-4b8b66658100.png"> | <img width="302" alt="Jul1-15005 prod env profile2 NTP widget" src="https://user-images.githubusercontent.com/28145373/124151430-8bacb800-da60-11eb-9f0f-55d56e23085a.png">

</details>

**Comment by jonathansampson** [comment] 2021-07-01 19:20
"Arriving in x days" refers to the _start of the payout process_, and not necessarily when the user will receive their rewards. For some, it may be `x` days. For others, it may be `x + 1` days. Correct?

**Comment by tmancey** [comment] 2021-07-01 19:26
@jonathansampson that is correct

**Comment by jonathansampson** [comment] 2021-07-01 19:36
Thank you for confirming, @tmancey. We should then expect to receive routine feedback from users who fall into the _x + y days_ category, given the current wording.

**Comment by srirambv** [comment] 2021-07-14 08:27
Verification passed on OnePlus 6T with Android 10 running 1.27.100
- Verified starting July 1 the new UI showed as expected on brave://rewards
<img width=300 src=https://user-images.githubusercontent.com/17010094/125589031-c399db89-835a-40aa-8204-408d96cf1b5d.png>
- Verified new UI showed expected ad grant amount per the cashed in tokens from the logs.
- Verified that uncashed in tokens from June rolled over to July and are reflected in the "Current earnings this month (estimated)" value
- Verified able to view ads and "Current earnings this month (estimated)" + "Ads received this month" both increment as expected
- Verified that the balance values for June match each other as well the amount of the expected ad grant
- Verified that the number of days shown on UI decreases each day as it gets closer to the expected ad grant date.
