### ISSUE TITLE
[Android] Pull publisher_info_db

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#9655] opened 2020-05-06 14:26 UTC
## Description 
We need to have an ability to analyse user's db to help figure out problems with rewards. Android uses a sandboxed storage for apps and it's not accessible unless device is rooted. We can add it under `brave://rewards-internals`. Something like a button `Download publisher_info_db`. 

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment] 2020-05-07 09:11
This would be super helpful for @brave/legacy_qa and support. Big ++.

**Comment by NejcZdovc** [comment] 2020-06-01 07:10
closing as dupe of https://github.com/brave/brave-browser/issues/9766

**Closed by NejcZdovc** 2020-06-01 07:10 UTC
Labels: feature/rewards, suggestion
