### ISSUE TITLE
Unable to connect wallet to add tokens on CoinGecko

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19582] opened 2021-11-19 03:29 UTC
## Description 

Unable to connect wallet to add tokens on CoinGecko

## Steps to Reproduce

   1. Try to add a token 
   2. Shows error 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/142560088-371bce6c-b03c-4522-b603-5956ddc4b2bd.png)

## Expected result:
Should connect wallet

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | macOS Version 11.5.2 (Build 20G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by bbondy** [comment] 2021-11-19 20:23
Closing as a duplicate of https://github.com/brave/brave-browser/issues/17878

**Closed by bbondy** 2021-11-19 20:23 UTC
Labels: bug, QA/Yes, release-notes/exclude, feature/wallet, OS/Desktop
