### ISSUE TITLE
Excluded websites re-appear when revisiting that site

### ISSUE THREAD

**Issue by da2x** [brave/brave-browser#2046] opened 2018-11-08 10:57 UTC
## Steps to Reproduce

   1. Visit example.com and wait a few seconds
   2. Close the tab
   3. Go to Brave Rewards and exclude example.com
   4. Open a new tab, visit example.com, and wait a few seconds
   5. Close the tab
   6. Go to Brave Rewards again

## Actual result:

example.com has reappeared on the list.

## Expected result:
example.com should be excluded from the list.

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

0.55.22 Chromium: 70.0.3538.77 (Official Build) (64-bit)
Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment] 2018-11-08 12:12
I think this one should be fixed in 0.56

**Comment by srirambv** [comment] 2018-11-08 14:20
Dupe of #1440

**Closed by srirambv** 2018-11-08 14:20 UTC
Labels: feature/rewards
