### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by JesperDonnis** [brave/brave-browser#36427] opened 2024-02-28 09:19 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Using two external monitors and the macbook one on a caldigit dock
Brave Version: 1.63.161 Chromium: 122.0.6261.57
Operating System: Mac OS X 14.3.1

URL (if applicable) where crash occurred:

Can you reproduce this crash?
yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Having multiple full screen windows on different monitors
2.And other apps full screen as well (eg. an iterm2 window, slack etc)
3. Navigate between desktops using CTRL + left/right arrow - after a while it insta-crashes
Hope this helps. 

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/03701200-b651-8c0b-0000-000000000000

**Comment by bsclifton** [comment] 2024-03-06 05:04
Thanks for the report - this issue is a duplicate of https://github.com/brave/brave-browser/issues/35528 so I will close

Good news is - we have a fix with https://github.com/brave/brave-core/pull/22468 😄 We'll work on getting this merged and pushed out to release channel

**Closed by bsclifton** 2024-03-06 05:04 UTC
Labels: crash, OS/macOS, priority/P2
