### ISSUE TITLE
mute button on tabs get in the way - please add option to disable...

### ISSUE THREAD

**Issue by tbjubnb** [brave/brave-browser#20083] opened 2021-12-14 03:37 UTC
mute button on tabs get in the way - please add option to disable...
----------

don't need a mute button on each tab - it gets in the way and keeps getting clicked by accident when trying to either switch to a tab or close it. 

please provide a simple toggle in preferences (or flag) to enable/disable this "feature".

**Comment by rebron** [comment] 2021-12-17 20:01
Closing as dupe of https://github.com/brave/brave-browser/issues/19979
The flag to disable the click-ability of the audio icon is making it's way through the channels
brave://flags/#tab-audio-icon-interactive

If you're running Nightly, you can try it now.

We're planning on having it available in the next hotfix for 1.33.x before the end of the year.
#19979

**Closed by rebron** 2021-12-17 20:01 UTC
Labels: OS/Desktop

**Comment by tbjubnb** [comment] 2021-12-20 05:40
thank you!!!
greatly looking forward to this...  =)

(just a thought, but in the future please consider that drastic design features like this probably shouldn't be forced upon everyone, especially not without the option to revert back to original behavior - this one in particular has been extra annoying and has remained unaddressed for WAY too long...!)
