### ISSUE TITLE
Sell option is not shown for tokens when grouped by Network or None.

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32724] opened 2023-09-04 10:24 UTC
## Description 

Sell option is not shown for tokens when grouped by Network or None.

## Steps to Reproduce

   1. Set portfolio filter to None/Network
   2. Click on the token menu
   3. Sell option is not shown
   4. Set portfolio filter to Account
   5. Click on the token menu
   6. Sell option is shown

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/b4a8215e-b3fa-408e-a702-078261fec7f8

## Expected result:
Probably show Sell option for a token irrespective of how its filtered

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | 21631edab5a70964c2f5817bfa4d06c32b4ab314
OS | Windows 11 Version 22H2 (Build 22621.2215)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by srirambv** [comment] 2023-09-04 10:33
Also noted that the steps from https://github.com/brave/brave-core/pull/19528 only work if the portfolio is filtered by Accounts. Filtering it by network shows the token menu options but don't really work as intended

https://github.com/brave/brave-browser/assets/17010094/cf78194c-0af5-4fc4-8313-0f433d398690

**Comment by bsclifton** [comment] 2024-02-26 06:40
Closing as duplicate of https://github.com/brave/brave-browser/issues/35550

**Closed by bsclifton** 2024-02-26 06:40 UTC
Labels: design/needs-mock-up, QA/Yes, release-notes/exclude, feature/web3/wallet, OS/Desktop, front-end-change
