### ISSUE TITLE
Pocket extension crashes

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#991] opened 2018-09-06 21:02 UTC
## Description 
Pocket Extension crashes when trying to invoke (by clicking Pocket icon) Page Saved! function.

## Steps to Reproduce
   1. Install Pocket extension: https://chrome.google.com/webstore/detail/save-to-pocket/niloccemoadcdkdjlinkgdfekeahmflj?hl=en
   2. Sign in.
   3. Go to any page and select Pocket icon and Pocket Extension will crash.

## Actual result:
Pocket Extension crashes and requires a reload. Reloading Pocket will keep you in the same crash loop.

On restart of the browser, Pocket icon will be loaded and reappear and may function to 'save to pocket' on 1-2 pages. 3rd page, resulted in a crash.

## Expected result:
Selecting Pocket extension will 'save page to pocket' and display a drop down menu with notification of Page Saved! plus additional related content with the menu disappearing after a few seconds.

## Reproduces how often: 
Every time.

## Brave version (about:brave info) 
Version 0.55.1 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)

### Additional Information
Issue reproduced on Win x64 and MacOS Mojave 10.14 beta

**Comment by stshank** [comment] 2018-09-06 23:16
I experienced this too on MacOS Mojave beta.

**Comment by srirambv** [comment] 2018-09-07 00:39
Dupe of #685 (for a different extension)

**Comment by rebron** [comment] 2018-09-07 04:04
Possible but Pocket extension is crashing and becomes disabled, browser isn't crashing like in #685.

**Closed** 2018-09-08 01:11 UTC
Labels: bug, feature/extensions

**Comment by GeetaSarvadnya** [comment] 2018-09-21 07:54
Verification Pass on:

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
