### ISSUE TITLE
[Bug] Google translate doesnt work - cant connect to network

### ISSUE THREAD

**Issue by inson1** [brave/brave-browser#33823] opened 2023-10-23 09:09 UTC
![brave_FwpA4m6ULw](https://github.com/brave/brave-browser/assets/75314629/48a7016f-f514-4e99-b6e1-f8a3758044df)

**Comment by rebron** [comment] 2023-10-24 04:25
duplicate of https://github.com/brave/brave-browser/issues/3725

**Closed by rebron** 2023-10-24 04:25 UTC
Labels: google, OS/Desktop

**Comment by inson1** [comment] 2023-10-24 07:01
@rebron Sorry, I looked. I don't know how I could have missed that.

**Comment by inson1** [comment] 2023-12-18 09:56
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
