### ISSUE TITLE
Feature: Support "reopen last closed tab" in Private browsing mode

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#7103] opened 2019-11-26 19:07 UTC
## Description 

At this time, when in Private browsing (or Private w/tor) windows, if you close a tab there's no way to reopen it, as there is in standard windows (by using the `History` menu or `ctrl + shift + t`). 

Chrome/Chromium used to allow this but it appears to have been removed at some point. This function should be available to Brave users as well. Note that other Chromium browsers (Vivaldi, Opera) have not implemented this yet. Edge and Firefox still offer this functionality in Private browsing windows:

![ffpt](https://user-images.githubusercontent.com/3299098/69664082-80033f00-103c-11ea-99cf-6cf31ecc0062.gif)

## Miscellaneous Information:

User request: https://www.reddit.com/r/brave_browser/comments/dwb0ig/private_browsing_tabs_restore/

**Comment by bsclifton** [comment] 2019-11-26 22:19
This was previously opened before with https://github.com/brave/brave-browser/issues/5997

Last comment from @rebron suggested to wait for upstream to implement

**Comment by rebron** [comment] 2020-01-24 17:15
Closing. Dupe of #5997

**Closed by rebron** 2020-01-24 17:15 UTC
Labels: feature-request, feature/keyboard-shortcuts, feature/private-browsing, feature/settings
