### ISSUE TITLE
🏠 button in Android (not very important)

### ISSUE THREAD

**Issue by Swastinaik** [brave/brave-browser#24667] opened 2022-08-15 13:44 UTC
Whenever I turn off the _bottom toolbar_
The home button isn't present please fix this issue. whereas chrome has home button even when toolbar is up. By the way great experience by your browser.

**Comment by fallaciousreasoning** [comment] 2022-11-01 03:22
Duplicate of https://github.com/brave/brave-browser/issues/24667

**Closed by fallaciousreasoning** 2022-11-01 03:22 UTC
Labels: OS/Android
