### ISSUE TITLE
Closing last tab should open a new tab (not exit browser)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1002] opened 2018-09-07 06:03 UTC
Carried over from https://github.com/brave/browser-laptop/issues/5873

## Description
If there is only one window and you close all the tabs, Brave will exit on Linux and Windows. Instead of exiting, it should open a new tab

On macOS, when the last tab is closed the browser is left open with no windows. This proposal would also open a new tab

**Comment by nCrazed** [comment] 2018-09-07 07:08
This sounds like how one of the chrome extensions used to work. The problem was that it would sometimes not open the new tab fast enough so the window would die anyway.

**Comment by lostpebble** [comment] 2018-10-12 07:16
Yes please. For some reason I do this often, and coming from Chrome where it simply gave me a dashboard with recently opened tabs, this is surprising behavior.

I guess sometimes you just want a clean slate to start with again. Maybe its a lil OCD, but would be nice to have the option at least.

**Comment by eljuno** [comment] 2019-04-10 20:42
+1 from Community https://community.brave.com/t/closing-last-tab-closes-the-browser-is-there-any-fix-and-also-button-to-open-recent-closed-tabs/52349?u=eljuno

**Comment by Milo-W** [comment] 2019-04-16 08:11
So what's the state of this? Why is it in the backlog? Listen, do you want people to use Brave or do you want to do your own shit no one cares about? We need basic functions which are a STANDARD by now for web browsers. This should be done like with 3 months! And those tickets are from 2018!

**Comment by Brave-Matt** [comment] 2019-05-27 10:50
+1 from Community:
https://community.brave.com/t/prevent-closing-of-last-tab-from-closing-entire-browser/62761/2

**Comment by PiN73** [comment] 2019-05-29 18:11
This extension solves the problem
https://chrome.google.com/webstore/detail/dont-close-window-with-la/dlnpfhfhmkiebpnlllpehlmklgdggbhn

**Comment by PiN73** [comment] 2019-05-29 18:12
Solved with extension [Don't Close Window With Last Tab](https://chrome.google.com/webstore/detail/dont-close-window-with-la/dlnpfhfhmkiebpnlllpehlmklgdggbhn)

**Comment by Gortus** [comment] 2019-11-15 19:29
My +1: I installed Brave and made it my default browser for a couple days to test it out. 

Everything was fine, and I'm particularly interested in the BAT model. But this issue is a deal breaker for me. I'm sure it seems like a minor feature to many, but it's a major inconvenience to me. It's easily configured out of the box in Vivaldi and Firefox, so I'll stick with those.

**Comment by SumatraPeter** [comment] 2020-01-25 18:05
So, will this ever be implemented?

**Comment by Brave-Matt** [comment] 2020-02-13 23:21
+1 https://github.com/brave/brave-browser/issues/1002

**Comment by rebron** [comment] 2020-02-26 22:00
Let's add a setting above this one, default off/unchecked, "Don't close window when closing last Tab"

<img width="686" alt="Screen Shot 2020-02-26 at 1 56 17 PM" src="https://user-images.githubusercontent.com/5951041/75391894-cc5e5500-589f-11ea-957e-6113f99aca33.png">

**Comment by DaveBG0** [comment] 2020-08-15 06:08
I have the same problem. Closing the last tab causes the entire browser to close which looks like a bug. There is X button for this function.

**Comment by antonio-sn** [comment] 2020-09-29 20:25
Same here. I'm planning to move to Brave, but need this feature. It doesn't make sense for me to close the browser if I just close the last tab. At least should be optional.

**Comment by LinusLeonard** [comment] 2021-01-09 11:09
This is literally the only reason why Firefox is my default browser instead of Brave. I want to use Brave sooo badly, but this is a dealbreaker. 

And no, the "Don't Close Window With Last Tab" plugin/addon/extension is not a proper solution because it only works on the last remaning Brave window that you've opened. So if you've got two or more browser windows open (I usually have at least three windows when I work because I've got three monitors), closing the last opened tab on any of these windows will close the window unless it's the last remaining window. The plugin has a setting that "fixes" that, but it breaks the dragging tabs between windows feature, which is also a dealbreaker when working with multiple browser windows.

**Comment by OmanF** [comment] 2021-02-25 08:22
I don't have anything meaningful to contribute to the thread, but I _would_ say that such functionality that is so much sought by so many of your users, as the amount of upvotes and comments in this thread shows, and that is the default of a rival product, and having this issue **open** for 3 years, with comments up a month ago and still, not even a minor advancement towards a solution... well, lets just say doesn't foster much confidence in the product and the team behind it.

Updates? Advancement? Actually implementing it (heck, there are plugins doing this, so it _is_ doable!)?
Crickets.

Nice `Brave` team. Very nice.
Might as well stick with UnGoogled Chromium.

**Comment by SumatraPeter** [comment] 2021-02-26 06:07
The original issue that this one's carried over from is _more than **four years old**_ actually @OmanF. I for one have lost all interest. Unsubscribed. 🙅 👎 👋

**Comment by DmitriiShamrikov** [comment] 2021-03-14 12:44
This is critical. Staying with Firefox until it's fixed

**Comment by bsclifton** [comment] 2021-03-15 07:16
Thanks for your patience folks - there are a lot of issues that we have to sort through and only a limited amount of developers to fix them. We do our best to try to use objective criteria when triaging / prioritizing each of these issues alongside Chromium updates, crashes, and bug fixes

I can definitely appreciate the desire for this feature - this is something we'd absolutely want to implement. Thanks again for your patience
cc: @rebron - maybe we can track this in Asana?

**Comment by Lethiferous** [comment] 2021-04-20 17:37
Apologies for the necro...

FYSA - Still an issue in version 1.23.71 [ Chromium - 90.0.4430.72 (Official Build) (64-bit) ]

**Comment by HattinGokbori87** [comment] 2021-08-28 19:19
> 
> 
> This is literally the only of two reason why Firefox is my default browser instead of Brave (the other one being the UI fonts being way too small and seemingly not customizable). I want to use Brave sooo badly, but this is a dealbreaker.
> 
> And no, the "Don't Close Window With Last Tab" plugin/addon/extension is not a proper solution...

100% agree. THIS IS THE REASON I still have Brave as the backup browser (in case I need Chrome related functionality). If they like their own way that much why they just can't give us at least an hidden option like Firefox (browser.tabs.closeWindowWithLastTab)?

If I remember correctly this was a feature of the old Opera browser, the under-recognized pioneer of *Tabbed Browsing*. Once you get used to this behaviour it's nearly impossible to break from. Some people like to keep 100 tab open at once and so closing the browser with the last tab may not be an issue to them. But everyone is not like that and I think Brave developers should accept this fact.

**Comment by MaciejPolanski** [comment] 2021-12-09 18:59
Let me provide use case for this issue:
1) User installs new shiny Brave browser
2) User goes straight to Settings to make sure everything is OK
3) User closes Settings
4) User starts using his new, shiny...moment... WHERE IS MY BROWSER? 
Did it crash after settings changed?

Obviously this issue not being fixed for so long most likely will never be fixed. 
So I returns to FF, it is not that bad after all :)

**Comment by creative-resort** [comment] 2021-12-15 18:45
It's great to see this in the backlog of upcoming tasks!

It might turn out an easy fix 
for an annoying UX issue.

**Comment by la5v3** [comment] 2021-12-22 19:05
As a workaround you can pin an empty tab. You can then keep closing tabs and don't mind about keeping one tab open while you browse.

**Comment by notDavid** [comment] 2022-04-20 10:16
Fyi, the [Firefox equivalent of this](https://kb.mozillazine.org/About:config_entries) is setting `browser.tabs.closeWindowWithLastTab` to `false` : 

> This preference controls whether closing the last tab, closes the window.

> True: Close window when closing last tab (default)
False: Do not close the window when closing last tab (pre Firefox 3.5 behavior)

> Note: Changing to False prevents Firefox from closing the window when you close the last tab such as with Ctrl+W, and subsequently from closing Firefox itself when closing the last tab of the last Firefox window.

**Closed** 2022-07-20 11:26 UTC
Labels: OS/Linux, OS/Windows, priority/P3, usability, QA/Yes, release-notes/include, feature/settings, OS/Desktop

**Comment by MadhaviSeelam** [comment] 2022-07-29 23:03
Verification `Passed` using

Brave | 1.43.53 Chromium: 104.0.5112.69 (Official Build) beta (64-bit)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | Windows 11 Version 21H2 (Build 22000.795)

### Steps:

- Install `1.43.53`
- launch Brave
- open multiple tabs
- open brave://settings/system
- toggle `OFF`  `Close window when closing last tab`
- close all the tabs except last one
- confirmed when last tab is closed, a new tab opened
- when the browser window is closed, close all tabs warning message is displayed as it's the existing functionality
- toggle `ON`  `Close window when closing last tab`
- closing all tabs, closes the browser
 

https://user-images.githubusercontent.com/98358127/181855463-19bba76d-61f1-4cd7-8503-2c94a228f8ed.mp4
