### ISSUE TITLE
existing users getting warning message when opening shields for the first time - follow up to 5582

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5924] opened 2019-09-06 20:57 UTC
## Description 
When users upgrade from 0.68.x to 0.69.x, they are defaulted to Advanced view as expected (per #5582). However, the first time they open shields, they are given a warning on the shields. Presumably, these are existing users who don't need this warning.

## Steps to Reproduce

   1. Install 0.68.x.
   2. Visit a couple of sites.
   3. Upgrade to 0.69.x
   4. Visit a site and open shields.

## Actual result:
![Screen Shot 2019-09-06 at 4 30 48 PM](https://user-images.githubusercontent.com/28145373/64459924-25a2b400-d0c7-11e9-9dcb-846b55004886.png)

## Expected result:
No warning message

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? 0.68.x no, 0.69.x yes
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by GeetaSarvadnya** [comment] 2019-09-08 18:21
The issue is reproducible in Windows x64 - `0.69.124` Chromium: 76.0.3809.132

**Comment by btlechowski** [comment] 2019-09-09 11:49
Reproduced on 

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Ubuntu 18.04 LTS

**Comment by GeetaSarvadnya** [comment] 2019-09-24 16:20
This issue is reproducible even when the shield is down

Open a site in 0.68.140 and make the shield down and upgrade it to 0.69.128

![image](https://user-images.githubusercontent.com/38657976/65530172-161fc980-df15-11e9-8433-0e73f5e1a714.png)

**Comment by rebron** [comment] 2019-09-27 16:07
wontfix. New UI.

**Closed by rebron** 2019-09-27 16:07 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/shields/panel
