### ISSUE TITLE
Brave news feed infinite spinner

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#31228] opened 2023-06-22 17:57 UTC
## Description 
Happening often on my devices after opening brave or loading new tabs

## Steps to reproduce 

These STR have been reliable to repro the infinite spinner issue on NTP.

   1. Install Brave version 1.54.70
   2. Launch app, open settings to disable NTP SI in new tab page settings
   3. Return to NTP, open some tabs
   4. Go back to settings and re-enable NTP SI
   5. Return to NTP again, observe brave news feed
   6. Repeat steps a few times if not observed

## Actual result 
![screenshot-1687455473440](https://github.com/brave/brave-browser/assets/17885425/7d17a1ca-a510-4209-aea7-2b4812b234c8)

## Expected result
News feed should load

## Issue reproduces how often 
Intermittent

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? N/A
- Can you reproduce this issue with the current Play Store Beta version? N/A
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 13
   
## Brave version
Reproducible on 1.54.70 (CR 114)
Reproducible on 1.54.73 (CR 115)

**Comment by Uni-verse** [comment] 2023-08-15 18:48
This is still reproducible when upgrading to version `1.57.47`, exact steps below. 

1. Install version 1.56.20
2. Enable brave news
3. Add some sources in brave news settings
4. Upgrade to 1.57.47
5. Observe NTP after upgrading
6. Repeat if needed to reproduce (intermittent)

**Comment by i-love-to-code** [comment] 2023-09-21 05:08
I believe the cause of the issue is a missing call back here [publishers_controller.cc](https://github.com/brave/brave-core/blob/4abebb0a9867c74849d09057009e5f1b7bec5927/components/brave_news/browser/publishers_controller.cc#L204). 

@petemill has a TODO here so will be better placed to comment on this.

If the downloading / parsing of publisher data fails, the call will fail silently with no callbacks will be invoked, leaving the UI to wait and wonder.

A simple fix is to invoke the callback that's fired on the [happy path](https://github.com/brave/brave-core/blob/4abebb0a9867c74849d09057009e5f1b7bec5927/components/brave_news/browser/publishers_controller.cc#L251) and handle the lack of data in the UI with a "Reload feed" button etc.

```
diff --git a/components/brave_news/browser/publishers_controller.cc b/components/brave_news/browser/publishers_controller.cc
index b9aec87f7a6804b983a2b5a0692ceaa4676f5536..72642f3101114ea4d72f9cbdf988bf99b3d04aa0 100644
--- a/components/brave_news/browser/publishers_controller.cc
+++ b/components/brave_news/browser/publishers_controller.cc
@@ -202,6 +202,10 @@ void PublishersController::EnsurePublishersIsUpdating() {
         absl::optional<Publishers> publisher_list =
             ParseCombinedPublisherList(api_request_result.value_body());
         if (!publisher_list) {
+          controller->on_current_update_complete_->Signal();
+          controller->is_update_in_progress_ = false;
+          controller->on_current_update_complete_ =
+            std::make_unique<base::OneShotEvent>();
           return;
         }

```

**Comment by kreaninw** [comment] 2023-10-09 14:56
As of Brave 1.58.137, Chromium 117.0.5938.153, this is still happening.

**Comment by kjozwiak** [comment] 2023-10-11 14:23
Adding `OS/Desktop` as we've had reports of the same issue occurring on `Desktop` as per https://bravesoftware.slack.com/archives/C02DT9F5EP5/p1696927887802789. So this is definitely not a `Android` only issue.

**Closed** 2024-04-25 06:20 UTC
Labels: bug, priority/P2, QA/Yes, OS/Android, OS/Desktop, feature/brave-news

**Comment by stephendonner** [comment] 2024-05-08 23:21
## Verified `PASSED` using

```
Brave | 1.66.103 Chromium: 124.0.6367.159 (Official Build) beta (64-bit)
-- | --
Revision | 74d46bb25d9ea5e6432e19f0cf38480cc372b0cf
OS | Windows 10 Version 22H2 (Build 19045.4355)
```



## See also:
* https://github.com/brave/brave-browser/issues/37738
* https://github.com/brave/brave-browser/issues/37972

**Comment by GeetaSarvadnya** [comment] 2024-06-12 09:53
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.67.112`

- Verified the STR from the description and ensured the following:
   - Confirmed that Brave news infinite spinner is not shown when NTP SI switch is disabled/enabled
   - Confirmed that Brave news feeds were shown as expected when NTP SI switch is disabled/enabled
