### ISSUE TITLE
The padding on the sides makes it difficult to select the scroll bar (Brave Nightly)

### ISSUE THREAD

**Issue by hyperio546** [brave/brave-browser#34786] opened 2023-12-08 04:29 UTC
## Description 
So the new Brave UI with the rounded corners has slight padding on the sides, which looks good but the issue is that it is a bit difficult to hold the scroll bar because you have to take the cursor over there, it won't just simply hold like it did before with the previous UI by just going to the edge and then clicking and holding it.

## Steps to Reproduce

   1. Take your cursor to the edge where the scroll bar is
   2. Hold the mouse or touchpad and then try to move the scroll bar
   3. It won't move

## Actual result:

It doesn't select and move

## Expected result:
It should select and move

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

<html>
<body>

Brave | 1.63.20 Chromium: 120.0.6099.62 (Official Build) nightly (64-bit)
-- | --
Revision | 458935430c4b639cbc37cf6a39768b28befe0786
OS | Windows 11 Version 23H2 (Build 22631.2715)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- No, as it does not have the padding on the sides
- Can you reproduce this issue with the beta channel? 
- Haven't checked
- Can you reproduce this issue with the nightly channel? 
- Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- No
- Does the issue resolve itself when disabling Brave Rewards? 
- No
- Is the issue reproducible on the latest version of Chrome? 
- No

## Miscellaneous Information:

It works fine on Edge which also has padding on the sides.

https://github.com/brave/brave-browser/assets/96462198/702ed791-0254-4dff-9214-a0ece00a0f2b

**Comment by rebron** [comment] 2023-12-08 21:43
Closing as dupe of https://github.com/brave/brave-browser/issues/34478 Thanks for the video @hyperio546 That was helpful.

**Closed by rebron** 2023-12-08 21:43 UTC
Labels: design, needs-discussion, OS/Desktop, front-end-change

**Comment by hyperio546** [comment] 2023-12-09 07:53
> Closing as dupe of #34478 Thanks for the video @hyperio546 That was helpful.

My pleasure!
