### ISSUE TITLE
Brave is now intercepting media keys

### ISSUE THREAD

**Issue by ArchFrosty** [brave/brave-browser#3807] opened 2019-03-20 13:37 UTC
## Description 

Note: this is probably a new Chromium "feature".
After the most recent update, Brave intercepts media button key presses on my keyboard (play, stop, skip, etc.). I use these buttons to control desktop Spotify client to play my music, but now while Brave is opened (doesn't need focus) these buttons do nothing. Furthermore if I have a Youtube video opened in one of my tabs (doesn't need to be the active tab), it controls this video (play, pause, [next, previous - if in playlist]).

Even this is somewhat buggy, for example, if video is NOT in a playlist, the next and previous buttons do still control Spotify, but as soon as I switch to a tab with video in a playlist, these buttons control the playlist again.

If this is a wanted feature, at least give me the option to disable it. Please. 

Suggestion to fix: if this behaviour only occurred if the tab with a video is SELECTED (Brave doesn't have to be in focus, just the tab is currently selected), otherwise the key press is not intercepted, this would be a fine compromise.

## Steps to Reproduce

   1. Press media (play, for example) button on keyboard.

## Actual result:

Nothing happens if Youtube video is not opened in some tab.
Plays video if it is opened in one of the tabs.

## Expected result:
If media button is pressed, Brave does nothing, instead Spotify plays my music.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.590

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

I am not familiar with Chromium internals, however according to issue #3299 this does seem like its is a "feature" added in Chromium version 73. My up to date version of Chrome is only version 72 so I cannot replicate this issue there.

**Comment by ArchFrosty** [comment] 2019-03-20 17:35
If anyone has the same issue, I am posting my temporary workaround here.
This is an [AutoHotkey](https://www.autohotkey.com/) script I have written that intercepts the _play/pause_, _next_ and _previous_ media key presses and sends them to Spotify instead of letting Brave intercept them.

```
Media_Play_Pause::
DetectHiddenWindows, On 
PostMessage, 0x319,, 0xE0000,, ahk_exe Spotify.exe
DetectHiddenWindows, Off 
return

Media_Next::
DetectHiddenWindows, On 
PostMessage, 0x319,, 0xB0000,, ahk_exe Spotify.exe
DetectHiddenWindows, Off 
return

Media_Prev::
DetectHiddenWindows, On 
PostMessage, 0x319,, 0xC0000,, ahk_exe Spotify.exe
DetectHiddenWindows, Off 
return
```

**Comment by TDeisinger** [comment] 2019-03-20 19:31
I can confirm I have this issue as well. I use Windows Media player and I realized it stopped taking commands from my keyboard and it would even start playing videos on the browser. I never realized it was the browser doing it.

**Comment by TDeisinger** [comment] 2019-03-20 19:32
I currently use the Dev channel

**Comment by Soben** [comment] 2019-03-21 12:10
I am encountering this issue as well on OSX.

Even after leaving the offending website that took over my Media Keys, I do not regain them to my previous application (Spotify, in this case) until I restart Brave.

This does appear to be tied with the newest Chromium release https://www.neowin.net/news/chrome-73-will-bring-hardware-media-key-support-automatic-picture-in-picture/

**Comment by bsclifton** [comment] 2019-03-21 17:39
Can someone please give this a try? Go to brave://flags and search for `Hardware Media Key Handling`. Disable this setting and let us know if that fixes the issue 😄

**Comment by Soben** [comment] 2019-03-21 17:46
@bsclifton Hey Brian,

This flag being disabled works for me.

I don't mind having it temporarily gain the media keys, though, just want it to relinquish control when done.

But for now, I'll leave the flag active to block Brave from ever taking over my media keys.

**Comment by ArchFrosty** [comment] 2019-03-21 18:00
@bsclifton Yes! That does fix the issue, thank you very much.

**Comment by bsclifton** [comment] 2019-03-21 18:00
Awesome @Soben - thanks for confirming! 😄 Great that folks have a work-around; would be even better if it wasn't needed 😛 

Let's keep this issue open and perhaps (based on the number of upvotes / etc), we can look at disabling the flag by default

**Comment by jbartolozzi** [comment] 2019-04-07 18:30
> Can someone please give this a try? Go to brave://flags and search for `Hardware Media Key Handling`. Disable this setting and let us know if that fixes the issue 😄

Thanks

**Comment by bsclifton** [comment] 2019-05-14 16:31
Maybe this is something we can expose in our settings screen

**Comment by petemill** [comment] 2019-05-14 18:25
Setting conditional could be added here: https://cs.chromium.org/chromium/src/content/public/browser/media_keys_listener_manager.cc?type=cs&g=0&l=19

**Comment by Tywele** [comment] 2019-06-04 12:48
In Chrome I can use my media keys for Google Music (in the browser) even when I watch a video on YouTube. If I use Brave it starts and stops the video instead of the music when I have YouTube open with a video. Can this behaviour be changed somehow?

**Comment by bsclifton** [comment] 2019-06-05 16:18
I believe this was tied to the field trial `HardwareMediaKeyHandling` which we recently dropped. This change has been made in Nightly and will be working it's way through the channels

Can anyone on Nightly confirm that they don't see the problem? If so, I think we're safe to close this out 😄

**Comment by bsclifton** [comment] 2019-06-24 06:54
Closing as this should be resolved in 0.67.x and newer versions

**Closed by bsclifton** 2019-06-24 06:54 UTC
Labels: design, feature/keyboard-shortcuts, priority/P4, workaround/flags

**Comment by LaurenWags** [comment] 2019-06-26 18:48
@bsclifton https://github.com/brave/brave-browser/pull/4551 is actually in 0.68.x milestone, should this issue be moved to match that milestone?

**Comment by bsclifton** [comment] 2019-06-26 20:24
whoops! good catch, @LaurenWags 😄 Fixed!

**Comment by LaurenWags** [comment] 2019-08-06 13:05
Verified passed with

Brave | 0.68.119 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

* Verified able to play, pause, mute, fullscreen, etc a YT video when tab was in focus using expected keys (k, m, f, etc)
* Verified that when the YT tab was not in focus but Brave was, selecting these keys did not affect the YT video.
* Verified that when Brave was not in focus, selecting these keys did not affect the YT video.

**Comment by harooporks** [comment] 2019-08-25 03:15
The fix in v 0.68.131, is not flawless.

The fix only works if your media player of choice is communicating with windows(If it shows the currently playing song on the lock screen and in the volume overlay). If your media player doesn't this or you have disabled it then the only detected source for media within windows will be brave, so the media keys will control brave and your other service at the same time. 

If your media service does communicate with windows then media keys (as of 0.68.131) only affect the service in focus and show the track metadata (rather than "brave.exe" like it did pre 0.68.131)
![image](https://user-images.githubusercontent.com/37671527/63644747-dada8100-c743-11e9-9a40-ca3f48071549.png)
But there is a bug that will pause what ever is in brave when you change focus from music to brave

As a work around, the media flags should be added into the settings menu to make it easier for users to choose how media on brave operates
![image](https://user-images.githubusercontent.com/37671527/63645073-d8c7f080-c74a-11e9-9b36-b0856cb9694c.png)

**Comment by PlayingPenguin** [comment] 2021-02-19 23:30
Sorry to open this issue again. 
But for me with Manjaro on Kernel 5.10.15
Even when changing #hardware-media-key-handling to disabled it still intercepts my media stream.
![Screenshot_20210220_002943](https://user-images.githubusercontent.com/27441458/108572531-c82e1180-7312-11eb-81bb-76d49928b996.png)

**Comment by PlayingPenguin** [comment] 2021-02-21 14:03
I found the problem. The Plasma integration extension was handling the media keys instead of pure brave.
Sorry for necrobumping the issue.

**Comment by bsclifton** [comment] 2021-02-22 07:32
@PlayingPenguin no worries - thanks for sharing what caused the problem for you 😄
