### ISSUE TITLE
Report of gas prices not estimating nicely for BSC

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19615] opened 2021-11-19 23:19 UTC
https://www.reddit.com/r/brave_browser/comments/qxdnz0/new_wallet_gas_fee_bsc/

**Comment by recoveringcultist** [comment] 2021-11-24 22:04
the new brave wallet wallet will only accept 107 as a minimum GWEI amount, but BSC gas prices are usually around 5 lol. I guess it's back to Metamask for now.

**Comment by onyb** [comment] 2021-11-25 04:21
Closing this as duplicate of https://github.com/brave/brave-browser/issues/19706.

**Closed by onyb** 2021-11-25 04:21 UTC
Labels: priority/P2, QA/Yes, release-notes/include, feature/wallet, OS/Android, OS/Desktop
