### ISSUE TITLE
 Tip icon is Not appearing in the Twitter feed

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5228] opened 2019-07-12 14:48 UTC
## Description 

 Tip icon is Not appearing in the Twitter feed

## Steps to Reproduce

   1. Clean profile `0.67.108`
   2. Login Twitter.com
   3. Ensure that the BAT tip icon doesn't appear in the action section of any tweets
   4. Enable Brave Rewards
   5. Verify that Brave tip icons dynamically appear in the Twitter feed within a few seconds
   6. Tip icon is Not appearing in the Twitter feed

*Note*: Please note this is happening only on the new twitter layout.

## Actual result:

 Tip icon is Not appearing in the Twitter feed

![image](https://user-images.githubusercontent.com/38657976/61136574-88216e80-a4e1-11e9-8641-4a916fbd3311.png)

## Expected result:
 Brave Tip icon is should appear in the Twitter feed

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.67.108 Chromium: 75.0.3770.100 (Official Build) beta (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @emerick

**Comment by rebron** [comment] 2019-07-12 16:13
Duplicate of https://github.com/brave/brave-browser/issues/4548?

**Comment by GeetaSarvadnya** [comment] 2019-07-12 16:26
@rebron yup. It's the same issue. When I log into twitter it's redirecting me to the layout which is for mobile.twitter.com there I am not able to see `Tip` icon in the twitter feed.

**Closed** 2019-07-12 16:27 UTC
Labels: duplicate
