### ISSUE TITLE
[ALL] Disable History Collection (Erase on Exit is not the same)

### ISSUE THREAD

**Issue by DarkBlaez** [brave/brave-browser#9488] opened 2020-04-27 15:00 UTC
Fully disable the recording of browsing history. Clear on Exit is not the same. This has been asked for many times in many forums. Yet this easy change has not been done. Is there a real reason why this change is being avoided? Not doing so makes it suspect as to what the reason to still record is. I suppose the only option is to fork this and recode this to truly disable, then release it as an alternate version. I'd like to see an official response as to why this simple change has not been made when it has been one of the most prevalent request across forums.

**Comment by rebron** [comment] 2020-04-28 05:29
Closing. Duplicate of #5329. Thanks for the filing the issue, will +1 #5329 for you.

**Closed by rebron** 2020-04-28 05:29 UTC
Labels: duplicate
