### ISSUE TITLE
DARK MODE ENHANCEMENT

### ISSUE THREAD

**Issue by Dev-i-l** [brave/brave-browser#11853] opened 2020-09-25 05:57 UTC
ADD THE OPTION TO TOGGLE DARK MODE IN THREE DOT MENU

**Comment by srirambv** [comment] 2020-09-25 08:02
Dupe of #11085

**Closed by srirambv** 2020-09-25 08:02 UTC
Labels: OS/Android

**Comment by Dev-i-l** [comment] 2020-09-25 09:10
AS OF NOW WE CAN ENABLE DARK MODE ONLY BY GOING INTO SETTINGS, SO I SUGGEST ADDING THE OPTION IN THREE DOT MENU FOR EASY ACCESSIBILITY, HENCE MY ISSUE IS NOT THE SAME AS #11085

**Comment by Dev-i-l** [comment] 2020-09-25 09:21
> Dupe of #11085

AS OF NOW WE CAN ENABLE DARK MODE ONLY BY GOING INTO SETTINGS, SO I SUGGEST ADDING THE OPTION IN THREE DOT MENU FOR EASY ACCESSIBILITY, HENCE MY ISSUE IS NOT THE SAME AS #11085 AND IT SHOULD BE REOPENED
