### ISSUE TITLE
Brave Freezing Issue

### ISSUE THREAD

**Issue by EncryptTown** [brave/brave-browser#5360] opened 2019-07-23 23:37 UTC
## Description 

When Brave is being used, duckduckgo and some other pages freeze. When looking in the network tab it is observed that the fonts (and on occasion the css) take anywhere between 6 to 14 seconds to load.

## Steps to Reproduce

   1. Install Brave: Version 0.68.104 Chromium: 75.0.3770.100 (Official Build) unknown (64-bit)
       or
       Install Brave: Version 0.69.77 Chromium: 76.0.3809.62 (Official Build) unknown (64-bit)
   2. Open the network tab.
   3. Browse to duckduckgo.com or try a few random other pages.

## Actual result:

![brave_screenshot](https://user-images.githubusercontent.com/50508651/61754253-51601980-ad67-11e9-8560-f029ac3833f2.png)

## Expected result:

A more reasonable time to load fonts.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave: Version 0.68.104 Chromium: 75.0.3770.100 (Official Build) unknown (64-bit)
Brave: Version 0.69.77 Chromium: 76.0.3809.62 (Official Build) unknown (64-bit)

## Version/Channel Information:

Dev and Nightly

- Can you reproduce this issue with the current release? I can't compile that one.
- Can you reproduce this issue with the beta channel? I can't compile that one.
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No, it only helps a tiny bit.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? I rather not install Chrome due to privacy reasons. But from looking online I don't see any Chrome users with the same issue.

## Miscellaneous Information:

None.

**Comment by EncryptTown** [comment] 2019-07-28 04:11
@kjozwiak is there any more information I can provide to resolve this issue?
Thank you so much.

**Comment by janwilmans** [comment] 2019-08-02 12:03
Not sure if this is related, but I also see freezes in loading pages with 
very large logs from ci-jobs in gitlab.

example: 
https://gitlab.com/gitlab-org/gitlab-services/design.gitlab.com/-/jobs/264387571

this particular page does not show the problem, but I have internal project where the logs are much larger (~5MB), where I see this:

![image](https://user-images.githubusercontent.com/5933444/62368824-0647c280-b52e-11e9-92d9-09536227672d.png)

* As you can see I, I get the 'page unresponsive'  popup.
* It is 100% reproduceable, so if you tell me how to gather more information, I will provide it.
* In Chrome the same page always loads normally

**Comment by niknah** [comment] 2019-08-02 21:05
Same with the reddit share button on some pages.  Click it a few times and all the tabs & windows on brave freezes.

**Comment by rebron** [comment] 2019-08-09 16:32
Might be adblock related. cc: @snyderp

**Comment by janwilmans** [comment] 2019-08-09 17:41
Ok I'll bite, the gitlab is self hosted and does not contain ads, however since it reproduces 100% its a.simple test. However that might make the page malfunction...

**Comment by snyderp** [comment] 2019-08-09 17:44
If `Does the issue resolve itself when disabling Brave Shields? No, it only helps a tiny bit.` is true, doesn't sound like its adblock / filter list related.

**Comment by janwilmans** [comment] 2019-08-09 18:48
I tried it, for the gitlab case, it doesn't matter if shields are disabled or not. The page still freezes. I just noticed, that other CI builds that have much less data in the log window (3300 lines in stead of 18.000) do not experience this problem.

**Comment by ReenigneCA** [comment] 2019-12-07 15:17
I'm not sure if this is related or not, I thought I saw a thread about my specific problem before but I haven't been able to find it again. When I go to a web page with particular fonts for the first time or open my Popular folder on my bookmark bar it triggers a total UI freeze for more than a few seconds on my linux desktop (I haven't seen this issue on macos are you guys using linux?). 

The desktop is a beast with an i7 and an NVMe SSD and it still freezes for around 10 seconds or so for the bookmark folder. If I open the browser and go straight to facebook it also freezes but not quite as long and if I open the bookmark folder it freezes again but not quite as long. I did a systrace on all of my brave processes and the first process named brave (ie the one with the lowest pid but not brave-browser,) shows a huge list of lines like these:

access("/usr/share/fonts/truetype/noto/NotoSansOlChiki-Regular.ttf", R_OK) = 0
madvise(0x250c6a237000, 602112, MADV_DONTNEED) = 0

followed by a huge list of lines like these:

openat(AT_FDCWD, "/usr/share/fonts/truetype/noto/NotoSansTelugu-Regular.ttf", O_RDONLY) = 228
fstat(228, {st_mode=S_IFREG|0644, st_size=169152, ...}) = 0
mmap(NULL, 169152, PROT_READ, MAP_PRIVATE, 228, 0) = 0x7f5ff6658000
close(228)  

There are more fonts being loaded and processed than there are items in my Popular folder. My guess is that facebook and my popular folder use fonts that aren't installed and they trigger a system wide search. I'm assuming that the facebook fonts are actually found but that there is a font missing for my Popular folder and so the search goes through all known font locations and processes all fonts without having any sort of persistent mapping of fonts to filenames. I'm not sure why I don't see it on my mac, perhaps mac has a system wide API that handles this sort of thing or I simply have the fonts I need in locations that are quickly found...

**Comment by ReenigneCA** [comment] 2019-12-11 17:40
Just updated to the Ubuntu 1.1.20 package and the freezing issue is gone for me.

**Comment by arch-btw** [comment] 2020-02-24 18:09
Having the same issue, most of it is resolved in brave-dev-bin 1.6.49-4 except for when I press this button:


![image20201](https://user-images.githubusercontent.com/57669023/75178827-b01ab680-56ed-11ea-8ae4-34e674bf9f60.png)


Pressing it freezes Brave for like 8 seconds.

**Comment by arch-btw** [comment] 2020-03-01 22:35
Alright fam, time for a celebration, it's all fixed in:

Version 1.6.53 Chromium: 80.0.3987.122 (Official Build) unknown (64-bit)

![fixed](https://user-images.githubusercontent.com/57669023/75635307-d34fd500-5bc9-11ea-8713-7d4ae6b028d4.gif)

**Closed** 2020-03-19 21:41 UTC
Labels: needs-investigation, perf, priority/P3
