### ISSUE TITLE
Markdown link text missing protocol

### ISSUE THREAD

**Issue by truongnmt** [brave/brave-browser#6936] opened 2019-11-15 08:46 UTC
## Description 
Markdown link text missing protocol `https://`

## Steps to Reproduce

   1. Open Brave Browser, navigate to [a sample github markdown wiki page](https://github.com/truongnmt/instagram-clone/wiki)
   2. Open Chrome, Edge, Firefox and navigate to above link
   3. See the different

## Actual result:
For link start with `https` protocol, Brave cut the https part.
![image](https://user-images.githubusercontent.com/11817656/68929351-863d2400-07cf-11ea-82b5-336e50e2c774.png)

## Expected result:
Chrome, Edge, Firefox display the full absolute link.
![image](https://user-images.githubusercontent.com/11817656/68929377-96ed9a00-07cf-11ea-9f89-ece5585ad162.png)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Version 0.70.123 Chromium: 78.0.3904.97 (Official Build) (64-bit)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment] 2020-01-10 17:38
Closing. Not able to reproduce this. Please reopen if you're still having issues with the latest version of Brave. 
<img width="560" alt="Screen Shot 2020-01-10 at 9 37 29 AM" src="https://user-images.githubusercontent.com/5951041/72173618-d75f3380-338c-11ea-8772-0b0460bc492c.png">

**Closed by rebron** 2020-01-10 17:38 UTC
