### ISSUE TITLE
Edit person setting is missing 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4615] opened 2019-05-27 14:43 UTC
## Description 

Edit person setting is missing. Found while verifying #4333

## Steps to Reproduce

   1. Install beta/dev/nightly profile 
   2. Person settings is missing 
   3. Can't edit the the profile to add some cool new profile icons 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/58426696-3cb71c00-806b-11e9-8c5b-a4ee6fdc68b6.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/58426703-4a6ca180-806b-11e9-99e8-ff932c2d64c4.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.65.107 Chromium: 75.0.3770.38 (Official Build) beta(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Linux

Brave | 0.66.76 Chromium: 75.0.3770.38 (Official Build) dev(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Linux

Brave | 0.67.62 Chromium: 75.0.3770.38 (Official Build)nightly (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  No Chrome still has the option under `Chrome name and picture` on Chrome release and Beta as well

## Miscellaneous Information:

cc: @bsclifton @petemill @rebron @brave/legacy_qa

**Comment by srirambv** [comment] 2019-06-14 21:40
+1 from @tggir1  via #4929

**Comment by kjozwiak** [comment] 2019-06-14 22:19
+1 from me as well. Bit annoying that you can't edit the default user. You would have to create a new user, change the icon, remove the initial one that was created when first launching Brave.

**Comment by jkys** [comment] 2019-06-15 00:25
+1 would require having to resync the profiles and add back in the different customizations

**Comment by ShadronSoul** [comment] 2019-06-17 11:21
+1 Really annoying when you can't edit existing users at all so creating a new user is required to make changes

**Comment by mserajnik** [comment] 2019-06-17 12:54
Another +1.

**Comment by M-Brody** [comment] 2019-06-24 19:07
+1 on both linux and mac.

**Comment by houruomu** [comment] 2019-06-26 06:50
+1 on windows

**Comment by CoVoCre** [comment] 2019-06-29 21:42
I get the issue on the current browser ! OP said "Can you reproduce this issue with the current release? No". Well, I definitely can 😉
Or maybe the download link from the brave website actually got me a dev version ? I've got :
Brave | 0.65.121 Chromium: 75.0.3770.100 (Build officiel) (64 bits)
<img width="1390" alt="Capture d’écran 2019-06-29 à 23 41 32" src="https://user-images.githubusercontent.com/25605953/60389730-772b3300-9ac7-11e9-8be4-c6cd3bf6380c.png">

**Comment by mserajnik** [comment] 2019-07-03 13:10
> I get the issue on the current browser ! OP said "Can you reproduce this issue with the current release? No".

This is probably because when OP created the issue, this feature had been working in `0.64.x` (at least in _some_ way; iirc, I was able to edit the default user and change the name/image back then), which was the current release at that time.

**Comment by Leon0402** [comment] 2019-07-07 15:06
+ 1 on linux + mac

**Comment by Brave-Matt** [comment] 2019-07-19 20:09
Several +1s from Reddit:
https://www.reddit.com/r/brave_browser/comments/cezd24/how_do_i_change_a_person/

**Comment by renaldofreire** [comment] 2019-07-20 20:26
+ 1 linux and mac

**Comment by sebas-w** [comment] 2019-07-22 21:46
# +1 

### Info
OS: `macOS Mojave version 10.14.5 (18F132)`
Brave Browser: `Version 0.66.100 Chromium: 75.0.3770.142 (Official Build) (64-bit)`

When Attempting to access the manage profile url directly I'm redirect to the settings page. The URL I've tried to access is: `brave://settings/manageProfile`

**Comment by arnydo** [comment] 2019-07-24 12:23
+1 Version 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)

**Comment by mb300sd** [comment] 2019-08-02 04:48
+1 Version 0.67.123 Chromium: 76.0.3809.87 (Official Build) (64-bit)

**Comment by Brave-Matt** [comment] 2019-08-06 17:27
+1
https://www.reddit.com/r/brave_browser/comments/cmky9k/cannot_edit_the_users_avatar_name/

**Comment by Leon0402** [comment] 2019-08-11 10:24
+2
https://community.brave.com/t/change-user-name-of-a-user-profil/69562

**Comment by bsclifton** [comment] 2019-08-12 06:23
I believe @petemill is checking this out...

**Comment by petemill** [comment] 2019-08-12 06:42
Yep just waiting for a review at https://github.com/brave/brave-core/pull/3140 :-)

**Comment by rebron** [comment] 2019-08-22 20:35
Closing as fixed in 70.x and dupe of https://github.com/brave/brave-browser/issues/5211.

**Closed by rebron** 2019-08-22 20:35 UTC
Labels: QA/Yes, bug, feature/user-interface, regression, release-notes/include
