### ISSUE TITLE
Release brave stable, beta, development and nightly to snap store

### ISSUE THREAD

**Issue by KizunaH** [brave/brave-browser#11184] opened 2020-08-12 03:13 UTC
**Anyone in there?**
Yes. eg: Opera (stable, beta, development)

https://github.com/brave/brave-browser/issues/1000

**Comment by bsclifton** [comment] 2020-08-14 07:44
We should have snaps available for Brave. Are you not seeing any available?

cc: @mihaiplesa @linhkikuchi 

Will close this as a duplicate of https://github.com/brave/brave-browser/issues/1007

**Closed** 2020-08-14 07:44 UTC
Labels: OS/Desktop, OS/Linux/snap, duplicate

**Comment by KizunaH** [comment] 2020-10-05 04:55
> We should have snaps available for Brave. Are you not seeing any available?

In snap store?

**Comment by bsclifton** [comment] 2020-10-05 07:06
@KizunaH yup; I did a fresh install of Ubuntu 20 and all the versions show there for me?
![image](https://user-images.githubusercontent.com/4733304/95049424-950a1f00-069e-11eb-9124-4b40733c53c1.png)

**Comment by mihaiplesa** [comment] 2020-10-05 09:41
Alos https://snapcraft.io/install/brave/ubuntu

**Comment by KizunaH** [comment] 2020-10-08 07:11
> @KizunaH yup; I did a fresh install of both Ubuntu 18 and 20 and all the versions show there for me?

Something wrong in our end then it needs to discuss with snap-store developers. When search 'brave', only keepass and sc-controllers details appear for result or brave doesn't display in 'Productivity' section while chromium, opera and firefox available.

(snap-store 3.36.1 in ubuntu 20.04.01)

**Comment by mihaiplesa** [comment] 2020-10-20 16:42
Our snap was set to `unlisted`, have switched now to `public`.

**Comment by Aikatsui** [comment] 2021-01-06 14:59
bit late to add a comment.
@mihaiplesa now `brave-stable` appear for search result but seems still  has issue with `beta` and `nightly` snaps

![ksnip_20210106-215712](https://user-images.githubusercontent.com/63988538/103782724-64090400-506a-11eb-8046-1eef210fac5c.png)

**Comment by mihaiplesa** [comment] 2021-01-06 17:05
@Aikatsui out snap name is simply `brave` and all the channels ('candidate', `edge`, `beta`, `stable`) currently serve the same version

**Comment by Aikatsui** [comment] 2021-01-07 11:07
Ah! now noticed it, ago misunderstood due https://github.com/brave/brave-browser/issues/11184#issuecomment-703443195
thank you

**Comment by cybernats** [comment] 2021-01-21 01:38
> out snap name is simply `brave` and all the channels ('candidate', `edge`, `beta`, `stable`) currently serve the same version

@mihaiplesa this way worst ever, we cannot have stable, beta, nightly versions installed separately on our devices or even you offer same version. if tap to install beta version then it switch the existing installed stable to beta. Can you guys publish three separate snaps? as above @bsclifton screenshot? 

![image](https://user-images.githubusercontent.com/77595033/105267332-045f3c80-5bc4-11eb-9990-3552aa569f1d.png)

**Comment by cybernats** [comment] 2021-02-07 10:26
@mihaiplesa if that difficult, i prefer this way https://github.com/brave/brave-browser/issues/13745

**Comment by dtantono** [comment] 2021-02-07 11:52
I found brave stable for snap is going live and it is good. So, I hope brave in beta or other channels for snap is a good addition as well.
