### ISSUE TITLE
Import of Chrome extensions switches them on automatically even when they should be off

### ISSUE THREAD

**Issue by radeksvarz** [brave/brave-browser#15359] opened 2021-04-18 17:36 UTC
## Description 

Import of Chrome extensions switches them on automatically even when they are switched off within Chrome before the import.

## Steps to Reproduce

   1. Have Chrome with bookmarks, some active extensions and some (many) extensions switched off
   2. Install Brave, use welcome screen to import bookmarks (and extensions)

## Actual result:
All extensions from Chrome are imported, but also switched on opening the initial settings screen for each extension, which require that.

## Expected result:
All extensions are imported, but only those switched on in Chrome would become switched on in Brave.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

1.23.71 Chromium: 90.0.4430.72 (Official Build) (64-bit)
--
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | Windows 10 OS Version 2009 (Build 19042.928)

**Comment by bsclifton** [comment] 2022-09-12 05:01
Closing as duplicate of https://github.com/brave/brave-browser/issues/24250 which was resolved recently 😄

**Closed by bsclifton** 2022-09-12 05:02 UTC
Labels: feature/importer, feature/extensions, priority/P5, OS/Desktop
