### ISSUE TITLE
[Desktop] Disable trackers and adblocking settings doesn't persist on linux

### ISSUE THREAD

**Issue by KizunaH** [brave/brave-browser#11422] opened 2020-08-25 18:51 UTC
## Steps to Reproduce

   1. Shields > Trackers and adblocking
   2. Change from standard to disabled
   3. Refresh browser tab
   4. It back to standard

## Brave version (brave://version info)
1.12.114

**Comment by github-account1111** [comment] 2020-08-26 03:41
Same problem on Windows. Shield settings don't persist in general.

**Comment by Yuki2718** [comment] 2020-09-15 08:36
Same on Windows, setting to "Disabled" will never be remembered but "Aggressive" will be.
@github-account1111 That issue was about various shield settings but on my end the current issue is only about trackers and adblocking, other configs such as cookie or fingerprint work fine. Don't you?

**Comment by rebron** [comment] 2020-09-25 16:54
@KizunaH I think this is a duplicate of #11585

**Comment by Yuki2718** [comment] 2020-09-29 09:17
Now it looks more of an UI-mismatch issue. The global setting shows it's set to Standard but actually on any of individual page ads and tracker settings are set to "Allow all trackers and ads".

**Comment by rebron** [comment] 2020-10-09 16:21
Closing as fixed with #11585 
@Yuki2718 If you're seeing a mismatch, please file a separate issue. Global settings when set are for sites going forward you haven't visited yet. It doesn't globally make a change for all sites that you've already made in the past.

**Closed by rebron** 2020-10-09 16:21 UTC
Labels: OS/Desktop

**Comment by Yuki2718** [comment] 2020-10-10 03:23
@rebron I now don't see the mismatch, running on 1.15.72.
