### ISSUE TITLE
Close Other Tabs - Crashes Brave

### ISSUE THREAD

**Issue by MikeMeeseeks** [brave/brave-browser#34905] opened 2023-12-14 23:42 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.104 Chromium: 120.0.6099.115
Operating System: Mac OS X 14.2.0

URL (if applicable) where crash occurred: All

Can you reproduce this crash? Yes with 100% consistency 

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open Multiple Tabs
2. Click 'Close Other Tabs'
3. Wait about 1 second, Brave crashes 

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/96170300-100a-300b-0000-000000000000

**Comment by valynor** [comment] 2023-12-15 02:53
@simonhong this might be related to the other recent crash-on-tab-close that was fixed in .104?

**Comment by rebron** [comment] 2023-12-15 23:46
Closing as duplicate of https://github.com/brave/brave-browser/issues/34909

**Closed by rebron** 2023-12-15 23:46 UTC
