### ISSUE TITLE
Blocked count is not properly aligned on tablet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#15777] opened 2021-05-12 13:27 UTC
## Description 
Blocked count is not properly aligned on tablet

## Steps to reproduce 

   1. Install 1.25.57 x64 build
   2. Visit a page that has a lot of trackers
   3. Open shields, block count is on extreme left which makes it look really bad

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/117981599-16a8e600-b32d-11eb-858c-384326d7dd05.png)

## Expected result
Have a smaller shields design so even if something is bad doesn't look obvious 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10
   
## Brave version
1.25.57

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

#10690 was closed as duplicate but still needs to be fixed. Shields looks awfully bad on tablets 
cc: @deeppandya @alexsafe @anthonypkeane @karenkliu

**Comment by srirambv** [comment] 2021-06-01 11:46
Issue seems to be fixed on the current beta build 1.26.46. Block count seems better placed than before. Although real fix is when the shields size is decreased (#10690 closed as dupe) 

![image](https://user-images.githubusercontent.com/17010094/120318117-5ed97980-c2d7-11eb-8686-7387474fd25f.png)

**Comment by anthonypkeane** [comment] 2021-06-02 20:39
cc'ing @karenkliu on this one design eyes.
@alexsafe for implementing when you get time. Thanks

**Comment by karenkliu** [comment] 2021-06-03 17:07
This seems like a dupe of https://github.com/brave/brave-browser/issues/15635 ?

**Closed** 2021-06-15 17:32 UTC
Labels: OS/Android, QA/Yes, android-tablet-specific, bug, design, priority/P3, release-notes/exclude

**Comment by srirambv** [comment] 2021-08-02 15:12
Verification passed on Samsung Tab A with Android 10 running 1.28.99 x64 Beta Build
- Verified blocked count is properly aligned on shields

<img width=500 src=https://user-images.githubusercontent.com/17010094/127883769-82415579-e21f-485b-b14b-99ee09432837.png>

**Comment by karenkliu** [comment] 2021-08-02 18:26
This is still missing the background treatment:

![image](https://user-images.githubusercontent.com/2388823/127906922-3a614723-8443-4a64-a535-50bf0c9faf3b.png)

**Comment by srirambv** [comment] 2021-08-03 02:33
Will add an new follow up issue for that
