### ISSUE TITLE
Translate to English doesn't translate webpage

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#237] opened 2018-05-28 15:11 UTC
## Description 

Translate to English doesn't translate webpage
## Steps to Reproduce

   1. Open any non-English page
   2. Right click and select Translate to English
   3.  Popup shows translating but fails

 ## Actual result:

![translate](https://user-images.githubusercontent.com/17010094/40620673-a8eb0efe-6267-11e8-8533-b034ba01e5fe.gif)

## Expected result:
Should either translate the page to English or not show the option in context menu
## Reproduces how often: 

Easy

## Brave version (about:brave info)

2e9c470

**Comment by jonathansampson** [comment] 2018-09-14 13:18
I believe this is a duplicate of #208.

**Comment by bsclifton** [comment] 2018-09-14 16:16
Closing as dupe of https://github.com/brave/brave-browser/issues/208

**Closed by bsclifton** 2018-09-14 16:16 UTC
Labels: feature/context-menu, feature/translate, l10n
