### ISSUE TITLE
[VPN] Implement kill switch

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#23211] opened 2022-06-02 15:53 UTC
**Summary**
Implement a kill switch that automatically disconnects the device from the internet if the VPN connection drops out. So that there’s no chance that the users IP address and other sensitive information could be exposed when the VPN stops working.

**Comment by bsclifton** [comment] 2023-02-06 19:01
Closing as duplicate of https://github.com/brave/brave-browser/issues/23193

**Closed by bsclifton** 2023-02-06 19:01 UTC
Labels: OS/Android, feature/vpn
