### ISSUE TITLE
Leo - New design for follow ups + Conversation starters

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#39797] opened 2024-07-16 20:43 UTC
### Description

As part of the conversation starters, we're changing the design of the suggested questions to a new format. 

Each item should be represented by an emoji. We'd show 3 items as follow ups.

Design file here:
https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/%F0%9F%94%84-Leo-%5BIN-PROGRESS%5D?node-id=4226-13767&t=WL7FRILdWtE2Rkk7-1

Library file for component details:
https://www.figma.com/design/MNwi0uwXNhkAbPiJ86G4vm/%E2%9C%A8-Leo?node-id=1592-7938&t=NoHVFsVy4yIGe5EM-1

**Comment by LorenzoMinto** [comment] 2024-08-29 09:26
Spec: https://docs.google.com/document/d/1vpyqa38tQh74mTmyr0ggcaFx1znNkjubvhB7rk3L-Wk/edit

**Comment by LorenzoMinto** [comment] 2024-09-04 14:45
Duplicate of https://github.com/brave/brave-browser/issues/40854

**Closed by LorenzoMinto** 2024-09-04 14:45 UTC
Labels: design, OS/Android, OS/Desktop, browser-ai
