### ISSUE TITLE
Crash in Geolocation::OnPositionUpdated

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#41871] opened 2024-10-24 21:36 UTC
https://share.backtrace.io/api/share/6x2MfK4RyNCeRuMcAmfJ0P2
```
[ 00 ] blink::(anonymous namespace)::CreatePositionError(device::mojom::blink::GeopositionError const&) ( immediate_crash.h:176 )
[ 01 ] blink::Geolocation::OnPositionUpdated(mojo::StructPtr<device::mojom::blink::GeopositionResult>) ( geolocation.cc:527 )
[ 02 ] void base::internal::DecayedFunctorTraits<void (blink::Geolocation::*)(mojo::StructPtr<device::mojom::blink::GeopositionResult>), cppgc::internal::BasicPersistent<blink::Geolocation, cppgc::internal::StrongPersistentPolicy, cppgc::internal::IgnoreLocationPolicy, cppgc::internal::DisabledCheckingPolicy>&&>::Invoke<void (blink::Geolocation::*)(mojo::StructPtr<device::mojom::blink::GeopositionResult>), cppgc::internal::BasicPersistent<blink::Geolocation, cppgc::internal::StrongPersistentPolicy, cppgc::internal::IgnoreLocationPolicy, cppgc::internal::DisabledCheckingPolicy>, mojo::StructPtr<device::mojom::blink::GeopositionResult>>(void (blink::Geolocation::*)(mojo::StructPtr<device::mojom::blink::GeopositionResult>), cppgc::internal::BasicPersistent<blink::Geolocation, cppgc::internal::StrongPersistentPolicy, cppgc::internal::IgnoreLocationPolicy, cppgc::internal::DisabledCheckingPolicy>&&, mojo::StructPtr<device::mojom::blink::GeopositionResult>&&) ( bind_internal.h:738 )
[ 03 ] base::OnceCallback<void (mojo::StructPtr<device::mojom::blink::GeopositionResult>)>::Run(mojo::StructPtr<device::mojom::blink::GeopositionResult>) && ( callback.h:156 )
[ 04 ] device::mojom::blink::Geolocation_QueryNextPosition_ForwardToCallback::Accept(mojo::Message*) ( geolocation.mojom-blink.cc:295 )
[ 05 ] mojo::InterfaceEndpointClient::HandleValidatedMessage(mojo::Message*) ( interface_endpoint_client.cc:1046 )

```

**Comment by rebron** [comment] 2024-10-29 16:10
Closing as dupe of https://github.com/brave/brave-browser/issues/41859

**Closed by rebron** 2024-10-29 16:10 UTC
Labels: closed/duplicate, crash, OS/macOS, OS/Desktop
