### ISSUE TITLE
In brave://flags the default values don't show what the default is.

### ISSUE THREAD

**Issue by arch-btw** [brave/brave-browser#15880] opened 2021-05-15 23:57 UTC
## Description 

In brave://flags the default values don't show what the default is.

For example take the Vulkan flag at brave://flags/#enable-vulkan

It says "Default".

But what does Default mean? Does that mean Vulkan is enabled or disabled? It doesn't specify.

## Steps to Reproduce

   1.  Go to brave://flags.
   2. Notice the Default values.
   3. They don't specify what Default means.

## Actual result:

The label is: Default.

## Expected result:

The label would be better if it's: Default (Enabled) or Default (Disabled)

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Every version.

## Version/Channel Information:

All channels.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards?  No
- Is the issue reproducible on the latest version of Chrome? Don't know.

**Comment by rebron** [comment] 2021-09-09 22:55
Closing as dupe of https://github.com/brave/brave-browser/issues/16644

**Closed by rebron** 2021-09-09 22:55 UTC
Labels: OS/Desktop
