### ISSUE TITLE
Tab GUI glitch

### ISSUE THREAD

**Issue by StephD** [brave/brave-browser#7006] opened 2019-11-19 10:04 UTC
## Description 
There is a persistant icon in the tab that overlay over other tabs. It come from a previous tab that has been closed and the "tab icon" persist in the tab bar. It appear it the previous update and the problem is still active in this v1.0

## Steps to Reproduce
Step to reproduce :

Open the site
Open new tab
Go on the website and load a page
Close the page while loading
Re-open the tab (ctrl-maj-t)
Close it again
---++ Basically, playing with the website page to close to try to glich, and add new tab to change the position of the glitch in the tab

## Reproduces how often: 
It's may happen everyday since a small month. Restart the browser erase the glitch

## Brave version (brave://version info)
Brave | 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1909 (Build 18363.476)
JavaScript | V8 7.8.279.23

## Version/Channel Information:
I don't know

## Other Additional Information:
- Seem to glitch when you close the tab while the page is loading only.
- Could glitch multiple time as you see on the picture. I can re-open the tab (ctrl-maj-t), close it and glitch again
- I practice the bug on "https://manjaro.org/download/". The home page doesn't seem to glitch. May be something special loading on this one
- All glitch persist even if I reopen the page

## Miscellaneous Information:
DUPLICATE OF [#6978](https://github.com/brave/brave-browser/issues/6978)
Try to explain a fact. This glitch seam to be "attached" and follow another tab. 
If I open 10 new tab, this glitch seam to be attached to on tab and will stay on it. 
If I close all the new tab, the glitch will persist in the position, not follow the tab anymore
If I open a new tab, the glitch will go back to the previous tab
I already got the glitch with facebook icon, here is manjaro.org icon

![2019-11-19 18_00_49-About Version - Brave](https://user-images.githubusercontent.com/1171858/69137108-0d9fd580-0af7-11ea-91d5-c5dcf6c2ed6b.png)
![2019-11-19 18_01_14-New Tab - Brave](https://user-images.githubusercontent.com/1171858/69137109-0d9fd580-0af7-11ea-96f0-bca802d65671.png)
![2019-11-19 18_03_36-New Issue · brave_brave-browser - Brave](https://user-images.githubusercontent.com/1171858/69137110-0e386c00-0af7-11ea-9260-0f86b0a2644d.png)
![2019-11-19 18_03_41-New Tab - Brave](https://user-images.githubusercontent.com/1171858/69137111-0e386c00-0af7-11ea-8a88-e99d7ae7b8ef.png)
![2019-11-19 18_03_48-New Tab - Brave](https://user-images.githubusercontent.com/1171858/69137112-0e386c00-0af7-11ea-9433-22675d00113d.png)
![2019-11-19 18_03_54-New Tab - Brave](https://user-images.githubusercontent.com/1171858/69137113-0ed10280-0af7-11ea-8249-593476245562.png)
![2019-11-19 18_04_06-New Tab - Brave](https://user-images.githubusercontent.com/1171858/69137115-0f699900-0af7-11ea-9762-91479598a410.png)
![2019-11-19 18_04_13-New Tab - Brave](https://user-images.githubusercontent.com/1171858/69137116-10022f80-0af7-11ea-85f7-d7d2de16b24c.png)
![2019-11-19 17_55_05-New Tab - Brave](https://user-images.githubusercontent.com/1171858/69137117-109ac600-0af7-11ea-9f5c-47c73f1c575d.png)

edit 19/11 : I just opened the manjaro tab, and close it and the glitch disappear ..

edit 21/11 : try to modify the "brave://flags/#enable-oop-rasterization"
![2019-11-21 12_17_12-Experiments - Brave](https://user-images.githubusercontent.com/1171858/69303774-317b2c80-0c59-11ea-9e98-a610469fb9b1.png)
![2019-11-21 12_17_07-Experiments - Brave](https://user-images.githubusercontent.com/1171858/69303773-30e29600-0c59-11ea-8026-c55d94839fef.png)
Enable :
![2019-11-21 12_19_30-Experiments - Brave](https://user-images.githubusercontent.com/1171858/69303772-30e29600-0c59-11ea-80be-29210d8bd8c9.png)
![2019-11-21 12_19_26-Experiments - Brave](https://user-images.githubusercontent.com/1171858/69303776-3213c300-0c59-11ea-8021-b6d1e78b7d82.png)

**Comment by bsclifton** [comment] 2019-11-19 16:17
Thanks for reporting, @StephD! Can you please try opening this URL up and changing the value of the flag to `Disabled`?
brave://flags/#enable-oop-rasterization

I'm curious if you're able to reproduce this after changing. Although, it sounds like the problem may have went away

**Comment by StephD** [comment] 2019-11-21 04:22
Hey, this option doesn't change anything. I could reproduce the error with this option enable and disabled.
Updated info : 
- seem to glitch when you close the tab while the page is loading only. 
- Could glitch multiple time as you see on the picture. I can re-open the tab (alt-maj-t), close it and glitch again
- I practice the bug on "https://manjaro.org/download/". The home page doesn't seem to glitch. May be something special loading on this one
- All glitch persist even if I reopen the page

![2019-11-21 12_19_30-Experiments - Brave](https://user-images.githubusercontent.com/1171858/69303772-30e29600-0c59-11ea-80be-29210d8bd8c9.png)
![2019-11-21 12_17_07-Experiments - Brave](https://user-images.githubusercontent.com/1171858/69303773-30e29600-0c59-11ea-8026-c55d94839fef.png)
Enable :
![2019-11-21 12_17_12-Experiments - Brave](https://user-images.githubusercontent.com/1171858/69303774-317b2c80-0c59-11ea-9e98-a610469fb9b1.png)
![2019-11-21 12_19_26-Experiments - Brave](https://user-images.githubusercontent.com/1171858/69303776-3213c300-0c59-11ea-8021-b6d1e78b7d82.png)

**Comment by onmyouji** [comment] 2019-11-23 03:43
I can confirm that this problem also happens on my system. I'm not sure how to reproduce it, but it happens from time to time.

Brave: 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
Revision: 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS: Windows 10 OS Version 1809 (Build 17763.832)
JavaScript: V8 7.8.279.23

**Comment by onmyouji** [comment] 2019-11-23 04:01
Probably duplicate of #6978

**Comment by StephD** [comment] 2019-11-23 04:12
definitly duplicate. I didn't found this one because I didn"t link the glitch with the "loading state"

**Closed** 2019-12-31 06:05 UTC
Labels: need-more-info
