### ISSUE TITLE
Allowing Dapp sites to install opens a blank brave://wallet page 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6279] opened 2019-10-02 13:54 UTC
## Description 

Allowing Dapp sites to install opens a blank brave://wallet page 

## Steps to Reproduce

   1. Launch a new profile on `0.69.131`
   2. Visit https://cryptokitties.co/
   3. Click `Allow` from extension install modal
   4. New tab opens brave://wallet which loads and stops no UI shown
   5. Reload page, UI shows up

## Actual result:

[wallet_no_ui.zip](https://github.com/brave/brave-browser/files/3681418/wallet_no_ui.zip)

## Expected result:
Should load the UI when the tab is opened

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
--| --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

## Miscellaneous Information:

cc: @bbondy @ryanml

**Comment by ryanml** [comment] 2020-01-31 00:17
@srirambv I am closing this one as I cannot reproduce on release or current `e-r-c` builds. I have added it to the next milestone and it can be confirmed as part of next week's QA

**Closed by ryanml** 2020-01-31 00:17 UTC
Labels: QA/Yes, bug, feature/crypto-wallets, intermittent-issue, priority/P3, release-notes/exclude

**Comment by srirambv** [comment] 2020-02-11 04:20
Still reproduces on current release component with steps from #8121. Going to move it out of milestone as #8121 is going to supersede this issue
