### ISSUE TITLE
Expired grants appear in rewards pane, claim button does nothing

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#4708] opened 2019-06-04 18:29 UTC
If there is an expired grant, it still appears in the rewards pane, and clicking the "Claim" button does nothing. 

**Expected behavior**
For my two cents, probably best if expired grants don't appear at all in the pane.  But if / when they need to appear, clicking "Claim" should dismiss the grant offer

**Screenshot**
![screen_shot_2019-06-02_at_1 25 57_pm](https://user-images.githubusercontent.com/76526/58904324-22f58480-86bc-11e9-9e9f-3b9f259fe236.png)
(clicking claim in the above image does nothing, screenshot was taken on 6/2/2019)

**Comment by GeetaSarvadnya** [comment] 2019-08-05 04:48
The issue is Reproducible in Brave Beta 0.68.116. Even after claiming grants, the claim notification is shown on the BAT logo. Click on the claim button doesn't do anything

![4708](https://user-images.githubusercontent.com/38657976/62439652-46938480-b76a-11e9-9019-ecfecf7c03b9.gif)

**Comment by NejcZdovc** [comment] 2020-04-10 12:38
@brave/legacy_qa is this still a problem?

**Comment by LaurenWags** [comment] 2020-04-10 12:41
@GeetaSarvadnya can you reproduce this one still? I wasn't able to get expired grants to show in my panel, but if you had success before maybe you will again 😄

**Comment by NejcZdovc** [comment] 2020-08-27 09:46
closing as it was fixed in https://github.com/brave/brave-browser/issues/11170

**Closed by NejcZdovc** 2020-08-27 09:46 UTC
Labels: bug, feature/rewards, needs-more-info
