### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by FixmyBrave** [brave/brave-browser#11812] opened 2020-09-22 20:15 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.14.81  Chromium: 85.0.4183.102
Operating System: Mac OS X 10.15.6

URL (if applicable) where crash occurred:

Can you reproduce this crash? Not intentionally

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. One thing I've noticed is that I think it crashes more, or perhaps only, when I use a custom accessibility keyboard in the Mac. I use that because I've created some macros and this is the easiest way to use them.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/e6967000-106a-1805-0000-000000000000

**Comment by bsclifton** [comment] 2020-09-24 23:14
Closing as a duplicate of https://github.com/brave/brave-browser/issues/7546 - thanks for the report 😄

**Closed by bsclifton** 2020-09-24 23:14 UTC
Labels: OS/macOS, crash
