### ISSUE TITLE
[Android] Ad grants claim toast notification needs design work in Android

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#25580] opened 2022-09-23 12:56 UTC
## Description 
Found while testing https://github.com/brave/brave-browser/issues/24294
Ad grants claim toast notification needs design work in Android

## Steps to reproduce 

   1. Clean profile 1.44.95 staging env
   2. Enable rewards
   3. Send ad grants to the profile (ask me or @LaurenWags or @Miyayes )
   4. Click on BR panel and see Ad grants notification
   5. Ad grants claim toast notification needs design work in Android
   

## Actual result 

![image](https://user-images.githubusercontent.com/38657976/191963468-7fc70a76-da3a-42c6-84f8-14ad5f4a30d0.png)

## Expected result
Ad grants claim toast notification should be same as Desktop
![image](https://user-images.githubusercontent.com/38657976/191963652-dc2f10d4-550b-4ea5-8d0d-10e7d029ca43.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Vivo x70 pro with android version 12
   - Android version: 12
   
## Brave version
Bravemonoarmx64.apk_1.44.95

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

CC: @brave/qa-team @Miyayes @deeppandya

**Comment by Miyayes** [comment] 2022-09-24 08:22
Closing as dupe of https://github.com/brave/brave-browser/issues/20626. Thanks for filing though, Geeta!

**Closed by Miyayes** 2022-09-24 08:22 UTC
Labels: bug, feature/rewards, QA/Yes, QA/Test-Plan-Specified, OS/Android
