### ISSUE TITLE
NTP claim rewards notification doesn't go away after clicking on it and completing CAPTCHA

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#8623] opened 2020-03-11 01:24 UTC
## Description 

NTP claim rewards notification doesn't go away after clicking on it and completing CAPTCHA.

## Steps to Reproduce

   1. On the 6th of the month, visit the New Tab Page and see the claim rewards notification
   2. Click on "Claim" and complete the CAPTCHA
   3. Open a new tab and see the Claim Rewards notification still there, even though reward has been claimed.
4. Open another new tab and see that the Claim Rewards notification is gone.

## Actual result:

The Claim Rewards notification still shows on the first new tab after completing CAPTCHA, and only goes away upon opening a second new tab.
![image](https://user-images.githubusercontent.com/2388823/76372937-43fa9e00-62fc-11ea-987c-827a8c5ec5e6.png)

## Expected result:
The Claim Rewards notification should not show.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Nightly?

## Version/Channel Information:
All channels

**Comment by rebron** [comment] 2020-03-11 01:43
dupe of https://github.com/brave/brave-browser/issues/7690? which is a follow-up of https://github.com/brave/brave-browser/issues/6755

**Comment by karenkliu** [comment] 2020-03-11 01:47
@rebron This is for the NTP notification, not the Brave Rewards panel. Might have the same cause though.

**Comment by NejcZdovc** [comment] 2020-03-11 06:00
yup this is dupe of #7690

**Closed by NejcZdovc** 2020-03-11 06:00 UTC
Labels: bug, feature/rewards
