### ISSUE TITLE
Default theme should be dark or light depending on Windows 10 preference

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3804] opened 2019-03-20 09:39 UTC
Follow up to https://github.com/brave/brave-browser/issues/1189

This feature has been implemented on MacOS, but Windows version had some problems and is hidden behind a flag.  https://github.com/brave/brave-core/pull/1805#pullrequestreview-214222419

## Steps to Reproduce

1. Clean install
2. Launch Browser
3. Check theme settings have three options (Same as Windows, Dark, Light)
4. Check Same as Windows applies Windows theme to brave theme
5. Check Dark/Light works independently with Windows theme.

## Actual result:

There is no `Same as Windows` in `Brave colors` 
![image](https://user-images.githubusercontent.com/34715963/54673926-a19a4700-4afb-11e9-868e-bb91f98a0f03.png)

## Expected result:
`Same as Windows` is available in `Brave colors` 
`Same as Windows` is the default option on Windows 10

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.62.32 Chromium: 73.0.3683.75 (Official Build) beta (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

cc @brave/legacy_qa @petemill @simonhong

**Comment by simonhong** [comment] 2019-03-20 20:34
This is expected behavior for now because upstream disabled dark theme support on Win10.
When they enable it, we can consider this option again.

**Comment by srirambv** [comment] 2019-03-20 20:46
@btlechowski have you checked with setting apps colour? 
![image](https://user-images.githubusercontent.com/17010094/54717815-716c9b80-4b2f-11e9-8448-63e1aba7b176.png)
![image](https://user-images.githubusercontent.com/17010094/54717886-96f9a500-4b2f-11e9-93d9-1114e6df22d8.png)

By default the app is set to light always.

**Comment by simonhong** [comment] 2019-03-20 22:30
@srirambv @btlechowski We don't need to test theme on Windows for now.
Chromium didn't enable platform theme support yet.

**Comment by simonhong** [comment] 2019-04-14 21:18
@btlechowski We can test `Same as Windows` feature since 0.63 (currently beta)

**Comment by kjozwiak** [comment] 2019-05-02 16:02
@simonhong was this upstreamed in one of the C74 bumps?

**Comment by simonhong** [comment] 2019-05-02 22:29
@kjozwiak beta(C74) has `Same as Windows` option and it's default.
However, needs more fixes to make theme works properly on Windows like MacOS.
Fix for https://github.com/brave/brave-browser/issues/4059 is merged and waiting for uplifting.
Fix for https://github.com/brave/brave-browser/issues/4056 is waiting for review.
When all above fixes are uplifted to C74, brave theme will work properly in Windows.

**Closed** 2019-05-13 00:42 UTC
Labels: OS/Windows, QA/Test-Plan-Specified, QA/Yes, feature/user-interface, priority/P5

**Comment by btlechowski** [comment] 2019-06-12 01:53
Verification passed on

Brave | 0.66.87 Chromium: 75.0.3770.80 (Official Build) beta (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

Verified test plan from https://github.com/brave/brave-core/pull/2352 and from the description. Checked changing Same as Windows(Dark)->Same as Windows(Light) and Same as Windows(Light)->Same as Windows(Dark). Checked settings dropdown, permissions alert box (notifications, geolocation, translations, alerts) and downloads bar.
