### ISSUE TITLE
Apply our corner radius on all dialogs

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#17758] opened 2021-08-30 00:43 UTC

**Comment by rebron** [comment] 2021-09-07 17:57
Follow up to: #17722

**Comment by Michael82548** [comment] 2021-11-08 02:17
Would be nice if this could be changed with a flag.

**Comment by nullhook** [comment] 2021-11-09 19:21
```c++
WebUIBubbleManagerT<VPNPanelUI>
```

`WebUIBubbleManagerT`
creates a WebUIBubbleDialogView (views::BubbleDialogDelegateView) which basically is a view and sets a border `border->SetCornerRadius(GetCornerRadius());`

`GetCornerRadius` is a function that detects OS and applies platform specific corner radius

**Comment by rebron** [comment] 2023-09-15 22:13
Closing as dupe of https://github.com/brave/brave-browser/issues/32150 and fixed with https://github.com/brave/brave-core/pull/19795 in 1.59.x

**Closed by rebron** 2023-09-15 22:13 UTC
Labels: feature/user-interface, design, priority/P3, OS/Desktop
