### ISSUE TITLE
Option for turning off search suggestions isn't working as intended

### ISSUE THREAD

**Issue by Debagnik** [brave/brave-browser#29460] opened 2023-04-02 07:27 UTC
## Description 

As per the image attached below, the old searches are turned on but I cannot find the option for disabling that.

I have turned off Settings > appearance > “Show autocomplete suggestions in address bar” options and Settings > privacy and security > “Auto-complete searches and URLs” but these did not help. Images attached below. Any Ideas

I have already asked in the Brave community page about this which could be found [here](https://community.brave.com/t/how-do-i-turn-off-the-search-suggestion-in-the-address-bar/472247) but the solution doesn't seem to work.

## Steps to Reproduce

   1. launch brave.
   2. open a new tab.
   3. click on the address bar
   4. observe that the old searches appear as suggestions

## Actual result:

[](https://global.discourse-cdn.com/brave/optimized/3X/a/0/a041601a7f4a6d28bda5801103278118b9822520_2_1035x582.jpeg)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment] 2023-04-06 02:03
Closing as dupe of https://github.com/brave/brave-browser/issues/29461

**Closed by rebron** 2023-04-06 02:03 UTC
Labels: OS/Desktop
