### ISSUE TITLE
Brave crashes with sigill on Linux

### ISSUE THREAD

**Issue by Finoderi** [brave/brave-browser#29893] opened 2023-04-20 15:15 UTC
## Description 
Brave binary packages crush on Arch Linux and Gentoo Linux.

## Steps to Reproduce
Try to launch Brave by any means.

## Actual result:
It crushes with 'Illegal instruction' error.

## Expected result:
The browser launches.

## Reproduces how often: 
As often as you please.

## Brave version (brave://version info)
On Arch - brave-bin 1:1.50.121-1, on Gentoo - 1.50.121 from here - https://gitlab.com/jason.oliveira/brave-overlay 

## Version/Channel Information:
- Can you reproduce this issue with the current release? 
Yup.

- Can you reproduce this issue with the beta channel? 
On Arch I tried beta version with the same result.

- Can you reproduce this issue with the nightly channel? 
On Arch I tried nightly version with the same result. 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
I would like to try it when Brave finally was able to launch.

- Does the issue resolve itself when disabling Brave Rewards?
Same as above.

- Is the issue reproducible on the latest version of Chrome? 
I have no idea but highly doubt it.

**Comment by rillian** [comment] 2023-04-20 15:16
I'm also seeing this with the brave-browser-1.50.121-1.x86_64 rpm package on Fedora 37.

**Comment by rillian** [comment] 2023-04-20 15:32
Downgrading to the previous release is a work-around. E.g. on Fedora
```sh
sudo dnf install brave-browser-1.50.119-1
```

**Comment by EinfxchFinn** [comment] 2023-04-20 15:49
Probably a  duplicate of #19801

**Comment by Finoderi** [comment] 2023-04-20 16:02
For me everything worked as expected for years until the last update to 1.50.121 version.

**Comment by rillian** [comment] 2023-04-20 17:33
We think we've found a fix. Hope to have a new release out in a day or so.

**Comment by rillian** [comment] 2023-04-20 21:50
Fixed for me on Fedora in brave-browser `1.50.125`.

If you want to help verify, pre-release packages are available from https://github.com/brave/brave-browser/releases/tag/v1.50.125

**Comment by kjozwiak** [comment] 2023-04-20 22:12
We pushed out `1.50.125 Chromium: 112.0.5615.165` which should fix the issue for everyone. If you were having issues, please let us know if the above release fixed your issue. You can also download the `deb` files manually via https://github.com/brave/brave-browser/releases/tag/v1.50.125. Just for some context, the above was fixed by upgrading chromium from `112.0.5615.138` to `112.0.5615.165`.

**Closed by kjozwiak** 2023-04-20 22:12 UTC
Labels: OS/Desktop
