### ISSUE TITLE
Clearing "History" doesn't remove "Top Sites" in the homepage.

### ISSUE THREAD

**Issue by sayedarifuddin** [brave/brave-browser#9929] opened 2020-05-25 06:59 UTC
![image](https://user-images.githubusercontent.com/47639147/82786959-53af6a80-9e87-11ea-8ed1-8a8294abeba6.png)
Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/47639147/82787018-72156600-9e87-11ea-8758-ad12ea716eb9.png)

**Comment by markwylde** [comment] 2020-06-20 04:31
Can confirm this is still not fixed in:
```Version 1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit)```

Can we at least warm users about this until a fix it put in, or ideally remove top sites until it can be implemented with the users privacy settings in mind?

**Comment by markwylde** [comment] 2020-06-27 08:55
@BrendanEich can you have a look at this.

People are currently under the assumption that when they clear their history, the history of their browsing will be cleared.

I have my Brave clear on exit, however the Top Sites remains. What's even more scary, is even if you have "Top Sites" disabled, it still actually remembers them.

I know this might take some time to fix, but in the meantime can we warn users about the bug. Even to put a message on the "Clear browsing data" modal?

Something like this, just until we can fix this?

<img width="1114" alt="Screen Shot 2020-06-27 at 6 54 29 pm" src="https://user-images.githubusercontent.com/5929807/85918604-aa093200-b8a7-11ea-93f3-ff9d510fcdba.png">

**Comment by markwylde** [comment] 2020-06-27 08:59
Where is this "Top Sites" data saved?

**Comment by markwylde** [comment] 2020-06-27 09:03
This might actually be fixed in the latest update. I've not managed to recreate this issue today.

**Comment by markwylde** [comment] 2020-06-27 11:01
Nope, just happened again:
<img width="1399" alt="Screen Shot 2020-06-27 at 8 59 53 pm" src="https://user-images.githubusercontent.com/5929807/85920699-47b92d00-b8b9-11ea-9a81-9f5d0cb6e737.png">

I can't find where that URL is stored however.

**Comment by bsclifton** [comment] 2020-06-28 20:19
cc: @rebron - we probably should make it visible on the `Clear on exit` modal which group clears top sites (or we could give it its own entry)

**Comment by markwylde** [comment] 2020-07-04 21:29
@BrendanEich can we please, as a stop gap, warn people that wiping their history is not wiping everything?

**Comment by abuassar** [comment] 2020-07-06 10:37
https://news.ycombinator.com/item?id=23746117

**Comment by RickyNotaro** [comment] 2020-07-06 23:54
Someone posted on Hacker News that someone posted on the GitiHub issue that someone posted the GitHub issue on Hacker News.

**Comment by RickyNotaro** [comment] 2020-07-06 23:55
[Someone posted on Hacker News that someone posted on the GitiHub issue that someone posted the GitHub issue on Hacker News.](https://news.ycombinator.com/item?id=23751496)

**Comment by RickyNotaro** [comment] 2020-07-06 23:55
[Someone posted on Hacker News that someone posted on the GitHub issue that someone posted the GitHub issue on Hacker News.](https://news.ycombinator.com/item?id=23751496)

**Comment by simonhong** [comment] 2020-07-07 01:09
NTP gets topsites data from browser's history and manages them(site url, favicon cache url and etc...) to its own place(localStorage) in [here](https://github.com/brave/brave-core/blob/master/components/brave_new_tab_ui/storage/grid_sites_storage.ts#L64).
Because of this, NTP shows previous topsite tiles after clearing history. (But favicon is not visible because NTP uses cached in history.)
cc: @bsclifton @petemill

**Comment by simonhong** [comment] 2020-07-07 06:18
I'm trying to fix this by clearing topsites data implicitely when user clears history. WDYT? @rebron @bsclifton

**Comment by bsclifton** [comment] 2020-07-07 06:40
@simonhong that should work perfectly. We will allow those to be edited (we have an issue for it), but at the moment it's tied directly to history (only real action you can do is move, pin, and close)

**Comment by simonhong** [comment] 2020-07-07 06:47
@bsclifton Ok. Working on it :)

**Comment by Joshfindit** [comment] 2020-07-07 10:21
As a user, I’m now concerned that there are other places where urls and/or history are kept.

**Comment by bsclifton** [comment] 2020-07-07 16:20
@Joshfindit top sites should be the only place where we stored URLs - which with localStorage it would be tied to the Brave extension's localStorage. Clearing cookies should be clearing it - but the problem is if you pick clear history, this should be wiped too

There aren't any other areas we're aware of- but might be good to do an audit
cc: @diracdeltas

**Comment by n-e-r-u** [comment] 2020-07-08 11:56
Yes please fix this. My student seen the pornhub icon on top sites.

**Comment by niutech** [comment] 2020-07-08 13:33
@n-e-r-u Why don't you at least use the Incognito mode?

**Comment by n-e-r-u** [comment] 2020-07-08 14:03
> @n-e-r-u Why don't you at least use the Incognito mode?

It was just a joke. At least, i imagine people complaining about this issue because of porn website in top sites :D

**Closed** 2020-07-22 12:09 UTC
Labels: QA/Yes, feature/history, priority/P2

**Comment by GeetaSarvadnya** [comment] 2020-08-18 12:47
Verification passed on

```

Brave | 1.13.73 Chromium: 84.0.4147.125 (Official Build) dev (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/6047
Scenario 1:
NTP with some top sites
![image](https://user-images.githubusercontent.com/38657976/90514264-929b4680-e17e-11ea-9c18-93982dee8623.png)

- Verified that the deleted site `cnn.com` from the brave://histrory is removed from NTP top sites list
![image](https://user-images.githubusercontent.com/38657976/90514361-b5c5f600-e17e-11ea-822a-33f9dc3c0e1a.png)
- Verified that the deleted pinned site `theverge.com` from the brave://histrory is removed from NTP top sites list 
![image](https://user-images.githubusercontent.com/38657976/90514441-cfffd400-e17e-11ea-9f5c-f45bf5d8b073.png)
![image](https://user-images.githubusercontent.com/38657976/90514524-ec9c0c00-e17e-11ea-9735-b59bdc0f17ea.png)
- Verified that the top sites are removed from NTP's when whole history is removed from brave://hostory
![image](https://user-images.githubusercontent.com/38657976/90514654-12c1ac00-e17f-11ea-88f8-dc99e0ee4829.png)



**Scenario 2:** - launch profile with SR code
- Verified that the NTP's have SR images along with SR top sites pinned
![image](https://user-images.githubusercontent.com/38657976/90513678-a4301e80-e17d-11ea-984e-c98121700004.png)

- Verified that the history is empty in SR profile
![image](https://user-images.githubusercontent.com/38657976/90513731-b90cb200-e17d-11ea-8069-131ad2faea86.png)
