### ISSUE TITLE
VPN auto disconnects when the device goes to sleep for more than an hour

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26885] opened 2022-11-21 03:58 UTC
## Description 

VPN auto disconnects when the device goes to sleep for more than an hour

## Steps to Reproduce

   1. Clean profile 1.46.118
   2. Install VPN
   3. Wait for device to go to sleep for more than an hour
   4. Login back to device, VPN is disconnected

## Actual result:

VPN auto disconnects when the device goes to sleep for more than an hour

## Expected result:
VPN should not auto disconnect

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.46.118 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 10 Version 21H2 (Build 19044.2251)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @spylogsster @bsclifton @mattmcalister

**Comment by bsclifton** [comment] 2022-11-22 08:32
@GeetaSarvadnya is this a dupe of https://github.com/brave/brave-browser/issues/26351?

**Comment by bridiver** [comment] 2022-11-30 16:23
https://github.com/brave/brave-browser/issues/26351#issuecomment-1332421555

**Comment by bsclifton** [comment] 2022-12-01 06:29
Closing as a duplicate of https://github.com/brave/brave-browser/issues/26351

**Closed by bsclifton** 2022-12-01 06:29 UTC
Labels: bug, OS/macOS, OS/Windows, QA/Yes, QA/Test-Plan-Specified, OS/Desktop, feature/vpn
