### ISSUE TITLE
certain upgrades are notifying users that Ads are available - follow up to 5434

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6270] opened 2019-10-02 00:38 UTC
## Description 
Found while testing #5434 

Certain upgrades are prompting users that 'Brave Ads have arrived'. 

This is similar to, but not the same as https://github.com/brave/brave-browser/issues/4383.

## Steps to Reproduce

pre req: be in one of the original Ad regions (US, UK, CAN, FR, GER)
   1. Install 0.63.55
   2. Enable Rewards
   3. Disable Ads only
   4. Upgrade on `test` channel to 0.69.131

Also experienced this when starting with version `0.66.101`. Probably applies to other versions as well.

## Actual result:
Prompted about `Brave Ads have arrived!` on BAT logo.

## Expected result:
No prompt until https://github.com/brave/brave-browser/issues/4383 implemented. Even then, seems like a slightly different notification is expected with that issue.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.131 Chromium: 77.0.3865.90 (Build ufficiale) (a 64 bit)
-- | --
Revisione | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
Sistema operativo | macOS Versione 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 0.68.x no, 0.69.x yes
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? probably
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @brave/legacy_qa @rebron

**Comment by GeetaSarvadnya** [comment] 2019-10-11 11:41
Reproduced in Windows 10 x64 - 0.69.135

![image](https://user-images.githubusercontent.com/38657976/66648837-33a99e80-ec4a-11e9-8430-3a7fafc9b931.png)

**Comment by LaurenWags** [comment] 2019-10-11 13:52
Reproduced on macOS:
- Upgraded build from 0.64.77 to 0.69.135 
- Upgraded build from 0.69.132 to 0.69.135 
<img width="1202" alt="Screen Shot 2019-10-11 at 9 45 41 AM" src="https://user-images.githubusercontent.com/28145373/66656401-e9a1c800-ec0b-11e9-8e16-aa916f937cae.png">

**Comment by GeetaSarvadnya** [comment] 2019-10-15 12:54
This is reproducible even if browser is restarted. STR is mentioned below:

1. Clean profile 0.70.116
2. Enable rewards
3. Turn off Ads switch
4. Exit and relaunch the browser
5. Enable Ads notification is shown on BAT logo


0.64.77 - Not Reproducible
0.63.55 - Not Reproducible
0.65.121 - Not Reproducible
0.66.101 - Not Reproducible
0.67.125 - Not Reproducible
0.68.142 - Not Reproducible
0.69.135 - **Reproducible**
0.70.116 - **Reproducible**

**Comment by btlechowski** [comment] 2019-10-15 23:48
Reproduced on 

Brave | 0.72.103 Chromium: 78.0.3904.50 (Official Build) nightly (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Linux

1. Installed 0.69.x.
2. Enabled rewards
3. Disabled ads
4. Upgraded to 0.72.x
![image](https://user-images.githubusercontent.com/34715963/66877722-e6655e00-efb6-11e9-8292-74fd8ffb629d.png)

**Comment by tmancey** [comment] 2019-10-29 15:26
@LaurenWags Can this issue please be retested as part of https://github.com/brave/brave-browser/issues/6612 when merged

**Comment by GeetaSarvadnya** [comment] 2019-11-04 20:12
The issue is still reproducible in Windows 10 x64 - 0.71.111 followed the STR from https://github.com/brave/brave-browser/issues/6270#issuecomment-542196777

**Comment by tmancey** [comment] 2019-11-04 22:57
@GeetaSarvadnya 6612 was only just merged to nightly. Please test in latest nightly with 6612. Thanks

**Comment by btlechowski** [comment] 2019-11-27 05:59
@tmancey The issue is still reproducible

Brave | 1.2.11 Chromium: 78.0.3904.108 (Official Build) dev (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Used test plan from https://github.com/brave/brave-browser/issues/6270#issuecomment-542196777

![image](https://user-images.githubusercontent.com/34715963/69697616-3c174500-10e3-11ea-965d-0532219beb59.png)

**Comment by btlechowski** [comment] 2019-11-27 16:21
@tmancey decided that the issue found by @GeetaSarvadnya in https://github.com/brave/brave-browser/issues/6270#issuecomment-542196777 merits its own ticket. Logged https://github.com/brave/brave-browser/issues/7133

**Comment by tmancey** [comment] 2019-11-29 13:00
Closing issue for retesting as @btlechowski has created #7133 for an edge case. However once users are running a build with #6612 on-boarding will be shown for users who have ads switched-off as part of the migration

**Closed by tmancey** 2019-11-29 13:00 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/ads, priority/P4
