### ISSUE TITLE
New tab page has "0" left in the header as typo

### ISSUE THREAD

**Issue by raoalok** [brave/brave-browser#6900] opened 2019-11-13 11:16 UTC
## Description 

New tab page has "0" left in the header as typo.

<img width="1437" alt="Screen Shot 2019-11-13 at 4 40 13 PM" src="https://user-images.githubusercontent.com/24505929/68758803-7ccb8480-0634-11ea-96fd-e8347d6ae339.png">

**Comment by NejcZdovc** [comment] 2019-11-13 13:39
closing as dupe of https://github.com/brave/brave-browser/issues/5710

**Closed by NejcZdovc** 2019-11-13 13:39 UTC

**Comment by bsclifton** [comment] 2019-11-13 18:51
Thanks for the report, @raoalok 😄 We have a fix already I believe in our dev build and it'll be working it's way down to release channel soon
