### ISSUE TITLE
Dark/Light mode toggle not fully respected

### ISSUE THREAD

**Issue by willstocks** [brave/brave-browser#5451] opened 2019-07-30 15:07 UTC
Taken from Community post (unanswered - see [here](https://community.brave.com/t/dark-light-mode-toggle-not-fully-respected/65185)) as I still see this issue if ever I try to toggle dark/light mode based on "Same as Windows" or statically declaring the color theme disregarding Windows.

## Description of the issue:
I enabled Dark Mode on Windows 10, but changed Brave from “Same as Windows” to “Light”.

Now, I see the main area of the browser is light, but the settings menu, downloads bar etc. is all in Dark Mode - it’s all pretty jarring. The text in the downloads bar is barely legible as the font is so light.

## Steps to Reproduce:
1. Set Windows colour scheme to “Dark”
1. Change Brave from “Same as Windows” to “Light”
1. Restart Brave - areas of the UI are still dark?
1. Actual Result (gifs and screenshots are welcome!):
1. Selecting “Light Mode” only styles certain parts of the Brave UI as “Light”. The rest is dark (I’ve also restarted Brave, and have also restarted my machine since!).

Top bar fine, downloads bar dark?
![](https://sjc1.discourse-cdn.com/business4/uploads/brave/optimized/3X/8/3/8375f8bad430a921900cf62479c87ac545af3b06_2_1035x559.png)

Settings menu dark?
![](https://sjc1.discourse-cdn.com/business4/uploads/brave/original/3X/7/1/71eb7d6deda966e8c662a90c82d13911bbfa1c36.png)

Settings page dark, despite being set to light?
![](https://sjc1.discourse-cdn.com/business4/uploads/brave/optimized/3X/2/6/26ffae535837306802d9746b5a64dff5696c3779_2_1035x382.png)

## Expected result:
Selecting “Light Mode” should apply the light mode throughout the entire Brave UI, not just parts of it?

## Reproduces how often:
N/A - I had never really used Dark Mode on Windows before and don’t have another machine to hand to play with.

## Operating System and Brave Version:
Windows 10 Enterprise. Version 1809. Build 17763.259.
Brave Version 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)
Brave Version 0.66

Additional Information:

**Comment by Brave-Matt** [comment] 2019-08-02 15:48
@willstocks-tech,
This is certainly an issue, but can you try and go to `Appearance --> Theme`, select Light theme (or same as Windows) -- then, select the drop down again and choose Dark, then (last time I promise) select Light theme _again_? 

While it's not an _actual_ solution, this often resolves the color issue for me:
![THEME](https://user-images.githubusercontent.com/3299098/62382311-28c3e680-b502-11e9-8103-378c7c90876f.gif)

**Comment by kjozwiak** [comment] 2019-08-02 17:02
@willstocks-tech what is your default theme set on Windows? Do you maybe have a dark one selected that's propagating into Brave?

**Comment by willstocks-tech** [comment] 2019-08-02 17:27
@kjozwiak - my Windows theme at the time was Dark, however that is partially my point here:
Brave’s theme toggle should overrule that setting. If I set my theme to “same as Windows” then that’s fine. But if I set it to “Light” in this case, then Brave should be themed Light. Windows theme should not propagate throughout Brave’s UI

**Comment by rebron** [comment] 2019-08-09 17:01
cc: @simonhong Did you fix this one from a previous issue?

**Comment by Brave-Matt** [comment] 2019-12-03 22:11
+1 from reddit:
https://www.reddit.com/r/brave_browser/comments/e5j7po/dark_appearance_color_issue/

I was under the impression we had addressed this issue already? cc @rebron

**Comment by simonhong** [comment] 2019-12-04 00:17
Hmm, this was fixed and I tried many times but can't repro on my Win10.

**Comment by rebron** [comment] 2019-12-04 17:19
@Brave-Matt Can you get the OS/OS version? Only thing I can think of is 'Auto' setting in macOS not applying since it changes from light to dark. Was going to say may be multiple profile issue but user is reporting only one profile in use.

**Comment by rebron** [comment] 2019-12-04 17:20
@Brave-Matt Nevermind, I see user mentioned Windows 10. I'll see if I can reproduce too.

**Comment by rebron** [comment] 2020-02-26 19:34
@willstocks We've had numerous updates/fixes to themes since this has been filed. Are you still having issues with dark/light toggle on Windows 10 with our latest 1.4.95 release?

**Comment by willstocks** [comment] 2020-03-02 16:06
@rebron I haven't noticed anything obvious on W10

**Comment by rebron** [comment] 2020-03-02 18:12
@willstocks Can we go ahead and close this issue then?

**Comment by willstocks** [comment] 2020-03-03 13:32
Yes feel free to! 🙂

Will Stocks
Blogger & Technology Aficionado
💭: @willstocks_ (Twitter, Instagram, Pinterest)
⌨️: willstocks (GitHub)
👨🏻‍💻: willstocks.co.uk
________________________________

**Comment by rebron** [comment] 2020-03-04 00:08
Closing. Thanks for filing and following up with us @willstocks Really appreciated!

**Closed by rebron** 2020-03-04 00:08 UTC
Labels: OS/Windows, feature/themes, needs-more-info
