### ISSUE TITLE
missing conversionEnvelope on ios conversions for Verifiable Ad Conversion

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-browser#19943] opened 2021-12-06 18:28 UTC
Verifiable Ad Conversions do not seem to be working consistently on iOS.

Originally thought to be due to slow upgrades but example A. is a fresh campaign that only started after ios was supposed to be supported.

All ios conversions are missing conversion envelope
[Example A. ](https://metabase.bsg.brave.com/question/1245/notebook?campaign_id=8b30cb36-e5d4-460b-9e95-3199d80720bb)

Some ios conversions have conversionEnvelope
[Example B.](https://metabase.bsg.brave.com/question/1245/notebook?campaign_id=8b30cb36-e5d4-460b-9e95-3199d80720bb)
Use link from above but replace `WHERE` clause with 
`WHERE ads_aurora.campaign_redshift_staging.campaign_id in ('04d01606-3bf2-41d9-afa2-54408159ed43', '1056f376-67d3-49dd-a255-f0854f1c4907')`

## Testing
Set settings to US-geo.

#### 1.  DOM
Confirm staging catalog contains the following creativeInstanceId
```
VAC DOM:
creativeInstanceId: de8274a9-716b-4340-afa1-9bfa52289077
Conversion URL: https://brave.com/?vac=*
```
Map locally page.html from .zip file in https://github.com/brave/brave-core/pull/8640
Force Ad for creativeInstanceId
Go to conversion URL: https:brave.com/?vac=DOM
Confirm that conversion ID is extracted into conversion queue table
Confirm that conversionEnvelope is generated and sent in ads confirmation

#### 2. URL
Confirm staging catalog contains the following creativeInstanceId
```
VAC URL:
creativeInstanceId: 0e3fa44c-edd4-4ad3-b21e-e6c93ef001c4
Conversion URL: https://*.nytimes.com/section/world?conversion_id=*
```
Force Ad for creativeInstanceId
Go to conversion URL: https://www.nytimes.com/section/world?conversion_id=tm-<insert_value>
Confirm that conversion ID is extracted into conversion queue table
Confirm that conversionEnvelope is generated and sent in ads confirmation

Confirm with @iambrianfung that these confirmations are in the staging ads database

**Comment by tmancey** [comment] 2022-01-28 22:10
Closing issue as duplicate of https://github.com/brave/brave-ios/issues/4914

**Closed by tmancey** 2022-01-28 22:10 UTC
Labels: bug, needs-investigation, feature/ads
