### ISSUE TITLE
GPU-related artifacts

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#3969] opened 2019-04-02 14:40 UTC
## Description 
From Twitter: https://twitter.com/JohnMarkoff2/status/1111299290268196864

> My Brave experience has become so horrible. A new tab takes 3-5 secs, typing in the url bar has a lag of multiple seconds. While typing, the window turns to garbage.  I deleted ~/Library/Application Support/Brave* and reinstalled and it's the same.
>
> Automatic graphics switching does not have an impact, but I do have more than one GPU card.
>
> Chrome works on the same machine.
>
> It's only a brave issue and for me it didn't start until the Dev release w/ ads. It's actually a 2012 with a GeForce GT 650 running OSX Yosemite. No issues on my other computers. Running Brave immediately turns the fan up to max and I get that weird graphic effect.

More details in the thread

![image](https://user-images.githubusercontent.com/3109556/55411301-9df0d080-558f-11e9-9978-8ad9d335cbe7.png)

**Comment by iefremov** [comment] 2019-04-02 14:46
[chrome_gpu.zip](https://github.com/brave/brave-browser/files/3034493/chrome_gpu.zip)

GPU logs from Chrome and Brave (note different versions).
Brave managed to pick Apple drivers, while Chrome uses Intel (?)

**Comment by iefremov** [comment] 2019-04-02 14:46
@bbondy @bridiver @BrendanEich 
FYI, filed the GPU issue discussed in twitter

**Comment by iefremov** [comment] 2019-04-02 14:47
@rebron please triage

**Comment by iefremov** [comment] 2019-04-06 09:36
Similar picture is in https://github.com/brave/brave-browser/issues/3471#issuecomment-480489980

**Comment by larseggert** [comment] 2020-05-20 16:24
Similar issue here, in Google Sheets. Version 1.10.64 Chromium: 81.0.4044.138 (Official Build) beta (64-bit).

<img width="1099" alt="Screen Shot 2020-05-20 at 19 23 29" src="https://user-images.githubusercontent.com/200328/82471484-6dd7fa00-9acf-11ea-89d3-ba8cc1b22578.png">

**Comment by bsclifton** [comment] 2020-05-21 05:45
@larseggert if you run into this again, you can try disabling hardware acceleration under brave://settings/system

**Comment by larseggert** [comment] 2020-05-21 13:13
It’s a max’ed out 16” MacBook, running on discrete GPU, since I have a large external monitor attached.

I think this is actually a Chromium issue, when it happens in Brave it also happens in Chrome.

**Comment by lukemulks** [comment] 2020-07-17 06:20
I'm also encountering this issue. 

`

Brave | 1.12.87 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Linux
JavaScript | V8 8.4.371.19
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Command Line | /opt/brave.com/brave-dev/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --enable-features=DnsOverHttps,AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode,MixedContentSiteSetting,ReducedReferrerGranularity,PasswordImport,PrefetchPrivacyChanges --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,TextFragmentAnchor,AllowPopupsDuringPageUnload,AutofillEnableAccountWalletStorage,NotificationTriggers,SmsReceiver,TabHoverCards,VideoPlaybackQuality,UseButtonTranslateBubbleUI --flag-switches-begin --load-media-router-component-extension=1 --enable-features=DnsOverHttps,AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode,MixedContentSiteSetting,ReducedReferrerGranularity,PasswordImport,PrefetchPrivacyChanges,BraveAdblockCosmeticFiltering,TabGroups --flag-switches-end
`

I'm encountering the issue on several different websites at the moment. 

The most recent was Twitter: 
![Screenshot from 2020-07-16 23-06-34](https://user-images.githubusercontent.com/8979240/87754455-d08cff80-c7b9-11ea-8b65-65b83545547d.png)

Artifacts present at the top of the Mentions section. 

I've reproduced on at least 3 different occasions in Google Sheets. 

Will disable hardware acceleration and report back if I reproduce the issue.

**Comment by kachapman** [comment] 2020-09-03 21:28
Disabling hardware acceleration solved the problem, but created a new problem where certain web pages that were using it are extremely slow.

**Comment by kachapman** [comment] 2020-09-16 16:05
The issue still persists in Version 1.14.81

**Comment by jeroenim0** [comment] 2020-11-01 16:59
1.16.67 still present, restart of the browser solves the issue though. No need to reboot..

**Comment by eljuno** [comment] 2020-11-22 04:12
+1 from Community httpss://community.brave.com/t/display-glitches-after-a-while/181318?u=eljuno

You'll find similar reports on Community.

**Comment by bsclifton** [comment] 2021-02-08 08:07
Closing as duplicate of https://github.com/brave/brave-browser/issues/3471

**Closed by bsclifton** 2021-02-08 08:07 UTC
Labels: gpu/driver
