### ISSUE TITLE
Moving of bookmark may not be synced when bookmark is added during  `Looking for device` state

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#7991] opened 2020-01-31 10:39 UTC
Found while testing: https://github.com/brave/brave-core/pull/4324

If bookmarks were added during `Looking for device` state, then moving of existing bookmark will not be propagated. Note: best to follow the STR

Important: Reproducible on 1.5.x, 1.4.x, 1.3.x. Not reproducible on 1.2.x

## Steps to Reproduce

   1. Clean profile DeviceA and DeviceB
   2. DeviceA: create bookmark `a1.com`
   3. DeviceA: create sync chain and copy code words
   4. DeviceB: enter code words
   5. DeviceB: [During `Looking for device`]create bookmark `b1.com`
   6. Wait for sync
   7. DeviceA: move `a1.com` after `b1.com` bookmark 
   8. Wait till the change is propagated to DeviceB

DeviceA: Ubuntu 18.04LTS
DeviceB: Windows 7x64

## Actual result:

The moving of bookmark is not propagate to another device
DeviceA
![image](https://user-images.githubusercontent.com/34715963/73531419-b3868f00-441a-11ea-83a0-c4856a7a8ab7.png)

DeviceB
![image](https://user-images.githubusercontent.com/34715963/73531403-ac5f8100-441a-11ea-85d6-51bc5e20f026.png)

## Expected result:
The moving of the bookmark is always propagated

## Reproduces how often: 

100% repro rate with above STR

## Brave version (brave://version info)

**Reproducible on**

Brave | 1.5.69 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.5.69 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Ubuntu 18.04 LTS

Brave | 1.3.106 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Ubuntu 18.04 LTS

Brave | 1.3.106 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

**Not Reproducible on**

Brave | 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Ubuntu 18.04 LTS

Brave | 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

cc @brave/legacy_qa @jsecretan @AlexeyBarabash @darkdh @rebron  @bsclifton

**Comment by darkdh** [comment] 2020-02-01 00:29
This might be dupe of https://github.com/brave/brave-browser/issues/7691

**Comment by btlechowski** [comment] 2020-02-03 12:55
@darkdh Looks like it. Feel free to close one as a duplicate.

**Closed** 2020-02-03 18:56 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, duplicate, feature/sync, regression
