### ISSUE TITLE
Browser freezes while downloading something

### ISSUE THREAD

**Issue by abhagsain** [brave/brave-browser#8397] opened 2020-02-25 08:59 UTC
## Description 

The setting of the browser is to ask where to download each file from the internet. So when it open file explorer it freezes the browser and I need to kill the it from the task manager. 
## Steps to Reproduce

   1.  Change default download setting to "ask every time" when downloading something
   2.  Try to download something, zip, mp3, image files.

## Actual result:

![Screenshot (45)](https://user-images.githubusercontent.com/36589645/75231279-2ba66180-57db-11ea-9de0-5e4390268e1f.png)

Freezes the whole browser and it can't be closed
## Expected result:
Should download file(s)

## Reproduces how often: 

8 / 10 times.

## Brave version (brave://version info)

Brave | 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit)
-- | --
Revision | dc00a510e4c2ae25c4d084cc3d946fc782249224-refs/branch-heads/3987@{#917}
OS | Windows 10 OS Version 1909 (Build 18363.657)
JavaScript | V8 8.0.426.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,WebXrGamepadModule,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,VideoPlaybackQuality,WebXR --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\Predator\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | 5e3a236d-4113a79e

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome? 
No. Chrome works fine

**Comment by rebron** [comment] 2020-04-17 19:24
@abhagsain Are you still running into this issue with the latest 1.7.92? I tried with our latest version on Win 10 and can't reproduce.

**Comment by bsclifton** [comment] 2020-07-27 05:48
Closing as there hasn't been an update. Let's re-open if it's still happening. Thanks 😄

**Closed by bsclifton** 2020-07-27 05:48 UTC
Labels: bug, feature/download, needs-investigation, perf
