### ISSUE TITLE
Bookmarks not showing only in new tab

### ISSUE THREAD

**Issue by dnrm** [brave/brave-browser#16535] opened 2021-06-21 18:41 UTC
## Description 

Always show bookmarks in new tab toggle doesn't work.

## Steps to Reproduce

   1. Go to settings
   2. Disable bookmarks but click the "Always show bookmarks on new tab page" toggle.
   3. Open a new tab

## Actual result:

Bookmarks aren't shown

## Expected result:

Bookmarks to be shown only in new tab

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave: 1.25.73 Chromium: 91.0.4472.106 (Official Build) (x86_64)
Revision: 574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}
OS: macOS Version 10.15.7 (Build 19H1030)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes

- Can you reproduce this issue with the beta channel? 
Don't know (haven't tested)
- Can you reproduce this issue with the nightly channel? 
Don't know (haven't tested)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:

None

**Comment by rebron** [comment] 2021-06-21 20:34
@stephendonner When you get a chance, can you take a look? I can't reproduce this myself as I'm seeing bookmarks on the new tab page but not on any other tab when selecting "Always show bookmarks on a new tab page".

@dnrm Do you have any bookmark related extensions or other extension that may be conflicting here?

**Comment by dnrm** [comment] 2021-06-22 12:55
I found out that the daily.dev extension causes this issue. Thanks @stephendonner

**Comment by rebron** [comment] 2021-06-22 17:41
@dnrm Thanks for following up. I'm going to close this one out then.

**Closed by rebron** 2021-06-22 17:41 UTC
Labels: OS/Desktop, feature/bookmarks, needs-investigation

**Comment by stephendonner** [comment] 2021-06-25 15:15
Sorry for missing the ping; thanks for resolving @dnrm and @rebron 👍
