### ISSUE TITLE
Improve tab selected state contrast for vertical tabs

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#41717] opened 2024-10-18 03:00 UTC
### Description

Hard to know which tab is selected

![Image](https://github.com/user-attachments/assets/2528212e-4e42-4dbf-add9-3cb62f5fad4d)

### Steps to reproduce

1. Enable vertical tab
2. Create some tabs
3. Select tabs

### Actual result

See the screen shot

### Expected result

should have more noticable color for selected and inactive tab

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.73.9 Chromium: 130.0.6723.44 (Official Build) nightly (x86_64) 

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @bsclifton @aguscruiz

**Comment by MadhaviSeelam** [comment] 2024-10-18 15:52
Reproduced the issue in Win 11 x64
```
Brave | 1.71.114 Chromium: 130.0.6723.58 (Official Build) (64-bit)
-- | --
Revision | 89c4031c685a4296315a6f421f46275f0b72dd55
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

Light | dark | custom
----- | ----- | ----
![Image](https://github.com/user-attachments/assets/62a29c54-0eb8-424b-8813-46734e689a32)|![Image](https://github.com/user-attachments/assets/0c63f0c6-3b35-4bdf-9763-a96438ce2eaa)|![Image](https://github.com/user-attachments/assets/a4fa04c3-15cb-4475-a5f9-f067ce50b6c3)

**Comment by rebron** [comment] 2024-10-18 17:50
Related: https://github.com/brave/brave-browser/issues/41450

**Comment by valynor** [comment] 2024-10-19 14:30
This is not only affecting vertical tabs but regular tabs, too: 

![Image](https://github.com/user-attachments/assets/bd8b9107-4e6a-4ba5-9d02-cdf732a30eaa)

The selected pinned tab (Protonmail) is BARELY visible on a large monitor esp. when looked at off-axis.

**Comment by Brave-Matt** [comment] 2024-10-23 17:14
Yes I am seeing _many_ users complain that in dark mode specifically it is too hard to tell which tab is selected:
https://community.brave.com/t/new-horizontal-tab-design-is-excellent/507900/4 (just a few examples)

**Comment by aguscruiz** [comment] 2024-10-23 17:21
Gonna be working on improving the contrast with @fallaciousreasoning over the next few days. 
This may be related too
https://github.com/brave/brave-browser/issues/41720#event-14801938066

**Comment by aguscruiz** [comment] 2024-11-08 12:00
Already fixed in Nightly

https://github.com/brave/brave-core/pull/26259

**Closed by aguscruiz** 2024-11-08 12:00 UTC
Labels: design, priority/P2, QA/Yes, release-notes/exclude, OS/Desktop, feature/vertical-tabs

**Comment by valynor** [comment] 2024-11-13 21:12
@aguscruiz 

I'm sorry to say the macOS/dark mode/"grey default colour" theme is just as bad as before: the active tab is VERY hard to make out and for pinned tabs it's almost impossible to see which one is the active one. 

![Image](https://github.com/user-attachments/assets/de0bc28d-c9d0-438e-a1d3-c104444b4b65)

**Comment by aguscruiz** [comment] 2024-11-14 11:57
> [@aguscruiz](https://github.com/aguscruiz) [@Brave-Matt](https://github.com/Brave-Matt)
> 
> I'm sorry to say the macOS/dark mode/"grey default colour" theme is just as bad contrast-wise as before: the active tab is VERY hard to make out and for pinned tabs it's almost impossible to see which one is the selected one.
> 
> ![Image](https://github.com/user-attachments/assets/de0bc28d-c9d0-438e-a1d3-c104444b4b65)
> 
> Brave 1.73.89 Chromium: 131.0.6778.69 (Official Build) (arm64)
> 
> I _want_ to use this theme because it's the darkest one but I'm constantly hunting to find the active tab and this isn't exactly fun. Please make it stand out (considerably) more.

Hi @valynor , thanks for reaching out! Are you using the default dark theme? In the latest release version the active tab should look like this.

![Image](https://github.com/user-attachments/assets/552d9f50-3c02-414e-b346-3e2b8a9b39fd)

**Comment by valynor** [comment] 2024-11-14 15:20
Hi @aguscruiz 
Yes to default theme and yes it looks like this. 
It's not my monitor, I see this on my main monitor, my iMac and on a MacBook just the same. 
And I just asked someone passing by what they think about the contrast of the active tab and they, too said it's hard to find. 

If you load a tab with bright white content this gets worse and it's even harder to see the selected tab because it outshines the already very low contrast. 

This is less of an issue in the "cool grey" and "grey" theme - but I truly think the contrast for the selected tab/selected pinned tab in the darkest "grey default colour" theme needs to be improved - or maybe give the active tab an (optional) brighter outline.
