### ISSUE TITLE
Check and fix regional ad blocking

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#4829] opened 2019-06-12 03:42 UTC
Check that regional ad blocking works on Android and fix any issues preventing it from working.

**Comment by emerick** [comment] 2019-08-21 15:13
Confirmed that regional ad blocking works on Android:

- Verified that switching languages in Settings and clearing the profile results in the correct regional list being selected by default
- Verified that correct list is downloaded and listed in brave://components
- Verified that ads are blocked per regional settings by visiting http://www.macwelt.de

The main issue I encountered is that we're not loading/displaying any Brave-specific WebUI pages (including brave://adblock/) on Android. Seems to be related to not building and loading `brave_resources.pak`. Also suspect we'll need to update the paths for Android in `common/resource_bundle_helper.cc`. Investigating this now.

**Comment by emerick** [comment] 2019-08-22 17:16
Created new issue to track Brave WebUI pages not loading on Android, so will close this issue for now.

**Closed by emerick** 2019-08-22 17:16 UTC
Labels: QA/No, android-related, priority/P1
