### ISSUE TITLE
Don't autocomplete hardcoded domain names when "use predictions service to help complete searches is disabled"

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#7747] opened 2020-01-16 00:34 UTC
Brave bundles ~500 domains that we think users might want autocompleted, so that some URL bar entries can be autocompleted for the user w/o a network request.  Even though this does not use a prediction service to help complete searches, I suggest disabling this feature when the user has disabled the "suggestion" setting.

![image](https://user-images.githubusercontent.com/76526/72483105-bc3d5b00-37b4-11ea-9c70-22b121b2225e.png)

I think this would be a good change because the current behavior is indistinguishable from what happens when you enable the above setting, and so this looks like a bug.  More importantly, it looks like a privacy-violating bug (e.g. the browser is making network requests I told it not to), which may lower user confidence in our other privacy protections, tools.  The user-serving benefit to the current configuration is small, and the risk (in perception) seems signifigant

**Comment by rebron** [comment] 2020-01-22 20:22
Closing as a dupe of https://github.com/brave/brave-browser/issues/7747. Sound right @snyderp?

**Comment by snyderp** [comment] 2020-01-22 20:40
@rebron not sure i follow the above.  This issue is a dupe of which issue?  (you did a self reference above)

**Comment by rebron** [comment] 2020-01-22 20:44
https://github.com/brave/brave-browser/issues/5934

**Comment by rebron** [comment] 2020-05-05 16:56
Closing. Addressed with this setting instead in https://github.com/brave/brave-browser/issues/9572

**Closed by rebron** 2020-05-05 16:56 UTC
Labels: design, feature/url-bar, priority/P3
