### ISSUE TITLE
[Feature request] Tab Groups

### ISSUE THREAD

**Issue by jaredready** [brave/brave-browser#9419] opened 2020-04-23 15:43 UTC
The latest release of Chrome and Chromium supports tab groups. Is this something that Brave is planning on supporting?

https://gizmodo[dot]com/tab-groups-is-chromes-best-new-feature-in-years-and-he-1842944249

**Comment by rebron** [comment] 2020-04-23 15:58
@jaredready You can try it in Brave here: brave://flags/#tab-groups

**Comment by jaredready** [comment] 2020-04-23 16:12
Oh thanks! I've got this enabled now.

**Comment by rodrigoswz** [comment] 2020-04-23 21:37
> @jaredready You can try it in Brave here: brave://flags/#tab-groups
> 

Yeah, activating this flag works, but consequently breaks handy menu when long press the tab icon on bottom bar.

**Comment by Brave-Matt** [comment] 2020-04-28 18:39
This is a dupe of #7142:
https://github.com/brave/brave-browser/issues/7142

**Closed** 2020-04-28 19:27 UTC
Labels: design, needs-discussion
