### ISSUE TITLE
Support the dark theme on the rewards page (dark mode)

### ISSUE THREAD

**Issue by Dizeeee** [brave/brave-browser#4229] opened 2019-04-25 07:07 UTC
This is a pretty simple problem, the colors setting that can be found in the appearance section of the menu does not seem to apply to the rewards page. The styling for the rewards page needs to be updated to support it.

**Comment by NejcZdovc** [comment] 2020-03-31 05:46
+1 from https://github.com/brave/brave-browser/issues/8926

**Comment by eljuno** [comment] 2020-06-30 19:09
Duplicate of #2822?

**Comment by NejcZdovc** [comment] 2020-07-01 04:54
let's keep it. Added  link to this issue in #2822

**Comment by anji5h** [comment] 2021-07-15 14:16
It's 2021 and still, the issue is not fixed.

**Comment by bsclifton** [comment] 2021-07-15 16:52
Hi folks

We are working on a new "2.0" interface for Rewards; you can track those issues with the [rewards-ui-2.0](https://github.com/brave/brave-browser/labels/rewards-ui-2.0) label. I've added this so we don't forget to include it in the scope of the work

**Comment by Rybec** [comment] 2022-07-13 05:09
Halfway through 2022, and it's still a problem.

**Comment by Miyayes** [comment] 2022-09-29 22:15
We will be moving to a whole new Rewards interface in Rewards 3.0 (a "cards model" that unifies with the Brave Wallet interface). There, we will have a dark version of the UI, since the Brave Wallet UI in general always has a light/dark theme. Since that is on the horizon, I will close this as "wontfix".

**Closed by Miyayes** 2022-09-29 22:15 UTC
Labels: feature/user-interface, feature/rewards, rewards-2.0
