### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by deepak365** [brave/brave-browser#34835] opened 2023-12-12 10:05 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.101 Chromium: 120.0.6099.71
Operating System: Mac OS X 14.1.2

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
Can't remember what I am doing, it randomly crashes. In the last 24 hours, it crashed 5 times. 

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/b01c0d00-8bde-260b-0000-000000000000

**Comment by gurgunday** [comment] 2023-12-12 11:44
+1, please fix this, it's very annoying

Brave randomly crashes, sometimes 3 times in an hour, sometimes once a day

It started after updating to the latest version

**Comment by bsclifton** [comment] 2023-12-12 20:32
Should be fixed with https://github.com/brave/brave-core/pull/21326 - closing this as a duplicate of https://github.com/brave/brave-browser/issues/34785

We'll be having a release coming up for 1.61 that fixes this issue in the next few weeks- stay tuned!

**Closed by bsclifton** 2023-12-12 20:32 UTC
