### ISSUE TITLE
Issues with importing browsing data using built-in "importer"

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#3674] opened 2019-03-12 00:05 UTC
## Description 

Several users have reported the `Import bookmarks and settings` feature does not import all (or sometimes any) browsing data from other browsers, including Brave Muon.
This issue is unfortunately vague because it seems to do the trick for some users, some get their bookmarks but nothing else, others get passwords and browsing data but no bookmarks, etc. Reports come from all OS and all channels and from all available browsers.
Importing browsing data should be seamless in order to lower the barrier-to-entry for new/would-be Brave users.

## Steps to Reproduce

   1. Close all other chrome/chromium process running, launch Brave
   2. `Menu --> Bookmarks --> Import bookmarks and settings`
   3. Choose from available browsers on machine and attempt to import browsing data
   4.* Note that again, there don't seem to be many "clear" steps to reproduce this exactly given the nature of the issue - selecting different data to import, or importing one set of data at a time (one check box) is encouraged.

## Actual result:

Some or all data may not be imported

## Expected result:
Any browsing data selected should be imported after completing the process.

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)

All channels:
- `v0.60.48` Rel
- `v0.61.43` Beta
- `v0.62.16` Dev

### Additional Information

User reports - I have more to ad as well:

https://community.brave.com/t/new-chrome-brave-will-not-import-cookies-passwords-used-built-in-bookmarks-more-from-old-brave/47492/7
https://community.brave.com/t/updates-not-picking-up-old-settings-from-0-25-2/47520/4
https://community.brave.com/t/importing-chrome-content-not-quite-right-passwords-missing/47066/7
https://community.brave.com/t/importing-data-from-chome/46743/2
https://community.brave.com/t/failing-to-import-history-bookmarks-passwords-from-chrome-chromium/46173

**Comment by bsclifton** [comment] 2019-03-12 05:50
cc: @rebron for help prioritizing - definitely seeing a good amount of users hitting this on GitHub (in addition to the issues @Brave-Matt has shared above from Community)

**Comment by rebron** [comment] 2019-03-12 18:38
@Brave-Matt Need more reproducible steps and matrix of browsers this is affecting.

**Comment by willstocks-tech** [comment] 2019-03-20 10:04
From [Community](https://community.brave.com/t/importing-chrome-content-not-quite-right-passwords-missing/47066)

Description of the issue:

I have just migrated from Chrome to Brave and used the “import settings” to import my Chrome stuff. Favourites and other things have imported, but saved passwords did not which is killerrrrrrrrrrrrrrrrrr!

Steps to Reproduce (add as many as necessary): 1. 2. 3.

Download and install Brave
Menu
Settings
Import
Select Chrome profile
Make sure that “Passwords” is enabled for import
Actual Result (gifs and screenshots are welcome!):

Check “Saved Passwords” and see nothing is in there :sob:

Expected result:

Chrome saved passwords should also import, not just favourites.

Reproduces how often:

Every time I retry importing!

Brave Version(See the About Brave page in the main menu):

0.60.47

Reproducible on current live release (yes/no):

Yes

**Comment by willstocks-tech** [comment] 2019-03-20 10:06
Further detail from the same community thread:

The import was the first thing I did - I had not browsed to any other pages before trying to import.

OS: Windows 10 Enterprise x64
OS Version: 1703
OS Build: 15063.1631

Importing passwords from: Chrome 72.0.3626.121 (Official Build) (64-bit)

Let me know if you need any other info - all bookmarks came through fine, it looks like it’s just the passwords that didn’t :frowning_face:

---

I just tried this - on my Windows 10 machine (where I’ve had Brave installed for a couple of days now) it did not work at all. I tried:
- Importing individual tickboxes
- Importing all tickboxes
- Importing just passwords

No change in the passwords at all. I even tried with Brave being the ONLY application open on the machine… no success :frowning: despite it giving me the big blue tick - I have all my bookmarks though!

I just did a fresh install of Brave on my MacOS Mojave (10.14.3) machine (never had Brave on it before), closed all browsers first, then launched Brave and did the import and it worked perfectly (it’s probably worth having an instruction pop-up first to say “close all browsers before importing”?)!

Any ideas what I can do to get the import to now work on my Windows 10 machine (I don’t sync between the two - one’s a personal machine, one’s a work machine).

**Comment by GeetaSarvadnya** [comment] 2019-06-11 09:46
+1 https://community.brave.com/t/unable-to-import-bookmarks-and-bookmarks-bar/64414/9

**Comment by danny1199** [comment] 2019-06-11 14:03
Tried numerous times to import bookmarks and bookmarks bar from Firefox on Windows 10 laptop and although everything says it went through ok, there are no bookmarks imported and the bookmarks bar is empty. Tried it with Firefox open - nothing.  Tried it with Firefox closed - nothing. Uninstalled Brave and installed again, using latest version - nothing.  I don't know what else I can do but I can't use it as my default browser as it is.

**Comment by bsclifton** [comment] 2019-06-18 20:23
This may be a duplicate of https://github.com/brave/brave-browser/issues/2198 and https://github.com/brave/brave-browser/issues/2710

**Comment by danny1199** [comment] 2019-06-18 20:35
I managed to resolve my issue by exporting my bookmarks and bookmarks bar as an html file from Firefox to my desktop then importing that file into Brave as html files. The bookmarks bar just appeared as a folder in the bookmarks bar on Brave so I had to open that and drag each file from the drop down to the bar. A bit long winded, but I got there.

**Comment by simonhong** [comment] 2020-04-21 00:41
On windows, password importing from chrome seems broken after this upstream change (https://chromium-review.googlesource.com/c/chromium/src/+/1842671).
We are using import service in a separated utility service.
The problem is generated encryption key in browser process was not passed to this utility process because upstream doesn't use encryption key in utility process while importing. It's brave's feature.

**Closed** 2020-04-24 00:08 UTC
Labels: bug, feature/importer, needs-more-info, priority/P3

**Comment by rebron** [comment] 2020-04-27 17:01
Verified this works in Windows 1.10.x, following the updated steps in the pr for both the import dialog screen and for onboarding. Imported from Chrome 81.x Version 81.0.4044.122 

Brave | 1.10.11 Chromium: 81.0.4044.122 (Official Build) nightly (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | Windows 10 OS Version 1903 (Build 18362.720)

**Comment by GeetaSarvadnya** [comment] 2020-04-29 10:19
Verification is in progress
```
Brave | 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1803 (Build 17134.1006)
```
- Verified the test plan from https://github.com/brave/brave-core/pull/5300
