### ISSUE TITLE
Android crash forgetful browsing shield settings 

### ISSUE THREAD

**Issue by whowantsmybigdata** [brave/brave-browser#31833] opened 2023-07-24 20:55 UTC
Brave Version: 1.52.130 Chromium: 114.0.5735.198
Operating System: Android 13

URL (if applicable) where crash occurred:
brave://settings/shields

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Fresh install from playstore 
2. Tried with and without enabling `brave://flags Enable First Party Storage Cleanup support`
3. Close app completely 
4. As no new settings show up after enabling forgetful browsing (as they do on Linux Desktop tried to open `brave://settings/shields`

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/8c120800-b231-6e0a-0000-000000000000

**Comment by deeppandya** [comment] 2023-07-24 21:19
@Uni-verse @vlad-hoff can you reproduce the issue here ?

**Comment by deeppandya** [comment] 2024-03-06 20:23
@hffvld i am closing the issue as we can't reproduce the issue now.

**Closed by deeppandya** 2024-03-06 20:23 UTC
Labels: crash, OS/Android
