### ISSUE TITLE
empty items in the permissions of privacy settings

### ISSUE THREAD

**Issue by 424344** [brave/brave-browser#28859] opened 2023-03-02 14:25 UTC
## Description 

I see two empty items in the permissions of privacy settings.
what are those items? 
![image](https://user-images.githubusercontent.com/26486758/222455113-a9da8a0b-41e8-4189-8aee-cb84f627de2e.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

## Brave version (brave://version info)

[Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (64-bit)](https://brave.com/latest/)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment] 2023-03-02 23:23
Closing as dupe of https://github.com/brave/brave-browser/issues/28773 and fixed in 1.49.117 and higher set to release next week.

**Closed by rebron** 2023-03-02 23:23 UTC
Labels: OS/Desktop
