### ISSUE TITLE
[Android] Address bar incorrect size in Private/Incognito

### ISSUE THREAD

**Issue by derekantrican** [brave/brave-browser#9145] opened 2020-04-11 02:46 UTC
##  Description 

Normal mode:
![image](https://user-images.githubusercontent.com/1558019/79033443-3f2b4300-7b63-11ea-8ce0-0b63670287b0.png) 

Private/Incognito
![image](https://user-images.githubusercontent.com/1558019/79033450-47837e00-7b63-11ea-84e0-e9d4d05f8e0d.png)

## Steps to reproduce 

   1. Open a private/incognito tab
   2. Open a URL that is long (eg a Google search)
   3. Notice how the address bar extends behind the Brave icon (shields) and tab counter (and the url is actually visible behind the tab counter)

## Expected result

Address bar should be the same in private and non-private

## Issue reproduces how often

Easily reproduced

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Have not tried

## Device details
   - Install type (ARM, x86): Not sure
   - Device (Phone, Tablet, Phablet): Phone (Pixel 2)
   - Android version: 10
   
## Brave version
1.5.131

**Comment by srirambv** [comment] 2020-04-13 04:41
Dupe of #9040

**Closed by srirambv** 2020-04-13 04:41 UTC
Labels: OS/Android
