### ISSUE TITLE
Opening a new tab results in RESULT_CODE_KILLED_BAD_MESSAGE error

### ISSUE THREAD

**Issue by loldev69** [brave/brave-browser#27154] opened 2022-12-04 11:12 UTC
## Description 
When opening a new tab, the resulting tab displays a RESULT_CODE_KILLED_BAD_MESSAGE error.
Setting the "New tab page" option to "Dashboard" or "Homepage" results in this error, while setting it to "Blank page" does not.
The chrome://newtab link also results in the same error, while the chrome://new-tab-page and chrome://new-tab-page-third-party links work fine.
Opening any actual website works fine.

## Steps to Reproduce

   1. Open a new tab, either by clicking the plus icon in the tab bar or with CTRL+T

## Reproduces how often: 
Happens every time I open a new tab.

## Brave version (brave://version info)
1.46.134 Chromium: 108.0.5359.94 (Official Build) (64-bit) 
713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
Windows 10 Version 22H2 (Build 19045.2251)

## Version/Channel Information:

This is on the current release.

**Comment by rebron** [comment] 2022-12-06 17:11
Hi @loldev69 Do you have an extension that controls the dashboard or homepage? Can you provide a screenshot?

**Comment by loldev69** [comment] 2022-12-06 17:18
hi @rebron, as far as I'm aware extensions can't modify privileged pages, in any case I've tried disabling all extensions and the issue persisted.
Here's a screenshot, not very useful obviously.
![error](https://user-images.githubusercontent.com/13751360/205978331-a6df8e1f-9139-4a83-a39a-3469960ecb91.png)

In any case, if you're not getting other reports of this it's probably some random config glitch.

**Comment by RuthlessRuler** [comment] 2022-12-06 17:35
> hi @rebron, as far as I'm aware extensions can't modify privileged pages, in any case I've tried disabling all extensions and the issue persisted. Here's a screenshot, not very useful obviously. ![error](https://user-images.githubusercontent.com/13751360/205978331-a6df8e1f-9139-4a83-a39a-3469960ecb91.png)
> 
> In any case, if you're not getting other reports of this it's probably some random config glitch.

Hey can you check if you have disabled Brave News under flags? Link to issue: #27184

**Comment by stephendonner** [comment] 2022-12-06 21:19
Maybe this is https://github.com/brave/brave-browser/issues/26876?

**Comment by rebron** [comment] 2023-01-18 16:44
Closing as dupe of #26876, fixed in 1.46.141

**Closed by rebron** 2023-01-18 16:44 UTC
Labels: feature/new-tab, needs-investigation, priority/P2, needs-more-info, OS/Desktop
