### ISSUE TITLE
Changes that went live in a recent update to Brave causes Brave to completely lockup when opening a new window or tab

### ISSUE THREAD

**Issue by patgarner** [brave/brave-browser#9681] opened 2020-05-08 01:25 UTC
## Description 
After a recent update to Brave, Brave completely locks up and is unusable for up to several seconds whenever a new tab or window is opened. I've observed it lasting for 8-10 seconds. Other users have reported longer in the forums. This issue appeared simultaneously with the new Binance widget, however, it is unclear whether this is coincidental. The issue appears to be directly related to the number of bookmarks associated with a profile. New profiles added with little or no bookmarks do not display this issue. This issue never occurred before and the number of bookmarks I have has not substantially changed lately. For now I have installed an extension that completely disables the Brave new tab/window pane with the background and widgets and replaces it with a blank empty gray view. It's not as pretty as having a nice background, but I  will take it over this issue any day and will continue using it until the issue is resolved. This is now the goto workaround for this issue among users on the forums.

## Steps to Reproduce
   1. Have lots of bookmarks. The profile I experience this issue with, my primary profile, has at least tens of thousands.Perhaps hundreds.
   2. Open a new tab or window by using the menu items or keyboard commands.
   3. Attempt to type into the search bar or interact with Brave.

## Actual result:
Brave completely locks up and is unresponsive for several seconds. I observed this lasted for up to 10 seconds. Another user reported 15 seconds or longer in the forums.

## Expected result:
New window/tab opens and you can immediately start entering a search term or URL or other begin interacting with Brave.

## Reproduces how often: 
Every single time.

## Brave version (brave://version info)
Brave | 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.4 (Build 19E287)

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Unknown.
- Can you reproduce this issue with the dev channel? Unknown.
- Can you reproduce this issue with the nightly channel? Unknown.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards?  No.
- Is the issue reproducible on the latest version of Chrome?  No.

## Miscellaneous Information:
When I initially observed the issue I went so far as to completely wipe all my Brave profiles and re set them up, culminating in re-importing my password data first (no issue), and then my bookmarks. As soon as the bookmarks were imported it appeared that the problem was there, but not as bad. However, within a short amount of time the problem quickly was the same as before. At that time I tried the beta and dev build and they both exhibited the issue. That's it so far.

**Comment by wdeschain** [comment] 2020-05-08 02:42
I have a post near the bottom with context.  I shared the experience troubling many.  I deleted several folders and individual tabs the day my browser came home.  I have no more than 400 at the moment.  I deleted about 150 I'd estimate.  Brave is running smoothly.

I'd also add that it is running smoothly on a machine with 988 MB of space, because at less than 500 MB my programs set to the taskbar no longer have a graphic.

Relevant? I do not know.  You're talking to someone who up til 5 days ago thought RNG existed in video games-- but I was set straight.

**Comment by aaronovz1** [comment] 2020-05-08 17:10
I am seeing this happen randomly and I have barely any Bookmarks, less then 50.

**Comment by artella-coding** [comment] 2020-05-10 14:55
Seeing problem here as well.

**Comment by norsehealer** [comment] 2020-05-10 17:23
this is happening on both my MBP 2011 and my PC (built in 2013).  the MBP is taking ~5 seconds from clicking the + for a new tab.  the PC is less time before it's responsive.

I have 875 bookmarks. but if i had to guess, the Binance is trying to obtain recent prices before displaying the new page; well maybe not.

**Comment by norsehealer** [comment] 2020-05-14 15:25
it seems a little faster today, after i updated.  but the loading of the actual content is still about the same.

**Comment by patgarner** [comment] 2020-05-14 16:02
I checked after updating to the latest release build and my experience is that if the issue has been improved at all, it is such a minimal change as to be insignificant. I immediately re-enabled the new tab plugin I'm using which completely disables Brave's new tab. Interestingly I'm finding that I much prefer using Chrome's default new tab page over Brave's regardless of whether this issue exists or not. So even if the issue is fixed I may not go back to using it.

**Comment by bsclifton** [comment] 2020-05-14 16:17
@patgarner thanks for providing the detailed info - this is definitely something we're tracking

I'm curious if you would be able to copy your profile and try Nightly? Here's how you could do that
- Close all instances of Brave (maybe copy these steps to text edit or similar)
- Open `~/Library/Application Support/BraveSoftware` in Finder
- Copy or duplicate the `Brave-Browser` folder; rename this copy as `Brave-Browser-Nightly`
- Download / Install Brave Nightly from https://brave.com/download-nightly/
- Launch Nightly

This has a great fix by @cezaraugusto which should help speed things up. If that speeds things up for you I can expedite the fix 😄 Please let us know!

**Comment by patgarner** [comment] 2020-05-14 20:18
@bsclifton Yep, the nightly build appears to have resolved the issue. So far I'm able to use it with my massive list of bookmarks and the standard Brave new tab page without issue. Great job @cezaraugusto!

**Comment by bsclifton** [comment] 2020-05-15 06:34
@patgarner awesome! Super glad that was the root cause 😄 (fix was done with https://github.com/brave/brave-core/pull/5490)

This change will be in our next Beta build coming out soon and will be working its way through to the release channel. Basically, it's in the 1.10.x series of builds

I'll go ahead and close this issue as a dupe of https://github.com/brave/brave-browser/issues/9481

**Closed by bsclifton** 2020-05-15 06:34 UTC
Labels: feature/new-tab, perf, priority/P1

**Comment by bsclifton** [comment] 2020-05-15 06:36
Having to switch to another release channel is not the best work-around, but once I get a Beta out for you, you'll be able to switch to that (which is more stable than Nightly) or you can stay on Nightly and experience the new features 😄
