### ISSUE TITLE
No collapse/expand widgets on bookmark folders in Sidebar view

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#21000] opened 2022-02-09 17:45 UTC
## Description 

No collapse/expand widgets on bookmark folders in Sidebar view

## Steps to Reproduce

   1. install `1.37.36`
   2. load `brave://flags`
   3. enable `Enable Sidebar`
   4. click to `Relaunch`
   5. click on the `Bookmarks` icon in Sidebar
   6. download and import `https://github.com/brave/qa-resources/blob/master/brave_sorted_5000.html`
   7. try to expand/collapse containing folders

## Actual result:

There's no "twisty" icons to collapse/expand folders.

<img width="1770" alt="Screen Shot 2022-02-09 at 9 42 01 AM" src="https://user-images.githubusercontent.com/387249/153259113-c95cf2b9-c45b-4820-9d03-1d02b46fb883.png">

## Expected result:

As there is in `brave://bookmarks` should be expand/collapse widgets

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.37.36 Chromium: 98.0.4758.87 (Official Build) nightly (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 11.6.1 (Build 20G224)

**Comment by stephendonner** [comment] 2022-02-09 17:46
cc @simonhong @rebron

**Comment by rebron** [comment] 2022-03-14 21:45
closing as dupe of https://github.com/brave/brave-browser/issues/21484 right @stephendonner?

**Closed by rebron** 2022-03-14 21:45 UTC
Labels: bug, QA/Yes, QA/Test-Plan-Specified, OS/Desktop, feature/sidebar
