### ISSUE TITLE
Opening links from other apps always open 3 tabs

### ISSUE THREAD

**Issue by funkybob** [brave/brave-browser#5077] opened 2019-06-29 23:42 UTC
## Description 
Any time a link is opened from another application [email, slack, terminal, xdg-open] Brave will create 3 new tabs, all with the same url.

## Steps to Reproduce

   1. xdg-open https://github.com

## Actual result:

3 tabs open, all with https://github.com

## Expected result:

1 tab opens

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave 0.65.121 from repo
Debian Buster

###

I'm not 100% ruling out that this may be an OS config issue, but so far I can't see how if, even directly from xdg-open, it happens everywhere.

**Comment by maximbaz** [comment] 2019-06-30 07:39
Duplicate of #4142, see here for an available workaround: https://github.com/brave/brave-browser/issues/4142#issuecomment-504742158

**Closed** 2019-07-01 06:54 UTC
Labels: duplicate

**Comment by funkybob** [comment] 2019-07-16 23:21
Two updates since opening this ticket, and just noting the issue persists...

**Comment by funkybob** [comment] 2019-07-23 02:10
As of today's debian update ( 0.66.101 ) the problem still persists.

**Comment by finalclass** [comment] 2019-12-16 17:42
The issue is still there (for me it opens a tab in brave and it opens firefox with that URL as well). However provided workaround fixes it.
