### ISSUE TITLE
Brave doesn't remember 'Block fingerprinting' option

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#26506] opened 2022-11-03 14:00 UTC
## Description 
Brave doesn't remember choosen option in Shields > Block fingerprinting section after it is relaunched.

## Steps to Reproduce
   1. Launch Brave
   2. Change Shields > Block fingerprinting option to different than default
   3. Close Brave
   4. Launch Brave

## Actual result:
Shields > Block fingerprinting option is set to default (Standard).

## Expected result:
Shields > Block fingerprinting option is set to option choosen in step two.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.45.118 Chromium: 107.0.5304.91 (Official Build) (64-bit)

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No ability to test

## Miscellaneous Information:
I'm unable to reproduce this issue on 1.45.118 Chromium: 107.0.5304.91 (Official Build) (arm64)

**Comment by GeetaSarvadnya** [comment] 2022-11-07 04:05
@NoneHead Issue is not reproducible on Windows 10 x64 - 1.45.118. I have tried changing both the local site shiled settings and global shield settings for FF, but Figerprint settings are retained after the browser restart. Could you provide the recorded file, please? Thanks!

**Comment by NoneHead** [comment] 2022-11-07 17:22
@GeetaSarvadnya  Here is a video with bug reproduction:

https://user-images.githubusercontent.com/114309523/200374170-83cc125a-6d5b-4160-a501-52441ac3a5ff.mp4

Brave 1.45.118
Windows 11 Pro 22H2

**Comment by DesignerOn** [comment] 2022-11-12 13:14
I have reproduced this bug on arm64 beta channel: [Version 1.46.99 Chromium: 107.0.5304.91 (Official Build) beta (arm64)](https://brave.com/latest/)

Could't reproduce at production channel: [Version 1.45.123 Chromium: 107.0.5304.110 (Official Build) (arm64)](https://brave.com/latest/)

**Comment by DesignerOff** [comment] 2023-02-26 19:49
This is probably the same problem: https://github.com/brave/brave-browser/issues/27860

Refer to an end for a solution.

**Comment by rebron** [comment] 2024-09-10 16:03
Closing as dupe per https://github.com/brave/brave-browser/issues/27860#issuecomment-1405391359

**Closed by rebron** 2024-09-10 16:03 UTC
Labels: feature/shields/fingerprint, feature/settings, OS/Desktop
