### ISSUE TITLE
nightly crashing with brave::BraveComponentInstallerPolicy::ComponentReady

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#4632] opened 2019-05-28 23:52 UTC
## Description 

We've received several internal reports that the latest nightly build has become unstable and has been crashing with the following:

```
brave::BraveComponentInstallerPolicy::ComponentReady(base::Version const&, base::FilePath const&, std::__1::unique_ptr >)
```

@alexwykoff @srirambv @jasonrsadler & @mandar-brave have reported the above crash. Reports:

* https://stats.brave.com/dashboard#crash/5ced4c45c32dd9001f139ec2
* https://stats.brave.com/dashboard#crash/5ced65e94183fc001f7968cc
* https://stats.brave.com/dashboard#crash/5cec1ca5b16078001f5e1916

## Steps to Reproduce

- N/A (We currently don't have any STR but seems like it happens when relaunching Brave)

## Actual result:

The latest `nightly` build has become unstable and has been crashing more frequently.

## Expected result:

The `nightly` build shouldn't be crashing that often and should be more stable.

## Reproduces how often: 

N/A as I'm not sure how frequent this is happening. However, @alexwykoff @srirambv @jasonrsadler & @mandar-brave mentioned that it's happening pretty often.

## Brave version (brave://version info)

Brave | 0.67.65 Chromium: 75.0.3770.38 (Official Build) nightly(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A - seems `nightly` related 
- Can you reproduce this issue with the beta channel? N/A - seems `nightly` related
- Can you reproduce this issue with the dev channel? N/A - seems `nightly` related
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by bsclifton** [comment] 2019-05-28 23:58
Closing as a dupe of https://github.com/brave/brave-browser/issues/4624

**Closed by bsclifton** 2019-05-28 23:58 UTC
Labels: bug, crash, priority/P3
