### ISSUE TITLE
System randomly freezing

### ISSUE THREAD

**Issue by Alan-Gomes** [brave/brave-browser#9294] opened 2020-04-17 14:41 UTC
## Description 

I'm using linux mint 19.3 (kernel 5.0.0-32-generic) and brave (latest version), the system freezes totally (needing to forcefully reboot the computer) randomly when using the browser and the latest system logs shows a possible browser crash.

Could be related to #7439 but there's more information on my log.

## Steps to Reproduce

Couldn't find a way to reproduce it, as it seems to be random

## Reproduces how often: 

Intermittent issue.

## Brave version (brave://version info)

Brave 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{# 1037}

## Version/Channel Information:

- Can you reproduce this issue with the current release? Couldn't test
- Can you reproduce this issue with the beta channel? Couldn't test
- Can you reproduce this issue with the dev channel? Couldn't test
- Can you reproduce this issue with the nightly channel? Couldn't test

## Miscellaneous Information:

Log from `journalctl` right before the crash:

```
Apr 17 11:12:34 desktop systemd-coredump[20963]: Process 2235 (brave) of user 1000 dumped core.
                                                 
                                                 Stack trace of thread 2330:
                                                 #0  0x000056555b822ce2 n/a (brave)
                                                 #1  0x000056555a220eba n/a (brave)
                                                 #2  0x000056555a232361 n/a (brave)
                                                 #3  0x000056555a232167 n/a (brave)
                                                 #4  0x000056555a1ec5b8 n/a (brave)
                                                 #5  0x000056555a232d98 n/a (brave)
                                                 #6  0x000056555a20b4e5 n/a (brave)
                                                 #7  0x000056555a246f9e n/a (brave)
                                                 #8  0x000056555a282528 n/a (brave)
                                                 #9  0x00007efbff0bb6db start_thread (libpthread.so.0)
                                                 #10 0x00007efbf915588f __clone (libc.so.6)
                                                 
                                                 Stack trace of thread 2332:
                                                 #0  0x00007efbff0c1ed9 futex_reltimed_wait_cancelable (libpthread.so.0)
                                                 #1  0x000056555a27e9b0 n/a (brave)
                                                 #2  0x000056555a27ef90 n/a (brave)
                                                 #3  0x000056555a24345c n/a (brave)
                                                 #4  0x000056555a243ccb n/a (brave)
                                                 #5  0x000056555a243a24 n/a (brave)
                                                 #6  0x000056555a282528 n/a (brave)
                                                 #7  0x00007efbff0bb6db start_thread (libpthread.so.0)
                                                 #8  0x00007efbf915588f __clone (libc.so.6)
                                                 
                                                 Stack trace of thread 2331:
                                                 #0  0x00007efbf9155bb7 epoll_wait (libc.so.6)
                                                 #1  0x000056555a34b47a n/a (brave)
                                                 #2  0x000056555a348d52 n/a (brave)
                                                 #3  0x000056555a28f257 n/a (brave)
                                                 #4  0x000056555a232d98 n/a (brave)
                                                 #5  0x000056555a20b4e5 n/a (brave)
                                                 #6  0x000056555a242e64 n/a (brave)
                                                 #7  0x000056555a246f9e n/a (brave)
                                                 #8  0x000056555a282528 n/a (brave)
                                                 #9  0x00007efbff0bb6db start_thread (libpthread.so.0)
                                                 #10 0x00007efbf915588f __clone (libc.so.6)
                                                 
                                                 Stack trace of thread 2333:
                                                 #0  0x00007efbf9155bb7 epoll_wait (libc.so.6)
                                                 #1  0x000056555a34b47a n/a (brave)
                                                 #2  0x000056555a348d52 n/a (brave)
                                                 #3  0x000056555a28f194 n/a (brave)
                                                 #4  0x000056555a232d98 n/a (brave)
                                                 #5  0x000056555a20b4e5 n/a (brave)
                                                 #6  0x000056555a246f9e n/a (brave)
                                                 #7  0x000056555a282528 n/a (brave)
                                                 #8  0x00007efbff0bb6db start_thread (libpthread.so.0)
                                                 #9  0x00007efbf915588f __clone (libc.so.6)
                                                 
                                                 Stack trace of thread 2398:
                                                 #0  0x00007efbff0c510d __lll_lock_wait (libpthread.so.0)
                                                 #1  0x00007efbff0be098 __GI___pthread_mutex_lock (libpthread.so.0)
                                                 #2  0x00007efbef5cfed1 n/a (libGLX.so.0)
                                                 #3  0x000056555b150a3f n/a (brave)
                                                 #4  0x0000565558735df5 n/a (brave)
                                                 #5  0x000056555a220eba n/a (brave)
                                                 #6  0x000056555a232361 n/a (brave)
                                                 #7  0x000056555a232167 n/a (brave)
                                                 #8  0x000056555a1ec5b8 n/a (brave)
                                                 #9  0x000056555a232d98 n/a (brave)
                                                 #10 0x000056555a20b4e5 n/a (brave)
                                                 #11 0x000056555a246f9e n/a (brave)
                                                 #12 0x000056555a282528 n/a (brave)
                                                 #13 0x00007efbff0bb6db start_thread (libpthread.so.0)
                                                 #14 0x00007efbf915588f __clone (libc.so.6)
                                                 
                                                 Stack trace of thread 9084:
                                                 #0  0x00007efbff0c19f3 futex_wait_cancelable (libpthread.so.0)
                                                 #1  0x000056555a27e872 n/a (brave)
                                                 #2  0x000056555a27efb9 n/a (brave)
                                                 #3  0x000056555a27ed9f n/a (brave)
                                                 #4  0x000056555a1ec5f5 n/a (brave)
                                                 #5  0x000056555a232d98 n/a (brave)
                                                 #6  0x000056555a20b4e5 n/a (brave)
                                                 #7  0x000056555a246f9e n/a (brave)
                                                 #8  0x000056555a282528 n/a (brave)
                                                 #9  0x00007efbff0bb6db start_thread (libpthread.so.0)
                                                 #10 0x00007efbf915588f __clone (libc.so.6)
                                                 
                                                 Stack trace of thread 2335:
                                                 #0  0x00007efbff0c1ed9 futex_reltimed_wait_cancelable (libpthread.so.0)
                                                 #1  0x000056555a27e9b0 n/a (brave)
                                                 #2  0x000056555a27ef90 n/a (brave)
                                                 #3  0x000056555a1ec60b n/a (brave)
                                                 #4  0x000056555a232d98 n/a (brave)
                                                 #5  0x000056555a20b4e5 n/a (brave)
                                                 #6  0x000056555a246f9e n/a (brave)
                                                 #7  0x000056555a282528 n/a (brave)
                                                 #8  0x00007efbff0bb6db start_thread (libpthread.so.0)
                                                 #9  0x00007efbf915588f __clone (libc.so.6)
                                                 
                                                 Stack trace of thread 2529:
                                                 #0  0x00007efbff0c19f3 futex_wait_cancelable (libpthread.so.0)
                                                 #1  0x000056555a27e872 n/a (brave)
                                                 #2  0x000056555a27efb9 n/a (brave)
                                                 #3  0x000056555a27ed9f n/a (brave)
                                                 #4  0x000056555a24344e n/a (brave)
                                                 #5  0x000056555a243ccb n/a (brave)
                                                 #6  0x000056555a243a54 n/a (brave)
                                                 #7  0x000056555a282528 n/a (brave)
                                                 #8  0x00007efbff0bb6db start_thread (libpthread.so.0)
                                                 #9  0x00007efbf915588f __clone (libc.so.6)
                                                 
                                                 Stack trace of thread 2235:
                                                 #0  0x00007efbf914a5d7 ioctl (libc.so.6)
                                                 #1  0x00007efbee37982c n/a (libnvidia-glcore.so.435.21)
                                                 #2  0x00007efbee37af47 n/a (libnvidia-glcore.so.435.21)
                                                 #3  0x00007efbee37bd50 n/a (libnvidia-glcore.so.435.21)
                                                 #4  0x00007efbedf8bf30 n/a (libnvidia-glcore.so.435.21)
                                                 #5  0x00007efbedf8dfc5 n/a (libnvidia-glcore.so.435.21)
                                                 #6  0x00007efbedfa453c n/a (libnvidia-glcore.so.435.21)
                                                 #7  0x00007efbedfa488e n/a (libnvidia-glcore.so.435.21)
                                                 #8  0x00007efbedf37a8b n/a (libnvidia-glcore.so.435.21)
                                                 #9  0x00007efbedeec607 n/a (libnvidia-glcore.so.435.21)
                                                 #10 0x00007efbef0498e7 n/a (libGLX_nvidia.so.0)
                                                 #11 0x00007efbef049ad5 n/a (libGLX_nvidia.so.0)
                                                 #12 0x00007efbef07dc58 n/a (libGLX_nvidia.so.0)
                                                 #13 0x00007efbef5ce212 n/a (libGLX.so.0)
                                                 #14 0x00007efbef5cff82 n/a (libGLX.so.0)
                                                 #15 0x000056555b187bd0 n/a (brave)
                                                 #16 0x000056555b0fcc37 n/a (brave)
                                                 #17 0x000056555b735b4d n/a (brave)
                                                 #18 0x000056555b7335fa n/a (brave)
                                                 #19 0x000056555810d983 n/a (brave)
                                                 #20 0x000056555810f3bb n/a (brave)
                                                 #21 0x000056555810b6a5 n/a (brave)
                                                 #22 0x000056555810c03b n/a (brave)
                                                 #23 0x000056555b221556 n/a (brave)
                                                 #24 0x000056555a220eba n/a (brave)
                                                 #25 0x000056555a232361 n/a (brave)
                                                 #26 0x000056555a232167 n/a (brave)
                                                 #27 0x000056555a1eca66 n/a (brave)
                                                 #28 0x00007efbfd1e3417 g_main_context_dispatch (libglib-2.0.so.0)
                                                 #29 0x00007efbfd1e3650 n/a (libglib-2.0.so.0)
                                                 #30 0x00007efbfd1e36dc g_main_context_iteration (libglib-2.0.so.0)
                                                 #31 0x000056555a1ec852 n/a (brave)
                                                 #32 0x000056555a232d98 n/a (brave)
                                                 #33 0x000056555a20b4e5 n/a (brave)
                                                 #34 0x000056555e1c8eb1 n/a (brave)
                                                 #35 0x0000565559dc48e6 n/a (brave)
                                                 #36 0x0000565559e1605c n/a (brave)
                                                 #37 0x0000565559dc3b31 n/a (brave)
                                                 #38 0x00005655577ff6ff ChromeMain (brave)
                                                 #39 0x00007efbf9055b97 __libc_start_main (libc.so.6)
                                                 #40 0x00005655572c136a _start (brave)
```

**Comment by rebron** [comment] 2020-04-17 15:06
Hi @Alan-Gomes Can you update to the latest 1.7.92 and let us know if it's stilll an issue?

**Comment by Alan-Gomes** [comment] 2020-04-17 16:16
Crash reporting was disabled, I enabled it and updated the browser to 1.7.92. I will see how it goes.

**Comment by Alan-Gomes** [comment] 2020-04-19 15:27
Updating the browser did not solve the problem, the crash occurred again

**Comment by btlechowski** [comment] 2020-04-21 12:09
It is weird that your whole system is freezing to the point that you need to restart the computer.

What processor do you have? How much ram do you have?

**Comment by Alan-Gomes** [comment] 2020-04-21 17:09
> It is weird that your whole system is freezing to the point that you need to restart the computer.
> 
> What processor do you have? How much ram do you have?

I have a AMD Ryzen 5 3600 processor with 16gb of ram and a GeForce RTX 2060 SUPER video card.

I am beginning to suspect that there may be something related to the video driver. I was using version 435 of the nvidia-driver, I upgraded to version 440 yesterday but the problem continued, now I'm testing the system without nvidia power saving:

`nvidia-settings -a "[gpu:0]/GpuPowerMizerMode=1"`

I'll keep giving updates.

**Comment by Zeroneca** [comment] 2020-04-22 12:09
I'm experiencing a similar issue, but not my complete system freezes, only Brave. After a few moments (something between 5 seconds and 5 minutes) the browser gets responsive again. 

I recognized this issue the first time about a week ago, when Netflix began to freeze, but sound continued to play.

WhatsApp Web freezes a lot of times when receiving messages (it gets worse, when the tab or the window with wa web open does not have focus). 
Those freezes appear quite random, but those two scenarios are the most prominent in my case.

I don't get any log output (will post if I get any).

I'm also using the nvidia driver, but also experienced freezes when running on Intel.

Meanwhile I need to use firefox, but I really would appreciate to be able to use Brave again!

**Comment by JFitzy1321** [comment] 2020-04-26 16:12
I'm having a similar problem on Pop!_0S 19.10. I don't have to completely reboot my system, but brave freezes a lot. Especially if I'm switching to it from another application.

**Comment by JFitzy1321** [comment] 2020-04-27 02:29
Problem seems to have resolved for me after disabling hardware acceleration.

**Comment by bsclifton** [comment] 2020-04-27 05:58
Based on details above, this issue seems possibly related to drivers or GPU

For folks experiencing hangs or freezing and you do NOT suspect driver/GPU, please check out https://github.com/brave/brave-browser/issues/9481

**Comment by aaronovz1** [comment] 2020-05-08 17:06
I am seeing a similar problem on the latest version of Brave, although it's been happening for a while, maybe even since versions 1.2 or 1.3. I experienced it on Ubuntu Mate 18.04 and 20.04 with Kernel versions 5.4 and 5.6. I am also using nVidia drivers 440. The problem happens quite often, with the entire browser locking up for a few seconds. It happens a lot when opening a new Tab or loading a new page.

Is there anything else I can do to provide more info?

> 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)
> --
> Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
> OS | Linux
> JavaScript | V8 8.1.307.32
> Flash | (Disabled)
> User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
> Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,PassiveMixedContentWarning,AutoupgradeMixedContent,WebUIDarkMode,MixedContentSiteSetting,SimplifyHttpsIndicator,DnsOverHttps --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,TextFragmentAnchor,LookalikeUrlNavigationSuggestionsUI,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,VideoPlaybackQuality --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync

**Comment by Alan-Gomes** [comment] 2020-05-12 01:06
After some tests, I finally solved the problem. It turns out that brave was not the root cause of the problem, instead it was just a symptom. I'm going to leave the solution here for future reference:

First, after looking on `/var/log/Xorg.0.log` I found this:
```
[  6270.576] (EE) NVIDIA(GPU-0): WAIT (2, 8, 0x8000, 0x0000fc50, 0x0000fc6c)
[  6277.576] (EE) NVIDIA(GPU-0): WAIT (1, 8, 0x8000, 0x0000fc50, 0x0000fc6c)
```

After [some research](http://forums.debian.net/viewtopic.php?f=6&t=143983) I tried disabling power saving mode for nvidia driver, I made a startup script for `nvidia-settings -a "[gpu:0]/GpuPowerMizerMode=1"` to be ran on every boot.

The freeze was partially solved, but the system began to be slow instead (and sometimes freezing again). I figured it out that the problem was on my NVMe SSD ([source](https://askubuntu.com/questions/1126456/wd-sandisk-nvme-m-2-stick-not-quite-working)) by the following logs:

```
print_req_error: I/O error, dev nvme0n1, sector 0
```

The solution was to add `nvme_core.default_ps_max_latency_us=5500` after `quiet splash` on `/etc/default/grub` (and running `sudo upate-grub` after that).

Now everything is working fine.

I don't know if I must close the issue, since there are other people with similar (but maybe not the same) problems.

**Comment by bsclifton** [comment] 2020-05-12 07:15
@Alan-Gomes huge thanks for finding your root cause and documenting the fix 😄 

I'll go ahead and close this out - but it should still come up just fine in searches! You can also edit your original post above and link down to your post with the solution so that more people find it 😄

**Closed by bsclifton** 2020-05-12 07:15 UTC
Labels: OS/Linux, gpu/driver
