### ISSUE TITLE
Crash Report Version 1.68.128 Chromium: 127.0.6533.73 (Official Build) (arm64)

### ISSUE THREAD

**Issue by danielfstefan** [brave/brave-browser#40077] opened 2024-07-29 15:15 UTC
I did an update this morning and after that update it started crashing randomly, sometimes after a few seconds, sometimes minutes, at some point I managed to have a few hours of work done, and then it crashed during a Google Meet call and since then it kept crashing and crashing... I can't even keep it open long enough to save all the tabs I had open. 

At some point I managed to uninstall the last extension I installed today, and some others that were mainly deactivated, but that didn't seem to have any effect. 

Brave Version: 1.68.128 Chromium: 127.0.6533.73
Operating System: Mac OS X 14.5.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open the Brave Browser
2. Sometimes it just crashes
3. Sometimes it takes switching from one tab no another
4. Sometimes I get more time and it crashes in the middle of a Google Meet call
5. It just crashed 5 times while trying to send this report ...

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/22b30000-3daa-5d0c-0000-000000000000

**Comment by kjozwiak** [comment] 2024-07-29 21:39
Crash stack from `22b30000-3daa-5d0c-0000-000000000000`:

```
[ 00 ] base::OnceCallback<void (unsigned long long)>::Run(unsigned long long) && ( immediate_crash.h:176 )
[ 01 ] ChromeBrowsingDataRemoverDelegate::OnTaskComplete(ChromeBrowsingDataRemoverDelegate::TracingDataType, unsigned long long, base::TimeTicks, bool) ( chrome_browsing_data_remover_delegate.cc:1506 )
[ 02 ] base::OnceCallback<void ()>::Run() && ( callback.h:156 )
[ 03 ] base::internal::PostTaskAndReplyRelay::RunReply(base::internal::PostTaskAndReplyRelay) ( post_task_and_reply_impl.h:63 )
[ 04 ] void base::internal::DecayedFunctorTraits<void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&>::Invoke<void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay>(void (*&&)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&) ( bind_internal.h:671 )
[ 05 ] void base::internal::InvokeHelper<false, base::internal::FunctorTraits<void (*&&)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&>, void, 0ul>::MakeItSo<void (*)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>>(void (*&&)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>&&) ( bind_internal.h:930 )
[ 06 ] void base::internal::Invoker<base::internal::FunctorTraits<void (*&&)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&>, base::internal::BindState<false, true, false, void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay>, void ()>::RunImpl<void (*)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>, 0ul>(void (*&&)(base::internal::PostTaskAndReplyRelay), std::__Cr::tuple<base::internal::PostTaskAndReplyRelay>&&, std::__Cr::integer_sequence<unsigned long, 0ul>) ( bind_internal.h:1067 )
[ 07 ] base::internal::Invoker<base::internal::FunctorTraits<void (*&&)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay&&>, base::internal::BindState<false, true, false, void (*)(base::internal::PostTaskAndReplyRelay), base::internal::PostTaskAndReplyRelay>, void ()>::RunOnce(base::internal::BindStateBase*) ( bind_internal.h:980 )
[ 08 ] base::OnceCallback<void ()>::Run() && ( callback.h:156 )
[ 09 ] base::TaskAnnotator::RunTaskImpl(base::PendingTask&) ( task_annotator.cc:203 )
[ 10 ] void base::TaskAnnotator::RunTask<base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*)::$_3>(perfetto::StaticString, base::PendingTask&, base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*)::$_3&&) ( task_annotator.h:90 )
[ 11 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) ( thread_controller_with_message_pump_impl.cc:484 )
[ 12 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:346 )
[ 13 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:0 )
[ 14 ] base::OnceCallback<void ()>::Run() && ( callback.h:156 )
[ 15 ] base::TaskAnnotator::RunTaskImpl(base::PendingTask&) ( task_annotator.cc:203 )
[ 16 ] void base::TaskAnnotator::RunTask<base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*)::$_3>(perfetto::StaticString, base::PendingTask&, base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*)::$_3&&) ( task_annotator.h:90 )
[ 17 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) ( thread_controller_with_message_pump_impl.cc:484 )
[ 18 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:346 )
[ 19 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:0 )
[ 20 ] base::MessagePumpCFRunLoopBase::RunWork() ( message_pump_apple.mm:449 )
[ 21 ] invocation function for block in base::MessagePumpCFRunLoopBase::RunWorkSource(void*) ( message_pump_apple.mm:421 )
[ 22 ] base::apple::CallWithEHFrame(void () block_pointer)
[ 23 ] 0x1a9465030
```

**Comment by bsclifton** [comment] 2024-08-06 00:02
Looks to be the same root cause as https://github.com/brave/brave-browser/issues/40102 

I'll close this one as a duplicate. @danielfstefan please follow that issue for updates 😄

**Closed** 2024-08-06 00:02 UTC
Labels: closed/duplicate, crash, OS/macOS, priority/P2
