### ISSUE TITLE
rewards panel displaying incorrect publishers or none in certain cases when using Twitter

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#8289] opened 2020-02-18 00:27 UTC
## Description 

We've received several reports from the community mentioning that the `Rewards` panel sometimes displays and incorrect publisher in certain cases. In one of the examples, the user was seeing https://twitter.com/BrendanEich in the panel when viewing their DMs on Twitter.

There's also some cases where there's nothing appearing in the panel when viewing the panel. I've personally ran into this and have a Nightly that's experiencing this particular issue.

Possible related https://github.com/brave/brave-browser/issues/5580 which was an issue in the past but was never really addressed as QA and others couldn't reproduce. Assumed it was fixed by proxy by another issue.

## Steps to Reproduce

We'll need some information from the user experiencing this issue. I've tried reproducing a few times using `1.3.116 CR: 80.0.3987.106` without any luck. However, I did run into a case where my Nightly isn't displaying any publishers in the panel. I'll add STR once we have more info.

## Actual result:

<img width="787" alt="Screen Shot 2020-02-17 at 7 12 05 PM" src="https://user-images.githubusercontent.com/2602313/74693368-99d69d00-51b9-11ea-9a99-96efb96604f5.png">

![image (1)](https://user-images.githubusercontent.com/2602313/74693549-3a2cc180-51ba-11ea-8c8b-4c56915934be.png)

<img width="1396" alt="Screen Shot 2020-02-17 at 7 19 07 PM" src="https://user-images.githubusercontent.com/2602313/74693600-6b0cf680-51ba-11ea-887c-c03c71a291aa.png">

## Expected result:

<img width="1288" alt="Screen Shot 2020-02-17 at 7 10 04 PM" src="https://user-images.githubusercontent.com/2602313/74693375-9fcc7e00-51b9-11ea-9e42-6a1f97460bf5.png">

<img width="1020" alt="Screen Shot 2020-02-17 at 7 18 34 PM" src="https://user-images.githubusercontent.com/2602313/74693573-516baf00-51ba-11ea-8d7c-7e90e2d0d44d.png">

## Reproduces how often: 

We'll need some more info/investigation to find STR so we can gauge how often this happens.

## Brave version (brave://version info)

Brave | 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.15.3 (Build 19D76)

Brave | 1.6.36 Chromium: 80.0.3987.106 (Official Build) nightly (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | macOS Version 10.15.3 (Build 19D76)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `not 100% sure`
- Can you reproduce this issue with the dev channel? `not 100% sure`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

## Miscellaneous Information:

CCing @NejcZdovc @rebron @jonathansampson @yachtcaptain23 @BrendanEich @brave/legacy_qa

**Comment by kjozwiak** [comment] 2020-02-18 00:31
Another example of publishers not being displayed/appearing in the `Rewards` panel.

![emptyPanelTwitter](https://user-images.githubusercontent.com/2602313/74693947-03f04180-51bc-11ea-9c92-bec617385efe.gif)

**Comment by StephenTurley** [comment] 2020-02-18 00:36
Hi, I'm the user in the first screenshot. Here is my info:

Brave | 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Linux
JavaScript | V8 8.0.426.16
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --disable-sync --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,AllowPopupsDuringPageUnload,NotificationTriggers,WebXR,AudioServiceOutOfProcess,SmsReceiver,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service

**Comment by StephenTurley** [comment] 2020-02-18 00:56
I'm unable to reproduce this on my other computer for some reason. Looks like the same version of Brave. Bug is present on PopOs/Gnome3 but not Manjaro/XFCE

Brave | 1.3.115 Chromium: 80.0.3987.87 (Official Build) unknown (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Linux
JavaScript | V8 8.0.426.16
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
Command Line | /usr/lib/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --disable-sync --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,NotificationTriggers,AllowPopupsDuringPageUnload,WebXR,LookalikeUrlNavigationSuggestionsUI,SmsReceiver,AudioServiceOutOfProcess,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service

**Comment by bsclifton** [comment] 2020-03-16 16:06
Seems to be working after https://github.com/brave/brave-core/pull/4948 was merged - will retest once we have a beta

**Comment by kjozwiak** [comment] 2020-03-16 21:09
> Seems to be working after [brave/brave-core#4948](https://github.com/brave/brave-core/pull/4948) was merged - will retest once we have a beta

Seems like this is still happening. I can reproduce on my local profile using `1.8.12 CR: 80.0.3987.132` which includes https://github.com/brave/brave-core/pull/4948. When we had https://github.com/brave/brave-core/pull/4948 present in `1.7.x` and `1.8.x`, the reward panel wasn't working on most publishers which is working now 👍 However, Twitter still has the same problem. @bsclifton you were probably seeing the rewards panel being broken because of https://github.com/brave/brave-core/pull/4948.

**Comment by jonathansampson** [comment] 2020-03-18 19:14
I just checked in Nightly (1.8.22) and was able to get bad results. I started by going to twitter.com/jonathansampson, and then clicked to visit another profile from there. The rewards state for "jonathansampson" was displayed on the next profile:

![image](https://user-images.githubusercontent.com/815158/76998214-b124b980-6922-11ea-86be-879684aee12a.png)

**Closed** 2020-04-06 13:02 UTC
Labels: QA/Yes, bug, feature/rewards, priority/P2

**Comment by LaurenWags** [comment] 2020-05-01 13:05
@emerick there really aren't good STR in the issue description, seems like solid ones were never found. Could you offer any guidance on a test plan? If not, is a general regression test of Twitter tipping sufficient? cc @kjozwiak @rebron

**Comment by emerick** [comment] 2020-05-01 13:59
@LaurenWags Yeah this was a tough one to test and it seemed to be an intermittent issue at best. I think a general regression test of Twitter is definitely sufficient, perhaps focusing on multiple tabs.

**Comment by btlechowski** [comment] 2020-05-14 04:00
Verification passed on

Brave | 1.9.63 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Verified clicking around twitter users shows proper user name in the Rewards Panel. Started with `twitter.com/jonathansampson` and `https://twitter.com/BrendanEich`
Verified different twitter users in different tabs
Verified different twitter users in different windows.

Noticed that it takes some time to load rewards verified status for a twitter user, especially after restart
