### ISSUE TITLE
BAP & Shields tooltip overlap on each other 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14158] opened 2021-02-15 13:53 UTC
## Description 
BAP & Shields tooltip overlap on each other 

## Steps to reproduce 
Pre-requisite: Device should be set to JP as the bug is region specific

   1. Install 1.20.x nightly build 
   2. Visit any page to trigger shields modal 
   3. Upgrade to 1.22.41 x64 nightly build
   4. Launch browser, page loads
   5. BAP modal is shown and when page load completes, shields tooltip is shown overlapping BAP message

## Actual result 
<img width=400 src=![image](https://user-images.githubusercontent.com/17010094/107954938-0a62f600-6f95-11eb-8458-ff1a59951e57.png>

## Expected result
Should show only one tooltip at a time. Closing one should trigger the other

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.22.24 x64 Nightly build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Similar Desktop bug #14108

**Comment by kjozwiak** [comment] 2021-02-16 17:39
Added `release-blocking` as we'll want to include this in `1.20.x - Release #2` after speaking with @deeppandya and @miyayes.

**Comment by deeppandya** [comment] 2021-02-17 16:56
the issue is fixed in https://github.com/brave/brave-core/pull/7985/commits/8622599bd0f8444028150e25c10cec0d1d937d1c

**Comment by kjozwiak** [comment] 2021-02-17 22:11
Closing as this was fixed as per https://github.com/brave/brave-browser/issues/14158#issuecomment-780698020.

**Closed by kjozwiak** 2021-02-17 22:11 UTC
Labels: OS/Android, QA/Yes, bug, feature/rewards, release-notes/exclude, release/blocking

**Comment by kjozwiak** [comment] 2021-02-26 20:21
Moving this into `1.22.x` as the BAP work is being reverted via https://github.com/brave/brave-core/pull/8088. Once we have more information next week, we'll re-revert https://github.com/brave/brave-core/pull/8088 and move everything back into `1.21.x` and release `1.21.x - Release #2`.

**Comment by srirambv** [comment] 2021-03-11 12:22
This is not a valid issue anymore. Tooltip was to be shown only till March 6 which means tooltips won't show up anymore. Marking as `QA/No` 

cc: @Miyayes @deeppandya @brave/legacy_qa
