### ISSUE TITLE
Brave doesn't relaunch via taskbar Brave icon, after closing, if VPN is configured and Shields is enabled

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#32309] opened 2023-08-16 20:09 UTC
## Description 

Brave doesn't open after closing via taskbar Brave icon if VPN is configured and Shields is enabled.  Brave successfully relaunched once Shields is disabled on the VPN subscription page. 

## Steps to Reproduce

1. Install 1.57.47
2. launch Brave
3. click VPN button >> Already purchased VPN button 
4. connect to VPN via VPN panel
5. close Brave
6. click Brave icon in the task bar to relaunch
7. it spins but Brave doesn't open/launch
8. open taskbar and end task for Brave browser background processes
9. click Brave icon in the taskbar and launch Brave
10. disable VPN in the VPN panel and close the browser
11. Brave doesn't relaunch
12. follow step 8 and terminate background processes from Brave browser
13. click Brave icon in the taskbar and launch Brave
14. turned Shield down for VPN subscription page
14. close the browser

## Actual result:

 If VPN is configured and Shields Up, Brave doesn't relaunch after closing.  However, if Shields is down for VPN subscription page, Brave launch is successful via taskbar Brave icon after closing. 
 
 

https://github.com/brave/brave-browser/assets/98358127/7a68517b-1728-4b50-bd90-cbe2ccd6db89

 
 
 
## Expected result:
Brave should relaunch successfully when Shields is enabled. 

## Reproduces how often: 

Easily 

## Brave version (brave://version info)

```
Brave | 1.57.47 Chromium: 116.0.5845.96 (Official Build) (64-bit)
-- | --
Revision | 180d2fdf443f9be410c38fd8c4ccfe7e99ea2b16
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@clifton @spylogsster 
cc: @stephendonner

**Comment by stephendonner** [comment] 2023-08-17 05:47
Sadly, can confirm this with 

```
Brave | 1.57.47 Chromium: 116.0.5845.96 (Official Build) (64-bit)
-- | --
Revision | 180d2fdf443f9be410c38fd8c4ccfe7e99ea2b16
OS | Windows 10 Version 22H2 (Build 19045.3324)
```

cc @rebron @kjozwiak @LaurenWags as a heads-up

![issue-32309](https://github.com/brave/brave-browser/assets/387249/230f50ee-cb04-4e4e-980d-08683cd124d2)


Nice find, @MadhaviSeelam

**Comment by stephendonner** [comment] 2023-08-17 05:48
also cc @mattmcalister so he's aware

**Comment by spylogsster** [comment] 2023-08-17 05:57
Looks like Nightly and Beta works fine, can someone else confirm? thanks

**Comment by spylogsster** [comment] 2023-08-17 05:58
it would be great to get some logs if possible, launch browser with `--enable=logging=stderr --v=1`

**Comment by MadhaviSeelam** [comment] 2023-08-18 17:03
Verification `In progress` using 
```
Brave | 1.59.28 Chromium: 116.0.5845.96 (Official Build) nightly (64-bit)
-- | --
Revision | c5f495e1d4d870a7622249b14df7fa33a9e862b8
OS | Windows 11 Version 22H2 (Build 22621.2134)
```
Verified using STR from the description https://github.com/brave/brave-browser/issues/32309#issue-1853839526. 

### Confirmed Brave relaunch is successful as expected. 

Verified with both brave://flags/#brave-vpn-wireguard enabled and disabled.  

brave://flags/#brave-vpn-wireguard - Enabled (Default)
https://github.com/brave/brave-browser/assets/98358127/c712bad1-154c-416a-93ed-1d0d878b3d4c


brave://flags/#brave-vpn-wireguard - Disabled
https://github.com/brave/brave-browser/assets/98358127/358da32f-882c-49d0-9dc6-9e7d3c825d19

**Comment by kjozwiak** [comment] 2023-08-21 21:07
Closing the above as https://github.com/brave/brave-core/pull/19735 was merged directly into `1.57.x` as @MadhaviSeelam couldn't reproduce the issue on `BETA` nor `Nightly`.

**Comment by kjozwiak** [comment] 2023-08-21 21:07
The above requires `1.57.52` or higher for `1.57.x` verification 👍

**Closed by kjozwiak** 2023-08-21 21:07 UTC
Labels: bug, QA/Yes, release-notes/include, OS/Desktop, feature/vpn

**Comment by MadhaviSeelam** [comment] 2023-08-22 16:04
Verification `PASSED` using
```
Brave | 1.57.52 Chromium: 116.0.5845.96 (Official Build) (64-bit)
-- | --
Revision | 1f876d1266f048189d3cc887cfa5208508ac8194
OS | Windows 11 Version 22H2 (Build 22621.2134)
```
Verified using original STR from https://github.com/brave/brave-browser/issues/32309#issue-1853839526

Confirmed as an existing user: 
- after connecting to VPN via VPN panel and closing, successfully relaunched Brave via taskbar Brave icon
- after disconnecting VPN and closing, successfully relaunched Brave via taskbar Brave icon
- after connecting to VPN, disabling shields and closing, successfully relaunched Brave via taskbar Brave icon


example | example 
--- | ----
<img width="946" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/1a1d83fd-c76c-45a6-8335-69b2d6ce1718">|<img width="948" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6e328926-ed68-4c18-96d5-e6f7a0749775">

**Comment by stephendonner** [comment] 2023-08-22 16:41
## Verification `IN-PROGRESS` using 

```
Brave | 1.57.52 Chromium: 116.0.5845.96 (Official Build) (64-bit)
-- | --
Revision | 1f876d1266f048189d3cc887cfa5208508ac8194
OS | Windows 10 Version 22H2 (Build 19045.3324)
```

**Comment by stephendonner** [comment] 2023-08-22 17:24
## Verified `IN-PROGRESS` using

```
Brave | 1.57.47 Chromium: 116.0.5845.96 (Official Build) (x86_64)
-- | --
Revision | 180d2fdf443f9be410c38fd8c4ccfe7e99ea2b16
OS | macOS Version 11.7.9 (Build 20G1426)
```
