### ISSUE TITLE
Unable to use Hangouts Extensions

### ISSUE THREAD

**Issue by carn1x** [brave/brave-browser#2638] opened 2018-12-19 08:58 UTC
## Steps to Reproduce

   1. Install Hangouts Chrome extension
   2. Press the Hangouts chrome extension button, observe Sign In button
   3. Press signing button, observe new window appears with URL https://hangouts.google.com/webchat/blank?pli=1#Email=user@gmail.com . However the page is blank. No errors in the JS console. Same result if the page is reloaded with Shields DOWN.

## Actual result:
* Unable to sign in to Hangouts

## Expected result:
* Sign in popup shows a page to signin, or uses the existing browser session already signed into google.

## Reproduces how often: 
* Everytime

## Brave version (brave://version info)

Brave | 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Linux

(Same observed on OSX)

### Reproducible on current release:
- Unable to test currently

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  **No**
- Is the issue reproducible on the latest version of Chrome?  **No**

**Comment by rebron** [comment] 2019-01-08 18:10
Looks like a dupe of https://github.com/brave/brave-browser/issues/1982?

**Comment by rebron** [comment] 2019-01-08 20:06
Dupe of #1982 and landed in 60.x

**Closed by rebron** 2019-01-08 20:06 UTC
