### ISSUE TITLE
Brave 1.65.114 freezes on startup on Linux

### ISSUE THREAD

**Issue by RoguedBear** [brave/brave-browser#37716] opened 2024-04-19 06:22 UTC
## Description 
After updating to brave `1.65.114` from `1.64.122` pushed via apt, brave does not open any gui window & freezes until killed manually.

After rolling back to `1.64.122` brave is working normally

## Steps to Reproduce

   1. upgrade to `1.65.114` via apt
   2. launch brave

## Actual result:
- using cli to launch to show the logs
- when the recording turns black, brave starts to produce visual glitches

https://github.com/brave/brave-browser/assets/39442192/5b3abf42-da47-48e8-b99e-c6df8261c486

https://github.com/brave/brave-browser/assets/39442192/5a0d2277-1747-4987-8a87-595cf6428c6b

## Expected result:
(after downgrading)

https://github.com/brave/brave-browser/assets/39442192/c23ea018-ffd9-46ca-82ce-a6e50a0308f0

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

NA / brave doesnt open

### OS Info
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

$ uname -a
Linux FireFly 6.5.0-27-generic #28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 15 10:51:06 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:
Logs:
- ### Logs from `1.65.114`
```
$ brave-browser
[200426:200426:0419/105717.684979:ERROR:chrome_browser_cloud_management_controller.cc(161)] Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.
[200426:200426:0419/105717.820439:ERROR:profile_attributes_storage.cc(1033)] Failed to PNG encode the image.
[200426:200426:0419/105722.262371:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[200426:200426:0419/105727.735507:ERROR:sharing_service.cc(221)] Device registration failed with fatal error
[200426:200426:0419/105819.672845:ERROR:topics_fetcher.cc(111)] Failed to get topics: 0, 
^C
```

- ### Logs from `1.64.122`
```
$ brave-browser
[211608:211608:0419/111016.624796:ERROR:policy_logger.cc(157)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(161) Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.
[211608:211608:0419/111016.698431:ERROR:profile_attributes_storage.cc(1033)] Failed to PNG encode the image.
[211608:211608:0419/112458.433051:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
```

**Comment by Humandoodlebug** [comment] 2024-04-19 07:38
Seeing the same issue on Arch Linux - downgrading also "fixed" the problem for me.

**Comment by Finoderi** [comment] 2024-04-20 06:47
Same issue on Gentoo.

```
$ brave-bin
[4140:4140:0420/104446.538446:ERROR:chrome_browser_cloud_management_controller.cc(161)] Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.
[4140:4140:0420/104446.580639:ERROR:profile_attributes_storage.cc(1033)] Failed to PNG encode the image.
[0420/104446.760567:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0420/104446.760694:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0420/104446.761850:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0420/104446.763324:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0420/104446.767614:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0420/104446.767704:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0420/104446.769006:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[4140:4140:0420/104446.747927:ERROR:check.cc(375)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[4140:4140:0420/104446.808201:ERROR:check.cc(375)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[4140:4140:0420/104446.809825:ERROR:check.cc(375)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[4140:4140:0420/104446.811198:ERROR:check.cc(375)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[4140:4140:0420/104446.812666:ERROR:check.cc(375)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[4140:4140:0420/104446.814456:ERROR:check.cc(375)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[4140:4140:0420/104446.816135:ERROR:check.cc(375)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[4140:4140:0420/104446.817359:ERROR:check.cc(375)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[4140:4140:0420/104446.824316:ERROR:check.cc(375)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[4140:4140:0420/104446.826155:ERROR:check.cc(375)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[4140:4140:0420/104446.828243:ERROR:check.cc(375)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[4140:4140:0420/104447.910634:ERROR:sharing_service.cc(221)] Device registration failed with fatal error
```

**Comment by IkelAtomig** [comment] 2024-04-22 01:09
Same thing on Fedora Linux too.

**Comment by matburnx** [comment] 2024-04-22 08:13
I've got the same problem on Pop OS 22.04, but I also get the same errors when launching Chromium 124.0.6367.60, so it may not be Brave-related.

**Comment by jcberquist** [comment] 2024-04-22 22:05
@matburnx: I think you are right regarding the issue being related to the Chromium version, looks like there is an bug report there for this issue: https://issues.chromium.org/u/1/issues/329678163

**Comment by defunctl** [comment] 2024-04-23 22:20
It looks like they now marked that issue as fixed: https://issues.chromium.org/u/1/issues/329678163#comment50 

Although I'm not sure which version of Chromium the fix is going out in.

**Comment by Finoderi** [comment] 2024-04-25 10:51
It looks like Brave devs cannot be bothered at all to test new builds for linux. It's not the first time even for the last year when an update makes the browser completely unusable on linux.

**Comment by IkelAtomig** [comment] 2024-04-26 04:51
It's been fixed - https://brave.com/latest/.

**Comment by RoguedBear** [comment] 2024-04-26 06:58
can confirm, this is working now in `1.65.122 `.

wow, didn't realise this was a duplicate of #37498

**Comment by defunctl** [comment] 2024-04-26 16:04
Note that setting the ozone platform hint to `auto` or `wayland` via `brave://flags` no longer works, it shows the Ozone platform as `x11` and not `wayland`.

![image](https://github.com/brave/brave-browser/assets/1066195/92d54873-b731-4f8a-9890-9c4b1a3e1e17)

To actually force the ozone platform to wayland, you must now pass this command line argument to the brave executable directly, e.g. `brave --ozone-platform=wayland`

Then the Ozone platform correctly shows `wayland`:

![image](https://github.com/brave/brave-browser/assets/1066195/3da1958d-2de8-4f14-ad3e-8488f289bfd6)

**Comment by bsclifton** [comment] 2024-05-20 23:25
Closing as duplicate of https://github.com/brave/brave-browser/issues/37498 and https://github.com/brave/brave-browser/issues/37860

**Closed by bsclifton** 2024-05-20 23:25 UTC
Labels: bug, closed/duplicate, OS/Linux, perf, OS/Desktop
