### ISSUE TITLE
"Don't ask again" checkbox for caret browsing doesn't always work

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#36858] opened 2024-03-15 21:39 UTC
## Description 

Some users are seeing that when they enable caret browsing (`F7`), the browser prompts them as to whether or not they want to enable caret browsing. However, if the user selects the the prompt always displays, even when the user selects the `Don't show this message again` checkbox.

![image](https://github.com/brave/brave-browser/assets/3299098/70ddbd55-5dcd-44d3-8703-c7d86d6b1248)

It is unclear why users are stuck in this state. Testing on my end in Windows 10, I'm able to select the checkbox, hit `F7` again and I do not see the prompt (caret browsing simply enables/disables itself). 

## Steps to Reproduce

   1. Open Brave
   2. Press `F7` to enable caret browsing and view prompt
   3. Check `Don't ask me again` box, then `Turn on`

## Actual result:

Prompt appears every time

## Expected result:
Prompt shouldn't appear if box is checked

## Reproduces how often: 

Always (for user)

## Brave version (brave://version info)

v1.63.174

## Version/Channel Information:

- Can you reproduce this issue with the current release? Y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

User report: https://community.brave.com/t/on-off/537709/2

**Comment by MadhaviSeelam** [comment] 2024-03-18 19:58
Couldn't reproduce the issue in Win 11 
```
Brave | 1.63.174 Chromium: 122.0.6261.128 (Official Build) (64-bit)
-- | --
Revision | 0d369d4e1dfee7bcea82774079dc8cd658746c98
OS | Windows 11 Version 23H2 (Build 22631.3296)
```

**Comment by Szyymas** [comment] 2024-03-19 18:26
Everything works fine for me on Win 10
```
Brave: 1.63.174 Chromium: 122.0.6261.128 (Official Build) (64-bit) 
Revision: 0d369d4e1dfee7bcea82774079dc8cd658746c98
OS: Windows 10 Version 22H2 (Build 19045.4170)
```

**Comment by Szyymas** [comment] 2024-03-19 18:35
Everything works fine for me on Win 10
`Brave: 1.63.174 Chromium: 122.0.6261.128 (Official Build) (64-bit)`

**Comment by bsclifton** [comment] 2024-03-20 19:57
The value isn't saved if you click `Cancel`. Usually, the preference in these cases is only saved if you click the big orange button (cancel doesn't usually save).

I'll close this issue out as expected; if we want to save it, we could present another option - `Keep off` and then have it save that setting.

**Closed by bsclifton** 2024-03-20 19:57 UTC
Labels: bug, feature/user-interface, needs-investigation, OS/Windows, OS/Desktop

**Comment by b-hayes** [comment] 2024-12-31 03:14
This is still a problem. Dont ask again does not work for cancel. I never want it on just want it to ignore f7.
