### ISSUE TITLE
[Android] Searches appearing in top sites

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#29093] opened 2023-03-15 19:03 UTC
## Description
We are receiving a large number of reviews complaining that searches are appearing in the NTP top sites and search suggestions.

Seems to be introduced in 1.49.122 and looks like an upstream update since the behavior is the same in Chrome.

### Review Examples
https://appfigures.com/reviews/266342430751LShd9FX3IFAdGeLcGSP8nmA?lang=en
https://appfigures.com/reviews/266342430751Llds5Dqm9-g63DeIaLG9UJA?lang=en
https://appfigures.com/reviews/266342430751LyViouNUuIDZ61GAGBqRx6w
https://appfigures.com/reviews/266342430751LbN4wtKYxMUtW3a27fEVdJQ?lang=en

### Screenshots

**Brave 1.49.122**
![image](https://user-images.githubusercontent.com/28269287/225415648-aff8cf63-9556-4ed0-849c-20ab800d9536.png)

**Chrome 111.0.5563.58**
![image](https://user-images.githubusercontent.com/28269287/225415825-a7f4b6e7-8eed-4e1a-bdd5-935ddf75b4a9.png)

**Comment by HunterMeyer** [comment] 2023-03-19 11:24
I can report this is happening to me too. The search listings are often neither frequent nor recent searches.

Sometimes when I long press > remove one search result from the Top Sites section all of them will disappear - but this is infrequent.

**Comment by marcvangend** [comment] 2023-03-21 21:44
I'm seeing the same behavior and I can also reproduce it with a fresh install of Brave Nightly ("Brave - Nightly 1.51.51, Chromium 112.0.5615.29"). My device is a Pocofone F1 running Android 12.

#29124 is a duplicate of this issue.

**Closed** 2023-03-29 11:51 UTC
Labels: QA/Yes, release-notes/exclude, OS/Android

**Comment by kjozwiak** [comment] 2023-04-03 05:22
@brave/qa-team can also use the STR/Cases that I used to verify the above on `master` before uplifting via https://github.com/brave/brave-core/pull/17802#issuecomment-1493678607.

**Comment by kjozwiak** [comment] 2023-04-04 02:56
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.50.112 Chromium: 112.0.5615.49 (Official Build) (32-bit)
--- | ---
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Android 13; Build/TQ2A.230305.008.E1
```

**`Clean Install Test Case`**

* ensured that searches are not appearing via `Top Sites` under the NTP
* ensured that websites are still being added into `Top Sites` without any issues
* ensured that you can still swipe left/right and navigate the `Top Sites` widget via the NTP
* ensured that you can remove `Top Sites` from the NTP without any issues

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|-----------------
![Screenshot_20230403-202915](https://user-images.githubusercontent.com/2602313/229674445-ff26c9da-8720-4b33-b2d2-1550e17582a8.png) | ![Screenshot_20230403-202926](https://user-images.githubusercontent.com/2602313/229674462-d0d1bd6a-a987-4807-ad96-dad2c25c045c.png) | ![Screenshot_20230403-224103](https://user-images.githubusercontent.com/2602313/229674547-79996939-a1b1-4510-88cb-9e7dca92ef97.png)

**Upgrade from `1.49.132 Chromium: 111.0.5563.147` -> `1.50.112 Chromium: 112.0.5615.49` Test Case**

* reproduced the issue using `1.49.132 Chromium: 111.0.5563.147` and added several searches into `Top Sites` via NTP
* ensured that the search entries were removed from `Top Sites` after upgrading to `1.50.112 Chromium: 112.0.5615.49`
* ensured that previously added websites are not being removed from `Top Sites` (only searches)
* ensured that websites are still being added into `Top Sites` without any issues
* ensured that you can still swipe left/right and navigate the `Top Sites` widget via the NTP
* ensured that you can remove `Top Sites` from the NTP without any issues

**`Example`** | **`Example`** 
---------------|----------------
![Screenshot_20230403-224621](https://user-images.githubusercontent.com/2602313/229675195-06543921-f0eb-4290-b425-c1f15df30b14.png) | ![Screenshot_20230403-224722](https://user-images.githubusercontent.com/2602313/229675201-58ccab55-27ac-40fa-bfbd-e2f88c83a6a0.png)
