### ISSUE TITLE
[Desktop] Ubuntu 20.04 horizontal lines on YouTube videos

### ISSUE THREAD

**Issue by ypitrey** [brave/brave-browser#10237] opened 2020-06-12 11:18 UTC
## Description 
YouTube videos are displayed in Brave with horizontal line artifacts at the bottom of the screen on Ubuntu 20.04. This happens both in fullscreen and when the player isn't in fullscreen. My system is up to date (did an auto update a couple of days ago). I'm using a Lenovo Thinkpad Yoga from about 2014, connected to a TV using a mini HDMI to HDMI cable. YouTube videos are displayed without any issues in Firefox on the same setup.

## Steps to Reproduce
   1. Open a youtube video in Brave on Ubuntu 20.04.
   2. See horizontal lines at the bottom of the screen, which shouldn't be there.
   3. Report issue on Github.

## Actual result:
See screen capture for an example.
![Screenshot from 2020-06-12 12-58-39](https://user-images.githubusercontent.com/17247240/84497018-4af3cc80-acae-11ea-83b0-92348877d24e.png)

## Expected result:
There should be no horizontal lines at the bottom of the screen.

## Reproduces how often: 
Every time I open a youtube video. I have tried restarting the computer to no effect.

## Brave version (brave://version info)
```

Brave | 1.9.80 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Linux
JavaScript | V8 8.1.307.32
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning,SimplifyHttpsIndicator,MixedContentSiteSetting,DnsOverHttps --disable-features=TextFragmentAnchor,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication,AudioServiceOutOfProcess,SmsReceiver,NotificationTriggers,VideoPlaybackQuality --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/livingroom/.config/BraveSoftware/Brave-Browser/Default
```

**Comment by ajaichemmanam** [comment] 2020-06-13 11:00
Duplicate #10223

**Comment by srirambv** [comment] 2020-06-15 11:45
Closing as dupe of #10223

**Closed by srirambv** 2020-06-15 11:45 UTC
Labels: OS/Desktop
