### ISSUE TITLE
Ads received this month isn't updating on brave://rewards in Ads panel

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12944] opened 2020-11-30 16:02 UTC
## Description 

"Ads received this month" is showing 0 however I have viewed a NTP SI image and an ad notification.

## Steps to Reproduce

   1. Clean install 1.19.x
   2. Enable Ads (I used NTP widget)
   3. Watch logs, wait for all items to load
   4. View an NTP SI.
   5. Browse a few sites
   6. Get ad notification 
   7. Navigate to brave://rewards

## Actual result:

Panel shows 0 for Ads received this month, but there is a 7-day ads history link. If you click on that, you can see what I viewed.
<img width="678" alt="Screen Shot 2020-11-30 at 10 56 32 AM" src="https://user-images.githubusercontent.com/28145373/100632670-1d055180-32fb-11eb-86d2-965f74114f01.png">
<img width="953" alt="Screen Shot 2020-11-30 at 10 56 24 AM" src="https://user-images.githubusercontent.com/28145373/100632671-1ecf1500-32fb-11eb-9db8-bb06cc67520f.png">

## Expected result:
Ads received this month should be showing 2 in the above scenario. 

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.19.39 Chromium: 87.0.4280.67 (Official Build) nightly (x86_64)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | macOS Version 10.15.7 (Build 19H15)

Also reproduces on M1 macOS laptop

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, 1.17.x
- Can you reproduce this issue with the beta channel? unsure 1.18.x
- Can you reproduce this issue with the nightly channel? yes 1.19.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @tmancey @jsecretan @brave/legacy_qa

**Comment by tmancey** [comment] 2020-12-04 07:48
Closing as a duplicate of https://github.com/brave/brave-browser/issues/12946

**Closed by tmancey** 2020-12-04 07:48 UTC
Labels: OS/Desktop, QA/Yes, feature/ads, regression, release/blocking

**Comment by GeetaSarvadnya** [comment] 2020-12-23 16:36
Verification passed on

```

Brave | 1.19.66 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.685)

```
Testing is covered in https://github.com/brave/brave-browser/issues/12946#issuecomment-750027656
