### ISSUE TITLE
Have a section in chrome://settings for Crypto Wallets

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13687] opened 2021-01-20 19:57 UTC
The extensions section of brave://settings is overused and cluttered. It would be nice to have all Crypto Wallets related settings together.

**Comment by karenkliu** [comment] 2021-01-27 00:57
Duplicate of https://github.com/brave/brave-browser/issues/13688

**Closed by karenkliu** 2021-01-27 00:57 UTC
Labels: OS/Desktop, design, feature/crypto-wallets
