### ISSUE TITLE
Debilitating performance on macOS after update to 0.61.52

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#3924] opened 2019-03-28 16:58 UTC
## Description 

Users have been experiencing severe performance issues after updating Brave to v0.61.52.
Many users report that downgrading to version 0.61.51 or lower fixes the performance issues.
Note: Many of the users I see reporting are running an oder version of macOS (even if just a little bit older). @yachtcaptain23 also mentions this potentially being caused by having too many tabs open (50+).
## Steps to Reproduce

N/A

## Reproduces how often: 

No STR
## Brave version (brave://version info)

v0.61.62

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Unclear

### Additional Information

Reports:
https://community.brave.com/t/browser-slow-to-the-point-have-to-abandon-it/50027
https://twitter.com/xah_lee/status/1110716056711004160?s=21
https://youtu.be/RHUWr6GkBh4

Potentially related macOS performance issues (I'm not entirely sure these are related but they all seemed to spring up around the same time):

- [Brave prevents macOS machine from going to Sleep](https://www.reddit.com/r/brave_browser/comments/b5iq99/latest_update_is_preventing_my_mac_from_going/)
- [Keyboard input doesn't register right away/lags on NTP #1 ](https://community.brave.com/t/new-tab-user-should-be-able-to-start-typing-immediately/49780)
- [Keyboard input doesn't register right away/lags on NTP #2 ](https://community.brave.com/t/url-bar-clears-after-a-couple-seconds-erasing-my-search/50787/2)
- [Keyboard input doesn't register right away/lags on NTP #3](https://community.brave.com/t/delay-when-typing-in-new-tab-page/50733)
- [Brave doesn't release control to integrated GPU](https://community.brave.com/t/brave-wont-change-back-to-integrated-gpu-and-high-battery-usage/47295/4)

**Comment by rebron** [comment] 2019-04-26 15:25
@Brave-Matt We need reproducible steps and separate issues. Performance issues resolved with 63.x?

**Comment by bsclifton** [comment] 2019-12-31 05:52
Closing as stale- I suspect root cause for this one was fixed

However, we do have other new similar reported issues; in particular https://github.com/brave/brave-browser/issues/6098

**Closed by bsclifton** 2019-12-31 05:52 UTC
Labels: needs-investigation
