### ISSUE TITLE
Crash in BraveManageSyncSettings.java

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#33835] opened 2023-10-23 17:35 UTC
I found that crash in GPS on 1.61.39 on nightly channel.

```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
  at org.chromium.chrome.browser.sync.settings.BraveManageSyncSettings$1.run (BraveManageSyncSettings.java:203)
  at java.util.TimerThread.mainLoop (Timer.java:563)
  at java.util.TimerThread.run (Timer.java:513)
```

**Comment by AlexeyBarabash** [comment] 2023-10-23 17:36
thanks, that's is duplicate of 
https://github.com/brave/brave-browser/issues/33782

**Comment by AlexeyBarabash** [comment] 2023-10-23 17:38
Closing as a duplicate of https://github.com/brave/brave-browser/issues/33782

**Closed by AlexeyBarabash** 2023-10-23 17:38 UTC
Labels: closed/duplicate, crash, feature/sync, priority/P2, QA/No, release-notes/exclude, OS/Android
