### ISSUE TITLE
Tabs cannot be sorted anymore via drag and drop using the mouse cursor

### ISSUE THREAD

**Issue by louistiti** [brave/brave-browser#20515] opened 2022-01-15 01:28 UTC
## Description 

Hi Team, thanks for creating Brave!
I'm on Ubuntu 20.10, since the latest Brave release (1.34.80), my tabs cannot be sorted anymore via drag and drop. When I try to drag a tab, it'll automatically open a new window with the selected tab. This issue wasn't happening before this update.

When using the shortcuts `ctrl+shift+pageup/pagedown`, it works well. It only does not work when using the mouse cursor.

## Steps to Reproduce

   1. Open Brave browser on Ubuntu desktop.
   2. Open a new tab (so you have 2 tabs).
   3. Drag one tab to the left or right to sort it next to the other tab.

## Actual result:

Tabs cannot be sorted via drag and drop using the mouse cursor.

## Expected result:

Tabs can be sorted via drag and drop using the mouse cursor.

## Reproduces how often: 

Easily reproduced, the issue happens 100% of the time.

## Brave version (brave://version info)

```
Brave | 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Linux
JavaScript | V8 9.7.106.18
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-crashpad --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --no-pings --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/louis/.config/BraveSoftware/Brave-Browser/Default
Variations | AdRewardsStudy:NextPaymentDayAdServingStudy:MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=8/MaximumInlineContentAdsPerDay=40AdvertiserSplitTestStudy:GroupBBraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0hBraveAds.UserActivityStudy:Triggers=EMPTY/Threshold=0.0/IdleTimeThreshold=5ConversionsStudy:NewDefaultPatternDefault1pBlockingStudy:DisabledEphemeralStorageStudy:EnabledForceDisableBlinkFeatures:EnabledNativeCosmeticFilteringStudy:EnabledPartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledRequestAdsEnabledApiStudy:EnabledSpeedreaderReleaseStudy:Disabled
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes.
- Can you reproduce this issue with the beta channel?
Yes, with brave-browser-beta 1.35.85. 
- Can you reproduce this issue with the nightly channel?
Did not try.

**Comment by ivan18m** [comment] 2022-01-15 13:01
It's a Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=1279532

**Comment by neofutur** [comment] 2022-01-17 12:06
same problem here, for all the drag and drop features, not just reorganizing tabs, on brave 1.34.80 Chromium: 97.0.4692.71 .

**Comment by ajparrah** [comment] 2022-01-17 13:33
I had the same problem, i had to downgrade the package to `v1.33.106` to use drag and drop features because there are websites where drag and drop didn't work properly

```bash
sudo apt-get install brave-browser=1.33.106
```

**Comment by rebron** [comment] 2022-01-19 21:29
Closing as dupe of https://github.com/brave/brave-browser/issues/20386 which has more details.

**Closed by rebron** 2022-01-19 21:29 UTC
Labels: OS/Desktop

**Comment by louistiti** [comment] 2022-01-22 00:08
A new release has been published. I have upgraded Brave on my Ubuntu by download the [v1.34.81](https://github.com/brave/brave-browser/releases/tag/v1.34.81) `.deb` file.

Then ran:
```bash
sudo apt install ./brave-browser_1.34.81_amd64.deb
```
