### ISSUE TITLE
New Tab page is blank for two--five seconds

### ISSUE THREAD

**Issue by da2x** [brave/brave-browser#3029] opened 2019-01-21 03:49 UTC
## Description 
The performance on the New Tab page is really bad. It takes **two to five clock seconds** from I open a tab until the background and content displays.

## Steps to Reproduce
   1. Press Ctrl+T

## Actual result:
The page remains white for several seconds.

## Expected result:
The background image, counters, clock, and top sites should display immediately.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows

I've got the same issue on macOS and Linux too

### Website problems only:  
N/A

### Additional Information
This also happens with a completely empty profile.

Other web browsers, including Chrome; Firefox; and Opera, have solved this by keeping an instance of their new tabs loaded at all time. Opening a new tab either switches in the pre-loaded instances or makes a copy of it.

**Comment by srirambv** [comment] 2019-01-21 11:44
@btlechowski @GeetaSarvadnya could you try reproducing this? I cant reproduce it on Linux. Could be Windows specific. @da2x This is on Windows 7/10?

**Comment by da2x** [comment] 2019-01-21 12:10
I’m seeing this on recent powerful hardware on macOS 10.14.2, Windows 10.17763.55, and on Fedora Linux 29.

**Comment by srirambv** [comment] 2019-01-21 12:52
This is what I see on a i7 Processor machine running Dev/Beta/Release profiles and Slack(memory hogger) simultaneous  on Ubuntu with 16GB RAM
https://youtu.be/7njF6IT_IU8

Yes the first tab that opens has an awkward white blank for a second but subsequent new tabs don't show any blank page image loading is quite instant.

cc: @bbondy

**Comment by da2x** [comment] 2019-01-22 02:51
The white flashes you see on that video last two to five seconds on all of my computers every time I open a tab. Recent hardware, two laptops with Intel graphics and 16 GiB RAM and one desktop AMD graphics and 32 GiB of RAM. This doesn’t happen in Vivaldi or Chrome.

**Comment by btlechowski** [comment] 2019-01-22 03:07
I was able o reproduce the issue. For around 1 second the new tab page is white.

![3029](https://user-images.githubusercontent.com/34715963/51509882-0e92a880-1dfb-11e9-90f7-634dc49d3696.gif)

Reproduced on

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows

**Comment by rebron** [comment] 2019-02-15 16:43
Closing. Dupe of https://github.com/brave/brave-browser/issues/3362

**Closed by rebron** 2019-02-15 16:43 UTC
Labels: priority/P3
