### ISSUE TITLE
[Desktop] Month Option Selected in Brave Reward not updated on @onClick

### ISSUE THREAD

**Issue by Hakamate** [brave/brave-browser#11613] opened 2020-09-07 11:41 UTC
## Description 
Into Brave rewards :
When you click on another month, informations are updated, but not the month option selected

## Steps to Reproduce
   1.  Go to : brave://rewards/
   2.  Click here : 
![image](https://user-images.githubusercontent.com/33601556/92383743-2b363e00-f10f-11ea-99da-2ca3b775eee6.png)
   3. Select another month

## Actual result:
![image](https://user-images.githubusercontent.com/33601556/92383666-0e016f80-f10f-11ea-807a-6ce11d6c2ec1.png)

## Expected result:
Change Selected Option

## Brave version (brave://version info)
![image](https://user-images.githubusercontent.com/33601556/92384019-9f70e180-f10f-11ea-9958-a0349c7dab85.png)

**Comment by NejcZdovc** [comment] 2020-09-09 09:13
@brave/legacy_qa did you maybe saw this problem? Just tried it and can't reproduce it on my side

**Comment by LaurenWags** [comment] 2020-09-09 11:52
Looks like it reproduces on 


Brave | 1.14.73 Chromium: 85.0.4183.83 (Official Build) beta (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.14.6 (Build 18G3020)

The data on the statement itself changes, but the dropdown still says "September 2020" no matter what I select. Ex:

This is actually Sept 2020:
<img width="958" alt="Sept 2020" src="https://user-images.githubusercontent.com/28145373/92594755-3e611f00-f271-11ea-8865-65c9f2b34ef4.png">

Here I chose Aug 2020:
<img width="968" alt="Choose Aug" src="https://user-images.githubusercontent.com/28145373/92594756-402ae280-f271-11ea-95c6-a6781ebe88cf.png">

You can see the data reflects Aug 2020, not Sept 2020 as in first screenshot, but dropdown still says Sept 2020:
<img width="950" alt="Dropdown stays Sept" src="https://user-images.githubusercontent.com/28145373/92594761-41f4a600-f271-11ea-9bd3-7cb544e6645f.png">

**Comment by LaurenWags** [comment] 2020-09-09 11:54
+1 from https://github.com/brave/brave-browser/issues/9211#issuecomment-689143715

**Comment by NejcZdovc** [comment] 2020-09-09 12:41
@LaurenWags does this problem exists on the latest nightly?

**Comment by LaurenWags** [comment] 2020-09-09 16:21
Yes.


Brave | 1.16.4 Chromium: 85.0.4183.102 (Official Build) nightly (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | macOS Version 10.14.6 (Build 18G3020)

September:
<img width="972" alt="Screen Shot 2020-09-09 at 12 19 29 PM" src="https://user-images.githubusercontent.com/28145373/92625606-df160580-f296-11ea-9d6a-a38d363a3f7d.png">

Chose August:
<img width="959" alt="Screen Shot 2020-09-09 at 12 19 37 PM" src="https://user-images.githubusercontent.com/28145373/92625612-e0dfc900-f296-11ea-8acd-829085d145f3.png">

Dropdown shows Sept but statement shows August data:
<img width="960" alt="Screen Shot 2020-09-09 at 12 19 43 PM" src="https://user-images.githubusercontent.com/28145373/92625617-e2a98c80-f296-11ea-9de2-33d37fed5487.png">

**Comment by zenparsing** [comment] 2021-02-10 16:23
Fixed in https://github.com/brave/brave-core/pull/7615

**Closed by zenparsing** 2021-02-10 16:23 UTC
Labels: OS/Desktop, QA/Yes, feature/rewards, priority/P3

**Comment by stephendonner** [comment] 2021-02-22 23:49
Verified `FIXED` on macOS Big Sur (11.2.1) using `nightly` build:

Brave | 1.22.39 Chromium: 89.0.4389.58 (Official Build) nightly (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 11.2.1 (Build 20D74)

![rewards-feb-and-march](https://user-images.githubusercontent.com/387249/108784884-2c282400-7525-11eb-8d6b-7caf4462d0c0.gif)

I ran out of testing BAT in this session, so March isn't as complete as it could be, but the transactions I made showed up :-)

**Comment by LaurenWags** [comment] 2021-03-22 12:38
changing from `release-notes/include` to `release-notes/exclude` as this was fixed by https://github.com/brave/brave-browser/issues/13590 which was included in 1.21.x
