### ISSUE TITLE
sync does not put Android bookmarks into folders

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2447] opened 2018-12-11 11:40 UTC
## Description 
Empty folders are synced in win, no bookmarks inside the folders.

## Devices
Device 1: Windows 10 (Sync chain creator) - `0.58.11` 
Device 2: Android ARM - Samsung Galaxy J3 - `1.0.71 (sync2)`

## Steps to Reproduce
See also https://github.com/brave/brave-browser/issues/2447#issuecomment-446716877 for STR.

   1. Create sync chain on device 1
   2. Open QR code on Windows and scan QR code from Android
   3. Verify that sync is established between Win and Android
   4. Add few bookmarks in Win ( Add couple of BM's into the folder and leave few BM's on Toolbar)
   5. Add 4 BM's in Android  
   6. Edit bookmarks 1 and add it to folder A
   7. Edit bookmark 2 and add it to folder B
   8. leave 2 BM's outside the folders
   9. Make sure all the Windows BM's are syched in Android
  10. Verify that all the BM's from Android are synched in Win
  
   

## Actual result:

All the Android BM's are imported outside the folders, folder A and folder B are empty, no BM's inside the folders - Waited for almost 15 mins

Console log error:

[2548:2356:1211/161535.544:ERROR:CONSOLE(0)] "Error in event handler: TypeError: Cannot read property 'url' of undefined
    at Object.NodeState.editBookmark (chrome://bookmarks/crisper.js:36:3143)
    at Object.NodeState.updateNodes (chrome://bookmarks/crisper.js:36:4691)
    at Object.reduceAction (chrome://bookmarks/crisper.js:36:7120)
    at Store.reduce_ (chrome://bookmarks/crisper.js:44:1112)
    at chrome://bookmarks/crisper.js:44:960
    at Store.dispatchInternal_ (chrome://bookmarks/crisper.js:44:1015)
    at Store.dispatchAsync (chrome://bookmarks/crisper.js:44:869)
    at Store.dispatch (chrome://bookmarks/crisper.js:44:927)
    at dispatch (chrome://bookmarks/crisper.js:48:726)
    at onBookmarkChanged (chrome://bookmarks/crisper.js:48:785)", source: chrome://bookmarks/?id=3 (0)
[2548:2356:1211/161535.544:ERROR:CONSOLE(0)] "Error in event handler: TypeError: Cannot read property 'url' of undefined
    at Object.NodeState.editBookmark (chrome://bookmarks/crisper.js:36:3143)
    at Object.NodeState.updateNodes (chrome://bookmarks/crisper.js:36:4691)
    at Object.reduceAction (chrome://bookmarks/crisper.js:36:7120)
    at Store.reduce_ (chrome://bookmarks/crisper.js:44:1112)
    at chrome://bookmarks/crisper.js:44:960
    at Store.dispatchInternal_ (chrome://bookmarks/crisper.js:44:1015)
    at Store.dispatchAsync (chrome://bookmarks/crisper.js:44:869)
    at Store.dispatch (chrome://bookmarks/crisper.js:44:927)
    at dispatch (chrome://bookmarks/crisper.js:48:726)
    at onBookmarkChanged (chrome://bookmarks/crisper.js:48:785)", source: chrome://bookmarks/?id=3 (0)

## Expected result:
Folders should not be empty 

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? NA

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by LaurenWags** [comment] 2018-12-12 16:22
Reproduced with Device 1 as macOS (using build below) and Device 2 is Android

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

* encountered while testing https://github.com/brave/brave-browser/issues/2144

**Comment by bbondy** [comment] 2018-12-12 19:08
I think empty folders should be synced, closing. LMK if I'm wrong though.

**Comment by LaurenWags** [comment] 2018-12-12 19:12
@bbondy I think we should change the issue title - what i'm seeing (and I think @GeetaSarvadnya is too) is that if you have a folder on android which contains bookmarks, when that folder is synced to my laptop the folder is empty. the bookmarks are not inside the folder. If you take a look at my screenshots in  the comment above, hopefully you can see what i mean. On the laptop the folder and bookmarks are there, but the bookmarks are not in the folder.

**Comment by LaurenWags** [comment] 2018-12-12 19:39
Additional Steps to Reproduce:
1. Clean install 0.58.11.
2. Import some bookmarks (I imported about 45 from an HTML file).
3. Create Sync chain.
4. Install 1.0.71 sync2 on Android device.
5. Join sync chain.
6. Add bookmarks (and put some of those bookmarks into folders) on Android device.
7. Wait for bookmarks to be synced to laptop.
8. When Sync occurs, the bookmarks are not in the folder(s) you created on Android. (screenshots in https://github.com/brave/brave-browser/issues/2447#issuecomment-446648487)

I'm unable to test this with adding bookmarks to Android device prior to joining sync chain (essentially reverse steps 5 and 6 above) due to a different issue: https://github.com/brave/browser-android-tabs/issues/924

**Comment by LaurenWags** [comment] 2018-12-12 19:47
seems like maybe the bookmark(s) on Android are being synced before I get them into a folder on my device? Then they get to laptop (Device 1) that way - meaning, out of the folder. Then this incorrect placement gets synced back to the Android device (Device 2).

**Comment by btlechowski** [comment] 2018-12-12 20:25
Reproduced on Windows 7 x64(0.58.11) and Samsungs s7 (1.0.71(sync2)) using https://github.com/brave/brave-browser/issues/2447#issuecomment-446716877 Steps.

![image](https://user-images.githubusercontent.com/34715963/49896616-1d795900-fe54-11e8-89af-4143fd56960b.png)

**Closed** 2018-12-13 16:01 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/sync, priority/P2

**Comment by AlexeyBarabash** [comment] 2018-12-13 17:24
Just verified PR https://github.com/brave/brave-core/pull/1079 fixed issue.

**Comment by AlexeyBarabash** [comment] 2018-12-13 17:31
@GeetaSarvadnya , sorry for confusing. I was using own build from the latest master with merged PR.

**Comment by kjozwiak** [comment] 2018-12-13 23:15
@GeetaSarvadnya thanks for checking this again! There were a few issues fixed relating to sync that went into `0.58.12` so I thought this might have been fixed. Looks like https://github.com/brave/brave-core/pull/1079 needs to land before we can re-check. We'll need to wait for new builds 👍 Hopefully we'll have a new build by tomorrow AM.

**Comment by GeetaSarvadnya** [comment] 2018-12-14 05:52
Verification passed on.


Brave | 0.59.8 Chromium: 71.0.3578.98 (Official Build) beta (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows

- Verified STR from description.
- Verified STR from https://github.com/brave/brave-browser/issues/2447#issuecomment-446716877

![image](https://user-images.githubusercontent.com/38657976/49985518-3c7e0500-ff92-11e8-8d12-35b0aaeb2398.png)
