### ISSUE TITLE
Fingerprinting Protections v2: Workers - Canvas - follow up to 11368

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12099] opened 2020-10-12 20:24 UTC
## Description 

Found while testing https://github.com/brave/brave-browser/issues/11368

Per discussion with @pes10k, assigning to @pilgrim-brave for investigation.

Per instructions on dev-pages.brave.software/farbling.html and dev-pages.bravesoftware.com/farbling.html, for Canvas the "Worker" column value should match the other columns for that row when FP = standard or strict (since Mode has "both" for this row) and the value should be different between the two pages.

This ONLY occurs on dev-pages.bravesoftware.com/farbling.html, whereas dev-pages.brave.software/farbling.html works as expected.

## Steps to Reproduce

   1. Clean profile, 1.16.x
   2. Navigate to dev-pages.brave.software/farbling.html and dev-pages.bravesoftware.com/farbling.html
   3. Confirm FP = standard (or strict, either one will reproduce the issue)
   4. Generate Fingerprints

## Actual result:

FP = standard
<img width="1204" alt="1 16 x standard FP Canvas" src="https://user-images.githubusercontent.com/28145373/95787272-2b45d280-0ca7-11eb-98ec-27a64e3b61b5.png">

FP = strict
<img width="1201" alt="1 16 x strict FP Canvas" src="https://user-images.githubusercontent.com/28145373/95787269-28e37880-0ca7-11eb-9ef5-c7434c7fc5e1.png">

## Expected result:
Worker column value should match other values in the same row (but should be different between the two pages)

## Reproduces how often: 

easily

## Desktop Brave version:

Brave | 1.16.58 Chromium: 86.0.4240.75 (Official Build) dev (x86_64)
-- | --
Revision | c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}
OS | macOS Version 10.14.6 (Build 18G3020)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes 1.16.x
- Can you reproduce this issue with the nightly channel? yes 1.17.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron

**Comment by LaurenWags** [comment] 2020-10-12 20:25
Reproduces in 1.17.x as well:

FP = standard
<img width="1116" alt="1 17 x standard FP" src="https://user-images.githubusercontent.com/28145373/95786752-36e4c980-0ca6-11eb-8b84-ca055d11906f.png">

FP = strict
<img width="1115" alt="1 17 x strict FP" src="https://user-images.githubusercontent.com/28145373/95786754-38ae8d00-0ca6-11eb-939f-df798a65d034.png">

**Comment by pes10k** [comment] 2021-02-02 05:08
I believe this is fixed now.  @LaurenWags can you check again when you have a chance?

**Comment by LaurenWags** [comment] 2021-02-02 12:16
@pes10k same question 😄 - what version do you think this should be checked against - Nightly (currently 1.21.x) or one of the other channels?

**Comment by pes10k** [comment] 2021-02-02 22:55
Ah, sorry @LaurenWags !  It should be fixed in nightly / 1.21.x

**Comment by pes10k** [comment] 2021-02-02 23:52
ah, apologies @LaurenWags , i think this one is not ready for another test (i jumped the gun)..  But the other, WebGL one should be good to go.  Sorry for the confusion!

**Comment by LaurenWags** [comment] 2021-02-03 20:34
no worries, will give the other one a try and put some notes on it. Thanks!

**Comment by pes10k** [comment] 2021-04-02 21:55
Closing as this is not a bug (its a result of the canvas API using a different path, and so a different intervention point, than main frame farbling)

**Closed by pes10k** 2021-04-02 21:55 UTC
Labels: OS/Android, OS/Desktop, QA/Yes, feature/shields/fingerprint, privacy, privacy-pod
