### ISSUE TITLE
tawk.to chat doesn't work with Brave Shields enabled

### ISSUE THREAD

**Issue by bitcoinuser** [brave/brave-browser#2093] opened 2018-11-10 14:19 UTC
## Description 

tawk.to chat doesn't work with Brave Shields enabled

## Steps to Reproduce

   1. Go to https://ask.for-bitcoin.com and go to chat on bottom right. (Brave shields enabled)
   2. Try to chat with admin site
   3. 

## Actual result:

You can send messages but the message is not delivered to admin site.

![captura de tela de 2018-11-10 12-18-24](https://user-images.githubusercontent.com/1178856/48302347-bed25f80-e4e2-11e8-8a7b-48c5c44da8b4.png)

## Expected result:

Messages be delivered.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Versão 0.56.12 Chromium: 70.0.3538.77 (Versão oficial) 64 bits

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? I didn't test

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

**Comment by ryanbr** [comment] 2019-07-18 00:51
@bitcoinuser is this issue fixed? the site ( now, https://microlancer.io/ ) . Loaded up a chat session at the bottom. seems to work. If you can confirm that'd be great :)

**Comment by ryanbr** [comment] 2020-05-26 10:25
Have closed this issue @bitcoinuser unable to reproduce this. Do re-open ticket if the site is still problematic.

**Closed by ryanbr** 2020-05-26 10:25 UTC
Labels: bug, priority/P5, webcompat, workaround/shields-down
