### ISSUE TITLE
Reload brave://rewards shows incorrect wallet balance for few seconds when Rewards is off

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2897] opened 2019-01-10 16:15 UTC
## Description 
Reload `brave://rewards` shows incorrect wallet balance for few seconds when Rewards is off. On 0.58.20 incorrect balance show up only for few seconds and then it shows up correct balance. But, in dev build 0.60.9 it remained permanently as (70 BAT). It won't show original wallet balance 35 BAT even after multiple `brave://rewards` page reload

## Steps to Reproduce

   1.  Clean profile 0.58.20
   2.  Enable Rewards and accept grants (35 BAT)
   3.  Turn off Rewards
   4. Open a verified publisher add tip it ( for my test tip amount is 1 BAT)
   5. Reload `Brave://Rewards` page  to see a-c balance
  

## Actual result:
a-c total balance is displayed as 70 BAT for couple of secs and then it shows up 34 BAT
![tip issue](https://user-images.githubusercontent.com/38657976/50980969-e4e6a100-151f-11e9-8eec-cbcee970f889.gif)

## Expected result:
Should display correct a-c balance after page reload

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.58.20 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows

### Reproducible on current release: nope
- Does it reproduce on brave-browser dev/beta builds? Yes on dev build 0.60.9 issue is reproducible

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional Information
@brave/legacy_qa

**Comment by NejcZdovc** [comment] 2019-01-18 17:22
I think this is kinda dupe of https://github.com/brave/brave-browser/issues/2214 as you shouldn't be able to tip when rewards are off. We added disabled state in 0.60 so this STR are not possible anymore. If you find new STR please update them and reopen this issue. Thank you

**Closed by NejcZdovc** 2019-01-18 17:22 UTC
Labels: QA/Yes, bug, feature/user-interface
