### ISSUE TITLE
[Follow up to #28769][Speedreader] "View page with Speedreader? Enable" pop-up notification is shown when page already in Speedreader Mode

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#30036] opened 2023-04-27 17:41 UTC
## Description 

Follow up to #28769

## Steps to reproduce 

   1. Launch Brave > In the new tab open supported page, for example https://www.theguardian.com/technology/2023/apr/26/microsoft-bid-for-activision-blizzard-blocked-by-uk-competition-regulator
   2. Hamburger Menu > Settings
   3. Appearance > Enable Speedreader > Relaunch now
   4. Switch or open any other tab
   5. Return back the tab which is shown in Speedreader Mode > Observe pop-up notification
   6. Tap "Enable" > Observe, that page is reloaded in a Regular Mode

## Actual result 

"View page with Speedreader? Enable" pop-up notification is shown when page already in Speedreader Mode and user is relaunching the browser or refreshing the page

https://user-images.githubusercontent.com/128532965/234944714-2a7c3cfb-81d9-4f63-b729-a20a4ec88e59.mp4

## Expected result

When supported page is shown in Speedreader Mode already, "View page with Speedreader? Enable" pop-up notification must not be shown again

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 6 [phone]
   - Android version: oriole-user 13 TQ2A.230405.003.E1 release-keys
   
## Brave version

1.51.105 [Beta], Chromium: 112.0.5615.165 (Official Build) beta (32-bit) 
Revision: c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by wchen342** [comment] 2023-05-08 12:53
This shall be fixed in 1.52.x, see brave/brave-core/pull/17934.
Duplicate of brave/brave-browser/issues/29523.

**Closed by wchen342** 2023-05-08 12:53 UTC
Labels: bug, QA/Yes, OS/Android, feature/speedreader
