### ISSUE TITLE
M1 Mac Support

### ISSUE THREAD

**Issue by FatSandwich** [brave/brave-browser#13155] opened 2020-12-11 01:24 UTC
Usually whenever I use Brave on my M1 Mac it works. But, now it has started to quit unexpectedly and has sometimes caused problems. I love this browser but I am currently using Safari because I cannot risk the work the is unsaved.

**Comment by kjozwiak** [comment] 2020-12-11 06:51
We're in the process of getting M1 builds on release 👍 CCing @bsclifton @rebron as they've been close to the work and could probably give a better update.

**Comment by FatSandwich** [comment] 2020-12-11 16:01
Great! By the way, is the Nightly Version supported for M1 Macs?

**Comment by bsclifton** [comment] 2020-12-11 18:27
Closing as a duplicate of https://github.com/brave/brave-browser/issues/12819

@FatSandwich yup- you can download any of our latest releases (look for Nightly) on https://github.com/brave/brave-browser/releases

Look for the `Brave-Browser-Nightly-arm64.dmg` - these should work great for you and it will auto update too 😄

**Closed by bsclifton** 2020-12-11 18:27 UTC
Labels: OS/Desktop, OS/macOS

**Comment by FatSandwich** [comment] 2020-12-11 18:34
So, will all my data save in the Nightly Version like my BAT?

**Comment by mihaiplesa** [comment] 2020-12-12 13:58
@FatSandwich both `x64` and `arm64` save data to the same location so it should work (just don't use them at the same time). Any other issues please report on https://github.com/brave/brave-browser/issues/12819

**Comment by FatSandwich** [comment] 2020-12-15 00:06
Everything synced when I used a sync chain except for the BAT? Is there a fix for this?

**Comment by mihaiplesa** [comment] 2020-12-15 00:16
https://github.com/brave/brave-browser/issues/11513

**Comment by FatSandwich** [comment] 2020-12-15 00:17
Oh thanks!
