### ISSUE TITLE
Pluggable transports and bridges for Tor

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1138] opened 2018-09-15 00:24 UTC
We should eventually make it easy to configure advanced user-facing Tor features like bridges and pluggable transports.

**Comment by Raj2032** [comment] 2018-09-22 02:17
Hope to see this implemented sometime mate (by the way I am joe232 from the brave community)

**Comment by ferremi** [comment] 2019-07-21 01:00
There is a forecast for this feature deployment?

**Comment by tomlowenthal** [comment] 2019-07-22 22:56
No, this work is not scheduled.

**Comment by phanirithvij** [comment] 2019-10-17 23:17
How to configure normally?

**Comment by Ghostineuro** [comment] 2020-02-06 12:18
Hope to see this work in the near future...

**Comment by fusionneur** [comment] 2020-06-26 16:14
this is the missing piece of the puzzle. it should be treated with highest priority instead.

**Comment by qwertyu7599** [comment] 2020-07-14 17:17
Tor feature as it is, is just basically useless. This should be scheduled.

**Comment by fusionneur** [comment] 2020-08-25 17:32
Can we please schedule this? World needs it..

**Comment by Strykar** [comment] 2020-09-06 01:54
@tomlowenthal Tor is almost unusable via the Private Tor Window as it defaults to standard exit node which Cloudflare's HCaptcha is pretty brutal to verify. This is trivially worked around by folks who run their own bridge and would make this feature usable.

Is it really a large development effort to add an option so users can specify their own bridge?

**Comment by jkmartindale** [comment] 2020-09-06 15:09
> Is it really a large development effort to add an option so users can specify their own bridge?

Work on a pull request and find out 😳

**Comment by Strykar** [comment] 2020-09-06 15:51
> Work on a pull request and find out

I was curious how much effort it might be, if I could have, I would have led with a PR :smile:

**Comment by fusionneur** [comment] 2021-01-19 19:36
Can we have a priority increase?

**Comment by AhmedElhadidii** [comment] 2021-11-04 02:24
looking forward to see this

**Comment by beari22** [comment] 2021-11-28 09:55
pls add config

**Comment by apatrushev** [comment] 2021-12-08 18:58
ToR was blocked in Russia. Without this option lovely ToR feature of Brave browser will be useless.

**Comment by darakcheeff** [comment] 2021-12-28 11:48
Tor still blocked and we need bridge feature in brave for russian users

**Comment by MrTomasRipley** [comment] 2022-01-28 10:15
Could you increase the priority for this task, please?

**Comment by fusionneur** [comment] 2022-01-28 12:06
this should be at least a P2...wtf P5??

**Comment by kmahyyg** [comment] 2022-02-02 12:32
wtf P5? We need this.

**Comment by Alex0007** [comment] 2022-02-04 21:31
Russian user here. Requesting bridges support

Reference: https://forum.torproject.net/t/tor-blocked-in-russia-how-to-circumvent-censorship/982

**Comment by iamashwin99** [comment] 2022-02-08 06:23
+1 on this feature request

**Comment by barkovv** [comment] 2022-02-09 20:34
yet another +1 for this.

The rational for this is that in some countries like Rusian federation the main Tor site is blocked by providers.
Do you accept the contributions? I would like to implement it if it's not hard and I have time for it. I do like Brave browser but without Tor support it doesn't make sense for me.

**Comment by NotDevelopper** [comment] 2022-03-07 15:30
Four years later the issue is still relevant. Much more than ever before.

**Comment by diracdeltas** [comment] 2022-03-08 03:58
I think the instructions in https://gist.github.com/mort3za/b28495d7e42e628e7b7c9346488b5e93 should work with Brave. But note that our torrc file is located in `APP_DATA/cldoidikboihgcjfkhdeidbpclkineef/1.0.23/tor-torrc`, replacing APP_DATA with your app data directory using the instructions in https://community.brave.com/t/where-does-brave-store-its-data-files/53830/2. Also note that `1.0.23` will change as we release new versions.

If you try this, let me know if it works.

**Comment by RomanSedykh** [comment] 2022-03-12 13:00
> 

no. it doesn't work.
also, in version 1.36.105
tor-rorrc file is located in /biahpgbdmdkfgndcmfiipgcebobojjkp/1.0.24/

**Comment by Karlson2k** [comment] 2022-03-14 07:17
There are many reasons to increase the priority of this issue. 
Please, set it at least on P2.

**Comment by Strykar** [comment] 2022-03-14 08:11
4 years and counting..

**Comment by NullHypothesis** [comment] 2022-03-14 14:58
> no. it doesn't work. also, in version 1.36.105 tor-torrc file is located in /biahpgbdmdkfgndcmfiipgcebobojjkp/1.0.24/ my torrc file:
> 
> ```
> SocksPort auto
> ControlPort auto
> CookieAuthentication 1
> UseBridges 1
> ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy managed
> obfs4 ...
> ```

Your bridge line should start with `Bridge` instead of `obfs4`. Other than that, this exact configuration works for me on Linux and Brave nightly. What does the log file in brave://tor-internals/ say? I assume obfs4proxy is installed and working?

**Comment by RomanSedykh** [comment] 2022-03-15 14:36
> Your bridge line should start with `Bridge` instead of `obfs4`

like so?
`
SocksPort auto
ControlPort auto
CookieAuthentication 1
UseBridges 1
ClientTransportPlugin obfs4
Bridge obfs4 ...
`
obfs4proxy is installed. not sure on how to check if it is working or not.

> What does the log file in brave://tor-internals/ say?

it is completely empty

**Comment by NullHypothesis** [comment] 2022-03-15 16:30
> like so?

Yes. Here's what my torrc looks like in Brave Nightly. (Note that I'm using one of the Tor Project's (public) default bridges, so there's no need to redact bridge information.)
```
SocksPort auto
ControlPort auto
CookieAuthentication 1

UseBridges 1
ClientTransportPlugin obfs4 exec /path/to/obfs4proxy managed
Bridge obfs4 38.229.1.78:80 cert=Hmyfd2ev46gGY7NoVxA9ngrPF2zCZtzskRTzoWXbxNkzeVnGFPWmrTtILRyqCTjHR+s9dg iat-mode=1
```

> obfs4proxy is installed. not sure on how to check if it is working or not.

Simply run `obfs4proxy -version`. As of today, the latest version is "obfs4proxy-0.0.13."

**Comment by RomanSedykh** [comment] 2022-03-16 15:12
>  As of today, the latest version is "obfs4proxy-0.0.13."
Same.
So, my config is correct, and obfs4proxy is working.
My brave version is ```Version 1.36.111 Chromium: 99.0.4844.51 (Official Build) unknown (64-bit)```
Tor window shows "disconnected" tor status.
What else i can try?

**Comment by iefremov** [comment] 2022-03-16 15:51
@RomanSedykh are you sure the bridge itself is not blocked?

**Comment by RomanSedykh** [comment] 2022-03-16 17:07
@iefremov just tried new one from tor telegram bot - no luck.

**Comment by choodique** [comment] 2022-03-19 22:48
> @iefremov just tried new one from tor telegram bot - no luck.
> 
> By the way, in `brave://tor-internals/` it doesn't show any tor version at all:
> 
> ```
> Tor Version:
> Tor Process Id: -1
> Tor Proxy URI:
> Tor Connection Status: Disconnected
> Tor Initialization Progress:
> ```
> 
> Is it supposed to be that way?

hi,

Brave - Версия 1.36.117 Chromium: 99.0.4844.74 (Официальная сборка), (arm64)

tor-torrc:

```
SocksPort auto
ControlPort auto
CookieAuthentication 1

ExcludeExitNodes {RU},{UA},{AM},{KG},{BY}

UseBridges 1
ClientTransportPlugin obfs4 exec /opt/homebrew/bin/obfs4proxy managed
Bridge obfs4 65.108.56.114:55487 621BA99387F65441630DFBC8A403D11D126EBC72 cert=5HzsLradvYOipNky+aHrgo31KRtxq5Cb6tz3y5Ds7PbBeB0r+C4r15IPYppupCJgzuXgWw iat-mod=0

```

In my opinion, it is very important to correctly specify the **path to obfs4proxy**

I installed it through homebrew and the full path in my case would be :  `/opt/homebrew/bin/obfs4proxy`

In this configuration I have a private Tor window and it works

`brave://tor-internals/`:
```
Версия Tor: 0.4.6.9
Идентификатор процесса Tor: 68294
Ссылка прокси Tor: socks5://127.0.0.1:64081
Статус соединения Tor: Connected
Прогресс инициализации Tor:
```

**Comment by RomanSedykh** [comment] 2022-03-19 23:33
@choodique with your config file it started to initialize and started to show tor version and other stuff on "brave-internals" page. But. Initialization was always stuck at 77%. After closing and opening tor window few times, it suddenly started working. Now it immediately connects and works every time i open it. I guess, it can stop doing so at any moment, but for now i can't even see the error message for that 77% bug. So... thanks, i guess?

**Comment by choodique** [comment] 2022-03-20 00:15
> @choodique with your config file it started to initialize and started to show tor version and other stuff on "brave-internals" page. But. Initialization was always stuck at 77%. After closing and opening tor window few times, it suddenly started working. Now it immediately connects and works every time i open it. I guess, it can stop doing so at any moment, but for now i can't even see the error message for that 77% bug. So... thanks, i guess?

I also encountered a "waiting" at 77%, but like you - after rebooting everything worked.

Whether the "77% condition" can happen again - I do not know, maybe I will have to change the bridge.

p.s. I request bridges from the telegram bot https://t.me/GetBridgesBot or look at https://torscan-ru.ntc.party/ (thanks @ValdikSS)

**Comment by volucris1** [comment] 2022-04-23 03:28
My tor-torrc:
```
SocksPort auto
ControlPort auto
CookieAuthentication 1

UseBridges 1 
ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy 
Bridge obfs4 5.161.61.213:443 04A8B84D840E96BF27CCC8575E9701410D68640C cert=SUbYQu1b+BMQpy+pR4BySzXAa/ogsDXDTH2Q0QvS9CK1rG4HfOeJmfd4Z1tW0OnSczqqEQ iat-mode=0
Bridge obfs4 51.79.53.112:52234 343FD85CDFAF09C3F19F7C7B93917B290EF72D47 cert=iAXNyHJ4VdQoQOHvO9rEvlvvv8y9lIQYOOdKbVu5n/MUaVlseNRNam602biHdrGDhL0+Nw iat-mode=0
Bridge obfs4 89.58.37.243:9117 EBE8ABF8522F9E09DC83675FCA1227037A4CAB06 cert=+RnVWpoYiOqo2cDX62oiizAv8UlPJAMN370PpxzI2uPq1yTxrJ4KsMQVPlaCkJ7o9JvBCw iat-mode=0
```

**Closed** 2022-08-03 13:43 UTC
Labels: help wanted, feature/tor, priority/P3, QA/Yes, release-notes/include

**Comment by stephendonner** [comment] 2022-09-15 06:01
@brave/qa-team not technically blocked here on Windows and Linux, but it might be wise to wait until the bridge/pluggable-transport issue has been fixed and verified first on macOS (to save redoing regression testing): https://github.com/brave/brave-browser/issues/25293 👍

**Comment by MadhaviSeelam** [comment] 2022-09-21 00:02
Verification `In progress` using
```
Brave | 1.44.93 Chromium: 105.0.5195.136 (Official Build) beta (64-bit)
-- | --
Revision | 872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

### Steps:

### <summary>  `brave://settings/pravcy` - PASSED </summary>
<details>

1. installed `1.44.93`
2. launched `Brave`
3. opened `brave://settings/privacy`
4. navigated to `Tor windows` section and confirmed following settings:
    - `Private window with Tor`
    - `Automatically redirect .onion sites`
    - `Use Bridges`
5. `Private window with Tor` is enabled by default 

![image](https://user-images.githubusercontent.com/98358127/191378521-32551d35-1619-486c-a78d-7524466d674a.png)

</details>

### </summary> Tor windows settings    </summary>

#### <summary> `Private window with Tor` - PASSED  </summary>
<details>

1. opened `brave://settings/privacy`
2. toggle `OFF` (or click the tab) to disable `Private window with Tor` setting
3. confirmed `Automatically redirect .onion sites`  and `Use Bridges settings` are greyed out
4. confirmed private window with TOR option is not available in hamburger menu
5. toggle `ON`  restored default values
6. launch  Tor window (Alt + Shift + N)
7. loaded brave://components in a NTP
8. `Brave Tor Client Updater (Windows) displayed with updated status as expected
9. visited check.torproject.org 
10. additionally, invoked New Tor connection for this site and confirmed it reloaded with a new Tor IP address
11. do a hard refresh (Ctrl+F5) and confirmed page  reloaded with a new IP address

step 3|step 4|step 5|step6|step7|step 9
----|----|----|----|----|----
<image width="1500" alt="step3" src="https://user-images.githubusercontent.com/98358127/191379046-dbcda1d4-0996-402c-ba14-5074ae484184.png">|<image width="1500" alt="step3" src="https://user-images.githubusercontent.com/98358127/191379312-f6e817a6-bfe7-4acf-a79e-43f7abbad192.png">|<image width="1500" alt="step3" src="https://user-images.githubusercontent.com/98358127/191379830-3c9a8aee-043e-44f1-a35e-e9f3ff64e1ab.png">|<image width="1450" alt="step3" src="https://user-images.githubusercontent.com/98358127/191380638-7119cb19-73b1-4b52-9094-e392a974b04c.png">|<image width="1450" alt="step3" src="https://user-images.githubusercontent.com/98358127/191380729-40ef9ab8-22a4-4dae-beb7-6207169f3a48.png">|<image width="1600" alt="step3" src="https://user-images.githubusercontent.com/98358127/191383790-42866369-2311-4b46-aecc-d603e018f04e.png">

</details>

**Comment by stephendonner** [comment] 2022-09-21 06:54
The testplan for this issue is the same as for https://github.com/brave/brave-browser/issues/16624#issuecomment-1251640467, which I've verified on Windows 10, already.

Doubled-up coverage on `Tor` would be good, but perhaps do a critical subset, rather than the full set, @MadhaviSeelam ?

**Comment by stephendonner** [comment] 2022-09-21 17:05
## Verified `PASSED` using 

Brave | 1.44.92 Chromium: 105.0.5195.136 (Official Build) beta (64-bit)
-- | --
Revision | 872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}
OS | Windows 10 Version 21H2 (Build 19044.2006)

Note the section from `Bridges (basic)` onward: https://github.com/brave/brave-browser/issues/16624#issuecomment-1251640467

**Comment by MadhaviSeelam** [comment] 2022-09-23 00:37
Verification `In progress` using
```
Brave | 1.44.97 Chromium: 106.0.5249.55 (Official Build) (64-bit)
-- | --
Revision | 4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
OS | Linux
```

### Steps:

### <summary>  `brave://settings/privacy` - PASSED </summary>
<details>

1. installed `1.44.93`
2. launched `Brave`
3. opened `brave://settings/privacy`
4. navigated to `Tor windows` section and confirmed following settings:
    - `Private window with Tor`
    - `Automatically redirect .onion sites`
    - `Use Bridges`
5. `Private window with Tor` is enabled by default 

![image](https://user-images.githubusercontent.com/98358127/191872682-04af0344-bf0c-4a75-a590-1c98ccf708d9.png)

</details>

### <summary> `Tor windows` settings </summary>

####  `Private window with Tor` - PASSED  
<details>

1. opened `brave://settings/privacy`
2. toggle `OFF` (or click the tab) to disable `Private window with Tor` setting
3. confirmed `Automatically redirect .onion sites`  and `Use Bridges settings` are greyed out
4. confirmed `private window with TOR` option is not available in `hamburger` menu
5. toggle `ON`  restored defaults
6. launched  `Tor window` (Alt + Shift + N  OR from `hamburger` menu)
7. loaded `brave://components` in a NTP
8. `Brave Tor Client Updater (Windows)` component displayed with updated status as expected
9. visited `check.torproject.org` 
10. additionally, invoked `New Tor connection` for this site and confirmed it reloaded with a new Tor IP address
11. confirmed page  reloaded with a new IP address when did a hard refresh (Ctrl+F5) 

step 2-4|step 5|step 6|step7
----|----|----|----
<image width="1500" alt="step3" src="https://user-images.githubusercontent.com/98358127/191873178-fbecbf09-acd2-4f9d-8aa3-4fb9edc3c194.png">|<image width="1500" alt="step3" src="https://user-images.githubusercontent.com/98358127/191873246-50f258af-1e81-4c9e-bf5d-2b2fc3bfde85.png">|<image width="1500" alt="step3" src="https://user-images.githubusercontent.com/98358127/191872867-f7affbc0-71d5-4797-95f4-e51869b754fa.png">|<image width="1500" alt="step3" src="https://user-images.githubusercontent.com/98358127/191872953-2a313739-74ae-44f2-86fa-b9ab23976d27.png">

</details>

####  `Automatically redirect .onion sites`  - PASSED 
<details>

1. New profile 
2. opened `brave://settings/privacy`
3. enabled  `Automatically redirect .onion sites`
4. open following sites in NTP
    -brave.com
    -mail.protonmail.com
5. confirmed following  .onion sites automatically redirected to Tor window  with  .onion URL:
    - brave.com -->https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/
    - mail.protonmail.com --> https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/

step 4|step 5
----|----
<image width="1500" alt="step3" src="https://user-images.githubusercontent.com/98358127/191873516-7d01a7d3-ebe9-4d7e-afe2-e249271e44d3.png">|<image width="1500" alt="step3" src="https://user-images.githubusercontent.com/98358127/191873610-8c387e0f-c275-4cc5-9160-7d7c899f5c24.png">

**Comment by stephendonner** [comment] 2022-09-26 20:31
## Verified `PASSED` using 

Brave | 1.44.99 Chromium: 106.0.5249.55 (Official Build) (x86_64)
-- | --
Revision | 4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
OS | macOS Version 11.7 (Build 20G817)



See the notes from the `Bridges (basic)` section onward, here: https://github.com/brave/brave-browser/issues/16624#issuecomment-1258265374
