### ISSUE TITLE
Newtab ads blocked and trackers blocked get counted together

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1754] opened 2018-10-20 17:22 UTC
## Description 

Newtab trackers blocked are not counting and instead being combined with ads blocked.
Reported and found here:
https://www.reddit.com/r/BATProject/comments/9pub7w/whats_with_the_low_level_of_trackers_blocked_and/

## Steps to Reproduce

   1. Clean profile
   2. Visit some sites
   3.  Open a new tab

## Actual result:

New tab trackers blocked doesn't increase even know it should, it gets combined with ads blocked.

## Expected result:

New tab should treat trackers separately.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

0.55.18

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  yes
- Does it reproduce on browser-laptop?  no

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? no
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information

This was due to a refactor done for a crash on RC1.

**Comment by srirambv** [comment] 2018-10-20 17:46
Dupe of #1735

**Closed by srirambv** 2018-10-20 17:46 UTC
