### ISSUE TITLE
"Forget me when I close this site" does nothing

### ISSUE THREAD

**Issue by ADHDefy** [brave/brave-browser#33351] opened 2023-10-01 19:46 UTC
## Description 

I keep "Clear browsing data on exit" on normally, but lately I've been depending on some PWAs that I need to remain logged into. I was searching the settings for a way to add an exception for cookies and site data of a specific site (which it seems there is no way to do on Android), when I came across the "Forget me when I close this site" option. I thought maybe I could enable that and disable it specifically on the sites I want to remain logged in to.

Unfortunately, it seems to be pointless. When exiting a site or closing the browser entirely, I remain logged in on sites I should have been logged out of, I still have all my browser history, cookies are saved, etc.

## Steps to reproduce 

   1. Enable "Forget me when I close this site"
   2. Visit some sites, log in on some, exit all tabs and/or browser
   3. Open Brave once more and revisit sites to see that you are still logged in
   4. Additionally, check the browsing data before and after closing sites to see that there is no change

## Actual result 

Nothing changes whether the setting is enabled or not

## Expected result

All browsing data is removed after a site's tab/the browser is closed, except for sites that have been specifically, individually excepted from the rule

## Issue reproduces how often 

Every time, easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? **Yes**
- Can you reproduce this issue with the current Play Store Beta version? **Yes**
- Can you reproduce this issue with the current Play Store Nightly version? **Yes**

## Device details
   - Install type (ARM, x86): **ARM**
   - Device type (Phone, Tablet, Phablet): **Phone**
   - Android version: **13**
   
## Brave version

Brave 1.58.135, Chromium 117.0.5938.140

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional information

Please make a way for Android users to clear all browsing data on exit but leave exceptions for specific sites so that PWAs are actually useful without sacrificing general browsing privacy.

From searching, people have been requesting this feature for both Desktop and Android since as far back as 2017. It is a basic feature that all other major browsers offer.

**Comment by slipstyle** [comment] 2024-05-22 21:04
This is crazy that there are specific options to "Forget me when I close this site" and they do absolutely nothing... Can confirm both on Android and Desktop (Linux).

Suuuuper misleading and gives a false sense of security... 

At least on Desktop you can change the default site settings to delete cookies when the browser exits, which seems to mostly work, but, not on Android.... as the OP has mentioned, I've found numerous issues and forum posts about this from many years ago, yet this is still presented as a (non-working) option. What a shame.

**Comment by bsclifton** [comment] 2024-05-22 23:51
cc @ShivanKaul

**Comment by ShivanKaul** [comment] 2024-05-23 00:03
If you have "forget me when I close this site" enabled for a site, you need to wait for 30 seconds after closing all tabs for that site before all data is cleared. Can you retry keeping that in mind?

**Comment by slipstyle** [comment] 2024-05-23 22:49
@ShivanKaul, I must apologize, you are absolutely correct about the 30 seconds, I feel like a complete mug now... I honestly couldn't believe what I was seeing, and turns out I just had to be a bit more patient...

I have observed, on Android, the shield option to "Forget me when I close this site" is indeed properly removing cookies after a short period (of approx 30s) after closing that website's tab(s). 

On desktop, I can confirm the same behavior, Brave Shield is correctly removing the site data after ~30s.

I should note (just to be verbose for anyone else stumbling onto this comment) even if I have the below desktop setting set to the most permissive option, the Brave Shield will still remove the cookies after the tab is closed:
- Settings -> Privacy and security -> "On-device site data" set to "Allow sites to save data on your device" 

Once again, I apologize for raising the alarm when I didn't fully understand the mechanism. Thank you for informing me of how it works.

Versions I can confirm:
Android 14: Brave 1.65.132, Chromium 124.0.6367.202
Desktop (Linux): Version 1.66.110, Chromium: 125.0.6422.60 (Official Build)  (64-bit)

**Comment by bsclifton** [comment] 2024-05-23 23:11
cc: @ADHDefy

**Comment by bsclifton** [comment] 2024-06-03 18:42
I'll close this as resolved

Thanks for the feedback, @slipstyle! @ShivanKaul if there are any changes to this functionality, please link back here. Maybe it could be a bit more obvious, etc. With upcoming Shred feature, we can just keep that in mind.

**Closed by bsclifton** 2024-06-03 18:42 UTC
Labels: privacy, privacy/feature, needs-more-info, OS/Android, privacy-pod

**Comment by h0m3** [comment] 2025-03-14 05:03
I would suggest, if possible, to add the 30 seconds information in a documentation, FAQ or a tooltip.

I thought that the functionality had an issue before arriving here, and undestanting how it works.

**Comment by qmcree** [comment] 2025-03-19 20:53
I also just encountered this issue and thought the feature was broken. I agree with @h0m3, including a tooltip or small line under the setting about it taking effect after 30 seconds would be helpful. Thanks for making the world's most amazing browser.

**Comment by bsclifton** [comment] 2025-03-27 21:16
cc: @ShivanKaul on the above feedback 😄👍

**Comment by ShivanKaul** [comment] 2025-03-28 00:16
I want to just shorten the time delay: https://github.com/brave/brave-browser/issues/42354
cc @goodov
