### ISSUE TITLE
[Android] Sticky URL/Bottom Bar 

### ISSUE THREAD

**Issue by pidus** [brave/brave-browser#11337] opened 2020-08-20 05:54 UTC
## Description 

Phones are getting bigger and longer. Vertical real estate is not a concern anymore. So, please give us an option for sticky URL and bottom toolbar.

**Comment by fallaciousreasoning** [comment] 2022-11-01 03:33
Duplicate of https://github.com/brave/brave-browser/issues/12883

**Closed by fallaciousreasoning** 2022-11-01 03:33 UTC
Labels: OS/Android
