### ISSUE TITLE
[Follow up to 28765] Disabling news source using context menu is not unfollowing from news sources list

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#28865] opened 2023-03-02 18:49 UTC
## Description 
After upgrading to a new version of the app with brave news v2 enabled, disabling the sources using the long press context menu on NTP will not unfollow sources in the following list. 

Follow up to https://github.com/brave/brave-browser/issues/28765

## Steps to reproduce 

   1. Install 1.48.x
   2. Enabled Brave News V2 under brave://flags
   3. Enabled News
   4. Subscribe to some channels/sources
   5. Unfollow Top sources channel (for easier verification)
   6. Return to NTP to update the feed
   7. Update app to 1.49.x
   8. Long press on one of the sources and disable using context menu
   9. Open news settings and checking following list
   

## Actual result 

https://user-images.githubusercontent.com/17885425/222521099-31f94876-e575-4970-9155-97613a5a78a3.mp4

## Expected result
Disabling sources should unfollow it in the list.

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? N/A

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 13
   
## Brave version
`1.49.117, Chromium 111.0.63.50`

**Comment by fallaciousreasoning** [comment] 2023-03-02 19:19
Possibly a duplicate of https://github.com/brave/brave-browser/issues/28765?

**Comment by Uni-verse** [comment] 2023-03-02 19:31
> Possibly a duplicate of #28765?

@fallaciousreasoning Its a follow up due to some issues with unfollowing sources on upgraded profile.

**Closed** 2023-03-03 18:21 UTC
Labels: bug, QA/Yes, OS/Android, feature/brave-news

**Comment by kjozwiak** [comment] 2023-03-16 01:58
The above requires `1.50.93` or higher for `1.50.x` verification 👍

**Comment by Uni-verse** [comment] 2023-03-28 22:04
Verified on `Samsung GS 21 5G` using version:

```
Brave	1.50.107 Chromium: 112.0.5615.39 (Official Build) beta (64-bit) 
Revision	a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}
OS	Android 13; Build/TP1A.220624.014
```
Scenario Test Steps: 

1. Install `1.50.86` (Beta App)
2. Enabled `Brave News V2` under `brave://flags`
3. Enabled News
4. Subscribe to some channels/sources
5. Unfollow Top sources channel (for easier verification)
6. Return to NTP to update the feed
7. Updated app to `1.50.107` (Beta)
8. Long press on one of the sources and disable using context menu
9. Open news settings and checking following list

https://user-images.githubusercontent.com/17885425/228376825-9ab33409-5933-4ba7-bcf7-cdf3974f3a06.mp4
