### ISSUE TITLE
Brave attempts to Google any IPv6 Address typed into the address bar

### ISSUE THREAD

**Issue by TheDiscordian** [brave/brave-browser#14410] opened 2021-03-01 16:06 UTC
## Description 

Typing any IPv6 IP address into the address bar will attempt to Google the address, regardless if the URI is specified or not.

## Steps to Reproduce

   1. Type IPv6 address into address bar with or without "http://", hell type basically anything
   2. Press enter

## Actual result:

My IP address was submitted to Google, and I got search results presented to me.

## Expected result:

My local page I was testing out, no data leakage.

## Reproduces how often: 

Easily reproduced, happens 100% of the time.

## Brave version (brave://version info)

```
Brave | 1.19.92 Chromium: 88.0.4324.152 (Official Build) unknown (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Linux
JavaScript | V8 8.8.278.15
```

## Miscellaneous Information:

This isn't just an extremely annoying bug, I consider this an extreme violation of privacy. Completely outside of the user's control, Brave will submit personal information to third parties as a result of this bug. If the user is specifying the URI the information should NEVER EVER be sent to a search engine, that's completely ridiculous.

**Comment by alekny** [comment] 2021-03-03 03:47
Did you wrap the ipv6 address inside "[]" brackets? Entering "http://[2606:2800:220:1:248:1893:25c8:1946]" (example.com) is working fine on my side, however http://2606:2800:220:1:248:1893:25c8:1946 will be sent to your default search engine. This is normal behavior, since the browser cannot differentiate between ipv6 block separators and added port number because both use ":".

**Comment by rebron** [comment] 2021-05-07 22:24
Closing, looks it's working as intended. Thanks @alekny

**Closed by rebron** 2021-05-07 22:24 UTC
Labels: OS/Desktop

**Comment by TheDiscordian** [comment] 2021-05-07 23:07
I don't understand why it'd default to searching it. You're talking about the port, but I'm talking about the URI, the prefix. Surely you must be able to detect a URI prefix like `http://` and simply not search for it, but instead give some other error? I can't imagine a scenario where a user is typing out `http://` at the beginning of their Google search.

If it's working as intended then so be it. However it's in my opinion very user un-friendly, and easily fixed.
