### ISSUE TITLE
Add native web page translator

### ISSUE THREAD

**Issue by sayedarifuddin** [brave/brave-browser#10302] opened 2020-06-16 14:22 UTC
## Feature request
Similar to Google Chrome and Microsoft Edge, native translator can bring a better webpage translation experience than what Google Translator extension does.

**Comment by ajgraves** [comment] 2022-04-07 16:58
> Vivaldi's built-in translator works great, including on Android and, according to Vivaldi, its self-hosted by them. I know of literally dozens of people who switched to vivaldi on android as its the only browser that does both translation and ad blocking. People previously had to choose one or the other, some had two browsers installed just to be able to use both features.
> 
> Even on desktop, recommending the google extension doesnt seem to be a very good solution for what is supposedly a privacy focused browser. Why cant brave implement a similar solution to Vivaldi? I feel this is something that brave, being American based, maybe doesnt understand how huge it is. For the vast majority of people I know, its unconceivable to not have access to a translation feature, even if they have to have a secondary browser installed just for that. Now, with Vivaldi doing also ad blocking, the other big feature peoole want, theres no reason to use anything else on Android, except of course for brave reawards which is why Id hope brave someday sees the light on this matter

I agree fully with @megamster, in fact, I was just having this exact same conversation with someone the other day. Vivaldi was able to add built-in translation that still respects end user privacy. I would absolutely love if Brave did the same thing, and bring it to iOS mobile as well! (no Vivaldi on iOS unfortunately)

**Comment by rebron** [comment] 2022-12-14 05:09
Closing as duplicate of https://github.com/brave/brave-browser/issues/23813 

Brave Translate was added in version 1.43.67 in August of this year for Windows/macOS/Linux and Android.

**Closed by rebron** 2022-12-14 05:09 UTC
Labels: feature/translate, priority/P4, feature-request, OS/Desktop
