### ISSUE TITLE
"Shields" text in Trackers and ads panel is not translated 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#22550] opened 2022-04-26 04:31 UTC
## Description 

Found while testing https://github.com/brave/brave-browser/issues/22514
Shields text in Trackers and ads panel is not translated in other locales

## Steps to Reproduce

   1. Set OS locale to France/Germany/Hindi/Kannada
   2. Clean profile 1.38.x
   3. Open any site and click on trackers and ads count
   4. Shields text in Trackers and ads panel is not translated in other locales

## Actual result:

Shields text in Trackers and ads panel is not translated in other locales
![image](https://user-images.githubusercontent.com/38657976/165219489-b32988e7-c007-4f62-ba95-64eeb455f7bf.png)

![image](https://user-images.githubusercontent.com/38657976/165225557-cce34ab4-256d-4dd2-90ca-9c7d3b6aa6a4.png)

## Expected result:

Shields text in Trackers and ads panel should be translated to other locales

![image](https://user-images.githubusercontent.com/38657976/165221352-5d15218e-1060-4293-80d3-061676de1538.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.38.106 Chromium: 101.0.4951.41 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
Betriebssystem | Windows 10 Version 21H2 (Build 19044.1645)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin

**Comment by mkarolin** [comment] 2022-04-26 14:40
I am not sure if this is intentional, but that string (`IDS_BRAVE_SHIELDS` in `components/resources/brave_shields_strings.grdp`) is marked as `translateable="false"`. Maybe because we are trying to get `Brave` out of that string in `brave/components/brave_shields/resources/panel/components/tree-list/index.tsx`:
<pre>
<span>{getLocale('braveShields').replace('Brave ', '').trim()}</span>
</pre>

So this is not a missing translation issue. This needs to get addressed in code.

cc: @nullhook

**Comment by btlechowski** [comment] 2022-04-26 20:30
Reproduced in Polish PL locale, for `ads and trackers` and for `scripts blocked`

Brave | 1.38.107 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/165386769-f68ab9db-fd93-414b-aba6-c5c9d945698a.png)
![image](https://user-images.githubusercontent.com/34715963/165386825-fcc4337f-c223-456e-b537-929d0bc1fcbc.png)

**Comment by nullhook** [comment] 2022-05-20 21:22
"Shields" is part of the product name and I'm not sure we should translate this. 
Previous shield had "Back" as the button label I believe

**Comment by mkarolin** [comment] 2022-05-24 00:36
According to the style guide:

> Brave feature names are uppercase, and we always translate (or transliterate) them into other languages. The only exception is the Brave name itself—this should never be translated.

cc: @rmcfadden3 to confirm

**Comment by rmcfadden3** [comment] 2022-05-24 01:27
@mkarolin — thx for checking. So, yes, this was the rule. But @laurentiugruia is overseeing localization strategy now, and I'm not sure if that rule has changed. @laurentiugruia — wdyt on this one?

**Comment by laurentiugruia** [comment] 2022-05-25 16:10
Confirming the rule from the style guide has not changed.

**Comment by petemill** [comment] 2022-08-31 04:41
@laurentiugruia @rmcfadden3 As per my comment at https://github.com/brave/brave-core/pull/14768#pullrequestreview-1091286517, is it therefore logical to only have the product name translated (e.g. "Shields") and we prefix the word "Brave" ourselves in the UI? Would Brave always precede the translated product name, in all languages?

**Comment by laurentiugruia** [comment] 2022-08-31 12:59
@petemill In some languages Brave precedes the translated "Shields", in other languages it comes after so I think the solution would be to have "Brave Shields" as the string to translate. 
Translators will then only translate "Shields" per the Style Guide and handle this situation.

**Closed** 2022-09-28 01:02 UTC
Labels: l10n, priority/P2, QA/Yes, QA/Test-Plan-Specified, regression, OS/Desktop

**Comment by stephendonner** [comment] 2022-10-24 20:48
## Verified `PASSED` using 

Brave | 1.46.76 Chromium: 107.0.5304.62 (Official Build) beta (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.46.76`
2. launched Brave (in English)
3. loaded `cnn.com` 
4. set respective languages as the primary one, below, via `Apple` -> `System Preferences` -> `Language & Region`
5. clicked on the `Shields` icon in the URL bar
6. clicked on the `Blocked-cookies count`
7. looked at the translated string for `Shields`

#### Confirmed all were translated, except for German, which I'll spinoff as a separate issue and cross-reference, here.

`French` | `German`(*) | `Hindi` | `Kannada`
----------|-----------|--------|-----------
<img width="1115" alt="Capture d’écran 2022-10-24 à 1 19 15 PM" src="https://user-images.githubusercontent.com/387249/197625022-55f1ad6c-d6c4-491c-a750-24d2bb5a6a0d.png"> | <img width="1115" alt="Bildschirmfoto 2022-10-24 um 1 23 44 PM" src="https://user-images.githubusercontent.com/387249/197625389-ee1db1ed-4a94-4376-8617-b45413e85968.png"> | <img width="1115" alt="स्क्रीन शॉट 2022-10-24, अ 1 26 04 पर" src="https://user-images.githubusercontent.com/387249/197625467-815b9b81-bc21-46de-a91e-233288a37a7d.png"> | <img width="1115" alt="Screen Shot 2022-10-24 at 1 37 28 PM" src="https://user-images.githubusercontent.com/387249/197625583-061ba7c8-eae0-4bbc-b463-14c5bb0fca07.png">

**Comment by stephendonner** [comment] 2022-10-24 21:24
Logged https://github.com/brave/brave-browser/issues/26216
