### ISSUE TITLE
Installation binaries / Support for Arch based linux distribution

### ISSUE THREAD

**Issue by arjunvijayanathakurup** [brave/brave-browser#9956] opened 2020-05-27 04:43 UTC
## Description 

Brave Browser is not available on Arch-based Linux distribution. There seems to be a couple of AUR packages and snap installation packages, but they cannot be trusted. It would be great to have a stable release for Arch based distros.

**Comment by bsclifton** [comment] 2020-06-15 21:49
Thanks for the request, @arjunvijayanathakurup - I'm going to close this issue as a duplicate of https://github.com/brave/brave-browser/issues/1950

Please subscribe there for updates 😄 

You're probably going to want to use https://aur.archlinux.org/packages/brave-bin

**Closed by bsclifton** 2020-06-15 21:49 UTC
