### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by bilals12** [brave/brave-browser#35181] opened 2024-01-08 16:10 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.109 Chromium: 120.0.6099.144
Operating System: Mac OS X 14.1.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/e3b10a00-f4b8-4b0b-0000-000000000000

**Comment by bsclifton** [comment] 2024-03-06 06:17
Closing as a duplicate of https://github.com/brave/brave-browser/issues/35256

This has been fixed and should be good now 😄

**Closed by bsclifton** 2024-03-06 06:17 UTC
Labels: crash, OS/macOS, priority/P2
