### ISSUE TITLE
P3A - Click on `Skip welcome tour` isn't giving correct response value

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7262] opened 2019-12-07 00:30 UTC
## Description 

Found while testing #6285 
P3A - Click on `Skip welcome tour` isn't giving correct response value

Q3: Did you follow the on-boarding process
(Brave.Welcome.InteractionStatus)

1. Did not click within welcome screen
2. Clicked once
3. Clicked twice or more but did not make it to the end
4. Made it to end of on-boarding flow

## Steps to Reproduce

   1. clean profile 1.1.18
   2. click on skip welcome tour in on-boarding page
   3. reload the local-state file
   4. response value is displayed as 0 instead of  1 (Clicked once)

## Actual result:

response value is displayed as 0 instead of  1 (Clicked once)

## Expected result:
the response value should be displayed correctly

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.1.18 Chromium: 79.0.3945.56 (Official Build) (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @iefremov @bsclifton @rebron

**Comment by LaurenWags** [comment] 2019-12-07 00:49
Reproduces on macOS


Brave | 1.1.18 Chromium: 79.0.3945.56 (Official Build) (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | macOS Version 10.13.6 (Build 17G5019)

**Comment by iefremov** [comment] 2019-12-17 08:21
I think this is probably something expected since the aim of this metric is to understand whether users go through the onboarding process. So skipping the welcome tour means that they are not interested in scrolling through different screens. @davidtemkin could you please take a look at the issue?

**Comment by rebron** [comment] 2020-02-07 17:32
@davidtemkin re-ping. cc: @mattmcalister I think this is right where clicking skip is 0 instead of 1. We want to measure interaction of flowing through welcome flow and skipping should mean 0.

**Comment by mattmcalister** [comment] 2020-02-19 17:58
The question could be much more precise. I suggest we leave the question as is for now, as we can deduce what we need to know from the data we're currently collecting.

**Comment by iefremov** [comment] 2020-03-03 06:57
> The question could be much more precise. I suggest we leave the question as is for now, as we can deduce what we need to know from the data we're currently collecting.

@mattmcalister Can we just close this for now?

**Comment by bsclifton** [comment] 2020-03-11 18:41
Closing as I see a thumbs up emoji response from @mattmcalister 😄

**Closed by bsclifton** 2020-03-11 18:41 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, features/P3A
