### ISSUE TITLE
[Desktop] Unable to select search engine for Tor Window mode

### ISSUE THREAD

**Issue by BlueskyFR** [brave/brave-browser#10221] opened 2020-06-11 13:59 UTC
It is currently impossible to choose a custom search engine when using the Tor Window Mode when the computer is in french (OS: Windows 10).

How are the users supposed to change it anyway?

**Comment by bsclifton** [comment] 2020-10-27 22:31
Closing as duplicate of https://github.com/brave/brave-browser/issues/5794

**Closed by bsclifton** 2020-10-27 22:31 UTC
Labels: OS/Desktop, feature-request, feature/search, feature/tor
