### ISSUE TITLE
custom background images for newtabs

### ISSUE THREAD

**Issue by QWIILXEY** [brave/brave-browser#39712] opened 2024-07-12 09:07 UTC
### Platforms

Android, iOS

### Description

This request is pretty self explanatory but could this be a feature that gets implemented for android and ios?

**Comment by iccub** [comment] 2024-07-17 18:01
Duplicate of https://github.com/brave/brave-browser/issues/38361 https://github.com/brave/brave-browser/issues/26570

**Closed by iccub** 2024-07-17 18:01 UTC
Labels: feature-request, OS/Android, OS/iOS
