### ISSUE TITLE
Private and Tor windows NTP UI doesn't fill completely 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3322] opened 2019-02-12 13:31 UTC
## Description 

Private and Tor windows NTP UI doesn't fill completely. Issue originally reported by @NejcZdovc 

## Steps to Reproduce

   1. Install beta build
   2. Open a new Tor/Private window
   3. Shows white blank space at the bottom of the page

## Actual result:

Private:![image](https://user-images.githubusercontent.com/17010094/52638587-4a032d00-2ef8-11e9-9eed-06aba685ac29.png)
Tor:![image](https://user-images.githubusercontent.com/17010094/52638611-55eeef00-2ef8-11e9-9890-1ed44a1444af.png)

## Expected result:
UI should cover the entire page

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.60.26 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Linux/macOS

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on beta and dev

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @rossmoody @petemill

**Comment by btlechowski** [comment] 2019-02-13 21:09
Not reproducible on Windows 7 x64 and Windows 10 x64.

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 

![image](https://user-images.githubusercontent.com/34715963/52744054-da666e00-2fdb-11e9-8a5b-87b26bbd7758.png)

![image](https://user-images.githubusercontent.com/34715963/52744064-e3efd600-2fdb-11e9-80cb-65e76a24e039.png)

**Comment by kjozwiak** [comment] 2019-02-13 22:02
Noticed the same thing happening on my `macOS 10.14.2 x64` last night when I was using Tor windows. Using the following `Display` settings:

<img width="593" alt="screen shot 2019-02-13 at 5 01 50 pm" src="https://user-images.githubusercontent.com/2602313/52747122-1801d180-2fb1-11e9-8ab4-3df8b27d7815.png">

Example of the issue occurring (notice the white spaces at the bottom occurring):

<img width="1853" alt="screen shot 2019-02-13 at 4 59 27 pm" src="https://user-images.githubusercontent.com/2602313/52747066-f99bd600-2fb0-11e9-90ae-02f412649352.png">

**Comment by NejcZdovc** [comment] 2019-02-13 22:12
personally I think this should be release blocking for 0.60 as it looks really bad, specially on big screen

![image](https://user-images.githubusercontent.com/9574457/52747721-d0953880-2fe4-11e9-8229-c9cbc931da31.png)

**Comment by kjozwiak** [comment] 2019-02-13 22:19
@NejcZdovc agreed. Looks like it's a regression and doesn't happen on `0.59.35`. I double checked `0.59.35` and couldn't reproduce. This looks pretty bad and it's an obvious regressions. We're making the experience worse than it was one release before.

CCing @rebron on thoughts re: getting this fixed in `0.60.x`.

**Closed** 2019-02-14 19:37 UTC
Labels: QA/Yes, bug, design, feature/new-tab, regression, release-notes/include

**Comment by srirambv** [comment] 2019-02-18 10:53
Verification passed on 

Brave | 0.60.34 Chromium: 72.0.3626.109 (Official Build) beta(64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Linux

* Private and Tor window NTP UI fills correctly on all resolution sizes
