### ISSUE TITLE
Title Bar Buttons Moved Below After Update To 1.60.110

### ISSUE THREAD

**Issue by TakuyaSama** [brave/brave-browser#34086] opened 2023-11-03 11:12 UTC
## Description 

Just after updating to Brave 1.60.110, first time I opened Brave Browser, the title bar buttons buttons were moved from the bar where they were (along with the Searchbar, plugins, etc), to just below it.

## Steps to Reproduce

   1. Update to Brave 1.60.110.
   2. Open Brave.
   3. Search for the title bar buttons.

## Actual result:

![image](https://github.com/brave/brave-browser/assets/15946300/f7f1a308-d0f7-4c97-9d08-ca4fb4905859)

## Expected result:
Just as before the update, the title bar buttons should be aligned and on the same Y position as the bar.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

1.60.110

## Version/Channel Information:

Stable

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Didn't try.
- Can you reproduce this issue with the nightly channel? Didn't try.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No, but didn't try, since it's a GUI/UI issue.
- Does the issue resolve itself when disabling Brave Rewards? No, but didn't try, since it's a GUI/UI issue.
- Is the issue reproducible on the latest version of Chrome? Didn't try, the only Chromium-based web browser I use in my PCs is Brave.

**Comment by Emi-HoloGhostRevisionist88** [comment] 2023-11-03 15:05
https://github.com/brave/brave-browser/issues/33928
Already fixed on nightly.

**Comment by TakuyaSama** [comment] 2023-11-03 16:06
> #33928 Already fixed on nightly.

Nice to see it's already fixed.
When should be fixed then?
I'll close it then, given it's already fixed on Nightly?
Given it's a bug/an issue pretty obvious and disturbing, I think it should be fixed ASAP in the stable channel, don't you think?

**Comment by rebron** [comment] 2023-11-03 22:13
Closing as dupe of #33928 We'll get that fix uplifted to release asap.

**Closed by rebron** 2023-11-03 22:13 UTC
Labels: OS/Linux, OS/Desktop, feature/vertical-tabs
