### ISSUE TITLE
Brave window is shaking when popup dialog is shown

### ISSUE THREAD

**Issue by Blagoja95** [brave/brave-browser#36313] opened 2024-02-22 21:38 UTC
## Description 

When trying to close Brave window with multiple tabs, popup dialog shows which makes Brave window shake making user unable to use dialog (see attached video).
When window is in full screen mode everything is fine but when window is occupying half of a monitor size this problem occurs. 

This problem also happens when bookmarks dialog is opened.

Maybe similar issue #15381

## Steps to Reproduce:
   1. Open brave browser set window size to half of screen width
   2. Open two or more tabs
   3. Try to close Brave window 

## Actual result:
 Window start shaking and making user unable to use browser.

## Expected result:
Should not be shaking.

## Reproduces how often: 
Can be constantly reproduced with ease.

## Brave version (brave://version info)
Brave	1.62.165 Chromium: 121.0.6167.184 (Official Build) (64-bit) 
Revision	646e9a49ef45084cb2341eb1e9afabc339004a27
OS	Linux

[Screencast from 2024-02-22 22-11-32.webm](https://github.com/brave/brave-browser/assets/33908472/324af2f4-6fac-4151-b08e-684cec3b599c)

**Comment by Blagoja95** [comment] 2024-02-23 11:42
I tried it and I can't reproduce this issue on Windows machine

Brave | 1.63.161 Chromium: 122.0.6261.57 (Official Build) (64-bit)
Revision | 37b02b4a373f40114e70cc034e491bcc8380f23a
OS | Windows 11 Version 21H2 (Build 22000.2777)

**Comment by rebron** [comment] 2024-02-23 22:23
@Blagoja95 Can you try again with 1.63.162 on your Linux machine. Should be fixed with that version with the Chromium update to 122.0.6261.69.

**Comment by rebron** [comment] 2024-02-23 22:26
Going to close this one out as a dupe of https://github.com/brave/brave-browser/issues/35690 but please reopen @Blagoja95 if you're still seeing it in 1.63.x

**Closed by rebron** 2024-02-23 22:26 UTC
Labels: OS/Desktop
