### ISSUE TITLE
[Desktop] Lines glitch on Youtube player

### ISSUE THREAD

**Issue by tankmohit** [brave/brave-browser#9466] opened 2020-04-26 05:29 UTC
## Lines are showing while playing a youtube video. 

[Screenshot](https://imgur.com/inMYscG)

## Possible steps to Reproduce (It occurs randomly)
1. Open a youtube video
2. click on a large player
3. make video play full screen
4. exit full screen mode
5. repeat steps 3 & 4 couple of times
6. hover mouse on progress bar of a video
7. lines as shown in screenshot should appear.

## Actual result:
+ It should not show lines or glitch

### Tried to reproduce on following systems
1. Ubuntu 20.04
2. Fedora 31
3. Arch Linux

## Brave version (brave://version info) [From Arch Linux]
Brave	1.7.98 Chromium: 81.0.4044.113 (Official Build) unknown (64-bit)
Revision	e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS	Linux
JavaScript	V8 8.1.307.28
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
Command Line	/usr/lib/brave-bin/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=WebUIDarkMode,PasswordImport,AutoupgradeMixedContent,PassiveMixedContentWarning,SimplifyHttpsIndicator,MixedContentSiteSetting,DnsOverHttps --disable-features=AutofillServerCommunication,TextFragmentAnchor,LookalikeUrlNavigationSuggestionsUI,SmsReceiver,AudioServiceOutOfProcess,AllowPopupsDuringPageUnload,NotificationTriggers,VideoPlaybackQuality --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path	/usr/lib/brave-bin/brave
Profile Path	/home/mohit/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:
* Stabel channel

- Can you reproduce this issue with the current release?
- Yes

- Can you reproduce this issue with the beta channel?
- Not tested

- Can you reproduce this issue with the dev channel?
- Not tested

- Can you reproduce this issue with the nightly channel?
- Not tested

**Comment by ryanbr** [comment] 2020-04-26 08:02
Which Graphics card do you have? Are you using open source/binarys for the graphic card drivers?

Can you re-test with Hardware acceleration in `Brave Settings`

**Comment by tankmohit** [comment] 2020-04-28 05:56
Hardware acceleration stops the glitch but affects the overall performance.

**Comment by sam5558** [comment] 2020-05-04 11:53
Hello,
I had the same issue, but when i disabled Hardware acceleration the lines on youtube videos dissapeared.
However, i'm concerned about disabling Hardware acceleration and the impact on my daily professional & personal usage.
So is it possible to find a fix for this issue & keep Hardware Acceleration enabled ? 

PS:
I'm using _**Version 1.8.86 Chromium: 81.0.4044.129 (Official Build)**_ on a _**Linux Mint 19.1 Tessa**_

**Comment by Pross** [comment] 2020-07-18 22:21
Still an issue for me
https://imgur.com/a/jE5EbpD
Version 1.13.6 Chromium: 84.0.4147.85 (Official Build) unknown (64-bit)

Turning off hardware acc makes absolutely no difference.

**Comment by bsclifton** [comment] 2020-07-20 01:58
The best recommendation I have for when artifacts like this show up (and disabling HW acceleration DOES work) is to check your drivers. Updating on Windows to latest version or on Linux trying a different driver (ex: try proprietary driver, etc)

**Comment by Pross** [comment] 2020-07-20 02:33
I dont have the option of using a different driver as im using the intel driver. Im happy to provide any info needed.

**Comment by salehif** [comment] 2020-08-06 20:48
same issue here on Windows 10
using Brave Version 1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)

seems you are using "Fingerprinting blocked (aggressive)" 
to fix the problem is too easy, on Youtube website switch to "Fingerprinting blocked (standard)" seems fix my problem after trying, should fix yours. If you watch Youtube on popup on a website, you must change it to "FB standard" too

BTW, HW acceleration is enabled

**Comment by Pross** [comment] 2020-08-06 23:18
>seems you are using "Fingerprinting blocked (aggressive)"

Ok, yes that did actually work! Changing to standard did stop the issue.

**Closed** 2021-02-02 05:21 UTC
Labels: OS/Desktop, OS/Linux, gpu/driver, priority/P5, workaround/disable-hw-acceleration
