### ISSUE TITLE
Option to Only use Sponsored Images

### ISSUE THREAD

**Issue by jhreis** [brave/brave-browser#10563] opened 2020-07-04 13:26 UTC
## Description 

I love the sponsored images and as a longterm Brave user, find them less repetitive (seeing the same ~12 rotating images starts making the browser feel bland). I would love the option (on all platforms) to _only_ see sponsored images.

## Steps to Reproduce

   1. Open new tab
   2. See non-sponsored image
   3. Pout

## Actual result:

See non-sponsored image

## Desired result:

See sponsored image

## Reproduces how often: 

75% 😂(since sponsored percentage is 25%)

## Brave version (brave://version info)

All with sponsored images

## Miscellaneous Information:

Pseudo-related: https://github.com/brave/brave-browser/issues/10264

**Comment by mlinksva** [comment] 2020-12-24 20:43
I strongly dislike generic background images but am very curious to see sponsored images that help pay for Brave development. For the settings UI, "Show Sponsored Images" could be outdented, implying and actually being a setting independent of "Show Background Images".

**Comment by tmancey** [comment] 2021-07-30 20:27
Closing issue as a duplicate of https://github.com/brave/brave-browser/issues/16228 as users can now select 0 ad notifications per hour.

**Closed by tmancey** 2021-07-30 20:27 UTC
Labels: OS/Desktop, closed/duplicate, feature-request, feature/ads
