### ISSUE TITLE
YouTube notifications in Windows 10 dead as a doornail in Release and Beta builds 

### ISSUE THREAD

**Issue by snowbound** [brave/brave-browser#21452] opened 2022-03-03 17:21 UTC
## Description 
Toast Notifications and Action Center notifications no longer work

## Steps to Reproduce

   1. Go to YouTube subscribe to several channels and ensure notifications are set to all
   2.  Right mouse click on lock on Youtube.com and ensure notifications are allowed
   3.  Make sure in Windows10 21H2 that notifications are allowed for Brave in Action Center as well as Notificaiton banners

## Expected result:
One should get Notification Banners as well as notification in the Windows10 Action Center

## Reproduces how often: 
Happens with every subscribed YouTube channel where notifications are set to ALL

## Brave version (info found on brave://version)
[Version 1.36.109 Chromium: 99.0.4844.51 (Official Build) (64-bit)](https://brave.com/latest/) also occurring in the Brave ebta build as well

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? YES

## Miscellaneous Information:
This was working fine until March 1, 2022 then all notifications from YouTube ceased working

**Comment by rebron** [comment] 2022-03-09 19:06
Closing as dupe of #2362

**Closed by rebron** 2022-03-09 19:06 UTC
Labels: needs-investigation, OS/Windows, feature/notifications, OS/Desktop
