### ISSUE TITLE
The most recent version as of today, the download page in brave browser, is broken

### ISSUE THREAD

**Issue by Xyncgas** [brave/brave-browser#5668] opened 2019-08-15 03:29 UTC
Yes I have searched it and no issues have been stated on this

## Description 

The download page is not working, when you go to see the downloads, there is nothing to display (which there were a lot) and they will show up again after you have the tap for the download page to be opened and download something at the mean while.

## Steps to Reproduce

   1.  Open the download tap in the newest version of brave browser.
        Nothing shows up.

   2. Go to twitch.tv and right click the page, then save a html off the page.
       Before doing that keep the tap for the download page opened.

   3. You see all your previous download history now.

## Actual result:
See screenshot

## Expected result:
Showing thing / history of the things that I have downloaded

## Reproduces how often: 
Everytime, for me, ever since update

## Brave version (brave://version info)
Version 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)

## Version/Channel Information:
I don't know

- Can you reproduce this issue with the current release?
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
I am lazy I wont try
- Does the issue resolve itself when disabling Brave Rewards?
I am lazy I wont try
- Is the issue reproducible on the latest version of Chrome? 
I am lazy I wont try

## Miscellaneous Information:
I love your browser it's feels safer for me while I watch my anime waifu and ero-manga and poke around the internet all day

**Comment by Xyncgas** [comment] 2019-08-15 03:31
Expected :
![image](https://user-images.githubusercontent.com/35312807/63071025-516cb880-bed2-11e9-80b1-e610dcf2e9dc.png)
Actual :
![image](https://user-images.githubusercontent.com/35312807/63071045-719c7780-bed2-11e9-967b-a66930599c4b.png)

**Comment by rebron** [comment] 2019-08-15 04:28
Closing, dupe of https://github.com/brave/brave-browser/issues/5330. @Xyncgas will +1 that issue for you.

**Closed by rebron** 2019-08-15 04:28 UTC

**Comment by Xyncgas** [comment] 2019-08-15 04:30
Yeah alright

**Comment by Xyncgas** [comment] 2019-08-15 04:30
I am watching as for this
Also will see what I can do
