### ISSUE TITLE
  bravebrowser翻译功能没用

### ISSUE THREAD

**Issue by biange200** [brave/brave-browser#25400] opened 2022-09-14 10:56 UTC
![Screenshot_20220914_185246.jpg](https://user-images.githubusercontent.com/37582806/190135936-8ea0fd94-d5ce-4ac3-9dcc-b2bfedd5b630.jpg)

 试过多个网站都是无法翻译

**Comment by bsclifton** [comment] 2022-09-15 22:08
Closing as a duplicate of https://github.com/brave/brave-browser/issues/24303

**Closed by bsclifton** 2022-09-15 22:08 UTC

**Comment by biange200** [comment] 2022-09-15 23:07
Thank you for your reply brave sometimes can translate sometimes the translation function does not work, you need to try more times to be able to translate function is very unstable can not be translated more oftenI would like to ask brave support scripting function? For example, tampermonkey获取Outlook for Android
