### ISSUE TITLE
Remove Search Tabs button from Brave

### ISSUE THREAD

**Issue by BeefMarinade** [brave/brave-browser#16135] opened 2021-05-28 22:23 UTC
## Description 

It's like a Pimple on your face!!!
How to remove Search Tab button on Brave Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit)
https://winaero.com/remove-search-tabs-button-from-google-chrome-title-bar/
chrome://flags/#enable-tab-search
gets me nothing but proves it can be removed

**Comment by Tonev** [comment] 2021-05-29 04:24
https://github.com/brave/brave-browser/issues/16007

**Comment by Johann999** [comment] 2021-05-29 14:51
Edge 91.0 does not have this tab search icon.

**Comment by TheAresjej** [comment] 2021-05-30 03:12
Brave should not have visible useless new buttons from chromium.

**Comment by vrindavan** [comment] 2021-06-02 10:17
Exactly. Brave is making me switch to Firefox more and more

**Comment by Johann999** [comment] 2021-06-23 10:05
The tab search icon is always in version 1.26 still there. Please remove it.

Incidentally, it is not available in Edge, Opera and Vivaldi.

**Comment by seanbebliss** [comment] 2021-06-25 03:21
Version 1.25.70 Chromium: 91.0.4472.77 (Official Build) (64-bit) (p.s. - NEVER UPDATE AGAIN INVASIVE CIRCLE TRIANGLE ICON HATE SEEING IT MAKE IT GO AWAY! ROLL BACK TOO TECHNICAL (where easy install old version? NONE!!!!). YOU BREAKING MY MIND STUPED ALWAYS VISIBLE BUTTON!)

**Comment by rebron** [comment] 2021-08-20 19:00
Closing as dupe of #16007 and fixed in 1.29.x to be released on August 31. Can check out beta/nightly too.

**Closed by rebron** 2021-08-20 19:00 UTC
Labels: OS/Desktop
