### ISSUE TITLE
LastPass Browser Extension stopped working on Brave desktop browser for Windows

### ISSUE THREAD

**Issue by nopapersplease** [brave/brave-browser#39960] opened 2024-07-24 02:47 UTC
### Description

The LastPass browser extension stopped working for me in Brave browser today. Reviews of the extension on the Chrome Web Store suggest that the issue started within the last week. LastPass doesn't seem interested in fixing the issue. Maybe it's not their issue to fix. Maybe Brave made a change and broke the extension.

### Steps to reproduce

1. Install LastPass extension from Chrome Web Store and pin it.
2. Click the LastPass extension icon to log in.

### Actual result

A tiny white square appears below the extension icon, but the login page does not load.
![Screenshot 2024-07-23 214047](https://github.com/user-attachments/assets/e79b48b0-25c4-475c-867e-0db8843939c7)

### Expected result

LastPass extension login screen appears.
![Screenshot 2024-07-23 214155](https://github.com/user-attachments/assets/dc76d2de-3834-47d8-b844-24f71c4d0f7e)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Release Notes v1.67.134 (Jul 17, 2024)

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Inability to use the LastPass extension on Brave will force me to switch to another browser. I really don't want to use Chrome but the extension works with Chrome so I'll have no other choice. LastPass is the only password manager that I can use both at home and at work.

**Comment by refeax** [comment] 2024-07-24 12:41
this is the reason why i stopped using lastpass and canceled my subscription. I recommend using "Proton Pass" which does the exact same thing but you dont have to pay to use it on multiple platforms

**Comment by nopapersplease** [comment] 2024-07-24 13:35
Thank you for the suggestion. Switching from LastPass is not a viable option for me at this time. Not only do I use it for secrets but I also use it for two-factor authentication. I also just added two new members to my LastPass family. If I switch I'm impacting more than just me. Finally, LastPass is the only service of its kind that I can access from my work computer. I can't make the switch without major headaches.

I opened the ticket to LastPass support and they tell me that they're aware of the problem and they're working on it. So, until then, I'll switch to Firefox browser and return to Brave as soon as the problem is fixed.

Jul 24, 2024 7:42:17 AM refeax - notifications at github.com ***@***.***>:

**Comment by refeax** [comment] 2024-07-24 13:48
I dont mean to be an advisory for Proton but as far as I know everything you mentioned does exist in the Proton Pass free version.
They have notes, 2FA and the ability to import your passwords from Lastpass.
But I do understand why it could be a headache trying to navigate with multiple people on this.

**Comment by bsclifton** [comment] 2024-07-24 18:01
Hi folks - this is a duplicate of https://github.com/brave/brave-browser/issues/39759

We released a fix today which should be live. Please make sure to update Brave and let us know how it goes! Thanks 😄

**Closed by bsclifton** 2024-07-24 18:01 UTC
Labels: OS/Desktop
