### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by xwilders** [brave/brave-browser#34943] opened 2023-12-16 15:53 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.104 Chromium: 120.0.6099.115
Operating System: Mac OS X 14.2.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Move any tab outside of the left bar (in order to make a new window or merge it into a new window)
2. The moment you start moving the tab out, it crashes
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/95ec0400-100a-300b-0000-000000000000

**Comment by rebron** [comment] 2023-12-21 18:00
closing as dupe of https://github.com/brave/brave-browser/issues/34909.
Hi @xwilders  Can you update to the latest 1.61.109 that released today and see if this is still an issue for you.

**Closed by rebron** 2023-12-21 18:00 UTC
Labels: crash
