### ISSUE TITLE
address bar orange auto completion, cannot change url

### ISSUE THREAD

**Issue by markg85** [brave/brave-browser#30031] opened 2023-04-27 13:16 UTC
Hi,

This is vague to describe so i hope an image helps:
![image](https://user-images.githubusercontent.com/49061/234871885-4ef65642-29c4-409f-8dce-4e2a2886c38e.png)

What i typed in the above case is "exchange".
The part in the address bar is that top line in the image. The part brave highlights is the second line.

So it shows me everything i need to know but it **doesn't allow me to edit the url**.

This is super annoying. I might want to go to that side but to some other part in the url that i happen to know about.

Couple questions:
1. What is this orange highlight weirdness? It happens on only very few sites it seems. Many of the other sites i visit have no such thing at all.
2. How can i disable it?

Best regards,
Mark

**Comment by markg85** [comment] 2023-05-15 19:50
?? Anyone ??

**Comment by markg85** [comment] 2023-05-29 14:07
ping @kjozwiak 
Sorry, just pinging someone from brave on this.

I hate this feature and i really want to turn it off. What's it called and how do i get rid of it?
Thanx!

**Comment by jpovixwm** [comment] 2023-06-02 06:47
I have the same issue. This "feature" (more like annoyance) wasn't always there, it was introduced at some point during the last 12 months or so. Previously, you were able to hit <kbd>End</kbd> and the caret would go to the end of the autocompleted entry and you could then change where you want to navigate to. In the case of OP's screenshot, you could for example change the currency pair to `ETH_USDT` and hit enter.
This is no longer possible with this new autocomplete because there's no way to edit the autocompleted entry.
I may try to narrow down the version of Brave this first appeared in, if I get nothing better to do in the evening.

**Comment by jpovixwm** [comment] 2023-06-03 09:21
Duplicate of #28198. This was first present in Brave v1.47.164 (Chromium v109.0.5414.74) (not including beta and nightly builds). The preceding release v1.46.153 (Chromium v108.0.5359.128) didn't do this.
This can also be observed in vanilla chromium, so it doesn't really have anything to do with Brave, but it would be nice if Brave could implement a fix for this.
I guess the next step would be to `git bisect` these two chromium revisions to pinpoint the commit that introduced this change.

**Comment by markg85** [comment] 2023-06-04 13:41
@jpovixwm Thank you for your help!

That's an interesting finding (it happening on chromium too).
I did have a quick look at commits between these two chrome version https://github.com/chromium/chromium/compare/108.0.5359.128...109.0.5414.74

But github isn't suitable for that many commits (5000+). Haven't tried on the command line yet.
It's probably a commit containing at least the work "omnibox" as that's what the address bar is called.

**Comment by jpovixwm** [comment] 2023-06-04 21:20
Actually, this issue is more complex than I initially assumed. This feature can be seen in even older chromium builds, for example v103. (That's not to say that it first appeared in v103, I just didn't check with versions older than that)
So the fact that this only surfaced in Brave after the update from chromium 108 to chromium 109 is even more puzzling.
To the best of my knowledge, the situation is:
- this thing can be seen in vanilla chromium v109, v108, as well as older versions, such as v103
- it cannot be seen in Brave built with chromium v108 and older
- it can be seen in Brave built with chromium v109 and newer

I really have no idea how to find the culprit anymore.

**Closed** 2023-06-05 20:00 UTC
Labels: OS/Desktop
