### ISSUE TITLE
Incognito still being generated from translated strings

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#2147] opened 2018-11-15 01:59 UTC
This issue https://github.com/brave/brave-browser/issues/738 changed Incognito -> Private for all source strings, but the translations are still being preserved. I think we need to add some 1 time code to clear out the translations, and maybe also to make sure we don't re-upload them when we do `npm run push_l10n`

**Comment by LaurenWags** [comment] 2019-10-14 19:19
Still reproduces with 

Brave | 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | macOS Version 10.13.6 (Build 17G5019)

Noticed English (UK) uses `Incognito` instead of `Private` terminology.

**Comment by GeetaSarvadnya** [comment] 2019-10-15 07:55
Reproduced in Windows 10 x64 - 0.69.135

![image](https://user-images.githubusercontent.com/38657976/66811744-3dcfe380-ef4f-11e9-8c7b-887c60d1cbc4.png)

**Comment by btlechowski** [comment] 2019-10-21 13:57
Dupe of https://github.com/brave/brave-browser/issues/2147

**Comment by btlechowski** [comment] 2019-10-21 13:59
I closed the wrong issue. Sorry.

**Comment by btlechowski** [comment] 2019-10-21 14:05
Still reproducible on Linux https://github.com/brave/brave-browser/issues/6564

Affected locales: en_GB/en_AU/en_NZ

![image](https://user-images.githubusercontent.com/34715963/67199803-70238a00-f402-11e9-8c50-3ae8e2970e59.png)

Brave | 0.70.119 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Ubuntu 18.04 LTS

**Comment by petemill** [comment] 2019-11-01 18:55
Hmm, I'm investigating this but not sure I understand what happened yet.

About a year ago, we would have submitted changes in the source US strings from e.g. "New Incognito Window" to "New Private Window".

However, in transifex looks like we (or it automatically) accepted the original translations for certain languages. So British English has the string translated (and approved) as "New Incognito Window"

<img width="50%" src="https://user-images.githubusercontent.com/741836/68048723-6cafbe80-fc9e-11e9-8b62-cacbf79ed2a6.png" />


Similarly, spanish
<img width="50%" src="https://user-images.githubusercontent.com/741836/68048548-0460dd00-fc9e-11e9-80bd-adfcf5b4c44e.png" />

But German _does_ have the correct translation
<img width="50%" src="https://user-images.githubusercontent.com/741836/68048687-586bc180-fc9e-11e9-8d88-fd69a231da79.png" />

**Comment by bsclifton** [comment] 2019-11-08 16:04
Fixed with https://github.com/brave/brave-core/pull/3922

**Closed by bsclifton** 2019-11-08 16:04 UTC
Labels: 1.0, QA/Yes, l10n, priority/P3

**Comment by GeetaSarvadnya** [comment] 2019-11-11 02:31
Verification passed on

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

![image](https://user-images.githubusercontent.com/38657976/68556746-7e8d2080-0459-11ea-96ba-895c4c66c1ed.png)
