### ISSUE TITLE
NTP clock shows 24hrs format irrespective of device date/time format settings

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2530] opened 2018-12-13 12:58 UTC
## Description 

NTP clock day period component (AM / PM) fail on Linux 

## Steps to Reproduce

   1. Clean install 0.58.12
   2. Open a new tab 
   3. Checks how well you know 24hr format

## Actual result:

https://drive.google.com/open?id=1GMl-4xRTovTsy_SMxix0dTRZ5TLAWuGf

## Expected result:
Should show smililar to other platfroms

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @petemill @brave/legacy_qa

**Comment by petemill** [comment] 2018-12-13 13:09
This isn’t to do with AM / PM not showing but to do with the 24hr time showing. We wouldn’t show AM / PM with 18:00 because it’s implied. So the issue is that the time format is in 24hr on Linux? Is this reproducible in 0.57 or previous 0.58?

**Comment by srirambv** [comment] 2018-12-13 13:11
Yup its always in 24hr format on all channels.

**Comment by LaurenWags** [comment] 2018-12-13 21:17
@srirambv actually I see 12hr format, regardless of system setting (on both mac and linux):
MacOS:
![screen shot 2018-12-13 at 1 29 33 pm](https://user-images.githubusercontent.com/28145373/49967997-70095280-fef2-11e8-98bd-96cc0690225b.png)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X


Linux (Ubuntu):
![screen shot 2018-12-13 at 4 14 13 pm](https://user-images.githubusercontent.com/28145373/49968008-7992ba80-fef2-11e8-8d56-a320f081d4d7.png)
![screen shot 2018-12-13 at 4 15 04 pm](https://user-images.githubusercontent.com/28145373/49968021-84e5e600-fef2-11e8-81ef-657d9be70ccb.png)

**Comment by btlechowski** [comment] 2018-12-18 02:42
@srirambv I see 12hr format regardless of format setting. 
![image](https://user-images.githubusercontent.com/34715963/50128805-e56c7e80-0276-11e9-8dff-876326528d3a.png)

Tested on Ubuntu 17.10

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Linux

**Comment by kirkins** [comment] 2018-12-23 04:11
Same as @btlechowski always shows 12hr format even when on 24hr clock for system.

Version 0.59.9 Chromium: 72.0.3626.17 (Official Build) unknown (64-bit)

Ubuntu 18.04

**Comment by rebron** [comment] 2019-01-22 17:16
@srirambv Is this still a problem w/ 60.16? New tab page just landed.

**Comment by srirambv** [comment] 2019-01-24 15:24
@rebron sadly nope. I still see 24hr format 
![screenshot from 2019-01-24 20-53-23](https://user-images.githubusercontent.com/17010094/51688258-34e25f00-201a-11e9-990b-b61ae9bd00e4.png)

**Comment by kjozwiak** [comment] 2019-01-29 23:41
Getting 24hrs on my Mint 19.1 x64 laptop as well. Using the following build:

Brave | 0.60.18 Chromium: 72.0.3626.71 (Official Build) beta(64-bit)
-- | --
Revision | f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}
OS | Linux

![screenshot from 2019-01-29 18-39-06](https://user-images.githubusercontent.com/2602313/51948160-747fc100-23f5-11e9-9344-2b63e0d4fa33.png)

**Comment by apisarek** [comment] 2019-06-10 20:10
On my computer I have 12h clock format, without AM/PM marker. I would like to have 24h clock format, that's what I use in my system clock.
```
➜  ~ cat /etc/os-release 
NAME="Linux Mint"
VERSION="19.1 (Tessa)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.1"
VERSION_ID="19.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tessa
UBUNTU_CODENAME=bionic
```

**Comment by bsclifton** [comment] 2019-06-24 05:15
Related / possible dupe of https://github.com/brave/brave-browser/issues/1308

**Comment by cezaraugusto** [comment] 2019-08-29 17:53
Closing as a duplicate of #1308. Please see my https://github.com/brave/brave-browser/issues/1308#issuecomment-525482063 regarding what we can/cannot do in this regard.

**Closed by cezaraugusto** 2019-08-29 17:53 UTC
Labels: OS/Linux, QA/Test-Plan-Specified, QA/Yes, priority/P4, release-notes/include, release/not-blocking
