### ISSUE TITLE
don't load unused built-in extensions

### ISSUE THREAD

**Issue by bughit** [brave/brave-browser#4612] opened 2019-05-26 20:48 UTC
## Description 
In addition to rewards (#3436), the following extensions/processes should not be loaded when their functionality is not activated.

- Utility: Bat Ledger Service (nothing related to BAT has been activated)
- Utility: Bat Ads Service (nothing related to BAT has been activated)
- Extension: Brave Sync (sync has not been activated)

PDF viewer, can probably be covered by #4350 (load on demand and unload when not in use)

## Brave version (brave://version info)

Brave: 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)
Revision: 78e4f8db3ce38f6c26cf56eed7ae9b331fc67ada-refs/branch-heads/3729@{#1013}
OS: Windows 7 Service Pack 1 Build 7601.24443

**Comment by rebron** [comment] 2019-06-07 16:01
Closing as a duplicate of #3436 where we'll handle thee cases as well. I'll +1 #3436 too. 
PDF should no longer be an issue.

**Closed by rebron** 2019-06-07 16:01 UTC

**Comment by bughit** [comment] 2019-10-24 20:06
@rebron @petemill 

This issue was closed as a dup of #3436, but the fix (brave/brave-core#3698) appears to be rewards specific. If that's the case, please reopen.

**Comment by bughit** [comment] 2019-11-13 17:18
@rebron Is there a problem with reopening this? #3436 is fixed in 1.0 but this isn't.

**Comment by bsclifton** [comment] 2019-12-31 18:36
@bughit sorry for the long turn-around on a response ☹️ The functionality you're looking for should be covered with https://github.com/brave/brave-browser/issues/5429 👍
