### ISSUE TITLE
Cast is not disabled on toggling off media router switch in extension settings

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#18152] opened 2021-09-16 04:27 UTC
## Description 
Toggling off media router setting in `brave://settings/extensions` should disable 

## Test Plan
Specified here: https://github.com/brave/brave-core/pull/10116

## Steps to Reproduce

   1. Enable cast by enabling the media router toggle in `brave://settings/extensions`
   2. Verify that cast functionality works
   3. Disable cast
   4. Cast should not be available in the hamburger menu

## Actual result:
Cast still works

## Expected result:
Cast should be disabled

## Reproduces how often:
 Easily reproduced

## Desktop Brave version:
`1.29.80 Chromium: 93.0.4577.63 (Official Build) (x86_64)`

**Comment by stephendonner** [comment] 2021-09-16 10:56
Wow; sorry for missing this!

**Comment by vis2x** [comment] 2021-09-17 19:10
Any ETA on when it will be fixed?

**Comment by bridiver** [comment] 2021-09-21 16:24
How do you enable/disable cast? How do I verify cast functionality is working or not? The steps to repro don't provide sufficient detail.

**Comment by vis2x** [comment] 2021-09-23 19:31
> How do you enable/disable cast? How do I verify cast functionality is working or not? The steps to repro don't provide sufficient detail.

It never disables that's the bug. Go on Youtube on the latest version of Brave and a cast button will appear which should not.

**Comment by bridiver** [comment] 2021-09-23 19:52
> > How do you enable/disable cast? How do I verify cast functionality is working or not? The steps to repro don't provide sufficient detail.
> 
> It never disables that's the bug. Go on Youtube on the latest version of Brave and a cast button will appear which should not.

Yes, I understand what the issue is, the problem is that the steps to repro are not sufficiently detailed.

**Comment by vis2x** [comment] 2021-09-23 19:54
> > > How do you enable/disable cast? How do I verify cast functionality is working or not? The steps to repro don't provide sufficient detail.
> > 
> > 
> > It never disables that's the bug. Go on Youtube on the latest version of Brave and a cast button will appear which should not.
> 
> Yes, I understand what the issue is, the problem is that the steps to repro are not sufficiently detailed.

Fair. To be honest, I'm not sure how to repro either, it just happened randomly one day, perhaps after I updated to the latest version but I'm not sure.

**Comment by vis2x** [comment] 2021-10-01 23:31
Any ETA on fix? Or how I can downgrade version without uninstalling and losing my BAT?

**Comment by jumde** [comment] 2021-10-02 00:50
@vis2x - The PR should be merged early next week.

**Closed** 2021-10-03 22:34 UTC
Labels: OS/Android, OS/Desktop
