### ISSUE TITLE
[Android] Show only promotions that are active

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11163] opened 2020-08-11 05:38 UTC
Right now in the UI we display promotions that are in attested state as well. We should only show promotion that is in active state. If user clicks on notification and there is an error, promotion should be cleared from the UI and re-fetch from the server so that we really just show the latest in the UI.

**Comment by bsclifton** [comment] 2020-08-27 05:24
Marking as in-progress after talking with @NejcZdovc and marking as P2

**Comment by srirambv** [comment] 2020-09-02 14:28
@bsclifton @NejcZdovc  can you please add a test plan to this? I don't see any associated PR's for the issue. 

cc: @deeppandya @kjozwiak

**Comment by NejcZdovc** [comment] 2020-09-02 14:30
@srirambv will leave this to @deeppandya when he is done with it

**Comment by kjozwiak** [comment] 2020-09-02 16:57
@NejcZdovc is this `release/blocking`? Does this need to go into `1.13.x`? As per process, we shouldn't have any opened issues in milestones unless the issue is labelled as `release/blocking` as per process.

If this isn't `release/blocking`, lets remove it from this milestone as I don't see any associated PRs with this. Once finished, we can land in `1.15.x` and create uplifts if needed. CCing @bsclifton @aekeus

**Comment by deeppandya** [comment] 2020-09-22 19:27
To test this issue, i requested for two ugp grants. and then set one grant to inactive. As i mentioned to @NejcZdovc it still shows the notification as active.

**Comment by bsclifton** [comment] 2020-09-23 18:42
Blocked - need help looking at Grant - one of them should be inactive, but it's not unfortunately

**Comment by deeppandya** [comment] 2020-10-05 20:24
@bsclifton @NejcZdovc @SergeyZhukovsky  Basically everytime we have a new promotion, we add notification here https://github.com/brave/brave-core/blob/57ad35c07f14459949aafe5ccfdf8807a5ae8943/components/brave_rewards/browser/rewards_notification_service_impl.cc#L64 and in android, we look for the number of promotion we get from https://github.com/brave/brave-core/blob/57ad35c07f14459949aafe5ccfdf8807a5ae8943/components/brave_rewards/browser/rewards_notification_service_impl.cc#L119 So to test the above issue, in the first run, i let it show all the notification we get from backend and then to verify whether the UI is updating based on update in the promotion, i added a flag for one notification here https://github.com/brave/brave-core/blob/57ad35c07f14459949aafe5ccfdf8807a5ae8943/components/brave_rewards/browser/rewards_notification_service_impl.cc#L64 before we add promotion to the list. and the UI is reflecting the change perfectly. It doesn't require any code change at android side.

**Closed** 2020-10-07 18:42 UTC
Labels: OS/Android, QA/Test-Plan-Required, QA/Yes, blocked, closed/not-actionable, feature/rewards, priority/P2, release-notes/include
