### ISSUE TITLE
Newest version crashes found on M1 Pro macOS

### ISSUE THREAD

**Issue by scris** [brave/brave-browser#25215] opened 2022-09-05 11:16 UTC
## Description 

When using Brave Browser 1.42, everything works fine. Then it auto update to the newest version available now, and it crashes every time when I tried to launch it. Downgrading to 1.42.95 make it work again. Given that auto update is very efficient, sorry I'm wondering if I have chance to use it anymore :(

Thank you for taking time on this.

 - macOS Monterey 12.5.1
 - MacBook Pro (2021) with Apple M1 Pro

## Steps to Reproduce

   1.  Open the newest version of Brave on specific platform.
   2.  It crashes.

## Actual result:

Crashes on open, without the Apple warning on accidentally exit.

## Expected result:
The app can open.

## Reproduces how often: 

Every time opening it.

#### Working Version:
Brave | 1.42.95 Chromium: 104.0.5112.81 (正式版本) (arm64)
修订版本 | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
操作系统 | macOS 版本12.5.1（版号21G83）

#### Crash Version:
Brave | 1.43.89
Brave | 1.43.88
Brave | 1.43.87
  - Just crashes, thus I can't get access to brave://version.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
  - Yes. To check, I downloaded it from GitHub release.
- Can you reproduce this issue with the beta channel? 
  - Beta hasn't got a macOS ARM .dmg file.
- Can you reproduce this issue with the nightly channel? 
  -  Nightly hasn't got a macOS ARM .dmg file.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 
  - No.

## Miscellaneous Information:

- Cleaning up user data does not work for me.

**Comment by yordiak** [comment] 2022-09-05 11:56
I have installed brave (version 1.43.89) on a macbook air (version 12.5.1, with M1 processor) and I do not experience any crash issues.

**Comment by scris** [comment] 2022-09-05 13:59
What need/could/should I provide?
Screen replay: https://user-images.githubusercontent.com/23412857/188466365-3356f670-0c41-4650-948a-0e731cecde15.mp4

**Comment by bsclifton** [comment] 2022-09-06 05:52
@scris can you please install the older version of Brave and then visit brave://flags ? I suspect you have an option disabled here which is causing the crash. Disabling News or Sync can cause this crash - set those back to `Default`

Please let us know if this works 😄

**Comment by skystash** [comment] 2022-09-06 10:23
Holy crap please fix this

**Comment by skystash** [comment] 2022-09-06 10:30
Would appreciate if the option to disable news were stable.

![Screenshot 2022-09-06 at 11 27 03](https://user-images.githubusercontent.com/12685308/188612895-d17e1f96-4c18-41bb-9c70-aca5bc19846d.png)
![Screenshot 2022-09-06 at 11 27 56](https://user-images.githubusercontent.com/12685308/188612900-2b68febd-28f7-44fd-8f31-e656a26f4016.png)

**Comment by skystash** [comment] 2022-09-06 10:35
I can confirm Brave works again after resetting "Enable Brave News" and downloading the latest version from the site.

on macOS M1 v12.4

**Comment by bsclifton** [comment] 2022-09-06 16:18
News is controlled via regular settings; it's no longer an experiment. The flags could be removed at any time
![image](https://user-images.githubusercontent.com/4733304/188685727-648a8037-b56b-4b37-90d5-92cb14010ba8.png)

Thanks for confirming 😄

**Comment by bsclifton** [comment] 2022-09-06 17:46
Closing this as a duplicate of https://github.com/brave/brave-browser/issues/25156

You can subscribe to that issue for more details

**Closed by bsclifton** 2022-09-06 17:46 UTC
Labels: crash, OS/Desktop

**Comment by scris** [comment] 2022-09-09 00:05
> @scris can you please install the older version of Brave and then visit brave://flags ? I suspect you have an option disabled here which is causing the crash. Disabling News or Sync can cause this crash - set those back to `Default`
> 
> Please let us know if this works 😄

You're right, thank you!
