### ISSUE TITLE
Twitter tips button needs proper spacing

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#6456] opened 2019-10-12 07:03 UTC
## Description 
Twitter Tips button is too close to the share button and needs proper spacing/padding.

## Actual result:
<img width="587" alt="Screen Shot 2019-10-11 at 11 52 47 PM" src="https://user-images.githubusercontent.com/5951041/66696691-f01f5680-ec82-11e9-81b7-11e378663ef3.png">

## Expected result:
![61867921-e8f37280-aef5-11e9-8e2c-79c5ce4c9a37](https://user-images.githubusercontent.com/5951041/66696763-99664c80-ec83-11e9-8187-13ddb059103b.png)

See: https://github.com/brave/brave-browser/issues/4548

## Reproduces how often: 
This reproduces easily in 0.69.135. 
1. Login to Twitter
2. Ensure Brave Rewards is on.
3. Notice Twitter Tips button placement.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by alexandriaroberts** [comment] 2019-10-12 08:56
Hey @rebron I can do it!! 👍

**Comment by kjozwiak** [comment] 2019-10-12 15:58
Looks like this is also reproducible using `0.67.123 CR: 76.0.3809.87` which means Twitter must have changed something in their end which is causing the problem. Seems to be happening when you're logged into Twitter.

**`Example while being logged in:`**

<img width="605" alt="Screen Shot 2019-10-12 at 11 43 12 AM" src="https://user-images.githubusercontent.com/2602313/66704148-8b4a1780-ece7-11e9-9676-5e8a43d2b9ec.png">

**`Example while being logged out:`**

<img width="612" alt="Screen Shot 2019-10-12 at 11 43 43 AM" src="https://user-images.githubusercontent.com/2602313/66704152-93a25280-ece7-11e9-87d4-f795d722f791.png">

**Comment by brimwats** [comment] 2019-10-13 01:02
It would be excellent if the twitter tip button could be turned on and off. I'm happy to try out BAT, but I cannot stand the button so I had to opt out of BAT.

**Comment by srirambv** [comment] 2019-10-13 23:41
Possible dupe of  #4562

**Comment by bsclifton** [comment] 2019-10-14 05:40
@brimwats you actually can turn it off on a per-publisher basis:
1. Navigate to brave://rewards/
2. Click the `Tip Settings` button
    <img width="672" alt="Screen Shot 2019-10-13 at 10 38 40 PM" src="https://user-images.githubusercontent.com/4733304/66731077-3f43c380-ee0a-11e9-8acf-754eb2b8357d.png">
3. Uncheck the types that you don't want to see (or uncheck them all!)
    <img width="624" alt="Screen Shot 2019-10-13 at 10 39 51 PM" src="https://user-images.githubusercontent.com/4733304/66731092-67cbbd80-ee0a-11e9-8cef-5b6b06a838e3.png">

**Comment by bsclifton** [comment] 2019-10-14 05:42
@alexandriaroberts you're definitely welcome to grab this! 😄 I've been putting together a contributor guide (not merged yet) which has some tips for getting started:
https://github.com/brave/brave-browser/pull/6265
(comments extremely welcomed!)

Once you get setup and have things building, editing the rewards parts shouldn't be too hard
cc: @ryanml

**Comment by alexandriaroberts** [comment] 2019-10-14 06:41
Hey @bsclifton , Yes, I would love too!! Thank you! I will set my laptop up and will  start working on it. Thank you.😀 If I have any questions I will message here! 😊

**Closed** 2019-10-30 18:39 UTC
Labels: 1.0, QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards, priority/P2

**Comment by GeetaSarvadnya** [comment] 2019-11-04 08:07
Verification passed on



Brave | 0.71.108 Chromium: 78.0.3904.87 (Official Build) beta (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/68106632-3f664900-ff08-11e9-9468-d8332994e43a.png)
