### ISSUE TITLE
Shields blocking youtube video options popup menu

### ISSUE THREAD

**Issue by BartAgterbosch** [brave/brave-browser#17458] opened 2021-08-12 13:29 UTC
## Description 
Brave shields will cause youtube to no longer open the menu when clicking on a video's 3 dots (the "Save to playlist", "Not interested" and "Report", etc, menu), this applies to both the video thumbnail menu on the recommendations page or search results page for example, but also on a video page itself.
The problem goes away after disabling brave shields

Also replicable on the latest Brave on Android, when visiting the non-mobile version of youtube (desktop version)

## Steps to Reproduce

   1. Enable shields
   2. Visit youtube
   3. Click 3 dots next to video thumbnail to open menu

## Expected result:
Opens menu

## Actual result:
Doesn't open menu

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Version 1.28.105 Chromium: 92.0.4515.131 (Official Build) (64-bit)
Windows 10

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? 
- Yes

**Comment by Tonev** [comment] 2021-08-12 13:32
@ryanbr committed a fix that will be available within 24 hours. Until that you can manually add a custom filter via `brave://adblock` that will resolve the issue.

1. Open `brave://adblock`.
2. Enter `youtube.com#@#.ytd-popup-container` in the `Custom Filters` textbox.

Related to https://github.com/brave/adblock-lists/pull/633.

**Comment by sergekhakhin** [comment] 2021-08-12 14:07
Got the same problem with the same setup.

**Comment by Tonev** [comment] 2021-08-12 14:17
Try the following:

1. Close YouTube.
2. Open `brave://adblock`.
3. Add `youtube.com#@#.ytd-popup-container` in the `Custom Filters` textbox at the bottom of the page.
4. Check YouTube again.

**Comment by sergekhakhin** [comment] 2021-08-12 14:18
> Try the following:
> 
> 1. Close YouTube.
> 2. Open `brave://adblock`.
> 3. Add `youtube.com#@#.ytd-popup-container` in the `Custom Filters` textbox at the bottom of the page.
> 4. Check YouTube again.

Makes no difference.

**Comment by Tonev** [comment] 2021-08-12 14:31
I know it sounds weird, but for some reason the custom filter doesn't work all the time. Refresh YouTube a couple of times, that makes the custom filter take effect.

**Comment by BartAgterbosch** [comment] 2021-08-12 14:39
Same, the custom filter doesn't seem to fix it for me either, unsure why, but if there's a pull request for a fix I'll just sit back and wait for that

**Comment by Tonev** [comment] 2021-08-12 17:37
I'm not sure the issue is related to the latest YouTube changes the custom filter above aims to "disable". I got the same results with and without using the custom filter - YouTube options begin to function after many refreshes. The Community is filled with threads about the broken YouTube functionality, I'm sure developers will commit a fix as soon as they figure out what the issue is. It's a very weird issue - some users resolve their issues by using the custom filter from my first comment, other users are unable to make it work.

**Comment by BartAgterbosch** [comment] 2021-08-12 19:16
Just found out it applies to the "Save" to playlist manu popup too, and the top right buttons like notifications, create, and account, but only on a video page, they seem to work as intended on the homepage for example..
Either way I can reapply the custom filter and refresh the pages a million times, it doesn't do anything for me, neither does restarting brave (I tried)

**Comment by sergekhakhin** [comment] 2021-08-12 21:08
> I'm not sure the issue is related to the latest YouTube changes the custom filter above aims to "disable". I got the same results with and without using the custom filter - YouTube options begin to function after many refreshes. The Community is filled with threads about the broken YouTube functionality, I'm sure developers will commit a fix as soon as they figure out what the issue is. It's a very weird issue - some users resolve their issues by using the custom filter from my first comment, other users are unable to make it work.

Got it. I installed uBlock Origin and disabled Shields on the YouTube domain as a workaround.

**Comment by Tonev** [comment] 2021-08-13 03:07
Are you still experiencing issues? The updated `Brave Ad Block` component seems to have fixed the issues on my end.

**Comment by ryanbr** [comment] 2021-08-13 04:07
Safe to close this, fix has rolled out automatically, if not follow: #17465 (comment)

**Closed by ryanbr** 2021-08-13 04:07 UTC
Labels: OS/Desktop

**Comment by BartAgterbosch** [comment] 2021-08-13 18:19
Seems fixed now
