### ISSUE TITLE
Rewards and welcome page favicons are completely black 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4535] opened 2019-05-22 08:17 UTC
## Description 

Rewards and welcome page favicons are completely black 

## Steps to Reproduce

   1. Clean profile 0.65.107
   2. Enable Rewards
   3. Verify the favicons for Welcome and Rewards page

## Actual result:

Rewards and welcome page favicons are completely black 

![image](https://user-images.githubusercontent.com/38657976/58156911-d6aa4d80-7c94-11e9-9190-bc8447cba5e5.png)

## Expected result:
Rewards and welcome page favicons should be visible

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave	0.65.107 Chromium: 75.0.3770.38 (Official Build) beta (64-bit)
Revision	3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS	Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa

**Comment by NejcZdovc** [comment] 2019-05-22 08:25
@GeetaSarvadnya I guess this is dupe of https://github.com/brave/brave-browser/issues/3933?

**Comment by GeetaSarvadnya** [comment] 2019-05-22 08:45
@NejcZdovc I have not changed the theme with Default theme `Light` I am seeing favicons black

**Comment by NejcZdovc** [comment] 2019-05-22 09:39
I think root cause is the same

**Comment by srirambv** [comment] 2019-05-22 12:49
@NejcZdovc this is dupe of #3933. Its the theme on Linux which makes it either dark or white. I see white icons similar to #3933 
![image](https://user-images.githubusercontent.com/17010094/58175578-72749300-7c6e-11e9-94a8-972ac31a43d8.png)

**Closed by srirambv** 2019-05-22 12:49 UTC
Labels: OS/Linux, QA/Yes, bug
