### ISSUE TITLE
Downloads not being instantly displayed under "brave://downloads" until window resize

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#5330] opened 2019-07-23 05:39 UTC
## Test plan
See https://github.com/brave/brave-core/pull/3212

## Description 

Downloads are not being displayed under `brave://downloads/` instantly at times. You'll need to resize the current browser window for the entries to be displayed.

Couldn't reproduce it with `76.0.3809.71 (Official Build) beta`. Might be a regression with C76 as every channel but release is affected.

## Steps to Reproduce

   1. launch brave with a clean profile
   2. visit https://www.thinkbroadband.com/download
   3. download a few small file from the bottom of the page (I used `Extra Small File (5MB)` & `Small File (10MB)`)
   4. once the download has completed, click on `Show All` via the download bar

## Actual result:

![downloadIssue](https://user-images.githubusercontent.com/2602313/61685066-7746d900-ace9-11e9-974d-e0f55058e9f4.gif)

## Expected result:

Downloads entries should be instantly displayed under `brave://downloads/` without the need to resize the browser window.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.69.77 Chromium: 76.0.3809.62 (Official Build) nightly (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not reproducible using `0.66.101 Chromium: 75.0.3770.142`
- Can you reproduce this issue with the beta channel? Reproducible using `0.67.114 Chromium: 76.0.3809.62`
- Can you reproduce this issue with the dev channel? Reproducible using `0.68.108 Chromium: 76.0.3809.62`
- Can you reproduce this issue with the nightly channel? Reproducible using `0.69.77 Chromium: 76.0.3809.62`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No, couldn't reproduce using `76.0.3809.71 (Official Build) beta`.

## Miscellaneous Information:

CCing @brave/legacy_qa @rebron @bsclifton

**Comment by GeetaSarvadnya** [comment] 2019-07-24 13:16
The issue is reproducible on Windows 10 x64


Brave | 0.67.112 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 10 OS Version 1803 (Build 17134.523)

**Comment by mkarolin** [comment] 2019-07-24 20:09
Reproduced in a debug version with 76.0.3809.72 on a Mac.

**Comment by mkarolin** [comment] 2019-07-24 23:01
@bsclifton, didn't get a chance to take a closer look, assigning to you.

**Comment by GeetaSarvadnya** [comment] 2019-08-06 05:11
+1 from community https://community.brave.com/t/download-page-doesnt-show-any-downloads/74008

**Comment by florisre** [comment] 2019-08-06 12:14
Reproduced in Version 0.67.123 Chromium: 76.0.3809.87 (Offizieller Build) (64-Bit) on Linux. Also, another user reports the same at community: https://community.brave.com/t/downloads-view-seems-to-be-broken-in-the-latest-dev-version/72838

**Comment by onmyouji** [comment] 2019-08-07 16:33
Reproduced in 0.67.123 Chromium: 76.0.3809.87 (Official Build) (64-bit) on Windows 10

**Comment by Laurence02** [comment] 2019-08-08 12:32
Reproduced in Version 0.68.121 Chromium: 76.0.3809.100 (Official Build) beta (64-bit), on Windows 8.1.

**Comment by mhidro** [comment] 2019-08-13 06:29
Happens every time I open the downloads tab. 
Just a blank screen until I hit F10 to open the inspect menu, which I guess resizes the window. 

Version 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)

**Comment by Th3-A6add0n** [comment] 2019-08-13 16:57
> Happens every time I open the downloads tab.
> Just a blank screen until I hit F10 to open the inspect menu, which I guess resizes the window.
> 
> Version 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)
> OS: Windows 7 SP2 and Windows 10.

Tbh, this is a good temporary solution. LOL

**Comment by rebron** [comment] 2019-08-15 04:29
+1 from @Xyncgas via #5668

**Comment by Laurence02** [comment] 2019-08-15 13:15
Still exists in Version 0.69.107 Chromium: 76.0.3809.100 (Official Build) beta (64-bit).

**Comment by kjozwiak** [comment] 2019-08-19 14:33
@rebron @bsclifton we should reprioritize this as a `P2`. Definitely annoying folks and we're getting more 👍 from users.

+1 from https://twitter.com/kameshkotwani/status/1163347365379502080

**Closed** 2019-08-20 15:59 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/download, feature/user-interface, priority/P2, regression, release-notes/include

**Comment by LaurenWags** [comment] 2019-08-20 22:07
Verified passed with

Brave | 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/3212
* Verified STR from description
