### ISSUE TITLE
Remove the affiliate link scam

### ISSUE THREAD

**Issue by AdityaAnand1** [brave/brave-browser#10134] opened 2020-06-07 03:25 UTC
https://davidgerard.co.uk/blockchain/2020/06/06/the-brave-web-browser-is-hijacking-links-and-inserting-affiliate-codes/

**Comment by eljuno** [comment] 2020-06-07 05:40
Duplicate of #10131

**Comment by AdityaAnand1** [comment] 2020-06-07 06:28
That issue is being used as a distraction, as in it does not actually fix the scam, just hides it in the one scenario where brave was caught using it.

This issue was created because unknowingly changing URLs to affilaite URLs is unethical towards brave users and even to Brave's affiliate partners.

Shouldn't a $42M funded startup have a better monetization model than running short sighted scams?

**Comment by joshxyzhimself** [comment] 2020-06-07 06:41
https://news.ycombinator.com/item?id=23442027

**Comment by izzetemredemir** [comment] 2020-06-07 14:38
When I try to visit http://binance.us  brave browser redirect me to  ref link en?ref=35089877
https://github.com/brave/brave-core/blob/1cac2377c9a2d5e35873d4d3d74130336b86d062/components/omnibox/browser/suggested_sites_provider_data.cc

**Comment by izzetemredemir** [comment] 2020-06-07 14:45
@bbondy @mkarolin

**Comment by bsclifton** [comment] 2020-06-07 16:51
Discussion happening already here: 
https://github.com/brave/brave-browser/issues/10129

Closing this one as a duplicate

**Closed by bsclifton** 2020-06-07 16:51 UTC
