### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by itsthejb** [brave/brave-browser#34978] opened 2023-12-20 11:07 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.104 Chromium: 120.0.6099.115
Operating System: Mac OS X 14.2.1

URL (if applicable) where crash occurred:

Can you reproduce this crash?

No, but seems to be happening regularly in recent versions. Possibly linked to having audio playing in one tab. Also triggered when closing a tab.

Many crashes since Dec 11th. Previously Brave more or less never crashed

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/f1a50e00-100a-300b-0000-000000000000

**Comment by rebron** [comment] 2023-12-21 17:59
closing as dupe of https://github.com/brave/brave-browser/issues/34909.
Hi @itsthejb  Can you update to the latest 1.61.109 that released today and see if this is still an issue for you.

**Closed by rebron** 2023-12-21 17:59 UTC
