### ISSUE TITLE
Brave has become SLOW very SLOW, so slow i do not wan to run it

### ISSUE THREAD

**Issue by johesch** [brave/brave-browser#23419] opened 2022-06-12 14:21 UTC
## Description 

see above

## Steps to Reproduce

Just use it

I run LMDE 5 on X86 64-bit .
uname -a
Linux htng 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux
Brave version: Version 1.39.122 Chromium: 102.0.5005.115 (Officiell version) (64 bitar)
   1. 
   2. 
   3. 

## Actual result:

slow and sluggish NOT USABLE AT ALL

## Expected result:
Not sluggish

## Reproduces how often: 

ALLWAYS from some month ago and until now, when I gave up

## Brave version (brave://version info)

Linux htng 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux
Brave version: Version 1.39.122 Chromium: 102.0.5005.115 (Officiell version) (64 bitar)

## Version/Channel Information:

What?

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

I am tired of all changes that are pushed out to your users, and it seems you in a lesser way test before shipping, thats sad. Ive been running unix (that is LINUX nowadays) for more then 35 years. I wokrde in the swedish defensce industry and know a lot about developing IT systems in unix/linux.

**Comment by rebron** [comment] 2022-06-13 16:02
cc: @atuchin-m

**Comment by ahydronous** [comment] 2022-06-13 22:33
This might be related to: https://github.com/brave/brave-browser/issues/22641

It honestly blows my mind you guys respond to an extremely generically issue like this but ignore one where much of the pre-work has been done.

**Comment by ahydronous** [comment] 2022-06-13 22:35
This might be related to https://github.com/brave/brave-browser/issues/23254.

It honestly blows mind my mind you guys ignore an extremely generically described issue like this, but then choose to ignore one that actually adheres to your bug description guidelines.

**Comment by johesch** [comment] 2022-06-14 04:46
Well if a software does not work people stop using it. I changed to brave from firefox, how many uses firefox? Thats the fact. So what do you want with your software. I like brave but SW-engs. allways seems to tinker and change the code. When new generation SW-engs come along they do not have the experience.......and so the software gets more buggy, Thats life.
So its your call.

**Comment by atuchin-m** [comment] 2022-06-14 09:00
Performance bugs are sophisticated and usually related to specific user profile state/software/hardware configuration. Frequently, issues are caused by drivers/extensions/third-party software. Therefore, we need more details to deal with it.

We have an instruction related to the perf bugs: https://github.com/brave/brave-browser/wiki/How-to-submit-a-perf-bug

Could you please explains what exactly is slow? Startup? Page loading? UI responsibility? Video/audio playback?
Better to attach some some details like video/task manager screenshot/etc.

**Comment by johesch** [comment] 2022-06-14 14:43
Ok, what is slow. As I said just now after a reinstall (complete removal) it took about a few days and then a bit sluggishness returned back. The newly installed brave i working fine. Also I run about 7 LMDE systems with Brave and why do you tihink I bother at all? I could just skip this. I say what I say to help you connect to your own actions when changeing brave sourece code. For instance do you tes before delivery? on what hardware and OS-plaforms etc. These are thing that tell you about Brave status. I 
**_The sluggish thing is about open hyperlinks and sometimes about not reactiing to my interaction at all for example if I'am trying to do a new search from duckduckgo it seems that brave does not react at all for a second or three-four._** This is new and I spend several hours each day on these systems and its annoying and a good reason to test other browsers. I do not like firefox because i loads my systems more than brave som my cooling fans gets noisy. Note I run intel I3 and a GTX750TI on my 55inch samsung Qled tv as a computer monitor and streaming device. In my end the only thing that change is brave behavior.
Note. I live in sweden and Putin is not a frined of sedens right now, since the ucrainian war perhaps some thins bee happening. This is the only other thing that I can think of. I have not noticed anythin about my internet connection since I test it with speedtes.net alomst every day. This Is all I know my friends! I know my way around a unix system so tell me if I can gather any more info for you guys! DO you hav any brave logs......sorry for all words just trying to explain

**Comment by rebron** [comment] 2022-06-22 15:28
Closing as not actionable. @johesch As mentioned in the previous comment, we need more information from this template we provided: https://github.com/brave/brave-browser/wiki/How-to-submit-a-perf-bug. Please file a new issue with the information from that template.

Issues of this type need a lot more information and specifics otherwise we can't even begin to try and solve for it.

**Closed by rebron** 2022-06-22 15:28 UTC
Labels: needs-investigation, OS/Linux, perf, OS/Desktop
