### ISSUE TITLE
New tab stats don't update when you go back

### ISSUE THREAD

**Issue by sillibird** [brave/brave-browser#1865] opened 2018-10-26 17:43 UTC
## Description 
If you open a new tab, and go to a site, then hit back, all the stats will show as 0 (Trackers blocked, Ads blocked, etc)

## Steps to Reproduce

   1. With new tab page enabled open a new tab
   2. Note the correct amount of Trackers/Ads/etc. blocked.
   3. Navigate to any page
   4. Hit the back button and note all amounts showing 0.

## Actual result:
![image](https://user-images.githubusercontent.com/6666242/47583169-99f7bd00-d924-11e8-8742-387e0dc51cb1.png)

## Expected result:
![image](https://user-images.githubusercontent.com/6666242/47583180-a11ecb00-d924-11e8-81ea-dfdaa3fe94f4.png)

## Reproduces how often: 
Reproduces 100% of time

## Brave version (brave://version info)

Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
--|--
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows

### Reproducible on current release:
Reproduces on current release channel

### Website problems only:  
Brave shield should not have an effect as it is not enabled on new tab, and chrome does not have this feature so that is irrelevant. 

### Additional Information
N/a

**Comment by srirambv** [comment] 2018-10-27 12:43
Dupe of #307

**Closed by srirambv** 2018-10-27 12:43 UTC
