### ISSUE TITLE
Right click and Translate does not work.

### ISSUE THREAD

**Issue by Sophist-UK** [brave/brave-browser#3748] opened 2019-03-15 22:37 UTC
## Description 
Right click and select "Translate to English" - translation pop-up appears but translation never happens.

This does NOT appear to be the same issue as #237 (which is closed) because Translation hangs rather than giving a failure message.
 
## Steps to Reproduce
I have not reproduced this issue on a different PC, but I assume that the following steps will reproduce it:

   1. Set languages to UK English, English, Portuguese (Portugal) and Portuguese and spell check to UK English and Portuguese
   2. Go to a non-english page.
   3. Right click text and select Translate to English.

## Actual result:
Translation pop-up appears but translation never happens.

Exact same settings in Chrome and translation works fine.

## Expected result:
Translation happens.

## Reproduces how often: 
I have this problem on multiple pages from different sites.

## Brave version (brave://version info)
Brave | 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17763.379

### Reproducible on current release:
This issue is on current Brave release.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NO
- Is the issue reproducible on the latest version of Chrome? NO

**Comment by Sophist-UK** [comment] 2019-03-16 16:22
This may or may not be a duplicate of #208 - in 208 you get a message "Page could not be translated" - in this one it simply hangs whilst saying "Translating". In either case, you don't get the translation.

**Comment by rebron** [comment] 2019-03-17 05:07
Closing. It's a dupe of #208. You have expected results here as translation happens and that's what we're fixing in #208.

**Closed by rebron** 2019-03-17 05:07 UTC
