### ISSUE TITLE
Brave Browser Claims It's MANAGED -- But link only refers to Chromebook, not Desktops

### ISSUE THREAD

**Issue by dblanch256** [brave/brave-browser#7025] opened 2019-11-20 12:20 UTC
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment] 2019-12-02 06:40
@dblanch256 do you have more information? I am having trouble understanding your description. Is this something that brave.com is claiming? Or is this something in product?

As-is, there is not enough information here to understand what the problem is or where it is.  Please reply back with some additional info. Thanks!

**Comment by dblanch256** [comment] 2019-12-02 06:57
Yes, Brave is claiming it.  Here's a snippet from the Brave Settings Page:

[image: image.png]

David C Blanchard
MIT '76
609.238.3895

*"If I have seen a little farther than others, it is because I have stood
on the shoulders of giants"*   -- Isaac Newton


*"If I have not seen as far as others, it is because giants were standing
on my shoulders."*  -- Hal Abelson


*"In the field of Computer Science, we stand on each others' feet."*  --
Richard Hamming

**Comment by bsclifton** [comment] 2019-12-02 07:04
@dblanch256 for some reason, the picture didn't seem to attach? Can you try again?

Is this on the desktop browser? or android? or iOS?

**Comment by dblanch256** [comment] 2019-12-02 07:20
It was not attached--it was embedded.  Hoping you don't have display images
turned off.
Just in case, I'll attach it this time.

David C Blanchard
MIT '76
609.238.3895

**Comment by dblanch256** [comment] 2019-12-02 07:21
BTW, this is an i7 desktop (Windows 10).  Been running Brave for about a
year now.

Generally, very happy with it.

David C Blanchard
MIT '76
609.238.3895

*"If I have seen a little farther than others, it is because I have stood
on the shoulders of giants"*   -- Isaac Newton


*"If I have not seen as far as others, it is because giants were standing
on my shoulders."*  -- Hal Abelson


*"In the field of Computer Science, we stand on each others' feet."*  --
Richard Hamming

**Comment by bsclifton** [comment] 2019-12-02 07:26
Pictures still not showing; if you're replying via email, I'm not sure if GitHub handles that properly (versus being logged into the website)

Once you get to brave://settings, how do you see the link you're mentioning? (what section of settings are you clicking on?)

cc: @fmarier

**Comment by dblanch256** [comment] 2019-12-02 07:52
Not sure why you can't see images--never had that problem before.

Anyway, the short message is at the top the Brave/Settings page (right
under the heading tabs)
which reads:  "Your browser is managed by your organization."

When I click on that link, I get a page containing only this text:

"Your administrator can change your browser setup remotely. Activity on
this device may also be managed outside of Chrome. Learn More
<https://support.google.com/chromebook/answer/1331549>"

The "Learn More" link sends me to here:
https://support.google.com/chromebook/answer/1331549


But I don't own a Chromebook.  I'm using a desktop PC.

Hope this helps.

David C Blanchard
MIT '76
609.238.3895

*"If I have seen a little farther than others, it is because I have stood
on the shoulders of giants"*   -- Isaac Newton


*"If I have not seen as far as others, it is because giants were standing
on my shoulders."*  -- Hal Abelson


*"In the field of Computer Science, we stand on each others' feet."*  --
Richard Hamming

**Comment by NejcZdovc** [comment] 2019-12-02 08:03
@bsclifton I think we should show our custom page or replace link with https://support.google.com/chrome/answer/9281740

**Comment by dblanch256** [comment] 2019-12-02 08:34
Maybe.  It's confusing because I'm the "Manager" (or at least the
administrator) of these machines.  So I don't know the root cause of these
messages.  I hope I'm not "doing this to myself" only because I have the
wrong value for some setting.

David C Blanchard
MIT '76
609.238.3895

*"If I have seen a little farther than others, it is because I have stood
on the shoulders of giants"*   -- Isaac Newton


*"If I have not seen as far as others, it is because giants were standing
on my shoulders."*  -- Hal Abelson


*"In the field of Computer Science, we stand on each others' feet."*  --
Richard Hamming

**Comment by NejcZdovc** [comment] 2019-12-02 09:24
If I am not mistaken this was fixed with https://github.com/brave/brave-browser/pull/6475, which redirects to our support page.

**Comment by dblanch256** [comment] 2019-12-02 14:40
I just checked my Brave version.  It seems to think it's up to date:

"Brave is up to date
Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
<https://brave.com/latest/>"
David C Blanchard
609.238.3895

**Comment by NejcZdovc** [comment] 2019-12-02 14:44
@dblanch256 this landed in master, which means it will be released in version 1.3. Currently it's in Nightly version

**Comment by dblanch256** [comment] 2019-12-02 14:53
Thanks for investigating this!  Be well, citizen!

David C Blanchard
MIT '76
609.238.3895

*"If I have seen a little farther than others, it is because I have stood
on the shoulders of giants"*   -- Isaac Newton


*"If I have not seen as far as others, it is because giants were standing
on my shoulders."*  -- Hal Abelson


*"In the field of Computer Science, we stand on each others' feet."*  --
Richard Hamming

**Comment by NejcZdovc** [comment] 2019-12-04 12:51
this was fixed with https://github.com/brave/brave-browser/pull/6475

**Closed by NejcZdovc** 2019-12-04 12:51 UTC
Labels: need-more-info
