### ISSUE TITLE
brave stalling/beach balling when auto-completing URLs via tab

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#7688] opened 2020-01-10 07:06 UTC
## Description 

Sometimes when you quickly click on the URL bar and try auto-completing a URL via the `TAB`, the cursor will start beach balling and Brave will stall for a few seconds until the URL is completed.

I've ran into this a few times recently and it happens at least ~3-4 times a day.

## Steps to Reproduce

I don't really have STR but it usually happens when Brave has been idling for a bit of time and you quickly click on the URL bar, start typing something and press `TAB` to auto-complete.

## Actual result:

Brave stalls and starts beach balling for a few seconds until the URL auto-completes.

## Expected result:

Brave shouldn't be stalling nor beach balling when auto-completing URLs.

## Reproduces how often: 

As mentioned above, it happens a few times a day but it's not easy to reproduce as it doesn't always happen. I seem to reproduce when I try auto-completing a URL after Brave has been idle for ~20min.

## Brave version (brave://version info)

Brave | 1.5.22 Chromium: 79.0.3945.117 (Official Build) nightly (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.15.2 (Build 19C57)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes, reproduced`
- Can you reproduce this issue with the beta channel? `Not 100% sure`
- Can you reproduce this issue with the dev channel? `Not 100% sure`
- Can you reproduce this issue with the nightly channel? `Yes, reproduced`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

## Miscellaneous Information:

CCing @brave/legacy_qa @rebron @bsclifton @snyderp

**Comment by snyderp** [comment] 2020-01-10 20:19
I am also seeing this as recent as "Version 1.4.56 Chromium: 79.0.3945.117 (Official Build) dev (64-bit)".

Pretty frustrating, maybe locks brave up for ~5 sec

**Comment by bsclifton** [comment] 2020-01-10 21:14
@snyderp are you running on macOS also?

**Comment by snyderp** [comment] 2020-01-10 21:15
@bsclifton yep!

**Comment by bsclifton** [comment] 2020-01-13 07:39
@snyderp is this still happening w/ latest version of Nightly? We recently disabled out of process rasterization because of reports that it was crashing / causing artifacts / causing hangs for some users

Guessing it's something else, but wanted to check first 😄

**Comment by snyderp** [comment] 2020-01-13 19:07
I have not seen it in the last two nightlies.  I will report back here if I notice it again.

In general through, i see (saw?) it on tab autocomplete / omnibar issues most, but occasionally on same page, across-origin navigations, which might point to some per-process site-isolation issue

**Comment by rebron** [comment] 2020-01-14 19:37
Possibly related to https://github.com/brave/brave-browser/issues/7199.

**Comment by snyderp** [comment] 2020-01-14 20:19
Most def related, I bet a dupe

**Comment by snyderp** [comment] 2020-01-15 17:25
Just experienced again with `Version 1.4.58 Chromium: 79.0.3945.117 (Official Build) dev (64-bit)`

**Comment by bsclifton** [comment] 2020-01-15 22:35
@snyderp does it repro if you disable rewards? If not, I think we can de-dupe this issue to https://github.com/brave/brave-browser/issues/7199

**Comment by bmatzner** [comment] 2020-01-17 11:16
Seeing the same result on Catalina 10.15.2 (19C57) with Version 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit) with rewards enabled. Effect occurs after the browser has been idle for some time. Beach ball upon clicking in the URL bar and attempting to type. Entered text will appear after a few seconds. Will continue to test with rewards disabled.

**Comment by kjozwiak** [comment] 2020-01-21 05:10
@bsclifton @rebron I disabled Rewards as mentioned on Friday during our triage meeting and I managed to reproduce the issue with the same profile while Rewards was disabled. I'm not 100%, but I don't think it's related to Rewards.

@bmatzner if you disable rewards via `brave://rewards`, can you still manage to reproduce the issue?

**Comment by bmatzner** [comment] 2020-01-25 21:10
@kjozwiak Have been using Brave with Rewards disabled for a few days, and I'm afraid the issue is still there. After a while, in a new tab, when entering text, the beach ball appears.

**Comment by bsclifton** [comment] 2020-01-27 05:48
@bmatzner thanks for confirming 👍

**Comment by rebron** [comment] 2020-03-24 04:40
@bmatzner Can we have you try one more time with 1.5.115 Chromium: 80.0.3987.149.
May have been resolved with the most recent Chromium versions.

@pes10k Any more beachballing with url/autocomplete?

**Comment by pes10k** [comment] 2020-03-24 19:04
@rebron i haven't seen this in a while 👍

**Comment by bmatzner** [comment] 2020-03-24 20:16
Same here, haven‘t seen the behavior in a couple of days. Thanks so much!

**Closed** 2020-03-30 15:58 UTC
Labels: bug, debug, needs-investigation, perf, priority/P2

**Comment by kjozwiak** [comment] 2020-03-30 21:03
Haven't seen this in a long time either. Must have been resolved in one of the Chromium bumps 👍
