### ISSUE TITLE
On custom asset dialog, some fields seem to be populating using previous attempts

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#23358] opened 2022-06-09 12:52 UTC
## Description 

From customer at https://community.brave.com/t/wallet-asset-token-management-ordering-view/399725

''I also encountered a few bugs in the add custom asset dialog. When a network is selected and then a token contract inserted, other fields would often be filled out/overwritten from a previous add custom asset attempt.
Brave version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (x86_64) on macOS 12.4''

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by jamesmudgett** [comment] 2022-06-17 16:22
@srirambv

**Comment by srirambv** [comment] 2022-07-05 12:06
Sorry for the delay but seems like the issue is still reproducible on 1.40.109 however this seems fixed on 1.41.x and 1.42.x. So I'd close the issue for now and maybe reopen if we start receiving complaints on 1.41.x This is/was actually a regression of #21337 on 1.40.x

**Closed by srirambv** 2022-07-05 12:06 UTC
Labels: bug, needs-investigation, feature/wallet, OS/Desktop
