### ISSUE TITLE
Unable to load Brave Rewards content on address bar

### ISSUE THREAD

**Issue by vuongggggg** [brave/brave-browser#5931] opened 2019-09-08 07:49 UTC
## Description 
Unable to load Brave Rewards content after clicked on the address bar's icon

## Steps to Reproduce
   No step for reproducing.

## Actual result:
![unable to load brave rewards on navigation bar](https://user-images.githubusercontent.com/3168632/64485223-f9fb0780-d247-11e9-8ec4-44beacdd6a1b.png)

## Expected result:
Brave Rewards should be shown

## Reproduces how often: 
No steps to reproduce

## Brave version (brave://version info)

Brave | 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 10 OS Version 1903 (Build 18362.10019)
JavaScript | V8 7.6.303.29
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extensions-install-verification=enforce_strict --enable-features=NewExtensionUpdaterService,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,TranslateUI,NetworkService,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\quocv\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | d74ef32b-ca7d8d80

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
no
- Does the issue resolve itself when disabling Brave Rewards?
no
- Is the issue reproducible on the latest version of Chrome? 
I don't know.

## Miscellaneous Information:

- Already tried to Reset settings
- Already tried to Re-install Brave
- Already tried to clear data
... but it still happens.

**Comment by NejcZdovc** [comment] 2019-09-08 16:43
closing as dupe of https://github.com/brave/brave-browser/issues/5336. This will be fixed in 0.69

**Closed by NejcZdovc** 2019-09-08 16:43 UTC
Labels: feature/rewards
