### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by nafidurmus** [brave/brave-browser#34934] opened 2023-12-15 19:36 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.101 Chromium: 120.0.6099.71
Operating System: Mac OS X 14.2.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/7eff0300-100a-300b-0000-000000000000

**Comment by rebron** [comment] 2023-12-15 23:47
We have a fix. Closing as duplicate of https://github.com/brave/brave-browser/issues/34909

**Closed by rebron** 2023-12-15 23:47 UTC

**Comment by nafidurmus** [comment] 2023-12-17 18:29
not fixed, brave browser is currently freezing
