### ISSUE TITLE
Implement Storage Access API

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#2157] opened 2018-11-15 19:17 UTC
https://github.com/whatwg/html/issues/3338

**Comment by fmarier** [comment] 2019-07-30 17:05
Microsoft is implementing this and is proposing to upstream it: https://groups.google.com/a/chromium.org/d/topic/blink-dev/e5fu5Q06ntA/discussion

**Comment by FYJen** [comment] 2020-05-04 03:09
With Safari and Firefox supporting this feature, is there a timeline on when Brave will support it? Chrome's is in progress - https://bugs.chromium.org/p/chromium/issues/detail?id=989663.

With Brave being the privacy-first browser, this Storage Access API offers additional optionality for the developers to provide fine-grained access control and to explicitly obtain user consent.

**Comment by laughinghan** [comment] 2020-05-12 23:29
Brave has previously said "we would use this if it were already implemented in Chromium" https://github.com/whatwg/html/issues/3338#issuecomment-358436083

**Comment by pes10k** [comment] 2020-07-23 06:13
closing in favor of https://github.com/brave/brave-browser/issues/8514 (Since the API now exists in chromium, and https://github.com/brave/brave-browser/issues/8514 covers how we'd actually use it)

**Closed by pes10k** 2020-07-23 06:13 UTC
Labels: priority/P5, privacy, privacy/feature

**Comment by drmercer-lucid** [comment] 2024-01-16 23:21
Any updates on actually supporting the Storage Access API - i.e. allowing third-party iframes to request access to their own first-party storage? AFAIK ephemeral storage does not at all solve the problems that SAA was intended to solve :upside_down_face:

**Comment by JannisBush** [comment] 2024-04-30 07:26
> Any updates on actually supporting the Storage Access API - i.e. allowing third-party iframes to request access to their own first-party storage? AFAIK ephemeral storage does not at all solve the problems that SAA was intended to solve 🙃

This blog post from Brave makes it sound like Brave does not plan on ever supporting it: https://brave.com/privacy-updates/24-google-sign-in-permission/

> Brave disables the storage access API in Chromium as we believe this approach is not the right way to protect privacy on the Web. The storage access API asks users to make privacy-risking choices they do not understand, and generally requires users to bear the burden of protecting their own privacy.
