### ISSUE TITLE
Broken tab rearrangement on Linux

### ISSUE THREAD

**Issue by intrnl** [brave/brave-browser#20023] opened 2021-12-10 09:18 UTC
## Description 

Tab rearrangement through mouse is broken on latest Brave Nightly.

## Steps to Reproduce

   1. Open up Brave.
   2. Open multiple tabs, it can be anything.
   3. Try to rearrange the tabs by dragging them.

## Actual result:

Tab rearrangement is completely impossible, the tab will always split into a new window.

https://user-images.githubusercontent.com/20620901/145548838-92f20834-1963-434a-a179-18b13fd1551a.mp4

## Expected result:
You should be able to rearrange tabs.

## Reproduces how often: 

Easily reproducible.

## Brave version (brave://version info)

Brave: 1.35.20 Chromium: 97.0.4692.36 (Official Build) nightly (64-bit)
Revision: 747e0a0f19c13ca6ee136200f5b097448ae4892f-refs/branch-heads/4692@{#607}
OS: Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not tested.
- Can you reproduce this issue with the beta channel? Not tested.
- Can you reproduce this issue with the nightly channel? Yes.

This should only happen on Nightly currently as it's on Chrome 97, which has the faulty behavior.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? Reproducible on Chrome Beta 97 and Dev 98.

## Miscellaneous Information:

I thought it would be appropriate to file the issue here as well so people are aware of it and don't file another.

KDE Plasma 5.23.4, X11, Arch Linux 5.15.7-lqx1-1-lqx

**Comment by intrnl** [comment] 2022-01-05 08:19
Unfortunately, Chrome 97 has landed into stable, and there hasn't been any news whether the issue would be fixed soon.

**Comment by ipha** [comment] 2022-01-08 19:33
Upstream fixed this in 98+. Is it possible to cherry-pick the patches?

https://chromium-review.googlesource.com/c/chromium/src/+/3355376
https://chromium-review.googlesource.com/c/chromium/src/+/3355470

**Comment by bsclifton** [comment] 2022-01-10 08:09
Thanks for the report, @intrnl

I'm going to close this as duplicate of https://github.com/brave/brave-browser/issues/20386 - you can follow that issue for updates 😄

**Closed by bsclifton** 2022-01-10 08:09 UTC
Labels: priority/P5, repros-on-chrome, Chromium/waiting upstream, OS/Linux/arch, OS/Desktop
