### ISSUE TITLE
Automatically disable Brave shield and white list for it

### ISSUE THREAD

**Issue by gda44** [brave/brave-browser#15674] opened 2021-05-07 10:56 UTC
## Description 
Hello, 
We use Brave Software in an Enterprise and we need to automatically disable brave shield for one website (which use SSO and works without the shield).
Actually, the only way we found is to go on this site and disable it manually. 

Is there a way to disable automatically Brave shield for one website ? Is there a Whitelist regkey for Shields we can configure ? 
In the same way as we can configure a whitelist URL for example. 

I already go on few issues on github, a solution could be to configure the white list of adblock via brave://adblock page, but in our context it doesn't solve our issue. 
Here there is our tests in brave://adblock : 
@@||ourwebsite^
@@||ourserverauthdomain^

On our website, the shield indicates that it has blocked nothing but when we disable it, SSO working. 

I didn't find my answer in old request so, i'm asking for help. 
Is it possible to automatically configure the shield for one site ? (we want to keep it for the other site). 

Thank you a lot ! 

## Steps to Reproduce
   1. Try to automatically configure brave shield. 
   2. Try 1 : Adding our website and sso server in brave://adblock 
   3. Try 1 : Go to the website and check the number of blocked sites, same at before configuration of adblock. 
 

## Actual result:
No automatical configuration of brave shield. 

## Expected result:
Regestry Key or other to disable Brave Shield for a specific website. 

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Test with Brave 1.19.90 on Windows 10 1909, also test with 1.24.82. 

## Version/Channel Information:
- Can you reproduce this issue with the current release? **yes** 
- Can you reproduce this issue with the beta channel? not tried
- Can you reproduce this issue with the nightly channel? not tried 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **yes**
- Does the issue resolve itself when disabling Brave Rewards? don't try as brave shield disabling corrects the issue 
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:
For try, we delete the configuration registry key of Brave.

**Comment by bsclifton** [comment] 2021-09-28 18:45
Similar to https://github.com/brave/brave-browser/issues/5290

**Comment by bsclifton** [comment] 2022-08-15 16:44
Closing as a duplicate of https://github.com/brave/brave-browser/issues/12782

**Closed by bsclifton** 2022-08-15 16:44 UTC
Labels: closed/duplicate, feature/shields, enterprise, OS/Desktop
