### ISSUE TITLE
Font size being ignored under a certain size

### ISSUE THREAD

**Issue by VicGUTT** [brave/brave-browser#5116] opened 2019-07-03 11:09 UTC
## Description 
_Providing more details about the font size issue in #4742._

It appears the browser have a minimum font size below which it will completely discard any value specified via CSS, no matter the unit used (px, em, rem).
This behavior causes fonts to be way larger then they should be considering a specified CSS font-size value.

And of course this all happens without zooming in or out of the page.
Just normal viewport, browsing etc...

## Steps to Reproduce
   1. Considering this [Codepen](https://codepen.io/anon/pen/MMmJqB).
   2. Visite it in Brave, then in any other browser (I have checked via Chrome, Firefox and even IE _(Not on this codepen though as it does not support IE anymore)_).

## Actual result:
In my example, specifying a font size has no effect under 12px.

**Brave**
![brave](https://user-images.githubusercontent.com/39224143/60586756-09b32700-9d93-11e9-9630-eb62e0305a1f.JPG)

**Chrome/Firefox**
![others](https://user-images.githubusercontent.com/39224143/60586788-1fc0e780-9d93-11e9-9d3e-beb28e85b188.JPG)

## Expected result:
The texts should be minuscule and behave like the other browsers.

## Reproduces how often: 
Easily reproduced.

## Brave version (brave://version info)
- **Brave** :  0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit) 
- **Revision** :  cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
- **OS** :  Windows 10 OS Version 1803 (Build 17134.829)

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome?
Yes _(Version : 75.0.3770.100 (Build officiel) (64 bits))_

## Miscellaneous Information:
Related issue : #4742.

**Comment by srirambv** [comment] 2019-07-03 11:19
Seems to be working fine for me on Linux on `0.66.99`
![image](https://user-images.githubusercontent.com/17010094/60587529-b0cb9a80-9d62-11e9-90e5-5b88addd5556.png)

Little confused when you say you have checked it on Chrome and you also said its reproducible on Chrome as well. 

cc: @GeetaSarvadnya to verify on Windows 10

**Comment by VicGUTT** [comment] 2019-07-03 18:03
Hi @srirambv , from your image it seems au contraire that you are having the same issue I am.
Maybe I did not explain myself well.

On other browsers (Chrome and Firefox) when opening the Codepen the texts are very small (like in the 2nd picture) that's because the browsers apply the given CSS "font-size" _(.1rem, .1em and 1px with a root size of 10px)_ accordingly. Whereas Brave does not seem to be able to go smaller then a certain amount _(12px in this context)_.

This is a very contrived example to illustrate the problem but as far as i'm concerned the issue is reproducible with any live websites _(see the images below)_.

**Chome :**
![chome](https://user-images.githubusercontent.com/39224143/60614535-5c113980-9dcd-11e9-8edd-12d663aa4e9b.png)

**Brave :**
![brave](https://user-images.githubusercontent.com/39224143/60614536-5ca9d000-9dcd-11e9-84af-13d3c12e1de9.png)

**Comment by Golutazem** [comment] 2019-07-15 15:42
The "Minimum font size" is a necessary feature -- not a bug. It can also be set by the user at
chrome://settings/fonts

**Comment by bsclifton** [comment] 2019-07-21 07:14
Closing - @VicGUTT please try adjusting chrome://settings/fonts and re-open if there is still an issue. Thanks 😄

**Closed by bsclifton** 2019-07-21 07:14 UTC
