### ISSUE TITLE
Fails to load https://www.forbes.com/crypto-blockchain/ when accessing using EU IP

### ISSUE THREAD

**Issue by Eurno** [brave/brave-browser#4462] opened 2019-05-16 08:49 UTC
## Description 
When visiting https://www.forbes.com/crypto-blockchain/ the browser just shows an empty page which has "cookies on Forbes" on the left hand side. I have checked in other browsers and it is a problem that is only applicable to Brave.

## Steps to Reproduce
Go to https://www.forbes.com/crypto-blockchain/ in the Brave browser.

**EDITED**: Needs to be done via EU IP address.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)
--
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X
JavaScript | V8 7.4.288.26
Flash | 32.0.0.171 /Library/Internet Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36

## Version/Channel Information:
Tried with dev tools open (so not caching) and still the same. Using most up to date brave as far as I am aware. Have metamask, Presearch and ENU Ironman installed. 

## Other Additional Information:
Tried without shields, still persists. Console lists the following error:

VM210:1 Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at consentIsSet (?toURL=https://www.forbes.com/crypto-blockchain:32)

With the following message:

MessageEvent {isTrusted: true, data: "{"PrivacyManagerAPI":{"action":"getConsent","timestamp":1557996390795,"self":"forbes.com"}}", origin: "https://www.forbes.com", lastEventId: "", source: Window, …}

**Comment by bsclifton** [comment] 2019-05-18 06:40
@Eurno for debugging, can you please try to temporarily disable metamask? (you should be able to via brave://extensions)

Metamask and other extensions sometimes modify the DOM, which can cause web compatibility problems. I'm not using any extensions and the link above works for me (shields up and down).

**Comment by srirambv** [comment] 2019-05-18 12:59
@bsclifton its a GDPR cookie issue. If you are behind EU VPN then you can reproduce the issue. 
![image](https://user-images.githubusercontent.com/17010094/57970096-30d0a900-794b-11e9-8ffa-e957d61413fd.png)

**Comment by ryanbr** [comment] 2019-05-20 11:40
I tested from a UK IP address, saw the same issue. consent.trustarc.com seems to be the culprit, possibly have issues loading/using the cookie to show the GDPR.

**Comment by kjozwiak** [comment] 2019-05-27 16:41
Reproduced the same thing @srirambv mentioned above. Works fine when accessing via a NA IP address. However, when loading the website from EU, you'll run into the issue. Most likely something to do with the way GDPR cookies are being set. Looks like once you consent and set the cookies, the redirect doesn't occur.

**Comment by ryanbr** [comment] 2019-06-10 05:40
I'm not sure if filters is the answer, but something like this has been used; Not the first time I've seen trustarc cause issues.

```
@@||consent-pref.trustarc.com^$subdocument,domain=forbes.com
@@||truste-svc.net/cookie_js/$subdocument,domain=forbes.com
@@||consent.trustarc.com^$image,domain=forbes.com
@@||consent.trustarc.com/asset/$script,domain=forbes.com
@@||consent.truste.com/notice$script,domain=forbes.com
```

**Comment by ryanbr** [comment] 2020-03-08 03:55
I've rechecked this. @Eurno I'm getting the consent message, with shields on. Seems to be okay now we can get past the consent dialog. (Tested with Shields=ON)

**Comment by ryanbr** [comment] 2020-07-10 02:41
Okay re-checked before closing. Cookie/Consent dialog box comes up (UK IP tested). and can get passed it.

**Closed** 2020-07-10 02:42 UTC
Labels: QA/Yes, closed/works-for-me, feature/shields/webcompat, needs-more-info, release-notes/include, webcompat
