### ISSUE TITLE
The Allowed Cookies Can Not Be Deleted

### ISSUE THREAD

**Issue by hennrynusasatria** [brave/brave-browser#11259] opened 2020-08-17 05:47 UTC
Hi All,

**Description:**
The allowed cookies can not be deleted, please check the following screenshot:

![image](https://user-images.githubusercontent.com/69782842/90360823-e0cd1e80-e086-11ea-8078-0578cf8a9e39.png)

**Steps to Reproduce:**

   1. Open brave://settings/content/cookies
   2. Delete the allowed cookies
   3. The allowed cookies can not be deleted

**Actual result:**
The allowed cookies can not be deleted

**Expected result:**
The allowed cookies must be able to be deleted

**Reproduces how often:**
Easily reproduced

**Desktop Brave version:**
Version 1.12.112 Chromium: 84.0.4147.125 (Official Build) (32-bit)

**Android Device details:**
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Android 9

**Comment by dentistformyeye** [comment] 2020-08-18 01:04
#8604 is the same as this issue, except the former only mentions desktop.

**Comment by hennrynusasatria** [comment] 2020-08-20 18:01
Hi @dentistformyeye 

Yes, #8604 and #10532 are the same as this issue, this also happens on Brave Android

cc: @rebron @tomlowenthal

**Comment by bsclifton** [comment] 2020-08-31 05:53
+1 from @cjwijtmans via https://github.com/brave/brave-browser/issues/11515 for deleting embedded cookies
> ## Steps to Reproduce
>
>   1. go to brave://settings/content/cookies
>   2. see "embedded" cookies with trash icon
>   3. click trash icon
> ## Actual result:
>
> nothing happens, cookie setting is still there
> 
> ## Expected result:
>
> cookie setting is deleted

**Comment by hmiel** [comment] 2021-01-03 02:52
Hi Guys, is there a known workaround for this issue? 
Is going directly to the particular website then `Lock` >> `Cookies` >> `Block` does the trick (even if that website still appears on my list _Sites that can always use cookies_)?

**Comment by snowbound** [comment] 2021-01-10 04:28
See https://github.com/brave/brave-browser/issues/12375

**Comment by Saxonis** [comment] 2021-01-14 15:42
Same issue here with Windows 7 64bit.

**Comment by snowbound** [comment] 2021-01-14 17:41
I wonder if this is at all related to another festering issue with Brave in that it does not seem to be able to delete certain Google based cookies upon browser closure https://github.com/brave/brave-browser/issues/9085

**Comment by Michael82548** [comment] 2021-05-01 17:36
The way it works on mobile is that you can block cookies that were previously allowed but when you delete blocked cookies, it moves it back to "allowed" and when you try to remove them from allowed, it does nothing.

**Comment by Brave-Matt** [comment] 2021-06-15 20:05
+1 on Android:
https://community.brave.com/t/cannot-remove-sites-from-cookie-exception-list/259885/2

**Comment by snowbound** [comment] 2021-06-15 20:44
I am trying out Vivaldi which like Chrome and MS Edge Chromium has no issues deleting the .google.com cookie when one exits the browser in question. This was in reference to a 14+ month old issue I struggle with Brave in that it leaves you logged into ALL of your Google accounts unless you a) remember to use Google's logout pulldown or b) do the scorch earth approach and delete ALL cookies every time you close the browser.

**Comment by cjwijtmans** [comment] 2021-06-15 20:52
Ms edge is actually the best chromium browser i ever used. It probably does a ton of spyware stuff but oh well.. i just avoid using edge for anything i consider too personal. But a ms browser that is actually and vscode which is the best ide ever. Looks like microsoft actually makes good software now. What world am i living today 🤦🏼‍♂️. Anyhow brave leaves a sour taste when it comes to usability.

**Comment by snowbound** [comment] 2021-06-15 20:57
I must say that Brave has been the most frustrating browser to report issues regarding. Thankfully the devs here still respond to threads. I had high hopes for Brave when I started using it for the first time back in 2019. It was a breath of fresh air wrt support. I have been very vocal wrt Brave and support issues in Brave Community and Reddit which becomes full of BAT-related issues.

**Comment by joloyonaha** [comment] 2021-09-07 07:25
Having an issue removing/hiding these 2?
![cookie](https://user-images.githubusercontent.com/15605674/132301644-7dc37cc2-1362-4715-907d-0239415fa902.png)

Turn off the 'Google login buttons...' and the above cookies will be hidden.
![toggle](https://user-images.githubusercontent.com/15605674/132302056-9fdc802a-881d-4608-897f-a6105eae3459.png)

Let me know if this works for you.

**Comment by cjwijtmans** [comment] 2021-09-07 11:24
I never turned on that option in the first place. And i believe "hiding" cookies is a terrible idea.

**Comment by snowbound** [comment] 2021-10-17 23:49
Ditto for me. I made sure that Google Login buttons was disabled. I have had to resort using a third party extensionCookie AutoDelete to fix this issue as outline in https://github.com/brave/brave-browser/issues/9085

**Comment by bridiver** [comment] 2022-02-04 01:39
> I never turned on that option in the first place. And i believe "hiding" cookies is a terrible idea.

The option currently is on by default as a compromise for user experience. The default settings block the use of google login for sites and most users would be unable to fix that without allowing much more than necessary. This may be removed soon after we verify everything still works correctly with partitioned cookie storage cc @pes10k

**Comment by bridiver** [comment] 2022-02-04 01:46
this has been mentioned in other related issues, but currently cookie settings created by shields are not deletable in the `brave://settings/content/cookies` UI, they can only be changed in the shields panel. The reasons are a bit complicated, but the gist is that these cookie settings are auto-generated by combining shield specific cookie settings and shields on/off settings. They show up here because the final result is a chromium cookie setting, but it's not a setting that is currently persisted along with the ones you create on this page yourself (which are deletable). Also until somewhat recently it wasn't possible to express "block third party cookies on b.com" in a single content setting so in some cases you'd end up with two settings in `brave://settings/content/cookies` that actually corresponded to a single setting in brave shields and deleting only one of them would be problematic. Now that it is possible, we are looking at making changes that will make it possible to add/delete cookie settings in either the shields panel or the `brave://settings/content/cookies`

**Comment by Michael82548** [comment] 2022-02-04 03:14
> 

So you are saying that normally if we make changes via brave shields, the cookies on those sites are permanent unless you undo those changes? That what it looked like to me when I was having this issue.

**Comment by Michael82548** [comment] 2022-02-04 03:14
> this has been mentioned in other related issues, but currently cookie settings created by shields are not deletable in the `brave://settings/content/cookies` UI, they can only be changed in the shields panel. The reasons are a bit complicated, but the gist is that these cookie settings are auto-generated by combining brave specific cookie settings and shields on/off settings. They show up here because the final result is a chromium cookie setting, but it's not a setting that is currently persisted along with the ones you create on this page yourself (which are deletable). Also until somewhat recently it wasn't possible to express "block third party cookies on b.com" in a single content setting so in some cases you'd end up with two settings in `brave://settings/content/cookies` that actually corresponded to a single setting in brave shields and deleting only one of them would be problematic. Now that it is possible to have a single setting for block third party, we are looking at making changes that will make it possible to add/delete cookie settings in either the shields panel or the `brave://settings/content/cookies`

So you are saying that normally if we make changes via brave shields, the cookies on those sites are permanent unless you undo those changes? That what it looked like to me when I was having this issue.

**Comment by bridiver** [comment] 2022-02-04 03:17
> So you are saying that normally if we make changes via brave shields, the cookies on those sites are permanent unless you undo those changes? That what it looked like to me when I was having this issue.

I'm not sure what you mean by "the cookies on those sites are permanent". All I'm saying is that cookie settings made in brave shields can currently only be managed through brave shields. Deleting these settings does not delete any existing cookies no matter how or where they were created, that is controlled under `brave://settings/siteData`

**Comment by iefremov** [comment] 2022-04-26 12:52
duplicate of https://github.com/brave/brave-browser/issues/12375

**Closed by iefremov** 2022-04-26 12:52 UTC
Labels: priority/P3, OS/Android, OS/Desktop
