### ISSUE TITLE
DDG URL is being updated on upgrade - follow up to 6187

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6469] opened 2019-10-14 20:55 UTC
## Description 
Follow up from https://github.com/brave/internal/issues/647#issuecomment-541900942 and https://github.com/brave/brave-browser/issues/6187

DDG search engine entry is being updated to new URL for existing users in certain cases.

## Steps to Reproduce

pre-req: use DE, AU, NZ, IRL
   1. Install 0.69.x
   2. Set SE to Bing.
   3. Upgrade to 0.70.x
   4. Verify Bing was retained as SE default.
   5. View DDG URL from brave://settings/searchEngines

## Actual result:
DDG entry shows new URL (DE):
<img width="539" alt="Screen Shot 2019-10-14 at 16 45 34" src="https://user-images.githubusercontent.com/28145373/66781735-13741c80-eea2-11e9-890a-c883be3312d9.png">

DDG entry shows new URL (AU, NZ, IRL):
<img width="532" alt="Screen Shot 2019-10-14 at 4 47 08 PM" src="https://user-images.githubusercontent.com/28145373/66781812-49190580-eea2-11e9-84bd-8337efa02bed.png">

## Expected result:
DDG entry should retain previous URL even when it is not the default on upgrades:
<img width="537" alt="Screen Shot 2019-10-14 at 4 47 51 PM" src="https://user-images.githubusercontent.com/28145373/66781846-60f08980-eea2-11e9-92e0-1e4e3ba0b37a.png">

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.70.115 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @rebron @bsclifton @brave/legacy_qa

**Comment by LaurenWags** [comment] 2019-10-14 20:56
Added to 0.70.x milestone and added `release-blocking` label per discussion with @rebron - please update if needed.

**Comment by bsclifton** [comment] 2019-10-14 21:58
@LaurenWags is this a dupe of https://github.com/brave/brave-browser/issues/6424?

Fixing this might be difficult. Will talk with @rebron

**Comment by LaurenWags** [comment] 2019-10-14 22:12
Might be a dupe - in #6424 DDG was the default selection and in this issue, DDG is not the default SE selection, so per discussion with @rebron I understood that it should retain the old URL.

**Comment by bsclifton** [comment] 2019-10-17 21:21
Closing as `wontfix` after discussion with @rebron. The lists shown are the "pre-populated" lists which change with locale (this is expected behavior). 

The entries will remain there (untouched) if you either set as default engine or edit the keyword (ex: user interacts with it)

**Closed by bsclifton** 2019-10-17 21:21 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/search, release-notes/exclude, wontfix
