### ISSUE TITLE
[Desktop] blocking navigation to page

### ISSUE THREAD

**Issue by jcesarmobile** [brave/brave-browser#10792] opened 2020-07-17 16:12 UTC
## Description 

Directly navigating to https://capacitorjs.com/docs/apis/push-notifications, but links that navigate to it don't work, the url changes but the content don't load.
The page doesn't have ads or anything different from the rest of the site, I think it's just because of the url containing push-notifications

## Steps to Reproduce

   1. Open https://capacitorjs.com/docs/apis/permissions
   2. Click next
   3. Should load https://capacitorjs.com/docs/apis/push-notifications but it's blocked

## Actual result:

url changes to https://capacitorjs.com/docs/apis/push-notifications but has the permissions content

## Expected result:
load the actual https://capacitorjs.com/docs/apis/push-notifications content

## Reproduces how often: 
always

## Brave version (brave://version info)
1.11.97

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? NO

## Miscellaneous Information:

We have had a few reports of problems loading the notifications page
https://github.com/ionic-team/capacitor-site/issues/78
https://github.com/ionic-team/capacitor/issues/1866
https://github.com/ionic-team/capacitor/issues/2790
https://github.com/ionic-team/capacitor/issues/2925

Also happens on Brave iOS app

**Comment by rebron** [comment] 2020-09-02 18:24
@jcesarmobile Hi, I'm not able to reproduce this on our latest release, 1.13.82 following your steps to reproduce. Back and Next navigation works for me on that page.

**Comment by rebron** [comment] 2020-09-02 18:30
Closing as works for me. Couldn't reproduce on 1.13.82, our current release version and 1.14.70 and @LaurenWags with 1.14.72.

**Closed by rebron** 2020-09-02 18:30 UTC
Labels: OS/Desktop

**Comment by jcesarmobile** [comment] 2020-09-02 22:54
Will test tomorrow as I don’t really use brave and I’m on the iPad at the moment. It’s still broken on the iPad version, I also reported it on its appropriate repo, see linked issue.

**Comment by LaurenWags** [comment] 2020-09-03 12:19
Hey @jcesarmobile - I checked a couple iOS versions and I can definitely reproduce there. I commented on your issue in that repo with what I found - https://github.com/brave/brave-ios/issues/2726#issuecomment-686449727

Thanks for reporting this on the appropriate repos, it definitely helps us sort out where the issues are!

**Comment by DiGiTal1133** [comment] 2020-09-03 13:47
ดาวน์โหลด Outlook for iOS<https://aka.ms/o0ukef>
________________________________
จาก: Rafael Ebron <notifications@github.com>
ส่ง: Thursday, September 3, 2020 1:30:41 AM
ถึง: brave/brave-browser <brave-browser@noreply.github.com>
สำเนาถึง: Subscribed <subscribed@noreply.github.com>
ชื่อเรื่อง: Re: [brave/brave-browser] [Desktop] blocking navigation to page (#10792)


Closed #10792<https://github.com/brave/brave-browser/issues/10792>.
