### ISSUE TITLE
"Tips" don't disappear when I disable them

### ISSUE THREAD

**Issue by MoonshineIndustries** [brave/brave-browser#13180] opened 2020-12-13 02:08 UTC
Shove those tips where the sun doesn't shine. Jesus, how thirsty are you? I gotta disable "top" sites, rewards, referrals and now block tips with uBlock. How much more desperate can you be? It's not like you're adding anything of value to this browser.

**Comment by angrybacon** [comment] 2020-12-13 02:35
I noticed it just now and came looking for a way to disable them. When I do this: 

![image](https://user-images.githubusercontent.com/5608624/102001501-48bd0a00-3cf3-11eb-99bb-10d7e8a45687.png)

I don't want to see this:

![image](https://user-images.githubusercontent.com/5608624/102001518-8a4db500-3cf3-11eb-962e-d0f116d970be.png)

Nor this:

![image](https://user-images.githubusercontent.com/5608624/102001589-0e07a180-3cf4-11eb-980a-51a5ec576063.png)

I don't use Twitter so I'm not sure what happening there.

**Comment by kerim** [comment] 2020-12-13 04:30
Same here.

**Comment by kerim** [comment] 2020-12-13 04:32
I would, however, like to have negative tips: the ability to make developers on Github pay me for new ways in which their product has found to annoy me.

**Comment by MoonshineIndustries** [comment] 2020-12-13 05:30
> I would, however, like to have negative tips: the ability to make developers on Github pay me for new ways in which their product has found to annoy me.

It's such an obvious scam too. As if any of those people will get your tips, it's all going in Brave's pockets...

**Comment by rebron** [comment] 2020-12-15 05:11
Closing as a duplicate of #12870. Restarting should disable the Tips icon but looking to fix so doesn't require a browser restart

**Closed by rebron** 2020-12-15 05:11 UTC
Labels: OS/Desktop
