### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by fsclavo** [brave/brave-browser#29031] opened 2023-03-13 17:04 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.49.120  Chromium: 111.0.5563.64
Operating System: Linux 5.15.0-67-generic

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce th is crash? (If it's not reproducible, what were you doing just before the crash?)
1. Nothing special, just browsing normally.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/c4820400-c5e7-be09-0000-000000000000

**Comment by rebron** [comment] 2023-03-16 19:53
Closing as dupe of https://github.com/brave/brave-browser/issues/29083

**Closed by rebron** 2023-03-16 19:53 UTC
Labels: closed/duplicate
