### ISSUE TITLE
Bat Ledger Service uses 99% of CPU

### ISSUE THREAD

**Issue by jesusmartinoza** [brave/brave-browser#8691] opened 2020-03-14 02:51 UTC
## Description 
In the last weeks I noticed that Brave Browser Helper process is using a lot of CPU(~99%). Digging in the browser tools I found that Bat Ledger Service is taking all the CPU.

## Test plan / Steps to Reproduce (edited by @bsclifton)

   1.  Install Brave, fresh profile
   2. Enable rewards
   3. Visit a page (website, twitter profile, etc)
   4. Click BAT icon in omnibox

## Actual result:
<img width="752" alt="CPU usage" src="https://user-images.githubusercontent.com/5506693/76673548-e5d3f200-656b-11ea-8e65-e2e3cea6fec3.png">

## Reproduces how often: 
Every time I open the browser.

## Brave version (brave://version info)
```Brave	1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
Revision	fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS	macOS Version 10.14.6 (Build 18G95)
JavaScript	V8 8.0.426.26
Flash	(Disabled)
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,VideoPlaybackQuality,AllowPopupsDuringPageUnload,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,LookalikeUrlNavigationSuggestionsUI,WebXR,WebXrGamepadModule --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/hongoloco/Library/Application Support/BraveSoftware/Brave-Browser/Default
```

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by congard** [comment] 2020-03-14 16:06
The same issue on Linux.
```
Brave: 1.8.10 Chromium: 80.0.3987.132 (Official build) unknown (64-bit)
Version: fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
```

**Comment by tag9724** [comment] 2020-03-14 22:58
I just started to get the same problem an hour ago after restarting Brave, it seem that the process "Bat Ledger Service" don't stop restarting and I cannot stop it.

```
Brave | 1.7.59 Chromium: 80.0.3987.132 (Official Build) dev (64-bit)
Revision :  fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS  : Windows 10 OS Version 1903 (Build 18362.720)
```

**Comment by victorelec14** [comment] 2020-03-15 20:41
+1

![image](https://user-images.githubusercontent.com/543450/76710172-8ad60280-6705-11ea-8467-0d7d93b15107.png)

> Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
> Windows 10
> Versión	10.0.19582 Build 19582

**Comment by kjozwiak** [comment] 2020-03-15 23:17
Thanks for all the info. We're currently looking into this as we speak. +1 from me as well.

I've noticed this on Friday when I updated to `1.8.11 CR: 80.0.3987.132` as I was a few days behind Nightly. After a bit of time, I started noticing that my machine started turning on the fans/overheating. This has been happening all weekend. As per the above, it's due to the `BAT Ledger Service` going to 100%.

Reproduced using the following:

```
Brave | 1.8.11 Chromium: 80.0.3987.132 (Official Build) nightly (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | macOS Version 10.15.3 (Build 19D76)
```

<img width="881" alt="Screen Shot 2020-03-15 at 6 36 33 PM" src="https://user-images.githubusercontent.com/2602313/76712691-7d168200-66f1-11ea-9376-1cb728763553.png">

CCing @rebron @NejcZdovc @mandar-brave @bsclifton @BrendanEich

**Comment by GeetaSarvadnya** [comment] 2020-03-16 04:47
Experiencing the same issue in `Windows 10x 64 - 1.8.11`

![image](https://user-images.githubusercontent.com/38657976/76723965-3cf5e480-676f-11ea-8797-79f5eeca5554.png)

**Comment by bsclifton** [comment] 2020-03-16 05:30
Updated original issue to add steps. I used the [build bisect tool](https://github.com/brave/brave-browser/wiki/Build-Bisect-Tool) to narrow down the problem to `1.7.30` which is now on Beta and Nightly. Pull request which introduced the problem is https://github.com/brave/brave-core/pull/4252

**Comment by bsclifton** [comment] 2020-03-16 07:44
Marked as `release-notes/exclude` since this has not made it to Release channel yet. Problem that is known is only in Beta/Dev/Nightly

**Closed** 2020-03-16 08:50 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards, perf, priority/P1, release-notes/exclude

**Comment by aleqx** [comment] 2020-03-25 01:47
This is still happening in the new 1.5.115. 100% CPU for Bat Ledger Service, wallet not working properly, registered publishers not recognized at all, ads not showing.

https://community.brave.com/t/bat-ledger-cpu-usage-at-100-publishers-no-longer-recognized-outdated-rewards-info/112190/13?u=alexr

**Comment by NejcZdovc** [comment] 2020-03-25 06:26
@aleqx we have this tracking here https://github.com/brave/brave-browser/issues/8846

**Comment by kjozwiak** [comment] 2020-03-30 16:17
Verification **PASSED** on `macOS 10.15.4 x64 Catalina` using the following build:

```
Brave | 1.7.78 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.15.3 (Build 19D76)
```

* Went through the STR mentioned via https://github.com/brave/brave-browser/issues/8691#issue-581001498
* Tipped `https://duckduckgo.com` & `https://laurenwags.github.io` via `--rewards=staging=true` and ensured that `Utility: BAT Ledger Service` wasn't increasing to 100% CPU

As per https://github.com/brave/brave-browser/issues/8691#issuecomment-603664380, we have an issue that's tracking a similar issue that's occurring on all channels via #8846.

**Comment by victorelec14** [comment] 2020-05-08 19:24
Version 1.8.90 Chromium: 81.0.4044.129 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/543450/81441480-23bb5400-9172-11ea-863d-568bb88d0166.png)

**Comment by NejcZdovc** [comment] 2020-05-09 05:52
@victorelec14 this one should fix the final thing using CPU https://github.com/brave/brave-browser/issues/9607
