### ISSUE TITLE
Devices duplicated after adding them to the Sync chain

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#40130] opened 2024-07-30 22:40 UTC
### Description

Seeing users report that their devices are being duplicated on the Sync chain after being added. This is present across all platforms (Desktop, iOS and Android). Once a device is added to the chain, duplicate entries for that device appear in `Settings --> Managed Synced devices`:

![image](https://github.com/user-attachments/assets/20aa05b0-e01f-4354-9f4c-a3fbccb9df15)

Further, as illustrated above, they seem to _continue_ duplicating over time. One user encountering this also included some additional details:

> Cannot test it now. But when I noticed the issue a few days ago, I had a lot of copies from my Windows Brave too… So it looks like an issue with the Desktop Version, that keeps creating new devices without noticing them. Until now, I did not see any mobile devices duplicating.

> If you delete the duplicates on iPhone or iPad that do not share the same device id as the is shown in the MacOS Brave (but keep the one, that is shown in MacOS Brave), the sync stops working completely. Seems like the Desktop browsers are not only creating new devices that are invisible to themself, but they are also syncing new bookmarks using the new device ids.

This behavior occurs consistently, even if the Sync chain is completely deleted and start fresh. 

### Steps to reproduce

1. Start a Sync chain
2. Add other devices to it
3. Observe devices suplicating

### Actual result

Duplicate devices appear on Sync chain 

### Expected result

Device should only appear once in list after added to the chain

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

v1.68.128

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

User thread:
https://community.brave.com/t/device-is-listed-as-multiple-different-devices/557152/10

Additionally, I can see this occur on my end as well — although they do not _continue_ to duplicate for me, I do see the same device added multiple times, despite only ever having been Synced once:
<img width="469" alt="image" src="https://github.com/user-attachments/assets/5d1eaaf8-b0f6-493e-94ec-79180d9ed020">

**Comment by Satlinker** [comment] 2024-08-04 08:59
Same problem wirh brave in 1 ubuntu PC and 2 android phones.
It doesn't even help to build a complete new sync-chain with a new code.
It seems, that every time when brave on PC starts, a new PC copy appears in both android phones.
It doesn't help to delete the new device copies.
The order of the devices displayed in the device list is different after each start, but is the same on all devices.

**Comment by mingcheng** [comment] 2024-08-05 15:10
![image](https://github.com/user-attachments/assets/0e49a12e-d821-4fe8-a0ad-c2a4408ef6cb)

I have the some problem with my macbook(macos) and surface pro(windows).

I think maybe it's a common issues. plz check this case and fix asap. thx~

**Comment by AlexeyBarabash** [comment] 2024-08-07 11:32
We had similar issue on Android:
https://github.com/brave/brave-browser/issues/39470

At that time it wasn't reproduced for Desktops.

I am working on the current.

**Comment by AlexeyBarabash** [comment] 2024-08-07 13:44
I wasn't able to reproduce this issue neither on macOS/Windows/Linux/Android. Tested on the latest Stable version `1.68.134 Chromium: 127.0.6533.88 (Official Build) unknown (64-bit) `. Also I had done several browser restarts - but this didn't help to get the issue.
Android|Windows PC|macOS|Ubuntu Linux
--|--|--|--
![Screenshot_20240807-154108](https://github.com/user-attachments/assets/dd2aad94-df57-48bd-bd90-f3b0f99fbf91)|![image (3)](https://github.com/user-attachments/assets/a1a5b39f-45a9-46ac-86a2-2f83e7ea1d76)|![Screenshot 2024-08-07 at 16 00 00](https://github.com/user-attachments/assets/b470534d-b628-48b6-b9e3-a117d0458ee0)|![image (4)](https://github.com/user-attachments/assets/eb1dcdcd-52f6-4ef5-8b2d-ae30d684ec4d)

@Satlinker , @mingcheng , could you please share, what Brave version do you use on the devices? Is it the latest Stable version, `1.68.x`?

**Comment by codetist** [comment] 2024-08-07 15:01
I can still reproduce it with Desktop Version `1.68.134 Chromium: 127.0.6533.88 (Official Build) (arm64)` and Mobile Version `1.67 (127)`.

What did I do. 
* Removed old sync chain and all bookmarks from all devices (MacBook, iPhone and iPad)
* Created some test bookmarks an Brave Desktop
* Created new sync chain on Brave Desktop
* Added iPhone
* Added iPad
* All devices synced!
* Quit Brave via `Brave` menu on MacBook (not just hide the window, really exit the application)
* Restarted Brave
* **Load a page from a random existing bookmark**
* Voila.... Desktop Brave appears twice on iPhone and iPad

Just kept the sync chain window open and repeated the cycle. Every time I close Brave Desktop, reopen it AND **click an existing bookmark** a new copy appears on mobile devices. It seems not to happen, if I open Brave Desktop without interacting with existing bookmarks.

**Comment by AlexeyBarabash** [comment] 2024-08-08 20:11
thanks @codetist 
I tried the exact steps you have posted, but I found a weird issue - it left the chain by itself:
![image](https://github.com/user-attachments/assets/f752b4ec-5540-4154-b51b-4ac666ac3ad6)
according to the sync-internals the passphrase is set and OS encryption is available and I for sure didn't click on leave sync chain button.

Browser was updated to `1.68.137 Chromium: 127.0.6533.100 (Official Build) (x86_64)` maybe something weird happened there.

**Comment by codetist** [comment] 2024-08-08 21:10
Strange....
I also updated mine to the same version `[Version 1.68.137 Chromium: 127.0.6533.100 (Offizieller Build) (arm64)]` (although it's `arm64` in my case), deleted old chain, created new one.... and just keep getting duplicates as before.

**Comment by AlexeyBarabash** [comment] 2024-08-08 21:13
thanks
Then I will use a new profile with backed up the current failed.

**Comment by codetist** [comment] 2024-08-08 22:48
As you mentioned profiles.... I deleted my profile, the problem was gone. I just set up everything as usual, problem re-appeared. But finally found what seems to be the root cause: The device id stays stable, which means no duplicates, as long as you do not enable "clear cookies and website data" on browser exit. As soon as this option is enabled, the browser creates a new device id for itself after each restart. It stops immediately after disabling this option.

I don't know how to switch the browser to English, but that's the setting in German interface:
<img width="980" alt="image" src="https://github.com/user-attachments/assets/318731c5-d113-4e3a-b1e0-5c95d1480531">

**Comment by AlexeyBarabash** [comment] 2024-08-09 09:33
Thanks @codetist !!!

With the step you provided of enabling 
`Preference and security` => `Delete browsing data` => `On exit` => `Cookies and other site data`

I was able to reproduce the issue immediately, even on Linux.

Investigating and preparing a fix.

**Comment by mingcheng** [comment] 2024-08-09 16:40
> I wasn't able to reproduce this issue neither on macOS/Windows/Linux/Android. Tested on the latest Stable version `1.68.134 Chromium: 127.0.6533.88 (Official Build) unknown (64-bit) `. Also I had done several browser restarts - but this didn't help to get the issue.
> 
> Android	Windows PC	macOS	Ubuntu Linux
> ![Screenshot_20240807-154108](https://github.com/user-attachments/assets/dd2aad94-df57-48bd-bd90-f3b0f99fbf91)	![image (3)](https://github.com/user-attachments/assets/a1a5b39f-45a9-46ac-86a2-2f83e7ea1d76)	![Screenshot 2024-08-07 at 16 00 00](https://github.com/user-attachments/assets/b470534d-b628-48b6-b9e3-a117d0458ee0)	![image (4)](https://github.com/user-attachments/assets/eb1dcdcd-52f6-4ef5-8b2d-ae30d684ec4d)
> @Satlinker , @mingcheng , could you please share, what Brave version do you use on the devices? Is it the latest Stable version, `1.68.x`?

yes, it's the last stable release. 

<img width="737" alt="Screenshot 2024-08-10 at 00 38 40" src="https://github.com/user-attachments/assets/d00ed44a-ebf4-4856-9a1f-9c173e6bc0cd">

**Comment by poun64** [comment] 2024-08-09 17:18
Hello,
This duplication problem has been around for several weeks. I'm struggling with it and I thought I was the only one...
My operating systems are Windows 10 and 11, Xubuntu 22.04 and 24.04 and I delete my cookies at the end of each Brave session.
These devices duplicate each other until synchronization is blocked.
Brave is up to date, for example for Xubuntu 24.04: Version 1.68.137 Chromium: 127.0.6533.100 (Official Build) (64 bits).
Note : translated from French with https://www.deepl.com/fr/translator

![Synchro Brave](https://github.com/user-attachments/assets/671c26ae-6939-4a97-a4b4-6de34a2589e1)

**Comment by AlexeyBarabash** [comment] 2024-08-15 12:40
Here is a code responsible for leaving the sync chain: 
https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/browsing_data/chrome_browsing_data_remover_delegate.cc;l=1547;bpv=0

Related Chromium change:
https://source.chromium.org/chromium/chromium/src/+/d1756d22e544a554af3594fa71c839d2c472b2e1

Upstream's logic is - when we delete cookies, we must log out from the websites and when we logout from the Google account, we also must logout from browser Sync.
For sure this is not applicable for Brave and I am fixing it.

**Comment by H2SO4JB** [comment] 2024-08-15 18:00
I'm not that familiar with how Github works, but does this mean the bug has been found and an update will be released shortly to fix this? I have big problems with duplicates as soon as I create a sync chain, even if I do fresh Brave installs without any extensions.

**Comment by AlexeyBarabash** [comment] 2024-08-16 08:24
@H2SO4JB 
> does this mean the bug has been found and an update will be released shortly to fix this? 

yes, this means the bug was found, work on fix is in progress.

> and an update will be released shortly to fix this?

some time is required to complete PR, get the review, get the QA approval and uplift to Stable channel, so I am expectinhg it will be ready the next week.

**Comment by H2SO4JB** [comment] 2024-08-16 11:17
@AlexeyBarabash 
Great, thanks! Then I await the next release with excitement. 😃

**Comment by TheZitroX** [comment] 2024-08-22 04:38
And i was worried about my passwords gotten apart.

**Comment by thag0205** [comment] 2024-08-23 09:36
Fix did not make it into 1.69.153.  Still duplicating sync devices when clearing cookies manually or upon exit when option is selected.  Release notes made no reference to this issue 40130.  Hopefully this fix will make it into the next update.

**Closed** 2024-08-24 11:10 UTC
Labels: bug, feature/sync, priority/P2, QA/Yes, release-notes/include, OS/Desktop

**Comment by AlexeyBarabash** [comment] 2024-08-26 07:24
> Fix did not make it into 1.69.153. Still duplicating sync devices when clearing cookies manually or upon exit when option is selected. Release notes made no reference to this issue 40130. Hopefully this fix will make it into the next update.

sorry, @thag0205 I wasn't able to complete it last week, just created uplift PRs today into beta and stable versions. Hopefully it will be available with the next hotfix.

**Comment by GeetaSarvadnya** [comment] 2024-08-27 11:03
Verification INPROGRESS on

```
Brave | 1.69.156 Chromium: 128.0.6613.85 (Official Build) (64-bit)
-- | --
Revision | 1d701f8c67ab98b8c562ddd0fa2dafc1305f8605
OS | Windows 10 Version 22H2 (Build 19045.4780)
```

**Comment by H2SO4JB** [comment] 2024-09-09 16:31
Hi,

Why is this bug marked as solved? To this day I can't get these duplicates to stop being created in my sync chains when "Cookies and other site data" to clear on exit is enabled. I have done several tests now for several days, there of my late reply.

I have Brave V1.69.162 on four Windows computers. After this update was released, I updated Brave on all my computers and deleted the sync chain on all of them. Then I created a new sync chain but the duplicates keep getting created. Then I went through the same procedure again but without enabling "Cookies and other site data" to clear on exit. I've had it like that for several days now and it works perfectly, no duplicates.

But now when I enable "Cookies and other site data" to clear on exit again, immediately duplicates start to be created.

Shouldn't this bug be fixed already in V1.69.160? I have V1.69.162 in my four computers.
Or what am I missing?

**Comment by thag0205** [comment] 2024-09-09 16:40
I have v1.69.162 on macOS and can confirm its happening again.  Was fixed under v1.69.160.  So apparently the bug was reintroduced under v1.69.162.

**Comment by H2SO4JB** [comment] 2024-09-09 16:46
Glad to hear I'm not alone. This is driving me crazy as I thought I was alone with this problem. Hope those who know this look at it again.
AlexeyBarabash?

**Comment by poun64** [comment] 2024-09-09 16:49
Hello everyone,
I confirm, with Brave version 1.69.122 under Linux, devices continue to be duplicated if cookies are deleted.
This problem is still unresolved, contrary to what was announced for Release Notes v1.69.160 (Aug 29, 2024) [Fixed issue where synced devices could be duplicated in certain cases. (#40130)].
Translated from the French with “https://www.deepl.com/”

**Comment by TheZitroX** [comment] 2024-09-09 17:53
Who tested it and said it's fixed?

**Comment by poun64** [comment] 2024-09-09 17:59
It says here: https://brave.com/latest/

**Comment by codetist** [comment] 2024-09-10 05:59
Yepp. It is still happening. Not as often as before and it looks somehow random for me now.
Clearing the browser data seems not to be the only reason, that causes loss of the device id.

**Comment by H2SO4JB** [comment] 2024-09-10 08:17
@AlexeyBarabash
Is this something you might look at again?

**Comment by a-1375** [comment] 2024-09-10 17:46
Im also still having that issue on 1.69.162 stable, where my sequoia mac is duplicating in the sync list on my ubuntu device, adding one more duplicate every time I reopen the mac browser after it’s been closed. 

I too have the setting enabled where cookies delete on closing, and can confirm that deleting and creating a new chain didn't seem to help at all, but deactivating that cookie setting in the mac’s browser seem to have stopped it from duplicating.

hough:
I then toggled that setting back on, wanting to confirm the issue reproducing again, but it seems not to, even though I’ve closed and reopened the mac browser multiple times in the last hours.

Have also tried closing in different ways (eg. ⌘+Q or through menu), tried closing the browser on both devices, tried closing them in different order, tried opening them in different order, and in between closings I visited the sync settings a couple of times and opened some websites from bookmarks. 
I’ve also deleted the chain and started a new one to see if I could reproduce it then, but I still can’t.  

And nothing else has been changed in settings and such, don't know if that off/on-toggle I did on the cookie setting can somehow have resolved the issue for me, at least it hasn’t reappeared for me since I did the toggle a couple of hours ago. 

But maybe I’m missing something as to why it stopped for me, or maybe it has just changed from appearing constantly to only happen once in a while, as @codetist mentioned. 


I guess it's already tried by others of course, but maybe someone could try that same toggling and comment if it stopped the issue for you too.


 Details on the issue for me (before it stopped) and on my device setup:

-Have deleted the chain/sync account from server and started a new one a couple of times, first by deleting chain from Ubuntu device, next time doing it from the mac device, issue still reproduced.
-These two computers are the only devices on my chain, and chain was started from the ubuntu device
-I only used the bookmarks sync, all others I had left on default disabled
-A one way issue for me, the ubuntu device does not duplicate in the sync list on the mac, it’s only the mac duplicating in the sync list on the ubuntu device.

-The mac was on Sonoma when I noticed the issue and is now on Sequoia, issue was reproduced equally on sequoia and sonoma.
-The Ubuntu is 24.04 running on mac hardware (dual boot with macOS 10.7, but separate macbook from the sequoia one).

**Comment by poun64** [comment] 2024-09-12 00:11
Good evening,
As a test, I synchronized two devices on the same channel. Both are running Brave Version 1.69.162 Chromium: 128.0.6613.120 (Official Build) (64 bits).
The first device is running Linux Xubuntu 22.04.
The second device runs Linux Xubuntu 24.04.
I use them both every day, and only the one running Xubuntu 22.04 is duplicated.
The settings are the same and the cookies are deleted every time I close the browsers.
My test lasted several days...
**Note: I didn't test toggling “On/Off” the deletion of cookies when closing browsers.**

**Comment by codetist** [comment] 2024-09-12 09:36
@a-1375 I did toggle cookie deletion to off, saved and returned to on yesterday. Second day without duplication.... That's unusual at least...

**Comment by poun64** [comment] 2024-09-16 00:02
In Version 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit) under Linux, devices are always duplicated.
The problem has yet to be solved.
I've just tested it over 2 days:
- Deleting cookies when closing the browser,
- Or by checking “Forget me when I close this site” in the “Protections” menu...

**Comment by a-1375** [comment] 2024-09-16 21:08
> @a-1375 I did toggle cookie deletion to off, saved and returned to on yesterday. Second day without duplication on my Mac.... That's unusual at least... 


Huh, that's interesting, indeed a bit unclear.. Well anyway, I hope you get to keep it that way! 

(Maybe best to not get the hopes up to much though, at least until some more days have passed where the bug continues to be challenged by all the different stuff that normal browser usage brings)

**Comment by a-1375** [comment] 2024-09-16 23:19
@techbot2342 Good to know, because I was about to give it a try and turn off every cookie/site data-delete-setting I can find, on all my 5 operating systems..

Dont mind to dump that theory for something easier that works, so what would you say is the way to at least temporary counter this dysfunctional sync-behaviour until it can be properly addressed, fixed and pushed to stable?

**Comment by poun64** [comment] 2024-09-17 00:06
I see in the topic header that'it has been declared “Closed” “Solved ???”

Shouldn't we warn **AlexeyBarabash** [https://github.com/AlexeyBarabash] that the problem persists, he who seems to have worked on this bug???
Personally, I don't know what to do...
