### ISSUE TITLE
Brave wallet use URI instead of domain for verification, creating incompatibility issue with service using DID as URI

### ISSUE THREAD

**Issue by marc-aurele-besner** [brave/brave-browser#35410] opened 2024-01-18 14:40 UTC
## Description 
Services like Ceramic typically pass in the DID of the user as the URI in the Siwe message.

Brave wallet seems to be verifying that the URI match the origin of the request, instead to be using the domain property of the Siwe message.

This makes it therefore impossible to sign such message, giving this error in Brave Wallet:
<img width="328" alt="braveWalletError" src="https://github.com/brave/brave-browser/assets/82244926/644721eb-e7a3-43ce-81cd-f94d3c0f4e6f">

## Steps to Reproduce

   1. While on Brave, with Brave Wallet enable, visit https://app.oamo.io
   2. Connect your wallet and try to sign the message, you should have the same error as the screenshot
  
  * You may need to disable Brave Shield

## Actual result:
<img width="328" alt="braveWalletError" src="https://github.com/brave/brave-browser/assets/82244926/644721eb-e7a3-43ce-81cd-f94d3c0f4e6f">

## Expected result:
Regular signing message like:
![image](https://github.com/brave/brave-browser/assets/82244926/ef437e70-eabf-459c-9e99-a8b0ed6cedd9)

## Reproduces how often: 
Each time when signing the Siwe message

## Version/Channel Information:
Version 1.61.116 Chromium 20.0.6099.17

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? I haven't try
- Can you reproduce this issue with the nightly channel? I haven't try

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No (It's link to Brave Wallet)

**Comment by kdenhartog** [comment] 2024-02-01 18:52
closing as a duplicate of https://github.com/brave/brave-browser/issues/34470

We'll take a look still

**Closed by kdenhartog** 2024-02-01 18:52 UTC
Labels: feature/web3/wallet, OS/Desktop
