### ISSUE TITLE
Brave page indicator text not visible in dark theme

### ISSUE THREAD

**Issue by Liunkae** [brave/brave-browser#1026] opened 2018-09-07 18:30 UTC
## Description 
When you visit a Brave system page (chrome://) like chrome://settings/, the "Brave" text in the url bar is black. This makes it hard to read when using the dark theme.

## Steps to Reproduce
   1. Open Settings (select kabob menu > Settings)
   2. Make sure the "Brave colors" setting is set to "Default" or "Dark"

## Actual result:
![image](https://user-images.githubusercontent.com/19424103/45236547-c0449900-b2a1-11e8-9af2-071b228ba127.png)
The "Brave" text is hard to read.

## Expected result:
The "Brave" text should be white to provide contrast with the black background.

## Reproduces how often: 
Always

## Brave version (about:brave info) 
Version 0.55.1 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)

### Reproducible on current release:
No.

**Comment by petemill** [comment] 2018-09-07 20:35
Duplicate of https://github.com/brave/brave-browser/issues/978

**Closed by petemill** 2018-09-07 20:35 UTC
