### ISSUE TITLE
Copying brave:// URL using keyboard shortcut copies chrome:// scheme

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#28588] opened 2023-02-17 17:57 UTC
## Description 

Copying brave:// URL using keyboard shortcut copies chrome:// scheme

## Steps to Reproduce

1. install `1.49.100`
2. launch Brave
3. open `brave://settings/appearance`
4. copy the above URL using `command` + `C`
5. paste and note the URL
6. copy the above URL using the `Copy` context-menu item
7. paste and note the URL

## Actual result:

`command`+`C` = `chrome://settings/appearance`
`Copy` context-menu = `brave://settings/appearance`

## Expected result:

In both cases, it should copy `brave://settings/appearance`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.49.100 Chromium: 110.0.5481.100 (Official Build) beta (x86_64)
-- | --
Revision | 4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS | macOS Version 11.7.4 (Build 20G1120)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

/cc @spylogsster @LaurenWags @rebron @kjozwiak @emerick @mkarolin

**Comment by MadhaviSeelam** [comment] 2023-02-17 18:17
Couldn't reproduce in Win 11 x64  (Ctrl + C)
```
Brave | 1.49.100 Chromium: 110.0.5481.100 (Official Build) beta (64-bit)
-- | --
Revision | 4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS | Windows 11 Version 21H2 (Build 22000.1574)
```

**Comment by LaurenWags** [comment] 2023-02-17 18:30
Can reproduce with `1.49.100` (C110) on Beta but not a prior release `1.47.186` (C109). 

Seems like possibly a C110 regression.

**Comment by spylogsster** [comment] 2023-02-21 11:11
Looks like fixed in latest master, cannot reproduce it on 1.50.50 Nightly for macos, but was able to reproduce on 1.50.38,
@stephendonner @LaurenWags @MadhaviSeelam can you pls recheck on your side? thanks

**Comment by spylogsster** [comment] 2023-02-22 08:02
Closing as not reproducible anymore

**Comment by rebron** [comment] 2023-03-03 00:06
@LaurenWags @stephendonner @MadhaviSeelam Can you recheck this with the release candidate 1.49.117 Chromium: 111.0.5563.50 (Official Build) (arm64) 

I'm seeing chrome:// when copying from an internal page.

**Comment by LaurenWags** [comment] 2023-03-03 14:34
@rebron Tried with `1.49.117` and can reproduce, I get `chrome://` instead of `brave://` example - copied `brave://version/` via `cmd + C` but `chrome://version/` was pasted here. Copying `brave://version/` via context menu pastes `brave://version/` as expected.

However, also tried with `1.49.118` (newer RC) and I am getting `brave://` not `chrome://`.

Example, copied from `brave://settings/appearance` and pasted in this comment. Pasting in Slack does the same thing. Tried copying via "cmd + C" as well as context menu.  

Can you try the latest RC to confirm?

**Comment by rebron** [comment] 2023-03-09 16:16
Closing. Tested in latest RC. Looks good with copy and paste from steps in last comment. 

Brave | 1.49.120 Chromium: 111.0.5563.64 (Official Build) (arm64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 13.3 (a) (Build 22E7752300f)
JavaScript | V8 11.1.277.13
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

**Closed by rebron** 2023-03-09 16:16 UTC
Labels: bug, closed/invalid, priority/P2, branding, OS/Desktop
