### ISSUE TITLE
Android Autoplay should parity Desktop

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#13343] opened 2020-12-30 23:08 UTC
## Description 
The Android app no longer has the option to adjust `Autoplay` options/permissions as per:
https://support.google.com/chrome/thread/26214034?hl=en

The Android version of Brave should offer the same autoplay options (as a permission, global as well as per-site) as theDesktop version does.
cc @SergeyZhukovsky @anthonypkeane 

### Additional information

https://bravesoftware.slack.com/archives/C0816QH3R/p1609179962208200

**Comment by SscoootzZ** [comment] 2021-04-13 16:49
Hi Brave Team,

I'm still learning my way around GitHub, so caveat to my post here. 2nd'ly I'm one of many users who are endeared to the notion of migrating exclusively to the Brave platform (and your project is also the name of our adorbs li'l Chi'Weenie, so there's that ^_^). I'm wondering what the action is on the autoplay issue, for the Android/mobile platform. It is mentioned—in the (mobile) Brave installation start-up info—that this browser can help in conserving data usage re: web browsing, which seems like what this option would address. (I know that is a paraphrase of the feature description.) Now I see that it was moved 27 days ago, and that it is listed as "Open." Does that mean that the issue is still actively bring worked on? I understand that it's very busy work to dev a large-scale and cross-platform project. That said, if one of you is willing/able to take a few minutes for a quick explanation and/or update, I'd really appreciate your time. 

Regards,
Scott

**Comment by mattspew** [comment] 2021-08-11 22:02
Why are you dragging your feet on this? Blocking auto-play is essential!

**Comment by AllamanB** [comment] 2021-08-23 08:52
you're really taking your time with this it's ridiculous to see how brave developers don't pay any attention to one of thier most important platforms and keep losing users this function has been added to bromite by hobbist developers and it works perfectly fine.
I suggest to take a look at thier repo and add this must-have feature to brave:
https://github.com/bromite/bromite/blob/2251acbca8218619186c410d91f95b553be989d5/build/patches/Revert-the-removal-of-an-option-to-block-autoplay.patch

https://github.com/bromite/bromite/blob/2251acbca8218619186c410d91f95b553be989d5/build/patches/Disable-unified-autoplay-feature.patch

BTW please don't make excuses that you want to use a better way to block autoplay this is an important feature that you couldn't find a way to add for a long time so just do what they did.

**Comment by anthonypkeane** [comment] 2021-08-23 19:56
Duplicate of https://github.com/brave/brave-browser/issues/14142

**Closed** 2021-08-23 21:49 UTC
Labels: closed/duplicate, feature/autoplay, OS/Android, privacy/permissions

**Comment by mattspew** [comment] 2021-08-23 22:26
Duplicate of a more recent job id? That doesn't make sense.
