### ISSUE TITLE
Change "no tokens" messaging on BR panel for BAT Points regions

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#6604] opened 2019-10-24 20:01 UTC
For locales where BAT Points are required, when wallet Balance = 0, change the list of "3 ways to fill your wallet":

1) Delete the heading and the 3 bullets

2) Replace it with a sentence -> "Look for ad notifications as you continue to use Brave. Your BAT Points balance will increase with each ad you view."

Reason: Users can't add funds, and we are unlikely to issue free token grants. 

![Screen Shot 2019-10-24 at 12 53 05](https://user-images.githubusercontent.com/71029/67520440-b0327900-f65d-11e9-9858-af92a96bf6c8.png)

**Comment by rebron** [comment] 2019-10-30 22:43
Closing. Duplicate of #6654

**Closed** 2019-11-07 15:31 UTC
Labels: 1.0, QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards, l10n

**Comment by GeetaSarvadnya** [comment] 2019-11-11 05:03
Verification passed on


Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/68562223-bc487400-046e-11ea-9e27-8fe25e236fae.png)
