### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#32022] opened 2023-08-01 21:32 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.57.33 Chromium: 115.0.5790.114
Operating System: Linux 6.2.6-76060206-generic

URL (if applicable) where crash occurred: I opened a guest window from the hamburger menu.

Perfectly reproducible. I can trigger a full browser crash by trying to open a guest window.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/288f0900-0f67-770a-0000-000000000000

**Comment by bsclifton** [comment] 2023-08-01 23:41
Thanks for reporting @fmarier - going to close as a dupe of https://github.com/brave/brave-browser/issues/31997

@fallaciousreasoning has a fix up here:
https://github.com/brave/brave-core/pull/19511

**Closed** 2023-08-01 23:41 UTC
Labels: crash
