### ISSUE TITLE
Shouldn't have to click on `Refresh Brave VPN` after initial purchase

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#24987] opened 2022-08-26 00:19 UTC
## Description 

Shouldn't have to click on `Refresh Brave VPN` after initial purchase

## Steps to Reproduce

   1. install `1.45.1`
   2. launch Brave using `--vmodule="*/VPN/*"=1 --enable-logging=stderr`
   3. via `brave://flags`, set `Enable experimental SKU SDK` to `Enabled`
   4. click `Relaunch`
   5. load `account.brave.software`
   6. enter basic-auth creds for site
   7. enter an email address and click `Get login link` 
   8. check your email inbox
   9. click `Log in to Brave` or the link in the email
   10. click on `Browse plans`
   11. scroll down and click on `Buy now` for `Brave VPN Subscription`
   12. enter payment details on `https://checkout.stripe.com/pay/cs_test…`
   13. click `Subscribe`
   14. you should get a `Complete your purchase`... screen
   15. click on `Complete payment`
   16. click on the `VPN` button in the toolbar (or via the "`hamburger"` -> `Brave VPN` menu
   
 
## Actual result:

<img width="1574" alt="Screenshot 2022-08-25 at 4 44 23 PM" src="https://user-images.githubusercontent.com/387249/186790212-168c38ee-9bed-41da-8fc3-a6917cfbd3d3.png">

## Expected result:

<img width="1574" alt="Screenshot 2022-08-25 at 4 44 32 PM" src="https://user-images.githubusercontent.com/387249/186790259-cbf9e440-4d82-4763-96d6-835dc074e945.png">

Should not have to manually click to "refresh" just-issued credentials

This used to Just Work (`tm`)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.44.60 Chromium: 105.0.5195.37 (Official Build) nightly (x86_64)
-- | --
Revision | 5f67e9f258cc28ab970e57572290edf1863ee3c5-refs/branch-heads/5195@{#621}
OS | macOS Version 13.0 (Build 22A5321d)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@mattmcalister @bsclifton @simonhong @spylogsster @srirambv @husobee @AlanBreck

**Comment by AlanBreck** [comment] 2022-08-26 01:21
@stephendonner, this used to work as described? There haven't been any recent changes to accounts staging environment. Are there error logs in the console?

**Comment by stephendonner** [comment] 2022-08-26 15:01
> @stephendonner, this used to work as described? There haven't been any recent changes to accounts staging environment. Are there error logs in the console?

Yes, this used to work automagically, before.  It's not a very-recent regression, however, sorry: I've been experiencing this for at least a few weeks (3+) and have simply just worked around :-(

**Comment by stephendonner** [comment] 2022-08-29 16:58
Before clicking on `Refresh Brave VPN`, I entered `!!(navigator.brave && window.chrome.braveSkus)` into the console:

<img width="1312" alt="Screen Shot 2022-08-29 at 9 51 51 AM" src="https://user-images.githubusercontent.com/387249/187253436-e41bff53-c6f7-4147-a8f5-abc3f05c9580.png">


This shows we have valid credentials at this time.

**Comment by stephendonner** [comment] 2022-08-31 21:44
Tried to find a regression range, today, and tested the following builds, **_none_** of which had this working automagically after purchase, either:
* 1.43.20
* 1.42.78
* 1.41.88
* 1.40.90

The last two there, `1.41.88` and `1.40.90` don't get past the `Buy now` button click - they just spin.

**Comment by spylogsster** [comment] 2022-10-13 08:20
Looks like it was fixed together with https://github.com/brave/brave-browser/issues/25946, @stephendonner I cannot reproduce anymore, closing to recheck

**Closed by spylogsster** 2022-10-13 08:20 UTC
Labels: bug, QA/Test-Plan-Specified, regression, OS/Desktop, feature/vpn

**Comment by LaurenWags** [comment] 2022-11-21 15:47
Verified with

```
Brave	1.46.118 Chromium: 108.0.5359.48 (Official Build) beta (arm64) 
Revision	18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS	macOS Version 12.6.1 (Build 21G217)
```

Verified STR from https://github.com/brave/brave-browser/issues/24987#issue-1351571561 with some minor differences as detailed below:

   1. install `1.46.118`
   2. launch Brave using `--args --vmodule="*/skus/*"=2 --enable-logging=stderr --v=0`
   3. via `brave://flags`, set `VPN` to `Enabled`
   4. Relaunched the browser
   5. load `account.bravesoftware.com` (staging site, not dev)
   6. enter basic-auth creds for site
   7. enter an email address and click `Get login link` 
   8. check your email inbox
   9. click `Log in to Brave` or the link in the email
   10. click on `Browse plans`
   11. scroll down and click on `Buy now` for `Brave VPN Subscription`
   12. enter payment details on `https://checkout.stripe.com/pay/cs_test…`
   13. click on the `VPN` button in the toolbar (or via the "`hamburger"` -> `Brave VPN` menu

--> Confirmed no "Buy" copy shown, the switch to toggle VPN on was shown
--> Confirmed after toggling VPN on, I was prompted to install config
--> Confirmed after installing config, VPN was enabled (did not encounter https://github.com/brave/brave-browser/issues/26863)

Example | Example | Example | Example | Example
---- | ---- | ---- | ---- | ----
<img width="1195" alt="1" src="https://user-images.githubusercontent.com/28145373/203097999-61d1e80f-a6b6-4ba9-adf7-fe8d2408343c.png"> | <img width="1191" alt="2" src="https://user-images.githubusercontent.com/28145373/203098002-6532e921-8c90-4ab3-8159-45c55d9f65df.png"> | <img width="1190" alt="3" src="https://user-images.githubusercontent.com/28145373/203098003-6834c1d5-d37e-43ce-9291-c0612df90107.png"> | <img width="1191" alt="4" src="https://user-images.githubusercontent.com/28145373/203098005-c504946d-ccec-4668-8fb6-1369f3dbebf1.png"> | <img width="520" alt="5" src="https://user-images.githubusercontent.com/28145373/203098006-e764afa2-554c-4549-9de7-0452a79d66cb.png">

**Comment by MadhaviSeelam** [comment] 2022-11-21 16:02
Verification `PASSED` using
```
Brave | 1.46.121 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

Verified using original STR from https://github.com/brave/brave-browser/issues/24987#issue-1351571561

- Verified  no `Brave Firewall +VPN Buy` onboard modal displayed
- Verified `Refresh Brave VPN` button is no longer available 
- Confirmed correct modal with VPN toggled `OFF` displayed when clicked on VPN button after initial purchase
- Verified VPN was successfully connected with green light displayed

VPN after initial purchase|connected
------|-----
![image](https://user-images.githubusercontent.com/98358127/203098194-aba8e576-fbee-40f8-a2e9-d0d3fa03eceb.png) |![image](https://user-images.githubusercontent.com/98358127/203099376-8d0ab6c6-6673-4701-9299-39b0637bed8f.png)

**Comment by stephendonner** [comment] 2022-11-22 08:13
## Verified `PASSED` using 

Brave | 1.46.122 Chromium: 108.0.5359.48 (Official Build) beta (x86_64)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)

Followed my STR from https://github.com/brave/brave-browser/issues/24987#issue-1351571561:

- Verified no Brave Firewall +VPN Buy onboard modal displayed
- Verified Refresh Brave VPN button is no longer available
- Confirmed correct modal with VPN toggled OFF displayed when clicked on VPN button after initial purchase
- Verified VPN was successfully connected with green light displayed

I did encounter the `Couldn't connect to server` error, but a click on `Try again` connected just fine, to the auto-detected server.  We'll continue to suss out VPN-connection issues through the test lifecycle.



VPN after initial purchase | connected to `BraveVPN`
--------------------------|--------------------------
<img width="1312" alt="Screen Shot 2022-11-23 at 12 02 41 AM" src="https://user-images.githubusercontent.com/387249/203258431-720c0dc3-e829-4b4c-ac5e-50c1d68a27c3.png"> | <img width="1312" alt="Screen Shot 2022-11-23 at 12 01 26 AM" src="https://user-images.githubusercontent.com/387249/203258346-5b62bf34-64b3-43de-9da8-cebffabfaae1.png">
