### ISSUE TITLE
Consider changing return type of `NTPBackgroundPrefs::GetSelectedValue()` to `std::string`

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#25602] opened 2022-09-25 10:01 UTC
Having absl::variant return type doesn't seem to be useful that much.

e.g. GURL can be constructed from std::string, absl::hold_alternative<GURL>() seems to return true even when std::string was stored in the variant.

**Comment by null-sys** [comment] 2022-09-27 19:45
Hey @sangwoo108 , I am new on this repo and this seems like a good start for me. I would like to contribute on this issue. Can you assign this to me?

**Comment by sangwoo108** [comment] 2022-09-27 22:46
Hi, @null-sys . Thank you for your interest! I assigned you.

**Comment by tony83033** [comment] 2022-10-01 15:02
Hii @sangwoo108  sir , I am new in opensource , and brave browser seems like a good start for me . I would like to contribute on this issue. Can you pls assign this to me ?

**Comment by sangwoo108** [comment] 2022-10-02 03:06
hi @tony83033 ! I'm sorry but I think @null-sys is already on this. Let me know you if I get something new good-first issue. Which language do you prefer between js and c++?

**Comment by tony83033** [comment] 2022-10-02 03:44
Thanks @sangwoo108 , I prefer  J.S

**Comment by null-sys** [comment] 2022-10-02 16:06
Hey @sangwoo108 , I raise a RR since the change was simple. But brave repo, workflow and contribution is quite complicated. Can you please spare some time and explain few things to me? I want to contribute longer on this repo.

**Comment by sangwoo108** [comment] 2022-10-03 06:49
Thanks @null-sys . I saw your PR but I think the patch would break the build. Did you happen to try building the browser yourself? The build instruction is here: https://github.com/brave/brave-browser/blob/master/README.md

> Can you please spare some time and explain few things to me?

That would be my pleasure.

**Comment by tarannum-2002** [comment] 2022-12-07 13:53
Since this issue is still open, can i work on this?
I have started open source recently i'd like to contribute

**Comment by sangwoo108** [comment] 2022-12-08 01:03
Hi, @tarannum-2002, Welcome! It doesn't seem @null-sys is working on this for a few months, so I believe you can take this.

**Comment by vednp** [comment] 2023-03-24 15:42
Hi I am new to this repo and as a user of brave I would like to contribute to this as it is still open I would like to do it if you can assign it to me

**Comment by hjasaiwal114** [comment] 2023-04-01 20:42
since this issue is open can i contribute to that ?

**Comment by sangwoo108** [comment] 2023-04-04 08:15
Hi, @hjasaiwal114 . It's open but I'm concerned if @vednp is still working on it. Could you wait for @vednp could to confirm?

Hi, @vednp . How's it going? I'm wondering if you're still working on this.

**Comment by vednp** [comment] 2023-04-04 10:58
@sangwoo108 I am facing an error while building I followed steps maybe you can try assigning @hjasaiwal114 if he could solve it.

**Comment by sangwoo108** [comment] 2023-04-04 13:53
@hjasaiwal114 I assigned you.

@vednp Meanwhile, is there anything I can help you with? Could you tell me what errors you're facing?

**Comment by hjasaiwal114** [comment] 2023-04-04 19:58
Thank you @sangwoo108  for assigning me could you tell me which file code is

**Comment by sangwoo108** [comment] 2023-04-17 14:43
Hi, @hjasaiwal114 . Sorry for delayed response. I guess the https://github.com/brave/brave-core/pull/15314 could be a good start point. The PR changes the return type but doesn't include  changes fro its callsites. I'd like to recommend build the browser by yourself.

**Comment by ajayseeker** [comment] 2024-03-17 18:39
Hey @sangwoo108, I see the issue is still open and last conversation was almost a year back. I would like take this issue up. Can you please assign it to me?

**Comment by sangwoo108** [comment] 2024-03-17 23:32
Hi @ajayseeker . Assigned to you. Thanks!

**Comment by ajayseeker** [comment] 2024-03-21 17:47
Hi @sangwoo108, I've raised a [ PR](https://github.com/brave/brave-core/pull/22707), Can you please review it?
I've done the following:
1. Changed method signature
2. Modified code in all the references of the method
3. Ran npm run build command and ensured build passes
4. Ran test cases and ensured no test case failed due to change in GetSelectedValue()
Please, guide me if I've missed on anything.

**Comment by sangwoo108** [comment] 2024-03-21 22:56
Sure that'd be my pleasure. Welcome!

**Closed** 2024-03-25 01:13 UTC
Labels: good first issue, priority/P4, QA/No, release-notes/exclude, OS/Desktop
