### ISSUE TITLE
Restart browser reset the USD conversion value to zero

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7110] opened 2019-11-26 20:34 UTC
## Description 

Restart browser reset the USD conversion value to zero

## Steps to Reproduce

   1. Clean profile 2.0.0
   2. Enable rewards and fund the wallet
   3. Send a one-time tip to a verified pub
   4. Check one-time tip amount in rewards settings, summary and BR panel
   5. USD conversion value for 1 BAT is displayed as expected `0.20 USD`
   6. Click on the hamburger menu and exit the browser
   7. Relaunch the browser
   8. Click on BR panel and see USD conversion value reset to `0.00 USD`
   
   

## Actual result:

Restart browser reset the USD conversion value to zero
![image](https://user-images.githubusercontent.com/38657976/69670210-67853a00-10b9-11ea-84c8-554e828b99dc.png)

## Expected result:
Restart browser shouldn't reset the USD conversion value to zero

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave 2.0.0 Chromium 78.1.3.15
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @yrliou @SergeyZhukovsky

**Comment by yrliou** [comment] 2020-01-07 18:58
@GeetaSarvadnya I can't reproduce this using current master, it is probably already fixed, please help verify again in the next beta build, thanks!

**Comment by yrliou** [comment] 2020-01-07 19:05
Ah I didn't fund through uphold but claiming a grant in step 2, I'll try again.

**Comment by yrliou** [comment] 2020-01-08 00:53
Ok, I just try it again by funding through uphold in step2, cannot reproduce anymore on master.

**Comment by yrliou** [comment] 2020-01-08 01:24
Closing since I can't reproduce on master anymore, @GeetaSarvadnya please feel free to reopen this one if not, thanks.

**Closed by yrliou** 2020-01-08 01:24 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, android-core-release, feature/rewards

**Comment by srirambv** [comment] 2020-01-24 21:51
Verification passed on OnePlus 6T with Android 10 running 1.5.58 x64 build
- Verified steps from issue description and value didn't change
- Verified restarting via hamburger menu didn't reset USD to 0
- Verified removing app from memory and relaunching doesn't reset USD to 0
-------
Verification passed on Samsung Tab A with Android 9.0 running 1.5.58 x64 build
- Verified steps from issue description and value didn't change
- Verified restarting via hamburger menu didn't reset USD to 0
- Verified removing app from memory and relaunching doesn't reset USD to 0
-------
