### ISSUE TITLE
Self-custody invite is shown even when the rewards payment ID is not whitelisted

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#35664] opened 2024-01-29 15:30 UTC
## Description 

Solana self-custody invite is shown even when the rewards payment ID is not whitelisted
## Steps to Reproduce

   1. Clean profile 1.63.x
   2. Launch brave using staging env flags  `brave.exe --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=9,"*/brave_rewards/*"=9,"*/bat-native-ads/*"=9,"*/bat-native-confirmations/*"=9,"*/brave_ads/*"=9,"*/brave_user_model/*"=9 --rewards=staging=true,rewards=debug=true`
  3. Enable rewards for the region `US`
  4. Enable self-custody flag via brave://flags
  5. Create a Brave wallet
  6. Solana self-custody invite is shown on both BR panel and NTP even when the rewards payment ID is not whitelisted

## Actual result:

Solana self-custody invite is shown even when the rewards payment ID is not whitelisted

## Expected result:
Solana self-custody invite should be shown only when the rewards payment ID is whitelisted

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.63.134 Chromium: 121.0.6167.85 (Official Build) beta (64-bit)
-- | --
Revision | cdcba6ef408b305ce19b1a9b3fabbb5e9e3b36bf
OS | Windows 10 Version 22H2 (Build 19045.3930)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @Miyayes @zenparsing

**Comment by Miyayes** [comment] 2024-01-29 16:05
I believe this duplicate of https://github.com/brave/brave-browser/issues/35622?

**Comment by GeetaSarvadnya** [comment] 2024-01-29 16:06
yup, that's right. thanks for closing it @Miyayes

**Closed by Miyayes** 2024-01-29 16:05 UTC
Labels: feature/rewards, QA/Yes, QA/Test-Plan-Specified, OS/Desktop
