### ISSUE TITLE
Decouple creation of Ledger server URLs for different environments

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7824] opened 2020-01-20 12:06 UTC
i.e.

- Add a pure abstract class for ServerUrl
- Create concrete classes for each type of server URL
- Build a factory which makes a URL

**Comment by NejcZdovc** [comment] 2020-08-27 09:09
dupe of https://github.com/brave/brave-browser/issues/10987

**Closed by NejcZdovc** 2020-08-27 09:09 UTC
Labels: dev-concern, feature/rewards
