### ISSUE TITLE
Unable to delete/remove created wallet in Crypto wallets

### ISSUE THREAD

**Issue by Rishirandhawa** [brave/brave-browser#12053] opened 2020-10-08 15:55 UTC
## Description 
Cannot delete the account. No delete button visible

## Steps to Reproduce

   1. logged into Brave wallet
   2. went to settings -> contact
   3. Selected the account - got in to edit - no DELETE button visible

## Actual result:

![image](https://user-images.githubusercontent.com/18483046/95483326-9b3e1b00-097e-11eb-8be6-d1f0a8693579.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment] 2020-10-09 05:54
Dupe of #5741. This is mostly done and will probably be released sometime soon.

**Closed by srirambv** 2020-10-09 05:54 UTC
Labels: OS/Desktop, feature/crypto-wallets

**Comment by janwarming** [comment] 2020-12-09 20:40
From which build is this fixed?

**Comment by uxtops** [comment] 2021-01-03 07:46
Why is this closed??? I'm on Linux and Version: 1.18.77 Chromium: 87.0.4280.101 (Official Build) (64-Bit)
And it is **still** the same: - **no DELETE button visible**
What the f ?
