### ISSUE TITLE
BR panel shows wallet creation failed even when its enabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3646] opened 2019-03-10 12:17 UTC
## Description 

BR panel shows wallet creation failed even when its enabled

## Possible steps to reproduce (Not very sure)

   1. Upgrade to dev build 0.63.4
   2. Enable rewards
   3. Set browser to delete data on exit 
   4. Close the browser and leave it for a while and relaunch
   5. Rewards page shows rewards enabled, but when click on BR panel shows as `Wallet creation failed`
   6. Clicking on try again shows wallet summary on panel 

## Actual result:

![Capture](https://user-images.githubusercontent.com/17010094/54084850-6eda9c80-430c-11e9-8c84-a00ae5f897d4.PNG)

## Expected result:
Should not show any unnecessary error

## Reproduces how often: 

Easily reproduced but not really sure if the above steps is what is causing it. 

## Brave version (brave://version info)

Brave | 0.63.4 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 10 OS Build 17134.590

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on Dev builds
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A

**Comment by Liunkae** [comment] 2019-03-10 18:41
When you click Try Again, it resets all the Brave Rewards settings, which is kind of annoying.

**Comment by NejcZdovc** [comment] 2019-03-11 05:48
closing as dupe of https://github.com/brave/brave-browser/issues/3440

**Closed by NejcZdovc** 2019-03-11 05:48 UTC
Labels: QA/Yes, bug, feature/global-settings, feature/rewards, needs-investigation
