### ISSUE TITLE
Peertube playback (torrent issue)

### ISSUE THREAD

**Issue by ChameleonScales** [brave/brave-browser#3164] opened 2019-01-30 17:05 UTC
## Description 
When attempting to watch a video on any Peertube instance, I get this message:
"Sorry, but this video is not available because the remote instance is not responding. 
Please try again later."

## Example:
https://video.blender.org/videos/watch/f507dfdc-e73e-45a4-9778-d758cbe1ce96

## Brave version:
Brave: 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
Revision: 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS: Linux

### Reproducible on current release:
Yes:
Brave: 0.61.2 Chromium: 72.0.3626.71 (Official Build) dev(64-bit)
Revision: f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}
OS: Linux

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?
No
- Is the issue reproducible on the latest version of Chrome?
No

### Additional Information
Related issue: https://github.com/brave/browser-laptop/issues/10672

**Comment by blakeearth** [comment] 2019-03-15 18:15
This is currently an issue on Version 0.63.9 Chromium: 73.0.3683.75 (Official Build) dev (64-bit). I love Brave's philosophy, and I hope it will be increasingly useful in escaping centralized and privacy-unfriendly services like YouTube (in addition to making sites like YouTube safer and more private to use). I think this is an important issue for that reason, as PeerTube has different (and significantly less centralized) privacy concerns than YouTube and other popular streaming websites.

**Comment by blakeearth** [comment] 2019-04-04 22:08
For now, Brave users should be able to disable the WebTorrent extension as a workaround, and PeerTube should work as normal. Go to `brave://settings`, search for WebTorrent, and disable it. This is a problem with Brave's WebTorrent extension.

**Comment by pookito** [comment] 2019-06-10 07:37
> For now, Brave users should be able to disable the WebTorrent extension as a workaround, and PeerTube should work as normal. Go to `brave://settings`, search for WebTorrent, and disable it. This is a problem with Brave's WebTorrent extension.

Thanks for the advise.  I was having the same problem as you stated and solved it.  I just thought about dropping a line of thanks.  :+1:

**Comment by feross** [comment] 2019-07-23 23:56
Related: https://github.com/brave/brave-browser/issues/5361

**Comment by feross** [comment] 2019-07-26 23:46
Confirmed that this is the same issue as #5361 and it is fixed by this PR: https://github.com/brave/brave-core/pull/3035

**Closed** 2019-07-27 19:42 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/webtorrent, priority/P5, webcompat

**Comment by kjozwiak** [comment] 2019-09-18 06:04
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.126 Chromium: 77.0.3865.65 (Official Build) (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | macOS Version 10.14.6 (Build 18G95)

* ensured that the following videos which are hosted on a PeerTube instance work when `WebTorrent` is enabled & disabled
   * https://video.blender.org/videos/watch/f507dfdc-e73e-45a4-9778-d758cbe1ce96
   * https://video.blender.org/videos/watch/3d95fb3d-c866-42c8-9db1-fe82f48ccb95
   * https://framatube.org/videos/watch/9c9de5e8-0a1e-484a-b099-e80766180a6d

**Comment by kjozwiak** [comment] 2019-09-18 06:05
@feross please let me know if the above test cases are sufficient enough for verification ☝️

**Comment by feross** [comment] 2019-09-18 06:47
@kjozwiak That should be sufficient validation!

**Comment by pookito** [comment] 2019-10-18 22:52
Thank you, it works for me.
