### ISSUE TITLE
gHacks.net Report Incorrect Fonts

### ISSUE THREAD

**Issue by Nihal247** [brave/brave-browser#23391] opened 2022-06-10 08:50 UTC
## Description 
ghacks.net report incorrect fonts. I wonder if this is due to Brave's Language Fingerprinting Protection. Disabling shields load up the correct fonts on the site.

## Steps to Reproduce

   1.  Browse to ghacks.net
   2.  Notice the fonts on the site.
   3. Disable shields, and the correct fonts load up.

## Actual result:
![ss 1](https://user-images.githubusercontent.com/80682093/173027915-c5e6bc00-f84a-4dc0-bda4-5d3f8dc1826e.png)

## Expected result:
![ss 2](https://user-images.githubusercontent.com/80682093/173027946-5e643789-b654-4be6-95c9-48b9069c049d.png)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
v1.39.120

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No

## Miscellaneous Information:
OS: Windows 11 (22000.708)

**Comment by rebron** [comment] 2022-06-10 21:26
cc: @pilgrim-brave

**Comment by Nihal247** [comment] 2022-06-13 04:10
Visiting the site now, this problem no longer persists and the correct fonts are shown. I guess the devs have resolved the issue.

Cheers!

**Comment by Nihal247** [comment] 2022-06-13 12:50
Just 9 hours after closing this issue, I see the problem again, tested with both an old and a new profile.

**Comment by holdit** [comment] 2022-06-15 05:06
It's the same problem as #23093 .

Until they fix this, disable the "Prevent sites from fingerprinting me based on my language preferences" option in Shields and restart the browser.

**Comment by bsclifton** [comment] 2022-06-15 06:15
Closing as duplicate of https://github.com/brave/brave-browser/issues/23093

**Closed by bsclifton** 2022-06-15 06:15 UTC
Labels: OS/Desktop
