### ISSUE TITLE
Context menu doesn't always open for current/active tab in vertical tabs minimized mode

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#29836] opened 2023-04-18 21:34 UTC
## Description 

Found while testing https://github.com/brave/brave-browser/issues/29692.   In vertical tab view and if minimized mode is selected, and when right clicked on the active tab to open context menu, it doesn't open always.  It appears it opens only when I clicked bottom right corner of the tab.  This issue was not reproducible in 1.52.51 Nightly and the context menu working as expected.

## Steps to Reproduce

   1. Install 1.51.95 
   2. launch Brave
   3. open brave://flags and enable #brave-vertical-tabs
   4. visit newyorker.com and open context menu and enable `Use vertical tabs`
   5. open few more tabs and toggle `Expand/Minimize` button to view `Minimize` tab view
   6. right click on an active tab
 

## Actual result:

Context menu doesn't open always.  Had to click bottom right to open the menu

https://user-images.githubusercontent.com/98358127/232910207-24ec8fb0-a019-4367-b0d4-69bda27de2eb.mp4

## Expected result:
Context menu should open as in inactive tabs 

## Reproduces how often: 

Easy 

## Version/Channel Information:

- Can you reproduce this issue with the current release?  N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @sangwoo108 
cc: @brave/qa-team

**Comment by stephendonner** [comment] 2023-04-18 23:38
FWIW, I've seen this on both `beta` and `nightly` on `macOS`, too.

**Comment by sangwoo108** [comment] 2023-04-19 00:47
Could you check if this happens with this patch too? https://github.com/brave/brave-core/pull/18092

It looks like the close button is consuming the event. I made the close button have smaller size, so it might be fixed with that. 

If the context menu doesn't show up even there's no highlight circle around the close button, we can say that it's not fixed.

**Comment by MadhaviSeelam** [comment] 2023-04-19 17:30
> Could you check if this happens with this patch too? https://github.com/brave/brave-core/pull/18092
> 
> It looks like the close button is consuming the event. I made the close button have smaller size, so it might be fixed with that.
> 
> If the context menu doesn't show up even there's no highlight circle around the close button, we can say that it's not fixed.

@sangwoo108 tested the patch in 1.52.57.  The fix seem to be working as Context menu opens when clicked in minimized mode. However, when clicked at the bottom middle below `x`.  Expected?

https://user-images.githubusercontent.com/98358127/233153256-5893ccf1-b4b4-4c69-9993-e197ddc234bb.mp4

**Comment by sangwoo108** [comment] 2023-04-20 00:16
Yes, that looks like what expected. As long as you can see the shadow circle around the 'x' button, the context menu won't show up. This is the same behavior with the horizontal tab strip.

**Comment by sangwoo108** [comment] 2024-03-23 00:51
Let me close issue as it's expected behavior. If we want to update the behavior by overriding the upstream's implementation, please feel free to reopen this.

**Closed by sangwoo108** 2024-03-23 00:51 UTC
Labels: bug, QA/Test-Plan-Specified, OS/Desktop, feature/vertical-tabs
