### ISSUE TITLE
Brave Rewards NTP widget showing the wrong state

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#8711] opened 2020-03-16 20:05 UTC
## Description 

I found an intermittent bug on NTP; occasionally the Brave Rewards widget shows opt-in state with incorrect color and "Try again" instead of "Turn on Rewards" on button text. My browser profile is already opted into Rewards though so this state shouldn't even be showing. Sometimes this bug is accompanied with the Shields and Rewards icon not showing in the address bar as well. 
My Rewards settings page seems normal, and the bug seems to disappear when I open another tab. The bug keeps showing up again after a period of time though.

## Steps to Reproduce

I'm unclear how to reproduce this.
   1. Open a new tab 
   2. Sometimes the bug is there, sometimes it's not.
 

## Actual result:

![Screen Shot 2020-03-13 at 12 37 32 PM](https://user-images.githubusercontent.com/2388823/76795462-7dad2800-6786-11ea-83df-e65432cb8a0d.png)

## Expected result:
It should show the already opted-in state: 
![Screen Shot 2020-03-16 at 1 03 26 PM](https://user-images.githubusercontent.com/2388823/76795492-94537f00-6786-11ea-8547-300087d0702d.png)

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)

Version 1.8.9 Chromium: 80.0.3987.132 (Official Build) nightly (64-bit)

## Version/Channel Information:

Nightly

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? Unsure; the bug would be hidden but probably not solved
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by rebron** [comment] 2020-03-16 20:20
dupe of #8698

**Closed by rebron** 2020-03-16 20:20 UTC
Labels: feature/rewards
