### ISSUE TITLE
Feature Request : Automatic Translation by Brave into English without using Google Translate Extension

### ISSUE THREAD

**Issue by gssakash** [brave/brave-browser#23799] opened 2022-06-30 17:14 UTC
### Issue
Auto translation of Websites on a visit with maybe a warning asking the user if he's okay with it.

### Proposal
The auto translation is a must-have for the Brave Browser IMO. I'm not sure how technically challenging it would be to implement this feature is but It would be really helpful if Brave had translation from foreign languages to the default brave browser language set by the user and it would definitely help it stand out from the competition as well [although it is holding its own really well]. And a native browser experience is always better than using the recommended translation extension especially since it does not translate every single page of the article/source and requires the user to keep activating it once the page changes.

**Comment by rebron** [comment] 2022-06-30 23:49
Closing as dupe of https://github.com/brave/brave-browser/issues/23813
@gssakash Brave translation service is on its way.

**Closed by rebron** 2022-06-30 23:49 UTC
Labels: OS/Desktop
