### ISSUE TITLE
"privacy invasive actions" should be "privacy-invasive actions" in malicious-site warning

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#14768] opened 2021-03-16 21:13 UTC
## Description 
"privacy invasive actions" should be "privacy-invasive actions" in malicious-site warning

## Steps to Reproduce

   1.  in `nightly`, load `http://1-1ads.com/` (or any from `https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext`)
   2. look at the warning text

## Actual result:
"...privacy invasive actions."

<img width="1175" alt="Screen Shot 2021-03-16 at 2 09 01 PM" src="https://user-images.githubusercontent.com/387249/111380266-56bb5780-8661-11eb-8846-4bcd13c3b747.png">

## Expected result:
Should read "...privacy-invasive actions." The text snippet is a compound modifier.

See below for an example from our official site copy.

<img width="1175" alt="Screen Shot 2021-03-16 at 2 11 03 PM" src="https://user-images.githubusercontent.com/387249/111380383-84080580-8661-11eb-9c65-a3464503755f.png">

## Brave version (brave://version info)

Brave | 1.23.41 Chromium: 89.0.4389.90 (Official Build) nightly (x86_64)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | macOS Version 11.2.3 (Build 20D91)

**Comment by Ayushsunny** [comment] 2021-04-15 14:29
Hello @srirambv Can I work on this issue?

**Comment by srirambv** [comment] 2021-04-15 14:31
Assigned the issue to you @Ayushsunny . Please use the PR template when creating the pull request.

**Comment by Ayushsunny** [comment] 2021-04-15 14:34
> Assigned the issue to you @Ayushsunny . Please use the PR template when creating the pull request.

Thank you so much sir for helping me in the last PR and also in this one for assigning me.
but for this issue, I need more clarification like what exactly I have to do as I am new to open source so please help me sir

**Comment by jcsavage2** [comment] 2021-04-16 01:00
Hello! I am also curious about investigating this issue, but I am not able to replicate this error locally. Right now I am running npm start Component, which starts Brave Browser Development. When I try the URLs listed above I only get "site cannot be reached" error. I am not sure if this is because I am not running the correct version of Brave? The steps to reproduce lists that I need to run "nightly". Is this different than the current version I am running? Do you have any developer resources I could reference so that I can load the nightly version and reproduce this error locally? Thank you!

**Comment by Ayushsunny** [comment] 2021-04-23 10:20
Hello Sir @srirambv I am not able to find out the location of this code. can you help me please,

**Comment by srirambv** [comment] 2021-04-23 11:57
Looks like there is already a PR up for it https://github.com/brave/brave-core/pull/8427. 

cc: @mkarolin

**Comment by Ayushsunny** [comment] 2021-04-23 12:02
> Looks like there is already a PR up for it [brave/brave-core#8427](https://github.com/brave/brave-core/pull/8427).
> 
> cc: @mkarolin

Sir but there is a conflict on that this commit https://github.com/brave/brave-core/pull/8427/files#diff-6314ab9f5910c0e3dd53f8ac6bf09b584020abe6790abe7ebcdacc5756c5d5f9

that is already solved by me and got merged https://github.com/brave/brave-core/pull/8535#event-4599564322

**Comment by srirambv** [comment] 2021-04-23 12:13
Probably needs a rebase to fix it. cc: @AdamTranquilla 

Will leave @mkarolin to check the PR. @Ayushsunny you can check for other issues to contribute as the PR has been open for 20 days

**Comment by soham4abc** [comment] 2021-07-02 07:08
I can work on this issue. If possible pls assign @srirambv

**Closed** 2021-07-12 16:39 UTC
Labels: OS/Desktop, good first issue, priority/P5

**Comment by stephendonner** [comment] 2021-07-23 17:26
On desktop, the text for this specific case has changed, so can't be verified there, due to https://github.com/brave/brave-core/commit/f6335b3bb358ec5dae51ca37b0a789b947437ec4.

Removing `OS/Desktop` and adding `OS/Android`; what should be verified is the in-product UI on Android corresponding to the commit here: https://github.com/brave/brave-core/pull/9312/files.

**Comment by srirambv** [comment] 2021-08-03 14:07
Marking the issue as QA/No as this interstitial page is changed as part of #15189 & #15433. Here is what the new page looks like on Android similar to desktop(#15433)

Dark | Light
-- | --
![image](https://user-images.githubusercontent.com/17010094/128029267-bdc9dbda-1345-41c6-a464-83b18856c22b.png) | ![image](https://user-images.githubusercontent.com/17010094/128029174-a0791258-e11c-4451-aac2-fc2e72646eb6.png)
