### ISSUE TITLE
Crash Report - crash when custom ad was trying to show itself

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#13758] opened 2021-01-25 23:31 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.21.25  Chromium: 88.0.4324.96
Operating System: Windows NT 10.0.19042

URL (if applicable) where crash occurred:
Bouncing between tabs with various websites and then the settings page (trying to open search engine list)

Can you reproduce this crash?
I've had a similar crash before - not sure if this is the same (duplicate)

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
Unknown. I'm not sure the last time I saw an ad

Best attempt at documenting steps:
1. Visit several websites (have open tabs)
2. Open settings page (via Hamburger menu)
3. Hit a condition where Ad tries to show itself while on a settings (internal) page

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/161f0100-604d-b505-0000-000000000000

**Comment by kjozwiak** [comment] 2021-01-26 00:13
Hmmm tried a few times with my personal profile using the STR/Cases via https://github.com/brave/brave-browser/issues/13758#issue-793802278 with the following build but couldn't reproduce the crash:
```

Brave | 1.21.25 Chromium: 88.0.4324.96 (Official Build) nightly (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2009 (Build 19042.746)
```

I also tried the above with a new profile several times but couldn't reproduce either. @bsclifton maybe there's an entry in `brave://settings/searchEngines` that's causing the browser to crash? Maybe something added via Open Search?

**Comment by bsclifton** [comment] 2021-01-26 00:28
Thanks @kjozwiak - I dug into crash report and I guess I got really unlucky 😛 The steps I followed ending up not mattering - the crash was due to custom ad notification. Will update ticket!

cc: @tmancey 

```
[ 00 ] brave_ads::MessagePopupView::ClosePopup(bool)
[ 01 ] RtlUnwindEx
[ 02 ] brave_ads::AdsServiceImpl::CloseNotification(std::__1::basic_string<char,std::__1::char_traits<char>,std::__1::allocator<char> > const &)
[ 03 ] base::OneShotTimer::FireNow()
[ 04 ] RtlUnwindEx
[ 05 ] base::internal::BaseTimerTaskInternal::Run()
[ 06 ] base::ThreadLocalStorage::Slot::Get()
[ 07 ] RtlUnwindEx
[ 08 ] base::TaskAnnotator::RunTask(char const *,base::PendingTask *)
[ 09 ] brave_ads::AdsServiceImpl::StartNotificationTimeoutTimer(std::__1::basic_string<char,std::__1::char_traits<char>,std::__1::allocator<char> > const &)
[ 10 ] mojo::Connector::PostDispatchNextMessageFromPipe()
[ 11 ] mojo::SimpleWatcher::Context::Notify(unsigned int,MojoHandleSignalsState,unsigned int)
[ 12 ] RtlUnwindEx
[ 13 ] brave_ads::AdsServiceImpl::StartNotificationTimeoutTimer(std::__1::basic_string<char,std::__1::char_traits<char>,std::__1::allocator<char> > const &)
[ 14 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow *)
[ 15 ] base::MessagePumpForUI::ProcessMessageHelper(tagMSG const &)
[ 16 ] 0x7ffe85fd1280
[ 17 ] 0x7ffe85fd1280
[ 18 ] NtdllDispatchMessage_A
[ 19 ] _PeekMessage
[ 20 ] PeekMessageW
[ 21 ] base::MessagePumpForUI::ProcessNextWindowsMessage()
[ 22 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
[ 23 ] RtlUnwindEx
[ 24 ] RtlUnwindEx
[ 25 ] base::MessagePumpForUI::DoRunLoop()
[ 26 ] base::sequence_manager::internal::ThreadController::RunLevelTracker::RunLevel::UpdateState(base::sequence_manager::internal::ThreadController::RunLevelTracker::State)
[ 27 ] base::TimeTicks::Now()
[ 28 ] base::MessagePumpWin::Run(base::MessagePump::Delegate *)
[ 29 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool,base::TimeDelta)
[ 30 ] base::internal::WeakPtrFactoryBase::WeakPtrFactoryBase(unsigned __int64)
[ 31 ] base::ThreadLocalStorage::Slot::Get()
[ 32 ] base::RunLoop::Run()
[ 33 ] RtlUnwindEx
[ 34 ] RtlUnwindEx
[ 35 ] performance_monitor::ProcessMonitor::StartGatherCycle()
[ 36 ] ChromeBrowserMainParts::MainMessageLoopRun(int *)
[ 37 ] content::BrowserMainRunnerImpl::Initialize(content::MainFunctionParams const &)
[ 38 ] content::BrowserMainLoop::RunMainMessageLoopParts()
[ 39 ] content::BrowserMainRunnerImpl::Run()
[ 40 ] content::BrowserMain(content::MainFunctionParams const &)
[ 41 ] RtlUnwindEx
[ 42 ] malloc_base
[ 43 ] ChromeMainDelegate::RunProcess(std::__1::basic_string<char,std::__1::char_traits<char>,std::__1::allocator<char> > const &,content::MainFunctionParams const &)
[ 44 ] content::RunBrowserProcessMain(content::MainFunctionParams const &,content::ContentMainDelegate *)
[ 45 ] content::ContentMainRunnerImpl::RunServiceManager(content::MainFunctionParams &,bool)
[ 46 ] base::WideToUTF8(base::BasicStringPiece<std::__1::basic_string<wchar_t,std::__1::char_traits<wchar_t>,std::__1::allocator<wchar_t> > >)
[ 47 ] base::CommandLine::GetSwitchValueASCII(base::BasicStringPiece<std::__1::basic_string<char,std::__1::char_traits<char>,std::__1::allocator<char> > > const &)
[ 48 ] RtlUnwindEx
[ 49 ] content::ContentMainRunnerImpl::Run(bool)
[ 50 ] base::CommandLine::GetSwitchValueASCII(base::BasicStringPiece<std::__1::basic_string<char,std::__1::char_traits<char>,std::__1::allocator<char> > > const &)
[ 51 ] content::RunContentProcess(content::ContentMainParams const &,content::ContentMainRunner *)
[ 52 ] RtlpAllocateHeapInternal
```

**Comment by kjozwiak** [comment] 2021-01-26 01:06
awesome, thanks @bsclifton 👍

**Comment by tmancey** [comment] 2021-01-26 08:12
Closing issue as a duplicate of https://github.com/brave/brave-browser/issues/13139

**Closed by tmancey** 2021-01-26 08:12 UTC
Labels: bug, crash, feature/ads
