### ISSUE TITLE
Toolbar icons appear jumbo on Ubuntu and Windows

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#270] opened 2018-06-04 22:06 UTC
DPI setting is 250%
Resolution: 4858 x 1536
<img width="987" alt="screen shot 2018-06-04 at 6 05 03 pm" src="https://user-images.githubusercontent.com/831718/40944184-d5a0458a-6821-11e8-8251-2409d081eba2.png">

Compare to macOS:
<img width="1201" alt="screen shot 2018-06-04 at 6 05 51 pm" src="https://user-images.githubusercontent.com/831718/40944218-f5b6e522-6821-11e8-88c1-a1e05fa5861e.png">

**Comment by srirambv** [comment] 2018-06-08 02:45
On hover shows a weird hover effect on giant buttons

![buttonhover](https://user-images.githubusercontent.com/17010094/41136476-741ccc36-6aa4-11e8-96ea-8023e4ffd1af.gif)

**Comment by AlexeyBarabash** [comment] 2018-06-24 18:40
Issue has been happened because this Chromium commit 
https://chromium.googlesource.com/chromium/src.git/+/877c14658b8234f20d24545d7684191b3de9b387 had not been synced with brave-core vector icons. `1x` files had been merged into main vector_icons and no longer used in a separate way, so small icons are ignored now. Happened since moving to Chromium 67.

**Closed** 2018-07-06 20:24 UTC
Labels: misc/icons

**Comment by bbondy** [comment] 2018-07-07 00:52
👍

**Comment by srirambv** [comment] 2018-09-21 18:53
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

**Comment by Martina-Neumayer** [comment] 2020-06-13 15:59
Seems that the issue is back.
Updated today my Brave from  1.10.85-1 to 1.11.61 and the icons, toolbars, well.. the whole UI is much bigger than it was before the update.

Looks like this issue also affects scaling (ctrl + / ctrl-) function.
Webpages are not scaled corrctly and on some random pages by scaling the page elements are not aligned at all. I mean they does not fit to the scaling factor.
This occurs even on the "new tab" page.

System : Arch x64
Browser: Version 1.11.61 Chromium: 83.0.4103.97 (Official Build) unknown (64-bit)
Machine: Lenovo Legion Y530-15ICH (81LB00BTPB)
