### ISSUE TITLE
Brave Appearance Setting Missing

### ISSUE THREAD

**Issue by baranwalabhinav** [brave/brave-browser#19633] opened 2021-11-21 07:50 UTC
## Description 
The “Appearance” tab under “Settings” is missing in the Brave Browser for Windows. The Settings page lists - Get Started, Appearance, New Tab page and gives settings options for Get Started and New Tab page but nothing for Appearance. Clicking on the appearance tab does nothing too.

## Steps to Reproduce
   1. Go to Settings.
   2.  Click Appearance on the left side list of options.

## Actual result:
![image](https://user-images.githubusercontent.com/89128577/142754097-e2068972-8c3d-4810-a09f-614570429097.png)

## Expected result:
There should be settings for Appearance after Get Started.

## Reproduces how often: 
All the time. Easily reproduced.

## Brave version (brave://version info)
1.32.106

**Comment by rebron** [comment] 2021-11-22 18:41
cc: @GeetaSarvadnya

**Comment by GeetaSarvadnya** [comment] 2021-11-23 11:01
@baranwalabhinav : Issue isn't reproducible for me on both clean and upgrade profile in Windows 10 x64. Can you reproduce the issue consistently ?
![appearance settings](https://user-images.githubusercontent.com/38657976/143012760-f73a778c-4fb2-4462-af5e-45f830f920a3.gif)

**Comment by baranwalabhinav** [comment] 2021-11-23 11:21
Yes. This entire "Appearance" set of settings is missing from my settings. As visible in the screenshot posted below, the tab for "Appearance" gives 0 settings options. This issue exists even after trying to access it with a new profile.

P.S. - "Hardware Acceleration" is disabled and all extensions have been disabled too.

![image](https://user-images.githubusercontent.com/89128577/143015416-78766cd1-2772-4f50-9f83-f988007b2623.png)

**Comment by rebron** [comment] 2021-11-23 18:42
@baranwalabhinav What version of Windows are you running?

**Comment by baranwalabhinav** [comment] 2021-11-23 18:44
@rebron Windows 10. i3-4th Gen. 4GB RAM. More than 100GB of hard disk space exists. Nvidia GeForce 820M.

**Comment by baranwalabhinav** [comment] 2021-11-23 18:53
@rebron @GeetaSarvadnya 
Don't know if this is of any help but do take a look.
![image](https://user-images.githubusercontent.com/89128577/143086147-d8d47e41-5f1d-4c72-bad5-53e0f8dc6cf7.png)

**Comment by simonhong** [comment] 2021-11-26 04:27
@baranwalabhinav Do you have any changes from brave://flags?
I can reprothis  if `New Tab Page Branded Wallpapers` is disabled from brave://flags.

**Comment by baranwalabhinav** [comment] 2021-11-26 11:33
@simonhong Great work! The "New Tab Page Branded Wallpapers" flag was disabled! setting it to default has done the trick! Awesome!!! Thanks!

**Comment by simonhong** [comment] 2021-11-26 11:50
@baranwalabhinav Nice to find the root cause. Thanks for reporting!
If my fix is merged into current nightly, it will be arrived to you when 1.34 becomes stable. (current stable is 1.32)

**Comment by baranwalabhinav** [comment] 2021-11-27 04:18
@simonhong Great! looking to find further bugs to report!

**Closed** 2021-12-06 07:19 UTC
Labels: priority/P3, QA/Yes, release-notes/exclude, feature/settings, OS/Desktop

**Comment by stephendonner** [comment] 2021-12-24 20:35
Verified `PASSED` using

Brave | 1.35.56 Chromium: 97.0.4692.56 (Official Build) nightly (64-bit)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Windows 10 Version 20H2 (Build 19042.1415)

Followed steps from https://github.com/brave/brave-core/pull/11299 and confirmed that the `brave://settings/appearance` window is correct and works, even when `New Tab Page Branded Wallpapers` was set to `Disabled` in `brave://flags`.

example | example
----------|----------
![19633-1](https://user-images.githubusercontent.com/387249/147371670-545c7510-8421-4974-98da-c9ed211db4a0.png) | ![19633-2](https://user-images.githubusercontent.com/387249/147371675-a362ec37-0e6d-4eef-9664-c11ea3f19453.png)
