### ISSUE TITLE
New Tab page Crashes if Brave News is disabled

### ISSUE THREAD

**Issue by RuthlessRuler** [brave/brave-browser#27184] opened 2022-12-06 17:29 UTC
## Description 

I have set "Enable Brave News" to be disabled, upon relaunch the New Tab page seems to throw Aww Snap error.
Upon setting the flag to default the New Tab page displays as expected.

## Steps to Reproduce

   1. Goto Brave://flags
   2. Search for Enable Brave News
   3. Set it to be disabled
   4. Relaunch the browser and open new tab

## Actual result:

We get Aw, Snap!
Error Code: RESULT_CODE_KILLED_BAD_MESSAGE

## Expected result:
New tab page loads fine

## Reproduces how often: 

Easily Reproduced

## Brave version (brave://version info)

1.46.134 Chromium: 108.0.5359.94 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment] 2023-01-18 16:45
Closing as dupe of https://github.com/brave/brave-browser/issues/26876, fixed in 1.46.141
@RuthlessRuler please reopen if you're still experiencing a crash.

**Closed by rebron** 2023-01-18 16:45 UTC
Labels: OS/Desktop

**Comment by RuthlessRuler** [comment] 2023-01-22 12:14
Hey @rebron , 

I just checked with brave 1.47.171 on W10, and this issues still exists.

**Comment by brokoler** [comment] 2023-03-04 13:45
I can confirm that the issue still exists with 1.48.171 on Windows 10.
Please re-open this issue.

**Comment by brokoler** [comment] 2023-03-04 13:56
I can confirm that the issue still exists with 1.48.171 on Windows 10.

@rebron 
Could you please re-open this issue?

**Comment by brokoler** [comment] 2023-03-05 11:11
@RuthlessRuler 
Since rebron didn't reply for a while and asked you initially to re-open this case if not fixed, I created a new issue mainly based on your input: https://github.com/brave/brave-browser/issues/27184

Hope this is fine for you, regards.

**Comment by RuthlessRuler** [comment] 2023-03-05 11:59
> @RuthlessRuler Since rebron didn't reply for a while and asked you initially to re-open this case if not fixed, I created a new issue mainly based on your input: #28901
> 
> Hope this is fine for you, regards.

Thanks a lot for the efforts.
