### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Steven-W-Clark** [brave/brave-browser#39077] opened 2024-06-15 11:54 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.67.116 Chromium: 126.0.6478.71
Operating System: Windows NT 10.0.19045

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Every time I click on the cast button to send YouTube to the YouTube app on my Virgin Media (UK Cable TV provider) box Brave crashes. It has only started doing this in the last two days.
2. Not sure if it is anything to do with it but on Thursday windows 10 downloaded and installed the June 11, 2024—KB5039211 update
3. I also have a Hisense smart TV with the YouTube app and I am able to cast to this device with no issues
4. I have removed and reattached my YouTube account from this device but it still crashes

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/e82f0c00-37ee-1f0c-0000-000000000000

**Comment by Domsed** [comment] 2024-06-15 19:07
I have a same problem when i try cast Twitch or Youtube sound to Google Nest it crash Brave. It starts after the last update.

**Comment by iefremov** [comment] 2024-06-17 10:52
@Domsed can you please upload crash dumps from brave://crashes? @Steven-W-Clark can you also upload more dumps?

**Comment by iefremov** [comment] 2024-06-17 10:52
the uploaded stack is a diagnostic one, not really a crash
```
[ 00 ] crash_reporter::DumpWithoutCrashing() ( crashpad.cc:270 )
[ 01 ] base::debug::DumpWithoutCrashing(base::Location const&, base::TimeDelta) ( dump_without_crashing.cc:94 )
[ 02 ] brave_ads::database::table::(anonymous namespace)::GetCallback(base::OnceCallback<void (bool, std::__Cr::vector<brave_ads::TransactionInfo, std::__Cr::allocator<brave_ads::TransactionInfo>> const&)>, mojo::StructPtr<brave_ads::mojom::DBCommandResponseInfo>) ( transactions_database_table.cc:135 )
[ 03 ] void base::internal::DecayedFunctorTraits<void (*)(base::OnceCallback<void (brave_rewards::mojom::Result)>, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>), base::OnceCallback<void (brave_rewards::mojom::Result)>&&>::Invoke<void (*)(base::OnceCallback<void (brave_rewards::mojom::Result)>, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>), base::OnceCallback<void (brave_rewards::mojom::Result)>, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>>(void (*&&)(base::OnceCallback<void (brave_rewards::mojom::Result)>, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>), base::OnceCallback<void (brave_rewards::mojom::Result)>&&, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>&&) ( bind_internal.h:671 )
[ 04 ] void base::internal::InvokeHelper<false, base::internal::FunctorTraits<void (*&&)(base::OnceCallback<void (brave_rewards::mojom::Result)>, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>), base::OnceCallback<void (brave_rewards::mojom::Result)>&&>, void, 0ul>::MakeItSo<void (*)(base::OnceCallback<void (brave_rewards::mojom::Result)>, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>), std::__Cr::tuple<base::OnceCallback<void (brave_rewards::mojom::Result)>>, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>>(void (*&&)(base::OnceCallback<void (brave_rewards::mojom::Result)>, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>), std::__Cr::tuple<base::OnceCallback<void (brave_rewards::mojom::Result)>>&&, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>&&) ( bind_internal.h:930 )
[ 05 ] void base::internal::Invoker<base::internal::FunctorTraits<void (*&&)(base::OnceCallback<void (brave_rewards::mojom::Result)>, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>), base::OnceCallback<void (brave_rewards::mojom::Result)>&&>, base::internal::BindState<false, true, false, void (*)(base::OnceCallback<void (brave_rewards::mojom::Result)>, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>), base::OnceCallback<void (brave_rewards::mojom::Result)>>, void (mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>)>::RunImpl<void (*)(base::OnceCallback<void (brave_rewards::mojom::Result)>, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>), std::__Cr::tuple<base::OnceCallback<void (brave_rewards::mojom::Result)>>, 0ul>(void (*&&)(base::OnceCallback<void (brave_rewards::mojom::Result)>, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>), std::__Cr::tuple<base::OnceCallback<void (brave_rewards::mojom::Result)>>&&, std::__Cr::integer_sequence<unsigned long, 0ul>, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>&&) ( bind_internal.h:1067 )
[ 06 ] base::internal::Invoker<base::internal::FunctorTraits<void (*&&)(base::OnceCallback<void (brave_rewards::mojom::Result)>, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>), base::OnceCallback<void (brave_rewards::mojom::Result)>&&>, base::internal::BindState<false, true, false, void (*)(base::OnceCallback<void (brave_rewards::mojom::Result)>, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>), base::OnceCallback<void (brave_rewards::mojom::Result)>>, void (mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>)>::RunOnce(base::internal::BindStateBase*, mojo::StructPtr<brave_rewards::mojom::DBCommandResponse>&&) ( bind_internal.h:980 )
[ 07 ] base::OnceCallback<void (mojo::StructPtr<brave_ads::mojom::DBCommandResponseInfo>)>::Run(mojo::StructPtr<brave_ads::mojom::DBCommandResponseInfo>) && ( callback.h:156 )
[ 08 ] bat_ads::mojom::BatAdsClient_RunDBTransaction_ForwardToCallback::Accept(mojo::Message*) ( bat_ads.mojom.cc:7613 )
[ 09 ] mojo::InterfaceEndpointClient::HandleValidatedMessage(mojo::Message*) ( interface_endpoint_client.cc:1031 )
[ 10 ] mojo::InterfaceEndpointClient::HandleIncomingMessageThunk::Accept(mojo::Message*) ( interface_endpoint_client.cc:368 )
[ 11 ] mojo::MessageDispatcher::Accept(mojo::Message*) ( message_dispatcher.cc:43 )
[ 12 ] mojo::InterfaceEndpointClient::HandleIncomingMessage(mojo::Message*) ( interface_endpoint_client.cc:721 )
[ 13 ] mojo::internal::MultiplexRouter::ProcessIncomingMessage(mojo::internal::MultiplexRouter::MessageWrapper*, mojo::internal::MultiplexRouter::ClientCallBehavior, base::SequencedTaskRunner*) ( multiplex_router.cc:1120 )
[ 14 ] mojo::internal::MultiplexRouter::Accept(mojo::Message*) ( multiplex_router.cc:733 )
[ 15 ] mojo::MessageDispatcher::Accept(mojo::Message*) ( message_dispatcher.cc:43 )
[ 16 ] void base::internal::DecayedFunctorTraits<void (mojo::Connector::*)(char const*, unsigned int), mojo::Connector*, char const* const&>::Invoke<void (mojo::Connector::*)(char const*, unsigned int), mojo::Connector*, char const*, unsigned int>(void (mojo::Connector::*)(char const*, unsigned int), mojo::Connector*&&, char const*&&, unsigned int&&) ( connector.cc:554 )
[ 17 ] void base::internal::InvokeHelper<false, base::internal::FunctorTraits<void (mojo::Connector::* const&)(char const*, unsigned int), mojo::Connector*, char const* const&>, void, 0ul, 1ul>::MakeItSo<void (mojo::Connector::* const&)(char const*, unsigned int), std::__Cr::tuple<base::internal::UnretainedWrapper<mojo::Connector, base::unretained_traits::MayNotDangle, (partition_alloc::internal::RawPtrTraits)0>, base::internal::UnretainedWrapper<char const, base::unretained_traits::MayNotDangle, (partition_alloc::internal::RawPtrTraits)0>> const&, unsigned int>(void (mojo::Connector::* const&)(char const*, unsigned int), std::__Cr::tuple<base::internal::UnretainedWrapper<mojo::Connector, base::unretained_traits::MayNotDangle, (partition_alloc::internal::RawPtrTraits)0>, base::internal::UnretainedWrapper<char const, base::unretained_traits::MayNotDangle, (partition_alloc::internal::RawPtrTraits)0>> const&, unsigned int&&) ( bind_internal.h:930 )
[ 18 ] void base::internal::Invoker<base::internal::FunctorTraits<void (mojo::Connector::* const&)(char const*, unsigned int), mojo::Connector*, char const* const&>, base::internal::BindState<true, true, false, void (mojo::Connector::*)(char const*, unsigned int), base::internal::UnretainedWrapper<mojo::Connector, base::unretained_traits::MayNotDangle, (partition_alloc::internal::RawPtrTraits)0>, base::internal::UnretainedWrapper<char const, base::unretained_traits::MayNotDangle, (partition_alloc::internal::RawPtrTraits)0>>, void (unsigned int)>::RunImpl<void (mojo::Connector::* const&)(char const*, unsigned int), std::__Cr::tuple<base::internal::UnretainedWrapper<mojo::Connector, base::unretained_traits::MayNotDangle, (partition_alloc::internal::RawPtrTraits)0>, base::internal::UnretainedWrapper<char const, base::unretained_traits::MayNotDangle, (partition_alloc::internal::RawPtrTraits)0>> const&, 0ul, 1ul>(void (mojo::Connector::* const&)(char const*, unsigned int), std::__Cr::tuple<base::internal::UnretainedWrapper<mojo::Connector, base::unretained_traits::MayNotDangle, (partition_alloc::internal::RawPtrTraits)0>, base::internal::UnretainedWrapper<char const, base::unretained_traits::MayNotDangle, (partition_alloc::internal::RawPtrTraits)0>> const&, std::__Cr::integer_sequence<unsigned long, 0ul, 1ul>, unsigned int&&) ( bind_internal.h:1067 )

```

**Comment by iefremov** [comment] 2024-06-17 11:49
probably a dupe of https://github.com/brave/brave-browser/issues/39081

**Comment by iefremov** [comment] 2024-06-17 15:08
closing as a duplicate

**Closed by iefremov** 2024-06-17 15:08 UTC
Labels: crash, needs-more-info

**Comment by Domsed** [comment] 2024-06-17 16:35
> @Domsed can you please upload crash dumps from brave://crashes? @Steven-W-Clark can you also upload more dumps?

I try to uploud it: b055ca58-04b7-40c5-9629-5c1235e6eda0
