### ISSUE TITLE
Brave Nightly requests Bluetooth access, even though we disable WebBluetooth

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#16198] opened 2021-06-02 15:50 UTC
I received the below prompt when starting `1.27.24 Chromium: 91.0.4472.77 (Official Build) nightly (x86_64)`.
<img width="262" alt="Screen Shot 2021-06-02 at 9 26 03 AM" src="https://user-images.githubusercontent.com/76526/120511508-1762f400-c390-11eb-9aba-e6bd4f376f1a.png">

This is surprising bc Brave has disabled WebBluetooth for a while, as of https://github.com/brave/brave-core/pull/114

I am on MacOS 11.3.

**Comment by LaurenWags** [comment] 2021-06-02 16:16
I tried the following updates and was unable to reproduce:
1. Installed `1.27.3 Nightly` and updated to `1.27.33`. Did not get the prompt above.
2. Installed `1.27.28 Nightly` and updated to `1.27.33`. Did not get the prompt above.
3. Installed `1.26.34 Nightly` and updated to `1.27.33`. Did not get the prompt above.

**Comment by kjozwiak** [comment] 2021-06-02 17:27
Couldn't reproduce it either on my `macOS 11.3 x64` machine running through the following:

* Connected my Bluetooth headphones to the machine
* opened a random YT video and ensured audio was working

Updated using:

* `1.27.28 Chromium: 91.0.4472.77` --> `1.27.36 Chromium: 91.0.4472.77` - **`Couldn't Reproduce`**
* `1.27.31 Chromium: 91.0.4472.77` --> `1.27.36 Chromium: 91.0.4472.77` - **`Couldn't Reproduce`**
* `1.27.18 Chromium: 91.0.4472.77` --> `1.27.24 Chromium: 91.0.4472.77` - **`Couldn't Reproduce`**

**Comment by ShivanKaul** [comment] 2021-09-16 00:47
I couldn't repro either on a fresh install of Brave Nightly on a clean system (MacOS 10.12). Closing for now.

**Closed by ShivanKaul** 2021-09-16 00:47 UTC
Labels: privacy, privacy/chromium-redqueen, OS/Desktop
