### ISSUE TITLE
Can't remove sites from rewards list after restoring them all

### ISSUE THREAD

**Issue by dginovker** [brave/brave-browser#2515] opened 2018-12-13 00:50 UTC
## Description, Steps to Reproduce and Actual Result
Went to chrome://rewards/, clicked "See all x sites", clicked "Restore all", it restored them, started clicking "x" on the sites I didn't want to include, but nothing happened.

## Expected result:
I expected the sites I clicked "x" on to disappear

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) unknown (64-bit)
Running on Manjaro OS (Arch Linux), building Brave from source with the AUR here: https://aur.archlinux.org/packages/brave/. My about is below:

```
Brave | 0.57.18 Chromium: 71.0.3578.80 (Official Build)unknown (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux
JavaScript | V8 7.1.302.28
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
Command Line | /usr/lib/brave/brave --no-sandbox --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave,AutofillServerCommunication,UnifiedConsent --flag-switches-begin --flag-switches-end --
Executable Path | /usr/lib/brave/brave
Profile Path | /home/(my user)/.config/BraveSoftware/Brave-Browser/Default
```

### Reproducible on current release:
No idea, but I know it was happening on the 0.56 version too.

**Comment by NejcZdovc** [comment] 2018-12-13 14:51
hi thank you for reporting the issue. I think this is dupe of https://github.com/brave/brave-browser/issues/1693, so will move it to that one.

**Closed by NejcZdovc** 2018-12-13 14:51 UTC
