### ISSUE TITLE
Unable to restart/update Brave via Relaunch button

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16539] opened 2021-06-22 03:44 UTC
## Steps to Reproduce

   1.  clean profile
   2. launch Brave
   3. go to `Brave` `About Brave`
   4. click the `Relaunch` button

## Actual result:

Nothing happens

![relaunch](https://user-images.githubusercontent.com/387249/122859768-5f12d680-d2d1-11eb-92f9-6ed24783ab8f.gif)

## Expected result:
Browser should restart/relaunch w/update

## Reproduces how often: 

100%

## Brave version (brave://version info)

`1.28.17 Chromium: 91.0.4472.114 (Official Build) nightly (x86_64)`

**Comment by srirambv** [comment] 2021-06-22 03:47
+1 on macOS Version 10.15.7

**Comment by kjozwiak** [comment] 2021-06-22 03:50
Can't reproduce this on `Win 10 x64`. Seems like `macOS` specific. Nice find @stephendonner & @srirambv.

@rebron we should get this fixed sooner than later.

**Comment by rebron** [comment] 2021-06-22 03:53
cc: @mihaiplesa

**Comment by mihaiplesa** [comment] 2021-06-22 04:01
@stephendonner OS version?

**Comment by srirambv** [comment] 2021-06-22 04:03
@mihaiplesa I see it on macOS Version 10.15.7

**Comment by mihaiplesa** [comment] 2021-06-22 04:05
@srirambv I've seen you message above but would like to know if it happens on 11+

**Comment by simonhong** [comment] 2021-06-22 04:07
I can repro this on my `11.3.1` macOS.

**Comment by mihaiplesa** [comment] 2021-06-22 04:07
So the problem is not that the app updates and can't relaunch but that it presents the relaunch button and text when there is no update.

**Comment by simonhong** [comment] 2021-06-22 04:08
@mihaiplesa ah, `1.28.17` is our latest nightly?

**Comment by mihaiplesa** [comment] 2021-06-22 04:09
Yes - on the public channels.

**Comment by NonstickAtom785** [comment] 2021-06-22 04:31
![image](https://user-images.githubusercontent.com/36454623/122863583-a789be80-d2e8-11eb-84d8-60a5087adeee.png)
Simple search says it's "fixed" already in the nightly builds. Is this not the case?

**Comment by mihaiplesa** [comment] 2021-06-22 04:42
Trying to isolate the breking change between 1.289 and 1.28.11.

@simonhong do you know if https://github.com/brave/brave-core/pull/8642 could have had some unforeseen effects?

<img width="1177" alt="Screenshot 2021-06-21 at 23 35 51" src="https://user-images.githubusercontent.com/907672/122864459-978bd200-d31c-11eb-929d-2fb9ba1d77f5.png">

**Comment by mihaiplesa** [comment] 2021-06-22 04:46
@brave/legacy_qa if the above PR is the cause then this would have manifested when updating from 1.26.64 to 1.24.65 on the test channels - anyone tried this?

**Comment by NonstickAtom785** [comment] 2021-06-22 04:54
I don't think that commit had anything to do with the relaunch button. All I see is changes to the actual updater and installer.

**Comment by simonhong** [comment] 2021-06-22 04:55
@mihaiplesa Well, I'm not sure.. I'm trying to test it on my local

**Comment by srirambv** [comment] 2021-06-22 05:00
@mihaiplesa happens on 1.26.64 as well 

https://user-images.githubusercontent.com/17010094/122865960-1aae2780-d31f-11eb-91cd-fb48482baff5.mov

**Comment by mihaiplesa** [comment] 2021-06-22 05:02
@srirambv thanks for checking. 1.26.63 should be fine by my estimation.

**Comment by NonstickAtom785** [comment] 2021-06-22 05:05
It definitely works in 1.25.45

**Comment by bsclifton** [comment] 2021-06-22 05:36
Issue should be fixed by @mihaiplesa after revert:
master - https://github.com/brave/brave-core/commit/14e74d6e017308d69c70bdc65798a467d9de6e92
1.27 - https://github.com/brave/brave-core/commit/47f369babddf9aa440b00fc47c7659035aadae73
1.26 - https://github.com/brave/brave-core/commit/7f3c11a939a9b2dfec4b6176c287cd15863c28ee

We'll just need to get new binaries out 😄

**Closed** 2021-06-22 08:00 UTC
Labels: OS/Desktop, OS/macOS, bug, priority/P1, regression

**Comment by LaurenWags** [comment] 2021-06-22 12:18
Verified passed with `macOS x64 Catalina 10.15.7`:

```
Brave | 1.26.67 Chromium: 91.0.4472.114 (Official Build) (x86_64)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS Version 10.15.7 (Build 19H1030)
```

Reproduced the issue with `1.26.65`, "Relaunch" button was shown on brave://settings/help when no update was present, clicking "Relaunch" did nothing.

Confirmed no "Relaunch" button was shown on brave://settings/help for `1.26.67` when no update was present.

`1.26.65` | `1.26.67`
----- | -----
<img width="1033" alt="1 26 65" src="https://user-images.githubusercontent.com/28145373/122921774-e8a5c100-d330-11eb-9b85-96406a1f097c.png"> | <img width="1030" alt="1 26 67" src="https://user-images.githubusercontent.com/28145373/122921777-e9d6ee00-d330-11eb-97cf-5cc60a180b49.png">

Confirmed able to update from `1.25.73` --> `1.26.67` on `test` channel.
Confirmed able to update from `1.26.65` --> `1.26.67` on `test` channel.

**Comment by mherrmann** [comment] 2021-06-22 16:07
Sorry everybody for the trouble and thank you for fixing this problem, which seems to have been caused by my PR. Thank you @mihaiplesa @bsclifton @simonhong :pray:
