### ISSUE TITLE
Rewards panel is stuck in pre-opt state if wallet creation fails/crashes browser

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#3416] opened 2019-02-19 17:24 UTC
## Description 

While testing other fixes. Introduced a situation where if the browser crashes when creating a wallet from panel, the panel will forever be stuck in pre-opt state.

## Steps to Reproduce

Dev will need to introduce crash (induce DCHECK failure in `RewardsServiceImpl::OnPanelPublisherInfo` and try to push panel create wallet before crash occurs)

## Actual result:

<img width="1169" alt="screen shot 2019-02-19 at 12 13 42 pm" src="https://user-images.githubusercontent.com/25326067/53034393-0ef58200-3441-11e9-8b4a-1f0ade73bcd4.png">
Panel is stuck in pre-optin state. Only a profile clear can resolve.

## Expected result:
Either attempt to create wallet again or accept created wallet.

## Reproduces how often: 

Tricky. Would be very difficult to repro on a release build. Would more than likely only occur if there was an OS crash or any other catastrophic failure.

## Brave version (brave://version info)

found on 0.63.x

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
?

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment] 2019-03-07 09:12
closing as dupe of https://github.com/brave/brave-browser/issues/3440

**Closed by NejcZdovc** 2019-03-07 09:12 UTC
Labels: QA/No, feature/rewards, priority/P3
