### ISSUE TITLE
Popup/Popunder Tabs on ThePirateBay

### ISSUE THREAD

**Issue by GaryEarthling** [brave/brave-browser#7266] opened 2019-12-07 15:15 UTC
Popup/popunder tabs still occur on ThePirateBay. The issue is documented in issue 13730 (link below). Can 13730 be reopened? The description, steps to reproduce, etc are well documented there so I didn't copy them here.

[Popups and Popunders on ThePirateBay #13730](https://github.com/brave/browser-laptop/issues/13730)

## Brave version
Brave	1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
Revision	4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS	Windows 10 OS Version 1903 (Build 18362.476)

**Comment by ryanbr** [comment] 2019-12-09 07:39
We're testing (and rolling out soon) ubo and cosmetic fixes. This should eliminate most if not all popups from this site. No eta just yet, but its coming soon.

**Comment by GaryEarthling** [comment] 2019-12-12 11:54
Thanks @ryanbr. Shouldn't 13730 be reopened then - so that it can be tested when the new release come out?  If it's not reopened, the issue might be forgotten. The issue described in 13730 occurs on ThePirateBay in the latest Brave release (v1.0.1).

**Comment by ryanbr** [comment] 2019-12-12 12:05
You're pointing to an older unused repo re: #13730

**Comment by GaryEarthling** [comment] 2019-12-12 12:20
Ok, I'll go ahead and open a new issue. Should this be logged against brave-browser or brave-core?

**Comment by GaryEarthling** [comment] 2019-12-12 12:46
Opened a new issue against brave-browser. Hope that's the right spot.

[Popups on ThePirateBay #7338](https://github.com/brave/brave-browser/issues/7338)

**Comment by bsclifton** [comment] 2020-01-13 07:41
Closing as dupe of https://github.com/brave/brave-browser/issues/7338

**Closed by bsclifton** 2020-01-13 07:41 UTC
