### ISSUE TITLE
site: drive.google.com issue: videos do not play

### ISSUE THREAD

**Issue by alexwykoff** [brave/brave-browser#1495] opened 2018-10-10 18:36 UTC
## Description 
When visiting google drive to play a video, it was noticed that the video play would present, but clicking play would not work.

## Steps to Reproduce

   1.  Log into drive.google.com
   2.  Attempt to view a video

## Actual result:
Video player displays, however video does not start.

## Expected result:
The video should play either via autoplay or by clicking on play.

## Reproduces how often: 
Easily reproduceable.

## Brave version (chrome://version info)
0.55.12

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
- Does it reproduce on browser-laptop? 
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by srirambv** [comment] 2018-10-10 18:50
Dupe of https://github.com/brave/brave-browser/issues/1122

**Closed by srirambv** 2018-10-10 18:50 UTC
Labels: webcompat
