### ISSUE TITLE
Make BAT browser action extension to show next to Brave one

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#296] opened 2018-06-06 21:55 UTC
Each extension can have at most one browser action and this seems needed for ledger 2.0.

**Comment by bbondy** [comment] 2018-08-07 07:55
I actually do prefer it as WebUI but I don't think we'll get brave-extension in time converted to WebUI too.  So not sure if it will work for UI consistently.  It's probably best to do it from the start in WebUI.

**Comment by bbondy** [comment] 2018-08-07 07:55
I don't think the page will make the network requests though, it can call into C++ which can do it though.

**Comment by NejcZdovc** [comment] 2018-08-07 08:38
@bbondy page will not make any network requests, everything will be done via C++

**Comment by petemill** [comment] 2018-09-26 22:27
Duplicate of https://github.com/brave/brave-browser/issues/669

**Closed by petemill** 2018-09-26 22:27 UTC
