### ISSUE TITLE
bad performance with latest update

### ISSUE THREAD

**Issue by 424344** [brave/brave-browser#20929] opened 2022-02-07 10:38 UTC
## Description 

performance in the latest update is bad. please fix it.
see also other people on reddit:
https://www.reddit.com/r/brave_browser/comments/smb4jq/performance_has_gone_steeply_downhill_with_latest/
 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by 424344** [comment] 2022-02-07 19:14
brave 1.35.100 + windows10 21h2.

I changed nothing and now brave seems slower, especially scrolling, but also changing tabs (I have many tabs open in multiple windows).

**Comment by lplohmann** [comment] 2022-02-10 19:37
I'm a Mac OS user and I'm also experiencing very bad performance since last update.

Scrolling is very janky and tab switching is slow.

Also, some pages take a long time to start loading, while others seem to load without delay.

**Comment by bsclifton** [comment] 2022-02-11 05:22
Hey there folks - I think we have a fix for this! 😄 There was a flag which (in the Chromium code) is enabled by default. With Chrome, this flag is disabled via Finch server for all users. We've been able to reproduce major perf problems and then see the problem resolved once this is fixed

Kudos to @petemill and @atuchin-m for the great debugging work 😄 Fix is here:
https://github.com/brave/brave-variations/pull/217

If you want to try the fix without waiting, you can launch Brave with the following argument:
`--disable-features="NavigationThreadingOptimizations"`

**Comment by bsclifton** [comment] 2022-02-14 23:27
We're at 50% rollout for the fix - I'll close this issue once we hit 100% or if you can confirm the work-around above works @lplohmann @424344

**Comment by bsclifton** [comment] 2022-02-16 00:11
OK the mentioned fix is rolled out; things should be in good shape now. Closing issue 👍 You may need to close/restart the browser. Please let us know if you're still experiencing a problem and we can re-open

**Closed by bsclifton** 2022-02-16 00:11 UTC
Labels: needs-investigation, priority/P2, perf, OS/Desktop

**Comment by lplohmann** [comment] 2022-02-17 17:21
Sorry for the delay, only today I could test it again and yes, it is much better now.
