### ISSUE TITLE
Click on `?` in the brave://extensions for CW is navigating to the Google support page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#14997] opened 2021-03-29 11:05 UTC
## Description 

Click on `?` in the brave://extensions for CW is navigating to the Google support page

## Steps to Reproduce

   1. Open brave 1.24.x
   2. Install CW
   3. Open brave://extensions
   4. Click on `Details` in CW extension
   5. Click on `?` in the brave://extensions for CW is navigating to the link `https://support.google.com/chrome_webstore/answer/2664769?p=enable_extensions&visit_id=637526116984148721-3470980430&rd=1#extensionpermissions`

## Actual result:

![image (16)](https://user-images.githubusercontent.com/38657976/112827634-3dc49480-90ac-11eb-8f49-75dda2bd6660.png)

## Expected result:
Should redirect to specific articles on https://support.brave.com/

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.24.29 Chromium: 90.0.4430.41 (Official Build) nightly (64-bit)
-- | --
Revision | e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}
OS | Windows 10 OS Version 2004 (Build 19041.867)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @bbondy

**Comment by rahulsnkr** [comment] 2021-05-28 16:56
Duplicate of #14463?

**Comment by bbondy** [comment] 2021-05-28 18:22
I think so, thanks. Closing.

**Closed by bbondy** 2021-05-28 18:22 UTC
Labels: OS/Desktop, QA/Test-Plan-Specified, QA/Yes, branding, feature/wallet, priority/P3
