### ISSUE TITLE
CPU at 80% in Private Window - HUGE BUG! (Linux) STOP before MAIN BROWSER!

### ISSUE THREAD

**Issue by privacyosint** [brave/brave-browser#19193] opened 2021-11-02 19:24 UTC
## Description 

The cpu is out of control inside of private window. I have all 3 browsers going at once they put my computer at 100% cpu. Beta, Dev, Nightly. One of the browsers will each take 30-40% for my 6 core. I had to stop using brave on my laptop because of this.. It eats up my battery to fast. 
I have tried Linux Mint, Kubuntu. Same issue. Please fix this before it gets to the main browser... 

## Steps to Reproduce

   1. Look at CPU
   2. Open Brave
   3. Wait 10-20 secs to let it get to normal
   4. CPU goes up crazy in private window. I haven't even load any pages yet... 
   5. 30-40% =  1 private window inside of each brave browser OS. Beta, Dev, Nightly.

## Reproduces how often: 

EVERY TIME. 

## Brave version (brave://version info)

Version 1.32.89 Chromium: 95.0.4638.69 (Official Build) dev (64-bit)
Version 1.32.84 Chromium: 95.0.4638.54 (Official Build) beta (64-bit)
Version 1.33.50 Chromium: 95.0.4638.69 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NO
- Can you reproduce this issue with the beta channel? YES
- DEV? YES, I do use DEV. Love how you guys removed it from your site..
- Can you reproduce this issue with the nightly channel? YES

## Miscellaneous Information:

![brave](https://user-images.githubusercontent.com/90421861/139930918-fb2ee3e0-5fa5-42ce-b542-4d0dc2e0d2c8.png)

**Comment by privacyosint** [comment] 2021-11-02 19:30
@bsclifton

**Comment by rebron** [comment] 2021-11-03 16:05
Dupe of https://github.com/brave/brave-browser/issues/18961?

**Comment by bbondy** [comment] 2021-11-05 18:26
Will be fixed with https://github.com/brave/brave-browser/issues/18961 landing soon

**Closed by bbondy** 2021-11-05 18:26 UTC
Labels: OS/Linux, perf, needs-more-info, OS/Desktop
