### ISSUE TITLE
installation sometimes failing on both dev & beta when using x86 stub installers

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1606] opened 2018-10-16 07:17 UTC
## Description 

When attempting to install either `dev` or `beta` on a x86 machine using the sub installer, the installation fails after the download has been completed. Reproducing this constantly on my Win 7 x86 VM.

Windows showing the following:

```
Files that help describe the problem:
  C:\Users\kjozwiak\AppData\Local\Temp\WER4F47.tmp.WERInternalMetadata.xml
  C:\Users\kjozwiak\AppData\Local\Temp\WER536D.tmp.appcompat.txt
  C:\Users\kjozwiak\AppData\Local\Temp\WER536E.tmp.mdmp
<img width="724" alt="screen shot 2018-10-16 at 3 06 32 am" src="https://user-images.githubusercontent.com/2602313/46998431-85c7ea80-d0f0-11e8-909c-0101b2ec0d45.png">

```

## Steps to Reproduce

Test Case 1:

   1. visit https://github.com/brave/brave-browser/releases/tag/v0.55.14
   2. download `BraveBrowserDevSetup32.exe`
   3. attempt installing the above executable under Win 7 x86

Test Case 2:

   1. visit https://github.com/brave/brave-browser/releases/tag/v0.56.4
   2. download `BraveBrowserDevSetup32.exe`
   3. attempting installing the above executables under Win 7 x86

## Actual result:

<img width="724" alt="screen shot 2018-10-16 at 3 06 32 am" src="https://user-images.githubusercontent.com/2602313/46998455-91b3ac80-d0f0-11e8-82bf-073e2721d1cc.png">

<img width="859" alt="screen shot 2018-10-16 at 1 37 59 am" src="https://user-images.githubusercontent.com/2602313/46998088-88761000-d0ef-11e8-8a17-6b6b46a1a2cd.png">

## Expected result:

Should be installing on `Win 7 x86` without any issues.

## Reproduces how often: 

100% reproducible using my Win 7 x86 machine.

## Brave version (brave://version info)

Brave | 0.56.4 Chromium: 70.0.3538.54 (Official Build) dev (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Windows

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Windows

### Additional Information

@brave/legacy_qa if anyone has Win 7 x86, can you please check and see if it's being installed for you? If you don't have Win 7 x86, maybe try a few installs on any Win x86 systems.

**Comment by srirambv** [comment] 2018-10-16 13:32
Reproduced on Windows 7 x64 with `BraveBrowserDevSetup32.exe`
![image](https://user-images.githubusercontent.com/17010094/47019960-46b48c00-d126-11e8-895f-a8733a11eb8d.png)

**Comment by LaurenWags** [comment] 2018-10-16 13:39
Reproduced on Win 7 x86 VM when attempting to install `BraveBrowserBetaSetup32.exe`:
![screen shot 2018-10-16 at 9 36 01 am](https://user-images.githubusercontent.com/28145373/47020438-5e404480-d127-11e8-8328-fd7aa5c3b1ee.png)
![screen shot 2018-10-16 at 9 38 13 am](https://user-images.githubusercontent.com/28145373/47020444-60a29e80-d127-11e8-9224-e75c1a2542f4.png)

**Comment by kjozwiak** [comment] 2018-10-16 14:28
Awesome! Thanks for taking a look @LaurenWags! I was wondering if it might have been my VM but seems like a legitiment issue 👍

**Comment by simonhong** [comment] 2018-10-16 18:18
@kjozwiak Can you test whether `brave_installer.exe` works on x32?

**Comment by bbondy** [comment] 2018-10-17 14:41
Moving it out of the release since @kjozwiak and @srirambv found that it's working for Release channel but not for Beta and Dev. They will retest on next Beta and Dev in case it was just something wrong in the process to upload the last one.

**Comment by simonhong** [comment] 2018-10-18 00:39
Install testing with 32bit installer on x64(Win10) didn't fail at all.
I assume that this issue is x86 OS related.

**Comment by simonhong** [comment] 2018-10-18 05:46
Finished to install x86 Win7 on my VM and I got the same error.
After many trying, I installed whole three release.
<img width="756" alt="screen shot 2018-10-18 at 14 45 09" src="https://user-images.githubusercontent.com/6786187/47133624-84f7aa00-d2e4-11e8-8fdc-d0eaac5da082.png">

I'll dig more about this failure.

**Comment by simonhong** [comment] 2018-10-18 07:07
In failed case, running installer returns very early time.

**Comment by simonhong** [comment] 2018-10-18 09:15
I found the cause of this failure.
When there is no registry entry(HKEY_CURRENT_USER\Software\BraveSoftware\Promo),
silent installer is easy to fail. However, it's not failed on x64 even if there is no that registry key.
I think this crash wouldn't be happened when we uses latest omaha client.

Ah, non stable stub installer doesn't use latest omaha.
This is the reason why only stable stub installer was ok.

@mbacchi We should use latest omaha for all channel stub installer. That will resolve this crash.

I'll dig more about silent installer fail on x86 when our registry key is empty.

**Comment by simonhong** [comment] 2018-10-24 22:55
@kjozwiak x86 beta/dev stub installer also updated. You can check this again.

**Comment by crazy-max** [comment] 2018-10-25 23:00
@simonhong Where can I download `brave_installer-ia32.exe` or `brave_installer-x64.exe` for the release channel please ?

**Comment by simonhong** [comment] 2018-10-26 00:13
@crazy-max , you could get `brave_installer-xxx.exe` (we call it as silent installer) when brave install is finished with stub installer(online installer). Why do you need silent installer? It just installs brave browser itself and not updater.

Also, this issue was fixed - you can install beta/dev on x86 by using stub installer from https://brave.com/download-beta and https://brave.com/download-dev

**Comment by simonhong** [comment] 2018-10-26 00:37
@crazy-max Only online installer is available from above link.
After finishing install with online installer, you can get `brave_installer-xxx.exe` in `C:\Program Files\BraveSoftware\Update\Download` if you installs with admin mode.

Make sure that running `brave_installer-xxx.exe` directly could cause brave updater not work properly.

**Comment by crazy-max** [comment] 2018-10-26 00:39
@simonhong In fact it's to make a portable app but thanks anyway

**Closed** 2018-10-26 04:32 UTC
Labels: OS/Windows, QA/Yes, bug, installer/omaha, priority/P1, release/blocking, setup/installer

**Comment by mbacchi** [comment] 2018-10-26 13:43
@crazy-max I can get you the `.exe` files. I upload them manually to the updates server which is where the stub installer collects them to install. Find me in slack and let me know the version and architecture you need and I'll pass them along.

**Comment by crazy-max** [comment] 2018-10-26 14:00
@mbacchi [Already done](https://github.com/portapps/untouched/releases/tag/brave-0.55.20) but thanks ;)
