### ISSUE TITLE
Brave doesn't recognize "http:" site entries as bookmarks when importing

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#13189] opened 2020-12-14 18:35 UTC
## Description 

It appears that Brave doesn't recognize "http" entries as bookmarks when imported from Firefox. Bookmarks imported in this way do not show black "bookmarked" flag icon and instead appear as white. 

User left very accurate description:

> I tested this on 25 of my imported bookmarks and it followed the pattern 100% of the time.
> 
> If my imported bookmark has a URL beginning with HTTP in the Bookmark Manager, then the opened tab has a white bookmark flag on it.
> 
> If my imported bookmark has a URL beginning with HTTPS in the Bookmark Manager, then the opened tab has a black bookmark flag on it.
> 
> If I add a new bookmark in Brave, that new bookmark has a URL beginning with HTTPS in the Bookmark Manager and the opened tab has a black bookmark flag on it.

## Steps to Reproduce

   1. Have Firefox bookmarks w/both `http` and `https`. 
   2. Import bookmarks from Firefox into Brave
   3. Open imported bookmarks

## Actual result:

Bookmarks with `http` appear as white/unbookmarked 

## Expected result:
All bookmarks should appear as bookmarked w/black bookmark icon 

## Miscellaneous Information:

https://community.brave.com/t/bookmark-icon-on-url-bar-shows-white-after-selecting-the-url-from-my-bookmarks/186806/9

**Comment by fmarier** [comment] 2020-12-14 20:45
I suspect it's working as intended:

1. HTTP version of the site is bookmarked in Firefox and imported into Brave (as HTTP).
2. Clicking on the bookmarks takes us to the HTTPS version of the site (thanks to Brave's HTTPS upgrades).
3. The URL in the URL bar doesn't match the URL of the bookmark (HTTP v. HTTPS) and so the bookmark icon stays white (white = not bookmarked, black = bookmarked).

It's not ideal, because there is already a bookmark for the insecure version of the site and so it's confusing, but technically http://example.com and https://example.com are two different URLs.

One thing we could potentially do is to apply HTTPS when we import bookmarks, but then we wouldn't be importing bookmarks as-is, which some users might be unhappy about.

**Comment by rebron** [comment] 2020-12-15 05:09
per @fmarier comments above this looks like a won't fix @Brave-Matt.

**Comment by rebron** [comment] 2020-12-17 22:05
Let's close this one out. Not ideal but works as expected and possibly just a handful of bookmarks that a user will care about and then would just have to bookmark the https:// site.

**Closed by rebron** 2020-12-17 22:05 UTC
Labels: OS/Desktop, closed/wontfix
