### ISSUE TITLE
ads notification not showing

### ISSUE THREAD

**Issue by thewiz69** [brave/brave-browser#12049] opened 2020-10-08 11:09 UTC
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment] 2020-10-09 05:58
@thewiz69 do you have more information? What version you're on? What channel you're on? (Release, Beta, Nightly)

**Comment by tmancey** [comment] 2020-10-09 17:21
@thewiz69 There is a known issue which will be resolved by https://github.com/brave/brave-browser/issues/11952, can you please test our nightly build (installs along side our release builds), you can download the nightly build from https://www.brave.com/download-nightly. If the issue is not resolved in this build please re-open this ticket with additional information as requested by @bsclifton . Thanks

**Closed by tmancey** 2020-10-09 17:21 UTC
Labels: OS/Desktop, feature/ads
