### ISSUE TITLE
User is unable to change avatar icon after adding user/person. 

### ISSUE THREAD

**Issue by OyeBenny** [brave/brave-browser#4973] opened 2019-06-19 02:14 UTC
## Description 
When a Person/User is added to Brave they are unable to edit/alter their avatar/user icon. 

## Steps to Reproduce
1. Go to your account settings
2. Go to Manage People
3. Try to change your avatar icon sensibly in those two places. 

## Actual result:
Cannot update/edit User avatar/icon.

## Expected result:
I want to be able to change it. Right now mine is stuck on the default empty gray person. 

## Brave version (brave://version info)
v 0.65.120 - Windows 10 Pro

**Comment by kjozwiak** [comment] 2019-06-19 03:27
Duplicate of https://github.com/brave/brave-browser/issues/4615. Closing. @OyeBenny please re-open if the above is a different issue.

**Closed by kjozwiak** 2019-06-19 03:27 UTC
