### ISSUE TITLE
Blank, black screen when trying to view the `Top Sites` panel in `Customization` on the new-tab page (NTP)

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#37631] opened 2024-04-16 22:39 UTC
## Description 

Blank, black screen when trying to view the `Top Sites` panel in `Customization` on the new-tab page (NTP)

Found while testing https://github.com/brave/brave-browser/issues/37110

## Steps to Reproduce

   1. install `1.66.80`
   2. launch Brave
   3. open a new-tab page
   4. click on `Customize` at the bottom (but don't yet enable Brave News)
   5. now, click `Top Sites`

## Actual result:

Blank, black screen

screenshot | in dev tools' console
------------|---------------------
<img width="1312" alt="Screen Shot 2024-04-16 at 3 30 46 PM" src="https://github.com/brave/brave-browser/assets/387249/9651d6f8-8eb5-49fa-8941-d0437f6fdc56"> | <img width="1312" alt="Screen Shot 2024-04-16 at 3 24 34 PM" src="https://github.com/brave/brave-browser/assets/387249/a095e5a8-1abe-4404-83b0-588b4f4f8a8b">

## Expected result:

`Customize Dashboard` remains, focused on the chosen panel, `Top Sites`

<img width="1312" alt="Screen Shot 2024-04-16 at 3 38 35 PM" src="https://github.com/brave/brave-browser/assets/387249/10f60600-bcb4-4996-a4fe-eaab4eb7cfa3">

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave	1.66.80 Chromium: 124.0.6367.29 (Official Build) beta (x86_64) 
Revision	2d822a1940c9159c1f307cd1c0a8f58fcfb50fe0
OS	macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `No`

cc @fallaciousreasoning @petemill @rebron @brave/qa-team

**Comment by fallaciousreasoning** [comment] 2024-04-17 00:55
So this doesn't repro for me in 1.66.80 in Linux. However, we've been seeing a few of these `ChunkLoadError`s which is worrying me a bit. I wonder what's causing them.

**Comment by fallaciousreasoning** [comment] 2024-04-17 00:58
It seems like it could be a caching error, but I'm not sure. Does it repro in another profile?

**Comment by stephendonner** [comment] 2024-04-17 17:10
> It seems like it could be a caching error, but I'm not sure. Does it repro in another profile?

Reproduces 100% in a clean profile, for me.

**Comment by sangwoo108** [comment] 2024-04-18 00:07
On my mac, both beta and nightly works well.

**Comment by fallaciousreasoning** [comment] 2024-04-18 00:08
I'm worried it's a build/installer problem. Does reinstalling the same version change anything @stephendonner?

**Comment by stephendonner** [comment] 2024-04-18 22:24
> I'm worried it's a build/installer problem. Does reinstalling the same version change anything @stephendonner?

I think it's using `Morpheon Dark`: https://chromewebstore.google.com/detail/morpheon-dark/mafbdhjdkjnoafhfelkjpchpaepjknad (now that I've retraced my steps); can you and @sangwoo108 try installing that, and see if the new-page page/`Customize` dialogs are broken/

**Comment by fallaciousreasoning** [comment] 2024-04-18 23:08
Hmmm, still works for me - that would've been a neat solution though. Does it work for you when you remove it?

![image](https://github.com/brave/brave-browser/assets/7678024/7ad7a78f-1c43-499f-9a05-5271f71a07e1)

It'd be weird though, 'cause I don't think extensions can run on chrome:// urls

**Comment by fallaciousreasoning** [comment] 2024-04-18 23:44
I wonder if this could be related to the React 18 upgrade

**Comment by sangwoo108** [comment] 2024-04-18 23:46
Yeah, it works for me with the theme(Nightly)

**Comment by sangwoo108** [comment] 2024-04-18 23:50
@stephendonner I'm cuirous what you see when you type "chrome://newtab/314.chunk.js" to the location bar?

**Comment by stephendonner** [comment] 2024-04-19 00:31
@sangwoo108 here you go, thanks for asking!

> @stephendonner I'm cuirous what you see when you type "chrome://newtab/314.chunk.js" to the location bar? And also curios if you're uising intel mac or arm

<img width="1312" alt="Screenshot 2024-04-18 at 5 29 44 PM" src="https://github.com/brave/brave-browser/assets/387249/9623b5aa-ab80-45a5-a9a9-6b5c794ff8ff">

Intel macOS-x64, Big Sur:

```
Brave | 1.66.82 Chromium: 124.0.6367.60 (Official Build) beta (x86_64)
-- | --
Revision | 5dc8a11fe47f7e764f9108c665f3276805497669
OS | macOS Version 14.5 (Build 23F5059e)
```

**Comment by sangwoo108** [comment] 2024-04-19 00:40
Interesting, I'm not sure it should be same but my beta returns different source for the address. I've checked using my arm machine. I'll try checking using intel mac and let you know

**Comment by sangwoo108** [comment] 2024-04-19 00:56
Gotcha! On my intel machine, it was reproducible. I suspect something was wrong while rolling out the beta. Maybe webpack dependency? But not sure who can look into this.

<img width="1221" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/bb09d0e2-0326-4a8c-a9bd-6344bdaab213">

**Comment by fallaciousreasoning** [comment] 2024-04-19 01:36
Going to be interesting to see what happens when the new Beta comes out. Hopefully this just disappears?

**Comment by stephendonner** [comment] 2024-04-19 07:05
> Going to be interesting to see what happens when the new Beta comes out. Hopefully this just disappears?

Happens with the `latest nightly`

```
Brave	1.67.23 Chromium: 124.0.6367.60 (Official Build) nightly (x86_64) 
Revision	2574e866fb941a93ad6414bb02563c9ecb9fa9d5
OS	macOS Version 11.7.10 (Build 20G1427) 
```

too 😢

**Comment by fallaciousreasoning** [comment] 2024-04-21 21:03
@sangwoo108 does this happen in Dev for you on your Intel mac?

**Comment by sangwoo108** [comment] 2024-04-22 00:16
I checked but my dev version was okay. We're asking folks about the build machine here https://bravesoftware.slack.com/archives/C01EVLWS8R5/p1713744910635809

**Comment by fallaciousreasoning** [comment] 2024-04-29 02:02
@stephendonner not sure but can we get a build artifact from https://ci.brave.com/job/test-brave-browser-build-macos-x64/1189/ and see if it repros?

**Comment by stephendonner** [comment] 2024-04-30 19:14
Tested using https://build-artifacts.brave.com/test-brave-browser-build-macos-x64/1189/Brave-Browser-Nightly-x64.dmg

Cannot reproduce using:

## `Big Sur` `11.7.10`

Brave | 1.67.29 Chromium: 124.0.6367.60 (Official Build) nightly (x86_64)
-- | --
Revision | 87978a973dbc82c83fc1f20ab9ec943862c388ed
OS | macOS Version 11.7.10 (Build 20G1427)

**Comment by stephendonner** [comment] 2024-05-14 17:28
Trying again with 

```
Brave | 1.66.107 Chromium: 125.0.6422.41 (Official Build) (x86_64)
-- | --
Revision | 188213f024297511fc5e37efe56eabde5992b300
OS | macOS Version 11.7.10 (Build 20G1427)
```

Perhaps this was related to a few of the Brave News pref-service-initialization issues, which was resolved in `1.66.x` 🤞

**Comment by MadhaviSeelam** [comment] 2024-05-14 17:51
Also couldn't reproduce in `macOS`

<img width="1470" alt="Screenshot 2024-05-14 at 10 41 31 AM" src="https://github.com/brave/brave-browser/assets/98358127/2e1dadf6-90f2-4ffe-884c-b12396e92a25">

**Comment by stephendonner** [comment] 2024-05-14 20:06
Brave | 1.66.107 Chromium: 125.0.6422.41 (Official Build) (x86_64)
-- | --
Revision | 188213f024297511fc5e37efe56eabde5992b300
OS | macOS Version 14.5 (Build 23F79)

<img width="1312" alt="Screenshot 2024-05-14 at 1 06 20 PM" src="https://github.com/brave/brave-browser/assets/387249/77554941-9585-4e19-a203-351a1cac1e79">

**Comment by fallaciousreasoning** [comment] 2024-05-14 21:17
Okay, I don't trust this at all @stephendonner - I'm going to start another thread in DevOps

**Comment by chutneyio** [comment] 2024-05-19 23:42
Blank page when select Customize -> Brave News:

<img width="1571" alt="Screenshot 2024-05-20 at 06 40 37" src="https://github.com/brave/brave-browser/assets/145855391/f768fa9a-b3a2-4e55-b1ec-f8ac98e4d4c5">

Version 1.66.110 Chromium: 125.0.6422.60 (Official Build) (x86_64)

**Comment by fallaciousreasoning** [comment] 2024-05-20 00:15
@petemill looks like it's happening in the wild :fearful: - we should get that fix you were talking about ASAP

**Comment by petemill** [comment] 2024-05-21 23:58
This is caused by https://github.com/brave/brave-browser/issues/38435 but mainly https://github.com/brave/brave-browser/issues/38437. Not sure if you want to keep this open for verification test plan or close as duplicate. I'll put the test plan on 38435

**Comment by kjozwiak** [comment] 2024-05-22 03:44
Closing as the above should be fixed by https://github.com/brave/brave-core/pull/23753.

**Closed** 2024-05-22 03:44 UTC
Labels: OS/macOS, priority/P2, QA/Yes, QA/Test-Plan-Specified, regression, OS/Desktop

**Comment by kjozwiak** [comment] 2024-05-22 06:19
@brave/qa-team can also use the STR/Cases that were mentioned/outlined via https://github.com/brave/brave-browser/issues/38437#issue-2307404139 and can use https://github.com/brave/brave-core/pull/23753#issuecomment-2123942399 as a template. Please make sure that we're using the `Universal` installer for the above 👍 

The above requires `1.66.113` or higher for `1.66.x` verification 👍

**Comment by stephendonner** [comment] 2024-05-22 15:54
## Verification `PASSED` using

```
Brave | 1.66.113 Chromium: 125.0.6422.76 (Official Build) (x86_64)
-- | --
Revision | b1864a9a0152d4f1631121c6b13a7426f50cf336
OS | macOS Version 14.5 (Build 23F79)
```

### Followed my original steps to reproduce, for both new and existing profiles

## Existing profile

<img width="1312" alt="Screenshot 2024-05-22 at 8 44 52 AM" src="https://github.com/brave/brave-browser/assets/387249/ae39a9f4-d3e9-47e9-86e4-341fa915de86">


## New profile

<img width="1312" alt="Screenshot 2024-05-22 at 8 49 59 AM" src="https://github.com/brave/brave-browser/assets/387249/de6493dc-7189-49a1-a583-53c7624c422f">

### Confirmed I could no longer reproduce the JS error; new-tab pages opened the `Customize` dashboard without issue
