### ISSUE TITLE
Window controls and browser controls overlap with vertical tabs enabled

### ISSUE THREAD

**Issue by Coffeeling** [brave/brave-browser#31957] opened 2023-07-28 18:59 UTC
## Steps to Reproduce
Enable vertical tabs, disable the titlebar.

## Actual result:
![image](https://github.com/brave/brave-browser/assets/54371213/2c47b2c2-6323-4bd6-bafd-aa5ee42f49a9)

## Expected result:
Brave controls to the side of window controls

## Reproduces how often: 
100% repro on my machine, reboot didn't help. (Issue started after update, can't update again because update broke on Nightly)

## Brave version (brave://version info)
Brave	1.58.55 Chromium: 116.0.5845.51 (Official Build) nightly (64-bit) 
Revision	34193c8918bf9f572cebc0ac8bf4a5ba1a102483
OS	Windows 11 Version 22H2 (Build 22621.1992)

## Version/Channel Information:
- Can you reproduce this issue with the beta channel? 
    - No.
- Can you reproduce this issue with the nightly channel? 
    - Yes.

**Comment by rebron** [comment] 2023-07-28 19:11
Closing as dupe of https://github.com/brave/brave-browser/issues/31908

**Closed by rebron** 2023-07-28 19:11 UTC
Labels: OS/Desktop
