### ISSUE TITLE
Implement custom Brave Ad notifications

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#9592] opened 2020-05-03 04:44 UTC
Implement custom Brave Ad notifications

**Comment by tmancey** [comment] 2020-05-03 05:10
Resolving this issue would also close:

https://github.com/brave/brave-browser/issues/5541
https://github.com/brave/brave-browser/issues/5205
https://github.com/brave/brave-browser/issues/2887
https://github.com/brave/brave-browser/issues/4007
https://github.com/brave/brave-browser/issues/6913

**Comment by tjcrowder** [comment] 2020-10-22 12:40
@tmancey  - Oooh, excited to see that something progressing that deals with #6913! Is there anywhere (other than the code of the [PR](https://github.com/brave/brave-core/pull/6728)!) where can we read up on what's being done?

**Comment by tmancey** [comment] 2020-10-22 12:51
@tjcrowder unfortunately not at this time. Thanks

**Comment by bsclifton** [comment] 2020-12-08 18:47
Moving to 1.20 as revert to 1.19 was done w/ https://github.com/brave/brave-core/pull/7317

**Comment by LaurenWags** [comment] 2021-01-20 16:59
@tmancey @bsclifton @rebron since this has been tied to Nightly should this issue be marked as `QA/No`? Do we want some kind of placeholder issue opened? Maybe it could just remain open until a milestone is decided for custom ad notifications. Let me know your thoughts. Marking as `QA/Blocked` until we decide 👍🏻

**Comment by bsclifton** [comment] 2021-01-21 06:19
Great point - maybe we should just re-open until it moves off Nightly. WDYT, @tmancey?

**Comment by tmancey** [comment] 2021-01-21 09:05
@LaurenWags @bsclifton Reopened and changed milestone to 1.21 Nightly

**Comment by tmancey** [comment] 2021-02-10 12:26
This work is part of custom ad notifications is complete however until this change is available in beta/release channels this ticket should be blocked

**Comment by UtkarshVerma** [comment] 2021-02-17 08:22
Hi, I just noticed this feature has been enabled by default. I use `dwm` and for some reason, I'm not able to click on the hamburger menu after closing the ad notification. I want to use native notifications instead. Could you please tell me how to do so?

**Comment by tmancey** [comment] 2021-02-17 08:40
@UtkarshVerma Please install release or beta channel builds to remove custom ad notifications at this time. Thanks

**Comment by UtkarshVerma** [comment] 2021-04-03 08:52
@tmancey I'm using the latest release of Brave (Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) unknown (64-bit)). I still can't disable the custom notifications for ads.

**Comment by tmancey** [comment] 2021-04-04 07:53
@UtkarshVerma Could you please take a screenshot of the notification when it is shown on your screen. Thank you

**Comment by TheCultLeader666** [comment] 2021-04-07 22:17
IDK if my feedback is wanted here, but I vastly prefer native notifications for rewards ads, and it's enough to keep me from using the nightly build. These custom notifications look pretty ugly and out of place, especially since they don't follow the browser color scheme, and it's much better to be able to manage ads notifications natively.

**Comment by tmancey** [comment] 2021-04-08 06:58
@TheCultLeader666 Thank you for your feedback, we are currently working on improving the overall design and positioning, see https://github.com/brave/brave-core/pull/8377. cc @bradleyrichter @jenn-rhim

**Comment by UtkarshVerma** [comment] 2021-04-14 18:06
@tmancey This is how my ad notifications look like.
![pic-selected-210414-2335-18](https://user-images.githubusercontent.com/31820255/114758085-3541ae80-9d7a-11eb-9d51-8e4f769f2bd1.png)

**Comment by tmancey** [comment] 2021-04-29 16:36
Resolved as part of https://github.com/brave/brave-browser/issues/13132 which will now ride the trains

**Closed** 2021-04-29 18:19 UTC
Labels: OS/Android, OS/Desktop, QA/Yes, enhancement, feature/ads, priority/P3, release-notes/exclude

**Comment by UtkarshVerma** [comment] 2021-05-21 12:11
> @tmancey This is how my ad notifications look like.
> ![pic-selected-210414-2335-18](https://user-images.githubusercontent.com/31820255/114758085-3541ae80-9d7a-11eb-9d51-8e4f769f2bd1.png)

@tmancey Any thoughts?

**Comment by tmancey** [comment] 2021-05-21 13:07
@UtkarshVerma you cannot disable custom ad notifications. If you are experiencing issues, please raise a new github issue with steps to reproduce. Thank you

**Comment by GeetaSarvadnya** [comment] 2021-06-08 15:40
Verification passed on

```


<!--StartFragment-->
Brave | 1.26.54 Chromium: 91.0.4472.88&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | 109e9cd038b94a631aea7d40ee3d56c1278f2597-refs/branch-heads/4472@{#1385}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.985)

<!--EndFragment-->


```
- Verified the issue in https://github.com/brave/brave-browser/issues/13132#issuecomment-856617168

**Comment by GeetaSarvadnya** [comment] 2021-06-14 11:24
Verification passed on Samsung Galaxy Tab version 10 running brave Beta build `Bravemonoarm64 1.26.56.apk`
Verified the test plan from https://github.com/brave/brave-core/pull/8377
- Confirmed custom Ad notifications are served in Android
- Confirmed custom Ad notification are shown correctly in Light mode
- Confirmed custom Ad notification are shown correctly in Dark mode
- Encountered https://github.com/brave/brave-browser/issues/16350, https://github.com/brave/brave-browser/issues/16400 and https://github.com/brave/brave-browser/issues/16361
- Confirmed users are rewarded for viewing custom ads
- Additional testing is covered in https://github.com/brave/brave-browser/issues/13038#issuecomment-859397563 and https://github.com/brave/brave-browser/issues/15624#issuecomment-860598305
Brave://rewards - Ads panel:
![Screenshot_20210614-164557_Brave - Beta](https://user-images.githubusercontent.com/38657976/121884506-a4169600-cd30-11eb-9bae-ae11cb54087a.jpg)

**Comment by CodeDead** [comment] 2021-07-29 12:16
Notifications are not working on the Wayland display server.

**Steps to reproduce:**

- Use Linux
- Use Wayland
- Use Brave

**Comment by mattfbacon** [comment] 2021-10-07 23:29
PLEASE add an option to disable this. I hate these notifications, they display on top of actual notifications, they are ugly compared to my actual notifications. Everything was working fine before.

**Comment by tmancey** [comment] 2021-10-08 04:16
Hi. You can disable custom ad notifications in brave://flags. Thanks

**Comment by mattfbacon** [comment] 2021-10-09 04:07
Is that "Enable system notifications"? Or some other key?

**Comment by mattfbacon** [comment] 2021-10-09 04:08
Nevermind, it's "Enable Brave Ads custom notifications". Thanks. Hope this helps anyone that wants system notifications.

**Comment by mattfbacon** [comment] 2021-10-11 17:13
Actually, that doesn't work. Could you give the specific flag to set?

**Comment by UndarkAido** [comment] 2021-10-17 21:27
brave://flags/#brave-ads-custom-notifications isn't working for me either. I'm just going to turn off ads for now.

**Comment by UndarkAido** [comment] 2021-10-17 21:30
Looks like #18798 covers this issue though for anyone coming through
