### ISSUE TITLE
Failed to execute web browser

### ISSUE THREAD

**Issue by e-belair** [brave/brave-browser#5112] opened 2019-07-03 05:58 UTC
## Description 
When I click on a link from a third party application, I get this message:
![image](https://user-images.githubusercontent.com/596562/60566638-ca231580-9d67-11e9-9087-9576e1eb5cb0.png)

I noticed that occurs only when Brave is already opened.

Version 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)
Xubuntu 18.04
Brave is my default browser.

**Comment by rebron** [comment] 2019-07-05 17:14
@e-belair What application(s) are you using?

**Comment by e-belair** [comment] 2019-07-08 06:23
I need a bit time to list all the applications that cause this behavior, but the first on top of the list is Thunderbird.

**Comment by antonioprates** [comment] 2019-08-01 12:04
I got same issue with Brave on Xubuntu 18.04, when opening a link from slack...

**Comment by tbjornli** [comment] 2019-09-05 01:55
> I got same issue with Brave on Xubuntu 18.04, when opening a link from slack...

I'm having the exact same issue and when it happens it logs a segfault in the syslog:

`Sep  4 22:50:29 localhost kernel: [295838.515995] brave[13508]: segfault at 10 ip 000056143ecb8bd5 sp 00007ffd057968c0 error 4 in brave[56143a76a000+713a000]`

**Comment by e-belair** [comment] 2019-09-05 06:33
I got the same error message as @tbjornli 
`Sep  5 08:32:28 kernel: [  735.397955] brave[10014]: segfault at 10 ip 0000556736528bd5 sp 00007ffdf76206d0 error 4 in brave[556731fda000+713a000]
`

**Comment by tbjornli** [comment] 2019-09-05 12:38
If brave is already running and I'm running `brave-browser` from the terminal it segfaults as well. Here is the last output of strace:
```
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x10} ---
[31965:31965:0905/093642.871863:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

**Comment by nobd** [comment] 2019-09-24 09:59
Same issue here on Debian 9.11, a fix is needed. 

Switching to Chrome / Chromium in Preferred Applications is the only way to fix this atm.

**Comment by bsclifton** [comment] 2019-09-24 10:32
cc: @mbacchi

**Comment by mbacchi** [comment] 2019-09-24 13:05
This looks to be the problem described in https://github.com/brave/brave-browser/issues/4142, which a fix was added to nightly in PR https://github.com/brave/brave-core/pull/3431. It won't reach the release channel for 3 release cycles, so @bsclifton and @fmarier we may want to uplift that to the beta channel.

**Comment by fmarier** [comment] 2019-09-24 17:30
That's indeed a duplicate of #4142. Good idea about uplifting the work-around.

**Closed by fmarier** 2019-09-24 17:30 UTC
Labels: OS/Linux, need-more-info
