### ISSUE TITLE
Add "new tab" customization

### ISSUE THREAD

**Issue by leobel96** [brave/brave-browser#3269] opened 2019-02-07 22:46 UTC
Actually the user can only choose between the default new tab, continue from where he left or open a page chosen by the user. In my opinion the user should have the possibility to deeper customize the default "new tab" adding a search bar, hiding the websites tiles, choosing the backgrounds source, the colors palette, the elements position, ...

**Comment by Liunkae** [comment] 2019-02-07 23:49
Duplicate of #353

**Comment by leobel96** [comment] 2019-02-07 23:55
Oh, sorry. I've looked for something similar before opening the issue but I haven't seen it :(

**Closed** 2019-02-08 00:14 UTC
