### ISSUE TITLE
Bravify Chromium's QR Dino

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#11606] opened 2020-09-05 14:33 UTC
## Description 
Chromium 85 shipped with a [QR Code generator](https://source.chromium.org/chromium/chromium/src/+/master:chrome/common/qr_code_generator/) for sharing URLs and Web Authentication. This feature can be enabled within brave://flags/#sharing-qr-code-generator. Once enabled, users are able to generate a QR Code for the current URL via the context menu, or the address bar:

![image](https://user-images.githubusercontent.com/815158/92307016-04cea200-ef59-11ea-96dc-2ea46f05b3c4.png)

## Actual result:
![image](https://user-images.githubusercontent.com/815158/92307086-81fa1700-ef59-11ea-99c0-2b7c68d46d42.png)

## Expected result:
![image](https://user-images.githubusercontent.com/815158/92307162-e6b57180-ef59-11ea-8d1c-ad77beee1854.png)

![image](https://user-images.githubusercontent.com/815158/92307650-727ccd00-ef5d-11ea-882e-0193b1f239a7.png)
 
![image](https://user-images.githubusercontent.com/815158/92307368-87586100-ef5b-11ea-804c-edcf2fb73d5d.png)

**Comment by bsclifton** [comment] 2021-05-17 16:57
Per @mkarolin the dino version of the file lives at https://source.chromium.org/chromium/chromium/src/+/master:components/qr_code_generator/dino_image.h

**Comment by Brave-Matt** [comment] 2021-05-26 21:16
Chiming in here because this has actually been mentioned/requested a few times on socials. Plus one! :)
🚫  🦖 
➕ 🦁

**Comment by kjozwiak** [comment] 2021-06-01 22:50
We'll need to get this uplifted into `1.26.x` after discussing with @rebron during today's b-b triage/planning meeting. QR code was enabled and slated to be released in `1.26.x` via https://github.com/brave/brave-browser/issues/15900.

**Closed** 2021-06-07 20:45 UTC
Labels: OS/Android, OS/Desktop, branding, design/needs-mock-up, priority/P3

**Comment by srirambv** [comment] 2021-06-14 08:16
Removing Android label as there is no QR Code generated when a link is opened. @jonathansampson @mkarolin Please add a test plan for Android if it is required to be checked as I couldn't find a way to generate the QR code either via context menu on links or via URL bar or flags.

**Comment by LaurenWags** [comment] 2021-06-14 14:07
Verified passed with

```
Brave | 1.26.59 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;beta&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 10.15.7 (Build 19H1030)
```

Testing of QR code functionality is covered under https://github.com/brave/brave-browser/issues/15900#issuecomment-843567027.

For this issue, confirmed the Brave branding of the QR code being generated from URL bar, the downloaded file, and from context menu.

QR code generated from URL bar | Downloaded QR code image | QR code generated from context menu
----- | ----- | -----
<img width="336" alt="URL bar" src="https://user-images.githubusercontent.com/28145373/121905391-1c149a00-ccf8-11eb-837b-c0c349117824.png"> | ![qrcode_brave com-download](https://user-images.githubusercontent.com/28145373/121905399-1dde5d80-ccf8-11eb-92d0-9cb7deb0e5ea.png) | <img width="338" alt="context menu" src="https://user-images.githubusercontent.com/28145373/121905409-1f0f8a80-ccf8-11eb-831c-b7b19f8e0099.png">

While testing I did encounter and log https://github.com/brave/brave-browser/issues/16403. This issue reproduces in Chrome though and is not unique to Brave or this branding change.
