### ISSUE TITLE
Dailymotion doesn't load 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1580] opened 2018-10-15 15:08 UTC
## Description 

Dailymotion doesn't load 

## Steps to Reproduce

   1. Clean profile on 0.55.13
   2. Visit https://dailymotion.com/
   3. Page goes into infinite load and errors our. Stopping page load causes webview crash. (Couldnt capture crash details on Linux)

## Actual result:

![screenshot from 2018-10-15 11-06-37](https://user-images.githubusercontent.com/17010094/46959586-65ede380-d06a-11e8-8e0f-e12595aaefe7.png)

## Expected result:
Should load the site correctly 

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes 
- Does it reproduce on browser-laptop?  No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No change with shields down. Page still goes into infinite loop
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Found while testing https://github.com/brave/brave-core/pull/599/

**Comment by btlechowski** [comment] 2018-10-15 15:21
Reproduced on Windows 7 x64

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Windows 7

**Comment by GeetaSarvadnya** [comment] 2018-10-15 15:22
Issue is reproducible on Windows
![image](https://user-images.githubusercontent.com/38657976/46960446-31a31300-d0bc-11e8-80ad-7da1a00fd745.png)

**Comment by LaurenWags** [comment] 2018-10-15 21:32
Reproduced on macOS 10.12.6 x64

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

**Comment by bbondy** [comment] 2019-01-20 23:56
@srirambv @LaurenWags or @btlechowski (just one), does this still reproduce?

**Comment by btlechowski** [comment] 2019-01-21 05:10
Still reproducible.

![image](https://user-images.githubusercontent.com/34715963/51453950-9668ac00-1d42-11e9-97b5-652df2259cae.png)

Reproduced on:
Release channel

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

Beta channel

Brave | 0.59.26 Chromium: 72.0.3626.64 (Official Build) beta (64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows 7

Dev channel

Brave | 0.60.15 Chromium: 72.0.3626.53 (Official Build) dev (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows 7

**Comment by Brave-Matt** [comment] 2019-01-24 20:23
This issue is ongoing, just wanted to note that if you `Allow ads/tracers` in Shields the site will load and display as intended.

**Comment by mrzealot** [comment] 2019-02-19 10:13
Just ran into this during webcompat checks, its problem is how we handle the request to sb.scorecardresearch.com/beacon.js. If we allow, it's fine. If I block it from devtools so that it's "properly" blocked, it's fine again. But the 307 to the empty data URL causes it to go into an infinite loop somehow (didn't dig that far down yet). Not sure if the 200 with empty response would be any better as it'd still think it managed to load it, realize it's bad for some reason, and retry.

**Comment by Brave-Matt** [comment] 2019-06-05 19:12
Wanted to flag this because it's still an easily reproducible issue on all Brave channels (Release channel at v0.64.77 at the time of writing this).
Several users reporting on Community:
https://community.brave.com/t/dailymotion-is-not-working-in-brave/63261/9

Very high traffic/popular site and its worth moving this up in priority/getting eyes on it sooner rather than later. cc @rebron

**Comment by ryanbr** [comment] 2019-06-06 11:34
Okay, this has required a bit of work to debug, but I believe it has to do with scorecardresearch.com.

Technically the filter /beacon.js should be blocking this. But its not. If the domain scorecardresearch.com is blocked outright it let the site render correctly. 
`
||scorecardresearch.com^$domain=dailymotion.com`

**Closed** 2019-06-06 18:14 UTC
Labels: QA/Yes, bug, feature/shields/webcompat, webcompat
