### ISSUE TITLE
Incorrect 'Monthly Payment' value shown for  'Auto Contribute'

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2207] opened 2018-11-21 09:57 UTC
## Description 
When we enable Rewards from `Brave Rewards` panel, by default `Monthly Payment` value is displayed as 5 BAT (0.00 USD). If you do a contribution, without changing the default monthly payment value, 20 BAT (montly payment) is considered for auto contribution.

If you refresh the Rewards page, you can see `Monthly Payment` value as 20 BAT under 'Auto Contribute' section.

Note : Please note this issue is arising only on staging environmnet, when you enable Rewards from `Brave Rewards` panel. If you enable Rewards from welcome page issue is not reproducible.

## Steps to Reproduce

   1. Launch brave with clean profile from CLI using `BraveSoftware/Brave-Browser/Application/brave.exe --rewards-env=stag --rewards-reconcile-interval=4`
   2. Enable rewards through Brave Rewards panel
   3. Verify `Monthly Payment` value is displayed as 5 BAT (0.00 USD)
   4. Claim the free grants and make sure Grants added to wallet
   5. Add few sites to Rewards including YT and Twitch
   6. Wait until reconcile time interval to completes ( In this case 4 mins as mentioned in step 1)
   7. After auto contribution, verify the auto contribution value
   
## Actual result:
Auto contribution value is displayed as 20 BAT which is not matching with `Monthly Payment` value which is displayed under `Auto - Contribute` section
![monthly budget value issue_0 56 14](https://user-images.githubusercontent.com/38657976/48833597-bb23c000-eda1-11e8-912b-40ad7fdeb09f.gif)

## Expected result:
Default value should be displayed correctly. `Monthly Payment` value and the amount which is considered for auto contribute should be same.

## Reproduces how often: 
Easily

## Brave version (brave://version info)

Brave | 0.56.14 Chromium: 70.0.3538.102 (Official Build) (64-bit)
-- | --
Revision | 4bbeebac88fdc09c97265e47c205868bbd190497-refs/branch-heads/3538@{#1077}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by GeetaSarvadnya** [comment] 2018-11-27 10:29
It's reproducible on Production as well `BraveBeta` - `0.57.7`

**Comment by LaurenWags** [comment] 2018-11-27 21:37
Reproduced on Prod using dev channel build below on macOS:

Brave | 0.58.10 Chromium: 71.0.3578.53 (Official Build) dev(64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X

**Comment by jasonrsadler** [comment] 2018-12-03 22:42
I’m unable to reproduce on newer builds. Can we recheck and see if this issue is still valid?

**Comment by kjozwiak** [comment] 2018-12-03 23:02
@GeetaSarvadnya mind checking to see if this is still an issue with the latest RC builds?

**Comment by LaurenWags** [comment] 2018-12-03 23:04
Could not reproduce with steps from description (at step 3 I saw 20 BAT instead of the listed 5BAT) while using this build

Brave | 0.57.12 Chromium: 71.0.3578.75 (Official Build) (64-bit)
-- | --
Revision | 06ef00b5279f93f8e0c1e73acedd49d7dcc09767-refs/branch-heads/3578@{#836}
OS | Mac OS X

![screen shot 2018-12-03 at 6 03 58 pm](https://user-images.githubusercontent.com/28145373/49407209-d38ec580-f725-11e8-9a32-e2c3a0e37499.png)

**Comment by NejcZdovc** [comment] 2018-12-04 04:39
closing as appears that it was resolved

**Closed by NejcZdovc** 2018-12-04 04:39 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards, priority/P4
