### ISSUE TITLE
`Add to Chrome` on CWS main page

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#5730] opened 2019-08-20 02:15 UTC
Follow up to https://github.com/brave/brave-browser/issues/790

## Steps to Reproduce

   1. Open `https://chrome.google.com/webstore/category/extensions`

## Actual result:

`Add to Chrome` on CWS main page
![image](https://user-images.githubusercontent.com/34715963/63312151-d7d53000-c300-11e9-8db6-fe90cc31cea1.png)

## Expected result:
`Add to Brave` on CWS main page

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.69.110 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron

**Comment by bsclifton** [comment] 2019-08-20 04:14
Functionality originally fixed with https://github.com/brave/brave-core/pull/2845

Looks like it regressed... content script has correct selector still

**Comment by bsclifton** [comment] 2019-08-20 04:19
Ah - if you refresh after going to a detail page, it then executes the content script properly (weird that a refresh is needed though)

This issue can be fixed by adding `https://chrome.google.com/webstore/category/extensions` (or a better selector) to the manifest.json here:
https://github.com/brave/brave-core/blob/05c7b6199273870ecc536798a0f223c5f2d5794d/components/brave_extension/extension/brave_extension/manifest.json#L36-L38

**Comment by LaurenWags** [comment] 2019-08-29 19:53
Reproduced originally described issue as well as issue described with https://github.com/brave/brave-browser/issues/5730#issuecomment-522846401


Brave | 0.69.119 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

**Comment by eljuno** [comment] 2019-10-04 20:43
+1 from Community https://community.brave.com/t/chrome-web-store-still-displaying-add-to-chrome/86046?u=eljuno

**Comment by kjozwiak** [comment] 2019-10-07 06:05
@rebron @bsclifton looks like this regressed again. Originally it was fixed via https://github.com/brave/brave-browser/issues/790 and checked by QA via the following verifications https://github.com/brave/brave-browser/issues/790#issuecomment-522824557.

I also checked and reproduced using `0.69.119 Chromium: 76.0.3809.132` which was originally used for verification as per https://github.com/brave/brave-browser/issues/790#issuecomment-522824557. Definitely seems like something was changed on Google's side.

CCing @brave/legacy_qa so they're aware of the issue.

**Closed** 2019-11-19 03:28 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/extensions, good first issue, priority/P3

**Comment by btlechowski** [comment] 2020-01-04 09:16
Verification passed on

Brave | 1.3.81 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4013 and from the description
Verified extensions main page and individual extension pages.

![image](https://user-images.githubusercontent.com/34715963/71763286-9d001d00-2eda-11ea-90bb-0474601f0e33.png)
![image](https://user-images.githubusercontent.com/34715963/71763288-a5585800-2eda-11ea-81d8-8d0989a54e7f.png)
![image](https://user-images.githubusercontent.com/34715963/71763299-d6d12380-2eda-11ea-8657-756fc630767f.png)
