### ISSUE TITLE
Leo not detecting active page content in foreground of active tab, when opened from sidebar. 

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#34145] opened 2023-11-07 06:10 UTC
## Description 

Leo does not always detect the active browser page in foreground in active browser tab when invoked from the sidebar. 

For example, when I go to a YouTube video, initiate playback and open Leo from the sidebar, the active page isn't linked in the prompt UI, and when I ask Leo to summarize the YT video in the active foreground, the response output mentions being unable to summarize the video. 

When I refresh the browser window, I encounter the expected behavior nearly every time. Triggering the refresh with both the browser window and Leo open at the same time appears to link the two windows properly. 

## Steps to Reproduce

   1. Navigate to any youtube video on youtube.com
   2. Begin playing the video.
   3. Open Leo from sidebar. 
   4. Observe blank, unrelated prompt.
   5. Ask Leo to summarize video; observe generic "unable to summarize the video in the youtube page" message.

## Actual result:

View from my machine when I invoke Leo while YT is playing in the foreground of the active tab alongside the sidebar; note, I have not navigated to another window away from the active tab/page at all, I have only clicked the sidebar to open Leo alongside the active view.
<img width="1198" alt="leo-invoked-with-yt-playing-in-active-view-0" src="https://github.com/brave/brave-browser/assets/8979240/1e08f48b-dba2-4a1f-8fde-06ffcd8b354b">
## Expected result:
When I refresh the active tab and window, I observe the expected behavior that I would hope to see when I initially invoke Leo from the active foreground page/tab. 
<img width="1202" alt="leo-invoked-with-yt-playing-on-refresh-1" src="https://github.com/brave/brave-browser/assets/8979240/ab50e75a-a70c-48e1-88d2-ebe4fed448a9">

## Reproduces how often: 

Nearly 100% of the time, currently, for the scenario described above. 

Potentially related: I also encounter similar unlinked behavior when I toggle between model options within Premium. 

## Brave version (brave://version info)

1.62.28 Chromium: 119.0.6045.105 (Official Build) nightly (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? tbd
- Can you reproduce this issue with the beta channel? tbd
- Can you reproduce this issue with the nightly channel? ++

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? na
- Does the issue resolve itself when disabling Brave Rewards? na
- Is the issue reproducible on the latest version of Chrome? na

## Miscellaneous Information:

I'm not sure exactly what is doable here without having a quick way of observing what's happening behind the scenes, but it seems like when Leo is invoked from the sidebar of the active tab/foreground/page, that Leo isn't detecting the metadata for the active window or hooking in the same way it does on refresh. 

I suspect that users opening from the sidebar in the active view would expect Leo to detect the linked page automatically, and that when another model is selected from the available options, that detection would take place immediately on toggle.

**Comment by mattmcalister** [comment] 2024-01-31 15:05
hoping this will be solved with https://github.com/brave/brave-browser/issues/34945

**Comment by petemill** [comment] 2024-03-21 17:11
Yes this is a duplicate of https://github.com/brave/brave-browser/issues/34945. Closing in favor of that. But I did copy your excellent STR...

**Closed by petemill** 2024-03-21 17:11 UTC
Labels: priority/P3, QA/Yes, release-notes/include, OS/Desktop, browser-ai
