### ISSUE TITLE
Intermittent crash in Confirmations due to invalid wallet

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#8535] opened 2020-03-04 22:00 UTC
We have such a crash somewhere in rewards/ads
`Stack Trace:
  RELADDR   FUNCTION                                                                          FILE:LINE
  v------>  memcpy                                                                            /cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.9/src/mem.rs:15:35
  0000000000903588  __aeabi_memcpy                                                                    /cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.9/src/arm.rs:131:0
  000000000128ea95  crypto_hash_sha512_tweet(unsigned char*, unsigned char const*, unsigned long long)  ../../brave/vendor/bat-native-tweetnacl/tweetnacl.cc:619:17`

**Comment by tmancey** [comment] 2020-04-22 12:53
@SergeyZhukovsky @jsecretan This crash occurs on macOS too, so desktop and mobile will be affected. I am investigating the root cause, as replacing tweetnacl will not resolving the underlining issue.

**Closed** 2020-04-24 13:20 UTC
Labels: bug, crash, feature/ads, priority/P1

**Comment by GeetaSarvadnya** [comment] 2020-05-08 10:03
Verification passed on

```
Brave | 1.9.60 Chromium: 81.0.4044.129 (Official Build) dev (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1803 (Build 17134.1006)
``

- Verified the test plan from https://github.com/brave/brave-core/pull/5347

```
[13068:9980:0508/152352.354:INFO:redeem_token.cc(58)] Redeem
[13068:9980:0508/152352.354:INFO:confirmations_impl.cc(740)] Saving confirmations state
[13068:9980:0508/152352.355:INFO:redeem_token.cc(108)] CreateConfirmation
[13068:9980:0508/152352.355:INFO:redeem_token.cc(110)] POST /v1/confirmation/{confirmation_id}/{credential}
[13068:9980:0508/152352.355:INFO:redeem_token.cc(113)] URL Request:
[13068:9980:0508/152352.355:INFO:redeem_token.cc(116)]   URL: https://ads-serve.bravesoftware.com/v1/confirmation/9599715d-8f63-470c-84ef-9dc435c7b863/eyJwYXlsb2FkIjoie1wiYmxpbmRlZFBheW1lbnRUb2tlblwiOlwiOXBhU2tCOXlua0ZHa1Zjc0ZrOG04OVZqL0dxbEJqc1FQbCtHeFo2MGZIVT1cIixcImJ1aWxkQ2hhbm5lbFwiOlwiZGV2XCIsXCJjcmVhdGl2ZUluc3RhbmNlSWRcIjpcImU0Y2M0OWNiLWU1ODEtNDIxZC05OWM4LTMwYTZjMmE0MWI4NVwiLFwicGF5bG9hZFwiOnt9LFwicGxhdGZvcm1cIjpcIndpbmRvd3NcIixcInR5cGVcIjpcInZpZXdcIn0iLCJzaWduYXR1cmUiOiJacDgwSENoUGtJOEpTWVcwU0tYdzVYV3NRVjZ6c2l6Y1Fod3dqWEJTYWZONlljckpCc3BtTTcwdVBuOHFETS83b0VWbERsYUMzamlMcWFHbC9XdE9oZz09IiwidCI6Imc2cTg4YkRFZ0p2WTdTQ1MzN243aEZYRHB2U09nZ3dmRnpPeEp4dnA1UDA2K3ExdEpXeGNicG90bHYxL1htOHd5c012eEdzWC93cnQrTVdjblBGeHNnPT0ifQ==
[13068:9980:0508/152352.355:INFO:redeem_token.cc(128)]   Body: {"blindedPaymentToken":"9paSkB9ynkFGkVcsFk8m89Vj/GqlBjsQPl+GxZ60fHU=","buildChannel":"dev","creativeInstanceId":"e4cc49cb-e581-421d-99c8-30a6c2a41b85","payload":{},"platform":"windows","type":"view"}
[13068:9980:0508/152352.355:INFO:redeem_token.cc(131)]   Headers:
[13068:9980:0508/152352.355:INFO:redeem_token.cc(133)]     accept: application/json
[13068:9980:0508/152352.355:INFO:redeem_token.cc(137)]   Content_type: application/json
[13068:9980:0508/152352.355:INFO:refill_tokens.cc(53)] Refill
[13068:9980:0508/152352.355:INFO:refill_tokens.cc(71)] RequestSignedTokens
[13068:9980:0508/152352.355:INFO:refill_tokens.cc(74)] No need to refill tokens as we already have 49 unblinded tokens which is above the minimum threshold of 20
[13068:9980:0508/152352.364:INFO:confirmations_impl.cc(756)] Successfully saved confirmations state
[10832:16020:0508/152352.388:INFO:client.cc(593)] Successfully saved client state
[10832:16020:0508/152352.414:INFO:client.cc(593)] Successfully saved client state
[10832:16020:0508/152352.448:INFO:client.cc(593)] Successfully saved client state
[10832:16020:0508/152352.477:INFO:client.cc(593)] Successfully saved client state
[10832:16020:0508/152352.500:INFO:ad_notifications.cc(321)] Successfully saved notifications state
[10832:16020:0508/152352.569:INFO:client.cc(593)] Successfully saved client state
[13068:9980:0508/152352.964:INFO:redeem_token.cc(154)] OnCreateConfirmation
[13068:9980:0508/152352.964:INFO:redeem_token.cc(156)] URL Request Response:
[13068:9980:0508/152352.964:INFO:redeem_token.cc(157)]   URL: https://ads-serve.bravesoftware.com/v1/confirmation/9599715d-8f63-470c-84ef-9dc435c7b863/eyJwYXlsb2FkIjoie1wiYmxpbmRlZFBheW1lbnRUb2tlblwiOlwiOXBhU2tCOXlua0ZHa1Zjc0ZrOG04OVZqL0dxbEJqc1FQbCtHeFo2MGZIVT1cIixcImJ1aWxkQ2hhbm5lbFwiOlwiZGV2XCIsXCJjcmVhdGl2ZUluc3RhbmNlSWRcIjpcImU0Y2M0OWNiLWU1ODEtNDIxZC05OWM4LTMwYTZjMmE0MWI4NVwiLFwicGF5bG9hZFwiOnt9LFwicGxhdGZvcm1cIjpcIndpbmRvd3NcIixcInR5cGVcIjpcInZpZXdcIn0iLCJzaWduYXR1cmUiOiJacDgwSENoUGtJOEpTWVcwU0tYdzVYV3NRVjZ6c2l6Y1Fod3dqWEJTYWZONlljckpCc3BtTTcwdVBuOHFETS83b0VWbERsYUMzamlMcWFHbC9XdE9oZz09IiwidCI6Imc2cTg4YkRFZ0p2WTdTQ1MzN243aEZYRHB2U09nZ3dmRnpPeEp4dnA1UDA2K3ExdEpXeGNicG90bHYxL1htOHd5c012eEdzWC93cnQrTVdjblBGeHNnPT0ifQ==
[13068:9980:0508/152352.964:INFO:redeem_token.cc(158)]   Response Status Code: 201
[13068:9980:0508/152352.964:INFO:redeem_token.cc(159)]   Response: {"id":"9599715d-8f63-470c-84ef-9dc435c7b863","payload":{},"createdAt":"2020-05-08T09:54:01.879Z","type":"view","modifiedAt":"2020-05-08T09:54:01.879Z","creativeInstanceId":"e4cc49cb-e581-421d-99c8-30a6c2a41b85"}
[13068:9980:0508/152352.964:INFO:redeem_token.cc(160)]   Headers:
[13068:9980:0508/152352.964:INFO:redeem_token.cc(162)]     accept-ranges: bytes
[13068:9980:0508/152352.964:INFO:redeem_token.cc(162)]     access-control-allow-origin: *
[13068:9980:0508/152352.964:INFO:redeem_token.cc(162)]     content-length: 211
[13068:9980:0508/152352.964:INFO:redeem_token.cc(162)]     content-type: application/json; charset=utf-8
[13068:9980:0508/152352.964:INFO:redeem_token.cc(162)]     date: Fri, 08 May 2020 09:54:02 GMT
[13068:9980:0508/152352.964:INFO:redeem_token.cc(162)]     status: 201
[13068:9980:0508/152352.964:INFO:redeem_token.cc(162)]     via: 1.1 varnish
[13068:9980:0508/152352.964:INFO:redeem_token.cc(162)]     x-cache: MISS
[13068:9980:0508/152352.964:INFO:redeem_token.cc(162)]     x-cache-hits: 0
[13068:9980:0508/152352.964:INFO:redeem_token.cc(162)]     x-served-by: cache-sea4478-SEA
[13068:9980:0508/152352.964:INFO:redeem_token.cc(182)] FetchPaymentToken
[13068:9980:0508/152352.964:INFO:redeem_token.cc(184)] GET /v1/confirmation/{confirmation_id}/paymentToken
[13068:9980:0508/152352.964:INFO:redeem_token.cc(187)] URL Request:
[13068:9980:0508/152352.964:INFO:redeem_token.cc(190)]   URL: https://ads-serve.bravesoftware.com/v1/confirmation/9599715d-8f63-470c-84ef-9dc435c7b863/paymentToken
[13068:9980:0508/152353.299:INFO:redeem_token.cc(206)] OnFetchPaymentToken
[13068:9980:0508/152353.299:INFO:redeem_token.cc(208)] URL Request Response:
[13068:9980:0508/152353.299:INFO:redeem_token.cc(209)]   URL: https://ads-serve.bravesoftware.com/v1/confirmation/9599715d-8f63-470c-84ef-9dc435c7b863/paymentToken
[13068:9980:0508/152353.299:INFO:redeem_token.cc(210)]   Response Status Code: 200
[13068:9980:0508/152353.299:INFO:redeem_token.cc(211)]   Response: {"id":"9599715d-8f63-470c-84ef-9dc435c7b863","createdAt":"2020-05-08T09:54:01.879Z","type":"view","modifiedAt":"2020-05-08T09:54:01.899Z","creativeInstanceId":"e4cc49cb-e581-421d-99c8-30a6c2a41b85","paymentToken":{"publicKey":"bPE1QE65mkIgytffeu7STOfly+x10BXCGuk5pVlOHQU=","batchProof":"MWz9jJyoTPxFk4+NrjvWi8XC2wF3D+apBoWtXKfz1wJErQrOw5+PMqZYiTpL3gTcvUU+n9ZawaKAbaEgH7XACg==","signedTokens":["3AQ71KidERXqoWou5e4z/EZg0zVkhbTf2PtOyJrD2io="]}}
[13068:9980:0508/152353.299:INFO:redeem_token.cc(212)]   Headers:
[13068:9980:0508/152353.299:INFO:redeem_token.cc(214)]     accept-ranges: bytes
[13068:9980:0508/152353.299:INFO:redeem_token.cc(214)]     access-control-allow-origin: *
[13068:9980:0508/152353.299:INFO:redeem_token.cc(214)]     content-length: 442
[13068:9980:0508/152353.299:INFO:redeem_token.cc(214)]     content-type: application/json; charset=utf-8
[13068:9980:0508/152353.299:INFO:redeem_token.cc(214)]     date: Fri, 08 May 2020 09:54:02 GMT
[13068:9980:0508/152353.299:INFO:redeem_token.cc(214)]     status: 200
[13068:9980:0508/152353.299:INFO:redeem_token.cc(214)]     via: 1.1 varnish
[13068:9980:0508/152353.299:INFO:redeem_token.cc(214)]     x-cache: MISS
[13068:9980:0508/152353.299:INFO:redeem_token.cc(214)]     x-cache-hits: 0
[13068:9980:0508/152353.299:INFO:redeem_token.cc(214)]     x-served-by: cache-sea4478-SEA
[13068:9980:0508/152353.299:INFO:confirmations_impl.cc(740)] Saving confirmations state
[13068:9980:0508/152353.300:INFO:redeem_token.cc(395)] Added 1 unblinded payment token with an estimated redemption value of 0.05 BAT, you now have 1 unblinded payment tokens
[13068:9980:0508/152353.300:INFO:confirmations_impl.cc(740)] Saving confirmations state
[13068:9980:0508/152353.300:INFO:redeem_token.cc(423)] Successfully redeemed 9599715d-8f63-470c-84ef-9dc435c7b863 confirmation id with e4cc49cb-e581-421d-99c8-30a6c2a41b85 creative instance id for view
```
