### ISSUE TITLE
unable open Developer-Console since V1.22.66 (Mar 23, 2021)

### ISSUE THREAD

**Issue by JProof** [brave/brave-browser#14896] opened 2021-03-23 16:22 UTC
## Description 
Update to latest  V1.22.66 (Mar 23, 2021) on Ubuntu 20.04.2 LTS
 
try to open the developer-tools does not work

## Steps to Reproduce
Step1:
Right Mouse-Click on Webseite "Untersuchen"
...does not open the developer-tools

Step2:
By using Keyboard
ctrl+shift+i
does not open the developer-tools

## Actual result:
Does not open the developer tools

## Reproduces how often: 
everytime

## Brave version (brave://version info)

Brave | 1.22.66 Chromium: 89.0.4389.90 (Offizieller Build) (64-Bit)

Überarbeitung | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
Betriebssystem | Linux
JavaScript | V8 8.9.255.20

**Comment by lclutz** [comment] 2021-03-23 16:55
Having a similar issue on Windows 10 with the same version. The developer tools will eventually open but it takes a long time. Disabeling all extensions did not resolve the issue. I even rebooted my machine.

I could not reproduce the issue on my Manjaro box tho.

## Brave version

Brave | 1.22.66 Chromium: 89.0.4389.90 (Offizieller Build) (64-Bit)

Überarbeitung | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
Betriebssystem | Windows 10 OS Version 2009 (Build 19042.870)
JavaScript | V8 8.9.255.20

**Comment by aidan-walden** [comment] 2021-03-23 20:18
Same issue as @lclutz on Windows 10. Only experiencing it with 10+ tabs open at the same time.

Brave version
Brave | 1.24.14 Chromium: 89.0.4389.90 (Official Build) nightly (64-bit)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | Windows 10 OS Version 2009 (Build 19042.867)
JavaScript | V8 8.9.255.20

**Comment by JProof** [comment] 2021-03-24 11:19
Solved with Update to Version 1.22.67 Chromium: 89.0.4389.90 (Offizieller Build) (64-Bit)

thank you!

**Comment by tinchoz49** [comment] 2021-03-24 13:03
Same issue on Fedora 33

Version 1.23.48 Chromium: 89.0.4389.90 (Official Build) beta (64-bit)

**Comment by lclutz** [comment] 2021-03-24 17:08
Yes, can confirm. 1.22.67 fixed it for me as well.

**Comment by bsclifton** [comment] 2021-03-24 23:20
Partial fix deployed - we'll have another coming soon! This is ultimately a duplicate of https://github.com/brave/brave-browser/issues/14880 and https://github.com/brave/brave-browser/issues/14721

**Closed by bsclifton** 2021-03-24 23:20 UTC
Labels: OS/Desktop
