### ISSUE TITLE
replace MM with Brave under "Congratulations" modal during seed phrase backup

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6274] opened 2019-10-02 05:27 UTC
## Description 

We should replace `MetaMask cannot recover your seedphrase` with `Brave cannot recover your seedphrase` under the `Congratulations` modal after backing up the seedphrase.

## Steps to Reproduce

   1. launch brave and create a crypto wallet under `brave://wallet`
   2. backup your seed phrase following the steps

## Actual result:

<img width="998" alt="Screen Shot 2019-10-02 at 12 09 42 AM" src="https://user-images.githubusercontent.com/2602313/66019842-f3605880-e4b2-11e9-8844-9a6a07fb1560.png">

## Expected result:

Should specify the following:

```
Brave cannot recover your seedphrase . Learn more.
```

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` (not released yet)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @ryanml @bbondy @rebron @tomlowenthal @brave/legacy_qa

**Comment by srirambv** [comment] 2019-10-02 13:04
Dupe of https://github.com/brave/brave-browser/issues/6100

**Closed by srirambv** 2019-10-02 13:04 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/crypto-wallets
