### ISSUE TITLE
Window blurs in segments

### ISSUE THREAD

**Issue by shawnc722** [brave/brave-browser#2478] opened 2018-12-12 00:56 UTC
## Description 

After leaving Brave open for a while, portions of the window (or even the whole window) will sometimes be blurred. Moving the mouse over the affected portions will typically get rid of the blur, but within a few minutes it will be back. The level of blurriness changes as well - although it's nearly always worse on my second monitor, so it may just be the monitor or the resolution.

## Steps to Reproduce

   1. Open Brave
   2. Wait a minute or two

## Actual result:

Pasting screenshots doesn't seem to work in .png or .jpg format, but if you imagine seeing the window through an unfocused camera lens then you get the idea.

## Expected result:
No blur

## Reproduces how often: 

Every time Brave is open

## Brave version (brave://version info)

Brave | 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Haven't used the dev builds

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

This happens on both my 4K monitor running off a GTX1080 and my 1080p monitor running off intel HD 530 graphics, but is usually worse on the 1080p monitor. Since it happens with two different graphics adapters on two different resolutions, and has persisted after reinstalling Brave, it seems to be a browser issue. Also, no other program (including chrome, edge, and firefox) has this issue.

**Comment by bsclifton** [comment] 2020-09-14 04:54
Closing as duplicate of https://github.com/brave/brave-browser/issues/3259

**Closed by bsclifton** 2020-09-14 04:54 UTC
Labels: OS/Desktop
