### ISSUE TITLE
Brave Text & Graphics not Rendering Properly

### ISSUE THREAD

**Issue by InklingGirl** [brave/brave-browser#30185] opened 2023-05-07 14:51 UTC
## Description 

Randomly, after waking my PC from sleep, most text & other graphics started to not render, & now the vast majority don't render anymore, which makes navigating settings an ordeal to say the least.

## Steps to Reproduce

   1. Use Brave
   2. Put PC to sleep (Brave may have updated?)
   3. Text & graphics no longer render

## Actual result:

Text & graphics no longer render.

Here's a look at `brave://settings/`:

![2023-05-08_00-53](https://user-images.githubusercontent.com/9910447/236685454-90d613c6-4dac-4241-a40d-f59e6770dee6.png)

## Expected result:

Text & graphics to render.

## Reproduces how often: 

Every time browser is opened, even after a PC restart.

## Brave version (brave://version info)

**Brave:** 1.51.110 Chromium: 113.0.5672.77 (Official Build) (64-bit)
**Revision:** c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
**OS:** Linux [AMD64 Ubuntu 22.04.2 LTS (Jammy Jellyfish), w/ its default desktop environment as GNOME 42.5 & default window server as Wayland]

## Version/Channel Information:

Acquired from the Brave's official Debian GNU/Linux repo.

## Other Additional Information:

The issue resolves itself when disabling hardware acceleration, but I would really rather not shoot my CPU usage up when hardware acceleration has always worked for me until now.

## Miscellaneous Information:

N/A

**Comment by r4f4ss** [comment] 2023-05-07 15:55
Same here

**Comment by mariuslapagna** [comment] 2023-05-08 10:04
Same here! Fedora 38 latest updates as OS.

**Comment by PhillipDyer** [comment] 2023-05-10 04:12
Same issue. Fedora 38.

**Comment by r4f4ss** [comment] 2023-05-10 17:23
Seems to be solved here after the latest upgrade from Brave's official Debian GNU/Linux repo.

**Comment by InklingGirl** [comment] 2023-05-10 17:58
Likewise @r4f4ss as of:
**Brave:** 1.51.114 Chromium: 113.0.5672.92 (Official Build) (64-bit)
I can now turn on hardware acceleration again & all text/graphics render correctly now.

I'll leave the thread up to see if it's fixed for others &/or until a developer responds, though.

**Comment by rebron** [comment] 2023-05-10 23:04
Dupe of https://github.com/brave/brave-browser/issues/30180

**Closed by rebron** 2023-05-10 23:04 UTC
Labels: OS/Linux, workaround/disable-hw-acceleration, OS/Desktop

**Comment by InklingGirl** [comment] 2023-05-25 15:10
This issue has manifested again.

**Comment by MCC-CCM** [comment] 2024-01-22 21:08
This just started happening to me after shutting down the computer for the weekend. I have not found a single site that loads correctly.

I'm using a Dell XPS 15 9500 Laptop on Windows 10 Pro x64 with Nvidia GeForce GTX1650Ti.

Deleting the GPU cache folder did not help, and I'd prefer not to use a Beta build.... any more suggestions?
![image](https://github.com/brave/brave-browser/assets/157422016/6f1586d4-ca12-4832-94f0-e13b539d1d3f)
