### ISSUE TITLE
Slow to start

### ISSUE THREAD

**Issue by Xenios91** [brave/brave-browser#620] opened 2018-07-21 20:47 UTC
## Description 
For Mint 18.3, Brave is incredibly slow to start.

## Steps to Reproduce
Opening Brave for the first time since system boot.

## Reproduces how often: 
Every time the browser is open for the first time since system boot.

## Brave version (about:brave info) 

Name | Version
-- | --
Brave | 0.23.39
V8 | 6.7.288.46
rev | 3ee14b0
Muon | 7.1.6
OS Release | 4.15.0-29-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.103

**Comment by srirambv** [comment] 2018-07-21 21:14
Dupe of https://github.com/brave/browser-laptop/issues/3025. Please use https://github.com/brave/browser-laptop/issues/ for browser-laptop related issues.

**Closed by srirambv** 2018-07-21 21:14 UTC
