### ISSUE TITLE
Fix network audit in CI pipeline for macOS on `development` channel

### ISSUE THREAD

**Issue by mihaiplesa** [brave/brave-browser#5886] opened 2019-09-04 08:20 UTC
The following is happening when passing `development` as a channel to the CI pipeline. `nightly`, `dev`, `beta` and `release `work as expected.

```
12:18:31  + npm run network-audit -- '--output_path=src/out/Release/Brave\ Browser\ Development.app/Contents/MacOS/Brave\ Browser\ Development'
12:18:31  
12:18:31  > brave@0.71.63 network-audit /Users/jenkins/jenkins/workspace/tching_popular_sites_from_google
12:18:31  > node ./scripts/commands.js start --enable_brave_update --network_log --user_data_dir_name=brave-network-test "--output_path=src/out/Release/Brave\ Browser\ Development.app/Contents/MacOS/Brave\ Browser\ Development"
12:18:31  
12:18:31  Network audit started. Logging requests for the next 2min or until you quit Brave...
12:18:31  undefined: src/out/Release/Brave\ Browser\ Development.app/Contents/MacOS/Brave\ Browser\ Development --enable-logging --v=0 --enable_brave_update --network_log --user_data_dir_name=brave-network-test --output_path=src/out/Release/Brave\ Browser\ Development.app/Contents/MacOS/Brave\ Browser\ Development --user-data-dir=/Users/jenkins/Library/Application\ Support/BraveSoftware/brave-network-test --log-net-log=/Users/jenkins/jenkins/workspace/tching_popular_sites_from_google/network_log.json --net-log-capture-mode=IncludeSocketBytes
12:18:31  /bin/sh: src/out/Release/Brave Browser Development.app/Contents/MacOS/Brave Browser Development: No such file or directory
12:18:31  fs.js:126
12:18:31      throw err;
12:18:31      ^
12:18:31  
12:18:31  Error: ENOENT: no such file or directory, open '/Users/jenkins/jenkins/workspace/tching_popular_sites_from_google/network_log.json'
12:18:31      at Object.openSync (fs.js:447:3)
12:18:31      at Object.readFileSync (fs.js:349:35)
12:18:31      at start (/Users/jenkins/jenkins/workspace/tching_popular_sites_from_google/lib/start.js:138:26)
12:18:31      at Command.listener (/Users/jenkins/jenkins/workspace/tching_popular_sites_from_google/node_modules/commander/index.js:315:8)
12:18:31      at Command.emit (events.js:200:13)
12:18:31      at Command.parseArgs (/Users/jenkins/jenkins/workspace/tching_popular_sites_from_google/node_modules/commander/index.js:654:12)
12:18:31      at Command.parse (/Users/jenkins/jenkins/workspace/tching_popular_sites_from_google/node_modules/commander/index.js:474:21)
12:18:31      at Object.<anonymous> (/Users/jenkins/jenkins/workspace/tching_popular_sites_from_google/scripts/commands.js:155:4)
12:18:31      at Module._compile (internal/modules/cjs/loader.js:774:30)
12:18:31      at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10) {
12:18:31    errno: -2,
12:18:31    syscall: 'open',
12:18:31    code: 'ENOENT',
12:18:31    path: '/Users/jenkins/jenkins/workspace/tching_popular_sites_from_google/network_log.json'
12:18:31  }
12:18:31  npm ERR! code ELIFECYCLE
12:18:31  npm ERR! errno 1
12:18:31  npm ERR! brave@0.71.63 network-audit: `node ./scripts/commands.js start --enable_brave_update --network_log --user_data_dir_name=brave-network-test "--output_path=src/out/Release/Brave\ Browser\ Development.app/Contents/MacOS/Brave\ Browser\ Development"`
12:18:31  npm ERR! Exit status 1
12:18:31  npm ERR! 
12:18:31  npm ERR! Failed at the brave@0.71.63 network-audit script.
12:18:31  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
12:18:31  
12:18:31  npm ERR! A complete log of this run can be found in:
12:18:31  npm ERR!     /Users/jenkins/.npm/_logs/2019-09-03T11_18_30_431Z-debug.log
```

**Comment by bsclifton** [comment] 2020-02-03 18:14
I believe this is a duplicate of https://github.com/brave/brave-browser/issues/7207 - we'd want to solve that and then this should be good to go. I suspect the log isn't written because output buffer is not flushed (for writing the file) as process is killed unexpectedly

**Closed by bsclifton** 2020-02-03 18:14 UTC
Labels: dev-concern
