### ISSUE TITLE
Browser history not work well sometimes

### ISSUE THREAD

**Issue by egg734631** [brave/brave-browser#4294] opened 2019-05-03 05:09 UTC
## Description 

The problem happened  when I testing the browser history api.

My test is open website with specify URL params, 
and check if the userToken is empty, then direct back to GameHall.
else, pushState( null, null, url.origin) to clean the URL params.
and add popstate event to check if the user click the back button,
he will direct back to GameHall.

Generally, it's work fine. 
But there's sometimes not work correctly 
when I click back and forward button multiple times
but it's work well in Chrome.

## Brave version (brave://version info)

Version 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)

**Comment by rebron** [comment] 2019-05-10 15:50
@egg734631 Can you submit some sample code to reproduce this?

**Comment by bsclifton** [comment] 2019-05-20 20:02
Since there isn't anything actionable- I'm going to close this issue. But please do re-open and share more information if you have it. 

Would be great if you had an example (ex: something on jsbin.com or your personal site) that can reproduce for everybody

**Closed by bsclifton** 2019-05-20 20:02 UTC
