### ISSUE TITLE
[Android 14] Brave is crashing and phone is freezing when opening "Help & feedback" from any settings page

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#30101] opened 2023-05-03 03:35 UTC
## Description 

Brave is crashing and phone is freezing when opening "Help & feedback" from any settings page

## Steps to reproduce 

   1. Launch Brave > Hamburger Menu > Settings
   2. Open `Brave Shields & privacy` > Three dot Menu in top right corner > Tap > Help & feedback > Observe app crash and phone freeze
   3.  Open `Password manager`, `Payment methods` or `Addresses and more` > Tap `?` > Observe app crash and phone freeze

## Actual result 

When trying to open `Help & feedback` from any settings page like `Brave Shields & privacy`, `Password manager`, `Payment methods` or `Addresses and more`, Brave is crashing and the phone is freezing. It's happening only on Pixel 6 and Pixel 7 with Android 14 and not reproducible on Pixel 6 and Galaxy Tab8 with Android 13.

https://user-images.githubusercontent.com/128532965/235827697-d94b17dc-155a-4331-a210-ef80b65a0c8c.mp4

## Expected result

App must not crash when opening `Help & feedback`

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 6 / Pixel 7 [phone]
   - Android version: Android 14 [UPB1.230309.017 release-keys]
   
## Brave version

1.51.109 Chromium: 113.0.5672.63 (Official Build) (64-bit)

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by deeppandya** [comment] 2023-05-03 18:15
@vlad-hoff i was able to reproduce it on my device.

**Comment by deeppandya** [comment] 2023-06-15 21:54
This issue seems to be resolved on android 14.

**Comment by deeppandya** [comment] 2023-06-16 21:52
Closing this issue as resolved.

**Closed by deeppandya** 2023-06-16 21:52 UTC
Labels: bug, OS/Android, QA Pass - Android ARM
