### ISSUE TITLE
VPN button in Android app MENU position - User Experience

### ISSUE THREAD

**Issue by adripo** [brave/brave-browser#23166] opened 2022-05-31 19:44 UTC
### Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you have the same issue.

VPN button is at the top of the menu, but it shouldn't. The Chromium standard has accustomed that the first and second element in the menu are **'New tab'** and 'New Private tab'. Now the first element is **'Brave VPN'**.

The shortcut used to open a new tab by keeping pressed the menu icon and swiping to the element that need to be tapped conflicts with the choice of putting VPN as the first element. I have a **muscle memory** to do this action and every time I need to open a new tab, I enable VPN instead. 

**In my opinion this ruin the entire user experience.**

As an alternative the VPN button can be moved under the New tabs section

## Steps to reproduce 

   1. Update android app to v1.39.115 from Play Store.
   2. Open app.
   3. Press menu dots.

## Actual result 
![image](https://user-images.githubusercontent.com/26493496/171269477-f10c39cc-2e15-4321-8a84-ade7aac83f51.png)

## Expected result
![image](https://user-images.githubusercontent.com/26493496/171270385-bbbe4e40-7e2f-40e5-927d-83594ee07834.png)

## Issue reproduces how often 

With latest Play Store version v1.39.115

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? N/D
- Can you reproduce this issue with the current Play Store Nightly version? N/D

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Android
   - Android version: 11
   
## Brave version

v1.39.115

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/D
- Does the issue resolve itself when disabling Brave Rewards? N/D
- Is the issue reproducible on the latest version of Chrome? N/D

**Comment by BlackRabbit22** [comment] 2022-06-01 17:19
I second this. I do not want to use Braves VPN service.

Why did the team thin kit is a good idea to have it on top of the New tab and New Private tab buttons? This is an awful UX design. 

I suggest allowing users to disable menu items like Brave VPN, Wallet, Brave Rewards, and Brave News.

**Comment by m77e4t** [comment] 2022-06-01 17:29
You can disable menu items by directly disabling the feature via brave://flags.

Eg., Brave News via 'Enable Brave News' and turn it to 'Disabled'. 
It will completely remove brave news from the browser including the three dotted menu items. (No idea if it will some stuff on ur browser by future release)

Having an option to disable menu items or those that are in the settings page at-front easily, quickly available to the user may not be good as brave needs to make money from their features. (From brave software company standpoint)
Every company wants their premium feature available easily to the user and accessible to them quickly from the menu items even if some group of users do not want said features.

**Comment by forgetso** [comment] 2022-06-07 18:38
Share the sentiment in this thread. Absolutely appalling UX decision and will also need to change browser if it remains this way.

**Comment by bsclifton** [comment] 2022-06-07 19:21
Thanks for the report folks - we've addressed this (fixed in in Nightly; we're uplifting to release channel)

I'll close this out as a duplicate of https://github.com/brave/brave-browser/issues/23240

**Closed by bsclifton** 2022-06-07 19:21 UTC
Labels: feature/settings, OS/Android, feature/vpn
