### ISSUE TITLE
Https iframe fails to load in Brave!

### ISSUE THREAD

**Issue by BaseMax** [brave/brave-browser#5861] opened 2019-09-02 14:26 UTC
Hello,

## Description 

https://github.com/brave/browser-laptop/issues/13392

## Steps to Reproduce

https://github.com/prasathmani/tinyfilemanager/issues/216
https://github.com/MattyIce/bottracker/issues/31

### What's my user agent?

https://www.whatsmyua.info/
http://whatsmyuseragent.org/

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
```

### Version

**Brave is up to date.**
Version 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)

Best Regards,
Max Base

**Comment by rebron** [comment] 2019-09-06 15:34
https://github.com/brave/browser-laptop/issues/13392#issuecomment-425788256
Closing. @BaseMax I can't reproduce this either. 

Please use the issue template and provide more detailed steps to reproduce so we can know what we're looking for.

**Closed by rebron** 2019-09-06 15:34 UTC
