### ISSUE TITLE
iPadOS Full screen video issue with Youtube

### ISSUE THREAD

**Issue by Ehtisham95** [brave/brave-browser#35682] opened 2024-01-30 04:16 UTC
## Description: 
When a video is played in **fullscreen** on youtube and the screen is locked and then unlocked, the video plays in the background but the video cannot be viewed, meaning that the video is neither playing in PiP mode or in fullscreen (which it actually should) nor in the original box of the video.

## Steps to Reproduce 
  1. Open a Youtube Video and press the **fullscreen** button on the video.
  2. Lock the iPad and unlock it. 

## Expected result:
It should display the video in Full Screen after the screen is unlocked.

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily Produced. It happens every time.

## Brave Version: 
Version 1.61.1 (24.1.4.20)

- Can you reproduce this issue with the most recent build from TestFlight? 
No. I haven't built it from the source. I downloaded it from the Brave website.
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
No. I haven't built it from the source. I downloaded it from the Brave website. 
- Can you reproduce this issue with the current build from AppStore? 
I believe yes but I have downloaded it from the Brave official website.
### Device details: 
iPad Pro 11 inch (3rd Generation) - iPadOS 17.3 (21D50)

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
No disabling Brave shields does not resolve this issue. 
- Is the issue reproducible on the latest version of Mobile Safari?
Mobile Safari doesn't have this issue.

### Additional Information
This happens if the background play is ON or OFF.

**Comment by iccub** [comment] 2024-02-21 14:17
Duplicate of https://github.com/brave/brave-browser/issues/36064
We fixed it yesterday btw

**Closed by iccub** 2024-02-21 14:17 UTC
Labels: OS/iOS
