### ISSUE TITLE
Downloading a crx file fails with CRX_REQUIRED_PROOF_MISSING on v1.40

### ISSUE THREAD

**Issue by pitsi** [brave/brave-browser#23680] opened 2022-06-24 17:38 UTC
## Description 
There are a couple of extensions that I use and are not in the chrome store, for unknown reasons. So, I download them and I install them manually with the procedure described below. But on v1.40, brave fails to even start the download and pops the error described in the title.

## Steps to Reproduce

   1. Find an extension that is packed as a crx file, e.g. the one for libredirect
   2. Make sure "Ask where to save each file before downloading" (under brave://settings/downloads) is disabled.
   3. Try downloading by clicking on it and notice the message on the screenshot below. Downloading it via right click > "save link as" will not produce the same behavior.

## Actual result:
This error comes up and the file is either not downloaded at all or deleted instantly after download. Downloading it from firefox or with wget has no issues.
 
![2022-06-24-202210_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/175611785-89985afb-9a45-4485-902b-2bf3f3435bb7.png)

## Expected result:
The file should download with no issues and I would install it manually (= go to brave://extensions > enable developer mode > drag n drop the file in the extensions window).

## Reproduces how often: 
Easily.

## Brave version (brave://version info)
```
Brave	1.40.105 Chromium: 103.0.5060.53 (Official Build) (64-bit) 
Revision	a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS	Linux
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Probably
- Can you reproduce this issue with the nightly channel? Probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

## Miscellaneous Information:
There is another similar issue (#5524) from ~3 years ago, but that one has to do with installing while this one has to do with downloading.
The fact that it also happens on chromium 103 makes me believe that some built in security policy is blocking it. It did not happen on chromium 102 or brave 1.39 (or any other previous version).

**Comment by fmarier** [comment] 2022-07-05 23:08
I did the following on Ubuntu 20.04 (X11 with i3) and it worked fine for me:

1. Download the CRX file on <https://github.com/libredirect/libredirect/releases/tag/v2.2.1>.
2. In a fresh Brave release profile, go to `brave://extensions`.
3. Turn on developer mode.
4. Drag and drop the downloaded CRX file from my download folder in Nautilus.
![Screenshot from 2022-07-05 16-03-11](https://user-images.githubusercontent.com/167821/177431338-ee29a458-14ff-44bd-9705-76d88e5f5518.png)
![Screenshot from 2022-07-05 16-03-55](https://user-images.githubusercontent.com/167821/177431341-22708c8e-51f8-4b3e-bbda-747b13c5b90f.png)
![Screenshot from 2022-07-05 16-04-03](https://user-images.githubusercontent.com/167821/177431342-1f926226-3921-4d8e-86cd-498890468aa6.png)

Are you using Nautilus? Maybe it has something to do with the source of the drag n' drop.

**Comment by pitsi** [comment] 2022-07-06 03:56
Steps 2 to 5 are irrelevant to the behavior I describe, because the issue happens on step 1 only.
So, about that step. Did you right click > save as or did you just click the file and let the browser do the download? The first, as I just checked, will download the file, but the second one brings the forementioned behavior.

I use pcmanfm as my file manager.

**Comment by fmarier** [comment] 2022-07-06 04:23
> Did you right click > save as or did you just click the file and let the browser do the download?

I just clicked the link and the save as dialog popped up automatically.

**Comment by pitsi** [comment] 2022-07-06 04:32
Is there a "save as" dialog in chromium based browsers? Maybe you have enabled the "ask where to save files when downloading" in brave://settings/downloads.

**Comment by fmarier** [comment] 2022-07-06 17:40
You're right, I had that option enabled and without it I can reproduce the problem you described.

Prior to 1.40 it was downloading the CRX file instead of trying to install it?

**Comment by pitsi** [comment] 2022-07-06 19:03
Yes. It is not trying to install it, because the installation was and is (and will always be) manual.
It is not downloading it or deletes it once it finishes downloading.

**Comment by pitsi** [comment] 2022-09-28 11:38
Three months and four major updates later (for both brave and chromium) and the issue is still there.
Can we finally say this is an upstream "feature" of chromium since v103 and call it a day?
I really have no problem using the workaround that was described above.

**Comment by fmarier** [comment] 2022-10-14 22:19
You're right, it's an upstream issue and we would likely want to see it fixed there instead of carrying an extra patch.

**Comment by pitsi** [comment] 2022-10-15 03:59
Has anyone filed an issue report for it upstream?

**Comment by Oppen** [comment] 2023-01-25 11:55
It works properly on Ungoogled Chromium. Does it carry a patch for this? Otherwise, it doesn't look like an upstream issue.

**Comment by pitsi** [comment] 2023-01-25 16:10
Did someone reply on this and deleted his message? I got a notification, but there was nothing here when I checked.

**Comment by Oppen** [comment] 2023-01-25 16:59
Yes, I commented but then I realized what I said was incorrect and didn't want to bother.

**Comment by pitsi** [comment] 2023-01-26 04:52
Ok no worries :)
I thought someone found another workaroud to the issue and I wanted to check it out.
As it seems, this is now a "feature" of chromium and it won't be fixed in the future.

**Comment by dpthegrey** [comment] 2023-02-22 01:56
I have same problem, `CRX_REQUIRED_PROOF_MISSING` error on clicking a link which contains the download file for .crx extension. I can see this is not occuring on Linux.

OS: macOS(Apple Macbook Pro)
Version: 1.50.53 Chromium: 110.0.5481.104 (Official Build) nightly (x86_64) 

Also, cannot enable an extension after dragging and dropping even when developer mode is turned on. 
The Extension shows error `This extension is not listed in the Brave Web Store and may have been added without your knowledge.` Since Chrome is now not allowing to install extensions which are outside of Chrome web store, I think there is a need to fix this and may no longer be an upstream issue.

![image](https://user-images.githubusercontent.com/49444980/220500279-0f5fcfbb-c2e2-4ea1-854d-445e7ca0ae98.png)


I wrote a reddit post about it on [r/brave_browser](https://www.reddit.com/r/brave_browser/comments/118b1cj/this_extension_is_not_listed_in_the_brave_web/)

**Comment by fmarier** [comment] 2023-02-22 03:59
@dpthegrey It might be better to file a separate issue for the behavior you are seeing.

The present issue is around the inability to download a CRX file unless one enables the setting mentioned in https://github.com/brave/brave-browser/issues/23680#issuecomment-1175769545. It sounds like the problem you have is that you already have the CRX file, but you cannot side-load it.

**Comment by dpthegrey** [comment] 2023-02-22 04:11
@fmarier my apologies for mixing up side-loading issue along with failing to download CRX file with an error `CRX_REQUIRED_PROOF_MISSING` browser error.

I can confirm about not being able to download CRX file through a link containing CRX file directly, without `Save Link As...` option on right click over the link.

**Comment by pitsi** [comment] 2023-11-02 15:51
It has been more than one year and exactly 20 releases of brave (counting today's 1.60.x) since this and as it seems nothing is going to change. Can we close this and call it a day?

**Comment by fmarier** [comment] 2023-11-02 17:31
> Can we call it a feature of chromium, close this and call it a day?

Given that there is a work-around and that it's not looking like that behavior will change in Chromium, I think we can close it.

**Closed by fmarier** 2023-11-02 17:31 UTC
Labels: feature/extensions, priority/P5, Chromium/waiting upstream, OS/Desktop
