### ISSUE TITLE
Run browser in Tor mode by default

### ISSUE THREAD

**Issue by ignishub** [brave/brave-browser#5639] opened 2019-08-13 04:10 UTC
Can i do it? Or can we make this happen?

It is really important for privacy

**Comment by bsclifton** [comment] 2019-08-13 05:21
Thanks for the request, @ignishub! This is a duplicate of https://github.com/brave/brave-browser/issues/1457

I'll give that a bump on your behalf

**Closed by bsclifton** 2019-08-13 05:21 UTC
