### ISSUE TITLE
Disable autoplay notification slide

### ISSUE THREAD

**Issue by MariuzM** [brave/brave-browser#3975] opened 2019-04-02 19:52 UTC
## Description 

When visiting a site autoplay notification that slides from right to left kicks in. 

## Steps to Reproduce

Visit any site with autoplay

## Expected result:
Can this be disabled because it's really distracting. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by eljuno** [comment] 2019-04-02 20:16
Duplicate of #3751

**Closed** 2019-04-02 20:45 UTC
Labels: closed/not-actionable
