### ISSUE TITLE
Unable to trigger `view` events for some Brave News/inline ads after browser restart

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#32877] opened 2023-09-08 18:47 UTC
When NTP is last opened tab and browser is restarted, then some `view` events won't be triggered when viewing an ad

## Steps to Reproduce

1. Clean install
2. Enable `brave://flags/#brave-ads-should-always-run-brave-ads-service`
3. Enable staging env for rewards
4. Enable Rewards and make sure you got the tokens
5. Enable Brave News
6. Make sure Brave News tab is the last opened tab
7. Restart Brave
8. `View` few ads

## Actual result:

`view` event is not triggered for some ads

Ads are served and placed in the feed next to each other:
Two inline ads served at the same time:
```
19:19:07.718  V  [VERBOSE1:eligible_inline_content_ads_v2.cc(129)] 2 eligible ads out of 2 ads
19:19:07.718  V  [VERBOSE1:inline_content_ad_handler.cc(113)] Opportunity arose to serve an inline content ad
19:19:07.719  V  [VERBOSE1:inline_content_ad_serving.cc(96)] Found 1 eligible ads
19:19:07.719  V  [VERBOSE1:inline_content_ad_serving.cc(113)] Served inline content ad
19:19:07.719  V  [VERBOSE1:inline_content_ad_handler.cc(130)] Served inline content ad:
                   placementId: 52e4cda9-dd47-42fc-82ba-2b8f4baa0e61
                   creativeInstanceId: cbe9f40d-257f-429c-939c-39f3d05a0372
                   creativeSetId: 59ae2407-51ae-48f6-9d67-6ae234319181
                   campaignId: 07de7f05-ab32-4af0-a350-a1bce4427eac
                   advertiserId: 93130af3-2def-4ecb-b836-b3772e73b3c9
                   segment: untargeted
                   title: Staging - Inline Test 2
                   description: Fung Brave News Inline Display Ad - ios/android
                   imageUrl: https://pcdn.brave.com/brave-ads/468beb93-2458-5d3e-8d7b-bc1f387d2e9b.webp.pad
                   dimensions: 900x750
                   ctaText: Work at Brave
                   targetUrl: https://brave.com/careers
19:19:07.720  V  [VERBOSE1:purchase_intent_resource.cc(75)] Successfully loaded bejenkminijgplakmkmcgkhjjnkelbld purchase intent resource
19:19:07.721  V  [VERBOSE1:purchase_intent_resource.cc(81)] Successfully initialized bejenkminijgplakmkmcgkhjjnkelbld purchase intent resource version 1
19:19:07.728  V  [VERBOSE1:eligible_inline_content_ads_v2.cc(129)] 1 eligible ads out of 2 ads
19:19:07.728  V  [VERBOSE1:inline_content_ad_handler.cc(113)] Opportunity arose to serve an inline content ad
19:19:07.728  V  [VERBOSE1:inline_content_ad_serving.cc(96)] Found 1 eligible ads
19:19:07.728  V  [VERBOSE1:inline_content_ad_serving.cc(113)] Served inline content ad
19:19:07.728  V  [VERBOSE1:inline_content_ad_handler.cc(130)] Served inline content ad:
                   placementId: 99999e22-680a-4598-a44c-93b192ce8ccc
                   creativeInstanceId: 1d87cb97-3f55-4a3d-bce1-1c841f39b6f8
                   creativeSetId: 59ae2407-51ae-48f6-9d67-6ae234319181
                   campaignId: 07de7f05-ab32-4af0-a350-a1bce4427eac
                   advertiserId: 93130af3-2def-4ecb-b836-b3772e73b3c9
                   segment: untargeted
                   title: [Staging] Aspect Ratio
                   description: Test Aspect Ratio
                   imageUrl: https://pcdn.bravesoftware.com/brave-news-ads/0f61aa5e-d79f-4585-9835-b75afb3343b0.jpg.pad
                   dimensions: 900x750
                   ctaText: Aspect Ratio
                   targetUrl: https://brave.com/careers/
19:19:07.753  V  [VERBOSE3:inline_content_ad_handler.cc(137)] Served inline content ad with placement id 52e4cda9-dd47-42fc-82ba-2b8f4baa0e61 and creative instance id cbe9f40d-257f-429c-939c-39f3d05a0372
19:19:07.796  V  [VERBOSE3:inline_content_ad_handler.cc(137)] Served inline content ad with placement id 99999e22-680a-4598-a44c-93b192ce8ccc and creative instance id 1d87cb97-3f55-4a3d-bce1-1c841f39b6f8

```
Two ads are placed together:
![image](https://github.com/brave/brave-browser/assets/34715963/dd883774-81e4-4379-ac92-24b273240fe9)

## Expected result:
all `view` events are triggered

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave v1.58.117 on Lenovo TB-8506FS (Android 11.0)

Brave v1.57.x on Lenovo TB-8506FS (Android 11.0) with `brave://flags/#brave-ads-should-always-run-brave-ads-service`

cc @tmancey @aseren @iambrianfung

**Comment by tmancey** [comment] 2023-10-11 16:06
@btlechowski this should be resolved by https://github.com/brave/brave-core/pull/20466, can you please retest once merged. Thanks

**Comment by btlechowski** [comment] 2023-11-28 17:17
Still reproducible 1.61.86

**Comment by Uni-verse** [comment] 2023-11-28 17:22
Reproduced on Nightly 1.62.87, also another ad card right below. 

Example | Example
-|-
![Screenshot 2023-11-28 at 10 22 08 AM](https://github.com/brave/brave-browser/assets/17885425/42e9b06e-7a4f-42e3-9527-289d211fced8) | ![Screenshot 2023-11-28 at 10 22 23 AM](https://github.com/brave/brave-browser/assets/17885425/e8920591-dad6-41b5-9fda-9ff933732c0a)

**Comment by aseren** [comment] 2023-12-19 21:32
The problem is that we are running this code 2 times on browser start if the last open tab is NTP: [code](https://github.com/brave/brave-core/blob/master/android/java/org/chromium/chrome/browser/brave_news/CardBuilderFeedCard.java#L408)
This should be called one time. Desktop doesn't have this issue.
@deeppandya @SergeyZhukovsky could you please take a look?

**Comment by deeppandya** [comment] 2023-12-19 21:34
> The problem is that we are running this code 2 times on browser start if the last open tab is NTP: [code](https://github.com/brave/brave-core/blob/master/android/java/org/chromium/chrome/browser/brave_news/CardBuilderFeedCard.java#L408)
> This should be called one time. Desktop doesn't have this issue.
> @deeppandya @SergeyZhukovsky could you please take a look?

Thank you @aseren I will look into it from my end. I will reach out to @tapanmodh for more context.

**Comment by kjozwiak** [comment] 2024-01-05 22:05
@deeppandya just curious if there's any progress/updates on this one? I recently switched back to `Android` and I'm seeing the above occur on a daily basis. The first inline ad appears to be grouped/merged with the first news card, then sometimes the same ad appears right blow that. Quick example:

**`Example`** | **`Example`**
---------------|-----------------
![Screenshot_20231217-150000](https://github.com/brave/brave-browser/assets/2602313/eaaea042-498e-4a05-932b-de0a61948e75) | ![Screenshot_20240105-163543](https://github.com/brave/brave-browser/assets/2602313/3de87398-e3d9-4066-bdd4-7c46cb9644c6)

**Comment by tapanmodh** [comment] 2024-01-08 06:47
@kjozwiak I'll check it

**Comment by tmancey** [comment] 2024-01-09 19:34
@tapanmodh I believe this was resolved. Any luck? Thanks

**Closed** 2024-01-16 08:47 UTC
Labels: enhancement, needs-investigation, QA/Yes, release-notes/exclude, feature/ads, OS/Android

**Comment by hffvld** [comment] 2024-02-14 02:07
`Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 13 TP1A.220624.014 release-keys
- Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.63.153
Chromium: 121.0.6167.164 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-browser/issues/32877#issue-1888163148

**ACTUAL RESULTS:**
- Verified that only 1 ad is shown on NTP

---------------------------

*Galaxy Tab S8 *

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/708ddd71-fd45-421a-a768-f03bf329e29b) | ![2](https://github.com/brave/brave-browser/assets/128532965/74347343-17c8-4788-9896-e3ea1cef3350) |

*Pixel 7*

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/2d9b4b7c-4947-4539-b0f4-053461888d73) | ![2](https://github.com/brave/brave-browser/assets/128532965/02545ac8-0d03-49ff-b2de-8b83022dba59) |
