### ISSUE TITLE
Brave 1.51.110 bugs out with KDE's KWallet. All sites get logged out and sync breaks.

### ISSUE THREAD

**Issue by urbenlegend** [brave/brave-browser#30147] opened 2023-05-04 20:14 UTC
## Description 
I updated Brave to 1.51.110 yesterday on my Arch Linux KDE machine and it completely broke sync and logged me out of all my sites. Sync complained that it could not access my browser's secure storage even though KWallet shows that it contains a key called `Brave Safe Storage`. Relogging into all of my sites and resetting sync seemed to correct the issue, but I am able to reproduce this on a fresh install of Brave every time.

Brave was working absolutely fine with KWallet prior to the 1.51.110 update.

## Steps to Reproduce

   1. **Start fresh.** Delete `Brave Safe Storage` key from KWallet. Delete app settings in `~/.config/BraveSoftware` and `~/.cache/BraveSoftware`
   2. Launch Brave and sign into a few sites, as well as Brave Sync.
   3. Close Brave
   4. Relaunch Brave. Notice that sites are logged out and that sync is broken.
   5. Re-sign into all of your sites and reset sync using `brave://sync-internals`
   6. Close Brave
   7. Relaunch Brave. Notice that it does not break.

## Actual result:
Browser complains it is unable to access secure storage **once**, unless user settings are cleared. After that, it seems okay, although it does make me paranoid that it may not be using secure storage.

## Expected result:
Browser should not complain about secure storage.

## Reproduces how often: 
Every time

## Brave version (brave://version info)

1.51.110 Chromium: 113.0.5672.77 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? Not tested

## Miscellaneous Information:

**System Info:**
Operating System: Arch Linux 
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.9
Kernel Version: 6.3.1-arch1-1 (64-bit)

**Comment by Stolexiy** [comment] 2023-05-05 06:53
Hello!
I faced exactly the same issue after updating to Brave v1.51.110 on my KDE Neon Linux OS.

## Brave version (brave://version info)
Version 1.51.110 Chromium: 113.0.5672.77 (Official Build) (64-bit)

## Miscellaneous Information:
**System Info:**
Operating System: KDE neon 5.27
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.9
Kernel Version: 5.19.0-41-generic (64-bit)

**Comment by brauliobo** [comment] 2023-05-05 15:56
annoying issue, lost all my sessions :(

**Comment by c0pp1** [comment] 2023-05-05 20:21
Hello!
I also faced the same issue. After some attempts I was able to make it work with the following steps:

1) Disable sync through `brave://sync-internals`
2) Go to *System settings >> KDE Wallet >> Access control* and activate the option *Prompt when an application accesses a wallet*
3) reboot
4) Enable sync. When closing and reopening the browser it will ask for access to the Wallet, choose *Always allow* and done!

Let me know if this works on your platforms too

## Brave version (brave://version):
1.51.110 Chromium: 113.0.5672.77 (Official Build) (64-bit) 

## Miscellaneous Information:
Operating System: Kubuntu 23.04
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-20-generic (64-bit)

**Comment by agilob** [comment] 2023-05-06 11:34
Related discussions:

https://github.com/brave/brave-browser/issues/30040

https://github.com/brave/brave-browser/issues/30167

https://community.brave.com/t/sync-not-working-brave-was-unable-to-access-your-systems-secure-storage/485452

**Comment by Tortillas-IT** [comment] 2023-05-06 11:48
same issue here on arch + KDE btw

**Comment by Tortillas-IT** [comment] 2023-05-06 11:50
btw, if i try to delete brave keys using kwallet by KDE and restart brave all seems to be fine, but if i restart brave again... it breaks

**Comment by kawazoe** [comment] 2023-05-07 23:41
I've been experiencing this issue as well. Something I've tried is only revoking access to the Brave app, without clearing any keys or disabling sync, then restarting the browser. Brave didn't trigger any prompt to access my wallet, which is suspicious.

**Comment by codeonblocks** [comment] 2023-05-08 01:49
I'm having the same issue on Kubuntu 23.04.

Downgrading to a lower version fixed the issue. How can I subscribe to this to see when it's patched?

`sudo apt install brave-browser=1.50.125`

Operating System: Kubuntu 23.04
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-20-generic (64-bit)
Graphics Platform: X11

**Closed** 2023-05-08 15:08 UTC
Labels: QA/Yes, release-notes/include, OS/Desktop

**Comment by Rad0van** [comment] 2023-05-09 11:57
The same issue here (Kubuntu 22.04.2 LTS). However even downgrading to 1.50.125 doesn't help.

The "Login data" contains records and KWallet has the "Brave Safe Storage" key with some kind of passphrase...

Is there a way to make at least the downgraded version work?

**Comment by AlexeyBarabash** [comment] 2023-05-09 12:13
@Rad0van 
if  KWallet has the "Brave Safe Storage" with the password, 1.50.125 supposed to work, as it didn't have that bug. Not sure what went wrong.

**Comment by Rad0van** [comment] 2023-05-09 13:14
> @Rad0van if KWallet has the "Brave Safe Storage" with the password, 1.50.125 supposed to work, as it didn't have that bug. Not sure what went wrong.

Not sure either. Have tried installing latest nightly and copying the Default directory into the profile but does not work either. But now I see it's v1.51.110 (May 3, 2023) so the patch is not there yet.

Was trying to troubleshoot why even older version doesn't work. Attempted to start brave with `--password-store=kwallet` but that gives this:
```
[11707:11707:0509/140942.838550:ERROR:object_proxy.cc(623)] Failed to call method: org.kde.KWallet.isEnabled: object_path= /modules/kwalletd: org.freedesktop.DBus.Error.ServiceUnknown: The name org.kde.kwalletd was not provided by any .service files
[11707:11707:0509/140942.838612:ERROR:kwallet_dbus.cc(100)] Error contacting kwalletd (isEnabled)
[11707:11707:0509/140942.839711:ERROR:object_proxy.cc(623)] Failed to call method: org.kde.KLauncher.start_service_by_desktop_name: object_path= /KLauncher: org.freedesktop.DBus.Error.ServiceUnknown: The name org.kde.klauncher was not provided by any .service files
[11707:11707:0509/140942.839737:ERROR:kwallet_dbus.cc(72)] Error contacting klauncher to start kwalletd
[11707:11707:0509/140942.840528:ERROR:object_proxy.cc(623)] Failed to call method: org.kde.KWallet.close: object_path= /modules/kwalletd: org.freedesktop.DBus.Error.ServiceUnknown: The name org.kde.kwalletd was not provided by any .service files
[11707:11707:0509/140942.840556:ERROR:kwallet_dbus.cc(452)] Error contacting kwalletd (close)

```
Attempting for `--password-store=kwallet5` as some sources suggest doesn't do anything - seems such option is being ignored.

If I do `--enable-logging=stderr` I get lots of these:
`[28656:28674:0509/151342.305936:INFO:login_database.cc(1393)] Password decryption failed, encryption_result is 2
`
@AlexeyBarabash any ideas?

**Comment by AlexeyBarabash** [comment] 2023-05-09 13:24
@Rad0van 
Error came from https://source.chromium.org/chromium/chromium/src/+/main:components/os_crypt/sync/kwallet_dbus.cc;l=107?q=kwallet_dbus.cc&ss=chromium%2Fchromium%2Fsrc

I didn't see such during my work on the issue, the wallet was available for me.
I would suggest to double check wallet settings. Here is how it looks to me (pretty much default), especially check these I am sure are required
`Enable the KDE wallet subsystem`
`Enable Secret Service DBus API`
![image](https://github.com/brave/brave-browser/assets/24739341/8b83de72-e16c-41e3-bac6-726be53258f7)

**Comment by airend** [comment] 2023-05-09 13:47
@AlexeyBarabash, thanks for fixing it. Do you know if next stable build will likely contain the uplift in https://github.com/brave/brave-core/pull/18406?

**Comment by AlexeyBarabash** [comment] 2023-05-09 13:49
@airend the current plan is `May 17, 2023`

**Comment by Rad0van** [comment] 2023-05-09 13:52
> @Rad0van Error came from https://source.chromium.org/chromium/chromium/src/+/main:components/os_crypt/sync/kwallet_dbus.cc;l=107?q=kwallet_dbus.cc&ss=chromium%2Fchromium%2Fsrc
> 
> I didn't see such during my work on the issue, the wallet was available for me. I would suggest to double check wallet settings. Here is how it looks to me (pretty much default), especially check these, as I am sure they are required `Enable the KDE wallet subsystem` `Enable Secret Service DBus API` ![image](https://user-images.githubusercontent.com/24739341/237107720-8b83de72-e16c-41e3-bac6-726be53258f7.png)

My version is missing that "Secret Service DBus API" section...

**Comment by Rad0van** [comment] 2023-05-09 19:54
Have tried to upgrade to 22.10 hoping it would resolve the d-bus issue and maybe will start working again. Didn't help.

Then I wen to look into `/usr/share/dbus-1/services` directory and checked contents of the `org.freedesktop.secrets.service` The file was there previously but I didn't pay much attention to it because I thought its content was wrong. This is what's inside:
```
[D-BUS Service]
Name=org.freedesktop.secrets
Exec=/usr/bin/gnome-keyring-daemon --start --foreground --components=secrets

```

So I had the idea to try starting Brave with `--store-password=gnome` 
### And it worked - my stored passwords are back!!!

Maybe it would help to someone else as well...

**Comment by DanielHuelsmann** [comment] 2023-05-10 18:50
> Hello! I also faced the same issue. After some attempts I was able to make it work with the following steps:
> 
> 1. Disable sync through `brave://sync-internals`
> 2. Go to _System settings >> KDE Wallet >> Access control_ and activate the option _Prompt when an application accesses a wallet_
> 3. reboot
> 4. Enable sync. When closing and reopening the browser it will ask for access to the Wallet, choose _Always allow_ and done!
> 
> Let me know if this works on your platforms too
> 
> ## Brave version (brave://version):
> 1.51.110 Chromium: 113.0.5672.77 (Official Build) (64-bit)
> 
> ## Miscellaneous Information:
> Operating System: Kubuntu 23.04 KDE Plasma Version: 5.27.4 KDE Frameworks Version: 5.104.0 Qt Version: 5.15.8 Kernel Version: 6.2.0-20-generic (64-bit)

This method works on my computer. Thank you.

Operating System: Fedora Linux 37 KDE Plasma Version: 5.27.4 KDE Frameworks Version: 5.105.0 Qt Version: 5.15.9 Kernel Version: 6.2.14-200.fc37.x86_64 (64 bits)

**Comment by btilford** [comment] 2023-05-12 22:42
I was able to disable and re-enable from another system but before I fixed it I did notice that in KWallet the only entry under Brave Keys > Passwords was something like _Brave Storage_ and not _Brave Safe Storage_

**Comment by codeonblocks** [comment] 2023-05-13 02:58
> I was able to disable and re-enable from another system but before I fixed it I did notice that in KWallet the only entry under Brave Keys > Passwords was something like _Brave Storage_ and not _Brave Safe Storage_

I noticed this same thing.

**Comment by vincegre** [comment] 2023-05-13 14:09
How to fix problem on existing Brave installed on Debian 11 ? as I have problem on all my computers now with Brave complaining it can't access secure storage and can't sync and I have no way in Brave to at least reset the sync or something like that :(
Thanks

**Comment by cthu1hoo** [comment] 2023-05-15 07:44
@AlexeyBarabash When I've encountered this issue I rolled back Brave to 1.50 and reverted profile directory (under ~/.config/BraveSoftware) from borg backup, which didn't help - I could see older profile data but sync was still disabled with the same error.  Then I've tried restoring kwallet data files which also didn't help.

Could you please comment on this? Maybe some other directory should be backed up and/or restored? Thanks.

**Comment by AlexeyBarabash** [comment] 2023-05-15 10:27
Hello, @cthu1hoo 

Just curious, how old was that backup?

I am sure we didn't change seed encryption since Sync v2 release in 2020.

**Comment by Igeljaeger** [comment] 2023-05-15 10:31
I have this issue with pretty much every linux OS atm. Steamdeck's Steam OS, Nobara (Fedora), Pop!_OS and Debian. All of which I use KDE on.

**Comment by kjozwiak** [comment] 2023-05-16 04:13
The above requires `1.51.117` or higher for `1.51.x` verification. @brave/qa-team example the STR/Cases can also be found via https://github.com/brave/brave-core/pull/18404#issuecomment-1548927266.

**Comment by AlexeyBarabash** [comment] 2023-05-16 12:33
@cthu1hoo 
> I think I rolled back to a backup made at April 26. 

this, I would say, is fresh enough.

> In general, should restoring ~/.config/BraveSoftware be enough to rollback Brave profile? This whole situation got me thinking that, at least this part of my profile backups is useless because I can't really roll back for whatever reason.

Yes, it should rollback the profile. I did that several times. The only requirement is to do restore on the same computer where the backup was done.

**Comment by DiarrheaMcgee** [comment] 2023-05-16 16:45
> The only requirement is to do restore on the same computer where the backup was done.

not necessarily
ive backed up ~/.config/BraveSoftware and ~/.cache/BraveSoftware and by restoring those after reinstalling linux it continued where it left off when i backed those up

**Comment by AlexeyBarabash** [comment] 2023-05-16 16:47
@DiarrheaMcgee 
that's interesting, and do you remember, were the passwords still saved in password manager after that procedure?

**Comment by DiarrheaMcgee** [comment] 2023-05-16 16:49
yes it was in the exact same state as when i backed it up
same tabs open same passwords stored and all the website sessions were still there

**Comment by btlechowski** [comment] 2023-05-16 17:19
Reproduced on 1.51.114, on Neon KDE 5.27 x64:

![image](https://github.com/brave/brave-browser/assets/34715963/976cfb1e-0c90-4e36-8bec-53c1a1fdd7ad)|![image](https://github.com/brave/brave-browser/assets/34715963/a96a800d-85ee-41e2-bad6-f8a2487d7b39)
--|--

Verification passed on

Brave | 1.51.117 Chromium: 113.0.5672.92 (Official Build) (64-bit) 
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Neon KDE 5.27 x64

### Clean install

<details>

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/30147#issue-1696636696, ensured the following once Brave was restarted:

ensured that passwords from brave://settings/passwords were still visible/listed
ensured that you're not logged out of any websites that were logged in
ensured that sync is still working and doesn't display the Sync service could not be started, Brave Sync is not running
synced several bookmarks between two devices several times and ensured sync was working as expected

![image](https://github.com/brave/brave-browser/assets/34715963/cef97e8d-7109-4b08-bf51-3a3a08782a55)|![image](https://github.com/brave/brave-browser/assets/34715963/3d442059-4d35-495f-ad74-9677871bfc42)|![image](https://github.com/brave/brave-browser/assets/34715963/318fcfe6-724a-4613-b14d-44fbee68abed)|![image](https://github.com/brave/brave-browser/assets/34715963/2357bd3a-92cf-4240-a98e-42a98cfd9c4b)
--|--|--|--

</details>


### Upgrade install

<details>

ensured that passwords from brave://settings/passwords were still visible/listed
ensured that you're not logged out of any websites that were logged in
ensured that sync is still working and doesn't display the Sync service could not be started, Brave Sync is not running
synced several bookmarks between two devices several times and ensured sync was working as expected


![image](https://github.com/brave/brave-browser/assets/34715963/6ccfc315-06df-42e8-8976-6a1443b80f76)|![image](https://github.com/brave/brave-browser/assets/34715963/053d02d1-cad1-429b-87c0-0cac3567760a)|![image](https://github.com/brave/brave-browser/assets/34715963/fd6f380a-b4a8-43b8-a185-4162c39459cd)
--|--|--

</details>

**Comment by cthu1hoo** [comment] 2023-05-18 14:01
Updated to 1.51.118 (Fedora 38 KDE) and sync seems to work just fine. Thanks!

**Comment by markg85** [comment] 2023-05-29 13:43
I still have this very issue!
Brave version: v1.51.118

My conditions are slightly different though.
- I don't want to use KWallet. It's disabled.
- I don't want to use **any** of brave's password managers (they are all disabled) as i use bitwarden.

But upon starting brave it keeps nagging me about setting up kwallet.
How do i make brave shut up?

**Comment by markg85** [comment] 2023-05-29 14:12
Oke, considered fixed.
With the above settings **+ reboot**, brave behaves as expected. No password manager spam anymore.
