### ISSUE TITLE
"Help" button on modal after brave fails to install points to incorrect link/domain

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1605] opened 2018-10-16 06:15 UTC
## Description 

When b-c fails to install for whatever reason, you'll get a modal that will display an error message on why the installation as failed which will include both `Help` and `Close` buttons. Clicking on the `Help` button will attempt to load the following URL in this instance:

```
https://updates.bravesoftware.com/support/installer/?hl=en&product=%7BCB2150F2-595F-4633-891A-E39720CE0531%7D&error=-1073741571&from_extra_code=1&guver=1.3.99.0&m=1&os=6.1.7601.24263&sp=Service%20Pack%201&iid=&brand=&source=gethelp&testsource=auto
```

## Steps to Reproduce

Not 100% sure how to reproduce, but I was attempting to install the versions listed below under `Win 7 x86` and the installation would always fail. Once I clicked on the `Help` button, my default browser opened and loaded the above link which is dead.

## Actual result:

<img width="1430" alt="screen shot 2018-10-16 at 2 05 10 am" src="https://user-images.githubusercontent.com/2602313/46995766-1a7a1a80-d0e8-11e8-92a1-cb0a94b669fc.png">

## Expected result:

Clicking on the `Help` button should take the user to a Brave support page, or http://community.brave.com.

## Reproduces how often: 

100% reproducible once you get the appropriate modal when the installation fails for some reason.

## Brave version (brave://version info)

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Windows

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds? 

Yes, currently reproducible on both `dev` and `beta`.

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Windows

Brave | 0.56.4 Chromium: 70.0.3538.54 (Official Build) dev (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Windows

- Does it reproduce on browser-laptop? 

N/A

**Comment by bsclifton** [comment] 2018-10-16 06:29
Closing as duplicate of https://github.com/brave/brave-browser/issues/1585

**Closed by bsclifton** 2018-10-16 06:29 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, setup/installer
