### ISSUE TITLE
import using account seed phrase broken link

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#5682] opened 2019-08-15 18:31 UTC
## Description 
Returning to brave://wallet can't use "import using account seed phrase"

## Steps to Reproduce
   1. Go to brave://wallet
   2. Close browser and go back to brave://wallet (so you're logged out and see Welcome Back! screen)
   3. Click "Import using account seed phrase"
   4. Notice it takes you to a blank brave://wallet page.

## Actual result:
![Screen Shot 2019-08-15 at 11 27 46 AM](https://user-images.githubusercontent.com/5951041/63117174-1315de80-bf50-11e9-8682-1e94c39cae7c.png)
![Screen Shot 2019-08-15 at 11 28 13 AM](https://user-images.githubusercontent.com/5951041/63117181-14dfa200-bf50-11e9-9447-d107929eca51.png)

## Expected result:
Should take me to import flow.

## Brave version (brave://version info)
Version 0.71.5 Chromium: 76.0.3809.100 (Official Build) nightly (64-bit)

**Comment by ryanml** [comment] 2019-08-15 18:39
Note: Import is functional, just not from the path where you have already created an account

**Comment by srirambv** [comment] 2019-10-02 21:53
Issue doesn't seem to be fixed. If I set device language to English and then follow the steps from original issue then clicking on it does nothing. Seems like a dead UI. But when i change locale to French and try the same steps it shows the  recover seed page but fails to recover

**Comment by kjozwiak** [comment] 2019-10-02 21:59
Reproduced using `Crypto Wallets - Version: 1.0.9`:

This isn't working correctly as @srirambv mentioned above. Restoring a `12 word` seed phrase from MM really screws up `brave://wallet` and puts it into an unstable state. Example:

<img width="1162" alt="Screen Shot 2019-10-02 at 5 55 00 PM" src="https://user-images.githubusercontent.com/2602313/66085119-58ad5b80-e53e-11e9-9065-eb49b2fa7e27.png">

<img width="564" alt="Screen Shot 2019-10-02 at 5 55 40 PM" src="https://user-images.githubusercontent.com/2602313/66085129-619e2d00-e53e-11e9-9f1a-0d2e18cc7459.png">

Once you're in the above state, `brave://wallets` doesn't load correctly at times. Some of the buttons completely stop working so you can't even restore another wallet. If someone attempts to restore a MM seed phrase, they'll basically put `brave://wallet` into a bad state/unusable state.

**Comment by kjozwiak** [comment] 2019-10-02 23:54
@srirambv this seems to be working for me using the following STR:

* load `brave://wallet` in a new profile (dismiss the disclosure)
* select `Restore` which takes you to the `Import an Account with Seed Phrase` screen
* paste your wallet seed and enter a new password --> Click `Import`
* the `Congratulations` screen loads with some information
* click on `All Done` and `brave://wallet` loads as expected

re: MM seeds not working, re-opened https://github.com/brave/brave-browser/issues/5698

@rebron mind going through this as well? Is it working for you?

**Comment by rebron** [comment] 2019-10-03 00:07
This is working for me. Original issue is when coming back to brave://wallet, I selected 'Import account using seed phrase' and the page was blank. That was the issue that was hung up, didn't even have the option to recover my account via seed phrase.

This is what I'm getting now. And I was able to use the seed phrase to recover my account while creating a new password.
![Screen Shot 2019-10-02 at 5 02 27 PM](https://user-images.githubusercontent.com/5951041/66090097-c6ee2000-e536-11e9-8f21-9d740a02782e.png)

Verified with: 
Version 0.69.131 Chromium: 77.0.3865.90 macOS 10.15

**Comment by srirambv** [comment] 2019-10-03 02:16
Seems to be working for me as well now on both Windows and Linux. Closing and marking the issue as verified

**Closed by srirambv** 2019-10-03 02:17 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/crypto-wallets, release-notes/exclude

**Comment by CMEONE** [comment] 2019-11-23 04:43
@rebron This isn't working anymore, so could you please reopen the issue? Here is what I have tried doing:
1. Go to brave://wallet
2. Click on "Restore account? Import using account seed phrase"
It doesn't even redirect anywhere!

**Comment by paulwaldmann** [comment] 2019-12-29 13:01
Same for me, using Manjaro Linux and the latest Brave browser `Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) unknown (64-bit)`, click on "Restore account? Import using account seed phrase" takes no effect.

Please reopen this issue!

**Comment by srirambv** [comment] 2019-12-29 16:21
@paulwaldmann @CMEONE  could one of you please log a new issue with the exact steps. This issue is already linked to a merged PR so won't be reopening. We can triage the new issue that will be logged

**Comment by bsclifton** [comment] 2019-12-30 05:57
@CMEONE @paulwaldmann created an issue for you all here:
https://github.com/brave/brave-browser/issues/7537

Please do add information that will help us troubleshoot 😄 Thanks!
