### ISSUE TITLE
Blue line on top of window when focused (not maximized)

### ISSUE THREAD

**Issue by SlowNicoFish** [brave/brave-browser#9420] opened 2020-04-23 15:53 UTC
## Description 

This issue has been here for as long as I've used Brave.
When i go out of a maximized window on Windows 10 the browser shows a blue line on top of 
the window. It is a thin blue line (in my case) and seems to be changing colors based on my current Windows color.

## Steps to Reproduce

   1. Open Brave
   2. Go out of maximized mode
   3. See the colored line at the top

## Actual result:

![image](https://user-images.githubusercontent.com/19305293/80119934-9f21e080-858a-11ea-9e57-d3cbe2423421.png)

## Expected result:
For the browser not to show this line, or at least make it an option

## Reproduces how often: 

Easily reproduced on Windows 10, meaning it's always there when the window is not maximized

## Brave version (brave://version info)

Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)

## Version/Channel Information:

This can be reproduced on the official channel as well as the Dev channel

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No.
- Does the issue resolve itself when disabling Brave Rewards?
No.
- Is the issue reproducible on the latest version of Chrome? 
Yes

## Miscellaneous Information:

OS: Windows 10

**Comment by rebron** [comment] 2020-06-12 16:45
This is Windows OS behavior and works the same with other Windows apps and Chrome. You can choose a different color or no color in the Colors section of Windows OS . The blue line is more pronounced on dark theme vs light theme.

**Comment by SlowNicoFish** [comment] 2020-06-12 17:25
Alright. I've seen some chromium browsers remove it such as Vivaldi and the new Edge. Is that doable?

**Comment by rmda** [comment] 2020-07-29 12:31
I've seen this also removed on later builds of Edge and I can verify this issue occurs in Brave and Chrome. I'm using Windows 10 with a dark theme.
![image](https://user-images.githubusercontent.com/8079732/88800307-91718d80-d16d-11ea-8b8b-2761c7f629cf.png)

**Comment by bsclifton** [comment] 2020-08-03 08:20
This is definitely an annoying one - and should be solvable. Will share any updates if I get a chance to investigate

**Comment by SlowNicoFish** [comment] 2020-11-13 21:23
@bsclifton Did you found a solution this? It's quite annoying!

**Comment by tero-dev** [comment] 2020-12-07 13:36
Can reproduce
Name|Value
-- | --
Brave | 1.17.75 Chromium: 87.0.4280.88 (Official Build) (64-bit)
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{# 1761}
OS | Windows 10 OS Version 2004 (Build 19041.630)

<details>
  <summary>Screenshot</summary>
  <img src="https://user-images.githubusercontent.com/31454692/101355873-e651ad00-389f-11eb-84c5-e0459640f76b.png"/>
</details>
<details>
  <summary>Accent Settings</summary>
  <img src="https://user-images.githubusercontent.com/31454692/101356222-6b3cc680-38a0-11eb-9dff-939f9b678bb6.png"/>
</details>

**Comment by SlowNicoFish** [comment] 2021-04-07 18:30
Is there any update on this issue. Chrome, vivaldi and edge does not have this

**Comment by LUC18fknU7P** [comment] 2021-04-07 20:31
> Is there any update on this issue? Chrome, vivaldi and edge does not have this 🤔

Can also confirm still happens to this day. Super annoying...

**Comment by Maledis87** [comment] 2021-06-01 13:50
Please give us an update on this thread, it's still an issue. The only app on windows that I have used that ever does this...Please update us, and I can't use this browser until this is fixed. Workaround is setting a custom color to black and changing title bar windows to black, but then all the setting menus are black and hard to see. thanks

**Comment by Maledis87** [comment] 2021-06-01 13:50
> Is there any update on this issue? Chrome, vivaldi and edge does not have this 🤔

Also, this is an issue with me as well. Really annoying that this is the only app that does this.

**Comment by LUC18fknU7P** [comment] 2021-06-01 15:52
@rebron Could we get an update? Super frustrating..

**Comment by vanquishings** [comment] 2021-08-23 01:18
Has been and continues to be an issue for me. Would love a fix.

**Comment by LUC18fknU7P** [comment] 2021-08-23 09:57
> Has been and continues to be an issue for me. Would love a fix.

Same here. @bsclifton any updates? This has to be fixable somehow

**Comment by rebron** [comment] 2021-10-06 17:29
Looks like this will be a Windows 10 issue. I'm not seeing a blue line with Windows 11.

**Comment by LUC18fknU7P** [comment] 2021-10-06 23:46
> Looks like this will be a Windows 10 issue. I'm not seeing a blue line with Windows 11.

I think this issue should still be tackled, its really irritating and I'd imagine most of the world will stay on Windows 10 for a long time before upgrading (including me)

**Comment by rebron** [comment] 2021-10-07 00:23
@LUC18fknU7P We're looking at a fix. When it's an upstream bug https://bugs.chromium.org/p/chromium/issues/detail?id=950362 we have to see how it's being addressed there. That's part of the reason for the delay on certain issues like this one.

**Comment by LUC18fknU7P** [comment] 2021-10-07 00:54
> @LUC18fknU7P We're looking at a fix. When it's an upstream bug https://bugs.chromium.org/p/chromium/issues/detail?id=950362 we have to see how it's being addressed there. That's part of the reason for the delay on certain issues like this one.

That issue seems to be closed as fixed?
https://chromium.googlesource.com/chromium/src.git/+/67ad9ea9d720b7e9bad80b43a325df9a49a0cc28

did this fix not go to the upstream? Maybe I'm missing something here

**Closed** 2021-10-07 07:13 UTC
Labels: OS/Windows, priority/P4, QA/Yes, repros-on-chrome, OS/Desktop, Chromium/reported upstream
