### ISSUE TITLE
don't load unused built-in extensions

### ISSUE THREAD

**Issue by bughit** [brave/brave-browser#9178] opened 2020-04-13 19:34 UTC
## Description 
 The following extensions/processes should not be loaded when their functionality is not activated:

- Utility: Bat Ledger Service (nothing related to BAT has been activated)
- Utility: Bat Ads Service (nothing related to BAT has been activated)
- Extension: Crypto Wallets (nothing related to wallets has been activated)

## Brave version (brave://version info)
```txt
Brave: 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)
Revision: e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS: Windows 7 Service Pack 1 (Build 7601.24550)
```

**Comment by congard** [comment] 2020-04-14 07:24
+1
```
Brave: 1.9.14 Chromium: 81.0.4044.92 (Official Build) unknown (64-bit)
Revision: 0
ОS: Linux
```

**Comment by NejcZdovc** [comment] 2020-04-14 07:53
closing as dupe of https://github.com/brave/brave-browser/issues/5429

**Comment by NejcZdovc** [comment] 2020-04-14 07:54
dupe of https://github.com/brave/brave-browser/issues/5429

**Closed** 2020-04-14 07:54 UTC
Labels: duplicate

**Comment by bughit** [comment] 2020-04-14 14:45
@NejcZdovc What insanity is this? You created #9196 after this and then closed this as dup of a newer issue? 

You did not even bother to vopy it correctly, there's no mention of "Extension: Crypto Wallets"

And of course #5429, which you closed, has nothing to do with this. This bug does not even mention rewards.

**Comment by NejcZdovc** [comment] 2020-04-14 15:03
regarding `Extension: Crypto Wallets (nothing related to wallets has been activated)`. It's disabled when you start a browser. You can try it on a clean profile and you will see that this extension is not running:
![image](https://user-images.githubusercontent.com/9574457/79239920-6b9bd380-7e71-11ea-9ecf-05c0a9c97809.png)
It will be activated when you visit a site that support dapps.

Yes I created https://github.com/brave/brave-browser/issues/9196 as you listed 3 processes that are handled by 3 different teams and can't be tracked in one issue. That's why I split it.

Yes I listed https://github.com/brave/brave-browser/issues/5429 as user was reporting utility as well. `Utility: Bat Ledger Service (nothing related to BAT has been activated)` is rewards service which will be needed for https://github.com/brave/brave-browser/issues/9130 like I said in #5429.

**Comment by bsclifton** [comment] 2020-04-14 18:03
Thanks for the update, @NejcZdovc 

To recap, here are the tracking issues for each item:
- Utility: Bat Ledger Service https://github.com/brave/brave-browser/issues/5429
- Utility: Bat Ads Service https://github.com/brave/brave-browser/issues/9196
- Extension: Crypto Wallets https://github.com/brave/brave-browser/issues/8742
