### ISSUE TITLE
Entry Point Not Found...

### ISSUE THREAD

**Issue by EternalTranquility1** [brave/brave-browser#33017] opened 2023-09-14 22:11 UTC
**Brave Release v1.58.124 (Chromium 117.0.5938.62)** 
i cant launch brave on this version
error message upon launch

> brave.exe - Entry Point Not Found
> The procedure entry point IsEnclaveTypeSupported could not be located in the dynamic link library C:\Program Files\BraveSoftware\Brave-Browser\Application\117.1.58.124\chrome.dll

using windows 10
reverted to 1.57.64 and the problem disappeared

**Comment by DigitalMoneyinn** [comment] 2023-09-15 15:18
if i revert to 1.57.64 version by data links will be deleted or restored automatically.

**Comment by PasinduOshada** [comment] 2023-09-15 15:21
i'm also having this same issue since yesterday. i've been using brave as my primary browser for a while now and i'm now in a big trouble since i can't access it. most of my passwords and bookmarked sites are there. Can someone give me a fix to this. I need my data back

**Comment by DigitalMoneyinn** [comment] 2023-09-15 15:32
I searched many sites but did not find any solution, if anybody got a solution please reply

**Comment by kenherbert** [comment] 2023-09-15 19:20
There are recent reports of this for Chrome too, so it is an upstream issue: https://support.google.com/chrome/thread/234827907/issue-with-chrome-dll-isenclavetypesupported-entry-point-not-found

**Comment by miku871** [comment] 2023-09-16 02:49
> @DigitalMoneyinn what i did to 'revert' was download 'brave-v1.57.64-win32-x64.zip' from the [v1.57.64 release page](https://github.com/brave/brave-browser/releases/tag/v1.57.64) and extract it to 'C:\Program Files\BraveSoftware\Brave-Browser\Application' replacing everything, then disable both brave update services, and everything is working fine for me so far.

Thank You bro.. My issue just solved.

**Comment by DigitalMoneyinn** [comment] 2023-09-16 05:04
> @DigitalMoneyinn what i did to 'revert' was download 'brave-v1.57.64-win32-x64.zip' from the [v1.57.64 release page](https://github.com/brave/brave-browser/releases/tag/v1.57.64) and extract it to 'C:\Program Files\BraveSoftware\Brave-Browser\Application' replacing everything, then disable both brave update services, and everything is working fine for me so far.

My problem also solve , Thank you for your suggestion. This solution is working for me.

**Comment by daris1789** [comment] 2023-09-16 09:44
> @DigitalMoneyinn what i did to 'revert' was download 'brave-v1.57.64-win32-x64.zip' from the [v1.57.64 release page](https://github.com/brave/brave-browser/releases/tag/v1.57.64) and extract it to 'C:\Program Files\BraveSoftware\Brave-Browser\Application' replacing everything, then disable both brave update services, and everything is working fine for me so far.

Thank You bro

**Comment by Georg1na1** [comment] 2023-09-16 10:44
> @DigitalMoneyinn what i did to 'revert' was download 'brave-v1.57.64-win32-x64.zip' from the [v1.57.64 release page](https://github.com/brave/brave-browser/releases/tag/v1.57.64) and extract it to 'C:\Program Files\BraveSoftware\Brave-Browser\Application' replacing everything, then disable both brave update services, and everything is working fine for me so far.

Made my account active again to tell you thank you

**Comment by rebron** [comment] 2023-09-17 04:03
Can you update to the latest 1.58.127. Should be fixed with that version.
Closing as dupe of https://github.com/brave/brave-browser/issues/33058

**Closed by rebron** 2023-09-17 04:03 UTC
Labels: OS/Desktop

**Comment by DigitalMoneyinn** [comment] 2023-09-18 08:19
Yes
Thanks
