### ISSUE TITLE
Integrate ethwallet

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#248] opened 2018-05-31 22:00 UTC
https://github.com/brave/browser-laptop/pull/13177

**Comment by bbondy** [comment] 2018-06-02 14:09
I'd be interested in following this more closely, could you perhaps to checkbox list items summary in the first comment as things progress? Thank you!

**Comment by diracdeltas** [comment] 2019-05-30 21:19
should we close this?

**Comment by bsclifton** [comment] 2019-05-30 23:20
@diracdeltas yup- good call 😄 

Closing as a dupe of https://github.com/brave/brave-browser/issues/4494

**Closed by bsclifton** 2019-05-30 23:20 UTC
Labels: feature/cryptocurrency
