### ISSUE TITLE
Replace DuckDuckGo Search with Brave Search in Private Window

### ISSUE THREAD

**Issue by nickga66** [brave/brave-browser#22373] opened 2022-04-18 10:55 UTC
## Description 
When opening a new Private Window in Brave, the only and default Search Option shown as a Toggle is DuckDuckGo.
DuckDuckGo has shown itself as hostile willing to censor many search results including torrents & YouTube downloads.
The DuckDuckGo search **should be replaced by Brave Search**.

## Steps to Reproduce

   1. Open a new Private Window
   2. The Search Toggle Shown is for DuckDuckGo

## Miscellaneous Information:
<img width="1063" alt="Screen Shot 2022-04-18 at 12 53 23 PM" src="https://user-images.githubusercontent.com/103934323/163798780-7623f7bf-9c93-41bd-8416-b9d1d04ed01b.png">

**Comment by Turphin** [comment] 2022-04-18 18:40
maybe an option to choose a private search engine instead of forcing a specific engine with no way to change it?

**Comment by ice155** [comment] 2022-04-19 13:53
**Before:** https://torrentfreak.com/duckduckgo-removes-pirate-sites-and-youtube-dl-from-its-search-results-220415/
**After:** https://torrentfreak.com/duckduckgo-restores-pirate-sites-and-points-to-bing-220419/
**Official statement from the CEO of DuckDuckGo, Inc.:** https://twitter.com/yegg/status/1515636218691739653
**Summary:** The issue is now resolved, DuckDuckGo was not directly responsible for this, Bing is.

**Comment by IronMaltese** [comment] 2022-04-24 20:30
It feels weird that brave is using another search engine other than it's own in the browser, but a search engine choice screen is a better option

**Comment by bsclifton** [comment] 2022-04-26 07:53
Hi folks - this DDG toggle showing in the private window is a known issue. If you had an older profile and have touched this before (toggled on or off), we will continue to show this as we didn't want to break existing users

When disabled, it'll use your default search engine. We'll be removing this legacy setting soon from the private window (@rebron working on a few related issues; he's self-assigned)

**Comment by rebron** [comment] 2022-06-29 05:48
Closing as a dupe and fixed in 1.42.x. 
We went in a different direction and fixed this by adding a search box on the NTP and in Tor with https://github.com/brave/brave-browser/issues/22566 and adding a separate search engine setting for Private Windows with https://github.com/brave/brave-browser/issues/23091

**Closed by rebron** 2022-06-29 05:48 UTC
Labels: closed/duplicate, priority/P3, feature/settings, OS/Desktop
