### ISSUE TITLE
Keep top sites tile base theme agnostic

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#22244] opened 2022-04-12 13:47 UTC
## Description 

Currently the color of the top sites tile base changes based on the theme: i.e. white for the light theme and dark gray for the dark theme.  This is not only unnecessary but looks out of place because the NTP photos are formatted to have enough color density and darkness for text legibility - The same reason why the widget base color doesn't change.

2 changes are required:

1. make the tile base color theme agnostic (make it the same as the dark theme)
2. the hover flyout for the edit (pencil) looks too bright for the dark theme because it's using the light theme color.  needs to be adjusted.

@aguscruiz @rebron 

## Steps to Reproduce

   1. 
   2. 
   4. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by aguscruiz** [comment] 2022-04-18 15:19
Specs can be taken from this Figma file:
https://www.figma.com/file/QCBklDojDtDTKApz10XqSQ/%F0%9F%A6%81-New-Tab-Page?node-id=1%3A648

I''m proposing the dark color theme but with the same subtle transparency and background blur as the widgets, so they have some connection and we don't do two whole different colors that may end up clashing a bit 

![image](https://user-images.githubusercontent.com/15734630/163830190-ce3ba962-86f0-4507-9e70-f6c39b173137.png)
![image](https://user-images.githubusercontent.com/15734630/163830211-ed078d03-d671-4a1d-8469-68e0ac40a0cd.png)

**Comment by rebron** [comment] 2024-05-16 14:21
Closing as a dupe of https://github.com/brave/brave-browser/issues/38183 and fixed in 1.68.x

**Closed by rebron** 2024-05-16 14:21 UTC
Labels: design, priority/P3, QA/Yes, OS/Android, OS/Desktop
