### ISSUE TITLE
Feature request please: Side bar 

### ISSUE THREAD

**Issue by MaximumCodingLife** [brave/brave-browser#17876] opened 2021-09-04 03:26 UTC
A small bar on the side like what oprea and Vivaldi browsers have. Features such as: Music with Spotify, apple music. Custom tabs, messaging apps.
Thank you

**Comment by stephendonner** [comment] 2021-09-04 05:48
Hi @MaximumCodingLife you can enable this via the toggle to `Enabled` in `brave://flags/#sidebar` - might still only work in `nightly` builds.

**Comment by rebron** [comment] 2021-09-09 23:36
Closing as dupe of https://github.com/brave/brave-browser/issues/15833

**Closed by rebron** 2021-09-09 23:36 UTC
Labels: closed/duplicate
