### ISSUE TITLE
[Android] Full night mode same as Samsung browser

### ISSUE THREAD

**Issue by newuser-web** [brave/brave-browser#10559] opened 2020-07-03 16:36 UTC
## Description  
Feature request
Full night mode in brave browser same as samsung internet browser

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment] 2020-07-05 01:13
Dupe of #6380

**Closed by srirambv** 2020-07-05 01:13 UTC
Labels: OS/Android
