### ISSUE TITLE
watching video on ESPN continually increases Ads/Trackers blocked on new tab page - follow up to 1311

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2505] opened 2018-12-12 20:48 UTC
## Description 
Follow up to #1311 

When watching a video (such as [this](http://www.espn.com/soccer/uefa-champions-league/775/blog/post/3725073/spurs-sneak-into-ucl-knockout-rounds-after-fighting-back-for-draw-at-barca) one), the Ads/Trackers on new tab page incrementally increase. Per https://github.com/brave/brave-browser/issues/1311#issuecomment-446512675 it doesn't seem to be happening on Linux or Windows for @srirambv or @GeetaSarvadnya but I am seeing it on macOS.

## Steps to Reproduce

   1. Open a new tab page
   2. Open a second window
   3. Have both within view on monitor
   4. Visit video above.
   5. Watch in counts go up while the video plays.

## Actual result:

https://drive.google.com/file/d/1Bb6xMRuL8zylcUGpgo4RjYcdRoENERoL/view?usp=sharing

## Expected result:
Once page has loaded I wouldn't expect the counts to go up.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? yes
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @brave/legacy_qa to confirm this does not reproduce on Windows/Linux

**Comment by nithronium** [comment] 2018-12-14 00:58
I do not know if this was also mentioned before but I have the same issue with Youtube. Sometimes it becomes like 700 ads/trackers being blocked. It starts with 3-4, then keeps increasing as I keep watching.

Problem is resolved when I disabled the shields. However, if I activate again, problem occurs again.

**Comment by Brave-Matt** [comment] 2018-12-14 06:19
https://www.reddit.com/r/brave_browser/comments/9zusl9/can_youtube_really_have_300_trackers_or_is_brave/

**Comment by nithronium** [comment] 2018-12-14 09:21
Alright then. I didn't know YouTube had such aggressive ads. Other than that, my friend also reported he had issues with espn but no other website so far. I think I'm good to go. @srirambv

**Comment by lukemulks** [comment] 2019-02-11 07:17
I took a look at the espn video playback, and the requests we're blocking are requests that we should be blocking imo. 

The majority appear to be chartbeat requests, which are sending data back to chartbeat through the video player. 

I'm also observing the following requests, that appear to be related to video header bidding,
```
Request URL: http://espn.hb.omtrdc.net/?s:sc:rsid=wdgespcom%2Cwdgespge&s:sc:tracking_server=w88.espn.com&h:sc:ssl=0&s:user:mid=61908584608842934314814505294492092541&s:sp:ovp=Brightcove&s:sp:sdk=1.6.7&s:sp:channel=espn&s:sp:player_name=PROD%201.9.x%20-%20BC%205.28%20-%20no%20flashls%20-%20FW%20v3.x&s:sp:hb_version=js-n-1.6.9.110-a2ee4c&l:sp:hb_api_lvl=4&s:event:sid=1549868828525149226884&s:event:type=start&l:event:duration=10&l:event:playhead=0&l:event:ts=1549868833557&l:event:prev_ts=-1&s:asset:type=main&s:asset:name=NBA_One-Play%20(No-call%20on%20Durant%E2%80%99s%20double-dribble%20leads%20to%20controversial%20ending)%202019%2F2%2F10%20ESHEET&s:asset:video_id=25969632&s:asset:publisher=EE0201AC512D2BE80A490D4C%40AdobeOrg&l:asset:length=38&s:stream:type=vod&l:stream:bitrate=0&l:stream:fps=0&l:stream:dropped_frames=0&l:stream:startup_time=0&s:meta:startType=manual&s:meta:Showcode=nba_instantreplay&s:meta:a.media.type=2&s:meta:a.nielsen.clientid=us-600140&s:meta:a.nielsen.vcid=b01&s:meta:a.nielsen.appid=P31187EE2-AC6E-46CB-BB54-D07591BED067&s:meta:a.nielsen.program=NBA_One-Play%20(No-call%20on%20Durant%E2%80%99s%20double-dribble%20leads%20to%20controversial%20ending)%202019%2F2%2F10%20ESHEET&s:meta:a.nielsen.segc=Sport%2FProgram%20Code&s:meta:a.nielsen.admodel=2&s:meta:a.nielsen.sega=NBA_One-Play%20(No-call%20on%20Durant%E2%80%99s%20double-dribble%20leads%20to%20controversial%20ending)%202019%2F2%2F10%20ESHEET&s:meta:a.nielsen.accmethod=0&s:meta:a.nielsen.ctype=VIDEO
```

Might seem high, but I'd suggest that if the blocking taking place doesn't disrupt the UX, then it's likely something we should avoid making exceptions for imo. Nielsen and other companies that I'm observing blocked requests to profile user data.

**Comment by Brave-Matt** [comment] 2019-05-02 06:45
+1 (kinda):
https://community.brave.com/t/laptop-runs-hot-when-brave-browser-open/54034/3?u=mattches
☝️ User cites ESPN as an example of a site that causes high CPU usage/heat

**Comment by adamwinn** [comment] 2019-09-20 22:50
I'm seeing this too.  My trackers blocked counter was increasing by multiple thousands in just a few seconds.  Brave shot up to 700% cpu.  This is on the homepage of espn.com.  It didn't used to do this so maybe it was something caused in the last update.  I'm using `Version 0.68.139 Chromium: 77.0.3865.90 (Official Build) (64-bit)`

**Comment by ryanbr** [comment] 2019-12-15 19:39
I've checked this in Brave released (Version 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)):

I'll address the 2 issues, the espn site is using trackers continuously throughout the video, and it should be blocked (as @lukemulks stated). Using uBo to see which trackers are being hit. https://secure.fanboy.co.nz/gif/espn-trackers.gif All of these are being blocked by shields. (Note, uBo number of blocked items is also increasing as the video plays)

The other issue, does it cause cpu usage? https://secure.fanboy.co.nz/gif/espn-cpu.gif  I don't think so? Even on my old Ryzen 1700 desktop. Getting around 10-15% variance. I'll check other platforms like smart phones and maybe less core heavy cpus. But initial checks it seems okay.

**Comment by ryanbr** [comment] 2020-12-09 08:45
Okay, retested this. `https://www.espn.com/soccer/uefa-champions-league/775/blog/post/3725073/spurs-sneak-into-ucl-knockout-rounds-after-fighting-back-for-draw-at-barca`  

The blocked items counter don't continue going up, which stopped on 24 blocked items, except if you keep scrolling in the window (new blocked requests come through).

Safe to close @LaurenWags

**Comment by LaurenWags** [comment] 2021-01-04 13:01
@ryanbr after re-reading the steps, this issue is about watching a video on espn, not visiting an article like the one you referenced. 

So, in the STR below the issue still reproduces using default shield settings:
1. Open one window to show NTP with stats
2. Open a second window and visit an article with a video like https://www.espn.com/soccer/brazilian-serie-a/story/4274748/fan-unrest-in-brazil-serves-as-warning-to-europes-super-league-dreams
3. Keep both windows within view (ex. side by side)
4. Play the video on the article
5. Watch the shield count continually increase as the video is playing. On the NTP the "Trackers & ads blocked" continues to increase as well.

Confirmed using 


Brave | 1.19.72 Chromium: 87.0.4280.101 (Official Build) beta (x86_64)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | macOS Version 10.15.7 (Build 19H15)

**Comment by kjozwiak** [comment] 2021-01-04 16:31
Reproduced this pretty easily as well using the STR that @LaurenWags mentioned via https://github.com/brave/brave-browser/issues/2505#issuecomment-753961726 on `Win 10 x64` using the following build:

```
Brave | 1.18.77 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2009 (Build 19042.685)
```

After loading the URL, the `Trackers & ads blocked` stat under `brave://newtab` slowly increased while the video was being played.

![image](https://user-images.githubusercontent.com/2602313/103556623-14ff7b00-4e80-11eb-8a8b-9ef1b0d23bcb.png)

**Comment by ryanbr** [comment] 2021-01-05 01:24
Hmm okay, its affecting other browsers.  Only occurs during video plackback.


The following should help a little bit, but won't stop 3 other blocked requests.
https://github.com/easylist/easylist/commit/7eef3792b6372d453d862ee65bd7fdebff931ab3  

(new) blocked 3rd-party requests from the video playback.

`scorecardresearch.com`
`metrics.brightcove.com`
`espn.hb.omtrdc.net`

**Comment by ryanbr** [comment] 2023-05-09 04:37
Looks good now @LaurenWags , safe to close?

**Comment by LaurenWags** [comment] 2023-05-09 20:39
@ryanbr so just tried again and issue still reproduces but not as quickly as it did initially. 

My "Trackers and ads blocked" on NTP was around 30-something when I started, it's now almost 60. Value on shields is increasing as well, but not sure where that one started out.

Used https://www.espn.com/soccer/uefa-champions-league/story/4944234/champions-league-live-updates-real-madrid-manchester-city fwiw.

<img width="2251" alt="Screenshot 2023-05-09 at 4 38 15 PM" src="https://github.com/brave/brave-browser/assets/28145373/48929cc4-b818-4aa7-9c49-6c3f1d5a7e3f">

Using

```
Brave | 1.52.86 Chromium: 113.0.5672.77 (Official Build) beta (x86_64)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | macOS Version 13.3.1 (a) (Build 22E772610a)
```

**Comment by ryanbr** [comment] 2023-05-10 03:52
@LaurenWags I'm leaning towards its intended, other adblocking extensions show the increase in blocked items.

In a video, if they keep sending trackers during video playback (and viewing the page) it should be blocked. However it should cause any performance issues. Are you seeing any perf issues?

**Comment by LaurenWags** [comment] 2023-05-10 12:31
@ryanbr no performance issues at this time 👍🏻

**Comment by ryanbr** [comment] 2023-05-14 03:01
Okay, we'll close this. Not really a fix for a site who keeps sending out trackers. We'll just keep blocking it.

**Closed by ryanbr** 2023-05-14 03:01 UTC
Labels: bug, feature/shields, feature/new-tab, QA/Yes, QA/Test-Plan-Specified, OS/Desktop
