### ISSUE TITLE
Shield prevents signing up on Uphold when trying to KYC

### ISSUE THREAD

**Issue by Jezz1e** [brave/brave-browser#4139] opened 2019-04-17 03:56 UTC
## Test plan
See https://github.com/brave/brave-core/pull/2773

## Description 

I haven't created an Uphold account yet so when I tried clicking "Connect" through the "Your Uphold Wallet" on the Brave Rewards website and sign up from the given link, I couldn't because of Shield. However, when I disable it I'm able to sign up. 

   1. Log in to https://publishers.basicattentiontoken.org and click on "Connect" from Your Uphold Wallet. (If you are already connected, you can disconnect and try connecting again)
   2. Try signing up (not signing in) with Shield enabled on default settings

## Actual result:

Shield doesn't allow signing up 

## Expected result:
Sign up with no issues

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave: 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)
Revision:  e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS: Windows 10 OS Build 17763.437

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
I have not yet tried
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
Disabling Shield resolves the issue
- Is the issue reproducible on the latest version of Chrome? 
Not reproducible on latest ver of Chrome 
### Additional Information

Due note that I did not sign up through the Uphold website itself because I tried signing up from there and I can do it easily even with Shield on. This issue only occurs when signing up through the link given by the "Connect".

**This only affects signing up not signing in**

**Comment by davidtemkin** [comment] 2019-06-13 21:28
Please prioritize this issue -- we should create rules that allow Uphold connect to work with shields on. 

Discussed briefly with @diracdeltas and @evq. Sounds like it is possible. The driver is that Uphold Connect is coming soon for Brave Rewards users -- v 0.68. 

cc @mandar-brave @alexwykoff @kjozwiak @rebron @bsclifton

**Comment by kjozwiak** [comment] 2019-06-13 21:46
Going to bump this to a `P2` as it sounds like want this completed by `0.68.x`.

**Comment by diracdeltas** [comment] 2019-06-13 22:21
it worked for me just now with shields on. 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit) MacOS

**Comment by mandar-brave** [comment] 2019-06-14 15:19
@diracdeltas did you try the KYC; with netverify coming in to play (Jumio). Back in Jan when @tomlowenthal and I were playing, we were blocking out KYC. Uphold by itself is not a challenge. 

The real issue is the KYC part. https://portal.netverify.com/login
Uphold uses their app version of netverify.com to get users KYC'd.

Thanks.

**Comment by diracdeltas** [comment] 2019-06-14 17:01
@mandar-brave can you or @tomlowenthal post the repro steps to hit that bug?

**Comment by mandar-brave** [comment] 2019-06-17 18:32
@diracdeltas will do; i am trying to see if i can disconnect my ID from my account; i am already KYC'd and Uphold does not show me the verify option. Also assigned issue to Uphold QA to verify if Brave is blocking any of the steps. stay tuned.

**Comment by kjozwiak** [comment] 2019-06-17 19:01
I need to KYC my account either way, so I'll go through the process and document any snags/issues that I run into while using the latest nightly with default shield settings.

**Comment by kjozwiak** [comment] 2019-06-18 06:16
Some quick results/observations:

* Used `0.68.56 Chromium: 75.0.3770.90` with the default shields settings

`Logging into an already existing Uphold Account` - **PASSED**

Going through https://publishers.basicattentiontoken.org and logging into an already created account works without any issues using the default shields settings. I went through 2FA and had no issues logging into Uphold.

`Creating a new account through the Publisher Web Portal` - **PASSED** (x2 attempts)

Seems like creating a new Uphold account through https://publishers.basicattentiontoken.org is also working. Once you've created a new Publisher account, clicking on `Connect to Uphold` will take you to the following:

<img width="898" alt="Screen Shot 2019-06-18 at 2 12 04 AM" src="https://user-images.githubusercontent.com/2602313/59657364-7bbe2600-916e-11e9-976f-9b8def6f7bb3.png">

Once you fill out the above information and click on `Sign up & Authorize`, you'll be taken back to the Publisher web portal:

<img width="598" alt="Screen Shot 2019-06-18 at 2 13 48 AM" src="https://user-images.githubusercontent.com/2602313/59657456-c0e25800-916e-11e9-9e4c-a474c0767c62.png">

Clicking on `Go to Uphold` will take you back to the Uphold account and you'll need to fill out the remaining information:

<img width="1071" alt="Screen Shot 2019-06-18 at 2 14 52 AM" src="https://user-images.githubusercontent.com/2602313/59657487-dfe0ea00-916e-11e9-906e-a88d6f0c941b.png">

I managed to fill out all the information and setup my 2FA without any problems using the default shield settings.

**Comment by kjozwiak** [comment] 2019-06-18 06:22
However, I'm running into an issue when attempting to KYC with Uphold. Once I've created an account, I go through the KYC process and select "License" as my identification. I accept all the permission prompts from Brave to let Brave us the web cam and run into the following error every time:

<img width="1195" alt="Screen Shot 2019-06-18 at 1 43 26 AM" src="https://user-images.githubusercontent.com/2602313/59657677-65649a00-916f-11e9-8864-e2221921661e.png">

Once the above fails, clicking on `Retry` takes you back to the main Uphold page and you'll see the following:

<img width="1027" alt="Screen Shot 2019-06-18 at 1 44 20 AM" src="https://user-images.githubusercontent.com/2602313/59657703-7d3c1e00-916f-11e9-908b-0c1a1bd88b74.png">

The only data that I ended up providing was my address without ID because the above failed but it seems like Uphold accepted the application even though it's missing information and put it under review. I'm basically stuck now until Uphold asks for more information or locks my account due to incorrect/insufficient information. Retrying the KYC process won't work as you're already in a "Pending" state.

@mandar-brave I managed to reproduce the above three times. I think this is a major issue in terms of users being able to KYC without any issues. Has anyone run into the above before?

**Comment by diracdeltas** [comment] 2019-06-18 22:50
@kjozwiak thanks for the detailed repro steps; i edited the issue title accordingly

**Comment by bsclifton** [comment] 2019-06-18 23:47
Exceptions that we added before (when doing in-product KYC via a modal) can be seen here:
https://github.com/brave/brave-core/pull/898/files

**Comment by diracdeltas** [comment] 2019-06-22 00:06
i have a fix for this; will add tests then open

**Closed** 2019-06-27 18:25 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/shields, feature/shields/adblock, priority/P2, release-notes/include

**Comment by LaurenWags** [comment] 2019-08-22 16:15
@brave/legacy_qa when testing this issue, please test on new and upgraded profiles.

**Comment by LaurenWags** [comment] 2019-08-26 13:32
I'm still having trouble with this one. @kjozwiak @diracdeltas could one of you take a look to see if you see the same? 

At the step where I have to upload the front of my drivers license I am getting the below screen (I have confirmed that I am trying to upload a .png file):
![Screen Shot 2019-08-26 at 9 28 41 AM](https://user-images.githubusercontent.com/28145373/63694291-1b89d700-c7e4-11e9-8340-e027e20cdb04.png)

If I go to shields, I see this:
![Screen Shot 2019-08-26 at 9 30 39 AM](https://user-images.githubusercontent.com/28145373/63694343-39573c00-c7e4-11e9-9928-3b85507f424a.png)

![Screen Shot 2019-08-26 at 9 31 34 AM](https://user-images.githubusercontent.com/28145373/63694389-55f37400-c7e4-11e9-89cf-546816c94213.png)

Allowing all device recognition attempts will allow my KYC to proceed. Seems like maybe we need something additional for this issue to be resolved?
