### ISSUE TITLE
Brave force exits while opening a new tab. 

### ISSUE THREAD

**Issue by Vidhan31** [brave/brave-browser#13454] opened 2021-01-09 16:20 UTC
## Description 
Since past one week, Brave force exits while opening a new tab. While the issue persisted for months but it was a rare occurrence and thought it was obvious as I was using a nightly build. However the issue is now frequent, making Brave unusable. One thing to note it happens only when I close a existing tab after finishing using it & then open a new tab.

## Steps to reproduce 

   1. Open Brave browser. 
   2. Go to any website.
   3. Close that tab & open a new tab. 

## Actual result 
Brave freezes and force exits. 

## Expected result
Brave should open a new tab without any problem. 

## Issue reproduces how often 
Easily reproduced. 

## Version/Channel Information:
 Specific to Nightly. 

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM 
   - Device type (Phone, Tablet, Phablet): Phone 
   - Android version: 10
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

This is what logs are after Brave force exits:
https://del.dog/egolilehip

**Comment by srirambv** [comment] 2021-01-12 07:55
Can you try upgrading to current nightly build? I don't see any crashes on it.

**Comment by Vidhan31** [comment] 2021-01-12 18:46
Currently I am on Brave Nightly version 1.20.72 and unfortunately the issue still persists. https://imgur.com/gallery/9XTv5W2

**Comment by Vidhan31** [comment] 2021-01-12 21:37
> Can you try upgrading to current nightly build? I don't see any crashes on it.

I can confirm this is the issue. 👇
https://github.com/brave/brave-browser/issues/13494

Browser doesn't crash while widget is enabled.

**Comment by bsclifton** [comment] 2021-01-13 06:55
oh wow - thanks for reporting @Vidhan31 - I'm going to close this as a duplicate of https://github.com/brave/brave-browser/issues/13494 since it seems to be the same issue

**Closed by bsclifton** 2021-01-13 06:55 UTC
Labels: OS/Android, crash, needs-more-info
