### ISSUE TITLE
Brave Ads should not be shown when the device is offline

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3700] opened 2019-03-13 11:47 UTC
## Description 

Ads shown when device is offline 

## Steps to Reproduce

   1. Install dev build 
   2. Enable rewards and enable ads 
   3. Disconnect device from network and keep the browser active
   4. ads shown up even when there is no network

## Actual result:

![IMG_20190312_092845](https://user-images.githubusercontent.com/17010094/54276554-04239e00-4564-11e9-9122-f4485f3f73ea.jpg)

## Expected result:
No ads should be shown when there is no active internet connection

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Dev build

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on Dev
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A

### Additional Information

May be related to #3116
cc: @tmancey @jsecretan @mandar-brave

**Comment by NumDeP** [comment] 2019-07-14 21:43
I almost created another issue titled, 'Disabled - Continue running background apps when Brave is closed' should not display ads when the browser is closed. Which of course it does in the latest stable version I'm running 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit) on OpenSuse

**Comment by tmancey** [comment] 2019-07-15 23:23
> I almost created another issue titled, 'Disabled - Continue running background apps when Brave is closed' should not display ads when the browser is closed. Which of course it does in the latest stable version I'm running 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit) on OpenSuse

I am unable to reproduce when the browser is closed, can you please provide steps, i.e. do you minimize or quit the browser and if so, where do you click the Quit option please. Thank you

**Comment by NumDeP** [comment] 2019-07-16 13:21
I'm pretty sure I pressed 'Exit'. 

In addition, just in case you were wondering, I also have 5 ads to be shown in an hour, monthly contribution set to lowest, minimum page time before log is at 1 minute and minimum visit for publisher relevancy is set to 1 visit.

I'd should mention that it only happened the once and felt it was worth reporting because the browser was off, not minimised. I'd update this comment box cc'ing your username if it does occur again.

**Comment by tmancey** [comment] 2019-07-16 16:31
@NumDeP thank you

**Comment by tmancey** [comment] 2019-11-29 12:40
Only affects Windows and Linux. macOS is working as expected

**Comment by ColinPanarra** [comment] 2021-02-25 18:57
Hi, I'm new to open-source contributions and feel like this could be a good first problem! 
Could you please help point me to where I should look to find/work on this error?

**Comment by tmancey** [comment] 2021-02-26 18:09
@ColinPanarra Please check out `net::NetworkChangeNotifier::IsOffline()` and https://source.chromium.org/chromium/chromium/src/+/master:net/base/network_change_notifier.cc?q=NetworkChangeNotifier::IsOffline()&ss=chromium%2Fchromium%2Fsrc

**Comment by tmancey** [comment] 2021-03-08 07:09
Confirmed still an issue on 1.23.23

**Comment by tmancey** [comment] 2022-06-07 22:47
Closing as the Chromium API is a pretty strong indicator that the user won't be able to connect to remote sites but is not guaranteed

**Closed by tmancey** 2022-06-07 22:47 UTC
Labels: bug, OS/Linux, OS/Windows, feature/ads
