### ISSUE TITLE
Update popup is visible when there is new update on MacOS

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#2700] opened 2018-12-22 19:01 UTC
Reported by @NejcZdovc. Update popup is visible when update is available on macos.
This popup should not be visible.

![sparklepopup](https://user-images.githubusercontent.com/6763301/50377812-24853180-05e1-11e9-8e2f-41e82c4da820.png)

@simonhong is this something we can change in Sparkle?

**Comment by Liunkae** [comment] 2018-12-23 03:58
The version number in the "Get Info" window is also incorrect.
![](https://user-images.githubusercontent.com/19424103/50380683-5673b380-0634-11e9-95b3-ec390357678d.png)

**Comment by simonhong** [comment] 2018-12-31 01:56
@NejcZdovc  This popup should not be visible to use because we uses background update mode in sparkle. How did you see this popup?

**Comment by simonhong** [comment] 2018-12-31 03:03
This issue includes two kinds issues.
* Update popup is visible when there is new update on MacOS
* Our own version number isn't displayed at some places

This issue is changed for first issue and other issue will be created for second issue.

**Comment by mherrmann** [comment] 2022-03-10 07:14
I believe this is a duplicate of #9562 and am therefore closing it.

**Closed by mherrmann** 2022-03-10 07:14 UTC
Labels: bug, priority/P5, QA/Yes
