### ISSUE TITLE
Use Brave icon instead of Chrome icon

### ISSUE THREAD

**Issue by pragyanone** [brave/brave-browser#11507] opened 2020-08-29 07:39 UTC
https://amp.reddit.com/r/Android/comments/5jedw4/til_in_android_chrome_if_you_try_to_swipe_up_the/

In this trick/ Easter Egg, chrome logo is diplayed. It would be better if the lion icon of Brave-browser is displayed here.
Just a comment for individuality.

**Comment by srirambv** [comment] 2020-08-31 05:11
Dupe of #9867

**Closed by srirambv** 2020-08-31 05:11 UTC
