### ISSUE TITLE
disconnect and reconnect different Uphold wallet  shows error on brave://rewards

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5817] opened 2019-08-27 15:53 UTC
## Description 
If you disconnect your first wallet from brave://rewards and reconnect with a second, different wallet, brave://rewards page shows an error and you can't get away from it. Additionally, if you open the panel, it is not showing the balance of the second wallet.

## Steps to Reproduce

   1. Enable Rewards, click on Verify Wallet and proceed to create an account with Uphold or login with an existing account. (I logged in with an existing, un KYC'd account. If you create a new one, you need to complete the name, location, etc portion and verify your email address to gain access to the Uphold Dashboard).
   2. On the Uphold Dashboard, go to your profile > Applications > Authorized Applications.
   3. Remove Brave Browser.
   4. Logout of Uphold.
   5. Go back to brave://rewards.
   6. Click on 'Disconnected'.
   7. Create a new account or Sign in with a different existing account (my second account here was KYC'd, but I don't know that it matters).
   8. Open a new tab and navigate to brave://rewards.

## Actual result:
See this on brave://rewards
![Screen Shot 2019-08-27 at 11 31 46 AM](https://user-images.githubusercontent.com/28145373/63786714-91fc0700-c8c0-11e9-99f6-2e2c44598445.png)

Additionally, if you open the panel, you will see that your balance is not accurately reflected (my second account connected has a Brave Browser card balance of 25 BAT, but panel is showing 0 BAT) and no error:

![Screen Shot 2019-08-27 at 11 51 53 AM](https://user-images.githubusercontent.com/28145373/63787015-164e8a00-c8c1-11e9-911a-1e2ef6f131c1.png)

Note - once you open the panel, brave://rewards page may not show the error immediately but it comes back.

## Expected result:
No error, able to connect second account without problems.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.116 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
cc @mandar-brave

**Comment by NejcZdovc** [comment] 2019-09-04 13:18
@LaurenWags I can't reproduce this one. Let's test it on the latest nightly when we land everything today. Closing for now. Please reopen if you can still reproduce it tomorrow

**Closed by NejcZdovc** 2019-09-04 13:18 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/rewards

**Comment by LaurenWags** [comment] 2019-09-05 17:16
Unable to reproduce with 

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X
