### ISSUE TITLE
Webpage loading: blank page for several seconds

### ISSUE THREAD

**Issue by fear-the-beaver** [brave/brave-browser#3658] opened 2019-03-11 15:47 UTC
## Description 
Some webpages like https://tools.usps.com/go/TrackConfirmAction!input.action and https://www.theverge.com/ stay blank for 3-5 seconds before showing the content.

## Steps to Reproduce

   1. Enable shields in Brave (ads and trackers, HTTPs, block 3rd party cookies and device recognition)
   2. Access https://tools.usps.com/go/TrackConfirmAction!input.action or https://www.theverge.com/ 

## Actual result:

    1. Blank page is being displayed for 3-5 seconds.
    2. Page elements start loading up.

## Expected result:

   1.  Page elements start loading up.

## Reproduces how often: 

100%

## Brave version (brave://version info)

**Desktop:**

Brave | 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)
-- | --
Revision | da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS | Mac OS X

**Mobile:**

Brave | 1.0.84 Chromium 72.0.3626.121

OS | Android 9

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Not tested

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 

Yes

- Is the issue reproducible on the latest version of Chrome? 

Not tested

**Comment by gabrielhug** [comment] 2019-03-12 21:15
This seems to be related to these sites' use of Google Optimize's anti-flicker page hiding.

The issue exists for me even when the brave extension is disabled with the `--disable-brave-extension` command line argument, but not when the brave extension is enabled and shields are disabled. Reproducible on beta and dev, but not in Chrome.

**Comment by rebron** [comment] 2019-03-15 16:27
cc: @kjozwiak to check on where this is getting tripped up.

**Comment by kjozwiak** [comment] 2019-07-26 21:45
@fear-the-beaver @gabrielhug this was most likely resolved by https://github.com/brave/brave-browser/issues/4402 and released in `0.66.x` on `June 25, 2019`.

I went through a view cases loading https://www.theverge.com/ and didn't run into any issues. I'm going to close this off. If you're still running into the above issue, please feel free to re-open.

**Closed** 2019-07-26 21:45 UTC
Labels: duplicate, webcompat
