### ISSUE TITLE
Make Youtube to work with Leo for transcripts

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#34666] opened 2023-12-01 19:09 UTC
We should re-use desktop's functionality for that

**Comment by petemill** [comment] 2023-12-17 22:30
It should already be using desktop functionality for Youtube, there is no platform conditional code for this as far as I'm aware

**Comment by mattmcalister** [comment] 2024-01-31 15:09
Hoping Leo with Youtube on Android gets resolved by https://github.com/brave/brave-browser/issues/34945

**Comment by petemill** [comment] 2024-02-27 10:12
Closing as duplicate of https://github.com/brave/brave-browser/issues/34945

**Closed by petemill** 2024-02-27 10:12 UTC
Labels: priority/P3, QA/No, release-notes/exclude, OS/Android, features/P3A, browser-ai
