### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by HasselHenric** [brave/brave-browser#42337] opened 2024-11-18 09:15 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.73.89 Chromium: 131.0.6778.69
Operating System: Linux 6.6.51+rpt-rpi-2712

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open Brave
2. Go to any adress
3. Wait for 10 - 30 seconds

Info from Journalctl:
nov 18 10:11:25 Desktop1 systemd-coredump[8670]: [🡕] Process 8442 (brave) of user 1000 dumped core.
                                                 
                                                 Module libsystemd.so.0 from deb systemd-252.31-1~deb12u1.arm64
                                                 Module libudev.so.1 from deb systemd-252.31-1~deb12u1.arm64
                                                 Stack trace of thread 1:
                                                 #0  0x00005556562f1534 n/a (brave + 0x8111534)
                                                 #1  0x00005556562f1528 n/a (brave + 0x8111528)
                                                 #2  0x00005556525d8d74 n/a (brave + 0x43f8d74)
                                                 #3  0x00005556525db49c n/a (brave + 0x43fb49c)
                                                 #4  0x00005556579375b0 n/a (brave + 0x97575b0)
                                                 #5  0x0000555655ae4e88 n/a (brave + 0x7904e88)
                                                 #6  0x0000555655ae4e88 n/a (brave + 0x7904e88)
                                                 #7  0x0000555654e6d980 n/a (brave + 0x6c8d980)
                                                 #8  0x0000555656eceef0 n/a (brave + 0x8ceeef0)
                                                 #9  0x00005556572d824c n/a (brave + 0x90f824c)
                                                 #10 0x0000555654340444 n/a (brave + 0x6160444)
                                                 #11 0x0000555654340444 n/a (brave + 0x6160444)
                                                 #12 0x00005556543419d4 n/a (brave + 0x61619d4)
                                                 #13 0x000055565433f4c8 n/a (brave + 0x615f4c8)
                                                 #14 0x00007fff7bf57740 __libc_start_call_main (libc.so.6 + 0x27740)
                                                 #15 0x00007ffff5eac6c8 n/a (n/a + 0x0)
                                                 ELF object binary architecture: AARCH64
nov 18 10:11:23 Desktop1 systemd[1]: Started drkonqi-coredump-processor@0-8669-0.service - Pass systemd-coredump journal entries to relevant user for potential DrKonq>
nov 18 10:11:23 Desktop1 systemd[1]: Started systemd-coredump@0-8669-0.service - Process Core Dump (PID 8669/UID 0).

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/01c51100-8605-eb0c-0000-000000000000

**Comment by bsclifton** [comment] 2024-12-09 18:41
Thanks for reporting! This is a duplicate of https://github.com/brave/brave-browser/issues/42315

**Closed by bsclifton** 2024-12-09 18:41 UTC
Labels: closed/duplicate, crash, OS/Linux
