### ISSUE TITLE
"youtube.com on YouTube 'creator'" attribution shows up in auto-contribute list

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15216] opened 2021-04-09 20:46 UTC
## Description 
"youtube.com on YouTube 'creator'" shows up in auto-contribute list

## Steps to Reproduce

   1.  new profile, launch with `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=4`
   2. enable Rewards
   3. accept the UGP BAT grant on staging
   4. load `youtube.com`
   5. search for `Jonathan Sampson`
   6.click on `Jonathan Sampson` 
   7. click on `Videos`
   8. click on the `Netscape, circa 1994.` video and play it
   9. wait for Auto-Contribution to happen
   10. load `brave://rewards-internals` and/or `brave://rewards` and look at the AC entries

## Actual result:

The unverified `youtube.com on YouTube` creator shows up in the Auto-Contribute list, alongside verified creators.

<img width="677" alt="Screen Shot 2021-04-09 at 1 17 38 PM" src="https://user-images.githubusercontent.com/387249/114238577-b263c280-9939-11eb-8433-4a0bd506220f.png">

<img width="1312" alt="Screen Shot 2021-04-09 at 1 24 27 PM" src="https://user-images.githubusercontent.com/387249/114238743-fc4ca880-9939-11eb-8008-496d876cba35.png">

## Expected result:

Not 100%; first time I've seen this appear like this?

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 1.23.69 Chromium: 90.0.4430.61 (Official Build) (x86_64)
-- | --
Revision | dced74d4124b26b14126b611853d33512b60c7b6-refs/branch-heads/4430@{#1115}
OS | macOS Version 11.2.3 (Build 20D91)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @LaurenWags @zenparsing @emerick

**Comment by stephendonner** [comment] 2021-04-09 20:50
Forgot to mention; not a regression, as @LaurenWags reproduced it this on `1.22.x` as well.

**Comment by thefallofbecause** [comment] 2021-05-04 23:00
I'm seeing a similar (assuming related) issue in beta 1.24.60/76.

Visiting a verified channel directly adds the unverified YouTube account to the AC list, but not the verified creator.
<img width="691" alt="Screen Shot 2021-05-05 at 01 34 45" src="https://user-images.githubusercontent.com/8562416/117079998-9a6b3d00-ad45-11eb-8275-8a40e57e170e.png">

The verified creator is only added when one of their videos is opened/played.

**Comment by Miyayes** [comment] 2023-02-03 02:08
Closing as dupe of: https://github.com/brave/brave-browser/issues/22859

**Closed by Miyayes** 2023-02-03 02:08 UTC
Labels: bug, feature/rewards, QA/Yes, release-notes/include, OS/Desktop
