### ISSUE TITLE
`Brave Software API keys are missing` on initial launch

### ISSUE THREAD

**Issue by Sh1d0w** [brave/brave-browser#1152] opened 2018-09-17 03:58 UTC
## Test Plan

* launch Brave using a brand new profile and sure you're not seeing the `Brave Software API keys are missing` notification
* after the initial launch, restart Brave a few more times and ensure that you're not seeing the `Brave Software API keys are missing` notification

## Description 
When Brave is launched for first time, during load an error message appears below the Url bar

## Steps to Reproduce

   1. Open Brave

## Actual result:
![Error](https://i.imgur.com/Rr9tUF3.jpg)

## Expected result:
No error

## Reproduces how often: 
Every time

## Brave version (chrome://version info)
0.55.3 Chromium: 70.0.3538.12 (Official Build) dev (64-bit)

**Comment by srirambv** [comment] 2018-09-17 14:07
That is expected for now. Will be removed in future. Dupe of #1061

**Comment by bsclifton** [comment] 2018-09-17 16:49
Re-opened; this should not be showing on Release builds

**Comment by bbondy** [comment] 2018-09-22 13:11
I think we just need to hide the whole bar instead of just the learn more which was done previously. I talked to @w0ts0n and he said the safe browsing stuff is working correctly, and also the geolocations stuff is working correctly.

**Comment by ltilve** [comment] 2018-09-28 10:29
So it seems that `HasOAuthClientConfigured` is false, so I have created a patch to hide the whole bar in that case as it seems all the functionality is working as expected.

If it were necessary to obtain a proper `OAuth` key, these are the steps to request it http://www.chromium.org/developers/how-tos/api-keys
(Slightly clearer here https://gist.github.com/cvan/44a6d60457b20133191bd7b104f9dcc4)

https://console.cloud.google.com/projectselector/apis/credentials/oauthclient
![credentials](https://user-images.githubusercontent.com/2891281/46203423-feb9fa80-c319-11e8-83a3-372811265791.png)

And then adding them to the `args.gn`
```
google_api_key = "your_api_key"
google_default_client_id = "your_client_id"
google_default_client_secret = "your_client_secret"
```

**Comment by srirambv** [comment] 2018-10-10 21:21
Issue still happens on `0.55.12`. Even after nuking the profile and installing fresh still shows the API notification bar. Reproduced on Windows and Linux. @kjozwiak @LaurenWags reproduced on macOS

**Comment by bbondy** [comment] 2018-10-12 00:59
Just noting I wasn't able to reproduce this with a debug build locally on master. But the fix seems to be on all branches.  Maybe it is only showing up in release builds or official builds or something like that.

**Closed** 2018-10-12 03:36 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, release/blocking
