### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by andybn** [brave/brave-browser#34974] opened 2023-12-19 21:53 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.104 Chromium: 120.0.6099.115
Operating System: Mac OS X 14.1.2

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Nothing special, it randomly crashes a lot of times since last update. It cannot be used.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/2b730e00-8bde-260b-0000-000000000000

**Comment by itsthejb** [comment] 2023-12-20 11:08
Sounds similar to #34978

**Comment by rebron** [comment] 2023-12-21 18:00
closing as dupe of https://github.com/brave/brave-browser/issues/34909.

**Closed by rebron** 2023-12-21 18:00 UTC
Labels: closed/duplicate
