### ISSUE TITLE
Surface smooth scrolling flag to settings and make as default

### ISSUE THREAD

**Issue by joewood9364** [brave/brave-browser#41102] opened 2024-09-17 14:23 UTC
### Description

Surface smooth scrolling flag to settings and make as default

### Steps to reproduce

Surface smooth scrolling flag to settings and make as default

### Actual result

Surface smooth scrolling flag to settings and make as default

### Expected result

Surface smooth scrolling flag to settings and make as default

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Surface smooth scrolling flag to settings and make as default

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Surface smooth scrolling flag to settings and make as default

**Comment by rebron** [comment] 2024-09-19 21:50
Closing as wontfix due to the conversation in this chromium issue: https://issues.chromium.org/issues/359747082

"WSP (Windows Scrolling Personality) was identified as a source of battery regressions, and we are planning to remove the code. We already disabled the feature in Edge."

**Closed by rebron** 2024-09-19 21:50 UTC
Labels: OS/Desktop
