### ISSUE TITLE
Crash Report: when using "close other tabs"

### ISSUE THREAD

**Issue by cschaffner** [brave/brave-browser#34933] opened 2023-12-15 19:25 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.104 Chromium: 120.0.6099.115
Operating System: Mac OS X 14.1.2

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open at least three tabs
2. Right-Click  on the last (right-most) tab, and choose "Close other Tabs".
3. Brave crashes after a while.

No crash occurs when using the "Close Tabs to the Right" command, which is a feasible work-around for this problem.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/09e70400-100a-300b-0000-000000000000

**Comment by cschaffner** [comment] 2023-12-15 19:29
Same as
#34912
#34905

**Comment by rebron** [comment] 2023-12-15 23:46
Thanks. closing as duplicate of https://github.com/brave/brave-browser/issues/34909

**Closed by rebron** 2023-12-15 23:46 UTC
Labels: closed/duplicate, crash
