### ISSUE TITLE
Claim grant message remains after claiming grant via Rewards panel

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#7665] opened 2020-01-08 17:32 UTC
## Description 

The "Claim grant" message remains on the brave://rewards page after claiming a grant via the rewards panel

## Steps to Reproduce

   1. Clean profile
   2. Enable Rewards
   3. Claim a grant *via the Rewards panel*

## Actual result:

"Claim grant" message remains at the top of the brave://rewards settings page

## Expected result:
The "Claim grant" message should auto-dismiss after claiming the grant via the Rewards panel

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment] 2020-01-22 19:52
@emerick  can you verify if the grant is claimed?

**Comment by emerick** [comment] 2020-01-22 22:15
@srirambv Yes, it is claimed. When the second message pops up, you can't claim the grant from it as it's already been retrieved. I suspect that there is a disconnect between the panel and the rewards settings page, i.e., the rewards settings page isn't correctly informed that the grant was claimed from the panel so it proceeds to show the message.

**Comment by srirambv** [comment] 2020-01-23 12:17
> the rewards settings page isn't correctly informed that the grant was claimed from the panel so it proceeds to show the message.

This happens on desktop as well. So might need a library fix for this? cc: @NejcZdovc

**Comment by SergeyZhukovsky** [comment] 2020-03-06 19:28
I can't replicate that on latest master. I talked with @emerick and most likely that commit from his PR fixed it https://github.com/brave/brave-core/commit/ad51870faed5ff487b431a71fa95414d0c59d14d. No problem on Android anymore. @NejcZdovc do we need to move it to desktop only as @srirambv mentioned that the problem is there as well or do we have something separate there?

**Comment by NejcZdovc** [comment] 2020-03-06 20:37
@srirambv if this is problem on desktop please file an issue with STR. Thank you
@SergeyZhukovsky if this is not a problem anymore we can just close this one

**Comment by SergeyZhukovsky** [comment] 2020-03-06 20:57
ok, closing that issue

**Closed by SergeyZhukovsky** 2020-03-06 20:57 UTC
Labels: OS/Android, QA/Test-Plan-Specified, QA/Yes, android-core-release, feature/rewards, priority/P2
