### ISSUE TITLE
Show Brave Stats toggle broken

### ISSUE THREAD

**Issue by cdes5804** [brave/brave-browser#25663] opened 2022-09-28 02:15 UTC
## Description 

"Show Brave Stats" toggle is broken and the browser won't turn it off.

## Steps to Reproduce

   1. Open "New Tab".
   2. Click on "Show Brave Stats" switch in Customize Dashboard setting.

## Actual result:

https://user-images.githubusercontent.com/48202567/192671998-babb2a85-ed0a-4ee2-8c39-df4760a5212e.mov

## Expected result:
Show be able to turn off display of brave stats.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.44.101 Chromium: 106.0.5249.65 (Official Build) (x86_64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment] 2022-09-28 06:28
Confirmed in 

Brave | 1.44.101 Chromium: 106.0.5249.65 (Official Build) (x86_64)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | macOS Version 11.7 (Build 20G817)

This is working in



Brave | 1.46.15 Chromium: 106.0.5249.65 (Official Build) nightly (x86_64)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | macOS Version 11.7 (Build 20G817)



cc @sangwoo108 - is there an uplift we need to take in the next maintenance release/hotfix?

**Comment by stephendonner** [comment] 2022-09-28 06:28
Looks like we need https://github.com/brave/brave-browser/issues/24985

cc @fallaciousreasoning

**Comment by fallaciousreasoning** [comment] 2022-09-28 20:37
I've created the uplift pr, and requested an uplift :smile:

**Comment by kjozwiak** [comment] 2022-10-05 18:33
Closing the above as this has been fixed via https://github.com/brave/brave-core/pull/14839 and will be uplifted into `1.44.x` via https://github.com/brave/brave-core/pull/15264.

**Closed by kjozwiak** 2022-10-05 18:33 UTC
Labels: bug, priority/P3, QA/Yes, release-notes/include, regression, OS/Desktop

**Comment by stephendonner** [comment] 2022-10-05 22:34
## Verified `PASSED` using 

Brave | 1.45.87 Chromium: 106.0.5249.91 (Official Build) beta (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. install `1.45.87`
2. launched Brave
3. clicked on `Skip welcome tour`
4. clicked `Customize`
5. clicked `Brave Stats`
6. confirmed `Show Brave Stats` was toggled to `Enabled` / `On` and confirmed stats on the page
7. toggled `Show Brave Stats` to `Disabled`/ `Off`, and confirmed stats disappear
8. toggled back `On`
9. also context-clicked the 3 vertical dots and chose `Hide Brave Stats` and confirmed they disappeared


`step 6` | `step 7` | `step 8` | `step 9a` | `step 9b`
-------|-------|--------|--------|---------
<img width="1312" alt="Screen Shot 2022-10-05 at 6 27 12 PM" src="https://user-images.githubusercontent.com/387249/194175556-8ca24a5a-eeac-4348-af38-cd7b541d19a3.png"> | <img width="1312" alt="Screen Shot 2022-10-05 at 6 27 16 PM" src="https://user-images.githubusercontent.com/387249/194175570-57673f11-ff58-4379-a807-68e5fb3102cf.png"> | <img width="1312" alt="Screen Shot 2022-10-05 at 6 33 25 PM" src="https://user-images.githubusercontent.com/387249/194176053-fa800234-50c9-4ce8-ab96-768181058b70.png"> | <img width="1312" alt="Screen Shot 2022-10-05 at 6 27 28 PM" src="https://user-images.githubusercontent.com/387249/194175576-ebf62aad-9ff6-4e52-a568-16f8c80e5940.png"> | <img width="1312" alt="Screen Shot 2022-10-05 at 6 30 18 PM" src="https://user-images.githubusercontent.com/387249/194175701-17f76eda-91b9-47d2-8a77-4de335766e09.png">

**Comment by kjozwiak** [comment] 2022-10-05 22:44
Thanks for checking the above @stephendonner 👍 I'm going to close this off as a duplicate but I'll move it into `1.44.x` once we uplift via https://github.com/brave/brave-core/pull/15264.
