### ISSUE TITLE
[Android][Follow up #11092] Shields onboarding doesn't always show up when items are blocked

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11189] opened 2020-08-12 08:59 UTC
## Description 
[Follow up #11092] Shields onboarding doesn't always show up when items are blocked

## Steps to reproduce 

   1. Set VPN to India(at the time of testing)
   2. Clean install 1.12.112
   3. Click on Wikipedia top tile
   4. Ensure donation message shows up and shields has a blocked item
   5. No shields onboarding is shown
   6. Visit another page where ads are blocked
   7. Shields onboarding is shown 

## Actual result 
![11092-followup](https://user-images.githubusercontent.com/17010094/89996218-70875d00-dc82-11ea-9921-0ade587382f5.gif)

## Expected result
Should show onboarding whenever an item is blocked or detected in shields

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.12.112

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

_If you visit Wikipedia by typing in URL and you don't get the donation banner then you won't see anything blocked in shields. So **make sure you set VPN to a region where Wiki is asking for a donation**. At the time of testing, I had it for India where the donation banner showed up_

**Comment by srirambv** [comment] 2020-08-12 12:48
cc: @deeppandya @bsclifton @anthonypkeane @kjozwiak

**Comment by LaurenWags** [comment] 2020-08-12 19:01
Reproduced on Asus Zenfone (x86) with Android 6 using 1.12.112 BraveModernx86.apk.

**Comment by deeppandya** [comment] 2020-11-23 00:09
This should be fixed with latest version. @LaurenWags @srirambv can you please verify ?

**Comment by kjozwiak** [comment] 2020-12-02 21:04
> This should be fixed with latest version. @LaurenWags @srirambv can you please verify ?

@deeppandya re: latest version, do you mean the latest `master`? This was ~10 days ago so assuming we should try `1.19.x`?

**Comment by deeppandya** [comment] 2020-12-02 21:09
It should have been fixed in earlier release so if you can just verify it. I have verified it from my end.

**Comment by LaurenWags** [comment] 2020-12-03 00:30
yep, works for me using LG Nexus 5 (ARM) with Android 5.1 on `1.17.74` downloaded from GPS 👍 

![Screenshot_2020-12-02-19-27-23](https://user-images.githubusercontent.com/28145373/100947998-d8cda900-34d4-11eb-93d0-9e4657c226b0.png)

**Comment by bsclifton** [comment] 2020-12-27 17:22
@deeppandya can you link to the fix for this? And then we can close this out / put the milestone for where the fix landed 😄 Thanks!

**Comment by deeppandya** [comment] 2020-12-27 18:41
@bsclifton this should be fixed in latest release and I think @LaurenWags has updated the same in above comment. So I think it's safe to close it for now.

**Closed** 2020-12-27 23:02 UTC
Labels: OS/Android, QA/Yes, bug, feature/shields, onboarding, release-notes/exclude
