### ISSUE TITLE
[Desktop] Ads on Google search pages

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [brave/brave-browser#11597] opened 2020-09-04 13:44 UTC
## Description 
Recently, ads started to appear on Google search pages. I tried to switch `Trackers & ads blocking` from `Standard` to `Aggressive` -- it didn't helped.

## Steps to Reproduce

   1. Search "google it" in Google

## Actual result:
You see adds above actual search results

## Expected result:
No ads

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Brave | 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Linux

**Comment by ryanbr** [comment] 2020-09-22 01:42
Hey @GrigoriyMikhalkin   Is this still occuring? (well in Version 1.14.81)

**Comment by GrigoriyMikhalkin** [comment] 2020-09-22 08:49
@ryanbr Hi, yep, still occuring for me.

**Comment by ryanbr** [comment] 2020-09-22 11:21
Unless there is a possible extension inserting google ads. I would test in private-window mode with no extension (or possibly a new Brave profile as a test)

Here is what I see: 

![google-ads-diff](https://user-images.githubusercontent.com/1659004/93875879-ef63c100-fd29-11ea-8570-3ac1440ca478.png)

**Comment by bsclifton** [comment] 2020-09-22 17:18
@GrigoriyMikhalkin I may know what the problem is- let's try the following:
1. Visit brave://components/
2. Find `Brave Ad Block Updater` mine is set as version `1.0.706` (what is yours?)
3. Click the `Check for update` button
4. Try closing / re-opening Brave

Let us know if this solves

**Comment by GrigoriyMikhalkin** [comment] 2020-09-22 19:36
@ryanbr, @bsclifton Thanks for help!

@ryanbr Indeed, it was one of my extensions -- it actually was adding ads to Google and Bing search pages.

**Comment by bsclifton** [comment] 2020-09-22 19:41
@GrigoriyMikhalkin perfect! thanks for the update 😄 Glad you found it!

**Closed** 2020-09-22 19:41 UTC
Labels: OS/Desktop, feature/shields/adblock

**Comment by ryanbr** [comment] 2020-09-23 03:23
Great to see it was resolved, which extension was causing it @GrigoriyMikhalkin ?

**Comment by GrigoriyMikhalkin** [comment] 2020-09-23 07:24
@ryanbr It was some website color picker extension from Chrome Store. Unfortunately, i rushed deleting it and didn't remember which one exactly(name was "Color picker" which is very generic, there's a lot of of extensions with same name). ( And i'm pretty sure, it started adding ads only after some time after it was installed.
