### ISSUE TITLE
Automatically Focus on Leo AI Dialog Box Upon Opening

### ISSUE THREAD

**Issue by gnukeith** [brave/brave-browser#40825] opened 2024-09-03 17:55 UTC
### Platforms

Linux, macOS, Windows

### Description

Currently, when using the "CTRL + B" (Cmd+B on macOS) hotkey to open the Leo AI panel, the dialog box opens, but users need to manually click the text box to start typing. It would be much more convenient if the text input field were automatically focused, allowing users to begin typing immediately without the extra step of clicking the box.

**Comment by rebron** [comment] 2024-09-04 20:25
Closing as dupe of https://github.com/brave/brave-browser/issues/38703

**Closed by rebron** 2024-09-04 20:25 UTC
Labels: feature-request
