### ISSUE TITLE
File download doesn't work in Element (Matrix)

### ISSUE THREAD

**Issue by rkfg** [brave/brave-browser#23153] opened 2022-05-31 10:35 UTC
## Description 

Files in Element rooms can not be downloaded in Brave:
![2022-05-31_13-28-11](https://user-images.githubusercontent.com/184066/171153458-568661db-e5f9-4e4f-84c5-98a01cfd7b3c.png)
Works fine in Google Chrome 102.0.5005.61 and Chromium 101.0.4951.64 (on Debian Testing).

## Steps to Reproduce

   1. Sign in to https://app.element.io
   2. Enter any room with files or create a new one and post a file
   3. Try to download it

## Actual result:

Getting this vague message "Failed - Network error" while the download page shows an attempt to save a local blob.

## Expected result:
File is saved normally as in Chrome and Chromium.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

```
1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)
--
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | Linux
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

**Comment by rkfg** [comment] 2022-06-02 10:22
Yeah, same issue in all three of these. Blobs fail to download and I'm pretty sure it works in vanilla Chrome/Chromium.

**Comment by rebron** [comment] 2022-06-03 17:58
Closing as dupe of https://github.com/brave/brave-browser/issues/23171

**Comment by rebron** [comment] 2022-06-03 17:59
@rkfg Thanks for filing the issue.

**Closed by rebron** 2022-06-03 17:58 UTC
Labels: OS/Desktop
