### ISSUE TITLE
[Follow up to #37348] When device language/region is set to the allowlisted country (ex. USA) it is possible to enable `Rewards` for `Russia` and `Ukraine`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#38770] opened 2024-06-03 16:44 UTC
### Description

Follow-up to #37348

### Steps to reproduce

1. Set device language/region to the allowlisted country, for example, USA
2. Launch Brave > Tap `Rewards` icon
3. Start using Rewards > Select `Russia` or `Ukraine` > Continue
4. Tap `Done` > Tap `Rewards` icon > `Observe`

### Actual result

When the device language/region is set to the allowlisted country (ex. USA) it is possible to enable `Rewards` for `Russia` and `Ukraine`, but it is not possible to connect `custodian`. At the same time, it's not possible to do it for other countries from this list - https://github.com/brave/devops/wiki/Region%E2%80%90based-sanctions-blocking#category-3.

https://github.com/brave/brave-browser/assets/128532965/d903852c-c321-4c37-a850-262c8efc16cd

### Expected result

It must be not possible to **enable** `Rewards` for `Russia` and `Ukraine` based on this list https://github.com/brave/devops/wiki/Region%E2%80%90based-sanctions-blocking#category-3.

https://github.com/brave/brave-browser/assets/128532965/16523ed3-2779-4875-843c-935392443aad

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.67.98 
Chromium: 125.0.6422.112 (Official Build) beta (64-bit) 

### Device

- Brand/Model: Google Pixel 7
- Android version: panther_beta-user 14 AP31.240426.023 release-keys

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @zenparsing @Miyayes

**Comment by LaurenWags** [comment] 2024-06-03 17:16
Added `OS/Desktop` as this reproduces there as well.

Observed this behavior for Ukraine, Russia, Belarus, and Moldova as per https://bravesoftware.slack.com/archives/CJR5902AW/p1717429888783069?thread_ts=1717107096.424009&cid=CJR5902AW.

**Comment by GeetaSarvadnya** [comment] 2024-06-07 15:28
Good catch @hffvld !

The issue is reproduced on Linux, cases 5, 6 and 7 are failed due to this issue.

**Comment by Miyayes** [comment] 2024-06-11 17:16
This should be resolved with a backend change.

**Comment by Miyayes** [comment] 2024-06-11 17:50
@hffvld has verified that this is now resolved, thanks to backend change. 

>I can't enable Rewards anymore for Russia and Ukraine in build 1.67.112 when region set to the US  in Prod.

**Closed by Miyayes** 2024-06-11 17:51 UTC
Labels: bug, feature/rewards, priority/P1, QA/Yes, OS/Android, OS/Desktop

**Comment by GeetaSarvadnya** [comment] 2024-06-12 16:40
Verified the issue on Production and Staging both. The issue is fixed on Production but not on staging. 

Rewards can't be enabled on Production environment for Russia/Ukraine as expected
![image](https://github.com/brave/brave-browser/assets/38657976/f3dd1140-2ae5-4e90-95c5-92cac62d26fe)

**Comment by Miyayes** [comment] 2024-06-12 16:41
> Verified the issue on both Production and Staging env. The issue is fixed on Production but not on staging.
> 
> Rewards can't be enabled on Production environment for Russia/Ukraine as expected ![image](https://private-user-images.githubusercontent.com/38657976/339057712-f3dd1140-2ae5-4e90-95c5-92cac62d26fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMTA3MzcsIm5iZiI6MTcxODIxMDQzNywicGF0aCI6Ii8zODY1Nzk3Ni8zMzkwNTc3MTItZjNkZDExNDAtMmFlNS00ZTkwLTk1YzUtOTJjYWM2MmQyNmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE2NDAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYWQxMmZkODdiYzk1NDM4MjUyYzFjMzU1NzQ3MGE2NDkzZWY1OWIwMjFhYjk0Y2U3MGMyN2YyNTBkOGQyNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TlGqUKwTghBxP3Wc4gqLhveQd7sdlgagndCpRvgVIMM)

@GeetaSarvadnya Yes, I think this is because staging backend was not updated yet, so this is expected.
