### ISSUE TITLE
Pdf files can't opened in encrypted new window

### ISSUE THREAD

**Issue by sungerbob** [brave/brave-browser#3336] opened 2019-02-13 06:52 UTC
## Description 
Hi, I can't open pdf files in encrypted new window. Like banking or government website.

## Steps to Reproduce

1. Login to government website.
2. A new encrypted window shows up.
3. Pressing pdf button in new window.
4. A new window shows up, too.
5. Pdf editor gives error message below.
"PDF.js v2.0.673 (build: 31012570)
Message: Invalid PDF structure"

## Actual result:
Pdf editor gives error message below.
"PDF.js v2.0.673 (build: 31012570)
Message: Invalid PDF structure"

## Expected result:
Opens pdf.

## Reproduces how often: 
Everytime.

## Brave version (brave://version info)

Brave | 0.61.22 Chromium: 72.0.3626.81 (Official Build) dev (32-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
+ Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
+ No
- Is the issue reproducible on the latest version of Chrome? 
+ No

### Additional Information

I can open encrypted pdf file in new tab, not encrypted window. Also I recorded issue but I have to hide every detail on pdf file. Last seconds of the gif shows up pdf file successfully opened in new tab. Also this issue reproducible in Vivaldi 2.3.x and more versions.

![123](https://user-images.githubusercontent.com/31207969/52691795-0c8fb580-2f73-11e9-8458-78c4bd735bb8.gif)

**Comment by tomlowenthal** [comment] 2019-02-13 18:53
I don't know what you mean by "encrypted new window". Are you saying that you can't view PDF's which are only accessible after you've logged in?

**Comment by sungerbob** [comment] 2019-02-13 19:04
Yes, I can't open same pdf link after I logged out. It's like bank account, when I login my account info, a new window shows up and continue my job in there. In new window when I click pdf button, a new "dispatch" (you can see in gif) window shows up and opens pdf on it.

**Comment by tomlowenthal** [comment] 2019-02-15 00:35
I'm sorry, I'm still having trouble following you. Can you list out the step by step process you go through, what you expect, and what happens instead?

**Comment by sungerbob** [comment] 2019-02-16 19:23
![123123](https://user-images.githubusercontent.com/31207969/52904151-f6b31680-3238-11e9-81c5-d7ba3501fdaa.gif)

1. I login website
2. I click pdf button on right side
3. A new dispatch window shows up, it should open pdf not giving error "Invalid PDF scructure" on it.
4. But If I copy the pdf link to regular tab, browser successfully open pdf file without giving any error.

**Comment by tomlowenthal** [comment] 2019-02-19 19:08
@brave/legacy_qa Can you try to reproduce? Do we have a test resource for PDFs behind logins? I think @fmarier was working on a related issue, but I don't recall the details.

**Comment by fmarier** [comment] 2019-02-20 00:07
The issue I looked at was #1958, which was related to basic auth (#1788), but in this case, it looks more like #1287.

**Comment by kjozwiak** [comment] 2019-02-27 03:39
> @brave/legacy_qa Can you try to reproduce? Do we have a test resource for PDFs behind logins? I think @fmarier was working on a related issue, but I don't recall the details.

@tomlowenthal I think we can dupe this one to https://github.com/brave/brave-browser/issues/3474 where @jumde added a reproducible case. Unfortunately QA doesn't have any PDF cases (going to change this) that are behind authentication. I don't think this due to authentication and is a general PDF.js issue. I managed to reproduce this on my banking account as mentioned under https://github.com/brave/brave-browser/issues/3474#issuecomment-467710518.

**Comment by kjozwiak** [comment] 2019-02-27 03:43
Duplicate of #3474 as mentioned above. @tomlowenthal please re-open if you feel differently 👍

**Closed** 2019-02-27 03:42 UTC
Labels: duplicate
