### ISSUE TITLE
How to use a hardware wallet only

### ISSUE THREAD

**Issue by anishp55** [brave/brave-browser#19787] opened 2021-11-28 05:12 UTC
How does one use a ledger device for the wallet instead of having to create one through Brave?  We can import a seed phrase, but we cannot delete wallets, and I appears we cannot use a hardware device to import an existing one, unless we make a wallet first.  It feels like no one considered work flows.

**Comment by tredondo** [comment] 2021-11-28 10:24
Excellent question. It's really annoying that the default account can't be deleted, e.g. after importing a private key.

**Comment by srirambv** [comment] 2021-11-29 06:48
This is as per design. You need to have a wallet created in order to link you hardware wallet. You can't use the ledger seed to import your wallet into Brave wallet. 

cc: @jamesmudgett @bbondy

**Comment by anishp55** [comment] 2021-11-29 18:55
@srirambv can you elaborate please?  why do i need to have a wallet created in brave to be able to use a hardware wallet?
here is the current flow
1) i have my existing hardware wallet with my seed phrase on it
2) start brave, and create a wallet for no real reason since i am not going to be using it
3) connect my hardware wallet and then select the addresses i would like to use
4) profit.

what i envision the flow to look like
1) i have my existing hardware wallet with my seed phrase on it
2) start brave, and be given the option to use my existing hardware wallet with brave, i am not importing my seed phrase
3) profit.


also what is preventing me from using my seed phrase from ledger in the brave wallet?  the only thing that maybe be different is the derived wallet address, and current i can select from 3 diff types.

**Comment by bbondy** [comment] 2021-11-29 19:08
We're looking to allow hardware wallets without having to create an HD wallet here:
https://github.com/brave/brave-browser/issues/19693

I'll close this issue since this is a dupe of that one. Please feel free to follow that one though.

**Closed by bbondy** 2021-11-29 19:08 UTC
Labels: needs-discussion, feature/wallet, OS/Desktop
