### ISSUE TITLE
Github creators are not getting added to the Auto-Contribution table

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12454] opened 2020-11-02 09:25 UTC
## Description 

Github creators are not getting added to the Auto-Contribution table
## Steps to Reproduce

   1. Clean or upgraded profile 1.18.25 or 1.17.57
   2. Enable rewards / AC switch
   3. Open GH creator https://github.com/laurenwags in a NTP
   4. Spend min time so that creator gets added to the AC table ( even after 30 secs GH pub isn't added to AC table)
  

## Actual result:

Github creators are not getting added to the Auto-Contribution table

## Expected result:
Github creators should be added to the Auto-Contribution table

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.18.25 Chromium: 87.0.4280.40 (Official Build) nightly (64-bit)
-- | --
Revision | 349b9adbfb2784db684617c7731a57d1e61b3be0-refs/branch-heads/4280@{#863}
OS | Windows 10 OS Version 1903 (Build 18362.1139)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by LaurenWags** [comment] 2020-11-02 12:09
cc @emerick also since this occurs on 1.17.x per @GeetaSarvadnya notes in the description. maybe related to greaselion work for GH?

**Comment by NejcZdovc** [comment] 2020-11-02 12:25
closing this one as dupe of https://github.com/brave/brave-browser/issues/12107

**Closed by NejcZdovc** 2020-11-02 12:25 UTC
Labels: OS/Desktop, QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards, regression

**Comment by LaurenWags** [comment] 2020-11-02 12:35
@NejcZdovc this works with 1.16.x (current release). So it is expected that this will not work with 1.17.x?

**Comment by NejcZdovc** [comment] 2020-11-02 14:07
@LaurenWags yes
