### ISSUE TITLE
[Desktop] Command line args are listed twice after upgrade

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11040] opened 2020-07-31 14:04 UTC
## Description 

Command-line args are listed twice after upgrade
## Steps to Reproduce

   1. Clean profile 1.11.x
   2. Upgrade to 1.12.x
   3. Open chrome://version
   4. Command-line args are listed twice after upgrade
 . 

## Actual result:

Command-line args are listed twice after upgrade
![image](https://user-images.githubusercontent.com/38657976/89030688-98a3c180-d34e-11ea-834b-909dc14f924c.png)

## Expected result:

Command-line args should be listed once after upgrade
## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @darkdh

**Comment by Johann999** [comment] 2020-07-31 22:38
I have had this problem for months.
Almost all commands line args are duplicated.

**Comment by GeetaSarvadnya** [comment] 2020-08-04 12:46
Cmd line args are listed thrice in Windows 10 x64 - `1.12.105` 

![image](https://user-images.githubusercontent.com/38657976/89295366-81324480-d67e-11ea-98c7-5d0eb08d1597.png)

**Comment by rebron** [comment] 2020-08-04 18:37
Closing as dupe of https://github.com/brave/brave-browser/issues/8263

**Closed by rebron** 2020-08-04 18:37 UTC
Labels: OS/Desktop, OS/Windows, QA/Test-Plan-Specified, QA/Yes, misc/command-line-args, regression
