### ISSUE TITLE
Kaspersky Free Antivirus thinks Brave beta is a trojan

### ISSUE THREAD

**Issue by avion540** [brave/brave-browser#1498] opened 2018-10-10 18:55 UTC
## Description 
The free version of Kaspersky Free Antivirus thinks the Brave beta installer is a trojan. I believe it is tor that is tripping the detection.

## Steps to Reproduce
   1. Install Kaspersky Free Antivirus
   2. Run Full Scan
   3. Brave beta detected as trojan and completely removed from the computer. If trying to run the Brave beta installer, the installer will halt and the exe deleted. 

## Actual result:
Screenshot of Kaspersky Free Antivirus:
![image](https://user-images.githubusercontent.com/14863961/46758842-b2a87780-cc82-11e8-8fe7-58ab3fbc3650.png)

Full file path of detection: C:\Users\USER\AppData\Local\BraveSoftware\Brave-Browser-Beta\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.1\tor-0.3.3.8-win32-brave-5

## Expected result:
Brave able to run without triggering a trojan detection

## Reproduces how often: 
I installed Kaspersky Antivirus after installing the Brave beta. When it deleted Brave, I tried to re-install Brave, but it stopped the install and deleted the temporary installer exe.

## Brave version (chrome://version info)
Latest Windows Brave beta installer

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes
- Does it reproduce on browser-laptop? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information
N/A

**Comment by Brave-Matt** [comment] 2018-10-12 09:21
They finally got back to me:
![](https://i.imgur.com/SvrV6BY.jpg)

**Comment by Mephiztopheles** [comment] 2018-10-19 20:59
until that fix, there is no way to use brave ;)

**Comment by Brave-Matt** [comment] 2018-11-02 18:47
@Mephiztopheles,
I had a user manage to whitelist Brave in Kaspersky recently. I imagine that the steps will need to be repeated for any new build/install and potentially for updates to the browser. You may find it useful in the interim though:
https://community.brave.com/t/auto-updater-for-dev-builds-is-detected-as-trojan-by-kaspersky-antivirus/34917/7?u=mattches

**Comment by perariontaeadastra** [comment] 2018-12-09 10:16
+1
Ms Windows 7.
![2018-12-07 22_41_47](https://user-images.githubusercontent.com/20157473/49695985-4cb56f00-fba3-11e8-816a-457accf70fc3.png)
The problem thought is that after this "false-positive" the OS has been damaged.

**Comment by starper** [comment] 2018-12-09 12:58
Btw the title of this issue is a bit misleading, since there are problems with all channels, not just `beta`. The only difference is that `brave` from `release` channel installs without any problems, but when the time for updates comes, `Kaspersky` will scream at you and delete everything.
Optional disabling of autoupdates could be a temporary workaround here. Don't know if it's possible though.

**Comment by Mephiztopheles** [comment] 2018-12-09 13:46
You cannot start brave because it will automatically search for update. Even if you don't actually start it, it will search for updates and Kaspersky will send messages in five second interval.

**Comment by bsclifton** [comment] 2018-12-31 17:32
Two +1's from users in https://github.com/brave/browser-laptop/issues/1489

**Comment by Brave-Matt** [comment] 2019-01-23 17:40
In latest correspondence with Kaspersky they've confirmed that Brave users should no longer get flagged when attempting to download, install or update Brave.
[More info on Community](https://community.brave.com/t/update-on-brave-being-flagged-as-malware-false-positive-by-kaspersky-anti-virus/43152)

**Comment by riastradh-brave** [comment] 2019-05-06 21:29
We have tried to address this in two ways:

1. Brave is no longer bundled with the tor daemon itself; rather, Brave downloads an extension which contains the tor daemon, _if_ you open a private window with Tor.  If you don't do that, then Brave never even has a tor daemon executable on your system.
2. The tor daemon executable that we distribute is now signed, which placates some antivirus systems that would object to having unsigned executables.  (See https://github.com/brave/brave-browser/issues/3229 for more details.)

We have had confirmation that Kaspersky's free antivirus no longer objects to Brave, so I'm going to close this, but if the symptoms persist, please feel free to open a new issue!

**Closed by riastradh-brave** 2019-05-06 21:29 UTC
Labels: priority/P5, support
