### ISSUE TITLE
Brave is not saving passwords using the in-browser password manager

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#6776] opened 2019-11-06 00:14 UTC
## Description 

Many users have reported that Brave will no longer save their login/password data. After entering credentials into a forum, they're offered to save the password via browser prompt, but the data never gets stored. Data saved in this way is not reflected in `Settings --> Autofill --> Passwords` either.

## Steps to Reproduce

**These are the steps that the users went through when this issue occurred** -- I was unable to reproduce the issue on my end.

   1. Ensure the `Offer to save Passwords` and `Auto-sign in` options are enabled in `Settings --> Passwords --> Autofill`
   2. Visit a site that requires login credentials (ie community.brave.com)
   3. Enter credentials, ensure the browser prompts you to save the password for this site
   4. Check `Settings --> Autofill --> Passwords` again to verify login data was saved

## Actual result:

Login data is not saved and, subsequently, the form fields will not autofill login data when returning to the site.

## Expected result:
Autofill/password data should be saved and viewable in `Settings --> Autofill --> Passwords` and should also be entered into form fields where this data was saved.

## Reproduces how often: 

For users encountering the issue is always present. 

## Brave version (brave://version info)

Issues reported while running:
- v0.70.121
- v0.70.122

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Not enough info
- Can you reproduce this issue with the nightly channel? Not enough info 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No 
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

- https://community.brave.com/t/passwords-and-usernames-will-not-save-in-the-latest-desktop-build-version-0-70-121-chromium-78-0-3904-70/89820

   - This user was on macOS Catalina 10.15.1
   - This user was previously able to save login data as intended until they updated to v0.70.121 
   - This user gets the same results in Brave Beta build as well
   - Note that for this user `Login data` file **was not found** in `~/Application Support/BraveSoftware/Brave-Browser/[Default or named Profile folder]` 

- https://community.brave.com/t/lost-all-brave-passwords-on-update/90589
   - This user was using macOs 10.14.4
   - This user had previous login data saved in browser without issue
   - This user claims that after updating to v0.70.122, password/autofill data was lost

- https://community.brave.com/t/brave-doesnt-remember-any-of-my-passwords/87646
   - This user recently download the browser and is unable to save any passwords
   - User stopped responding, exact OS version is unknown, but using macOS 

- https://community.brave.com/t/brave-does-not-save-passwords/89889/6
   - This user is on macOS v10.12.6
   - This user gets the same results in Brave Beta  build as well
   - This user provided detailed information:
> I originally installed the older version of Brave on a user account that does not have admin rights.
> On that account, Brave did save passwords as expected. At some point, Brave started running out of memory regularly and crashed every day.
> I continued using Brave without update on another user account (with admin rights).
> There, Brave did not have the crashing problem, but it never saved website login passwords on that account.
> Yesterday I installed the latest version of Brave on the user account with admin rights. Unfortunately, the new version of Brave does not save website login passwords either – at least not on the user account on which I installed it (this is the account with admin rights. The original older version of Brave was initially installed on the other user account, without admin rights).
> 
> I examined the unix rights of Braves files in the Library. The directories have read/write permissions for the account where I am using Brave (old and new version. old version installed on other user account. new Brave version installed on this account).
> So that does not provide any clue what is going wrong.
> [...]
>There is one thing that I noticed though:
>I tried to save passwords for this community forum and 2 other forums.
>Brave Beta did not remember the passwords for any of these.
>BUT it did remember the user names for the other 2 web forums.
>The user names for these other web forums were remembered correctly for login, but the text field for the passwords was empty. That is by the way the same with the official release (non-beta).

- https://community.brave.com/t/passwords-not-working/89293/3
   - This user is on macOS Catalina v10.5.1, Brave v0.70.121
   - This user lost passwords and other browser settings after updating to Catalina
   - This user cannot save any login data -- does not appear in `Autofill`. This happens on any/all websites

- https://community.brave.com/t/lost-all-passwords-history-bookmarks-etc-upon-app-re-launch/89336
   - This user is on macOS High Sierra v10.13.6, Brave v0.70.121
   - This user claims their browsing data was lost including all logins/passwords after a browser relaunch.
   - They also note that data from _all their profiles_ was removed or is not appearing.

**Comment by Brave-Matt** [comment] 2019-11-11 18:27
Another user reporting the same behavior and providing `passwords-internals information`:

> 
> I’m having the same problem (macOS Mojave 10.14.6, running on MBP; Brave Version 0.70.123 Chromium: 78.0.3904.97 (Official Build) (64-bit); also had problem with Brave Version 0.70.122), and here’s what I got after going to brave://password-manager-internals:
> 
> Captured password manager logs are listed below. Logs are cleared and no longer captured when all password-manager-internals pages are closed.
> Version: | 78.0.70.123 (official)
> -- | --
> Revision: | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
> User Agent: | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
> App Locale: | en-US
> Variations: |  
> Message: PasswordAutofillAgent::SendPasswordForms
> 
> only_visible: false
> 
> Security origin: https://community.brave.com/ 1
> 
> Number of all forms: 0
> 
> Message: PasswordAutofillAgent::SendPasswordForms
> 
> only_visible: false
> 
> Security origin: https://community.brave.com/ 
> 
> Number of all forms: 0
> 
> Message: PasswordAutofillAgent::SendPasswordForms
> 
> only_visible: false
> 
> Security origin: https://community.brave.com/ 
> 
> Number of all forms: 0
>

**Comment by Brave-Matt** [comment] 2019-11-25 18:22
Another couple users reporting this -- these users specifically have issues logging into specific hosts:
https://community.brave.com/t/save-password-not-prompted-second-attempt/67856/29

**Comment by bsclifton** [comment] 2019-11-26 23:00
Closing as a dupe of https://github.com/brave/brave-browser/issues/4061

**Closed by bsclifton** 2019-11-26 23:00 UTC
Labels: feature/autofill, feature/password-manager, feature/settings

**Comment by rubenvthoff** [comment] 2020-05-27 18:32
After the last Brave update "1.9.72" all my passwords are lost and autofill for passwords isn't working anymore (it doesn't save my passwords either). I'm using Mac OS Sierra 10.12.6.

**Comment by kyrawertho** [comment] 2020-06-18 08:48
I lost my passwords in the last update to 1.10.90 on Linux. It's no longer saved new passwords neither.

I finally found out I had to enable kdewallet. Passwords are now saved but kdewallet asks for a password on startup, which is also an annoyance.

**Comment by didli** [comment] 2020-06-20 12:20
Same here as @kyrawertho , but with whatever gnome/xfce uses as user passwords manager (seahorse or gnome-keyring, can't remember). Problem is I don't need nor want any of them.

**Comment by bsclifton** [comment] 2020-06-22 23:24
For Linux on Gnome, I think `gnome-keyring` is required actually
cc: @fmarier 

Passwords are stored in autofill sqlite database in the profile. For example `default/Login Data`. If this file exists, you can open using a utility like `DB Browser for SQLite` and browse the contents

If at any time the key used for encryption changes, the old entries can't be decoded anymore. For example, if you move from one computer to another. It happens also on macOS when you use migration assistant

The ideal use-case to avoid these scenarios would be to use Sync v2 which we've landed in Nightly, which does handle password syncing 😄

**Comment by fmarier** [comment] 2020-06-25 01:21
`gnome-keyring` (or its KDE cousin) is required in order to save passwords in Brave securely.

If you don't care about an attacker who has access to your local file system, then you can use a [command-line option](https://peter.sh/experiments/chromium-command-line-switches/#password-store) to force the use of the insecure password store:

    --password-store=basic

You can find the possible values in the [Chromium source code](https://source.chromium.org/chromium/chromium/src/+/master:headless/app/headless_shell_switches.cc;l=52-60;drc=731c566fb3cc28fb9159a99f955082b9e8649209).

**Comment by LuigiNicaPRO** [comment] 2020-09-08 17:54
Same problem here but not on all websites. I have problems with shipstation.com for example

**Comment by geoidesic** [comment] 2022-11-06 13:08
I have this problem too. Happens on one device but works fine on a different device. I've checked the settings and it claims to be saving the password and I can see the password in the password manager but it doesn't offer the password in a drop-down when it should.

**Comment by vbxyz** [comment] 2024-05-09 04:14
same here,  https://customerservice2.southerncompany.com/ , erasing password with popup box >Invalid username/password.
Please note: The password field has been cleared for security purposes.<
