### ISSUE TITLE
Warning message not being displayed,  when click on `Confirm Sync code` without any code added

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3190] opened 2019-02-01 12:47 UTC
## Description 
Follow up of #2845

Warning message not being displayed,  when click on `Confirm Sync code` without any code added.
steps to reproduce the issue is same as 2845 

## Actual result:

![warning message not displayed](https://user-images.githubusercontent.com/38657976/52123574-89a25d00-264c-11e9-9875-df454f3d73ca.gif)

## Expected result:
Warning message should be displayed as `Invalid sync code. please try again`

## Reproduces how often: 

Intermittent issue
## Brave version (brave://version info)

Brave | 0.59.34 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Windows 10

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? no

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional Information
@brave/legacy_qa @cezaraugusto

**Comment by srirambv** [comment] 2019-02-01 14:16
Does console log any errors when this issue reproduces?

**Comment by GeetaSarvadnya** [comment] 2019-02-07 11:16
@srirambv https://github.com/brave/brave-browser/issues/3190#issuecomment-459736333 - I did not get any console error. 

I am not able to reproduce the issue on `0.59.35` - Needs to be investigated what is fixed in 0.59.35

**Comment by srirambv** [comment] 2019-02-07 11:39
cc: @darkdh @AlexeyBarabash

**Comment by einaralex** [comment] 2019-02-11 22:24
I'm dealing with the same issue and I have a valid sync code, no error messages and no messages in the console log.
Version: Version 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)

**Comment by kjozwiak** [comment] 2019-02-12 06:18
> I'm dealing with the same issue and I have a valid sync code, no error messages and no messages in the console log.
> Version: Version 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)

@einaralex does restarting the browser help? Or are you running into the above issue every single time, even after a restart?

**Comment by einaralex** [comment] 2019-02-12 07:54
@kjozwiak I've tried restarting the browser a couple of time now, no changes.

**Comment by einaralex** [comment] 2019-02-12 22:48
After messing around a bit it seems to work to do a hard reload (cmd+shift+R) on brave://sync page.

**Comment by kjozwiak** [comment] 2019-02-13 22:28
Awesome, thanks for the info @einaralex. At least there's a work around for now until we get this fixed. Appreciate your time/input 👍

**Comment by GeetaSarvadnya** [comment] 2019-04-25 17:03
Unable to reproduce the issue on `0.63.48` and `0.64.60`. Looks like the issue is fixed.

**Comment by mapleoin** [comment] 2019-06-05 14:31
I've just run into this on Version 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)
 (Debian installed via snap)

I actually think I'm entering a correct code, but the button does nothing. There is also no warning message being displayed if the code is missing or if the code is incomplete/wrong.

**Comment by kjozwiak** [comment] 2019-06-06 02:17
@mapleoin seems like you might be a few versions behind. `0.64.77` is the latest version of release. Once you update, can check and see if you can still reproduce the issue with the newest version?

* [1] https://github.com/brave/brave-browser/releases/tag/v0.64.77

**Comment by GeetaSarvadnya** [comment] 2019-06-06 06:05
Verified on 0.63.48 - Unable to reproduce the issue, It's working fine in Windows 10 x64

**Comment by GeetaSarvadnya** [comment] 2019-06-24 09:43
+1 from community https://community.brave.com/t/sync-nothing-happens-after-i-click-confirm-sync-code/66820

**Comment by GeetaSarvadnya** [comment] 2019-06-24 09:45
Users are still facing the issue. Hence re-opening the issue and removing a Not actionable label

**Comment by MRVDH** [comment] 2019-06-24 10:00
Just want to point out that this is not a problem with properly displaying a warning message. The sync code I enter is correct. The button just doesn't do anything. See https://github.com/brave/brave-browser/issues/4756

**Comment by GeetaSarvadnya** [comment] 2019-06-24 10:08
@MRVDH Basically the button `Confirm Sync code` isn't responsive whether you enter correct sync or leave sync code field empty.

**Comment by cezaraugusto** [comment] 2019-07-08 19:32
@AlexeyBarabash do you know if something changed in the back-end for this feature? it's been a while I don't make changes to Sync

**Comment by Brave-Matt** [comment] 2019-07-08 19:58
A couple users on Community still reporting this (in latest):
https://community.brave.com/t/confirm-sync-code-button-is-non-responsive/67268

**Comment by SephReed** [comment] 2019-07-17 21:59
Just got this issue.  No response, any way it's clicked.

**Comment by ThatLifeofGames** [comment] 2019-07-20 19:08
Also having the same issue with a valid sync code on a fresh (so latest) version of brave. Tried reloading with empty cache and hard reload with no difference. No errors in console.

**Comment by smorgisborg1** [comment] 2019-07-24 21:10
Attempting to create a new sync code and cancelling does fix the issue, but for mine at least the button works but the sync is not achieved. The button is greyed out with the swirling circle but it just times out.

**Comment by GeetaSarvadnya** [comment] 2019-07-24 21:12
Further investigation on the issue, the issue is reproducible consistently using the steps below:

1. Clean profile
2. Click on `Start a new Sync Chain`
3. Select phone/tablet or computer option
4. View sync code and QR code
5. Click on Cancel
6. Click on `Close anyway` 
7. Click on `I have Sync Code` option
8. Enter Valid or invalid code or leave the sync code field empty
9. Click on `Confirm Sync Code`

Actual: Click on Confirm sync code does nothing, doesn't throw any error message in case of invalid code, wait for sometimes (3 to 4 mins ) and then click again on `Confirm Sync Code` gives the expected result. Click on cancel (step5 ) is taking time to cancel the sync chain as sync chain is already looking for the device to sync, there is a network delay in getting the response from the cancel sync chain. After canceling sync chain immediately, if we click on `I have sync code` option and enter valid or invalid code in the sync code text box and click on `Confirm Sync Code` doesn't take any action as the cancel process is still not completed in step 5.

Verified the sync background page logs. This issue is occurring due to network delay.

![image](https://user-images.githubusercontent.com/38657976/61829085-ce81b080-ae85-11e9-9119-42092e3b26ba.png)

**Comment by smorgisborg1** [comment] 2019-07-24 21:18
Managed to bypass issue by first syncing android phone and then adding a new device through the brave://sync menu that loads after a successful sync.

**Comment by cezaraugusto** [comment] 2019-07-24 21:20
^^^ cc @AlexeyBarabash @darkdh @SergeyZhukovsky this seems related to the library itself

**Comment by AlexeyBarabash** [comment] 2019-07-29 16:28
Here is a PR which should fix https://github.com/brave/brave-core/pull/3038 .

**Comment by 93RS** [comment] 2019-07-31 07:06
The same problem arises. The click on the button does nothing, whether there are written words, or those words are right or wrong.
Brave: 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
OS: Windows 10 OS Version 1903 (Build 18362.267)

**Comment by AlexeyBarabash** [comment] 2019-07-31 16:16
Hopefully this is fixed with https://github.com/brave/brave-core/pull/3038.

**Closed** 2019-07-31 16:15 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug

**Comment by AlexeyBarabash** [comment] 2019-08-02 16:03
I can verify the fix works on own-built master (0.70.30), but the fix somehow does not work on Nightly (0.70.22).

**Comment by AlexeyBarabash** [comment] 2019-08-07 13:20
I can verify fix works on Nightly (0.70.34).

 @GeetaSarvadnya @kjozwiak @srirambv @rebron - should the fix for this issue be uplifted to beta/dev/stable?

**Comment by kjozwiak** [comment] 2019-08-08 02:17
> I can verify the fix works on own-built master (0.70.30), but the fix somehow does not work on Nightly (0.70.22).

@AlexeyBarabash looks like `5e293e8` landed right after `0.70.23` [1] which might explain why it didn't work on `0.70.22`? I'm a bit hesitant uplifting something that didn't work one `0.70.22` and then worked on `0.70.34`.

* [1] https://github.com/brave/brave-core/commits/master?after=7abb49bdb59ccb4e741f6b9f2f90d50f1ed3de9f+69

**Comment by AlexeyBarabash** [comment] 2019-08-08 08:16
@kjozwiak 
Yes, I also re-checked the commits history, the fix hadn't work in `0.70.22` because it was landed right after `0.70.23`.
![image](https://user-images.githubusercontent.com/24739341/62686474-78585580-b9cd-11e9-822b-5b6aebdaab67.png)

When I wrote the message about `0.70.22` I hadn't recheck that, and just installed the latest update for Nightly.

So @brave/uplift-approvers could you please discuss the uplift?

**Comment by kjozwiak** [comment] 2019-08-09 19:27
@AlexeyBarabash after deliberating with the @brave/uplift-approvers team, we're going to let this ride the trains from `Nightly` to `Release`. There's a few +1's from the community but I don't think this is critical enough to warrant an uplift. `0.68.x` has ~a week before release so we try to only uplift critical fixes 👍

**Comment by MRVDH** [comment] 2019-08-13 06:52
@kjozwiak so does that mean the fix will be in the next release? Because it still doesn't work for me in the latest (current) Release. (it spins for a while after clicking it but after a while it stops and nothing has happened)

**Comment by AlexeyBarabash** [comment] 2019-08-13 07:43
@MRVDH this means the fix first will appear in dev, then in beta and then in release. Each step is a version bump and takes ~ 3 weeks https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule.

**Comment by LaurenWags** [comment] 2019-09-26 22:35
Verified passed with

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-browser/issues/3190#issuecomment-514802188
* Verified error message displayed when no code or invalid code:
<img width="699" alt="Screen Shot 2019-09-26 at 6 32 36 PM" src="https://user-images.githubusercontent.com/28145373/65729459-5786b500-e08c-11e9-90d5-9eeefaa214cd.png">
* Verified entering a valid sync code added device to sync chain.

**Comment by xdever** [comment] 2019-12-16 18:21
I am having exactly the same issue with "Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) unknown (64-bit)". It is Manjaro Linux community/brave package. I'm trying to synchronize 2 Linux machines and an Android phone. One Linux machine synced with the phone, but the other won't - it just does nothing when I click the "Confirm Sync Code" button. It does the same thing if I enter an arbitrary code. There are no error messages in the debug console, no error messages in the Linux console, and no network traffic at all when I click the button.

**Comment by AlexeyBarabash** [comment] 2019-12-16 18:46
@xdever 
it looks similar to https://github.com/brave/brave-browser/issues/6504 which is fixed in 1.3.x, current `dev` build.

**Comment by VidfamneOrigin** [comment] 2020-01-02 19:46
Trying the 'fix' above on my Win10 (lastest upgrades) / Brave Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit), causes Brave to crash/close after hitting the Confirm-key and it going grey to indicate connection to sync-server. Upon restarting it, I get asked to restore latest session.
