### ISSUE TITLE
Text partially invisible on settings page

### ISSUE THREAD

**Issue by ygoe** [brave/brave-browser#17489] opened 2021-08-15 13:00 UTC
Have you searched for similar issues? Yes but I don't know what to search for and didn't want to manually review 278 open and 1746 closed issues. Sorry.

## Description 
Some of the text on the settings page is invisible. See screenshot, left column, text "Erweiterte Einstellungen" at the bottom.

![grafik](https://user-images.githubusercontent.com/868315/129479410-5b182210-7154-4f6a-be6d-684ccc448245.png)

## Brave version (brave://version info)
1.28.105 Chromium: 92.0.4515.131 (Offizieller Build) (64-Bit)

**Comment by thefallofbecause** [comment] 2021-08-15 13:49
There is a border radius on the button that is causing the text to clip. It happens in any language, but German and any others that force the text onto two lines makes it more noticeable.

**Comment by srirambv** [comment] 2021-08-16 06:02
Dupe of #17461

**Closed by srirambv** 2021-08-16 06:02 UTC
Labels: OS/Desktop
