### ISSUE TITLE
Delete and search icons are overlapping in brave://history

### ISSUE THREAD

**Issue by dryspeed** [brave/brave-browser#32399] opened 2023-08-20 07:53 UTC
## Description 
The Delete and Search icons overlap, leading to unexpected behavior in Brave History.

## Steps to Reproduce

   1. Open Brave history settings by visiting 'brave://history/'.
   2. Open the history settings in a minimized window.
   3. Attempt to delete a specific website from your history.
   4. Notice that the delete and search icons overlap.

## Actual result:
In a minimized window, the issue can be observed:

https://github.com/brave/brave-browser/assets/142707208/fe5a3bc4-2d60-462d-a7ea-e7b5917ef2ee

## Expected result:
In fullscreen mode, the icons display correctly:

https://github.com/brave/brave-browser/assets/142707208/49fe24f7-e1db-4bfe-b77b-1ce66cb60154

## Reproduces how often: 
Consistently, Every time.

## Brave version (brave://version info)
Brave: 1.57.47
Chromium: 116.0.5845.96 (Official Build) (arm64)
Operating System: macOS Ventura

## Version/Channel Information:
The issue is reproducible with the current release.

```[tasklist]
### Tasks
```

**Comment by bsclifton** [comment] 2023-08-21 17:23
cc: @fallaciousreasoning

**Comment by fallaciousreasoning** [comment] 2023-08-21 22:38
That's not ideal! Thanks for reporting @nutscreams

**Comment by FortisLeo** [comment] 2023-08-23 13:57
@fallaciousreasoning sir how can I am unable to find the file in which I have to make changes to fix this issue I will truly appreciate your help.

**Comment by Nishchay1571999** [comment] 2023-08-24 15:24
Hi fallaciousreasoning What should actually happen to the search and the Delete Button. when the App is minimized? Its probably happening because there might be no styles for that perticular size ratio given to those button. I would like to take this issue.

**Comment by KSSaiTeja** [comment] 2023-08-30 05:36
can i work on this issue to fix it..

**Comment by fallaciousreasoning** [comment] 2023-08-30 22:36
@Nishchay1571999 there should be some minimum gap between the search button and the delete button (probably 8px)

**Comment by priyankuhazarika** [comment] 2023-09-05 15:20
@bsclifton can you assign this to me, i can work on it!

**Comment by harshul786** [comment] 2023-09-09 09:22
Hello Maintainers!

I'm pleased to let you know that I've fixed the overlapping bug described in this issue. I've created a pull request that addresses the problem.

You can review the changes in the PR above!

If there are any specific details or test cases you'd like me to provide, please feel free to let me know. I'm here to assist with any additional information or adjustments needed to get this issue resolved.

Thank you for maintaining this project, and I look forward to your feedback on the proposed fix!

Best regards.

**Comment by harshul786** [comment] 2023-09-10 16:24
#https://github.com/chromium/chromium/pull/193

**Comment by fallaciousreasoning** [comment] 2023-09-11 03:47
Awesome, thanks @harshul786! That looks great - I'll just create a fork of your branch to run CI!

**Comment by fallaciousreasoning** [comment] 2023-09-11 03:54
Sorry, I just had a look and noticed you've forked https://github.com/brave/chromium, rather than https://github.com/brave/brave-core - we don't actually modify that project directly, our patches live in https://github.com/brave/brave-core.

That said, it should be possible to make a very similar change in https://github.com/brave/brave-core. It looks like we already patch `ui/webui/resources/cr_elements/cr_toolbar/cr_toolbar_selection_overlay.html` with `brave/ui/webui/resources/br_elements/br_toolbar/br_toolbar_selection_overlay_overrides.css`, so it should be possible to add your CSS there directly (you'll have to include the selector).

Thanks for making a patch!

**Comment by harshul786** [comment] 2023-09-11 06:22
@fallaciousreasoning I've implemented the changes as per your previous advice. Could you please review the updates? Additionally, if you have any specific questions or concerns about these changes, please don't hesitate to let me know. Thanks!

**Comment by GouravKumar13** [comment] 2023-09-27 03:02
@bsclifton @fallaciousreasoning can you assign this to me, I can work on it!

**Comment by Dhanush-4554** [comment] 2023-09-28 08:57
Hey! I think I can resolve this issue. Can you assign it to me @fallaciousreasoning, I can change the css here in right way.
Thank you!

**Comment by trana5197** [comment] 2023-09-30 21:51
@bsclifton @fallaciousreasoning I can work on it! Can you assign it to me? Thank you! Looking forward to make my first contribution.

**Comment by IAmRiteshKoushik** [comment] 2023-10-03 10:32
Has this issue been resolved or is it still up for grabs ?

**Comment by fallaciousreasoning** [comment] 2023-10-04 20:43
The issue is still up for grabs. There seems to be a lot of interest in working on it but @harshul786 has a partially finished PR, so if he's still working on it, I think we should let him finish it.

**Comment by harshul786** [comment] 2023-10-04 20:50
I am working on it 🫡

**Comment by sabasyedcodes** [comment] 2023-10-20 14:13
Hello I would love to contribute ! I think I can solve this issue. Can you please assign to me ?

**Comment by sabasyedcodes** [comment] 2023-10-23 06:19
@harshul786 are you still working on it  ?

**Comment by Rohankumarmenu** [comment] 2023-10-29 15:03
I would like to work upon this. Can you assign the task to me.

**Comment by ImtiyazAly** [comment] 2023-11-28 08:57
Hey, @fallaciousreasoning is the overlapping issue solved or not? I think I can quickly fix this issue. Can you assign me to contribute?

**Comment by fallaciousreasoning** [comment] 2023-11-28 20:48
@ImtiyazAly if you submit a PR, I'm happy to help you get it merged :smile:

**Comment by Hitanshu5979** [comment] 2023-12-24 04:36
Hey @fallaciousreasoning 
I see that the overlapping issue is yet to be resolved.
Do you mind if I try to fix this?

**Comment by bsclifton** [comment] 2023-12-29 18:59
@Hitanshu5979 please do 😄 Ping us if you have a pull request or question

**Comment by Prashanthsai525** [comment] 2024-01-09 04:42
@fallaciousreasoning is the issue fixed??

**Comment by Rohankumarmenu** [comment] 2024-01-09 04:51
I am not the owner of that repository

**Comment by abhishek0wb** [comment] 2024-01-20 05:54
I'm working on it

**Comment by esuleman** [comment] 2024-01-25 01:49
is this issue fixed? if not I am willing to work on it

**Comment by Rohankumarmenu** [comment] 2024-01-25 03:22
I am not the owner of repository.

**Comment by fallaciousreasoning** [comment] 2024-01-25 20:26
Not fixed yet :)

**Comment by Vedant767** [comment] 2024-01-30 17:45
@fallaciousreasoning please assign it to me, I will fix it.

**Comment by Gajmain2020** [comment] 2024-02-07 06:05
is this issue yet open? I want to contribute to this repo.

**Comment by bsclifton** [comment] 2024-02-07 08:45
Yes hi folks - please do work on a fix and then share a link to the pull request here 😄 No need for assignment

**Comment by areebqazi** [comment] 2024-02-18 21:46
This issue is fixed in the current app , shouldn't it be closed now ?

**Comment by himanshuyadav14** [comment] 2024-02-27 05:00
This issue is fixed. Can you please close it.

**Comment by fallaciousreasoning** [comment] 2024-02-27 19:25
I think this is fixed now - closing this.

**Closed by fallaciousreasoning** 2024-02-27 19:25 UTC
Labels: bug, good first issue, feature/history, priority/P4, feature/settings, OS/Desktop
