### ISSUE TITLE
tab-switch to most recent tabs first

### ISSUE THREAD

**Issue by headkace** [brave/brave-browser#7685] opened 2020-01-10 04:12 UTC
## Description 
When tab switching with hot key, &lt;ctrl-t&gt;, it would be much better if you were sent to the most recent tab that was active rather than simply moving to the next tab to the right.  
## Steps to Reproduce
   1. Open a number of tabs.
   2. Switch between two non-adjacent tabs by clicking on the tabs one after the other.
   3. Next, change tabs with &lt;ctrl-t&gt;.  

## Actual result:
Current behavior is to go to the next tab to the right. (Or, to loop back to 1st tab, if on right-most tab.)

## Expected result:
Preferred behavior would be to go to the previously active tab.  And, furthermore, with multiple presses of &lt;ctrl-t&gt; to progress backward through the history of most recently active tabs.

## Reproduces how often: 
Always.  (This is a feature request.)

## Brave version (brave://version info)
Version 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)

## Version/Channel Information:
- Can you reproduce this issue with the current release?  Yes
- Other channels unknown, but expect the behave in the same way.

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? No.
- Is the issue reproducible on the latest version of Chrome? Not sure
- Is the issue reproducible on the latest version of Opera? No.

## Miscellaneous Information:
Understand there are extensions that do things like this.  However, I feel like this is an important, basic browser feature for busy users that keep many open tabs.  This might be a good candidate for an optional feature via settings as well.  Would suggest default to most-recent with optional settings to choose left-to-right behavior.  Thanks.

**Comment by srirambv** [comment] 2020-01-10 13:18
Closing as dupe of #913

**Closed by srirambv** 2020-01-10 13:18 UTC

**Comment by headkace** [comment] 2020-01-13 04:01
Thanks! ...  I had searched before opening and don't know why existing issue didn't come up. :/
