### ISSUE TITLE
Unable to dismiss the first rewards notification

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6691] opened 2019-10-31 20:44 UTC
The first rewards notification reappears after browser restart

## Steps to Reproduce

   1. Clean install
   2. Click BAT icon in URL bar -> first rewards notification is dismissed (expected)
   3. Restart Brave

### Actual result:

first rewards notification is shown
![image](https://user-images.githubusercontent.com/34715963/67984659-806c0e00-fc27-11e9-9896-6a7bc93e657e.png)

### Expected result:
first rewards notification is dismissed
![image](https://user-images.githubusercontent.com/34715963/67984679-8c57d000-fc27-11e9-9a52-83e73e2998ab.png)

### Broader test plan (from the PR via @petemill)
0. Clean user data directory
1. Launch Brave
2. Create a second profile via App Menu -> Create a New Profile
3. **Expected:** Both profile windows have the rewards icon with the badge text "1"
4. Click the rewards button in the second profile window
5. **Expected:** The second profile window's rewards icon does not have a badge
6. **Expected:** The first profile window's rewards icon does have a badge
7. Quit the browser
8. Start the browser again
9. **Expected:** The rewards icon badge state from each profile window is the same as 5) and 6)

## Reproduces how often: 

Always

## Brave version (brave://version info)

**Reproducible on**

Brave | 0.71.106 Chromium: 78.0.3904.70 (Official Build) beta (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

Brave | 0.72.112 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

Brave | 0.73.45 Chromium: 78.0.3904.70 (Official Build) nightly (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

**Not reproducible on**

Brave | 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @NejcZdovc @petemill

**Comment by btlechowski** [comment] 2019-11-04 12:30
@rebron @bsclifton While this is a visual only issue, it is a regression. Could you prioritize it?

**Comment by bsclifton** [comment] 2019-11-06 23:46
marked as `release-notes/exclude` since it's not reproducible on 0.70.x

**Closed** 2019-11-07 16:53 UTC
Labels: 1.0, QA/Test-Plan-Specified, QA/Yes, feature/rewards, priority/P2, regression, release-notes/exclude

**Comment by LaurenWags** [comment] 2019-11-08 22:22
Verified passed with

Brave | 0.71.113 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | macOS Version 10.13.6 (Build 17G5019)

* Reproduced issue using 0.71.108
* Verified STR from description
* Verified test plan from https://github.com/brave/brave-core/pull/3898
