### ISSUE TITLE
[Desktop] Brave is listed in System reports as an iOS app for M1/arm64

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12954] opened 2020-11-30 22:31 UTC
## Description 

Brave is listed in System Reports as an `iOS` app. I believe we'd want to be Universal.

## Steps to Reproduce

   1. Have Brave arm64 build installed
   2. Go to About this Mac > click on System Report > Applications
   3. Locate Brave in the list

## Actual result:

![Screen Shot 2020-11-30 at 1 54 43 PM](https://user-images.githubusercontent.com/28145373/100673519-9750c880-3331-11eb-8e59-a44e6f92dd17.png)

## Expected result:
Under "Kind" should see `Universal` not `iOS`

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.19.41 Chromium: 87.0.4280.67 (Official Build) nightly (arm64)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | macOS Version 11.0.1 (Build 20B29)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? no, Chrome is listed as Universal

## Miscellaneous Information:

cc @rebron @bsclifton

**Comment by bsclifton** [comment] 2020-12-01 19:13
@mihaiplesa do we know if ARM64 binaries all show as `iOS` if they're native (versus universal)?

**Comment by mihaiplesa** [comment] 2020-12-01 19:21
Wasn't able to reproduce the iOS one but they would definitely not show as universal since we don't have that kind of package yet.

**Comment by mihaiplesa** [comment] 2021-01-14 14:36
Confirming this was only happening on `nightly` and should now be fixed by https://github.com/brave/brave-core/pull/7581 which switches from native to universal in 1.21.2+

**Closed** 2021-01-19 09:50 UTC
Labels: OS/Desktop, OS/macOS-arm64, QA/Yes, priority/P3

**Comment by LaurenWags** [comment] 2021-01-20 13:09
Verified passed with

```
Brave	1.20.84 Chromium: 88.0.4324.96 (Official Build) dev (arm64)
Revision	68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS	macOS Version 11.1 (Build 20C69)
```

Verified STR from description.

<img width="1038" alt="Universal" src="https://user-images.githubusercontent.com/28145373/105178989-bf210900-5af6-11eb-8267-5bb6b8a00c3f.png">
