### ISSUE TITLE
Unable to access appearance section

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#17800] opened 2021-09-01 04:38 UTC
When i go to the settings page and press the appearance button nothing happens, if i manually scroll to it it is not between the rest of the options.
I have created a new profile and have the same results.
I am using linux, PopOS (ubuntu)
Have the latest release of PopOS and Brave installed.

![Brave](https://user-images.githubusercontent.com/86555108/131612723-583c2cc1-afa2-4610-a74b-ded919dc569a.png)

What to do?

**Comment by Githuborian** [comment] 2021-09-02 04:49
This is dutch: Vormgeving = appearance

**Comment by the-anonymous-raven** [comment] 2021-09-04 08:57
I second this issue. I am on arch linux (latest version of brave stable release) and opening Appearance does not open the desired page.

**Comment by Githuborian** [comment] 2021-09-16 05:32
Still get anoyed by these dissapearing panels

**Comment by TheFeelTrain** [comment] 2021-09-26 14:13
I have the same problem. Arch Linux with the latest stable release (1.29.81)
I think it might be related to this error in the console.

![Screenshot_20210926_070946](https://user-images.githubusercontent.com/12601452/134811347-dccccc40-ee58-4169-98f0-c82f703fed62.png)

The Appearance section does work in Brave Beta (1.31.61) with a fresh profile and doesn't have this error.

**Comment by wknapik** [comment] 2021-09-27 11:48
Can't reproduce this on up-to-date Arch Linux running `Brave Browser 93.1.29.81` via `brave-bin 1:1.29.81-1`.

**Comment by Githuborian** [comment] 2021-09-27 12:18
Yet we all are stil experiencing these issues.

**Comment by TheFeelTrain** [comment] 2021-09-27 12:43
I have actually figured out what causes it. I thought the only thing I hadn't tried was resetting `brave://flags` so I did that and the section reappeared. I went through and set them back to what they were one-by-one until it disappeared again.

It is caused by the flag `#brave-ntp-branded-wallpaper` being set to Disabled 

![Screenshot_20210927_054015](https://user-images.githubusercontent.com/12601452/134909903-d939210c-4cc6-4cdb-bef6-16d7725cc309.png)

Setting it to Default or Enabled fixes the Appearance section. I'm not even quite sure what this flag does since it seems to be independent of the "Show Sponsored Images" toggle on the new tab page.

**Comment by TheFeelTrain** [comment] 2021-09-27 12:51
Digging even deeper into it, it seems like the "superReferralThemeName" in the error from my first screenshot is related to these branded wallpapers. According to https://github.com/brave/brave-browser/issues/9329#issuecomment-620806161 "referrals are unavailable on Linux"

**Comment by wknapik** [comment] 2021-09-27 14:43
@rebron seems this is caused by the `brave-ntp-branded-wallpaper` flag, as indicated by @TheFeelTrain [here](https://github.com/brave/brave-browser/issues/17800#issuecomment-927835917).

**Comment by mikhoul** [comment] 2021-09-27 15:24
Same here under Windows.

**Comment by Githuborian** [comment] 2021-09-28 17:05
I have fixed this issue by disabling the above suggested flag and restart chrome.

**Comment by TheFeelTrain** [comment] 2021-09-28 17:41
I would leave the issue open. As far as I can tell it's not the intended behavior so it's still a bug that should be fixed.

**Comment by mikhoul** [comment] 2021-09-29 00:08
> I would leave the issue open. As far as I can tell it's not the intended behavior so it's still a bug that should be fixed.

Exactly it's not the intended behavior, changing the flag is just a workaround it need to be fixed.

**Comment by rebron** [comment] 2024-02-09 05:49
Closing as this flag was removed in 1.35.x https://github.com/brave/brave-core/pull/11307

**Closed by rebron** 2024-02-09 05:49 UTC
Labels: OS/Desktop
