### ISSUE TITLE
Customizing UI for Windows

### ISSUE THREAD

**Issue by Ahmed-Imam** [brave/brave-browser#13028] opened 2020-12-03 10:50 UTC
I just cloned the brave source code for **windows**, I was able to customize the home page and change some colors, but i wasn't able to fully reskin the UI, such as the toolbar( I want to reorder/add some buttons), settings, history, bookmarks, and downloads page couldn't find the source code for those pages. so can we customize the mentioned UI or what does it require to do so ?

**Comment by rebron** [comment] 2020-12-07 19:21
You can use an extension for some of this. Otherwise, it's quite a lot effort to do the remaining customizations you're looking to do.

**Comment by bsclifton** [comment] 2020-12-08 18:55
Thanks for the report @Ahmed-Imam - I'm going to close this as a duplicate of https://github.com/brave/brave-browser/issues/774 

You can subscribe there for updates and also post a comment with some ideas that you had in mind

**Comment by bsclifton** [comment] 2020-12-08 18:55
Whoops - had left a comment thinking this was a dupe of another issue, but I realize you're asking for help finding specific pages. Let me help share links for you

**Comment by bsclifton** [comment] 2020-12-08 21:56
@Ahmed-Imam we have a specific override system with Polymer (what Chromium uses for their pages) that you'll want to check out

There's a lot of great examples under [`browser/resources/settings/brave_overrides/`](https://github.com/brave/brave-core/tree/master/browser/resources/settings/brave_overrides). A few examples:
- [basic_page.js](https://github.com/brave/brave-core/blob/master/browser/resources/settings/brave_overrides/basic_page.js) - where we modify settings page
- [about_page.js](https://github.com/brave/brave-core/blob/master/browser/resources/settings/brave_overrides/about_page.js) - for our about page

You can use a similar mechanism to modify the downloads / history / etc pages. We inject the header onto those pages by using the `br_toolbar` object here:
https://github.com/brave/brave-core/tree/master/ui/webui/resources/br_elements/br_toolbar

**Closed by bsclifton** 2020-12-08 21:56 UTC
Labels: dev-concern, dev-experience, question

**Comment by Ahmed-Imam** [comment] 2020-12-09 06:26
@bsclifton thanks for sharing the links, I appreciate it, just one more question if u don't mind, is the tabs and the search bar design also in polymer ? 

<img width="2045" alt="Screen Shot 2020-12-09 at 2 24 22 PM" src="https://user-images.githubusercontent.com/20854551/101593023-3ceaf280-3a2a-11eb-8656-562238e14861.png">

**Comment by bsclifton** [comment] 2020-12-10 07:23
@Ahmed-Imam no, unfortunately that is not in Polymer. You'll have to dig into some C++ to modify those. You might start looking for the bookmark icon that we took out of the omnibox (and put to the left). That'll be a great example for how to modify the browser chrome itself

**Comment by a-ditucalan** [comment] 2021-02-05 07:56
> @Ahmed-Imam we have a specific override system with Polymer (what Chromium uses for their pages) that you'll want to check out
> 
> There's a lot of great examples under [`browser/resources/settings/brave_overrides/`](https://github.com/brave/brave-core/tree/master/browser/resources/settings/brave_overrides). A few examples:
> 
> * [basic_page.js](https://github.com/brave/brave-core/blob/master/browser/resources/settings/brave_overrides/basic_page.js) - where we modify settings page
> * [about_page.js](https://github.com/brave/brave-core/blob/master/browser/resources/settings/brave_overrides/about_page.js) - for our about page
> 
> You can use a similar mechanism to modify the downloads / history / etc pages. We inject the header onto those pages by using the `br_toolbar` object here:
> https://github.com/brave/brave-core/tree/master/ui/webui/resources/br_elements/br_toolbar


hello im trying to modify the history page and download page. 

do i need to add a code to manage to customize ng ui of history and download page. currently the settings page I already overide the ui because there is existing code that i can follow. unlike the history page. how can i add like settings_resouces.grd file in history to register the component that will overide the component in history page? does it need a c++?

**Comment by a-ditucalan** [comment] 2021-02-05 08:40
> @Ahmed-Imam we have a specific override system with Polymer (what Chromium uses for their pages) that you'll want to check out
> 
> There's a lot of great examples under [`browser/resources/settings/brave_overrides/`](https://github.com/brave/brave-core/tree/master/browser/resources/settings/brave_overrides). A few examples:
> 
> * [basic_page.js](https://github.com/brave/brave-core/blob/master/browser/resources/settings/brave_overrides/basic_page.js) - where we modify settings page
> * [about_page.js](https://github.com/brave/brave-core/blob/master/browser/resources/settings/brave_overrides/about_page.js) - for our about page
> 
> You can use a similar mechanism to modify the downloads / history / etc pages. We inject the header onto those pages by using the `br_toolbar` object here:
> https://github.com/brave/brave-core/tree/master/ui/webui/resources/br_elements/br_toolbar

hello i succesfully override the files in settings page. its easy to me to override it because the override file is existing for settings. its already setup. currently i want to override the ui of the history and download page. how can i add like settings_resources.grd and build.gn for history? it should be coded in c++?? right now i just copy the file in chrome for  history_resources.grd but it now working
![image](https://user-images.githubusercontent.com/58244709/107009995-be63c480-67d0-11eb-9785-49d40d749302.png)
