### ISSUE TITLE
LastPass Extension Broken in v4.132.0 released July 15, 2024 - works in Chrome - LastPass customer support refuses to fix

### ISSUE THREAD

**Issue by asheroto** [brave/brave-browser#39759] opened 2024-07-15 17:28 UTC
### Description

I'm sure there are many LastPass users out there that transitioned to Brave Browser at some point in time. For the past 4+ years, I've never had any major issue with the LastPass extension and Brave Browser. A few hours ago, LastPass released version `4.132.0` on the Chrome Web Store. Since that time, the extension won't show the login screen at all.

I have confirmed the issue on a totally separate computer with a new Brave Browser installation.

I realize the first thought here is to point to the developer, LastPass, because it is their code that is seemingly broken. I have, however, already contacted and literally spoken with a LastPass representative. They informed me that they have no intention of fixing or changing anything because "Brave Browser has never been an officially supported browser" (their words). I explained to them that Brave Browser now hit 50M monthly users and that surely there are hundreds of thousands or millions of LastPass users with Brave. They don't care and were unwilling to resolve any issues, even when I mentioned some JS errors. Their mentality is "if it works on Chrome, that's good enough".

That being said, I'm not sure if there's some workaround that the Brave devs can work out to hopefully get this working.

### Steps to reproduce

1. Install Brave Browser
2. Install [LastPass](https://chromewebstore.google.com/detail/hdokiejnpimakedhajhdlcegeplioahd) extension
3. Try to click extension

### Actual result

![image](https://github.com/user-attachments/assets/e19e53d2-15b7-4513-b57a-e7c3fae27e27)

### Expected result

Login screens should appear, or vault.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.67.123 Chromium: 126.0.6478.126 (Official Build) (64-bit) 
Windows 11 Version 23H2 (Build 22631.3880)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [X] in the latest version of Chrome

### Miscellaneous information

Have tried disabling shields entirely. Brave Browser has been the same version for a few days, so it's not Brave's fault that caused this.

LastPass extension works in Chrome. I am seeing some errors with "collect errors" turned on. Unknown if related.

![image](https://github.com/user-attachments/assets/41c1a552-e2f3-449f-a17f-dd304b34c36f)

![image](https://github.com/user-attachments/assets/5c738fef-0ecf-4543-aedb-6bfe5e26a5cf)

Sadly, LastPass has been going down hill for the last few years. I'm close enough to switch myself and my entire company to another provider at this point. Hopefully the Brave devs can take a look and help figure out a workaround.

---

I did ask them for a previous version of the extension's CRX file but they were unable to provide it. I was able to confirm this issue by restoring version 4.131.4_0, enabling Developer mode, and Loading Unpacked...

![image](https://github.com/user-attachments/assets/f1cd676e-d20b-4fe5-be01-b42d5be0a9ba)

Definitely began with version `4.132.0`.

**Comment by ohitson** [comment] 2024-07-16 08:24
I get the same issue, I've just done a fresh install of windows 11 and installed the Brave browser, went to the LastPass website to install the extension, which takes me to the chrome extensions store. Installed it, and when i click on the extension all i get is the tiny white box underneath. Also this is the only extension i have installed, as it is a fresh install
![image](https://github.com/user-attachments/assets/88149b8d-11de-426c-a1b3-c215b6d2f878)

**Comment by mauops** [comment] 2024-07-16 10:54
I'm facing the same issue, I tried in Google Chrome an it worked, however it's not working in Brave browser

**Comment by aFastHero** [comment] 2024-07-16 14:30
Same issue here. If they have no plan to address the issue to ensure compatibility with Brave, I will have to move to another option, like the one offered by Proton.

**Comment by asheroto** [comment] 2024-07-16 16:22
I understand that LastPass is focused only on the major browsers because most businesses only use one of the three, but considering it's such a widely used extension at 25M total users, and Brave has 50M users, I'm a bit surprised they refused to even look at the issue. I actually spoke with a representative on the phone who told me that they would not be fixing the issue because it's not an "officially supported browser".

I really like LastPass because it has a lot of options and generally works well. I like that I can fill form fields, and like the ability to specify Never URLs. But over the past 6 months or so it seems things have grown more problematic with the extension. I kept having to use 2FA on each reboot, sometimes the extension would mess up and I had to disable/enable, the extension wouldn't work with Never URLs unless the browser was restarted, and now with `v4.132.0` it's finally died.

As mentioned, from a backup I was able to "load unpacked" an older version of the extension, `v4.131.4`, and that does still work. For now, that seems to be a viable workaround, but who knows for how long the extension will continue to work. I am using the free trial of another software and plan on switching unless either the extension is updated or Brave devs figure out why this is happening in Brave but not Chrome.

**Comment by solrevdev** [comment] 2024-07-17 13:19
If I could have left LastPass, I would have done so the other Christmas when I had to reset every password after their well-known data breach. 

The problem is I've been with them since I got my first LastPass/XMarks account back in 2013, so as you can imagine, moving to an alternative is not going to be easy with that amount of data/usage over the years.

Anything I can do to help make this new extension work with Brave, please let me know, and talent aside, I will do my best!

**Comment by aFastHero** [comment] 2024-07-17 16:48
@solrevdev There is an option in LastPass to export all of your data. You can then easily import everything into the new password manager. [How to Import from LastPass to Proton Pass](https://proton.me/support/pass-import-lastpass#:~:text=Open%20the%20Proton%20Pass%20browser,using%20your%20system's%20file%20manager.)

**Comment by Brave-Matt** [comment] 2024-07-17 18:20
Several users reporting the same thing here:
https://community.brave.com/t/lastpass-extension-failing-to-launch-starting-2-days-ago/558376/16

Wanted to add that this _may_ be a Win11 specific issue as I cannot reproduce the issue on macOS or Windows 10

**Comment by mdorn** [comment] 2024-07-17 18:22
Reproduced on MacOS Sonoma in Brave browser after a computer upgrade.

**Comment by solrevdev** [comment] 2024-07-17 18:24
The issue for me is on an M1 Mac  running on Sonoma and an older Intel Mac running the one before Sonoma forget which one  but can provide full info if needed

**Comment by ShivanKaul** [comment] 2024-07-17 18:27
@solrevdev can you attach screenshots of the LastPass problems you're facing on MacOS?

**Comment by solrevdev** [comment] 2024-07-17 18:34
> @solrevdev can you attach screenshots of the LastPass problems you're facing on MacOS?

I can but It will be tomorrow now though. I’ll at you once done

However, It’s identical to the screenshots showed in the original description except macOS UI

https://github.com/brave/brave-browser/issues/39759#issue-2409258684

**Comment by ShivanKaul** [comment] 2024-07-17 18:36
I can repro the issue on MacOS too now by updating LastPass.

**Comment by bsclifton** [comment] 2024-07-17 18:39
Thanks for the reports folks - @ShivanKaul and I will do some more debugging. Thanks for your patience!

**Comment by bsclifton** [comment] 2024-07-17 19:55
OK folks - I believe I have found the root cause. Thank you @asheroto for the detailed report - the errors with `Uncaught ReferenceError: ReportingObserver is not defined` led to the smoking gun.

[ReportingObserver](https://developer.mozilla.org/en-US/docs/Web/API/ReportingObserver) is a browser API which LastPass is using. We disabled this in March 2020 with https://github.com/brave/brave-core/pull/4578

According to the pull request (https://github.com/brave/brave-core/pull/4578), you should be able to launch Brave with the command line argument attached: `--enable-blink-features=ReportingObservers`. However, I tried this and it doesn't work.

I did locally build Brave and back out that PR and LastPass works great. So that is the root cause. 

Will chat more with @ShivanKaul - stay tuned

**Comment by asheroto** [comment] 2024-07-18 15:15
Now that I realize LastPass is not mentioned at all on **any** of the articles on top password managers, I am strongly considering switching.

**Comment by mauops** [comment] 2024-07-18 18:48
I've also switched to Bitwarden, which I highly recommend. It's open source and has a free version. I'm only using LastPass because of my company and encountered this issue

**Comment by nmyers217** [comment] 2024-07-19 02:45
I've been looking for an excuse to switch to bitwarden for so long, since lastpass has been so awful. It was so quick and easy, and I can't believe I waited so long to do this. Thanks for the emotional support everyone!

**Comment by insilications** [comment] 2024-07-19 08:15
This was the last straw for me as well. Their response is awful. I have been thinking about switching from LastPass.

**Comment by shark711** [comment] 2024-07-19 12:50
I get exact same result
OS: Ubuntu 24.04 LTS
Brave: Version 1.67.134 Chromium: 126.0.6478.186 (Official Build) (64-bit)
LastPass: Version 4.132.0

**Closed** 2024-07-19 16:19 UTC
Labels: bug, feature/extensions, priority/P2, QA/Yes, release-notes/include, OS/Desktop

**Comment by vizoere** [comment] 2024-07-20 00:50
From LastPass community page:

https://support.lastpass.com/s/question/0D5TP00000I43Oo0AJ/lack-of-support-for-brave-browser

Looks like it was posted somewhere close to 1:30pm EDT

[HenryO_LP](https://support.lastpass.com/s/profile/0058c00000DAdaNAAT) (Employee)

7 hours ago
Hello ,


I have received a response on this request. Our development team is aware of the issue and will be working on a fix. There is no ETA I can provide right now. I apologize for any issue that this may have caused you.


Thank you,

Henry | Customer Care

**Comment by Benjamin-Connelly** [comment] 2024-07-20 01:01
Welp, I have been meaning to migrate away... bye LP.

**Comment by insilications** [comment] 2024-07-20 12:30
I have migrated to Bitwarden. Extremely easy. Their browser extension is lightweight, much faster. Should have done sooner.

**Comment by CYXNNN** [comment] 2024-07-21 09:15
just deleted my lastpass account and moved to 1password.

**Comment by bsclifton** [comment] 2024-07-22 17:10
Hi folks - I'm curious how many people here are using the Nightly (purple icon) version of Brave?

The fix is live here - you should be able to try it and confirm the fix worked. If you use Beta (blue icon) or Release (orange icon) channel, the fix will be there soon. Changes take ~3 weeks to go from Nightly => Beta and Beta => Nightly.

Please let us know!

**Comment by vizoere** [comment] 2024-07-22 17:19
I'll be able to check in a few hours when I get home.

Should it work just by starting the nightly browser, or do I need to use the argument?
--enable-blink-features=ReportingObservers

**Comment by solrevdev** [comment] 2024-07-22 17:27
@bsclifton ill happily try the nightly build. 

Does it run alongside the usual stable version or does it replace it and does it keep all sync settings/sync chain and such? 

Where is the best place to get it for macOS?

Thanks 🙏 

> Hi folks - I'm curious how many people here are using the Nightly (purple icon) version of Brave?
> 
> The fix is live here - you should be able to try it and confirm the fix worked. If you use Beta (blue icon) or Release (orange icon) channel, the fix will be there soon. Changes take ~3 weeks to go from Nightly => Beta and Beta => Nightly.
> 
> Please let us know!

**Comment by bsclifton** [comment] 2024-07-22 17:46
@solrevdev yes - you can run it alongside the regular one and then when you're done testing / confirming, you can remove it

You can download here: https://brave.com/download-nightly

Because it will create a new empty profile, you can go to the extension store and re-download LastPass here:
https://chromewebstore.google.com/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd

Please let us know! I create an uplift (basically requesting we merge the patch) for Beta and Release channel. We're monitoring to see if anything else is impacted after the change before we merge the fix past Nightly

**Comment by bsclifton** [comment] 2024-07-22 17:47
@vizoere unfortunately, the `--enable-blink-features=ReportingObservers` CLI flag didn't work for me. I would try the Nightly version if possible (see above notes).

**Comment by krisbray** [comment] 2024-07-22 19:12
Still receiving this on windows 11 v1.67.134 oddly its only on one of my virtual desktops and the other ones that have different profiles work fine. seems to be isolated to the profile? reinstalling brave and reinstalling lastpass does not fix it.

**Comment by bsclifton** [comment] 2024-07-22 19:40
> > @solrevdev yes - you can run it alongside the regular one and then when you're done testing / confirming, you can remove Brave Nightly. Or you can keep it and try new features every once in a while 😄
> > You can download here: https://brave.com/download-nightly
> > Because it will create a new empty profile, you can go to the extension store and re-download LastPass here: https://chromewebstore.google.com/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd
> > Please let us know! I create an uplift (basically requesting we merge the patch) for Beta and Release channel. We're monitoring to see if anything else is impacted after the change before we merge the fix past Nightly
> 
> @bsclifton Thanks so much for the info!.
> 
> I can test the nightly build in isolation if I understand correctly meaning I can test on an Intel Mac and an M1 Mac and I’ll post specs and results here by tomorrow hopefully at the latest

Yes, that is exactly right! Since Nightly is a different release channel, the profile is isolated from your main one. If you wanted to clean up the Nightly profile after you test, you can find it at `~/Library/Application\ Support/BraveSoftware/Brave-Browser-Nightly`

**Comment by solrevdev** [comment] 2024-07-22 21:29
@bsclifton 

First up Intel macOS works great: 

![SCR-20240722-tkfz](https://github.com/user-attachments/assets/1e3369a5-7c63-4bc1-b376-0f1e5a248716)

Brave Nightly Version (Latest):
Version 1.70.11 Chromium: 127.0,6533.57 (Official Build) nightly (x86_64)

Last Pass Extension Version (Latest):
4.132.0

Intel Specs:
```text
OS: macOS Monterey 12.7.5 x86_64
Host: Mac mini (Mid 2014)
Kernel: Darwin 21.6.0
Uptime: 21 days, 5 hours, 37 mins
Packages: 330 (brew), 115 (brew-cask)
Shell: zsh 5.9
Display (DELL D2721H): 1920x1080 @ 60Hz [External]
DE: Aqua
WM: Quartz Compositor
WM Theme: Multicolor (Dark)
Font: .AppleSystemUIFont [System], Helvetica [User]
Cursor: Fill - Black, Outline - White (32px)
Terminal: iTerm 3.5.3
Terminal Font: CascadiaMonoPL-Regular (16pt)
CPU: Intel(R) Core(TM) i5-4278U (4) @ 2.60 GHz
GPU: Intel Iris [Integrated]
Memory: 12.76 GiB / 16.00 GiB (80%)
```

I'll update this comment with my M1 arm mac test tomorrow. 👍🏼️

**Comment by kjozwiak** [comment] 2024-07-22 21:31
Quickly went through https://github.com/brave/brave-core/pull/24726#issuecomment-2243808118 on `Nightly` and confirmed that `LastPass` is working. Ensured that you can open the panel without any issues and that passwords are being auto-filled. Also checked and ensured that you can fill passwords by clicking on the fields and selecting the credentials that `LastPass` provides.

The above requires `1.68.127` or above for `1.68.x` verification. We're scheduled to release `1.68.x` on `July 23` or `July 24` depending if we get another `Chromium 127` bump.

**Comment by GeetaSarvadnya** [comment] 2024-07-23 13:06
Verification **PASSED** on

```
Brave | 1.68.127 Chromium: 127.0.6533.57 (Official Build) (64-bit)
-- | --
Revision | 88b0d9010af274686b27d8be77edd728fcba04a5
OS | Windows 10 Version 22H2 (Build 19045.4651)

```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/39759#issue-2409258684, ensured that `LastPass` was working correctly as per the following:

* ensured that `LastPass` can be installed/launched via https://chromewebstore.google.com/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd without any issues
* ensured that tapping on the `LastPass` icon opened the panel without any issues
* ensured that `LastPass` is autofilling saved passwords without any issues
  * used https://accounts.google.com/v3/signin/ as a quick check in this instance
* ensured that selecting the `Username` or `Password` field for a website with a saved password correctly loads `LastPass`
  * ensured that you can fill in the credentials via selecting either the `Username` or `Password` from a field

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|-----------------
![image](https://github.com/user-attachments/assets/5ab9e9fb-c4a5-4989-ab4b-74d962bad52a) | ![image](https://github.com/user-attachments/assets/adb2f697-9cd9-4f21-8e9c-3451854a4218) | ![image](https://github.com/user-attachments/assets/c15903dd-7a12-46b3-96ea-eeb455e1cff2) | ![image](https://github.com/user-attachments/assets/42e7cf93-84ea-42ad-bcbc-ab93247552ec)

**Comment by bsclifton** [comment] 2024-07-23 17:02
Thanks for testing @solrevdev! 😄 From @kjozwiak comment - the timing of our next release with this fix. This would be when it hits Release channel.
> We're scheduled to release 1.68.x on July 23 or July 24 depending if we get another Chromium 127 bump.

**Comment by krisbrkrunch** [comment] 2024-07-23 17:15
Working for me on nightly as well. Thanks for fixing this so quickly!

**Comment by vizoere** [comment] 2024-07-23 20:43
Successful here as well with Nightly 1.70.15 on Windows 11.

Amazingly fast turnaround @bsclifton !

Thank you and all the Brave devs!!!

**Comment by xxtensazenxx** [comment] 2024-07-23 21:34
Just ditched lastpass after 5+ years. Whatever - I'm over it. Bitwarden it is.

**Comment by vizoere** [comment] 2024-07-24 21:56
Working in regular Brave browser [Version 1.68.128 Chromium: 127.0.6533.73 (Official Build) (64-bit)] as of 7/24/2024, 5:50pm EDT

**Comment by shahidul-7** [comment] 2024-07-25 00:32
Working now after last update of Brave! Thanks the team

**Comment by solrevdev** [comment] 2024-07-25 00:35
I’ll update tomorrow but thanks all involved in advance 🙏

**Comment by sefinek24** [comment] 2024-07-25 09:48
Now it works in the stable version of Brave, thanks!

**Comment by mauops** [comment] 2024-07-26 08:03
nice job, thanks

**Comment by BobT36** [comment] 2024-07-26 21:04
Ack, this is annoying. Just hit the same issue with no login on icon, when lastpass updated from 4.131.3_0 to 4.132.0_0 yesterday. 
So BRAVE somehow did a workaround for this? What was that, switching back on the API? 
Irritating, as I'm still on W7 and therefore stuck on the old version of Brave. (This at least proves it's not a W11 only thing).


Irritating that LastPass just don't care and did the typical "support" buffer think by sending you away. This app has REALLY been going downhill lately. 
I'll try and "load unpacked" the previous version, if not then it's time to switch away from lastpass.

**Comment by pablo17** [comment] 2024-07-27 14:13
I have had this issue on Linux (LMDE 6) with Brave and upgraded to regular/stable Brave (1.68.128) just now after reading the comments and the issue went away.  Thanks guys.

**Comment by andy-fitch** [comment] 2025-01-21 13:58
I have Lastpass 4.138.3 on Brave and have the same issue - super frustrating. I'm going to switch over to Keeper

**Comment by BobT36** [comment] 2025-01-21 18:21
> I have Lastpass 4.138.3 on Brave and have the same issue - super frustrating. I'm going to switch over to Keeper. Doesn't seem like Lastpass is maintaining their stuff and is becoming irrelevant.

@andy-fitch  Restore the old working version's files from Previous Versions in Windows, then use the "Load Unpacked" method to run that specific (working) version. 
You'll lose updates, but it will work.
