### ISSUE TITLE
Misleading Error Message

### ISSUE THREAD

**Issue by timolson** [brave/brave-browser#35882] opened 2023-05-20 17:42 UTC
![image](https://github.com/brave/wallet-standard-brave/assets/1697115/8ffc8717-e658-4cba-8859-76b811965366)

Our dapp is _not_ a swap site and this message is _extremely_ confusing to our users.

This error seems to show whenever a user submits a transaction which has the same arguments as a previous transaction. Could this be a nonce problem?

Submitting a second transaction with the same parameters as a previous one is normal behavior for our dapp.  How can we suppress this error and get a second transaction through?

Also, how is this cropped error supposed to be helpful?  It's hard to even get a proper error report from our users.

![image](https://github.com/brave/wallet-standard-brave/assets/1697115/da0bbb18-cb8f-4c67-9af9-036d4837377b)

**Comment by bsclifton** [comment] 2024-02-26 06:27
Closing as duplicate of https://github.com/brave/brave-browser/issues/31377

**Closed by bsclifton** 2024-02-26 06:27 UTC
Labels: feature/web3/wallet
