### ISSUE TITLE
Brave v0.68 removed bookmark bar from New Tab Page

### ISSUE THREAD

**Issue by willstocks** [brave/brave-browser#5760] opened 2019-08-22 09:15 UTC
## Description 

I have "Show Bookmark Bar" set to "Off" in Brave's settings. Always have. But it has still always shown in the NTP which is incredibly useful. It's the only page I'd really want it! But now, with v0.68, it is gone 😢 

## Steps to Reproduce

   1. Upgrade from v0.67 -> v0.68
   2. Open v0.68 Brave
   3. Open a new tab
   4. Notice the bookmarks bar is gone

## Actual result:

I've checked the "Dashboard" settings toggles and there's no option to have the Bookmarks Bar back on the NTP alone:
![image](https://user-images.githubusercontent.com/43744514/63502389-65fa1380-c4c5-11e9-8305-27a85888883a.png)

## Expected result:
Up until v0.68, the bookmarks bar showed on the NTP. It would be nice to have the option back to only show it on this page?

## Brave version (brave://version info)

Brave | 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1809 (Build 17763.615)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by SilencerWeb** [comment] 2019-08-22 10:18
Opened this repo to report the same thing, haha

**Comment by rebron** [comment] 2019-08-22 18:25
Closing. Dupe of: https://github.com/brave/brave-browser/issues/4782

**Closed by rebron** 2019-08-22 18:25 UTC
Labels: duplicate

**Comment by SilencerWeb** [comment] 2019-08-23 06:47
@rebron, #4782 was created on Jun 10 but such behavior already was in Brave and got removed in the latest release, it doesn't make any sense

**Comment by willstocks** [comment] 2019-08-28 11:50
@rebron I'm with a @SilencerWeb - I'm a bit confused around this one... the functionality existed, but was removed and is to be re-added at a later date as already is re-enabled in a nightly? Is there a reason it was removed if it was already planned to be re-added?

**Comment by SilencerWeb** [comment] 2019-08-30 08:02
@willstocks, I guess they just decided to hide it by default and add an option to show it. I've just checked in Chrome, it always shows there by default and there is no option to disable it.

But yeah, it makes no sense that they just deleted it without adding an option to enable it, kinda irresponsible.

**Comment by bsclifton** [comment] 2019-09-02 20:31
Sorry for the confusion on this one folks - we could have done a better job for sure. This should be fixed when 0.69.x is released, which would be ~Sep 10th. As noted above, it should be fixed on Nightly (along with Beta and Developer versions)
