### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by loo0niRy** [brave/brave-browser#32578] opened 2023-08-29 14:52 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.57.53 Chromium: 116.0.5845.114
Operating System: Linux 5.19.0-35-generic

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/e74f0a00-fa56-9c0a-0000-000000000000

**Comment by rebron** [comment] 2023-09-12 02:15
Closing as dupe of https://github.com/brave/brave-browser/issues/32579

**Closed by rebron** 2023-09-12 02:15 UTC
