### ISSUE TITLE
[Android] Issue with UI bottom toolbar

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#9276] opened 2020-04-16 21:51 UTC
## Description 
There is an odd UI bug on the bottom bar when in "tab" mode, please see the link below for a video.
See: https://imgur.com/a/kkzCRLs

## Steps to reproduce 

   1. Open Brave
   2. Tap the Tabs button
   3.  Tap to the right of the + button

## Actual result 
 - You'll see two round dots appear

## Expected result
 - nothing :)

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build?

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet):
   - Android version: 10
   
## Brave version
1.5.120

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment] 2020-04-17 03:39
Dupe of #8460

**Closed by srirambv** 2020-04-17 03:39 UTC
Labels: OS/Android, QA/Yes, bug
