### ISSUE TITLE
Bug In Welcome Page On Clean Install (Stable Channel)

### ISSUE THREAD

**Issue by Nihal-Raj** [brave/brave-browser#24358] opened 2022-08-01 13:39 UTC
## Description 
Uninstall Brave Stable (if already installed) and check the `Also delete your browsing data?` option. Reinstall and go through the first run welcome screen, on the last (4th) page after choosing a search engine click on "Done.". Observe nothing happens and the browser is stuck on the page.

## Steps to Reproduce

   1. Uninstall Brave with `Also delete your browsing data?` checked.
   2. Reinstall
   3. Go through the welcome setup and the browser is stuck on the last page. 

## Expected result:
The browser shouldn't get stuck on and continue to brave://newtab (New Tab Page)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.41.100

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Didn't checked
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
 Facing the bug since a welcome page was removed from Brave Core recently, but doesn't gets produced in Nightly channel. Been facing this since quite a few releases.

**Comment by rebron** [comment] 2022-08-01 20:30
@Nihal-Raj What OS are you running? Windows?

**Comment by Nihal-Raj** [comment] 2022-08-02 09:26
> @Nihal-Raj What OS are you running? Windows?

Yes, I'm running Win 11.

**Comment by rebron** [comment] 2022-08-17 20:11
Closing as dupe of https://github.com/brave/brave-browser/issues/24358.
Thank for the report @Nihal-Raj

**Closed by rebron** 2022-08-17 20:11 UTC
Labels: needs-investigation, priority/P5, about-pages/welcome, OS/Desktop
