### ISSUE TITLE
Brave crashes when the last tab in a new window is closed either by middle click or closing the specific tab - Crash Report

### ISSUE THREAD

**Issue by flyweight** [brave/brave-browser#40258] opened 2024-08-03 14:49 UTC
Brave Version: 1.68.134 Chromium: 127.0.6533.88
Operating System: Linux 6.9.11-200.fc40.x86_64

URL (if applicable) where crash occurred: N/A

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open a single URL in a new window
2. Close the tab either by using middle click or clicking the (x) on the tab. **Do not** click the window manager's (x)
3. If there is more than one tab open in the window, middle click or closing individual tabs will not crash. It will only crash when the last tab is closed either by middle click or closing the tab.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/6a400b00-ea85-600c-0000-000000000000

**Comment by briskt** [comment] 2024-08-05 01:04
I've been seeing this for several days also, at least since version 1.68.128. I thought it was only with a private window, but you correctly identified that it occurs with any window.

Brave: Version 1.68.134 Chromium: 127.0.6533.88 (Official Build) (64-bit)
Linux kernel: 6.9.3-76060903-generic
OS: Pop!_OS 22.04 LTS

syslog:
```
/usr/bin/brave-browser-stable: line 39: 23751 Illegal instruction     (core dumped) "$HERE/brave" "$@"
```

**Comment by jjspace** [comment] 2024-08-13 17:47
Cross linking because I came looking for a fix to the same issue and found multiple. Pretty sure this is a Duplicate of #39986

**Comment by iefremov** [comment] 2024-09-16 21:10
can people update and retest? It shouldn't happen in a newer version. Pls reopen if reproduced

**Closed by iefremov** 2024-09-16 21:10 UTC
Labels: crash, priority/P2, OS/Desktop

**Comment by ChadyG** [comment] 2024-09-16 21:52
Unable to reproduce on 1.69.168
