### ISSUE TITLE
Can't login to ProtonMail

### ISSUE THREAD

**Issue by groovinfingers** [brave/brave-browser#2810] opened 2019-01-03 20:12 UTC
## Description 
Cannot login to ProtonMail with Shields down

## Steps to Reproduce

1. Open Brave latest release (currently using 58.18)
2. Turn shields off
3. Go to https://mail.protonmail.com/login

## Actual result:

Site prompts with msg that cookies need to be enabled; click OK
Site compatibility message is displayed which says that WebCrypto (PRNG) and Web Storage are enabled by current browser

## Expected result:
Repeat same steps on Chrome and site shows login form (username and password fields)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Don't know.  Downloaded latest beta build for Mac.  When I run it, blows up.  Crash report sent to Apple.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by IOI-655321** [comment] 2019-01-04 14:30
Works for me on latest stable release with the below.

Tried two urls
https://app.protonmail.ch/login
https://mail.protonmail.com/login

Shields on
Ads and trackers blocked
3rd Party Cookies blocked
Device recognition blocked
All scripts allowed
Connections Encrypted

Blocking scripts led to a message about requiring JS. Reallowing JS removed this message and loaded fine.

Blocking all cookies led to the same issues as groovinfingers experienced.  Re-allowing cookies didn't stop this message going away.  I cleared all cookies/sitedata etc and even closed/re-opened browser and going to the url I had tested disabled cookies on redirected me to 

https://protonmail.com/compatibility 

which showed everything was available.  I could click the login link and login still so everything was working but something is still telling Protonmail that my browser has issues.  I tried enabling disable cache while dev tools is open to make sure it was properly connecting to the server again and still it redirected me.

**Comment by rebron** [comment] 2019-01-04 17:00
Closing can't reproduce.

**Comment by jacobcantele** [comment] 2019-02-27 22:20
I think I can help provide more info here. There is definitely an issue here. For me, Protonmail hangs on the loading screen on first attempt to login. Upon refresh, I'm able to log in with the second attempt. I'm a Manjaro Linux user if that affects anything... Here is a screenshot of my console log.

![screenshot from 2019-02-27 16-16-17](https://user-images.githubusercontent.com/10467486/53527113-a85d0d80-3aab-11e9-88e2-ca8b1ee20baf.png)

**Comment by Brave-Matt** [comment] 2019-03-19 17:54
+1 from Community:
https://community.brave.com/t/protonmail-not-loading-in-brave/46079/17

**Comment by rebron** [comment] 2019-05-14 18:13
cc: @kjozwiak

**Comment by AstroGD** [comment] 2019-06-19 09:02
Works fine first time for me with shields and without shields. Also there is no error being shown in the console. Tried it 3 times, still no issue.

| Title       	| Value                                                                   	|
|-------------	|-------------------------------------------------------------------------	|
|   Version   	|    0.65.120 Chromium: 75.0.3770.90  ( Offizieller Build )    (64-Bit)   	|
|   Revision  	| a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003} 	|
|      OS     	|              Windows   10 OS Version 1903 (Build 18362.145)             	|
| Java Script 	|                             V8   7.5.288.23                             	|

**Comment by kjozwiak** [comment] 2019-06-19 14:08
Thanks for taking a look @AstroGD. I tried reproducing the above many times on different channels and couldn't reproduce either. Had no issues logging into ProtonMail using the default shields settings.

**Comment by bsclifton** [comment] 2019-06-19 15:26
@jacobcantele are you able to try also?

**Comment by rebron** [comment] 2019-06-19 17:11
Bumped to p4 as this looks like login to protonmail is working generally.

**Comment by ChildishGiant** [comment] 2019-07-12 14:40
I'm not having this issue (using https://beta.protonmail.com/) Have you tried disabling extensions?


Title | Value
-- | --
Brave | 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1809 (Build 17763.557)
JavaScript | V8 7.5.288.23

**Comment by kjozwiak** [comment] 2019-10-31 02:22
@groovinfingers can you still reproduce this issue with the latest version of Brave which should be `0.70.121 Chromium: 78.0.3904.70`?

**Comment by jacobcantele** [comment] 2019-11-14 00:16
Fwiw, I am no longer able to reproduce this issue on Brave .68 or .70. I think this is safe to close.

**Closed** 2019-12-02 06:52 UTC
Labels: needs-investigation, priority/P4, webcompat
