### ISSUE TITLE
Cannot replace new-tab-page / Arts and Culture extension

### ISSUE THREAD

**Issue by krono** [brave/brave-browser#1771] opened 2018-10-22 10:58 UTC
## Description 

“Arts and Culture” Extension does not work, “New Tab”-Page cannot be changed

## Steps to Reproduce

   1. Install [Google Arts & Culture extension](https://chrome.google.com/webstore/detail/google-arts-culture/akimgimeeoiognljlfchpbkpfbmeapkh)
   2. Open new tab

## Actual result:

The Brave new tab page is displayed.

## Expected result:

An artwork from the Arts and Culture project should be displayed.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Item | Version 
---|---
Brave | 0.55.18 Chromium: 70.0.3538.67 (official build) (64-Bit)
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
Operating System | Mac OS X
JavaScript | V8 7.0.276.28

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Yes

- Does it reproduce on browser-laptop? 

n/a (no extensions there)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
n/a
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by srirambv** [comment] 2018-10-22 12:18
Dupe of https://github.com/brave/brave-browser/issues/993

**Closed by srirambv** 2018-10-22 12:18 UTC

**Comment by krono** [comment] 2018-10-22 12:19
Oh sorry. I think I have to improve my search-fu…

**Comment by srirambv** [comment] 2018-10-22 12:27
Closing in favour of #1771
