### ISSUE TITLE
User Review: address bar is sometimes disabled

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#36272] opened 2024-02-21 17:53 UTC
## Description 
https://play.google.com/console/u/0/developers/7093250338202488249/app/4972971274345155806/user-feedback/review-details?reviewId=ad2ea4a4-94cc-44c0-830d-abd06bc686ae&corpus=PUBLIC_REVIEWS

I was one of the first Brave users and continue to be a loyal supporter. I am running into an issue that's getting very annoying and I'm hoping the devs will take a note of it. The address bar is sometimes disabled. It's still there as a UI element. But it turns into a band that does nothing or doesn't display the usual address or "Search or type URL" text. Only way to recover is to kill and relaunch.

**Comment by anthonypkeane** [comment] 2024-02-21 17:53
Another report here: https://bravesoftware.slack.com/archives/C0816QH3R/p1708537822988589

**Comment by Brave-Matt** [comment] 2024-02-21 18:00
More detail on the user above — user reached out on Community saying:

> The address of a previously opened website gets stuck in the address bar after closing down tabs, and now the address bar becomes unresponsive until Brave is restarted. This bug has surfaced recently in the last few builds, and it’s not like it happens every time, but it’s quite frequent.

User later goes on to say:
>It occurs only when I’m closing tabs by swiping them away. And do keep in mind, it doesn’t happen every time but it’s quite frequent.

User also shared a recording of the behavior for clarity:
https://drive.proton.me/urls/S7YSA125A8#EfU_mExBNPZf

Original thread: https://community.brave.com/t/address-bar-gets-stuck/523569/8

**Comment by anthonypkeane** [comment] 2024-02-21 19:38
Maybe linked to https://github.com/brave/brave-browser/issues/33316

**Comment by kjozwiak** [comment] 2024-02-22 02:17
> @kjozwiak I think you mentioned on the triage call that this happens to you regularly.
> 
> Assigning to you for QA to attempt to find steps to repo. Whenever you have time.

yup, it happens on my device from time to time. I captured a video of the issue occurring. It's been happening for some time now so definitely not a new regression. I'll try getting some STR/Cases but usually happens when you've just opened a tab and then want to switch to another already opened tab.

https://github.com/brave/brave-browser/assets/2602313/f24247e1-3921-44bf-b01d-8d525cc81e03

**Comment by samartnik** [comment] 2024-02-28 16:12
I suspect this issue is connected with https://github.com/brave/brave-browser/issues/36438 and may be fixed by the same PR

**Comment by samartnik** [comment] 2024-03-07 02:06
I managed to reproduce it. The key is to get to the tab switching mode while web contents is being scrolled.

https://github.com/brave/brave-browser/assets/30602739/395749fb-e4ef-40cf-bbd4-095d144eea40

**Closed** 2024-03-07 18:42 UTC
Labels: bug, feature/url-bar, QA/Yes, OS/Android

**Comment by Uni-verse** [comment] 2024-04-01 19:46
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using version: 

```
Brave	1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
Revision	5d9143e1a0812c53bdc27fd5384591254306a88c
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Unable to reproduce using STR mentioned above.
