### ISSUE TITLE
prompted to allow notifications again after updating to Chromium 94 version

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#18276] opened 2021-09-22 13:32 UTC
## Description 

When updating from a Chromium 93 version with Ads/notifications enabled to a Chromium 94 version, I am being asked to allow notifications again.

Reproduced with 1.29.81/C93 --> 1.30.81/C94 (Release channel) and 1.30.77/C93 --> 1.31.56/C94 (Dev channel).

## Steps to Reproduce

   1. Install 1.29.81 (current release version)
   2. See prompt to allow notifications, allow them
   3. Enable Rewards
   4. Update (on `test` channel) to 1.30.81 RC
   5. Get prompt to allow notifications again

## Actual result:

<img width="358" alt="Screen Shot 2021-09-22 at 8 49 56 AM" src="https://user-images.githubusercontent.com/28145373/134352627-2702287a-6338-4f9a-8ff8-4d61085ca68e.png">

Brave image missing from above notification is known and logged separately (https://github.com/brave/brave-browser/issues/18154)

## Expected result:

Should not be prompted again

## Reproduces how often: 

easily

## Brave version (brave://version info)

`1.30.81 Chromium: 94.0.4606.50` on macOS x64 and arm64

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @brave/legacy_qa @rebron

**Comment by GeetaSarvadnya** [comment] 2021-09-22 13:55
Followed STR from the description. The Issue is not reproducible in `Windows 10 x64 1.30.81` Also https://github.com/brave/brave-browser/issues/18276#issuecomment-924941360 isn't reproducible in Windows. Looks like macOS specific issue.

**Comment by kjozwiak** [comment] 2021-09-22 14:37
Reproduced the issue on my MBP as well after removing all the Brave notifications. Received the following:

**`Example`** | **`Example`**
---------------|---------------
<img width="403" alt="Screen Shot 2021-09-22 at 9 53 34 AM" src="https://user-images.githubusercontent.com/2602313/134364381-efb32595-da66-4b78-a3b0-45ea5a03028a.png"> | <img width="216" alt="Screen Shot 2021-09-22 at 10 03 15 AM" src="https://user-images.githubusercontent.com/2602313/134364402-d58bc421-3d3b-4314-837f-464eee051d64.png">

> Followed STR from the description. The Issue is not reproducible in `Windows 10 x64 1.30.81` Also [#18276 (comment)](https://github.com/brave/brave-browser/issues/18276#issuecomment-924941360) isn't reproducible in Windows. Looks like macOS specific issue.

Definitely a macOS specific as Windows doesn't have these notifications re: notification permissions.

**Comment by mkarolin** [comment] 2021-09-23 13:11
Upstream bug https://bugs.chromium.org/p/chromium/issues/detail?id=1182393

**Comment by kjozwiak** [comment] 2021-09-27 21:13
Closing as this was fixed via https://github.com/brave/brave-core/pull/10237 and uplifted using into `1.31.x` & `1.30.x` via https://github.com/brave/brave-core/pull/10267 & https://github.com/brave/brave-core/pull/10268.

**Closed by kjozwiak** 2021-09-27 21:13 UTC
Labels: release/blocking, OS/macOS, QA/Yes, release-notes/exclude, regression, feature/ads, OS/Desktop
