### ISSUE TITLE
Udemy.com videos do not play with Shields (webcompat)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#4496] opened 2019-05-18 22:06 UTC
## Description 

Videos (courses) on udemy.com do not play unless Shields are disabled. The videos stay stuck on a loading spinner indefinitely with Shields enabled, but begin to play the moment Shields are disabled. cc: @bbondy 

## Steps to Reproduce

   1. Go to udemy.com
   2. Access a course on Udemy.com and play one of the videos
   3. Observe that the video does not play.

## Actual result:

Video is stuck with a loading spinner and does not play.

## Expected result:

Video should play as normal.

## Reproduces how often: 

100% of the time. Very easy to reproduce. 

## Brave version (brave://version info)

Reproduced on: MacOS, Version 0.64.75 Chromium: 74.0.3729.131 (Official Build) (64-bit).

**Comment by ryanbr** [comment] 2019-06-01 02:44
I don't have a login, but found this;

`https://www.udemy.com/aws-certified-solutions-architect-associate/`

Have tested with Sheids On (3rd party/https on) and the video on the right "preview this course", seemed to work fine?

**Comment by ryanbr** [comment] 2019-06-07 09:17
@Miyayes  can you confirm if videos are playable, I had no issues here (see my sample link)

**Comment by Miyayes** [comment] 2019-06-07 16:36
> @Miyayes can you confirm if videos are playable, I had no issues here (see my sample link)

Confirming that they are still **not** playable. In the sample link above, the video in the top right corner plays, but any of the actual course videos (if you go into the course previews in the list) do not play. I also tested with a course I purchased, and still seeing the same problem.

Version 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit), MacOS

**Comment by ryanbr** [comment] 2019-06-07 23:20
Can it be reproduced without the need for buying a course?

**Comment by ryanbr** [comment] 2019-06-22 08:31
@Miyayes does it work if you enable All cookies (instead of 3rd party cookies)

**Comment by Miyayes** [comment] 2019-06-24 18:48
@ryanbr Yes, it can be reproduced without buying a course. For example, go into the free preview course videos in the syllabus on this page: https://www.udemy.com/beginner-to-pro-in-excel-financial-modeling-and-valuation/

Yes, it does work (i.e., the videos play successfully) if you enable Allow All Cookies.

**Comment by ryanbr** [comment] 2019-07-11 10:20
Just revisited this, seems to be fixed? @Miyayes  Just tested in Brave Release and Nightly. seems to play well with cookies now.

**Comment by bsclifton** [comment] 2019-07-11 21:01
Closing - @Miyayes please re-open if issue persists after update 😄

**Closed** 2019-07-11 21:00 UTC
Labels: feature/shields/webcompat, priority/P4, workaround/shields-down
