### ISSUE TITLE
Youtube chat 30 second delay

### ISSUE THREAD

**Issue by Sp0kzz** [brave/brave-browser#36219] opened 2024-02-20 09:53 UTC
https://community.brave.com/t/youtube-live-chat-30-sec-delay/432842

a scriplet is probably causing the issue, it's not "greasylion" though i removed it and the problem still persists.

**Comment by Sp0kzz** [comment] 2024-02-20 09:55
a guy made a userscript that fixes this issue : https://greasyfork.org/en/scripts/474214-fix-brave-bug-for-youtube-live-chat

**Comment by goodov** [comment] 2024-02-20 09:57
cc @ryanbr there's some info on causes triggered by adblocker script doing something wrong:
https://greasyfork.org/en/scripts/474214-fix-brave-bug-for-youtube-live-chat

**Comment by Sp0kzz** [comment] 2024-02-20 10:32
with Shields off the issue still persists

**Comment by TEMP-ad** [comment] 2024-04-01 03:25
I sideloaded the userscript as a scriptlet for Brave to use in the resources.json file, and seems to work fine.

But I found another solution, since I don't care about Youtube and don't even log to it and all, I solved this by using the adblocker to not allow the Youtube service workers (youtube.com/sw.js) to run and be registered and all.

If you go to **Devtools** -> **Application** -> **Service Workers** and check **Bypass for network**, you will notice the chat loads pretty quickly.

So to do the same with the adblocker? all you need to do is to add:

```
||youtube.com$csp=worker-src 'none'
```

then go to `brave://serviceworker-internals/` and unregister the service worker for Youtube.

And that's how I fixed it myself, without tampermonkey or without using the userscript as a sideloaded scriptlet.

Of course there are going to be some side effects by not using the service workers, but it's fine by me.

**Comment by cyfung1031** [comment] 2024-05-03 01:14
> with Shields off the issue still persists

There is no option in Brave to let you fully turn off the scriptlets. The code is injected by Brave to every context within `youtube.com` including iframe.

The Reward/Shield/AdBlock are just "turn off". There are remaining parts to modify the `youtube.com` in Brave.
I believe they are stored as script files. I tried to find them but just some of them can be found.

As Brave do not provide disabling scriptlet option, we cannot test it.

----

If you want to see the scriptlet (built by Brave, inject into every context in `youtube.com`)
You can 
1. visit https://www.youtube.com/robots.txt
2. open console
3. type performance.now
4. You can see the modified `performance.now` (no matter how you turn off the options in Brave)
5. Double click the function text, you will be navigated to the injected scriptlet.

You can view the entire scriptlet injected into `youtube.com`
I believe this is also injected into the iframe so the iframe get broken.

<img width="674" alt="Screen Shot 2024-05-03 at 10 11 11" src="https://github.com/brave/brave-browser/assets/44498510/98e685e3-8fbb-49e9-93a9-a624f269b36a">

**Comment by Brave-Matt** [comment] 2024-05-17 19:46
I can now reproduce this issue as well. Happens whenever I land on a live YT video and sometimes on a live stream that's already ended. Chat box appears blank and the `X` button and "more options" buttons are not visible. ~30s later chat box appears as expected. 

To reproduce:
1. Visit any YT live stream (or previously recorded live stream)
2. Observe chat box or click to show it, then observe blank box with no controls
3. Wait 30s for chat and controls to appear

Would also like to note that the scriptlet mentioned above does resolve the issue for me.

**Comment by bsclifton** [comment] 2024-07-24 18:54
Closing as a duplicate of https://github.com/brave/brave-browser/issues/25694 - we do have a potential fix for this 😄 Stay tuned to that issue for more details

**Closed by bsclifton** 2024-07-24 18:54 UTC
Labels: webcompat/not-shields-related, google, OS/Desktop
