### ISSUE TITLE
Inconsistent automatic profile renaming on upgrade

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6345] opened 2019-10-08 01:15 UTC
Follow up to https://github.com/brave/brave-browser/issues/5814
Profile number does not match Person number.
For example: `Person 3` becomes `Profile 2`

## Steps to Reproduce

   1. Create 3 persons on 0.69.x
   2. Rename `Person 2` to `test`
   3. Upgrade to 0.70.x

## Actual result:

`Person 3` becomes `Profile 2`

0.69.132
![image](https://user-images.githubusercontent.com/34715963/66359506-b21aed80-e977-11e9-97f7-97f04fe7ddb1.png)
0.70.x
![image](https://user-images.githubusercontent.com/34715963/66359584-058d3b80-e978-11e9-8ba6-4ef346fbd4b2.png)

## Expected result:
`Person 3` becomes `Profile 3`

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.70.109 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @petemill @rebron

**Comment by GeetaSarvadnya** [comment] 2019-10-09 17:43
Reproduced in Windows 10 x64- BraveBeta `0.70.111`

**Comment by LaurenWags** [comment] 2019-10-09 21:50
Reproduced on macOS

Brave | 0.70.111 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

**Comment by rebron** [comment] 2019-10-18 16:30
@btlechowski Can you check if `person 1` is `profile 1` ? This maybe a wontfix.

**Comment by btlechowski** [comment] 2019-10-18 20:59
@rebron Yes. Current behavior is as follows:
`Person 1` becomes `Profile 1`
Renamed `Person 2` remains `test` 
`Person 3` becomes `Profile 2`

**Comment by petemill** [comment] 2019-10-18 21:15
This is unavoidable because chromium does not store the number, only the string which could be in any language and as far as I know there's no way to reverse the translation to get the original number. I would say the side effect isn't too bad.

**Comment by bsclifton** [comment] 2019-10-18 22:23
Given the above, I think this is a `wontfix`. Gonna close this out 😄

**Closed by bsclifton** 2019-10-18 22:23 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/profile-manager
