### ISSUE TITLE
brave:// internal URLs get copy-pasted as chrome:// URLs if you cmd+c/v

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#28083] opened 2023-01-26 22:07 UTC
## Description 

brave:// internal URLs get copy-pasted as chrome:// URLs if you cmd+c/v, not sure if this was always the case but seems wrong. 

## Steps to Reproduce

   1. Go to brave://settings
   2. Cmd+C on the omnibox and then Cmd+V somewhere

## Actual result:

You get chrome://settings

## Expected result:
brave://settings

## Reproduces how often: 

Easily. Note that right-clicking and copy pasting seems to work fine (but who does that). 

## Brave version (brave://version info)

MacOS, Nightly. Works fine on Stable.

**Comment by rebron** [comment] 2023-01-27 18:39
Reproducible on 1.49.62 but looks ok in 1.48.x
cc: @emerick

**Comment by rebron** [comment] 2023-02-24 06:13
dupe of https://github.com/brave/brave-browser/issues/28588?

**Closed** 2023-02-24 06:25 UTC
Labels: QA/Yes, release-notes/exclude, regression, branding, OS/Desktop
