### ISSUE TITLE
Token auto populate doesn't work 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#35266] opened 2024-01-11 11:46 UTC
## Description 
Token auto populate doesn't work 

## Steps to reproduce 

   1. Open wallet and select a token in portfolio
   2. Select Send from token details screen
   3. Send page loads but no token is auto populated
   4. Repeat steps for Swap 
   5. Tokens don't auto populate on Swap screen either

## Actual result 
Token auto populate doesn't work 

## Expected result
Tokens should auto-populate

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.62.130

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @onyb @simoarpe

**Comment by simoarpe** [comment] 2024-09-04 13:51
@srirambv I'm not able to reproduce this issue on the latest Android version `1.71.x`.
I'm closing this now.

**Closed by simoarpe** 2024-09-04 13:51 UTC
Labels: bug, QA/Yes, release-notes/include, feature/web3/wallet, OS/Android
