### ISSUE TITLE
VPN connection is lost when device wakes up from sleep

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26351] opened 2022-10-28 11:52 UTC
## Description 

VPN connection is lost when device wakes up from sleep

## Steps to Reproduce

1. Go to Power settings
2. Set `When plugged in, turn off my screen after` - 5 mins
3. Set `When plugged in, put my device to sleep after` - 30mins
4. Clean Nightly profile
5. Enable SKU Flag and VPN Flag
6. Purchase a new VPN subscription
7. Connect to VPN (US -East) and keep system idle for 30 mins
8. System should go to sleep
9. Restart/Wakeup the system, VPN is disconnected

## Actual result:

VPN connection is lost when device wakes up from sleep

## Expected result:
VPN should auto-reconnect after device comes back online

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.47.24 Chromium: 107.0.5304.68 (Official Build) nightly (64-bit)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.755)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Not chekced
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Regression of #25773, #23070
cc: @brave/legacy_qa @simonhong @spylogsster @bsclifton

**Comment by bsclifton** [comment] 2022-10-28 16:26
@spylogsster can you check this out? May have happened after the rework by @simonhong in https://github.com/brave/brave-core/pull/15502

**Comment by spylogsster** [comment] 2022-11-01 11:03
cannot reproduce, code looks working, asked @srirambv for some logs

**Comment by srirambv** [comment] 2022-11-03 14:48
Haven't had a chance to test this. I'll try to get logs and see if it repro's on latest nightly. Will close the issue if can't repro it

**Comment by bridiver** [comment] 2022-11-30 16:36
we should ensure that Brave shows the correct vpn state, but we should not be reconnecting on resume and we should not be disconnecting on suspend

**Comment by bsclifton** [comment] 2022-12-01 06:31
Removed the bug label; this is the OS behavior, which may not be ideal... but we can address in a FAQ.

@simonhong has a commit removing the functionality we had trying to special case the sleep/restore cases here:
https://github.com/brave/brave-core/pull/16163

**Comment by bsclifton** [comment] 2022-12-01 06:32
Closing as `wontfix`

**Closed by bsclifton** 2022-12-01 06:32 UTC
Labels: closed/wontfix, OS/Windows, OS/Desktop, feature/vpn

**Comment by bsclifton** [comment] 2026-02-23 19:26
Reopening after conversation today in VPN pod

Please note we had attempted to solve - but @bridiver shared guidance above about not changing OS behavior:
https://github.com/brave/brave-browser/issues/26351#issuecomment-1332438675

We did implement an opt-in vendor recommended feature called "on demand" which you can see here:
- Issue: https://github.com/brave/brave-browser/issues/29406
- PR: https://github.com/brave/brave-core/pull/17870

**Comment by alekspop26** [comment] 2026-02-23 21:41
I've checked the latest Brave build - it seems that we have that "Reconnect automatically" logic in place which essentially enables "On-demand" VPN feature in macOS. The drawback is that you can't turn off VPN outside of Brave browser easily - e.g. using System VPN tab - the feature doesn't differentiate between system-triggered disconnects and user-triggered disconnects in the System tab.
Well technically you can disable VPN there, but you'll have to go to the settings (admin password required) and turn off "Connect on demand" feature (user password required). Not the greatest CX, but works.
