### ISSUE TITLE
github.com top-left search crashing on kbd ⏎ Enter if Block scripts off

### ISSUE THREAD

**Issue by leotm** [brave/brave-browser#24177] opened 2022-07-21 10:47 UTC
## Description 

Crash when tapping <kbd>⏎ Enter</kbd> in github.com top-left search

## Steps to Reproduce

![Capture](https://user-images.githubusercontent.com/1881059/180195227-6b57a8ba-3957-4176-848d-9a8423ed276a.PNG)

Tap <kbd>⏎ Enter</kbd>

## Actual result:

Crash, browser close, on re-open, after Restore tabs, tabs data lost

## Expected result:

No crash, like searching google.com then hitting <kbd>⏎ Enter</kbd>

## Reproduces how often: 

Easily, everytime atm, only with _Block scripts_ off

## Brave version (brave://version info)

`Win10 1.41.99 Chromium: 103.0.5060.134 (Official Build) (64-bit)`

<html>
<body>
<div id="logo" style="float: right; margin-inline-start: 40px; text-align: end; width: 180px; color: rgb(232, 234, 237); font-family: &quot;Segoe UI&quot;, Tahoma, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(32, 33, 36); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><picture><img alt="Brave logo" src="chrome://theme/IDR_PRODUCT_LOGO"></picture></div>

Brave | 1.41.99 Chromium: 103.0.5060.134 (Official Build) (64-bit)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Windows 10 Version 21H2 (Build 19044.1826)
JavaScript | V8 10.3.174.20
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\-\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Active Variations | AdRewardsStudy:NextPaymentDayBraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=12/MaximumInlineContentAdsPerDay=60/AdServingVersion=1BraveAds.EpsilonGreedyBanditStudy:TreatmentBraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0hBraveAds.UserActivityStudy:Triggers=NTPSI/TimeWindow=15m/Threshold=0.0/IdleTimeThreshold=5sBraveDebounceStudy:EnabledConversionsStudy:NewDefaultPatternDefault1pBlockingStudy:DisabledDisableReduceLanguage:EnabledEphemeralStorageStudy:EnabledExtendedVariationsSafeMode5:SignalAndWriteViaFileUtil5FirstPartyEphemeralDomainBlockStudy:EnabledForceDisableBlinkFeatures:EnabledNativeCosmeticFilteringStudy:EnabledPartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledRequestAdsEnabledApiStudy:EnabledSpeedreaderReleaseStudy:Enabled

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? -
- Can you reproduce this issue with the nightly channel? -

## Other Additional Information:

- **Does the issue resolve itself when disabling Brave Shields?  Yes**
- Does the issue resolve itself when disabling Brave Rewards? -
- Is the issue reproducible on the latest version of Chrome? -

**Comment by wentokay** [comment] 2022-07-21 11:20
seeing the same problem here, including in a private window

brave: 1.41.99 Chromium: 103.0.5060.134 (Official Build) (arm64) 
revision: 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS:  macOS Version 12.4 (Build 21F79)

**Comment by srirambv** [comment] 2022-07-21 12:47
Duplicate of #24164 which is fixed and scheduled to be released as part of 1.41.x HF3

**Closed by srirambv** 2022-07-21 12:47 UTC
Labels: OS/Desktop
