### ISSUE TITLE
Send P3A samples consistently

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#8211] opened 2020-02-12 18:52 UTC
A number of samples are appearing in the P3A reports that are not Mondays. All P3A data should be sent consistently according to the spec.

This issue is being addressed on the stats side with https://github.com/brave/stats/issues/461. The client should also correct for incorrect delivery dates.

**Comment by bsclifton** [comment] 2020-02-24 17:04
@iefremov is this resolved now with https://github.com/brave/brave-core/pull/4531?

ex: is this a duplicate issue of https://github.com/brave/brave-browser/issues/8084

**Comment by iefremov** [comment] 2020-02-24 17:11
@bsclifton not sure, AFAIU the problem is that the wrong weekday is not properly reported? @mattmcalister

**Comment by mattmcalister** [comment] 2020-03-02 18:24
This appears to be resolved. Wait to close this until we can confirm on the stats side.

**Comment by rebron** [comment] 2020-04-17 15:12
Closing. Looks like samples are being sent consistently. @mattmcalister please re-open if it's not the case.

**Closed by rebron** 2020-04-17 15:12 UTC
Labels: bug, features/P3A
