### ISSUE TITLE
BAT Wallet 0.00

### ISSUE THREAD

**Issue by FatSandwich** [brave/brave-browser#12594] opened 2020-11-09 15:02 UTC
On the home page of brave it shows me that I have 1.480 BAT, but when I click on the brave rewards button in the corner it shows 0.00 BAT and 0.00 USD. This issue does not let me contribute, send or withdraw BAT. Am I doing something wrong?Please help, thanks in advance!

**Comment by tmancey** [comment] 2020-11-10 13:21
@FatSandwich I am closing this issue as it is a duplicate of https://github.com/brave/brave-browser/issues/12593 where I have sent you a message

**Closed by tmancey** 2020-11-10 13:21 UTC
Labels: OS/Desktop, feature/ads
