### ISSUE TITLE
Scanning QR Code shows `Sync code has expired` rather than `Sync could not be setup`

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23936] opened 2022-07-08 13:07 UTC
## Description 
Scanning QR Code shows `Sync code has expired` rather than `Sync could not be setup`

## Steps to reproduce 

   1. Install 1.39.123 on Device A
   2. Install 1.41.94 on Device B 
   3. Setup Sync chain on Device A
   4. Move Device B date to August 2nd 2022
   5. Try to scan QR code on Device A to join sync chain
   6. Shows `Sync code has expired` instead of `Sync could not be setup`

## Actual result 

https://user-images.githubusercontent.com/17010094/177997553-73efc1b5-2978-4e08-95c3-880c620fb1a8.mp4

## Expected result
Should show proper error message

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes if/when 1.41.94 is released
- Can you reproduce this issue with the current Play Store Beta version? Maybe Yes
- Can you reproduce this issue with the current Play Store Nightly version? Maybe Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device A: Oppo Reno 5 (Android 12) installed 1.39.123
   - Device B: Samsung Tab A (Android 10) installed 1.41.94 with date set to August 2nd 2022
   
## Brave version
1.41.94

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @AlexeyBarabash

**Comment by AlexeyBarabash** [comment] 2022-07-08 15:58
I can't reproduce with current Nightly or Stable.
Wrong text gives `1.39.123 on Device A` which is not supported now. Closing with `won't fix`
![Screenshot_20220708-183928](https://user-images.githubusercontent.com/24739341/178028079-1beb69e3-54f5-45e3-8a4a-c2220df5a373.png)

**Closed by AlexeyBarabash** 2022-07-08 15:58 UTC
Labels: bug, feature/sync, QA/Yes, OS/Android
