### ISSUE TITLE
brave.com site is blurred in firefox

### ISSUE THREAD

**Issue by Gitleptune** [brave/brave-browser#15879] opened 2021-05-15 23:02 UTC
## Description 

https://brave.com site doesn't function properly as it's all blurred because of something in the stylesheet.
![image](https://user-images.githubusercontent.com/76597257/118379296-066d6100-b5e2-11eb-8499-7c9e17caa9dc.png)

## Steps to Reproduce

   1. Open Firefox
   2. Go to https://brave.com

## Actual result:

Non-working page.

![image](https://user-images.githubusercontent.com/76597257/118380475-aaf3a100-b5ea-11eb-9278-d23cef9b501c.png)

## Expected result:

Working page.

![image](https://user-images.githubusercontent.com/76597257/118380185-97473b00-b5e8-11eb-9c6c-fe6817fb5798.png)

## Reproduces how often: 
Always, but only for certain people.

**Comment by jonathansampson** [comment] 2021-05-18 19:18
I suspect those for whom this reproduces have enabled the [_currently experimental_ support for `backdrop-filter`](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#property_backdrop-filter). As of the time of this writing, the feature is not enabled by default in Firefox. Users must first enable it in `about:config` to reproduce the reported behavior.

Once the feature is enabled, the `#mac-options` element is responsible for the blurred image. This element has the `backdrop-filter: blur` background, but also has a `visibility: hidden` property. It looks like Firefox's current implementation shows the blurred background in site of the `visibility: hidden` property.

**Comment by rebron** [comment] 2021-09-09 23:01
Closing as this looks like it's fixed. Please reopen if still running into issues.

**Closed by rebron** 2021-09-09 23:01 UTC
