### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by sherinhoro12** [brave/brave-browser#26001] opened 2022-10-13 17:38 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.44.105  Chromium: 106.0.5249.91
Operating System: Android 12

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/a6dd0000-580a-fd08-0000-000000000000

**Comment by rebron** [comment] 2022-10-14 16:08
Closing as dupe of https://github.com/brave/brave-browser/issues/26002

**Closed by rebron** 2022-10-14 16:08 UTC
