### ISSUE TITLE
workers not farbling user agent properly - follow up to 12097

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12392] opened 2020-10-29 16:51 UTC
## Description 

When Fingerprinting = strict, the "Worker" column value should match the other values in the row for User Agent on the QA pages. This is not occurring.

## Steps to Reproduce

   1. Clean profile 1.17.x
   2. Visit https://dev-pages.brave.software/farbling.html and https://dev-pages.bravesoftware.com/farbling.html
   3. With FP = standard (default), click Generate fingerprints on both pages.
   4. See FP values are the same across the User Agent row (expected, since "Mode" column says strict.
   5. Change FP = strict for both pages.
   6. Click `Generate fingerprints` on both pages.

## Actual result:

Worker column value for the User Agent row is different than other values in that row. It is the same value from when FP = standard and it is the same between both pages:
<img width="1199" alt="strict 1 copy" src="https://user-images.githubusercontent.com/28145373/97605451-0494d500-19e5-11eb-8f67-94a4c02e88f0.png">

## Expected result:
all values in User Agent row should be the same when FP = strict

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.17.55 Chromium: 86.0.4240.111 (Official Build) dev (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.14.6 (Build 18G6032)

Brave | 1.18.17 Chromium: 87.0.4280.27 (Official Build) nightly (x86_64)
-- | --
Revision | d8c1fe98de8d9c6bd46ebe8b0cc9d2b6bdccca1e-refs/branch-heads/4280@{#556}
OS | macOS Version 10.14.6 (Build 18G6032)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a for 1.16.x, this should be fully implemented with 1.17.x per https://github.com/brave/brave-browser/issues/9190#issuecomment-707172886
- Can you reproduce this issue with the beta channel? yes 1.17.x
- Can you reproduce this issue with the nightly channel? yes 1.18.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @pes10k @pilgrim-brave

**Comment by pes10k** [comment] 2020-10-29 17:36
thanks @LaurenWags !  Was just wondering, do you see the issue in nightly?  Im not able to reproduce there at least, so hopefully this just means something needs to be uplifted or retagged 🤞

**Comment by pes10k** [comment] 2020-10-29 17:41
Specifically it looks like it might be solved by https://github.com/brave/brave-core/pull/6906

**Comment by LaurenWags** [comment] 2020-10-29 17:43
@pes10k yes I can reproduce on nightly 1.18.17 with a clean profile:

<img width="1196" alt="Screen Shot 2020-10-29 at 1 42 38 PM" src="https://user-images.githubusercontent.com/28145373/97611484-a10ea580-19ec-11eb-8e6b-e311476f505e.png">

```
Brave | 1.18.17 Chromium: 87.0.4280.27 (Official Build) nightly (x86_64)
-- | --
Revision | d8c1fe98de8d9c6bd46ebe8b0cc9d2b6bdccca1e-refs/branch-heads/4280@{#556}
OS | macOS Version 10.14.6 (Build 18G6032)
```

**Comment by LaurenWags** [comment] 2020-10-29 17:45
ah, ok that one didn't make it into 1.18.17. let me try 1.18.18.

**Comment by LaurenWags** [comment] 2020-10-29 18:01
Does not reproduce with 1.18.18

<img width="1133" alt="Screen Shot 2020-10-29 at 2 00 30 PM" src="https://user-images.githubusercontent.com/28145373/97613513-2abf7280-19ef-11eb-845d-0d18b121ac48.png">


Brave | 1.18.18 Chromium: 87.0.4280.27 (Official Build) nightly (x86_64)
-- | --
Revision | d8c1fe98de8d9c6bd46ebe8b0cc9d2b6bdccca1e-refs/branch-heads/4280@{#556}
OS | macOS Version 10.14.6 (Build 18G6032)

**Comment by bsclifton** [comment] 2021-01-26 08:39
Closing as this should be fixed in later versions  - cc: @pes10k in case I have that wrong

**Comment by pes10k** [comment] 2021-01-26 09:01
@bsclifton this is not ready to be closed yet, its waiting on a fix @pilgrim-brave is working on to land (see https://github.com/brave/brave-core/pull/7596)

**Closed** 2021-01-28 20:47 UTC
Labels: OS/Android, OS/Desktop, QA/Yes, feature/shields/fingerprint, privacy, privacy-pod

**Comment by stephendonner** [comment] 2021-02-10 19:32
Verified `FIXED` using the inline testcase, with 

Brave | 1.21.50 Chromium: 88.0.4324.152 (Official Build) beta (x86_64)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | macOS Version 11.2.1 (Build 20D74)

<img width="965" alt="Screen Shot 2021-02-10 at 11 30 41 AM" src="https://user-images.githubusercontent.com/387249/107561596-92ab5a80-6b93-11eb-8fff-e54662d539d4.png">

**Comment by srirambv** [comment] 2021-03-02 06:59
Verification passed on OnePlus 6T with Android 10 running 1.21.70 x64 build
- Verified worker column has the same values as others for UA

FP=Standard

![image](https://user-images.githubusercontent.com/17010094/109609464-4369a180-7b23-11eb-82ed-775879aa03d6.png) | ![image](https://user-images.githubusercontent.com/17010094/109609470-46649200-7b23-11eb-9a07-689f2c22d38f.png)
-- | --

FP=Strict

![image](https://user-images.githubusercontent.com/17010094/109609496-52505400-7b23-11eb-8d62-05a8fc18a654.png) | ![image](https://user-images.githubusercontent.com/17010094/109610191-5335b580-7b24-11eb-89a7-a7ed3e735856.png)
-- | --

----------
Verification passed on Samsung Tab A with Android 10 running 1.21.70 x64 build
- Verified worker column has the same values as others for UA

FP=Standard
![image](https://user-images.githubusercontent.com/17010094/109610531-cb9c7680-7b24-11eb-81f1-191656205a6a.png) | ![image](https://user-images.githubusercontent.com/17010094/109610545-cfc89400-7b24-11eb-8024-b80620c491e5.png)
-- | --

FP=Strict

![image](https://user-images.githubusercontent.com/17010094/109610572-d6570b80-7b24-11eb-94f0-ccdb7e8e4252.png) | ![image](https://user-images.githubusercontent.com/17010094/109610586-d9ea9280-7b24-11eb-9e7e-0f00d0316b04.png)
-- | --
