### ISSUE TITLE
Brave Rewards' "Tip" button appears on Reddit, GitHub and Twitter even if I have disabled the Brave Rewards entirely

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#13157] opened 2020-12-11 04:46 UTC
Brave Rewards' "Tip" button appears on Reddit, GitHub and Twitter even if I have disabled the Brave Rewards entirely.
**Brave version 1.18.70, Windows 10 20H2.**

The "Tip" button appeared when I updated to the version 1.18.70, prior to the update I had had the Brave Rewards disabled. Even restarting doesn't solve the issue but sometimes it does. I had to disable them from Tips settings in Brave Rewards menu and restart the browser.

**Comment by MoonshineIndustries** [comment] 2020-12-13 02:10
These guys are so desperate with their sad little referral link via top sites and all the nasty little stuff they do in this browser. Just get firefox or chromium.

**Comment by andrewbusch7** [comment] 2020-12-21 03:12
I no longer see this, @Neon329 is that the same for you?

**Comment by Neon329** [comment] 2020-12-21 06:31
@andrewbusch7 Just turning off the Brave Rewards doesn't do anything. I still have to turn it off from Tips settings and I still have to restart the browser to make the Tips icon actually disaapear.

**Comment by misolori** [comment] 2020-12-23 01:15
I had to use uBlock origin in order to block these. Oh, the irony.

**Comment by misolori** [comment] 2020-12-23 01:28
After tweeting to them about this, someone responded that this is possible under `brave://rewards/` and clicking the tiny icon in the corner:

![image](https://user-images.githubusercontent.com/35271042/102948554-01651500-447b-11eb-8fb8-774e8a0145f3.png)

![image](https://user-images.githubusercontent.com/35271042/102948573-0b871380-447b-11eb-9862-7a2d23a5fbe6.png)

**Comment by resynth1943** [comment] 2020-12-24 14:08
Is this still enabled by default?

**Comment by Neon329** [comment] 2020-12-25 01:41
@resynth1943 I think it was all by design, it's not a bug. The developers wanted to expose a "Tip" button on all those websites (GitHub, Twitter, Reddit) so when users click on it they will be taken to Brave Rewards page so they can know and enable them if they have not enabled it.

**Comment by resynth1943** [comment] 2020-12-25 05:02
Oh... it was by design? 😅 was there any testing done before rolling this out, or am I now a lab rat for Brave's new experiments? 👀 

Anyhow, I'd like to propose that this behaviour be turned off by default. I'm sure #13222 embodies the outrage as a result of this feature.

**Comment by Miyayes** [comment] 2021-01-13 16:57
Related or near duplicate: https://github.com/brave/brave-browser/issues/13341

**Comment by Zireael07** [comment] 2021-02-03 11:37
Still happening.

**Comment by RumbleBronx** [comment] 2021-03-15 11:59
I don't think you can

**Comment by emerick** [comment] 2021-03-29 13:35
Duplicate of https://github.com/brave/brave-browser/issues/12870.

**Closed by emerick** 2021-03-29 13:35 UTC
Labels: OS/Desktop, feature/rewards, greaselion
