### ISSUE TITLE
Trying to visit a site that has an entry in bookmarks searches the site instead of navigating to the site

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#41961] opened 2024-10-29 21:27 UTC
### Description

Some users are reporting that on iOS, when there is a site present in their bookmarks, if they type that site into the address bar and try to visit it, the browser will instead run a search query for that site and display the results, rather than navigating to the site directly. 

### Steps to reproduce

1. In the search bar, search for a site present in your bookmarks or history
2. Press enter
3. The site will be searched in your default search engine and you will not be sent directly to the site

### Actual result

Browser displays search results for the URL entered

### Expected result

Browser should navigate to the site itself

### Reproduces how often

Easily reproduced

### Brave version

1.69.2

### Device/iOS version

iPhone Pro Max

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

User reports:
https://community.brave.com/t/the-search-bar-does-not-send-directly-to-the-site/577264

**Comment by kylehickinson** [comment] 2024-10-30 21:11
Duplicate of https://github.com/brave/brave-browser/issues/41910

**Closed by kylehickinson** 2024-10-30 21:11 UTC
Labels: bug, feature/bookmarks, feature/search, OS/iOS
