### ISSUE TITLE
Crash Report - trying to access a password; goes back to general screen

### ISSUE THREAD

**Issue by saucysoftware** [brave/brave-browser#27506] opened 2022-12-22 01:46 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.46.146  Chromium: 108.0.5359.128
Operating System: Android 13

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Trying to access a password 
2. Keeps bring me back to general screen when I try and click an account password. 
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/c2980000-f164-5909-0000-000000000000

**Comment by bsclifton** [comment] 2022-12-23 19:42
Backtrace https://brave.sp.backtrace.io/p/brave/debug?filters=(_rxid%3Dc2980000-f164-5909-0000-000000000000)&debug=(%224222579%22,0,0)

Another instance can be found here https://brave.sp.backtrace.io/p/brave/debug?filters=(_rxid%3Dc2980000-f164-5909-0000-000000000000)&fingerprint=13688392ddfe6486659dbb640412c67209011f54a093d9ec46fbc5fadec415fd
(reported with https://github.com/brave/brave-browser/issues/27505)

cc: @deeppandya @samartnik @SergeyZhukovsky 

Crash callstack doesn't appear to be symbolized ☹️

**Comment by bsclifton** [comment] 2022-12-23 19:51
I believe this is a duplicate of https://github.com/brave/brave-browser/issues/27089

**Closed by bsclifton** 2022-12-23 19:51 UTC
Labels: crash, priority/P2, OS/Android

**Comment by samartnik** [comment] 2022-12-23 19:55
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Typeface.getWeight()' on a null object reference
	at com.google.android.material.resources.TypefaceUtils.maybeCopyWithFontWeightAdjustment(TypefaceUtils.java:57)
	at com.google.android.material.internal.CollapsingTextHelper.setCollapsedTypefaceInternal(CollapsingTextHelper.java:482)
	at com.google.android.material.internal.CollapsingTextHelper.setTypefaces(CollapsingTextHelper.java:465)
	at com.google.android.material.textfield.TextInputLayout.setEditText(TextInputLayout.java:1441)
	at com.google.android.material.textfield.TextInputLayout.addView(TextInputLayout.java:706)
	at android.view.ViewGroup.addView(ViewGroup.java:5268)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1149)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1148)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1148)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1148)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
	at org.chromium.chrome.browser.password_entry_edit.CredentialEditFragmentView.onCreateView(CredentialEditFragmentView.java:42)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2988)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2898)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1510)
	at android.app.Activity.performStart(Activity.java:8603)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4191)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```
