### ISSUE TITLE
adblock with element chooser not working

### ISSUE THREAD

**Issue by tortino** [brave/brave-browser#19260] opened 2021-11-07 09:24 UTC
## Description 

I use brave V1.31.88 , and I have enabled aggressive adblocking, with following lists:
Easylist-Cookie List - Filter Obtrusive Cookie Notices
Fanboy Annoyances List
EasyList Italy
ABP X Files
uBlock Annoyances List (used with Fanboy Annoyances List)

I then load site https://arstechnica.com/
At the top of the page I see a big emtpy grey space, which I want to hide.
I use the brave element blocker to select that space, and brave adds this rule to brave: adblock page:

arstechnica.com##.ad.ad_crown

If I press F5 to reload the page I still see the emtpy space.
I was expecting to not see it anymore.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Tonev** [comment] 2021-11-09 05:17
@GeetaSarvadnya 

This looks like a duplicate of your issue - https://github.com/brave/brave-browser/issues/19229.

**Comment by rebron** [comment] 2021-11-12 19:54
Closing as dupe of #19229. Better steps to reproduce in this issue though as that's element I'd want hidden as well.

**Closed by rebron** 2021-11-12 19:54 UTC
Labels: OS/Desktop
