### ISSUE TITLE
Freezes caused by Brave?

### ISSUE THREAD

**Issue by pilsnerbeer** [brave/brave-browser#8473] opened 2020-02-29 17:32 UTC
## Description 

I have experienced two major freezes on my Windows 10 PC that I have never ever had before. Both occurred when using Brave browser (there are other services running but I wasnt using them). The most recent one happened when I tried opening new private window; at that moment everything froze (whole system) with loading cursor displayed. after 15-20 seconds the system unfreezed and everything went back to normal (multiple private windows popped up because I was mashing the key combination to no avail). My CPU and memory usage is normal and I do not run any intensive programs.

This may not be even related to the browser but I wasn't using any other program at that time and no new programs were installed. If you also have these issues please comment.

## Steps to Reproduce

   1. uknown so far

## Actual result:

15-20 system freezes, most recent one caused by trying to open private window, dont remember the cause of the previous one

## Reproduces how often: 

Experienced twice today so far.

## Brave version (brave://version info)

Brave | 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.657)

NOTE: it would be helpful to see here (or https://brave.com/latest/) the date of last update, so I can better estimate if future issues are related to browser updates or not.

**Comment by veyselerden** [comment] 2020-04-12 17:34
Same here on Linux. A workaround to this is to disable hardware acceleration via the switch on the settings screen and disable "GPU Rasterization" entry on `brave://flags` page but this will drop the performance of the browser significantly.

**Comment by rebron** [comment] 2020-04-17 19:39
@pilsnerbeer @veyselerden Can you let me know if you two are still having issues with our latest version we released earlier this week:

Brave | 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --

If there's any crash reports unsent, can you go ahead and send as well. It would be under brave://crashes and post the ids here please.

We addressed several performance issues since 1.4.x.

**Comment by veyselerden** [comment] 2020-04-20 02:41
Unfortunately, micro-freezes still occur when hardware acceleration is enabled.

To be spesific about the system I use:
OS: Pop!_OS 19.10 (occurs on any Linux-based OS)
GPU: Nvidia GTX 1060 
CPU: Intel i7-7700HQ
GPU DRIVER: 440.62 (also occurs on 440.82)

**Comment by bsclifton** [comment] 2020-05-12 16:56
Closing as this main issue is being tracked with https://github.com/brave/brave-browser/issues/9481

@veyselerden can you see the solution mentioned in https://github.com/brave/brave-browser/issues/9294#issuecomment-627159375?  I'm curious if you have a similar problem

**Closed by bsclifton** 2020-05-12 16:56 UTC
Labels: needs-more-info

**Comment by veyselerden** [comment] 2020-05-12 18:58
> Closing as this main issue is being tracked with #9481
> 
> @veyselerden can you see the solution mentioned in [#9294 (comment)](https://github.com/brave/brave-browser/issues/9294#issuecomment-627159375)? I'm curious if you have a similar problem

@bsclifton I have founded that the problem is only occuring on the primary laptop display. Problem not occurs on a monitor over HDMI. So I still don't think that it has to do something with nvme ssd.

**Comment by bsclifton** [comment] 2020-05-12 19:41
@veyselerden this is great to know. I wonder what is different about using HDMI versus regular laptop? You might check out brave://gpu with and without HDMI to see if the driver is doing something different. You can make two text files and use the `Copy Report to Clipboard` button to copy text and compare

**Comment by veyselerden** [comment] 2020-05-12 21:20
@bsclifton 
OK, [this](https://pastebin.com/raw/bj7EmNa7) is the output of `brave://gpu` without HDMI (on Laptop display)

And [this](https://pastebin.com/raw/B3KDEHLr) is the HDMI monitor output.

I've ran `diff -u` command and this is the [output](https://pastebin.com/raw/HGA5vj0y)


Links are pastebin..
