### ISSUE TITLE
making Brave Beta active application intermittently causes crash

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1491] opened 2018-10-10 17:41 UTC
## Description 
While working today I had Brave Beta inactive for a bit (unsure how long, but maybe 10 or so minutes) while working in another app. When I clicked on my Brave Beta window to make it active again, it crashed. Unfortunately I was not running from terminal at the time and I have not reproduced yet.

## Steps to Reproduce

I don't have specific steps as I haven't repro'd yet. However I had a twitch video running at the time and rewards enabled. I made Brave Beta inactive by clicking on slack app and working within that for 10 minutes or so. When I clicked on my Brave window, it crashed.

## Actual result:
Brave Crashed.

Uploaded Crash Report ID 786f090f18101a7e (Local Crash ID: 0c690fc1-ff50-4dd2-9d7d-a30e95ac8451)

https://stats.brave.com/dashboard#crash/5bbe34f7815e01001e5edbf6

## Expected result:
No crash.

## Reproduces how often: 
just once so far

## Brave version (chrome://version info)

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? unknown
- Does it reproduce on browser-laptop? no

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @kjozwiak as he mentioned he had a crash when using Twitch
cc @brave/legacy_qa to check on additional platforms.

**Comment by LaurenWags** [comment] 2018-10-10 17:42
@kjozwiak if you have your crash report ID can you add it here for investigation?

**Comment by kjozwiak** [comment] 2018-10-10 18:27
> @kjozwiak if you have your crash report ID can you add it here for investigation?

Sure, here's the crash that I experienced with `0.55.12 Chromium: 70.0.3538.45`:

* https://stats.brave.com/dashboard#crash/5bbe15b2eb34da001eeed0e6

Basically enabled `Rewards`, visited Twitch and started playing a random live stream. Once the stream was playing, switched over to another browser to complete several other things and switched back. Once I switched back, the browser crashed.

The crash that @LaurenWags posted seems a bit different so not sure if the one I experienced is related and just crashed at a different point in the stack, or they're completely different.

**Comment by NejcZdovc** [comment] 2018-10-10 18:33
I think this is dupe of https://github.com/brave/brave-browser/issues/1494 based on crash report

**Comment by GeetaSarvadnya** [comment] 2018-10-10 18:42
Able to reproduce the issue on Windows 10. Please find the below crash id
Crash Report ID 48f218b873cd8612

**Comment by LaurenWags** [comment] 2018-10-10 19:15
May also be related to https://github.com/brave/brave-browser/issues/1488 ?

**Comment by bbondy** [comment] 2018-10-11 01:14
Pretty sure this is a dupe of https://github.com/brave/brave-browser/issues/1494
Please re-test on next beta build.

**Closed by bbondy** 2018-10-11 01:14 UTC
Labels: crash
