### ISSUE TITLE
Add custom lists to set of filter lists used by ad-block and adblock-rust

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#4891] opened 2019-06-13 16:29 UTC
it would be great if users could specify custom lists to add into our filter list set.

Would be useful for more aggressive users, and for debugging / testing new potential filter rules

**Comment by antonok-edm** [comment] 2021-03-18 21:07
This issue appears to be a duplicate of https://github.com/brave/brave-browser/issues/8107, which is tracking more recent development/designs, so I'll close this one.

**Closed by antonok-edm** 2021-03-18 21:07 UTC
Labels: feature-request, feature/shields, feature/shields/adblock, priority/P3
