### ISSUE TITLE
Brave Browser will not launch from Unity on Ubuntu 18.04.2 in Gnome, will launch from "Activities" Panel

### ISSUE THREAD

**Issue by six0h** [brave/brave-browser#5176] opened 2019-07-08 15:33 UTC
Have you searched for similar issues? Before submitting this issue, please check the open issues and add a note before logging a new issue. 

Yes, I have searched, I couldn't find the same issue

## Description 
Brave Browser will not launch from Unity on Ubuntu 18.04.2 in Gnome. The browser will launch hitting "Activities" key and typing name. I have deleted the "Favorite" entry, and re-added from the 

## Steps to Reproduce

   1. Download the latest Brave
   2. Click, "Add to Favorites" to add it to the Unity bar
   3. Try to launch the browser from the activity bar

## Actual result:
Nothing happens. The Brave browser never launches

## Expected result:
The Brave browser should launch as normal

## Reproduces how often: 
Easily Reproduced, have tested on multiple computers

## Brave version (brave://version info)

Brave | 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Linux
JavaScript | V8 7.4.288.25
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
Command Line | /snap/brave/59/opt/brave.com/brave/brave-browser --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=fill-on-account-select,NewExtensionUpdaterService,DesktopPWAWindowing --disable-features=AutofillServerCommunication,AudioServiceOutOfProcess,DefaultEnableOopRasterization,AutofillSaveCardSignInAfterLocalSave,NetworkService,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path | /snap/brave/59/opt/brave.com/brave/brave-browser
Profile Path | /home/cody/snap/brave/59/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the dev channel? Unknown
- Can you reproduce this issue with the nightly channel? Uknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

This is the snap version that has been installed.

**Comment by rebron** [comment] 2019-07-12 15:38
cc: @posix4e Can you take a look?

**Comment by fmarier** [comment] 2019-07-23 18:51
Looks like a dupe of #5023 

@six0h We recommend using our official packages using https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux. That repository is supported and always up-to-date.

**Comment by six0h** [comment] 2019-07-23 18:56
Do you have a snap version?

**Comment by fmarier** [comment] 2019-07-23 20:06
> Do you have a snap version?

We do not currently have an official snap version. The only one that exists at the moment is unofficial and unsupported.

**Comment by kjozwiak** [comment] 2019-07-24 16:42
> Do you have a snap version?

It's also really behind on updates. We're currently on `0.66.101 CR: 75.0.3770.142` and the last snap is on `0.63.48 CR: 74.0.3729.108` which is really behind. Once `0.67.x` goes out next week, the snap version will be behind two CR bumps.

**Comment by mbacchi** [comment] 2020-04-07 20:43
Snaps are now updated more frequently, please see https://github.com/brave/unofficial-snap/ or install using `snap install brave`

**Comment by bsclifton** [comment] 2020-04-26 21:30
@six0h can you try the new Snap? Let us know if it works 😄

**Closed** 2020-04-26 21:29 UTC
Labels: OS/Linux, OS/Linux/snap, setup/installer
