### ISSUE TITLE
Findbar and password autofill dropdown not respecting light theme on Windows (nightly).

### ISSUE THREAD

**Issue by M1ch431** [brave/brave-browser#6516] opened 2019-10-17 05:42 UTC
## Description 
Password autofill dropdowns (username specifically) and the findbar display white text instead of dark text when using the light them on Windows.

## Steps to Reproduce
   1. Install Brave Nightly on Windows with the light theme enabled.
   2. Open a find bar and type text (noting that it's white).
   3. Alternatively, log into a website and save the login information.
   4. Log out and click the username or password fields to autofill your previously entered information. The username should be white.

## Actual result:
Imgur album: https://imgur.com/a/mnMFSk8
White text in the find bar and password autofill dropdown.

## Expected result:
Black text in the find bar and password autofill dropdown when using the light theme.

## Reproduces how often:
Always when using the light theme. The dark theme displays fine.

## Brave version (brave://version info)
Brave | 0.73.2 Chromium: 78.0.3904.50 (Official Build) nightly (64-bit)
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Windows 10 OS Version 1809 (Build 17763.805)

## Version/Channel Information:
I believe this only affects Nightly.

**Comment by rebron** [comment] 2019-10-25 16:33
Closing. duplicate of https://github.com/brave/brave-browser/issues/6573

**Closed by rebron** 2019-10-25 16:33 UTC
Labels: duplicate
