### ISSUE TITLE
Verified on uphold, but not in brave wallet

### ISSUE THREAD

**Issue by HRussellZFAC023** [brave/brave-browser#10104] opened 2020-06-05 09:57 UTC
## Description 

Unable to withdraw funds from brave to uphold as brave has not registered that the wallet has been verified.

## Steps to Reproduce

   1. Fresh copy of brave, enable rewards and link to uphold.
   2. Upload id to uphold, wait a week for them to manually verify you.
   3. Disable shields on uphold and press verify in brave://rewards.

## Actual result:

redirected to:
https://uphold.com/dashboard?application_id=6d8d9473ed20be627f71ed46e207f40c004c5b1a&intention=kyc

![image](https://user-images.githubusercontent.com/22746105/83863399-31d1a580-a71b-11ea-905f-1d69189965f3.png)
![image](https://user-images.githubusercontent.com/22746105/83863014-a3f5ba80-a71a-11ea-976e-31631f5b21a2.png)
![image](https://user-images.githubusercontent.com/22746105/83863106-cbe51e00-a71a-11ea-8810-45191825f6c2.png)

## Expected result:
Brave should register the wallet has been verified

## Reproduces how often: 

Bug seems to affect multiple users:
- https://www.reddit.com/r/brave_browser/comments/frr73b/brave_browser_card_in_uphold_not_showing_up/
- (youtube comments section) https://www.youtube.com/watch?time_continue=100&v=sV3Y0UkW0aI&feature=emb_title

## Brave version (brave://version info)

Brave | 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Linux
JavaScript | V8 8.1.307.32
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=DnsOverHttps,PasswordImport,SimplifyHttpsIndicator,MixedContentSiteSetting,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning --disable-features=AutofillServerCommunication,VideoPlaybackQuality,LookalikeUrlNavigationSuggestionsUI,TextFragmentAnchor,AllowPopupsDuringPageUnload,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers --flag-switches-begin --load-media-router-component-extension=0 --disable-features=AutofillServerCommunication,VideoPlaybackQuality,LookalikeUrlNavigationSuggestionsUI,TextFragmentAnchor,AllowPopupsDuringPageUnload,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,BraveAdblockCosmeticFiltering,HeavyAdIntervention,HeavyAdPrivacyMitigations,MixedContentSiteSetting --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/faux/.config/BraveSoftware/Brave-Browser/Default

#Additional information
In UK

**Comment by eljuno** [comment] 2020-06-06 11:02
Duplicate of #7961?

**Closed** 2020-06-25 09:33 UTC
Labels: feature/rewards
