### ISSUE TITLE
reCAPTCHA Problem

### ISSUE THREAD

**Issue by claytoncarney** [brave/brave-browser#12504] opened 2020-11-03 17:52 UTC
reCAPTCHA not working in Brave, but works fine in Chrome.

   1. Go to a site that uses reCAPTCHA
   2. Try and repeatedly fail (correct images selected, but test still fails)
   3. Go to the same site using Chrome
   4. Works the first time

Version 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64-bit)

I have tried setting Shields Down on these sites. I have repeatedly cleared site data. Brave consistently fails, even though the correct images are selected. I succeed with Chrome on the first attempt (sometimes even receiving the exact same tests).

I first observed this issue a few updates ago. I assumed it was an issue with the sites or reCAPTCHA. However, today I tried several sites with Chrome and had no problems. Now I would conclude the issue is with Brave.

Often times in Brave, the only way I can succeed is to switch to the audio test. The image tests repeatedly fail, even though I am certain I select the correct images. As stated, sometimes I receive the same tests in Chrome and select the same images and it works correctly.

Searching this issue, suggested causes for CAPTCHA problems are browser version or cache. I think I have addressed the cache. Perhaps unrelated, but I have encountered a problem with Amazon's music service using Brave where it rejects connection stating that I'm using too old a version of Chrome. Perhaps the user agent info Brave is providing is somehow contributing to this problem (just a guess).

I have even tried these sites in the latest version of Edge and do not encounter the problems I have with Brave.

At any rate, this is becoming such an issue for me that I am considering switching back to Chrome.

**Comment by bsclifton** [comment] 2020-11-03 18:52
@claytoncarney this should be fixed now - we just released an update. Can you verify you're on 1.16.72?

Closing as duplicate of https://github.com/brave/brave-browser/issues/12359

**Closed by bsclifton** 2020-11-03 18:52 UTC
Labels: OS/Desktop

**Comment by claytoncarney** [comment] 2020-11-03 19:14
Updated to 1.16.72. Initial tests indicate problem has been solved. Thank you!
