### ISSUE TITLE
Tor state is `Disconnected` in New Private Window with Tor tab

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15949] opened 2021-05-18 19:09 UTC
## Description 

Tor state is `Disconnected` in New Private Window with Tor tab

## Steps to Reproduce

   1. new profile on `nightly`
   2. open `File` | `Private Window with Tor`
   3. scroll down to the bottom of the tab
   4. look at `Tor Status`

## Actual result:

![tor-disconnected](https://user-images.githubusercontent.com/387249/118709171-80b00800-b7d1-11eb-8919-953c22d15238.png)

Logs:
```
May 18 11:53:42.000 [notice] Tor 0.4.5.8 opening new log file.
May 18 11:53:42.153 [notice] We compiled with OpenSSL 101010bf: OpenSSL 1.1.1k  25 Mar 2021 and we are running with OpenSSL 101010bf: 1.1.1k. These two versions should be binary compatible.
May 18 11:53:42.161 [notice] Tor 0.4.5.8 running on Windows 8 [or later] with Libevent 2.1.11-stable, OpenSSL 1.1.1k, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
May 18 11:53:42.161 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
May 18 11:53:42.162 [notice] Configuration file "C:\nonexistent" not present, using reasonable defaults.
May 18 11:53:42.163 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Program Files\BraveSoftware\Brave-Browser-Nightly\Application\91.1.26.22\<default>. Is this what you wanted?
May 18 11:53:42.163 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Program Files\BraveSoftware\Brave-Browser-Nightly\Application\91.1.26.22\<default>. Is this what you wanted?
May 18 11:53:42.166 [notice] Opening Socks listener on 127.0.0.1:0
May 18 11:53:42.166 [notice] Socks listener listening on port 57149.
May 18 11:53:42.166 [notice] Opened Socks listener connection (ready) on 127.0.0.1:57149
May 18 11:53:42.166 [notice] Opening Control listener on 127.0.0.1:0
May 18 11:53:42.166 [notice] Control listener listening on port 57150.
May 18 11:53:42.166 [notice] Opened Control listener connection (ready) on 127.0.0.1:57150
May 18 11:53:42.000 [notice] Bootstrapped 0% (starting): Starting
May 18 11:53:42.000 [notice] Starting with guard context "default"
May 18 11:53:42.000 [notice] New control connection opened from 127.0.0.1.
May 18 11:53:42.000 [warn] Got mismatched authentication cookie
May 18 11:53:43.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
May 18 11:53:43.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
May 18 11:53:43.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
May 18 11:53:43.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
May 18 11:53:43.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
May 18 11:53:43.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
May 18 11:53:43.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
May 18 11:53:44.000 [notice] Bootstrapped 100% (done): Done
```

General Info:
```
Tor Version:
Tor Process Id: 11772
Tor Proxy URI:
Tor Connection Status: Disconnected
Tor Initialization Progress:
```

## Expected result:
Should say `Initializing %` until it's ready, at which point it'll read `Connected` under `Tor Status`

## Reproduces how often: 

It's not 100%, but it's pretty prevalent - @kjozwiak can give better insight as to how often this happens for him, as he's dogfooding on Windows

## Brave version (brave://version info)

Brave | 1.26.22 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(64-bit)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | Windows&nbsp;10 OS Version 2009 (Build 21382.1)

**Comment by kjozwiak** [comment] 2021-05-18 20:25
I see this pretty often whenever I launch a Tor window using `Win 10 x64`. It's rare that I see an actual "initialization". It stays "Disconnected" so I usually need to wait ~30s or so until it says "Connected" or just restart the window once again and try again.

**Comment by Brave-Matt** [comment] 2021-06-03 18:55
I have users seeing this on macOS but the Tor status never seems to connect:
https://community.brave.com/t/tor-disconnected-in-osx-continually-have-to-uninstall-and-delete-brave-application-data-and-re-install/255824/2
https://community.brave.com/t/private-tabs-with-tor-is-always-disconnected/248390/4
https://community.brave.com/t/new-private-window-with-tor-not-working/235213
https://community.brave.com/t/tor-broken-with-brave-1-23-75/241744/7

**Comment by stephendonner** [comment] 2021-06-04 18:55
This should be helped quite a bit by the remediation fix(es) in https://github.com/brave/brave-browser/issues/14518.

**Comment by tysoncheah** [comment] 2021-06-16 02:31
Tor status still show disconnected

**Comment by Brave-Matt** [comment] 2021-06-21 18:29
Users are still encountering this issue in v1.25.73:
https://community.brave.com/t/tor-broken-with-brave-1-23-75/241744

**Comment by Awnage** [comment] 2021-07-14 15:58
I am still experiencing this on v1.26.74 (`Win 10 x64`). Tried turning off "Continue running background apps when Brave is closed" but that did not help either.

**Comment by stephenpassero** [comment] 2021-07-22 01:49
Running into the same problem here, on v 1.26.77, on MacOS 11.4. Toggling the "private window with tor" setting does nothing. Same as @Awnage above, `brave://tor-interals` gives this:

```
Tor Version:
Tor Process Id: -1
Tor Proxy URI:
Tor Connection Status: Disconnected
Tor Initialization Progress:
```,
and the other two tabs have no content

**Comment by kjozwiak** [comment] 2021-08-03 16:56
@darkdh sounds like the above might also be fixed by https://github.com/brave/brave-core/pull/9586? With Brave now removing the `watch` folder, assuming this state will be harder to get into? I ran into this a bunch of times on `Win` where launching a Tor window will start in the `Disconnected` state and would never start initializing. You would need to close/re-open a Tor window a few times.

**Comment by darkdh** [comment] 2021-08-03 17:02
@kjozwiak yes, it would be fixed by that PR.

**Comment by Awnage** [comment] 2021-08-03 19:20
One thing I noticed with this on Windows, not sure if it is relevant, but if I manually delete the tor directory, it is not recreated. If I manually create the tor/data directory, I can watch the data directory be deleted when I toggle the "Private window with Tor" but turning it back on does not restore the data directory. Interesting behavior.

**Comment by kjozwiak** [comment] 2021-08-04 02:38
> @kjozwiak yes, it would be fixed by that PR.

Thanks 👍 I'm going to move this into `1.28.x` as https://github.com/brave/brave-core/pull/9586 was uplifted via https://github.com/brave/brave-core/pull/9612.

**Closed by kjozwiak** 2021-08-04 02:38 UTC
Labels: OS/Desktop, bug, feature/tor, regression

**Comment by kjozwiak** [comment] 2021-08-04 02:42
@LaurenWags @rebron in case either of you check this one re: release notes, we can change this to `release-notes/exclude` and can just use https://github.com/brave/brave-browser/issues/16924 to cover the following which were all fixed with https://github.com/brave/brave-core/pull/9586:

* https://github.com/brave/brave-browser/issues/16068
* https://github.com/brave/brave-browser/issues/16924
* https://github.com/brave/brave-browser/issues/15949

**Comment by Awnage** [comment] 2021-08-05 02:40
Just tested again with Nightly. Still no dice. 
Version 1.29.50 Chromium: 92.0.4515.131

**Comment by GeetaSarvadnya** [comment] 2021-08-05 08:20
Reproduced the issue in `Windows 10 x64 - 1.28.102`

```

Brave | 1.28.102 Chromium: 92.0.4515.131 (Official Build) beta (64-bit)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | Windows 10 OS Version 2004 (Build 19041.1110)

```

**Comment by kjozwiak** [comment] 2021-08-06 17:17
Labelling this as `QA/No` as @GeetaSarvadnya opened a follow up via https://github.com/brave/brave-browser/issues/17381. Appears that there's still an intermittent issue where sometimes the Tor window starts in a `Disconnected` state and never attempts to re-connect. I personally can't reproduce the issue using `1.28.103 Chromium: 92.0.4515.131` but seems like @GeetaSarvadnya @stephendonner and @Awnage can.

We'll address the above in https://github.com/brave/brave-browser/issues/17381.
