### ISSUE TITLE
Token Grants | You have a grant waiting for you. 05/08/2019

### ISSUE THREAD

**Issue by jbunce** [brave/brave-browser#5534] opened 2019-08-05 04:16 UTC
## Description 

Token Grants Claim is not operational

## Steps to Reproduce

Click notification -> Pass human check 

## Actual result:

`Oops, something is wrong. Please try again later.
Brave Rewards is having an issue. Please try again later.`

## Expected result:

Claim is operational.

## Brave version (brave://version info)

0.67.123 Chromium: 76.0.3809.87 (Official Build) (64-bit)

**Comment by GeetaSarvadnya** [comment] 2019-08-05 05:02
The issue is Reproducible in Windows 10 running Brave Beta `0.68.116`. Click on `claim` throws  `Oops, something is wrong. Please try again later. Brave Rewards is having an issue. Please try again later`, But grants are claimed and wallet balance shows 4 BAT. After claiming grants the notification is not removed from the BAT logo, 1st click on `claim` shows `The grant is no longer available` message(screenshot2), 2nd click on `claim` button doesn't do anything (same for 3rd, 4th clicks and so on)

![image](https://user-images.githubusercontent.com/38657976/62439906-6ecfb300-b76b-11e9-9094-880bceb1c7c1.png)

![image](https://user-images.githubusercontent.com/38657976/62440123-4d22fb80-b76c-11e9-887d-3563036fbd7e.png)


![image](https://user-images.githubusercontent.com/38657976/62440072-11883180-b76c-11e9-87a1-bfeecb4fdb3e.png)

**Comment by MRVDH** [comment] 2019-08-05 15:33
I've had exactly the same problem.

**Comment by cbrunnkvist** [comment] 2019-08-08 09:22
I had "Oops, something is wrong." _after_ completing the human (-promise! 🤖) challenge, but _before_ upgrading to the latest version. 

Now _after_ upgrading to **0.67.124**, the alert is back saying "you have a grant waiting" but _nothing_ visible happens when I click the "Claim" button.

**Comment by GeetaSarvadnya** [comment] 2019-08-15 15:51
I am seeing the same issue in Dev channel. Uploading Dev profile for further analysis.
https://drive.google.com/open?id=1SKqHXgkqMd7j-JiT5fzf0b204hWiLTcq

cc @evq @jsecretan

**Comment by NejcZdovc** [comment] 2020-04-10 08:18
closing as we changed whole grant code. If this is still a problem please reopen

**Closed by NejcZdovc** 2020-04-10 08:18 UTC
Labels: feature/rewards, needs-investigation
