### ISSUE TITLE
Brave Rewards: Ads Panel

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#2621] opened 2018-12-18 17:58 UTC
Placeholder issue for;

a) the Desktop Brave REwards: Ads Panel (for supported countries)
b) Payments UI flow

cc @jenn-rhim

**Comment by mandar-brave** [comment] 2018-12-18 17:58
@NejcZdovc FYI

**Comment by mandar-brave** [comment] 2019-01-11 16:36
UI Elements for Brave Ads V1.0
Brave Rewards: Opt in
There are two paths to OPT in; for first time users and for existing users who have opted in to Brave Rewards.

For existing users who have upgraded to Brave-Core, they will see a notification opt-in below;
If the user says Turn on - it will turn on Ads for the browser immediately and accrue rewards.
If the user closes out the notification - Ads will remain turned off


For new users that are downloading Brave-Core with 0.59/0.60 as their first Brave version, opting into Brave Rewards will automatically opt them in to Ads, along with Auto-Contribute. These users should never see the “Brave Ads has arrived” notification. Instead, turning on Brave Rewards will turn on Brave Ads. This can happen if the user enables Brave Rewards from the Brave Rewards panel, or if they click on the master on switch (for Brave Rewards as a whole) in Brave Rewards settings.

For users that have the Brave-Core browser but have not opted in to Brave Rewards, no notification is presented when upgraded to 0.59/0.60 build (or later).

Every user can go to Brave Rewards settings and can opt in/out from the Ads Panel. So users who have decided to opt out may be able to get back and turn Ads on later.
Brave Rewards: Ads Panel (Front)


The front side of the Ads panel has four entries;
Estimated rewards since last payment keeps count of all unaccounted confirmed tokens that are yet to be paid but accruing at the client end. The client can aggregate payouts as confirmations come back to the client, aggregated once per day.
Next payment by date shows the date by which the current months payment will be made available to the user. 
The Ad notifications received is the total Ad notifications that showed up on the browser. Updated in near real time based on event logs.
The Ad pages viewed is the total landing pages that the user visited and spent 15 seconds on. Update in near real time based on event logs.

At the end of each month, the estimated earnings, ad notifications, and ad pages counts are reset. When the payment captcha is available, the Next payment-by date is updated to the next month.
Brave Rewards: Ads Panel (Back)


The user will have the choice to set Ads per Hour on the Brave Core desktop as part of the Ads settings. The range of this is 1-6 with default setting at 2 per hour.


Brave Rewards: Ads Payments workflow
Here is the aggregated view of Ads Panel and the Wallet view for Brave Ads.
At the end of each month, 
Estimated rewards gets reset to 0
Ad notifications received is reset to 0
Ad pages viewed is reset to 0
At the 8th of each month;
The Pay by date will reset to the next month
The server will get payments out on the 8th of each month for Ads and the client will receive a Captcha


Brave Rewards: Region not supported Ads Panel
For regions outside of launch areas Ads opt in will be completely disabled for 0.59/0.60 releases. The on/off toggle is grayed out to prevent users from opt in.

**Comment by mrose17** [comment] 2019-01-17 22:17
@mandar-brave - i believe that the only thing left here is what is in https://github.com/brave/brave-browser/issues/2562 ... so i think we can close this now. do you agree?

**Comment by mandar-brave** [comment] 2019-01-17 23:34
Fine @mrose17; we can close this - will file if we see any gaps from a QA perspective.

**Closed** 2019-01-17 23:34 UTC
Labels: feature/rewards, priority/P2

**Comment by srirambv** [comment] 2019-01-29 10:00
@mandar-brave @mrose17 should this be part of `0.59.x` or is this a dupe of #2562 ?
