### ISSUE TITLE
XHR requests canceled across a wide range of websites

### ISSUE THREAD

**Issue by Swader** [brave/brave-browser#2901] opened 2019-01-10 20:28 UTC
Full discussion in Twitter here: https://twitter.com/bitfalls/status/1082896409299505152

---

Version 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
Win10 x64. 

- Does not happen on OS X.
- Does not happen in private browsing mode.
- All extensions were OFF for the duration of reproducing the problems (I have only 3 extensions total - metamask, json viewer and Workona).
- Shields are completely off during all these tests.

---

On certain websites, ajax requests get canceled for no apparent reason (code -3, ERR_ABORT).

Examples are: https://www.diffbot.com/careers and https://gitcoin.co/explorer?network=mainnet&keywords=nimbus&order_by=-web3_created

Here is a HAR reproduction for Diffbot: https://gist.github.com/Swader/a994365480ee63927eb4045163133f89

Example screenshot:

![capture](https://user-images.githubusercontent.com/1430603/50995202-b1efdd80-151e-11e9-911b-3bd15e0d9013.jpg)

**Comment by srirambv** [comment] 2019-01-11 03:48
This looks fixed on the new beta. Could have been the CORS issue which wasn't fixed in 0.59.20.
![screenshot from 2019-01-11 09-17-58](https://user-images.githubusercontent.com/17010094/51012163-ce713180-1581-11e9-8238-7cb79878f699.png)

@Swader mind checking it on the new beta that went out yesterday?

**Comment by Swader** [comment] 2019-01-11 10:36
Still happens, same conditions. All extensions and shields off. I recommend adding a debug output and a command line --debug flag to the executable before every ERR_ABORT emit so that we can find out when these canels are being triggered.

![capture](https://user-images.githubusercontent.com/1430603/51028857-fa49e280-1594-11e9-9da3-9f192c189fa9.jpg)
![capture2](https://user-images.githubusercontent.com/1430603/51028865-fddd6980-1594-11e9-90e3-99b66eb8ef77.jpg)

**Comment by srirambv** [comment] 2019-01-11 10:42
Just to confirm you are still seeing this on [0.59.21](https://github.com/brave/brave-browser/releases/tag/v0.59.21) right?

**Comment by Swader** [comment] 2019-01-11 10:43
Correct: Version 0.59.21 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)

**Comment by srirambv** [comment] 2019-01-11 10:51
@btlechowski @GeetaSarvadnya  could you guys give it a try on Windows?

**Comment by iefremov** [comment] 2019-01-11 11:01
I don't think its the CORS issue, looks like smth different.
Maybe check this behavior in Chrome?

**Comment by srirambv** [comment] 2019-01-11 11:01
I can't reproduce the issue on Linux with the same build.

**Comment by Swader** [comment] 2019-01-11 11:04
It works in latest Chrome and Opera.
It does not happen on any other OS, or even in private mode on Win+Brave.

**Comment by iefremov** [comment] 2019-01-11 11:14
Thanks for checking this. Probably it is also worth checking in Chrome version corresponding to the problematic Brave build (Chromium: 72.0.3626.28) @srirambv

**Comment by Swader** [comment] 2019-01-11 17:04
Another example: https://prvikvadrat.hr/

**Comment by Swader** [comment] 2019-01-14 17:04
Another example on Github. A few refreshes with cache off helped.

![696bf552-c224-495d-9658-637a64c4cdce png](https://user-images.githubusercontent.com/1430603/51127824-c128a100-1826-11e9-9fab-3e3916393540.jpg)

**Comment by Liunkae** [comment] 2019-01-14 19:02
+1 from me (#2930).

- Includes the current beta (0.59.x) and dev (0.60.x) releases, but not the current public release (0.58.x).
- Includes macOS
- Seems to happen with a fresh profile after restarting the browser at least once
- Turning off shields does not help
- More examples of websites:
  - https://github.com while logged in (Recent Activity section does not load)
  - https://hstspreload.org/?domain=brave.com (HSTS check does not finish loading)
  - https://brave.com/jobs/ (job listings do not load)

**Comment by bbondy** [comment] 2019-01-15 04:50
this seems serious and new based on ^, putting P1 and putting as release/blocking.

**Comment by bsclifton** [comment] 2019-01-15 06:59
@Liunkae can you please update to latest? I'm curious if recent fixes resolve this problem for you (works for me!™)

**Comment by iefremov** [comment] 2019-01-15 07:43
Can't reproduce on Dev/Beta on MacOS.

Anyone with a stable repro, please save a netlog. To do this:
 1. Open brave://net-export/
 2. Click "Start logging to disk"
 3. Reproduce the bug in some other tab
 4. Return to brave://net-export, click "Stop logging", attach the resulted file to this ticket :)

Thanks

**Comment by Swader** [comment] 2019-01-15 08:01
Here's an older export from me.
[chrome-net-export-log.zip](https://github.com/brave/brave-browser/files/2758582/chrome-net-export-log.zip)

**Comment by Liunkae** [comment] 2019-01-15 20:17
Here's a netlog: [chrome-net-export-log.json.zip](https://github.com/brave/brave-browser/files/2761251/chrome-net-export-log.json.zip)

Still reproduces (100% of the time) for me with the following:

Brave | 0.60.13 Chromium: 72.0.3626.53 (Official Build) dev(64-bit)
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Mac OS X
macOS version 10.14.2

Steps to reproduce:
1. Start with a fresh profile.
2. Quit the browser.
3. Start Brave again.
4. Go to https://brave.com/jobs
5. Notice that the job listings do not load, even with shields off:

![](https://user-images.githubusercontent.com/19424103/51207163-b0803580-18cf-11e9-84aa-1689861c47ad.png)


The developer console shows that one of the resources was canceled:
![](https://user-images.githubusercontent.com/19424103/51206712-621e6700-18ce-11e9-87b7-f4eee653d019.png)

**Comment by kjozwiak** [comment] 2019-01-16 21:18
Removed `OS/Windows` as this is affecting macOS as well.

**Closed** 2019-01-16 22:40 UTC
Labels: need-more-info, needs-investigation, priority/P1, release/blocking

**Comment by srirambv** [comment] 2019-01-18 10:32
Verification passed on 

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta(64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Linux

* Verified steps from original issue 
* Verified steps from https://github.com/brave/brave-browser/issues/2901#issuecomment-454535749

**Comment by Swader** [comment] 2019-01-18 14:05
Please update issue to ping us when this lands in beta on Win

**Comment by bbondy** [comment] 2019-01-18 14:16
It's already updated on dev and beta

**Comment by Swader** [comment] 2019-01-18 14:48
Indeed it seems to work now. Can you explain how, without an update process?

**Comment by srirambv** [comment] 2019-01-18 16:41
@Swader your app should have been updated to 0.59.25. Could you check brave://version?

**Comment by Swader** [comment] 2019-01-20 08:54
It did indeed, but I don't remember the update process having happened. Might have occurred between a PC restart. Anyway thanks looks good now!
