### ISSUE TITLE
[Sync] Full History Sync not working correctly anymore (Brave or new History datatype issue?)

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#34116] opened 2023-11-05 00:34 UTC
## Description 

I reset my Phones storage and the old History is not synching anymore to my Android phone. I tested from PC to Android first, but also from PC to PC by having a new user data with  `--user-data-dir=` and nothing.

I used to work fine with Brave's old implementation: https://github.com/brave/brave-core/pull/16705, but seems like the official History datatype implementation https://github.com/brave/brave-core/pull/20329 is not working correctly.

Many things are happening here, but now it fails to work properly like in the past, for example:

- When the devices are joined, it will not sync the old items, only new History items

- My main computer is the one with all the many history items, and when I visited a site I previously had in my History, the new items synched okay to other devices and deleting the items, deleted the items.
   The thing is that after a while, some old history items got synched, only one day from ONLY the site I just visited and deleted, but nothing else. just like 3 items, 2 from yesterday and 1 from October 25th. I tested with Twitch for example, and if I visited the Smite game directory many times in the past, **only the latest item** from October 24th was synched. and not the older ones.
   So yes, it seems sometimes only one item is getting synched and only the latest entry, but nothing else, and it is only triggered when the 'new' History item is removed, and then it syncs the old one, far from synching, especially the old implementation that seemed to do the job pretty good.

- Also I got a 'hiccup' for new History items, when I made a brave search 'test' in Android, and then I removed it from my phone, and it still appeared in my normal user data, although other history items removed seemed to work fine.
   Sync-Internals increased the History Delete Directives counter, but seems like it still didn't delete it properly across devices.

If this is meant to work this way, it was working better when History was synched with the 'TypedURLs' data type. If it is not something that should happening, I am reporting this so it gets fixed.
Also, since the flags were removed to go back to the 'old ways', well, no way to test it, it might work fine in the older implementation, and since the new History datatype is the 'future' to keep it with Chromium implementation, then I won't test it on anything but the latest Nightly.

@AlexeyBarabash 

## Steps to Reproduce

   1. Have a device with some history
   2. Create a Sync Chain
   3. Select History
   4. Nothing will get synched
   5. If you have old history data from days ago, and you visit the site, sometimes some elements get synched from that site but not 'all'

## Actual result:

History not synching old items

## Expected result:

All history in sync between devices

## Reproduces how often: 

Always

## Desktop Brave version:

1.62.25 Chromium: 119.0.6045.105 (Official Build) nightly (64-bit)  on PC and Android.
## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13

**Comment by bsclifton** [comment] 2024-05-14 17:17
Closing as duplicate of https://github.com/brave/brave-browser/issues/35042

**Closed by bsclifton** 2024-05-14 17:17 UTC
Labels: OS/Android, OS/Desktop
