### ISSUE TITLE
Wallet route isn't changed when navigating between wallet options

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#31843] opened 2023-07-25 05:19 UTC
## Description 

Wallet route isn't changed when navigating between wallet options

## Steps to Reproduce

   1. Lock wallet 
   2. Restart the browser
   3. URL shows `brave://wallet/crypto/unlock`
   4. Navigate to other pages, URL remains `brave://wallet/crypto/unlock`

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/1440683f-073e-4976-9f7c-5645f976cbb7

## Expected result:
Should update the routes as and when navigated to other pages

## Reproduces how often: 

Intermittent happened once or twice but not constantly reproducible

## Brave version (brave://version info)

Brave | 1.57.23 Chromium: 115.0.5790.102 (Official Build) beta (64-bit)
-- | --
Revision | a6894864a77782c6f711fff91fc00f778dcf4aaa
OS | Windows 11 Version 22H2 (Build 22621.1992)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @josheleonard

**Comment by Douglashdaniel** [comment] 2023-07-25 05:43
Closing as duplicate of https://github.com/brave/brave-browser/issues/31153

**Closed** 2023-07-25 05:43 UTC
Labels: closed/duplicate, intermittent-issue, QA/Yes, release-notes/exclude, regression, feature/web3/wallet, OS/Desktop
