### ISSUE TITLE
Add account routing url is removed when switching to Import/Hardware selection

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19374] opened 2021-11-11 10:32 UTC
## Description 

Add account routing url is removed when switching to Import/Hardware selection

## Steps to Reproduce

   1. Go to Accounts -> Add Account
   2. Popup shows for adding new account. Check the URL shows `brave://wallet/crypto/accounts/add-account`
   3. Click on Import/Hardware, URL changes to `brave://wallet/crypto/accounts/`

## Actual result:

https://user-images.githubusercontent.com/17010094/141281980-c0b198db-113c-4e17-9368-9f4e87e72936.mov

## Expected result:
Probably not change 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.32.95 Chromium: 95.0.4638.69 (Official Build) beta (x86_64)
-- | --
Revision | `6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}`
OS | macOS Version 11.5.2 (Build 20G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Related to #17775
cc: @Douglashdaniel

**Comment by Douglashdaniel** [comment] 2021-11-11 14:28
This was intended and will give the ability to create routes for import and hardware in the future!

**Comment by muliswilliam** [comment] 2023-01-27 12:50
@srirambv Closing this because this modal was replaced with 3 button as show below

![Image](https://user-images.githubusercontent.com/48117473/215091102-3de73688-276e-46e9-a2e8-4b5f1f3e9342.png)

**Closed by muliswilliam** 2023-01-27 12:50 UTC
Labels: priority/P4, QA/Yes, release-notes/exclude, feature/web3/wallet, OS/Desktop, front-end-change
