### ISSUE TITLE
[ads] Add brand hostname to custom push notifications

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#33847] opened 2023-10-23 21:55 UTC
See the thread for more details: https://bravesoftware.slack.com/archives/CJL3G0S95/p1694803727792639?thread_ts=1694798923.945899&cid=CJL3G0S95

**Comment by tmancey** [comment] 2023-10-24 13:50
Closing as a duplicate of https://github.com/brave/brave-browser/issues/31119, @aguscruiz your thoughts on this change, and if design/product agree could you add to https://github.com/brave/brave-browser/issues/31119

**Closed by tmancey** 2023-10-24 13:50 UTC
Labels: enhancement, design/needs-mock-up, needs-discussion, blocked, feature/ads, OS/Desktop

**Comment by aguscruiz** [comment] 2023-10-24 14:39
Added to the designs! 
https://www.figma.com/file/FW1XBDHAtZFUccI3cVUzeh/%F0%9F%93%A2-Ads?type=design&node-id=156%3A5428&mode=design&t=Gjek4MgZLRPe4Ant-1
