### ISSUE TITLE
`Brave Ads has arrived!` notification in BAT icon is shown after browser restart on clean installs

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#7133] opened 2019-11-27 16:11 UTC
Issue originally found by @GeetaSarvadnya (https://github.com/brave/brave-browser/issues/6270#issuecomment-542196777)
@tmancey mentioned that this issue merits its own ticket

## Steps to Reproduce

1. Clean profile
2. Enable rewards
3. Turn off Ads switch
4. Restart the browser

## Actual result:

`Brave Ads has arrived!` notification in BAT icon is shown
![image](https://user-images.githubusercontent.com/34715963/69697616-3c174500-10e3-11ea-965d-0532219beb59.png)

Note: after dismissing the notification, it is no longer shown, even after browser restart.

## Expected result:
`Brave Ads has arrived!` notification in BAT icon is NOT shown

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Reproduced on

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Brave | 1.1.11 Chromium: 78.0.3904.108 (Official Build) beta (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Brave | 1.2.11 Chromium: 78.0.3904.108 (Official Build) dev (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @tmancey @NejcZdovc @rebron

**Comment by NejcZdovc** [comment] 2019-12-04 06:36
+1 from my side

**Comment by NejcZdovc** [comment] 2019-12-04 06:37
I would say that this is P2 and something that we should fix asap as we receive already a lot of complains about notifications

cc @jsecretan @mandar-brave

**Comment by tmancey** [comment] 2019-12-07 18:15
@NejcZdovc edge case that would only happen once on a clean install if the user disables ads (after enabling rewards), the issue is now fixed and PR is awaiting review, thanks

**Closed** 2019-12-10 17:38 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/ads, priority/P3

**Comment by LaurenWags** [comment] 2020-02-07 22:43
Verified passed with

Brave | 1.4.81 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.14.6 (Build 18G103)

* Reproduced the issue on 1.3.113
* Verified STR from description
