### ISSUE TITLE
Many scripts bypass shield

### ISSUE THREAD

**Issue by cortopy** [brave/brave-browser#7725] opened 2020-01-14 16:03 UTC
## Description 

Brave is not blocking ads and scripts on 9to5mac.com

## Steps to Reproduce

   1. Go to https://9to5mac.com/

## Actual result:

as per this screenshot, not a single script is blocked:

![image](https://user-images.githubusercontent.com/8725825/72359668-99dd0c00-36e6-11ea-8696-ffa95f9ca232.png)

Whereas using uBlock Origin 1.24.2 catches and blocks 14 scripts in chrome!!

![image](https://user-images.githubusercontent.com/8725825/72360126-6a7acf00-36e7-11ea-95f8-5329e08c2b4b.png)

## Expected result:
Brave shield should block the same amount of scripts as uBlock Origin and not display any ads

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.2.42 Chromium: 79.0.3945.117Â (Official Build)Â (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Linux

## Version/Channel Information:

Also reproduced on Android

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by ryanbr** [comment] 2020-01-14 21:10
Aware of this, https://github.com/brave/brave-browser/issues/7400

**Comment by ryanbr** [comment] 2020-01-14 21:11
9to5 and other related sites, are trying to get around this. even Ubo is having issues (tested this last night).

**Comment by rebron** [comment] 2020-03-06 17:21
@ryanbr not a dupe of #7400?

**Comment by llacb47** [comment] 2020-08-17 03:22
This can be closed now

**Closed** 2020-08-28 21:07 UTC
Labels: feature/shields/adblock, priority/P3
