### ISSUE TITLE
Fresh installs no longer work without Google Play Services available on system

### ISSUE THREAD

**Issue by SkewedZeppelin** [brave/brave-browser#37855] opened 2024-04-25 10:26 UTC
## Description 
Recent versions of Google Play Services library used by numerous apps such as Chrome, Brave, and Waze now query for available Google accounts immediately on first start and will hang if Google Play services isn't installed/available on the system.

## Steps to reproduce 

   1. Have a Google Play Services-free phone, such as one with CalyxOS (without microG), GrapheneOS (without Sandboxed Play), LineageOS (without gapps/microG), or my DivestOS (without unpriv microG)
   2. Install Brave
   3. Start Brave
   4. It hangs at a white screen

## Actual result 
It never starts.

## Expected result
For it to start like previously.

## Issue reproduces how often 
Every time.
Existing installs can also be broken after clearing app data.

## Version/Channel Information:

Issue started after the v124 rebase.

- Can you reproduce this issue with the current Play Store version?
  - Yes on v1.65.122
- Can you reproduce this issue with the current Play Store Beta version?
  - Yes on v1.66.90
- Can you reproduce this issue with the current Play Store Nightly version?
  - Yes on v1.67.38 and 1.67.44

### Additional information

I've had numerous others confirm this behavior on various devices/systems.

---
edited: to clarify that I mean Google Play Services (GMS). Play Services is both an app library and system component. I did not mean Google Play [Store] itself, although GMS library does have a dependence on seeing both GMS and Play [Store] available.

**Comment by Beatz106** [comment] 2024-04-28 03:32
Brave should not depend on Google to work, it makes no sense... It is also not worth using the issue of brave ads as justification since it ruins everything said before about such a function.

**Comment by Aadam-Marshall** [comment] 2024-04-28 16:44
> Brave should not depend on Google to work, it makes no sense... It is also not worth using the issue of brave ads as justification since it ruins everything said before about such a function.

Sure sure, what you said has been dozens of times in these issues. People with no Google Play Services are having all kinds of problems due to Brave's dependency on it (which is frustrating). The whole thing is more complex however, and Brave relies on GMS for Sync, etc.

See the dev's [comment](https://github.com/brave/brave-browser/issues/22253#issuecomment-1758316855)

**Comment by SkewedZeppelin** [comment] 2024-04-28 16:46
Broken features is one thing, but now it no longer starts at all.
Completely non-functional.

**Comment by Aadam-Marshall** [comment] 2024-04-28 17:00
Absolutely, this is bad and they should prioritize solving that whole GMS dependency thing and do something about it, but I suppose it's difficult.

**Comment by SergeyZhukovsky** [comment] 2024-04-30 19:31
I found the root cause, upstream's chromium 124 update made it impossible to run Brave on devices without Google Play Services. I'm working on the fix and most likely it will be released on the next week's release.

**Closed** 2024-05-01 23:30 UTC
Labels: bug, priority/P2, QA/Yes, release-notes/include, OS/Android

**Comment by SkewedZeppelin** [comment] 2024-05-01 23:38
Thank you @SergeyZhukovsky!

**Comment by kjozwiak** [comment] 2024-05-03 00:41
The above requires `1.65.128` or higher for `1.65.x` verification(s) 👍

**Comment by hffvld** [comment] 2024-05-07 21:48
Verified on `Pixel 7` and `Pixel 8 Pro Emulator` using version(s):
```
Device/OS: 
- Pixel 7 / panther_beta-user 14 AP31.240322.023 release-keys
- Pixel 8 Pro Emulator / Android 13 without `GPS`
Brave build: 1.65.129
Chromium: 124.0.6367.118 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/37855#issue-2263232827 or https://github.com/brave/brave-core/pull/23373#issuecomment-2091866400
2. *Verify*

**ACTUAL RESULTS:**
- Verified that Brave is not crashing or freezing on a device without `GPS`

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/a8668134-b1f9-4aff-9bbd-3bad194d3676) | ![2](https://github.com/brave/brave-browser/assets/128532965/445df013-14ba-4fa7-9f51-d541cab794f2) |

https://github.com/brave/brave-browser/assets/128532965/16843706-4432-4ee0-8adb-3fd5fc35d070
