### ISSUE TITLE
crash when closing multiple inactive tabs with same address

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1488] opened 2018-10-10 16:43 UTC
## Description 
With Rewards enabled, if have two YT tabs open and they are both inactive, when I close the second one Brave crashes. I've only been able to reproduce this with Rewards enabled and YouTube tabs, other sites have not reproduced this crash.

## Steps to Reproduce

1. Clean profile
2. Enable rewards (leave tab open)
3. Open new tab, navigate to YT video (I used https://www.youtube.com/watch?v=dVMYC4s341o)
4. Play video for a bit (20-40s is sufficient)
5. Pause video
6. Go back to chrome://rewards tab --> See video creator listed in auto contribute panel
7. Click on video creator link —> New tab opens with expected page
8. Go back to paused video tab
9. Click on creator name, then click on Videos at top --> You now have two pages open with the same link
10. Open a new tab
11. Make Brave inactive for a few minutes (work in slack, another app, etc)
12. Make Brave active again.
13. While on the new tab, click on x to close one of the video tabs
14. Click on x to close second video tab

## Actual result:
Brave Crashes

* Uploaded Crash Report ID b1a1013b0240da47 (Local Crash ID: 073e2cc9-0dfd-48fd-924b-e473431a7e56) --> https://stats.brave.com/dashboard#crash/5bbe1c2b503f16001e09bb02

* Uploaded Crash Report ID 3068a961e4df6c03 (Local Crash ID: 5b228fb0-5bdc-439d-9465-ff4d365dc97a) --> https://stats.brave.com/dashboard#crash/5bbe1e19815e01001e5de552

* Uploaded Crash Report ID c26fcc0a9b59b57b (Local Crash ID: 725619a2-235d-46ca-9999-de154368e136) --> https://stats.brave.com/dashboard#crash/5bbe26fb503f16001e0a301a

* Uploaded Crash Report ID dd48adb952a83836 (Local Crash ID: d25a9922-6815-422c-90a2-cf2039ae1e57) --> https://stats.brave.com/dashboard#crash/5bbe19df815e01001e5db7ca

## Expected result:
No crash, tab should close

## Reproduces how often: 
easily

## Brave version (chrome://version info)

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes
- Does it reproduce on browser-laptop? no

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @brave/legacy_qa to check on other platforms
cc @NejcZdovc since this is a crash but it's an unusual series of steps. I've only been able to repro with rewards enabled.

**Comment by kjozwiak** [comment] 2018-10-11 00:58
Adding this into the [1.0 (0.56.x)](https://github.com/brave/brave-browser/milestone/7) milestone as we should flush out as many crashes as we can before launching 1.0.

**Comment by bbondy** [comment] 2018-10-11 01:15
Dupe of
https://github.com/brave/brave-browser/issues/1494

I think this crash will appear fairly often in various different cases, so probably wait for next build for more.

**Closed by bbondy** 2018-10-11 01:15 UTC
Labels: QA/Yes, crash, feature/rewards

**Comment by LaurenWags** [comment] 2018-10-15 22:18
Verified passed with

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified STR from description several times and no crash was observed.
