### ISSUE TITLE
twitter banner/tipping mismatch issues

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5580] opened 2019-08-07 18:30 UTC
## Description 
Sometimes when tipping a Twitter user, there is a mismatch of information on the tip banner, the thank you banner, and if applicable, pending contributions (potentially tips panel as well).

## Steps to Reproduce

1. Clean profile.
2. Enable Rewards. Fund wallet or restore a wallet. (I didn’t use KYC’d wallet here, using anon wallet.)
3. Login to Twitter.
4. Navigate to a user’s twitter page.
5. Click on in-line tip button and tip user (user I tipped unverified, not sure if it matters).
6. Navigate to a different user’s twitter page.
7. Click on in-line tip button, view banner, but don’t tip.
8. Repeat steps 6-7 several times until you see a mismatch of info on Tipping banner.
9. Once you see the mismatch, actually tip.
10. Mismatch is displayed on thank you banner as well.
11. Furthermore, if you tipped an unverified pub in step 5/9, when you go to view your pending contributions, there’s a serious mismatch - it looks like you tipped one of the people from the banner, but when you click on the Site in the table, you’ll be taken to a page with your own info.

## Actual result:
Gif picks up from step 8 above:

![twittermismatch-dev](https://user-images.githubusercontent.com/28145373/62647789-52747780-b91f-11e9-8874-9b4dff53f357.gif)

Note that when the tip banner displays, there's a mix of info for `bcrypt` and `torproject`. After tipping when the thank you banner comes up, it says `bcrypt` but you were trying to tip `torproject`. 
When you go to pending contributions table and click on the sites, it looks like `bcrypt` is listed, however when you click on the site in the table, you see your own info. (`bcrypt` was who I tipped in step 5 btw)

## Expected result:
All info on tipping banner, thank you banner, and pending contributions (or actual tip table), should be for the intended recipient.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.100 Chromium: 76.0.3809.87 (Official Build) dev (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

Brave | 0.70.44 Chromium: 76.0.3809.100 (Official Build) nightly (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, could not reproduce on 0.67.x
- Can you reproduce this issue with the beta channel? no, could not reproduce on 0.68.x
- Can you reproduce this issue with the dev channel? yes, reproduced on 0.69.x
- Can you reproduce this issue with the nightly channel? yes, reproduced on 0.70.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
cc @mandar-brave @NejcZdovc @brave/legacy_qa

**Comment by kjozwiak** [comment] 2019-08-08 07:55
Reproduced this several on `macOS 10.14.5 x64` using the following build:

Brave | 0.70.46 Chromium: 76.0.3809.100 (Official Build) nightly (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

<img width="1353" alt="Screen Shot 2019-08-08 at 3 46 49 AM" src="https://user-images.githubusercontent.com/2602313/62685149-14fc0280-b990-11e9-8044-87f0a5bf3dad.png">

<img width="1301" alt="Screen Shot 2019-08-08 at 3 42 29 AM" src="https://user-images.githubusercontent.com/2602313/62685163-1e856a80-b990-11e9-9fd6-edc3177f331a.png">

<img width="1324" alt="Screen Shot 2019-08-08 at 3 54 48 AM" src="https://user-images.githubusercontent.com/2602313/62685252-4aa0eb80-b990-11e9-9531-7484c5a54411.png">

**Comment by jdkuki** [comment] 2019-08-08 23:37
Not able to recreate on 

Brave | 0.70.9 Chromium: 76.0.3809.72 (Developer Build) (64-bit)
-- | --
Revision | 5a04c669126f657f98824b436555cae41b8f4146-refs/branch-heads/3809@{#897}
OS | Ubuntu 19.10


I have a feeling this is because my linux build is too slow and problem is most likely race condition from `tabs_api` setting state via `getProfileUrl`. 

Is issue reproduced if 10-15s of wait time is held between page navigation?

**Comment by kjozwiak** [comment] 2019-08-09 00:20
I reproduced one of the cases several times using the following STR @jdkuki:

* launch `0.70.49 Chromium: 76.0.3809.100` (should be creating a brand new profile)
* under the tab that has the welcome page opened, click on the BAT icon --> `Join Rewards`
* load http://twitter.com and login
* once the page loads, quickly type `mandar` under `Search Twitter` on the top right
* click on `mandar` via the search results
* once https://twitter.com/Mandarstwit loads, click on the BAT icon with the verified checkmark

You'll notice the following:

<img width="1378" alt="Screen Shot 2019-08-08 at 7 34 58 PM" src="https://user-images.githubusercontent.com/2602313/62744411-749bf180-ba14-11e9-8f4b-a083e2f15af4.png">
<img width="1372" alt="Screen Shot 2019-08-08 at 7 35 06 PM" src="https://user-images.githubusercontent.com/2602313/62744412-7665b500-ba14-11e9-8ece-7ed23627203a.png">
<img width="359" alt="Screen Shot 2019-08-08 at 7 37 19 PM" src="https://user-images.githubusercontent.com/2602313/62744414-78c80f00-ba14-11e9-848b-93a513982803.png">
<img width="589" alt="Screen Shot 2019-08-08 at 7 37 28 PM" src="https://user-images.githubusercontent.com/2602313/62744415-7a91d280-ba14-11e9-8ce3-b69f5d3c07a1.png">

**Comment by emerick** [comment] 2019-08-09 00:26
@jdkuki Definitely make sure you're signed in on Twitter, as I suspect this problem is tied to new Twitter and you have to be signed in to get that.

**Comment by emerick** [comment] 2019-08-09 01:13
@NejcZdovc @jdkuki I think there's a disconnect when we're saving the publisher info so that we end up with the media key pointing to the wrong user ID. I noticed that there are two ways to call `SavePublisherInfo` in `twitter.cc`. One happens when you tip and one happens when you visit a Twitter URL. In the first case we have the screen name and user ID available to us and it all works as you'd expect. In the second case, I think we're scraping the DOM for the user ID and that leads to this problem.

**Comment by jdkuki** [comment] 2019-08-09 02:23
Was not able to reproduce exactly but have this issue:

1. Clean profile
2. Open twitter / login
3. Go to any profile page
4. Click BAT Panel icon (do not click inline tip button)
5. BAT Panel will be blank

Looks like BAT panel / page browsing doesn't create `publisher_key` in the format it expects to read.

If you click an inline tip button for user, then go back to their profile page and click panel button, correct info shows up.

**Comment by mandar-brave** [comment] 2019-08-09 02:29
thanks @jdkuki - do you believe the issue above can potentially be causing the issue here?

**Comment by jdkuki** [comment] 2019-08-09 02:32
not 100% sure but seems like two sides of the same coin

**Comment by LaurenWags** [comment] 2019-09-11 16:59
Reviewed this on a call with @NejcZdovc 

Unable to reproduce with 

Brave | 0.72.11 Chromium: 77.0.3865.65 (Official Build) nightly (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | macOS Version 10.13.6 (Build 17G5019)

But able to easily reproduce with

Brave | 0.69.125 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

**Comment by kjozwiak** [comment] 2019-10-02 01:29
@LaurenWags mind going through the above and see if you can reproduce using `0.69.x`? I spent ~2hrs going through the above cases using `0.69.131 CR: 77.0.3865.90` and couldn't reproduce. 

Used both `anon` and `KYC` accounts for the following cases:

* https://github.com/brave/brave-browser/issues/5580#issue-478077005 & https://github.com/brave/brave-browser/issues/5580#issuecomment-519732180 and 
* went through some exploratory QAing and couldn't reproduce

I also made sure that the Twitter ID's are correctly being added into the DB via:

* visiting a new user via their page and clicking on the panel
* clicking on a new user via clicking inline tipping and bringing up the banner
* tipping via both inline and panel (using `anon` & `KYC` methods)

Ensured the Twitter's ID are correctly being added in `publisher_info_db`:

<img width="1127" alt="Screen Shot 2019-10-01 at 9 26 05 PM" src="https://user-images.githubusercontent.com/2602313/66011782-7329fb00-e492-11e9-8e5e-a9031fc744d1.png">
<img width="909" alt="Screen Shot 2019-10-01 at 9 24 24 PM" src="https://user-images.githubusercontent.com/2602313/66011788-7624eb80-e492-11e9-8685-bc0f0d73dc06.png">

**Comment by LaurenWags** [comment] 2019-10-02 13:49
Unable to reproduce with

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* used mix of anon and KYC'd wallets for testing
* tested both prod and staging
* tipped via in-line tipping and from the panel
* tested scenarios from https://github.com/brave/brave-browser/issues/5580#issue-478077005 and https://github.com/brave/brave-browser/issues/5580#issuecomment-519732180

**Comment by NejcZdovc** [comment] 2019-10-02 16:25
thank you are for really pushing hard on testing this one. Will close it for now and let's reopen it if we still have problems

**Closed by NejcZdovc** 2019-10-02 16:25 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards, priority/P2
