### ISSUE TITLE
Contribution date stuck in the past

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2425] opened 2018-12-10 13:56 UTC
## Description 
Logged based on https://github.com/brave/brave-browser/issues/1693#issuecomment-445307249

User reported that their contribution date is still in November (11/18/2018). This date should have been moved forward if a contribution couldn't occur.

## Steps to Reproduce
Unsure exactly, the below is just a guess:

   1. Have a profile that gets upgraded to each new Release version
   2. On an older version (without retry logic), have a scenario where contribution can't go thru (not enough funds, maybe a-c was turned off, maybe grant server was down at time that contribution was supposed to happen, etc)

## Actual result:
Contribution date does not get moved. As a result, it is stuck in the past.

## Expected result:
If contribution does not occur, date should get moved.

## Reproduces how often: 
unknown

## Brave version (brave://version info)
unsure

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
On builds with retry logic maybe this is resolved, but we need to fix the contribution date for any users who got into this scenario prior to retry logic being implemented.

**Comment by LaurenWags** [comment] 2018-12-10 13:57
@disfit could you please take a look and see if there's any info you can help provide? Specifically, I'm hoping for Steps (long shot, but doesn't hurt to ask), Version (I know you mentioned your on 0.57.x now, but do you recall what version you were on when your contribution didn't go thru?), anything else you think could be helpful.

**Comment by glawrence** [comment] 2018-12-10 15:21
I can confirm I have the same issue, currently running 0.57.18 on macOS

**Comment by disfit** [comment] 2018-12-10 17:46
@LaurenWags I have not had any contribution go thru since May using the old Muon install, see https://github.com/brave/browser-laptop/issues/13156#issuecomment-408000197 for more information.

I installed version 0.55.22 to run next to my Muon version to try it out. I accepted a BAT grant in the newly created wallet. I found out that it was not possible to exclude publishers, so did not migrate / restore my old wallet and kept using the Muon version in the hope that a contribution would take place.

After the update to 0.56.12 on 2018-11-09 I still had the same problem of not being able to exclude publishers. This changed with the update to 0.56.14 on 2018-11-20. As far as I now, no contribution was made from my new wallet which had the 25 BAT grant. At that time I also restored my original wallet which at that time contained some earlier BAT grants and my own 700+ BAT, and stopped using the Muon version.

I have updated to 0.56.15 on 2018-11-23 and 0.57.18 on 2018-12-07.

As far as I now, the contribution date has not changed at any time during the above period.

All installations have been on Linux Mint 18.3 using the install instructions for Linux Mint 17+ on https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

I hope the above helps, but if you need more / different information, please let me know.

**Comment by glawrence** [comment] 2018-12-10 17:59
I took a different approach, on my Mac I upgraded from the Muon version to the Chromium version and moved my wallet across but since doing so my date has got stuck at 18/11/2018. Although I admit I keep turning Brave Rewards off and on owing to #1693

**Comment by reedriley** [comment] 2018-12-12 21:31
I think this might be a dupe of #2206 - but not entirely sure.

And for what it's worth, I'm hitting this and have been for the past several versions.  I'm running v0.57.18 on a mac right now.

**Comment by NejcZdovc** [comment] 2018-12-21 04:48
closing this one as dupe of https://github.com/brave/brave-browser/issues/2206

**Closed by NejcZdovc** 2018-12-21 04:48 UTC
Labels: QA/Yes, bug, feature/rewards, priority/P3
