### ISSUE TITLE
[Desktop] Address bar search broken in private windows when search provider set by extension

### ISSUE THREAD

**Issue by dharb** [brave/brave-browser#10549] opened 2020-07-02 23:05 UTC
## Description 
Many web extensions set the default search provider via [chrome_settings_overrides](https://developer.chrome.com/extensions/settings_override), for instance
- [Qwant for Chrome](https://chrome.google.com/webstore/detail/qwant-for-chrome/hnlkiofnhhoahaiimdicppgemmmomijo)
- [DuckDuckGo Privacy Essentials](https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg)
- [Ecosia](https://chrome.google.com/webstore/detail/ecosia-the-search-engine/eedlgdlajadkbbjoobobefphmfkcchfk)

When one of these is installed and allowed in private windows, searching done via the address bar stops working in private windows.

## Steps to Reproduce

   1. Install one of the extensions listed above that sets the default search provider
   2. Go to extension details page, flip "Allow in private" toggle to on
   3. Open private window and try to search for something from the address bar

## Actual result:
- if search query is "something", Brave tries to load http://something/
- if search query contains a non-URI encoded character such as a space, pressing enter doesn't do anything

## Expected result:
Searching from address bar should work as it does in normal non-private windows.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Windows 10 OS Version 1909 (Build 18363.900)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by dentistformyeye** [comment] 2020-07-05 03:05
In an earlier version of Brave turning off "Search privately with DuckDuckGo" in private windows was a workaround, but that doesn't seem to work anymore.

**Comment by atahabaki** [comment] 2020-08-04 03:47
Hi!..

I've developed a Chrome extension which uses Chromium's Omnibox API for quickly search anything, anywhere. Then uploaded it to Chrome web store which I called it "smartbox: smart search".

If you're interested in, take a look at [here](https://chrome.google.com/webstore/detail/smartbox-smart-searching/ligbhhoebpfhhafppbnieajgokmcccah)

It works pretty well with Google Chrome (works on incognito mode too). On Brave, it is not working.

Please fix this issue. Maybe this is not an issue but. Make an exception for this to work on both private and Tor sessions too.

Have a great day.

**Comment by posita** [comment] 2020-10-28 18:43
I'm getting crashes (two reports submitted this morning) when searching in private tabs with DuckDuckGo's Privacy Extension enabled in private tabs. Originally filed as duckduckgo/duckduckgo-privacy-extension#510, but it sounds like it might actually be related to this issue. Let me know if crash submission IDs would be helpful and how I should provide them. (I'm not sure what information leaks if I post the IDs here.)

**Comment by dentistformyeye** [comment] 2020-11-21 20:02
I'm also getting crashes now with DuckDuckGo Privacy Essentials enabled in private windows.
Brave Version: 1.17.73  Chromium: 87.0.4280.67
Operating System: Mac OS X 10.15.7

With "Search privately with DuckDuckGo" on private window NTP on:
Crash ID: crash/20310000-cf79-6b05-0000-000000000000
Off:
Crash ID: crash/67310000-cf79-6b05-0000-000000000000

**Comment by kjozwiak** [comment] 2021-01-29 17:40
Another +1 from https://github.com/brave/brave-browser/issues/11947 when using `DuckDuckGo Privacy Essentials`.

**Comment by bsclifton** [comment] 2021-04-12 05:26
Closing as a duplicate of https://github.com/brave/brave-browser/issues/10601

**Closed by bsclifton** 2021-04-12 05:26 UTC
Labels: OS/Desktop, feature/extensions, feature/search, needs-discussion, priority/P4
