### ISSUE TITLE
Android P3A for Brave.Uptime.BrowserOpenMinutes

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#12542] opened 2020-11-05 17:09 UTC
Follow up from https://github.com/brave/brave-core/pull/7016#issuecomment-721420347 .

`Brave.Uptime.BrowserOpenMinutes` uses `BrowserListObserver` class which is available on desktop, so the metric does not work on Android.

Need to implement.

**Comment by DJAndries** [comment] 2024-05-03 17:18
duplicate of https://github.com/brave/brave-browser/issues/33687

**Closed by DJAndries** 2024-05-03 17:18 UTC
Labels: OS/Android, features/P3A, feature/new-metric
