### ISSUE TITLE
BAT dropdown shows wallet details even before rewards is enabled 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#1429] opened 2018-10-04 19:43 UTC
## Description 

BAT dropdown shows wallet details even before rewards is enabled 

## Steps to Reproduce

   1. Install beta using `sudo apt install brave-browser-beta`
   2. Launch browser from terminal
   3. Click on BAT button in URL bar, shows Wallet details even though rewards is not enabled. Console logs errors 
```
[28798:28798:1004/145732.617047:ERROR:rapidjson_bat_helper.h(52)] Failed to parse:# go away 
User-agent: * 
Disallow: /  
```

## Actual result:

https://youtu.be/p2zkM1Y5CCI

## Expected result:
Should show the default dropdown to enable rewards 

## Reproduces how often: 

Easy

## Brave version (chrome://version info)

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  Yes on Beta build
- Does it reproduce on browser-laptop? N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

I couldn't reproduce this on Windows. @kjozwiak @LaurenWags to check once on macOS

**Comment by btlechowski** [comment] 2018-10-04 20:04
Not reproducible on Win7 x64

![image](https://user-images.githubusercontent.com/34715963/46499820-6fcd4680-c821-11e8-9b64-b63c89e5597f.png)


Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Windows 7

**Comment by NejcZdovc** [comment] 2018-10-04 20:06
can't reproduce on macOS

**Comment by srirambv** [comment] 2018-10-04 21:28
I cant reproduce this on a VM but consistently reproduce on laptop. Even after running `rm -rf ~/.config/BraveSoftware/Brave-Browser-Beta/` and creating a new profile.

**Comment by LaurenWags** [comment] 2018-10-05 21:54
I could not reproduce on macOS using the following build:

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

**Comment by kjozwiak** [comment] 2018-10-09 14:29
> I cant reproduce this on a VM but consistently reproduce on laptop. Even after running `rm -rf ~/.config/BraveSoftware/Brave-Browser-Beta/` and creating a new profile.

Did you ever manage to reproduce this on your Win machine?

**Comment by kjozwiak** [comment] 2018-10-09 14:31
Seems like this is only affecting Linux. @LaurenWags and @NejcZdovc couldn't reproduce on macOS and @btlechowski @srirambv couldn't reproduce the issue on Win.

**Comment by kjozwiak** [comment] 2018-10-25 03:45
I couldn't reproduce using the following platforms:

* Mint 18.3 x64 [Desktop] - **Couldn't reproduce**
* Ubuntu 18.04 x64 [VM] - **Couldn't reproduce**

Used the following build for the above tests/checks:

Brave | 0.56.6 Chromium: 70.0.3538.67 (Official Build) beta(64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux

@srirambv when you have some time, mind checking this again on your Ubuntu desktop and see if it's still an issue? If you can't reproduce it, lets close this off 👍

**Comment by srirambv** [comment] 2018-10-25 13:46
I can reproduce this on Linux Desktop Ubuntu 18.04. (clean OS install and beta)

**Comment by NejcZdovc** [comment] 2018-10-25 13:49
@srirambv which version you are using for testing?

**Comment by srirambv** [comment] 2018-10-25 14:13
@NejcZdovc  https://youtu.be/EwERdaXBlII

**Comment by NejcZdovc** [comment] 2019-01-04 11:12
@srirambv is this still a problem on 0.58?

**Comment by srirambv** [comment] 2019-01-04 11:41
@NejcZdovc yes I can still reproduce this consistently on my machine.

**Comment by kjozwiak** [comment] 2019-01-05 00:47
@srirambv is this reproducible with `0.59.18`? I quickly tried on my Mint 18.3 x64 VM and couldn't reproduce.

**Comment by srirambv** [comment] 2019-01-05 02:51
@kjozwiak I can actually reproduce this on all channels on my machine.

**Comment by NejcZdovc** [comment] 2019-01-21 11:07
closing as dupe of https://github.com/brave/brave-browser/issues/3016. This was fixed

**Closed by NejcZdovc** 2019-01-21 11:07 UTC
Labels: OS/Linux, QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards, needs-investigation, priority/P3
