### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by fsclavo** [brave/brave-browser#28780] opened 2023-02-27 17:15 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.48.171  Chromium: 110.0.5481.177
Operating System: Linux 5.15.0-60-generic

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Nothing special, just normal browser use.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/25870500-b06f-ac09-0000-000000000000

**Comment by rebron** [comment] 2023-02-27 19:22
closing as dupe of https://github.com/brave/brave-browser/issues/28783

**Closed by rebron** 2023-02-27 19:22 UTC
