### ISSUE TITLE
https://www.photopea.com/ ads showing in shields

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#40619] opened 2024-08-22 23:05 UTC
### Description

Opening https://www.photopea.com/ 

### Steps to reproduce

1. Opening https://www.photopea.com/
2. wait 5-20secs.
3. ads and a antii-adblock popup

### Actual result

![photopeeas](https://github.com/user-attachments/assets/5a72e2cd-f867-471c-8ee0-b2e7bb1ee3e7)

### Expected result

![photopeeas2](https://github.com/user-attachments/assets/66d4fb65-6ed7-4c3e-992e-34f41bf8d22f)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave 1.69

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

`||pagead2.googlesyndication.com^$xhr,3p,redirect-rule=noop.js,method=head,from=photopea.com` related rule

**Comment by Arthurprnt** [comment] 2024-08-28 08:36
Hello,
By removing ads, some features of the website are broken.
For exemple: https://github.com/photopea/photopea/issues/7108

**Comment by kuckir** [comment] 2024-08-28 15:32
Hi guys, I am the creator of Photopea. In your last release of Brave, you completely break Photopea. Why do you do it?

https://github.com/photopea/photopea/issues/7085
https://github.com/photopea/photopea/issues/7087
https://github.com/photopea/photopea/issues/7089
https://github.com/photopea/photopea/issues/7090
https://github.com/photopea/photopea/issues/7094
https://github.com/photopea/photopea/issues/7094
https://github.com/photopea/photopea/issues/7100
https://github.com/photopea/photopea/issues/7101
https://github.com/photopea/photopea/issues/7108
https://github.com/photopea/photopea/issues/7109

I hope you are happy to cause your users so much pain. And it is painful for me to have to tell everyone to switch to a different browser.

If you dont fix it in 2 days, Photopea.com in Brave will be just a white screen saying "Switch to a better web browser."

**Comment by bsclifton** [comment] 2024-08-28 17:36
Hi @kuckir 

I assure you, it's not the intention to break Photopea. This is my first time hearing about the website

Thanks for sharing the specific issues - I'll see if we can help with a webcompat fix. I can confirm the [official account](https://github.com/photopea/) is blocked - but I don't see why at the moment.  I suspect there may have been some heated messages which other repository owners ended up deleting.  I can definitely unblock this account if we're able to keep a good relationship here

Let me share this issue - stay tuned

**Comment by kuckir** [comment] 2024-08-28 19:50
I do allow my users to block ads in Photopea. 

But I want to tell them, that my income depends on them watching ads, or paying for a Premium account, and ask them to watch ads.

If you will try to remove my message "Are you blocking ads?", I will detect it and I will not allow a user to use any part of my work in such a case.

**Comment by ryanbr** [comment] 2024-08-28 20:09
Its been fixed.

**Comment by ShivanKaul** [comment] 2024-08-28 20:33
Closing this out since the original issue opened by @ryanbr is fixed and the [website breakage also seems to be fixed](https://github.com/brave/brave-browser/issues/40735). Tracking adblock-rust support for the filter mentioned in the issue description here: https://github.com/brave/adblock-rust/issues/391

**Closed by ShivanKaul** 2024-08-28 20:33 UTC
Labels: priority/P4, OS/Desktop

**Comment by ShivanKaul** [comment] 2024-08-28 20:39
(Just a reminder about Brave's blocking goals and policy: https://github.com/brave/brave-browser/wiki/Blocking-goals-and-policy)
