### ISSUE TITLE
Scriptlets not being downloaded [intermittent] 

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#39842] opened 2024-07-18 00:16 UTC
### Description

Scriptlets are missing or not downloading on some devices causing some tests to fail and ads leaking on YouTube

Seems to be an issue with 1.68 only, 1.69 is not impacted.

### Steps to reproduce

1. New install
2. Launch browser, restart app
3. Open test page - https://dev-pages.brave.software/filtering/scriptlets.html
4. Run the test

### Actual result

'This Frame' column showing `null`

![IMG_6798](https://github.com/user-attachments/assets/80066080-f9e6-49d3-9f27-ac877d3da5c7)

### Expected result

![IMG_3836](https://github.com/user-attachments/assets/52d91e44-6b90-4cd8-9f81-822b0e8797b2)

### Reproduces how often

Easily reproduced

### Brave version

1.68.117 - reproducible
1.69.115 - NOT reproducible

### Device/iOS version

iPhone, iPad

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment] 2024-07-31 17:47
Duplicate of https://github.com/brave/brave-browser/issues/38697 which was already fixed via `1.68.x` where `Nill/Null` would appear under the various columns intermittently.

**Closed by kjozwiak** 2024-07-31 17:47 UTC
Labels: bug, feature/shields/adblock, QA/Yes, release-notes/exclude, feature/shields/!scripts, OS/iOS
