### ISSUE TITLE
DNS forwarding not working in Brave browser

### ISSUE THREAD

**Issue by xameeramir** [brave/brave-browser#8903] opened 2020-03-28 15:38 UTC
## Description 
Have you searched for similar issues?
[Yes, found none](https://github.com/brave/brave-browser/issues?q=dns+forwarding+)

I have found that some domains behave differently in Chrome and Brave browsers:

| Browser | Request | Result | Expected |
| --- | --- | --- | --- |
| Chrome | http://therespect.org/ | Redirects to https://therespect.org/ | Yes |
| Brave | https://therespect.org/ | Redirects to http://hellonetaji.therespect.org/ | No |

This looks strange!

## Steps to Reproduce

   1. Hit http://therespect.org/ in Chrome and see the result
   2. Hit http://therespect.org/ in Brave and see the result

## Expected result:

http://therespect.org/ should redirect to https://therespect.org/

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1909 (Build 18363.720)
JavaScript | V8 8.0.426.27
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,WebXrGamepadModule,WebXR,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,VideoPlaybackQuality --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\hp\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | 5e3a236d-4113a79e

## Version/Channel Information:
Brave is up to date

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:

Google Chrome | 80.0.3987.149 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1909 (Build 18363.720)
JavaScript | V8 8.0.426.27
Flash | 32.0.0.344 C:\Users\hp\AppData\Local\Google\Chrome\User Data\PepperFlash\32.0.0.344\pepflashplayer.dll
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Command Line | "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox
Executable Path | C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

**Comment by rebron** [comment] 2020-05-08 16:43
@xameeramir We couldn't reproduce this. Looks like `http://therespect.org/` is redirecting properly in Brave on Windows 10 and on macOS as well. 
 
Can you try with the latest version of Brave, 1.8.95? Closing. Please reopen if this still an issue.

**Closed by rebron** 2020-05-08 16:43 UTC
