### ISSUE TITLE
Amazon music shows outdated Chrome message even with shields down

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3308] opened 2019-02-11 15:21 UTC
## Description 

Amazon music shows outdated Chrome message even with shields down

## Steps to Reproduce

   1. Visit https://music.amazon.co.uk/ in Brave (any channel)
   2. Disable/Enable shields, shows Chrome outdated error
   3. Open dev tools, console logs error even when shields is disabled

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/52572574-1b288080-2e3e-11e9-99fd-7881b0c5c254.png)
on Chrome 
![image](https://user-images.githubusercontent.com/17010094/52572615-35faf500-2e3e-11e9-9517-e1c6b869b42e.png)

## Expected result:
Same behaviour as Chrome

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Happens on all release/beta/dev channel builds

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Issue reported on community
https://community.brave.com/t/not-working-on-amazon-music-website-brave-v-0-59-34-chromium-72-0-3626-81/44666/1

**Comment by mrzealot** [comment] 2019-02-11 22:31
As per Slack, this is related to the Widevine component that the site detects as missing. Probably not much we can do, apart from making our native warning more obvious, as discussed in https://github.com/brave/brave-browser/issues/1940.

**Comment by bbondy** [comment] 2019-03-05 15:32
We already landed the new UX for making Widevine more obvious, so I'm closing this.

**Comment by jonathansampson** [comment] 2019-07-24 12:47
Looks like this is [still an issue](https://twitter.com/nomaspatanes/status/1153947651471052800), and unlikely related to Widevine.

![image](https://user-images.githubusercontent.com/815158/61794629-f32f4700-adf7-11e9-8a19-2ab7d94edcb2.png)

Doesn't appear to work with shields down.

**Comment by kjozwiak** [comment] 2019-07-24 16:21
Reproduced the issue on `macOS 10.14.5 x64` using the following build:

Brave | 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Mac OS X

When you initially visit https://music.amazon.com, you receive the Widevine modal as expected:

<img width="747" alt="Screen Shot 2019-07-24 at 12 16 23 PM" src="https://user-images.githubusercontent.com/2602313/61810440-41027a00-ae0d-11e9-86fb-f18fe9f76081.png">

However, once you start attempting to play some music, you'll receive the following as @srirambv & @jonathansampson pointed out above:

<img width="903" alt="Screen Shot 2019-07-24 at 12 16 48 PM" src="https://user-images.githubusercontent.com/2602313/61810472-55df0d80-ae0d-11e9-97f4-bd0c5741b03c.png">

**Comment by kjozwiak** [comment] 2019-07-24 16:37
Looks like this has been fixed on `dev` & `nightly`:

* 0.70.3 Chromium: 76.0.3809.62 (Official Build) nightly - Couldn't reproduce (Working)
* 0.69.91 Chromium: 76.0.3809.62 (Official Build) dev - Couldn't reproduce (Working)
* 0.67.115 Chromium: 76.0.3809.62 (Official Build) beta - Issue reproduced (doesn't work)

@btlechowski @GeetaSarvadnya  mind checking to see if you're getting the same results on Windows & Linux?

**Comment by GeetaSarvadnya** [comment] 2019-07-25 19:31
@kjozwiak Issue is Reproducible on Windows 10 x64 - `0.67.117`

After playing any music, I am receiving the below popup message.

![image](https://user-images.githubusercontent.com/38657976/61902843-ae62f780-af40-11e9-8bbc-972442de6d3f.png)

**Comment by kjozwiak** [comment] 2019-07-25 19:35
@GeetaSarvadnya does it work on `0.70.x` and `0.69.x` for you as well?

**Comment by GeetaSarvadnya** [comment] 2019-07-25 19:40
@kjozwiak Yup. It's working for me on Dev channel `0.68.106 Chromium: 76.0.3809.62 (Official Build) dev (64-bit)` and Nightly channel `0.70.3 Chromium: 76.0.3809.62 (Official Build) nightly (64-bit)`

**Comment by kjozwiak** [comment] 2019-08-21 05:07
As per the above, seems like this has been fixed and is working as expected. Assuming this has been fixed via https://github.com/brave/brave-browser/issues/4793.

**Closed by kjozwiak** 2019-08-21 05:07 UTC
Labels: bug, plugin/Widevine, webcompat

**Comment by kjozwiak** [comment] 2019-08-21 05:10
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

* Verified test cases outlined under https://github.com/brave/brave-browser/issues/3308#issue-408832446.

**Comment by rsc3** [comment] 2023-05-24 08:14
I'm getting a similar issue on Fedora38 in 2023. Accepted the wildvine install popup.

**Comment by rsc3** [comment] 2023-05-24 08:27
Ah now I see that wildvine didn't actually install. Same issue with Firefox :(
