### ISSUE TITLE
Flag to change shield protection level

### ISSUE THREAD

**Issue by epiccucumber15** [brave/brave-browser#21355] opened 2022-02-26 21:00 UTC
## Description 

Looking to change shield protection levels from the command line, but unable to find a switch/flag in https://github.com/brave/brave-core/blob/313944f3f9b321ef1b98541c58f627ceeb0a7aed/common/brave_switches.cc. Does such feature exist? I apologize if this is the wrong place to ask.

**Comment by rebron** [comment] 2022-03-09 19:05
@epiccucumber15 We were curious. How would you be using these flags via command line for shields?

**Comment by epiccucumber15** [comment] 2022-04-19 11:39
I would pass a flag for puppeteer to use.

**Comment by ShivanKaul** [comment] 2024-01-03 23:49
Dupe of https://github.com/brave/brave-browser/issues/3076

**Closed by ShivanKaul** 2024-01-03 23:49 UTC
Labels: feature/shields, priority/P5, feature-request, OS/Desktop
