### ISSUE TITLE
Address bar changes to `about:blank` upon loading the start page after starting Brave

### ISSUE THREAD

**Issue by onchov** [brave/brave-browser#38000] opened 2024-05-01 20:53 UTC
## Description 
After starting Brave and loading the start page, the URL in the address bar changes from the actual start page's URL to `about:blank`.

## Steps to Reproduce

   1. Go to Settings > On start-up, choose Open a specific page or set of pages and enter your start page's URL.
   2. (Not sure if it matters, but in Settings > New tab page > New tab page shows I have 'Blank page', and in Settings > Toolbar > Show Home button I have the same URL indicated).
   3. Close Brave.
   4. Open Brave.

## Actual result:

Brave starts and opens the start page, but the URL in the address bar immediately changes to `about:blank`.

## Expected result:
The actual start page URL should be shown rather than `about:blank`.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

I have observed the issue in two latest versions on both Windows and Linux:
```
Brave	1.65.126 Chromium: 124.0.6367.118 (Official Build) (64-bit) 
Revision	e6a0dcfed2e939addb42f91900875679412fa5b7
OS	Linux

Brave	1.65.126 Chromium: 124.0.6367.118 (Official Build) (64-bit) 
Revision	e6a0dcfed2e939addb42f91900875679412fa5b7
OS	Linux

Brave	1.65.123 Chromium: 124.0.6367.91 (Official Build) (64-bit) 
Revision	dd88871b12997b018e3acb2f589713a3ea10338b
OS	Windows 10 Version 21H2 (Build 19044.3086)

Brave	1.65.126 Chromium: 124.0.6367.118 (Official Build) (64-bit) 
Revision	e6a0dcfed2e939addb42f91900875679412fa5b7
OS	Windows 10 Version 21H2 (Build 19044.3086)
```

**Comment by rebron** [comment] 2024-05-01 21:34
@onchov what url are you using for your start page? Can you try a different one and see if still loads quickly and goes back to about:blank

**Comment by onchov** [comment] 2024-05-01 22:44
I did check that before logging the issue -- yes, it was going to `about:blank` with a different start page, too.

**Comment by onchov** [comment] 2024-05-02 17:59
OK, I found the culprit, it's this extension: https://chromewebstore.google.com/detail/ui-changer-for-reddit/bfcldjodnnkndfccfjndmdlppfkmccgh -- after turning it off, Brave works as expected. I'm leaving the issue open in case you want to investigate further for some reason, but you're more than welcome to close on my behalf. Sorry for the noise and thank you for maintaining the awesome browser that Brave is!

**Comment by hairycactus** [comment] 2024-05-22 22:31
I've been experiencing the same problem continuously ever since a certain Feb/Mar 2024 stable release (don't recall which version) -- except :
- Brave Android x64 (stable release, Google Play Store), Android v12, mobile phone
- No browser extensions installed
- A number of in-built adblocker rules added
- Preset Homepage URL: Can be any URL
- No other web browser installed on same device

#### Strange Behaviour Upon Cold Startup:
1. Brave Android flashes preset homepage URL very briefly (split second) on URL bar.
2. Brave then switches to display `about:blank` on URL bar.
3. Above takes place while web window itself remains blank (ie. nothing loaded).
4. URL bar then either:
   - continues to display `about:blank` indefinitely (unless I tap `Home` button several times);
   - OR: more rarely, after several seconds, automatically switches from `about:blank` back to preset Homepage URL
5. Brave then takes quite a long time (80-120+ secs) to load preset Homepage URL (or any bookmarked URL, or any typed-in URL) -- even when these are "lite" webpages that otherwise fully load in <1 sec during normal web browsing.

Not sure if related to the below issues, which I also start experiencing at the same time (in the *same* stable release version) as the Homepage URL vs `about:blank` in URL bar problem during Brave startup.

- #37411
- #36031

#### Current Personal Workaround (to cut waiting time by half):
1. Make sure that device is not connected to internet.
2. Start Brave Android (with preset Homepage URL configured).
3. Brave will switch to displaying `about:blank` in URL bar, regardless of preset Homepage URL.
4. Keeping tapping `Home' button, until Homepage URL appears in URL bar.
5. Tap `+` icon at bottom to "minimize" window. Don't open any other window/ tab.
6. Wait 30-40 seconds, then connect to internet.
7. Maximize Brave window.
8. Brave instantly loads webpage for Homepage URL (or any other intervening URL entered whilst waiting during Step 6).

**Comment by hairycactus** [comment] 2024-05-24 22:00
User PASSIVE_SCROLLER420 at below official Brave Reddit discussion thread (18 May 2024) seems to be facing the same slowness problem upon launching Brave (with no extensions installed):
https://old.reddit.com/r/brave_browser/comments/1cuyj3s/i_am_facing_the_same_issue_as_written_in_the

**Comment by rebron** [comment] 2024-07-10 18:07
Closing per author's last comments https://github.com/brave/brave-browser/issues/38000#issuecomment-2091179450 since the issue was caused by an extension.

**Closed by rebron** 2024-07-10 18:07 UTC
Labels: feature/new-tab, needs-more-info, feature/settings, OS/Desktop
