### ISSUE TITLE
Brave Crashes Clicking X on Private Tab (Control+W Ok)

### ISSUE THREAD

**Issue by andrewteg** [brave/brave-browser#40132] opened 2024-07-30 23:06 UTC
### Description

**Note:**
I posted at https://community.brave.com/t/brave-crashes-clicking-x-on-private-tab-control-w-ok/559791 but it seems to have gotten lumped in with #40005 so I'm opening one here.  Sorry if that's not the right protocol but it's a different issue.

**Issue:**
When closing a Private Tab with the mouse and clicking the “X” on the last tab, Brave will crash and close the non-private tabs as well. Additional testing shows it is only crashing when clicking the Private Tab’s X button, and other keyboard shortcuts like Alt+F4 and clicking the application windows X (next to min/max buttons on the right) all work fine.

### Steps to reproduce

1. Open Brave.
2. Control+Shift+N for a Private Tab
3. Click the “X” at the end of the “New Private Tab”

### Actual result

Brave crashes and kills the Private Tab and the profile that is open.

### Expected result

The Private Tab closes and the profile remains open as it does with Control+W or clicking the Windows X next to min/max buttons.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Current: 1.68.131 Chromium: 127.0.6533.73 (Official Build) (64-bit) 
First Noticed: 1.68.128 Chromium: 127.0.6533.73 (Official Build) (64-bit)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

I do have the Profile Manager set to start at launch and have not tried it without that.

**Comment by tobinfekkes** [comment] 2024-07-31 00:16
I am experiencing a similar issue, but slightly different. If I have a more than one Brave window open, and one of the windows has only one tab (private or regular), then click the X to close, Brave as a whole crashes. For example, I have 1 regular window open with 15 pinned tabs that I work out of, then I have another window with 1 tab open to YouTube on a second monitor, or one tab open to a private window temporarily logged into a Gmail account for a client. If I close the 1-tab window, my 15 pin-tabbed window dies as well. 

When I open Brave again, I get the "Brave crashed, would you like to send us the crash dump?" notice, then the prompt to restore all my windows. Then all my pinned tabs open back up. But this only occurs when I close the last tab in window. If I have two tabs in a second window, closing the second tab doesn't cause any harm. But when I close the last tab, the whole Brave instance dies, private or not.


Version 1.68.131 Chromium: 127.0.6533.73  (64-bit)

**Comment by jjspace** [comment] 2024-08-13 17:47
Cross linking because I came looking for a fix to the same issue and found multiple. Pretty sure this is a Duplicate of #39986

**Comment by tobinfekkes** [comment] 2024-08-16 04:32
My machine just updated to Version 1.68.141 Chromium: 127.0.6533.120 (Official Build) (64-bit) and can confirm this issue persists.

**Comment by andrewteg** [comment] 2024-08-22 19:14
I just updated to latest and it seems to be fixed.  Anyone else following this having issues?

[Version 1.69.153 Chromium: 128.0.6613.85 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by tobinfekkes** [comment] 2024-08-22 20:20
@andrewteg Thank you for the update! 

Yes, I can also confirm it is fixed on my end, with the same version.

**Comment by bsclifton** [comment] 2024-08-22 21:11
Thanks for raising this folks - I definitely had missed this 😓 (may have been the one who lumped into https://github.com/brave/brave-browser/issues/40005)

And thanks for confirming the issue is fixed 😄 I'll go ahead and close - but we can definitely check this out if anyone else is still experiencing the issue.

**Closed by bsclifton** 2024-08-22 21:11 UTC
Labels: crash, priority/P2, OS/Desktop

**Comment by revanmj** [comment] 2024-09-26 06:19
I'm still getting those crashes with v1.70.119

**Comment by andrewteg** [comment] 2024-09-26 14:17
> I'm still getting those crashes with v1.70.119 on Windows. Every single time I close private window with X, entire browser crashes.

I'm on Windows 11 and on brave://settings/help I also get [Version 1.70.119 Chromium: 129.0.6668.70 (Official Build) (64-bit)](https://brave.com/latest/) and I'm not having this issue this morning and have not since reporting it fixed above.  I'm guessing @bsclifton will want to know if you're using any extensions or have tried it with extensions disabled, too.
