### ISSUE TITLE
Unable to login to bank website

### ISSUE THREAD

**Issue by snowbound** [brave/brave-browser#24347] opened 2022-07-31 03:03 UTC
PLEASE USE THE TEMPLATE BELOW TO PROVIDE INFORMATION ABOUT THE ISSUE. 
INSUFFICIENT INFO WILL GET THE ISSUE CLOSED. IT WILL ONLY BE REOPENED AFTER SUFFICIENT INFO IS PROVIDED-->

## Description 
Unable to login to bank website

## Steps to Reproduce

   1. Use Brave [Version 1.43.51 Chromium: 104.0.5112.57 (Official Build) beta (64-bit)](https://brave.com/latest/)
   2. Go to https://online.acu.ca/
   3. Enter anything in USERNAME and press enter

## Actual result:
One gets this page
![image](https://user-images.githubusercontent.com/596147/182007942-e4d746a8-99b1-4a00-977c-cd7396d34135.png)

## Expected result:
You should get a page saying asking for your password

## Reproduces how often: 
Happens every time in the Beta. Fine in the release version of Brave

## Brave version (info found on brave://version)
[Version 1.43.51 Chromium: 104.0.5112.57 (Official Build) beta (64-bit)](https://brave.com/latest/)

## Version/Channel Information:
Brave

- Can you reproduce this issue with the current release? NO
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the dev channel? no idea
- Can you reproduce this issue with the nightly channel? no idea

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
I have disabled all extensions. I have created a new profile. Nothing makes a difference the same result occurs.

**Comment by ryanbr** [comment] 2022-07-31 06:32
Not using vpn?  I don't have a login, but I get this error: @snowbound   Does private window mode help?
![assin](https://user-images.githubusercontent.com/1659004/182013326-4e85b9ef-5599-45be-b4ea-af5cb8e5ad85.png)

**Comment by snowbound** [comment] 2022-07-31 14:25
That is what I should be seeing in the Beta of Brave but I am not. 

I am not using VPN, Private mode does work but I am lost at why I no longer see that page any longer in Brave Beta. I have no such issue with Brave release version. I am stymied what is causing this issue as Brave shields are off.

**Comment by snowbound** [comment] 2022-08-01 16:48
I am at my wits end with Brave browser. This issue is occurring in Brave Beta even in new profiles. It does not occur in Private mode. It still occurs with all extnesions disabled. It does NOT it occur in Brave Release. 

It does not occur in other browsers like Chrome or Edge. 

Uninstalling Brave Beta and ensuring User Data folder is removed and then installing Brave Beta from a newly downloaded exe causes this issue to occur. I still see the HTML code showing up rather than the prompt for the password. This is WITHOUT any extensions or changes to the settings in the new install.

I am also having an issue in Brave release version with https://www.canadiantire.ca/en.html if the shields are down in the release version. When Brave shields are down the site friequently stops responding in the release version of Brave. If I enable the shields the site loading and navigation is fine.

None of the other Chromium based browsers have issues with either of these sites.

**Comment by bsclifton** [comment] 2022-08-01 20:16
@snowbound I might be experiencing the same issue (but on a different site)

Can you please try this?
1. Go to brave://settings/wallet
2. Set `Default wallet` (might be one for Solana and one for Ethereum) to `None`
3. Force reload the page you are unable to login to (or quit/relaunch browser)

This fixed it for me for the site I was experiencing an issue (see https://github.com/brave/brave-browser/issues/24289)

Please let us know!

**Comment by snowbound** [comment] 2022-08-01 23:50
@bsclifton Holy crap that fixed this issue w the Credit Union. This site was working fine earlier last week then wham.  Thanks again. I wa wracking my brain here even a clean install did not fix this issue for the Credit Union

**Comment by bsclifton** [comment] 2022-08-02 01:10
@snowbound awesome, thanks for confirming! 😄 I'll share with the team

**Comment by snowbound** [comment] 2022-08-02 01:26
@bsclifton FYI on the clean install both of the wallets had been set to something other than NONE. When I restored my backup of my original Brave Beta it was the 2nd wallet that had to be set to NONE and which no doubt was causing this issue starting late last week. Personally these items should be set to NONE by default. If someone wants to use a wallet then they will ensure its set to the proper value.

**Comment by bsclifton** [comment] 2022-08-02 05:28
Closing as duplicate of https://github.com/brave/brave-browser/issues/24289 - will update that issue to include this as an example

**Closed by bsclifton** 2022-08-02 05:28 UTC
Labels: webcompat, OS/Desktop
