### ISSUE TITLE
Implement option to faster ad delivery for testing 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6436] opened 2019-10-11 16:16 UTC
## Description 

Testing ads on Android is quite tedious and time-consuming. QA time would be considerably reduced if we have an option to have faster ad delivery on Android(just on staging would also work). Note using a debug build isn't the same as installing an apk and testing. This had been requested during the first release but due to constraints wasn't done. We should consider adding this option on Android-core release

## Steps to Reproduce

   1. Start testing ads on Android
   2. Sign up for anger-management 

## Miscellaneous Information:

cc: @bbondy @anthonypkeane @kjozwiak @brave/android @jsecretan @tmancey

**Comment by tmancey** [comment] 2019-10-11 16:19
Agreed and we could add as a command-line arg which is triggered from android debug menu as this would help with desktop testing too

**Comment by tmancey** [comment] 2020-05-03 05:36
@srirambv I am closing this issue as it is a duplicate of https://github.com/brave/brave-browser/issues/9147 and will be implemented at the same time

**Closed by tmancey** 2020-05-03 05:36 UTC
Labels: OS/Android, feature-request, feature/ads
