### ISSUE TITLE
add custom adblock lists

### ISSUE THREAD

**Issue by tortino** [brave/brave-browser#12158] opened 2020-10-15 15:50 UTC
## Description 

I'd like to be able to add custom adblock lists to the browser: I'm thinking at some lists that I can find in ublock and other sites, like those blocking variuos type of annoyances, anti facebook, social, anti mining, etc. 
I should be able to just enter any url to add new lists. The new lists will be automatically updated regurarly.
Thanks.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by pes10k** [comment] 2020-10-19 16:59
Thank you for the issue @tortino !  Closing bc its a dupe of https://github.com/brave/brave-browser/issues/8107, but know that we hope to have something to share here soon

**Closed by pes10k** 2020-10-19 16:59 UTC
Labels: OS/Android, OS/Desktop

**Comment by tortino** [comment] 2020-10-19 17:14
ok I hope to see new soon!
thank you.
