### ISSUE TITLE
NTP images are stretched out but shows full image when dev tools are opened

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3380] opened 2019-02-15 10:57 UTC
## Description 

NTP images are stretched out but shows full image when dev tools are opened

## Steps to Reproduce

   1. Open a new tab 
   2. Be amazed by the new tab image
   3. Open dev tools, be shocked that you were looking at stretched image and not the full image

## Actual result:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17010094/52852310-3943f880-313e-11e9-8108-36b4a0236694.gif)

## Expected result:
Image should not be stretched on NTP and instead show the complete image because they are awesome

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.60.29 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on dev also
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A
### Additional Information

Found while verifying #1034
cc: @brave/legacy_qa to verify on other platforms 
cc: @rossmoody @petemill

**Comment by btlechowski** [comment] 2019-02-15 14:57
Reproduced on 

Brave | 0.60.29 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 7

![3380](https://user-images.githubusercontent.com/34715963/52864385-54ad0480-313a-11e9-8553-9091602b3de9.gif)

**Comment by petemill** [comment] 2019-02-15 17:49
Can we remove references to dev tools from this issue? I’m assuming the same experience is had when the window is made thinner, right? And if so the report is really that the images aren’t being bundled high enough for the larger window sizes? If that is the real issue here, there is a trade off between installer size and image quality where the line has to be drawn somewhere. (Number of images vs file size of images vs upper limit for installer size).

**Comment by rossmoody** [comment] 2019-02-15 18:38
Gonna close this one after the clarification in slack design channel this morning. This is working as intended and background images are proportionally cropping (not stretching) based on viewport size.

**Closed by rossmoody** 2019-02-15 18:38 UTC
Labels: QA/Yes, design, feature/new-tab, release-notes/exclude
