### ISSUE TITLE
Browser crash when attempting to tweet after tipping

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#5516] opened 2019-08-02 13:33 UTC
After tipping, clicking on `Tweet` may crash the browser 

## Steps to Reproduce

1. Clean install
2. Enable Rewards
3. Claim grant or fund wallet another way
4. Open publisher page (`https://www.reddit.com/user/jsadler-brave`)
5. Use inline tipping
6. Click tip amount
7. Quickly click another tip amount (repeat few times)
8. Immediately click `SEND MY TIP`
9. Immediately click `Tweet`

Note: This is an Intermittent issue, if browser does not crash, start from step 5.

## Actual result:

Browser Crash. Needs to run the browser again.

Windows 7 Uploaded Crash Report ID 7c1b0025c7afe8b9 (Local Context: fe8dec3f-846c-494d-8c7f-6305e621f7a0) 
Ubuntu 18.04 LTS Crash Report ID d165028fa3f61bfa

## Expected result:
No crash

## Reproduces how often: 

Intermittent issue, around 20% repro rate

## Brave version (brave://version info)

Brave | 0.68.114 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Ubuntu 18.04 LTS

Brave | 0.68.114 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

Reproduced on staging and production. Also reproduced by tipping youtube publisher.

cc @NejcZdovc @brave/legacy_qa

**Comment by btlechowski** [comment] 2019-08-08 23:07
Still reproducible

Brave | 0.68.120 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Ubuntu 18.04 LTS

Uploaded Crash Report ID fa3223c63ab8d96c (Local Context: Brave)
Crash report uploaded on Friday, August 9, 2019 at 1:05:16 AM

**Comment by masparrow** [comment] 2019-09-25 13:40
@NejcZdovc is it possible to get access to the crash reports cited above?

**Comment by masparrow** [comment] 2019-09-25 13:44
@btlechowski hi - a quick question - when it works (doesn't crash) what does the 'Tweet' button do for you? For me, nothing happens after clicking other than it dismisses the banner.

**Comment by btlechowski** [comment] 2019-09-30 11:27
@masparrow re grant, your don't really need the grant, you just need funds to tip

I reproduced the issue with `Tweet` button. This is not as it used to be before. Maybe it is related to the crash.
You should see something like that:
![image](https://user-images.githubusercontent.com/34715963/65874152-6075d000-e385-11e9-9776-adbe30a54f6c.png)

Does not reproduce on Tweeter(inline tipping), youtube and regular page.

**Comment by NejcZdovc** [comment] 2019-10-01 16:23
@btlechowski can you please send crash id or terminal logs

**Comment by btlechowski** [comment] 2019-10-01 16:48
The crash ids are in the description.

I will repaste them for convenience:
Windows 7 Uploaded Crash Report ID 7c1b0025c7afe8b9 (Local Context: fe8dec3f-846c-494d-8c7f-6305e621f7a0)
Ubuntu 18.04 LTS Crash Report ID d165028fa3f61bfa
Uploaded Crash Report ID fa3223c63ab8d96c (Local Context: Brave)

**Comment by NejcZdovc** [comment] 2019-10-01 16:53
@btlechowski thank you, I missed it.

**Comment by masparrow** [comment] 2019-10-03 14:51
@btlechowski @LaurenWags with the fix from PR [3592](https://github.com/brave/brave-core/pull/3592) (which resolves #6223) I have been unable to reproduce the crash from this issue. I've burned through 60 BAT (and I'm a cheap tipper ;) )and every time the Tweet page loads as expected. I'd recommend retesting this issue once #6223 is resolved (slated for 0.72 nightly ATM).

**Comment by LaurenWags** [comment] 2019-10-03 15:44
@masparrow if you would like, let us know once the fix for https://github.com/brave/brave-browser/issues/6223 has been merged to Nightly (looks like it's still open atm) and we can check this on Nightly for you.

**Comment by masparrow** [comment] 2019-10-03 19:02
@LaurenWags #6223 PR merged :) TIA!

**Comment by LaurenWags** [comment] 2019-10-07 14:42
@btlechowski I have not been able to reproduce with the following version. Can you please retest as well?


Brave | 0.72.72 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

**Comment by btlechowski** [comment] 2019-10-08 01:47
I am still able to reproduce the crash. I was testing on staging with grant.

Brave | 0.70.109 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Uploaded Crash Report ID 0e2953da93e8455a (Local Context: Brave)

I will try to get a recording tomorrow. Maybe it will help.

**Comment by masparrow** [comment] 2019-10-08 09:43
@btlechowski A recording would be great - just in case some subtle order of events or timing is key to reproducing.

**Comment by btlechowski** [comment] 2019-10-08 11:34
I managed to record it.

I also noticed that if crash does not reproduce, there is no need to stare from step 1. It is ok to start from step 5.

![5516](https://user-images.githubusercontent.com/34715963/66392467-3b5e0e80-e9d0-11e9-9be8-326e7199ef5c.gif)

**Comment by masparrow** [comment] 2019-10-09 08:14
That's great - thanks @btlechowski ! Was this capture from a single session? So "clean install, setup BAT, tip, tweet with no crash, tip again in the same session, tweet, crash"?

**Comment by btlechowski** [comment] 2019-10-09 11:57
I am not sure about that one, but I crashed when it was Not a single session.
1. claim grant
2. Tip few times https://www.reddit.com/user/jsadler-brave
3. Restart browser
4. Tip few times
Crash dump id: e6d1a30849676156

**Comment by masparrow** [comment] 2019-10-15 14:00
[brave-console-log.txt](https://github.com/brave/brave-browser/files/3729664/brave-console-log.txt)

Interesting behaviour in the last few lines; 

```
[6564:6564:1015/155205.029930:INFO:brave_tip_ui.cc(416)] [5516] OnTwitterShareURL : https://twitter.com/intent/tweet?text=I just tipped jsadler-brave using the Brave Browser. Check it out at https://brave.com/tips.%20%23TipWithBrave
[6594:6608:1015/155205.294032:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
/usr/bin/brave-browser-nightly: line 48:  6564 Segmentation fault      (core dumped) "$HERE/brave" "$@"
```

@NejcZdovc the URL format looks ok to me - although I'd expect %20's instead of the spaces? But, that ```"$HERE/brave" "$@"``` looks unusual... any ideas? Also, the connection reset looks might suspect as well...

**Comment by Brave-Matt** [comment] 2019-11-07 21:25
+1 https://www.reddit.com/r/brave_browser/comments/dskf2j/when_i_try_to_tweet_that_i_just_sent_a_tip_to_a/

**Comment by GeetaSarvadnya** [comment] 2019-11-14 20:36
The issue is reproducible windows 10 x64 - 1.1.1 beta version

Brave | 1.1.1 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

**Comment by GeetaSarvadnya** [comment] 2019-12-04 12:13
Reproduced once in Windows 10 x64 - 1.1.18  Chromium: 79.0.3945.56

**Comment by masparrow** [comment] 2019-12-06 12:23
> OnTwitterShareURL

Discussed with @NejcZdovc;

twitter.cc / GetShareURL - see chromium url_util.h

use https://cs.chromium.org/chromium/src/net/base/url_util.h?type=cs&q=QueryIterator&g=0&l=39

to build the URL for 'https://twitter.com/intent/tweet'

**Comment by Brave-Matt** [comment] 2020-10-02 17:42
Hello! I've got another report of this issue from a user on Community. I notice that this issue hasn't been addressed in some time but I'm wondering if we can get some eyes on it? Thread is here:
https://community.brave.com/t/after-tiping-a-creator-on-yt-the-browser-chrashes/160367/5 

☝️ User also submitted a video recording of the behavior if it would be necessary or useful to see.

**Comment by NejcZdovc** [comment] 2020-10-07 18:32
this was refactored with GL and we can't reproduce it so let's test it out

**Comment by kjozwiak** [comment] 2020-10-20 20:36
Verification **PASSED** on `macOS 10.15.7 x64` using the following build:

```
Brave | 1.17.43 Chromium: 86.0.4240.99 (Official Build) nightly (x86_64)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | macOS Version 10.15.7 (Build 19H2)
```

* Verified the STR/Cases outlined via https://github.com/brave/brave-browser/issues/5516#issue-476182283 and couldn't reproduce the issue (x40 times).
* Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/5516#issue-47618228 using:
  * https://twitter.com/bravelaurenwags (inline tipping)
  * https://github.com/laurenwags (inline tipping)

**Comment by kjozwiak** [comment] 2020-10-20 20:38
@btlechowski mind taking a look at this one as you're the one that could reproduce this pretty consistently. I went through your original STR/Cases via https://github.com/brave/brave-browser/issues/5516#issue-476182283 at least ~40 times and couldn't reproduce.

**Comment by btlechowski** [comment] 2020-10-20 22:47
Crashed on the first attempt.

Brave | 1.17.43 Chromium: 86.0.4240.99 (Official Build) nightly (64-bit)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/96652300-ea009300-1336-11eb-8cb8-6faf9e4195a3.png)

**Comment by kjozwiak** [comment] 2020-10-20 23:03
Thanks @btlechowski 👍 Wonder if this is related to Linux/Windows. Seems like @GeetaSarvadnya could reproduce via https://github.com/brave/brave-browser/issues/5516#issuecomment-554068322 & https://github.com/brave/brave-browser/issues/5516#issuecomment-561617964 but anyone with macOS hasn't had any luck.

@btlechowski mind crash ID? Lets check BackTrace and see if that crash has happened on macOS.

@LaurenWags mind giving it a go on your macOS and see if you can reproduce?

**Comment by btlechowski** [comment] 2020-10-21 11:14
@kjozwiak The crash report was not generated. Probably due to https://github.com/brave/brave-browser/issues/4296.

**Comment by LaurenWags** [comment] 2020-10-21 12:12
@kjozwiak could not reproduce issue, updated https://github.com/brave/brave-browser/issues/5516#issuecomment-713124858 with my notes. We should probably get a follow up issue logged for Win/Linux if this is still occurring there 👍

**Comment by btlechowski** [comment] 2020-10-21 15:29
After internal discussion it was decided to reopen this issue and mark it as `OS/Linux` and `OS/Windows`

**Comment by btlechowski** [comment] 2020-12-17 13:11
Still crashing


Brave | 1.18.74 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Ubuntu 18.04 LTS

**Comment by LaurenWags** [comment] 2020-12-17 14:25
I reproduced on Linux as well today

```
Brave	1.18.74 Chromium: 87.0.4280.101 (Official Build) (64-bit)
Revision	9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS	Linux
```

Moving to Rewards Global board for triage cc @marshall

**Comment by zenparsing** [comment] 2021-04-06 13:24
Possibly related: #15142

**Closed** 2021-04-06 16:38 UTC
Labels: OS/Desktop, OS/Linux, OS/Windows, QA/Test-Plan-Specified, QA/Yes, crash, feature/rewards, intermittent-issue, release-notes/include

**Comment by GeetaSarvadnya** [comment] 2021-04-16 09:43
Verification passed on

```

Brave | 1.24.65 Chromium: 90.0.4430.72 (Official Build) dev (64-bit)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | Windows 10 OS Version 2004 (Build 19041.867)

```
- Verified the STR from the description and ensured there is no crash when tweet after tipping
