### ISSUE TITLE
Add ability to edit profile in settings

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#5211] opened 2019-07-10 23:15 UTC
## Test plan
1. Visit chrome://settings/
1. Verify there is a section like `Profile name and icon` at the top
1. Click it; it should take you to edit profile screen

## Description 
Add the ability to edit profile in Settings. Create a brave://settings/editProfile page that allows users to edit their profile name and choose a Brave icon/avatar. 

In the Getting Started section of Settings, add the option labeled "Profile name and icon" as the access point to brave://settings/editProfile (Chrome's equivalent is chrome://settings/manageProfile)

## Design
[pending]

**Comment by kjozwiak** [comment] 2019-07-30 03:16
@rebron is this a dupe of https://github.com/brave/brave-browser/issues/4615?

**Closed** 2019-08-13 16:59 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/profile-manager, priority/P3

**Comment by kjozwiak** [comment] 2019-09-20 02:48
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | macOS Version 10.14.6 (Build 18G95)

* Verified the test case outlined under https://github.com/brave/brave-browser/issues/5211#issue-466569458
* ensured that clicking on `Profile name and icon` opens `brave://settings/manageProfile`
* ensured that changing the profile icon and name under `brave://settings/manageProfile` propagates via the `Manage People` window and `Profile Icon` via the navigation bar
* ensured that the profile icon doesn't appear under `PB` and `Tor` windows

<img width="1189" alt="Screen Shot 2019-09-19 at 10 30 25 PM" src="https://user-images.githubusercontent.com/2602313/65295427-4d663300-db2f-11e9-9fa5-d700f04e72bb.png">
<img width="930" alt="Screen Shot 2019-09-19 at 10 38 00 PM" src="https://user-images.githubusercontent.com/2602313/65295435-522ae700-db2f-11e9-929d-56b6b2b50a7d.png">
<img width="850" alt="Screen Shot 2019-09-19 at 10 38 10 PM" src="https://user-images.githubusercontent.com/2602313/65295441-56ef9b00-db2f-11e9-8efc-ddbbe8633951.png">
