### ISSUE TITLE
Verified Reddit pubs info isn't displayed in DB

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7190] opened 2019-12-03 13:55 UTC
## Description 

Verified Reddit pubs info isn't displayed in DB

## Steps to Reproduce

   1. Clean profile 1.3.50 - Launch brave with staging flag
   2. Enable rewards
   3. Send a one time tip to a verified Reddit pub https://www.reddit.com/user/alex_the_brave/
   4. Verified Reddit pubs info isn't displayed in DB

## Actual result:

Verified Reddit pubs info isn't displayed in DB
Nightly channel:
![image](https://user-images.githubusercontent.com/38657976/70056074-d81fdf80-1600-11ea-8d25-ebc748d9d1cd.png)

## Expected result:
Verified Reddit pubs info should be displayed in DB 
Release channel:
![image](https://user-images.githubusercontent.com/38657976/70055883-7495b200-1600-11ea-9530-d491393912fc.png)

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.3.50 Chromium: 79.0.3945.56 (Official Build) nightly (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by NejcZdovc** [comment] 2019-12-04 06:47
I can't reproduce this one on the latest master.

**Comment by GeetaSarvadnya** [comment] 2019-12-04 11:08
@NejcZdovc I can reproduce the issue in the latest night build version 1.4.1 Chromium: 79.0.3945.56 (Official Build) nightly (64-bit)

The issue could be specific to Windows. Please let me know if you need any other details.

**Comment by NejcZdovc** [comment] 2020-04-10 08:22
closing as can't reproduce on 1.9.x

**Closed by NejcZdovc** 2020-04-10 08:22 UTC
Labels: OS/Windows, QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards, needs-investigation, regression

**Comment by LaurenWags** [comment] 2020-04-10 12:33
@GeetaSarvadnya please double check this one as it was not reproducible for me on macOS.
