### ISSUE TITLE
`Search the web privately` text isn't translated in other locales 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#24296] opened 2022-07-27 16:44 UTC
## Description 

Found while testing https://github.com/brave/brave-browser/issues/24138
`Search the web privately` text isn't translated in other locales 

## Steps to Reproduce

   1. Set the OS locale to Germany/France/Hindi/Kannada
   2. Install brave `1.42.80`
   3. Open PT/TOR/Guest window
   4. `Search the web privately` text isn't translated in other locales 

## Actual result:

`Search the web privately` text isn't translated in other locales 

**Hindi**
![image](https://user-images.githubusercontent.com/38657976/181302040-c0a1bf81-c0bf-4b76-aa3f-2c4661f7f38b.png)

## Expected result:

`Search the web privately` text should be translated to other locales 

## Reproduces how often: 

100%

## Brave version (brave://version info)

क्रोमियम | 1.42.80 Chromium: 104.0.5112.57 (आधिकारिक बिल्ड) (64-बिट)
-- | --
पुनरीक्षण | 212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}
OS | Windows 10 Version 21H2 (Build 19044.1826)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin

**Comment by btlechowski** [comment] 2022-07-27 17:37
Duplicate of https://github.com/brave/brave-browser/issues/24267

**Closed by btlechowski** 2022-07-27 17:37 UTC
Labels: bug, closed/duplicate, QA/Yes, release-notes/exclude, QA/Test-Plan-Specified, OS/Desktop
