### ISSUE TITLE
[Desktop] Sync v2 - Apps are not automatically installed

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#11204] opened 2020-08-12 13:04 UTC
App is synced but the App is not installed

According to @darkdh this is an upstream bug

## Steps to Reproduce

1. Clean install on `DeviceA` and `DeviceB`
1. Establish sync chain between `DeviceA` and `DeviceB`
1. Enable Apps sync on `DeviceA` and `DeviceB`
1. `DeviceA`: Open interia.pl
1. `DeviceA`: Click `Install Interia` in the URL field ![image](https://user-images.githubusercontent.com/34715963/89920328-8d794d00-dbfc-11ea-8517-d82a1102acdc.png)
1. Wait for sync update
1. `DeviceB`: Open interia.pl

## Actual result:

`DeviceB`: App is synced
![image](https://user-images.githubusercontent.com/34715963/90018085-b6591b00-dcac-11ea-88b3-4c29b6bd9880.png)

`DeviceB` : App is not installed
![image](https://user-images.githubusercontent.com/34715963/90018248-ebfe0400-dcac-11ea-8d0d-0fdcff279e14.png)

## Expected result:
`DeviceB` : App is installed
![image](https://user-images.githubusercontent.com/34715963/90018315-02a45b00-dcad-11ea-8bae-93d5b52284d4.png)

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @darkdh @jsecretan @AlexeyBarabash @rebron

**Comment by jsecretan** [comment] 2020-08-27 15:47
@AlexeyBarabash could you also file an upstream bug for this and see what they say?

**Comment by AlexeyBarabash** [comment] 2020-08-27 15:50
@jsecretan yes, will do

**Comment by AlexeyBarabash** [comment] 2020-08-27 18:04
@btlechowski @jsecretan 
I could not reproduce it .
Got the app on device B.
![image](https://user-images.githubusercontent.com/24739341/91478586-ce35bf00-e8a8-11ea-8d71-bf0b49eb9c10.png)

**Comment by AlexeyBarabash** [comment] 2020-08-27 18:07
On device B just then Right Button click  on the icon INT and choose install - then all works.

**Comment by rebron** [comment] 2020-09-18 16:27
@darkdh Is this an upstream bug? 
@AlexeyBarabash I'm not sure what you mean here, @btlechowski is saying that it should be installed without having to do a right click on the icon to install. He's going to the url again and seeing a prompt to re-install the app and he shouldn't see that prompt at all.

**Comment by darkdh** [comment] 2020-09-18 16:31
We already had this conversation in slack
https://bravesoftware.slack.com/archives/C2HJYB45N/p1598556672031500

**Comment by AlexeyBarabash** [comment] 2020-09-29 13:13
Closing as we have https://github.com/brave/brave-browser/issues/11911 .

**Closed by AlexeyBarabash** 2020-09-29 13:13 UTC
Labels: OS/Desktop, QA/Test-Plan-Specified, QA/Yes, feature/sync, priority/P4
