### ISSUE TITLE
Brave letting youtube ads through

### ISSUE THREAD

**Issue by BartAgterbosch** [brave/brave-browser#15846] opened 2021-05-13 22:50 UTC
As of the latest release of brave on windows, version 1.24.85 64bit, it is no longer blocking youtube ads inbetween videos in playlists
This started right the very second after it had finished updating to the latest version

**Comment by ryanbr** [comment] 2021-05-13 23:14
Youtube has been certainly trialing ads, can you try adding to the `brave://adblock` and then refresh the youtube tab:

```
||youtube.com/watch?*=prefetch
||youtube.com/watch?v=*&pbj=
```

@BartAgterbosch

**Comment by kyoyacchi** [comment] 2021-05-14 10:53
You may use uBlock Origin extension for block ads (In my opinion.)

**Comment by ryanbr** [comment] 2021-05-15 03:07
> You may use uBlock Origin extension for block ads (In my opinion.)

They're using the same filters being implemented @kyoyacchi  The fixes I committed into Easylist will apply to Brave and uBO.

Also uBO is affected too: https://old.reddit.com/r/uBlockOrigin/comments/ncoosp/not_blocking_ads_on_youtube_anymore/

**Comment by Tonev** [comment] 2021-05-15 04:58
@ryanbr 

Your solution doesn't work in the following case: https://github.com/brave/brave-browser/issues/15830

I use Brave Shields at aggressive mode along with Fanboy Annoyances List and uBlock Annoyances List.

What worked for me was installing uBlock Origin in hard mode with default filter lists.

**Comment by ryanbr** [comment] 2021-05-15 11:30
```
||youtube.com/watch?*=prefetch
||youtube.com/watch?v=*&pbj=
```

Don't use these filters ^, they caused issues, we implented fixes in Easylist (Desktop only). https://github.com/brave/brave-browser/issues/15830 is different issue and will also affect uBO.

**Comment by Tonev** [comment] 2021-05-15 12:00
Regarding https://github.com/brave/brave-browser/issues/15830

I could easily reproduce the issue before installing uBlock Origin, and can't reproduce it at all ever since.

A few things worth mentioning (because I've seen you mention them on Reddit):

- I use only default uBlock Origin filters along with Fanboy Annoyances List and uBlock Annoyances List in Brave's adblock;
- I purge and update filters manually regularly, usually on every PC boot;
- I clear all browsing data on exit except the browsing data for "Site and Shields Settings";

**Comment by ryanbr** [comment] 2021-05-15 12:20
Move any comments  regarding https://github.com/brave/brave-browser/issues/15830  into that ticket, thanks.

**Comment by ryanbr** [comment] 2021-05-18 00:08
Rolled some test youtube filters into `Fanboy Annoyances` via `brave://adblock`, which should land in the next 24hrs.

**Comment by BartAgterbosch** [comment] 2021-05-20 10:04
Seems to work as it should now, for me at least, not sure if I should close it since seemingly it didn't work for everyone

**Closed** 2021-05-20 10:12 UTC
Labels: OS/Desktop
