### ISSUE TITLE
Add unit tests for Brave Ads service

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#4177] opened 2019-04-19 19:58 UTC
This is a follow up to the work that was done in: https://github.com/brave/brave-core/pull/1365

The initial unit test class has been set up, we just need test cases.

**Comment by tmancey** [comment] 2020-01-20 13:36
Closing as a duplicate of https://github.com/brave/brave-browser/issues/4317

**Closed by tmancey** 2020-01-20 13:36 UTC
Labels: dev-concern, feature/ads, tests
