### ISSUE TITLE
Confirm sync code does nothing

### ISSUE THREAD

**Issue by MRVDH** [brave/brave-browser#4756] opened 2019-06-07 18:29 UTC
## Description 
Confirm sync code does nothing.

## Steps to Reproduce
I have two laptops and one phone.

1. I set up a sync chain on laptop 1;
2. then added my phone with the sync code. This worked.
3. I then tried to add laptop 2 and this is the result.

## Actual result:
No console logs, no errors, nothing.
The code you see in this picture is different from my actual code for privacy reasons.
![gif](https://i.imgur.com/IxuSYfe.gif)

## Expected result:
Succesful sync

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)
9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
Windows 10 OS Version 1809 (Build 17763.475)

**Comment by bsclifton** [comment] 2019-06-24 05:28
@rebron is this a dupe? If so, do you have a link to that issue?

**Comment by GeetaSarvadnya** [comment] 2019-06-24 09:39
@bsclifton @rebron This issue is a dupe of https://github.com/brave/brave-browser/issues/3190

**Comment by bsclifton** [comment] 2019-06-24 16:11
Thanks, @GeetaSarvadnya 😄

**Closed** 2019-06-24 16:11 UTC
Labels: duplicate, feature/sync
