### ISSUE TITLE
Option to select which data to clear on exit on Android

### ISSUE THREAD

**Issue by ramonls8** [brave/brave-browser#34462] opened 2023-11-21 19:19 UTC
## Description 
Brave on Android has an option to clear data on exit, but it deletes all data without providing the option to choose which data to clear and which not to.
Similar to Brave for Windows, there should be an option to choose which data to delete, for example, history and cache, while retaining cookies and site settings.

## Steps to reproduce 

 1. On Android, open Brave and go to Settings.
 2. Go to Brave Shields & Privacy.
 3. Enable the Clear data on exit option.

## Actual result 
It does not allow you to choose which data to delete and which to keep. When the option is enabled, it always clears all data on exit.

## Expected result
There should be a menu where you can choose which data should be cleared on exit and which should not.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
Yes
- Can you reproduce this issue with the current Play Store Beta version?
Yes
- Can you reproduce this issue with the current Play Store Nightly version?
Yes

**Comment by srirambv** [comment] 2023-11-22 04:51
Dupe of #17209

**Closed by srirambv** 2023-11-22 04:51 UTC
Labels: OS/Android
