### ISSUE TITLE
Browser noticeably slower since last update

### ISSUE THREAD

**Issue by wooque** [brave/brave-browser#22118] opened 2022-04-06 10:19 UTC
## Description 
Browser is noticeably slower since last update (version 100.0.4896.60). Even simple sites take few seconds to fully load, like Hackernews

## Steps to reproduce 

   1. Open some simple site like https://news.ycombinator.com/item?id=30926834
   2. 
   3. 

## Actual result 
Site opens relatively quckly but it takes few seconds to render fully (upvoat arrows show up after few seconds)

## Expected result
Site opens and renders almost instantly

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes 
- Can you reproduce this issue with the current Play Store Beta version? /
- Can you reproduce this issue with the current Play Store Nightly version?  /

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone (Xiaomi Redmi Note 4)
   - Android version: 11
   
## Brave version

Brave | 1.37.110 Chromium: 100.0.4896.60 (Official Build) (64-bit)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | Android 11; Build/RQ3A.211001.001
Google Play services | SDK=12451000; Installed=220920037; Access=3p
JavaScript | V8 10.0.139.8
User Agent | Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Mobile Safari/537.36
Command Line | --use-mobile-user-agent --top-controls-show-threshold=0.5 --top-controls-hide-threshold=0.5 --use-mobile-user-agent --enable-viewport --validate-input-event-stream --enable-longpress-drag-selection --touch-selection-strategy=direction --disable-composited-antialiasing --enable-dom-distiller --disable-client-side-phishing-detection --disable-domain-reliability --no-pings --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --disable-features=NativeBraveWallet --flag-switches-end --disable-background-media-suspend --no-restore-state
Executable Path | No such file or directory
Profile Path | /data/user/0/com.brave.browser/app_chrome/Default
Variations | AdRewardsStudy:NextPaymentDayAdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=12/MaximumInlineContentAdsPerDay=60BraveAds.UserActivityStudy:Triggers=EMPTY/Threshold=0.0/IdleTimeThreshold=5BraveDebounceStudy:EnabledConversionsStudy:NewDefaultPatternDefault1pBlockingStudy:DisabledDisableCnameUncloakingForAndroid:DisabledEphemeralStorageStudy:EnabledExtendedVariationsSafeMode5:Default5FirstPartyEphemeralDomainBlockStudy:DefaultForceDisableBlinkFeatures:EnabledPartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledRequestAdsEnabledApiStudy:EnabledVulkanStudy:Disabled

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? Seems it's faster but still even with Shields disabled it's a tad slower than Bromite for example
- Does the issue resolve itself when disabling Brave Rewards? /
- Is the issue reproducible on the latest version of Chrome? /

**Comment by mavdl2117** [comment] 2022-04-06 10:26
Same here, but duplicate of #22030

**Closed** 2022-04-14 10:39 UTC
Labels: OS/Android
