### ISSUE TITLE
`I have sync code` button alignment issue is certain locales

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#14435] opened 2021-03-02 13:59 UTC
## Description 

`I have sync code` button alignment issue is certain locales.
Verified the issue in Germany and France locales

## Actual result:

**Germany**
![image](https://user-images.githubusercontent.com/38657976/109658565-c1ae5e00-7b8c-11eb-8fd8-ecf35363708a.png)

**France**
![image](https://user-images.githubusercontent.com/38657976/109659176-6cbf1780-7b8d-11eb-921f-eb41d456d586.png)

## Expected result:

![image](https://user-images.githubusercontent.com/38657976/109658619-d0951080-7b8c-11eb-88bb-483237120af0.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.21.71 Chromium: 89.0.4389.72 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
Betriebssystem | Windows 10 OS Version 2004 (Build 19041.804)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron

**Comment by LaurenWags** [comment] 2021-03-02 15:58
Reproduces for Spanish (Spain) as well:

<img width="1141" alt="Spanish-Spain" src="https://user-images.githubusercontent.com/28145373/109675921-37430b80-7b46-11eb-98d4-82fa2e20cd0c.png">

```
Brave | 1.21.71 Chromium: 89.0.4389.72 (Build oficial) (x86_64)
-- | --
Revisión | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
Sistema operativo | macOS Versión 10.15.7 (Compilación 19H512)
```

**Comment by btlechowski** [comment] 2021-03-02 19:03
Dupe of https://github.com/brave/brave-browser/issues/11069

**Closed by btlechowski** 2021-03-02 19:03 UTC
Labels: OS/Desktop, QA/Test-Plan-Specified, QA/Yes, bug, feature/user-interface
