### ISSUE TITLE
Brave crashes when select Sync option from Tor window

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7225] opened 2019-12-05 17:55 UTC
## Description 

Brave crashes when select Sync option from Tor window
## Steps to Reproduce

   1. Clean profile 1.1.18
   2. Open a Guest window
   3. Select New private window with tor option from guest window
   4. Select the `Sync` option from Tor window

## Actual result:

Brave crashes when select Sync option from Tor window

## Expected result:

No crash
## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.1.18 Chromium: 79.0.3945.56 (Official Build) (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the dev channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @bsclifton

**Comment by LaurenWags** [comment] 2019-12-05 18:09
@GeetaSarvadnya does this reproduce on current release 1.0.1?

**Comment by GeetaSarvadnya** [comment] 2019-12-05 18:16
@LaurenWags this is what is shown on 1.0.1 `Sync`, `Crypto wallet` and `Rewards` options aren't available.

![image](https://user-images.githubusercontent.com/38657976/70260697-d7c94500-17b6-11ea-8634-943811cc477b.png)

**Comment by LaurenWags** [comment] 2019-12-05 19:10
I can reproduce with your STR on macOS, but interestingly enough if I open a Tor window from a normal (not Guest) window, there is no crash. brave://sync page opens in the normal window as expected.


Brave | 1.1.18 Chromium: 79.0.3945.56 (Official Build) (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | macOS Version 10.13.6 (Build 17G5019)

**Comment by LaurenWags** [comment] 2019-12-05 19:18
Ok, a little more digging. Crash reproduces with 1.0.1 if you type brave://sync into menu bar instead of clicking from hamburger menu.

Steps:
Open 1.0.1
Open a Guest Window
Click on hamburger menu and choose New Private Window with Tor
In the Tor window, type brave://sync in URL bar.
--> Brave crashes
--> crash report IDs: `43536bea6aa71a9c` and `032a60f787ea56bf`

Similarly, this also produces a crash:
Open 1.0.1
Click on hamburger menu and choose New Private Window with Tor
In the Tor window, type brave://sync in URL bar.
--> Brave crashes
--> crash report IDs: `e8e73a65d7f5f7ab` and `577565f0c6903870`

**Comment by yrliou** [comment] 2019-12-06 00:38
To sum up, opening sync page in Tor window on 1.0.1 would crash no matter what; on 1.1.x, it would only crash if Tor window is created from a guest window.

We currently are not able to open private window from a guest window, which I think we should align with how private window is handled first.
It would make us more consistent between private and private with Tor cases and also remove the possibility of this crash path on 1.1.x.

**Comment by kjozwiak** [comment] 2019-12-09 15:35
As per our discussion with @bsclifton & @rebron, moving this out from `1.1.x` as we should get this fixed for `1.2.x`. It's going to be too late to include this in the `1.1.x` release for tomorrow. It also looks like a large change that will need more QA/bake time rather than a quick check.

@yrliou also mentioned this was already happening in `1.0.x` when opening a sync page in a Tor window.

**Closed** 2019-12-09 21:41 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, crash

**Comment by LaurenWags** [comment] 2019-12-16 20:07
Verified passed with

Brave | 1.2.27 Chromium: 79.0.3945.79 (Official Build) beta (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-core/pull/4155
<img width="383" alt="Screen Shot 2019-12-16 at 3 02 57 PM" src="https://user-images.githubusercontent.com/28145373/70939111-9423d600-2015-11ea-9b26-51103a9870dd.png">
<img width="1226" alt="Screen Shot 2019-12-16 at 3 03 36 PM" src="https://user-images.githubusercontent.com/28145373/70939117-95ed9980-2015-11ea-9b35-7c04e41ee1f0.png">
<img width="1195" alt="Screen Shot 2019-12-16 at 3 04 28 PM" src="https://user-images.githubusercontent.com/28145373/70939120-971ec680-2015-11ea-8271-3526dbb684ce.png">

* Verified originally reported STR from description could not be executed per the changes made by the PR
* Verified that opening a Tor window from normal profile and visiting Sync from the hamburger menu opened brave://sync in a normal tab as expected. No crash was observed.
