### ISSUE TITLE
Brave Wallet custom base currency setting not being applied.

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [brave/brave-browser#19639] opened 2021-11-21 20:45 UTC
## Description 
Brave Wallet will always use USD as the base currency regardless of what it is set to in `brave://settings/wallet`

## Steps to Reproduce

   1. Go to `brave://settings/wallet`
   2. Set "Default base currency" to anything else than USD
![2021-11-21-214311-brave](https://user-images.githubusercontent.com/22710992/142778293-5d634deb-351a-440a-83f5-afdf3e6fcb15.png)
   3. Check `brave://wallet/crypto/portfolio
![2021-11-21-214356-brave](https://user-images.githubusercontent.com/22710992/142778295-96ec2bc8-d15a-4fac-8c9d-c8a6c6be6663.png)
  4. Relaunch Brave, notice it is still using USD.

## Actual result:
Brave Wallet uses USD even when a different currency is set.
## Expected result:
Brave Wallet should use the custom base currency set.

## Reproduces how often: 
Always

## Brave version (brave://version info)
<html>
<body>

Brave | 1.34.25 Chromium: 96.0.4664.45 (Official Build) nightly (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 2004 (Build 19041.1348)

</body>
</html>

## Version/Channel Information:
- Can you reproduce this issue with the current release? Unknown
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No 
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by srirambv** [comment] 2021-11-24 17:12
Should be ready when #19234  is done. Closing as dupe of #19234

**Closed by srirambv** 2021-11-24 17:12 UTC
Labels: feature/wallet, OS/Desktop
