### ISSUE TITLE
Lighthouse ads injection during report

### ISSUE THREAD

**Issue by StephD** [brave/brave-browser#17065] opened 2021-07-21 09:20 UTC
## Description 

I wanted to try lighthouse to test the speed of my website. I use brave as it's a chromium base browser and lighthouse is integrated.
What a surprise when I discover that my website told me that there is unused CSS such as 
- a[href^="http://www.afgr2.com/"] { display: none !important; }
- a[href^="https://trackjs.com/?utm_source"] { display: none !important; }
- a[href^="http://go.fpmarkets.com/"] { display: none !important; }
- div[id^="ads300_250-widget"] { display: none !important; }
- .... and so on another one every time lighthouse is running

May be it's a problem into my website. But it actually does it also on other shopify store.
I can only reproduce this on brave with inspect code. 
Edge is fine, Firefox is fine, lighthouse website is fine. I also downloaded especially google chrome to try and it's also fine.

## Steps to Reproduce

   1. Go to natoaka.com  (https://www.aurathelabel.com/ got the same result
   2. Inspect the code
   3. Run a lighthouse report

## Actual result:

---
![image](https://user-images.githubusercontent.com/1171858/126463931-7a136d02-e4d5-4825-8716-23a0266fbbf2.png)
---
![image](https://user-images.githubusercontent.com/1171858/126463993-1bd7edff-a820-4667-ba8b-dcaee4a8b2a7.png)
---
![image](https://user-images.githubusercontent.com/1171858/126464076-22e2481b-5319-45e7-ba97-7e72a0c79596.png)

## Expected result:
![image](https://user-images.githubusercontent.com/1171858/126464114-8508bc8e-2ab4-4f7e-96fd-9aeb02677c71.png)

## Reproduces how often: 
All the time

## Brave version (brave://version info)
Brave | 1.26.77 Chromium: 91.0.4472.164 (Official Build) (64-bit)
Revision | 541163496c9982c98f61819bab7cf2183ea8180f-refs/branch-heads/4472@{#1569}
OS | Windows 10 OS Version 2009 (Build 19043.1110)
JavaScript | V8 9.1.269.39

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
YES. Just realize that it's doesn't appear when shields is disabled

- Is the issue reproducible on the latest version of Chrome? 
No

I really hope to be wrong and brave isn't responsible of that but it's weird.
I will probably uninstall brave because that kind of thing is really disturbing for a browser that claim security, privacy, control

**Comment by ryanbr** [comment] 2021-07-21 10:14
Hey @StephD These are just generic css cosmetics, no privacy issues here.  All sourced from Easylist https://github.com/easylist/easylist/blob/master/easylist/easylist_general_hide.txt

The CSS cosmetics are used to remove empty spaces from sites using these elements.

**Comment by StephD** [comment] 2021-07-22 03:46
Mmm :-) I don't really understood why I would see that kind of cosmetic into the CSS or the point to see this ads to remove empty space (Or may be the shield replace these ads by empty space for security?)

You look aware that there is nothing to worry about :-) so it's ok
But why do I only have this with shield active on brave only?

**Comment by ryanbr** [comment] 2021-08-17 00:38
Sorry missed the response, We include ads/trackers by default. Helps block trackers, ads. and the css elements will cleanup (collapse) and blank spaces left over. Similar to what other adblock software does here. @StephD

**Comment by ryanbr** [comment] 2021-08-17 01:11
Closing report, as this is working as intended. Disabling "Ads and trackers" if people not wanting cosmetics to be injected. Another option for `@@||domain.com^$ghide`  in `brave://adblock` should also avoid this.

**Closed by ryanbr** 2021-08-17 01:11 UTC
Labels: OS/Desktop
