### ISSUE TITLE
Crash/hang resulted in a system-wide malfunction

### ISSUE THREAD

**Issue by liyun-li** [brave/brave-browser#2596] opened 2018-12-17 08:06 UTC
## Description 
The browser on Linux randomly crashes and consumes all of my system resources which basically DoS'd my machine. I should mention that I was running it on a Ubuntu 18 in VMWare. Maybe it's also worth mentioning that I was operating on the VM in fullscreen mode.

## Steps to Reproduce

   1. Work with Google Maps APIs. 
   2. Introduce various arbitrary events on the map. Double clicking triggered it for me. 
   3. Occasionally experience the anomaly.

## Actual result:
The VM is corrupted. Before the incident it seemed like the browser was trying to launch an infinite amount of some instances which corrupted the entire memory block for the VM.

## Expected result:
Nothing crashes.

## Reproduces how often: 
Once or twice per 5-6 hours of usage

## Brave version (brave://version info)
0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)

### Reproducible on current release:
I have been `apt-get`ting so yes?

### Website problems only:  
I don't want to try it again because it would affect the entire VM

**Comment by srirambv** [comment] 2019-04-16 14:04
May be the VM is low on memory and crashing. Does this happen on actual device or just VM? If its just VM then it would probably be because of low RAM or not enough virutal processors assigned. Closing the issue for now. If you manage to reproduce the issue on an actual device please reopen the issue

**Closed by srirambv** 2019-04-16 14:04 UTC
