### ISSUE TITLE
Please add an option for a plain, white newtab page

### ISSUE THREAD

**Issue by pitsi** [brave/brave-browser#8719] opened 2020-03-17 13:09 UTC
## Description 
As the title suggests, I would like to be able to set my newtab page to just plain white (or any other "soft" color). Removing the background image from the newtab options results in a really annoying, bright, gradient background.

## Steps to Reproduce
1. Open a new tab page (brave://newtab)
2. Use the "sliders" shortcut on the bottom of the page to disable the "show background image" option. I have also disabled the stats and the rewards option, but they are irrelevant to the rest. 
3. Notice that bright, gradient background that looks like some stock wallpaper from a recent ubuntu release :P 

## Actual result:
What I mention on step 3 above, unless you use a background image.

## Expected result:
I think a white page, or even one with a more subtle colors, would be better.

## Reproduces how often: 
Everytime I open a new tab.

## Brave version (brave://version info)
Brave: 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
Revision: fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS: Linux

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Yes. I checked that channel a couple of months ago
- Can you reproduce this issue with the dev channel? Same as above
- Can you reproduce this issue with the nightly channel? Same as above

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? No. It is not related to shields at all.
- Does the issue resolve itself when disabling Brave Rewards? No. It is not related to rewards too. 
- Is the issue reproducible on the latest version of Chrome? No. Chrome offers a plain white newtab page since 2008.

## Miscellaneous Information:
Debian testing x64. Also, what is the "show sponsored images" supposed to do? Brave enables it once I disable "show background image" and then it grays out. A bug maybe?
On top of the above, I see that the same gradient is used on the top of the options, bookmarks and history page, but only at the top.

**Comment by rebron** [comment] 2020-05-08 16:00
@pitsi Closing as a duplicate of #2999 
We'll address blank new tab page there.

**Closed by rebron** 2020-05-08 16:00 UTC
Labels: duplicate
