### ISSUE TITLE
Transparent Background while viewing Networks in Crypto Wallet

### ISSUE THREAD

**Issue by deepxcode** [brave/brave-browser#17028] opened 2021-07-19 11:56 UTC
## Description 

When we view the Networks section in Crypto Wallet, A box appears which lists all the Networks. The box has a transparent background, i.e. I can see the lines of the main page when I View the Networks. It doesn't look good, either it should have an opaque background or a darker, slightly transparent background.

## Steps to Reproduce

   1. Login in to [brave://wallet](brave://wallet)
   2. On the main screen, Where you see the `Main Ethereum Network` or Any Network As such Click on that, and you will see a list of Networks. You can see the issue that I have stated, it doesn't' look good.
  
## Actual result:

![image](https://user-images.githubusercontent.com/31823246/126155461-7c9d6dec-e161-4615-bbfb-d36c1dd417f5.png)
![image](https://user-images.githubusercontent.com/31823246/126155556-682e457d-3ce0-48c9-9834-f612023f90bb.png)

## Expected result:
The list of Networks should Have an Opaque background or a slightly darker background such that the lines cannot be seen.

## Reproduces how often: 

100%

## Brave version (brave://version info)

<html>
<body>

Brave | 1.26.77 Chromium: 91.0.4472.164 (Official Build) (64-bit)
-- | --
Revision | 541163496c9982c98f61819bab7cf2183ea8180f-refs/branch-heads/4472@{#1569}
OS | Windows 10 OS Version 2009 (Build 19043.1110)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by deepxcode** [comment] 2021-07-19 11:59
@stephendonner This is a good first issue, how do I add the required tag?

**Comment by srirambv** [comment] 2021-07-19 14:00
That is not a bug but an upstream design we inherited from MetaMask. Also, once the native wallet is available this would be obsolete.

Thanks for the issue though, Going to close this one as wontfix.

**Closed by srirambv** 2021-07-19 14:00 UTC
Labels: OS/Desktop

**Comment by deepxcode** [comment] 2021-07-20 05:03
Oh okay, got it! Thank you!
