### ISSUE TITLE
Due to performance issue, wallet balance doesn't go down immediately after tipping a verified pubs 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3345] opened 2019-02-13 20:08 UTC
## Description 
Due to performance issue, wallet balance doesn't go down immedaitely after tipping a verified pubs. Page reload required once or twice to see updated wallet balance.

## Steps to Reproduce

   1. Clean profile 0.60.27
   2. Claim grants
   3. Open verified pub
   4. Send tip to verified pub ( For my test I have sent 10 BAT)
   5. Verify that wallet balance did not go down
   6. Restart browser, verify that wallet balance still did not go down
   7. Reload page once or twice ( Balance goes down)

## Actual result:

Even after browser restart, wallet balance doesn't go down. required page reload once or twice

![wallet balance doesn t go down immediately - requires page reload](https://user-images.githubusercontent.com/38657976/52740369-ea407b00-2ff8-11e9-85ba-6836c2b05181.gif)

## Expected result:
Wallet balance should go down immediately after tipping a verified pubs

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.60.27 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 10

### Reproducible on current release: No
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment] 2019-02-13 20:36
this doesn't look like client issue. I am still getting 500 from the server, so let's check again when server/uphold is stable again.

**Comment by kjozwiak** [comment] 2019-02-13 22:16
@NejcZdovc I think @GeetaSarvadnya mentioned that this wasn't reproducible on the current release via:

```Reproducible on current release: No```

If this was a server side issue, I'm assuming `0.59.35` would also experience the same problems? Is there a difference between `0.59.35` and `0.60.x` where the performance can differ depending on what state the server is in? Maybe when @GeetaSarvadnya was checking it on production, she got lucky and everything worked but hit server issues on `0.60.x`?

**Comment by NejcZdovc** [comment] 2019-03-07 09:32
tried this on the latest 0.63 and can't reproduce it. Will close it. If you can still reproduce it on the latest 0.63 please re-open it.

**Closed by NejcZdovc** 2019-03-07 09:32 UTC
Labels: QA/Yes, bug, feature/rewards, priority/P4, regression
