### ISSUE TITLE
Install folder : no choice ?

### ISSUE THREAD

**Issue by marseye** [brave/brave-browser#1143] opened 2018-09-15 12:08 UTC
Installing on Windows, the install is silent and rushing automatically to my system hard-drive. I have to be a strict manager of the few remaining space on this HDD, so I had to uninstall Brave. Sorry. 

It is really annoying to me not to be able to chose which partition will receive the install. 

Thank you.

**Comment by srirambv** [comment] 2018-09-15 12:17
Duplicate of https://github.com/brave/brave-browser/issues/598.  

This is a known issue on Chrome as well which was logged (https://bugs.chromium.org/p/chromium/issues/detail?id=113987) in 2012 and still not fixed.

**Closed by srirambv** 2018-09-15 12:17 UTC
