### ISSUE TITLE
Potential Tor leak [H1 #505764]

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#3606] opened 2019-03-06 18:32 UTC
https://hackerone.com/reports/505764

In some cases, a Windows system configuration can cause a Brave user in private windows to be deanonymized to a specific set of configured servers. We should disable the Chromium support for this Windows configuration within incognito and guest sessions.

**Comment by diracdeltas** [comment] 2019-03-06 19:16
dupe of #3603

**Closed by diracdeltas** 2019-03-06 19:16 UTC
Labels: feature/private-browsing, feature/tor, priority/P2, privacy
