### ISSUE TITLE
Brave Beta has bookmarks overflow "ghost" button

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#42766] opened 2024-12-09 18:16 UTC
### Description

In Brave Beta, v1.74.20, the bookmarks overflow button at the top-right of the page is "ghost-like" in that it is invisible until hovered over directly. Note that I do not see this issue in Nightly build (1.75.76) at this time:

https://github.com/user-attachments/assets/fd5a7c79-c698-48e8-a227-754579f9b00f

This issue only occurs when the browser is using a "light" theme — "dark" theme shows the overflow button as expected. 

### Steps to reproduce

1. Have light theme enabled in browser
2. Go to `Settings --> Bookmarks` and get spooked by the overflow button 👻 

### Actual result

Ghost button

### Expected result

Button should be visible at all times

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Beta v1.74.24

### Channel information

- [ ] release (stable)
- [x] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by emerick** [comment] 2024-12-09 22:54
@fallaciousreasoning In my testing, it seems like we need to uplift https://github.com/brave/brave-core/pull/26676 and https://github.com/brave/brave-core/pull/26673 in order to fix this for 1.74.x. If that makes sense to you, I can get uplifts rolling for those tomorrow. If you think there's a better way to deal with this for 1.74.x let me know, of course!

**Comment by kjozwiak** [comment] 2024-12-10 19:51
> ~[@fallaciousreasoning](https://github.com/fallaciousreasoning) In my testing, it seems like we need to uplift [brave/brave-core#26676](https://github.com/brave/brave-core/pull/26676) and [brave/brave-core#26673](https://github.com/brave/brave-core/pull/26673) in order to fix this for 1.74.x. If that makes sense to you, I can get uplifts rolling for those tomorrow. If you think there's a better way to deal with this for 1.74.x let me know, of course!~
> 
> After speaking with [@fallaciousreasoning](https://github.com/fallaciousreasoning), it looks like we only need to uplift [brave/brave-core#26673](https://github.com/brave/brave-core/pull/26673) to fix this.

Closing as per the above. As per @emerick, it was fixed via https://github.com/brave/brave-core/pull/26673.

**Closed by kjozwiak** 2024-12-10 19:51 UTC
Labels: bug, feature/user-interface, priority/P2, feature/settings, OS/Desktop

**Comment by LaurenWags** [comment] 2024-12-10 21:33
Requires 1.74.25 or higher for verificattion 👍🏻

**Comment by MadhaviSeelam** [comment] 2024-12-11 22:40
Verification `PASSED` using
```
Brave | 1.74.25 Chromium: 132.0.6834.33 (Official Build) beta (64-bit)
-- | --
Revision | 041ffab11e000929213dcdae825dba438ff8a620
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

Couldn't reproduce actual issue of overflow "ghost" button.  However, `Could not find "toolbar-extra" element` error is shown in the console for brave://bookmarks page in `1.74.20 Chromium: 131.0.6778.108 beta (64-bit)` 

<Details>

![Image](https://github.com/user-attachments/assets/b2e5f479-4370-437d-818a-a615197996d7)
</Details>


#### Confirmed `Could not find "toolbar-extra" element` error is not shown in the console 

![Image](https://github.com/user-attachments/assets/9c4bd793-50ff-4235-8389-dc874c02a2dc)

**Comment by Brave-Matt** [comment] 2024-12-11 23:02
I would like to note that this issue can be reproduced in Win10 and also macOS
