### ISSUE TITLE
Brave Browser Linux Manjaro

### ISSUE THREAD

**Issue by thejoker3000** [brave/brave-browser#13073] opened 2020-12-07 17:23 UTC
## Description 

I recently installed manjaro Linux and brave. I'm downloading tools and things that I need and first thing I went to download was VMware workstation. Upon clicking download, it prompts to ask where to save the file.
When the prompt comes up, it has some strange look about it.

See images below.e
![brave-bad](https://user-images.githubusercontent.com/53082621/101383165-13f72000-38b9-11eb-8e58-2530b5c6ab39.png)
![compare-brave-manjaro](https://user-images.githubusercontent.com/53082621/101383166-148fb680-38b9-11eb-92da-5e5b2c9b96b4.png)

First image (image 1) is the prompt to where to save, so I thought it might be that the linux is bad. But when the screenshot prompt came up to ask where to save the captured image, it looked normal (image 2)

## Steps to Reproduce

   1. Install manjaro
   2. Install brave via snap tool or snap store
   3. try downloading something random and make it ask where you want to save that file

## Brave version (info found on brave://version)

Latest version

**Comment by rebron** [comment] 2020-12-07 18:37
Closing as duplicate of #13064

**Closed by rebron** 2020-12-07 18:37 UTC
Labels: closed/duplicate
