### ISSUE TITLE
Can't enter site URL on 'Favorites (top sites)' customization Card.

### ISSUE THREAD

**Issue by satyam-rockz** [brave/brave-browser#23872] opened 2022-07-05 07:31 UTC
## Description 

On the home page of Brave Browser [Desktop], there is a card of 'favorite sites' and there is also an option to edit the site name and its URL. The site name is editable, and when someone clicks the URL input area, the editing  popup gets closed.

## Steps to Reproduce

   1.  Open the brave default Home page
   2.  Locate the 'Favorite sites/ most frequently visited sites'
   3.  Hover on a site icon
   4.  Editing icon will appear
   5.  Click on the edit icon
   6.  Enter the new site name
   7.  Try to change the site URL. It will close instantly. Or if you will click on the popup anywhere, it will still get closed somehow.

## Actual result:

-> Can't Edit the 'Favorite sites card'

## Expected result:
-> Should be able to enter new site URL in the 'Favorite sites card'

## Reproduces how often: 

-> The Function isn't working

## Brave version (brave://version info)

1.40.109 Chromium: 103.0.5060.66 (Official Build) (64-bit) 

## Version/Channel Information:

- Reproduced this issue with the current release

**Comment by rebron** [comment] 2022-07-05 20:34
Closing as duplicate of https://github.com/brave/brave-browser/issues/23689

**Comment by rebron** [comment] 2022-07-05 20:35
Fix is on the way, currently in beta and nightly in 1.42.x and will make it into 1.41.x.

**Closed by rebron** 2022-07-05 20:34 UTC
Labels: OS/Desktop
