### ISSUE TITLE
"3rd-party cookies blocked" seems to also block cross-origin requests as well

### ISSUE THREAD

**Issue by jryans** [brave/brave-browser#2521] opened 2018-12-13 10:54 UTC
## Description 
A user [reported](https://twitter.com/GustavMarwin_/status/1071780162243563526) that our site was broken in Brave. It appears that the Brave mode "3rd-party cookies blocked" also blocks cross-origin requests, which seems like a bug based on the setting's name.

## Steps to Reproduce

   1. Set cooking mode to "3rd-party cookies blocked"
   2. Go to https://riot.im/app/#/register
   3. You will see the error message "Unable to query for supported registration methods"

## Actual result:
![2018-12-13 at 10 51](https://user-images.githubusercontent.com/279572/49933977-0fafec00-fec5-11e8-86ad-a823039ab675.png)

## Expected result:
If I set to allow cookies, then I get:

![2018-12-13 at 10 52](https://user-images.githubusercontent.com/279572/49934018-26564300-fec5-11e8-8afe-078682db295e.png)

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Brave | 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?
Yes, reproduces on Dev as well.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
Yes, disabling the shield (or just changing the cookies part) resolves it.
- Is the issue reproducible on the latest version of Chrome? 
No, Chrome works correctly.

**Comment by jeroen7s** [comment] 2018-12-14 07:45
have been noticing the same for about a day
other example is https://deltablue.cloud/#/account/login

**Comment by iefremov** [comment] 2019-01-09 12:51
Should fixed as a duplicate of #2252

**Closed by iefremov** 2019-01-09 12:51 UTC
Labels: feature/shields/webcompat

**Comment by btlechowski** [comment] 2019-01-09 22:08
Verification passed on

Brave | 0.58.20 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/50931588-5dd3f300-1463-11e9-8c16-b1f1602ae0f4.png)
