### ISSUE TITLE
Beta: brave://settings/importData blank page

### ISSUE THREAD

**Issue by aliabe-creator** [brave/brave-browser#19436] opened 2021-11-14 05:54 UTC
## Description 

Unsure if there's another issue that addresses this, I looked around and I couldn't find a related one.

I just installed Brave Beta, and naturally navigated to brave://settings/importData to import my bookmarks. However, instead of seeing a dialog to import my stuff, I get a completely blank page.

## Steps to Reproduce

   1. Navigate to brave://settings/importData
   2. Observe blank page

## Actual result:

![image](https://user-images.githubusercontent.com/80125711/141669314-d69ce1fa-980b-4b8f-acb5-99f228796bc7.png)

## Expected result:

Dialog/page to import data from other browsers/files.

## Reproduces how often: 

Every time brave://settings/importData is visited.

## Brave version (brave://version info)

1.33.77 (Beta), Windows 10 Home 21H1

## Version/Channel Information:

- Can you reproduce this issue with the current release? Unsure
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Unsure if it's just a broken link... It's practically a new Brave install.

**Comment by aliabe-creator** [comment] 2021-11-14 06:01
Clarification: if I visit the Import bookmarks and settings page normally through Settings, the dialog box does show up. However, when I attempt to type the same URL and visit it directly, the dialog box fails to load. In fact, the entire page "freezes" until the user clicks *twice* on a link on the page.

**Comment by sisco0** [comment] 2021-11-15 05:34
Should this issue be fixed with the pull request proposed in https://github.com/brave/brave-core/commit/ce1ed9a2370ab840d73ff1ad424f4a914659b4db?

**Comment by aliabe-creator** [comment] 2021-11-15 07:51
@sisco0 Weird, still blank page for me though, 1.33.77 Chromium: 96.0.4664.35 (Official Build) beta (64-bit). Hopefully fixed in the next Beta update.

**Comment by sisco0** [comment] 2021-11-15 14:15
@allabe Reach out any version from 1.34.5, as this change was introduced 5 days ago. The commit page contains the releases references tags where this commit is included.

**Comment by aliabe-creator** [comment] 2021-11-15 18:39
@sisco0 oh ok, thanks!

**Closed** 2021-11-15 18:39 UTC
Labels: OS/Desktop

**Comment by stephendonner** [comment] 2021-11-15 23:58
Duplicate of https://github.com/brave/brave-browser/issues/19364
