### ISSUE TITLE
[Follow up to #22610] Auto-redirect AMP pages - Loops - page won't load on Android.

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#23312] opened 2022-06-07 21:27 UTC
## Description 
Loading this ULR causes a AMP redirect loop, page won't load, DevTools network shows looping pageload /amp

Follow up to https://github.com/brave/brave-browser/issues/22610 as this is behaving differently on Android vs Desktop

## Steps to reproduce 

1.   Open URL https://t.co/0Ydr4haUQd which should land at
2. https://www.airlive.net/new-footage-shows-an-ukrainian-mig-29-taking-off-from-mykolaiv-seconds-before-the-runway-is-shelled-by-the-russians/
3. Watch the Omnibox blink
4. Devtools watch the Network tab and see that it loads page then /amp and loops on that

## Actual result 
Page load gets stuck in loop

https://user-images.githubusercontent.com/17885425/172485641-9bbcc052-edfa-4eb3-98e4-7a6b014264aa.mp4

## Expected result
Page should load 

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy Devices
   - Android version: 12
   
## Brave version
version `1.39.118, Chromium 102.0.5005.78`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ShivanKaul** [comment] 2022-06-08 03:22
Dupe of https://github.com/brave/brave-browser/issues/23320. The site is doing a js redirect now.

**Closed by ShivanKaul** 2022-06-08 03:22 UTC
Labels: bug, closed/duplicate, QA/Yes, OS/Android, feature/vpn
