### ISSUE TITLE
VPN auto disconnects when device goes to sleep

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25773] opened 2022-10-03 14:45 UTC
## Description 

Similar to #23070, VPN auto disconnects when device goes to sleep

## Steps to Reproduce

   1. Install VPN profile
   2. Wait for device to go to sleep
   3. Login back to device, VPN is disconnected

## Actual result:

VPN auto disconnects when device goes to sleep

## Expected result:
Should not disconnect VPN when device wakes up

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.46.24 Chromium: 106.0.5249.65 (Official Build) nightly (arm64)
-- | --
Revision | `3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}`
OS | macOS Version 12.4 (Build 21F79)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA 
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @spylogsster @bsclifton @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment] 2022-10-03 14:46
Issue is reproducible in Windows 10 x64 - 1.45.78 Chromium: 106.0.5249.65

@spylogsster Looks like regression as it was fixed in https://github.com/brave/brave-browser/issues/23070

**Comment by LaurenWags** [comment] 2022-10-03 14:49
cc @rebron

**Comment by spylogsster** [comment] 2022-10-11 15:31
cannot reproduce on macos

**Comment by srirambv** [comment] 2022-10-12 14:24
@spylogsster I was able to repro it on macOS with latest nightly and VPN on staging.

**Comment by GeetaSarvadnya** [comment] 2022-10-18 07:33
Reproduced the issue in `Windows 10 x64 - 1.45.98 Chromium: 106.0.5249.119`

My system was idle for 40 mins, when I unlock the system, the VPN got disconnected and it remained disconnected even after the unlock.

![image](https://user-images.githubusercontent.com/38657976/196365690-5f735be5-ea7e-46d9-9c40-44e1160182ab.png)

**Closed** 2022-10-18 17:50 UTC
Labels: QA/Yes, release-notes/exclude, regression, OS/Desktop, feature/vpn

**Comment by GeetaSarvadnya** [comment] 2022-10-26 13:34
Verification PASSED on

```
Brave | 1.46.80 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 10 Version 21H2 (Build 19044.2130)

```
- Ensured that VPN doesn't gets disconnected when system goes to sleep
- System was idle for 30 mins, when I unlock the system, the VPN is in connected state and it remained connected after unlock as expected.

**Comment by bsclifton** [comment] 2022-12-01 17:00
Updated to `QA/No` - we backed out this behavior with https://github.com/brave/brave-core/pull/16163. We're going to let the OS handle it however the OS is supposed to be handling it
