### ISSUE TITLE
Tip button messed up on GitHub organization People tab

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#26174] opened 2022-10-21 18:02 UTC
## Description 

Similar to https://github.com/brave/brave-browser/issues/18494, the Tip button is messed up on https://github.com/orgs/orgname/outside-collaborators. 

We should just not have the Tip button on that People tab (I've mentioned the URLs below), it's a distraction from trying to do People management on a GitHub org. We currently don't have the Tip button on https://github.com/username/reponame/settings/access either.

## Steps to Reproduce

Go to the Outside Collaborators page of a GitHub org: https://github.com/orgs/orgname/outside-collaborators

## Actual result:

![image](https://user-images.githubusercontent.com/5284154/197258506-912c52fb-3161-43a5-9890-f6119ede1e48.png)

## Expected result:
Not have Tip button on any of the following:
1. https://github.com/orgs/*/people/*
2. https://github.com/orgs/*/outside-collaborators
3. https://github.com/orgs/*/pending_collaborators

## Reproduces how often: 

Always

**Comment by GeetaSarvadnya** [comment] 2023-01-20 11:41
Verification **PASSED** on

```
Brave | 1.47.177 Chromium: 109.0.5414.87 (Official Build) (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 10 Version 21H2 (Build 19044.2486)
```
- Verified the issue with the dev component `Brave Local Data Updater - Version: 1.0.699` and confirmed Inline Tip issue is fixed [Confirmed with @ShivanKaul that the issue is fixed with the GH page https://github.com/orgs/ietf-wg-ohai/outside-collaborators, unable to verify from my end as it's private repo]
- Inline Tip is NOT shown in people and members Github pages, Logged https://github.com/brave/brave-browser/issues/27926

**Closed** 2023-01-20 13:25 UTC
Labels: bug, feature/rewards, QA Pass-Win64, QA Pass-macOS, priority/P3, QA/Yes, greaselion, OS/Desktop
