### ISSUE TITLE
Soften the dividing line color of the address bar

### ISSUE THREAD

**Issue by Ehab-d** [brave/brave-browser#42310] opened 2024-11-15 08:02 UTC
### Description

After Brave update, The color of the dividing line has become lighter. This makes the line striking and annoying.

### Steps to reproduce

Here is an image of what it looks like before and after...
![Image](https://github.com/user-attachments/assets/562dd318-d215-4e75-9ec8-2a75d81d655e)

### Actual result

[not available]

### Expected result

[not available]

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

[Version 1.73.89 Chromium: 131.0.6778.69]

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment] 2024-11-20 19:37
Closing as a dupe of https://github.com/brave/brave-browser/issues/42286 and fixed in 1.73.91.

@Ehab-d Can you update to the 1.73.91 and let us know what you think? Thanks.

**Closed by rebron** 2024-11-20 19:37 UTC
Labels: OS/Desktop
