### ISSUE TITLE
Search from omnibox doesn't work with search engine extension

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#15170] opened 2021-04-07 09:35 UTC
## Description 

Search from omnibox doesn't work with private window allowed search engine extension.

## Steps to Reproduce

   1. Install search extension such as https://chrome.google.com/webstore/detail/ecosia-the-search-engine/eedlgdlajadkbbjoobobefphmfkcchfk/related?hl=en
   2. Turn on `Allow in private window` in brave://extensions/?id=eedlgdlajadkbbjoobobefphmfkcchfk
   3. Open private window and search any keyword from omnibox

## Actual result:

Search doesn't work.
When type `test` keyword in omnibox private window(or tor), it tries to load as a url instead of search term.

## Expected result:
Load extension's search engine result page

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

This issue seems related with  https://github.com/brave/brave-browser/issues/14218

**Comment by simonhong** [comment] 2021-04-08 04:07
We are using separate `TemplareURLService` for normal and private window because we want to set different search engine for both mode. Chromium uses same service for both mode.
In chromium code, there are many assertions - default search provider is set by extension (not user) if this kind of extension is installed. However, `TemplateURLService` for private window doesn't have extension search provider by default. This causes many runtime failure with DCHECK enabled.

**Comment by bsclifton** [comment] 2021-04-12 05:24
@simonhong is this a duplicate of https://github.com/brave/brave-browser/issues/10601?

**Comment by simonhong** [comment] 2021-04-12 05:29
@bsclifton Yes, I think so.

**Closed** 2021-04-12 05:38 UTC
Labels: OS/Desktop, closed/duplicate
