### ISSUE TITLE
Brave 0.55.18 - can't edit adblocker lists, can't enable regional lists

### ISSUE THREAD

**Issue by Haxy89** [brave/brave-browser#1725] opened 2018-10-19 07:07 UTC
How to enable regional lists?
How to edit adblocker lists?

"Edit default shield settings" button move to Brave Settings

**Comment by Sh1d0w** [comment] 2018-10-19 08:56
This is must have feature, as it seems the current Brave adblock rules does not block most of the ads. 

We need a way to enable more adblock lists, or at least provide a way to insert out own rules, copied from those lists out there.

**Comment by Haxy89** [comment] 2018-10-19 09:00
How is it possible that official release version does not have this feature?
![image](https://user-images.githubusercontent.com/37550896/47208452-1c650780-d38e-11e8-9c25-e15161dd8fe9.png)

This should be mark as beta or dev!

**Comment by ashishoffline** [comment] 2018-10-19 09:07
Yes,
Current Brave AdBlock doesn't block most of the ad.
It also doesn't block regional ad and there is no option to enable that.

**Comment by onmyouji** [comment] 2018-10-19 09:17
Probably duplicate of #403

**Comment by bbondy** [comment] 2018-10-19 14:02
We don't have custom list of ads yet but regional adblock is supported. You can see if it is in use or not in about:adblock

**Comment by Sh1d0w** [comment] 2018-10-19 14:04
@bbondy about:adblock says: Regional Ad Block: Disabled. How can I enable it in the new chromium build?

**Comment by srirambv** [comment] 2018-10-19 14:37
@Sh1d0w  you can follow the steps from here on Linux to enable Regional adblock 
https://github.com/brave/brave-browser/issues/1238#issuecomment-427495893

**Comment by srirambv** [comment] 2018-10-19 14:38
Dupe of  https://github.com/brave/brave-browser/issues/403?

**Comment by Haxy89** [comment] 2018-10-19 16:44
> @Sh1d0w you can follow the steps from here on Linux to enable Regional adblock
> [#1238 (comment)](https://github.com/brave/brave-browser/issues/1238#issuecomment-427495893)

What about windows? Is Brave linux only? If so please mark it on website.
I am Windows user and for me current official 0.55.18 release is dev or at least beta.

**Comment by srirambv** [comment] 2018-10-19 20:49
@Haxy89 Brave is available for all platforms(Windows/Mac/Linux). The link posted i[here](https://github.com/brave/brave-browser/issues/1725#issuecomment-431385120) s specific for Linux. For Windows you need to change the region in Settings and regional adblock to work.

**Comment by Sh1d0w** [comment] 2018-10-20 03:40
@srirambv Thanks man, but I am Mac user for several years now. Can you advise how to enable this on Mac? I was searching for region setting, but there is no region there?

**Comment by srirambv** [comment] 2018-10-20 12:12
@Sh1d0w for Mac its here https://github.com/brave/brave-browser/issues/1238#issuecomment-426068531

**Comment by srirambv** [comment] 2018-10-29 17:16
#403 should cover this as well.

**Closed by srirambv** 2018-10-29 17:16 UTC
Labels: priority/P2
