### ISSUE TITLE
Repeated Full Browser Crashes

### ISSUE THREAD

**Issue by KieranP** [brave/brave-browser#34962] opened 2023-12-19 00:43 UTC
Since the release of v1.61.100 (Dec 6, 2023), I have been having repeated full browser crashes, sometimes 3 or 4 per day. I can be on any site when it happens, most commonly happens when switching between browser tabs, but not always. I thought it might be related to chrome memory saver, so I turned it off, but no change. I thought it might be related to extensions, so I disabled them all, but no change.

Brave Version: 1.61.104 Chromium: 120.0.6099.115
Operating System: Mac OS X 14.2.0, on Macbook M2 Pro

Here is a selection of crash report IDs:

```
Uploaded crash report ID:	40980b00-100a-300b-0000-000000000000
Uploaded crash report ID:	556a0b00-100a-300b-0000-000000000000
Uploaded crash report ID:	582d0b00-100a-300b-0000-000000000000
Uploaded crash report ID:	f8810900-100a-300b-0000-000000000000
Uploaded crash report ID:	d12b0900-100a-300b-0000-000000000000
Uploaded crash report ID:	0b150900-100a-300b-0000-000000000000
Uploaded crash report ID:	6ef00800-100a-300b-0000-000000000000
Uploaded crash report ID:	9e330e00-8bde-260b-0000-000000000000
Uploaded crash report ID:	67cc0c00-8bde-260b-0000-000000000000
Uploaded crash report ID:	2bab0c00-8bde-260b-0000-000000000000
Uploaded crash report ID:	71fe0b00-8bde-260b-0000-000000000000
Uploaded crash report ID:	52e00b00-8bde-260b-0000-000000000000
Uploaded crash report ID:	ec210a00-8bde-260b-0000-000000000000
Uploaded crash report ID:	b9050a00-8bde-260b-0000-000000000000
Uploaded crash report ID:	f9ce0900-8bde-260b-0000-000000000000
```

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/40980b00-100a-300b-0000-000000000000

**Comment by rebron** [comment] 2023-12-21 18:01
closing as dupe of https://github.com/brave/brave-browser/issues/34909.
Hi @KieranP  Can you update to the latest 1.61.109 that released today and see if this is still an issue for you.

**Closed by rebron** 2023-12-21 18:01 UTC
