### ISSUE TITLE
Ubuntu Snap breaks U2F/FIDO authentication

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#12320] opened 2020-10-26 17:40 UTC
A community member reports that YubiKeys are not working when using the Ubuntu snap: https://community.brave.com/t/yubikey-not-working-using-brave-on-ubuntu-20-04/168773/12

brave 1.15.76 82 latest/stable brave

**Comment by bsclifton** [comment] 2020-12-27 18:22
Closing as duplicate of https://github.com/brave/brave-browser/issues/6782

**Closed by bsclifton** 2020-12-27 18:22 UTC
Labels: OS/Desktop, OS/Linux/snap
