### ISSUE TITLE
brave crashing when auto filling a form.

### ISSUE THREAD

**Issue by Ngugisenior** [brave/brave-browser#36348] opened 2024-02-23 18:10 UTC
## Description 
Whenever i try to autofill a form my brave beta desktop crashes.

## Steps to Reproduce

   1.  Try to auto fill a form

## Actual result:
brave crashes

## Reproduces how often: 
reproduceable evrytime

## Brave version (brave://version info)
[Version 1.64.74 Chromium: 122.0.6261.43 (Official Build) beta (64-bit)](https://brave.com/latest/)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by Bilalharoon** [comment] 2024-02-23 18:48
I wasn't able to reproduce. What operating system are you on and can you post the crash logs?

**Comment by rebron** [comment] 2024-02-23 20:56
Hi @Ngugisenior Can you update to a new version via brave://settings/help. The fix was in 1.64.75. Current version of beta is 1.64.82. Let us know if you're still seeing the issue after you update.
https://github.com/brave/brave-browser/issues/36077

**Comment by rebron** [comment] 2024-03-01 19:24
Closing as duplicate of #36077 @Ngugisenior Let us know if you're still seeing a crash.

**Closed by rebron** 2024-03-01 19:24 UTC
Labels: closed/duplicate, OS/Desktop
