### ISSUE TITLE
[Desktop] Follow up of 9186 - with shields down, FP values Web for audio is NOT same on both pages

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10260] opened 2020-06-15 08:46 UTC
## Description 

Follow up of 9186 - with shields down, FP values for `Web audio` is NOT same on both pages

## Steps to Reproduce

   1. Clean profile 1.10.90
   2. Visit https://dev-pages.bravesoftware.com/farbling.html
   3. Make shield down and Generate FP values
   4. Visit https://dev-pages.brave.software/farbling.html
   5. Make shield down and Generate FP values
   6. Look for Web audio values for both pages 2 and 4
   7. Web audio values are different in both pages

## Actual result:

https://dev-pages.bravesoftware.com/farbling.html
![image](https://user-images.githubusercontent.com/38657976/84636450-3ca5ea80-af12-11ea-9724-fd0993a26216.png)

https://dev-pages.brave.software/farbling.html

![image](https://user-images.githubusercontent.com/38657976/84636493-492a4300-af12-11ea-93ff-457bf0a746f9.png)

## Expected result:

As per the comments https://github.com/brave/brave-browser/issues/9186#issuecomment641513325 with shields down, FP values for Web audio should be same on both pages
## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.10.90 Chromium: 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | Windows 10 OS (Build 10240.17443)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not sure
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @pes10k

**Comment by btlechowski** [comment] 2020-06-15 11:04
@pes10k I believe this is a dupe of https://github.com/brave/brave-browser/issues/9194, which implements the ability to turn off fingerprinting?

**Comment by pes10k** [comment] 2020-06-15 15:47
@btlechowski I dont think this is a dupe, this looks like a bug, related to https://github.com/brave/brave-browser/issues/10223

**Comment by pes10k** [comment] 2020-06-15 15:47
cc @pilgrim-brave

**Closed** 2020-06-17 23:22 UTC
Labels: OS/Desktop, QA/Test-Plan-Specified, QA/Yes, feature/shields/fingerprint

**Comment by LaurenWags** [comment] 2020-06-18 12:00
labeling as `QA/Blocked` for now as this requires an uplift to test

**Comment by pes10k** [comment] 2020-06-23 17:12
re release-notes, i think it'd be sufficient to say "non-critical memory issue was fixed related to farbling and fingerprint randomization" or similar

**Comment by LaurenWags** [comment] 2020-06-23 17:18
awesome, thanks for the suggestion re: release notes blurb @pes10k  😄

**Comment by GeetaSarvadnya** [comment] 2020-06-24 07:24
Verification passed on
```

Brave | 1.11.73 Chromium: 83.0.4103.106 (Official Build) dev (64-bit)
-- | --
Revision | ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS | Windows 10 OS Version 1903 (Build 18362.900)

```
- Verified STR from the description
https://dev-pages.bravesoftware.com/farbling.html
![image](https://user-images.githubusercontent.com/38657976/85514597-d4de5680-b619-11ea-9d34-d703498251c3.png)


https://dev-pages.brave.software/farbling.html
![image](https://user-images.githubusercontent.com/38657976/85514440-ac565c80-b619-11ea-8059-2deaad953bbc.png)
