### ISSUE TITLE
"Allow Google login buttons on third party sites" option missing from Social media blocking (Nightly/Dev)

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#5922] opened 2019-09-06 18:28 UTC
## Description 

The top option to block Google login embeds in the `Social media blocking` section in `Settings` is missing in Nightly and Dev builds

**Release build (v0.68.132):**
![image](https://user-images.githubusercontent.com/3299098/64451433-1147c280-d099-11e9-9caf-3c863a56fc59.png)

**Dev (v0.71.70):**
![image](https://user-images.githubusercontent.com/3299098/64451493-32a8ae80-d099-11e9-8007-18ebb84636df.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by rebron** [comment] 2019-09-10 16:35
Doesn't reproduce on 0.70.93. Seeing the issue in 0.71.x Dev (and 72.x Nightly).

**Comment by bsclifton** [comment] 2019-09-13 16:57
@rebron @bbondy per comments in triage, this is not an issue, right? (we can close)

**Comment by bbondy** [comment] 2019-10-01 18:22
We can close this since the cookie exception is not needed anymore and never applied. I.e. no tracking element to allow by option anymore.

**Closed by bbondy** 2019-10-01 18:22 UTC
Labels: feature/settings, priority/P2, privacy
