### ISSUE TITLE
Vertical tabs group sync icon is basically invisible

### ISSUE THREAD

**Issue by NomarCub** [brave/brave-browser#36854] opened 2024-03-15 18:49 UTC
## Description 

The tab group sync icon is barely visible both on light and dark mode.
I'm on Windows 11 if that matters.

Vertical tabs:
![image](https://github.com/brave/brave-browser/assets/5298006/ac8e0fde-fa55-47a6-9cb0-3a8543815e7e)
![image](https://github.com/brave/brave-browser/assets/5298006/5ed0c19c-7fcb-41a2-95d0-86fe3127fee1)

Normal tabs:
![image](https://github.com/brave/brave-browser/assets/5298006/25b91099-c5f3-45b9-a163-b7a04357ba2d)
![image](https://github.com/brave/brave-browser/assets/5298006/f1a614bb-5842-44e2-8003-e86604fbe37a)

## Brave version

1.63.174 Chromium: 122.0.6261.128 (Official Build) (64-bit)

**Comment by rebron** [comment] 2024-03-15 19:05
cc: @zenparsing 
Dupe of https://github.com/brave/brave-browser/issues/35202 or at least I think the fix is there for the icon and contrast. Fixed in 1.65.x in beta now

**Comment by rebron** [comment] 2024-03-18 18:14
Closing as duplicate.

**Closed by rebron** 2024-03-18 18:14 UTC
Labels: closed/duplicate, OS/Desktop
