### ISSUE TITLE
Wrong Asset is turning up for ETH on Optimism and ETH on Arbitrum

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#28976] opened 2023-03-09 17:13 UTC
## Description 

When I select on ETH on Arbitrum or ETH on Optimism, it just shows me the ETH price on ethereum. It should show me the eth price on them other chains. @Douglashdaniel mentioned that we need to add chain ID

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment] 2023-03-10 04:32
Dupe of #24248

**Closed** 2023-03-14 16:38 UTC
Labels: bug, QA/Yes, release-notes/include, feature/web3/wallet, OS/Desktop, front-end-change

**Comment by srirambv** [comment] 2023-04-26 06:44
**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (64-bit) 
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | Linux

- Verified steps from [brave/brave-core#17544](https://github.com/brave/brave-core/pull/17544)
- Verified correct token details page is loaded when selecting Eth on Optimism and Eth on Aurora
- Verified selecting token from Panel routes it correctly to the token details page

https://user-images.githubusercontent.com/17010094/234490936-d6ef67be-faa4-47b9-9daa-6097b0c6c004.mp4

---------------------

**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (64-bit)
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17544](https://github.com/brave/brave-core/pull/17544)
- Verified correct token details page is loaded when selecting Eth on Optimism and Eth on Aurora
- Verified selecting token from Panel routes it correctly to the token details page

https://user-images.githubusercontent.com/17010094/234490900-a9f5b083-d146-4022-8fc7-cc731dc0ef4a.mp4


---------------------

**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (arm64)
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17544](https://github.com/brave/brave-core/pull/17544)
- Verified correct token details page is loaded when selecting Eth on Optimism and Eth on Aurora
- Verified selecting token from Panel routes it correctly to the token details page

https://user-images.githubusercontent.com/17010094/234491233-4bad5040-33c5-4750-9735-124a759fa0bb.mov
