### ISSUE TITLE
pending AC values are rounded once publisher verifies - follow up to 3741

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4886] opened 2019-06-13 13:19 UTC
## Description 
When there is a pending auto contribute for a publisher  and the publisher verifies, the contribution is made, but it is rounded down to nearest whole number. One time tips and recurring tips don't have this issue as they can only (currently) be set to whole numbers.

## Steps to Reproduce

   1. Launch with staging and reconcile flags, enable Rewards. Close Brave.
   2. Go to publisher_list and change second value for a verified site like `3zsistemi.si` to false from `["3zsistemi.si",true,false....` to `["3zsistemi.si",false,false....`
   3. Relaunch with same flags.
   4. Populate AC table, be sure that the site you modified shows as unverified and has a % value that won't result in a whole number contribution.
   5. Once reconcile completes, verify the site you modified is listed in Pending Contributions.
   6. Navigate to the site again, click on panel, click Refresh Status.

## Actual result:
This is the Pending Contributions list before refreshing status. Look at the first line, 2.6 BAT contribution to site:
![Screen Shot 2019-06-12 at 2 31 38 PM](https://user-images.githubusercontent.com/28145373/59434491-a64c5f80-8db9-11e9-8c0f-055f6b549ca3.png)

This is the tips list after refreshing status, see that only 2.0 BAT was contributed:
![Screen Shot 2019-06-12 at 2 38 36 PM](https://user-images.githubusercontent.com/28145373/59434539-c0863d80-8db9-11e9-9567-c4563874a0c9.png)

## Expected result:
Actual contribution amount, 2.6 BAT, would be contributed.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.68.39 Chromium: 75.0.3770.87 (Official Build) nightly(64-bit)
-- | --
Revision | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @mandar-brave @NejcZdovc

**Comment by NejcZdovc** [comment] 2019-06-13 13:21
This happens because tips currently only accept int. We need to adjust tip flow to accept double

**Comment by GeetaSarvadnya** [comment] 2019-07-15 13:54
The issue is Reproducible on `Windows 10 x64 - 0.67.108`

![image](https://user-images.githubusercontent.com/38657976/61221360-ffe7d700-a735-11e9-8114-bcfd4747bcc8.png)

![image](https://user-images.githubusercontent.com/38657976/61221440-23ab1d00-a736-11e9-9def-f5d6c6a61519.png)

**Comment by jhoneycutt** [comment] 2019-10-15 18:05
This was resolved by the changes to fix #6228. We no longer create pending contributions for unverified publishers during Auto Contribution.

**Closed** 2019-10-15 18:10 UTC
Labels: closed/not-actionable, feature/rewards
