### ISSUE TITLE
Bookmark Bar does not toggle

### ISSUE THREAD

**Issue by rushilsrivastava** [brave/brave-browser#3202] opened 2019-02-03 03:22 UTC
## Description 
There is no way to disable the bookmark bar from showing on the New Tab page.

## Steps to Reproduce
   1. Right click on Bookmark bar
   2. Toggle "Show Bookmarks Bar" option

## Actual result:
![Result gif](https://media.giphy.com/media/69rzJr5i2GRbukE9PC/giphy.gif)

## Expected result:
The bar should disappear on the New Tab page.

## Reproduces how often: 
Easily reproducible. 

## Brave version (brave://version info)

Brave | 0.59.34 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?
Not tested.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?
 n/a
- Is the issue reproducible on the latest version of Chrome? 
n/a

**Comment by eljuno** [comment] 2019-02-03 04:13
Duplicate of #1306

**Closed** 2019-02-03 04:42 UTC
