### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by JijoBose** [brave/brave-browser#36721] opened 2024-03-12 04:23 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.63.169 Chromium: 122.0.6261.111
Operating System: Mac OS X 13.6.4

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Browser crashes when using "Picture in Picture" mode

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/87061200-38c5-9e0b-0000-000000000000

**Comment by rebron** [comment] 2024-03-12 15:56
cc: @sangwoo108

**Comment by rebron** [comment] 2024-03-12 22:27
Dupe of this one? https://github.com/brave/brave-browser/issues/35528

**Closed** 2024-03-12 23:12 UTC
Labels: crash, OS/macOS, priority/P2
