### ISSUE TITLE
No option to import History, Bookmarks, passwords to Brave-dev from brave brave (release version)

### ISSUE THREAD

**Issue by TontyTon** [brave/brave-browser#2938] opened 2019-01-13 19:37 UTC
## Description 

There is no option to select Brave release version in Brave-dev version and vice-versa in Import settings.
![capture](https://user-images.githubusercontent.com/35778430/51089658-f1aa0580-1768-11e9-9f6f-90d4d9633889.PNG)

This would help easy transition between and parallel use of different versions of brave.

## Steps to Reproduce

   1. Install both Brave release and dev versions
   2. go to settings>Import Bookmarks And Settings
   3. Click on drop down list

## Actual result:

Brave release version absent

## Expected result:
Option to import History, Bookmarks, passwords from brave rel to brave-dev

## Reproduces how often: 

Always

## Brave version (brave://version info)

Windows
Rel 0.58.21 
dev 0.60.11

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? no
- Is the issue reproducible on the latest version of Chrome? yes (no option to import from brave, may be not resolvable)

### Additional Information

Add option to import search engines and settings, which is not available for chromium. Or otherwise add option to export to and import from text file for brave.

[This would also help easy transition between and parallel use of different versions of brave. ]

**Comment by srirambv** [comment] 2019-01-14 02:41
Dupe of https://github.com/brave/brave-browser/issues/1357

**Closed by srirambv** 2019-01-14 02:41 UTC
