### ISSUE TITLE
Rewards panel doesn't list IPFS links fully in panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#16612] opened 2021-06-25 06:14 UTC
## Description 

Rewards should work only for ipns + dnslink case, all others ipfs urls should be disabled

## Steps to Reproduce

   1. Visit an IPFS URI
   2. Open rewards panel
   3. Shows incomplete link

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/123378366-8fce6680-d584-11eb-8a4a-4bb6f89ac32e.png)

## Expected result:
It should work only for ipns + dnslink case, all others should be disabled

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.28.27 Chromium: 91.0.4472.120 (Official Build) nightly (64-bit)
-- | --
Revision | `12c5925972cffe578ca7ca7a295e98ee7e178a7a-refs/branch-heads/4472@{#1506}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bridiver @spylogsster 

Related to #14841

**Comment by zenparsing** [comment] 2021-06-30 16:09
See https://github.com/brave/brave-browser/issues/16612 for a previous related issue.

**Comment by stephendonner** [comment] 2021-06-30 21:07
> See #16612 for a previous related issue.

That's this bug; did you mean https://github.com/brave/brave-browser/issues/14841?

**Comment by bridiver** [comment] 2021-07-06 18:16
This issue is "won't fix" as written because we don't currently (and maybe never will have) a process for validating IPFS CID. We may or may not want to implement this for dnslink only. @bbondy ?

**Comment by bbondy** [comment] 2021-07-06 18:53
Updated the original issue to add "t it should work only for ipns + dnslink case, all others should be disabled"

**Closed** 2021-07-16 17:51 UTC
Labels: OS/Desktop, QA/Yes, bug, feature/ipfs, feature/rewards, release-notes/include

**Comment by stephendonner** [comment] 2021-07-20 17:05
Verified `FIXED` using 


Brave | 1.29.12 Chromium: 92.0.4515.101 (Official Build) nightly (x86_64)
-- | --
Revision | edb73f4fb624e2ea0cb6f5cc39c9e317ecd3535b-refs/branch-heads/4515@{#1536}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. launched Brave
3. loaded the following: `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html`, `https://wikipedia-on-ipfs.org`, and `ipns://en.wikipedia-on-ipfs.org/wiki/`
4. confirmed only `ipns://` links and regular `https://` links showed in the `Rewards` UI

`ipns://en.wikipedia-on-ipfs.org/wiki/` | `https://wikipedia-on-ipfs.org` | `ipfs://bafybeiemxf5abjwjbik<snip>/wiki/Vincent_van_Gogh.html`
--------------------|---------------|-----------------
<img width="1312" alt="Screen Shot 2021-07-20 at 9 52 04 AM" src="https://user-images.githubusercontent.com/387249/126365498-d0c188c4-b70a-49d1-a9ea-b1443c753f1d.png"> | <img width="1312" alt="Screen Shot 2021-07-20 at 9 50 50 AM" src="https://user-images.githubusercontent.com/387249/126365477-8901132b-40f1-4b4a-bde0-7ac13480ddc9.png"> | <img width="1312" alt="Screen Shot 2021-07-20 at 9 51 48 AM" src="https://user-images.githubusercontent.com/387249/126365489-a73eb643-7a1e-400c-aa60-077b5300ae4f.png">
