### ISSUE TITLE
missing title on focused tab and on tab hover

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#14511] opened 2021-03-06 00:12 UTC
## Description 
Title is missing on focused tab and when hovering over tab.

## Steps to Reproduce

Open several web pages. Notice on hover and selected tab, that page title is missing.

## Actual result:
<img width="663" alt="Screen Shot 2021-03-05 at 4 07 58 PM" src="https://user-images.githubusercontent.com/5951041/110187439-37087180-7dcd-11eb-87d7-789d8187aaf1.png">

## Expected result:
Page title should not be blank.

## Reproduces how often: 

Easy.

## Brave version (brave://version info)

Brave | 1.23.21 Chromium: 89.0.4389.72 (Official Build) nightly (arm64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment] 2021-03-06 00:33
Additional breakage. Looks like M1 arm64 specific and turning off hardware acceleration resolves.

<img width="1382" alt="Screen Shot 2021-03-05 at 4 24 56 PM" src="https://user-images.githubusercontent.com/5951041/110188421-7c7a6e00-7dd0-11eb-991e-3c23570a4f7e.png">
<img width="386" alt="Screen Shot 2021-03-05 at 4 29 10 PM" src="https://user-images.githubusercontent.com/5951041/110188427-7e443180-7dd0-11eb-8faf-b87616dbd085.png">

**Comment by bsclifton** [comment] 2021-03-12 07:04
Closing as duplicate of https://github.com/brave/brave-browser/issues/3471

**Closed by bsclifton** 2021-03-12 07:04 UTC
Labels: OS/Desktop, OS/macOS-arm64, QA/Yes, priority/P2, release-notes/exclude, workaround/disable-hw-acceleration
