### ISSUE TITLE
News' "add this RSS feed" functionality doesn't honor the HTTPS upgrade setting

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#38282] opened 2024-05-13 17:54 UTC
Steps To Reproduce:

1. Enable Brave News
2. In Brave settings (brave://settings/shields), set "Upgrade connections to HTTPS" to "Strict"
3. Open WireShark. Enable capturing. Set the display filter in WireShark to `http`
4. Visit https://fmarier.github.io/brave-testing/news-add-rss.html
5. Click the feed icon in the URL bar
6. Go back to WireShark. You can see a plaintext request sent to 172.105.6.87

## Actual

![Screenshot from 2024-05-13 10-52-56](https://github.com/brave/brave-browser/assets/167821/44e8c2b2-a43b-4449-b268-69864dfc35f3)

## Expected

The request should be upgraded to HTTPS and no HTTP request should be visible in WireShark.

Originally reported at https://hackerone.com/reports/2502007

**Comment by fmarier** [comment] 2024-05-13 17:57
The other thing that this suggests is that we are likely not running these URLs through our privacy filters (e.g. debouncer, query string filter).

**Comment by fmarier** [comment] 2024-05-13 19:16
To confirm, I updated the test page to add an `fbclid` parameter to the URL and it doesn't get stripped out:
![Screenshot from 2024-05-13 12-15-18](https://github.com/brave/brave-browser/assets/167821/a174bf32-dc6d-4d95-ac02-331694ee0a50)

**Comment by bsclifton** [comment] 2024-05-20 23:31
cc: @LorenzoMinto

**Comment by diracdeltas** [comment] 2024-06-06 20:11
@bsclifton is anyone able to take this issue?

**Comment by diracdeltas** [comment] 2024-09-03 18:48
@boocmp do you think you could take this?

**Comment by fallaciousreasoning** [comment] 2024-09-05 08:26
@fmarier I suspect this is probably a broader problem with our `ApiRequestHelper` class so this probably affects everything that uses it :fearful:

**Comment by boocmp** [comment] 2024-09-05 10:30
ApiRequestHelper uses the SharedUploaderFactory which bypasses any Brave code for requests passing through it, I always thought it is by design.

**Comment by fallaciousreasoning** [comment] 2024-09-05 12:15
cc @petemill not really sure on the best approach here?

**Comment by fmarier** [comment] 2024-09-05 18:50
I think this should be a News-specific fix (for these custom RSS feeds). We should not change any other internal requests.

**Comment by diracdeltas** [comment] 2024-12-16 17:51
Reopening as the fix for this was incomplete, but feel free to close it again and just open a follow-up if that's easier: https://bravesoftware.slack.com/archives/C6R461GF4/p1733936717990789

**Comment by DJAndries** [comment] 2024-12-17 17:15
> Reopening as the fix for this was incomplete, but feel free to close it again and just open a follow-up if that's easier: https://bravesoftware.slack.com/archives/C6R461GF4/p1733936717990789

Merged https://github.com/brave/brave-core/pull/26989 as a follow up last week

**Closed by DJAndries** 2024-12-17 17:15 UTC
Labels: priority/P2, QA/Yes, release-notes/include, Chromium/upgrade minor, OS/Desktop, feature/brave-news, privacy/https-upgrades

**Comment by LaurenWags** [comment] 2025-01-09 16:35
@fmarier do you think this one should be tested on all desktop OSes (Windows, macOS, Linux) or is verification on one OS sufficient? If you think this is important enough to test on all desktop OSes please add the `QA/Test-All-Platforms` label. Thanks!

**Comment by fmarier** [comment] 2025-01-09 20:27
@LaurenWags It should be fine on just one desktop platform. There's nothing OS-specific about this.

**Comment by LaurenWags** [comment] 2025-01-09 20:35
Excellent, thanks for the input @fmarier 😄

**Comment by MadhaviSeelam** [comment] 2025-01-14 21:10
Verification `PASSED` using
```
Brave | 1.75.159 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | a7b6f5093a2dad31fc3f56241a7d55be255e69e2
OS | Windows 11 Version 24H2 (Build 26100.2605)
```


Reproduced the issue in 1.73.x using the STR from https://github.com/brave/brave-browser/issues/38282#issue-2293463880

![Image](https://github.com/user-attachments/assets/6714c549-6a42-465c-8d7f-de51e306c0ec)


1. Installed 1.75.x 
2. launched Brave
3. Enable Brave News in the NTP
4. opened `brave://settings/shields`
5. set "Upgrade connections to HTTPS" to "Strict"
6. opened WireShark and enable capturing (wifi)
7. Set the display filter in WireShark to http
8. visited https://fmarier.github.io/brave-testing/news-add-rss.html
9. Click the feed icon in the URL bar

#### Confirmed no http request is shown related to `brave-news` in the wireshark


example | example | example | example | example 
----- | ------ | ------ | ----- | ------
![Image](https://github.com/user-attachments/assets/f32c2740-7f24-4da5-aa02-174cf4c66571)|![Image](https://github.com/user-attachments/assets/b989f610-a71d-46c8-b09f-9d887ce00a42)|![Image](https://github.com/user-attachments/assets/5a62588d-1432-4b18-8ff1-a574bc56b466)|![Image](https://github.com/user-attachments/assets/d2c34bfb-d8a7-42ad-8d4d-4e94e63eea02)|![Image](https://github.com/user-attachments/assets/7fac0287-54b0-42b0-b6b5-374615bcd673)
