### ISSUE TITLE
DevTools slow performances and colors problem in the "Sources" tab

### ISSUE THREAD

**Issue by JacopoSciampi** [brave/brave-browser#7342] opened 2019-12-12 14:29 UTC
## Description 
The DevTool "sources" tab show the code in just white color (I have the dark mode activated) and the performances while debugging some code are very bad. The same code debugged in Chrome or other browsers is working fine. 

## Actual result:
As I said, slow performances and something is wrong with colors. See attached pictures.

## Expected result:
I except Brave to work like Chromium.

## Reproduces how often: 
Everytime in every site. I tried unistalling and re-installing the browser in order too see if the problem solve, without success.

## Brave version (brave://version info)

Brave | 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)
-- | --
Revision | 99b6d241cf84f7fa7434ae8a59f9e74eb1464280-refs/branch-heads/3945@{#888}
OS | Windows 10 OS Version 1909 (Build 18363.535)
JavaScript | V8 7.9.317.29
Flash | 32.0.0.303 C:\Windows\system32\Macromed\Flash\pepflashplayer64_32_0_0_303.dll
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.74 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --profile-directory=Default --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,SimplifyHttpsIndicator,WebUIDarkMode --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,SyncUSSBookmarks,AllowPopupsDuringPageUnload,WebXR,AudioServiceOutOfProcess,SmsReceiver,UnifiedConsent,WebXrGamepadModule --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\jacop\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome?  No.

## Miscellaneous Information:
**Photo taken in Brave**
![image](https://user-images.githubusercontent.com/32507291/70720276-cf5f9580-1cf3-11ea-97fb-eb4cfbbeb34c.png)

**Photo taken in Chrome (79.0.3945.79)**
![image](https://user-images.githubusercontent.com/32507291/70720294-d7b7d080-1cf3-11ea-8b15-7edbc2d8bde2.png)

The color being this different can mean that something didn't load up properly (I guess) but I haven't found a way to solve this.

**Comment by LesterCovax** [comment] 2019-12-12 19:50
Looks like the same issue as [this one](https://github.com/brave/brave-browser/issues/5618).

> @bsclifton says...
This may be fixed now; with Nightly (and it'll work its way down through channels), you can enable remote debugging under brave://settings/privacy. When this is enabled, it should fetch sources

**Comment by bsclifton** [comment] 2019-12-13 06:34
Closing as a dupe of https://github.com/brave/brave-browser/issues/5618 (thanks for the assist, @LesterCovax!)

@JacopoSciampi this is fixed in [Developer](https://brave.com/download-dev) and [Nightly](https://brave.com/download-nightly) versions of the product. I created a PR now to uplift this to our Beta branch (1.2) since there have been a recent bump in requests:
https://github.com/brave/brave-core/pull/4228

**Closed by bsclifton** 2019-12-13 06:34 UTC
