### ISSUE TITLE
Shields should be disabled for about pages

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#223] opened 2018-05-24 14:57 UTC
## Description 
Shields should be disabled for about pages

## Steps to Reproduce

   1. Build from source
   2. Open settings page
   3. Shields is enabled and shows shields panel when clicked 

 ## Actual result:
![image](https://user-images.githubusercontent.com/17010094/40493339-859bfa00-5f40-11e8-9cae-640af76078ce.png)

## Expected result:
Shields should not be enabled for about pages
## Reproduces how often: 

Easy

## Brave version (about:brave info)

 46eaccaf

**Comment by cezaraugusto** [comment] 2018-05-30 01:32
dupe of #169

**Closed by cezaraugusto** 2018-05-30 01:32 UTC
Labels: bug, feature/about-pages, feature/shields
