### ISSUE TITLE
Brave crashes after clicking on `Sync`, `About Brave` and `Settings` menus in 1.17.70

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12759] opened 2020-11-18 10:48 UTC
## Description 

Brave crashes after clicking on `Sync`, `About Brave` and `Settings` menus in 1.17.70

## Steps to Reproduce

   1. Clean or upgraded profile 1.17.70
   2. Open hamburger menu, click on `Sync`, `About Brave` and `Settings` menus
   3. Brave crashes

## Actual result:

Crash

## Expected result:
No crash

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.17.70 Chromium: 87.0.4280.60 (Official Build) (64-bit)
-- | --
Revision | 12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS | Windows 10 OS Version 2004 (Build 19041.572)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @bsclifton

**Comment by AlexeyBarabash** [comment] 2020-11-18 10:53
Maybe it can be related with CHECK mentioned in https://github.com/brave/brave-core/pull/7121#issuecomment-729174574 

https://source.chromium.org/chromium/chromium/src/+/master:content/public/browser/web_ui_message_handler.h;l=125;drc=f50df03b5c021e63d80ecf09ea452fa9976071ea;bpv=1;bpt=1?q=content%2Fpublic%2Fbrowser%2Fweb_ui_message_handler.h&ss=chromium%2Fchromium%2Fsrc
```
  template <typename... Values>
  void CallJavascriptFunction(const std::string& function_name,
                              const Values&... values) {
    CHECK(IsJavascriptAllowed()) << "Cannot CallJavascriptFunction before "
                                    "explicitly allowing JavaScript.";
```
But for me it wasn't  always reproducible.

I noticed it after updating my repo so it has `Upgrade from Chromium 87.0.4280.49 to Chromium 87.0.4280.60`

**Comment by LaurenWags** [comment] 2020-11-18 12:34
Reproduces on macOS with the below build


Brave | 1.17.70 Chromium: 87.0.4280.60 (Official Build) (x86_64)
-- | --
Revision | 12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS | macOS Version 10.14.6 (Build 18G6042)

Crash Report IDs:
11a70000-0b46-6205-0000-000000000000
13a70000-0b46-6205-0000-000000000000
18a70000-0b46-6205-0000-000000000000

Could not reproduce with previous build


Brave | 1.17.69 Chromium: 87.0.4280.60 (Official Build) (x86_64)
-- | --
Revision | 12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS | macOS Version 10.14.6 (Build 18G6042)

**Comment by GeetaSarvadnya** [comment] 2020-11-18 12:49
Crash Report Id's collected from `Windows 10 x64 - 1.17.70`

8ba70000-0b46-6205-0000-000000000000
fca70000-0b46-6205-0000-000000000000
06a80000-0b46-6205-0000-000000000000

**Comment by AlexeyBarabash** [comment] 2020-11-18 12:52
Crashes here https://source.chromium.org/chromium/chromium/src/+/master:ui/base/template_expressions.cc;l=167;drc=f50df03b5c021e63d80ecf09ea452fa9976071ea;bpv=1;bpt=1?q=bool%20ReplaceTemplateExpressionsInternal&ss=chromium%2Fchromium%2Fsrc 

not related to the thing I mentioned above

**Comment by marcmv1** [comment] 2020-11-18 13:15
Same behavior for me on 1.17.70. Windows 10 20H2, 64 bit Brave.

**Comment by marcmv1** [comment] 2020-11-18 13:28
Another data point... my browser string is still reading .60, the commit log says it was upgraded to .66.

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.60 Safari/537.36

**Comment by srirambv** [comment] 2020-11-18 16:35
Need to retest https://github.com/brave/brave-browser/issues/12699 once this is fixed for NTP settings

**Comment by kjozwiak** [comment] 2020-11-18 18:34
Closing as https://github.com/brave/brave-core/pull/7183 & https://github.com/brave/brave-core/pull/7184 were merged.

**Closed by kjozwiak** 2020-11-18 18:34 UTC
Labels: OS/Desktop, QA/Test-Plan-Specified, QA/Yes, crash, release/blocking

**Comment by jorgicio** [comment] 2020-11-18 22:22
I'm having the same issue in Linux.

**Comment by GeetaSarvadnya** [comment] 2020-11-19 11:08
Verification passed on

```

Brave | 1.17.71 Chromium: 87.0.4280.66 (Official Build) (64-bit)
-- | --
Revision | fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}
OS | Windows 10 OS Version 2004 (Build 19041.572)

```

- Verified STR from the description and ensured there is no crash after clicking on `Sync`, `Settings` and `About Brave` menus
- Verified all the menu options from the 3 dot menu ( Customize and control brave) options and ensured there is no crash
- Verified PT/TOR/Guest window and ensured all the tabs are working fine
- Verified few settings randomly in brave://settings and ensured settings are working as expected
