### ISSUE TITLE
Reading List disappeared

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [brave/brave-browser#19431] opened 2021-11-13 14:49 UTC
## Description 
Reading list in no longer working. Button is not displaying in the Bookmarks tab and the option is gone from tab contextual menu.

## Steps to Reproduce
   1. Launch Brave
   2. Open any web adress

## Actual result:
Brave no longer displays the Reading List button in the right end of the Bookmarks toolbar
It is also impossible to add tabs to the Reading List by righ-clicking an open tab and selecting "Add tab to reading list" as this option is gone too.
There are no options in the Settings panel to enable it.

## Expected result:
Brave should be displaying the Reading List button at the right end of the Bookmarks toolbar and the appropriate option in tab contextual menus.

## Reproduces how often: 
Always / No steps to reproduce

## Brave version (brave://version info)
Brave | 1.31.91 Chromium: 95.0.4638.69 (Official Build) (64-bit)
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | Windows 10 Version 2004 (Build 19041.1348)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the nightly channel? Unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No

**Comment by brett-dtc** [comment] 2022-05-25 05:53
This problem is back as of 1.39.111

**Comment by UjCbFwtBayFM** [comment] 2022-05-25 12:07
Noticing the same this. It seems it was an intentional change per https://github.com/brave/brave-browser/issues/21976

**Comment by yatinnagar** [comment] 2022-05-25 19:55
same problem , lost my important links stored in reading list.

**Comment by dairefagan** [comment] 2022-06-19 18:44
I was able to restore this a few months ago in brave://flags but now it has disappeared and the option is no longer there.

![image](https://user-images.githubusercontent.com/12515718/174495857-2ec6c591-f3bb-4a5b-9dfe-d102f740defe.png)

Please fix the reading list, or at least leave us with the brave://flags workaround, I cannot think why it would make sense to remove both. This issue should be give priority.

**Comment by rebron** [comment] 2022-08-30 17:48
Closing out as duplicate of https://github.com/brave/brave-browser/issues/17959. 
And follow-up feature request https://github.com/brave/brave-browser/issues/25020

**Closed by rebron** 2022-08-30 17:48 UTC
Labels: OS/Desktop
