### ISSUE TITLE
Implement NFT Details screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#27302] opened 2022-12-12 13:37 UTC
## Description 
Can't open NFT's added via token registry 

## Steps to reproduce 

   1. Install 1.4.125 build
   2. Add a CryptoKitties NFT or Punks Comic NFT's
   3. Go back to portfolio and click on the NFT added in step 2, doesn't load the NFT details view

## Actual result 
Can't open NFT's added via token registry 

## Expected result
Should open NFT details view

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Not checked

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 12
   
## Brave version
1.47.125 x64 Beta 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @wchen342 @Pavneet-Sing

**Comment by wchen342** [comment] 2022-12-12 15:05
Isn't that what supposed to happen because of https://github.com/brave/brave-browser/issues/23507? Disable NFT details until portfolio page is implemented.

**Comment by srirambv** [comment] 2022-12-12 15:17
Ok yes I hadn't checked the test plan for #23507. Do I keep the issue open and we can use this for NFT details view or do we have an open issue in which case I can close this one as invalid

**Comment by wchen342** [comment] 2022-12-12 15:22
I don't think there is another issue for this so please keep it open. Maybe change the title to something like "implement NFT portfolio page"?

**Comment by Pavneet-Sing** [comment] 2022-12-13 13:16
Likely a dupe of https://github.com/brave/brave-browser/issues/27276

**Closed by Pavneet-Sing** 2022-12-13 13:16 UTC
Labels: QA/Yes, feature/web3/wallet, OS/Android
