### ISSUE TITLE
Update macOS Nightly Icons to be correct size

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#27399] opened 2022-12-15 12:30 UTC
## Description 

We need to update our MacOS icons with a minor size update.
Here are the required images
https://drive.google.com/drive/folders/17A01qCt12Tc1qsFMyvGfbnNigcjuSKmU?usp=share_link

**Comment by rebron** [comment] 2023-04-27 04:32
Closing as dupe of https://github.com/brave/brave-browser/issues/14801 and fixed in 1.51.x. @aguscruiz reopen if I'm incorrect.

**Closed by rebron** 2023-04-27 04:32 UTC
Labels: design, OS/macOS, priority/P3, misc/icons, QA/No, release-notes/include, OS/Desktop
