### ISSUE TITLE
Add option to disable static / baked-in search suggestions in address URL bar

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#5934] opened 2019-09-08 17:08 UTC
## Description

Brave offers suggestions in the search bar from a static/baked-in list. Typically, this list is comprised of Alexa top ~500 sites. There is currently no option to _disable_ this feature. 

Even though the feature does _not_ affect privacy, some users prefer to disable it, as some suggestions may be distracting or confusing. Secondly, many of the top Alexa sites included in the static list are from a completely different region than where a user may be from, and may therefore strike a user as unknown, untrusted or "shady" at first glance (see Reddit discussion linked below).

Because users do not know that these suggestions are drawn from a static list, they may perceive such suggestions as leaky _(including in private tabs),_ or believe that they've been compromised with ad/malware.

![image](https://user-images.githubusercontent.com/11497541/64491709-923dc000-d239-11e9-9070-2ff7bd34a92f.png)

cc: @kjozwiak @bsclifton 

## References 

Discussion and user request: https://www.reddit.com/r/brave_browser/comments/czsvo0/new_to_brave_why_this_browser_suggests_me_shady/ez3gf30/?context=3

Prior mention (@kjozwiak): https://github.com/brave/brave-browser/issues/2323#issuecomment-445665310

**Comment by rebron** [comment] 2019-11-20 21:04
@Miyayes Dupe of https://github.com/brave/brave-browser/issues/843?

**Comment by bsclifton** [comment] 2019-12-02 06:41
@rebron I think it's a little different. This request would still show the entries, but not the baked in ones (which may be part of Alexa top 500 or something like this)

**Comment by rebron** [comment] 2020-01-22 20:51
Other way around. Duping this to #7747

**Closed by rebron** 2020-01-22 20:51 UTC
Labels: duplicate
