### ISSUE TITLE
Update chromium to  90.0.4430.212	

### ISSUE THREAD

**Issue by Area51Kacz** [brave/brave-browser#15762] opened 2021-05-11 21:47 UTC
## Description 
Could we update to Chromium 90.0.4430.212 _(brave its still on .93)_
--

<br class="Apple-interchange-newline">

## Steps to Reproduce

just update it to 90.0.4430.212	

## Version/Channel Information:

Stable

**Comment by bsclifton** [comment] 2021-05-12 09:26
@Area51Kacz yup - we're already working on it 😄 Closing this as a duplicate of https://github.com/brave/brave-browser/issues/15725

**Closed by bsclifton** 2021-05-12 09:26 UTC
Labels: OS/Desktop
