### ISSUE TITLE
Update onboarding flow (brave://welcome)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#11861] opened 2020-09-25 17:58 UTC
## Description 
Original description:

> We've talked about adjusting the order of the onboarding for Desktop- possibly updating how search looks and where it's placed (currently 4th screen). I believe it was proposed to be the 2nd screen and we may show icons for the options
> 
> Once we have a mock up, we can start work to adjust this flow 😄 

Per @kjozwiak 's feedback, this is the user-facing issue related to https://github.com/brave/security/issues/216.

## Design

The welcome experience must incorporate a new slide that presents the antifraud referral confirmation checkbox to the user:

![image](https://user-images.githubusercontent.com/2388823/94468654-a1134f80-0179-11eb-9c17-402ff41afe8b.png)

P3A needed for both checkboxes.

To integrate this slide, improved ordering and visuals should be made to the welcome experience:
- Replace 1st "Let's Go" slide with the import slide
- Search engine slide is 2nd
- Incorporate search engine icons into SE dropdown
- Brave Shields is 3rd
- Antifraud referral confirmation checkbox is 4th
- Brave Rewards is 5th and last
- Update search engine slide graphic
- Update Brave Rewards slide graphic with Lottie file

![image](https://user-images.githubusercontent.com/2388823/98983607-df6c9000-24d5-11eb-8920-3ac2ac6d7515.png)

## Assets
Figma: https://www.figma.com/file/MFHpcXJMg2RUQpUJMAZZ4R/?node-id=1159%3A24270

Brave Rewards slide Lottie file:
preview: https://lottiefiles.com/share/6RkxWM
json file: https://assets3.lottiefiles.com/packages/lf20_6RkxWM.json
implementation info: http://airbnb.io/lottie/#/web

**Comment by karenkliu** [comment] 2020-09-25 22:44
This is a dupe of this issue: https://github.com/brave/security/issues/216

**Comment by kjozwiak** [comment] 2020-09-26 02:26
We'll need a user facing issue that refers to https://github.com/brave/security/issues/216 so it doesn't get lost when QA starts running through verifications. Unless we're planning on moving the work that's being done in https://github.com/brave/security/issues/216 into https://github.com/brave/brave-browser when ready.

**Comment by karenkliu** [comment] 2020-11-13 22:56
Closing this in favor of these issues:
- MacOS first launch: https://github.com/brave/brave-browser/issues/12679
- Windows first launch: https://github.com/brave/brave-browser/issues/12680

**Closed by karenkliu** 2020-11-13 22:56 UTC
Labels: OS/Desktop, design/needs-mock-up, onboarding, priority/P3
