### ISSUE TITLE
Brave has closed!

### ISSUE THREAD

**Issue by jhauradou** [brave/brave-browser#6130] opened 2019-09-23 15:25 UTC
## Description 

   1. I left Brave browser opened with just one tab on www.udemy.com website;
   2. It was running a video, but it was paused,  I left this way for about 45 minutes;
   3. I came back to my computer and pressed play button, but nothing happens
   4. I pressed Reload button;
   5. Brave web browser has closed.

## Actual result:
Brave Browser has closed.
## Expected result:
Brave browser keep open it!

## Reproduces how often: 
It was the first time that it happens. 

## Brave version (brave://version info)
Brave is up to date
Version 0.68.139 Chromium: 77.0.3865.90 (Official Build) (64-bit)
OS: Windows 8.1 Pro

**Comment by ortsaCniveK** [comment] 2019-09-23 18:27
I'm also having similar issues, however, it's random crashes that are happening.  No error messages and I'm able to restore pages, but it's intermittent.  May also be due to Windows, but I'll keep note of my info here.

Version 0.68.139 Chromium: 77.0.3865.90 (Official Build) (64-bit)

Windows 10 Version 1903 Build 18980.1

**Comment by ortsaCniveK** [comment] 2019-09-23 18:28
I'm also having similar issues, however, it's random crashes that are happening.  No error messages and I'm able to restore pages, but it's intermittent.  May also be due to Windows, but I'll keep note of my info here.

Version 0.68.139 Chromium: 77.0.3865.90 (Official Build) (64-bit)

Windows 10 Version 1903 Build 18980.1

**Comment by bsclifton** [comment] 2019-09-24 10:41
We have had the root cause for some crashes found and fixed recently - @jhauradou @ortsaCniveK  would you be able to grab the latest and see if the issue still happens?

If so- I'm curious if either of you has sync enabled. If so, a work-around can be to leave your sync chain and create a new one (and add other devices to this new chain)

Let us know 😄

**Comment by ortsaCniveK** [comment] 2019-09-24 16:37
That seems to have fixed the issue for me!

**Comment by bsclifton** [comment] 2019-09-25 01:10
Sync related problems tracked here:
https://github.com/brave/brave-browser/issues/6091

I believe we have a fix for this issue; build is on the way. This should be resolved with:
0.68.x https://github.com/brave/brave-core/pull/3523
0.69.x https://github.com/brave/brave-core/pull/3524
0.70.x https://github.com/brave/brave-core/pull/3525

**Closed by bsclifton** 2019-09-25 01:10 UTC
Labels: crash, priority/P1

**Comment by bsclifton** [comment] 2019-09-25 01:12
Several +1's from https://www.reddit.com/r/brave_browser/comments/d8lkgj/brave_keeps_crashing_version_068140_windows_10/
