### ISSUE TITLE
brave-translate does not handle Chinese

### ISSUE THREAD

**Issue by cc19264997** [brave/brave-browser#25327] opened 2022-09-11 05:39 UTC
Hello, why did the browser's translation function not respond? I am a Chinese user, and I couldn't translate when I opened VPN! what should I do?

I downloaded the Crx translated by Google, but I still can't translate the webpage content!

I hope you can answer it for me and thank you again!

**Comment by diracdeltas** [comment] 2022-09-11 16:41
you may need to restart, see https://github.com/brave/brave-browser/issues/25170#issuecomment-1242154933

**Comment by atuchin-m** [comment] 2022-09-12 08:03
@cc19264997 to use the build-in translation engine please remove or disable Google Translate extension.
If you have the extension it still be used instead of the build-in implementation.

**Comment by cc19264997** [comment] 2022-09-13 01:16
> you may need to restart, see [#25170 (comment)](https://github.com/brave/brave-browser/issues/25170#issuecomment-1242154933)


Hello, but he still can't translate Chinese!

**Comment by atuchin-m** [comment] 2022-09-13 16:01
Chinese will be supported in here: https://github.com/brave/brave-browser/issues/24303

**Comment by bsclifton** [comment] 2022-09-15 22:07
Closing as a duplicate of https://github.com/brave/brave-browser/issues/24303 - @cc19264997 you can subscribe to that issue for updates 😄 Thanks!

**Closed by bsclifton** 2022-09-15 22:07 UTC
Labels: l10n, OS/Desktop, brave-translate
