### ISSUE TITLE
Wrong page is shown in rewards panel when on YT

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1660] opened 2018-10-17 17:42 UTC
## Steps to Reproduce

1. Clean profile
2. Enable rewards and claim grant
3. Open google.com in new tab and wait till `Send a tip` is shown in rewards panel (reload if needed)
4. Open youtube.com in another tab and wait till `Send a tip` is shown in rewards panel
5. Switch to google.com tab and show rewards panel
6. Switch to youtube.com tab and open a video
7. Quickly switch back to google tab and wait for youtube page to load
8. Switch to youtube tab and open rewards panel

## Actual result:

Wrong page(google.com instead of youtube.com) is shown in rewards panel. 
The page shown in the rewards panel will be used for tipping(google.com instead of youtube.com) 
Reloading the page will not fix the issue.
![image](https://user-images.githubusercontent.com/34715963/47105024-24646080-d243-11e8-8663-aec6e01e8004.png)

Recording starts at step 5.
![rewards_fail](https://user-images.githubusercontent.com/34715963/47105168-760ceb00-d243-11e8-906d-3db473998d7a.gif)

## Expected result:
The proper page is shown in rewards panel
![image](https://user-images.githubusercontent.com/34715963/47105357-f9c6d780-d243-11e8-8671-b823e720512e.png)

## Reproduces how often: 

always

## Brave version (brave://version info)

Verification passed on

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Windows 7 x64

cc @kjozwiak @LaurenWags @srirambv @GeetaSarvadnya @mandar-brave @NejcZdovc

**Comment by LaurenWags** [comment] 2018-10-17 17:50
Reproduced on macOS

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

![screen shot 2018-10-17 at 1 49 49 pm](https://user-images.githubusercontent.com/28145373/47106037-93c25c00-d213-11e8-8956-876a9ea2e9d4.png)

**Comment by NejcZdovc** [comment] 2018-10-17 17:51
@LaurenWags @btlechowski this will be fixed with this one https://github.com/brave/brave-browser/issues/1517

**Comment by kjozwiak** [comment] 2018-10-17 20:20
As per @NejcZdovc, this will be fixed by #1517 which is inside the `1.x Backlog`. Moved this issue into the same milestone.

**Comment by NejcZdovc** [comment] 2018-10-18 06:45
closing as dupe, because it has the same problem then https://github.com/brave/brave-browser/issues/1517

**Comment by btlechowski** [comment] 2018-10-23 03:45
Reproduced in 0.55.20 on Ubuntu 17.10. https://github.com/brave/brave-browser/issues/1517 did not fix the issue.

Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux



![image](https://user-images.githubusercontent.com/34715963/47334252-8e876600-d686-11e8-9a95-dde1f67e52a3.png)

**Comment by kjozwiak** [comment] 2018-10-23 04:31
Here's STR that I've been using to reproduce the above:

* launch `0.55.20 Chromium: 70.0.3538.67` using a brand new profile
* visit https://www.youtube.com/channel/UCCatR7nWbYrkVXdxXb4cGXw
* click on the `BAT` icon in the URL and click on `Join Rewards`
* once the wallet has been created, open a new tab and load brave.com
* click on the BAT icon in the URL and you should see brave.com
* switch back to the YT tab (Datadash) and click on the `BAT` icon in the URL

You'll get the following:
 
<img width="999" alt="screen shot 2018-10-23 at 12 31 04 am" src="https://user-images.githubusercontent.com/2602313/47335807-f45df880-d65a-11e8-9b19-67a83ec789a6.png">

**Comment by NejcZdovc** [comment] 2018-10-23 10:50
So I did a fix where when we switch tabs we don't preserve tabs. So now the expected behaviour is that when you switch back to https://www.youtube.com/channel/UCCatR7nWbYrkVXdxXb4cGXw tab panel should show wallet summary. This will be fully fixed when we add support for media publishers in https://github.com/brave/brave-browser/issues/1282

**Closed** 2018-10-24 15:01 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/rewards

**Comment by GeetaSarvadnya** [comment] 2018-10-26 10:43
Tried above 2 STR's, issue is fixed and working fine on:


Brave | 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows
