### ISSUE TITLE
[macOS] Latest Update Sometimes Crashes When Switching Apps

### ISSUE THREAD

**Issue by Haravikk** [brave/brave-browser#36407] opened 2024-02-27 21:57 UTC
## Description 
I'm having a really hard time figure out a consistent reproduction for this issue, but ever since the latest update (which seems to include changes to the video player) I've been finding that Brave crashes somewhat frequently whenever a video is left open in the active tab when switching to another application on macOS.

## Steps to Reproduce
As I say, I can't find a properly consistent reproduction for this crash, but this is what seems to be in common:

   1.  Open a video on YouTube.
   2. Watch it in a mixture of fullscreen and picture-in-picture (to do the latter on YouTube you need to right-click on the video a few times till you get the correct contextual menu).
   3. Return the video to normal (neither fullscreen or PiP)
   4. Switch to another program

## Actual result:
Sometimes (but not always), Brave will silently crash, producing no crash-log of any kind, though it does recognise it was closed improperly on the next launch.

## Expected result:
Brave should not crash.

## Reproduces how often: 
Intermittent.

I can't figure out if the issue is some exact combination of switching between normal/fullscreen/PiP or if it's time related or what. All I know it's new to the latest release version, and seems to be video related (Brave windows without any video haven't given me any problems) and something to do with switching away from Brave (as I can switch as much as I want without video content).

Could all be red herrings of course, as no crash log is being generated that I can find.

## Brave version (brave://version info)
1.63.162 Chromium: 122.0.6261.69 (Official Build) (x86_64) 

## Version/Channel Information:
Current release

## Miscellaneous Information:
I'd like to take this opportunity to push again for issue #17492 (use native macOS Fullscreen/PiP for video) as while Brave's ability to playback video content is good, the player itself is a bit of a hindrance on macOS (doesn't fullscreen properly, doesn't do PiP over other apps etc.). But in the short term it would be best to fix these crashes first.

**Comment by Haravikk** [comment] 2024-03-05 23:35
Just wanted to update but I'm less sure about how tied to video playback this issue is; I definitely seem to notice it more when I've been playing videos (and I do a lot of that so it's hard to unpick) but I've also noticed this happening a couple of times when I haven't played video in a while.

It also doesn't seem to matter if video is actively playing or not as I originally thought, as several times now videos have cut off.

So I think the core of the problem seems to be the application switching/loss of focus rather than the video playback. But it's still hard to find a consistent reproduction to this; sometimes switching to Desktop does it, other times it's switching to another Fullscreen app, so any kind of switching away from Brave seems to be able to trigger this.

It's also strange that there's no crash-log being generated as far as I can see; definitely isn't being picked up by the normal macOS crash logging (message on re-opening the app) and I don't see any log files anywhere else.

Does anyone know if there's some other way I can get a log from Brave that might give a better clue as to what's happening?  It clearly knows it wasn't shutdown properly as it asks me to restore my tabs when I re-open, but beyond that I can't seem to get any more information.

**Comment by bsclifton** [comment] 2024-03-05 23:44
@Haravikk do you have crash report IDs on brave://crashes that you can share? If they haven't been uploaded, you can click `Send report` and restart the browser. It will then show an ID you can share here

That should help us narrow down the issue. Thanks for the verbose description above too! 😄

**Comment by Haravikk** [comment] 2024-03-05 23:55
Sorry, I didn't know about that page! Here's all the crash IDs that seem to have been recorded from my current system, I have another but the hardware/OS and nearly identical so I expect they'll be about the same.

IDs are from newest to oldest, and seem to go back to the 23rd of February, so that might put the origin of the issue before v1.63.162, as I feel like there was at least one update before I reported the problem so it may already have existed in v1.63.161.

````

e41c1500-0f95-950b-0000-000000000000
38091300-0f95-950b-0000-000000000000
fcc01200-0f95-950b-0000-000000000000
ae261100-0f95-950b-0000-000000000000
8e150e00-0f95-950b-0000-000000000000
ebda0a00-0f95-950b-0000-000000000000
fd1c0a00-0f95-950b-0000-000000000000
8fa80700-0f95-950b-0000-000000000000
bb430700-0f95-950b-0000-000000000000
0a670300-0f95-950b-0000-000000000000
14d20200-0f95-950b-0000-000000000000
c0360200-0f95-950b-0000-000000000000
71f60000-0f95-950b-0000-000000000000
8b181100-b651-8c0b-0000-000000000000
f7251000-b651-8c0b-0000-000000000000
759f0d00-b651-8c0b-0000-000000000000
38770500-b651-8c0b-0000-000000000000
6baa0400-b651-8c0b-0000-000000000000

````

Let me know if you want the crash IDs from the other system as well.

**Comment by bsclifton** [comment] 2024-03-06 04:18
Backtrace
https://brave.sp.backtrace.io/p/brave/debug?time=month&filters=JTVCJTVCJTIyX3J4aWQlMjIlMkMlMjJlcXVhbCUyMiUyQyUyMjhiMTgxMTAwLWI2NTEtOGMwYi0wMDAwLTAwMDAwMDAwMDAwMCUyMiU1RCUyQyU1QiUyMl9kZWxldGVkJTIyJTJDJTIyZXF1YWwlMjIlMkMlMjIwJTIyJTVEJTVE&debug=(%226aef7ab%22,0,0)


Callstack
```
[ 00 ] VideoOverlayWindowViews::GetWorkAreaForWindow() const ( video_overlay_window_views.cc:683 )
[ 01 ] VideoOverlayWindowViews::OnDisplayMetricsChanged(display::Display const&, unsigned int) ( video_overlay_window_views.cc:656 )
[ 02 ] display::DisplayChangeNotifier::NotifyDisplaysChanged(std::__Cr::vector<display::Display, std::__Cr::allocator<display::Display>> const&, std::__Cr::vector<display::Display, std::__Cr::allocator<display::Display>> const&) ( display_change_notifier.cc:80 )
[ 03 ] display::(anonymous namespace)::ScreenMac::OnNSScreensMayHaveChanged() ( screen_mac.mm:489 )
[ 04 ] -[__NSObserver _doit:]
[ 05 ] __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
[ 06 ] ___CFXRegistrationPost1_block_invoke
[ 07 ] _CFXRegistrationPost1
[ 08 ] ___CFXNotificationPost_block_invoke
[ 09 ] -[_CFXNotificationRegistrar find:object:observer:enumerator:]
[ 10 ] _CFXNotificationPost
[ 11 ] -[NSNotificationCenter postNotificationName:object:userInfo:]
[ 12 ] _NSApplicationPerformScreenInvalidationReactions
[ 13 ] ___NSMainRunLoopPerformBlockInModes_block_invoke
[ 14 ] __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
[ 15 ] __CFRunLoopDoBlocks
[ 16 ] __CFRunLoopRun
[ 17 ] CFRunLoopRunSpecific
[ 18 ] RunCurrentEventLoopInMode
[ 19 ] ReceiveNextEventCommon
[ 20 ] _BlockUntilNextEventMatchingListInModeWithFilter
[ 21 ] _DPSNextEvent
[ 22 ] -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
[ 23 ] __71-[BrowserCrApplication nextEventMatchingMask:untilDate:inMode:dequeue:]_block_invoke ( chrome_browser_application_mac.mm:244 )
[ 24 ] base::apple::CallWithEHFrame(void () block_pointer)
[ 25 ] -[BrowserCrApplication nextEventMatchingMask:untilDate:inMode:dequeue:] ( chrome_browser_application_mac.mm:243 )
[ 26 ] -[NSApplication run]
[ 27 ] base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*) ( message_pump_apple.mm:805 )
[ 28 ] base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) ( message_pump_apple.mm:156 )
[ 29 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ( thread_controller_with_message_pump_impl.cc:646 )
[ 30 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ( thread_controller_with_message_pump_impl.cc:0 )
[ 31 ] base::RunLoop::Run(base::Location const&) ( run_loop.cc:134 )
[ 32 ] content::BrowserMainLoop::RunMainMessageLoop() ( browser_main_loop.cc:1094 )
[ 33 ] content::BrowserMainRunnerImpl::Run() ( browser_main_runner_impl.cc:159 )
[ 34 ] content::BrowserMain(content::MainFunctionParams) ( browser_main.cc:34 )
[ 35 ] content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams, bool) ( content_main_runner_impl.cc:708 )
[ 36 ] content::ContentMainRunnerImpl::Run() ( content_main_runner_impl.cc:1140 )
[ 37 ] content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) ( content_main.cc:335 )
[ 38 ] content::ContentMain(content::ContentMainParams) ( content_main.cc:348 )
[ 39 ] ChromeMain ( chrome_main.cc:194 )
[ 40 ] main ( chrome_exe_main_mac.cc:216 )
[ 41 ] start
```

**Comment by bsclifton** [comment] 2024-03-06 04:45
@Haravikk I believe we have a fix by @sangwoo108 with https://github.com/brave/brave-core/pull/22468!

This should be a duplicate of issue https://github.com/brave/brave-browser/issues/35528. I'll close this one - but stay tuned for the fix

Thanks again for reporting!

**Closed by bsclifton** 2024-03-06 04:45 UTC
Labels: crash, OS/macOS, priority/P2, OS/Desktop
