### ISSUE TITLE
Claiming reward cannot get passed the captcha stage

### ISSUE THREAD

**Issue by valluminarias** [brave/brave-browser#17476] opened 2021-08-13 04:22 UTC
## Description 

Tried claiming the Add reward many times already but I stil can't get passed the captcha stage. I tried like the whole day.

## Steps to Reproduce

   1.  Open brave browser
   2.  Go to reward section via the Learn more link in the home page reward widget
   3.  Claim the reward
   4.  It will start the captcha

## Actual result:

![image](https://user-images.githubusercontent.com/8232426/129304042-13283955-aa30-499b-8141-48d1267cbb15.png)

## Expected result:
Expected to pass the captcha since I followed all the instruction given.

## Reproduces how often: 

Many times already. Loss track of it.

## Brave version (brave://version info)

1.28.105 Chromium: 92.0.4515.131 (Official Build) (64-bit)
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | Windows 10 OS Version 2009 (Build 19043.1165)

**Comment by bsclifton** [comment] 2021-08-13 18:59
cc: @emerick

**Comment by Miyayes** [comment] 2021-08-14 17:43
The most common reason is that your screen/display scaling is distorting the pixels in some way. We often ask users to try checking their display scaling settings and moving it back to 100% first. And then trying some different magnifications. Hopefully you can find a scaling % that works for you. @valluminarias

**Comment by zenparsing** [comment] 2021-08-18 16:38
@emerick Let's investigate the Windows scaling issues when we bring in the panel 2.0 work.

**Comment by GeetaSarvadnya** [comment] 2021-09-15 11:10
The issue is Reproducible with a new captcha on the `1.31.41` nightly build. The issue arises with 125% and 150% resolutions, works fine with 100% resolution
![Captcha test on Nightly](https://user-images.githubusercontent.com/38657976/133422943-1430f23d-7283-41f8-8781-f451c3a0c12d.gif)

**Closed** 2021-09-16 17:01 UTC
Labels: feature/rewards, priority/P4, QA/Yes, release-notes/include, OS/Desktop

**Comment by GeetaSarvadnya** [comment] 2021-09-17 12:29
Great Job! @emerick 

Verification passed on

```
Brave | 1.31.50 Chromium: 94.0.4606.50 (Official Build) nightly (64-bit)
-- | --
Revision | 0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}
OS | Windows 10 Version 21H1 (Build 19043.1165)
```
- Verified the issue against the `Display resolution 1920 x 1080` with 125%, 150%, 175% and 100% app resolution

**_125 % resolution - Captch test_**
![125% Resolution-Captcha test](https://user-images.githubusercontent.com/38657976/133781731-e51f45ea-191c-43cb-9a69-bc0dad49d36b.gif)

**_150 % resolution - Captch test_**
![150% Resolution-Captcha test](https://user-images.githubusercontent.com/38657976/133781844-7b4c865b-341b-403d-84dc-78e1b8c906ae.gif)

**_175 % resolution - Captch test_**
![175% Resolution-Captcha test](https://user-images.githubusercontent.com/38657976/133781900-33f75e5a-7549-463e-901a-60c9a9e8d143.gif)

**_100 % resolution - Captch test_**
![100% Resolution-Captcha test](https://user-images.githubusercontent.com/38657976/133781946-78b1446d-4e52-454a-b804-26b9d045f4d9.gif)
