### ISSUE TITLE
Radio button not visible on latest dev/beta version

### ISSUE THREAD

**Issue by sundarms** [brave/brave-browser#1355] opened 2018-09-30 06:39 UTC
## Description 
Radio button not visible on all sites

## Steps to Reproduce

   1.  Just visit https://www.sublimetext.com/buy?v=3.0
   2.  Following text  "This license is for me
 The license is for the business:" have a radio button but not visible on brave
   3. 

## Reproduces how often: 

Always on most of the sites
### Reproducible on current release:

YES

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Brave | 0.56.1 Chromium: 70.0.3538.22 (Official Build) dev (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X
JavaScript | V8 7.0.276.15
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.22 Safari/537.36
Command Line | /Applications/Brave Browser Dev.app/Contents/MacOS/Brave Browser Dev --enable-tab-audio-muting --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer --flag-switches-begin --flag-switches-end

**Comment by srirambv** [comment] 2018-09-30 13:32
Dupe of #1160. Workaround for now is to disable h/w acceleration from settings (see https://github.com/brave/brave-browser/issues/1160#issuecomment-423028344)

**Closed by srirambv** 2018-09-30 13:32 UTC
