### ISSUE TITLE
Unable to toggle off/on for `Customize sync` settings when Sync is enabled

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#41495] opened 2024-10-08 21:38 UTC
### Description

After enabling `Customize sync` setting in the Sync page, not able to toggle `on`/`off` for `Sync data` toggles.  This is not CR 130 issue as I can reproduce in `1.72.59 (Chromium 129.0.6668.89)`.  However I couldn't reproduce in Current release `1.70.123` or `1.71.104 Chromium: 129.0.6668.89`. 

### Steps to reproduce

1. Install 1.72.68
2. launch Brave
3. Add another profile via hamburger menu
4. enable Sync via hamburger menu
5. open second profile and join the sync
6. enable `Customize sync` setting
7. toggle `off/on` for any data setting (eg.`Theme`)

### Actual result

Not able to toggle `on`

https://github.com/user-attachments/assets/73c7c297-f2e8-41d4-b4e7-dd66a139a361

### Expected result

![Image](https://github.com/user-attachments/assets/af42f075-a248-4935-9a45-e1730eb0d71e)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.72.68 Chromium: 130.0.6723.31 (Official Build) nightly (64-bit)
-- | --
Revision | f04ca2afa25cd46e348d74922bb587b88d56cba6
OS | Windows 11 Version 23H2 (Build 22631.4249)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@rebron 
cc: @brave/qa-team

**Comment by bsclifton** [comment] 2024-10-11 18:04
Closing as duplicate of https://github.com/brave/brave-browser/issues/41493

**Closed by bsclifton** 2024-10-11 18:04 UTC
Labels: bug, feature/sync, QA/Yes, QA/Test-Plan-Specified, regression, OS/Desktop
