### ISSUE TITLE
The reader mode icon disappears after toggling on

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#18243] opened 2021-09-21 07:47 UTC
## Description 

The reader mode icon immediately disappears after toggling on reader mode. Switching tabs or reloading the page via `Shift` + `Reload` brings the icon back.

## Steps to Reproduce

   1. Ensure `Speedreader` is disabled via `brave://settings/appearance`.
   2. Open `https://brave.com/blog` or `https://edition.cnn.com/2021/09/20/americas/canada-election-results-trudeau-o-toole-intl/index.html`.
   3. Click on the reader mode icon in the address bar.

## Actual result:

The reader mode icon disappears.

## Expected result:
The reader mode icon shouldn't disappear.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

<html>
<body>

Brave | 1.32.4 Chromium: 94.0.4606.50 (Official Build) nightly (64-bit)
-- | --
Revision | 0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}
OS | Windows 7 Service Pack 1 (Build 7601)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@stephendonner @keur

**Comment by bsclifton** [comment] 2021-09-21 07:57
@Tonev is this a duplicate of https://github.com/brave/brave-browser/issues/18234?

**Comment by Tonev** [comment] 2021-09-21 08:01
@bsclifton 

I think `Reader mode` and `Speedreader` are two different features. I tested the bug, filled by @stephendonner, and the behavior there is a bit different to what I'm describing in this bug report. I just included video recordings in the other Github ticket, please take a look at them, so we can determine whether we're talking about the same bug (duplicate) :+1:

**Comment by Tonev** [comment] 2021-09-21 08:30
@bsclifton 

- `Reader mode` (this bug report)

https://user-images.githubusercontent.com/20608253/134138108-832bff55-a68d-4492-afc5-757fa503d807.mp4

- `Speedreader` (@stephendonner's bug report)

https://user-images.githubusercontent.com/20608253/134138181-75b9ec97-1362-4bbf-9fb6-4e2853549885.mp4

**Comment by iefremov** [comment] 2021-11-02 14:47
duplicate https://github.com/brave/brave-browser/issues/18234

**Comment by Tonev** [comment] 2021-11-03 07:31
@iefremov 

Are you sure it's a duplicate? After @bsclifton asked if this was a duplicate, I provided video recordings about my report and @stephendonner's report. 

I also thought this wasn't a duplicate after @bsclifton didn't close it as such, and @stephendonner and @rebron assigned/moved the report.

**Comment by iefremov** [comment] 2021-11-03 11:05
my bad @Tonev , I've completely missed that comments - reopening. FWIW, i wasn't able to reproduce both issues on Beta

**Comment by Tonev** [comment] 2021-11-03 12:40
@iefremov 

I was able to easily reproduce the issue on `Release`, `Beta`, and `Nightly`.

1. Ensured `Speedreader` was disabled via `brave://settings/appearance`.
2. Opened `https://brave.com/blog/`.
3. Clicked on the `Reader mode` icon in the address bar.
4. Ensured the `Reader mode` icon disappeared.

Reloading the page brought back the `Reader mode` icon on all `Release`, `Beta`, and `Nightly` but then encountered the following bug: https://github.com/brave/brave-browser/issues/18242.

<html>
<body>


Brave | 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | Windows 7 Service Pack 1 (Build 7601)


</body>
</html>

<html>
<body>


Brave | 1.32.88 Chromium: 95.0.4638.69 (Official Build) beta (64-bit)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | Windows 7 Service Pack 1 (Build 7601)


</body>
</html>

<html>
<body>


Brave | 1.33.52 Chromium: 95.0.4638.69 (Official Build) nightly (64-bit)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | Windows 7 Service Pack 1 (Build 7601)


</body>
</html>

I will update the report description since this bug is reproducible on all `Release`, `Beta`, and `Nightly` nowadays.

**Closed** 2022-03-23 10:47 UTC
Labels: bug, QA/Yes, release-notes/include, QA/Test-Plan-Specified, OS/Desktop

**Comment by stephendonner** [comment] 2022-03-30 22:18
Verified `PASSED` using 

Brave | 1.38.74 Chromium: 100.0.4896.60 (Official Build) beta (x86_64)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | macOS Version 11.6.5 (Build 20G527)

Used the testplan from https://github.com/brave/brave-browser/issues/18243#issue-1002004352

Confirmed that the `Speedreader` icon not only persists after initial click (to enable the feature), but exists as a working `On`/`Off` toggle of the reader mode.

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="1312" alt="Screen Shot 2022-03-30 at 3 14 04 PM" src="https://user-images.githubusercontent.com/387249/160940223-aface0b8-4551-4237-abe7-4100ab73c8a8.png"> | <img width="1312" alt="Screen Shot 2022-03-30 at 3 14 11 PM" src="https://user-images.githubusercontent.com/387249/160940235-e7657a45-cdfe-4066-ab0b-05c0f715b4ea.png"> | <img width="1312" alt="Screen Shot 2022-03-30 at 3 14 23 PM" src="https://user-images.githubusercontent.com/387249/160940237-0b7a38c1-2d6f-4447-bd13-e890177c2249.png"> | <img width="1312" alt="Screen Shot 2022-03-30 at 3 14 26 PM" src="https://user-images.githubusercontent.com/387249/160940241-e8c25ce7-900b-4dea-9a1e-fce3295b7e8d.png"> | <img width="1312" alt="Screen Shot 2022-03-30 at 3 14 38 PM" src="https://user-images.githubusercontent.com/387249/160940244-d869d714-3ec4-411a-bd7d-86fb3fe1b0eb.png">

**Comment by MadhaviSeelam** [comment] 2022-04-04 22:27
Brave | 1.38.78 Chromium: 100.0.4896.60 (Official Build) beta (64-bit)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | Windows 11 Version 21H2 (Build 22000.593)

- Install 1.38.78
- Launch Brave
- Disabled Speedreader in brave://settings/appearance.
- Open https://edition.cnn.com/travel/article/den-tokyo-asia-best-restaurant-2022-intl-hnk/index.html
- Click on the Speedreader mode icon in the address bar.
- Verified that the Speedreader icon persists after initial click to enable the feature and the reader mode icon do not disappear.
- Verified the existing functionality of Speedreader with On/Off toggle and is working as expected.

ex1|ex2|ex3|ex4|ex5
---|---|---|---|---
<img width="950" alt="Speedreader disabled" src="https://user-images.githubusercontent.com/98358127/161640639-12f8ee56-e156-4bb6-b84a-2bfd5b8a28c4.png">|<img width="955" alt="Speed reader popup" src="https://user-images.githubusercontent.com/98358127/161640721-aff52831-b09b-4539-a4b0-96b6853079d2.png">|<img width="950" alt="Speed reader icon in the URL" src="https://user-images.githubusercontent.com/98358127/161640496-fd4e4edd-beeb-47ae-9330-d1b2a68b51ca.png">|<img width="947" alt="Turn on speed reader " src="https://user-images.githubusercontent.com/98358127/161640761-5c158bba-115a-4992-8d19-55e54437ddff.png">|<img width="952" alt="Turn off speed reader " src="https://user-images.githubusercontent.com/98358127/161641578-070e2a76-d506-4d0c-91fd-f8e0f59c3054.png">
