### ISSUE TITLE
Brave Ads are not displayed while viewing a fullscreen video

### ISSUE THREAD

**Issue by hudson-newey** [brave/brave-browser#14337] opened 2021-02-24 11:41 UTC
## Description 
When watching Youtube or any other fullscreen videos (such as twitch), the user is not shown any Brave Reward alerts/notifications. This may be intentional (as to not irritate the user). Although, many users (including myself) would like to see this as a toggleable option (through the Brave Reward settings panel).

## Steps to Reproduce
   1. Enable Brave Rewards
   2. Go to Youtube
   3. No brave reward alerts will show while in fullscreen

## Actual result:
No Brave Reward alerts are shown while in Youtube's (and other video sites) fullscreen mode

## Expected result:
Give the user the opportunity to enable brave rewards while watching videos in fullscreen mode

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 1.20.108 Chromium: 88.0.4324.182 (Official Build) (64-bit)
-- | --
Revision | 73ee5087001dcef33047c4ed650471b225dd8caf-refs/branch-heads/4324@{#2202}
OS | Windows 10 OS Version 2004 (Build 19041.746)

## Version/Channel Information:

- Can you reproduce this issue with the current release? **Yes**
- Can you reproduce this issue with the beta channel?  **Haven't tested**
- Can you reproduce this issue with the nightly channel? **Haven't tested**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **Haven't tested**
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Does not have required features

**Comment by rebron** [comment] 2021-03-01 17:29
cc: @jsecretan, @tmancey 
This is working as expected. 
Not sure if this would be a popular setting that other users would want to turn on. It would also be default off obviously.

**Comment by tmancey** [comment] 2021-03-01 17:31
Based upon feedback from users this would be a good option and as you say with the default off.

**Comment by tmancey** [comment] 2021-03-16 12:59
Closing as duplicate of https://github.com/brave/brave-browser/issues/9264

**Closed by tmancey** 2021-03-16 12:59 UTC
Labels: closed/duplicate, enhancement, feature-request, feature/ads, OS/Desktop
