### ISSUE TITLE
Many input buttons no longer responsive in 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#1074] opened 2018-09-10 03:13 UTC
**Have you searched for similar issues?** 
 Yes
## Description 
Many input buttons have become unresponsive in Brave Developer release (v 0.55.2 Chromium: 70.0.3528.4 (Official Build) dev (64-bit). This issue was first reported in [Community](https://community.brave.com/t/bug-website-imgur-com/31754/3), and it seems the user (or someone on his behalf) has opened an issue here in Github (#1065). I wanted to formalize the issue, but for consistency, here is the text from the original issue logged:
Developer Channel v0.55.2 , with Windows 10 x64

> Hello
> 
> 1/ go to the imgur.com website and login (here identified with a Twitter account)
> 2/ the window does not appear and i cannot to select and add an image when I click on this button:
> 
> https://i.imgur.com/XgkxNZf.png
> 
> 3/ I disabled all blockages (the lion's head is grayed out) and allowed popup windows to be displayed
> 4/ I disconnected my account imgur and I identified myself again
> 5/when I click on this button, the window still does not appear.
> 
> Normally, it is a Windows Explorer window that should be displayed
> 
> same problem to add a file in Google Drive
> (for download no problem)
> 
> If you want additional information, do not hesitate.

I would like to add that this can reproduced on Facebook, community.brave.com, and many Google suite applications. Even when attempting to write this issue, I had to copy/paste the images from my drive into Github, clicking the "Select them" link at the bottom of the page wouldn't open the browsing window.
## Steps to Reproduce

   1.  Visit https://imgur.com
   2. Click "New Post" in top left
   3.  When option to drag an image, browse computer or copy/paste URL loadds, click "Browse"

## Actual result:
Nothing happens. No window to browse files appears, no error message. Shields on/off both produce the issue:
![imgurbutton](https://user-images.githubusercontent.com/3299098/45274300-a951a280-b46b-11e8-9bd9-f681c097920f.gif)

## Expected result:
Window to browse files/folders for upload should appear
![imgruchrome](https://user-images.githubusercontent.com/3299098/45274344-f3d31f00-b46b-11e8-863f-005bb44183a8.gif)

## Reproduces how often: 
Always

## Brave version (about:brave info) 
Brave Developer release (v 0.55.2 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
Windows 10

### Reproducible on current release:
No, input buttons function without issue on browser-laptop

### Website problems only:  
**- Does the issue resolve itself when disabling Brave Shields?**
No
**- Is the issue reproducible on the latest version of Chrome?** 
No

### Additional Information
Just another quick example of the behavior on a different website:
![commubutton](https://user-images.githubusercontent.com/3299098/45274480-7fe54680-b46c-11e8-8c74-19df5658ea6c.gif)

**Comment by srirambv** [comment] 2018-09-10 12:12
Cant reproduce on Windows
![1074](https://user-images.githubusercontent.com/17010094/45296798-2cf1aa80-b4d1-11e8-8ef0-fbc4f0b0e785.gif)

**Comment by franco27** [comment] 2018-09-10 13:52
hello
I disabled all extensions. Now it works properly for imgur and Drive.

I found the extension causing this problem: "ImTranslator: Translator, Dictionary, Voice "
https://chrome.google.com/webstore/detail/imtranslator-translator-d/noaijdpnepcgjemiklgfkcfbkokogabh

**Comment by bsclifton** [comment] 2018-09-10 16:48
@franco27 great! Thanks for the update 😄 I'll go ahead and close this issue out

**Closed by bsclifton** 2018-09-10 16:48 UTC
Labels: bug, webcompat

**Comment by franco27** [comment] 2018-09-12 11:31
I would like to write more information: with Vivaldi, the ImTranslator extension is installed and enabled and I don't have this problem.
