### ISSUE TITLE
Crypto Wallet - not consistent with other wallets when recovering wallet

### ISSUE THREAD

**Issue by andwan0** [brave/brave-browser#14148] opened 2021-02-13 23:22 UTC
## Description 
The ETH address is WRONG when restoring from a 24-word phrase generated from another wallet, ie. MEWWallet, or Trust Wallet, or Maiar (Elrond) Wallet or MetaMask.

## Steps to Reproduce

   1. Create a wallet using Maiar. Take note of the ETH public address & 24-word recovery phrase.
   2. Open MEWWallet, import 24-word recovery phrase. The ETH public address generated is same from Maiar.
   3. Open MetaMask, import 24-word recovery phrase. The ETH public address generated is same from Maiar.
   4. Open Trust Wallet, import 24-word recovery phrase. The ETH public address generated is same from Maiar.
   5. Open Brave Browser, import 24-word recovery phrase. The ETH public address generated is NOT same from Maiar.

## Actual result:
The ETH address is not the same, thus cannot use existing wallet from another app.

## Expected result:
If MEWWallet, MetaMask, Trust Wallet, Maiar can recreate the same ETH address from the 24-word recovery phrase, we expect Brave Browser to do the same.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Windows 10 OS Version 2004 (Build 19041.804)
JavaScript | V8 8.8.278.15
User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36
Command Line | "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,LegacyTLSEnforced,AutoupgradeMixedContent,WinrtGeolocationImplementation,SafetyTip,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity --disable-features=AutofillEnableAccountWalletStorage,AutofillServerCommunication,TextFragmentAnchor,DirectSockets,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,TabHoverCards,SafeBrowsingEnhancedProtection,SignedExchangeSubresourcePrefetch,PasswordCheck,NetworkTimeServiceQuerying,LangClientHintHeader,PrivacySettingsRedesign,NotificationTriggers,WebOTP,IdleDetection --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\Owner\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | 4b6d01b8-d33012a0

## Version/Channel Information:
n/a

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
n/a

**Comment by diracdeltas** [comment] 2021-02-17 07:59
this is a duplicate of #13245 and will be fixed in an upcoming release

**Closed by diracdeltas** 2021-02-17 07:59 UTC
Labels: OS/Desktop
