### ISSUE TITLE
Brave VPN connection failed initially with `Failed to write the VPN config` error in the VPN panel and then connected successfully with intermittent failures

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#30598] opened 2023-05-25 18:17 UTC
## Description 

Brave VPN connection failed initially with `Failed to write the VPN config` error in the VPN panel.  Tried to connect again and it connected successfully. Tested the connection with no other VPN entries (i.e Brave VPN Beta) and with other Brave VPN entries in the OS/Network settings.  Fwiw, I have noticed that when VPN was not connected, phonebook entry was populated with `BraveVPN` entry (previously for issue #30291, phonebook entry was not populated).  

## Steps to Reproduce

Scenario 1: New install 

1. Install 1.52.112
2. launch Brave
3. connect to VPN with a new purchase in staging 

Scenario 2: Upgrade from 1.51.x --> 1.52.x 

1. Install 1.51.x
2. launch Brave
3. connect to VPN with a new purchase in staging 
4. upgrade to 1.52.x 
5. Disconnect and connect again

## Actual result:

`Failed to write the VPN config` is shown in the VPN panel.  Enabled again. Successfully connected.  
However, there are subsequent failures like quickly disconnect again from connected state or when switching servers,
Fresh Install: 
example | example | example | example 
--- | --- | --- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/e0bed44f-a6f4-4825-8954-f1e60573986a)|![image](https://github.com/brave/brave-browser/assets/98358127/6dffde1f-9e78-4693-a0f4-f201a170f61b)|![image](https://github.com/brave/brave-browser/assets/98358127/d3ce0d75-e76b-47c9-9460-ed4ea4a25f9b)|![image](https://github.com/brave/brave-browser/assets/98358127/d7296350-e7e1-41bd-9bd4-1d77cd863ac9)

Upgrade: 

https://github.com/brave/brave-browser/assets/98358127/8a98eb02-a828-412d-9c17-39aa60009cf1

## Expected result:
Brave VPN should connect successfully without errors

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.52.112 Chromium: 114.0.5735.35 (Official Build) (64-bit)
-- | --
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
 @simonhong @bsclifton @rebron 

cc: @brave/qa-team

**Comment by bsclifton** [comment] 2023-05-25 21:53
Thanks @MadhaviSeelam for sharing logs over Slack - here is an example of what is logged when the config write failure happens:
```
[29704:26744:0525/144344.251:VERBOSE2:utils.cc(410)] CreateEntry Create Entry(BraveVPN) with sanjose-1.sgw.guardianapp.com
[29704:11184:0525/144344.262:VERBOSE2:brave_vpn_os_connection_api_base.cc(294)] SetLastConnectionError : failed to write "NumCustomPolicy" field to `rasphone.pbk`
[29704:11184:0525/144344.262:VERBOSE2:brave_vpn_os_connection_api_base.cc(239)] OnCreateFailed
[29704:11184:0525/144344.262:VERBOSE2:brave_vpn_os_connection_api_base.cc(333)] UpdateAndNotifyConnectionStateChange : changing from CONNECTING to CONNECT_NOT_ALLOWED
[29704:11184:0525/144344.262:VERBOSE2:brave_vpn_service.cc(133)] OnConnectionStateChanged CONNECT_NOT_ALLOWED
```

There may be a file lock issue. `RasSetEntryProperties` is touching this file and then we immediately call `WritePrivateProfileString`
https://github.com/brave/brave-core/blob/dd24dbe31d3015a7156facebb7d402fc1c2c92c8/components/brave_vpn/browser/connection/ikev2/win/ras_utils.cc#L493-L499

From [the docs](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-writeprivateprofilestringw):
> If the function fails, or if it flushes the cached version of the most recently accessed initialization file, the return value is zero. To get extended error information, call [GetLastError](https://learn.microsoft.com/en-us/windows/desktop/api/errhandlingapi/nf-errhandlingapi-getlasterror).

We could definitely enhance by calling `GetLastError` to see the error message

**Comment by bsclifton** [comment] 2023-05-25 22:01
The correct solution I think would be to get rid of the calls to `WritePrivateProfileString`.

For those, we can do what a lot of scripts do. PowerShell *should* be installed and we should be able to call a commandlet:
https://docs.microsoft.com/en-us/powershell/module/vpnclient/set-vpnconnectionipsecconfiguration?view=windowsserver2019-ps

When calling this without parameters, it'll ask for the values. Here are the ones I provided:
`AuthenticationTransformConstants`: GCMAES256
`CipherTransformConstants`: GCMAES256
`DHGroup`: ECP384
`IntegrityCheckMethod`: SHA256
`PfsGroup`: None
`EncryptionMethod`: GCMAES256

Using the PowerShell method should work on Windows Arm64 also (this may fix https://github.com/brave/brave-browser/issues/28942)

**Comment by spylogsster** [comment] 2023-06-01 10:51
I cannot reproduce this on latest master and it seems could be fixed by https://github.com/brave/brave-core/pull/18510
@stephendonner @MadhaviSeelam can you please check this on latest Nightly? thanks

**Comment by spylogsster** [comment] 2023-06-01 11:47
I cannot reproduce in both cases, it looks similar to https://github.com/brave/brave-core/pull/18510 and seems this could be fixed  there. @stephendonner @MadhaviSeelam please recheck on latest Nightly if issue still actual? thanks

**Closed** 2023-06-02 04:26 UTC
Labels: bug, release/blocking, QA/Yes, QA/Test-Plan-Specified, regression, OS/Desktop, feature/vpn

**Comment by kjozwiak** [comment] 2023-06-02 09:17
The above requires `1.52.119` or higher for `1.52.x` verification 👍

**Comment by GeetaSarvadnya** [comment] 2023-06-02 14:23
Verification **INPROGRESS** on

```
Brave | 1.52.119 Chromium: 114.0.5735.90 (Official Build) (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 10 Version 22H2 (Build 19045.2965)

```

**Comment by MadhaviSeelam** [comment] 2023-06-02 18:21
Verification  `PASSED` using
```
Brave | 1.52.119 Chromium: 114.0.5735.90 (Official Build) (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```
Verified using original STR https://github.com/brave/brave-browser/issues/30598#issue-1726279388

Fresh Install: 

### Confirmed connected to VPN successfully.  No longer seeing `Failed to write the VPN config` error in the VPN panel.
ex | ex 
--- | --- 
![image](https://github.com/brave/brave-browser/assets/98358127/371dbc64-cba3-45dd-8ac8-6e27302c3140)|![image](https://github.com/brave/brave-browser/assets/98358127/55149f3a-3d22-423f-875b-fdba4b37cb2e)|![image](https://github.com/brave/brave-browser/assets/98358127/b91ad38f-e2c3-49c0-85b7-9e5033e74c3d)



Upgraded profile: 

### Confirmed connected to VPN successfully.  No longer seeing `Failed to write the VPN config` error in the VPN panel.

ex|ex|ex
--- | --- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/55196815-3989-4c3d-9751-8fda0f54ace9)|![image](https://github.com/brave/brave-browser/assets/98358127/4a0a2395-ac39-4a14-8b21-e9939a46726e)|![image](https://github.com/brave/brave-browser/assets/98358127/e63daf65-25b4-4f59-88d8-3f8dd7c4c6fc)


Connect/disconnect via OS settings

### Confirmed connected to VPN successfully.  No longer seeing `Failed to write the VPN config` error in the VPN panel.

![image](https://github.com/brave/brave-browser/assets/98358127/c3b80870-1881-4a01-a54b-d68be158ee7a)
![image](https://github.com/brave/brave-browser/assets/98358127/4caa5844-e611-4af1-9392-71e55e37ab33)

**Comment by stephendonner** [comment] 2023-06-02 22:41
Filed a followup issue for the `Can't connect to server` messages we're seeing: https://github.com/brave/brave-browser/issues/30792
