### ISSUE TITLE
Add a sleeping tab feature in Brave like it is present in Microsoft Edge

### ISSUE THREAD

**Issue by clicky6** [brave/brave-browser#17827] opened 2021-09-02 06:40 UTC
![image](https://user-images.githubusercontent.com/89839714/131794888-339cbb7b-5cb1-4939-9b6c-679a2608074c.png)

Add a **sleeping tab** feature in Brave like it is present in Microsoft Edge. It helps to reduce consumption of system resources by putting tabs to sleep after a certain amount of time described by the user.

**Comment by Tonev** [comment] 2021-09-03 07:01
I've never used `Microsoft Edge` but your suggestion sounds like a duplicate of https://github.com/brave/brave-browser/issues/17453, is that correct?

**Comment by clicky6** [comment] 2021-09-03 07:21
Yes.

**Comment by Tonev** [comment] 2021-09-03 07:25
CC: @bsclifton

**Comment by clicky6** [comment] 2021-09-03 07:33
@Tonev How to do find duplicate issues?🤔

**Comment by Tonev** [comment] 2021-09-03 07:41
Well, I like Brave so I browse Github on a regular basis (mostly daily basis) to stay in touch with upcoming changes, etc, also I'm a regular `Brave Community` user which is also helping me. I remembered seeing a very similar issue to yours, searched for it and it turned out your issue is a duplicate. But to answer your question - you should use the search functionality of Github before opening an issue, although sometimes you might be given tons of random issues, it heavily depends on what you're searching for.

**Comment by clicky6** [comment] 2021-09-03 07:59
Thank You very much Sir.

**Comment by bsclifton** [comment] 2021-09-03 16:40
Thanks for the assist, @Tonev 😄 

Closing as a duplicate of https://github.com/brave/brave-browser/issues/17453 - you can subscribe there for updates 😄 (I shared your screenshot there too!)

**Closed by bsclifton** 2021-09-03 16:40 UTC
Labels: OS/Desktop
