### ISSUE TITLE
autoplay video blocking not working on cbsnews.com

### ISSUE THREAD

**Issue by smolin** [brave/brave-browser#9014] opened 2020-04-03 15:12 UTC
## Description 

With autoplay set to 'block', videos still play on cbsnews.com

## Steps to Reproduce

   1. set autoplay to 'block'
   2. load https://www.cbsnews.com/

## Actual result:

Page loads and videos start playing (you might have to scroll down to find one if it's not a top story)

## Expected result:

Page loads with videos paused.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | macOS Version 10.14.6 (Build 18G4032)
JavaScript | V8 8.0.426.25
Flash | (Disabled)

## Version/Channel Information:

No other channels tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?

no

- Does the issue resolve itself when disabling Brave Rewards?

no
 
- Is the issue reproducible on the latest version of Chrome? 

yes

**Comment by witchpiggie** [comment] 2020-04-29 16:51
Seems to be an issue on other sites as well. [This page](https://abc7.com/oc-sheriff-to-review-22000-cases-in-deputy-evidence-scandal/5906144/) for example also autoplays even when set to blocked.

**Comment by rebron** [comment] 2020-05-22 20:31
Closing as dupe of #9597

**Closed by rebron** 2020-05-22 20:31 UTC
Labels: duplicate
