### ISSUE TITLE
Shield and BAT icons are too small as compared to GPS version icons

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7137] opened 2019-11-27 18:22 UTC
## Description 

Shield and BAT icons are too small as compared to GPS version icons

## Steps to Reproduce

   1. Clean profile 2.0.0
   2. Enable rewards
   3. Shield and BAT icons are too small as compared to GPS version icons

## Actual result:

Shield and BAT icons are too small as compared to GPS version icons

![image](https://user-images.githubusercontent.com/38657976/69749399-6ebb4f00-1170-11ea-9951-115ae1de7cc9.png)

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave 2.0.0 Chromium 78.1.3.15

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @yrliou @SergeyZhukovsky

**Comment by yrliou** [comment] 2020-01-31 19:12
Close as a duplicate of https://github.com/brave/brave-browser/issues/7550

**Closed by yrliou** 2020-01-31 19:12 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, android-core-release, priority/P2
