### ISSUE TITLE
P3A: Change the meaning of the first answer to all Rewards-related questions 

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#7679] opened 2020-01-09 21:55 UTC
## Description 

Currently a set of P3A questions have answers that are designed to determine how many people have Brave Rewards *disabled*, but in fact are actually measuring how many people have *no wallet* -- a different metric, since it is possible to have Rewards disabled, but still have a wallet. 

These questions are:

Brave.Rewards.WalletBalance
Brave.Rewards.AutoContributionsState
Brave.Rewards.TipsState
Brave.Rewards.AdsState

In each case, the first response is currently

"No wallet" (or "No wallet created" -- same meaning)

In the case of all four questions, the first answer should in fact be

"Rewards not enabled"

This answer should *replace* the current "no wallet" answer. 

Meaning that if Brave Rewards is currently not on, the answer should be reported on the basis of the Rewards on/off setting. The presence or absence of a wallet is not relevant.

## Steps to Reproduce

A browser that once had Rewards on, but now has it off, should uniformly report "Rewards not enabled" for all of the above questions.

## Actual result:

A browser with Rewards off will report answers other than the first one if Rewards has been enabled at any point previously.

## Expected result:

A browser with Rewards off should uniformly report "Rewards not enabled" for all of the above questions, even if Rewards has been on at some point previously.

## Reproduces how often: 

Presumably 100% based on @iefremov code inspection

## Brave version (brave://version info)

Applies to all desktop platforms / all channels

**Comment by bsclifton** [comment] 2020-01-09 22:08
Closing as duplicate of https://github.com/brave/brave-browser/issues/7633

**Closed by bsclifton** 2020-01-09 22:08 UTC
