### ISSUE TITLE
Brave does not start

### ISSUE THREAD

**Issue by uzi18** [brave/brave-browser#40532] opened 2024-08-19 15:12 UTC
### Description

After launch window does not show.
Brave installed on local account - without admin rights
 
### Steps to reproduce

1.  Click on icon does not launch app

### Actual result

no window

### Expected result

open window

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

127.1.68.128
win10 pro 11h2/64bit

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

![obraz](https://github.com/user-attachments/assets/e13c5bab-52ad-45db-9c1c-198226db564b)

**Comment by bsclifton** [comment] 2024-08-19 17:08
@uzi18 can you please try uninstalling and reinstalling? 

Uninstall (Windows + R, `appwiz.cpl`, then uninstall `Brave`) and then reinstall the newest version from https://brave.com/download/.  During the uninstall, a box will show up. DO NOT TICK THE BOX, just click the `Uninstall` button. 

This should get you on 1.68.141 which has some crash fixes! Please let us know

**Comment by bsclifton** [comment] 2024-08-19 17:10
I suspect the root cause is https://github.com/brave/brave-browser/issues/40005 which is why an updated version of Brave would work (1.68.131 or higher). If you do an admin level install (accept the UAC prompt), an updater will be installed which can do background updates.

**Comment by bondeabhijeet** [comment] 2024-08-19 17:43
Hey, So I faced somewhat the same issue on my personal computer

1. **Open the Windows Registry Editor (Reg edit):**
   - Press `Win + R`, type `regedit`, and press `Enter`. If prompted by User Account Control, click `Yes`.

2. **Navigate to the following path:**
   - `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}`

3. **Verify the "ap" value:**
   - In the right pane, find the key named `ap`.
   - Check the data value of `ap`. 
     - For Windows x64, it should be set to `x64-rel`.
     - For Windows x86, it should be set to `x86-rel`.
   - If you're using a different version of Brave (such as Beta, Dev, or Nightly), the value might differ, e.g., `x64-be` for Beta, `x64-dev` for Dev, or `x64-ni` for Nightly.

4. **Copy your Brave user data:**
   - Navigate to `C:\Users\[USERNAME]\AppData\Local\BraveSoftware\Brave-Browser\User Data\`.
   - REMEMBER: Replace `[USERNAME]` with your actual Windows username.
   - Copy the entire `User Data` folder to a safe location (e.g., your desktop or an external drive).

5. **Uninstall Brave Browser:**
   - Open the Control Panel or Settings, go to `Programs and Features`, find `Brave`, and uninstall it.
   - When prompted, choose to clear the user data.

6. **Download and install the latest Brave Browser:**
   - Go to [Brave's official download page](https://brave.com/download/) and download the latest installer.
   - Run the installer to reinstall Brave Browser.

7. **Restore your previous user data:**
   - After the installation is complete, navigate to the newly created `User Data` folder (same path as before).
   - Replace the entire contents of this folder with the contents from the `User Data` folder you previously copied.

This process should restore your previous settings, bookmarks, and other data in the new installation of Brave Browser.

**Comment by uzi18** [comment] 2024-08-20 12:23
@bondeabhijeet 
![obraz](https://github.com/user-attachments/assets/e47ac6b0-d632-490f-a9c5-61db8d33f0a0)

**Comment by bondeabhijeet** [comment] 2024-08-20 13:53
Try setting ap to `x64-rel` and try, if this doesn't work kindly try reinstalling the browser (usually reinstalling the browser resolves the issue, follow the guide I mentioned above for reinstalling the browser without having to lose data and logins)

**Comment by bsclifton** [comment] 2024-08-22 16:45
OK going to go ahead and close this as there hasn't been an update. If there is still a problem, we can re-open or just continue working through things 😄 

I highly recommend to uninstall / reinstall though. That should get you sorted out. My educated guess based on the version reported `127.1.68.128` was that you were in the bucket of folks who were affected by https://github.com/brave/brave-browser/issues/40005. 

We had a release today with this fix and a lot more - please give that a shot. Thanks!

**Closed by bsclifton** 2024-08-22 16:45 UTC
Labels: crash, needs-more-info, OS/Desktop
