### ISSUE TITLE
Broken Web Page Report.

### ISSUE THREAD

**Issue by rnixs** [brave/brave-browser#36213] opened 2024-02-20 04:23 UTC
## Steps to Reproduce

   1. Open the honkailab and ygosu.
   2. Active the brave shield
   3. Page fails to load CSS.

## Actual result:

<img width="1604" alt="image" src="https://github.com/brave/brave-browser/assets/81290656/9bdc38ca-4b83-46c0-b937-2c6e2880f798">
<img width="1604" alt="image" src="https://github.com/brave/brave-browser/assets/81290656/349aedc0-c7b8-4a9b-b2ea-7a754fb89915">

## Expected result:
<img width="1512" alt="image" src="https://github.com/brave/brave-browser/assets/81290656/de8dc9c0-f637-4d55-9a8e-b524d529b756">

## Android Device details:
   - Install type (ARM, x86):All versions have this problem
   - Device type (Phone, Tablet, Phablet): phon, table, phablet
   - Android version: All versions have this problem

## Version/Channel Information:

- Can you reproduce this issue with the current release? - yes
- Can you reproduce this issue with the beta channel? - yes
- Can you reproduce this issue with the nightly channel? - yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? - yes
- Does the issue resolve itself when disabling Brave Rewards? - no
- Is the issue reproducible on the latest version of Chrome? - no

## Miscellaneous Information:

Braves Shield seems to be blocking something wrong. Can we quickly find out the cause and fix this?

**Comment by bsclifton** [comment] 2024-03-05 22:53
Closing as duplicate of https://github.com/brave/brave-browser/issues/36547

**Closed by bsclifton** 2024-03-05 22:53 UTC
Labels: feature/shields, webcompat/not-shields-related, OS/Android, OS/Desktop
