### ISSUE TITLE
Hide tipping banner when clicking outside of it and after a few seconds

### ISSUE THREAD

**Issue by agentofuser** [brave/brave-browser#4607] opened 2019-05-25 14:59 UTC
## Description 

After tipping someone, the (very large) banner stays visible, and I have to click on a very small target to make it go away.

## Steps to Reproduce

   1. Tip someone
   2. Try to hide/close the banner

## Actual result:

Banner stays on top unless you click small "x" on the top right corner.

## Expected result:
* Clicking outside should hide it. 
* Pressing Esc or Enter should hide it.
* It should close itself after a few seconds. (I can always check the Rewards screen.)

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

0.67.55 Chromium: 75.0.3770.38 (Official Build) nightly(64-bit)
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

## Version/Channel Information:

All channels.

- Can you reproduce this issue with the current release?
Don't know.
- Can you reproduce this issue with the beta channel?
Don't know.
- Can you reproduce this issue with the dev channel?
Partially. The banner auto closes after a few seconds. Esc also makes it go away. (Enter doesn't.) Clicking outside doesn't hide it.
- Can you reproduce this issue with the nightly channel?
Yes.

**Comment by srirambv** [comment] 2019-05-26 13:16
Assuming this is on  twitter tip banner since you mentioned nightly only so its a duplicate of #4590. More discussion there.

**Closed by srirambv** 2019-05-26 13:16 UTC

**Comment by agentofuser** [comment] 2019-05-26 13:25
@srirambv I tested this on a regular website too and had the same result.
