### ISSUE TITLE
Global media controls control Cast start/stop makes Brave to crash

### ISSUE THREAD

**Issue by BIOLorenz** [brave/brave-browser#17194] opened 2021-07-27 10:01 UTC
## Description 
Activating the flag #global-media-controls-cast-start-stop shows the media controller on the address bar (near the menu icon) upper right.
Clicking it while reproducing a video cause Brave Browser to force close.

## Steps to Reproduce

   1.  Go to brave://flags
   2.  Activate #global-media-controls-cast-start-stop and set to Enable
   3.  Reproduce a video/music (ex: Youtube Video)
   4. Click on the Media Controller button upper right in the address bar 
![image](https://user-images.githubusercontent.com/12199479/127135597-71808a8e-7299-4785-a58b-2f9c15e23c6c.png)

## Actual result:
Brave crash and force close after clicking the button

## Expected result:
![image](https://user-images.githubusercontent.com/12199479/127132951-34af01b6-935f-4971-a547-f646549df18b.png)
Global Media controls opens without problems (Microsoft Edge Example)

## Reproduces how often: 
Always when the icon is clicked

## Brave version (brave://version info)

Brave | 1.29.27 Chromium: 92.0.4515.107 (Official Build) nightly (64 bit)
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | Windows 10 OS Version 2009 (Build 19043.1110)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  N/A
- Can you reproduce this issue with the beta channel?  N/A
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards?  No
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by rebron** [comment] 2021-07-27 17:50
@BIOLorenz When you get a chance, can you go to brave://crashes/ and send the report and post the crash id here.

Do you have brave://settings/extensions the Media Router setting enabled too?

Flags are experimental features, so we'll be prioritizing this crash accordingly.

**Comment by BIOLorenz** [comment] 2021-07-28 08:20
Hello Rebron,

> @BIOLorenz When you get a chance, can you go to brave://crashes/ and send the report and post the crash id here.

ID: c50b2300-217a-ae06-0000-000000000000

> Do you have brave://settings/extensions the Media Router setting enabled too?

Yes, it's enabled. It crash if enabled and if disabled too.

> Flags are experimental features, so we'll be prioritizing this crash accordingly.

No problem about that, in previous version it was working, cannot say exactly in what nightly it broke up.


**Not working in Beta too** Just tried it for curiosity.

Brave | 1.28.92 Chromium: 92.0.4515.107 (Official Build) beta (64 bit)
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | Windows 10 OS Version 2009 (Build 19043.1110)

**Comment by iefremov** [comment] 2021-12-10 18:28
closing as a duplicate of https://github.com/brave/brave-browser/issues/19553

**Closed by iefremov** 2021-12-10 18:28 UTC
Labels: crash, priority/P4, OS/Desktop
