### ISSUE TITLE
[Desktop] navigating to non-existent/disabled internals page gives chrome:// page error message

### ISSUE THREAD

**Issue by thefallofbecause** [brave/brave-browser#10305] opened 2020-06-16 15:10 UTC
## Description 

When navigating to an internals page that either does not exist or is part of disabled functionality the URI in the address bar uses the correct brave:// scheme but the page error message gives the chrome:// scheme.

## Steps to Reproduce

   1. Navigate to `brave://test/`
   2. Navigate to `brave://sync-internals` (I am assuming only when sync is disabled?)

## Actual result:

<img width="711" alt="Screen Shot 2020-06-16 at 5 44 31 pm" src="https://user-images.githubusercontent.com/8562416/84791420-3c354e80-affb-11ea-9dbc-38fd3340cbaa.png">

## Expected result:
Error message should reference the brave:// scheme in the URI

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.10.90 Chromium: 83.0.4103.97 (Official Build) (64-bit)
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | macOS Version 10.14.6 (Build 18G87)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Untested, but checked recently closed issues for similar issues and could not see it
- Can you reproduce this issue with the dev channel? As per beta
- Can you reproduce this issue with the nightly channel? As per beta

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Shields unavailable for internals
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes, but that's part of the problem!

**Comment by rebron** [comment] 2020-08-07 17:57
brave://sync-internals works starting with 1.12.x. 

So this issue would be for brave://test brave://*

**Comment by swapnilmarkhedkar** [comment] 2020-09-19 16:57
The issue seems to be only for `brave://test/`. Since its not assigned to anyone yet, could I work on it?

**Comment by bsclifton** [comment] 2020-09-24 23:06
@swapnilmarkhedkar sure - go for it

**Comment by JuanFML** [comment] 2020-11-28 00:51
Hello everyone, I am new here and I would like to try to solve my first issue, I see someone is working on it, although it has passed some time already, can I give it a try?

**Comment by JackMechem** [comment] 2021-04-08 14:19
@bsclifton Do you mind if i work on this?

**Comment by bsclifton** [comment] 2021-04-08 16:55
@JackMechem sure, let's do it 😄 If nobody is assigned yet and there's not a pull request open, it's fair game

Let me know if you need help setting up or run into an issue

**Comment by JackMechem** [comment] 2021-04-08 18:00
> @JackMechem sure, let's do it  If nobody is assigned yet and there's not a pull request open, it's fair game
> 
> Let me know if you need help setting up or run into an issue

@bsclifton Hey when I run `npm run init` i get this error:
```
> git clone  .

fatal: repository 'undefined' does not exist
```

**Comment by bsclifton** [comment] 2021-04-08 18:47
@JackMechem I think you'll want to check to see if you have the LTS version of Node.js installed. One of the dependencies for the latest Node seems to have a problem with the dash one of the repos our script clones

**Comment by JackMechem** [comment] 2021-04-10 22:47
@bsclifton Hey. I have downloaded the LTS version of node and i am still having the same. I tried downgrading node even more and I still had no luck. Could it be an issue with git?
```
> brave@1.25.3 init
> node ./scripts/init.js

Performing initial checkout of brave-core
Cloning brave-core [undefined] into /home/jack/Documents/con/brave-browser/src/brave...
---------------------------------------------------------------------------------------------
/home/jack/Documents/con/brave-browser/src/brave
> git clone  .

fatal: repository 'undefined' does not exist

~/D/c/brave-browser ❯❯❯ node -v                                                   ✘ 1 master ✱
v10.24.0
~/D/c/brave-browser ❯❯❯                                                                     master ✱
```

**Comment by rahulsnkr** [comment] 2021-04-13 15:53
Hey @JackMechem, I was having the same issue and downgrading to Node.js v12 LTS worked for me

**Comment by fallaciousreasoning** [comment] 2022-05-03 23:18
I might take a look at this, as it's been quiet for a while, if no one objects.

**Closed** 2022-05-09 22:37 UTC
Labels: good first issue, priority/P5, branding, OS/Desktop

**Comment by stephendonner** [comment] 2022-05-31 19:58
## Verified `PASSED` using 

Brave | 1.40.77 Chromium: 102.0.5005.61 (Official Build) beta (x86_64)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | macOS Version 11.6.6 (Build 20G624)

### Steps:
1. installed `1.40.77`
2. launched Brave
3. entered `brave://test` into the URL bar and pressed `return`
4. checked the error messaging

#### Confirmed `brave://test` shows, rather than `chrome://test` in the error messaging.

`1.40.77` (`brave://test`) | `1.39.111`  (`chrome://test`)
-------------|-------------
<img width="1389" alt="Screen Shot 2022-05-31 at 12 57 36 PM" src="https://user-images.githubusercontent.com/387249/171274135-a35af504-88e7-4bee-8b38-df5ec47756b8.png"> | <img width="1312" alt="Screen Shot 2022-05-31 at 12 52 24 PM" src="https://user-images.githubusercontent.com/387249/171274173-60545d8f-ae67-4d7a-a75b-4c8f17a88cc4.png">

**Comment by MadhaviSeelam** [comment] 2022-05-31 23:28
Verification `PASSED` using
```
Brave | 1.40.80 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 11 Version 21H2 (Build 22000.675)
```

Steps:

- Installed 1.40.80
- Launched Brave
- Entered brave://test into the URL bar and pressed return
- Checked the error messaging
- Confirmed brave://test shows, rather than chrome://test in the error messaging.

brave://test (1.40.88) | chrome://test (1.39.111)
----|----
<img width="968" alt="image" src="https://user-images.githubusercontent.com/98358127/171299366-87fffcf1-e885-474d-954b-38a574b580d9.png">|<img width="968" alt="image" src="https://user-images.githubusercontent.com/98358127/171299385-c0eb068d-0472-4925-9f99-e51a3cc38639.png">
