### ISSUE TITLE
Segmentation fault on private tab

### ISSUE THREAD

**Issue by congard** [brave/brave-browser#9101] opened 2020-04-08 20:09 UTC
## Description 
If I open a private tab and start typing something, an error occurs and the browser closes with segmentation fault.

I noticed that this happens when typing smth that exists in history

## Steps to Reproduce

   1. Open private tab
   2. Start to type something

## Actual result:
Browser closes with segmentation fault

## Expected result:
No error

## Reproduces how often: 
Easily reproduced on last nightly

## Brave version (brave://version info)
```
Brave: 1.9.9 Chromium: 81.0.4044.83 (Official build) unknown (64-bit)
Revision: 5718ca617723806b9aacfb41108a0d911d1bde74-refs/branch-heads/4044@{#853}
OS: Linux
```

## Version/Channel Information:

- Q: Can you reproduce this issue with the nightly channel? A: Yes.

## Other Additional Information:

- Q: Does the issue resolve itself when disabling Brave Shields? A: No
- Q: Does the issue resolve itself when disabling Brave Rewards? A: No
- Q: Is the issue reproducible on the latest version of Chrome? A: Yes

**Comment by bsclifton** [comment] 2020-04-09 23:12
@congard do you have auto-suggestions enabled for your search engine? If so, I believe we just found this recently too with https://github.com/brave/brave-browser/issues/9119

cc: @rebron

**Comment by congard** [comment] 2020-04-10 12:22
@bsclifton, yes, auto-suggestions enabled

**Comment by bsclifton** [comment] 2020-04-10 17:02
@congard perfect - you can turn that off as a temporary work-around... I'm going to close this issue as a duplicate of https://github.com/brave/brave-browser/issues/9119. Looks like @mkarolin is looking into the issue and should have a fix soon 😄

**Closed by bsclifton** 2020-04-10 17:02 UTC
Labels: crash, feature/private-browsing
