### ISSUE TITLE
Shields Up Prevents Google Workspace Sign In and Pages From Loading

### ISSUE THREAD

**Issue by x5josh5x** [brave/brave-browser#22112] opened 2022-04-06 01:38 UTC
## Description 

With Shields Up enabled, unable to sign into Google Workspace. Turning off Shields Up fixes the issue. However, after signing in, if Shields Up is enabled on any page, it will give a error saying 'ERR_TOO_MANY_REDIRECTS'. This is true in a private window, with all extensions disabled as well. There are some pages that will not load, even with Shields Up disabled.

The same doesn't seem to be true with regular Gmail accounts, they seem to be working.

## Steps to Reproduce

   1. Turn Shields Up on.
   2. Navigate to drive.google.com and click 'Sign in'.
   3. Attempt to sign in with any Google Workspace account.

## Actual result:

This is the page that appears instead:
![screenshot](https://user-images.githubusercontent.com/29776845/161877532-c93b55df-736b-4ef3-94be-e69c21cc0bc5.png)

## Expected result:
Expected the ability to sign in with Google Workspace accounts.

## Reproduces how often: 

Easily reproduced every time.

## Brave version (info found on brave://version)

**Brave:** 1.37.111 Chromium: 100.0.4896.79 (Official Build) (arm64)
**Revision:**( 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
**OS:** macOS Version 12.3.1 (Build 21E258)

## Version/Channel Information:

- Can you reproduce this issue with the current release?

Yes. Only attempted on the current release.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?

Yes for some pages, but some pages continue to have issues.

## Miscellaneous Information:

Even when Shields Up disabled, some pages aren't loading. For example, Google Workspace Admin help pages won't load at all. Or this page loads and I appeared signed in, but it complains that something went wrong, even with Shields Up disabled:
![screenshot2](https://user-images.githubusercontent.com/29776845/161878200-570fd562-1e73-4ede-992e-cd36e9749563.png)

**Comment by rebron** [comment] 2022-04-07 20:58
cc: @ryanbr

**Comment by jekozyra** [comment] 2022-04-19 00:59
Seconding this issue. I can't log into any site that uses Google SSO.

**Comment by ryanbr** [comment] 2022-04-20 12:17
I'll test this under a clean profile, is it reproducible @jekozyra @x5josh5x  under a clean Brave profile?

**Comment by x5josh5x** [comment] 2022-04-21 03:28
@ryanbr Interesting, in the most recent build, I haven't been able to get it to replicate now, under a clean profile, or even my original profile. I've tried with three different profiles and two different Google Workspace accounts, and it all seems to be working even with Shields Up enabled on all Google domains. I'm now on: Version 1.37.116 Chromium: 100.0.4896.127 (Official Build) (arm64)

**Comment by ryanbr** [comment] 2022-04-21 11:48
@x5josh5x great to see it resolved, @jekozyra  is your similar issue fixed?

**Comment by x5josh5x** [comment] 2022-04-24 02:24
@ryanbr I spoke too soon. I'm still seeing the issue. I'm no sure why it was working for me the other day. But now today, on the same version (Version 1.37.116 Chromium: 100.0.4896.127 (Official Build) (arm64)), I'm getting the same initial issue.

As far as settings go, here is what I have found with my testing:

1. Opening the Shields Up menu from the browser bar and toggling to 'down' will allow the pages to load:
<img width="384" alt="Screen Shot 2022-04-24 at 11 13 28" src="https://user-images.githubusercontent.com/29776845/164953113-01706126-ae3d-4385-9b7f-93e44f9da4f8.png">

2. If that setting is toggled off, the page won't load again.
3. If I leave that setting in the 'Shields Up' setting and toggle the cookies settings, there is no change, the pages won't load.
4. However, by default, I keep 'Trackers & ads blocking' as 'Standard', but if I go into preferences and change it to 'Disabled', the page will load, even in a 'Shields Up' stage:
<img width="613" alt="Screen Shot 2022-04-24 at 11 17 23" src="https://user-images.githubusercontent.com/29776845/164953220-44ffc95d-f3c5-4d20-9a5d-f26162a71612.png">

5. Here's the interesting part. Once the page loaded, I think toggled the 'Trackers and ads blocking' setting back to 'Standard' and the page **still** loaded. Then I tried toggling Shields Up and Shields Down from the browser bar and the pages continued to work.

So it seems like it has something to do with the 'Trackers & ads blocking' setting and if the user temporarily disables the trackers and allows the page to load (seems like @jekozyra is right, watching the URLs going back, it has something to do with the sign-in process), then afterwards, it continues to work, regardless of the trackers setting.

**Comment by ryanbr** [comment] 2022-04-28 00:13
Can you check the latest Brave build 1.38.* helps @x5josh5x @jekozyra

**Comment by x5josh5x** [comment] 2022-04-28 04:54
@ryanbr So far, so good! Tested with a few different accounts and even with 'Shields Up' on and 'Trackers & ad blocking' set to 'Standard', was able to sign in and use Google Workspace without issue. Same for SSO, it handled the Google OAuth without issue. I'll keep testing and monitoring and let you know if I find anything, but so far this is promising. Thanks!

**Comment by ryanbr** [comment] 2022-04-30 01:01
Is your google now working okay @jekozyra  ?

**Comment by rebron** [comment] 2022-05-20 20:40
Should be fixed starting with 1.38.109 and above. Thanks @x5josh5x for the confirmation.
This issue I believe was a duplicate of https://github.com/brave/brave-browser/issues/22493

**Closed** 2022-05-20 20:41 UTC
Labels: feature/shields, workaround/shields-down, feature/shields/webcompat, google
