### ISSUE TITLE
Corrupted ledger state showing can't connect error

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#3396] opened 2019-02-17 13:18 UTC
When a ledger_state is corrupted, we show the wrong error.

# Here's what's shown:
<img width="1094" alt="screen shot 2019-02-17 at 8 14 20 am" src="https://user-images.githubusercontent.com/831718/52913422-145d9b80-328c-11e9-845a-000548bb936a.png">

Clicking on retry does nothing forever.

# What we should do:
We should instead either auto-recover, or show a message that it's corrupted and you need to go to recovery words.

# Here's my ledger_state:
```
{"walletInfo":{"paymentId":"","addressBAT":"","addressBTC":"","addressCARD_ID":"","addressETH":"","addressLTC":"","keyInfoSeed":""},"bootStamp":0,"reconcileStamp":1551675108,"last_grant_fetch_stamp":1550409240,"personaId":"","userId":"","registrarVK":"","masterUserToken":"","preFlight":"","fee_currency":"","settings":"adFree","fee_amount":0.0,"user_changed_fee":false,"days":0,"rewards_enabled":false,"auto_contribute":false,"transactions":[],"ballots":[],"ruleset":"","rulesetV2":"","batch":[],"current_reconciles":{}}
```

cc @NejcZdovc

**Comment by NejcZdovc** [comment] 2019-02-18 06:33
probably related to this one https://github.com/brave/brave-browser/issues/2997

**Comment by NejcZdovc** [comment] 2019-02-18 09:14
I couldn't reproduce this one on a clean profile. Let's try to debug it

**Comment by Liunkae** [comment] 2019-02-19 14:04
Related:#2649, #3046, #3403

**Comment by NejcZdovc** [comment] 2019-03-05 14:36
closing as dupe of https://github.com/brave/brave-browser/issues/2997

**Closed by NejcZdovc** 2019-03-05 14:36 UTC
Labels: feature/rewards, priority/P1
