### ISSUE TITLE
exit code 139, exo-open error message

### ISSUE THREAD

**Issue by quantenschaum** [brave/brave-browser#5915] opened 2019-09-06 08:32 UTC
## Description 
`brave-browser` exits with 139 when there is already a running instance.

## Steps to Reproduce
On Xubuntu 19.04 (disco) (xfce! not plain Ubuntu)
   1. [Install brave via ppa](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux)
   2. set brave as default browser (in `exo-preferred-applications`)
   3. launch brave
   4. launch brave again using `exo-open --launch WebBrowser`  or `brave-browser`

## Actual result:
Brave opens new window and

- an error message is displayed. (`exo-open`)  
  ![image](https://user-images.githubusercontent.com/3985599/64412733-5adfdf80-d090-11e9-8759-cb7644015dba.png)
- exits with 139. (`brave-browser`)

## Expected result:
Brave opens new window without any error message, exit code 0.

## Reproduces how often: 
every time

## workaround

launch brave via shell script 

```sh
#!/bin/sh
brave-browser "$@"
exit 0
```

## Brave version (brave://version)

```
Brave	0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)
Revision	fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS	Linux
JavaScript	V8 7.6.303.29
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
Command Line	/usr/bin/x-www-browser --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extensions-install-verification=enforce_strict --enable-features=NewExtensionUpdaterService,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,TranslateUI,NetworkService,UnifiedConsent --flag-switches-begin --load-media-router-component-extension=1 --disable-features=AutofillServerCommunication,TranslateUI,NetworkService,UnifiedConsent,ViewsCastDialog --flag-switches-end http://127.0.0.1:4000/
Executable Path	/opt/brave.com/brave/brave-browser
Profile Path	/home/user/.config/BraveSoftware/Brave-Browser/Default
Variations	d74ef32b-ca7d8d80
```

## Other Additional Information

Chrome does behave as expected.

**Comment by rebron** [comment] 2019-09-06 17:01
@fmarier Can you take a look?

**Comment by fmarier** [comment] 2019-09-07 00:59
At first glance, it looks like a dupe of #4142.

**Comment by fmarier** [comment] 2019-09-09 22:00
I was able to reproduce the problem and I do think it's the same root cause as #4142.

**Closed by fmarier** 2019-09-09 22:00 UTC
Labels: OS/Linux
