### ISSUE TITLE
Youtube forgets previous page position after viewing a video

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#31171] opened 2023-06-20 16:08 UTC
## Description 
When using Youtube in Brave, pressing "back" after viewing a video to return to the homepage will scroll you all the way back up to the top of the page. While the does not appear to refresh, the position you were on before is forgotten and you then have to scroll back down. This is particularly frustrating when you've scrolled for more than a page or two before selecting the content to watch. 

Pressing back should return you to the same spot on the page where you initially tapped on the content you wanted to play. 

## Steps to reproduce 

   1. Visit youtube.com in Brave
   2. Scroll down for a while and then tap on a video
   3. After video is loaded and playing, press the "back" button 

## Actual result 
Youtube returns to the top of the homepage and your previous position is forgotten

## Expected result
Position on the previous page should be remembered

## Issue reproduces how often 
Easily reproduced every time

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Android 13
   
## Brave version
v1.52.126

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No

**Comment by deeppandya** [comment] 2023-07-05 18:40
@Uni-verse please verify the issue on chrome and brave nightly.

**Comment by Uni-verse** [comment] 2023-07-05 18:59
@deeppandya 

Tested on chrome & brave with chromium 114.0.5735.196/114.0.5735.198 respectively and it seems like we are not returning to the previous position when navigating with back button on Brave.

<table><tr><td>Chrome</td><td>Brave</td></tr>

<tr><td>

https://github.com/brave/brave-browser/assets/17885425/370b4905-ed0a-4e08-88d9-d1bfaabd6892

</td><td>

https://github.com/brave/brave-browser/assets/17885425/364611e8-6612-46e4-a131-e9dbf6da5ca3

</td></tr></table>

**Comment by Uni-verse** [comment] 2023-07-05 19:12
> @deeppandya
> 
> Tested on chrome & brave with chromium 114.0.5735.196/114.0.5735.198 respectively and it seems like we are not returning to the previous position when navigating with back button on Brave. Same behavior on Brave Nightly 1.55.09 (Chromium 115.0.5790.56)
> 
> Chrome	Brave
>  31171_chrome.mp4 
>  issue_test_31171_02.mp4

Update: Seems to be intermittent on Chrome upon further investigation

**Comment by ChristianCiach** [comment] 2023-07-07 21:20
I have the same issue on every page when using Brave on Android since I've started using it about two years ago. Absolutely drives me nuts. It doesn't always happen, but it happens at least 50% of the time. I never had this issue with any other chromium based browser, only with Brave.

**Comment by bsclifton** [comment] 2024-10-15 20:55
Hi folks - we had previously address this in https://github.com/brave/brave-browser/issues/29432 and then just recently we made a change to our variations server which disabled the feature causing this problem (see https://github.com/brave/brave-variations/pull/1224 for more info).  This should be working great now.  If anyone is experiencing any issues please reply back here!

This issue should be a duplicate of https://github.com/brave/brave-browser/issues/29432 - I'm going to close as dupe.

Chrome can potentially run into this same issue if you click video links very fast. The timestamp is used for history index.

**Closed by bsclifton** 2024-10-15 20:55 UTC
Labels: site-bug, OS/Android, Android 13
