### ISSUE TITLE
Sorry Brave Stuff, but I have a problem.

### ISSUE THREAD

**Issue by CanalYT** [brave/brave-browser#35280] opened 2024-01-11 21:32 UTC
The YouTube updates the _**Anti-AddBlocker Wall**_.
![AdProblem](https://github.com/brave/brave-browser/assets/87686735/aed4aa51-678a-481b-9a31-72df6dc0e233)
The only thing _I ask is that **they can fix it**!_

**Comment by rebron** [comment] 2024-01-11 22:01
Closing as dupe of https://github.com/brave/brave-browser/issues/35276

**Comment by rebron** [comment] 2024-01-11 22:01
https://github.com/brave/brave-browser/issues/35276#issuecomment-1888037428

**Closed by rebron** 2024-01-11 22:01 UTC
Labels: OS/Desktop

**Comment by CanalYT** [comment] 2024-01-11 23:25
**THANKSUPPORT!**
