### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by rudeboy1one** [brave/brave-browser#26448] opened 2022-11-01 19:53 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.45.116  Chromium: 107.0.5304.91
Operating System: Windows NT 10.0.19044

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. i open brave 
2. and ater 20 seconds to 3 minutes the browser automatically shut down
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/df760700-c482-0f09-0000-000000000000

**Comment by rebron** [comment] 2022-11-02 16:00
closing as dupe of https://github.com/brave/brave-browser/issues/26449

**Closed by rebron** 2022-11-02 16:00 UTC
Labels: crash, OS/Windows, priority/P2, OS/Desktop
