### ISSUE TITLE
Allow disabling the built-in PDF viewer

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1778] opened 2018-10-22 17:31 UTC
There should probably be a checkbox somewhere in settings which let's you turn of PDFJS and just download PDFs instead.

**Comment by Liunkae** [comment] 2018-12-05 20:32
Related: #1531 (allow disabling PDF.js with the command line)

**Comment by SilverPuppy** [comment] 2018-12-10 18:37
I also noticed today in trying to work around the fact that dynamically generated PDFs do not work that the option to download instead of view in Brave does not have any effect. This combination of issues has forced me to keep FireFaux open for a work feature.

**Comment by SilverPuppy** [comment] 2018-12-20 17:37
I just realized that as of the current update this now works correctly.

**Comment by SilverPuppy** [comment] 2018-12-26 20:47
This should be closed. It was always a duplicate and now is resolved.

**Comment by Liunkae** [comment] 2018-12-26 23:58
Yes, please close this issue. It was fixed with brave/brave-core#941.

**Comment by SilverPuppy** [comment] 2019-01-02 19:37
This should be closed.

**Comment by btlechowski** [comment] 2019-01-02 22:14
Dupe of https://github.com/brave/brave-browser/issues/1531, which was fixed in https://github.com/brave/brave-core/pull/941

**Closed by btlechowski** 2019-01-02 22:14 UTC
Labels: extension/PDFJS, feature/global-settings, priority/P3
