### ISSUE TITLE
disable shadow

### ISSUE THREAD

**Issue by zksyncetester** [brave/brave-browser#39484] opened 2024-06-29 13:09 UTC
### Description

add a choice to disable shadow for linux when compositor was disabled

### Steps to reproduce

1. ugly shadow when right click 
2. 
3. 

### Actual result

![1](https://github.com/brave/brave-browser/assets/94652988/b497f133-958b-4fab-b691-d03193c0a34b)

### Expected result

![2](https://github.com/brave/brave-browser/assets/94652988/622e174f-4fa1-42e6-8680-56738b736130)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (64-bit)

### Channel information

- [X] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by roufsyed** [comment] 2024-08-06 23:47
I am facing the same issue.
Any update on this as of yet?

**Comment by UltraDoge** [comment] 2024-08-07 19:05
> I am facing the same issue. Any update on this as of yet?

no i think they never want fix that brave on linux more unstable than other os..

**Comment by snowsh1ne** [comment] 2024-08-08 11:24
Just updated, same issue

**Comment by runlow** [comment] 2024-08-13 01:20
In case anyone else is trying to figure this out - this seems discussed here also and present in chrome as well https://www.reddit.com/r/linuxquestions/comments/17sq1hv/how_to_disable_chrome_context_menu_border/

If I use the compositor `xcompmgr` the problem disappears but for various reasons I don't want to use a compositor.

I haven't found a workaround yet but if I do I can share it.

**Comment by UltraDoge** [comment] 2024-08-13 08:07
> In case anyone else is trying to figure this out - check the solution in #39069

It seems that the problem has been solved in the nightly version, thanks for the information

**Comment by bsclifton** [comment] 2024-09-06 19:57
Closing as duplicate of https://github.com/brave/brave-browser/issues/39069

**Closed by bsclifton** 2024-09-06 19:57 UTC
Labels: OS/Desktop
