### ISSUE TITLE
Many settings are not synchronized when Sync Settings is enabled

### ISSUE THREAD

**Issue by Germs2004** [brave/brave-browser#18191] opened 2021-09-19 00:04 UTC
## Description 
I'm a new user.  Installed Brave on two Windows 10 computers, configured all the settings on computer A to the way I like, enabled Sync on both computers and made sure both had "Settings" selected for sync.  Computer B did automatically update several of its settings to match Computer A, but many settings did not update so I had to spend several minutes manually comparing all the settings to get Computer B configured the way I want.  If I ever change my mind about a setting, I'd have to go through every device and manually update each one since many settings apparently don't sync.

Settings that didn't sync for me:

```
Name your Brave profile
Pick an avatar
Brave colors
Show top sites in autocomplete suggestions
Hide Brave Rewards button
Always show full URLs
New tab page shows
Look & feel > Default view
Social media blocking > Allow Google login buttons on third party sites
Social media blocking > Allow Facebook logins and embedded posts
Social media blocking > Allow Twitter embedded tweets
Social media blocking > Allow LinkedIn embedded posts
WebRTC IP handling policy
Allow privacy-preserving product analytics (P3A)
Clear browsing data (selections inside the window)
Site and Shields Settings > Permissions > Camera
Site and Shields Settings > Permissions > Microphone
Site and Shields Settings > Permissions > Notifications
Default search engines (removed items from the default list)
Hangouts
WebTorrent
Ethereum provider for using Dapps
Continue running background apps when Brave is closed
(and probably several more settings that I didn't test)
```

## Expected result:
Nearly every setting throughout Brave should be immediately updated to match the settings of previously Sync'd computers.  Only a few things like Download Location should be left computer-specific and not sync.  Anything that remotely makes sense to sync should sync so that I can simply enable Sync on a new install and trust that my browser is fully configured the way I want.

## Reproduces how often: 
every time, I assume

## Brave version (brave://version info)
Brave	1.29.81 Chromium: 93.0.4577.82 (Official Build) (64-bit)
Revision	e3a25d9b9e2d0b728e045ec87c0aa4942aa46e4e-refs/branch-heads/4577@{#1237}
OS	Windows 10 OS Version 2009 (Build 19043.1237)

**Comment by Germs2004** [comment] 2021-09-19 03:34
Possible dupe of https://github.com/brave/brave-browser/issues/13555

**Comment by NikharPandya** [comment] 2021-09-26 00:12
@Germs2004 
**The profile setting like**
- Name your Brave profile
- Pick an avatar
- Brave colors
- Show top sites in autocomplete suggestions
- Hide Brave Rewards button 

**are only available on desktop**

**Only the provided setting are synced to devices**
- Apps
- Bookmarks
- Extensions
- History
- Settings
- Theme
- Open tabs
- Passwords
- Addresses and more

Refer to links below 

- https://support.brave.com/hc/en-us/articles/360021218111-How-do-I-set-up-Sync-#:~:text=Open%20Brave%20Browser%20on%20your,your%20devices%20via%20Sync%20Chain%20.&text=You%20will%20be%20taken%20back,in%20the%20sync%20chain%20listed.
- https://brave.com/sync-v2/

**Comment by Germs2004** [comment] 2021-09-26 16:06
I'm sorry, NikharPandya, I don't recognize your point when you point out that certain settings "are only available on desktop."

Though some Brave desktop settings don't apply to Brave mobile, those settings should still sync between multiple Windows desktop clients.

**Comment by NikharPandya** [comment] 2021-09-26 17:08
@Germs2004 
At this moment only the listed settings sync to any synced devices whether it is desktop or Android

**Comment by Germs2004** [comment] 2021-09-30 21:05
Ok, so your point is that you are confirming that my observation is correct.  Those settings don't currently sync, just like I said.  Hence this ticket.

**Comment by NikharPandya** [comment] 2021-09-30 23:47
Yes

**Comment by NikharPandya** [comment] 2021-09-30 23:47
@bsclifton

**Comment by bsclifton** [comment] 2021-11-22 06:27
cc: @AlexeyBarabash @darkdh - not sure if there are any useful troubleshooting steps. It definitely does work for happy path scenario as I use this without issue

**Comment by bsclifton** [comment] 2021-11-22 06:27
Actually- yes; I think this is a duplicate of https://github.com/brave/brave-browser/issues/13555

**Closed by bsclifton** 2021-11-22 06:27 UTC
Labels: feature/sync, feature/settings, OS/Desktop
