### ISSUE TITLE
[Follow up to #42296] `Default` SE is shown in `QSE` settings for `Private Tab`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#42573] opened 2024-11-27 23:45 UTC
### Description

Follow-up to #42296.

### Steps to reproduce

1. Launch Brave
2. Hamburger menu > Settings
3. Search engines > Private Tab
4. Change SE to any available option, for example, `Bing`
5. Go back and tap `Quick-Search Engines` settings > *Observe that `Bing` is still shown*
6. Close the settings
7. Open a new `Private tab`
8. Tap `URL search bar` > Type any query > *Confirm that `Bing` is the 2nd one (first after `Leo`) as expected*
9. Tap ⚙️ icon > *Observe that `Bing` is shown in the first position*

### Actual result

`Default` SE is shown in `QSE` settings for `Private Tab`.

### Expected result

`Default` SE must NOT be shown in `QSE` settings for `Private Tab`.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.74.13 
Chromium: 131.0.6778.85 (Official Build) beta (64-bit) 

### Device

- Brand/model: ANY
- Android version: ANY

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by deeppandya** [comment] 2024-11-27 23:50
@hffvld we only check for standard tab changes.

**Comment by deeppandya** [comment] 2024-12-04 19:16
@hffvld it seems to be the expected behaviour for quick search engines. I am closing the issue based on the discussion during triage.

**Closed by deeppandya** 2024-12-04 19:16 UTC
Labels: bug, QA/Yes, OS/Android, feature/QuickSearch
