### ISSUE TITLE
Only enable Sponsored Background Images on NTP when Brave Rewards is enabled

### ISSUE THREAD

**Issue by urbenlegend** [brave/brave-browser#11889] opened 2020-09-28 17:12 UTC
## Description 
Quite a few people on the Brave subreddit have been complaining about Sponsored Images being turned on by default instead of being opt-in like Brave Rewards. It manifests in the following ways:

1. People are confused why they're being shown ads when they did not opt-into Brave Rewards. They don't even get BAT from them when Brave Rewards is turned off anyways.
2. They don't know how to turn it off or they think its malware.
3. They think it makes the browser feel "bloated"
4. A lot of ads are crypto and some users are freaked out by it.

I propose that sponsored images should not be shown when Brave Rewards is disabled because it confuses users and rubs them the wrong way when they're being shown ads and not earning BAT from them.

## Steps to Reproduce

   1. Restart with a new browser profile.
   2. Do not opt-into Brave Rewards
   3. Notice that Sponsored Images is enabled by default and not grayed out.

## Actual result:
Sponsored Images are shown when Brave Rewards is turned off

## Expected result:
Sponsored Images should not be shown when Brave Rewards is turned off. **Additionally**, the Sponsored Images option in NTP Customize and Settings ->New Tab Page should be **grayed out**

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

Any version

## Android Device details:
Any version

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by Melyyn** [comment] 2020-09-29 00:59
Bump. I agree with this

**Comment by bsclifton** [comment] 2020-09-29 06:51
cc: @mandar-brave @jsecretan

**Comment by tmancey** [comment] 2020-10-06 10:18
@jsecretan Related to https://github.com/brave/brave-browser/issues/11018

**Comment by bsclifton** [comment] 2021-05-13 08:29
Closing as `wontfix` - this is by design; more details can be found in https://brave.com/sponsored-images-now-available-on-all-brave-platforms/

Folks can resolve in one of two ways:
1. Opt-in to Brave rewards to see earnings (from the advertising revenue)
2. Disable the preference. Two clicks - `Customize` button in the bottom right of new tab page and then toggle `Show Sponsored Images`

We do have design criteria for the sponsored images shown, so they should fit the look and feel of the product

**Closed by bsclifton** 2021-05-13 08:29 UTC
Labels: OS/Android, OS/Desktop, blocked, enhancement, feature/ads, needs-discussion, suggestion

**Comment by urbenlegend** [comment] 2021-07-09 18:16
I highly urge you guys to reconsider this bug. New users can potentially be turned off by this and think that Brave comes with adware. Reactions like this https://www.reddit.com/r/brave_browser/comments/ogu86b/i_switched_to_brave_a_month_or_two_ago_loving_it/
are not uncommon. In my personal life, I've always had to explain to people why these ads are shown by default when they have not opted-into Brave Rewards.

I know Brave likes to say that these ads benefit the user because they earn you BAT, but users don't get the BAT if they're not opted-into Brave Rewards in the first place.

**Comment by tmancey** [comment] 2021-07-12 13:26
@urbenlegend this is not a bug and by design. However, you can disable these images by opening a new tab, clicking `Customize` at the bottom-right of the window, and turning off sponsored images.

**Comment by urbenlegend** [comment] 2021-07-12 15:46
I am aware that it is by design and I am aware of how to turn them off. But the opt-out default of this gives a really bad first impression to new users, a lot of whom are coming to Brave to avoid ads and get better privacy protections. My argument here is that when you haven't sold them on the benefits of Brave Rewards and they haven't opted-in, these Sponsored NTP ads that show up anyway look like your average adware that you get when you accidentally install a browser toolbar or extension that you weren't supposed to.

**First impressions matter.** I've tried to introduce Brave to many of my friends and frequently, the reaction is "Why does this browser come with ads?" and I have to explain to them at length about how Brave Rewards works. But even then, it's an uphill battle against skepticism and it leaves a bad taste in the mouth of many new users. You can see that from many of the comments in the Reddit thread I linked. It just adds additional friction when attracting new users.

**It is also hypocritical to say that Brave Rewards is user-respecting and go through a lot of effort to make it opt-in, and then turn around and smash users with a full-page ad anyways without their consent.** It just doesn't make sense. The Brave Rewards onboarding process explains how these ads respect users by being private and opt-in and how they also benefit you by earning BAT, yet these Sponsored Ads are neither opt-in nor earn you BAT when Rewards isn't enabled.

All I am saying is that new users are sometimes not aware of how Brave Rewards works. You should not give them any ads in any form whatsoever without first selling them on Brave Rewards first. It hinders adoption and gives Brave a bad reputation. Brave's ad network gains value when more people are using it and potentially shunning new users away right when they use the browser is just counter-productive.

**Comment by urbenlegend** [comment] 2022-09-29 08:10
This bug really should be considered now that there will be an influx of new users fleeing Chrome's Manifest v3 changes. Again, the sponsored backgrounds give a bad first impression when Rewards are not enabled, as shown by this recent Reddit post: https://www.reddit.com/r/brave_browser/comments/xr1d3f/just_switch_from_chrome_to_brave_for_the_adds/
