### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by AdobeFan16** [brave/brave-browser#40795] opened 2024-09-01 01:40 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.69.160 Chromium: 128.0.6613.114
Operating System: Windows NT 10.0.18362

No URL needed

Can you reproduce this crash?
While browsing

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
I was doing nothing, until it keeps crashing sometimes after a few hours and I'm sick and tired of

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/166a0c00-5a73-850c-0000-000000000000

**Comment by bsclifton** [comment] 2024-09-06 21:47
Closing as duplicate of https://github.com/brave/brave-browser/issues/40246

**Closed by bsclifton** 2024-09-06 21:47 UTC
Labels: crash, OS/Windows, priority/P2, OS/Desktop
