### ISSUE TITLE
You have contributed 2050 Quadrillion BATs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#7612] opened 2020-01-06 18:22 UTC
## Description 
I got this notice on Nightly:

![Screenshot from 2020-01-06 10-17-25](https://user-images.githubusercontent.com/167821/71838659-357ad680-306e-11ea-81b8-bc47f7630bf8.png)

## Brave version (brave://version info)
```
Brave	1.5.13 Chromium: 79.0.3945.88 (Official Build) nightly (64-bit)
Revision	c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS	Linux
```

**Comment by NejcZdovc** [comment] 2020-01-06 19:25
dupe of https://github.com/brave/brave-browser/issues/7562

**Closed by NejcZdovc** 2020-01-06 19:25 UTC
