### ISSUE TITLE
Crash Report On Closing A Tab 

### ISSUE THREAD

**Issue by 0xsha** [brave/brave-browser#34912] opened 2023-12-15 11:20 UTC
Definitely an annoying bug . here is how to reproduce it . 

Brave Version: 1.61.104 Chromium: 120.0.6099.115
Operating System: Mac OS X 14.1.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? 

1. Open a few websites in different tabs (lets say 6-7  tabs )
2. Select one random tab and then right-click select Close Other Tabs 
3. CMD/Ctrl+t open a new tab 
4. Click on the previously selected tab (which still is open from step 2)
5. Crashes

Possibility related :
https://github.com/brave/brave-browser/issues/34835
https://github.com/brave/brave-browser/issues/34890
https://github.com/brave/brave-browser/issues/34899
https://github.com/brave/brave-browser/issues/34898
https://github.com/brave/brave-browser/issues/34909
https://github.com/brave/brave-browser/issues/34905

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/68050400-100a-300b-0000-000000000000

**Comment by rebron** [comment] 2023-12-15 23:46
Closing as duplicate of https://github.com/brave/brave-browser/issues/34909

**Closed by rebron** 2023-12-15 23:46 UTC
