### ISSUE TITLE
Can We Disable Brave Rewards & Crypto Wallets?

### ISSUE THREAD

**Issue by joshxyzhimself** [brave/brave-browser#9107] opened 2020-04-09 05:24 UTC
## Reasons

- Consuming extra Bandwidth
  - Sometimes reaches 300 KB/s which is no joke since internet is expensive
- Consuming extra RAM
  - Not friendly for mid-tier devices
- It annoyingly re-runs when I try to end-process it

![image](https://user-images.githubusercontent.com/60829711/78860675-584dca00-7a65-11ea-9a5d-65587b71e39b.png)

**Comment by joshxyzhimself** [comment] 2020-04-09 05:28
- I'm aware of this one below but I'm talking about totally disabling it as an extension, it wastes my internet, yeah I'm saving $ on these blocked ads BUT I'm getting EXTRA DATA COSTS on these brave rewards and crypto wallets

![image](https://user-images.githubusercontent.com/60829711/78860798-aa8eeb00-7a65-11ea-9d54-b7bba5f3c2ff.png)

**Comment by elemanhillary** [comment] 2020-04-10 03:35
i suggest a toggle button to switch them on and off since some prefer them, and i would be happy to make it happen

**Comment by joshxyzhimself** [comment] 2020-04-10 12:43
Yes even an option to completely disable it as an extension would be valuable.

Really weird to have it running in the backround like a botnet client.

**Comment by NumDeP** [comment] 2020-04-10 23:38
Same as #8742 - They're likely to close this in favour of the other as it's already labelled.

I have the same issue with the interface and that, though surprisingly, this didn't used to occur before. Before it never used to show it and when ever you clicked on **Crypto Wallet** on that multi-coloured banner, then it used to appear and never went off unless you exited the browser.

For your information @elemanhillary, if memory serves me correct, I read that they discussed something about a toggle switch but can't remember what the issue was, I'm positive it pertained to crypto as well.

**Comment by NumDeP** [comment] 2020-04-11 00:15
I'm sure it must have been this https://github.com/brave/brave-browser/issues/6394 and the comment made by Tom.

**Comment by bsclifton** [comment] 2020-04-14 18:02
Closing as duplicate of https://github.com/brave/brave-browser/issues/8742

**Closed by bsclifton** 2020-04-14 18:02 UTC

**Comment by joshxyzhimself** [comment] 2020-06-07 00:25
https://news.ycombinator.com/item?id=23442027
