### ISSUE TITLE
rewards panel hard to distinguish against light

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#28283] opened 2023-02-03 20:01 UTC
## Description 

When opening the rewards panel on a website that's completely white, you'll notice that it's hard to distinguish between Brave and the website. I'm assuming the same issue can happen in `Dark` mode if vising a website that has the same background as the panel due to going into `Dark` mode or using the `Dark` theme. Adding some type of border would probably help.

## Steps to reproduce 

   1. install `1.48.154 Chromium: 110.0.5481.52` (or any version with rewards 2.5)
   2. once installed, ensure that you've enabled rewards and connected to a custodian
   3. visit startpage.com and open the rewards panel
   4. you'll notice it's hard to distinguish between the rewards panel and the website

## Actual result 

![image](https://user-images.githubusercontent.com/2602313/216673268-3f2e8f23-2270-4325-9ce2-23f93a0d88d3.png)

## Expected result

The rewards panel should be easier to distinguish. With the current design, it's hard to tell where it starts/ends.

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A` (going out via `1.48.x`)
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 13`
   
## Brave version

```
Brave | 1.48.154 Chromium: 110.0.5481.52 (Official Build) (32-bit)
--- | ---
Revision | 979113183ded4544a2c443aceb1629c430907e52-refs/branch-heads/5481@{#636}
OS | Android 13; Build/TQ1A.230105.002
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @Miyayes @deeppandya @LaurenWags

**Comment by Miyayes** [comment] 2023-02-03 22:35
Thanks. This is actually a dupe of https://github.com/brave/brave-browser/issues/27257, so we'll get to it :)

**Closed by Miyayes** 2023-02-03 22:35 UTC
Labels: enhancement, feature/user-interface, feature/rewards, QA/Yes, OS/Android

**Comment by kjozwiak** [comment] 2023-02-04 08:55
> Thanks. This is actually a dupe of #27257, so we'll get to it :)

Perfect 👍 Thanks.
