### ISSUE TITLE
Crash on www.merriam-webster.com

### ISSUE THREAD

**Issue by wooque** [brave/brave-browser#24162] opened 2022-07-20 22:14 UTC
## Description 

Searching word on www.merriam-webster.com crashes Brave

## Steps to Reproduce

   1. Open www.merriam-webster.com
   2. Enter any word and press Enter on keyboard

## Actual result:

Whole browser crashes

## Expected result:
Browser completes action without crashing

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave	1.41.99 Chromium: 103.0.5060.134 (Official Build) (64-bit) 
Revision	8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS	Linux
JavaScript	V8 10.3.174.20
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36
Command Line	/opt/brave.com/brave/brave --enable-features=OverlayScrollbar,VaapiVideoDecoder,VaapiVideoEncoder --enable-zero-copy --disable-features=UseChromeOSDirectVideoDecoder --disable-smooth-scrolling --enable-crashpad --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --enable-features=VaapiVideoEncoder,VaapiVideoDecoder,OverlayScrollbar --disable-features=UseChromeOSDirectVideoDecoder --flag-switches-begin --flag-switches-end
Executable Path	/opt/brave.com/brave/brave
Profile Path	/home/vuk/.config/BraveSoftware/Brave-Browser/Default
Active Variations	AdRewardsStudy:NextPaymentDay
AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=12/MaximumInlineContentAdsPerDay=60/AdServingVersion=1
BraveAds.UserActivityStudy:Triggers=NTPSI/TimeWindow=15m/Threshold=0.0/IdleTimeThreshold=5s
BraveDebounceStudy:Enabled
ConversionsStudy:NewDefaultPattern
Default1pBlockingStudy:Disabled
DisableReduceLanguage:Enabled
EphemeralStorageStudy:Enabled
ExtendedVariationsSafeMode5:SignalAndWriteViaFileUtil5
FirstPartyEphemeralDomainBlockStudy:Enabled
ForceDisableBlinkFeatures:Enabled
NativeCosmeticFilteringStudy:Enabled
PartitionBlinkMemoryCacheStudy:Enabled
PartitionConnectionsByNetworkIsolationKeyStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
RequestAdsEnabledApiStudy:Enabled
SpeedreaderReleaseStudy:Enabled

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? /
- Can you reproduce this issue with the nightly channel? /

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Not enabled
- Is the issue reproducible on the latest version of Chrome? /

**Comment by wooque** [comment] 2022-07-20 22:26
Started Brave in fresh user dir `brave-browser --user-data-dir=/tmp/tmp.MJKA6dzSth` it worked at first, but when I closed and started again in the same dir it started crashing. So crashing starts after second opening

**Comment by rebron** [comment] 2022-07-21 00:13
@wooque Can you send your crash report via brave://crashes/

**Comment by rebron** [comment] 2022-07-21 00:15
Possible dupe of https://github.com/brave/brave-browser/issues/24164

**Comment by bsclifton** [comment] 2022-07-21 02:32
Should be fixed by https://github.com/brave/brave-core/pull/14265 - closing out so we can retest

**Closed by bsclifton** 2022-07-21 02:32 UTC
Labels: crash, OS/Desktop

**Comment by GeetaSarvadnya** [comment] 2022-07-21 05:39
Verification PASSED on

```
Brave | 1.41.100 Chromium: 103.0.5060.134 (Official Build) (64-bit)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Windows 10 Version 21H2 (Build 19044.1826)

```
- Verified the STR from the description and ensured there is no crash when searching word on [www.merriam-webster.com](http://www.merriam-webster.com/)
- Verified few popular websites are performed search ensured there is no crash
https://www.amazon.com/
https://www.google.com/
https://www.wikipedia.org/
https://www.flipkart.com/
https://www.ebay.com/

**Comment by srirambv** [comment] 2022-07-21 05:41
Verification passed on Oppo Reno 5 with Android 12 running 1.41.100 x64 build
- Verified able to reproduce the crash on 1.41.99 using steps from issue description
- Verified able to search on website without crashing the browser when upgraded to 1.41.100
- Verified searching on a bunch of websites doesn't cause any crash

**Comment by LaurenWags** [comment] 2022-07-21 12:35
Verified passed with

```
Brave	1.41.100 Chromium: 103.0.5060.134 (Official Build) (arm64) 
Revision	8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS	macOS Version 12.4 (Build 21F79)
```

* Reproduced the issue using `1.41.99` (had to restart to pull griffin seed)
* Confirmed using `1.41.100` there was no crash observed when searching on merriam-webster.com
