### ISSUE TITLE
Default theme should be dark or light depending on OS preference

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#1189] opened 2018-09-19 01:52 UTC
macOS Mojave and Windows 10 support dark vs light appearance themes. Brave should respond to those preferences and default to that OS-level preference, unless the user has explicitly chosen dark or light theme.

**Comment by simonhong** [comment] 2018-11-14 10:11
When `NSRequiresAquaSystemAppearance` is set to true in Info.plist, it overrides system's theme.
Because of this, I got `NSAppearanceNameAqua` always.

**Comment by petemill** [comment] 2018-11-14 21:58
@simonhong the implementation referred to in https://bugs.chromium.org/p/chromium/issues/detail?id=850098 also makes the changes to the code to tell the OS that it supports light / dark appearance modes and also changes the menu background color appropriately. Of course, ours will need to look at ActiveTheme, in case the user changes it.

**Comment by petemill** [comment] 2018-11-14 22:39
@bradleyrichter @rossmoody @bbondy @simonhong @rebron we need to re-think the preferences for light / dark mode again when we land OS appearance support, since there would now be multiple places that this configuration value can come from:

- Operating System (macOS Mojave / Win 10)
- User (Preferences / Welcome screen)
- Channel (Default to Dark for Dev, Light for Beta / Release)

Once the user changes the Brave setting to Light / Dark (away from default) there is no UI for changing it back to track the OS value (as we removed 'Default' in https://github.com/brave/brave-core/pull/774).

So I propose either of the following:
## Option 1 - remove app-level user choice
- If OS supports OS-level light v dark mode:
  - Brave **does not** present an configuration option for light or dark mode
  - Brave always listens to the OS value for dark or light
- If OS does not support OS-level light v dark mode:
   - Present option in settings with the values: _Light_, or _Dark_
   - Brave continues to provide a default based on channel

## Option 2 - more (confusing?) user-choice
- If OS supports OS-level light v dark mode
  - Present option in settings with the values: _Light_, _Dark_, or _Same as macOS_ (or _Windows_)
  - Default to _Same as xyzOS_ (stored as _Default_ under the hood)

- If OS does not support OS-level light v dark mode **(same as current master)**
  - Present option in settings with the values: _Light_, _Dark_
  - Default to current channel-based logic

Option 1 is simplest and seems to fit in with what other apps are doing (including Chromium), but since Settings is advanced anyway then I don't really mind which we go for.

I would also, either way, suggest we consider removing the Channel-based defaults as I question the value: it is no longer a method of determining which channel a user is on since there are and will be many ways to change that.

One downside to Option 2 is that to complicate matters, if we advertise to macOS that we support light / dark mode, but then allow the user to differ the window's dark / ligth appearance separate from the OS then macOS will apply incorrect native UI adornations, e.g. window border tint, context menu color. Brave has this issue right now - we get the light window highlight even when we change our colors to dark, since the OS thinks the Brave window is a regular 'light' window:
![image](https://user-images.githubusercontent.com/741836/48516296-dfb6ef80-e817-11e8-947d-8d020232da03.png)

**Comment by simonhong** [comment] 2018-11-15 03:18
+1 to Option 1.
About channel based default, I think it is the only way to determine active theme type if user doesn't choose their preference and os-level theme doesn't exist.

**Comment by simonhong** [comment] 2018-11-15 09:30
I think we should pending this implementation before upstream CLs are merged into C71.
Or should we apply them in advance?

**Comment by Liunkae** [comment] 2018-11-15 19:03
@simonhong
> One downside to Option 2 is that to complicate matters, if we advertise to macOS that we support light / dark mode, but then allow the user to differ the window's dark / ligth appearance separate from the OS then macOS will apply incorrect native UI adornations, e.g. window border tint, context menu color. Brave has this issue right now - we get the light window highlight even when we change our colors to dark, since the OS thinks the Brave window is a regular 'light' window:

As I mentioned in #1289, you can override the system theme on macOS by using the API [NSApplication.appearance](https://developer.apple.com/documentation/appkit/nsapplication/2967170-appearance?language=objc).

I just ran a quick test and confirmed that this works (my system setting is dark). Each time one of the checkboxes is toggled, NSApplication.appearance is set to a different value, and the window's appearance changes dynamically.

![](https://user-images.githubusercontent.com/19424103/48574834-d55b2b00-e8d5-11e8-9fe4-c34b48d6b35e.gif)

**Comment by petemill** [comment] 2019-02-21 21:17
This is a higher priority now since the supporting mechanisms are in C73 / Brave 0.61 and the OS-support feature will be released in other chromium-based browsers at that time.

**Comment by simonhong** [comment] 2019-02-25 22:44
Started to work on this.

**Closed** 2019-03-13 21:57 UTC
Labels: OS/Windows, OS/macOS, QA/Yes, feature/user-interface, priority/P4

**Comment by btlechowski** [comment] 2019-03-20 09:41
The Windows 10 version has not been fully implemented to the point that it is hidden behind a flag.
Logged https://github.com/brave/brave-browser/issues/3804 as a follow up to this issue.

**Comment by LaurenWags** [comment] 2019-03-20 13:48
@kjozwiak not sure if this one can be marked as passed due to your testing on https://github.com/brave/brave-browser/issues/1289#issuecomment-474673983 ?

**Comment by kjozwiak** [comment] 2019-03-21 04:31
> @kjozwiak not sure if this one can be marked as passed due to your testing on [#1289 (comment)](https://github.com/brave/brave-browser/issues/1289#issuecomment-474673983) ?

Yup, checked this case as well while going through https://github.com/brave/brave-browser/issues/1289. Checked it one more time for this issue 👍 

Verification **PASSED** on `macOS 10.14.3 x64` using the following build:

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

* ensured that `Brave colors: Same as macOS`
* switched themes back and forth under `General` settings on the macOS machine and made sure that Brave adapted as expected.

**Comment by ubuntudroid** [comment] 2019-11-29 09:16
Strangely this has stopped working since it has been implemented. Whenever the system changes its appearance (e.g. based on sunrise/sunset) Brave will just ignore this and stick with the previous theme. You have to manually switch to either dark or light theme in Brave settings and then reselect "Same as macOS" which will then finally make Brave pick up the correct theme.

**Comment by ubuntudroid** [comment] 2019-11-30 16:14
Back with some more info on this: seems that it only does not work when the system changes its theme while the device is sleeping (or locked?). Otherwise it works as expected.
