### ISSUE TITLE
Suggestion: Add option to disable/hide audio mute button on tab

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#6690] opened 2019-10-31 19:06 UTC
## Description 

I've had a surprising number of users report that they very frequently mute a tab playing audio in the background on accident when moving or switching between tabs:

![image](https://user-images.githubusercontent.com/3299098/67977090-9b616280-fbd4-11e9-870d-5b11b8679ba8.png)
Note that there used to be a Chromium flag to enable/disable the mute tab button that was removed.

It may be good for future releases to add the option to disable or hide this feature should users continue to have this issue. 
## Miscellaneous Information:

User reports:
https://community.brave.com/t/please-add-an-option-to-disable-the-tab-audio-muting-button/89927
https://community.brave.com/t/how-do-i-turn-off-the-new-mute-sound-button-in-tabs/87439/3
https://www.reddit.com/r/brave_browser/comments/dow6hb/muteunmute_tabs/
https://www.reddit.com/r/brave_browser/comments/dirtje/tab_disable_mute_toggle_functionality/

**Comment by pSub** [comment] 2019-11-04 14:37
Note that this is especially annoying in combination with pinned tabs. I've a pinned tab with my subsonic  instance and it is really tough to switch to it. Let alone to know which tab it is as the mute button hides the favicon.
![pinned-tab-mute](https://user-images.githubusercontent.com/83842/68128936-f5399380-ff18-11e9-8891-c63e43921b97.png)

**Comment by bsclifton** [comment] 2019-11-05 04:37
Good call, @pSub - I've got that captured in https://github.com/brave/brave-browser/issues/6358 if you wanted to give it a thumbs up 😄

**Comment by pSub** [comment] 2019-11-05 08:09
Thank you @bsclifton, I gave it a thumbs up.

**Comment by TheSarnowski** [comment] 2019-11-08 11:16
Was just lookin' for a way to disable it, as I'm keeping muting tabs instead of closing them, or toggling...
Additional idea: let it ignore middle click on tabs (when someone wants to close tab with middle click...)

**Comment by th317erd** [comment] 2019-11-19 21:32
I am with you on this. Pinned tabs are especially annoying. Maybe just have the mute button not visible unless the tab is active?

**Comment by davidhq** [comment] 2019-12-12 08:30
Very annoying indeed... as much as Brave helps you "stay in the flow" by recently working reliably enough, this thing ejects you out of "the flow" in a split-second... then you say: ah yes, I clicked the mute button again, that's what's happened... I would rate this feature 1 out of 10 or even less. Please consider fixing if possible and thank you for great work :)

**Comment by DrewDogComputers** [comment] 2019-12-19 07:26
I am literally switching back to chrome because of this. Let me guess, one developer wanted the feature and here we are dealing with it... in what world do i want a fucking mute button the size of the 'x' and almost as big as the whole tab so i can fat finger it every, single, fucking, time...

**Comment by NejcZdovc** [comment] 2019-12-19 07:29
@rebron can we maybe up priority on this one?

**Comment by bradleyrichter** [comment] 2019-12-19 19:17
@rebron Perhaps the best solution is to only allow the click-action to occur if the tab is selected. Then you retain the mute/play indicator status and the button usefulness where it's really important.

**Comment by DrewDogComputers** [comment] 2019-12-19 21:09
Or, hear me out: put a toggle to remove this useless 'feature'

**Comment by th317erd** [comment] 2019-12-19 21:28
@bradleyrichter I think having it only show up on an active is a good idea, but I think it will still have the same level of frustration in some cases. For example, the situation is REALLY bad for pinned tabs, and would still be present for users who are trying to rearrange pinned tabs. It is only one extra click to alt-click and select "Mute Site". I feel this "feature" should just be removed altogether, as it will likely be frustrating to most users even if it shows up only on the active tab.

There are also "Mute Tab" extensions on the extension store for users who really want a "fast click" option to mute the tab.

**Comment by bsclifton** [comment] 2019-12-19 23:26
@rebron what do you think about adding a toggle for this (not sure where- appearance? we almost need a new tabs section in settings) and setting the default to OFF (matching Chrome default behavior). For folks wanting it, they could opt-in

**Comment by JoeriTheGreat** [comment] 2020-02-25 14:28
I'm on Version 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit) and the problem is gone!
They fixed it. 
https://github.com/brave/brave-browser/issues/2025

**Comment by felixsanz** [comment] 2020-07-01 11:22
Any update? It's so annoying

**Comment by bartkdm** [comment] 2020-07-01 11:23
> Any update? It's so annoying

I did an update and this is fix for me.

**Comment by felixsanz** [comment] 2020-07-01 11:45
I'm using `Version 1.10.93 Chromium: 83.0.4103.106 (Official Build) unknown (64-bit)` and it's still not fixed

**Comment by eljuno** [comment] 2020-08-10 20:05
+1 from Community https://community.brave.com/t/tab-mute-button/150875?u=eljuno

**Comment by tacosuzy** [comment] 2020-11-17 22:39
Since Brave is chromium based, would it be a chrome thing or would it be possible for Brave to implement this themselves? In chrome latest version and for a while the mute tab button doesn't do anything. I don't know if mute tab is apart of chrome. This is the feature or ability that we or some are looking for for those of us that have many tabs open. Maybe chrome can be looked at to why the mute function doesn't do anything in chrome and try to see if it can be applied to Brave. 

I see people saying not to remove it, it could be looked into to only be able to disable it completely but enabled by default for those that find it useful. 

If Brave could make this happen then I would be using Brave full time but until the mute function can be disabled I am unable to use it and am stuck with chrome.

**Comment by donnybystrom** [comment] 2020-12-27 10:20
+1, I click on this icon almost every time I want to switch to a tab with sound. It is very annoying and an UX mistake, this is not what the user wants most of the time he click on a tab, and the icon occupies most of the space property. Make it a right click feature for god sake.

**Comment by scottschindler** [comment] 2021-03-01 16:32
FWIW, I had to stop using brave solely because of this problem. Once it's fixed, I likely will return.

**Comment by MrCanan** [comment] 2021-03-20 19:07
It is the biggest missing option!
Please add a setting to disable it :)

**Comment by Michael82548** [comment] 2021-04-02 02:48
Please just add an option or flag to disable it in brave://flags

**Comment by nonduality42** [comment] 2021-04-21 15:12
Please add a toggle option of remove this... it's the #1 feature I dont like about brave

**Comment by nonduality42** [comment] 2021-04-21 15:13
> FWIW, I had to stop using brave solely because of this problem. Once it's fixed, I likely will return.

I am pretty close to leaving too... for solely this reason.

**Comment by Michael82548** [comment] 2021-04-21 19:52
Will this issue turn into one of the "easy to fix" issues that never get fixed? https://bugs.chromium.org/p/chromium/issues/detail?id=2469

**Comment by Michael82548** [comment] 2021-04-21 19:52
Will this issue turn into one of those "easy to fix" issues that is "too low" of a priority to get fixed? https://bugs.chromium.org/p/chromium/issues/detail?id=2469

**Comment by Careless** [comment] 2021-05-28 06:27
coming up on 2 years soon without a disable option... 

nice.

maybe these types of stupid features should be held to a vote on whether they're desirable or not. or just put them in the tabs right-click context menu if you really need to mute a tab that badly and also have its last state saved or associated with their respective bookmarks if it's a site you visit often. 

show the icon only when it's muted or change the colour of the text in the tab to identify its current audio state.

these are simple solutions to a practically useless feature induced problem that everyone who doesn't use has to deal with now.

**Comment by machineabuse** [comment] 2021-09-07 17:59
This is desperately needed. I use my browser as a minimal window on the side of my screen and as result my tab real estate is very compressed, resulting in much of the tab being taken up by the mute button. I click that thing unintentionally multiple times a day and never once have I actually needed to use it for anything since I block autoplay audio and video.

I would be willing to wager that a large percentage of the telemetry received from the usage of this button is unintentional clicks.

**Comment by Soleone** [comment] 2021-11-06 20:52
Please give this feature some love. It can be very annoying for people with tons of open tabs, incredibly easy to misclick.

**Comment by Michael82548** [comment] 2021-11-08 01:50
> This is desperately needed. I use my browser as a minimal window on the side of my screen and as result my tab real estate is very compressed, resulting in much of the tab being taken up by the mute button. I click that thing unintentionally multiple times a day and never once have I actually needed to use it for anything since I block autoplay audio and video.
> 
> I would be willing to wager that a large percentage of the telemetry received from the usage of this button is unintentional clicks.

Can confirm that it is true for me. Relying on Telemetry from clicks to keep a feature that you can accidently use by a flawed design is unnecessary and does not make any sense if it was ever implemented.

I use something called left click. It brings up a cool context menu which helps actually confirm that I want to mute a site or not and not accidentally mute a site. This "feature" is more annoying than helpful.

Don't keep a feature in without flags to disable it. Don't repeat what Google has done by removing the option in flags to disable tab search. Really fun for 11.6" Chromebooks when you are trying to actually get work done, and it literally takes up a full tab space.

https://www.reddit.com/r/chrome/comments/nl1ry1/how_to_disable_the_tab_search_after_910447277/
Check out this thread. Look how happy these users are from suffering through an A/B Google experiment with no option to turn the feature off anymore :)

**Comment by Michael82548** [comment] 2021-11-08 02:01
Granted, there is a "mute site" option on right click context on tab, there should be another option called "mute tab". I mean, **It's in Firefox**

Get rid of this stupid thing. Not everyone has an 8K ultrawide monitor at 100% scaling to hold all their tabs at normal size be capable of not having this feature be as annoying.

**Comment by Careless** [comment] 2021-11-08 02:03
it has only been 2 years... I'm sure this request is picking up steam now! /s

**Comment by Michael82548** [comment] 2021-11-08 02:03
Granted, there is a "mute site" option on right click context on tab, there should be another option called "mute tab" (which is what the mute button does). I mean, **It's in Firefox**

Get rid of this stupid thing. Not everyone has an 8K ultrawide monitor at 100% scaling to hold all their tabs at normal size to make this feature any less annoying.

**Comment by Michael82548** [comment] 2021-11-08 02:07
> it has only been 2 years... I'm sure this request is picking up steam now! /s

Yeah! Don't pull a Google and not fix an extremely annoying bug FOR 13 YEARS!
https://bugs.chromium.org/p/chromium/issues/detail?id=2469

**Comment by Ae3NerdGod** [comment] 2021-11-21 22:21
wow, ok, i dont understand why this is taking 3+ years to add a toggle in settings (or even a flag in brave://flags) that turns this on/off. can someone please explain why theres even a hesitation on this? it cant be more than like 40 lines of code, and thats being very generous. since ive switched to brave, this is THE MOST (and pretty much only) outstanding bug ive noticed. you could at least put some padding in the tab to have a clickable area (which i think chrome does) or put like a 500ms delay on the sound icon. on a 1366x768 laptop, this is extremely annoying when trying to research or dev something. 

im 99.9% loving brave except for this one annoying, obvious UI bug. im trying not to be frustrated, but this is just a glaring flaw in your ui thats gone untouched for 3 years. just give us a flag to change at the very least PLEASE.

**Comment by MSRhmn** [comment] 2021-12-04 11:50
It is very annoying when tabs are greater in number, I just moved to brave from chrome, everything looks better except this one.

**Comment by scottschindler** [comment] 2021-12-04 16:17
Brendan (CEO of brave) and his team are looking into this!

https://twitter.com/BrendanEich/status/1467164451665113089?s=20

**Comment by ianbruton** [comment] 2021-12-16 13:14
Please, for the love of whatever you're into, remove this cancerous feature.

**Comment by rebron** [comment] 2021-12-16 17:52
The flag to disable the click-ability of the audio icon is making it's way through the channels 
brave://flags/#tab-audio-icon-interactive 

If you running Nightly, you can try it now.

We're planning on having it available in the next hotfix for 1.33.x before the end of the year. 
https://github.com/brave/brave-browser/issues/19979

**Comment by th317erd** [comment] 2022-04-08 16:38
@rebron It appears a recent update has made this situation even worse (maybe something changed with the upcoming flag addition?). Now I can easily mute tabs again, and worse, they can not be unmuted! If I accidentally click the icon, then the site will mute, but if I right click, the menu says "Mute site", which does nothing, except turn into "Unmute site"... which also does nothing when clicked. The icon still shows muted, and the site is still muted.

When this happens, there is no way to unmute the site, unless you get really "lucky". It is almost like there are only a few pixels of the icon that are clickable. One must click click click click click everywhere on the icon over and over again to FINALLY get the site to unmute.

This went from bad user experience to simply broken. You might want to run a little more testing on your side to see if there was a regression... because since an update from a week or two ago it certainly feels like a regression.

**Comment by th317erd** [comment] 2022-04-08 16:48
@rebron I got it! I was able to capture the issue in-progress, and also was able to find steps to reproduce 100% of the time. See attached video.

Steps to reproduce:
1) Start the browser with a fresh instance (this seems important)
2) Start media on some pinned tab
3) Move to another pinned tab
4) Mute the pinned tab with audio playing
5) Now activate the pinned tab with audio playing
6) There is no way to unmute the site now

https://user-images.githubusercontent.com/4420452/162486417-e27e1b9a-393b-4ef6-9785-333b11986d25.mp4

**Comment by FeelTheWay** [comment] 2022-04-21 11:10
Worst feature ever. It drives me crazy everytime I'm clicking on a tabs and mute it . grrrr

**Comment by mafflin** [comment] 2022-04-24 19:36
The flag is now brave://flags/#enable-tab-audio-muting

**Comment by palmier3** [comment] 2022-05-21 14:23
I can share my experience too: I have spotify pinned. For months it worked ok to play music and click the tab, but at some point after an update, this changed. Now I cannot click the tab without slowing down my workflow and being super cautious not clicking the mute button. After I click it I cannot even unmute the site anymore: it seems muting by clicking the tab is decoupled from the "right click -> mute" option. The tab can be unmuted by doing some magic, like pausing the music, then playing again and then trying to unmute (I'm sure someone can reproduce this, I'm not gonna bother).
It's is puzzling that this kind of behavior didn't get fixed and that it even gets worse... for now I'm going to disable it.

**Comment by DevilEars** [comment] 2022-05-24 20:39
> I am literally switching back to chrome because of this. Let me guess, one developer wanted the feature and here we are dealing with it... in what world do i want a fucking mute button the size of the 'x' and almost as big as the whole tab so i can fat finger it every, single, fucking, time...

I literally switched to Brave because I could no longer disable this abomination on Chrome. There should not be any media controls on a tab on an icon there. Brave wisely had a feature whereby this abomination could be entirely removed. I hope this option makes its way back so I can remove the media controls from tabs where they do not belong in the first place

**Comment by DevilEars** [comment] 2022-05-24 20:47
> > FWIW, I had to stop using brave solely because of this problem. Once it's fixed, I likely will return.
> 
> I am pretty close to leaving too... for solely this reason.

To be fair I do not think this is Brave at all. Brave has fixed this and allowed config to remove this mute button nonsense on a tab entirely. I suspect it's a Chromium thing because that's how it broke in the first place.

I still fail to see why a browser tab needs media controls at all.

**Comment by machineabuse** [comment] 2022-12-02 04:23
As of today, I've noticed that the flag has disappeared from brave and has stopped working. Needs a fix asap.

**Comment by fallaciousreasoning** [comment] 2022-12-05 21:29
Okay, I just worked out what's going on - Chromium set the tab-audio-muting flag to expire after 107. As a temporary solution, if you enable chrome://flags/#temporary-unexpire-flags-m107 then you should be able to use the #tab-audio-muting flag again. I'll look into a more permanent solution.

**Comment by bradleyrichter** [comment] 2022-12-09 22:38
ok, here is the proposed solution. I'll let you all find it and comment. (the toggle would be available in Appearance for now and off by default)

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/13509546/206806752-26aee023-92df-4f7c-b450-ce9e14975768.png">

**Closed** 2022-12-13 22:49 UTC
Labels: feature/tabs-bar, feature/global-settings, priority/P3, QA/Yes, release-notes/include, audio, feature-request, OS/Desktop

**Comment by MadhaviSeelam** [comment] 2023-01-18 23:20
Verification `PASSED` using
```
Brave | 1.48.131 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```
Case 1: Mute indicators are not clickable  -`PASSED`
<details>

1. Install 1.48.131
2. launch Brave
3. open `brave://settings/appearance`
4. confirmed `Disable mute function in tab speaker icons` setting is available and toggled `Off` as a default
5. open few audio playing tabs 
6. click on the speaker icon of an audio playing tab
7. confirmed audio is muted as expected
8. return to  `brave://settings/appearance`
9. toggle `On` `Disable mute function in tab speaker icons` setting
10. click on the speaker icon of audio playing tab 

#### Confirmed speaker icon is not clickable when  the setting is enabled

ex1|ex2|ex3
----|-----|----
<img width="653" alt="image" src="https://user-images.githubusercontent.com/98358127/213315386-34d221ca-d7b3-4de8-900f-a801a3c68da4.png">|<img width="656" alt="image" src="https://user-images.githubusercontent.com/98358127/213315401-06d77df7-d89d-4b17-a375-ad3ba0d0ead1.png">|<img width="425" alt="image" src="https://user-images.githubusercontent.com/98358127/213315298-4d3348b9-8a05-4976-9fef-5056a0fdd807.png">
</details>

Case 2: Mute tab/Unmute tab in the context menu - `PASSED`
<details>

1.  new profile
2. `Disable mute function in tab speaker icons` setting is disabled as a default
3. right click on audio playing tab to open context menu
4. confirmed `Mute tab` is available above existing `Mute site` option
6. confirmed audio playing tab is muted successfully
7. clicked Unmute tab in the context menu
8. confirmed audio played again

#### Confirmed Mute tab/Unmute tab works as expected.

ex1|ex2|ex3|ex4
---|----|-----|----
<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/213314970-381bac7b-9590-4013-81ae-8bee9ca843a6.png">|<img width="326" alt="image" src="https://user-images.githubusercontent.com/98358127/213291602-acf4cb3c-ca4d-44c8-93ec-e52d13dd6db7.png">|<img width="324" alt="image" src="https://user-images.githubusercontent.com/98358127/213291800-81436920-773e-406a-822f-a5a82cdae7f7.png">|<img width="326" alt="image" src="https://user-images.githubusercontent.com/98358127/213292060-64a166d7-2034-4fd3-a8b3-beec1381ee80.png">

</details>

Case 3: Mute site/Unmute site in the context menu - `PASSED`
<details>

1. continue from Case 1: 
    - `Disable mute function in tab speaker icons` setting is enabled
    - Mute indicator is not clickable
2. right click on audio playing tab to open context menu
3. confirmed `Mute site` is available above existing `Mute site` option
4. confirmed audio playing tab is muted successfully
5. clicked Unmute site in the context menu
6. confirmed audio played again
7. click again `Mute site` and click `Unmute tab`

#### Mute site/Unmute site worked as expected and Mute tab/Unmute Tab over rides the option

ex1|ex2|ex3|ex4
----|-----|-----|----
<img width="457" alt="image" src="https://user-images.githubusercontent.com/98358127/213315727-03eb94d0-dc4e-4554-ae53-1f2db295439c.png">|<img width="132" alt="image" src="https://user-images.githubusercontent.com/98358127/213305605-b217330c-35b6-40ba-80e6-047ce7ab1726.png">|<img width="133" alt="image" src="https://user-images.githubusercontent.com/98358127/213305641-3be35e02-8088-4421-8536-e13aea6d58e0.png">|<img width="128" alt="image" src="https://user-images.githubusercontent.com/98358127/213305690-0d383c65-a5b9-421c-b494-cf05bcd1158a.png">
</details>

Case 4:  Mute/Unmute audio playing  pinned tabs and multiple tabs open  - `PASSED`
<details>

1. new profile 
2. `Disable mute function in tab speaker icons` setting is disabled as a default
3.  pin couple of tabs
4. play media on one of the pinned tab
5. switch to another pinned tab 
6. Mute the pinned tab with audio playing
5. confirmed audio playing tab is muted successfully
6. activate the pinned tab with audio playing
7. clicked Unmute tab in the context menu
8. confirmed audio played again

#### Confirmed Mute/Unmuting audio works on pinned tabs
#### Confirmed when audio playing tabs are clicked, tabs are activated instead of muting the audio

ex1|ex2|ex3|ex4|ex5
-----|-----|----|-----|-----
<img width="122" alt="image" src="https://user-images.githubusercontent.com/98358127/213313173-8152070e-ccae-4e92-a609-b38bca0766ed.png">|<img width="141" alt="image" src="https://user-images.githubusercontent.com/98358127/213313435-fd84d5e4-83d6-45ff-b810-2814fd6e7791.png">|<img width="125" alt="image" src="https://user-images.githubusercontent.com/98358127/213313630-a8cf3074-96fb-46ea-875f-51e3fc4f842a.png">|<img width="124" alt="image" src="https://user-images.githubusercontent.com/98358127/213313674-7dd574d7-7316-41c5-843a-b1a132573d76.png">|<img width="119" alt="image" src="https://user-images.githubusercontent.com/98358127/213313758-5099707e-ed5b-43c9-9193-2999a9b728be.png">

</details>

**Comment by stephendonner** [comment] 2023-01-18 23:36
## Verification `IN-PROGRESS` using 

Brave | 1.48.131 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

### Case 1: Mute indicators are not clickable
<details>

</details>

### Case 2: Mute tab/unmute tab in the context menu
<details>

</details>


### Case 3: Mute site/unmute site in the context menu
<details>

</details>


### Case 4: Mute/unmute audio playing pinned tabs and multiple tabs open
<details>

</details>

**Comment by MadhaviSeelam** [comment] 2023-01-24 21:23
Verification `In progress` using 
```
Brave | 1.48.137 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Linux
```

**Comment by rubyFeedback** [comment] 2023-03-19 22:28
I also encountered this issue - just providing more information, although in Thorium. I ended up here, via a Google search though. :-)

I started to research this because it happened for the third time now. Especially when I have many tabs open.

The feature is not useless, but it conflicts with my browsing behaviour, and since it interfered once too often in my case, I decided to invest time into researching how to get rid of it. Going back to the roots, keeping it simple. :-) (Actually, if it is a video I am playing such as on youtube, I tend to click on the video to stop it; and if I have to insta-close it, I just close the tab directly via mouse or keyboard command, so the disable audio button isn't too terribly useful anyway in my case.)

**Comment by fallaciousreasoning** [comment] 2023-03-20 20:17
@rubyFeedback in Brave we have a setting for enabling/disabling this behaviour if you want to try it out?
1. Open brave://settings/appearance
2. Turn the `Disable clickable tab mute indicators` setting on:
![image](https://user-images.githubusercontent.com/7678024/226455331-ee610b63-802e-4fd1-a61f-967e550ecf7a.png)

**Comment by rguerrettaz** [comment] 2023-04-16 19:31
Thank you! 🙏

**Comment by wesleysd1989** [comment] 2023-11-20 22:21
I think this function should be disabled by default, my god, I spent a few minutes researching whether it is possible to disable it, annoying feature, you keep missclick, I imagine that many people prefer to change browsers instead of using Brave , why keep a feature with usability problems enabled by default?
