### ISSUE TITLE
Brave freezes completely on download from any site

### ISSUE THREAD

**Issue by andreasraskeland** [brave/brave-browser#3318] opened 2019-02-12 07:36 UTC
## Description 
Brave freezes completely on download from any site. Force shutdown needed.

## Steps to Reproduce
   1. Open Brave 
   2. Go to https://laptop-updates.brave.com/latest/winx64

## Actual result:
Brave is still open, but any click makes a windows sound and nothing else.

## Expected result:
Download should complete and Brave should continue to function.

## Reproduces how often: 
Several times a day for a couple of days.

## Brave version (brave://version info)
Brave Software Inc
Copyright 2019 Brave Software Inc. All rights reserved.
Brave	0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit) 
Revision	ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS	Windows
JavaScript	V8 7.2.502.24
Flash	(Disabled)
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36
Command Line	"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,AutofillSaveCardSignInAfterLocalSave,AudioServiceOutOfProcess,AutofillServerCommunication,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path	C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\andreas.askeland\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations	c134752e-f685ead3
2c707b42-dcf7018a
411b6d4e-3f4a17df
d01ab0d3-5ac8943
3e006338-3f4a17df
1a0d11d4-2f9febdf
66df3e9d-a85d0b2f
b7e2524c-c92d551c
411c711e-3f4a17df
b3888d8d-afba0f91
61832c80-3f4a17df
cc20827f-77c422c
1d411afe-60fc1672
591560a-29acad4
2db4845-ace4e138
74785582-3f4a17df
241fff6c-ddf20878
9853922b-3f4a17df
9def365c-9def365c
2342e907-3f4a17df
9ca1387e-3f4a17df
1c752ce9-1c752ce9
41e765a5-3f4a17df
ab3d6cfd-3f4a17df
776de70c-e0278d3d
ed9149a9-3f4a17df
a5cb8590-3f4a17df
34d450b1-3f4a17df
6c6c4f61-3f4a17df
8f4db35c-3f4a17df
76b48ab8-d4bd105c
c70841c8-a2567007
14bdbe54-e8c7a65b
d8343fa3-3f4a17df
8ee5ed19-c3125ea2
74658432-fa79b94c
7f7844ec-69483e07
9e201a2b-3f4a17df
27212adc-27212adc
591576c8-3f4a17df
249dd49a-3f4a17df
5274eb09-3f4a17df
36115667-3f4a17df
ceff87ec-3f4a17df
44827ee5-3f4a17df
8ca44045-3f4a17df
3f79ac13-3f4a17df
8f1e27f-3f4a17df
edbcf7c5-ddf1844d
77bbdddc-3f4a17df
5485fc4d-3f4a17df
de47491b-3f4a17df
93731dca-3f4a17df
9b4c4257-3f4a17df
8fa604e0-ace4e138
43f62d3b-3f4a17df
4ae380f4-3f4a17df
165e16d1-3f4a17df
9e5c75f1-30e1b12b
6fa07eb4-7282ca76
2981bcb4-3f4a17df
5139837c-3f4a17df
4934552d-3f4a17df
7f8176d9-3f4a17df
f7217a71-b2047178
23a898eb-fc93cf74
7a5ba892-3f4a17df
d1cd70a5-80f9a33e
4ea303a6-3f4a17df
b19465ab-b19465ab
e5373d71-3d47f4f4
6e6e0c7e-3f17a7d8
95876445-2b71ffe4
d92562a9-441539fd
2b33233e-881ca6c9
b363a81f-3f4a17df
4da5ae82-3f4a17df
56302f8c-2f882e70
14c5a050-61ceed18
dc5b1f29-dc5b1f29
cc54eb06-803f8fc4
cac0a91c-3f4a17df
df072bba-9a6c5085
f56e0452-3f4a17df
8576baf1-3f4a17df
f3ea30a0-3f4a17df
3038aa2e-3f4a17df
51b9b54d-3f4a17df
7345ea6-3f4a17df
9a2f4e5b-4bc735ae
1354da85-f1a864dc
17507c76-3f4a17df
6844d8aa-669a04e0
494d8760-3f4a17df
f9e5da91-508355f5
fcdd9ed9-fcdd9ed9
3a4029d-d7f231f3
bbb8f811-3f4a17df
b0ea13bc-3f4a17df
41aa6aaa-da82a76f
94e68624-803f8fc4
cc73f8a1-3f4a17df
b4e8892d-3f4a17df
10a311eb-10a311eb
8834fcca-3f4a17df
6204e469-3f4a17df
ea0f933d-29e3c6de
493ac2c5-803f8fc4

### Reproducible on current release:
- Don't know.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No.
- Is the issue reproducible on the latest version of Chrome? 
No.

**Comment by srirambv** [comment] 2019-02-12 11:43
Do you see the freeze after selecting the location to save and see the download bar? Could be the save file prompt is hidden from view making it look like the browser is frozen. Use Alt+Tab to bring the save file prompt to focus and check if it fixes the issue

**Comment by GeetaSarvadnya** [comment] 2019-02-12 12:52
Not reproducible on 0.59.35 - Windows 10 x64

**Comment by andreasraskeland** [comment] 2019-02-12 15:05
> Do you see the freeze after selecting the location to save and see the download bar? Could be the save file prompt is hidden from view making it look like the browser is frozen. Use Alt+Tab to bring the save file prompt to focus and check if it fixes the issue

[Screen recording](https://andreasraskeland.keybase.pub/brave)

**Comment by andreasraskeland** [comment] 2019-02-13 08:10
I guess the save file prompt is hidden completely or crashed.

**Comment by Typositoire** [comment] 2019-09-06 18:29
I currently have the same issue, even if I cancel the download it stays frozen for like 4-5 seconds until I can click anywhere in the browser `Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)`

**Comment by bsclifton** [comment] 2019-10-08 18:39
Closing as this appears to be resolved 😄 Let's re-open if this happens again

**Closed by bsclifton** 2019-10-08 18:39 UTC
Labels: crash, need-more-info

**Comment by gio888** [comment] 2020-11-20 06:41
This happens in Mac OSX as well (MacbookAir 2017, Catalina). And happens also in Chrome (Version 86.0.4240.198 (Official Build) (x86_64)). So it seems something in the common open source code.

This happens only when downloading and creating a new folder to download to. It doesn't to happen when you're not creating a new folder.

**Comment by itsmagu** [comment] 2022-04-03 01:13
Happens to me on windows 10.

**Comment by itsmagu** [comment] 2022-04-04 17:40
It happens everytime i download something, it then waits for a response from explorer.exe? And catches up after a few seconds. Does not happen when i boot into Linux.

**Comment by roufsyed** [comment] 2022-04-27 05:59
The same is happening on my machine as a well.
Machine config: Ubuntu 22.04
i5 processor
amd64
brave-browser version: 100.1.37.116

**Comment by roufsyed** [comment] 2022-04-27 06:00
The same is happening on my machine as well.

Machine config: 
    Ubuntu 22.04
    i5 processor
    amd64
    brave-browser version: 100.1.37.116

**Comment by rhernandezch** [comment] 2022-05-11 00:48
Try running `sudo apt install xdg-desktop-portal-gnome` and restarting the system, that worked for me an a number of people.

**Comment by sergefdrv** [comment] 2022-05-11 09:19
> Try running `sudo apt install xdg-desktop-portal-gnome` and restarting the system, that worked for me an a number of people.

Wow, it really works! Thanks a lot!

**Comment by sergefdrv** [comment] 2022-05-18 08:58
Looks like fixed in v1.38.119 and doesn't require installing `xdg-desktop-portal-gnome` anymore.

**Comment by denniskb** [comment] 2022-08-05 21:00
Same problem on Ubuntu 22.04LTS, Brave 1.42.86. Bringing up the file open dialog (whether for uploading or saving files/images/...) and closing it again (having opened/saved a file or not) freezes that particular Brave window (incl. all its tabs). Other Brave windows are un-affected. Happens with any combination of window manager: wayland/X11 (OS) <=> wayland/X11 (Brave). Above fixes don't help.

**Comment by bsclifton** [comment] 2022-09-13 17:42
@brandonblack can you please create a new issue with your details? (this one is from 2019 and we don't want to re-use issues)

Sounds like you worked around it? Can you share more about that in the issue too? Thanks! 😄

**Comment by DanieleMDiNosse** [comment] 2023-03-01 13:14
I experienced the same issue and also for me the installation of xdg-desktop-portal-gnome solved the problem.

**Comment by jcgit1** [comment] 2024-06-29 04:45
Apparently still an issue with version v.1.67.123
