### ISSUE TITLE
Autoplay Blocking not working on Brave 

### ISSUE THREAD

**Issue by Zorin-Dev** [brave/brave-browser#9597] opened 2020-05-03 10:26 UTC
Autoplay Blocking not working on all sites. I switch autoplay off and videos still playing automatically on all sites (YouTube ....etc)

Brave Desktop v1.8.86 on Archlinux

Thanks,

**Comment by ahmed0x7ce** [comment] 2020-05-04 00:36
the same issue here but just with Youtube:
![image](https://user-images.githubusercontent.com/22503811/80929895-2ba87c00-8d9f-11ea-9057-e1fae210e777.png)

**Comment by Johann999** [comment] 2020-05-04 11:50
Since version 1.8.86 on Windows all Videos played automatically.
Chromium and other browsers don't.

**Comment by Bj007pro** [comment] 2020-05-05 17:22
Funny thing is, this isn't even a bug, it's just the default setting for autoplay has been changed back to "Always" from "Block".

**Comment by bsclifton** [comment] 2020-05-05 18:23
cc: @pes10k

**Comment by pes10k** [comment] 2020-05-05 18:24
cc: @pilgrim-brave

**Comment by jonahcoyote** [comment] 2020-05-05 22:49
I'm seeing this behavior too and even though the default changed, it's gotta be a bug. I'm on sites where autoplay block used to work and now it doesn't... I've tried toggling autoplay block on/off and restarting Brave. Just updated to the latest today. Hope this gets fixed soon!

**Comment by Johann999** [comment] 2020-05-06 09:15
![blick](https://user-images.githubusercontent.com/53431361/81160744-c1542f00-8f8a-11ea-9900-c971b3472d18.png)

In version 1.8.xx the video in the top left is played automatically, but not in version 1.7.98.

**Comment by Snaxeko** [comment] 2020-05-23 23:35
Same issue, it's not asking me if I want to block autoplay or not. About 2 months ago it was perfectly working.

**Comment by TheAresjej** [comment] 2020-05-25 22:14
as if someone were asking why adding youtube to the exceptions is a stupid idea... 😉
https://scirra.com/store/royalty-free-game-templates
same on **Windows** 10 / **Brave** Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Brave should block all videos autoplay 😋

**Comment by pes10k** [comment] 2020-05-25 22:17
Brave has mostly removed any differences w/ Chromium dealing autoplay, mostly bc Chromium has gotten much better about autoplay since way back when when Brave started going with a list approach (that got too tricky to manage).

Are you seeing differences between what Brave and Chrome do (re autoplay)?  If so, thats likely a bug.  If not, then thats likely the current intended behavior

**Comment by Ziusudra** [comment] 2020-05-29 22:40
The thing is, even if you specifically add a site to the option's block list, its videos will still autoplay. Are you actually saying that having an option that does not do what it claims and has no effect is intended?

**Comment by timkgh** [comment] 2020-05-29 23:29
It seems to work for me if I add `[*.]cnn.com` to the block list.

**Comment by pes10k** [comment] 2020-05-29 23:44
@pilgrim-brave should this be fixed with the recent autoplay fix?  If so, could we uplift?

**Comment by Ziusudra** [comment] 2020-05-30 00:39
> It seems to work for me if I add `[*.]cnn.com` to the block list.

So yes, adding [*.]cnn.com does stop videos from autoplaying on cnn.com - too bad I never go there. If I add `[*.]reddit.com` and `[*.]gfycat.com` to the block list, videos still autoplay on https://www.reddit.com/r/gfycats/. Article pages on `[*.]theroot.com` still autoplay a "recent video".

**Comment by timkgh** [comment] 2020-05-30 00:45
Not sure if you need to block the domains where videos are loaded from or the domain you are on. May be worth looking at the source of one of the videos and trying to block that.

**Comment by Ziusudra** [comment] 2020-05-30 00:51
The address of the gfycats is gfycat.com; the address of the videos on theroot is theroot.com. Adding `[*.]akamaihd.net` does not stop them from autoplaying on steampowered.com.

**Comment by pes10k** [comment] 2020-05-30 01:33
just to repeat, there is a known bug, we expect to have a fix in nightly Monday or Tuesday, and to uplift to other channels ASAP afterwards

**Comment by umbraesoulsbane** [comment] 2020-05-30 01:36
Bless you @pes10k !

**Comment by pes10k** [comment] 2020-06-02 21:09
@umbraesoulsbane please direct that praise to @pilgrim-brave :)

**Comment by Johann999** [comment] 2020-06-16 12:24
This bug is very annoying. Please correct.
Thank you.

**Comment by bsclifton** [comment] 2020-06-29 15:29
Re-opening after revert done with https://github.com/brave/brave-core/pull/5966

**Comment by Snaxeko** [comment] 2020-06-30 16:12
Is it fixed on nightly ?

**Comment by pes10k** [comment] 2020-06-30 19:51
@Snaxeko unfortunately, we hit another snag here, and found a couple of corner cases the update broke. So, this is the PR to watch that should solve in nightly once and for all 🤞 https://github.com/brave/brave-core/pull/5970

Its turned out to be a surprisingly subtle and tricky thing to get 100% right.  Thanks for bearing with us

**Closed** 2020-06-30 23:01 UTC
Labels: OS/Desktop, QA/Test-Plan-Specified, QA/Yes, bug, feature/autoplay, priority/P2, regression

**Comment by btlechowski** [comment] 2020-07-08 08:41
Marking as QA/Blocked - need a new build to test, 1.11.92 or newer.

**Comment by LaurenWags** [comment] 2020-07-08 11:56
Removing `QA/Blocked` label since https://github.com/brave/brave-browser/releases/tag/v1.11.92 is available

**Comment by kjozwiak** [comment] 2020-07-09 05:38
Verification **PASSED** on `macOS 10.15.5 x64` using the following build:

```
Brave | 1.11.92 Chromium: 84.0.4147.68 (Official Build) dev (64-bit)
-- | --
Revision | e7b7234037639b407e69c5428c891ce018cd6c0d-refs/branch-heads/4147@{#772}
OS | macOS Version 10.15.5 (Build 19F101)
```

* Verified using the STR/Case outlined via https://github.com/brave/brave-core/pull/5970#issue-441582754.

**Comment by Johann999** [comment] 2020-07-16 22:46
Bug has not been fixed in version 1.11.97.

**Comment by pes10k** [comment] 2020-07-16 22:48
@Johann999 just so we can recreate exactly what you're seeing, can you please share a link to a site thats demonstrating the behavior, and the behavior you're expecting?  We can then better sort out whats going wrong

**Comment by Johann999** [comment] 2020-07-18 09:00
the video in the top left is played automatically:
![blick tv](https://user-images.githubusercontent.com/53431361/87849063-e992cf00-c8e5-11ea-9dda-e0b89caf2d9c.jpg)

**Comment by pes10k** [comment] 2020-07-19 03:07
Thanks @Johann999 good catch!  I'm realizing that currently we don't do anything with that settings (its just vestigial, from the previous approach, where Brave's policy was different than Chrome's).

Im going to open a new issue for this, since its different from what we were using this issue to track (which was "change Brave so that it does what chrome does, now that chrome has better autoplay policy than it used to").  We'll use https://github.com/brave/brave-browser/issues/10807 to track that discussion, if you're interested. 

Thanks again for taking the time and letting us know about this @Johann999 !

**Comment by darkdh** [comment] 2020-07-19 04:08
@Johann999 you have to manually specified block autoplay in content setting.

**Comment by darkdh** [comment] 2020-07-19 04:19
Just verified 

per site autoplay setting works
<img width="882" alt="Screen Shot 2020-07-18 at 21 14 24" src="https://user-images.githubusercontent.com/11330831/87866911-2ee1eb80-c93c-11ea-97b1-e3ef0e94bb0d.png">

global autoplay setting doesn't work
<img width="874" alt="Screen Shot 2020-07-18 at 21 16 35" src="https://user-images.githubusercontent.com/11330831/87866913-31dcdc00-c93c-11ea-96b2-12645b468f45.png">

**Comment by timkgh** [comment] 2020-07-19 17:17
That used to be such a valuable feature of Brave, the #1 reason why I used Brave. I do not understand why browsers in general do not give an option to users to not autoplay videos. It is super annoying when videos start blasting their audio, with a delay after a page loads. It feels like it's such a basic feature to provide.

**Comment by warwickmm** [comment] 2020-07-19 17:35
For me, neither the global setting nor the site specific setting will block autoplay on cnn:

https://www.cnn.com/2020/07/19/politics/unemployment-benefits-economy-congress/index.html

However, if I create a new profile, then the global setting does block autoplay on the above.

**Comment by Johann999** [comment] 2020-07-20 08:53
As mentioned above, I made the following settings:
![autoplay setting](https://user-images.githubusercontent.com/53431361/87918553-e4b15500-ca76-11ea-960f-0db85c8aa876.jpg)

Autoplay on www.blick.ch is now blocked:
![blick tv blocked](https://user-images.githubusercontent.com/53431361/87918769-2a6e1d80-ca77-11ea-8a0c-9580215f564d.jpg)

Many thanks.

**Comment by Snaxeko** [comment] 2020-10-12 19:06
The issue isn't fixed at all, and Brave doesn't ask anymore if I want to allow or block it on each new website. 

Just try [here](https://www.ouest-france.fr/sante/virus/coronavirus/covid-19-cas-en-hausse-deuxieme-vague-forte-l-epidemie-devient-elle-incontrolable-701144) (no fast refresh, click on the logo then on any article) , 2 hypotheses:

1) Autoplay is blocked in brave://settings/content/autoplay like in the previous comment with the old Brave setting (global blocking option).
--> It works only if you refresh. But if you go for the first time on any article of this website, it will autoplay video. Everytime i go back to the home page then clicking on any article, the video autoplays.

2) Autoplay (previous setting) is not blocked, it should ask for each new website I visit like in Chrome. 
--> It doesn't ask anything, no pop up from Brave, the video autoplays. 


Now I try on another website that asks me if I want to enable autoplay or not (2nd hypothesis), like [here](https://www.allkeyshop.com/blog/) (Twitch video).
--> It works only the first time, when Brave pops up the window that ask me if I want to allow or block autoplay. If I click on block, it will not work the second time i go on the website.
It's probably because I'm now in the 1st hypothesis, i.e. old Brave setting that doesn't work. Instead of using the old buggy setting, why not fixing this issue by just **disabling the popup if the user clicks on "block"** ? 

Using Brave V1.15.72
Issue #10807 is irrelevant here

**Comment by vrindavan** [comment] 2021-06-19 02:20
Is this available in Windows? I never knew about this feature.
