### ISSUE TITLE
Torrents going into RAM

### ISSUE THREAD

**Issue by daphnei-mee** [brave/brave-browser#14814] opened 2021-03-18 16:48 UTC
## Description 

When downloading torrents in Brave, they are stored in RAM. This means that if your torrent is larger than your RAM, it will crash the tab.

## Steps to Reproduce

   1. Download a torrent larger than your RAM and wait for it to finish/fill up your ram.
   2. 
   3. 

## Actual result:

The tab either freezes, or the torrent finishes and then the tab crashes once you try to save it.

## Expected result:
The torrent should be downloaded in a temporary file rather than in RAM

## Reproduces how often: 

Every time a torrent larger than your available RAM is downloaded, and even sometimes when the torrent is smaller. 

## Brave version (brave://version info)

1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by srirambv** [comment] 2021-03-19 03:18
Dupe of #5563

**Closed by srirambv** 2021-03-19 03:18 UTC
Labels: OS/Desktop
