### ISSUE TITLE
Welcome page slides are not centered

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#6846] opened 2019-11-08 18:22 UTC
![Screen Shot 2019-11-08 at 3 21 35 PM](https://user-images.githubusercontent.com/4672033/68500862-79528a80-023b-11ea-96ad-6c948ecbb595.png)

Bug affects 0.72.x onwards.

## Test Plan

1. Navigate through slides
2. Assert slide content is not properly aligned

### Jumping content (from @petemill)
1. Open brave://welcome
2. Move to slide 2
3. Observe position of content
4. Hover over 'import' button
4. Observe content jumps to a different position

**Comment by bsclifton** [comment] 2019-11-11 04:28
@cezaraugusto can you add a test plan? What versions are affected? I tried this in 0.71.x and can't reproduce

**Comment by cezaraugusto** [comment] 2019-11-11 16:38
@bsclifton updated the comment. bug is present only in 0.72.x onwards

**Comment by antonok-edm** [comment] 2019-11-11 21:25
Also noticing that it quickly jumps to the intended location when moving the mouse nearby

![6846](https://user-images.githubusercontent.com/22821309/68622251-929b4700-0486-11ea-9752-02743511306f.gif)

**Comment by LaurenWags** [comment] 2019-11-15 20:38
In addition to @antonok-edm comment in https://github.com/brave/brave-browser/issues/6846#issuecomment-552622956 sometimes the content jumps to the intended location when interacting with the content via tab (as in https://github.com/brave/brave-browser/issues/5504 ).


Brave | 1.1.2 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

**Comment by GeetaSarvadnya** [comment] 2019-11-18 07:47
Encountered and reproduced https://github.com/brave/brave-browser/issues/6846#issuecomment-552622956 on windows 10 x64 - 1.1.4

**Comment by bsclifton** [comment] 2019-12-04 17:13
Marked as `release-notes/exclude` because I believe the problem isn't on 1.0.x

**Closed** 2019-12-04 23:52 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, about-pages/welcome, release-notes/exclude

**Comment by btlechowski** [comment] 2019-12-06 13:08
Not in 1.1.18, waiting for another build.

**Comment by kjozwiak** [comment] 2019-12-09 05:11
Verification **PASSED** on `macOS 10.15.1 x64` using the following build:

Brave | 1.1.19 Chromium: 79.0.3945.70 (Official Build) (64-bit)
-- | --
Revision | 65868db27916cebde51fc2465c9b34761e6383e2-refs/branch-heads/3945@{#869}
OS | macOS Version 10.15.1 (Build 19B88)

* reproduced the original issue using `1.1.18 Chromium: 79.0.3945.56`
* went through and verified the original STR as per https://github.com/brave/brave-browser/issues/6846#issue-520164136 
* ensured that the `brave://welcome` page is aligned on initial launch
* ensured that the `brave://welcome` page is aligned when navigating through the different pages
* ensured that each page is correctly aligned when interacting with buttons (Import, Set Default etc..)
* ensured alignment looks correct when navigating through each page using both `Next` & bullets
* ensured that resizing the `brave://welcome` window doesn't cause any alignment issues
* ensured that all the links are working as expected
* ensured the above STR/cases work as expected when using a secondary monitor
