### ISSUE TITLE
[Speedreader] Isolated world id

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#28581] opened 2023-02-17 09:41 UTC
Speedreader part of https://github.com/brave/brave-browser/issues/28569

Using ISOLATED_WORLD_ID_BRAVE_INTERNAL instead of content::ISOLATED_WORLD_ID_CONTENT_END + 9

**Comment by diracdeltas** [comment] 2023-02-18 06:11
this is actually a dupe of https://github.com/brave/brave-browser/issues/28569 fyi and @bridiver asked me to mark that p1 so this is becoming a p1

**Closed** 2023-02-20 08:03 UTC
Labels: priority/P1, QA/No, release-notes/exclude, OS/Desktop
