### ISSUE TITLE
Crash to desktop when pressing enter in github's search bar

### ISSUE THREAD

**Issue by dalmo3** [brave/brave-browser#24174] opened 2022-07-21 05:22 UTC
## Description 

Crash to desktop when pressing enter in github's search bar. Does not crash if clicking the search options popup menu with the mouse, only when pressing enter. I.e. using the mouse is the only way to search github for now.

## Steps to Reproduce

   1. Open github.com
   2. Type something in the search bar
   3. Press Enter

## Actual result:

Crash to desktop. All windows, all profiles.

## Expected result:
No crash.

## Reproduces how often: 

Every single time when following the steps above. Tested on two computers (both win 10 brave 1.41.99), multiple profiles, incognito mode.

## Brave version (brave://version info)

Brave	1.41.99 Chromium: 103.0.5060.134 (Official Build) (64-bit) 
Revision	8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS	Windows 10 Version 21H1 (Build 19043.1826)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? Yes
- Is the issue reproducible on the latest version of Chrome? No

**Comment by Ryan-Goldstein** [comment] 2022-07-21 05:29
Duplicate of https://github.com/brave/brave-browser/issues/24164.

**Comment by srirambv** [comment] 2022-07-21 07:38
This is fixed and should be available in the next HF. Closing as dupe of #24164

**Closed by srirambv** 2022-07-21 07:38 UTC
Labels: OS/Desktop
