### ISSUE TITLE
Brave Rewards / brave://adblock  NO DARK MODE: 

### ISSUE THREAD

**Issue by MrWaste** [brave/brave-browser#16117] opened 2021-05-28 00:29 UTC
## Description 

On Desktop there is a dark mode option, however its doesn't apply to brave rewards settings or brave's custom element blocker. Why is that? If you have dark mode on, it means dark mode for everything.

## Steps to Reproduce

   1. Go to Brave Rewards
   2. Go to "brave://adblock"
   3. Happens on Windows 10 and Linux Mint

## Part 1
![Brave](https://user-images.githubusercontent.com/49108816/119912466-66340800-bf10-11eb-9901-44e16ca3276b.png)
![brave1](https://user-images.githubusercontent.com/49108816/119912486-68966200-bf10-11eb-80d2-25f9322d2bb5.png)
![brave2](https://user-images.githubusercontent.com/49108816/119912694-d04cad00-bf10-11eb-8d82-039ebbc94278.png)
![brave3](https://user-images.githubusercontent.com/49108816/119912704-d17dda00-bf10-11eb-9bdd-fe48d51e0571.png)

## Part 2

![Brave Ad Block](https://user-images.githubusercontent.com/49108816/121946075-63efed00-cd09-11eb-9d3a-2b7b9a0616b2.png)

## Brave version (brave://version info)

Version 1.27.62 Chromium: 91.0.4472.101 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

Note:
Updated 6-14-21

**Comment by manikandancode** [comment] 2021-05-28 13:23
+1

**Comment by MrWaste** [comment] 2021-05-30 19:01
If its a bad idea please let me know, it won't take to long to add this.

**Comment by MrWaste** [comment] 2021-06-14 19:03
Updated more sections that need dark mode. Read above to original post, THANKS.

**Comment by rebron** [comment] 2021-10-21 22:31
Closing as dupe of https://github.com/brave/brave-browser/issues/8838

**Closed by rebron** 2021-10-21 22:31 UTC
Labels: OS/Desktop
