### ISSUE TITLE
Feature request: Show a user's Tor circuit in Private Window with Tor

### ISSUE THREAD

**Issue by Swangie-Errangie** [brave/brave-browser#15163] opened 2021-04-07 01:09 UTC
## Description 
It seems that currently, there is no way to view your Tor circuit in Private Window with Tor. You cannot see what Tor nodes your connection is going through. The Tor Browser already has such a feature:

![image](https://user-images.githubusercontent.com/76885647/113795416-d9907900-971a-11eb-8b43-af6668e6b517.png)

but the Brave Browser is yet to implement this. While this may not be the most important issue, I definitely recommend adding this if possible. Maybe this could be added in the lock icon near the URL address bar if desired.

## Steps to Reproduce

   1. Open the Brave Browser (Desktop).
   2. Open a Private Window with Tor and wait for the connection to be completed.
   3. Go to a website and try to see your Tor circuit from your browser.

## Actual result:
There is no option to view which relay servers your connection is going through. You are only able to see if you are connected to Tor and you can only choose the option to connect to a new Tor circuit.

## Expected result:

You can view which relay servers your connection is going through.

## Reproduces how often: 

The Tor circuit is always never visible as the information is never shown.

## Brave version (brave://version info)

Brave: 1.24.50 Chromium: 90.0.4430.51 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes!
- Can you reproduce this issue with the beta channel? Yes!
- Can you reproduce this issue with the nightly channel?  Yes!

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No!
- Does the issue resolve itself when disabling Brave Rewards?  No!
- Is the issue reproducible on the latest version of Chrome? Chrome doesn't even have Private Window with Tor so no!

This isn't a priority, simply a suggestion. It isn't required for Brave to implement this feature, but doing so can improve a user's experience with Private Window with Tor.

**Comment by srirambv** [comment] 2021-04-07 05:30
Dupe of #3586

**Closed by srirambv** 2021-04-07 05:30 UTC
Labels: OS/Desktop
