### ISSUE TITLE
document.referer leaks the referrer

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#1861] opened 2018-10-26 13:47 UTC
Referer headers are spoofed in brave, but document.referer leaks the current referer

**Comment by bbondy** [comment] 2018-10-28 19:05
This was a regression and we have a test fail for it, @yrliou will fix on Monday.

**Comment by yrliou** [comment] 2018-10-28 20:11
Marked as QA/No because it is covered by browser tests.

**Closed** 2018-10-28 20:19 UTC
Labels: QA/No, priority/P3, privacy

**Comment by bbondy** [comment] 2018-10-28 20:28
> @yrliou will fix on Monday.

I lied, she did it today :P
