### ISSUE TITLE
Mac App Icon Displaying Intermittently

### ISSUE THREAD

**Issue by ngurney** [brave/brave-browser#1334] opened 2018-09-28 01:04 UTC
I have searched for this issue and couldn't find anything. Not sure if I am the only one who is experiences. 

## Description 
Mac App Icon is 10.14 does not appear about 75% of the time. It shows the default "missing app icon" from Apple. See screenshot: https://cl.ly/10a1d3a80b1d

## Steps to Reproduce
Happens periodically. Will apear often during regular usage. Cannot find out what causes it to display or not display.

## Actual result:
App Icon does not display

## Expected result:
App icon displays constantly

## Reproduces how often: 
About 75% of the time

## Brave version (chrome://version info)
Version 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)

### Reproducible on current release:
Not that I am aware of, I don't use it.

**Comment by srirambv** [comment] 2018-09-28 01:49
Dupe of https://github.com/brave/brave-browser/issues/1217. This issue is fixed on Beta. You can download the beta from [here](https://brave.com/download-beta)

**Closed by srirambv** 2018-09-28 01:49 UTC
