### ISSUE TITLE
Updated to v0.57.18 and now I can't disable torrent viewer

### ISSUE THREAD

**Issue by tpby** [brave/brave-browser#2432] opened 2018-12-10 18:10 UTC
## Description 
In earlier versions I could go into about:preferences#extensions and disable the extension. Now when I updated to v0.57.18 torrent viewer is enabled again. I tried to access about:preferences but it just says Site cannot be reached. When I go into Menu>More tools>Extensions it's empty as well. Every time I click a magnet link it opens torrent viewer.

## Steps to Reproduce
   1. Update to v0.57.18.
   2. Click a magnet link for a torrent.
   3. Go into about:preferences#extensions.
   4. Go to Menu>More Tools>Extensions.

## Actual result:
Can't access the extension and disable it. Can't click magnet links without torrent viewer opening.

## Expected result:
My torrent software opens and I can download Ubuntu.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Brave | 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows

**Comment by eljuno** [comment] 2018-12-10 21:01
Duplicate of #897

**Closed** 2019-01-21 18:35 UTC
