### ISSUE TITLE
twitch verified pubs name is empty in `Thank you` - Rewards Banner

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3265] opened 2019-02-07 20:58 UTC
## Description 

twitch verified pubs name is empty in `Thank you` - Rewards Banner

## Steps to Reproduce

   1. Clean profile 0.60.19
   2. Open any verified twitch pubs and tip it (https://www.twitch.tv/videos/226907251)
   3. After tip, pubs name is empty in `Thank you` - Rewards banner

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/52442068-46faec00-2b48-11e9-9a0c-55c95174c85f.png)

![pubs name is empty on rewards banner](https://user-images.githubusercontent.com/38657976/52442047-3c405700-2b48-11e9-9e9d-c37996d906df.gif)

## Expected result:
 `Thank you` -Rewards banner should have pubs name

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.60.19 Chromium: 72.0.3626.81 (Official Build) beta (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional Information
@brave/legacy_qa @NejcZdovc

**Comment by kjozwiak** [comment] 2019-02-07 23:02
@GeetaSarvadnya are you referring to the empty circle that you're seeing? Should have something similar to the following correct?

<img width="505" alt="screen shot 2019-02-07 at 6 00 18 pm" src="https://user-images.githubusercontent.com/2602313/52448646-93233d80-2b02-11e9-985a-0255e7320117.png">

**Comment by GeetaSarvadnya** [comment] 2019-02-08 04:32
@kjozwiak Yes, correct. I was refererring empty circle.

**Comment by NejcZdovc** [comment] 2019-02-08 07:26
closing as dupe of this one https://github.com/brave/brave-browser/issues/3273 as the root problem is the same

cc @kjozwiak @rebron if we want this in 0.60

**Closed by NejcZdovc** 2019-02-08 07:26 UTC
Labels: QA/Yes, bug, feature/rewards, priority/P4

**Comment by GeetaSarvadnya** [comment] 2019-02-12 16:11
@NejcZdovc I am seeing this issue for YT verified pubs even, do you think #3273 is the root cause for this as well?
![3265](https://user-images.githubusercontent.com/38657976/52649795-fea84900-2f0e-11e9-8767-2a2e40fd37d5.gif)

**Comment by LaurenWags** [comment] 2019-02-12 21:12
I can reproduce this but only with a VOD. A live stream shows the correct letter in thank you banner. 

Brave | 0.60.26 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X
