### ISSUE TITLE
Auto Suggest Complex Password For Internet Forms

### ISSUE THREAD

**Issue by m-henderson** [brave/brave-browser#8606] opened 2020-03-10 03:32 UTC
## Description 
I would be an awesome feature if brave could suggest a complex password to the user when they are creating a password for a new account on a website. 

## Steps to Reproduce 
There is not really an issue to reproduce here because this is more like a feature request. 
1. go to a website and create a new account. 
2. type in the username/email you are going to use for the account
3. type in a password for the account. 

## Actual result:
You have to create a password off the top of your head instead of brave auto recommending a password. 

## Expected result:
Expected brave to suggest a complex password for me just like chrome does. 
![image](https://user-images.githubusercontent.com/16070192/76276957-4950dd80-6255-11ea-953d-a6e17e9b2974.png)

## Brave version (brave://version info)

![image](https://user-images.githubusercontent.com/16070192/76277060-9e8cef00-6255-11ea-9812-311e18ece37d.png)

## Version/Channel Information:

 I will have to test the other channels and get back to you on this. 

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment] 2020-03-17 18:42
duplicate of #4901

**Closed by rebron** 2020-03-17 18:42 UTC
Labels: feature-request, feature/password-manager
