### ISSUE TITLE
[Android] Support cosmetic filtering on Android

### ISSUE THREAD

**Issue by Oeufhp** [brave/brave-browser#9955] opened 2020-05-27 02:42 UTC
## Description 
I enabled cometic filtering in brave://flags, enable ads blocking in setting and update in brave://components

## Steps to reproduce 

   1. enter brave://flags and enable cosmetic filtering
   2. restart brave 2 times and open brave again
   3. go to https://apkmirror.com and still see the white space

## Actual result 
[screenshot1](https://imgur.com/wc43vRv)
[screenshot2](https://imgur.com/3LbV4Vf)

## Expected result
No white space

## Issue happens on 
   - Current Play Store version? yes
   - Beta build? no

## Device details
   - Install type (ARM, x86): ARM64
   - Device (Phone, Tablet, Phablet): Huawei P20 pro
   - Android version: Android 10
   
## Brave version
1.8.112

### Additional information

I found this [link](https://community.brave.com/t/cosmetic-filter-on-android/109789) but there's no solution yet

**Comment by srirambv** [comment] 2020-05-27 04:15
Cosmetic filtering is not yet applicable for mobile. 

cc: @pes10k @antonok-edm

**Comment by Oeufhp** [comment] 2020-05-27 04:17
Thanks, hope it will be available soon

**Comment by antonok-edm** [comment] 2020-05-27 15:09
@Oeufhp I'll leave this issue open to track the implementation status. Thank you for the report.

**Comment by antonok-edm** [comment] 2020-05-27 15:44
After further investigation, it appears that the cosmetic filtering background and content scripts are not used because Brave Android doesn't yet support extensions. Once https://github.com/brave/brave-browser/issues/4493 is resolved this should theoretically be ready immediately.

**Comment by srirambv** [comment] 2020-05-27 17:51
Thanks for the confirmation @antonok-edm 👍

**Comment by srirambv** [comment] 2020-11-02 12:58
+1 from @chris122380 via https://github.com/brave/brave-browser/issues/12405

**Comment by chris122380** [comment] 2021-01-12 16:24
Why would this need extension support when other mobile browsers with add filtering support this without extensions? Vivaldi for example.

**Comment by pes10k** [comment] 2021-01-12 16:28
@chris122380 because the previous desktop implementation used the extension API, and so the original approach was to add the extension interfaces to Android and then use the desktop filtering implementation.

Porting extension support to android ended up being prohibitive, and so whats captured here is the second go at the problem: to reimplement cosmetic filtering w/o using the extension interface, and then port that to desktop / make that the sole implementation

**Comment by Furax-31** [comment] 2021-01-25 05:21
Nightly 1.21.24 (Android 9)

Despite the implementation of cosmetic filtering, there are still sites with large empty spaces.

**Comment by antonok-edm** [comment] 2021-01-25 06:29
> Nightly 1.21.24 (Android 9)
> 
> Despite the implementation of cosmetic filtering, there are still sites with large empty spaces.
> 
> Example: https://www.01net.com/

cc @ryanbr

**Comment by ryanbr** [comment] 2021-01-25 11:18
On the mobile site, the cosmetics applied is causing the most ad-space issues `##.mrf-adv` (in Easylist) @antonok-edm 

Specifically:
`##div.mrf-heightLocked.mad.mrf-preInsertedMad.sRoba.mrf-adv`

![mrf-ad](https://user-images.githubusercontent.com/1659004/105699286-f87ccd00-5f6b-11eb-808b-a6a6d5b404f2.png)

**Comment by SergeyZhukovsky** [comment] 2021-01-25 20:29
I see the same issue on old implementation on desktop for apkmirror.com
![Screenshot from 2021-01-25 15-25-27](https://user-images.githubusercontent.com/12011303/105761870-a4e59180-5f21-11eb-9bb9-fbb7ca079b72.png)
Most likely it's something that has been missed in the original implementation as well on apkmirror.com. For https://www.01net.com/ I see empty spaces on mobile, but hard to compare with desktop as desktop version of website on mobile looks still different compare to a real desktop version

**Comment by Oeufhp** [comment] 2021-01-26 01:58
> I see the same issue on old implementation on desktop for apkmirror.com
> ![Screenshot from 2021-01-25 15-25-27](https://user-images.githubusercontent.com/12011303/105761870-a4e59180-5f21-11eb-9bb9-fbb7ca079b72.png)
> Most likely it's something that has been missed in the original implementation as well on apkmirror.com. For https://www.01net.com/ I see empty spaces on mobile, but hard to compare with desktop as desktop version of website on mobile looks still different compare to a real desktop version

For the desktop just enter `brave://flags/#brave-adblock-cosmetic-filtering` then enable it and restart the browser

**Comment by SergeyZhukovsky** [comment] 2021-01-26 15:13
@Oeufhp it is on by default on desktop. It's available on Android on Brave - Nightly. The thing is that apkmirror.com still has gaps.

**Comment by Oeufhp** [comment] 2021-01-27 02:31
@SergeyZhukovsky I tried Nightly in Android yesterday and it was as you said.

**Comment by Smart123s** [comment] 2021-01-27 17:22
I can confirm, that cosmetic filtering is working on android.
However, the `<amp-ad>` tags are still visible.
I have attached an example article that contains the tag. (This was the first one, that came up on Google News.)

![image](https://user-images.githubusercontent.com/28480228/106028578-69d39180-60cc-11eb-8150-9fe709ee59b1.png)
(Taken on Brave Nightly)


![image](https://user-images.githubusercontent.com/28480228/106028430-37299900-60cc-11eb-9ff3-b213a23a35a7.png)
(Taken on Chrome Windows, URL: https://news.google.com/articles/CAIiECjCnOLQetdp70j9F7dfaDIqGQgEKhAIACoHCAowqY2GCzC114MDMKn65gY?hl=hu&gl=HU&ceid=HU%3Ahu)

**Comment by antonok-edm** [comment] 2021-01-27 17:23
I think the `01net.com` issue is related to there being no aggressive mode on Android yet. If I toggle `Pixel 2 XL` in the device toolbar when devtools is open on Desktop, the ad spaces are hidden only in aggressive mode.

cc @pes10k - this may be an issue with our 1p/3p heuristics? Those look like pretty standard 3p Google ads when Shields are down.

**Comment by pes10k** [comment] 2021-01-30 02:41
I fixed the manual tests for this here: https://dev-pages.brave.software/cosmetic-filtering/text-ads.html

**Comment by DiAnTTA** [comment] 2021-01-30 04:34
<details><summary>Screenshot on Nightly 1.21.35</summary>

![Nightly_1_21_35](https://user-images.githubusercontent.com/74956696/106347044-0d4fbc80-62ee-11eb-8660-07805d6dcde1.jpg)

`Quảng cáo`*(Vietnamese)* = `Advertise`*(English)*
</details>

**Comment by pes10k** [comment] 2021-01-31 01:06
@DiAnTTA should be fixed once tis gets merged https://github.com/brave/brave-core/pull/7751

If not, can you share the full URLs of pages where you're still seeing the problem?

**Comment by DiAnTTA** [comment] 2021-02-02 01:12
@pes10k 
<details><summary>Screenshot on Nightly 1.21.37</summary>

https://mb.dkn.tv/the-gioi/ong-trump-lai-duoc-de-cu-giai-nobel-hoa-binh.html
![IMG_20210202_075750](https://user-images.githubusercontent.com/74956696/106537765-943ea800-652d-11eb-8c53-87982c661756.jpg)
https://zingnews.vn/cong-ty-duoc-nguong-mo-nhat-the-gioi-post1179779.html
![Screenshot_2021-02-02-08-03-23-268_com brave browser_nightly](https://user-images.githubusercontent.com/74956696/106537888-d23bcc00-652d-11eb-84ae-f0efedf2018a.jpg)


![IMG_20210202_075404](https://user-images.githubusercontent.com/74956696/106537953-f4354e80-652d-11eb-9a9f-f8dc2526ccfb.jpg)

</details>

**Comment by SergeyZhukovsky** [comment] 2021-02-02 02:26
@DiAnTTA it's not in 1.21.37. It has been merged after that Nightly build was created. The fix will appear in the next Nightly.

**Comment by DiAnTTA** [comment] 2021-02-02 14:27
@SergeyZhukovsky 
<details><summary>Screenshot Nightly 1.21.38:</summary>

![Screenshot_2021-02-02-21-18-03-647_com brave browser_nightly](https://user-images.githubusercontent.com/74956696/106613345-aa378180-659c-11eb-9f0a-0da25df140dd.jpg)
https://zingnews.vn/thong-tin-khach-hang-nguyen-kim-bi-hacker-rao-ban-post1179532.html

![IMG_20210202_212315](https://user-images.githubusercontent.com/74956696/106613744-1f0abb80-659d-11eb-94b8-bb6b09470baa.jpg)

</details>

**Comment by SergeyZhukovsky** [comment] 2021-02-02 14:31
thanks @DiAnTTA, could you post a full link to the article please?

**Comment by SergeyZhukovsky** [comment] 2021-02-02 14:32
nvm @DiAnTTA I see it https://zingnews.vn/thong-tin-khach-hang-nguyen-kim-bi-hacker-rao-ban-post1179532.html

**Comment by rodrigoswz** [comment] 2021-02-02 15:09
Nightly v1.21.38

Ad banners still exist on AMP pages of websites like Android Police and 9to5Google, but APKMirror is fixed.

https://www.androidpolice.com/2021/02/02/latest-galaxy-buds-pro-update-improves-anc-and-voice-detect-mode/?amp

https://9to5google.com/2021/02/02/android-11-begins-rolling-out-for-the-nokia-8-3-5g/amp/

![Screenshot_20210202-120749502.jpg](https://user-images.githubusercontent.com/14058427/106619490-69fde200-654f-11eb-83fd-a658c15b55fb.jpg)

![Screenshot_20210202-120626.png](https://user-images.githubusercontent.com/14058427/106619593-8437c000-654f-11eb-909a-343e3b243f34.png)

**Comment by antonok-edm** [comment] 2021-02-02 18:11
@ryanbr can you investigate https://zingnews.vn/thong-tin-khach-hang-nguyen-kim-bi-hacker-rao-ban-post1179532.html? Does it need a regional list? Looks like those are not hidden on desktop in Release/aggressive mode either.

**Comment by antonok-edm** [comment] 2021-02-02 18:16
@SergeyZhukovsky @pes10k https://9to5google.com/2021/02/02/android-11-begins-rolling-out-for-the-nokia-8-3-5g/amp/ is a regression, ad spots are correctly hidden in Release/standard blocking mode but not in latest Nightly.

**Comment by SergeyZhukovsky** [comment] 2021-02-03 17:37
@orspetol we need to keep it open still as the regression mentioned https://github.com/brave/brave-browser/issues/9955#issuecomment-771859523 isn't merged yet

**Comment by orspetol** [comment] 2021-02-03 17:52
@SergeyZhukovsky I did not close this ticket (at least that I know of). Currently diagnosing how this could have happened. Thank you for reopening in my behalf. If it was somehow caused on my end I will vocalize how not to repeat the issue. Thanks.

**Comment by mihaiplesa** [comment] 2021-02-03 18:12
https://github.com/brave/brave-core/pull/7751/commits has commits with `fixes` in commit message which close this issue automatically.

**Closed** 2021-02-04 18:20 UTC
Labels: OS/Android, OS/Desktop, QA/Yes, enhancement, features/shields/cosmetic-filtering, release-notes/exclude

**Comment by chris122380** [comment] 2021-02-04 18:23
In what stable version could we expect to start seeing this? Not until Brave 21?

**Comment by SergeyZhukovsky** [comment] 2021-02-04 18:37
@chris122380 yes it's correct, `1.21.x`

**Comment by LaurenWags** [comment] 2021-02-15 19:54
Verified passed with

```
Brave | 1.21.54 Chromium: 88.0.4324.152 (Official Build) beta (x86_64)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | macOS Version 10.15.7 (Build 19H512)
```

Verified test plan from https://github.com/brave/brave-core/pull/7799.
Confirmed no empty spaces from ads on https://9to5google.com/2021/02/02/android-11-begins-rolling-out-for-the-nokia-8-3-5g/amp/.

-----------

**Comment by chris122380** [comment] 2021-02-16 05:43
@SergeyZhukovsky How should we report cosmetic issues for specific webpages?
ksl.com for example with the ads removed leaves a gap above the first news article. 
![Screenshot_20210215-224145](https://user-images.githubusercontent.com/2205798/108023119-23909480-6fdf-11eb-8e31-e7196e359cc3.png)

**Comment by pes10k** [comment] 2021-02-16 05:47
@chris122380 the best thing to do is to report these issue upstream. [EasyList](https://github.com/easylist/easylist) is the best option here, since Brave (along with many other projects) all use it, and changes there will have the largest impact on the Web. If the maintainers wont accept the change there, they might refer you to other projects, many of which Brave also pulls from (EasyPrivacy, uBlock Origin, etc).

If none of those projects will accept the change (unlikely, but not impossible), please let us know then and we'll consider the change in a Brave specific list.

But, in general, the higher up the stream, the better (both for impact and maintainability)

**Comment by rodrigoswz** [comment] 2021-02-19 06:36
AMP pages are really problematic for me, otherwise I think everything is working.

Another example that the problem persists in the latest Nightly v1.22.34:
https://www.androidpolice.com/2021/02/18/pixel-dark-theme-is-no-longer-pitch-black-on-android-12/?amp

![Screenshot_20210219-033017.png](https://user-images.githubusercontent.com/14058427/108467206-9742d380-7263-11eb-866b-393b871401e7.png)

**Comment by antonok-edm** [comment] 2021-02-23 02:50
> Another example that the problem persists in the latest Nightly v1.22.34:
> https://www.androidpolice.com/2021/02/18/pixel-dark-theme-is-no-longer-pitch-black-on-android-12/?amp

@rodrigoswz I can't reproduce the loading "Ad" box at the top, but I do still see the broken frame under the title.

cc @ryanbr can you take a look? Should just be a cosmetic filter, at least for the white banner

**Comment by ryanbr** [comment] 2021-02-23 03:15
Okay, give it 24-48hrs. 

https://github.com/easylist/easylist/commit/d7ca65bab51f192617ea947e829a6d5dcde07688

Should clean up the site.

**Comment by urbenlegend** [comment] 2021-02-25 17:24
I am using the latest nightly with cosmetic filtering on (although I believe it is also enabled by default in Nightly) and I still see empty ad spaces on washington post.com and nytimes.com

![Screenshot_20210225-092038](https://user-images.githubusercontent.com/241316/109191406-ff555600-774a-11eb-94b3-c832d5148bd4.png)
![Screenshot_20210225-092017](https://user-images.githubusercontent.com/241316/109191428-041a0a00-774b-11eb-87f1-715a4a049f50.png)

Other sites like apk mirror and that 9to5 link seem to work fine. Is this a regression or do we just need to wait for easylist to catch up?

**Comment by daphnei-mee** [comment] 2021-02-25 18:44
I can confirm I experience the same issue as urbenlegend on sites like Washington Post or the NYT, among many others - on nightly with cosmetic filtering enabled. 

I also have inline ads on sites like google with brave on android. Not sure i that is the same issue as this or not, but I know on brave desktop they are removed if you set shields to aggressive.
![Screenshot_20210225-133910](https://user-images.githubusercontent.com/55215353/109201149-7bfa2b80-776f-11eb-85b0-36b58fc6acaf.jpg)

**Comment by antonok-edm** [comment] 2021-02-25 19:29
@daphnei-mee - inline first-party ads would be removed by enabling aggressive mode, which isn't supported yet on Android. Progress is tracked here: https://github.com/brave/brave-browser/issues/9831

@urbenlegend - @ryanbr could you investigate washingtonpost.com and nytimes.com?

**Comment by srirambv** [comment] 2021-02-26 13:57
Verification passed on OnePlus 6T with Android 10 running 1.21.68 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/7799
- Logged #14379 as tracking issue for new sites

apkmirror.com | 9to5google.com 
-- | -- 
![image](https://user-images.githubusercontent.com/17010094/109304657-79add500-7834-11eb-9ba2-3f458c14f3da.png) | ![image](https://user-images.githubusercontent.com/17010094/109304668-7dd9f280-7834-11eb-8281-ef99bfa57286.png) |

---------------
Verification passed on Samsung Tab A with Android 10 running 1.21.68 x64 build
- Verified test plan from https://github.com/brave/brave-core/pull/7799

apkmirror.com | 9to5google.com 
-- | -- 
![image](https://user-images.githubusercontent.com/17010094/109308859-7ae20080-783a-11eb-9cab-5d71de0bdf74.png) | ![image](https://user-images.githubusercontent.com/17010094/109308891-833a3b80-783a-11eb-981b-7ac4f0628772.png)
