### ISSUE TITLE
Quoted tweet doesn't display the twitter card for our brave.com/tips landing page. 

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#4605] opened 2019-05-24 21:40 UTC
@mandar-brave 

## Actual result:

Difference of a tweet without a quote tweet and with one.

1. Tip the twitter user from the BR panel
![Screen Shot 2019-05-24 at 2 38 35 PM](https://user-images.githubusercontent.com/4369856/58357955-ae0b8a80-7e31-11e9-9f62-212b1a001ff1.png)

2. Tip the tweet (tweet is quoted)
![Screen Shot 2019-05-24 at 2 38 24 PM](https://user-images.githubusercontent.com/4369856/58357962-b6fc5c00-7e31-11e9-8382-369e108422a5.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by mandar-brave** [comment] 2019-05-24 21:42
may be duplicate of https://github.com/brave/brave-browser/issues/4597
@emerick @NejcZdovc

**Comment by emerick** [comment] 2019-05-24 21:54
I think @jenn-rhim is saying she prefers the "tweet card" look of option #1. We're currently using the Twitter web intents API, which is fairly primitive so this would require some work.

https://developer.twitter.com/en/docs/twitter-for-websites/web-intents/overview.html

**Comment by NejcZdovc** [comment] 2020-04-10 07:38
closing as I don't see really what can be done here as @emerick said it intents are limited

**Closed by NejcZdovc** 2020-04-10 07:38 UTC
Labels: QA/Yes, enhancement, feature/rewards
