### ISSUE TITLE
Feature request: Disable auto-updates for browser and extensions

### ISSUE THREAD

**Issue by leodoi3** [brave/brave-browser#18016] opened 2021-09-11 00:24 UTC
Can you please add a feature to disable auto-updates for the browser and the extensions? A lot of users like me want to see the release notes before updating , so something like this would be very helpful.

**Comment by clicky6** [comment] 2021-09-11 05:21
Yes it would be definitely useful and must be considered to be added to Brave and another feature should be added in settings so that we can choose if installed extensions connect to the internet or not so that the extensions that don't require connecting to internet can be prohibited from connecting.

**Comment by rebron** [comment] 2021-09-17 00:19
Closing as dupe of #5576

**Closed by rebron** 2021-09-17 00:19 UTC
Labels: OS/Desktop
