### ISSUE TITLE
Removing device from sync chain fails at first but then succeeds 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14174] opened 2021-02-16 12:02 UTC
## Description 
Removing device from sync chain fails at first but then succeeds 

## Steps to reproduce 

   1. Install 1.22.27 x64 nightly build
   2. Create a standalone sync chain
   3. Try to delete the device name to close the sync chain, fails at first but then succeeds

## Actual result 

https://user-images.githubusercontent.com/17010094/108060367-aef53e80-704e-11eb-8493-1e0543e80574.mp4

## Expected result
Should not fail and remove it at first go

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Mostly Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.20.103 & 1.22.27

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @AlexeyBarabash

**Comment by AlexeyBarabash** [comment] 2021-02-16 12:05
I was able to reproduce it

**Comment by AlexeyBarabash** [comment] 2021-02-20 10:55
The same behavior is possible to see on the desktop if it has several thousands of bookmarks.
The reason is in this place https://github.com/brave/brave-core/blob/master/components/brave_sync/profile_sync_service_helper.cc#L23 , `brave_sync::ResetSync`:
```
  if (sync_service->GetTransportState() !=
      syncer::SyncService::TransportState::ACTIVE) {
// TransportState::CONFIGURING
    std::move(on_reset_done).Run();
    return;
  }
```
When we rapidly leaving the sync chain and it was just created and still in state `CONFIGURING`, then reset sync request is ignored in fact.

I am going to hide the button untill we will not have `ACTIVE` state.

**Comment by anthonypkeane** [comment] 2021-06-16 18:57
@AlexeyBarabash to take a look again when time permits.

**Comment by AlexeyBarabash** [comment] 2023-01-09 18:41
I can't reproduce it anymore. Maybe something was changed at the upstream.

**Comment by AlexeyBarabash** [comment] 2023-01-09 19:19
Probably it was fixed by https://github.com/brave/brave-core/pull/10841

**Comment by AlexeyBarabash** [comment] 2023-02-01 19:45
Closing as discussed with @srirambv in DM
>can be closed. Haven't seen it in a long time. Tried on latest nightly and no crash

**Closed by AlexeyBarabash** 2023-02-01 19:45 UTC
Labels: bug, needs-investigation, feature/sync, priority/P3, QA/Yes, release-notes/include, OS/Android
