### ISSUE TITLE
Blocking Youtube Autoplay is not working properly

### ISSUE THREAD

**Issue by BraveSauce** [brave/brave-browser#14266] opened 2021-02-19 23:21 UTC
## Description 
While blocking Autoplay globally and also explicitly for youtube.com, any video content that is opened in a new tab ignores the setting.

## Steps to Reproduce

   1. Browse youtube.com
   2. Open any video in a new tab
   3. Switch to the newly opened tab.

## Actual result:
Video starts playing, ignoring the setting.

## Expected result:
The setting should be respected and the video must not autoplay.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Brave | 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Windows 10 OS Version 2009 (Build 19042.804)

## Version/Channel Information:
I have not tested with beta or nightly versions.

## Other Additional Information:
-

## Miscellaneous Information:
Using a random extension for the same functionality works as intended.

**Comment by LanceTrahan** [comment] 2021-02-20 20:14
I can confirm this is also occurs on Mac OS Mojave. It's been going on ever since I recently switched to the browser (love it by the way) and had just gotten fed up with this bug and was about to post an issue until I found this recent post.

Hope it can be fixed soon. It's annoying when I have a number of youtube videos tabbed but jump away and then mistakenly jump to the wrong tab and have a video I wasn't ready to start watching yet start playing.

**Comment by rebron** [comment] 2021-03-01 21:51
@BraveSauce @LanceTrahan 
Is this what you have in Settings? I tried on Windows and macOS and with these settings, I have to select the play button on the video and autoplay blocking is working. 

I'm also on our latest 1.20.110. 

<img width="717" alt="Screen Shot 2021-03-01 at 1 48 16 PM" src="https://user-images.githubusercontent.com/5951041/109563658-ea532c80-7a94-11eb-8c67-fd693036e5d6.png">

**Comment by LanceTrahan** [comment] 2021-03-01 22:08
@rebron I'm on the same version with the same exact settings and opening a new YouTube tab from an existing YouTube tab causes them to play as soon as you click over to one of the new tabs that was opened. I've also tried it with Block enabled and with the explicit block setting set for the youtube.com site.

**Comment by BraveSauce** [comment] 2021-03-01 22:24
> @BraveSauce @LanceTrahan
> Is this what you have in Settings? I tried on Windows and macOS and with these settings, I have to select the play button on the video and autoplay blocking is working.
> 
> I'm also on our latest 1.20.110.
> 
> <img alt="Screen Shot 2021-03-01 at 1 48 16 PM" width="717" src="https://user-images.githubusercontent.com/5951041/109563658-ea532c80-7a94-11eb-8c67-fd693036e5d6.png">

Yes, these are my settings. Of course I experimented with different combinations such as a global block without site specific settings and a global allow with specific block for youtube.

Please make sure to test while opening videos in new tabs, as the issue only occurs there.

**Comment by LanceTrahan** [comment] 2021-03-02 01:25
@rebron I'm logged into YouTube. Besides the Brave Shields being active, I'm only running a dark mode reader extension (which is disabled for YouTube as it has built-in dark mode) and OneTab to condense my tabs down when they get too numerous.

**Comment by LanceTrahan** [comment] 2021-03-02 01:50
@rebron Did a short record of me experiencing the issue. It was also occurring when logged out of YouTube as well.

https://user-images.githubusercontent.com/2429609/109584388-0079e080-7ac7-11eb-8ed8-25f4ba66f070.mp4

**Comment by BraveSauce** [comment] 2021-03-02 08:08
@rebron I tried in a sandbox with no extensions, signed out. Exactly the same behavior.

The video above is the exact issue I'm having, the video opened in a new tab starts playing automatically, even with the icon showing that it has been blocked.

**Comment by LanceTrahan** [comment] 2021-03-02 17:03
> Update: I'm sorry, I wasn't trying clean after all. It turns out that UBlock Origin extension is the issue in my case.

@rebron 
I'm not using uBlock Origin because Brave's Shields has become a suitable replacement for it in my mind. I've tried the process again with all of my extensions disabled just to be 100% sure and still encountered the issue.

**Comment by rebron** [comment] 2021-03-02 20:33
@darkdh Looks like we're still running into an issue on YouTube for autoplay.

**Comment by LaurenWags** [comment] 2021-03-02 20:35
@rebron I can reproduce this issue, here are my STR:

1. Clean profile
2. Open settings, navigate to brave://settings/content/autoplay
3. Set Autoplay to blocked
4. Open new tab, navigate to youtube
5. Do a search
6. Open a video in a new tab (right click > Open in new tab, I also tried cmd + click on the link)
7. When you click on the tab, the video starts to play and URL bar shows the blocked icon

<img width="1031" alt="Screen Shot 2021-03-02 at 3 27 34 PM" src="https://user-images.githubusercontent.com/28145373/109711453-e4c91580-7b6c-11eb-85fe-4d828f420211.png">

```
Brave | 1.21.71 Chromium: 89.0.4389.72 (Official Build) (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 10.15.7 (Build 19H512)
```

**Comment by LanceTrahan** [comment] 2021-03-03 20:20
@rebron Just another observation. This seems particular to YouTube as I tried doing this for video pages on BitChute and Dailymotion and could not reproduce the issue.

**Comment by ardunster** [comment] 2021-05-19 05:20
Just found this thread as I also have this issue. Very annoying. So far Brave is the only acceptable ad blocking solution I've found on youtube on my Mac, but I really don't like the video autoplaying if I happen to close the tab that was in front of it, or click to the wrong tab, etc. 

As others have stated, the problem only occurs with a video that was loaded in a new tab that I haven't clicked on yet. (It DID not occur on tabs created that way, but not accessed until after I reloaded the browser from the last update.)

**Comment by Legion99A** [comment] 2021-05-21 23:11
Can confirm this issue.  Exactly as described in OP, very annoying and needs fixing ASAP.

Brave Version 1.24.86.  Linux Mint x 2 and Windows 10 x 2.

**Comment by thefallenknight** [comment] 2021-09-26 17:49
Just created my account especially for the Brave browser, which I sincerely hope will succeed (even more / long term) - it's simply the best principles out there of any browser, right now (imho). Looking to add my experiences (getting annoyed) with autoplay blocking actually TOO much, but could not resist attempting a repro here.

Is this issue still relevant, has it maybe been patched away already? Nearly 6 months old now...

Tried and was **unable to repro** it on my Win10 machine with Autoplay 'blocked' (and global Shields UP btw). 
Depending on the global Autoplay setting, either all media is blocked from playing automatically, or all is allowed. Also (YT or other) content in new tabs is either played or blocked, accordingly. So again, repro 0% for me.
Would also like to know whatever specifics are triggering this odd behavior for some users.

In general, the Autoplay blocker does seem to be very nice and aggressive, so please try to maintain this (and THANK you :P)!

**Comment by life777eternal** [comment] 2021-11-14 19:34
Blocking Autoplay on Bitchute.com isn't working.

**Comment by spylogsster** [comment] 2022-08-19 09:36
cannot reproduce with mentioned steps, can someone take a look too @brave/qa-team

**Comment by MadhaviSeelam** [comment] 2022-08-19 17:28
@spylogsster Not able to reproduce using STR above in `Win 11 x64`
```
Brave | 1.42.97 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

**Comment by rebron** [comment] 2022-08-19 19:20
@spylogsster I'm not about to reproduce either using the following these steps: https://github.com/brave/brave-browser/issues/14266#issuecomment-789198003

Brave | 1.42.97 Chromium: 104.0.5112.102 (Official Build) (arm64)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | macOS Version 13.0 (Build 22A5321d)
JavaScript | V8 10.4.132.22
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36

I'm going to close this one out as this looks fixed from likely a prior autoplay fix.

We can reopen if folks in this issue are still encountering the problem.

**Closed by rebron** 2022-08-19 19:20 UTC
Labels: priority/P3, feature/autoplay, feature/settings, OS/Desktop

**Comment by Gravesy83** [comment] 2025-12-26 19:35
I hate to be that guy... but YouTube is once again completely ignoring all autoplay settings.
I really don't want to resort to an extension just to stop YouTube from automatically loading and/or playing videos... but right now that's the only way that works 100% reliably.

[Brave 1.85.118 (Official Build) (64-bit)](https://brave.com/latest/)
Chromium: 143.0.7499.169
OS | Windows 11 Home, Version 10.0.26200 Build 26200
