### ISSUE TITLE
[Android] Unable to translate page 

### ISSUE THREAD

**Issue by newuser-web** [brave/brave-browser#10503] opened 2020-06-29 01:56 UTC
## Description  
Unable to translate page to any language

**Comment by srirambv** [comment] 2020-06-29 03:44
This is expected behaviour for now. Translate is disabled due to #8393 and will probably be available when #7606 is implemented. Also please use the template while logging issues even if its a feature request. Closing issue as wont fix as #7606 will cover it

**Closed by srirambv** 2020-06-29 03:44 UTC
Labels: OS/Android
