### ISSUE TITLE
changing the wallpaper of a new tab

### ISSUE THREAD

**Issue by netharuM** [brave/brave-browser#19525] opened 2021-11-17 12:16 UTC
# changing the wallpaper of the brave new tab 

brave is a good browser with so many features 
but the main issue that annoys me is changing the wallpaper in brave 

even when i change my default home page to the default chrome one still i cant set a custom wallpaper to new tab in brave 

pls guys fix this issue 

thanks 😀😀

**Comment by rebron** [comment] 2021-11-18 23:08
Closing as a dupe of https://github.com/brave/brave-browser/issues/15252

**Closed by rebron** 2021-11-18 23:08 UTC
Labels: closed/duplicate, OS/Desktop
