### ISSUE TITLE
Add additional options to group policy to configure p3a, usage, and crash report settings

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#18012] opened 2021-09-10 18:58 UTC
## Description 

For Windows group policy, see: https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy

- [ ] Add the ability to enable and disable p3a ping, usage ping, and crash reports ping.
- [ ] Update documentation: https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy

## Brave version (brave://version info)

n/a

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment] 2021-09-10 18:58
cc: @simonhong @keur

**Comment by bsclifton** [comment] 2024-04-26 04:01
Closing as duplicate of https://github.com/brave/brave-browser/issues/37033

**Closed by bsclifton** 2024-04-26 04:01 UTC
Labels: priority/P3, QA/Yes, enterprise, OS/Desktop
