### ISSUE TITLE
Desktop - unnecessary scroll bar on sections of Customize Dashboard popup

### ISSUE THREAD

**Issue by phoogm** [brave/brave-browser#12048] opened 2020-10-08 10:40 UTC
Closed #11374 via brave/brave-core#6634. -> This issue is still showing

On a new tab when selecting the Customize option a scrollbar is displayed while the content fits the popup

## Steps to Reproduce

   1. Open a new Tab
   2. Click on Customize
   3. Observe an unnecessary scoll bar is displayed

## Actual result:
<img width="738" alt="Screen Shot 2020-10-08 at 12 38 55 PM" src="https://user-images.githubusercontent.com/56597375/95448223-47720880-0963-11eb-81d1-9091b63bffa0.png">

## Expected result:
When the content fits the popup no scrollbar should be displayed.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 1.15.72 Chromium: 86.0.4240.75 (Official Build) (x86_64)
-- | --
Revision | c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}
OS | macOS Version 10.16 (Build 20A5384c) -> This is Mac OS Big Sur developer build version 9

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:
Thanks for looking into, best regards.

**Comment by srirambv** [comment] 2020-10-08 13:03
Dupe of #11374. This will be fixed in the next release

**Closed by srirambv** 2020-10-08 13:03 UTC
Labels: OS/Desktop
