### ISSUE TITLE
SHOWING 500 BILLION MATIC BALANCE IN MY BROWSER WALLET :O

### ISSUE THREAD

**Issue by F4brtB4425** [brave/brave-browser#22362] opened 2022-04-17 07:54 UTC
## Description 

**YESTERDAY I OPEND MY BRAVE WALLET AND TO MY SURPRISE HAD A (MATIC) BALANCE OF 500,000,000,000.00!!!
NATURALY I TRIED TO TRANSFER SOME OF IT TO AN OTHER ADDRESS AND OBVIOUSLY THE AMOUNT NEVER ARRIVED TO THE DESTINATION ADDRESS BECAUSE SOMETHING IS WRONG WITH MY BROWSER WALLET??? AT THE MOMENT THE MATIC BALANCE IN MY BROWSER WALLET IS 374,673,373,952.42. THIS IS THE ADDRESS ON POLYSCAN 0xf1fab4bBCe66b3A93Ba55eAb1D5276Ed68e1CE6D. OBVIOUDLY IT'S NOT SHOWING UP THERE SO I'M SUSPECTING THAT THERE'S SOMETHING WRON WITH MY BRAVE WALLET? THE STRANGE THING IS THAT I RESTORED THIS WALLET FROM MY SEED PHRASE ON ANOTHER COMPUTER ADDED THE POLYGON(MATIC) NETWORK TO MY BROWSER WALLET AND THE SAME INCORRECT BALANCE SHOWS UP ONCE AGAIN.** 

## Steps to Reproduce

   1. 
![BRAVE-WALLET-BALANCE-ERROR](https://user-images.githubusercontent.com/61804560/163705741-8eb0d7aa-9e00-48cf-bac2-26d5bd16a111.png)

   2. 
   3. 

## Brave version (brave://version info)

**V 1.37.116**

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

![BRAVE-WALLET-BALANCE-ERROR](https://user-images.githubusercontent.com/61804560/163705756-c6b67dbd-7e20-4a23-a191-51d131857709.png)

**Comment by Douglashdaniel** [comment] 2022-04-19 16:09
@F4brtB4425 could you go to `brave://settings/wallet/networks` and for the `Polygon Network` click edit and see what the `Chain's currency decimals` is set as? Should be `18`.

![Screen Shot 2022-04-19 at 10 07 47 AM](https://user-images.githubusercontent.com/40611140/164047738-8ead2ad5-3ab4-4820-a46b-0b19e870b55c.png)

**Comment by F4brtB4425** [comment] 2022-04-23 07:23
Hi there

Problem fixed. Although it was nice to see that balance for a few days... :/ :)

Thanks for the help!!!!!!

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by bbondy** [comment] 2022-05-17 13:41
Closing as a duplicate of https://github.com/brave/brave-browser/issues/19059

**Closed by bbondy** 2022-05-17 13:41 UTC
Labels: feature/wallet, OS/Desktop
