### ISSUE TITLE
Verified pubs shows up as not verified due to delay in fetching verified pubs list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2816] opened 2019-01-04 15:34 UTC
## Description 

Verified pubs shows up as not verified due to delay in fetching verified pubs list

## Steps to Reproduce

   1. Start a clean profile 
   2. Enable Rewards
   3. Before wallet is created, open a new tab and visit a verified pub site
   4. Click on BR panel, shows the pub is not verified
   5. Wait for a few seconds/mins until the list is downloaded, shows as verified in BR panel

## Actual result:

![screenshot from 2019-01-04 20-57-48](https://user-images.githubusercontent.com/17010094/50695898-02b98f00-1064-11e9-83f6-3510c83398db.png)

## Expected result:
![screenshot from 2019-01-04 20-58-02](https://user-images.githubusercontent.com/17010094/50695902-051be900-1064-11e9-9369-ee189d63588b.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A

**Comment by kjozwiak** [comment] 2019-01-04 21:40
@srirambv I believe we were running into this when we were releasing the `0.58.17` & `0.57.18` hotfixes during the holidays. Where it takes a bit of time to start showing which publishers were verified.

**Comment by iAlertServices** [comment] 2019-01-13 23:01
Waiting several minutes doesn't correct the problem on my end.  Waited multiple hours.  Is there a target date when this will be fixed being this is a major user feature?

**Comment by kjozwiak** [comment] 2019-01-14 06:16
@iAlertServices there's currently no target date yet but the issue has been prioritized. Just a matter of a developer picking it up.

**Comment by GeetaSarvadnya** [comment] 2019-01-14 11:33
1+https://community.brave.com/t/i-cant-send-a-second-tip-anymore/42370/7

**Comment by Sh1d0w** [comment] 2019-01-28 18:05
I have the same problem. It is actual a major issue, since I've verified one of my wbesites 2 weeks ago and it still shows as non verified. 

I was advised to delete `~/Library/Application\ Support/BraveSoftware/Brave-Browser/Default/publishers_list` after I deleted it and waited several hours to be re-downloaded the problem still exists.

If I open the file and search for my website it is there:

```
["XXXXXXXXXXX.com",true,false,{}]
```

But in Brave Rewards it shows as unverified, so I can not receive tips.

**Comment by kjozwiak** [comment] 2019-01-28 19:36
> But in Brave Rewards it shows as unverified, so I can not receive tips.

@Sh1d0w you'll still be able to receive tips from other users that have an up to date `publishers_list`.

**Comment by Sh1d0w** [comment] 2019-01-28 19:38
@kjozwiak My point is I think there is a bug in Brave, since I've taken the steps to make my list up to date as it seems it was not updating automatically for some reason, but even then after refreshing the list and verifying the website is there, it still shows unverified.

**Comment by jonathansampson** [comment] 2019-01-30 19:51
@Sh1d0w I believe this is a separate issue. I was speaking with @NejcZdovc recently about this, and failure of the `get_publishers()` method to return appropriate publisher information. So even if your `publishers_list` is _up to date_, some properties may still experience this issue.

We're looking further into the problem now, and will provide an update when we have a lead.

**Comment by kjozwiak** [comment] 2019-01-30 22:05
@Sh1d0w yup, definitely aware of the issue regarding publishers lists sometimes not being pulled. Regarding the above comment, I just wanted to point out that even though you're having issues pulling the publishers list, you'll still be getting tips from other folks 👍

Are you still having the same issue? The list  should be downloaded every 48hrs.

**Comment by Sh1d0w** [comment] 2019-01-31 01:19
@jonathansampson Since it is happening to me atm, let me know if I can provide more info like the verified domain name or some other logs. I can send those via email if needed so you can check them and see if there is any clue?

@kjozwiak Yes I am still experiencing this. I've verified the website more than two weeks ago, removed the `publishers_list` a week ago, it got refreshed I can see the website is there now, but Brave still shows my website is not verified :( I am not sure if others can send tips tho, since I've re-downloaded the publisher list and still there is a problem.

Let me know if I can help in some way to identify the issue.

**Comment by jonathansampson** [comment] 2019-01-31 19:36
@Sh1d0w Would you be willing to download our developer preview and see if you experience the issue there as well? You can get it online at brave.com/download-dev. Installing it *will not* impact your primary Brave install.

**Comment by Sh1d0w** [comment] 2019-02-01 04:08
@jonathansampson Sure I have the dev version installed long before it was released in the official channel. I've updated it to the latest dev, but unfortunately when trying to re - enable Brave Rewards I see:

<img width="377" alt="screenshot 2019-02-01 at 6 05 49" src="https://user-images.githubusercontent.com/5074917/52102157-9fca0200-25e7-11e9-91fe-a54de6ade66e.png">

I am ok for a Skype call, send me your Skype id to radoslav.vitanov@icloud.com and I will add you.

**Comment by NejcZdovc** [comment] 2019-02-01 16:43
@Sh1d0w if you installed dev long time ago wallet was created on staging, where dev now points to production. You will need to create new wallet or run staging flag when you start browser. More info here https://github.com/brave/brave-browser/wiki/Rewards#flags

**Comment by jonathansampson** [comment] 2019-02-01 17:07
Following a call with @Sh1d0w and @NejcZdovc, it was determined that the site in question wasn't marked as _verified_ in the `publisher_info_db`. After updating to 0.59.34 the issue was no longer reproducible.

**Comment by jonathansampson** [comment] 2019-02-01 17:07
Closing as it appears 0.59.34 resolves the issue.

**Comment by kjozwiak** [comment] 2019-02-02 20:47
@NejcZdovc out of curiosity, do we know which fix in `0.59.34 Chromium: 72.0.3626.81` might have fixed this?

**Comment by Sh1d0w** [comment] 2019-02-02 21:57
@kjozwiak I am not completely sure this is fixed in `0.59.34`

After I've updated to that version the site immediately became verified as it should, but maybe the DB update that was triggered was caused by the update itself?

I have second website that I've verified on 31st of Jan, today it still displays as unverified, just checked.

I see it is not present in publishers_list, so I again deleted it and will wait for it to refresh and see if it will show as verified once it does. But then this rises the question:

How frequently `publishers_list` get refreshed and do I have to delete it manually every time I verify a website? Last time had to wait two weeks before I've deleted it, so it can be re - downloaded?

cc @jonathansampson @NejcZdovc

**Comment by NejcZdovc** [comment] 2019-02-03 05:55
@Sh1d0w currently it's 48h, but that will be changed in 0.60 to 24h

**Comment by Sh1d0w** [comment] 2019-02-04 03:08
@NejcZdovc Today the list updated and the website appears as verified, so all good.

I guess the confusion comes because of the delay to refresh `publishers_list` maybe on the publishers website it needs to let you know that the website will appear as verified after up to XX hours, because regular users don't know how it works behind the scenes and may become confused too.

**Comment by jonathansampson** [comment] 2019-02-08 05:05
I *do not* think 59.34 resolved this, unless 59.35 regressed. I just ran into a domain today that was in the `publisher_list`, but marked as _not verified_ in the `publisher_info_db` file. Reopening.

**Comment by NejcZdovc** [comment] 2019-02-08 06:43
closing as domain was not in `publisher_list`. When we updated `publisher_list` domain was marked as verified.

**Closed by NejcZdovc** 2019-02-08 06:43 UTC
Labels: closed/invalid

**Comment by Sh1d0w** [comment] 2019-02-14 01:26
As I expected there is a lot of confusion regarding the interval that `publishers_list` gets updated, so I want again to suggest considering putting that information somewhere visible in the publishers platform when verifying a channel. See some of the topics below.

https://www.reddit.com/r/brave_browser/comments/aqb3ff/verified_publisher_site_showing_as_not_verified/

https://www.reddit.com/r/BATProject/comments/aq8uyp/brave_rewards_says_site_not_verified_despite/
