### ISSUE TITLE
Cannot open created browser shortcut on macOS Catalina.

### ISSUE THREAD

**Issue by cosmeao** [brave/brave-browser#7814] opened 2020-01-18 22:55 UTC
## Description 
I am trying to create dedicated browser shortcuts for a couple of websites that I use on a daily basis. I have had no issues doing so in Linux but on MacOS the created browser shortcuts fail to load properly. In short, for a given website, e.g., brave.com, I create a standalone browser shortcut which opens but then very quickly closes itself.

## Steps to Reproduce

   1.  Pick you favorite website, e.g., brave.com
   2. Navigate to your selected website using the brave-browser
   3.  Once at the selected website click the top-right menu button and select: More Tools -> Create Shortcut ....
4. Give a name to your standalone browser shortcut app
5. Make sure that "Open as window" is selected.
6. Click the Create button
7. Find the created shortcut app under ~/Applications/Brave Browser Apps/Name_of_Website.app
8. Double click or right-click and select open to start the shortcut.
9. Created shortcut will open for a fraction of a second and then close itself quickly.

## Actual result:

No screenshots to share since the app just closes on itself in mere seconds.

## Expected result:
Shortcut website opens as a standalone brave browser.

## Reproduces how often: 

Every time.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Nope, tried it.
- Does the issue resolve itself when disabling Brave Rewards? Nope, do not use them.
- Is the issue reproducible on the latest version of Chrome? Nope, it works perfectly on Chrome!

**Comment by timsayshey** [comment] 2020-02-17 15:09
+1

**Comment by rebron** [comment] 2020-03-06 17:45
@cosmeao Can you try this with the latest 1.4.96 and let us know if you're still running into this issue? Are you having issues with true pwa sites like Twitter.com?

**Comment by jesse-troy** [comment] 2020-03-10 18:47
I am having the same issue. It looks like the window tries to open, but it appears to close immediately.

@rebron I am using latest version [1.4.96] on osx 10.15.3. I tested with the application I want to open as well as Twitter.com and am seeing the same behavior

**Comment by rebron** [comment] 2020-03-10 21:37
@jesse-troy Are you using 'Create Shortcut' in the menu or using the icon in the url bar?

<img width="54" alt="Screen Shot 2020-03-10 at 2 30 40 PM" src="https://user-images.githubusercontent.com/5951041/76361210-bf982300-62db-11ea-867f-633b06107268.png">

@cosmeao I'm wondering if it this is a permissions issue in Security and Privacy -> Full Disk Access for Brave. Could be something else. Mentioning as I'm unable to reproduce.
<img width="673" alt="Screen Shot 2020-03-10 at 2 34 24 PM" src="https://user-images.githubusercontent.com/5951041/76361426-44833c80-62dc-11ea-8a6b-dac058d665f1.png">

Shortcut I created, selecting Open in New Window using 1.4.96 with macOS Catalina.
<img width="1503" alt="Screen Shot 2020-03-10 at 2 36 20 PM" src="https://user-images.githubusercontent.com/5951041/76361624-a17ef280-62dc-11ea-8a93-6da7e6dae791.png">

**Comment by jesse-troy** [comment] 2020-03-25 14:37
@rebron I do not see that icon at all in my URL bar. No idea why that is the case. I am using More Tools > Create Shortcut and then checking open as window. 

I tried giving Brave full disk access and it has the same behavior. 

When starting the shortcut/app it does seem to open for a fraction of a second and then it closes.

**Comment by rebron** [comment] 2020-03-25 15:36
@jesse-troy The icon will show in the url bar for some sites that are setup to be a progressive web app, pwa such as Twitter twitter.com/home or Google Photos for example. It'll be an install icon and then change to a launch icon when visiting the site again.

<img width="371" alt="Screen Shot 2020-03-25 at 8 31 24 AM" src="https://user-images.githubusercontent.com/5951041/77554254-13c20c00-6e73-11ea-930f-9b4cc3242347.png">

I'm able to create a shortcut that way and your way via `Create Shortcut` but I remember others had this issue before.

**Comment by msacchiPPRO** [comment] 2020-10-27 11:39
This is still an issue for me with the latest version of Brave on Catalina. 
The issue has been quiet for a while, perhaps somebody found a workaround by now?

**Comment by dansteren** [comment] 2020-10-28 20:48
I know this doesn't add much, but to be honest this is the whole reason I stopped using Brave. I have lots of windows open all the time (Jira, Google Calendar, Gmail). With vanilla chrome I can have these as separate icons and `cmd`+`tab` through them. If this was working in Brave I would switch over in a heartbeat. But without this it really cripples my workflow.

So yeah, I know it doesn't really help solve the problem. I just wanted to say I'm still following this issue and can't wait for it to be resolved. And a big thank you to whoever does work on it :)

**Comment by msacchiPPRO** [comment] 2020-10-29 14:05
This appears in `system.log` when trying to open a shortcut

```
Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043910). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class CommandDispatcher is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b79f40) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043960). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class ConstrainedWindowAnimationBase is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b79f90) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e0439b0). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class ConstrainedWindowAnimationShow is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a008) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043a28). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class ConstrainedWindowAnimationHide is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a058) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043a78). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class ConstrainedWindowAnimationPulse is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a0a8) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043ac8). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class ButtonUtils is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a0f8) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043b18). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class TextFieldUtils is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a148) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043b68). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class FindPasteboard is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a170) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043b90). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class FlippedView is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a1e8) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043c08). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class FocusTracker is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a210) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043c30). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class WeakPtrToMenuModelAsNSObject is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a260) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043c80). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class MenuControllerCocoa is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a2b0) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043cd0). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class ToolTipBaseView is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a300) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043d20). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class CrTrackingAreaOwnerProxy is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a350) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043d70). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class CrTrackingArea is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a3a0) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043dc0). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class UnderlayOpenGLHostingWindow is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a3f0) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043e10). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class WeakPtrNSObject is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a468) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043e88). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class CrPasteboardItemWrapper is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a490) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043eb0). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class NowPlayingInfoCenterDelegateCocoa is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a4e0) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043f00). One of the two will be used. Which one is undefined.
Oct 29 15:04:18 ma14101 app_mode_loader[73698]: objc[73698]: Class RemoteCommandCenterDelegateCocoa is implemented in both /Users/msacchi/Applications/Brave Browser Apps.localized/Google Chat.app/Contents/MacOS/app_mode_loader (0x101b7a530) and /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/86.1.15.76/Brave Browser Framework (0x10e043f50). One of the two will be used. Which one is undefined.
Oct 29 15:04:19 ma14101 com.apple.xpc.launchd[1] (com.brave.Browser.app.chfbpgnooceecdoohagngmjnndbbaeip.28080[73698]): Service exited due to SIGABRT
```

**Comment by ctwhome** [comment] 2020-12-06 12:44
Please mark this problem as urgent

**Comment by ctwhome** [comment] 2020-12-06 12:56
> @jesse-troy The icon will show in the url bar for some sites that are setup to be a progressive web app, pwa such as Twitter twitter.com/home or Google Photos for example. It'll be an install icon and then change to a launch icon when visiting the site again.
> 
> <img alt="Screen Shot 2020-03-25 at 8 31 24 AM" width="371" src="https://user-images.githubusercontent.com/5951041/77554254-13c20c00-6e73-11ea-930f-9b4cc3242347.png">
> 
> I'm able to create a shortcut that way and your way via `Create Shortcut` but I remember others had this issue before.

Does still work for you? which version do you use?

**Comment by dndrsn** [comment] 2021-02-26 14:56
I'm seeing a similar issue with Big Sur.  I am able to open the shortcut app in a window, but when I attempt to interact with the window in *any* way it immediately closes.  Using Brave V1.20.110 on macOS 11.2.1.

**Comment by ctwhome** [comment] 2021-02-26 16:32
So in my case, a window manager was conflicting. Try to close all programs and see which one is causing the problem

**Comment by dndrsn** [comment] 2021-02-26 19:48
@ctwhome Thanks.  That was remarkably helpful.  The conflict is with Better Touch Tool's window snapping features (https://folivora.ai/).  Curious why this is problem with Brave "shortcut app" windows and not with any other windows (including Chrome app windows) that I have encountered.

**Comment by ctwhome** [comment] 2021-02-27 06:36
It took me a hell of a time to figure it out

**Comment by ron-wolf** [comment] 2021-04-04 21:25
@ctwhome I’ve always used the toolbar icon, the apps it creates experience the same problem. IMO, it really shouldn't crash just because accessibility is turned on.

**Comment by dansteren** [comment] 2021-09-07 07:21
I'm not sure what changed but I just checked this functionality today on a whim after updating Brave and I can create shortcuts that open in a separate window just like I was able to in years past. I'm on Version 1.29.77 Chromium: 93.0.4577.63 (Official Build) (x86_64) on macOS Big Sur. I have two Brave user profiles and the shortcuts work as expected across the two profiles. Everything is working as expected for now!

Once again, not sure how long this has been fixed or who fixed it but I'd love to tip someone for their hard work. Thank you!!!

**Comment by bsclifton** [comment] 2021-09-07 07:42
Thanks for following up @dansteren - I think this was fixed with Chromium 92

cc: @petemill to confirm - I think we can close this out

@ron-wolf @ctwhome and others - can you please try this also to see if it works?

**Comment by ctwhome** [comment] 2021-09-09 07:19
@bsclifton I started using 'tiles for mac' and never had the problem again. thanks for taking care.

**Comment by bsclifton** [comment] 2021-09-10 16:37
I'll go ahead and close this out! Thanks for following up folks 😄

**Closed by bsclifton** 2021-09-10 16:37 UTC
Labels: OS/macOS, needs-more-info, feature/pwa
