### ISSUE TITLE
[Android] Rewards reset doesn't work

### ISSUE THREAD

**Issue by Maxime-J** [brave/brave-browser#14055] opened 2021-02-09 12:30 UTC
## Description
Option to reset Brave Rewards doesn't work

## Steps to reproduce
With Rewards activated
1. Settings > Advanced | Brave Rewards > Reset Brave Rewards

## Actual result
There's only a confirmation prompt and nothing is done on confirm.

## Expected result
There should be a prompt alerting that Brave needs to be restarted
and Brave Rewards should be resetted afterwards.

## Issue reproduces how often
Every time

## Version/Channel Information:
Every Play Store version

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.19.92
1.21.48
1.22.9

**Comment by srirambv** [comment] 2021-04-19 04:21
Dupe of #8780 &  #8776

**Closed by srirambv** 2021-04-19 04:21 UTC
Labels: OS/Android
