### ISSUE TITLE
windows not opening/pages not rendering when `--ozone-platform-hint=wayland`

### ISSUE THREAD

**Issue by Visual-Dawg** [brave/brave-browser#37498] opened 2024-04-11 05:56 UTC
Update: To fix run it with the following flag: `--ozone-platform-hint=wayland`

## Description 
The Brave Nightly version on Arch Linux running Hyprland with AMD does not render anything.

The window opens and react to input (opening a new window opens it, but nothing renders)

## Steps to Reproduce

   1. Run `brave-browser-nightly`

## Actual result:

![image](https://github.com/brave/brave-browser/assets/28539403/88587d1a-b432-4f5b-adeb-71c64889fcf9)

```ini
❮ brave-browser-nightly
[46910:46910:0411/084925.135712:ERROR:chrome_browser_cloud_management_controller.cc(161)] Cloud management controller initialization aborted asCBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the officialGoogle Chrome build.
[46910:46910:0411/084925.156727:ERROR:content_settings_pref.cc(406)] Invalid pattern strings: https://w=149,h=149:443,*
[46910:46910:0411/084935.197642:ERROR:sharing_service.cc(221)] Device registration failed with fatal error
```

## Expected result:

On Brave stable:
![image](https://github.com/brave/brave-browser/assets/28539403/060f5fdb-9d54-421f-bcf4-023a3da2665d)

## Reproduces how often: 

No steps to reproduce

## Brave version (brave://version info)

```ini
Brave | 1.66.74 Chromium: 124.0.6367.29 (Official Build) nightly (64-bit)
Revision | 43c41a798003efcabf0d292cb2a5efdcc633857b
OS | Linux
JavaScript | V8 12.4.254.8
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Command Line | /opt/brave.com/brave-nightly/brave --disable-domain-reliability --enable-dom-distiller --enable-distillability-service --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --enable-features --disable-features --flag-switches-begin --ozone-platform-hint=auto --enable-features=OverlayScrollbar --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions --ozone-platform=wayland
Executable Path | /opt/brave.com/brave-nightly/brave
Profile Path | /home/vdawg/.config/BraveSoftware/Brave-Browser-Nightly/Default
Active Variations | AllowCertainClientHintsStudy:EnabledBraveAdblockExperimentalListDefaultStudy:EnabledBraveAdblockMobileNotificationsListDefault:EnabledBraveAdsNewTabPageAdsStudy:EnabledBraveAdsSiteVisitStudy:EnabledBraveAdsTextClassificationPageProbabilitiesStudy:EnabledBraveAggressiveModeRetirementExperiment:DisabledBraveAutoTranslateStudy:AutoTranslateDisabledBraveDebounceStudy:EnabledBraveForgetFirstPartyStorage:EnabledBraveGoogleSignInPermissionStudy:EnabledBraveHorizontalTabsUpdateEnabledStudy:EnabledBraveHttpsByDefaultRolloutStudy:EnabledBraveLocalhostAccessPermissionStudy:EnabledBraveP3AConstellationEnabled:EnabledBraveP3ATypicalJSONDeprecationEnabled:EnabledBraveRequestOTRTabRolloutStudy:EnabledBraveRewardsAllowSelfCustodyProvidersStudy:EnabledBraveRewardsWebUiPanelStudy:EnabledBraveScreenFingerprintingBlockerStudy:EnabledBraveSearchAdStudy:EnabledBraveWebViewRoundedCornersStudy:EnabledClampPlatformVersionClientHint:DisabledCookieListDefaultStudy:EnabledCosmeticFilteringChildFramesStudy:EnabledDefault1pBlockingStudy:DisabledDefaultBraveCommandsStudy:EnabledDefaultBraveOmniboxMoreHistoryStudy:EnabledDisableReduceLanguage:EnabledEphemeralStorageStudy:EnabledHangWatcher:DefaultPartitionedCookies:EnabledPrivateNetworkAccessKillswitch:Disabled_PrivateNetworkAccessKillSwitchUseWritePixelsYUV:Disabled_UseWritePixelsYUVUserActivityStudy:Triggers

```

## Version/Channel Information:

- Can you reproduce this issue with the current release?  **No**
- Can you reproduce this issue with the beta channel? **I dont know**
- Can you reproduce this issue with the nightly channel? **Yes**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **I dont know**
- Does the issue resolve itself when disabling Brave Rewards? **I dont know**
- Is the issue reproducible on the latest version of Chrome? **I dont know**

**Comment by asheriif** [comment] 2024-04-11 23:39
Having the same issue with Brave Beta. Wayland, KDE, Nvidia.

**Comment by Visual-Dawg** [comment] 2024-04-12 08:20
It renders again after an update I think, but it looks like it does through so through X, as fractional scaling doesnt work properly.
`Brave Browser 124.1.67.2 nightly`

**Comment by Visual-Dawg** [comment] 2024-04-12 09:14
`Brave Browser 124.1.67.3 nightly` also has it

**Comment by asheriif** [comment] 2024-04-12 12:47
Yeah still the same after the latest beta update as well. Only renders when explicitly told to run under X which is pretty inconvenient because Xwayland is still a mess.

**Comment by asheriif** [comment] 2024-04-13 00:10
Yeah the issue only happens when running Brave (Beta or Nightly) with Ozone platform set to Wayland. The only workaround under a Wayland environment seems to running Brave with Ozone platform set to X which makes it run under XWayland which is a mess, or to use the disable gpu flag which is also not a solution.

I wasn't having issues the past few months and Brave Beta was running perfectly fine for me (including hardware acceleration) on Arch under Wayland and Nvidia proprietary drivers (latest). This just started after an update a couple of days ago.

I have the Vulkan flag set to disabled. Latest Chromium Snapshot (125.something) launches with Ozone platform set to Wayland but lots of things are messed up, so yeah looks like yet another Chromium/Electron issue with Wayland. It never ends :(

I'll go back to Brave stable (Chromium 123.something) for now. No issues there under Wayland and hardware acceleration works fine.

**Comment by janpeterd** [comment] 2024-04-15 20:45
I have the same issue with chromium
![afbeelding](https://github.com/brave/brave-browser/assets/62998174/00e728b6-a3d6-4250-8fa3-dc95b07db36c)

**Comment by rillian** [comment] 2024-04-16 19:46
I can reproduce with 1.67.11 Chromium: 124.0.6367.29 (Official Build) nightly (64-bit) on Fedora 39 x86_64, gnome desktop with intel Xe graphics. It works fine with `ozone-platform-hint` set to default, but I get nothing drawn at all with it set to `wayland`. Ozone Platform in brave://gpu defaults to `x11` on my system.

So switching back to x11 is likely a work around for problematic releases.

**Comment by rillian** [comment] 2024-04-16 19:58
Note on switching back: I used the flags/experiments page to change this, which is unavailable if nothing is drawing. To fix it I edited `$HOME/.config/BraveSoftware/Brave-Browser-Nightly/Local State` to remove the ozone hit string from the experiments array.

If that's too difficult, you can delete the whole profile directory. :(

**Comment by mak448a** [comment] 2024-04-17 23:27
It's not rendering anything on Brave stable now.

**Comment by archerallstars** [comment] 2024-04-18 05:25
This is a Chromium upstream issue: https://issues.chromium.org/issues/329678163

To fix this issue, the user must run Brave through the command line with `--ozone-platform=wayland` flag, or edit the desktop file with the flag.

**Comment by Mikaela** [comment] 2024-04-18 05:39
> To fix it I edited `$HOME/.config/BraveSoftware/Brave-Browser-Nightly/Local State` to remove the ozone hit string from the experiments array.
> If that's too difficult, you can delete the whole profile directory. :(

A bit easier is just changing the 3 there to 0, but it started looking blurry and I don't like this "workaround".

> It's not rendering anything on Brave stable now. Ozone set to Wayland.

I can confirm on `Brave Browser 124.1.65.114` if the version numbers matter.

> This is a Chromium upstream issue: https://issues.chromium.org/issues/329678163

Starred in hopes of them counting that as a 👍🏻 and prioritising.

> To fix this issue, the user must run Brave through the command line with `--ozone-platform=wayland` flag, or edit the desktop file with the flag.

Thanks, this actually works for me. I would just add that `--ozone-platform=wayland` is a different flag from `--ozone-platform-hint=wayland` which alone won't be enough as when I first read your comment, I thought they were the same.

**Comment by mufeedali** [comment] 2024-04-18 14:30
On Arch with the `brave-bin` AUR package, you can add `--ozone-platform=wayland` to `~/.config/brave-flags.conf`.

**Comment by TuxTheAstronaut** [comment] 2024-04-18 14:32
having same issue too but running brave with --enable-features=UseOzonePlatform --ozone-platform=wayland fixed it for me but setting ozone to wayland in chrome flags menu dose not work

**Comment by rillian** [comment] 2024-04-18 22:31
Chromium has [merged a fix](https://chromium-review.googlesource.com/c/chromium/src/+/5375669) which addresses the issue for me. Hopefully we can get that into a release soon.

**Comment by kjozwiak** [comment] 2024-04-20 05:57
Closing as the above has been resolved via https://github.com/brave/brave-core/pull/23166 👍

**Closed by kjozwiak** 2024-04-20 05:57 UTC
Labels: bug, OS/Linux, QA/Yes, release-notes/include, OS/Desktop

**Comment by kjozwiak** [comment] 2024-04-20 06:06
The above requires `1.65.116` or higher for `1.65.x` verification 👍

**Comment by btlechowski** [comment] 2024-04-23 15:22
Verified with

Brave | 1.65.118 Chromium: 124.0.6367.60 (Official Build) (64-bit)
-- | --
Revision | 8ecd7a3ff4b4d81f25b94f5b92ab7130587888cd
OS | Linux


Reproduced the issue:

![image](https://github.com/brave/brave-browser/assets/34715963/88734c68-cad6-4791-82bf-2c67169b2306)|![image](https://github.com/brave/brave-browser/assets/34715963/80968c9b-e502-4efb-9bf7-824f411b7c23)
--|--

Verified fixed:

![image](https://github.com/brave/brave-browser/assets/34715963/159b7724-875f-4eb1-aed0-8f067d520987)|![image](https://github.com/brave/brave-browser/assets/34715963/92f66f3c-21e3-44e7-922d-aad14d8f028c)
--|--
