### ISSUE TITLE
Standard ad blocking is not correctly blocking third-party ad leftovers

### ISSUE THREAD

**Issue by gigabit2** [brave/brave-browser#14299] opened 2021-02-22 17:59 UTC
## Description 

My understanding is that "Standard" mode for ad blocking should block third-party ads, including cosmetics (https://github.com/brave/brave-browser/issues/8475). I am finding that whilst it does block the ads, it does not always block the leftovers.

For example on https://forums.macrumors.com, although the ad is blocked, the leftover is not.

## Steps to Reproduce

   1. Go to https://forums.macrumors.com

## Actual result:

Observe that box is left where the ad was (at the top of the screen):

<img width="1203" alt="Screenshot 2021-02-22 at 18 00 14" src="https://user-images.githubusercontent.com/4457688/108749645-fb9db580-7537-11eb-8701-ab4fbb554808.png">

## Expected result:

Box should be hidden, as it contained a third-party ad which has been blocked.

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

Version 1.20.108 Chromium: 88.0.4324.182 (Official Build) (arm64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 

Yes

- Can you reproduce this issue with the beta channel? 

Yes

- Can you reproduce this issue with the nightly channel? 

Yes

## Other Additional Information:

I raised the issue originally here: https://community.brave.com/t/macrumors-com-whitespace-is-left/202137. Changes were made which correctly block the ad leftovers on the homepage but the leftover box remains on the forums. 

I queried this and I was advised that we need to use aggressive mode but I don't think this should be the case. Standard mode should block these leftovers: https://github.com/brave/brave-browser/issues/8475 - "by default we have cosmetic filtering that attempts to differentiate 1p and 3p ads, and only block the latter."

I have tested on other browsers (Edge, Chrome) using uBlock Origin and Easylist there and the box is correctly blocked.

## Miscellaneous Information:

N/A

**Comment by gigabit2** [comment] 2021-02-22 18:27
https://www.independent.co.uk/voices/keir-starmer-labour-shadow-chancellor-anneliese-dodds-b1805020.html - is another example.

**Comment by antonok-edm** [comment] 2021-03-25 22:38
@gigabit2 the heuristics we used have gotten some updates and I don't see any empty spaces on those sites anymore - is it safe to close this issue?

**Comment by ryanbr** [comment] 2021-06-09 13:42
Closing request @gigabit2 @antonok-edm   Unable to reproduce in release/beta.

**Closed by ryanbr** 2021-06-09 13:42 UTC
Labels: OS/Android, OS/Desktop
