### ISSUE TITLE
Typing Too Fast Too Soon In Location Bar Problem

### ISSUE THREAD

**Issue by jamesgoodhouse** [brave/brave-browser#4055] opened 2019-04-09 13:30 UTC
## Description 
When I open a new tab and immediately start typing, the first few characters are removed once the URL history is loaded in the location bar.

## Steps to Reproduce

   1. Visit a site like `gmail.com` so that it is in your history
   1. Open a new tab via `CMD-T`
   2. Immediately start typing out `gmail.com`

## Actual result:
Instead of having exactly what I typed (e.g., `gmail.com`) remain in the location bar upon opening a new tab, the first several characters are removed once the URL history is loaded.

## Expected result:
I would expect that as soon as I can start typing into the location bar, that it will remain there after everything has loaded.

## Reproduces how often: 
I can reproduce this every time if I am quick enough with my typing.

## Brave version (brave://version info)
0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)

### Reproducible on current release:
Have not checked

**Comment by cndouglas** [comment] 2019-04-09 15:23
Thanks for the report @jamesgoodhouse! This is a duplicate of #3756; feel free to subscribe to that issue for updates. Fortunately, the Brave team is currently working on this bug.

**Comment by cezaraugusto** [comment] 2019-04-09 15:46
@cndouglas thanks for triaging! @jamesgoodhouse, please refer to the issue mentioned above and thanks for reporting. I'm keeping an eye close on this bug.

**Closed by cezaraugusto** 2019-04-09 15:46 UTC

**Comment by jamesgoodhouse** [comment] 2019-04-09 19:14
Thanks for pointing me in the right direction. I searched but struggled finding an already filed issue.
