### ISSUE TITLE
Translate button freezes

### ISSUE THREAD

**Issue by lina-kram** [brave/brave-browser#26615] opened 2022-11-08 15:13 UTC
## Description 
Hi team,
Whenever I try to translate a page from a foreign language, the button freezes and becomes unresponsive. I also don't get autosuggestion to translate (no pop-up). I initially had English (US), English (UK) and English set up in the browser, and I have since tested it with just English (US) and just English (UK) and it has not fixed the issue.

## Steps to Reproduce

   1. Go to any of these sites: 
- https://belsat.eu/ (original language: Belarusian)
- https://www.polsatnews.pl/ (language: Polish)
- https://www.n-tv.de/ (original language: German)
- https://www.elmundo.es/ (original language: Spanish)
   
2. Click on the Translate button on the right side of the address bar

## Actual result
Frozen button and no translation.

<img width="159" alt="Screenshot 2022-11-08 at 15 03 52" src="https://user-images.githubusercontent.com/72753797/200599802-5f3a5aa3-cec3-4008-8131-94b06a2a79ec.png">

## Expected result
Detection of the original language and an option to translate the page. Translation of the page.

<img width="331" alt="Screenshot 2022-11-08 at 15 07 35" src="https://user-images.githubusercontent.com/72753797/200600902-949d898a-ab1f-4273-b590-e0f24eefd06c.png">

## Reproduces how often
Always.

## Brave version
Brave | 1.45.118 Chromium: 107.0.5304.91 (Official Build) (x86_64)
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 12.6 (Build 21G115)

## Other Additional Information

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Yes, I have a separate profile where Rewards are disabled.

## Miscellaneous Information:
In my two other profiles within the same browser on the same device this issue does not occur.

**Comment by lina-kram** [comment] 2022-11-09 14:04
This issue is resolved when Google Translate extension is removed from the browser (I installed it ages ago before we had a translate feature). However, there must be other Brave users with a similar problem who aren't aware of our new feature.

**Comment by rebron** [comment] 2022-11-11 19:14
Closing as dupe of https://github.com/brave/brave-browser/issues/24715 and will be fixed with next week's release.

**Closed by rebron** 2022-11-11 19:14 UTC
Labels: bug, feature/translate, OS/Desktop, brave-translate
