### ISSUE TITLE
Parent segment is not defined in ads catalog for purchase intent ads

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#8968] opened 2020-04-01 17:59 UTC
Follow up to https://github.com/brave/brave-browser/issues/8047

purchase intent ads have `parentCode` defined, but parent is not defined

## Steps to Reproduce

1. Clean profile
2. Connect to US
3. Open `https://ads-serve.bravesoftware.com/v2/catalog`
4. Search for parent Code: `rRWCQL4-i`

## Actual result:

segment with code `rRWCQL4-i` does not exist
Only segment with `"parentCode": "rRWCQL4-i"` exists
```
"segments": [{
		"code": "RuHxHavV2",
		"name": "automotive purchase intent by category-mid luxury car",
		"parentCode": "5W5gsHA15"
	}, {
		"code": "mqiPIYccl",
		"name": "automotive purchase intent by make-audi",
		"parentCode": "rRWCQL4-i"
	}
],
```

## Expected result:
segment with code `rRWCQL4-i` exists

Working Example from production catalog(us):
```
"segments": [{
		"code": "z7floCfZA_P",
		"name": "Personal Finance-Financial Advisors",
		"parentCode": "F6B46w9iJd"
	}, {
		"code": "XoEKKv5PqWWf",
		"name": "Personal Finance-banking",
		"parentCode": "F6B46w9iJd"
	}, {
		"code": "_PEMAp6RE_k9",
		"name": "Personal Finance-Learn Stocks",
		"parentCode": "F6B46w9iJd"
	}, {
		"code": "J9YDYm6oQIMb",
		"name": "Personal Finance-investing",
		"parentCode": "F6B46w9iJd"
	}, {
		"code": "F6B46w9iJd",
		"name": "Personal Finance"
	}, {
		"code": "BwhnRpkM8sF",
		"name": "Personal Finance-Personal Loans",
		"parentCode": "F6B46w9iJd"
	}, {
		"code": "5vPJWdHAEMlr",
		"name": "Personal Finance-stocks",
		"parentCode": "F6B46w9iJd"
	}]
```
Parent is defined in:
```
		"code": "F6B46w9iJd",
		"name": "Personal Finance"
```
The rest of the segments point to it through `parentCode`

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.7.78 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron @tmancey @moritzhaller  @jsecretan

**Comment by tmancey** [comment] 2020-07-10 10:34
Discussed with @moritzhaller and agreed to close issue as a duplicate of https://github.com/brave/brave-browser/issues/8486

**Closed by tmancey** 2020-07-10 10:34 UTC
Labels: bug, feature/ads
