### ISSUE TITLE
Bug when you try do a Swap with ETH

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#22600] opened 2022-04-28 14:32 UTC
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Douglashdaniel** [comment] 2022-05-04 15:30
Closing as duplicate of https://github.com/brave/brave-browser/issues/22680

**Closed by Douglashdaniel** 2022-05-04 15:30 UTC
Labels: bug, closed/duplicate, feature/wallet, OS/Desktop, feature/wallet/swap
