### ISSUE TITLE
IPFS Companion not working

### ISSUE THREAD

**Issue by Grathium-Industries** [brave/brave-browser#7584] opened 2020-01-03 12:22 UTC
## Description 
Whenever i enable IPFS Companion from the settings brave crashes

## Steps to Reproduce

   1. Go to settings
   2. Toggle IPFS Companion
   3. BOOM it crashes...

## Actual result:
Complete browser crash

## Expected result:
enables IPFS companion

## Reproduces how often: 
Every Time

## Brave version (brave://version info)
Brave version v1.1.23

## Version/Channel Information:
Stable release channel

## Other Additional Information:
Working Linux Mint v19.2

**Comment by srirambv** [comment] 2020-01-03 12:26
Dupe of https://github.com/brave/brave-browser/issues/7325

**Closed by srirambv** 2020-01-03 12:26 UTC
