### ISSUE TITLE
Monthly contributions (tips) and Auto Contribute are not listed on brave://rewards or panel summary

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7526] opened 2019-12-27 08:29 UTC
## Description 

Found while testing #6744 
Monthly Tips are not listed under monthly contributions panel

## Steps to Reproduce

   1. Clean profile 1.3.75 staging env
   2. Claim the UGP grants
   3. Open https://duckduckgo.com/
   4. Open the BR panel and set the monthly contributions for https://duckduckgo.com/
   5. The monthly Tip isn't set and https://duckduckgo.com/ isn't displayed under monthly contributions panel.
  

## Actual result:

Monthly Tips are not listed under monthly contributions panel
![7526](https://user-images.githubusercontent.com/38657976/72361051-d6286080-3716-11ea-9e59-e9b30e5b8e92.gif)

## Expected result:
Monthly Tips should be listed under monthly contributions panel

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.3.75 Chromium: 79.0.3945.88 (Official Build) dev (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @ryanml @rebron

**Comment by btlechowski** [comment] 2020-01-04 11:30
Not reproducible on

Brave | 1.3.81 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/71764859-bbbbdf00-2eed-11ea-9be3-18fbf3a621d5.png)

**Comment by NejcZdovc** [comment] 2020-01-04 15:46
not reproduced on macOS

**Comment by masparrow** [comment] 2020-01-10 14:47
@GeetaSarvadnya Hi Geeta - can I just confirm what 'DDG' is in your steps? Presuming it was 'ddg.com' I tried to reproduce the above on Windows, but it worked fine; 

<img width="695" alt="Screenshot 2020-01-10 at 14 46 20" src="https://user-images.githubusercontent.com/11368284/72161474-1c4c8f80-33b8-11ea-9000-b98db01373b5.png">

**Comment by NejcZdovc** [comment] 2020-01-10 15:08
@masparrow ddg is https://duckduckgo.com/

**Comment by masparrow** [comment] 2020-01-13 09:21
Cheers @NejcZdovc - just for completeness, I did a monthly tip for duckduckgo.com - works fine.

Nb. I was using; Version 1.5.24 Chromium: 79.0.3945.117 (Developer Build) (64-bit) (src/brave - c6d60490d12f0b94437532bae4eb1c246c8495a4)

<img width="690" alt="Screenshot 2020-01-13 at 09 18 27" src="https://user-images.githubusercontent.com/11368284/72244361-09b79d80-35e6-11ea-8c31-460d47ff68e4.png">

**Comment by LaurenWags** [comment] 2020-01-13 16:41
Could not reproduce on macOS using

Brave | 1.3.90 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.14.6 (Build 18G103)

@GeetaSarvadnya how did you fund your wallet? you don't specify in the steps if you restored an old wallet or claimed a staging UGP grant. not sure if that makes a difference.

**Comment by GeetaSarvadnya** [comment] 2020-01-14 14:14
@LaurenWags I have funded the wallet by accepting the UGP grants.

**Comment by GeetaSarvadnya** [comment] 2020-01-14 14:28
@masparrow Issue is still reproducible. Just verified it on latest beta channel 1.3.91. Please find the gif below:
![7526](https://user-images.githubusercontent.com/38657976/72352433-4380c500-3708-11ea-910b-d0b87b01a174.gif)

**Comment by LaurenWags** [comment] 2020-01-14 15:53
Reproduced on macOS (see https://github.com/brave/brave-browser/issues/7709#issuecomment-574235189) using steps from https://github.com/brave/brave-browser/issues/7709#issuecomment-574223737

fyi @masparrow in case this additional information helps
cc @kjozwiak @rebron for consideration for the 1.3.x release

**Comment by LaurenWags** [comment] 2020-01-17 21:04
Also experiencing this with one time tips using 

Brave | 1.3.94 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.14.6 (Build 18G103)

My wallet balance decreases but the tip isn't shown on brave://rewards Tips panel, wallet summary, or when I click on the BAT logo to show the summary.

**Comment by kjozwiak** [comment] 2020-01-21 18:11
I finally managed to reproduce this one `Win 10 x64`. Once I reproduced the above once on the `Win 10 x64` machine, it started occurring every single time with new profiles. Example:

Attached [publisher_info_db.zip](https://github.com/brave/brave-browser/files/4092793/publisher_info_db.zip) which belonged to this particular profile.

![panelsIssue](https://user-images.githubusercontent.com/2602313/72830433-b92bea00-3c4e-11ea-9bc4-8d3305147823.gif)

Reproduced the above issue using the following build:

Brave | 1.3.97 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
--- | ---
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1909 (Build 18363.592)

However, I'm still having a hard time reproducing this on `macOS` but sounds like @LaurenWags ran into it via https://github.com/brave/brave-browser/issues/7526#issuecomment-575794413.

**Comment by masparrow** [comment] 2020-01-22 11:46
Verified as fixed by the PR https://github.com/brave/brave-core/pull/4372 - @LaurenWags recommend this is regression tested against that PR (or nightly once that PR is merged).

**Comment by LaurenWags** [comment] 2020-01-23 23:04
Retested on Nightly extensively while checking https://github.com/brave/brave-core/pull/4399#issuecomment-577823383 and https://github.com/brave/brave-core/pull/4372#issuecomment-577908068 and could not reproduce. Moving to 1.3.x milestone to be retested after these PRs are uplifted. Adding `QA/Blocked` label for now as well.


Brave | 1.5.53 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

**Closed** 2020-01-23 23:11 UTC
Labels: QA/Blocked, QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards, regression, release-notes/exclude

**Comment by LaurenWags** [comment] 2020-01-31 22:05
Verified passed with

Brave | 1.3.106 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified 1 time tip, recurring tip, and AC using previously self-funded anon wallet:
<img width="804" alt="6078 and 7526" src="https://user-images.githubusercontent.com/28145373/73571769-4e906080-443d-11ea-8896-531537e238f8.png">
<img width="683" alt="Screen Shot 2020-01-31 at 3 48 01 PM" src="https://user-images.githubusercontent.com/28145373/73573330-168b1c80-4441-11ea-8287-1e5d8bb1c6e2.png">

* Verified 1 time tip, recurring tip, and AC using anon wallet funded via UGP (virtual) grant:
<img width="774" alt="ugp-6078 and 7526" src="https://user-images.githubusercontent.com/28145373/73573334-1a1ea380-4441-11ea-9b74-b58dc0899faa.png">
<img width="683" alt="Screen Shot 2020-01-31 at 3 48 01 PM" src="https://user-images.githubusercontent.com/28145373/73573335-1c80fd80-4441-11ea-8203-b2e833859104.png">

* Verified 1 time tip, recurring tip, and AC using KYC'd user wallet:
<img width="775" alt="scenario 5 KYCd-6078 and 7526" src="https://user-images.githubusercontent.com/28145373/73577745-bea5e300-444b-11ea-8a87-ce4c0ef1842b.png">
<img width="661" alt="Screen Shot 2020-01-31 at 4 50 54 PM" src="https://user-images.githubusercontent.com/28145373/73577753-c1083d00-444b-11ea-8004-435f73050c49.png">
