### ISSUE TITLE
Extension access in Brave?

### ISSUE THREAD

**Issue by WriterDad** [brave/brave-browser#14301] opened 2021-02-22 20:35 UTC
Is there some way to add extensions to mobile Brave? I don't think I've seen anything about it if that's possible or how to do it, but it would be nice to be able to use the autofill feature of Bitwarden (for an example) on mobile as readily as I can do it on the desktop version of Brave.

**Comment by srirambv** [comment] 2021-02-23 03:41
Extension support is tracked here #4493. Closing as dupe of #4493

**Closed by srirambv** 2021-02-23 03:41 UTC
Labels: OS/Android
