### ISSUE TITLE
Scripts not being blocked in Tor tabs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2006] opened 2018-11-06 04:10 UTC
## Description 
Scripts not being blocked in Tor tabs

## Steps to Reproduce

1. Clean profile 0.56.8
2. Open a Tor window tab
3. Open youtube.com play any video
4. Open shield panel and click on 'Global shield defaults' option
5. Turn on Script blocking option
6. Go back to YT video page, click refresh
7. Open shield and observe that scripts are not blocked
8. Repeat step 3 to 7 in Normal tabs observe that scripts are blocking

## Actual result:
Scripts not being blocked in Tor tabs

## Expected result:
SCripts should be blocked

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by kjozwiak** [comment] 2018-11-06 04:30
@GeetaSarvadnya moving this out of the `0.56.x - Release` milestone as I can reproduce the issue using the following build which was using the old shield design which means this isn't a new Shields regression:

Brave | 0.56.6 Chromium: 70.0.3538.67 (Official Build) beta(64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

@srirambv do you know if we have a similar big somewhere regarding Tor Windows not keeping state?

**Comment by tomlowenthal** [comment] 2018-11-06 19:06
Possible dupe of #1991 — can QA confirm?

**Comment by kjozwiak** [comment] 2018-11-06 23:59
@tomlowenthal once we receive an RC2 which will include the fix for https://github.com/brave/brave-browser/issues/1991, we can give this a double check and see if this is still an issue.

**Comment by GeetaSarvadnya** [comment] 2018-11-08 13:47
@tomlowenthal This issue persists in both RC2 (0.56.9) and RC3 (0.56.10). This is not dup of #1991

**Comment by tomlowenthal** [comment] 2018-11-08 18:22
Got it. I'd guess this is a problem with the settings toggle not getting hooked up to the backend in the guest window somehow.

**Comment by Brave-Matt** [comment] 2019-01-15 02:17
Looks like this is still an issue. +1 from me Using Brave Dev v0.60.13
+1 from Reddit as well:
https://www.reddit.com/r/brave_browser/comments/afuiun/tor_on_brave_should_use_different_different/

**Comment by Brave-Matt** [comment] 2019-02-11 20:39
+1 from Community:
https://www.reddit.com/r/brave_browser/comments/9z2vcn/tor_windows_not_blocking_scripts_when_setting/

**Comment by Brave-Matt** [comment] 2019-02-22 20:16
+1 https://community.brave.com/t/bug-report-for-shield-settings-in-tor-mode/45746/2

**Comment by Brave-Matt** [comment] 2019-03-29 19:34
+1 https://www.reddit.com/r/brave_browser/comments/b6s9bd/script_blocking_while_using_integrated_tor/

**Comment by riastradh-brave** [comment] 2019-07-25 18:20
This will be resolved as part of https://github.com/brave/brave-browser/issues/2307.

**Comment by yrliou** [comment] 2019-10-03 16:46
Fixed by https://github.com/brave/brave-core/pull/3319.

**Closed by yrliou** 2019-10-03 16:46 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/shields/!scripts, feature/tor, feature/tor/guest-semantics, priority/P2

**Comment by btlechowski** [comment] 2019-10-28 12:03
Verification passed on

Brave | 0.72.110 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

Verified test plan from the description
Verified test plan from https://github.com/brave/brave-core/pull/3319
Verified bookmarks and global settings are shared between normal and tor window. Extensions are not shared yet per https://github.com/brave/brave-browser/issues/2307#issuecomment-538018323
Verified that brave://settings page is redirected to normal window.
