### ISSUE TITLE
[Android] Can't swipe between open tabs when bottom toolbar is being used

### ISSUE THREAD

**Issue by Valiceemo** [brave/brave-browser#11083] opened 2020-08-04 16:48 UTC
## Description 
Running beta version 1.11.103
With the bottom toolbar activated via settings > appearance swipe to change tabs does not work
Disabling the bottom toolbar allows for swiping between tabs

## Steps to reproduce 

   1. Enable bottom toolbar
   2. Try to swipe between tabs

## Actual result 
Cannot swipe to change tab

## Expected result
Able to swipe between open tabs as per previous versions and when bottom toolbar is disabled

## Issue reproduces how often
100% of the time bottom toolbar is on 

## Issue happens on
   - Current Play Store version? 
     Yes
   - Beta build?
     Yes

## Device details
   - Device (Phone, Tablet, Phablet):
     OnePlus 7 Pro
   - Android version:
     10
## Brave version
Beta 1.11.103
Stable 1.11.105

**Comment by srirambv** [comment] 2020-08-05 06:06
Closing as dupe of #10668

**Closed by srirambv** 2020-08-05 06:06 UTC
Labels: OS/Android

**Comment by Valiceemo** [comment] 2020-08-05 06:19
Apologies I missing the other open issue.
I did search, just didn't see it
