### ISSUE TITLE
Error only in Brave - other browsers ok

### ISSUE THREAD

**Issue by mulawa1** [brave/brave-browser#40025] opened 2024-07-26 04:24 UTC
### Description

Error only in Brave - other browsers ok

### Steps to reproduce

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

  </body>
</html>

### Actual result

VM71:10 Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule 'html##html[lang][data-dpr="1"][style] > body.bluetheme.false > div#app.wrapper{display:none !important;}'.
    at <anonymous>:10:58
    at Array.forEach (<anonymous>)
    at <anonymous>:5:21
    at <anonymous>:26:11
(anonymous) @ VM71:10
(anonymous) @ VM71:5
(anonymous) @ VM71:26

### Expected result

Blank screen & no error

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

[Version 1.46.153 Chromium: 108.0.5359.128 (Official Build) (x86_64)](https://brave.com/latest/)

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment] 2024-07-27 00:25
Hi @mulawa1 Can you update to the latest version 1.68.128 and see if you're still seeing this issue?
brave.com or https://github.com/brave/brave-browser/releases/tag/v1.68.128

**Comment by mulawa1** [comment] 2024-07-27 01:05
Maybe I had too much shiraz yesterday, but today I can't reproduce the problem!.
For the record: my Brave reports:
"Brave is up to date
[Version 1.46.153 Chromium: 108.0.5359.128 (Official Build) (x86_64)](https://brave.com/latest/)"
and when I tried to download (2 attempts) a later version from brave.com I ended up with a corrupt dmg file. My Mac mini is running macOS 10.13.6 and I don't plan to upgrade it.
Thank you for taking the time to look at this issue but for the moment we can evidently forget about it!

**Comment by rebron** [comment] 2024-07-27 01:56
Thanks. Going to close this issue per your last comment.

**Closed by rebron** 2024-07-27 01:56 UTC
Labels: OS/Desktop, closed/by-author

**Comment by frives-w** [comment] 2024-07-31 10:23
I have same problem.
My Brave version: [Versión 1.68.128 Chromium: 127.0.6533.73 (Build oficial) (64 bits)]

![image](https://github.com/user-attachments/assets/25bf2b64-76eb-49d3-a2ab-6a9b0b8b76e0)

The error is not displayed with Chrome and Firefox. 
Any suggestions?

**Comment by EvgenNoskov** [comment] 2024-07-31 13:19
The same error. Issue is reproduced on websites with react or nextjs, particularly on https://nextjs.org/
[Version 1.68.131 Chromium: 127.0.6533.73 (Build official) (64-bits)]

`Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule 'html[lang] > body#body > head" > div.cvh.BlockClicksActivityBusy{display:none !important;}'.`

Or sometimes it could be another rule:

`Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule 'html[lang] > body#body > head" > div.cv-xwrapper > div.cvc > div.cv-inner{display:none !important;}'.`

**Comment by federicotorrisi** [comment] 2024-07-31 18:17
same here issue here (brave 1.68.134-1 on arch linux).
any site involving vuejs seems to raise an uncaught DOMException.
`VM374:10 Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule 'html[lang] > body#body > head" > div.cv-xwrapper > div.cvc > div.cv-inner{display:none !important;}'.
    at <anonymous>:10:58
    at Array.forEach (<anonymous>)
    at <anonymous>:5:21
    at <anonymous>:26:11`

**Comment by aseroff** [comment] 2024-07-31 19:12
Also on brave 1.68.134 (mac) and also still seeing this malware looking message

**Comment by aseroff** [comment] 2024-07-31 20:04
Nevermind I guess this is not malware

https://github.com/brave/brave-browser/issues/40151

**Comment by antonok-edm** [comment] 2024-07-31 20:08
Looks like a lot of problematic adblock filters have been coming in recently - sorry about all the console issues! For reference, these should all be resolved as of `Brave Ad Block Updater` version `1.0.7178` from `brave://components`, and I'll be working on https://github.com/brave/brave-browser/issues/40177 to ensure that it can't happen again.
