### ISSUE TITLE
Brave News `Customize` dialog is blank 

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#27052] opened 2022-11-29 23:49 UTC
## Description 

Brave News `Customize` dialog is blank

Found while testing https://github.com/brave/brave-core/pull/16086.

## Steps to Reproduce

1. install `1.48.15`
2. launch Brave
3. load `theatlantic.com`
4. click on the brand-new RSS-feed icon in the URL bar
5. click on `Best of The Atlantic`
6. click on `Manage feeds…`
7. click `Turn on Brave News`

## Actual result:

Blank `Customize Brave News` dialog

#### Screencast:
![blank-page](https://user-images.githubusercontent.com/387249/204673431-ef145180-683c-4c00-856c-6b34218e48a2.gif)

## Expected result:

`Customize Brave News` dialog, populated with `theatlantic.com` `Best of the Atlantic` feed shown under `Following`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.48.15 Chromium: 108.0.5359.62 (Official Build) nightly (x86_64)
-- | --
Revision | 041930a89a990cfab0315a2d9f20d6429a4a67cf-refs/branch-heads/5359@{#938}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Unknown`
- Can you reproduce this issue with the nightly channel? `Yes`

/cc @fallaciousreasoning @petemill @mattmcalister @rebron @brave/qa-team

**Comment by fallaciousreasoning** [comment] 2022-11-30 01:38
Okay, I have a simpler repro which doesn't require a new profile:
1. Subscribe to a feed
2. Disable Brave News
3. Refresh
4. Enable Brave News

This was being caused because you can get suggestions before you get publishers (so we'd have publisherId for the suggestion but no info about the publisher.

To fix this, I'm pushing the data into the NTP every time the publisher info is updated, which we possibly should've been doing anyway.

I think this was introduced by https://github.com/brave/brave-core/pull/16038, so the fix needs to be uplifted to 1.47.x

**Comment by stephendonner** [comment] 2023-01-19 21:03
Sadly, this still happens, occasionally, using:



Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

It's really tough to reproduce at will, so maybe a race condition?

blank tab | new tab
----------|--------
<img width="1312" alt="Screen Shot 2023-01-19 at 12 59 38 PM" src="https://user-images.githubusercontent.com/387249/213558860-dd843ba0-6e0a-4ae6-a99b-5eaa0efb20dc.png"> | <img width="1312" alt="Screen Shot 2023-01-19 at 1 00 45 PM" src="https://user-images.githubusercontent.com/387249/213558847-759c066a-c026-491b-b081-86514140c1d1.png">

**Comment by petemill** [comment] 2023-01-19 21:13
@fallaciousreasoning I wonder if that could be caused by this line https://github.com/brave/brave-core/blob/fc5f30881335f21f1aee93c9b14d84f789ecd013/components/brave_new_tab_ui/components/default/braveToday/customize/FeedCard.tsx#L72

I haven't traced calls to that function to see if it's likely Publisher could be null, but I couldn't find many other relevant calls from that error in @stephendonner 's screenshot.

**Comment by fallaciousreasoning** [comment] 2023-01-19 21:17
I think that's probably accurate @petemill - just curious how we're getting into that state. @stephendonner came up with a good repro so I might have a bit more of a dig (and guard that line too, once I've fixed things).

From @stephendonner 

> 1. new profile
> 2. launch Brave
> 3. open a new-tab page
> 4. scroll down on the Brave News opt-in dialog, click Learn More (this replaces the tab’s content)
> 5. now click the Back button on the browser
> 6. click Show Brave News
> 7. click Customize

**Comment by kjozwiak** [comment] 2023-01-19 22:15
Closing as we don't re-open issues that already have an landed PRs. So we'll need a new follow up issue which @stephendonner will create with the new STR/Cases he mentioned above. If this one isn't working, we can label this as `QA/No` and `release-notes/exclude` and QA can run through the above verification on the new issue that will get created and most likely uplifted.

The reason we don't re-open issues that it eventually gets too confusing once you start re-opening/closing an issue that has multiple PRs and uplifts associated with it. For example, in this case, we now have an issue that was supposed to fix an issue within `1.48.x` and was moved into that milestone but now also describes another issue within the `master`.

**Closed by kjozwiak** 2023-01-19 22:15 UTC
Labels: bug, QA/Yes, release-notes/exclude, QA/Test-Plan-Specified, regression, OS/Desktop, feature/brave-news

**Comment by stephendonner** [comment] 2023-01-19 22:29
>
> @stephendonner let us know once you've created the new issue 👍 Can mention it's a follow up to this one.

Done; logged https://github.com/brave/brave-browser/issues/27914 👍
