### ISSUE TITLE
[Desktop] Users should be able to customize keyboard shortcuts

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#354] opened 2018-06-15 08:02 UTC
Carried over from [browser-laptop](https://github.com/brave/browser-laptop/issues/1374)-

Users should be able to change/remap/clear keyboard shortcuts in the browser

As a work-around, we can consider including or linking to an extension such as [Shortkeys](https://chrome.google.com/webstore/detail/shortkeys-custom-keyboard/logpjaacgmcbpdkdchjiaagddngobkck?hl=en) that allows users to do this

**Comment by vinicentus** [comment] 2018-06-15 09:42
+1

**Comment by slavpetroff** [comment] 2018-11-15 10:57
+1

**Comment by Jay1** [comment] 2018-11-18 05:06
Hotkeys to navigate to recent tab is very important in my workflow, I've been using Brave exclusively for about 2 months now it's honestly the only small irritant with Brave browser so far.

**Comment by AndresPrez** [comment] 2019-03-22 14:07
The fact that the Brave Browser gains control over the play/pause button is very annoying.

**Comment by bsclifton** [comment] 2019-03-22 16:32
@AndresPrez there is a separate issue tracking media keys being taken over (which happens because of Chromium). Can you try the work-around suggested here?
https://github.com/brave/brave-browser/issues/3807#issuecomment-475332062

**Comment by AndresPrez** [comment] 2019-03-22 17:18
Awesome!, there's a bunch of configurations here that I didn't know.

I'm sure this simple answer: "brave://flags". Might solve a lot of issues out there.

**Comment by SeevenDev** [comment] 2019-05-07 10:05
@bsclifton Hi! Any plan on implementing this?

The Shortkeys extension doesn't allow to clear default shortcuts (in my case, I'd like to use Ctrl+Shift+Del with Streamkeys, but this shortcut is already taken for clearing browsing data, which is really annoying).

**Comment by orish1** [comment] 2019-08-08 08:59
I've had the same issue with Chrome (and now Brave, thinking at least another developer would have addressed it). 

I'm constantly deleting things by mistake because the default shortcut for adding a bookmark is Ctrl+D. What's worrying is that I sometimes don't even know what I've deleted because another window might be active. So when the bookmark dialog doesn't show up, I press Ctrl+D a few more times.

This is not the only problem I have with common shortcut keys, but this is the most serious one and I've lost valuable work and contacts and emails, etc without realizing until it's way too late. (Yes, I've even backed up data after I've deleted something important and only realized when I tried to *recover* the data from the backup!!!)

It's a habit I can't get rid of because I use the keyboard much more than I use my mouse - my work is very text-intensive. So I need an alternative shortcut for adding bookmarks for my research.

Any ideas in the meantime (shortkeys doesn't support adding bookmarks as a shortcut)?

Thanks

**Comment by pstephenwille** [comment] 2019-08-11 04:04
This is a deal killer for me.  Vivaldi is the only browser that supports customized key bindings.

**Comment by loneconspirator** [comment] 2019-10-22 15:11
I would like to assign keyboard shortcuts to bookmarks without using an untrusted extension

**Comment by tommyjcarpenter** [comment] 2020-01-16 14:39
I agree to this issue. On mac, typing command w is very awkward on my board to close the current tab. cant be done with one hand. would love to change to shift w

**Comment by vindberg** [comment] 2020-01-24 07:41
Please add this to the backlog for the next release! Its important for further adoption of the browser ASAP!!!

**Comment by zwimer** [comment] 2020-02-04 05:33
I agree. I constantly hit ctrl-D to close a window (I am used to doing this for terminals). I would like the ability to change the bookmark key-binding to a different shortcut.

**Comment by vinicentus** [comment] 2020-02-04 06:20
Would it be possible to write this as an open source chromium extension that would then be included by default? That way it might be easier to maintain. I don't know how efficient that would be, just throwing the idea to you :)

**Comment by Exr0n** [comment] 2020-07-08 05:19
Or, is there a plan on implementing this? That might help somebody looking to contribute take a crack at it.. :)

**Comment by gerardb7** [comment] 2020-09-15 09:34
Having a mechanism to modify and clear default shortcuts would prevent a lot of nagging issues such as unwanted zooming when pressing ctrl. Please implement this!

**Comment by auriusbendikas** [comment] 2020-09-21 08:23
This is the only reason now I am not using Brave browser. Not being able to customize shortcuts is a deal braker.

Would also be nice if I could edit short cuts in a file, that would help me to scrip my browser installations with my customisations pre-applied.

**Comment by brandon-toner** [comment] 2020-11-05 21:18
+1 — I'm getting interference with keystroked I use with other apps. 

Will be changing browsers because of this. May return if fixed.

**Comment by developersam1995** [comment] 2020-11-11 11:42
+1, Yes please add the ability to customize shortcuts.

**Comment by shenlin-tomtom** [comment] 2020-11-14 16:01
+ Please add the customize shortcuts.

**Comment by impshum** [comment] 2020-12-10 19:11
+1

I'd like to map alternative shortcut keys easily too.

**Comment by Gutie** [comment] 2020-12-16 16:16
+1

Must-have for great ux.

**Comment by trevorackerman** [comment] 2021-01-04 15:05
+1

**Comment by Jaco7Fourie** [comment] 2021-01-06 20:45
+1

**Comment by Alandil35** [comment] 2021-01-12 08:33
Yeah ! It will be great ! Shortcut keys for Brave and extensions !

**Comment by frandoodle** [comment] 2021-01-20 18:16
+1 Google docs shortcut for adding a comment is Ctrl + Shift + M which is overridden by Brave's account/wallet feature's (?) hotkey.

**Comment by edmundlaugasson** [comment] 2021-03-23 08:12
+1  also in [Notion](https://www.notion.so/) these are interfering with Brave shortcut keys, e.g. CTRL+SHIFT+9 will move tab to left but should create a page in [Notion](https://www.notion.so/). Even [Shortkeys](https://chrome.google.com/webstore/detail/shortkeys-custom-keyboard/logpjaacgmcbpdkdchjiaagddngobkck?hl=en) didn't help me to remove it :(

**Comment by sokkit** [comment] 2021-05-24 20:54
+1 also running in to issues with Brave and [Notion](www.notion.so). Would be really nice to be able to remove/change keyboard shortcuts.

**Comment by NotRexButCaesar** [comment] 2021-06-27 21:39
The alt-shortcuts can also interfere when entering Unicode characters.

**Comment by ECon87** [comment] 2021-07-01 14:01
Is this happening? It would be great if we could customize shortcut keys

**Comment by Ultrahalf** [comment] 2021-07-15 16:41
It would be cool if you could control multi media with keyboard. Idk what this thing is called 
![image](https://user-images.githubusercontent.com/41832211/125825433-af61ff38-6000-40ff-ba3c-42421e1b67b9.png)

**Comment by TheYellowArchitect** [comment] 2021-09-08 22:35
While many uses are posted above, it would help Vim users as well (vim-like bindings, j-k down-up)

Optimally, a configuration text file would be appreciated, so the configuration can be moved to other computers, but honestly as long keyboard shortcut functionality is added, I wouldn't have anything else to really ask.

**Comment by yamabiiko** [comment] 2022-02-20 23:43
+1 This feature would be a deal breaker, please give us an update

**Comment by SINE** [comment] 2022-04-26 15:43
This is a vital functionality missing.
The browser is using the same hotkeys for closing the browser as other programs use for unfocusing.
When using with Parsec, this force closes the browser which is frustrating and a loss of time and productivity.
PLEASE add customizable hotkeys or the ability to disable them at least.

**Comment by StijnHoeke-MH** [comment] 2022-05-24 07:10
+1

**Comment by LeuschkeTressa** [comment] 2022-07-23 19:59
Seems Brave doesn't respect macOS system shortcuts, at least not when they override a Brave shortcut. The custom keyboard shortcut is indicated in the corresponding Brave menu item, but has no effect.

At least a fix for that would be great.

**Comment by Noobvelopper** [comment] 2022-11-10 13:53
+1, I would love to be able to freely remap the shortcuts.

**Comment by romanr** [comment] 2022-11-25 11:11
It's like the worst possible implementation of keyboard shortcuts - not customisable and can not be overriden even by OS.

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment] 2023-03-28 22:29
@fallaciousreasoning 
Your work is amazing, the only problem I have noticed is with Back and Forward navigation. They are set to `left` and `right` keys by default, which can cause issues while editing text and all that, but the problem is how they can't be **completely** removed, because when you remove them, they come back on restart, and if you hit reset button, then they glitch and Brave doesn't even allow to be removed them anymore, because they come back immediately.
But it is working good besides that.

**Comment by fallaciousreasoning** [comment] 2023-03-28 23:02
Oooh interesting, that sounds like a few bugs :laughing:. Could you provide a few details (this isn't working at all on macOS yet).
What platform are you on? OSX, Linux, or Windows?
What version of Brave are you using? (if you go to brave://version it should tell you).

Glad to hear you're already using it! It should help us iron out a bunch of the bugs and get things ready for launch.

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment] 2023-03-29 00:30
@fallaciousreasoning

Thanks! yeah I have been using since the 4 minutes after the build (Windows) was available to download (I usually manually install builds minutes after they are available, so I usually have the latest).

I was just waiting for the `Shortcuts Generation Followup (17632)` that was released today to report this, I didn't know if this problem would get fixed by that.
Only 3 commands are affected by this anyway, `Back` and `Forward` and `Focus Menu Bar` commands, so should be easy to test when the fix is available, and it was only annoying when editing URLs on the omnibox mostly if I forgot to remove them on every start.

Another thing I see is duplicates of shortcuts, which is like whatever, because removing both shortcuts works fine, plus it is only some commands which I don't really edit:  `Select Tab [0 to 7]`, `Select Last Tab`, `Zoom Normal`, `Zoom Minus`, `Focus Menu Bar` (as well).

But everything I have tested works okay with the commands that are meant to work in Brave, should be amazing when the design for the Shortcuts UI (looks really good!) gets implemented as well!

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment] 2023-03-29 01:22
@fallaciousreasoning whatever build has nice commits I set a timer because I already know when it will be available for Windows. But I have had the flag enabled when it was only viewing the commands was released.
Nice news for the UI part, and I will be probably the first user to use it for sure!

Oh yes, I thought I said 'probably visual' in my comment, but then, I also forgot Preferences file exists and I could just have checked it to see exactly what you say 🤦‍♂️
```
            "34019": [
                "Control+Digit2",
                "Control+Numpad2"
```

Seems like 39003 = Focus Menu Bar, is crazy in the Accelerators in preferences file with 53 "AltLeft" 
![image](https://user-images.githubusercontent.com/122518587/228401190-7e85982b-ecc0-4d01-a2a3-0562083891d3.png)

So I guess it was getting crazy there! but I am glad it was or seems like it was a quick fix.

So, I will wait for the fix to drop, and if anything ever new happens, I will probably report and you will hear from me, because sometimes I feel I am the only one testing these features. 👍

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment] 2023-03-29 16:54
@fallaciousreasoning
Back and Forward navigation working great now, thanks for the quick fix! 🎉

`Focus Menu Bar`, is the only one that I still see with issues, not as important because not many would change that shortcut but here is:

![brave_2023-03-29_10-32-09](https://user-images.githubusercontent.com/122518587/228606974-611eb5cd-2b1a-4696-a8d3-48cef347bf57.gif)

Another thing I noticed about it is that the Preferences file shows it like this: `"39003":["F10","Alt","Alt","AltGr"]`, but if you remove the last `Alt` on UI = AltGr, the AltGr still works to focus in the menu bar, if you delete the first Alt, then that stops both Alt and AltGr from focusing in the menu bar, so it seems it is not getting the same treatment as the Back and Forward navigation, which they now even display like `AltGr` + `ArrowLeft` `-` in the UI to indicate the difference.

**Comment by fallaciousreasoning** [comment] 2023-03-29 21:04
Yeah, there's definitely a bit of funkiness :laughing: The `Focus Menu Bar` one is interesting because the shortcut is `Alt` with no other keys, and it actually doesn't work properly, at all (not in the Brave versions without the commands feature, not with the flag off, not in Chromium) which seems odd (especially because `F10` works).

I think the duplicates probably occur because Chromium adds a shortcut for `VKEY_MENU`, `VKEY_LMENU` and `VKEY_RMENU`  which (I think?) are all `Alt`/`AltGr`. I might have a bit of a dig into it.

The recorder definitely has a few problems too - one I've been noticing is that `Meta` doesn't show up until you press another key (but that might be a Linux thing). It's weird, but some input events don't fire (but then, when you press another key it knows what modifiers are down). I've been playing around with [this thing](https://css-tricks.com/snippets/javascript/javascript-keycodes/) to see if I can make sense of what's going on.

Thanks heaps for all the testing and feedback!

**Comment by rebron** [comment] 2023-07-12 00:34
Closing out in favor of https://github.com/brave/brave-browser/issues/30840. Please add new comments there or file new issues not covered in 30840.

A few notes:
We're targeting to release this feature within the 1.56.x time frame, still need to turn the flag on by default. 
We do have shortcuts on by default in Beta 1.57.x and Nightly 1.58.x.

**Closed by rebron** 2023-07-12 00:34 UTC
Labels: feature/keyboard-shortcuts, priority/P3, QA/Yes, release-notes/include, OS/Desktop
