### ISSUE TITLE
Login with Google OAuth not working

### ISSUE THREAD

**Issue by iamankitpawar** [brave/brave-browser#6408] opened 2019-10-10 15:12 UTC
## Description 
Whenever I try to use Oauth to login on any website, Brave simply opens up a new window and automatically closes after a few seconds and does not log me in.

## Steps to Reproduce

   1. Go to any website ( For example: https://www.geeksforgeeks.org/)
   2. Click on Login button.
   3. Try logging in using Google OAuth button.

## Actual result:

![image](https://user-images.githubusercontent.com/28015876/66581668-220abd00-eb9e-11e9-9668-ee91be577f53.png)

The above window appears and vanishes after few seconds but does not log me in.
## Expected result:
It should log me in using my Google account.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave	0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
Revision	58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS	Windows 10 OS Version 1803 (Build 17134.885)
JavaScript	V8 7.7.299.11
Flash	(Disabled)
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Command Line	"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-features=NewExtensionUpdaterService,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=UnifiedConsent,AudioServiceOutOfProcess,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI --flag-switches-begin --flag-switches-end
Executable Path	C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\Ankit\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default

## Version/Channel Information:

It is happening on the current stable version.
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Did not try
- Can you reproduce this issue with the dev channel? Did not try
- Can you reproduce this issue with the nightly channel? Did not try

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment] 2019-10-10 17:55
Does allow third party cookie fix this?

**Comment by rebron** [comment] 2019-10-10 20:16
@srirambv All cookies allowed in Shields Settings as a workaround does work.

@iamankitpawar Can you go into Shields and turn on All cookies allowed to see if that works for you.
<img width="369" alt="Screen Shot 2019-10-10 at 1 15 09 PM" src="https://user-images.githubusercontent.com/5951041/66602989-139db080-eb60-11e9-9d49-3ebefdbe0bc9.png">

**Comment by rebron** [comment] 2019-10-18 16:50
cc: @bridiver Related to the cookie fix with Google auth?

**Comment by bridiver** [comment] 2019-10-18 17:45
the old google auth hack was removed because it was much more complicated to integrate into the network service and we couldn't reproduce the problem on any of the sites from the original ticket. Everyone at Brave uses google auth on a regular basis and I can't repro on that site. @iamankitpawar do you have any extensions installed?

**Comment by aborigines** [comment] 2019-11-03 09:37
i got this problem too. im disable 2fa and enable back. it works.
so  2fa have new feature to use security keys like a mobile, usb or usb to auth, does not works with brave browser.

**Comment by ankush1593** [comment] 2019-11-23 10:06
> the old google auth hack was removed because it was much more complicated to integrate into the network service and we couldn't reproduce the problem on any of the sites from the original ticket. Everyone at Brave uses google auth on a regular basis and I can't repro on that site. @iamankitpawar do you have any extensions installed?

Same issue is easily reproducible for me as well and the workaround provided @rebron works pretty well. But can't we get to a permanent solution?

**Comment by bsclifton** [comment] 2019-11-25 06:29
I believe this was fixed with https://github.com/brave/brave-core/pull/3784, which is currently in our Nightly build (w/ OAuth enabled by default)

@iamankitpawar @ankush1593 @aborigines are you able to try on Nightly?

I'll close this as a dupe of https://github.com/brave/brave-browser/issues/5869... but let's re-open if the fix on Nightly (1.3) doesn't work.  1.3 is slated to hit release channel ~Feb 4

**Closed by bsclifton** 2019-11-25 06:29 UTC
Labels: webcompat, workaround/allow-all-cookies
