### ISSUE TITLE
Out of memory for Spotify and Instagram reels

### ISSUE THREAD

**Issue by kenewjr** [brave/brave-browser#36356] opened 2024-02-24 12:17 UTC
## Description 

everytime i open instagram reels it makes tab instagram freeze but when i turn off widevine it's working normally
and spotfy randomly crash with error : out of memory

## Steps to Reproduce

  -instagram-
   1. open instagram
   2. go to reels instagram 
   3. freeze without showing any video but some time showing only 3-5 video
-spotify-
   1. open spotify
   2. play from playlist
   3. spotfy randomly crash with error out of memory
## Expected result:
1.instagram showing videos reels everytime i scroll
2.spotfy continue play the song until playlist end

## Brave version (brave://version info)
1.63.162 Chromium: 122.0.6261.69 (Official Build) (64-bit) 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? yes

## Miscellaneous Information:
instagram reels worked when i turn off widevine

**Comment by Brave-Matt** [comment] 2024-03-07 18:02
Lots of users reporting this issue (Spotify) in this thread: 
https://community.brave.com/t/spotify-keeps-crashing-in-brave/532078/23

**Comment by wooque** [comment] 2024-03-21 18:12
I can confirm Spotify is leaking memory and crashes after some time on latest v1.64.109

**Comment by wooque** [comment] 2024-03-25 18:52
Latest Chrome 123.0.6312.58 doesn't have this issue. It's a shame that I have to use Chrome to play Spotify.

**Comment by ryanbr** [comment] 2024-03-27 23:22
https://www.reddit.com/r/truespotify/comments/1ay9n3d/spotify_crashes_and_gives_me_out_of_memory_error/

Looks like its in Chromium issue

**Comment by wooque** [comment] 2024-03-29 16:39
I noticed that high memory usage is not reported by task manager. For example hover over tab will show 3.7GB memory usage, while task manager shows 250MB.

**Comment by atuchin-m** [comment] 2024-05-09 16:49
an upstream bug: https://issues.chromium.org/issues/329580320

**Comment by atuchin-m** [comment] 2024-06-18 20:24
The upstream bug is fixed and Chromium claims it helps to resolve most of the issues for them.
However, it cant still reproduce the issue on a recent nightly (cr126) with chromium fix.

I've managed to grab and symbolize a memory-infra heap dump, but the data is controversial  (Release optimizations?):
![image](https://github.com/brave/brave-browser/assets/45488748/324f4c40-1da7-4021-80d9-7671d8f11300)

**Comment by atuchin-m** [comment] 2024-06-18 20:52
I've managed to get the correct stack. It matches the crash dumps and the details in the chromium issues.
![image](https://github.com/brave/brave-browser/assets/45488748/aa28c874-690c-46ed-a061-33feb83b59b1)

**Comment by atuchin-m** [comment] 2024-07-01 13:40
I've pushed CL to upstream that should improve the situation:
https://chromium-review.googlesource.com/c/chromium/src/+/5670619/1

However, despite Chrome also has this issue, it is more severe in Brave Browser.
The reason is an avalanche of requestIdleCallback originated from [ReChapta](https://www.gstatic.com/recaptcha/releases/KXX4ARWFlYTftefkdODAYWZh/recaptcha__en.js) javascript (from spotify.com)
Each round (typically 100ms) the page got N callback fires and schedules N+1 new requestIdleCallback with timeout (usually 3000ms).I haven't managed to catch the same for Chrome.
 
<img width="1393" alt="Screenshot 2024-06-24 at 10 38 35 PM" src="https://github.com/brave/brave-browser/assets/45488748/ea45b7b7-0c18-41b5-bbda-f969938a65ae">

![image](https://github.com/brave/brave-browser/assets/45488748/3212a24d-db97-4537-95a5-45b9694769ab)

**Comment by kjozwiak** [comment] 2024-08-06 14:53
Closing the above as it's being resolved by https://github.com/brave/brave-core/pull/24712.

**Comment by rebron** [comment] 2024-08-20 18:15
Closing out since we landed this in 1.69.x already. @ShivanKaul Can you create a new issue for this as it's a problem still on Nightly channel.

**Closed by rebron** 2024-08-20 18:15 UTC
Labels: crash, priority/P2, QA/No, perf, release-notes/include, OS/Desktop

**Comment by ryanbr** [comment] 2024-08-21 02:06
Asking for confirmation in https://community.brave.com/t/spotify-keeps-crashing-in-brave/532078/105
