### ISSUE TITLE
few non-english webpage are not translated to English - follow up of #208

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4532] opened 2019-05-22 06:05 UTC
## Description 

few non-english webpage are not translated to English

## Steps to Reproduce

   1. Open non-English webpage
   2. Right-click and select `Translate to English`
   3. Popup says `Translated` but webpage remained as it is (not translated to English)

## Actual result:

https://drive.google.com/open?id=1vJZxASdz3AVw-60VME4gbMA_685Kg8SD
The webpage is NOT translated to English
![image](https://user-images.githubusercontent.com/38657976/58154224-bd9e9e00-7c8e-11e9-8ccb-f60f86422fae.png)

## Expected result:
The webpage should translate to English

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.65.107 Chromium: 75.0.3770.38 (Official Build) beta (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@yrliou

**Comment by srirambv** [comment] 2019-05-22 13:15
Dupe of #4150

**Closed by srirambv** 2019-05-22 13:15 UTC
Labels: QA/Yes, bug, feature/translate
