### ISSUE TITLE
After update, the window's titles in dark theme become black and invisible

### ISSUE THREAD

**Issue by amzero** [brave/brave-browser#22132] opened 2022-04-06 18:18 UTC
I can't find an issue opened reported like this.

the image like example:

![github](https://user-images.githubusercontent.com/6620339/162041533-61cd4d33-5fbe-4797-a73c-e9ab6d205eb0.png)

Windows 8.1 
Brave Browser 1.37.111

**Comment by rebron** [comment] 2022-04-06 19:11
Duplicate of https://github.com/brave/brave-browser/issues/22027?

**Closed** 2022-04-06 19:41 UTC
Labels: OS/Desktop
