### ISSUE TITLE
Remove "Brave" in "Show Brave suggested sites in autocomplete suggestions" description

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#16797] opened 2021-07-06 23:06 UTC
## Description 

Remove "Brave" in "Show Brave suggested sites in autocomplete suggestions" description

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `brave://settings/appearance`
   4. look at `Show Brave suggested sites in autocomplete suggestions`

## Actual result:

Says `Show Brave suggested sites in autocomplete suggestions`

<img width="699" alt="Screen Shot 2021-07-06 at 4 01 52 PM" src="https://user-images.githubusercontent.com/387249/124676722-eafd3480-de73-11eb-9996-a706b44c24fa.png">

## Expected result:

Should just be `Show suggested sites in autocomplete suggestions`, per discussion with @rmcfadden3 @karenkliu, as they're not actually *our* suggestions

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.28.54 Chromium: 92.0.4515.81 (Official Build) nightly (x86_64)
-- | --
Revision | dba3af0a9a48954c8b188bc641e651580b7cb7b5-refs/branch-heads/4515@{#1162}
OS | macOS Version 11.4 (Build 20F71)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

**Comment by srirambv** [comment] 2021-07-07 04:19
This was done for the Brave referral links suggestions. Not sure if we need to have the setting itself anymore. 

cc: @bbondy

**Comment by bbondy** [comment] 2021-07-07 14:15
Brendan had mentioned some people liked to have it to support Brave and to leave it for now, so we'll just leave it for now. We can definitely do the text change though.

**Comment by Tonev** [comment] 2022-03-29 05:40
@stephendonner @bbondy 

If you have decided this needs a change, I can do the change over here:
https://github.com/brave/brave-core/blob/73096ec8b947b31cac0bc8499bc4b39c1847fa6b/app/brave_generated_resources.grd#L349

I believe that's all that has to be changed.

**Comment by stephendonner** [comment] 2022-03-29 05:43
> @stephendonner @bbondy
> 
> If you have decided this needs a change, I can do the change over here: https://github.com/brave/brave-core/blob/73096ec8b947b31cac0bc8499bc4b39c1847fa6b/app/brave_generated_resources.grd#L349
> 
> I believe that's all that has to be changed.

Sure, I don't see any change in direction, so removing `Brave` from that text seems good to me 👍   Put it up for review and tag the usual suspects.

**Comment by Tonev** [comment] 2022-03-29 05:59
@stephendonner 

Feel free to assign the issue to me, I have an open pull request that should fix it :+1:

**Comment by Tonev** [comment] 2022-04-01 16:38
@stephendonner, could you please use your rights to request a review for the PR? It's a one-word-change, but unfortunately it's taking a few days for a review :thinking:

**Comment by bsclifton** [comment] 2022-04-01 22:54
@Tonev just assigned @mkarolin for review; some of the localizations can be tricky, because they get auto-generated. I suspect it may need to be changed another place. For example, we'll auto-replace a set of words on Chromium upgrade and do a replace of `Google` with `Brave`

**Comment by bbondy** [comment] 2022-04-02 11:59
Sorry for any lost time but let's close this. The feature is related to Brave's list, which is not really maintained anymore. But it is Brave specific.

**Comment by bbondy** [comment] 2022-04-02 13:56
Actually I see the PR is already there and approved and correct, so I'll take that back and re-open.

**Closed** 2022-04-02 15:29 UTC
Labels: needs-text-change, priority/P4, feature/settings, OS/Desktop, 1_point

**Comment by stephendonner** [comment] 2022-04-07 17:59
Verified `PASSED` using 

Brave | 1.39.39 Chromium: 100.0.4896.79 (Official Build) nightly (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 11.6.5 (Build 20G527)

Confirmed `Brave` has been removed, and the text now reads `Show suggested sites in autocomplete suggestions`.

<img width="1485" alt="Screen Shot 2022-04-07 at 10 57 44 AM" src="https://user-images.githubusercontent.com/387249/162267071-d7cd01bd-7d2c-44ed-b118-ae3924c16139.png">

**Comment by MadhaviSeelam** [comment] 2022-04-29 00:55
Brave | 1.39.83 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 11 Version 21H2 (Build 22000.613)

Confirmed `Brave` has been removed, and the text now reads `Show suggested sites in autocomplete suggestions`.

![show suggested](https://user-images.githubusercontent.com/98358127/165870087-592121fc-fce7-45fe-90b0-187ee7e4a72f.png)
