### ISSUE TITLE
64 bit version of Brave for Android

### ISSUE THREAD

**Issue by chris122380** [brave/brave-browser#13744] opened 2021-01-25 06:19 UTC
## Description 
All the current versions of Brave for Android are built using the 32 bit version of chromium. Would like to see 64 bit versions on those platforms that would support it 

## Steps to reproduce

   1.  chrome://version/
   2. (Official Build) (32-bit)
   

## Actual result 
(Official Build) (32-bit)

## Expected result
(Official Build) (64-bit)

## Issue reproduces how often 
Every Android build

## Version/Channel Information:
Stable, Beta, and Nightly

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Android 10; moto g(7) power Build/QCOS30.85-18-6
   
## Brave version
1.19.86
1.21.21 (Nightly)

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? Chrome and Chromium do have 64 bit builds.

**Comment by srirambv** [comment] 2021-01-25 09:36
Closing as dupe of #7491

**Closed by srirambv** 2021-01-25 09:36 UTC
Labels: OS/Android
