### ISSUE TITLE
[Desktop] Can't paste hex value into colour input

### ISSUE THREAD

**Issue by ChildishGiant** [brave/brave-browser#10806] opened 2020-07-19 02:57 UTC
## Description 

It seems like the colour picker/input has been given a face lift and it's lovely! An issue I have is that you can't paste a hex value in, it pastes as if you were pasting a blank thing.

## Steps to Reproduce

1. Open a colour picker (I used this: https://www.w3schools.com/TAGS/tryit.asp?filename=tryhtml5_input_type_color)
2. Click on the bottom to change the format to hex
3. Copy a valid hex value and try to paste it in

## Actual result:

![](https://thumbs.gfycat.com/EsteemedPalatableFoxhound-size_restricted.gif)

## Expected result:
value pasted in (if a valid hex value)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave	1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)
Revision	19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS	Windows 10 OS Version 1909 (Build 18363.959)
JavaScript	V8 8.4.371.19
Flash	(Disabled)
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Command Line	"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,PassiveMixedContentWarning,AutoupgradeMixedContent,WebUIDarkMode,MixedContentSiteSetting,DnsOverHttps --disable-features=VideoPlaybackQuality,UseButtonTranslateBubbleUI,AutofillServerCommunication,TextFragmentAnchor,TabHoverCards,SmsReceiver,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,NotificationTriggers,LookalikeUrlNavigationSuggestionsUI --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-sync
Executable Path	C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\allie\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations	5e3a236d-4113a79e

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not attempted
- Can you reproduce this issue with the dev channel? Not attempted
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by bsclifton** [comment] 2020-07-20 05:56
Was able to reproduce this on Windows 10 x64 with Edge and Chrome. I'll see if I can find a issue# upstream

**Comment by bsclifton** [comment] 2020-07-20 06:01
Found issue upstream - seems there are some other regressions too (no eyedropper, etc). Can be tracked with https://bugs.chromium.org/p/chromium/issues/detail?id=1085414

**Comment by bsclifton** [comment] 2021-01-26 21:50
Eyedropper is back! Above issue was merged into https://bugs.chromium.org/p/chromium/issues/detail?id=992297 and that issue has since been fixed 😄 

Closing

**Closed by bsclifton** 2021-01-26 21:50 UTC
Labels: Chromium/waiting upstream, OS/Desktop, priority/P5, repros-on-chrome

**Comment by EricBCoding** [comment] 2024-08-31 17:46
This is still an issue in 2024, @bsclifton . Here is a video demonstration:

https://github.com/user-attachments/assets/cbd27e85-d408-4333-89d2-efb2affa2c72

Actually, it's broken in both directions - I can't copy values out of the Color Picker, either.

These are the relevant issues upstream:

- https://issues.chromium.org/issues/40124558
- https://issues.chromium.org/issues/40286362

Would Brave consider implementing its own Color Picker? Aside from the bugs, the Chromium tooling has a lot of room for improvement. For example, it is not possible to default to HEX format.

**Comment by OrsonFun** [comment] 2024-09-29 23:04
got the same issue here

**Comment by bsclifton** [comment] 2024-09-30 05:38
Thanks for sharing the issue numbers upstream @EricBCoding - I'll subscribe to those and others are welcome to subscribe too.

If we want to track that in our repo, we could create a new issue and link to those. But I think just subscribing to the Chromium ones are sufficient
