### ISSUE TITLE
Google Docs sync problems with same doc in multiple tabs

### ISSUE THREAD

**Issue by stshank** [brave/brave-browser#3745] opened 2019-03-15 19:00 UTC
## Description 
I often have the same Google Docs document open in two tabs (a poor man's split screen so I can refer to different sections of the same doc). Sometimes the two tabs are open in Brave; sometimes one in Brave and the other in another browser. Often I notice that the Brave version doesn't reflect changes made in a different tab.

For me, it doesn't *always* happen. Lowering shields during one instance of the problem fixed it, and the problem didn't recur when I raised shields again during that test. But I've run into this issue multiple times in recent months. It's a problem since (obviously) I don't want docs to be out of sync. I don't have this problem with other browsers I use (Chrome, Safari, Firefox).

## Steps to Reproduce

   1. Open same Google Doc in two tabs
   2. Edit one
   3. Switch to other tab and see that those edits haven't been made

## Actual result:
Changes in one document not always reflected in other

## Expected result:
Docs stay in sync

## Reproduces how often: 
intermittent

## Brave version (brave://version info)

Brave | 0.63.9 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X
JavaScript | V8 7.3.492.22
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
Command Line | /Applications/Brave-Browser-Dev.app/Contents/MacOS/Brave Browser Dev --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=NewExtensionUpdaterService,DesktopPWAWindowing,fill-on-account-select --disable-features=AutofillSaveCardSignInAfterLocalSave,AutofillServerCommunication,AudioServiceOutOfProcess,DefaultEnableOopRasterization,SharedArrayBuffer,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave-Browser-Dev.app/Contents/MacOS/Brave Browser Dev
Profile Path | /Users/sts/Library/Application Support/BraveSoftware/Brave-Browser-Dev/Default
Variations | c134752e-f685ead32c707b42-dcf7018a411b6d4e-3f4a17dfd01ab0d3-5ac8943b0271b40-360900151a0d11d4-2f9febdf6f93b899-10d7b58b66df3e9d-a85d0b2f4b8c3f4-3f4a17dfb7e2524c-c92d551c411c711e-3f4a17dfb3888d8d-afba0f916c18ba9d-3f4a17df8982496f-3f4a17df61832c80-3f4a17dfcc20827f-77c422c591560a-29acad4241fff6c-ddf208789853922b-3f4a17df9def365c-3f4a17df2342e907-3f4a17df9ca1387e-3f4a17df1c752ce9-1c752ce9776de70c-e0278d3ded9149a9-3f4a17df34d450b1-3f4a17df31362330-3f4a17dfc70841c8-a256700714bdbe54-e8c7a65bd8343fa3-3f4a17dfb517d646-3f4a17df8ee5ed19-c3125ea274658432-fa79b94caacdc39d-80f9a33ec36cdb78-3f4a17df9e201a2b-3f4a17df5274eb09-3f4a17df36115667-3f4a17dfceff87ec-3f4a17df44827ee5-3f4a17df332a4d9b-8e8e4a2b6a116980-3f4a17df3f79ac13-3d47f4f48f1e27f-3f4a17df345b5b61-3f4a17df77bbdddc-3f4a17df5485fc4d-3f4a17df9b4c4257-3f4a17df43f62d3b-3f4a17df4ae380f4-3f4a17df165e16d1-3f4a17df9e5c75f1-30e1b12b2594bdf4-3f4a17df6fa07eb4-7282ca762981bcb4-3f4a17df5139837c-3f4a17df4934552d-3f4a17df7f8176d9-3f4a17df73a8d7f1-1b1a79086c66bd8d-b204717823a898eb-fc93cf742b08b14-3f4a17df7a5ba892-3f4a17dfd1cd70a5-80f9a33e4ea303a6-3f4a17dfac8d4708-e340be04b19465ab-b19465ab6e6e0c7e-3f17a7d895876445-2b71ffe42b33233e-881ca6c9b363a81f-3f4a17df4da5ae82-3f4a17df56302f8c-2f882e70dc5b1f29-dc5b1f29bbc5c1b-3f4a17dffd56acdf-3f4a17dfcc54eb06-803f8fc4b2612322-8a9180b2ad6d27cc-3e870323cec9a952-9a6c5085f56e0452-3f4a17df8576baf1-3f4a17df3038aa2e-3f4a17dfd00fcbde-3f4a17df9a2f4e5b-4bc735ae1354da85-522c33b8494d8760-3f4a17dff9e5da91-508355f5fcdd9ed9-fcdd9ed9b0ea13bc-3f4a17dfc453dbf7-947ab53694e68624-803f8fc4cc73f8a1-3f4a17dfb4e8892d-a2d707c610a311eb-10a311eb8834fcca-3f4a17df6204e469-3f4a17df

### Reproducible on current release:
I'm on latest Dev

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
Sort of; see above
- Is the issue reproducible on the latest version of Chrome? 
I haven't seen it

**Comment by rebron** [comment] 2019-03-25 16:41
@stshank I'm trying to reproduce and I'll run through the different channels but currently can't reproduce in Google Docs via release or nightly channels. I'm switching between tabs and also having windows open side by side with the same doc and it looks like the edits are happening in real time.

**Comment by rebron** [comment] 2020-03-24 05:13
@stshank I'm going to close this one out. I tried again in both Google Docs and Sheets and edits seem to be reflected. Let me know if this still an issue for you though. Tested in both 1.5.115 and 1.8.32

**Closed by rebron** 2020-03-24 05:13 UTC
Labels: needs-investigation, priority/P4
