### ISSUE TITLE
Every page is missing elements and Brave community is down.

### ISSUE THREAD

**Issue by arch-btw** [brave/brave-browser#35160] opened 2024-01-06 00:29 UTC
Every page is missing elements (css, javascript) and Brave community is down.

Disabling built in adblocker seems to fix the issue.

**Comment by arch-btw** [comment] 2024-01-06 00:30
https://reddit.com/r/brave_browser/comments/18zm4y0/anyone_else_having_issues_with_their_brave_ad/

**Comment by dukio** [comment] 2024-01-06 00:36
If more info are required:
- Windows 11
- Version 1.61.114 Chromium: 120.0.6099.199 (Official Build) (64-bit)

Brave Shield on "Block tracker and ads" is blocking most website resources, even css or fonts

**Comment by panzer-chan** [comment] 2024-01-06 00:39
All sites are unusable, even GitHub. Need to turn shields down to fix the issue, adjusting any settings in Brave shield besides "Allow all tracker and ads" will not address this issue.
Ublock Origin works fine on all sites though.

Using Windows 10:	10.0.19045 Build 19045
Brave version: Version 1.61.114 Chromium: 120.0.6099.199 (Official Build) (64-bit)

**Comment by nunees** [comment] 2024-01-06 00:41
The EasyList Cookie seems to be the problem, just disable it in Content Filters settings.

**Comment by panzer-chan** [comment] 2024-01-06 00:43
> The EasyList Cookie seems to be the problem, just disable it in Content Filters settings.

Yep, it worked.
Do you know what's the issue with that and when it would be fixed?

**Comment by binex-dsk** [comment] 2024-01-06 00:54
> The EasyList Cookie seems to be the problem, just disable it in Content Filters settings.

Does the Android app have this setting?

**Comment by nunees** [comment] 2024-01-06 00:58
> > The EasyList Cookie seems to be the problem, just disable it in Content Filters settings.
> 
> Does the Android app have this setting?

Go to Settings -> Brave Shields & Privacy -> Content Filters

Disable the EasyList Cookie

But, I Don't know if it works on android

**Comment by igorskyflyer** [comment] 2024-01-06 01:09
> Nope, no Content Filtering settings in sight...

Maybe you're using an old version? I'm currently running the latest version `v1.61.109` and I can confirm the setting is there (`Settings` -> `Brave shields and privacy` -> `Content filtering`).

**Comment by binex-dsk** [comment] 2024-01-06 01:15
> > Nope, no Content Filtering settings in sight...
> 
> Maybe you're using an old version? I'm currently running the latest version `v1.61.109` and I can confirm the setting is there (`Settings` -> `Brave shields and privacy` -> `Content filtering`

Yeah it was out of date, I messed up my auto updating.

**Comment by brycewray** [comment] 2024-01-06 01:19
A Brave staffer said they borked the “EasyList Cookie” item but have now fixed it, although it requires users to update: https://www.reddit.com/r/brave_browser/comments/18zm4y0/comment/kginn5e/?context=3

**Comment by ryanbr** [comment] 2024-01-06 03:06
Should be resolved. It'll automatically fix itself. If not, can force an update in brave://components in Easylist Cookie.

**Closed by ryanbr** 2024-01-06 03:06 UTC
Labels: OS/Android, OS/Desktop
