### ISSUE TITLE
BAT grant CAPTCHA distortion

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#1031] opened 2018-09-07 22:43 UTC
All janked up on my Mac. I also got an image drag-and-drop behavior when trying to drag the BAT logo — I was dragging a square white box around the logo, and there was a green circle with a plus button inside it on the corner of the tile. But it looks like the grant actually worked nonetheless.

<img width="421" alt="screen shot 2018-09-07 at 3 36 44 pm" src="https://user-images.githubusercontent.com/639937/45246129-7d3ff100-b2b4-11e8-98ed-3f3ecd7d2ee1.png">

**Comment by jasonrsadler** [comment] 2018-09-09 19:47
Dupe of #928

**Closed by jasonrsadler** 2018-09-09 19:47 UTC
Labels: feature/rewards
