### ISSUE TITLE
Setup Crypto Wallets sometimes doesn't appear on first page load

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8120] opened 2020-02-07 08:41 UTC
## Description 

Web3 provider selection isn't triggered on first launch

## Steps to Reproduce

   1. Clean install 1.6.7
   2. Open new tab and visit cryptokittes.co
   3. No notification bar shown for setup 
   4. Reload the page notification bar shows up to setup Web3 provider(CW)

## Actual result:

![web3setup](https://user-images.githubusercontent.com/17010094/74013943-979f6200-49b3-11ea-9d64-2776e8068a9c.gif)

## Expected result:
Should trigger notification on first page load itself

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.6.7 Chromium: 80.0.3987.87 (Official Build) nightly (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NO
- Can you reproduce this issue with the beta channel? NO
- Can you reproduce this issue with the dev channel? NO 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bbondy

**Comment by bbondy** [comment] 2020-02-07 18:24
I think this is a duplicate of https://github.com/brave/brave-browser/issues/8119 can you confirm?

**Comment by srirambv** [comment] 2020-05-26 11:39
Moving to `1.10.x Beta` as https://github.com/brave/brave-core/pull/5624 is uplifted

**Comment by bbondy** [comment] 2021-09-22 13:04
The infobar will be removed with https://github.com/brave/brave-browser/issues/18213 so this is no longer valid

**Closed by bbondy** 2021-09-22 13:04 UTC
Labels: bug, priority/P3, QA/Yes, release-notes/exclude, OS/Desktop, feature/ethereum-remote-client
