### ISSUE TITLE
Shields Panel and Rewards Panel are not translated to Norwegian

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3425] opened 2019-02-20 02:15 UTC
Follow up from: https://github.com/brave/brave-browser/issues/3064

## Steps to Reproduce

   1. Change Brave language to `Norwegian` 
   2. Open Brave Shields

## Actual result:

Shields panel is not translated
![image](https://user-images.githubusercontent.com/34715963/53061097-0478ce00-34bd-11e9-935b-d798ea076caa.png)
Rewards Panel is not translated:
![image](https://user-images.githubusercontent.com/34715963/53061509-2757b200-34be-11e9-9b8a-9eeb76a3764f.png)

## Expected result:
Shields panel is translated
Rewards Panel is translated:

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.60.44 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows 7

Not reproducible for: Arabic, Bulgarian, Chinese(Traditional), Croatian, Czech, Danish, Dutch, Finish, French, German, Greek, Hebrew, Hungarian, Italian, Japanese, Korean, Lithuanian, Polish, Portuguese, Russian, Slovak, Slovenian, Spanish, Turkish, Vietnamese

cc @brave/legacy_qa @bbondy @tomlowenthal

**Comment by bbondy** [comment] 2019-02-20 17:15
`components/brave_rewards/resources/extension/BUILD.gn:      locale = string_replace(locale, "nb", "no")`

Possibly related ^

**Comment by LaurenWags** [comment] 2019-02-20 19:22
Reproduced on macOS

Brave | 0.60.44 Chromium: 72.0.3626.109 (Offisiell delversjon) (64-bit)
-- | --
Versjon | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Mac OS X

**Comment by kjozwiak** [comment] 2019-02-22 03:29
Same results on `Mint 19.1 x64 VM` using the following build:

Brave | 0.60.45 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Mac OS X

Example of the issue occurring on `Mint 19.1 x64`:

<img width="815" alt="screen shot 2019-02-21 at 10 21 08 pm" src="https://user-images.githubusercontent.com/2602313/53217939-11fe9700-3628-11e9-984e-0667ba0c5a16.png">

**Comment by cezaraugusto** [comment] 2019-05-21 14:58
still an issue on 0.67.44

**Comment by bsclifton** [comment] 2019-06-11 15:39
Merged back to 0.65.x - however, leaving milestone alone so that our next release will include this for manual QA 😄

**Comment by btlechowski** [comment] 2019-06-12 14:35
Verification passed on

Brave | 0.66.88 Chromium: 75.0.3770.87 (Official Build) beta (64-bit)
-- | --
Revision | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

Used test plan from https://github.com/brave/brave-core/pull/2593
Logged https://github.com/brave/brave-browser/issues/4861

![image](https://user-images.githubusercontent.com/34715963/59356097-7739dd80-8d28-11e9-8cd7-44a81cd0292d.png)
![image](https://user-images.githubusercontent.com/34715963/59356149-946eac00-8d28-11e9-80f2-3ed99f851484.png)
![image](https://user-images.githubusercontent.com/34715963/59356248-c8e26800-8d28-11e9-80e0-1eccf84664e4.png)

![image](https://user-images.githubusercontent.com/34715963/59356299-dd266500-8d28-11e9-8b16-d52de4c92606.png)

**Comment by bsclifton** [comment] 2019-06-13 16:16
Removed verification labels - since we'll have a 0.65.x hotfix (Chromium version) we can re-verify the fixes with an RC 😄

**Comment by kjozwiak** [comment] 2019-06-13 16:23
Thanks @bsclifton 👍

**Comment by kjozwiak** [comment] 2019-06-14 14:43
<img width="441" alt="Screen Shot 2019-06-14 at 10 39 40 AM" src="https://user-images.githubusercontent.com/2602313/59517190-ffd38d80-8e90-11e9-92d3-44b1eb5155ea.png">

<img width="484" alt="Screen Shot 2019-06-14 at 10 42 02 AM" src="https://user-images.githubusercontent.com/2602313/59517222-0feb6d00-8e91-11e9-912a-9d75567c29d2.png">

@bsclifton it doesn't look like the translations made it into the RC builds. Are we sure this landed and has all the correct translations on the release channel? However, https://github.com/brave/brave-browser/issues/4880 has definitely been fixed.

**Comment by btlechowski** [comment] 2019-06-14 14:47
@bsclifton The translations didn't make it as @kjozwiak noted.

**Comment by kjozwiak** [comment] 2019-06-14 18:31
This seems to be working on all the other channels other than `0.65.x`, results:

* `0.68.50 Chromium: 75.0.3770.87`- PASSED
* `0.67.83 Chromium: 75.0.3770.87` - PASSED
* `0.66.90 Chromium: 75.0.3770.87` - PASSED
* `0.65.120 Chromium: 75.0.3770.90` - FAILED

I also checked that each channel looks the same under `brave://settings/languages` and is picking the same list of languages when the system language is set to the following:

<img width="724" alt="Screen Shot 2019-06-14 at 2 30 22 PM" src="https://user-images.githubusercontent.com/2602313/59530172-f6f2b400-8eb0-11e9-99e4-52873852df9b.png">

Seems like the only difference is that `0.65.120` is on `75.0.3770.90` and the remaining channels are currently still on `75.0.3770.87`. But I'm not 100% sure if that could be the cause for the above.

**Comment by srirambv** [comment] 2019-06-14 18:38
Here's the result on Linux/Ubutnu 19.04 
Release: Versjon 0.65.120 Chromium: 75.0.3770.90 (Offisiell delversjon) (64-bit) - **FAIL**
Beta: Versjon 0.66.90 Chromium: 75.0.3770.87 (Offisiell delversjon) beta (64-bit) - **PASS**
Dev: Versjon 0.67.83 Chromium: 75.0.3770.87 (Offisiell delversjon) dev (64-bit) - **PASS**
Nightly: Versjon 0.68.48 Chromium: 75.0.3770.87 (Offisiell delversjon) nightly (64-bit) - **PASS**

**Closed** 2019-06-16 16:18 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/rewards, feature/shields, feature/shields/panel, l10n, priority/P2

**Comment by bsclifton** [comment] 2019-06-17 16:03
As noted, only the code was updated. No new translations were pulled down. That is something we typically do as part of the Chromium upgrade

**Comment by bsclifton** [comment] 2019-06-17 16:05
And awesome - see the other change that @mkarolin made 😄 Thanks for taking care of that!

**Comment by LaurenWags** [comment] 2019-08-05 22:01
Verified passed with

Brave | 0.68.118 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2709 and STR from description.
![Screen Shot 2019-08-05 at 17 58 42](https://user-images.githubusercontent.com/28145373/62497824-128c8380-b7ab-11e9-9ffc-3dc1d4eea701.png)
![Screen Shot 2019-08-05 at 18 00 00](https://user-images.githubusercontent.com/28145373/62497826-14eedd80-b7ab-11e9-8d43-5a730a75a339.png)
