### ISSUE TITLE
[Android] Display search engine path instead of keyword as keywords don't work on Android

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#11495] opened 2020-08-28 14:30 UTC
## Description 
Display search engine path instead of keyword as keywords don't work n Android

## Steps to reproduce 

   1. Just go to search engine settings

## Actual result 
![device-2020-08-28-102958](https://user-images.githubusercontent.com/30602739/91579361-7f743d80-e919-11ea-83c3-84b098141e8d.png)

## Expected result
![device-2020-08-28-102139](https://user-images.githubusercontent.com/30602739/91579263-5ce22480-e919-11ea-9751-e8b58b1588c4.png)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment] 2020-08-28 14:42
Dupe of #10110

**Comment by anthonypkeane** [comment] 2020-10-14 18:54
Please don't show the shortcut and remove :b etc

**Comment by samartnik** [comment] 2020-11-03 19:06
New look is
![device-2020-11-03-140124](https://user-images.githubusercontent.com/30602739/98029574-b5341780-1ddd-11eb-9b50-c3ae12d2fb5a.png)

**Closed** 2020-11-03 20:38 UTC
Labels: OS/Android, QA/Yes, feature/search, feature/settings, priority/P2

**Comment by srirambv** [comment] 2020-11-16 07:53
Verification passed on OnePlus 6T with Android 10 running 1.18.51 x64 beta build
- Verified only search engine name is shown as per https://github.com/brave/brave-browser/issues/11495#issuecomment-721320072

Standard Tab | Private Tab
-- | --
![image](https://user-images.githubusercontent.com/17010094/99225877-ae93a000-27e0-11eb-8f4f-0e006bd164dc.png) | ![image](https://user-images.githubusercontent.com/17010094/99225888-b2bfbd80-27e0-11eb-8a6f-7f8147dbf6e4.png)

-------------
Verification passed on Samsung Tab A with Android 10 running 1.18.51 x64 beta build
- Verified only search engine name is shown as per https://github.com/brave/brave-browser/issues/11495#issuecomment-721320072

Standard Tab | Private Tab
-- | --
![image](https://user-images.githubusercontent.com/17010094/99225895-b6ebdb00-27e0-11eb-8182-f36c5f484084.png) | ![image](https://user-images.githubusercontent.com/17010094/99225899-bb17f880-27e0-11eb-8601-3bdede02a6e7.png)
