### ISSUE TITLE
Brave News article title highlight styling UI fix

### ISSUE THREAD

**Issue by aliabe-creator** [brave/brave-browser#19359] opened 2021-11-10 19:53 UTC
## Description 

When hovering over article title in Brave News, highlight shape does not dynamically scale to article title size. Can be solved by introducing dynamic scaling, or switching from shape highlight to font bolding/color change.

## Steps to Reproduce

   1. Open Brave News.
   2. Mouse over small grid article title.
   3. Observe shape does not scale to appropriate dimensions.

## Actual result:

![image](https://user-images.githubusercontent.com/80125711/141183078-550064bb-aae4-4b70-b43b-a0b1a340d3ec.png)
![image](https://user-images.githubusercontent.com/80125711/141183109-15e71807-39a5-4d78-b95b-22999c324d08.png)

## Expected result:

Dynamically scaled shape, or font highlight.

## Reproduces how often: 

Very often.

## Brave version (brave://version info)

1.31.91

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Unsure
- Can you reproduce this issue with the nightly channel? Unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by srirambv** [comment] 2021-11-19 06:05
Duplicate of #14195

**Closed by srirambv** 2021-11-19 06:05 UTC
Labels: bug, OS/Desktop
