### ISSUE TITLE
Shields preventing file uploads after installing most recent update

### ISSUE THREAD

**Issue by allisonphillips** [brave/brave-browser#2465] opened 2018-12-11 20:47 UTC
## Description 
Shields preventing file uploads in most recent update.

<img width="735" alt="screen shot 2018-12-11 at 12 45 19 pm" src="https://user-images.githubusercontent.com/8813886/49829196-a4d6a780-fd42-11e8-9297-bb77bbdfb55a.png">

## Steps to Reproduce

   1. Go to a website like JIRA or GitHub with Brave Shields enabled
   2. Attempt to upload an image (I've been attempting Mac OS Screenshot PNGs), either via file picker or drag and drop. 

## Actual result:
Get an error message along the lines of `Something went really wrong, and we can't process that file. Try again.` (GitHub)

## Expected result:
To be able to upload screenshots and other files, which worked until I installed the most recent Brave version last night.

## Reproduces how often: 
Every time I try to upload any sort of screenshot. At first I thought it was JIRA being terrible, but I'm experiencing the same behavior with GitHub.

## Brave version (brave://version info)
```
Brave | 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X
JavaScript | V8 7.1.302.28
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave,AutofillServerCommunication,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/thanx/Library/Application Support/BraveSoftware/Brave-Browser/Default
Variations | c134752e-f685ead32c707b42-dcf7018a411b6d4e-3f4a17dfb7d3b6c2-3f4a17dfd01ab0d3-755bc7553e006338-3f4a17df1a0d11d4-2f9febdf66df3e9d-a85d0b2febeb14fc-3f4a17dfb7e2524c-3f4a17dfb3888d8d-afba0f916c18ba9d-3f4a17df8982496f-3f4a17df61832c80-3f4a17dfcc20827f-77c422c591560a-29acad49041608a-3f4a17df241fff6c-ddf208789853922b-3f4a17df125b7f68-3f4a17df9ca1387e-3f4a17df1c752ce9-1c752ce9776de70c-e0278d3ded9149a9-3f4a17df34d450b1-3f4a17df31362330-3f4a17dfc70841c8-a256700714bdbe54-e8c7a65b8ee5ed19-c3125ea274658432-fa79b94ced7ba060-3f4a17df121ae2bc-65969d679e201a2b-3f4a17df27212adc-27212adc249dd49a-3f4a17df5274eb09-3f4a17dfceff87ec-3f4a17df44827ee5-3f4a17df332a4d9b-8e8e4a2b8f1e27f-3f4a17df345b5b61-3f4a17dfedbcf7c5-ddf1844d77bbdddc-3f4a17df5485fc4d-3f4a17df93731dca-3f4a17df9b4c4257-3f4a17df43f62d3b-3f4a17df4ae380f4-3f4a17df165e16d1-3f4a17df9e5c75f1-30e1b12b6fa07eb4-7282ca762981bcb4-3f4a17df5139837c-3f4a17df4934552d-3f4a17df7f8176d9-3f4a17df6c66bd8d-b204717823a898eb-fc93cf747a5ba892-3f4a17df4ea303a6-3f4a17dfb19465ab-b19465ab6e6e0c7e-3f17a7d895876445-2b71ffe4d92562a9-441539fdfc369826-3f4a17df2b33233e-881ca6c94da5ae82-3f4a17df56302f8c-2f882e7014c5a050-61ceed18cc54eb06-803f8fc4b2612322-8a9180b2ad6d27cc-3e870323df072bba-9a6c5085f56e0452-3f4a17df8576baf1-3f4a17df3038aa2e-3f4a17df51b9b54d-3f4a17df7345ea6-3f4a17df4bc337ce-f483b7fd9a2f4e5b-4bc735aeddf77e2c-63745fe11354da85-522c33b817507c76-3f4a17df494d8760-3f4a17dfbbb8f811-3f4a17df94e68624-803f8fc4cc73f8a1-3f4a17dfb4e8892d-3f4a17df8834fcca-3f4a17df11d91db8-d93a06206204e469-3f4a17dfea0f933d-3f4a17df493ac2c5-803f8fc4
```

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? IDK, I'm not going to install those.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? *YES*
- Is the issue reproducible on the latest version of Chrome? No

**Comment by Liunkae** [comment] 2018-12-11 22:02
Duplicate of #2034

**Comment by srirambv** [comment] 2018-12-12 16:31
Closing as dupe. Thanks for linking the issue @Liunkae

**Closed by srirambv** 2018-12-12 16:31 UTC
