### ISSUE TITLE
Click on Browser back button resets the DDG search button

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#1490] opened 2018-10-10 17:24 UTC
## Description 
Click on Browser back button resets the DDG search button

## Steps to Reproduce

   1. Launch brave with clean profile from CLI
   2. Open an incognito window
   3. Toggle DDG search button to ON
   4.  Do a search on DDG in incognito tab
   5. Click on browser back button

## Actual result:

Click on Browser back button resets the DDG search button

![pbddg](https://user-images.githubusercontent.com/2602313/47472923-690d7000-d7de-11e8-8711-b9758131e193.gif)

## Expected result:
DDG search button should be in ON state

## Reproduces how often: 
Always

## Brave version (chrome://version info)

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes
- Does it reproduce on browser-laptop? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@kjozwiak @LaurenWags @btlechowski @srirambv

**Comment by kjozwiak** [comment] 2018-10-11 02:02
Reproduced on `macOS 10.13.6 x64` using `0.55.12 Chromium: 70.0.3538.45 (Official Build) beta`. DDG still ends up being the default search engine on enabled, but the "switch" looks like it's disabled despite being enabled. Example:

* launch brave and open an incognito window
* toggle DDG -> ON
* type in something in the URL and hit search (DDG is being used)
* click on `Back` to return to `about:newtab` (DDG looks disabled)
* open a new tab, DDG looks disabled but still using DDG as the default search
* close/re-open the incognito window and you'll notice DDG is disabled (still uses DDG though)

This could be related to https://github.com/brave/brave-browser/issues/307 which is basically the same issue but deals with stats.

**Comment by kjozwiak** [comment] 2018-10-11 02:05
@rebron @bbondy as mentioned above, this seems similar to #307 which is a `P2` within the `1.x Backlog` milestone. Should this be moved there as well as it's almost the exact same issue? If we take this into `Releasable builds 0.55.x`, I think we should move #307 as well.

**Comment by tomlowenthal** [comment] 2018-10-19 21:56
I think this is #wontfix because we don't have that toggle on the new tab page any more.

**Comment by kjozwiak** [comment] 2018-10-25 02:42
Re-opening as this is still an issue. Even though the above toggle doesn't exist, we still have a toggle under `about:newpage` which still has the same bug. Example of the issue occurring:

![pbddg](https://user-images.githubusercontent.com/2602313/47472754-cfde5980-d7dd-11e8-809b-5af445b925ec.gif)

Tested on `macOS 10.13.6 x64` using the following build:


Brave | 0.57.2 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

**Closed** 2018-11-07 22:09 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, feature/private-browsing, priority/P3

**Comment by srirambv** [comment] 2018-12-11 16:45
Verification passed on 

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

- Verified search engine switch doesn't reset when navigated back from search result page
