### ISSUE TITLE
chrome.declarativeNetRequest.updateDynamicRules never return on latest Brave (Chromium v114.0)

### ISSUE THREAD

**Issue by RealAlphabet** [brave/brave-browser#30785] opened 2023-06-02 19:39 UTC
## Description 
`chrome.declarativeNetRequest.updateDynamicRules` method will never return when you start Brave. You need to restart the extension to make it work.

## Steps to Reproduce

   1. Create a basic extension with a background script that do `chrome.declarativeNetRequest.updateDynamicRules`
   2. Import the extension on Brave with Developer mode.
   3. Restart Brave.
   4. Open the background script and type.
     `await chrome.declarativeNetRequest.updateDynamicRules({ removeRuleIds: [ 1337 ] })`
     `console.log("I'm a hacker.")`

## Actual result:
After 60 seconds, there is still no output from the console.
![image](https://github.com/brave/brave-browser/assets/23159705/77018beb-76f8-4cd8-b881-ea73d3f44c9a)

## Expected result:
The console proves that you're a true hacker.

## Reproduces how often: 
Each time on the latest version of Brave (Chromium v114.0)

## Brave version (brave://version info)
1.52.117 Chromium: 114.0.5735.90 (Build officiel) (64 bits) 

## Version/Channel Information:
Stable

- Can you reproduce this issue with the current release? 
Yes.

- Can you reproduce this issue with the beta channel? 
Not tested.

- Can you reproduce this issue with the nightly channel? 
Not tested.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No.

- Does the issue resolve itself when disabling Brave Rewards?
No.

- Is the issue reproducible on the latest version of Chrome? 
No.

## Miscellaneous Information:
Nothing.

**Comment by RealAlphabet** [comment] 2023-06-03 10:45
The minimum reproducible example can be found here.
https://github.com/RealAlphabet/Brave-DRN

**Comment by RealAlphabet** [comment] 2023-12-09 00:47
https://github.com/brave/brave-browser/issues/30854 was a duplicate of this...

**Comment by bsclifton** [comment] 2023-12-12 20:49
Thanks @RealAlphabet - I'll close this as a duplicate of https://github.com/brave/brave-browser/issues/30854 since there is more information there (more comments, etc). Please subscribe to that issue for updates

**Closed by bsclifton** 2023-12-12 20:49 UTC
Labels: OS/Desktop

**Comment by nikjp2021** [comment] 2024-11-06 13:37
no zip downloaded
