### ISSUE TITLE
Chromium items do not go dark to match theme but Brave specific items do

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4637] opened 2019-05-29 16:47 UTC
## Description 
On older OS such as High Sierra, Chromium items (web ui, menus) do not go dark to match selected theme but Brave specific items (shields, toolbar) do. 

Newer OSes (such as Mojave) do not have this problem.

## Steps to Reproduce

   1. On a machine with an older OS, such as High Sierra, change theme to dark in settings.
   2. Toolbar becomes dark as expected.
   3. Visit a page and open shields. Verify shields are dark as well.
   4. Open hamburger menu. It is not dark.
   5. Visit a page like brave://bookmarks, history, etc.
   6. Page is not dark but toolbar is.

## Actual result:
Hamburger menu and page backgrounds do not match dark theme.
![Screen Shot 2019-05-29 at 12 15 49 PM](https://user-images.githubusercontent.com/28145373/58575129-7d4f9a80-820f-11e9-855d-17c0f216654a.png)

![Screen Shot 2019-05-29 at 12 07 00 PM](https://user-images.githubusercontent.com/28145373/58575140-80e32180-820f-11e9-89b7-7ce4373ec155.png)

## Expected result:
Hamburger menu and page backgrounds should match dark theme as shields and toolbar do.
![Screen Shot 2019-05-29 at 12 15 43 PM](https://user-images.githubusercontent.com/28145373/58575176-8f313d80-820f-11e9-9419-cdceafe49d30.png)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.65.113 Chromium: 75.0.3770.38 (Official Build) beta(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? per discussion with @petemill Chrome doesn't have dark theme for older OSes

## Miscellaneous Information:
Some screenshots of how Mojave behaves can be found here: https://github.com/brave/brave-browser/issues/3965#issuecomment-497002643

**Comment by simonhong** [comment] 2019-05-29 18:01
I think this wouldn't be fixed because upstream chromium only support dark mode to native ui(ex menu) or webui for Mojave.

**Comment by bsclifton** [comment] 2019-05-29 22:03
Given what @simonhong mentioned, I tagged with a `waiting upstream` label (as it doesn't make sense to go against Chromium for this). If it never gets addressed, we can likely close with `wontfix`

**Comment by LaurenWags** [comment] 2019-05-31 16:24
Thanks @bsclifton @simonhong 

A user noted this also happens on their Linux machine - https://community.brave.com/t/different-background-color-in-the-settings-page-on-different-platform/63243

**Comment by simonhong** [comment] 2019-05-31 19:17
@LaurenWags Yup, this is expected behavior for current upstream implementation.
Dark mode is disabled by default on linux platform like old MacOS version.
I think we should support if user explicitly choose light or dark instead of `Same as XXX`.

**Comment by simonhong** [comment] 2019-05-31 19:30
@LaurenWags I think this also can be happened on older Windows like Win7 and Win8 because they don't support dark mode. Can you check this on Win7 and Win8 also?

**Comment by LaurenWags** [comment] 2019-06-04 19:37
@simonhong I don't have Win 8, but I can confirm this also happens for Win 7.

Brave	0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit) 
Revision	78e4f8db3ce38f6c26cf56eed7ae9b331fc67ada-refs/branch-heads/3729@{#1013}
OS	Windows 7 Service Pack 1 Build 7601.24334

![Screen Shot 2019-06-04 at 3 36 26 PM](https://user-images.githubusercontent.com/28145373/58908441-96a88900-86de-11e9-9b97-b69ec56f6099.png)

**Comment by Brave-Matt** [comment] 2019-06-07 18:03
I can reproduce this on Win10 in both Nightly and Release builds. I have another user here confirming Laurens initial report:
https://www.reddit.com/r/brave_browser/comments/bxk3by/release_channel_update_v065118_is_live/eq8gxno?utm_source=share&utm_medium=web2xhttps://www.reddit.com/r/brave_browser/comments/bxk3by/release_channel_update_v065118_is_live/eq8gxno?utm_source=share&utm_medium=web2x

**Comment by simonhong** [comment] 2019-06-07 22:06
In C75 (`75.0.3770.80`), dark mode support on Windows is disabled. (It was supported latest C74).
and latest chromium enabled it. There is no `kDarkMode` feature in `https://cs.chromium.org/chromium/src/ui/base/ui_base_features.h`
```
#if defined(OS_MACOSX)
const base::Feature kDarkMode = {"DarkMode", base::FEATURE_ENABLED_BY_DEFAULT};
#else
const base::Feature kDarkMode = {"DarkMode", base::FEATURE_DISABLED_BY_DEFAULT};
#endif
```
I assume(not sure) that chrome team internally picked https://chromium-review.googlesource.com/c/chromium/src/+/1597930 because  chrome 75 stable support dark mode on Windows.

@bbondy @bsclifton @mkarolin Should we also pick that?
If not, we don't have `Same as Windows` mode in Win10 with current C75.

**Closed** 2019-07-17 21:50 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, priority/P4

**Comment by btlechowski** [comment] 2019-08-27 23:51
Dark mode works awesome! Great work!

Verification passed on

Brave | 0.69.117 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Ubuntu 18.04 LTS

Verified steps from the description.
Also verified Light mode.

![image](https://user-images.githubusercontent.com/34715963/63815704-e4c3d600-c935-11e9-9453-1ed20d03d3e6.png)
![image](https://user-images.githubusercontent.com/34715963/63815714-ef7e6b00-c935-11e9-9a40-69e4620f0283.png)
![image](https://user-images.githubusercontent.com/34715963/63815716-f4dbb580-c935-11e9-8bda-86da0e7814e6.png)
![image](https://user-images.githubusercontent.com/34715963/63815727-fc02c380-c935-11e9-8ab6-692479ff0911.png)
![image](https://user-images.githubusercontent.com/34715963/63815735-01f8a480-c936-11e9-8616-a0e0fda1e9f8.png)
