### ISSUE TITLE
Brave beta sync not syncing extensions

### ISSUE THREAD

**Issue by tortino** [brave/brave-browser#19164] opened 2021-11-02 07:16 UTC
## Description 

On beta when I start to sync a new profile the extensions are not synced.
All other data is synced correctly (I have bookmarks, passwords, history...)
See also: 
https://www.reddit.com/r/brave_browser/comments/qjy6g4/brave_beta_sync_not_syncing_extensions_as_of/

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by josandstrom** [comment] 2021-11-18 05:20
Happens to me too. Using Brave 1.32.106. Settings, Extensions, Theme does not sync properly. Bookmarks, History seems to work though.

**Comment by tu5alum** [comment] 2021-11-19 01:20
Same here: installed new PC and Brave and extensions got not synced, even after hours.
Interestingly I added a new MacBook to the sync chain last week and the extensions had been pulled within seconds after entering the sync code/phrase.

Win: Version 1.32.106 (64-Bit)
MacOS: 1.31.91 (arm64)

I created a new sync chain and even 11 extensions are instelled, they are not synced yet, after about 5 hours:
![image](https://user-images.githubusercontent.com/45538118/142531507-bacd0ec2-908e-446e-a68c-cf50eeec1124.png)

**Comment by LIGHTUPSKECHERS** [comment] 2021-11-19 04:51
Mine are also not syncing. One device is a late 2013 Macbook pro 15 inch and the one I'm trying to sync to is a Macbook air 13 inch 2017.

**Comment by mikestaub** [comment] 2021-11-20 23:21
In the meantime this tool helped me import them manually: https://github.com/gabrielbarros/export-all-extensions

**Comment by xmrv** [comment] 2021-11-21 10:14
Same here.

**Comment by prof-m** [comment] 2021-11-21 17:12
Not on Beta, but actually seeing the same thing. My two Macbooks synced extensions within seconds, but my windows machine hasn't synced extensions even after a week.

**Comment by timkgh** [comment] 2021-11-21 19:34
Same issue between Mac and Linux, they are not sync'ing. 
Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)

**Comment by apolymen** [comment] 2021-11-23 08:24
Same issue here between Windows and Fedora Linux, extensions not syncing both ways.
Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)

**Comment by NayamAmarshe** [comment] 2021-11-25 11:08
Same issue here on stable version. The sync is broken.

**Comment by tu5alum** [comment] 2021-11-26 21:05
My sync is working again between Windows 10 machines and one MacBook, since last browser restart. Now all entries are showing `Modification Time | 2021-11-26 19:26:19` (CET)
New version on Windows is now 1.32.113 Chromium: 96.0.4664.45 (Offizieller Build) (64-Bit)

**Comment by timkgh** [comment] 2021-11-26 22:16
Looks fixed here too.

**Comment by NayamAmarshe** [comment] 2021-11-26 22:32
Yes, the sync works now

**Comment by apolymen** [comment] 2021-11-27 09:13
Version 1.32.113 fixed it!

**Comment by bsclifton** [comment] 2021-11-29 04:39
Closing as multiple reports above that it's working again

cc: @jsecretan @AlexeyBarabash in case we wanted to ID a root cause

**Closed by bsclifton** 2021-11-29 04:39 UTC
Labels: feature/sync, OS/Desktop, closed/works-for-me
