### ISSUE TITLE
Tracker & ads blocking reset to default after Clear browsing data

### ISSUE THREAD

**Issue by AdKiller** [brave/brave-browser#15607] opened 2021-05-04 07:00 UTC
## Description 

Tracker & ads blocking reset to default (Standard) after Clear browsing data

## Steps to Reproduce

   1. Set Tracker & ads blocking: aggressive
   2. Ctrl+Shift+Del, Clear browsing data, select all, all time.

## Actual result:

Tracker & ads blocking resets to standard.

## Expected result:
 Tracker & ads blocking should not change.

## Reproduces how often: 

Always

## Brave version (brave://version info)

(Apr 28, 2021)
Version 1.23.75 Chromium: 90.0.4430.93 (Official Build) (64-bit)
OS Windows 10 Pro 1909

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

**Comment by Tonev** [comment] 2021-05-04 09:41
Sounds like duplicate of https://github.com/brave/brave-browser/issues/15347.

**Comment by AdKiller** [comment] 2021-05-15 08:44
Confirming the issue is still present in the latest update Version 1.24.85 Chromium: 90.0.4430.212 (Official Build) (64-bit)

**Comment by rebron** [comment] 2021-08-12 22:39
Closing as dupe of #15437

**Closed by rebron** 2021-08-12 22:39 UTC
Labels: OS/Desktop
