### ISSUE TITLE
History entries no longer sorted by timestamp

### ISSUE THREAD

**Issue by NebuPookins** [brave/brave-browser#41781] opened 2024-10-22 04:55 UTC
### Description

When I open the history view (e.g. by pressing CTRL-H), previously, the entries were sorted by timestamp, which is how I expected. On the latest version of Brave (Version 1.71.114 Chromium: 130.0.6723.58 (Official Build) (64-bit)), it is no longer sorted by timestamp, but by some weird arbitrary order.

### Steps to reproduce

1. Press CTRL-H
2. Scroll through and examine the history entries

### Actual result

Items appear in a different order than by timestamp.

### Expected result

Items should appear ordered by timestamp

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Version 1.71.114 Chromium: 130.0.6723.58 (Official Build) (64-bit)

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

I'm attaching an example screenshot showing entries going from from 9:04PM at the top down to 8:57PM (which is normal) before suddenly jumping suddenly containing entries for 9:42PM again.

Some entries are censored for privacy reasons.

![Image](https://github.com/user-attachments/assets/83da9892-96bc-4102-a47a-cfac3a776349)

**Comment by bsclifton** [comment] 2024-10-22 08:41
Gave this a test - at first, I couldn't reproduce it.  But then I used Google Maps and was able to reproduce it.
![Image](https://github.com/user-attachments/assets/7a8535af-9aca-4787-8381-2a4afec6d07e)

However if I leave the page open for a while, it seems to fix itself? The entries shift up to where they are supposed to be

@NebuPookins can you try that too? Ctrl + H, it should show the wrong order. But then keep the page open a while. Scroll up and down the history page. See if the entries eventually move to where it's supposed to go. Please let me know - that could be an important clue

**Comment by bsclifton** [comment] 2024-10-22 18:10
I think this is a duplicate of https://github.com/brave/brave-browser/issues/41763 (which affects bookmarks). Seems history is also affected

Upstream bug in Chromium is https://issues.chromium.org/issues/374007459?pli=1

Will test to see that this is related to the `CCSlimming` feature and if so, I'll close this as a duplicate

**Comment by NebuPookins** [comment] 2024-10-22 23:33
> However if I leave the page open for a while, it seems to fix itself?

I don't know if it "fixes" itself, but if I leave the page open for a few seconds (say 10 seconds), the page does seem to auto-refresh, and then the entries appear in a new (but still wrong) order. The entries are *mostly* right, but every now and then, there's a cluster of entries which appear somewhere they don't belong, e.g. 4 entries dated at 4PM in the middle of 20 entries that are dated at 10PM.

**Comment by bsclifton** [comment] 2024-10-23 05:37
OK - I have confirmed, this is a duplicate of https://github.com/brave/brave-browser/issues/41763

I'll add some notes to that issue and close this as a duplicate.

We have a fix coming for this - stay tuned. This also affects the bookmarks page. In the meantime, you can add some command-line flags to Brave if you want to fix the behavior. On Windows, you can right click / edit the shortcut and then add `--disable-features=CCSlimming` to the end of the Target field.

**Closed by bsclifton** 2024-10-23 05:37 UTC
Labels: feature/history, OS/Desktop
