### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by AdobeFan16** [brave/brave-browser#40835] opened 2024-09-03 21:21 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.69.162 Chromium: 128.0.6613.120
Operating System: Windows NT 10.0.18362

I don't know what URL was

Can you reproduce this crash?
Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
I was browsing, until it keeps crashing over and over after a few hours, can you help me stop these constant crashes? Because I'm tired of them

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/85b71600-5a73-850c-0000-000000000000

**Comment by bsclifton** [comment] 2024-09-06 19:02
Closing as duplicate of https://github.com/brave/brave-browser/issues/40746

**Closed by bsclifton** 2024-09-06 19:02 UTC
Labels: crash, OS/Windows, priority/P2, OS/Desktop
