### ISSUE TITLE
[Desktop] ANGLE OpenGL libraries not included in nightly Linux builds

### ISSUE THREAD

**Issue by DebauchedSloth** [brave/brave-browser#11219] opened 2020-08-13 09:07 UTC
## Description 
ANGLE libraries are not included in the Linux build.  This break HW acceleration.

## Steps to Reproduce

   1. Look in zip file
   2. Verify that libEGL.so and libGLESv2.so are not included in the build.
   3. Profit!

## Expected result:
ANGLE libraries are included, or some other workaround is made, and hardware acceleration is functional.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.14.38 Chromium: 85.0.4183.59 (Official Build) unknown (64-bit)
-- | --
Revision | 7cc9a5ee672625c38427a839cb1b15efd3128084-refs/branch-heads/4183@{#1216}
OS | Linux
JavaScript | V8 8.5.210.19
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.59 Safari/537.36
Command Line | /usr/lib/brave-nightly-bin/brave --disable-gpu-driver-bug-workarounds --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --enable-features=AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode,DnsOverHttps,OmniboxContextMenuShowFullUrls,MixedContentSiteSetting,ReducedReferrerGranularity,PasswordImport,PrefetchPrivacyChanges --disable-features=NotificationTriggers,TextFragmentAnchor,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,AutofillServerCommunication,VideoPlaybackQuality,PrivacySettingsRedesign,TabHoverCards,SmsReceiver,SafeBrowsingEnhancedProtection --flag-switches-begin --enable-gpu-rasterization --enable-oop-rasterization --enable-zero-copy --ignore-gpu-blacklist --enable-features=AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode,DnsOverHttps,OmniboxContextMenuShowFullUrls,MixedContentSiteSetting,ReducedReferrerGranularity,PasswordImport,PrefetchPrivacyChanges,DecodeJpeg420ImagesToYUV,DecodeLossyWebPImagesToYUV,OopRasterizationDDL --flag-switches-end
Executable Path | /usr/lib/brave-nightly-bin/brave
Profile Path | /home/gwhite/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment] 2020-08-14 07:18
cc: @iefremov @fmarier

**Comment by iefremov** [comment] 2020-08-14 13:21
that explains why Brave always had software rendering on my linux machines :D 
sounds like the important one for linux users

**Comment by DebauchedSloth** [comment] 2020-08-14 13:26
You can check this by pulling libGL.so and libGLESv2.so from chrome dev and dropping them in the brave directory.

**Comment by DebauchedSloth** [comment] 2020-09-03 08:28
Just an FYI.  Still an issue as of:

`Brave	1.15.32 Chromium: 85.0.4183.83 (Official Build) unknown (64-bit)
Revision	94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS	Linux
JavaScript	V8 8.5.210.20
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
Command Line	/usr/lib/brave-nightly-bin/brave --disable-gpu-driver-bug-workarounds --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --enable-features=MixedContentSiteSetting,WebUIDarkMode,PassiveMixedContentWarning,AutoupgradeMixedContent,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,DnsOverHttps,OmniboxContextMenuShowFullUrls --disable-features=VideoPlaybackQuality,TextFragmentAnchor,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,NotificationTriggers,PrivacySettingsRedesign,AutofillServerCommunication,PasswordCheck,TabHoverCards,SmsReceiver,SafeBrowsingEnhancedProtection --flag-switches-begin --enable-gpu-rasterization --enable-oop-rasterization --enable-zero-copy --ignore-gpu-blacklist --enable-features=MixedContentSiteSetting,WebUIDarkMode,PassiveMixedContentWarning,AutoupgradeMixedContent,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,DnsOverHttps,OmniboxContextMenuShowFullUrls,DecodeJpeg420ImagesToYUV,DecodeLossyWebPImagesToYUV,OopRasterizationDDL --flag-switches-end
Executable Path	/usr/lib/brave-nightly-bin/brave
Profile Path	/home/gwhite/.config/BraveSoftware/Brave-Browser/Default`

**Comment by bsclifton** [comment] 2020-09-03 20:45
Closing as a duplicate of https://github.com/brave/brave-browser/issues/11504- thanks for the report 😄

**Closed by bsclifton** 2020-09-03 20:45 UTC
Labels: OS/Desktop, OS/Linux
