### ISSUE TITLE
Make it easier to change selected account for connected Dapps

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19862] opened 2021-12-01 17:34 UTC
If the user is already connected to a Dapp with some set of accounts, and they switch to an account that is not connected.
The panel should show some indication that they can switch to this account instead for connecting.

How this is handled in MetaMask is like this:
<img width="354" alt="Screen Shot 2021-12-01 at 12 34 13 PM" src="https://user-images.githubusercontent.com/831718/144284444-07f089aa-2f29-458d-a1c4-a094de1925ac.png">

We should have some different UI that works for us.

**Comment by Douglashdaniel** [comment] 2021-12-07 22:52
Closing as duplicate of https://github.com/brave/brave-browser/issues/19954

**Closed by Douglashdaniel** 2021-12-07 22:52 UTC
Labels: closed/duplicate, priority/P2, OS/Desktop
