### ISSUE TITLE
Binance Deposit address should show Address AND Memo if applicable

### ISSUE THREAD

**Issue by uniibu** [brave/brave-browser#9566] opened 2020-05-01 03:51 UTC
## Description 

Cryptocurrencies such as EOS, XLM, and XRP needs to have their `Address` AND `Memo` shown together.

## Steps to Reproduce

   1. Sign in to Binance Widget
   2. Toggle the visibility of the balances and go to Deposit tab
   3. Choose either EOS, XLM, or XRP

## Actual result:

On `Desktop Release`, Binance widget deposit addresses for networks such as EOS, XLM, XRP are only showing the `Address`
![release](https://i.gyazo.com/abea52485988c61581a730ced4652cb1.png)

An attempt to fix this landed on `Beta` and `Nightly` channels https://github.com/brave/brave-core/pull/5267, however, this time it only shows the `Memo`.
![beta-nightly](https://i.gyazo.com/4fffc8b2da828418db79df31cd13e4ad.png)

## Expected result:
It should show both `Address` and `Memo`  and imho, the fix should at least land on the `Release` channel, because right now, users with little to no knowledge about this currencies might deposit to the given address without the memo, only to find out later that they will not receive it on their Binance accounts.

## Brave version (brave://version info)

- Release

Brave | 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}

- Beta

Brave | 1.9.50 Chromium: 81.0.4044.129 (Official Build) beta (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}

- Nightly

Brave | 1.10.22 Chromium: 81.0.4044.129 (Official Build) nightly (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? YES

**Comment by srirambv** [comment] 2020-05-01 05:49
Dupe of #9535

**Closed by srirambv** 2020-05-01 05:49 UTC
Labels: closed/duplicate, deprecated/feature/widgets

**Comment by uniibu** [comment] 2020-05-01 13:26
@srirambv pardon me if i'm wrong,I just wanted to clarify on how could this be a duplicate of a closed issue which is not solved? The supposed fix https://github.com/brave/brave-core/pull/5267 for issues https://github.com/brave/brave-browser/issues/9535 and  https://github.com/brave/brave-browser/issues/9535 should have landed already at https://github.com/brave/brave-core/tree/v1.10.22 

I am now at **Nightly 1.10.23**

Brave | 1.10.23 Chromium: 81.0.4044.129 (Official Build) nightly (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}

And I still get  the image below.. **No** EOS address, just a `memo`

![nightly](https://i.gyazo.com/7c95b5b427a9f7cfe14f8ef4fd9111a7.png)

*I apologize if I'm wrong and just got confused*
