### ISSUE TITLE
Disable speech API on strict fingerprint blocking

### ISSUE THREAD

**Issue by 138138138** [brave/brave-browser#14242] opened 2021-02-18 16:05 UTC
## Description 
The speech API reveals language preferences on Windows 10. Please disable or spoof speech API when set to strict fingerprint blocking.

## Steps to Reproduce

   1. On Windows 10 go to https://browserleaks.com/javascript
   2. The SpeechSynthesis section reveals the languages installed on your system.

## Actual result:

SpeechSynthesis shows:
Microsoft David Desktop - English (United States)
Microsoft Zira Desktop - English (United States)
(My own language here. I want to keep secret.)

## Expected result:
SpeechSynthesis should be disabled, or only show:
Microsoft David Desktop - English (United States)
Microsoft Zira Desktop - English (United States)

## Reproduces how often: 
Easily reproduced

## Brave version (info found on brave://version)
Brave | 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Windows 10 OS Version 1809 (Build 17763.1757)

**Comment by pes10k** [comment] 2021-09-13 18:16
Thank you for the bug report!  Marking this as a dupe of https://github.com/brave/brave-browser/issues/18062, where we'll track progress on this issue.

**Closed by pes10k** 2021-09-13 18:16 UTC
Labels: privacy, OS/Windows, feature/shields/fingerprint, feature-request, privacy-pod, OS/Desktop
