### ISSUE TITLE
Claiming ads grants from rewards page hides one of the ad grant notification

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7498] opened 2019-12-20 14:35 UTC
## Description 
Claiming ads grants from rewards page hides one of the ad grant notification

## Steps to reproduce 

   1. Have multiple ad grants notifications
   2. Open rewards page and claim one of them
   3. After grant is claimed, one grant notification is hidden, reload page brings back the notification

## Actual result 
![adsclaim](https://user-images.githubusercontent.com/17010094/71255920-b19ebb80-2305-11ea-9dfe-9c9686554430.gif)

## Expected result
Hiding the notification makes it looks like the grant disappeared or was claimed should not hide any notification unless its claimed

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? May be yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Tablet Samsung Tab A
   - Android version: 9.0
   
## Brave version
1.6.1 RC1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment] 2020-02-06 17:48
Duplicate of: https://github.com/brave/brave-browser/issues/7760

**Closed** 2020-02-27 09:01 UTC
Labels: ARM, QA/Yes, android-related, bug, feature/rewards, release-notes/exclude
