### ISSUE TITLE
Cannot change order of browser tabs by pulling them while holding left mouse button (1.34.x)

### ISSUE THREAD

**Issue by szymonpk** [brave/brave-browser#20275] opened 2021-12-31 07:17 UTC
**Yes, I have looked for similar issues with the following keywords 'move tabs', 'move tab', 'move card', 'move cards', 'ole'. Nothing on the first page looked alike.**

## Description  

After upgrade to 1.34.x, I have found two issues that may be related:

1. When I am trying to move tab (change its position, 'holding' browser tab/card with the left-click), the new window is created and I cannot put tab/card in a new place in my old window. It worked with 1.33.xx.
2. When I am trying to pull (holding with right click) media URL (for example a YT URL) to the external player. Video playback does not start. It worked with 1.33.xx.

I think it may be the same issue somehow related to the lack of data (metadata?) passed when I move 'objects' out of (and withing) the Brave window.

## Steps to Reproduce

   1. Open a new window
   2. Open any two URLs
   3. Try to change their order by pulling one tab/card before or after another

## Actual result:

New Brave window is created.

## Expected result:

Tabs order should change.

## Reproduces how often: 

Easily reproduced - always.

## Brave version (brave://version info)

Brave | 1.34.77 Chromium: 97.0.4692.56 (Official Build) (64-bit)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | Linux
JavaScript | V8 9.7.106.18
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.56 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-crashpad --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --no-pings --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/szymon/.config/BraveSoftware/Brave-Browser/Profile 1
Variations | AdRewardsStudy:NextPaymentDayConversionsStudy:NewDefaultPatternDefault1pBlockingStudy:DisabledEphemeralStorageStudy:EnabledNativeCosmeticFilteringStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledRequestAdsEnabledApiStudy:EnabledSpeedreaderReleaseStudy:Disabled

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? Haven't checked
- Can you reproduce this issue with the nightly channel? Haven't checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Haven't checked
- Does the issue resolve itself when disabling Brave Rewards? Haven't checked
- Is the issue reproducible on the latest version of Chrome? Haven't checked

## Miscellaneous Information:

I have also tried with a new profile. Issue persists.

**Comment by npn225** [comment] 2022-01-07 18:57
I am also having this issue after the update to version 1.34.xx.
This was not a problem when I was running version 1.31.xx.

I have taken the liberty of doing some of the tests below: 

> ## Version/Channel Information:
> * Can you reproduce this issue with the current release?  
>> * Yes!  This problem started because I updated to the new release version of 1.34.xx

> * Can you reproduce this issue with the beta channel? Haven't checked
> * Can you reproduce this issue with the nightly channel? Haven't checked
> 
> ## Other Additional Information:
> * Does the issue resolve itself when disabling Brave Shields? 
>> * No, it does not! I have checked by disabling all functionality of Brave Shields and the problem persists.

> * Does the issue resolve itself when disabling Brave Rewards? 
>> * No, it does not! I have checked by disabling all functionality of Brave Rewards and the problem persists.

> * Is the issue reproducible on the latest version of Chrome? 
>> * No, it is not! I have installed the latest version of the Chromium browser (which Brave Browser is said to be based upon) and have found that this issue is NOT present in Chromium.

>

**Comment by bsclifton** [comment] 2022-01-10 08:05
Closing as duplicate of https://github.com/brave/brave-browser/issues/20386; Specific upstream information captured here:
https://github.com/brave/brave-browser/issues/20386#issuecomment-1008118828

**Closed** 2022-01-10 08:06 UTC
Labels: closed/duplicate, OS/Desktop

**Comment by LiftedStarfish** [comment] 2022-01-26 22:06
Many have suggested disabling system title bar and buttons, but that _does not_ work for me.

**Comment by npn225** [comment] 2022-01-26 23:06
> Many have suggested disabling system title bar and buttons, but that _does not_ work for me.

For myself and many others, this bug was resolved with the updated version of the Brave Browser - version 1.34.81.

If you are **not** using this latest version, then try updating your install to it and then see if it fixes the bug. 

If you **are** using this version and are still encountering this bug, then it may be best for you to open a new issue that explains how you are still experiencing this problem even with the latest version of the Brave Browser installed.
