### ISSUE TITLE
Extension Syncing

### ISSUE THREAD

**Issue by Modelmat** [brave/brave-browser#4094] opened 2019-04-13 01:00 UTC
## Description 
Currently Brave does not sync extensions through the sync chain. It does not sync the extension settings (proxyOmega and other chrome extensions sync settings through the google sync)

## Steps to Reproduce

   1. Set up a browser on one device, add some extensions
   2. Set up a sync chain with another device
   3. No extensions were synced.

## Actual result:
No extensions sync nor extension data.

## Expected result:
Extensions and extension data syncs.
(including chrome APPS)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 0.62.51 Chromium: 73.0.3683.103 (Official Build)unknown (64-bit)
-- | --
Revision | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes.

**Comment by srirambv** [comment] 2019-04-14 16:31
This would be extremly difficult with mobile devices in chain. Not sure if we plan to implement this 

cc: @bbondy @tomlowenthal

**Comment by bbondy** [comment] 2019-04-14 20:16
no extensions on mobile but we can still do it for desktop

**Comment by bsclifton** [comment] 2019-04-15 16:59
This would be a beautiful feature on desktop 🎉

**Comment by bavalpey** [comment] 2019-04-30 19:48
I know there are those who wish for this to happen.  There is a post on the brave forums requesting this as well: https://community.brave.com/t/sync-extensions-across-devices/41222/8.

This would be a great feature, and the ability for it to be a selection (similar to how bookmarks are done) would be great, too!

**Comment by 05nelsonm** [comment] 2019-05-10 17:54
Will syncing using our own personal servers be included, so people can choose not to expose their IP addresses to anyone but themselves? Maybe including advanced option for syncing via WebDav? Would be very nice.

Also, extension support for mobile is possible. Check out Kiwi Browser for Android. Copy/Paste?

**Comment by smaslennikov** [comment] 2019-05-16 17:35
Aside from extensions, syncing browser settings would be fantastic too. Really hoping to see either of the two soon!

**Comment by ewscott9** [comment] 2019-05-22 03:14
I would love to see this to be a Desktop feature. It would make sense not to do it for mobile, since chrome doesn't do it either.

Firefox does have the feature for mobile, though this has caused many problems for extension developers.

I wonder if we can use Firefox's sync system as a blueprint/inspiration for the Desktop sync system though. Since it works great and is open source see: https://github.com/mozilla-services/syncserver

**Comment by zdumitru** [comment] 2019-10-02 08:42
Any progress on this feature? It is very desired.

**Comment by bsclifton** [comment] 2020-01-13 07:06
Lots of +1's from https://github.com/brave/brave-browser/issues/7238

**Comment by deadbird99** [comment] 2020-01-14 15:24
Hi Brave dev team. Any news of this feature?

**Comment by vdrover** [comment] 2020-02-03 21:34
Adding my +1

**Comment by andrei-pavel** [comment] 2020-02-03 21:37
Studies have shown that adding this feature would leave Chrome at 20% of user market.

**Comment by tetractius** [comment] 2020-02-05 17:37
Studies also have shown that if you don't add this feature before Microsoft Edge for Linux support is release people will start to adopt that one first ... :fearful:

**Comment by mikestaub** [comment] 2020-02-05 17:54
@tetractius is right. This is the one feature blocking me from adopting Brave. It should be top priority.

**Comment by andrei-pavel** [comment] 2020-02-05 17:56
There must be some browser mafia conspiracy blocking the development of this feature. There's no other explanation.

**Comment by ThirtyWorse** [comment] 2020-02-14 01:10
This is a required feature if you actually want to compete with any modern browser. Syncing extensions (but most importantly their settings) is critical to adoption, and the longer brave lags behind on convenience things like this the longer brave will simply lag behind. People simply aren't willing to sacrifice convenience for security, anymore.

Obviously this is a desktop thing, and mobile devices should simply be excluded or opted out by default.

**Comment by kerner1000** [comment] 2020-02-19 08:54
For now, I would like to manually sinc, using [unison](https://www.cis.upenn.edu/~bcpierce/unison/). Can anyone tell, which files/ folders I need to sync (both devices ubuntu desktop)?

**Comment by ElderOrb** [comment] 2020-04-18 11:13
Please do it for desktop only, I personally will be happy and switch to brave immediately.

**Comment by bsclifton** [comment] 2020-05-28 07:04
This should be addressed by Sync v2; subscribe to https://github.com/brave/brave-browser/issues/9241 for updates 😄

**Comment by ElderOrb** [comment] 2020-06-18 11:40
#9241 is closed, does it mean extensions sync is working now?

**Comment by deadbird99** [comment] 2020-06-18 11:52
Check the milestone #9241 is into: https://github.com/brave/brave-browser/milestone/115

**Comment by ElderOrb** [comment] 2020-06-18 11:58
Checked - not sure what should be here searching by 'extension' results zero.

**Comment by bsclifton** [comment] 2020-06-18 17:03
@ElderOrb yes - this is working now 😄 Only available on Nightly at the moment (1.12) - but it does work great 😄

**Closed by bsclifton** 2020-06-18 17:03 UTC
Labels: feature/sync, fixed-with-sync-v2, priority/P4, suggestion

**Comment by btlechowski** [comment] 2020-08-06 02:19
Verification passed on

Brave | 1.12.107 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Ubuntu 18.04 LTS

Verified with following STR:
1. Clean install on `DeviceA` and `DeviceB`
1. Establish sync chain between `DeviceA` and `DeviceB`
1. Enable `Extension` syncing in Sync Settings
1. `DeviceA`: install https://chrome.google.com/webstore/detail/custom-cursor-for-chrome/ogdlpmhglpejoiomcodnpjnfgcpmgale/related
1. Wait for sync update

* Expected behavior
  * `DeviceB`: the extension is synced

![image](https://user-images.githubusercontent.com/34715963/89483247-dca62480-d79b-11ea-98df-346e0789dd92.png)
