### ISSUE TITLE
Parts of Brave Shields Get Cut Off on Small Laptops

### ISSUE THREAD

**Issue by 4444dogs** [brave/brave-browser#23408] opened 2022-06-10 22:39 UTC
## Description 
If you are using a small screen, parts of the Brave Shields menu can get cut off. (In my case, it's the "Global Defaults" button)

## Steps to Reproduce

   1. Open Brave on a Small Laptop (I tested this on a 14" Screen)
   2. Click the Brave Shields Button
   3. The Global Defaults Button Will be Cut Off

## Actual Result:
<img width="289" alt="Screenshot 2022-06-10 153005" src="https://user-images.githubusercontent.com/85034387/173158730-66e986a2-c745-43ba-8a46-2a38acf8532c.png">

## Expected result:
<img width="194" alt="Screenshot 2022-06-10 153248" src="https://user-images.githubusercontent.com/85034387/173158916-f96eefc5-5885-4c7f-a06c-1353c5fc21cd.png">

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave: 1.39.120
Revision: 870f7bcc58dfa811cc68c2186439721385e086d0-refs/branch-heads/5005@{#1125}
OS:  Windows 11 Version 21H2 (Build 22000.675)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Untested
- Can you reproduce this issue with the nightly channel? Untested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by nisarg-soni** [comment] 2022-06-11 13:31
I can confirm this issue can be reproduced.

**Comment by rebron** [comment] 2022-06-28 19:16
Closing as duplicate of https://github.com/brave/brave-browser/issues/22539
Fixed in 1.41.65 and higher (which is in beta now).

**Closed by rebron** 2022-06-28 19:16 UTC
Labels: feature/shields, OS/Desktop
