### ISSUE TITLE
Ads are shown in Private window

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5391] opened 2019-07-25 18:24 UTC
## Description 

Ads are shown in Private window

## Steps to Reproduce

   1. Clean profile  0.67.117
   2. Enable rewards
   3. Open a tab and visit brave.com and keep page idle for 5 sec, after that close the tab
   4. Open 2nd tab - don't load any site in it
   5. Open a private window and load brave.com or load some other sites
   6. Ads are shown in Private Tab

## Actual result:

Ads are shown in Private Tab

![image](https://user-images.githubusercontent.com/38657976/61898479-0ac11980-af37-11e9-9a17-64db0391c17e.png)

![image (4)](https://user-images.githubusercontent.com/38657976/61898517-1dd3e980-af37-11e9-8f53-5955c4262273.png)

## Expected result:

Ads should not be shown in Private window

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.67.117 Chromium: 76.0.3809.62 (Official Build) (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @tmancey

**Comment by LaurenWags** [comment] 2019-07-25 18:32
@GeetaSarvadnya do you have the logs for this? when you opened brave.com in a normal window i'm guessing it was classified (technology-computing or something similar) so the browser would know what kind of ad to serve. but when you opened the site in a private window, was it also assigned a classifier?

**Comment by kjozwiak** [comment] 2019-07-25 18:39
Assuming the ad was served using the data the classifier collected when brave.com was opened in a regular tab as @LaurenWags mentioned above. I tried the following in a private tab using `0.70.6 Chromium: 76.0.3809.6`:

* enabled ads and set `Maximum number of ads displayed` --> `5`
* opened a private tab and loaded several websites and received the following

```
[16646:775:0725/143142.582033:INFO:ads_impl.cc(213)] Browser state changed to idle
[16646:775:0725/143144.583787:INFO:ads_impl.cc(220)] Browser state changed to unidle
[16646:775:0725/143144.586001:INFO:ads_impl.cc(631)] Notification for category
[16646:775:0725/143144.586287:INFO:ads_impl.cc(648)] Notification not made: category is empty
[16646:775:0725/143144.598795:INFO:client.cc(267)] Successfully saved client state
```
I tried that several times and didn't receive any classifications as expected via PB. Leaving the PB opened, I went through the following:

* opened a regular tab and visited brave.com
* switched over back to the PB window and triggered an ad

```
[16645:775:0725/143437.246696:INFO:confirmations_impl.cc(1005)]   category: technology & computing-software
[16645:775:0725/143437.246737:INFO:confirmations_impl.cc(1006)]   url: https://eventchain.io/event-details/622712c1a0f7607621077fe2e7768736/2019_Blockchain_Futurist_Conference/?code=futurist60
[16645:775:0725/143437.246750:INFO:confirmations_impl.cc(1007)]   text: Buy passes with Crypto to get 60% off, limited time only!
[16645:775:0725/143437.246760:INFO:confirmations_impl.cc(1008)]   advertiser: Blockchain Futurist Conference
[16645:775:0725/143437.246785:INFO:confirmations_impl.cc(1009)]   uuid: 0533e784-7eb1-45ba-98c8-f2e64825a326
[16645:775:0725/143437.246796:INFO:confirmations_impl.cc(1010)]   type: click
```

**Comment by kjozwiak** [comment] 2019-07-25 18:43
@GeetaSarvadnya try the following case and see if you get the same results:

* enable ads on a new profile using `0.70.6 Chromium: 76.0.3809.6` and change `Maximum number of ads displayed` --> `5` (don't visit any websites)
* go into PB and visit `imdb.com` and trigger an ad (shouldn't be classified)
* open brave.com in a regular tab
* switch back to PB and trigger another ad

You should get an ad that's classified as `technology & computing-software`

**Comment by srirambv** [comment] 2019-07-25 19:52
I think the ad should not be served because the min time isn't satisfied and the tab is also closed. so what is being classified even though valid ad should not be served.

**Comment by LaurenWags** [comment] 2019-07-25 20:02
not sure what you mean by minimum time not being satisfied?

**Comment by LaurenWags** [comment] 2019-07-25 20:53
closing based on discussion internally, outcome is that if ads are enabled, are allowed (based on history) and there is data to determine what kind of ad could be shown - it should be shown regardless of whether you are in a private tab or not. confirmed with @mandar-brave and can provide additional detail if needed.

**Closed by LaurenWags** 2019-07-25 20:53 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/ads
