### ISSUE TITLE
Newly verified publisher should change state of Brave Rewards button

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#4942] opened 2019-06-16 03:07 UTC
When using "refresh status" within the Brave Rewards panel, the site currently being viewed may be newly verified. In that case, the Brave Rewards button in the address bar should be changed to reflect verified status.

**Comment by ryanml** [comment] 2019-06-24 03:59
Closing as a duplicate of: https://github.com/brave/brave-browser/issues/4846

**Closed by ryanml** 2019-06-24 03:59 UTC
Labels: feature/rewards
