### ISSUE TITLE
Dashboard setting `Show background image` switch is distorted in an upgraded profile

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8070] opened 2020-02-05 09:49 UTC
## Description 

Dashboard setting `Show background image` switch is distorted in an upgraded profile

## Steps to Reproduce

   1. Clean profile 1.2.43
   2. Open a bunch of sites
   3. Make sure top sites are added in a new tab page
   4. Upgrade to 1.3.110
   5. Remove stats
   6. Top sites are moved to the top as expected
   7. Click on Dashboard settings
   8. Dashboard setting `Show background image` switch is distorted in an upgraded profile
  
Note: close and open dashboard settings fix the issue

## Actual result:

Dashboard setting `Show background image` switch is distorted in an upgraded profile

![image](https://user-images.githubusercontent.com/38657976/73833715-6b0f0d00-4830-11ea-9663-3f12ff5d185a.png)

![image](https://user-images.githubusercontent.com/38657976/73829893-b8d44700-4829-11ea-932f-e027c4a7b4b3.png)

## Expected result:
Dashboard settings switches should be aligned properly

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.3.110 Chromium: 80.0.3987.78 (Official Build) (64-bit)
-- | --
Revision | cb5aa81cb0a3a2c674b93bc7ffb34a86cd3b4802-refs/branch-heads/3987@{#752}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No - upgraded from 1.0.1 -->1.2.43 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @petemill @bsclifton

**Comment by LaurenWags** [comment] 2020-02-05 14:28
Reproduces on macOS when using light theme only, does not reproduce on dark theme. Steps:
1. Install 1.2.43
2. Populate some top sites
3. Turn off stats
4. Upgrade on `test` channel to 1.3.110
5. Do not see issue with dark theme/same as macOS bc my OS is set to dark:
<img width="425" alt="Screen Shot 2020-02-05 at 9 26 10 AM" src="https://user-images.githubusercontent.com/28145373/73850516-d4bff480-47f9-11ea-8153-f2628bd4e5ae.png">

6. Change to light theme
7. Reproduce issue:
<img width="436" alt="Screen Shot 2020-02-05 at 9 26 34 AM" src="https://user-images.githubusercontent.com/28145373/73850520-d7224e80-47f9-11ea-887c-98a5c078798f.png">


Brave | 1.3.110 Chromium: 80.0.3987.78 (Official Build) (64-bit)
-- | --
Revision | cb5aa81cb0a3a2c674b93bc7ffb34a86cd3b4802-refs/branch-heads/3987@{#752}
OS | macOS Version 10.14.6 (Build 18G103)

**Comment by rebron** [comment] 2020-02-05 19:51
<img width="353" alt="Screen Shot 2020-02-05 at 11 50 35 AM" src="https://user-images.githubusercontent.com/5951041/73877560-be239880-480d-11ea-84f6-a25257e184f8.png">
I'm seeing this with the ntp flag enabled.

**Comment by rebron** [comment] 2020-02-05 23:00
I'm seeing the error intermittently and can reproduce by reloading the new tab page and opening and closing the dashboard settings.

**Comment by rebron** [comment] 2020-02-05 23:03
<img width="389" alt="Screen Shot 2020-02-05 at 2 47 32 PM" src="https://user-images.githubusercontent.com/5951041/73891167-7e1ddf00-4828-11ea-8f8a-bd1c0f28cbeb.png">
<img width="393" alt="Screen Shot 2020-02-05 at 2 56 03 PM" src="https://user-images.githubusercontent.com/5951041/73891173-80803900-4828-11ea-9e33-f737432fc747.png">

Able to reproduce on dark theme and light theme Win/macOS 1.3.111.

**Comment by w0ts0n** [comment] 2020-02-07 21:39
Can +1 that I saw this as of today.
 Brave Version 1.3.113 Chromium: 80.0.3987.87 (Official Build) (64-bit) on MacOS 10.15.1

<img width="554" alt="Screenshot 2020-02-07 at 4 31 49 PM" src="https://user-images.githubusercontent.com/2603015/74067934-5b2a3100-49c8-11ea-8a1e-6a01d3ae5a99.png">
<img width="373" alt="Screenshot 2020-02-07 at 4 30 15 PM" src="https://user-images.githubusercontent.com/2603015/74067938-5c5b5e00-49c8-11ea-809d-268ad7bc98fd.png">

**Comment by cezaraugusto** [comment] 2020-02-11 13:05
<img width="553" alt="Screen Shot 2020-02-11 at 9 57 00 AM" src="https://user-images.githubusercontent.com/4672033/74239002-b8b6ca00-4cb5-11ea-8cd6-96b1a8d6d0d6.png">

This seems to be an upstream bug that got fixed in some upstream version after this bug report. I'm not able to reproduce. Using macOS following steps Lauren suggested. Tested on:

Release build `Version 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)`
Beta build `Version 1.4.80 Chromium: 80.0.3987.85 (Official Build) beta (64-bit)`
Dev build `Version 1.5.86 Chromium: 80.0.3987.87 (Official Build) dev (64-bit)`
Nightly build `Version 1.6.14 Chromium: 80.0.3987.87 (Official Build) nightly (64-bit)`
Development build `Version 1.6.12 Chromium: 80.0.3987.87 (Developer Build) (64-bit)`

**Comment by kjozwiak** [comment] 2020-02-12 06:57
@GeetaSarvadnya @w0ts0n @LaurenWags mind checking to see if this is still reproducible as per the above comment from @cezaraugusto.

**Comment by LaurenWags** [comment] 2020-02-12 16:34
I have not been able to reproduce using 

Brave | 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.14.6 (Build 18G103)

Tried the following:
* Steps from my original comment about reproducing the issue: https://github.com/brave/brave-browser/issues/8070#issuecomment-582433750
* Steps from description https://github.com/brave/brave-browser/issues/8070#issue-560255386
* Comment by @rebron https://github.com/brave/brave-browser/issues/8070#issuecomment-582654143

Was unable to reproduce using dark or light theme on 1.3.115.

**Comment by w0ts0n** [comment] 2020-02-12 16:51
Version 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
Windows 10. 

I'm still able to reproduce. (included date and time in screenshot)
![image](https://user-images.githubusercontent.com/2603015/74357533-10286900-4d8e-11ea-8f4e-3fc7624a5c22.png)

**Comment by rebron** [comment] 2020-02-12 18:18
This looks to be happening on older profiles. New profiles don't seem to be effected.
cc: @simonhong in case he has any ideas.

**Comment by rebron** [comment] 2020-02-18 20:51
I think this will be fixed in 80.0.3987.116 with https://chromium.googlesource.com/chromium/src/+/b1738fb61215bb8610e08f65de4d01681e250f7f

**Comment by bsclifton** [comment] 2020-02-19 06:04
Closing - we should be able to verify this with latest build. I suspect this was fixed with https://chromium.googlesource.com/chromium/src/+/b1738fb61215bb8610e08f65de4d01681e250f7f

**Closed by bsclifton** 2020-02-19 06:04 UTC
Labels: Chromium/waiting upstream, QA/Test-Plan-Specified, QA/Yes, bug, feature/new-tab, regression

**Comment by kjozwiak** [comment] 2020-02-19 08:01
@w0ts0n mind checking one more time using https://github.com/brave/brave-browser/releases/tag/v1.3.118 which includes the css-grid revert that @bsclifton mentioned above.

**Comment by srirambv** [comment] 2020-02-19 09:05
Verification passed on 

Brave | 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit)
-- | --
Revision | dc00a510e4c2ae25c4d084cc3d946fc782249224-refs/branch-heads/3987@{#917}
OS | Linux

- Verified steps from issue description
- Verified switch knobs are correctly aligned 
- Dark Theme
![image](https://user-images.githubusercontent.com/17010094/74818523-d672d780-5324-11ea-895f-316360c457dd.png)
- Light Theme
![image](https://user-images.githubusercontent.com/17010094/74818560-e1c60300-5324-11ea-90e6-29dee336607a.png)
- Verified toggle all switches doesn't cause knobs to be misaligned

**Comment by rebron** [comment] 2020-02-24 17:07
@w0ts0n Works for you now, correct?

**Comment by w0ts0n** [comment] 2020-02-24 18:13
Correct! Thanks all.
