### ISSUE TITLE
Download "Show in Folder" does not open Windows Explorer.

### ISSUE THREAD

**Issue by Sophist-UK** [brave/brave-browser#3754] opened 2019-03-17 20:09 UTC
## Description 
"Show in Folder" option for downloaded file does not open a Windows Explorer window.

## Steps to Reproduce
   1. Download a file
   2. On the download bar at the bottom of the window, select "Show in Folder"

## Actual result:
Nothing happens.

## Expected result:
Windows Explorer window should open on the folder the download is to with the download item selected. 

## Brave version (brave://version info)
Brave | 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17763.379

### Reproducible on current release:
No idea.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? No

**Comment by bsclifton** [comment] 2019-03-18 23:05
hmm... I just tried this and it works fine

@Sophist-UK are you able to reproduce on any link? I know if a download fails (interrupted, corrupt, etc), you can't do "Show In Folder"

**Comment by rebron** [comment] 2019-03-22 15:54
Closing. QA can't reproduce. If you have new info we can reopen.

**Closed by rebron** 2019-03-22 15:54 UTC
Labels: OS/Windows, feature/download, need-more-info

**Comment by Sophist-UK** [comment] 2019-03-22 16:40
It is working for me now too. So appears to have been just a glitch. If it recurs I will log it again.

**Comment by casedup** [comment] 2023-07-17 15:43
Issue is happening to me using Brave browser inside of my ubuntu 22 server running xfce gui... Whenever I press show in folder for downloads it loads up Visual Code Insiders... default application for File Manager set to Thunar... so weird
