### ISSUE TITLE
Mouseover on setting or history or bookmarks icons says chrome:// instead of brave://

### ISSUE THREAD

**Issue by satishdelhibabu** [brave/brave-browser#6981] opened 2019-11-18 19:04 UTC
## Description 

Mouseover on setting or history or bookmarks icons says chrome:// instead of brave://

## Steps to Reproduce

   1. open a tab and mouseover history or bookmarks or settings icon

## Actual result:

![Screen Shot 2019-11-18 at 2 04 07 PM](https://user-images.githubusercontent.com/1200408/69081606-57f85800-0a0c-11ea-8b69-c2169636e3e9.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment] 2019-11-19 16:20
related: https://github.com/brave/brave-browser/issues/1973

**Comment by rebron** [comment] 2020-02-07 04:44
Closing as dupe of #2566

**Closed by rebron** 2020-02-07 04:44 UTC
Labels: branding, duplicate, feature/new-tab, priority/P4
