### ISSUE TITLE
White border is added to brave://welcome page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#15890] opened 2021-05-17 08:35 UTC
## Description 

White border is added to brave://welcome page

## Steps to Reproduce

   1. Open 1.26.21
   2. Open brave://welcome
   

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/118458392-55b5ad80-b718-11eb-9b44-9a3dfa656667.png)

## Expected result:
should not be any white border added to brave://welcome page

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.26.21 Chromium: 91.0.4472.57 (Official Build) nightly (64-bit)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | Windows 10 OS Version 2004 (Build 19041.985)

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @bsclifton 

@bsclifton reappeared the issue https://github.com/brave/brave-browser/issues/14137

**Comment by LaurenWags** [comment] 2021-05-17 14:15
duplicate of https://github.com/brave/brave-browser/issues/15870

**Closed by LaurenWags** 2021-05-17 14:15 UTC
Labels: OS/Desktop, QA/Test-Plan-Specified, QA/Yes, about-pages/welcome, regression
