### ISSUE TITLE
Brave browser crashes while opening on macOS

### ISSUE THREAD

**Issue by Datta0** [brave/brave-browser#11758] opened 2020-09-17 10:57 UTC
As stated, Beta, Dev, and Nightly crash while opening on macOS. The stable version works fine though.

To reproduce :
1. Download Beta/Dev/Nightly versions from GitHub or the official brave website.
2. Install the app
3. Open

I've seen a couple of threads with the same issue. They were closed it saying 'Disable Accessibility Keyboard' from System Preferences on macOS. 
But it is disabled and I've never enabled the same.

Crash Logs (Dev version):
[Hastebin](https://hastebin.com/tajisifopi.sql)

**Comment by bsclifton** [comment] 2020-09-24 23:15
Closing as duplicate of https://github.com/brave/brave-browser/issues/7546

**Closed by bsclifton** 2020-09-24 23:15 UTC
Labels: OS/Desktop, OS/macOS, crash
