### ISSUE TITLE
Unable to unfollow migrated Planet Mozilla atom feed in v2

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26255] opened 2022-10-25 23:04 UTC
## Description 

Unable to unfollow migrated Planet Mozilla atom feed in v2

## Steps to Reproduce

   1. install `1.47.14`
   2. launch Brave
   3. load `https://planet.mozilla.org/`
   4. copy the `Atom` feed link: `https://planet.mozilla.org/atom.xml`
   5. click on `Customize`
   6. click on `Brave News`
   7. enter `https://planet.mozilla.org/atom.xml` under `Feed URL` and click on `Add Source`
   8. wait a bit (big feed)
   9. load `brave://flags`
   10. set `brave://flags/#brave-news-v2` to `Enabled`
   11. click on `Relaunch`
   12. open a new-tab page
   13. click on `Customize`
   14. click on `Turn on Brave News`
   15. hover to the right of `Planet Mozilla` in the `Top Sources` section
   16. click `Unfollow`

## Actual result:

Nothing happens

<img width="1109" alt="Screen Shot 2022-10-25 at 4 03 40 PM" src="https://user-images.githubusercontent.com/387249/197898255-5f7fccf0-bfb7-4361-b3eb-d03d7db30e59.png">

## Expected result:

Should remove `Planet Mozilla` from the sources list

Note: I am still able to remove `Top Sources`

<img width="1109" alt="Screen Shot 2022-10-25 at 4 03 49 PM" src="https://user-images.githubusercontent.com/387249/197898237-54036a4d-bf9a-4c13-942d-26883b9460e1.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.14 Chromium: 107.0.5304.62 (Official Build) nightly (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @petemill @fallaciousreasoning @rebron @brave/qa-team

**Comment by fallaciousreasoning** [comment] 2022-10-25 23:18
Pretty sure this is a duplicate of https://github.com/brave/brave-browser/issues/26196

Should be fixed in `1.47.17` (I'm uplifting to `1.46.x`)

**Closed by fallaciousreasoning** 2022-10-25 23:18 UTC
Labels: bug, closed/duplicate, QA/Test-Plan-Specified, regression, OS/Desktop, feature/brave-news
