### ISSUE TITLE
Brave installer does not honor local culture

### ISSUE THREAD

**Issue by NZ-HIPS** [brave/brave-browser#6366] opened 2019-10-09 00:34 UTC
When installing latest nightly (0.72.81), brave starts in english language even though my system is localized:

```
C:\Windows\system32>powershell get-culture

LCID             Name             DisplayName
----             ----             -----------
1058             uk-UA            Ukrainian (Ukraine)
```

## Steps to Reproduce
   1. Install latest nighly on a non-english windows

## Actual result:
English

## Expected result:
Localized (e.g. French)

## Reproduces how often: 
Seems to be easily reproduced

## Brave version (brave://version info)
Brave | 0.72.81 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1809 (Build 17763.1)

## Version/Channel Information:
- Can you reproduce this issue with the current release?
Yes ( v0.69.132 )
- Can you reproduce this issue with the beta channel?
Didn't try
- Can you reproduce this issue with the dev channel?
Didn't try
- Can you reproduce this issue with the nightly channel?
Yes ( v0.72.81 )

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
N/A
- Does the issue resolve itself when disabling Brave Rewards?
N/A
- Is the issue reproducible on the latest version of Chrome? 
No (Chrome detects and runs in local language from the very first run)

## Miscellaneous Information:
If i manually delete the profile created by brave and then change a reg key at "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update\ClientState\{C6CB981E-DB30-4876-8639-109F8933582C}\lang" to anything else than default value "en", next profile creation occurs in local language, so to me it is an initial installer problem.

**Comment by kjozwiak** [comment] 2019-10-09 07:03
@user1313 are you referring to the `stub` installer? Example:

![Annotation 2019-10-09 030148](https://user-images.githubusercontent.com/2602313/66458676-4dc46080-ea41-11e9-8f4d-2daf4ec5d4af.jpg)

**Comment by user1313** [comment] 2019-10-09 10:59
@kjozwiak no, i am referring to the brave itself:
![screen](https://user-images.githubusercontent.com/931150/66475943-aa04a000-ea94-11e9-9485-61aaff32d067.PNG)

**Comment by ekerazha** [comment] 2020-04-19 08:42
Brave's default language should be system's language, like for every other major browser. AdBlock's block lists should also be automatically configured with country-specific lists. Having to manually configure the language is a showstopper for Brave's usage.

**Comment by bsclifton** [comment] 2020-05-20 22:06
@ekerazha I worked with @simonhong and tracked down this issue after another person pinged me. Apologies it took this long to resolve ☹️  It is fixed in Nightly and with next Dev/Beta build it will be fixed too. We're planning a 1.9 desktop release for tomorrow - so that will fix new installs on Windows

Thanks for reporting - I'll close this as a duplicate of https://github.com/brave/brave-browser/issues/9712 (which has more information, including links to the fixes)

**Closed by bsclifton** 2020-05-20 22:06 UTC
Labels: l10n, setup/installer
