### ISSUE TITLE
brave://settings/clearBrowserData doesn't automatically shows up requested dialog

### ISSUE THREAD

**Issue by saahriktu** [brave/brave-browser#8870] opened 2020-03-26 10:51 UTC
The behavior of the history cleanup dialog has changed (noticed in GNU/Linux).

In the versions newer than 1.8.30 brave://settings/clearBrowserData just shows brave://settings/ with some difference: requested cleanup dialog shows up only after clicking on the "Advanced Settings" button (which has nothing to do with history cleaning) at the end of the page.

**Comment by kjozwiak** [comment] 2020-03-26 17:53
* `1.5.115 CR: 80.0.3987.149 (Official Build) (64-bit)` - Can't reproduce
* `1.7.73 CR: 80.0.3987.149 (Official Build) dev` - Can't reproduce
* `1.8.32 CR: 81.0.4044.69 (Official Build) nightly` - Reproduced

Looks like this is only affecting Nightly and not the other channels. Checked on `macOS 10.15.3 x64 Catalina`. @mkarolin checked Windows and confirmed the above as well.

STR for QA:

**`Case #1`**

* launch brave and open `brave://settings/clearBrowserData`
* you'll notice that the `Clear browsing data` modal isn't being displayed

**`Case #2`**

* launch brave and press `command` + `control` + `delete`
* you'll notice that `brave://settings` is opened but that `Clear browsing data` modal isn't being displayed

**Comment by bsclifton** [comment] 2020-03-26 17:56
Great find with `1.8.30`, @saahriktu! 😄 `1.8.31` was the first version of Nightly where we landed Chromium 81, which helps narrow down where the problem is 👍 We'll look into and find out what happened

**Comment by bsclifton** [comment] 2020-03-26 18:21
@mkarolin has found the following:
1. Navigate to brave://settings/clearBrowserData
2. Nothing happens (clear modal should come up)
3. Click advanced on the side menu (left)
4. Modal all of the sudden pops up

I suspect it's related to https://github.com/brave/brave-core/commit/9d2f803f091caa2994e3ba28862cc6c4dbbef507#diff-166e28418b661667403b64249ce36c3a and how `Privacy` was moved under `Advanced`

**Closed** 2020-03-27 01:34 UTC
Labels: QA/Yes, bug, feature/settings, priority/P2

**Comment by btlechowski** [comment] 2020-04-13 06:53
Verification passed on

Brave | 1.8.72 Chromium: 81.0.4044.92 (Official Build) dev (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-browser/issues/8870#issuecomment-604581723
Verified opening the modal though `brave://settings/clearBrowserData` and `CTRL + SHIFT + DEL`

![image](https://user-images.githubusercontent.com/34715963/79099111-b4fdfd00-7d63-11ea-94b1-415322c29a07.png)
