### ISSUE TITLE
lld-link: error: duplicate symbol: public: static class network::SystemRequestHandler * __cdecl network::SystemRequestHandler::GetInstance(void)

### ISSUE THREAD

**Issue by zfoxzero** [brave/brave-browser#7566] opened 2020-01-02 03:25 UTC
Windows10
VS2019  
use   `npm run build`  error
use   `npm run build Release` success

`FAILED: chrome.dll chrome.dll.lib chrome.dll.pdb
ninja -t msvc -e environment.x64 -- ../../third_party/llvm-build/Release+Asserts/bin/lld-link.exe /nologo "-libpath:C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\ATLMFC\lib\x64" "-libpath:C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\lib\x64" "-libpath:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "-libpath:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "-libpath:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" /IMPLIB:./chrome.dll.lib /DLL /OUT:./chrome.dll /PDB:./chrome.dll.pdb @./chrome.dll.rsp
lld-link: error: duplicate symbol: public: static class network::SystemRequestHandler * __cdecl network::SystemRequestHandler::GetInstance(void) in obj/brave/services/network/public/cpp/cpp/system_request_handler.obj and in network_cpp.dll
lld-link: error: duplicate symbol: public: struct network::ResourceRequest __cdecl network::SystemRequestHandler::OnBeforeSystemRequest(struct network::ResourceRequest const &) in obj/brave/services/network/public/cpp/cpp/system_request_handler.obj and in network_cpp.dll
lld-link: error: duplicate symbol: public: void __cdecl network::SystemRequestHandler::RegisterOnBeforeSystemRequestCallback(class base::RepeatingCallback<struct network::ResourceRequest __cdecl(struct network::ResourceRequest const &)> const &) in obj/brave/services/network/public/cpp/cpp/system_request_handler.obj and in network_cpp.dll
ninja: build stopped: subcommand failed.`

**Comment by bsclifton** [comment] 2020-01-03 18:09
Closing as duplicate of https://github.com/brave/brave-browser/issues/7524

**Closed by bsclifton** 2020-01-03 18:09 UTC
Labels: dev-setup, need-more-info, source-master
