### ISSUE TITLE
Importing bookmarks from Safari fails

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#2710] opened 2018-12-23 05:38 UTC
## Description 
Users are reporting that bookmark imports from Safari are failing.

## Steps to Reproduce
1. Install Brave Core
2. Attempt to import bookmarks from Safari

## Actual result:
Import fails, or structure is not preserved.

## Expected result:
Import should succeed, and maintain original structure.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
0.58.16

### Reproducible on current release:
Yes.

### Related Issue(s)
See issue #996 for Vivaldi support.
Related upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=850225

**Comment by kirkins** [comment] 2019-01-06 04:48
+1 from Punisha on telegram

**Comment by Liunkae** [comment] 2019-03-07 23:46
Helpful information from Community: https://community.brave.com/t/why-importing-mac-safari-bookmarks-isnt-working/47521

**Comment by bsclifton** [comment] 2019-06-18 20:09
There is a known work-around for this (will share link if I can find it) - @rossmoody notes that the new Edge has a wizard which helps with this, which we can look at 😄

**Comment by Brave-Matt** [comment] 2019-10-22 18:55
@bsclifton https://support.brave.com/hc/en-us/articles/360019782291-How-do-I-import-or-export-browsing-data-

**Comment by bsclifton** [comment] 2020-01-08 22:45
+1 from @ZaJarv via https://github.com/brave/brave-browser/issues/7123

**Comment by simonhong** [comment] 2020-02-06 02:32
@rebron I think this issue should be `wontfix` because macOS prevent application access to safari's bookmark list. After giving that permission to Brave, it can import w/o any error. Same as chrome. WDYT?

**Comment by rebron** [comment] 2020-02-06 02:36
@simonhong Edge has a prompt for full disk access for Safari import. Can you take a look at that and maybe we need to add design/UE input in here? 
<img width="446" alt="Screen Shot 2020-02-05 at 6 35 58 PM" src="https://user-images.githubusercontent.com/5951041/73901018-61909f80-4846-11ea-81b4-ddf9c6d4af18.png">
<img width="458" alt="Screen Shot 2020-02-05 at 6 35 43 PM" src="https://user-images.githubusercontent.com/5951041/73901021-63f2f980-4846-11ea-94f5-095f7bbe36db.png">

**Comment by simonhong** [comment] 2020-02-06 02:42
@rebron Yup, showing guide dialog seems good.

**Comment by rebron** [comment] 2020-02-06 02:51
cc: @karenkliu @bradleyrichter on Safari full disk access dialog in order to import bookmarks from Safari.

**Comment by rebron** [comment] 2020-02-14 18:38
https://support.brave.com/hc/en-us/articles/360019782291#safari for a more targeted link into the section of the article.

**Closed** 2020-02-20 22:29 UTC
Labels: OS/macOS, QA/Yes, bug, design, feature/importer, priority/P3

**Comment by bsclifton** [comment] 2020-02-23 05:01
@rebron would be a good candidate for uplift 😄 Even if we just uplifted to Beta (1.5) or Dev (1.6)

**Comment by LaurenWags** [comment] 2020-03-11 16:48
Verified passed using `10.14.6 x64` on `macOS` (`Mojave`)

Brave | 1.5.109 Chromium: 80.0.3987.132 (Official Build) beta (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4530
<img width="482" alt="Screen Shot 2020-03-11 at 12 41 25 PM" src="https://user-images.githubusercontent.com/28145373/76441943-9092b780-6396-11ea-8f53-cbca3300958b.png">

* Confirmed the link on the modal opens https://support.brave.com/hc/en-us/articles/360019782291#safari in a new tab
* Confirmed `Cancel` closes the modal.
* Confirmed `Open System Preferences` opened System Preferences to the Privacy > Full Disk Access section
* Confirmed following the steps outlined in the help doc and close/relaunch of Brave I was able to import bookmarks from Safari.
<img width="1200" alt="Screen Shot 2020-03-11 at 12 44 19 PM" src="https://user-images.githubusercontent.com/28145373/76441972-98525c00-6396-11ea-9c59-484127c5151c.png">

**Comment by LaurenWags** [comment] 2020-03-11 17:17
cc @kjozwiak to check other macOS versions

**Comment by kjozwiak** [comment] 2020-03-12 03:22
Verification **PASSED** on `macOS 10.14.3 x64` using the following build:

```
Brave | 1.5.109 Chromium: 80.0.3987.132 (Official Build) beta (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | macOS Version 10.15.3 (Build 19D76)
```

* Verified test plan from https://github.com/brave/brave-core/pull/4530
* Confirmed the link on the modal opens https://support.brave.com/hc/en-us/articles/360019782291#safari in a new tab
* Confirmed `Cancel` closes the modal.
* Confirmed `Open System Preferences` opened System Preferences to the `Privacy > Full Disk Access` section
* Confirmed following the steps outlined in the help doc and close/relaunch of Brave I was able to import bookmarks from Safari.

<img width="478" alt="Screen Shot 2020-03-11 at 11 17 10 PM" src="https://user-images.githubusercontent.com/2602313/76484071-29edb800-63ef-11ea-9cf9-05fbe6759ec9.png">

<img width="699" alt="Screen Shot 2020-03-11 at 11 22 13 PM" src="https://user-images.githubusercontent.com/2602313/76484076-2ce8a880-63ef-11ea-9482-7bf96aa30b7e.png">

<img width="551" alt="Screen Shot 2020-03-11 at 11 20 47 PM" src="https://user-images.githubusercontent.com/2602313/76484085-2f4b0280-63ef-11ea-9672-fee8856573b8.png">
