### ISSUE TITLE
Twitter promoted ads sometimes get through.

### ISSUE THREAD

**Issue by jnki** [brave/brave-browser#2419] opened 2018-12-09 09:51 UTC
## Description 

Sometimes when I load twitter, promoted ads are displayed, but disappear when I refresh. My Brave shields are on and it says it is blocking ads.

## Steps to Reproduce

   1. Visit your twitter feed.
   2. Browse through the feed and you may find a promoted tweet (ad)
   3. Refresh the page, and it will be removed.

## Actual result:

Promoted ads sometimes show up in feed
https://i.imgur.com/MVogHVt.png
https://i.imgur.com/EHvqhH1.png

## Expected result:
No promoted ads in feed ever.

## Reproduces how often: 

Intermittent.

## Brave version (brave://version info)

Brave | 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 10 Pro 64bit 1809

**Comment by britalmeida** [comment] 2019-06-12 08:37
For me, the promoted tweets always show.
I believe this started happening when I enabled auto-play (default is disabled).
I don't know how to change again the autoplay setting.

Version 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)

**Comment by bsclifton** [comment] 2019-12-31 05:56
Surprised we missed this one! Apologies for not responding sooner

This is expected behavior, as far as I know. Because the content showing is a 1st party ad (ex: served by twitter.com). We have a basic cosmetic blocker (you can right click elements, and provide a selector) and will have list support for cosmetic blockers soon (@antonok-edm had merged, but it was reverted due to a technical problem)

cc: @snyderp @ryanbr

**Closed by bsclifton** 2019-12-31 05:56 UTC
