### ISSUE TITLE
BR panel contents are not scaled properly

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7147] opened 2019-11-28 14:07 UTC
## Description 

BR panel contents are not scaled properly

## Steps to Reproduce

STR1:
   1. Launch clean profile 1.3.38 with staging flags
   2. Enable rewards and claim grants
   3. Click on the hamburger menu and exit the browser
   4. Relaunch browser without staging flag
   5. Click on `Claim grants` from NTP widget
   6. Place the source triangle to the appropriate target
   7. BR panel contents are not scaled properly

STR2:
   1. Launch clean profile 1.0.1 with staging flag
   2. Enable rewards and claim grants in BR panel
   3. Place the source triangle to the appropriate target in BR panel
   4. BR panel contents are not scaled properly

## Actual result:

BR panel contents are not scaled properly
Nightly:
![image](https://user-images.githubusercontent.com/38657976/69811866-0b372d00-1215-11ea-9ac2-20b24c888aa1.png)

Release:
![image](https://user-images.githubusercontent.com/38657976/69812350-ff983600-1215-11ea-98b4-7d5e42efffea.png)

## Expected result:
BR panel contents should be scaled properly

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.3.38 Chromium: 78.0.3904.108 (Official Build) nightly (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @ryanml @rebron 

Windows 10 X64  - DPI is as below
![image](https://user-images.githubusercontent.com/38657976/69812849-007d9780-1217-11ea-9f3a-b090ee26c892.png)

**Comment by zenparsing** [comment] 2020-02-28 20:48
Although I was unable to reproduce the error on master and release (1.4.95), I was able to confirm the same root cause as #7597.

**Comment by NejcZdovc** [comment] 2020-02-29 06:09
@zenparsing will fix for https://github.com/brave/brave-browser/issues/7597 fix this one as well?

**Comment by zenparsing** [comment] 2020-02-29 06:43
@NejcZdovc it will

**Comment by NejcZdovc** [comment] 2020-02-29 06:44
please add it to PR so that PR will auto close this issue, just add new line with Resolves and link to this issue

**Closed** 2020-03-04 15:39 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards

**Comment by btlechowski** [comment] 2020-03-18 22:33
Verification passed on

Brave | 1.7.65 Chromium: 80.0.3987.132 (Official Build) dev (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/77013685-d5a78280-6970-11ea-854e-492690001b4e.png)

More verification done in: https://github.com/brave/brave-browser/issues/7597
