### ISSUE TITLE
please add [translate web page] button

### ISSUE THREAD

**Issue by limengyu1990** [brave/brave-browser#15746] opened 2021-05-11 10:51 UTC
Please add such a function, users can choose to translate the web content in the specified language at any time.

[demand](https://www.reddit.com/r/BATProject/comments/n9u3d8/please_add_such_a_function_users_can_choose_to/)

**Comment by limengyu1990** [comment] 2021-05-11 10:56
Translation is a very important function. Once brave realizes this function, I can completely uninstall chrome, but now I can't, because I can browse some English websites. If I don't have the function of automatic translation, it's too difficult..

**Comment by rebron** [comment] 2021-08-19 22:13
Hi @limengyu1990 For now we offer the same translation solution as Google via their Google Translate extension, you can get that here. We're working on our own translate service but we are addressing in a separate issue.
https://github.com/brave/brave-browser/issues/10302

**Comment by rebron** [comment] 2021-08-19 22:14
Closing as duplicate of #10302

**Closed by rebron** 2021-08-19 22:14 UTC
