### ISSUE TITLE
Support importing tabs from legacy Brave (Muon)

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#998] opened 2018-09-07 02:07 UTC
This would make migration almost completely painless.

**Comment by garrettr** [comment] 2018-11-28 21:31
I'm working on importing pinned sites right now and have run into a design problem that doesn't have an obvious solution. The problem is b-l and b-c handle pinned sites differently: pinned sites are global in b-l, but they are per-window in b-c.

Options for how to handle this:
1. During import, inject pinned sites into each imported window at the beginning of the tab strip.
    - Pros: user gets identical tab layout in transition from b-l to b-c
    - Cons: this is cosmetic at best. The tabs will all be distinct, and their state will not be maintained across windows as it is in b-l, because that is not how pinned sites work in b-c. This might annoy users who are initially expecting the old behavior, to find only a mirage.
2. Create a new window to hold just the pinned sites.
3. Something else I haven't thought of?

**Comment by bsclifton** [comment] 2018-11-28 21:46
How about option 3 - import the pinned tabs ONLY to the FIRST window 😄

**Comment by bsclifton** [comment] 2018-11-30 04:20
Fixed with https://github.com/brave/brave-core/pull/981 😄 

I renamed this issue (so it reflects that import only happens for Muon Brave) and created a more general issue https://github.com/brave/brave-browser/issues/2309

**Closed by bsclifton** 2018-11-30 04:20 UTC
Labels: QA/Yes, feature/importer

**Comment by LaurenWags** [comment] 2018-12-03 18:19
@garrettr @bsclifton what's the expected result if you had pages like 'about:brave' or 'about:preferences#payments' opened in muon? When those pages are imported to b-c I see the below. (note, about:history seems to have correctly migrated to brave://history)
<img width="1158" alt="screen shot 2018-12-03 at 1 18 25 pm" src="https://user-images.githubusercontent.com/28145373/49392963-03c26e00-f6fe-11e8-9139-f11e03152891.png">

**Comment by LaurenWags** [comment] 2018-12-05 18:46
@garrettr @bsclifton if I import a muon profile with a bunch of tabs (think 4 windows approx 100 tabs in each window), I beachball for a few seconds and then the fans on my mac start to kick on. it looks like we're loading all tabs simultaneously after import. Subsequent launches of b-c seem to be ok (no fan action) and when I click on a tab that's when it loads. Is this expected? cc @kjozwiak

**Comment by bsclifton** [comment] 2018-12-05 20:18
Per discussion, some waiting is OK- but the import should be happening async

@LaurenWags has logged https://github.com/brave/brave-browser/issues/2374 to address the issue 😄 👍

**Comment by btlechowski** [comment] 2018-12-05 21:10
Verification Passed on

Brave | 0.57.16 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7

Migrated from muon v0.25.201
- normal tab was imported
- private tab was ignored
- private tab with tor was ignored
- session tab was imported as normal tab
- multi windows were imported.
- multi tabs were imported, but slow with 20+ tabs (https://github.com/brave/brave-browser/issues/2374). The more the tabs the worse it is as all tabs are loaded concurrently.
- pinned tabs were imported as pinned tab
