### ISSUE TITLE
Wrong time on New Tab Page

### ISSUE THREAD

**Issue by damagicalcat** [brave/brave-browser#13669] opened 2021-01-20 03:39 UTC
## Description 

Time of brave is different from current time

## Steps to Reproduce
it just happens, i did nothing to reproduce it

## Actual result:

![Hkc3pwrFvx](https://user-images.githubusercontent.com/167821/105250555-cf54da80-5b2e-11eb-8d51-67026bb9cf61.jpg)

as you can see, the time on brave is different from my system time

## Expected result:
both times to be the same

## Brave version (info found on brave://version)

Brave | 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2004 (Build 19041.746)
JavaScript | V8 8.8.278.14
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36

**Comment by bsclifton** [comment] 2021-01-20 22:17
Related https://github.com/brave/brave-browser/issues/7951

**Comment by bsclifton** [comment] 2021-01-20 22:20
@damagicalcat has this always been a problem? (ex: are you an existing Brave user and this used to work?)

Wondering if this is a long-standing issue (ex: as seen in https://github.com/brave/brave-browser/issues/7951) or if this is a new bug because of Chromium 88 which was included in our 1.19 version update

**Comment by GeetaSarvadnya** [comment] 2021-01-21 06:38
Unable to reproduce the issue on Clean/Upgraded profile in Windows 10 x64. @damagicalcat Could you provide the STR to reproduce the issue?

Clean profile: `1.19.86`
![image](https://user-images.githubusercontent.com/38657976/105301406-0edbff00-5be1-11eb-83bc-7e4024d30fbd.png)

Upgraded profile: `1.18.78 to 1.19.86`
![image](https://user-images.githubusercontent.com/38657976/105301786-27e4b000-5be1-11eb-9838-c950fd192ce2.png)

**Comment by bsclifton** [comment] 2021-01-21 06:53
What time zone are you in @damagicalcat?

@GeetaSarvadnya I wonder if there's a difference if you switch between 12 hour clock and 24 hour

**Comment by damagicalcat** [comment] 2021-01-22 02:55
I am in pst/pdt

**Comment by luisman10** [comment] 2021-01-26 19:37
I have the same issue, I don't know if i could modify that clock.
![image](https://user-images.githubusercontent.com/78046615/105895850-1b1fec00-6027-11eb-9454-71734470cbb1.png)

**Comment by bsclifton** [comment] 2021-01-26 22:11
Per user `Delhills` on https://community.brave.com/t/my-brave-is-showing-the-wrong-time/197973/15 a work-around seems to be:
> To everyone having this problem. I changed my windows timezone to some random one and then again my actual timezone and it fixed this error. Try it.

**Comment by bsclifton** [comment] 2021-01-27 19:51
Upstream fix coming to trunk; will likely be hotfixed into Chromium update for 88 / 89

**Comment by damagicalcat** [comment] 2021-01-28 01:34
changing my windows time didn't work

Also, my brave's browser time is in GMT.

**Comment by bsclifton** [comment] 2021-02-03 08:00
This should be fixed with https://github.com/brave/brave-browser/pull/13915 and https://github.com/brave/brave-core/pull/7795 having been merged 😄

**Closed by bsclifton** 2021-02-03 08:00 UTC
Labels: Chromium/reported upstream, Chromium/waiting upstream, OS/Desktop, OS/Windows, bug, feature/new-tab

**Comment by bsclifton** [comment] 2021-02-03 08:10
Actually - found a test plan we can use; updated original post and marked as `QA/Yes` 😄 Will try test plan myself here in just a moment

**Comment by GeetaSarvadnya** [comment] 2021-02-03 12:36
Verification passed on

```

Brave | 1.19.90 Chromium: 88.0.4324.146 (Official Build) (64-bit)
-- | --
Revision | 406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}
OS | Windows 10 OS Version 2004 (Build 19041.746)

```

Verified the test plan from the description

- Reproduced the issue in 1.19.86

![image](https://user-images.githubusercontent.com/38657976/106747252-aa418b00-6649-11eb-928a-f2e59eaee8b9.png)

NTP clock is different from system time
![image](https://user-images.githubusercontent.com/38657976/106747887-7ca91180-664a-11eb-9b94-766ce48d7ae7.png)


Upgraded profile to 1.19.90 and ensured Time in NTP is displayed same as system time
![image](https://user-images.githubusercontent.com/38657976/106747567-16bc8a00-664a-11eb-8e59-9e6a56124fac.png)


12- hours clock
![image](https://user-images.githubusercontent.com/38657976/106746604-c4c73480-6648-11eb-9766-f78f661e0751.png)

24 - hour clock
![image](https://user-images.githubusercontent.com/38657976/106746748-f2ac7900-6648-11eb-8b11-94797bdedc98.png)
