### ISSUE TITLE
Brave beta 0.55.10 crashes frequently

### ISSUE THREAD

**Issue by linuxlover** [brave/brave-browser#1327] opened 2018-09-27 21:00 UTC
This browser crashes frequently and when I open again it shows option to restore earlier tabs. But again crashes.
Most frequently when using GMail and happens on other websites as well.
Guess this is still preview.
Thanks

**Comment by Miyayes** [comment] 2018-09-27 22:50
+3 reproductions of this in the community (Windows).

@btlechowski suggests it is related to #1326. Some users replicated 1326 quite identically.

Temporary solution from @btlechowski is to have the user disable Brave Rewards.

**Comment by srirambv** [comment] 2018-09-28 00:27
We can close this issue in favour of #1326 since others users reported the same steps causing crash. 

@linuxlover Please reopen the issue if you dont have Rewards enabled and still crashing.

**Closed by srirambv** 2018-09-28 00:27 UTC
Labels: crash, need-more-info
