### ISSUE TITLE
about:gpu log shows alot of errors

### ISSUE THREAD

**Issue by thepcwiz101** [brave/brave-browser#3160] opened 2019-01-30 12:52 UTC
## Description 

My PC is a toshiba sattelite c55d-b5102 laptop that has 4 GB of ram and a Amd a8-6410 APU (notice an apu is basically a cpu and gpu on one chip.) I have the latest amd drivers also and i can confirm that this occurs in older versions of the driver as well so that rules out a driver issue. I also have graphical issues from time to time especially on youtube. ALso on youtube videos tend to drop frames even when videos are set to low resolution and 60 fps video is disabled (via extension) Brave version is: 0.58.21 and it is installed on a windows 10 system. Link to log: https://pastebin.com/quw3qErA

## Steps to Reproduce

notice this may only be related to my specific hardware If anyone else is having the same issue please comment below.
   1. Use the browser. (using facebook and youtube for example) 
   2. Goto about:gpu

## Actual result:

Tons of errors (listed in log)

## Expected result:
Only a "GpuProcessHostUIShim:" should show.

## Reproduces how often: 

Everytime

## Brave version (brave://version info)

Listed in description

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
I haven't used the dev/beta builds so i cannot answer
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 
The issue is reproduceable on the latest version of chrome. 72.0.3626.81
### Additional Information

Any updates will be posted in the comments.

**Comment by srirambv** [comment] 2019-01-30 12:58
Can you try disabling hardware acceleration from advance settings and check if it resolves?

**Comment by thepcwiz101** [comment] 2019-01-30 13:02
i tested disabling hardware acceleration on google chrome and i get new errors. im going to test brave also.

**Comment by thepcwiz101** [comment] 2019-01-30 13:07
Data exported | 2019-01-30T13:04:59.195Z
-- | --
Chrome version | Chrome/71.0.3578.98
Operating system | Windows NT 10.0.17763
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/15234034d19b85dcd9a03b164ae89d04145d8368/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/15234034d19b85dcd9a03b164ae89d04145d8368/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | f2ed299569c0
2D graphics backend | Skia/71 7469a9341afab19271b8ef07af5c16a0f2c4ccc1-
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-chrome-google-url-tracking-client --disable-domain-reliability --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave,AutofillServerCommunication,UnifiedConsent --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --no-pings --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave,AutofillServerCommunication,UnifiedConsent --flag-switches-begin --flag-switches-end

**Comment by thepcwiz101** [comment] 2019-01-30 13:10
This shows up in my log after disabling hardware acceleration. It still doesn't solve the youtube lag problems sadly and youtube used to run really well a few years ago even on my old desktop pc that is weaker than my laptop.
[5124:6176:0130/070408.088:WARNING:ipc_message_attachment_set.cc(49)] : MessageAttachmentSet destroyed with unconsumed attachments: 0/1

**Comment by thepcwiz101** [comment] 2019-01-30 13:35
Update: disabling hardware acceleration hurts performance even worse. Youtube videos drop alot of frames on both the latest stable brave and latest google chrome. When hardware acceleration is enabled however videos tend to perform better but occasionally after switching tabs and browsing other sites then returning to the tab with the video the video has to be rendered again and this is when issues start to happen. There was one point i had a green screen where the video used to be and it went away after pressing play again.

**Comment by srirambv** [comment] 2019-01-30 15:53
Since its also reproducing on the latest version of Chrome, it could be an upstream issue and something that would be fixed on the next upgrade

**Comment by thepcwiz101** [comment] 2019-01-31 03:40
@srirambv On chrome 72 i notice the errors are less frequent and videos don't lag as bad anymore with hardware acceleration enabled.

**Comment by thepcwiz101** [comment] 2019-02-05 01:07
@srirambv  Update: I have installed firefox and it is working as a workaround for the issue i am experiencing for the meantime. I rarely experience frame drops on firefox. I guess my hardware is just not working correctly on google chrome for whatever reason. It's most likely due to changes done in the last couple of years.

**Comment by thepcwiz101** [comment] 2019-02-20 15:33
![image](https://user-images.githubusercontent.com/31826503/53103046-78819900-34f2-11e9-9a87-03192e6d8dda.png)
No videos or anything that requires alot of gpu usage and the cpu usage by the gpu process is above 30%

**Comment by thepcwiz101** [comment] 2019-03-05 20:59
Update 2: latest chrome version does not solve problem and i have also tried the latest dev version of chrome also which doesn't solve the problem either. I reported the issue many times to google ever since chrome 69 and still no solution.

**Comment by thepcwiz101** [comment] 2019-03-08 06:26
Update 3: After i got an update for windows 10 a few days ago these issues are well less noticeable even on google chrome. Reinstalling brave yields an even higher boost of performance. I still get about:gpu errors however.

**Comment by thepcwiz101** [comment] 2019-03-13 11:55
Well bad thing i found is google chrome's implementation of hardware accelerated webgl 2 causes these errors but webgl is fine.

**Comment by thepcwiz101** [comment] 2019-03-14 20:02
Debug code from a youtube video:
`{
  "ns": "yt",
  "el": "detailpage",
  "cpn": "OWzxq9sxqDIAbr7D",
  "docid": "ogxbXPG5T5A",
  "ver": 2,
  "referrer": "https://www.youtube.com/feed/subscriptions",
  "cmt": "519.318",
  "ei": "IrCKXPi2CoOrkATUx5wQ",
  "fmt": "136",
  "fs": "0",
  "rt": "623.951",
  "of": "GC6OCn1lTVgpgJyrp2hYjw",
  "euri": "",
  "lact": 5,
  "cl": "238138647",
  "mos": 0,
  "state": "8",
  "vm": "CAEQABgE",
  "volume": 100,
  "subscribed": "1",
  "c": "WEB",
  "cver": "2.20190313",
  "cplayer": "UNIPLAYER",
  "cbr": "Chrome",
  "cbrver": "73.0.3683.75",
  "cos": "Windows",
  "cosver": "10.0",
  "hl": "en_US",
  "cr": "US",
  "len": "609.849",
  "fexp": "23710476,23736685,23744176,23751767,23752869,23755886,23755898,23758087,23760558,23761607,23762649,23777630,23780478,23784514,23785334,23785835,23788853,23789671,23790938,23791116,23791632,23791649,23792876,23794282,23794415,23794458,23795650,23796190,23797359,23797553,23797553,23797625,23798019,23798241,23801087,9424417,9449243,9471239",
  "feature": "atom-subs-u",
  "afmt": "140",
  "vct": "519.318",
  "vd": "609.849",
  "vpl": "0.000-519.318,",
  "vbu": "0.000-592.000,",
  "vpa": "0",
  "vsk": "0",
  "ven": "0",
  "vpr": "1",
  "vrs": "4",
  "vns": "2",
  "vec": "null",
  "vvol": "1",
  "totalVideoFrames": 15715,
  "droppedVideoFrames": 23,
  "lct": "519.207",
  "lsk": false,
  "lmf": false,
  "lbw": "1140055.809",
  "lhd": "0.163",
  "lst": "0.000",
  "laa": "itag=140,type=3,seg=60,time=599.1-609.1,off=0,len=161644,end=1",
  "lva": "itag=136,type=3,seg=110,time=586.6-592.0,off=0,len=943144,end=1",
  "lar": "itag=140,type=3,seg=60,time=599.1-609.1,off=0,len=163438.8462585034,end=1",
  "lvr": "itag=136,type=3,seg=112,time=597.3-602.6,off=0,len=1539903.75,end=1",
  "lvh": "r4---sn-q4flrner",
  "lab": "0.000-609.059,",
  "lvb": "0.000-592.000,",
  "ismb": 1240000,
  "relative_loudness": "-10.849",
  "optimal_format": "720p",
  "user_qual": "hd720",
  "debug_videoId": "ogxbXPG5T5A",
  "0sz": false,
  "op": "",
  "yof": false,
  "dis": "",
  "gpu": "ANGLE_(AMD_Radeon(TM)_R5_Graphics_Direct3D11_vs_5_0_ps_5_0)",
  "cgr": true,
  "debug_playbackQuality": "hd720",
  "debug_date": "Thu Mar 14 2019 14:59:13 GMT-0500 (Central Daylight Time)"
}`

**Comment by thepcwiz101** [comment] 2019-04-11 15:28
Well looks like google chrome on solus os (linux distro) plays videos with no lag. This issue seems to be a windows 10 issue also alongside an aged AMD APU. I assume the only way to solve the problem is getting a new pc or downgrading to windows 7 (very insecure especially after this year but it is less gpu heavy from my testing last fall.)

**Closed** 2019-04-11 16:00 UTC
Labels: gpu/driver, need-more-info, waiting upstream
