### ISSUE TITLE
[Feature Request]: Allow Custom thumbnail images on Top Sites tiles

### ISSUE THREAD

**Issue by i7phillip** [brave/brave-browser#27623] opened 2023-01-03 21:36 UTC
I know this has been asked before but that thread is a year and a half old and has not had any responses. I would really like to be able to add a custom thumbnail image to the 'Top Sites' tiles. This is allowed in Opera, Firefox and Edge. The example below is from Firefox:

![image](https://user-images.githubusercontent.com/100315674/210444666-79b16dcf-9e86-454c-94aa-6f5e45e306f2.png)

Brave uses the website's favicon which gets distorted on the tiles or if the site does not have a favicon, then it doesn't really help identify the page quickly. (Example below)

![image](https://user-images.githubusercontent.com/100315674/210445083-81908546-7c96-4721-9aad-34a2dc6ccd04.png)

**Comment by rebron** [comment] 2024-06-11 16:38
Closing as dupe of #15371

**Closed by rebron** 2024-06-11 16:38 UTC
Labels: feature/new-tab, priority/P4, QA/Yes, release-notes/include, feature-request, OS/Desktop
