### ISSUE TITLE
Clock Not visible on new Tabs

### ISSUE THREAD

**Issue by pantharshit007** [brave/brave-browser#41282] opened 2024-09-28 06:19 UTC
### Description

So previously there is a clock whenever we open a new tab but now its not visible tried to turn it on and off multiple times but no result.

### Steps to reproduce

1. No steps needed 
2. Its not working now

### Actual result

current:
![image](https://github.com/user-attachments/assets/8d2a3efe-a059-4435-8cb6-037f418cd391)

![image](https://github.com/user-attachments/assets/69a5f076-2068-4f99-8e34-2795e1faf435)

### Expected result

Clock should be visible

### Reproduces how often

No steps to reproduce

### Brave version (brave://version info)

1.70.119 Chromium: 129.0.6668.70 (Official Build) (64-bit) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by bsclifton** [comment] 2024-09-30 02:24
Thanks for reporting! Closing as a duplicate of https://github.com/brave/brave-browser/issues/41226

**Closed by bsclifton** 2024-09-30 02:24 UTC
Labels: OS/Desktop
