### ISSUE TITLE
Link to Chrome Beta in the brave://flags/ Page

### ISSUE THREAD

**Issue by blackneuron** [brave/brave-browser#36888] opened 2024-03-18 04:31 UTC
## Description 
When you are on the flags page there is text in the header that links to Chrome.
Is says the following:
"Interested in cool new Chrome features? Try our [beta channel](https://chrome.com/beta)."

## Steps to Reproduce
   1. Open brave://flags/ or chrome://flags/
   2. Look at the last line under the warning message.

## Actual result:
![image](https://github.com/brave/brave-browser/assets/1899346/298c0b9a-de1d-463e-9b64-dae35b48161d)

## Expected result:
I would expect this to say Brave and link to the Brave Beta Download.

## Reproduces how often: 
Very easily.

## Brave version (brave://version info)
1.63.174 Chromium: 122.0.6261.128 (Official Build) (64-bit) 

## Version/Channel Information:
I have only tried this in the main release channel.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
    - No
- Does the issue resolve itself when disabling Brave Rewards? 
    - No
- Is the issue reproducible on the latest version of Chrome?
    - Yes

## Miscellaneous Information:
I am assuming this is something that cannot be changed, but I thought it was weird to have tags that have Brave in them and a Chrome link at the top.

**Comment by rebron** [comment] 2024-03-18 18:17
Closing as dupe of https://github.com/brave/brave-browser/issues/36803 Will be fixed with 1.64.x.

**Closed by rebron** 2024-03-18 18:17 UTC
Labels: OS/Desktop
