### ISSUE TITLE
Profile removed but ads still received

### ISSUE THREAD

**Issue by nipa-it** [brave/brave-browser#9894] opened 2020-05-22 10:28 UTC
Hi all,

## Description 
Even if I remove any new profile (with Brave Rewards activated)  created I keep receiving ads of those profiles.

## Steps to Reproduce
1. Create a new user profile, enable brave rewards
2, Delete new profile
3. Wait the ad notification

## Expected result:
Not to receive multiple notification if profiles are deleted

## Reproduces how often: 
Easy to reproduce.

## Brave version (brave://version info)
Brave Browser 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

**Comment by bsclifton** [comment] 2020-05-22 17:04
cc: @tmancey

**Comment by nipa-it** [comment] 2020-05-23 07:12
It appeared to be solved after restart of Brave Browser (without reboot system)

**Comment by tmancey** [comment] 2020-05-25 22:48
@nipa-it @bsclifton This has been resolved with https://github.com/brave/brave-browser/issues/7441, apologies for the inconvenience

**Comment by tmancey** [comment] 2020-05-25 22:49
Duplicate of https://github.com/brave/brave-browser/issues/7441

**Comment by bsclifton** [comment] 2020-05-29 07:28
I think we forgot to close this - closing. Please re-open if I was mistaken 😄

**Closed by bsclifton** 2020-05-29 07:28 UTC
Labels: bug, duplicate, feature/ads
