### ISSUE TITLE
Starting Brave hurts my eyes

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#13660] opened 2021-01-19 17:55 UTC
Have you searched for similar issues? Yes.
 
## Description 
For many years I've had this constant battle of trying to adjust the screen brightness and recently I've starting to increase the brightness to essentially become accustomed to how the majority of users work. One thing that is honestly frustrating and genuinely hurts when using Brave though not excruciatingly painful, is the initial startup of the browser and that white flash that follows it. I suppose the white flash is also persistent when creating any type of new window with Brave as well. 

I wondered why I didn't issue something about this before and I realised this has always been an issue with Brave and whenever I started and start Brave, I've always looked to the side and sometimes closed my eyes.

## Steps to Reproduce
Start a fresh browser or create a new window

## Actual result:
White flash.

## Expected result:
Make it significantly easier on the eyes without bringing delays to the browser experience 

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (64-bit) (openSuse)

## Miscellaneous Information:
I may be wrong but I believe this was a major issue with the Muon version and brave did temporarily fix this but there were also a couple of additional features to the Muon version that made page viewing easier. I can't remember them clearly but I think page preview was one of them.

**Comment by rebron** [comment] 2021-05-28 16:53
Closing as dupe of #16078 which has more detail of the issue.

**Closed by rebron** 2021-05-28 16:53 UTC
Labels: OS/Desktop, OS/Linux, priority/P5
