### ISSUE TITLE
Add option to bypass local IP warning for AI models

### ISSUE THREAD

**Issue by berry-13** [brave/brave-browser#39679] opened 2024-07-10 22:26 UTC
### Platforms

all

### Description

I'm trying to use a local server with Ollama on my LAN, but I'm running into a problem. It's recognizing my local IP as external, which is giving me a security warning. Can you guys add an option to disable this warning or even better, recognize when a link is local (like 192.168.1.1, 10.0.1.1)? That would be super helpful!

**Comment by stephendonner** [comment] 2024-07-10 22:29
thanks for logging; this is a duplicate of https://github.com/brave/brave-browser/issues/39627

**Closed by stephendonner** 2024-07-10 22:29 UTC
Labels: feature-request

**Comment by Asizdhung** [comment] 2024-07-10 22:30
10.0.9.250

**Comment by Asizdhung** [comment] 2024-07-10 22:31
My ip
