### ISSUE TITLE
Browser crashes when ad notification clicked on

### ISSUE THREAD

**Issue by maikelmclauflin** [brave/brave-browser#2970] opened 2019-01-15 16:47 UTC
## Description 

brave crashes after clicking on notification for ad

## Steps to Reproduce

   1. wait for ad to show
   2. click on notification
   3. repeat until crash

still investigating about what may cause crash. could be 
1) multiple profiles open / cross opening ad
2) certain tabs open

## Actual result:

brave crashes

## Expected result:
brave should open tab

## Brave version (brave://version info)

Version 0.60.13 Chromium: 72.0.3626.53 (Official Build) dev (64-bit)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bridiver** [comment] 2019-01-15 22:45
Can you make sure the crash report is submitted in chrome://crashes and post the remote crash id?

**Comment by kjozwiak** [comment] 2019-01-16 02:17
@maikelmclauflin once you submit the crash report, you should see something similar to the following:

<img width="714" alt="screen shot 2019-01-15 at 9 15 24 pm" src="https://user-images.githubusercontent.com/2602313/51222230-d676fb80-190a-11e9-98bd-0e4204c8242a.png">

Once you receive a `Uploaded Crash Report ID` after submitting, @bridiver can take a look 👍

**Comment by kevinlawler** [comment] 2019-01-18 16:36
Neither Michael nor I can repro on latest. It's possible this was fixed by some large passes which fixed other bugs. Closing for now, we can re-open if this reappears or we get a better handle on what's causing it.

**Comment by srirambv** [comment] 2019-01-29 10:52
Marking issue to `0.61.x` since https://github.com/brave/brave-core/pull/1361 is assigned to `0.61.x`. @bridiver does the fix require QA verification?

**Comment by Liunkae** [comment] 2019-01-30 03:16
Just ran into this crash. I clicked "View" on a Brave Rewards ad, and the entire browser crashed. I had one private window with one tab open at the time it crashed.

Brave | 0.61.2 Chromium: 72.0.3626.71 (Official Build) dev(64-bit)
Revision | f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}
OS | Mac OS X

From brave://crashes:
Uploaded Crash Report ID 6d4f2c9b58bdd1a6 (Local Crash ID: f1445443-5e45-40d1-8d37-2497c510857e)
Crash report captured on Tuesday, January 29, 2019 at 9:06:48 PM, uploaded on Tuesday, January 29, 2019 at 9:06:49 PM

Crash log:
[Crash.txt](https://github.com/brave/brave-browser/files/2810727/Crash.txt)

**Comment by Liunkae** [comment] 2019-01-30 03:36
It just crashed again when I had one private window with one tab open. It did not crash when I had one normal window with one tab open.

So, STR:
1. Turn on Brave Rewards ads. Change "Maximum number of ads displayed" to "5 per hour" to shorten the amount of time you have to wait.
2. Open a private window
3. Close any other normal windows.
4. Wait for an ad to appear.
5. Click the View button on the notification.

**Comment by maikelmclauflin** [comment] 2019-01-30 16:37
that's interesting. mine is happening with no private tabs.

**Comment by tmancey** [comment] 2019-02-01 14:42
@maikelmclauflin @Liunkae Strange as I am not seeing this issue but I am on 0.62 (master)

**Comment by tmancey** [comment] 2019-02-01 14:49
Which appears to be related to Brave Shields ```8   libchrome_dll.dylib                 0x000000011673f052 brave_shields::HTTPSEverywhereService::GetHTTPSURLFromCacheOnly(GURL const*, unsigned long long const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 242
9```

**Comment by bridiver** [comment] 2019-02-01 20:53
@maikelmclauflin stack dump without symbols isn't useful. Please go to `chrome://crashes` and post the crash id

**Comment by bridiver** [comment] 2019-02-02 00:33
https://github.com/brave/brave-core/pull/1546 fixes an issue with httpse that is likely the cause of the stack trace that @tmancey posted. There was definitely a problem in httpse, but not sure if it is the full fix for this or not

**Comment by maikelmclauflin** [comment] 2019-02-03 18:20
hey @bridiver here are the links: ```https://stats.brave.com/dashboard#crash/5c4b3d0d7eec89001f81e3a0
https://stats.brave.com/dashboard#crash/5c4b2e42d80b31001f402e2f
https://stats.brave.com/dashboard#crash/5c477e94e70c50001f3c0bb9
https://stats.brave.com/dashboard#crash/5c4763cbe70c50001f3b277a
https://stats.brave.com/dashboard#crash/5c3fd51a5d2553001f118da6
https://stats.brave.com/dashboard#crash/5c3f4e8535ed13001fd23713```

**Closed** 2019-02-04 17:50 UTC
Labels: bug, crash, feature/shields, priority/P1

**Comment by srirambv** [comment] 2019-02-12 12:39
@bridiver @tmancey could you please add a test plan if this requires QA verification?

**Comment by kjozwiak** [comment] 2019-02-14 04:24
@bridiver @tmancey should we use the STR/Test Case from https://github.com/brave/brave-browser/issues/3208 to verify this as they seem related? Is there any particular cases QA should go through?

**Comment by btlechowski** [comment] 2019-02-18 21:59
Verification passed on 

Brave | 0.60.29 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 7

I have been clicking on ads notifications through the weekend. No crashes.
