### ISSUE TITLE
[Android]Feature suggestion:- Import the disable 'AMP feature' from kiwi browser.

### ISSUE THREAD

**Issue by ShockRocky** [brave/brave-browser#9336] opened 2020-04-20 16:58 UTC
## Description 

The kiwi mobile browser which is now open source has unique features when compared to other mobile browsers, such as native night mode, extensions support, etc. But, the best unique privacy feature imo that kiwi has is the disable 'AMP feature'.

From the website:- 

"DISABLE AMP
Tired of getting those poorly laid out, annoying and hard to share AMP pages every time you click on a search result? Just go to options ( ⋮ ) -> Settings -> Privacy and enable the Remove AMP checkbox. "

Source:- https://kiwibrowser.com/features/

It would be nice to see it implemented, especially in the mobile browser where people, for now, can't install extensions which can achieve the same functionality, such as 'redirect amp to html'.

Similar issues:-

1) https://github.com/brave/brave-browser/issues/9312

2)https://github.com/brave/brave-browser/issues/8720

**Comment by DragoCubed** [comment] 2020-05-26 14:58
#7366

**Comment by Poopooracoocoo** [comment] 2020-11-01 01:51
@srirambv could you please close this as a dupe of #7366?

**Comment by srirambv** [comment] 2020-11-02 02:11
Dupe of #7366

**Closed by srirambv** 2020-11-02 02:11 UTC
Labels: OS/Android, feature-request, feature/global-settings
