### ISSUE TITLE
[VPN] Crash: System Billing API 

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#23064] opened 2022-05-25 23:00 UTC
## Description 
The app crashes somewhere in a system billing API `com.android.billingclient.api.SkuDetails.getPrice`

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment] 2022-05-25 23:41
Might be duplicate of https://github.com/brave/brave-browser/issues/23037

**Comment by kjozwiak** [comment] 2022-05-26 03:37
> Might be duplicate of #23037

@bsclifton lets close this one off. I'm pretty sure it's a duplicate of https://github.com/brave/brave-browser/issues/23037 👍

**Closed by kjozwiak** 2022-05-26 03:37 UTC
Labels: OS/Android
