### ISSUE TITLE
Should only show at most 1x Rewards CATPCHA

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#41760] opened 2024-10-21 15:46 UTC
Every time the Rewards CAPTCHA is triggered, it adds a new notification in addition to the ones already on the screen. It should only show at most 1 Rewards CAPTCHA notification at any given time. 

![Image](https://github.com/user-attachments/assets/4ce56591-827b-43a3-b178-09d2eb9385ea)

@tmancey Can provide more specific details.

**Comment by tmancey** [comment] 2024-10-21 17:00
Steps to Reproduce:

- Fresh install
- Join Brave Rewards
- Wait for confirmation tokens to be refilled.
- Configure payment id to require a captcha to be completed
- Navigate to brave://rewards.
- Tap on "30-day Ads History".
- Use the Like or Dislike buttons to consume confirmation tokens.

Each time the confirmation tokens are refilled, a new CAPTCHA notification is displayed. Only a single notification should be displayed.

**Comment by emerick** [comment] 2024-10-22 13:41
@tmancey will try to confirm the repro steps on staging (we had an unrelated issue that prevented us from refilling our tokens on staging). I haven't been able to repro this myself yet, but it could potentially be a timing issue. We do have code to guard against showing more than multiple adaptive captcha notifications simultaneously (essentially, they share the same id and are stored in a map) and I stepped through it in the debugger to confirm that it does the right thing if I artificially try to show a second notification. We can move that code to be earlier in the flow, which may help.

**Comment by tmancey** [comment] 2024-10-22 13:48
@emerick speaking with @zenparsing recent changes to Rewards in beta and nightly may have also fixed the issue. I will work on the ability to reset token limits then hopefully we can reproduce. Thanks

**Comment by tmancey** [comment] 2024-11-08 12:06
Closing as cannot reproduce, likely resolved by changes from @zenparsing . Thanks

**Closed by tmancey** 2024-11-08 12:06 UTC
Labels: feature/rewards, priority/P2, QA/Yes, release-notes/exclude
