### ISSUE TITLE
Cyrillic font improvement

### ISSUE THREAD

**Issue by Simvolick** [brave/brave-browser#26510] opened 2022-11-03 16:28 UTC
## Steps to Reproduce

   1. Open a new tab while having a browser title screen enabled.

## Actual result:

<img width="542" alt="CleanShot 2022-11-03 at 19 26 13@2x" src="https://user-images.githubusercontent.com/53820652/199777776-b80d4a5f-379b-49b2-8655-3b52eb3e1a66.png">

## Expected result:
English font is just fine.

## Reproduces how often: 

Anytime you have Cyrillic font

## Brave version (brave://version info)

1.45.116 Chromium: 107.0.5304.91 (Official Build) (arm64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by diracdeltas** [comment] 2022-11-09 08:09
cc @petemill @boocmp - i thought this was fixed by https://github.com/brave/brave-core/pull/12933 ?

**Comment by diracdeltas** [comment] 2022-11-09 08:12
oh i see, https://github.com/brave/brave-core/pull/12933 is not in 1.45. @Simvolick probably updating to 1.46 beta will fix the problem for now.

**Comment by diracdeltas** [comment] 2022-11-09 08:19
closing as duplicate of https://github.com/brave/brave-browser/issues/4309

**Closed by diracdeltas** 2022-11-09 08:19 UTC
Labels: closed/duplicate, OS/Desktop
