### ISSUE TITLE
Brave crash when click sidebar button on toolbar On macOS Sonoma 14.0

### ISSUE THREAD

**Issue by lovebigbear** [brave/brave-browser#33324] opened 2023-09-29 08:52 UTC
## Description 

Brave crash after click sidebar button on toolbar On macOS Sonoma 14.0

## Steps to Reproduce

Brave crash after click sidebar button on toolbar On macOS Sonoma 14.0

## Expected result:

no crash

## Reproduces how often: 

everytime

## Brave version (brave://version info)

[Version 1.58.135 Chromium: 117.0.5938.140 (Official Build) (arm64)](https://brave.com/latest/)

**Comment by lovebigbear** [comment] 2023-09-29 10:43
before brave crash, I enable 3 experimental flags by brave://flags, [#chrome-refresh-2023](chrome://flags/#chrome-refresh-2023), [#chrome-webui-refresh-2023](chrome://flags/#chrome-webui-refresh-2023), [#cr2023-mac-font-smoothing](chrome://flags/#cr2023-mac-font-smoothing).

Now I restore these flags to their default settings, brave will not crash when click sidebar button on toolbar On macOS Sonoma 14.0

**Comment by rebron** [comment] 2023-09-29 21:56
cc: @simonhong In case folks have turned on the flag. I know we removed it in 1.60.x.

**Comment by rebron** [comment] 2024-03-13 16:22
Closing as dupe of https://github.com/brave/brave-browser/issues/36214 and fixed in 1.65.26

**Closed by rebron** 2024-03-13 16:22 UTC
Labels: crash, OS/macOS, OS/Desktop, feature/sidebar
