### ISSUE TITLE
Cannot edit "People" profiles after they are created

### ISSUE THREAD

**Issue by tggir1** [brave/brave-browser#4929] opened 2019-06-14 21:20 UTC
## Description 
After creating People, their names and pictures cannot be changed.

## Steps to Reproduce
   1. In the top right corner of Brave window, click the profile icon. In the drop-down, click on the profile at the very top 
   2. The general settings window then loads, but no options to edit the profile

## Actual result:
Settings page loads (brave://settings)

## Expected result:
Should load the profile settings page ( chrome://settings/manageProfile in current release of Google Chrome )

I believe Brave used to load this page properly in one of the release builds a couple months ago. Not sure when it stopped working, I just noticed today.

## Reproduces how often: 
Easily Reproduced.

## Brave version (brave://version info)
Brave | 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Mac OS X

## Version/Channel Information:

Only tested in Release on macOS.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by srirambv** [comment] 2019-06-14 21:39
Dupe of #4929

**Closed by srirambv** 2019-06-14 21:39 UTC
