### ISSUE TITLE
[Desktop] Extremely hard to tell if tab is private or Tor in new version

### ISSUE THREAD

**Issue by Qix-** [brave/brave-browser#2735] opened 2018-12-25 06:53 UTC
## Description

**Brave version:** Version 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)

In the new flashy Brave UI, it's almost impossible to tell if the tab is private or private with Tor. This is a severe downgrade from the old UI where it was at least easily recognizable at a glance.

This, along with #2734, make for a pretty sizable setback in Tor experience in Brave :/

## Design

- Differentiate Private Window from Private Window with Tor by changing tab and toolbar colors
- The color changes would also increase contrast between active and inactive tabs by darkening tab background and lightening active tab+toolbar
- Decrease contrast of tab separator: private window #3F3256, Private Window with Tor #5A5366
- Differentiate Private Window with a "Private Window" badge on the right edge of toolbar
- Differentiate Private Window with Tor with a "Private with Tor" badge on the right edge of toolbar and custom graphic on tab bar background

![image](https://user-images.githubusercontent.com/2388823/94304383-577df700-ff24-11ea-8dd9-68067ba71056.png)

Contrast ratio improves:

![image](https://user-images.githubusercontent.com/2388823/94309807-8056ba00-ff2d-11ea-88f7-afd5f3c58ffb.png)

![image](https://user-images.githubusercontent.com/2388823/94310510-9add6300-ff2e-11ea-98b6-3421a6f01244.png)

Contrast ratio improves:
![image](https://user-images.githubusercontent.com/2388823/94310530-a466cb00-ff2e-11ea-8a33-2326ae8b286d.png)

![image](https://user-images.githubusercontent.com/2388823/94495302-3cbab500-01a6-11eb-93dc-8b05842c0901.png)

Contrast ratio improves:

![image](https://user-images.githubusercontent.com/2388823/94309838-8cdb1280-ff2d-11ea-8901-f17fe562000b.png)

## Assets
Figma: https://www.figma.com/file/sS3l8tqUFxt54MEiBTalUI/Desktop-toolbar-and-menu?node-id=117%3A11091

## Notes
Follow up issue to https://github.com/brave/brave-browser/issues/8576

**Comment by srirambv** [comment] 2018-12-25 13:41
cc: @tomlowenthal @brave/design

**Comment by Qix-** [comment] 2018-12-28 14:18
Well in the old version you could see "tor" in the tab. That was helpful enough. You'd also see "connecting to tor" in the address bar.

However, I don't see any of that anymore which leads me to believe that I'm not actually connected, which gives me lots of anxiety (: especially since things feel faster to connect in the new brave, which generally **isn't** a good sign when dealing with Tor.

**Comment by tomlowenthal** [comment] 2019-01-11 18:13
In private windows with Tor, the word "Tor" is visible on the right, next to the menu button. On regular private windows, you see a pair of sunglasses there instead. But that's certainly not an easy way to tell windows apart at a glance, from menu bars, or so on.

**Comment by Smooey** [comment] 2019-03-18 20:58
Not sure if this was mentioned before or not, but going along with the TOR tab stuff, it's hard to tell which tab you're on or not because they're all dark colored. Current tabs maybe could be changed to different color or shade of color? Currently if you have 5 or more tabs open for a specific site, it's hard to figure out which one is opened or not. I was accidentally closing tabs I didn't want closed, then I couldn't just reopen last closed tabs.

**Comment by simonhong** [comment] 2020-11-03 06:52
@karenkliu Can you share each theme(dark/private/tor)'s hover color of location bar?

**Comment by karenkliu** [comment] 2020-11-03 18:47
@simonhong 

Location bar
- Dark Theme: no change
- Private Window: `#C6B3FF` 2px border
- Private Window with Tor: `#CFABE2` 2px border

Omnibox background color
- Dark Theme: `#181A21`
- Private Window: `#0B0724`
- Private Window with Tor: `#0B0724`

**Closed** 2020-11-25 10:25 UTC
Labels: QA/Yes, design, feature/private-browsing, feature/tor, priority/P4, release-notes/include

**Comment by LaurenWags** [comment] 2021-01-04 14:58
Questions sent to @rebron for clarification, marking as `QA/Blocked` for now

**Comment by karenkliu** [comment] 2021-01-08 19:15
I verified the designs on Windows and noted no color discrepancies between platforms.

Tested:

- MacOS Version 1.20.68 Chromium: 88.0.4324.51 (Official Build) nightly (x86_64)
- Windows Version 1.20.68 Chromium: 88.0.4324.51 (Official Build) nightly (64-bit)

**Comment by LaurenWags** [comment] 2021-01-08 21:44
Verified passed with

```
Brave | 1.19.79 Chromium: 87.0.4280.141 (Official Build) dev (x86_64)
-- | --
Revision | 9f05d1d9ee7483a73e9fe91ddcb8274ebcec9d7f-refs/branch-heads/4280@{#2007}
OS | macOS Version 10.15.7 (Build 19H15)
```

Confirmed visual differences between dark theme normal windows, private windows, and Tor windows.
Confirmed text on profile bubbles for Private and Tor windows as per https://github.com/brave/brave-core/pull/6912#issue-507378614.

`Dark theme example` | `Dark theme example`
----- | -----
<img width="1033" alt="Screen Shot 2021-01-08 at 4 37 28 PM" src="https://user-images.githubusercontent.com/28145373/104066975-4eadea00-51d0-11eb-8bb0-1972f1026798.png"> | <img width="1035" alt="Screen Shot 2021-01-08 at 4 37 17 PM" src="https://user-images.githubusercontent.com/28145373/104066979-4fdf1700-51d0-11eb-99c7-406bd4901cc1.png">

`Private window example` | `Private window example` | `Private window example`
----- | ----- | -----
<img width="1033" alt="Screen Shot 2021-01-08 at 4 37 47 PM" src="https://user-images.githubusercontent.com/28145373/104067037-6c7b4f00-51d0-11eb-8c6d-3addd1cf1dde.png"> | <img width="1035" alt="Screen Shot 2021-01-08 at 4 37 56 PM" src="https://user-images.githubusercontent.com/28145373/104067040-6e451280-51d0-11eb-8efe-d327d9f3de1c.png"> | <img width="1032" alt="Screen Shot 2021-01-08 at 4 38 09 PM" src="https://user-images.githubusercontent.com/28145373/104067046-6f763f80-51d0-11eb-96ad-951745fa428d.png">

`Tor window example` | `Tor window example` | `Tor window example`
----- | ----- | -----
<img width="1033" alt="Screen Shot 2021-01-08 at 4 38 32 PM" src="https://user-images.githubusercontent.com/28145373/104067094-86b52d00-51d0-11eb-9806-91063fa99ee0.png"> | <img width="1035" alt="Screen Shot 2021-01-08 at 4 38 40 PM" src="https://user-images.githubusercontent.com/28145373/104067099-887ef080-51d0-11eb-8434-76b50e22049b.png"> | <img width="1034" alt="Screen Shot 2021-01-08 at 4 38 47 PM" src="https://user-images.githubusercontent.com/28145373/104067100-89b01d80-51d0-11eb-83e9-1fefc45dbb89.png">

----------------------
