### ISSUE TITLE
The buttons should be customizable

### ISSUE THREAD

**Issue by mohistmen** [brave/brave-browser#7386] opened 2019-12-13 23:30 UTC
Well, what I want to do is just hide the "Bookmark this tab" button between the "Home" button and the address bar. Actually I almost don't use bookmark functions. I just need the "Home" button besides the address bar, without any buttons between them. Thanks

**Comment by bsclifton** [comment] 2020-01-13 07:27
Thanks for the suggestion, @mohistmen! I'm going to close this issue as a duplicate of https://github.com/brave/brave-browser/issues/774 and give that issue a bump on your behalf 😄

**Closed by bsclifton** 2020-01-13 07:27 UTC
Labels: duplicate
