### ISSUE TITLE
No ad notification on Gnome Desktop in Arch Linux

### ISSUE THREAD

**Issue by Digitalone1** [brave/brave-browser#13352] opened 2021-01-01 10:34 UTC
## Description 

I started to use Brave browser on Gnome Desktop in Arch Linux from two weeks. In this period I didn't get any ad notification while I started to use Brave on my Android phone from few days and I got many ad notifications. 

This behavior let me think notifications don't work on Gnome, but if I test them [here](https://www.bennish.net/web-notifications.html) I can see the Gnome popup on the desktop. So websites notifications work, but how to ensure Brave ads work too?

Maybe you could implement a little test utility like the one on that website, but specific to Brave ads. I also ensured that `libnotify` is installed and `#enable-native-notifications` is enabled in `brave://flags/` (these were the suggestions in similar issues I searched for). Anyway I'm still getting no ad notifications and I don't know if they are missing or the browser is trying to show them and the system miss something.

## Steps to Reproduce
   1. Just use Brave on Gnome in Arch Linux

## Actual result:
No ad notification in two weeks

## Expected result:
At least one ad notification in two weeks

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
I install the browser from `brave-bin` on [AUR](https://aur.archlinux.org/packages/brave-bin/). `cups` and `libnotify` as opt packages are installed, `libgnome-keyring` and `pepper-flash` are not. 

Version 1.18.77 Chromium: 87.0.4280.101

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Don't know.
- Can you reproduce this issue with the nightly channel? Don't know. 

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by stoneface919** [comment] 2021-01-03 00:40
It is actually reproducible on some arch based distributions using the Gnome Desktop Environment. I've tried Manjaro, Archbang and Arcolinux with no results whatsoever.

**Comment by Digitalone1** [comment] 2021-01-03 10:07
> It is actually reproducible on some arch based distributions using the Gnome Desktop Environment. I've tried Manjaro, Archbang and Arcolinux with no results whatsoever.

Well, it could be a Gnome or Arch Linux issue.

But since it seems to work on Gnome in other distributions, it's likely an issue related on Arch based system. Anyway the real problem here is Brave packaging not providing real information on what dependency is needed to work with their ad system. And this is bad also for investors which pays supposing the ads are showing, but they're not.

`libnotify` seems needed, but it's not stated [here](https://github.com/brave/brave-browser/wiki/Linux-Development-Environment). I have to know about it searching for issues on Google. Then not officially supporting Arch Linux is already a downside, relying on an AUR package which is made by a third party user. Maybe someone in Brave staff can make an account and do an officially supported package on AUR? So this browser is not deeply tested on Arch Linux and that's why issues like this appears.

Which are the dependencies to work with it? Could they be clearly specified in the future for all distributions? How could it be tested? Thanks.

**Comment by bsclifton** [comment] 2021-01-04 05:24
This might be expected - the Arch Linux build is not official. If its being built from source, they definitely don't have our API keys, etc needed to communicate with ads backend. If the Arch Linux build is just repackaging the Linux build, it should work

cc: @tmancey @jsecretan

**Comment by Digitalone1** [comment] 2021-01-04 08:34
> This might be expected - the Arch Linux build is not official. If its being built from source, they (package maintainers) definitely don't have our API keys, etc needed to communicate with ads backend. If the Arch Linux build is just repackaging the Linux build, it should work
> 
> cc: @tmancey @jsecretan

It's not built from source as you can see in the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=brave-bin).

It's just the `linux-amd64.zip` package extracted and placed under `/usr/lib/brave-bin/`.

**Comment by tmancey** [comment] 2021-01-04 18:41
@Digitalone1 Would you be willing to screen-share so I can help investigate the issue? Thank you

**Comment by Digitalone1** [comment] 2021-01-04 18:59
@tmancey I don't have any software to screen-share. At least I can provide screenshots.

Anyway, to test this issue would be better if someone of Brave devs installs Arch Linux of its system and run brave-bin browser shipped on AUR.

**Comment by tmancey** [comment] 2021-01-04 19:26
@Digitalone1 We use Zoom, and I can send a link if that helps via email if you reach out to me at tmancey@brave.com. Thanks

**Comment by Digitalone1** [comment] 2021-01-04 19:40
> @Digitalone1 We use Zoom, and I can send a link if that helps via email if you reach out to me at [tmancey@brave.com](mailto:tmancey@brave.com). Thanks

Sorry, I don't use Zoom, neither have time for it. You can test it on your own, it's not so difficult to install Arch Linux on a dedicated partition.

**Comment by austinbutler** [comment] 2021-01-07 10:54
Not sure if I am running into the same issue, in my case it seems I haven't received ads for quite a while and in `brave://rewards` it shows `Ads received this month: 0`.

Does that mean even if notifications were working I still wouldn't have seen any ads? Or is it possible that it's zero _because_ notifications aren't working?

**Comment by tmancey** [comment] 2021-01-08 12:50
@austinbutler Would you be willing to screen-share as I can then investigate the logs with your permission to find out the cause. Please do not send logs as these may contain private information. Thank you

**Comment by austinbutler** [comment] 2021-01-09 20:08
@tmancey sure, I will email you

**Comment by Digitalone1** [comment] 2021-01-19 20:58
I decided to uninstall the browser.

Weeks have passed, versions have changed, but the issue is still there, only sponsored images are working, no ad notifications are shown on Arch Gnome. 

Honestly, I don't like the browser very much, I prefer Firefox and combining it with an adblock is not very different from Brave. I wanted to try the Brave Reward project, but it's buggy and I think it never worked completely on Arch.

I know it could be Arch missing something, but you have to provide a list of dependencies. How can a distribution provide a fully working package if you don't tell which libraries are required to show your notification? 

Since you devs never tested on the system, neither provided a list of required dependencies (honestly, I don't have to know about libnotify for html5 notifications on a ticket issue, you should state it on github readme), I don't think it's worth keep trying it.

**Comment by tmancey** [comment] 2021-01-21 08:10
@Digitalone1 If ads are not shown advertisers are not charged. Could you please let me know the version of Arch Linux you are running. Thanks

**Comment by tmancey** [comment] 2021-02-10 12:31
Closing issue and will reopen if users report the issue has not been resolved.

**Comment by jalberto** [comment] 2021-03-15 14:18
This issue is not solved, it seems related to wayland

**Comment by bsclifton** [comment] 2021-03-15 16:52
@jalberto Wayland can be tracked with https://github.com/brave/brave-browser/issues/13866 - this is for Gnome 😄

**Closed** 2021-03-15 16:51 UTC
Labels: OS/Linux/arch, closed/wontfix, feature/ads, needs-investigation

**Comment by shanmukhateja** [comment] 2021-04-02 12:28
@tmancey if you're interested, I'd like to volunteer for screen-sharing.  I use Manjaro Linux which is technically Arch derivative and with GNOME+Wayland, I do not see ads.

**Comment by tmancey** [comment] 2021-04-04 07:56
@shanmukhateja If you could email me at tmancey@brave.com with available times, I am based in the United Kingdom. Thanks, Terry
