### ISSUE TITLE
Omnibar query gets selected after opening a new tab

### ISSUE THREAD

**Issue by dodas** [brave/brave-browser#4060] opened 2019-04-10 05:18 UTC
## Description 

After opening a new tab, query typed into omnibar gets selected after slight delay (about 0.5s).
This causes problem, because typed query is then overridden by following characters.

## Steps to Reproduce

   1. Open a new tab (either with keyboard shortcut, or with [+] button).
   2. Start typing something immediately, for example "brave browser".

## Actual result:

Text in omnibar ends up being "e browser" (or similar, depending on speed of typing).

## Expected result:
Query should be "brave browser".
Brave shouldn't trigger this delayed select and should allow typing immediately after opening new tab.

## Reproduces how often: 

Every time after opening a new tab.

## Brave version (brave://version info)

| Key | Value
| ----- | -------
| Brave | 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)
| Revision | `e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}`
| OS | Mac OS X version 10.14.3 (18D109)

### Reproducible on current release:
Same result on Brave Dev Channel v0.64.40.
I never had this issue with Chromium.

**Comment by cndouglas** [comment] 2019-04-11 00:23
Thanks for the report @dodas! This is a duplicate of #3756; feel free to subscribe to that issue for updates. Fortunately, the Brave team is currently working on this bug.

**Comment by dodas** [comment] 2019-04-11 03:10
Sorry for duplicate, it's hard to find..
Thanks!

**Closed** 2019-04-11 03:10 UTC

**Comment by cndouglas** [comment] 2019-04-11 03:28
No problem! I added this issue's title to that issue's comment thread. The keywords may make it easier for others to find in the future.
