### ISSUE TITLE
For some publishers attention not shown in BR Panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3789] opened 2019-03-19 19:38 UTC
## Description 

For some publishers attention not shown in BR Panel

## Steps to Reproduce

   1. Open brave 0.63.14
   2. Open youtube.com
   3. Open different publishers YT videos in different tabs ( I have opened YT videos in 6 tabs diff 
      publishers)
   4. Click on BR panel on each publisher
   5. Verify the Attention value in BR panel

## Actual result:

For some publishers attention not shown in BR Panel

![image](https://user-images.githubusercontent.com/38657976/54636210-f01ff500-4aab-11e9-9e3a-60b5b7b70056.png)

## Expected result:
Attention should be shown BR Panel for all publishers

## Reproduces how often: 

Intermittent issue
## Brave version (brave://version info)

Brave	0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
Revision	909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS	Linux

### Reproducible on current release: no
- Does it reproduce on brave-browser dev/beta builds?  Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by NejcZdovc** [comment] 2019-03-20 11:42
looks like dupe of https://github.com/brave/brave-browser/issues/3800

**Closed by NejcZdovc** 2019-03-20 11:42 UTC
Labels: QA/Test-Plan-Specified, QA/Yes, bug, feature/rewards
