### ISSUE TITLE
[Desktop] Feature Request : smaller or inobtrusive download status bar

### ISSUE THREAD

**Issue by didli** [brave/brave-browser#10377] opened 2020-06-19 16:58 UTC
## Description 
The Download Status bar that appears when downloading a file is a bit obtrusive and takes too much space, specifically its height (could be 30% ~ 40% what it is presently).   

## Steps to Reproduce
Everytime since its configured that way.

## Expected result:
An option that produces for a smaller, compact bar is enough. 
I don't think this should be default since visually impaired people would met difficulties with a smaller status bar.

## Brave version (brave://version info)
All that I know of.

**Comment by rebron** [comment] 2020-08-07 18:23
Thanks @didli. Closing this one as a duplicate of #1638

**Closed by rebron** 2020-08-07 18:23 UTC
Labels: duplicate
