### ISSUE TITLE
Brave Nightly keeps crashing after updating

### ISSUE THREAD

**Issue by Hongbo-Miao** [brave/brave-browser#12799] opened 2020-11-19 20:24 UTC
## Description 

My Brave Nightly just updated by itself. But now it keeps crashing a few seconds after I open it.

## Brave version (brave://version info)

Brave	1.19.21 Chromium: 87.0.4280.66 (Official Build) nightly (x86_64)
Revision	fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}
OS	macOS Version 10.15.7 (Build 19H15)
JavaScript	V8 8.7.220.25
Flash	(Disabled)
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Crash too fast, cannot try.
- Does the issue resolve itself when disabling Brave Rewards? Crash too fast, cannot try.
- Is the issue reproducible on the latest version of Chrome? No

**Comment by BxOxSxS** [comment] 2020-11-19 21:05
Can reproduce on Manjaro linux and Windows It does not crash with internet connection down or brave rewards off (it can be used to make temporally fix)
Log from terminal:
```libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[25456:25456:1119/220310.084371:ERROR:vaapi_wrapper.cc(541)] vaInitialize failed: unknown libva error
[25456:25456:1119/220310.089122:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[25429:25429:1119/220310.588986:ERROR:CONSOLE(0)] "Unrecognized Content-Security-Policy directive 'defaultframe-ancestors'.
", source: chrome://newtab/ (0)
Failed to parse JSON adblock resources: EOF while parsing a value at line 1 column 0
[25429:25429:1119/220311.309436:ERROR:sharing_service.cc(218)] Device registration failed with fatal error
[25456:25456:1119/220314.603960:ERROR:gl_surface_presentation_helper.cc(259)] GetVSyncParametersIfAvailable() failed for 1 times!
[25456:25456:1119/220318.530906:ERROR:gl_surface_presentation_helper.cc(259)] GetVSyncParametersIfAvailable() failed for 2 times!
[25456:25456:1119/220318.535377:ERROR:gl_surface_presentation_helper.cc(259)] GetVSyncParametersIfAvailable() failed for 3 times!
[bad_variant_access.cc : 44] RAW: Bad variant access
--2020-11-19 22:03:25--  https://cr.brave.com/
Załadowano certyfikat CA '/etc/ssl/certs/ca-certificates.crt'
Translacja cr.brave.com (cr.brave.com)... 199.232.193.7, 199.232.197.7
Łączenie się z cr.brave.com (cr.brave.com)|199.232.193.7|:443... połączono.
Żądanie HTTP wysłano, oczekiwanie na odpowiedź... 200 OK
Długość: 36
Zapis do: `/dev/fd/4'

     0K                                                       100% 1,91M=0s

2020-11-19 22:03:26 (1,91 MB/s) - zapisano `/dev/fd/4' [36/36]


Failed to get crash dump id.
Report Id: 76100000-cf79-6b
/usr/bin/brave-browser-nightly: linia 48: 25429 Przerwane               (zrzut pamięci) "$HERE/brave" "$@"```

**Comment by BxOxSxS** [comment] 2020-11-19 21:13
Same with 1.19.20 (i downgraded package for test)
Brave version: (brave://version info)
Brave 1.19.21 Chromium: 87.0.4280.66 (Official Build)
Revision fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}
OS Linux

JavaScript V8 8.7.220.25
Flash (Disabled)
User Agent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
Command /opt/brave.com/brave-nightly/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=PasswordImport,ReducedReferrerGranularity,DnsOverHttps,LegacyTLSEnforced,PrefetchPrivacyChanges,GlobalPrivacyControl,WebUIDarkMode,AutoupgradeMixedContent --disable-features=AutofillEnableAccountWalletStorage,AutofillServerCommunication,PrivacySettingsRedesign,AllowPopupsDuringPageUnload,VideoPlaybackQuality,TextFragmentAnchor,TabHoverCards,NotificationTriggers,SmsReceiver,SignedExchangeSubresourcePrefetch,SafeBrowsingEnhancedProtection,PasswordCheck,NetworkTimeServiceQuerying,IdleDetection --flag-switches-begin --enable-features=PasswordImport,ReducedReferrerGranularity,DnsOverHttps,LegacyTLSEnforced,PrefetchPrivacyChanges,GlobalPrivacyControl,WebUIDarkMode,AutoupgradeMixedContent,PDFViewerUpdate,TabGroups,TabGroupsCollapse --flag-switches-end

Path to execute file /opt/brave.com/brave-nightly/brave
Profile path /home/boss/.config/BraveSoftware/Brave-Browser-Nightly/Default

**Comment by lcdss** [comment] 2020-11-20 03:47
Same here on Arch Linux:

OS: Arch Linux x86_64 
Kernel: 5.9.9-zen1-1-zen

<details>
<summary>Logs</summary>
[5359:5359:1120/001020.762877:ERROR:vaapi_wrapper.cc(541)] vaInitialize failed: unknown libva error
[5359:5359:1120/001020.773948:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[5334:5483:1120/001021.152333:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[5334:5483:1120/001021.152606:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[5334:5483:1120/001021.152877:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[5334:5334:1120/001021.453300:ERROR:sharing_service.cc(218)] Device registration failed with fatal error
[5334:5334:1120/001023.354696:ERROR:CONSOLE(0)] "Unrecognized Content-Security-Policy directive 'defaultframe-ancestors'.
", source: chrome://newtab/ (0)
[bad_variant_access.cc : 44] RAW: Bad variant access
[5361:5366:1120/001029.023876:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
[5361:5366:1120/001029.024474:ERROR:broker_posix.cc(110)] Error sending sync broker message: Broken pipe (32)
[5361:5366:1120/001029.024710:ERROR:broker_posix.cc(110)] Error sending sync broker message: Broken pipe (32)
[5361:5366:1120/001029.024901:ERROR:broker_posix.cc(110)] Error sending sync broker message: Broken pipe (32)
[5361:5366:1120/001029.025070:ERROR:broker_posix.cc(110)] Error sending sync broker message: Broken pipe (32)
[5361:5366:1120/001029.025217:ERROR:broker_posix.cc(110)] Error sending sync broker message: Broken pipe (32)
[5361:5366:1120/001029.025353:ERROR:broker_posix.cc(110)] Error sending sync broker message: Broken pipe (32)
[5361:5366:1120/001029.025490:ERROR:broker_posix.cc(110)] Error sending sync broker message: Broken pipe (32)
[5361:5366:1120/001029.025972:ERROR:broker_posix.cc(110)] Error sending sync broker message: Broken pipe (32)
/sbin/brave-browser-nightly: line 48:  5334 Aborted                 (core dumped) "$HERE/brave" "$@"
<details>

**Comment by Hongbo-Miao** [comment] 2020-11-20 06:26
My Brave Nightly got updated again.

```
Brave | 1.19.22 Chromium: 87.0.4280.66 (Official Build) nightly (x86_64)
-- | --
Revision | fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}
OS | macOS Version 10.15.7 (Build 19H15)
JavaScript | V8 8.7.220.25
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
```

This time, it doesn't crash any more.

**Comment by bsclifton** [comment] 2020-11-20 06:36
I believe there was an issue that @tmancey had found and fixed; it should be resolved if you update to the latest version of Brave on Nightly. If you can't upgrade in-app (because it crashes), you'll likely have to reinstall from https://brave.com/download-nightly

I think we can close this - but can you confirm that 1.19.22 fixes the problem @lcdss @BxOxSxS ?

**Comment by BxOxSxS** [comment] 2020-11-20 07:51
@bsclifton Works fine for me on 1.19.23

**Closed** 2020-11-20 08:26 UTC
Labels: OS/Desktop, crash, needs-investigation
