### ISSUE TITLE
Import settings from other Brave profile fails

### ISSUE THREAD

**Issue by coleberhorst** [brave/brave-browser#5709] opened 2019-08-18 17:30 UTC
## Description 
In settings when you select import bookmarks and settings and choose another Brave profile, nothing happens.

## Steps to Reproduce
1. Change to a different User profile.
2. Go to settings <chrome://settings/importData>
3. Select Chrome Person 1
4. Click import with everything checked.

## Actual result:
No changes to history or bookmarks.

## Expected result:
Cookies, bookmarks and history should be automatically imported.

## Reproduces how often: 
Always

## Brave version (brave://version info)
```
Brave | 0.68.129 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1903 (Build 18362.295)
JavaScript | V8 7.6.303.29
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Command Line | "C:\Users\coleb\AppData\Local\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extensions-install-verification=enforce_strict --enable-features=NewExtensionUpdaterService,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,NetworkService,UnifiedConsent,TranslateUI --flag-switches-begin --flag-switches-end
Executable Path | C:\Users\coleb\AppData\Local\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\coleb\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | d74ef32b-ca7d8d80
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
N/A, shields not active in settings.

- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment] 2019-08-19 04:58
Closing as a duplicate of https://github.com/brave/brave-browser/issues/1357

@coleberhorst there isn't a way to import from another instance of Brave at the moment... only a way to import from Chrome/Chromium (as you saw) and the legacy version of Brave (aka Muon)

**Closed by bsclifton** 2019-08-19 04:58 UTC
