### ISSUE TITLE
BAT Ad icon has a red underline below the text

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#21322] opened 2022-02-25 06:37 UTC
## Description 
BAT Ad icon has a red inline border

## Steps to reproduce 

   1. Enable News
   2. Scroll down feed to see an inline ad
   3. Ad text has white background but also has a red underline below the text

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/155666745-8d4878e4-e854-47b0-b9e4-c99c83b56e33.png)

## Expected result
No underline of any colour 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10
   
## Brave version
1.36.105

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @alexsafe

**Comment by stephendonner** [comment] 2022-02-25 09:30
@srirambv dupe of https://github.com/brave/brave-browser/issues/20732?

**Closed** 2022-03-09 14:59 UTC
Labels: bug, QA/Yes, release-notes/exclude, OS/Android, feature/brave-news

**Comment by stephendonner** [comment] 2022-03-22 18:29
Verified `PASSED` using Brave `1.38.63, Chromium 100.0.4896.46` on a `Google Pixel XL` running `Android 9.0`.

Confirmed there's no longer a red underline below `Ad`

![Screenshot_20220322-111350](https://user-images.githubusercontent.com/387249/159550452-8e52390d-16bd-447f-b07c-de983be27e74.png)

**Comment by kjozwiak** [comment] 2022-03-25 04:26
Verification **PASSED** on `Pixel 6` running `Android 12` using `1.37.105 Chromium: 100.0.4896.46`

![Screenshot_20220325-002255](https://user-images.githubusercontent.com/2602313/160054118-e86df904-defc-4909-b2a7-270d3096d521.png)

Verification **PASSED** on `Samsung Galaxy Tablet A` running `Android 12` using `1.37.105 Chromium: 100.0.4896.46`

![Screenshot_20220325-002402_Brave](https://user-images.githubusercontent.com/2602313/160054133-5421a3aa-44b1-45a7-a547-5519badc385c.jpg)
