### ISSUE TITLE
Brave Dev crashes as soon as I click on buttons in the search bar

### ISSUE THREAD

**Issue by Leon0402** [brave/brave-browser#5619] opened 2019-08-11 10:34 UTC
## Description 
Brave Dev is terminated as soon as I click on the icon for Brave Rewards or for the shield

## Steps to Reproduce

   1. Open Brave Dev
   2. Click one of the two icons in the search bar 

## Actual result:
Brave terminates.

## Exspected Results:
It should not crash and instead show the popups for this

## Reproduces how often: 
Every time

## Brave version (brave://version info)
0.69.100 Chromium: 76.0.3809.87 (Official Build) unknown (64-bit)
Linux Manjaro

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not tried yet
- Can you reproduce this issue with the beta channel? Not tried yet
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Not tried yet

## Other Additional Information:

Error message: `brave-dev” terminated by signal SIGSEGV (Address boundary error)`
Other error messages, which might be related to the issue: 
`User namespaces are not detected as enabled on your system, brave will run with the sandbox disabled
[13389:13389:0811/112713.098991:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
[13389:13389:0811/112713.524891:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[13366:13382:0811/112713.565894:ERROR:rewards_service_impl.cc(194)] Failed to read file: /home/leon/.config/BraveSoftware/Brave-Browser/Default/ledger_state
[13439:13439:0811/112713.658688:ERROR:ledger_impl.cc(381)] Failed to initialize wallet
[13439:13439:0811/112714.918300:ERROR:redeem_token.cc(243)] Failed to fetch payment token
`
I can still access the rewards page by using brave://rewards in my search bar.

**Comment by Leon0402** [comment] 2019-08-13 08:14
@bsclifton 
And I believe the last three messages: 
`[13366:13382:0811/112713.565894:ERROR:rewards_service_impl.cc(194)] Failed to read file: /home/leon/.config/BraveSoftware/Brave-Browser/Default/ledger_state [13439:13439:0811/112713.658688:ERROR:ledger_impl.cc(381)] Failed to initialize wallet [13439:13439:0811/112714.918300:ERROR:redeem_token.cc(243)] Failed to fetch payment token`
have nothing to do with that problem. The file "ledger_state" is actually in the directory of the profile and not in the default one, so in 
`/home/leon/.config/BraveSoftware/Brave-Browser/Profile 1` as it contains wallet information, it causes perhaps the second and third error message. And that might cause some of the bat/ads/payment problems reported every day in the forum like 10 times . 
Can you confirm that this is a different bug? Perhaps you could move it then in a separate bug report?
Thanks!

**Comment by rebron** [comment] 2019-08-15 22:18
@Leon0402 Can you update via brave://settings/help and see if it reproduces on Version 0.70.66 Chromium: 76.0.3809.100 (Official Build) dev (64-bit)

That's the current dev version.

**Comment by Leon0402** [comment] 2019-08-16 08:45
Hi @rebron I updated Brave-dev to the latest available version in my Linux repo, which is 
Version 0.70.65 Chromium: 76.0.3809.100 (Official Build) unknown (64-bit)
-> One minor version behind 

The bug still exists in that version, should it be already resolved or does the fix come with .66? 
The error message is still the same `“brave-dev” terminated by signal SIGSEGV (Address boundary error)
`
The other error messages I talked about in my previous comment are also still there.

**Comment by rebron** [comment] 2019-08-16 17:15
cc: @tmancey Can you take a look?

**Comment by NejcZdovc** [comment] 2019-08-29 06:36
maybe this is dupe of https://github.com/brave/brave-browser/issues/5646?

**Comment by Leon0402** [comment] 2019-08-29 07:08
Seems pretty much like the same problem and the same error message. Although the other is the duplicate of mine. I know that the brave them is quite busy, but a crash of the whole program should have a p1 priority (maybe p2 as it‘s not the stable version). And 18 days is quite a lot of days, would have been at least nice to know if anyone is actually investigating this.

**Comment by NejcZdovc** [comment] 2019-09-20 12:21
closing this one as 5646 was already triaged. Thank you for the report

**Closed by NejcZdovc** 2019-09-20 12:21 UTC
Labels: crash, feature/rewards
