### ISSUE TITLE
todoist chrome extension does not work

### ISSUE THREAD

**Issue by harperaa** [brave/brave-browser#6901] opened 2019-11-13 16:25 UTC
## Description 
When running the latest version of brave, with the todoist extension installed, it does not function correctly.  When I try to open a new task and start typing, it does not show the keystrokes, but they are there when I hit return.  I confirmed this issue does not happen on chrome.

## Steps to Reproduce
   1. Install todoist extension
   2. May need to start a free account, using gmail to authenticated
   3. Hit add new task button, start typing.  When I do this, I don't see the characters on the screen, but they do appear when I hit enter to save the tasks.

## Actual result:
![Screen Shot 2019-11-13 at 11 21 06 AM](https://user-images.githubusercontent.com/1330944/68782724-d4073000-0607-11ea-8540-ff2bd203dfea.png)
![Screen Shot 2019-11-13 at 11 21 19 AM](https://user-images.githubusercontent.com/1330944/68782722-d4073000-0607-11ea-9118-acfab997dcd1.png)

## Reproduces how often: 
Should be easy to reproduce

## Brave version (brave://version info)

Brave | 0.70.123 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.4 (Build 17E199)
JavaScript | V8 7.8.279.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=NewExtensionUpdaterService,PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,LookalikeUrlNavigationSuggestionsUI,UnifiedConsent,SyncUSSBookmarks --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/allenharper/Library/Application Support/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:
Not sure.

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
I have not enabled rewards
- Is the issue reproducible on the latest version of Chrome? 
No, it works fine in latest version of Chrome.

## Miscellaneous Information:
None.

Thanks for great browser...

**Comment by aussiechief** [comment] 2019-11-13 19:08
- Unable to reproduce on Brave 1.0 STABLE (78.0.3904.97) running Windows 10 64x (1903).
- Unable to reproduce on Google Chrome BETA (79.0.3945) running Windows 10 64x (1903).

[Link to screenshot](https://i.imgur.com/b8ZTLVd.png)

**Comment by harperaa** [comment] 2019-11-13 20:12
Wow, thats odd, any way I can further troubleshoot this.  I opened dev tools, don't see any errors or anything in the console related to that plugin. Btw, thanks for the quick look, that is impressive with a project this size.  Please advise how I can further troubleshoot or provide evidence for your use.
Thanks again.

**Comment by aussiechief** [comment] 2019-11-13 20:16
- Unable to reproduce on Brave 1.0 STABLE (78.0.3904.97) running MacOS Mohave (10.14.5 ).

@harperaa Alan, I would suggest reinstalling the extension to see if that resolves the issue. Another option is to reinstall Brave.

[Link to screen recording](https://i.imgur.com/2a4wbnM.mp4)

<img width="566" alt="Screen Shot 2019-11-13 at 12 26 42 PM" src="https://user-images.githubusercontent.com/52020530/68799789-09b31580-0616-11ea-83a9-b77453139b5c.png">

brave://version
Brave   1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)
Revision:    021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS:  macOS Version 10.14.5 (Build 18F132)

**Comment by harperaa** [comment] 2019-11-13 20:18
I did try to uninstall and reinstall the extension.  It looks like it may be a timing and transmission of packets issue... if I open a new task, type in eeeee, then I see nothing, but about 30-60 seconds later, it appears... odd.  Now, if I hit return, it appears in the task list as normal... problem is typing blind...  I will try to install brave or better yet, check on another mac.

**Comment by aussiechief** [comment] 2019-11-13 20:24
I was not able to reproduce the issue on two different Macs that I tried.

Do you have issues typing in extension pop-overs other than ToDoList?  If you don't have an another extension that has text inputs, try downloading one from the Web Store to test (such as _Sticky Notes - Just popped up!_)

**Comment by harperaa** [comment] 2019-11-13 20:47
Yes, I just checked that lastpass works well, and it has a text input box on the extension button... really odd.

**Comment by NumDeP** [comment] 2019-11-16 18:05
I think this has to be an issue with the extension eco system. I've started to notice issues with screen capture extensions and at first thought this was due to a bug, however, I've noticed this across similar extensions.

**Comment by bsclifton** [comment] 2019-12-02 19:56
Something you can try: 
1. go to brave://inspect/#extensions
2. click `inspect` next to the `Todoist` extension to open the background page console
3. use the extension and reproduce the problem

Hopefully, if there's an error, it'll show in the logs. You can share that here (remove any personal info) and it might help w/ troubleshooting 😄

**Comment by rebron** [comment] 2020-01-10 17:26
@harperaa It looks like todoist extension is working. Closing for now. Let me know if I need to reopen if it's still not working for you.

**Closed by rebron** 2020-01-10 17:26 UTC
Labels: feature/extensions
