### ISSUE TITLE
[Desktop] No option to change default search engine in Private Mode 

### ISSUE THREAD

**Issue by Nuc1eoN** [brave/brave-browser#11351] opened 2020-08-20 17:44 UTC
Navigating to `brave://settings/search` should let the user change his default search engine.

However there is no option to change it for private mode.

**Comment by srirambv** [comment] 2020-08-21 04:13
Search Engine settings is the same for Normal tabs and private tabs. There is no option to set differently for different window types. Additionally for private windows you can set DDG with the switch on new tab. That way you can have different for private tabs

cc: @rebron

**Comment by srirambv** [comment] 2020-08-24 05:49
There is no separate setting to change private mode search engine. You can set DDG with this switch on the new tab page on a private window
![image](https://user-images.githubusercontent.com/17010094/91008263-e3bf9600-e5d5-11ea-9139-4131a08c8b38.png)

**Comment by Nuc1eoN** [comment] 2020-08-24 13:11
@srirambv Thanks oh ok I didn't see this. It's weird that this would not be in the settings I must say.

> Search Engine settings is the same for Normal tabs and private tabs. There is no option to set differently for different window types.

To be frank, the Brave mobile version has exactly that option in the Settings.

**Comment by rebron** [comment] 2020-09-18 17:01
Closing as dupe of #2158 and #5794

**Closed by rebron** 2020-09-18 17:01 UTC
Labels: OS/Desktop, feature/search, priority/P4
