### ISSUE TITLE
Chrome (Brave) DevTools Sources Panel missing JS colors and tooltips.

### ISSUE THREAD

**Issue by jtheletter** [brave/brave-browser#7335] opened 2019-12-12 02:25 UTC
Suddenly my Brave app's Dev Tools Sources Panel is missing colors and tooltips for JavaScript files. 

Here's what I see in Brave: 

![Screen Shot 2019-12-11 at 18 07 47](https://user-images.githubusercontent.com/49571924/70677236-789a8300-1c43-11ea-8866-82e5f18017d3.png)

Here's that same file JS file on the same breakpoint in Chrome, with JS colors a tooltip by hover of a variable: 

![Screen Shot 2019-12-11 at 18 07 36](https://user-images.githubusercontent.com/49571924/70677249-7f28fa80-1c43-11ea-8050-87e7032b03d3.png)

This appears to be occurring for any JS file on any website. I've tried quitting and relaunching Brave app. I've poked through the DevTools controls and prefs and online docs. What could be causing this, how might I fix it? 

* MacOS Catalina 10.15.1 (19B88)
* Brave Version 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)
* Chrome Version 79.0.3945.79 (Official Build) (64-bit)

  [1]: https://i.stack.imgur.com/5zXhM.png
  [2]: https://i.stack.imgur.com/adn7P.png

**Comment by bsclifton** [comment] 2019-12-12 05:56
@jtheletter I think this may be somewhat expected; the fix is in 1.3 (Developer edition) and later. You can try that version quickly to see if it works:
https://brave.com/download-dev/

Once downloaded, you can go to brave://settings/privacy and enable Remote Debugging. This is something we turned off to block external requests from being made. I suspect this is what is broken for you

If that DOES fix the issue, 1.3 will be shipping to Release channel on February 4th. Please let us know 😄

**Comment by SirKlaus** [comment] 2019-12-12 11:01
@bsclifton It does fix the color problem but it doesn't fix the tooltip problem. Looks like I have to use an other browser until February 😞

**Comment by jtheletter** [comment] 2019-12-12 16:34
> This is something we turned off to block external requests from being made. 

@bsclifton: Even if I view a static and local (from `file:///`) website? Why block external requests with no option to allow them?

**Comment by bsclifton** [comment] 2019-12-12 17:50
@rebron do you think we can expedite the Remote Debugging fix (land in 1.2, which is being released January 6th)?

@SirKlaus thanks for linking to the Chromium bugs - I starred those and will follow progress

**Comment by bsclifton** [comment] 2019-12-13 06:35
Closing as a dupe of https://github.com/brave/brave-browser/issues/5618 

I created a PR now to uplift this to our Beta branch (1.2, shipping January 6th) since there have been a recent bump in requests:
https://github.com/brave/brave-core/pull/4228

**Closed by bsclifton** 2019-12-13 06:35 UTC
Labels: feature/dev-tools, need-more-info
