### ISSUE TITLE
Clicking on Brave stable opens up Brave Beta.

### ISSUE THREAD

**Issue by Techguyprivate** [brave/brave-browser#2281] opened 2018-11-29 10:23 UTC
Yes. 
Issues. https://github.com/brave/brave-browser/issues/1324

## Description 

Clicking on Brave stable opens up Brave beta , not brave dev version though. I think that Brave beta updated recently .The brave beta version is 0.57.8. I don't know whether it is rewritten over Brave stable or just shortcut problems. Both on linux mint 17 & ubuntu 18.04 . 

Simply , I am unable to open Brave stable version which is my default with lot of bookmarks ,history & most importantly  passwords . Brave beta opens up each time.

## Steps to Reproduce

   1. Update brave beta to recent version 0.57.8 .
   2. Click on Brave stable shortcut.
  

## Actual result:

Brave beta opens up instead of stable.

## Expected result:
Brave stable should be opened ,not beta.

## Reproduces how often: 

Everytime.

## Brave version (brave://version info)

Brave | 0.57.8 Chromium: 71.0.3578.53 (Official Build) beta (64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Linux
JavaScript | V8 7.1.302.21
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.53 Safari/537.36
Command Line | /usr/bin/brave-browser --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave,AutofillServerCommunication --flag-switches-begin --autoplay-policy=document-user-activation-required --default-tile-height=1024 --default-tile-width=1024 --blink-settings=disallowFetchForDocWrittenScriptsInMainFrame=true --enable-experimental-web-platform-features --enable-fast-unload --force-gpu-rasterization --history-entry-requires-user-gesture --javascript-harmony --enable-oop-rasterization --use-simple-cache-backend=on --site-per-process --enable-tcp-fastopen --enable-webgl-draft-extensions --enable-zero-copy --gpu-rasterization-msaa-sample-count=16 --ignore-gpu-blacklist --num-raster-threads=4 --reduced-referrer-granularity --save-page-as-mhtml --save-previous-document-resources=onload --show-saved-copy=primary --enable-smooth-scrolling --tls13-variant=final --v8-cache-options=code --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService,AutomaticPasswordGeneration,Av1Decoder,BloatedRendererDetection,BlockTabUnders,ClickToOpenPDFPlaceholder,DisallowUnsafeHttpDownloads,ExperimentalProductivityFeatures,FontCacheScaling,FramebustingNeedsSameOriginOrUserGesture,GuestViewCrossProcessFrames,LayoutNG,LazyFrameLoading,LazyImageLoading,MarkHttpAs,NtlmV2Enabled,OmniboxReverseAnswers,OmniboxRichEntitySuggestions,OmniboxSpeculativeServiceWorkerStartOnQueryInput,OmniboxTailSuggestions,OmniboxUIExperimentMaxAutocompleteMatches,PWAFullCodeCache,ParallelDownloading,PassiveDocumentWheelEventListeners,PassiveEventListenersDueToFling,PasswordImport,PdfIsolation,PictureInPicture,RecurrentInterstitialFeature,ScrollAnchorSerialization,ServiceWorkerScriptFullCodeCache,SoundContentSetting,UseSurfaceLayerForVideo,V8ContextSnapshot,V8Orinoco,V8VmFuture,WebAssembly,WebAssemblyBaseline,WebAssemblyThreads,WebRTC-H264WithOpenH264FFmpeg,WebRtcHybridAgc,WebRtcUseEchoCanceller3,brotli-encoding --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave,AutofillServerCommunication,DoodlesOnLocalNtp,OmniboxDocumentProvider,QueryInOmnibox,TopSitesFromSiteEngagement,UseGoogleLocalNtp --flag-switches-end
Executable Path | /opt/brave.com/brave-beta/brave-browser-beta
Profile Path | /home//.config/BraveSoftware/Brave-Browser-Beta/Default

The version is for Brave beta cause I am unable to open brave stable.

### Reproducible on current release:Yes.
- Does it reproduce on brave-browser dev/beta builds? 
Yes.

### Additional Information

The executable Path & profile Path are for Brave beta , not stable.

**Comment by rebron** [comment] 2018-12-04 20:00
@srirambv looks like a dupe of https://github.com/brave/brave-browser/issues/1324?

**Comment by srirambv** [comment] 2018-12-05 02:37
Yup its a dupe. And this is not just an issue with the most recent install, any version(dev/beta/release) all point to the same shortcut so if you have beta/dev open and you need to launch release the only way  to have both windows open is right click and open new window. This is a pretty annoying bug

**Closed by srirambv** 2018-12-05 02:37 UTC
Labels: OS/Linux

**Comment by Techguyprivate** [comment] 2018-12-25 19:16
Any solution , success , workarounds ,tweaks, hack ?

**Comment by Techguyprivate** [comment] 2019-03-20 13:10
Today, Clicking on brave stable , open up brave beta on Ubuntu & Linux mint . I did remove brace , then installed it as suggested above. But the problem still occurs.
