### ISSUE TITLE
Crash when trying to use specific Google services

### ISSUE THREAD

**Issue by candroid-man** [brave/brave-browser#27944] opened 2023-01-21 01:47 UTC
Brave Version: 1.47.171, Chromium: 109.0.5414.87
Operating System: Windows NT 10.0.22621

URL (if applicable) where crash occurred:

https://console.cloud.google.com/projectcreate

https://accounts.google.com/ServiceLogin?ltmpl=music&service=youtube&uilel=3&passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Den%26next%3Dhttps%253A%252F%252Fmusic.youtube.com%252F%26feature%3D__FEATURE__&hl=en

Can you reproduce this crash?

Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)

Simply going to these links crashes Brave for me. I am using IVPN and NextDNS, and NextDNS isn't blocking anything related to these links. It happens every time without fail. I am unable to log in to YouTube Music or create any Google Cloud projects, so, so far, everything seems to be Google related. This does not occur on any other browsers.

Crash ID: crash/8aeb0200-7249-7e09-0000-000000000000
Crash ID: crash/e0e00200-7249-7e09-0000-000000000000

**Comment by goodov** [comment] 2023-01-23 15:24
this is fixed with https://github.com/brave/brave-browser/issues/27791

**Comment by rebron** [comment] 2023-01-23 17:17
Closing as dupe of https://github.com/brave/brave-browser/issues/27791

**Closed by rebron** 2023-01-23 17:17 UTC
