### ISSUE TITLE
Once unchecked native token can't be added back unless the modal is closed and reopened

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22556] opened 2022-04-26 10:53 UTC
## Description 

While testing #22159, found if a native token is unchecked, it can't be checked/added again until you close the edit visible asset modal.

## Steps to Reproduce

   1. Install 1.38.107 build
   2. Disable native asset from  visible asset modal
   3. Try adding again, doesn't work
   4. Close modal and reopen and try to add again, works this time

## Actual result:

https://user-images.githubusercontent.com/17010094/165284186-6f8ba602-670d-45e7-99e9-70c57957203a.mov

## Expected result:
Should be able to check/uncheck the asset without having to close the modal and reopen it

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.38.107 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | `93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}`
OS | All

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes when 1.38.x is released
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by Douglashdaniel** [comment] 2022-05-20 16:24
Marking as duplicate of https://github.com/brave/brave-browser/issues/22952

**Closed by Douglashdaniel** 2022-05-20 16:24 UTC
Labels: bug, closed/duplicate, QA/Yes, release-notes/exclude, feature/wallet, OS/Desktop
