### ISSUE TITLE
Add aggressive mode option in shields

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#15666] opened 2021-05-06 22:15 UTC
## Description 
The work in https://github.com/brave/brave-browser/issues/7487 adds support in settings for aggressive mode, however we are missing the option to enable aggressive mode in shields. Please add this option.

@karenkliu for a design

cc @pes10k

**Comment by karenkliu** [comment] 2021-05-07 00:01
This is a dupe of https://github.com/brave/brave-browser/issues/9831#issuecomment-786804751

**Closed by karenkliu** 2021-05-07 00:01 UTC
Labels: OS/Android, QA/Yes, design/needs-mock-up, priority/P3, release-notes/include
