### ISSUE TITLE
Warning message when downloading file overlaps file name

### ISSUE THREAD

**Issue by paul-brown9** [brave/brave-browser#17855] opened 2021-09-03 04:44 UTC
## Description 

The warning message when downloading a potenially harmful file overlaps the file name.

## Steps to Reproduce

   1. Download a file that displays the warning message (in this case, a .jar file)

## Actual result:

![image](https://user-images.githubusercontent.com/52123953/131950431-8bcd07e3-a5db-439d-b71b-3c577ef836da.png)

## Expected result:
![image](https://user-images.githubusercontent.com/52123953/131950379-5d24f748-8779-49ab-bb9f-defa0bf73fa7.png)

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

<html>
<body>

Brave | 1.29.76 Chromium: 93.0.4577.58 (Official Build) (64-bit)
-- | --
Revision | c4410ece044414ea42fa4ba328d08195e818a99c-refs/branch-heads/4577@{#1076}
OS | Windows 10 OS Version 2009 (Build 19042.1165)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

None.

**Comment by rebron** [comment] 2021-09-17 00:02
Closing as dupe of #17313

**Closed by rebron** 2021-09-17 00:02 UTC
Labels: OS/Desktop
