### ISSUE TITLE
Brave's Standalone installer fails

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#34286] opened 2023-11-13 01:24 UTC
The error message is "Installation failed due to a server side error. Please try again later."

![image](https://github.com/brave/brave-browser/assets/1076393/b7280f70-fd2f-453c-9649-8a368f3e422e)

**Comment by kjozwiak** [comment] 2023-11-13 05:43
Adding some more context/information in case someone runs into the above:

* `1.62.37 Chromium: 119.0.6045.124` was updated to `1.62.38 Chromium: 119.0.6045.134` without any issues. Seems like `1.62.38 Chromium: 119.0.6045.134` is the latest `Nightly` on `Public` as per https://versions.brave.com

* https://github.com/brave/brave-core/pull/20829 landed in `master` ~3 days ago via `1.62.38`

* seems like updates are NOT affected as I can update to `1.62.38 Chromium: 119.0.6045.134` but can't install that version with the `BraveBrowserStandaloneNightlySetup.exe` due to the above error.

* downloaded the stub installer via https://brave.com/download-nightly which downloaded/installed `1.62.38 Chromium: 119.0.6045.134` without any issues.

So it appears that the issue occurs when a user tries installing `Brave` via the `standalone` installer from https://github.com/brave/brave-browser/releases.

**Comment by GeetaSarvadnya** [comment] 2023-11-13 06:28
Adding one more point to the above information, standalonesilent installers are NOT affected. I have downloaded and installed `BraveBrowserStandaloneSilentNightlySetup.exe`  I am able to install `1.62.45` without any issues.

**Closed** 2023-11-13 07:22 UTC
Labels: bug, OS/Windows, setup/installer, QA/Yes, release-notes/exclude, OS/Desktop

**Comment by MadhaviSeelam** [comment] 2023-11-13 21:17
Verification `PASSED` using
```
Brave | 1.62.49 Chromium: 119.0.6045.134 (Official Build) nightly (64-bit)
-- | --
Revision | ebbe0beec9dfdb603463869912ad4ec19899293d
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

- Downloaded standalone installer `BraveBrowserStandaloneNightlySetup.exe` and installed successfully via https://github.com/brave/brave-browser/releases/download/v1.62.49/BraveBrowserStandaloneNightlySetup.exe

<image width ="500" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/50e6bab4-5b62-46d0-9b70-f20497bf7236">


- Downloaded online installer installed successfully via brave.com `1.62.38 Chromium: 119.0.6045.134 (Official Build) nightly` and upgraded to `1.62.49 Chromium: 119.0.6045.134 (Official Build) nightly` 

1.62.38 | upgrade | 1.62.49
------ | ------ | ----
![image](https://github.com/brave/brave-browser/assets/98358127/eac4b16c-df76-438d-b9cd-b6bf81e5e1be)|![image](https://github.com/brave/brave-browser/assets/98358127/dfc2ef86-d084-42c7-8c01-0ac2f5700e98)|![image](https://github.com/brave/brave-browser/assets/98358127/46b1ca1e-6af4-4f7a-97ca-62396ed129d5)

- Downloaded Silent installer and installed successfully `BraveBrowserStandaloneSilentNightlySetup.exe` via 
https://github.com/brave/brave-browser/releases/download/v1.62.49/BraveBrowserStandaloneSilentNightlySetup.exe

<image width ="500" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2cb94abb-a574-4a97-8451-abb05b1915bb">

**Comment by MadhaviSeelam** [comment] 2023-11-13 21:25
@GeetaSarvadnya @kjozwiak not adding `QA Pass-Win64` label to verify on Win 10.

**Comment by kjozwiak** [comment] 2023-11-13 21:25
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.62.49 Chromium: 119.0.6045.134 (Official Build) nightly (64-bit)
-- | --
Revision | ebbe0beec9dfdb603463869912ad4ec19899293d
OS | Windows 11 Version 22H2 (Build 22621.2506)
```

Using https://github.com/brave/brave-browser/releases/download/v1.62.49/BraveBrowserStandaloneNightlySetup.exe, ensured that I was able to install `1.62.49 Chromium: 119.0.6045.134` on my machine without any issues/failures.

-------------

Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.62.49 Chromium: 119.0.6045.134 (Official Build) nightly (32-bit)
-- | --
Revision | ebbe0beec9dfdb603463869912ad4ec19899293d
OS | Windows 10 Version 22H2 (Build 19045.3636)
```

Using https://github.com/brave/brave-browser/releases/download/v1.62.49/BraveBrowserStandaloneNightlySetup32.exe, ensured that I was able to install `1.62.49 Chromium: 119.0.6045.134` on my machine without any issues/failures.

**Comment by stephendonner** [comment] 2023-11-13 21:34
## Verified `PASSED` using

```
Brave | 1.62.49 Chromium: 119.0.6045.134 (Official Build) nightly (64-bit)
-- | --
Revision | ebbe0beec9dfdb603463869912ad4ec19899293d
OS | Windows 10 Version 22H2 (Build 19045.3636)
```

Using `https://github.com/brave/brave-browser/releases/download/v1.62.49/BraveBrowserStandaloneNightlySetup.exe`, ensured that I was able to install 1.62.49 Chromium: 119.0.6045.134 on my machine without any issues/failures.

example | example
----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/6a96cd3a-5c00-4d3c-967c-fc482e019640) | ![image](https://github.com/brave/brave-browser/assets/387249/538ad366-c12b-42f1-9694-ba996c047d2d)

Also downloaded StandaloneSilent installer `BraveBrowserStandaloneSilentNightlySetup.exe` and installed successfully via
`https://github.com/brave/brave-browser/releases/download/v1.62.49/BraveBrowserStandaloneSilentNightlySetup.exe`

Confirmed the issue using `1.62.45`, first:

![image (2)](https://github.com/brave/brave-browser/assets/387249/eecef585-35be-4e4f-a559-7b76120853fc)

**Comment by MadhaviSeelam** [comment] 2023-12-06 01:25
Verification `PASSED` using
```
Brave | 1.62.94 Chromium: 120.0.6099.35 (Official Build) beta (64-bit)
-- | --
Revision | e0c8a0307f7aad8a0f79a5540dccc57d561daf8a
OS | Windows 11 Version 22H2 (Build 22621.2715)
```

#### Standalone installer - BraveBrowserStandaloneBetaSetup.exe

- Downloaded standalone installer `BraveBrowserStandaloneBetaSetup.exe via https://github.com/brave/brave-browser/releases/download/v1.62.94/BraveBrowserStandaloneBetaSetup.exe and installed `1.62.94 Chromium: 120.0.6099.35` successfully without errors. 

<img width="462" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f394e8c5-5f21-4a56-9289-de282f70797c">

#### Silent standalone installer -` BraveBrowserStandaloneSilentBetaSetup.exe`

- Downloaded silent standalone installer BraveBrowserStandaloneSilentBetaSetup.exe via https://github.com/brave/brave-browser/releases/download/v1.62.94/BraveBrowserStandaloneSilentBetaSetup.exe and installed 1.62.94 Chromium: 120.0.6099.35` successfully without errors.

<img width="515" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/68ba487e-278a-4ea7-b08e-4b7abb337dc7">
