### ISSUE TITLE
`Send a tip` tooltip is not shown for Reddit and Twitter publishers

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#25558] opened 2022-09-22 15:29 UTC
## Description 

`Send a tip` tooltip is not shown for Reddit and Twitter publishers

## Actual result:

Reddit
![image](https://user-images.githubusercontent.com/38657976/191787863-201721c7-f1fe-47ef-a6be-0f51380052a8.png)

Twitter
![image](https://user-images.githubusercontent.com/38657976/191788251-4852cd05-2a5a-43b1-98c3-3ae5850dbcd7.png)

## Expected result:

discussed with @mkarolin 
As per the code the `Send a tip` tooltip should be shown for Twitter and reddit
![image](https://user-images.githubusercontent.com/38657976/191789689-c3a9a0eb-e0d6-4e08-b21e-d028ec601865.png)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (64-bit)
-- | --
Revision | fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}
OS | Windows 10 Version 21H2 (Build 19044.2006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team  @Miyayes

**Comment by LaurenWags** [comment] 2022-10-03 12:24
This is a duplicate of:

**Comment by Miyayes** [comment] 2022-11-09 17:24
@Miyayes Go back and check old issues and make sure they're up to date.

**Comment by mkarolin** [comment] 2023-03-15 17:52
Closing as we no longer use tooltips with the inline tipping buttons (https://github.com/brave/brave-browser/issues/28699).

**Closed by mkarolin** 2023-03-15 17:52 UTC
Labels: bug, polish, feature/rewards, priority/P4, QA/Yes, QA/Test-Plan-Specified, greaselion, OS/Desktop
