### ISSUE TITLE
Brave Browser Helper 100% CPU, can't force quit, run with Brave closed, task manager shows nothing

### ISSUE THREAD

**Issue by SephReed** [brave/brave-browser#9534] opened 2020-04-29 18:20 UTC
## Description 
I've been having serious issues on Mac OS with Brave for a month now.  A recent issue with BAT Ledger got fixed, but it appears the problem was just moved elsewhere.

Currently, Brave Browser Helper is using 100% CPU.  If I force quit it, it comes back.  If I close Brave browser and force quit the task, it still comes back.  I'm going to try restarting my computer, and if that doesn't work I'll have to uninstall Brave entirely.

## Steps to Reproduce
Install Brave Browser.

## Actual result:

This is my Brave Task Manager:
![Screen Shot 2020-04-29 at 1 10 33 PM](https://user-images.githubusercontent.com/14002040/80631106-e0970d80-8a1a-11ea-9348-a0b619987c5a.png)

This is my Activity Monitor with Brave not running at all, having just force quit the process seconds ago:
<img width="799" alt="Screen Shot 2020-04-29 at 1 05 56 PM" src="https://user-images.githubusercontent.com/14002040/80631198-00c6cc80-8a1b-11ea-8c49-0b9a4d398b07.png">

## Brave version (brave://version info)
```

Brave | 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.14.3 (Build 18D109)
JavaScript | V8 8.1.307.28
Flash | 32.0.0.303 /Library/Internet Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning,SimplifyHttpsIndicator,MixedContentSiteSetting,DnsOverHttps --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,TextFragmentAnchor,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,VideoPlaybackQuality --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/seph/Library/Application Support/BraveSoftware/Brave-Browser/Default
```

## Miscellaneous Information:

Please take this seriously: you have a rogue process running on my computer that is taking 100% CPU and can not be stopped.

**Comment by SephReed** [comment] 2020-04-29 18:27
I've found more details.  In the process of restarting my lap top, I had to go through my other users and log them out.

One of my users has been having the BAT Ledger issue for a while now.  After logging that one out, I went back to my main user and the process was no longer running.

It would seem that the `Brave Browser Helper` task was running on behalf of a separate Mac OS user that had the Brave Browser open.  I did not check the Brave Task Manager before closing that app instance, but I presume this is still related to BAT Ledger.

**Comment by SephReed** [comment] 2020-04-29 18:30
Looking back on the screenshot of Activity Monitor I now see that the user was indeed `seph-p`

I'll have to test this from that user soon.  I highly, highly suspect this is BAT Ledger.  I also just updated both users Brave version last night.

**Comment by rebron** [comment] 2020-04-29 18:35
@SephReed That's interesting. Logging out the other user looks like process is no longer running so it's working properly?

**Comment by rebron** [comment] 2020-04-29 18:38
@SephReed We have a new release coming out soon https://github.com/brave/brave-browser/releases/tag/v1.8.86 if you want to give that one a spin.

**Comment by SephReed** [comment] 2020-05-02 00:25
It's part of this issue: https://github.com/brave/brave-browser/issues/8846

And it's still not fixed.

**Comment by bsclifton** [comment] 2020-05-12 19:50
Closing as dupe of https://github.com/brave/brave-browser/issues/8846 - we have a fix for the final known issue going out today 😄

**Closed by bsclifton** 2020-05-12 19:50 UTC
Labels: perf

**Comment by hereiszee** [comment] 2021-07-13 00:34
Did you have the Lolli extension installed?

Just ran into the same issue. Quitting the process crashed only that extension. Proceeded to uninstall the extension, and ever since then have never had this issue. Possible that Lolli is using users as nodes? @SephReed
