### ISSUE TITLE
sync page lists multiple devices as This Device

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3234] opened 2019-02-05 21:11 UTC
## Description 
Found while testing https://github.com/brave/brave-browser/issues/2501

When syncing on 0.60.19, multiple devices are shown as This Device, but only one should be.

## Steps to Reproduce

   1. Clean install 0.60.19 and have another device (like Android 1.0.77 version) ready with clean install.
   2. Go to brave://sync
   3. Start sync chain and join with Android (or other device)

## Actual result:
Once sync chain is completed, both devices say (This Device)
![screen shot 2019-02-05 at 3 54 09 pm](https://user-images.githubusercontent.com/28145373/52304310-79e28b80-2960-11e9-880a-a53b3fa6d6c7.png)

## Expected result:
Only the actual device should say (This Device):
![screen shot 2019-02-05 at 4 10 14 pm](https://user-images.githubusercontent.com/28145373/52304346-8c5cc500-2960-11e9-8683-1508b023c7c4.png)

## Reproduces how often: 
reproduces easily on beta, does not reproduce on release 0.59.35

## Brave version (brave://version info)

Brave | 0.60.19 Chromium: 72.0.3626.81 (Official Build) beta(64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by GeetaSarvadnya** [comment] 2019-02-11 10:34
Not reproducible on Windows `10 x64 - 0.60.25`

![image](https://user-images.githubusercontent.com/38657976/52557849-a7bf4880-2e16-11e9-8cd8-167ad2962c30.png)

**Comment by btlechowski** [comment] 2019-02-12 02:43
Not reproducible on Ubuntu 17.10

Brave | 0.60.26 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Linux

![image](https://user-images.githubusercontent.com/34715963/52607398-6068a480-2e76-11e9-82a4-f056ce3c9c90.png)

**Comment by rebron** [comment] 2019-03-01 19:23
cc: @cezaraugusto to take a look

**Comment by AlexeyBarabash** [comment] 2019-03-06 12:19
Cannot reproduce with Android 1.0.84-rc2 and brave-core linux 0.60.x ... 0.63.x .

**Comment by cezaraugusto** [comment] 2019-05-24 00:42
closing for now as not reproducible. please re-open if I'm wrong or if this happens again. thanks!

**Closed by cezaraugusto** 2019-05-24 00:42 UTC
Labels: OS/macOS, QA/Test-Plan-Specified, QA/Yes, bug, feature/sync, priority/P3, regression, release-notes/exclude
