### ISSUE TITLE
1Password Extension 100% broken on newest Brave

### ISSUE THREAD

**Issue by marintoo** [brave/brave-browser#1730] opened 2018-10-19 17:04 UTC
## Description
1Password Extension doesn't work at all

## Steps to Reproduce
Install Brave and 1Password Extension
Have 1Password 7 installed on the mac

## Actual result:
Icon constant flickering, doesn't open, unusable

## Expected result:
Should work normal just like on Chrome
I assume this might be because of the invalid signature code of Brave

## Reproduces how often:
Every time

## Brave version (brave://version info)
Brave | 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)
OS | Mac OS X
JavaScript | V8 7.0.276.28
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36

**Comment by bsclifton** [comment] 2018-10-19 17:32
@marintoo what version of 1Password do you have?  I believe you need to have 7.1.2 (or newer) for it to work. With that version, they added our application details so that it would work properly 😄

**Comment by marintoo** [comment] 2018-10-19 17:54
I just checked and I have 1Password 7.1.1

**Comment by bsclifton** [comment] 2018-10-19 18:36
@marintoo awesome - please try updating and let us know if that resolves the issue 😄

**Comment by krono** [comment] 2018-10-20 11:42
Any way to have it working with 1Password 6?

**Comment by marintoo** [comment] 2018-10-20 12:53
< 7.2 works fine on Chrome, is there any way to get Brave working with older versions?
Found another one who has a problem with 1Password 6 on Brave:
https://www.reddit.com/r/brave_browser/comments/9jghrb/brave_beta_now_available/e6uld4j/

**Comment by renschler** [comment] 2018-10-20 18:19
Same, I am running 1Password 6 and it looks like it's $65 to upgrade to 1Password 7 license.

**Comment by bsclifton** [comment] 2018-10-21 07:30
@marintoo unfortunately, there isn't a way to get this working with earlier versions. We reached out to the folks at 1Password and had them update the checks they make

I'm not sure if the 1Password developers at AgileBits are open to new work on version 6, but you can definitely ask in their support forum:
https://discussions.agilebits.com

Since there is nothing we can do on our side (ex: there's not a bug that we can fix), I'm going to close this issue out. However, please feel free to update us here if you hear from AgileBits staff 😄

**Closed by bsclifton** 2018-10-21 07:30 UTC
Labels: feature/extensions, need-more-info

**Comment by renschler** [comment] 2018-10-21 18:49
I've started a new discussion on the agilebits website, since the link above was originally filed against the beta brave release.

If anyone else wants this resolved it would be awesome if you could add your thoughts there! Thanks

https://discussions.agilebits.com/discussion/97296/1password-extension-does-not-work-with-official-brave-release-and-1-password-6-desktop-application/p1?new=1

**Comment by tomlowenthal** [comment] 2018-10-22 20:57
I know that a lot of folks are sticking with 1Password v6 because they prefer a standalone tool to a subscription service. But! You can also get 1Password v7 as a standalone tool:
1. Download & install 1Password v7 from <https://1password.com/downloads/>
2. In your menu bar, go to *1Password 7* > *Purchase License*

You get all the best features added to v7. You don't need a subscription. And you can use Brave. Win/win/win, IMO.

**Comment by krono** [comment] 2018-10-22 20:58
@tomlowenthal Except I'm stuck on 10.11…

**Comment by bsclifton** [comment] 2018-10-22 20:59
@krono I think your best bet would be to let the AgileBits developers know in https://discussions.agilebits.com/discussion/97296/1password-extension-does-not-work-with-official-brave-release-and-1-password-6-desktop-application/p1?new=1

**Comment by krono** [comment] 2018-10-22 21:00
@bsclifton Yes, I know. Been there, done that :)
