### ISSUE TITLE
Add 'View in Chrome Webstore' option on extension page.

### ISSUE THREAD

**Issue by TontyTon** [brave/brave-browser#3248] opened 2019-02-06 13:31 UTC
## Description 

Add 'View in Chrome Webstore' option on extension page.

## Steps to Reproduce

   1. Install an extension from Chrome Webstore
   2. Go to its page in chrome://extensions/

## Actual result:

![1](https://user-images.githubusercontent.com/35778430/52344558-13816a00-2a41-11e9-871b-a5450d1e9e8b.jpg)

## Expected result:
From Chrome- 72.0.3626.81
![2](https://user-images.githubusercontent.com/35778430/52344563-15e3c400-2a41-11e9-9e5d-b9eadc84ef9e.jpg)

## Reproduces how often: 

Always

## Brave version (brave://version info)

0.59.34 | 72.0.3626.81

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? - No 
- Is the issue reproducible on the latest version of Chrome? - No

**Comment by srirambv** [comment] 2019-02-09 04:09
Whats the use case for this? Its just going to open the webstore and nothing else.

cc: @tomlowenthal

**Comment by thepcwiz101** [comment] 2019-02-09 05:35
@TontyTon If your looking for an extension just look up google chrome webstore in google and then use the search function. It may require more steps but until the change is made to put a link into the chrome://extensions it will have to do. By the look of this i suspect it was intentional as the devs of brave intended to remove all calls made by the browser to google when they switched the browsers engine a little while back.

**Comment by TontyTon** [comment] 2019-02-09 07:08
@srirambv As @thepcwiz101 , it requires much more steps to go to extension page in web store. It leads to time waste, for example
- when an extension get deleted from webstore it becomes almost impossible to know that and we have to keep searching till we get convinced that it is deleted (or copy extension ID put it in webstore URL, much longer process)
- Another problem is, even when extension is not deleted and is less popular and have common name (which is normal in webstore), we don't get it in top results and only option left is again, copy extension ID and put in webstore URL.

And most extensions don't have any website or page, so only place to find it is in webstore.

And @thepcwiz101 , I don't think that
> it was intentional as the devs of brave intended to remove all calls made by the browser to google

_I think_ it is more of branding issue (Branding is important but feature removal for branding is not good, _my view_).

Since, the link structure is very simple
https://chrome.google.com/webstore/detail/<Extension ID>
So, even if Chrome included some calling back, Brave can add the link itself.

**Comment by bsclifton** [comment] 2021-04-07 22:41
Closing as a duplicate of https://github.com/brave/brave-browser/issues/12868

**Closed by bsclifton** 2021-04-07 22:41 UTC
Labels: feature/extensions, priority/P5
