### ISSUE TITLE
Allow users to hide the `To exit full screen, press ESC` message when going fullscreen on videos

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#38928] opened 2024-06-10 17:13 UTC
## Test plan
1. Fresh profile
2. In tab 1, visit YouTube.com and view a view
3. Click the full screen square icon in the bottom right of the video
4. You should see the "To exit full screen, press <kbd>esc</kbd>" message
5. Hit escape to go back to regular mode
6. In tab 2, visit brave://settings/system
7. Toggle the new `Show full screen reminder to press Esc on exit` setting to FALSE
8. Go back to tab 1
9. Click the full screen square icon in the bottom right of the video
10. You should NOT see the reminder from step 4

### Platforms

Linux, macOS, Windows

### Description

Folks should be able to turn off this message which shows each time they go fullscreen on a video in the browser
![image](https://github.com/brave/brave-browser/assets/4733304/a881c90e-84d3-434c-91e3-860babd19a85)

For example, Vivaldi has this configurable - under `Webpages` group in settings, with `Show Fullscreen Reminder` (defaulted to true).
![image](https://github.com/brave/brave-browser/assets/4733304/48cc5fce-f0ab-41a7-820b-e2e114d6f22e)

**Comment by bsclifton** [comment] 2024-06-10 17:14
This might be the code we need to intercept - if we had a new toggleable preference:
https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/exclusive_access/exclusive_access_manager.cc;l=76-92;drc=5c8e0b22fce77592e386624c5c25be6fad037958

cc: @rebron for prioritization

**Comment by jagadeshjai** [comment] 2024-06-11 04:02
Hi @bsclifton , I would like to take this task.

Clarification - Do you want me to use this Option `Show Fullscreen` Reminder for only tab-initiated fullscreen or including others as well(Like Browser initiated - F11).

**Comment by jagadeshjai** [comment] 2024-06-11 04:03
I think this toggle can be under the `Content` section in the settings page. What are your thoughts?

![image](https://github.com/brave/brave-browser/assets/45998266/ea43b8be-051c-49f6-a7e1-1ef92c7e08ba)

**Comment by rebron** [comment] 2024-06-11 04:56
@jagadeshjai Might be ok as a supported feature flag under brave://flags Our settings are overwhelming as it is.

**Comment by rebron** [comment] 2024-06-11 05:02
Alternatively, we could put it here. <img width="732" alt="Screenshot 2024-06-10 at 9 57 12 PM" src="https://github.com/brave/brave-browser/assets/5951041/9168452b-0d0d-40e8-ad73-759ada53bced">
`Show Full screen reminder to press esc on exit` below `Warn me before closing with multiple tabs`

**Comment by jagadeshjai** [comment] 2024-06-11 18:37
Sure @rebron  I can place it under `System` section.

However, I still want to clarify whether we only want to use this toggle for tab-initiated fullscreen and not for browser-initiated fullscreen. This will help ease the implementation in the first go :grinning: 

CC: @bsclifton

**Comment by bsclifton** [comment] 2024-06-12 23:30
Hi @jagadeshjai that would be great! I think this can easily be done using a chromium_src override for `chrome/browser/ui/views/frame/browser_view.cc`

Basically, we can replace the `BrowserView::UpdateExclusiveAccessBubble` method with a new method that checks the pref and exits if true. If pref is false, we can call the original Chromium method. I just verified this works great 😄

**Comment by bsclifton** [comment] 2024-06-12 23:32
> However, I still want to get clarified whether we only want to use this toggle for tab-initiated fullscreen and not for browser-initiated fullscreen. This will help ease the implementation in the first go 😀

@jagadeshjai I might need help understanding this. I guess the use-case would be if you have a video tag on a page and you click (or use shortcut key for) the fullscreen button
![image](https://github.com/brave/brave-browser/assets/4733304/77e2519a-8ace-49a5-97f1-180dc7a8ce1c)

**Comment by jagadeshjai** [comment] 2024-06-13 01:44
> Maybe you can try in Vivaldi and see how it does the F11 versus tab specific. Does toggling the preference hide for both?

Hi @bsclifton ,

I actually checked the other day. Vivaldi(on Linux) doesn't show the fullscreen reminder bubble by default, regardless of whether the Show Fullscreen Reminder option is turned on or off (there isn't an option to show it, though). Hence this option only affects tab-initiated fullscreen.

**Comment by jagadeshjai** [comment] 2024-06-13 01:47
> Here's the patch I tried (obviously we'd want to use the chromium_src override)
> 
> ```diff
> diff --git a/chrome/browser/ui/views/frame/browser_view.cc b/chrome/browser/ui/views/frame/browser_view.cc
> index 4b52ce3877855040f91fc48afdcbbd347e30a8c0..cd4a37e5adc3cc78c6e06fd130ab04ef120a10ab 100644
> --- a/chrome/browser/ui/views/frame/browser_view.cc
> +++ b/chrome/browser/ui/views/frame/browser_view.cc
> @@ -1961,6 +1961,10 @@ void BrowserView::ExitFullscreen() {
>  void BrowserView::UpdateExclusiveAccessBubble(
>      const ExclusiveAccessBubbleParams& params,
>      ExclusiveAccessBubbleHideCallback first_hide_callback) {
> +
> +  //BSC - test. Don't show the exit
> +  return;
> +
>    // Trusted pinned mode does not allow to escape. So do not show the bubble.
>    bool is_trusted_pinned =
>        platform_util::IsBrowserLockedFullscreen(browser_.get());
> ```

I guess this patch will probably hide both the tab-initiated and browser-initiated bubbles. I will check and confirm.

**Comment by jagadeshjai** [comment] 2024-06-13 19:52
> I guess this patch will probably hide both the tab-initiated and browser-initiated bubbles. I will check and confirm.

@bsclifton 
FYI: As expected, based on `params`, an appropriate bubble will be created. Since our primary goal is to only handle the bubble when going fullscreen on videos, I'll do something like this:

```
if (params.type == EXCLUSIVE_ACCESS_BUBBLE_TYPE_FULLSCREEN_EXIT_INSTRUCTION) {
  return;
}
```

**Closed** 2024-06-17 08:35 UTC
Labels: priority/P4, QA/Yes, release-notes/include, QA/Test-Plan-Specified, feature/video, feature-request, feature/settings, OS/Desktop

**Comment by stephendonner** [comment] 2024-07-08 21:40
## Verified `PASSED` using

```
Brave | 1.69.88 Chromium: 127.0.6533.26 (Official Build) nightly (x86_64)
-- | --
Revision | d60303973dc3604d9d348b981322a8a04dcbb86d
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by MadhaviSeelam** [comment] 2024-07-23 16:08
Adding `QA/Test-All-Platforms` label as it was mentioned in the issue description

**Comment by MadhaviSeelam** [comment] 2024-07-23 16:58
Verification `PASSED` using
```
Brave | 1.69.122 Chromium: 127.0.6533.57 (Official Build) beta (64-bit)
-- | --
Revision | bd77e9b76a8e67ff2bf9f62f1df7d60378ca811f
OS | Windows 11 Version 23H2 (Build 22631.3880)
```

#### Case One: `Show full screen reminder to press Esc on exit` defaulted to `On`/`Enabled`
<details>

### Steps:
1. installed `1.69.122`
2. launched Brave
3. opened `brave://settings/system`
4. confirmed `Show full screen reminder to press Esc on exit` was set to `Enabled`/`On` by default
5. loaded `https://www.youtube.com/watch?v=Qm846KdZN_c`
6. clicked on `View in Fullscreen`

### Confirmed `To exit full screen, press [Esc]` message shown
### Confirmed when clicked [Esc], regular mode is shown

step 4 | step 5| step 6
---------|---------|----------
![image](https://github.com/user-attachments/assets/637c0b3e-da1f-4e2b-a5b8-53c002c23a53)|![image](https://github.com/user-attachments/assets/4d8e424f-47f1-4089-b605-f8d923cbc251)|![image](https://github.com/user-attachments/assets/dead28cb-1026-4b53-8fef-67a27b69e97e)

</details>

#### Case Two: `Show full screen reminder to press Esc on exit` toggled to `Off`/`Disabled`
<details>

### Steps:

1. continue from  Case 1
2. opened `brave://settings/system`
4. toggled `Show full screen reminder to press Esc on exit` to `disabled`/`Off`
5. loaded `https://www.youtube.com/watch?v=Qm846KdZN_c`
6. clicked on `View in Fullscreen`

#### Confirmed `To exit full screen, press [Esc]` message is not shown 

step 4| step 5| step 6
---------|---------|----------
![image](https://github.com/user-attachments/assets/e965f753-fddb-4a16-9431-2852815e3e91)|![image](https://github.com/user-attachments/assets/ba544688-14b0-48df-9f54-a11d9a7ca005)|![image](https://github.com/user-attachments/assets/0b1be7e5-4b08-4576-9947-6360fd6265ec)

**Comment by MadhaviSeelam** [comment] 2024-07-29 23:42
Verification `PASSED` using
```
Brave	1.69.128 Chromium: 127.0.6533.73 (Official Build) beta (64-bit) 
Revision	715445841b1da480bcc24c12077a6dc926951996
OS	Linux
```

#### Case One: `Show full screen reminder to press Esc on exit` defaulted to `On`/`Enabled` - PASSED
<details>

### Steps:
1. installed `1.69.128`
2. launched Brave
3. opened `brave://settings/system`
4. confirmed `Show full screen reminder to press Esc on exit` was set to `Enabled`/`On` by default
5. loaded `https://www.youtube.com/watch?v=mFjU4JuJgnM`
6. clicked on `View in Fullscreen`

#### Confirmed `To exit full screen, press [Esc]` message shown
#### Confirmed when clicked [Esc], regular mode is shown

step 4 | step 5| step 6
---------|---------|----------
![image](https://github.com/user-attachments/assets/2932c442-ff61-4641-9a89-3b32cd47d001)|![image](https://github.com/user-attachments/assets/5f437a95-8d9f-4ed3-9b76-1b8c0c4915a6)|![image](https://github.com/user-attachments/assets/4b355011-cd55-4509-98c7-753a2314f700)


</details>

#### Case Two: `Show full screen reminder to press Esc on exit` toggled to `Off`/`Disabled` - PASSED
<details>

### Steps:

1. continue from  Case 1
2. opened `brave://settings/system`
4. toggled `Show full screen reminder to press Esc on exit` to `disabled`/`Off`
5. loaded `https://www.youtube.com/watch?v=mFjU4JuJgnM`
6. clicked on `View in Fullscreen`

#### Confirmed `To exit full screen, press [Esc]` message is not shown 

step 4| step 5| step 6
---------|---------|----------
![image](https://github.com/user-attachments/assets/14f05c8c-4d35-4512-891a-022cc7b89fc5)|![image](https://github.com/user-attachments/assets/d4c4023b-1774-4469-a404-1ac5ab578d0b)|![image](https://github.com/user-attachments/assets/86d46596-9322-4f49-806d-87cac3eb4c32)

**Comment by MariuzM** [comment] 2024-07-30 03:22
@MadhaviSeelam what is that? 
<img width="201" alt="image" src="https://github.com/user-attachments/assets/16350080-150c-4377-bffc-d4284f3e8659">

**Comment by MadhaviSeelam** [comment] 2024-07-30 20:40
Hi @MariuzM it's an existing functionality.  When `Show full screen reminder to press Esc on exit`, toggle is turned off, go full screen, and hover on top, the `X` shows up.  Also, can be verified this 1.68.131 as well. Just to reaffirm the fix is to show `To exit full screen, press [Esc]` message when the toggle is turned on.  Hope that answers your question. 

> @MadhaviSeelam what is that? 
<img alt="image" width="201" src="https://private-user-images.githubusercontent.com/36937039/353300594-16350080-150c-4377-bffc-d4284f3e8659.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNzA0OTksIm5iZiI6MTcyMjM3MDE5OSwicGF0aCI6Ii8zNjkzNzAzOS8zNTMzMDA1OTQtMTYzNTAwODAtMTUwYy00Mzc3LWJmZmMtZDQyODRmM2U4NjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDIwMDk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NDMyN2Y2OTY0ZmRmZGE5YTRlZjI4YmIyNjUwZDYyNzZhOGJhYzUxNWRiYzA4ODgxYjY1N2Q5NzE5ZTRmZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oGnNiCACEPhR5Y4JFSE7M64XcK_xKNtfz_mDfqhztjQ">

**Comment by bsclifton** [comment] 2024-09-06 21:57
@OptimusPrime91 what version are you using? You need to be on Brave 1.69.153 or higher

**Comment by HornyPrivateGamer** [comment] 2024-11-22 07:21
@bsclifton @rebron @MadhaviSeelam @OptimusPrime91 

An similar request from #42394

Request for an Option to Disable the Full-Screen 'X' Exit Button

Platforms
all, Windows

Description
For websites like YouTube, after entering full-screen mode on Windows, this grey X dot appears. However, this does not seem to be the case on macOS. Which has proven having "X" button will result in a worse user experience.

![Image](https://github.com/user-attachments/assets/5f5939f0-5833-4a74-9ab5-e1ef9868ef20)

It’s very distracting, much like the old “Esc to exit full screen” message, which we now thankfully have an option to disable. If we really want to exit full-screen mode, we can easily do it manually or by pressing "F" on YouTube. Having the ability to disable this X button should also be an option.

I’m sincerely asking for this feature to be added, similar to the option to disable the “Esc to exit full screen” message. Many users don’t like it, and this has been reported widely on platforms like Reddit, the Brave community, and Google forums.

Here are some examples (and there are plenty more):

https://community.brave.com/t/how-to-disable-this-fullscreen-x-exit-button/144391
https://support.google.com/chrome/thread/2757504/remove-black-circle-x-button-in-fullscreen-mode?hl=en
https://www.reddit.com/r/BoosteroidCommunity/comments/1d3fkmp/disable_exit_full_screen_button_for_chrome/
https://www.reddit.com/r/Diepio/comments/97nlnj/how_to_remove_chromes_x_dot_which_kicks_you_out/

Adding this option would help make Brave even more minimalistic, which could attract more users from Chrome. Plus more option is alwasy better than it will suite more people.

Thank you for reading, and please consider this request. Have a great day!

Brave Version: 1.73.89
Platform: Windows 11
Solution: Option to Disable the Full-Screen 'X' Exit Button

**Comment by StevenSchifter** [comment] 2025-01-30 17:39
I have another similar request: even though I have Settings > System > "Show full screen reminder to press Esc on exit" disabled, I see a message `To exit full screen, press and hold ESC` every time I press F11 to enter full screen.

**Comment by HornyPrivateGamer** [comment] 2025-01-31 13:25
> I have another similar request: even though I have Settings > System > "Show full screen reminder to press Esc on exit" disabled, I see a message `To exit full screen, press and hold ESC` every time I press F11 to enter full screen.
> 
> EDIT: I just discovered (and disabled) a flag that removes that particular message:
> 
> brave://flags/#press-and-hold-esc-to-exit-browser-fullscreen
> 
> However, I still get the message `To exit full screen, press F11` when pressing F11 to enter full screen.

yea in the same boat as you but sadly this is closed so it would be better than you open another issue
