### ISSUE TITLE
Vertical Tab Feature Not Working After Recent Update in Macos

### ISSUE THREAD

**Issue by Sohampatra1** [brave/brave-browser#33057] opened 2023-09-16 11:09 UTC
## Description 
After the recent update of Brave Browse in my Macbook Air M1, the vertical tab feature has stopped working. When attempting to use the vertical tab option, it fails to display the tabs in a vertical layout as intended. This issue is hindering the user experience and preventing efficient tab management.

## Steps to Reproduce

   1. Launch Brave Browser.
   3. Open multiple tabs.
   4. Go to Full screen
   5. Observe that the tabs are not displayed in a vertical layout.

## Actual result:

<img width="1440" alt="ISSUE" src="https://github.com/brave/brave-browser/assets/74552333/494c7e7c-8550-4ba4-a0f8-b44c6f71b948">

## Expected result:
Tabs Should be Visible At Left side

## Reproduces how often: 
After the recent update, the vertical tab feature is not functioning as expected. Clicking on the vertical tab icon does not display the tabs in a vertical layout.

## Brave version (brave://version info)
Version- v1.58.124
OS-Mac os

## Version/Channel Information:

- Can you reproduce this issue with the current release- yes
- Can you reproduce this issue with the beta channel? - not confirmed
- Can you reproduce this issue with the nightly channel? - not confirmed

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields- no
- Does the issue resolve itself when disabling Brave Rewards- no 
- Is the issue reproducible on the latest version of Chrome?- Yes

## Possible Solution:
It is recommended to investigate the recent update and identify any changes that may have caused the vertical tab feature to malfunction. Additionally, testing the feature on different operating systems and configurations may help pinpoint the root 
cause of the issue.

### Impact:
The inability to use the vertical tab feature affects users who rely on efficient tab management. This issue may lead to decreased productivity and frustration among users.
### Note:
Please let me know if any further information or clarification is required.

```[tasklist]
### Tasks
- [ ] https://github.com/brave/brave-browser/issues/33020
```

**Comment by kenherbert** [comment] 2023-09-16 12:53
Previous report of this issue: https://github.com/brave/brave-browser/issues/33020

Which MacOS version are you on? I don't see this problem on Monterey.

**Comment by Sohampatra1** [comment] 2023-09-16 15:39
> Previous report of this issue: #33020
> 
> Which MacOS version are you on? I don't see this problem on Monterey.

Macos Ventura 13.5.2.  // using macbook Air M1

**Comment by rebron** [comment] 2023-09-16 15:56
Closing as dupe of #33020

**Closed by rebron** 2023-09-16 15:56 UTC
Labels: OS/Desktop
