### ISSUE TITLE
Brave not honoring Short Time setting - W7

### ISSUE THREAD

**Issue by mjb51** [brave/brave-browser#2987] opened 2019-01-16 20:03 UTC
## Steps to Reproduce

   1. Set short time to HH:mm in Region and Language
   2. Open Brave

## Actual result:

![image](https://user-images.githubusercontent.com/7631637/51275160-26070700-199f-11e9-89b8-0bc683e7aa65.png)

![image](https://user-images.githubusercontent.com/7631637/51275244-61093a80-199f-11e9-8b54-d47c200240c3.png)

## Expected result:

Time would be displayed using OS regional setting, in this case 14:58.
## Brave version (brave://version info)

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows

### Reproducible on current release:  Unknown
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  n/a
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment] 2021-03-10 21:24
Closing as duplicate of https://github.com/brave/brave-browser/issues/7951

**Closed by bsclifton** 2021-03-10 21:24 UTC
Labels: feature/new-tab, priority/P5
