### ISSUE TITLE
"Not enough [[currency]]" shown in One-Time Tipping UI

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#14985] opened 2021-03-27 20:44 UTC
## Description 
One-time tipping UI doesn't show "tokens" in message.

## Steps to Reproduce
Attempt to issue a one-time tip with insufficient funds.

## Actual result:
![image](https://user-images.githubusercontent.com/815158/112734298-ea6b0e80-8f12-11eb-80f3-593fe04675e7.png)

## Expected result:
Named token should be replaced with appropriate locale string.

## Reproduces how often: 
Easily.

## Brave version (brave://version info)

Brave | 1.24.29 Chromium: 90.0.4430.41 (Official Build) nightly (64-bit)
-- | --
Revision | e9c92b1eaca8487e212f3f6bc081fdb6d4863759-refs/branch-heads/4430@{#723}

## Version/Channel Information:
- Can you reproduce this issue with the current release? No.
- Can you reproduce this issue with the beta channel? No.
- Can you reproduce this issue with the nightly channel? Yes.

**Comment by zenparsing** [comment] 2021-03-27 23:14
Duplicate of https://github.com/brave/brave-browser/issues/14973 (fixed in https://github.com/brave/brave-core/pull/8368)

**Closed** 2021-03-28 07:42 UTC
Labels: OS/Desktop, bug, feature/rewards, l10n, regression
