### ISSUE TITLE
Brave over Tor leaks time zone

### ISSUE THREAD

**Issue by suncloudsmoon** [brave/brave-browser#24090] opened 2022-07-17 02:10 UTC
## Description 

When using Brave over Tor, It supposedly leaks sensitive information, such as the time zone offset and time zone. 

## Steps to Reproduce

   1. Click on "new private window with Tor"
   2. Go to <a href="https://coveryourtracks.eff.org/">https://coveryourtracks.eff.org/</a>
   3. Once the website is loaded, click on "Test your Browser" button.

## Actual result:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/34616349/179380716-ad79d88b-83a8-4855-88e6-9a660580ff7b.png">

## Expected result:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/34616349/179380860-91128a08-d899-4d5e-b2cb-65e1e7e646a8.png">

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.41.96 Chromium: 103.0.5060.114 (Official Build) (64-bit)
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Windows 11 Version 21H2 (Build 22000.795)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
N/A
- Can you reproduce this issue with the nightly channel? 
N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
N/A

## Miscellaneous Information:

N/A

**Comment by neeythann** [comment] 2022-07-17 07:43
this might be related to https://github.com/brave/brave-browser/issues/8574

**Comment by diracdeltas** [comment] 2022-07-17 16:17
@rebron not sure if this is a regression or not. anyway https://github.com/brave/brave-browser/issues/15247 also leaks some of this info.

setting lang to the most common lang (english) might be too inconvenient for most users but i think we can set this one to UTC by default without too much inconvience

**Comment by ShivanKaul** [comment] 2023-03-10 20:48
dupe of https://github.com/brave/brave-browser/issues/27501

**Closed by ShivanKaul** 2023-03-10 20:48 UTC
Labels: closed/duplicate, privacy, feature/tor/leakproofing, OS/Desktop, privacy/discussed
