### ISSUE TITLE
Automatically remove known tracking parameters from URLs

### ISSUE THREAD

**Issue by snyderp** [brave/brave-browser#4537] opened 2019-05-22 17:39 UTC
Something like this (possibly longer list) and baked in:

https://greasyfork.org/en/scripts/10096-general-url-cleaner

Would be a nice 1-up-and-over on ITP 2.2

**Comment by fmarier** [comment] 2019-06-10 17:24
Maybe a dupe of #4239?

**Comment by snyderp** [comment] 2019-06-10 17:33
I wasn't sure if #4239 was about cookie life times or query parameters, or some combo of the two.  I mean't this to cover just the latter case.  No complaint to close this from me if you think thats covered by the other issue

**Comment by fmarier** [comment] 2019-06-10 21:26
You're right that #4239 is more generic in the sense that we could fix it in more than one way. Personally I'd be tempted to start with the easier solution of stripping out the query string params that are known trackers, as you suggested here.

I've added your link there, so I think we can close this one.

**Closed by fmarier** 2019-06-10 21:26 UTC
Labels: priority/P4, privacy, privacy/feature, privacy/tracking
