### ISSUE TITLE
Browser crashes when trying to switch to tab opened from split view

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#42518] opened 2024-11-26 07:54 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.75.48 Chromium: 131.0.6778.85
Operating System: Windows NT 10.0.22631

URL (if applicable) where crash occurred:

Can you reproduce this crash? 
Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Right click on a link and open in split view
2. Click on any link from the new split window to open a new tab
3. Switch back to split view and close the opened tab from step 1
4. Click on the tab opened in step 2, browser crashes

https://github.com/user-attachments/assets/fbfe1664-89ba-427a-8919-53dcd6b1e767

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/a6b21400-bd3e-f40c-0000-000000000000

cc: @iefremov @rebron @bsclifton

**Comment by bsclifton** [comment] 2024-11-26 08:18
cc: @simonhong

**Comment by simonhong** [comment] 2024-11-27 06:15
checking

**Comment by simonhong** [comment] 2024-11-27 08:36
When split view is used, next active tab candidate is different after closing active tab from with non split view.

In non split view,
1. Create any two tabs. Left tab is A right tab is B
2. Create a new background tab from tab B by using context menu's `Open link in new tab`
3. Close tab B
4. New active tab is a tab created at step 2

In split view,
1. Create a tab(tab A) and open split view from this tab
2. Second tab is new active tab (tab B)
3. Create a new background tab from tab B by using context menu's `Open link in new tab`
4. Close tab B
5. New active tab is tab A

I assume that this behavior change could make unexpected behavior or crash.

**Comment by simonhong** [comment] 2024-12-03 04:27
Tracked the old & new web contents notification from tab strip model.
There is one tab A and it's the active tab.
Created split view from tab A and paired tab B is created and it's active tab now.
Received active tab changed notification about old active contents is A and new active web contents is B.
So far so good.
Create another inactive tab C from tab B by `Open link in new tab` context menu over any link
Still tab B is active tab and didnt' receive any active tab changed notification becuase newly created tab C is opened as inactive tab.
Close current active tab B.
and received active tab changed notification as old active tab is tab C and new active tab is tab A.
This last notification info is wrong now. old active tab should be tab B because it was last active tab.

**Comment by simonhong** [comment] 2024-12-03 08:00
I found the cause. https://github.com/brave/brave-core/pull/23139 made this regression.
We subclassed to make tab activate whenever click split web contents.
But, this also make focus manager change active tab.
Focus manager should not change active tab state. Only user's click over web contents affects active tab state.

```
class ActivatableContentsWebView : public ContentsWebView {
  METADATA_HEADER(ActivatableContentsWebView, ContentsWebView)
 public:
  using ContentsWebView::ContentsWebView;
  ~ActivatableContentsWebView() override = default;

  ContentsWebView:
  void OnFocus() override {
    ContentsWebView::OnFocus();
    if (web_contents() && web_contents()->GetDelegate()) {
      web_contents()->GetDelegate()->ActivateContents(web_contents());
    }
  }
};
```

**Closed** 2024-12-04 00:40 UTC
Labels: bug, crash, priority/P2, QA/Yes, release-notes/exclude, OS/Desktop, split view
