### ISSUE TITLE
Conversion of initial url of a redirect is not triggered

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#8663] opened 2020-03-12 19:24 UTC
Found when testing https://github.com/brave/brave-browser/issues/6536

Redirects consist of initial url and landed url. 
Conversion will not happen when initial url is covered by url pattern

## Steps to Reproduce

   1. Follow steps from https://github.com/brave/internal/issues/718

## Actual result:

Conversion is not performed

## Expected result:
Conversion is performed

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.7.54 Chromium: 80.0.3987.132 (Official Build) nightly (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Ubuntu 18.04 LTS

Brave | 1.7.54 Chromium: 80.0.3987.132 (Official Build) nightly (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

cc @brave/legacy_qa @tmancey @jsecretan @rebron

**Comment by rebron** [comment] 2020-03-12 20:03
Will be fixed with #4026

**Comment by tmancey** [comment] 2020-05-29 10:15
Closing as duplicate of https://github.com/brave/brave-browser/issues/4026

**Comment by tmancey** [comment] 2020-07-31 18:22
Closing issue as will be resolved by https://github.com/brave/brave-browser/issues/11012

**Comment by btlechowski** [comment] 2020-09-08 15:16
The issue is still reproducible

Brave | 1.14.79 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Ubuntu 18.04 LTS

Also reproduced by @LaurenWags.

**Comment by tmancey** [comment] 2020-09-08 16:59
conversion urls do not support redirects, as conversion urls rely on the page you are currently viewing

**Closed by tmancey** 2020-09-08 16:59 UTC
Labels: QA/Yes, bug, feature/ads, priority/P3, release-notes/include
