### ISSUE TITLE
google contacts export error

### ISSUE THREAD

**Issue by 424344** [brave/brave-browser#23204] opened 2022-06-02 08:47 UTC
## Description 

I cannot save the contacts.csv file from https://contacts.google.com/
Using chrome works correctly.

## Steps to Reproduce

   1. load https://contacts.google.com/
   2. select export on the left and click "export" button
   3. select the save folder

## Actual result:

I get a network error
![image](https://user-images.githubusercontent.com/26486758/171592030-928efe46-0252-4016-8b1c-57f664e5ec5c.png)

I have tried disabling brave shields but it doesn't work.

## Expected result:
I want to save the contacts.

## Reproduces how often: 

always.

## Brave version (brave://version info)

Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by 424344** [comment] 2022-06-02 08:49
In the brave:downloads page I see this:
![image](https://user-images.githubusercontent.com/26486758/171592749-c52d974e-07e0-4861-a3aa-50de237f8a97.png)

**Comment by rebron** [comment] 2022-06-02 15:34
cc: @ryanbr I was able to reproduce this.

**Comment by ryanbr** [comment] 2022-06-03 04:16
Okay, discovered its related to this https://github.com/brave/brave-browser/issues/23171

The issue occured during to v1.39.41-> v1.39.42. Both https://github.com/brave/brave-browser/issues/23171 & https://github.com/brave/brave-browser/issues/23204 work fine `v1.39.41` and fails in `v1.39.42`

```
Nightly v1.39.70 (Chromium 101.0.4951.34)  BAD
Nightly v1.39.47 (Chromium 100.0.4896.79) BAD
Nightly v1.39.42 (Chromium 100.0.4896.79) BAD
Nightly v1.39.41 (Chromium 100.0.4896.79) Good
Nightly v1.39.40 (Chromium 100.0.4896.79) Good
```

**Comment by rebron** [comment] 2022-06-03 17:59
Closing as dupe of https://github.com/brave/brave-browser/issues/23171
Thanks @ryanbr

**Closed by rebron** 2022-06-03 17:59 UTC
Labels: google, OS/Desktop
