### ISSUE TITLE
Auto-completes for chrome:// but not brave://

### ISSUE THREAD

**Issue by kirkins** [brave/brave-browser#3665] opened 2019-03-11 16:44 UTC
## Description 

Wanted to use auto-complete to go to `brave://extensions`, isn't included but I noticed `chrome://extensions` is included.

## Steps to Reproduce

   1. type brave:// in url bar
   2. compare to chrome:// in url bar
   3. 

## Expected result:
Find extensions page in auto-complete.

## Reproduces how often: 

Always

## Brave version (brave://version info)

0.63.4 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by gabrielhug** [comment] 2019-03-12 19:49
Duplicate of #2951

**Comment by bsclifton** [comment] 2019-03-12 21:40
@gabrielhug great catch!

Thanks for the help recently with triaging issues 😄

**Closed** 2019-03-12 21:42 UTC
Labels: duplicate
