### ISSUE TITLE
promoCode is not claimed after going offline during installation

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1818] opened 2018-10-24 01:48 UTC
## Steps to Reproduce

1. (Important) Uninstall Brave Browser with User Data to have a Clean install
![image](https://user-images.githubusercontent.com/34715963/47382336-5e7da880-d702-11e8-9de3-68cf7495a568.png)
2. (On Windows )Download stub/mini installer and rename it to `BraveBrowserSetup-KAM253.exe`
3. Run the stub/mini installer
4. During installation  go offline
![image](https://user-images.githubusercontent.com/34715963/47400692-94d91900-d73e-11e8-81a2-97a62d0f1476.png)
5. After Brave is launched by installer, wait 60 seconds
6. Go online and wait another 60 seconds
7. Check if promoCode file exists
8. Check `Local State` file for `promo_code`

Note: `promoCode` and `Local State` files are located in `AppData\Local\BraveSoftware\Brave-Browser\User Data\` on Windows

## Actual result:

`promoCode` is not claimed
`promo_code` is not added to `Local State`

IMPORTANT: Combined with https://github.com/brave/brave-browser/issues/1811 the promoCode will never be claimed.

## Expected result:
`promoCode` is claimed
`promo_code` is added to `Local State`

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows 7 x64

@kjozwiak Can you check on Mac?
cc @srirambv @LaurenWags @GeetaSarvadnya @emerick

**Comment by emerick** [comment] 2018-10-24 16:05
The problem is that our attempt to contact the referral server will fail when you're offline. Once #1811 is fixed, this should no longer be a problem (although you would need to restart Brave after coming back online, as we only make the referral check at startup).

**Comment by emerick** [comment] 2018-10-25 00:04
Closing now that #1811 is merged. @btlechowski please let me know how it looks now (see above comment).

**Closed by emerick** 2018-10-25 00:04 UTC
Labels: OS/Windows, QA/Yes, feature/referral-promo

**Comment by GeetaSarvadnya** [comment] 2018-10-26 14:35
Verification passed on:

Brave | 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Windows

Local state file:
![image](https://user-images.githubusercontent.com/38657976/47573135-35575500-d95a-11e8-9feb-7496ef0be69a.png)

Build id and promo code added in Local state file after online:
download_id":"62a46706-a125-48f4-a916-0edab830b7c8","promo_code":"sge733"
