### ISSUE TITLE
[pin, unpin, pin again] to create chortcut [with app icon]

### ISSUE THREAD

**Issue by iamdtms** [brave/brave-browser#32289] opened 2023-08-16 13:12 UTC
## Description 
On **Windows 11** Pro 22H2 this issue available for months now...

## Steps to Reproduce
   1. When I create an app shortcut on taskbar, the icon not exist at the first time. Open as window checked. 
   2. Than unpin and pin again to solve it.

## Actual result:
Brave icon remains visible. 

## Expected result:
App icon would like to have. 

## Reproduces how often: 
10/~3 probably, I think it depends on how fast and/or the icon is available or etc. 

## Brave version (brave://version info)
Brave v1.57.47

## Version/Channel Information:
Windows 11 Pro 22H2

- Can you reproduce this issue with the current release?  
Yes

- Can you reproduce this issue with the beta channel? 
Probably

- Can you reproduce this issue with the nightly channel? 
Probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  
Not relevant

- Does the issue resolve itself when disabling Brave Rewards? 
Not relevant

- Is the issue reproducible on the latest version of Chrome? 
Do not think so, did not met with it

## Miscellaneous Information:
Thank you: https://github.com/iamdtms

**Comment by MadhaviSeelam** [comment] 2023-09-11 21:34
Closing as this is dupe of https://github.com/brave/brave-browser/issues/27558

**Closed by MadhaviSeelam** 2023-09-11 21:34 UTC
Labels: OS/Windows, OS/Desktop
