### ISSUE TITLE
Brave ads are blocked from any ISP, Real ISSUE!

### ISSUE THREAD

**Issue by MrWaste** [brave/brave-browser#12113] opened 2020-10-13 20:25 UTC
## Description 

I have tried many different IPs from google cloud or digital ocean and all FAIL. (10 or more)
None of them let these Catalogs go through. 
Even if its a clean IP address still blocked, it could be my other house you just blocked, thanks.

## Steps to Reproduce

   1. Watch Youtube Video
   2. https://www.youtube.com/watch?v=Ude5V0pYtiU

## Actual result:

Ads are Blocked and can't get to the AD Catalog.

## Reproduces how often: 

EVERYTIME

## Desktop Brave version:

Everything.

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the nightly channel? YES

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? NO

## Miscellaneous Information:

1. Watch Youtube Video
2. https://www.youtube.com/watch?v=Ude5V0pYtiU

**Comment by MrWaste** [comment] 2020-10-17 21:04
@bsclifton

Hi there, sorry for pinging you like this but didn't know what else to do because I haven't heard anything back yet. You and others have helped me in the past with just some of these issues and they are now fixed. Could you report this to something because this is huge problem for every device. Thank you for your time and hope to hear back if possible.

https://github.com/brave/brave-browser/issues/11586
https://github.com/brave/brave-ios/issues/2861

This still needs to get fixed for Ios
https://github.com/brave/brave-ios/issues/2906

**Comment by dodieboy** [comment] 2020-11-24 03:30
cloudflare dns also block brave ads from working

**Comment by bsclifton** [comment] 2020-12-03 18:14
cc: @tmancey @jsecretan

**Comment by jsecretan** [comment] 2020-12-03 18:23
Hi @dodieboy, can you say more about this?  When I check their DNS (1.1.1.1), I see our ads endpoint servers properly resolve.  Are you on their WARP solution or something?  Or using another one of their products?

**Comment by jsecretan** [comment] 2020-12-03 18:24
@MrWaste can you say more about your use case here?  Is your main browsing machine a computer in Google Cloud / Digital Ocean?

**Comment by MrWaste** [comment] 2020-12-03 22:35
@jsecretan I made a Pfsense Firewall to be an OpenVpn server inside of digital ocean or google cloud. Both don't work when putting in the domain url of brave ads. Doesn't matter for the Ip Address. The Dns is being sent over DOH to 1.1.1.1

I use 1.1.1.1 with DOH at my house and brave ads go through same with the domain url. I am sure I'm not using WARP what so ever. 

I have a feeling it has something to do because its digital ocean or google cloud. Or Brave has something wrong with the search but I didn't try the domain url inside of chrome. I deleted the servers because I can't use it.. I could remake it but it takes 2 hours ish..


If you looked at the video I can ping the domain just fine but when putting the search box, Nothing.. Removes the url from it, like it was never there.

**Comment by dodieboy** [comment] 2020-12-04 07:38
@jsecretan nope, i'm not using WARP solution. All i did was manual set my router dns to 1.1.1.1 and 1.0.0.1 in my router setting

**Comment by tmancey** [comment] 2021-03-12 15:01
Closing issue as cannot reproduce. @dodieboy @MrWaste If you are willing to screen-share I can help diagnose the cause of the issue. Thanks

**Closed by tmancey** 2021-03-12 15:01 UTC
Labels: OS/Desktop, feature/ads, needs-investigation

**Comment by MrWaste** [comment] 2021-03-15 20:29
It is still broken, I have a free idea for everyone to try.
I use the Proton VPN free servers. The brave ads server work such as the catalogs 1 - 7 in the USA if you go to the link below. 
Before if you used the cloud servers you could go to the link.

However, you don't receive any ads and is the same with this. @tmancey If you could use these servers and tell me if they work. I use Usa 2. It will take about 2-3 days to find out if your are going to receive brave ads from your new location. Because your on the vpn, it can take awhile to go through all of the ads without the vpn on.. I didn't notice receiving any ads. It doesn't happen right away, give it some time.


After typing this all out I had an idea, maybe its not the servers, maybe the location data because the browser actual knows your real location and the vpn location messes with it or something around those lines.

![Brave1](https://user-images.githubusercontent.com/49108816/111216836-235dc780-8592-11eb-8fbe-215c0e846a8d.png)


https://ads-serve.brave.com/v1/catalog
Change v(1-7)
