### ISSUE TITLE
Android - support AutoFill API

### ISSUE THREAD

**Issue by MadsBen** [brave/brave-browser#7007] opened 2019-11-19 11:19 UTC
On Android, please support the AutoFill API, to allow the use of 3rd party password managers, like Keepass2Android.

https://developer.android.com/guide/topics/text/autofill

Related:
https://github.com/PhilippC/keepass2android/issues/1044

**Comment by mrtumnus** [comment] 2021-11-30 21:03
This is a duplicate of #7355

**Comment by fallaciousreasoning** [comment] 2022-08-12 02:45
Closing this because it duplicates #7355 (thanks @mrtumnus)

**Closed by fallaciousreasoning** 2022-08-12 02:45 UTC
Labels: OS/Android
