### ISSUE TITLE
Progressive web app shortcuts are not working on Mac Intel/m1

### ISSUE THREAD

**Issue by heldr** [brave/brave-browser#21369] opened 2022-02-28 18:02 UTC
## Steps to Reproduce

   1. Go to [https://maps.google.com](https://maps.google.com) or any other PWA
   2. On Brave menu go to `More tools` -> `Create shortcut`, or click in `Install` on address bar
   3. Try to open app clicking on its icon

## Actual result:
![CleanShot 2022-02-28 at 09 53 20](https://user-images.githubusercontent.com/134727/156033752-9ddbac6c-7c99-4ffe-ba36-0654dce23a27.gif)

## Expected result:
Progressive web apps should open as desktop applications or a new Brave tab.

## Brave version (brave://version info)
Brave | 1.35.104 Chromium: 98.0.4758.109 (Official Build) (arm64) - ``
Revision | 03268453da2c7409eb1ee934d97abfc6f3b45420-refs/branch-heads/4758@{#1179}
OS | macOS Version 12.2.1 (Build 21D62)

## Version/Channel Information:
Issue also happens on Brave beta.

**Comment by jonthomason** [comment] 2022-02-28 18:22
In case this helps, on my Intel Mac, PWA's still work on my Home profile, but do not work with the update today on my Work profile. @heldr, do you have multiple profiles?

**Comment by heldr** [comment] 2022-02-28 18:26
@jonthomason just created 2 new profiles and none of them worked with twitter and YouTube pwas too.

**Comment by jonthomason** [comment] 2022-02-28 18:59
Just thought I'd check. No idea why PWA's still work on my home profile. I'm definitely seeing the same thing you're seeing on my Work profile.

**Comment by mengesb** [comment] 2022-03-01 03:45
I've noticed that since upgrading to macOS Monterey (12.2.1) AND updating Brave soon after I've not been able to open my Outlook PWA. I've tried a few other PWAs, including Brave's community PWA, and nothing is working. I get the same behavior as the OP, click to open, immediately crashes/dies/exits.

**Comment by bsclifton** [comment] 2022-03-01 05:32
Thanks for the report folks - we have a fix which we've verified 😄 We should have this released in the next few days

Closing as a duplicate of https://github.com/brave/brave-browser/issues/21302

**Closed by bsclifton** 2022-03-01 05:32 UTC
Labels: OS/Desktop
