### ISSUE TITLE
Reopen Issue #15825

### ISSUE THREAD

**Issue by BRAVERaaa** [brave/brave-browser#15853] opened 2021-05-14 08:17 UTC
Reopen Issue #15825

(Copy from https://github.com/brave/brave-browser/issues/15825#issuecomment-841090194)
Sorry for disturbing, but something different happens.
Few weeks ago, every time I clean cookies and cache then restart browser, the ID shown was different, and the IDs between normal window and incognito window were different as well.
But now, I try it again, the IDs between normal window and incognito window are the same!!! It is amazing!!!
I even have tried to change my ip, but the ID is always the same.
![PNG1](https://user-images.githubusercontent.com/84130904/118241431-b5b91380-b4ce-11eb-93cc-4f4db2770e4e.png)
![PNG2](https://user-images.githubusercontent.com/84130904/118241453-bd78b800-b4ce-11eb-960d-513ee92cb159.png)

Fingerprintjs seems to have updated. Maybe this is the cause.
![PNG3](https://user-images.githubusercontent.com/84130904/118241694-07fa3480-b4cf-11eb-80cc-8bcc9206bbb3.png)

**Comment by pes10k** [comment] 2021-05-18 03:46
I'm going to close this because there is no need to create an issue to reopen an issue (thats what the "reopen" button is for :P )

More seriously @BRAVERaaa , I appreciate you staying on us for this, its important we get this sorted. I expect the cause here is whats being discussed in https://github.com/brave/brave-browser/issues/15875, so lets discuss more there.  But, in parallel, i'll look into the currently deployed fingerprintpro js code and see if there are other signals they collect client side we can disrupt and perturb (we have some new blocking and farbling protections about to land and / or deployed as we speak fwiw)

**Closed by pes10k** 2021-05-18 03:46 UTC
Labels: OS/Android, OS/Desktop

**Comment by pes10k** [comment] 2021-05-18 03:49
And, just wanted to add, you are 100% not "disturbing".  I'm grateful for you taking the time to report this issue, especially when its something we've missed.  So please dont take me closing this issue as being unappreciative in any way.  Im only trying to consolidate issues so that its easier to keep track of whats open, whats being addressed by in-development changes, and what still needs to be sorted out.

Or, in other words, I'm very glad for your help, and its a much welcome-and-needed nudge to make sure we get the issues linked to above addressed :)
