### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by lutz36** [brave/brave-browser#36388] opened 2024-02-27 09:47 UTC
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.63.162 Chromium: 122.0.6261.69
Operating System: Mac OS X 12.7.3

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/4f4d0f00-b651-8c0b-0000-000000000000

**Comment by bsclifton** [comment] 2024-03-05 23:23
@lutz36 thanks for the report - do you have more information about what you were doing when this happened? Have you had any more crashes since?

**Comment by bsclifton** [comment] 2024-03-06 05:01
@lutz36 never mind - no need for a response 😄 

I believe this issue is a duplicate of https://github.com/brave/brave-browser/issues/35528 and that we have a fix! You can see https://github.com/brave/brave-core/pull/22468 for more info

Thanks for reporting!

**Closed by bsclifton** 2024-03-06 05:01 UTC
Labels: crash, OS/macOS, priority/P2, OS/Desktop
