### ISSUE TITLE
go-ipfs does not receive updates

### ISSUE THREAD

**Issue by Mubelotix** [brave/brave-browser#16171] opened 2021-06-01 11:36 UTC
## Description 

I have been using IPFS in Brave since it was launched. However, it is very slow and many peers seems to have troubles connecting to my node. I think it comes from the go-ipfs version installed by Brave, which is outdated (7.0). According to [this article](https://brave.com/ipfs-support/),

> The go-ipfs binary is downloaded and kept up to date by Brave if a local node is enabled. It uses the same update mechanism as extensions.

I have been waiting for months but go-ipfs is still not updated.
Note: Maybe it's only the webui.

## Steps to Reproduce

   1. Use IPFS in Brave
   2. Wait a few months
   3. go-ipfs is outdated

## Actual result:

![Screenshot](https://user-images.githubusercontent.com/42696684/120316474-c2ff3c00-c2dd-11eb-9a15-348aa512c98d.png)

## Expected result:

Brave should fetch go-ipfs newer versions. 

## Reproduces how often: 

At each go-ipfs update (once every few months)

## Desktop Brave version:

Latest since January.
Current: 1.23.73

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

I'm on Ubuntu 21.04. I have another `go-ipfs` installed outside Brave that works very well. I have been able to update it a few times.

**Comment by RubenKelevra** [comment] 2021-06-18 11:00
I can confirm this issue. The go-ipfs version is still 0.7 while 0.8 is out quite a while now. Additionally, 0.9 is already in the RC2 stage. So brave is lagging behind here.

**Comment by stephendonner** [comment] 2021-07-01 20:27
Thanks, all - we should be shipping this Real Soon Now (tm); testing has completed and you can keep track over in https://github.com/brave/brave-browser/issues/16578

**Comment by RubenKelevra** [comment] 2021-07-01 22:26
Great, thanks for the work!

**Comment by stephendonner** [comment] 2021-07-02 00:55
> Great, thanks for the work!

NP, and sorry for the delay.  We'll be getting our testing and release process smoothed out a bit more, which should mean (much) quicker updates when there's a released version of `go-ipfs`.

This shipped a few hours ago, and your clients should be updated or updating soon.

@spylogsster how did we want to resolve this issue?  Dupe of https://github.com/brave/brave-browser/issues/16578?

**Comment by spylogsster** [comment] 2021-07-02 08:45
yes, lets wait update for 0.9.0

**Comment by RubenKelevra** [comment] 2021-07-12 15:06
This can be closed, it's fixed. :)

**Closed** 2021-08-03 08:23 UTC
Labels: OS/Android, OS/Desktop
