### ISSUE TITLE
Ads displaying on YouTube even with Shields Enabled

### ISSUE THREAD

**Issue by irlcatgirl** [brave/brave-browser#8797] opened 2020-03-21 04:34 UTC
## Description 

Even with Brave Shields enabled ads are showing up on YouTube

## Steps to Reproduce

   1.  Visit https://www.youtube.com/watch?v=J1Fxl4cGVd4 with shields enable
   2.  Scroll down
   3.  See advertisements

## Actual result:

![Screenshot from 2020-03-21 00-31-38](https://user-images.githubusercontent.com/8227641/77219362-821d6c00-6b0b-11ea-847d-2201fd9167dc.png)

## Expected result:

YouTube to load without ads.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Linux
JavaScript | V8 8.0.426.26
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,VideoPlaybackQuality,WebXrGamepadModule,NotificationTriggers,SmsReceiver,AudioServiceOutOfProcess,LookalikeUrlNavigationSuggestionsUI,WebXR --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/nathaniel/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by outforpublic** [comment] 2020-03-23 18:40
Unable to reproduce on Brave Nightly latest version (may already be patched in nightly but not in beta or stable)

Brave | 1.8.25 Chromium: 80.0.3987.149 (Official Build) nightly (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1909 (Build 18363.720)
JavaScript | V8 8.0.426.27
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Command Line | "C:\Users\Fred\AppData\Local\BraveSoftware\Brave-Browser-Nightly\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,DnsOverHttps,MixedContentSiteSetting,SimplifyHttpsIndicator,PassiveMixedContentWarning,AutoupgradeMixedContent,WebUIDarkMode --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,NotificationTriggers,SmsReceiver,AudioServiceOutOfProcess,LookalikeUrlNavigationSuggestionsUI,VideoPlaybackQuality --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | C:\Users\Fred\AppData\Local\BraveSoftware\Brave-Browser-Nightly\Application\brave.exe
Profile Path | C:\Users\Fred\AppData\Local\BraveSoftware\Brave-Browser-Nightly\User Data\Default
Variations | 5e3a236d-59e286d0

**Comment by rebron** [comment] 2020-05-08 16:23
Closing as dupe of #3348 
@irlcatgirl Will add a +1 for you #3348.

**Closed by rebron** 2020-05-08 16:23 UTC
