### ISSUE TITLE
Back arrow bug

### ISSUE THREAD

**Issue by dryspeed** [brave/brave-browser#35036] opened 2023-12-24 15:26 UTC
https://github.com/brave/brave-browser/assets/142707208/11d896a5-2cbd-4bb3-a1a8-5b0a97087925

While using back gesture, an another arrow is being displayed.
Version: Sonoma 14.2.1
---
Version 1.61.109 Chromium: 120.0.6099.144 (Official Build) (arm64)
cc: @rebron @LaurenWags

**Comment by valynor** [comment] 2023-12-24 23:04
Yeah, I reported that in #34109 a while ago .. no reaction.

**Comment by rebron** [comment] 2023-12-25 18:38
closing as duplicate of #34109

**Closed by rebron** 2023-12-25 18:38 UTC
Labels: closed/duplicate, OS/Desktop
