### ISSUE TITLE
[Android] Gestures not working

### ISSUE THREAD

**Issue by brokoli-mate** [brave/brave-browser#9160] opened 2020-04-13 01:41 UTC
## Description 
Swipe gestures(left/right from the edges) do not work as back forward page

## Steps to reproduce 

   1. Open browser
   2. Open few pages
   3. Swipe left/right from sceen edges

## Actual result 
nothing happens

## Expected result
Forward or back page

## Issue reproduces how often 
Easily reproduced

## Issue happens on 
   - Current Play Store version? yes
   - Beta build?

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version:9
   
## Brave version
1.5.131, chromium 80.0.39.87.162

**Comment by srirambv** [comment] 2020-04-13 05:32
Dupe of #7362

**Closed by srirambv** 2020-04-13 05:32 UTC
Labels: OS/Android
