### ISSUE TITLE
How to import bookmarks?

### ISSUE THREAD

**Issue by p3yot3** [brave/brave-browser#16148] opened 2021-05-31 14:00 UTC
I can't find the import option anywhere on android - how to import my bookmarks?

**Comment by srirambv** [comment] 2021-06-01 03:49
Currently this is not supported. Since you already replied [here](https://github.com/brave/brave-browser/issues/6378#issuecomment-851510285), going to close this issue as duplicate of #6378.

**Closed by srirambv** 2021-06-01 03:49 UTC
Labels: OS/Android
