### ISSUE TITLE
Hulu.com unable to get location for live tv.

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#12083] opened 2020-10-12 00:07 UTC
## Description 
Hulu.com (live TV) unable to get location when requested, 

## Steps to Reproduce

   1.  Login to `Hulu.com` and livetv subscription, and open livetv option.
   2. Hulu asks for me to share my location, and after I select “allow” it cannot load. Instead it chews on the request either indefinitely, or errors out with “unable to find your location - get help.”

## Actual result:
Unable to get location data for hulu.com livetv.

## Expected result:
Expect `hulu.com` to get location details for livetv option.

## Reproduces how often: 
Need a US hulu account, with livetv enabled.

## Brave version (brave://version info)
`Version 1.15.72 Chromium: 86.0.4240.75 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Unsure
- Can you reproduce this issue with the nightly channel? Unsure.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Reported here: https://community.brave.com/t/hulu-unable-to-get-location-and-load/165895/6

Have tested `hulu.com` which playback worked fine. Just unable to test the livetv option.

**Comment by Haydn-010** [comment] 2020-10-13 22:22
Hello,
I am currently having this issue as-well. The issue just started recently with my setup ( I don't know what update exactly broke this sorry)

I am running version Version 1.15.72 Chromium: 86.0.4240.75 (Official Build) (64-bit)

Disabling the shields did not fix this issue.
Disabling rewards did not fix the issue.
The issue is not reproducible in chrome, it works as intended there.

**Comment by Haydn-010** [comment] 2020-10-23 22:30
Hello, 
this issue was resolved with the latest update

**Comment by bsclifton** [comment] 2020-10-26 07:15
@ryanbr can you retest?

@Haydn-010 thanks for the update 😄

**Comment by ethanpmullen** [comment] 2020-12-20 05:46
This issue was temporarily resolved but I'm having this problem again

**Comment by rebron** [comment] 2021-01-22 16:47
@ethanpmullen Are you still having issues with our latest 1.19.86? Looks like this was resolved for @Haydn-010.

**Comment by ethanpmullen** [comment] 2021-01-22 16:48
It works again, just went a few months without it working

**Comment by rebron** [comment] 2021-01-22 16:53
@ethanpmullen Cool thanks for checking! If you run into again please create a new issue.

**Closed by rebron** 2021-01-22 16:53 UTC
Labels: OS/Desktop, priority/P3, webcompat
