### ISSUE TITLE
DumpWithoutCrashing in updater::DoPeriodicTasks

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#41650] opened 2024-10-15 18:44 UTC
https://share.backtrace.io/api/share/9HM2hVx2B4DsC2bIkECEGV1
```
[ 00 ] crash_reporter::DumpWithoutCrashing() ( crashpad.cc:267 )
[ 01 ] base::debug::DumpWithoutCrashing(base::Location const&, base::TimeDelta) ( dump_without_crashing.cc:108 )
[ 02 ] logging::(anonymous namespace)::DumpWithoutCrashing(base::debug::CrashKeyString*, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>> const&, base::Location const&, base::NotFatalUntil) ( check.cc:117 )
[ 03 ] logging::(anonymous namespace)::CheckLogMessage::~CheckLogMessage() ( check.cc:168 )
[ 04 ] logging::(anonymous namespace)::CheckLogMessage::~CheckLogMessage() ( check.cc:166 )
[ 05 ] logging::(anonymous namespace)::CheckLogMessage::~CheckLogMessage() ( check.cc:166 )
[ 06 ] std::__Cr::default_delete<logging::LogMessage>::operator()(logging::LogMessage*) const ( unique_ptr.h:69 )
[ 07 ] std::__Cr::unique_ptr<logging::LogMessage, std::__Cr::default_delete<logging::LogMessage>>::reset(logging::LogMessage*) ( unique_ptr.h:281 )
[ 08 ] logging::CheckError::~CheckError() ( check.cc:335 )
[ 09 ] logging::CheckError::~CheckError() ( check.cc:325 )
[ 10 ] base::internal::AssertBlockingAllowed() ( thread_restrictions.cc:54 )
[ 11 ] base::ScopedBlockingCall::ScopedBlockingCall(base::Location const&, base::BlockingType) ( scoped_blocking_call.cc:46 )
[ 12 ] base::ScopedBlockingCall::ScopedBlockingCall(base::Location const&, base::BlockingType) ( scoped_blocking_call.cc:41 )
[ 13 ] base::PathExists(base::FilePath const&) ( file_util_posix.cc:596 )
[ 14 ] updater::DoPeriodicTasks(base::OnceCallback<void ()>) ( scheduler_mac.cc:69 )
[ 15 ] base::OnceCallback<void ()>::Run() && ( callback.h:156 )
[ 16 ] base::TaskAnnotator::RunTaskImpl(base::PendingTask&) ( task_annotator.cc:203 )
[ 17 ] void base::TaskAnnotator::RunTask<base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*)::$_3>(perfetto::StaticString, base::PendingTask&, base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*)::$_3&&) ( task_annotator.h:90 )
[ 18 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) ( thread_controller_with_message_pump_impl.cc:470 )
[ 19 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:332 )
[ 20 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:0 )
[ 21 ] base::MessagePumpCFRunLoopBase::RunWork() ( message_pump_apple.mm:450 )
[ 22 ] base::apple::CallWithEHFrame(void () block_pointer)
[ 23 ] base::MessagePumpCFRunLoopBase::RunDelayedWorkTimer(__CFRunLoopTimer*, void*) ( message_pump_apple.mm:405 )
[ 24 ] __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
[ 25 ] __CFRunLoopDoTimer
[ 26 ] __CFRunLoopDoTimers
[ 27 ] __CFRunLoopRun
[ 28 ] CFRunLoopRunSpecific
[ 29 ] 0x7ff81fc86a09
[ 30 ] 0x7ff81fc86816
[ 31 ] 0x7ff81fc86561
[ 32 ] 0x7ff8188d7171
[ 33 ] 0x7ff8191ebaf0
[ 34 ] __71-[BrowserCrApplication nextEventMatchingMask:untilDate:inMode:dequeue:]_block_invoke ( chrome_browser_application_mac.mm:335 )
[ 35 ] base::apple::CallWithEHFrame(void () block_pointer)
[ 36 ] -[BrowserCrApplication nextEventMatchingMask:untilDate:inMode:dequeue:] ( chrome_browser_application_mac.mm:334 )
[ 37 ] 0x7ff8188c8585
[ 38 ] base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*) ( message_pump_apple.mm:807 )
[ 39 ] base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) ( message_pump_apple.mm:161 )
[ 40 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ( thread_controller_with_message_pump_impl.cc:640 )
[ 41 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ( thread_controller_with_message_pump_impl.cc:0 )
[ 42 ] base::RunLoop::Run(base::Location const&) ( run_loop.cc:134 )
[ 43 ] content::BrowserMainLoop::RunMainMessageLoop() ( browser_main_loop.cc:1102 )
[ 44 ] content::BrowserMainRunnerImpl::Run() ( browser_main_runner_impl.cc:156 )
[ 45 ] content::BrowserMain(content::MainFunctionParams) ( browser_main.cc:34 )
[ 46 ] content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams, bool) ( content_main_runner_impl.cc:732 )
[ 47 ] content::ContentMainRunnerImpl::Run() ( content_main_runner_impl.cc:1162 )
[ 48 ] content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) ( content_main.cc:356 )
[ 49 ] content::ContentMain(content::ContentMainParams) ( content_main.cc:369 )
[ 50 ] ChromeMain ( chrome_main.cc:231 )
[ 51 ] main ( chrome_exe_main_mac.cc:218 )
[ 52 ] start
```

**Comment by mherrmann** [comment] 2024-10-16 12:21
I believe this is a duplicate of #41360.

**Closed by mherrmann** 2024-10-16 12:21 UTC
Labels: crash, OS/macOS, priority/P2
