### ISSUE TITLE
Issue with the tradingview chart on bitmex.com

### ISSUE THREAD

**Issue by khayto** [brave/brave-browser#9521] opened 2020-04-29 02:45 UTC
Been having this issue for the longest time, figured id finally post about it.

When using brave to go on Bitmex.com the tradingview chart isnt fully visible, price is hidden in the margin, and brave is the only browser that does that.

just visit bitmex.com and you'll see, i believe it does it for everyone since ive seen others post about it on reddit. 

screenshot : https://imgur.com/a/tx84kUa

**Comment by bsclifton** [comment] 2020-05-06 05:47
@khayto is this still happening? or is the problem resolved?

**Comment by ryanbr** [comment] 2020-05-10 09:43
Maybe be related https://github.com/brave/brave-browser/issues/3412

**Comment by ryanbr** [comment] 2020-05-10 09:45
@khayto  If you allow fingerprinting in Shields on the site, does it help?

**Comment by khayto** [comment] 2020-05-10 11:00
@ryanbr oh i hadnt even considered it. disabling shield does work ty.

**Comment by pes10k** [comment] 2021-04-02 22:16
Can't reproduce, and should be fixed by farbling

**Closed by pes10k** 2021-04-02 22:16 UTC
Labels: closed/not-actionable, webcompat, workaround/shields-down
