### ISSUE TITLE
Google Sheets not working correct since latest update. v78

### ISSUE THREAD

**Issue by thommesborg** [brave/brave-browser#6618] opened 2019-10-26 07:22 UTC
## Description 
<Since latest update to Version 0.70.121 Chromium: 78.0.3904.70 (Offizieller Build) (64-Bit), Google Sheets won't be displayed correctly. As my English is not so perfect, please have a look at the screenshots below.>

## Steps to Reproduce

   1. Open a Google Spreadsheet
   2. See the content in each cell slided out of the cells
   3. 

## Actual result:
Brave doesn't show GSheets correctly.
<img width="1410" alt="Bildschirmfoto 2019-10-26 um 09 02 45" src="https://user-images.githubusercontent.com/40795115/67615828-4cc95800-f7d1-11e9-88ab-d56f5418a1a3.png">
Brave result

## Expected result:
Brave should show this sheet like Chrome does.
<img width="1410" alt="Bildschirmfoto 2019-10-26 um 09 03 44" src="https://user-images.githubusercontent.com/40795115/67615839-64084580-f7d1-11e9-9cfd-d0908eb8d4e7.png">
Chrome result

## Reproduces how often: 
Everytime 

## Brave version (brave://version info)
Version 0.70.121 Chromium: 78.0.3904.70 (Offizieller Build) (64-Bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? not in use
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment] 2019-11-15 17:44
@thommesborg Looks like this works with shields down. Could also probably go into advanced view and allow all device recognition attempts for just Google sheets? Does that work for you?

**Comment by thommesborg** [comment] 2019-11-15 19:25
Hi @rebron I confirm with shields down it works as expected.

**Comment by snyderp** [comment] 2020-02-13 22:37
fwiw, just got an email about this.  I dont think we should leave Google Sheets bugs as P5, seems like its gotta be P3, given how popular the service is.  WDYT?

**Comment by ryanbr** [comment] 2020-02-14 01:06
Hey @thommesborg can you supply a shared link of the Google sheet? Just so we can reproduce the issue, and see what is causing it

**Comment by thommesborg** [comment] 2020-02-14 07:21
Ho @ryanbr like I've replied here: https://github.com/brave/brave-browser/issues/6618#issuecomment-554494822 with shields down it works. 

There is nothing else in this sheet like text an numbers. You cab easily build your own sheet for testing. This one is shared with the team and is work in process.

**Comment by ryanbr** [comment] 2020-02-14 08:27
I couldn't reproduce it here, even with plain text. Just a sample shared sheet would help

**Comment by thommesborg** [comment] 2020-02-14 08:40
@ryanbr for the moment I have to rely on a stable service, so I'm on the run with my Chromebook. I can't check the latest version of Brave on this device, because it's a Chromebook. 

If you can't repro the issue, maybe it got fixed in between. Will check next time when back home and the MacBook is in reach.

**Comment by akshaybhalotia** [comment] 2020-05-14 13:02
I came here looking exactly for this. Somehow this is a tricky one. I'll keep posting my findings here, since G Sheet is an essential part of my workflow.

1. The scrambled view appears when opening a Google Sheet (author could be yourself or someone else but given sheet must not have been created in this browser), but not when creating a new one, even if you copy paste the same data. Probably why @ryanbr wasn't able to repro.
2. Works fine with shields up except fingerprinting. The number of blocks used to be 3 before, reduced to 1. 
![image](https://user-images.githubusercontent.com/9196911/81937410-35d54080-9611-11ea-9a79-57e135833150.png)

3. Once allowing fingerprint and then blocking it again seems to resolve the issue permanently. Number of blocked content remains at 1 instead of going back to 3. Even opening new sheets which have previously never been opened in this browser seem to work correctly. Looks like some cookie being set in the fingerprinting process that "enables" the correct render.

**Comment by akshaybhalotia** [comment] 2020-05-14 13:05
Could not attempt trying in private more before disabling the fingerprint experiment. Cannot reproduce after, so not sure if this is consistent.

**Comment by pes10k** [comment] 2020-05-15 03:33
I can't reproduce either.  I expect our new fingeprinting protections will solve, and that this is related to us blocking some font-measurement APIs in the previous fingerprinting protections system.

If anyone is still seeing, could you share a link to a google doc thats showing the problem (even if its in read-only mode) and I can figure out exactly whats going on with this and fingerprinting protections?  Otherwise, if no one is still seeing, lets close the issue

**Comment by thommesborg** [comment] 2020-05-15 04:15
@pes10k hi, so for me the issue is solved. If I go to the sheet I had trouble with at the time I started this bug, it looks well now.

<img width="1355" alt="Bildschirmfoto 2020-05-15 um 06 13 16" src="https://user-images.githubusercontent.com/40795115/82010809-6b127a80-9673-11ea-8f92-84c2665780d8.png">

Cheers,
Thomas

**Closed** 2020-05-15 04:17 UTC
Labels: feature/shields, google, priority/P3, webcompat, workaround/shields-down
