### ISSUE TITLE
Option for setting time zone

### ISSUE THREAD

**Issue by RoofLee** [brave/brave-browser#5282] opened 2019-07-18 16:17 UTC
## Description 
Currently brave browser haven't an option to set custom time zone. So it seriously destruct anonymous status. Because when I connect to some VPN I want to set time zone of server location to prevent leak. Some shit is exist in Linken Sphere Browser.

## Steps to Reproduce

   1. Add option to choose time zone for browser

## Actual result:
More respectful by community and settings for time zone

**Comment by bsclifton** [comment] 2019-07-22 07:37
Closing as dupe of https://github.com/brave/brave-browser/issues/2965

**Closed by bsclifton** 2019-07-22 07:37 UTC
Labels: priority/P5, privacy, suggestion
