### ISSUE TITLE
[Desktop] Search Engines added by Extensions unavailable in Private Window

### ISSUE THREAD

**Issue by ppittle** [brave/brave-browser#10601] opened 2020-07-08 03:37 UTC
## Description 

Search Engines added by Extensions can't be referenced by _Keyword_ + <kbd>Tab</kbd> in Private Window

![image](https://user-images.githubusercontent.com/1190907/86871939-164a1980-c090-11ea-9272-7b0cbf3d90ed.png)

```cucumber
Given the user has installed an Extension which adds a Search Engine
And the user has modified the Extension so that "Allow in private" is true.

Given the user is in a Private Window
And the Address Bar has Focus
When the user types the Extension's Search Keyword and presses Tab

Then further input is directed to the Extension's Search Engine
```

Scenario fails for Private Window:
![image](https://user-images.githubusercontent.com/1190907/86872279-d3d50c80-c090-11ea-92e0-fe3b1bd60c22.png)

Works with a 'normal' Window:

![image](https://user-images.githubusercontent.com/1190907/86872554-7e4d2f80-c091-11ea-911d-9890bc3de5e8.png)

## Steps to Reproduce

   1.  Install an Extension that Provides a Search Engine.  I used **LastPass**
       
> `brave://settings/searchEngines`
>
> ![image](https://user-images.githubusercontent.com/1190907/86871939-164a1980-c090-11ea-9272-7b0cbf3d90ed.png)

   2. Ensure the Extension is available in Private

> brave://extensions/?id=hdokiejnpimakedhajhdlcegeplioahd
> 
> ![image](https://user-images.githubusercontent.com/1190907/86872070-61642c80-c090-11ea-9d3c-ccdb7d44e538.png)

   3. Open a new Private Window
   4. Focus the Address Bar
   5. Type the Extension's Search Engine Keyword and press <kbd>Tab</kbd>.  (In the case of LastPass, it's `lp`) 

## Actual result:

![image](https://user-images.githubusercontent.com/1190907/86872279-d3d50c80-c090-11ea-92e0-fe3b1bd60c22.png)

<kbd>Tab</kbd> Cycles through the History list that appears in the Address bar.  Control is not routed to the Extension's Search Engine.

## Expected result:
Private Window should behave as a 'normal' Window does.  Input should be routed to the Extension's Search Engine

![image](https://user-images.githubusercontent.com/1190907/86872554-7e4d2f80-c091-11ea-911d-9890bc3de5e8.png)

## Reproduces how often: 

Always reproduces

## Brave version (brave://version info)

```

Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Windows 10 OS Version 1909 (Build 18363.900)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?   **YES**
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?   **NO**
- Does the issue resolve itself when disabling Brave Rewards?  **NO**
- Is the issue reproducible on the latest version of Chrome?  **NO**

![image](https://user-images.githubusercontent.com/1190907/86872236-b7d16b00-c090-11ea-8632-ddebc9d7e1c8.png)

**Comment by atahabaki** [comment] 2020-08-04 03:56
Hi!..

I'm facing that too...

I've developed a Chrome extension which uses Chromium's [Omnibox API](https://developer.chrome.com/extensions/omnibox) for quickly search anything, anywhere. Then uploaded it to Chrome web store which I called it "[smartbox: Smart Searching](https://chrome.google.com/webstore/detail/smartbox-smart-searching/ligbhhoebpfhhafppbnieajgokmcccah)".

If you're interested in, you can take a look at [here](https://chrome.google.com/webstore/detail/smartbox-smart-searching/ligbhhoebpfhhafppbnieajgokmcccah).

It works pretty well with Google Chrome (works on incognito mode too). On Brave, it is not working.

Please fix this issue. Maybe this is not an issue but. Make an exception for this to work on both private and Tor sessions too.

Have a great day.

**Comment by bsclifton** [comment] 2020-10-27 22:33
Related (or possible duplicate of) https://github.com/brave/brave-browser/issues/10549

**Comment by atahabaki** [comment] 2020-10-28 02:37
> Related (or possible duplicate of) https://github.com/brave/brave-browser/issues/10549

None of them (#10601 and #10549) is solved. 10601 is the most similar one.

Thanks for the reply.

**Comment by ppittle** [comment] 2020-11-05 01:12
Agree this and #10549 appear to be the same root issue.  But I will point out, mine has more pictures :D

**Closed** 2021-05-14 14:53 UTC
Labels: OS/Desktop, QA/Yes, feature/extensions, feature/search, priority/P4, release-notes/include

**Comment by stephendonner** [comment] 2021-05-17 23:09
Verified `PASSED` using the testplan from https://github.com/brave/brave-core/pull/8626 with build 

Brave | 1.26.22 Chromium: 91.0.4472.57&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | e3443317fa07f1e9997e4a9c738eddfefc3c0292-refs/branch-heads/4472_54@{#6}
OS | macOS Version 11.3.1 (Build 20E241)

Steps:

1. clean profile, launched Brave
2. installed Ecosia extension - `https://chrome.google.com/webstore/detail/ecosia-the-search-engine/eedlgdlajadkbbjoobobefphmfkcchfk/related`
3. confirmed Normal window's default search provider is ecosia
4. opened private window and confirmed ecosia is default search provider
5. toggled DDG button to `On` and confirmed it doesn't change the search provider - still using Ecosia
6. toggled DDG button to `Off` and confirmed it doesn't change the search provider - still using Ecosia
7. in `brave://extensions`,  on the Ecosia extension details page, I toggled `Allow in private` on and off
8. confirmed changing `Allow in private` option doesn't affect private window's search provider - still using Ecosia
9. disabled Ecosia extension and check normal and private windows use default search provider - uses Google
10. toggled DDG button to `On` in Private  and confirmed search provider is changed to DuckDuckGo

steps 1-2 | step 3 | step 4 | step 5 | step 6 | step 7 | step 8 | step 9 | step 10
---------|----------|---------|----------|---------|----------|----------|---------|----------
<img width="1312" alt="Screen Shot 2021-05-17 at 3 56 37 PM" src="https://user-images.githubusercontent.com/387249/118566951-c913eb00-b729-11eb-8608-e43f63312f98.png"> | <img width="1312" alt="Screen Shot 2021-05-17 at 3 57 28 PM" src="https://user-images.githubusercontent.com/387249/118566954-c9ac8180-b729-11eb-9303-081422564ba3.png"> | <img width="1312" alt="Screen Shot 2021-05-17 at 3 57 45 PM" src="https://user-images.githubusercontent.com/387249/118566956-c9ac8180-b729-11eb-9b9c-13c84b794abb.png"> | <img width="1312" alt="Screen Shot 2021-05-17 at 3 58 12 PM" src="https://user-images.githubusercontent.com/387249/118566957-ca451800-b729-11eb-8aab-6acfd0e949ec.png"> | <img width="1312" alt="Screen Shot 2021-05-17 at 3 58 23 PM" src="https://user-images.githubusercontent.com/387249/118566960-caddae80-b729-11eb-90b9-f3e37e988b09.png"> | <img width="1312" alt="Screen Shot 2021-05-17 at 4 03 18 PM" src="https://user-images.githubusercontent.com/387249/118566961-caddae80-b729-11eb-8062-c903904ddc73.png"> | <img width="1312" alt="Screen Shot 2021-05-17 at 4 04 19 PM" src="https://user-images.githubusercontent.com/387249/118566964-cb764500-b729-11eb-8f10-05bdd8c1dfe6.png"> | <img width="1312" alt="Screen Shot 2021-05-17 at 4 04 36 PM" src="https://user-images.githubusercontent.com/387249/118566965-cb764500-b729-11eb-814c-e9a2f3ae4c83.png"> | <img width="1312" alt="Screen Shot 2021-05-17 at 4 04 59 PM" src="https://user-images.githubusercontent.com/387249/118566966-cc0edb80-b729-11eb-8464-ca9320dd9a40.png">

**Comment by LaurenWags** [comment] 2021-06-01 16:10
Testing https://github.com/brave/brave-core/pull/8626 will cover the following issues:
- https://github.com/brave/brave-browser/issues/15224 
- https://github.com/brave/brave-browser/issues/10601 (this issue)
- https://github.com/brave/brave-browser/issues/14218
