### ISSUE TITLE
"Continue where you left off" doesn't work on macOS

### ISSUE THREAD

**Issue by gabriellovate** [brave/brave-browser#22065] opened 2022-04-04 12:55 UTC
## Description 
The “Continue where you left off” option does not work as intended upon closing the window. 

## Steps to Reproduce
   1. Check the option “Continue where you left off” on Settings > Get started > On start-up
   2. Close Brave
   3. Open Brave

## Actual result:
Instead of opening the previously opened tabs, it opens a blank page.

## Expected result:
Opening the previously opened tabs. 

## Reproduces how often: 
It happens every time.

## Brave version (brave://version info)
Brave | 1.37.109 Chromium: 100.0.4896.60 (Official Build) (arm64)
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | macOS Version 12.3.1 (Build 21E258)

**Comment by rebron** [comment] 2022-04-04 17:57
@gabriellovate Are you seeing this consistently or intermittently? Do you have an extensions installed that you think might conflict with this setting?

**Comment by gabriellovate** [comment] 2022-04-05 09:47
It is consistent, and I cannot think of any extensions that could conflict with settings. I deactivated all extensions and the problem persists. Although if I click the “quit” option in the brave icon's from the dock instead of closing the window with the  red button in the navigator window, the option does work.

**Comment by rebron** [comment] 2022-04-07 21:06
Hi @gabriellovate This actually works as designed where closing a window is just that, closing the window. So a new window would be fresh and open whatever you set as a new tab option.

Continue where you left off is when you Quit the browser versus Closing the Window. This is the same behavior on chrome. 

We do have a separate issue where we'll add a warning if you have multiple tabs in a window to make sure you do in fact want to close it.

**Closed by rebron** 2022-04-07 21:06 UTC
Labels: OS/macOS, OS/Desktop

**Comment by mh0w** [comment] 2022-08-14 14:39
Hello. I just wanted to comment to say that I managed to resolve this issue in my case by **unchecking 'Continue running background apps when Brave is closed'**. This presumably works by making Brave exit when you click the X, rather than continuing to run in the background, which seems to be consistent with @rebron's comment.
